### ISSUE TITLE
Is it supported optgroup?

### ISSUE THREAD

**Issue by honzapospi** [JedWatson/react-select#1004]
Hi may I ask you if is supported optgroup, jist like here: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_optgroup

Thanks

**Comment by t1mmen** [comment]
This is a duplicate of https://github.com/JedWatson/react-select/issues/59 and https://github.com/JedWatson/react-select/issues/191

Check out the fork at https://github.com/HubSpot/react-select-plus/ with support for optgroups, although I too would love to see this natively supported.

**Comment by piecyk** [comment]
Just use custom `optionRenderer` and transfrom your options, dummy example https://plnkr.co/edit/sRgVrUBFXMhim4gYrFMZ?p=preview

**Comment by darkxeno** [comment]
It would be nice to have support to optgroups within react-select. Is there any possibility to merge the HubSpot fork?

**Comment by JedWatson** [comment]
This has been implemented in `v2`, see my comment on #59
