### ISSUE TITLE
React global namespace

### ISSUE THREAD

**Issue by pjebs** [JedWatson/react-select#1009]
If I were to `npm install react-select --save` and `import Select from 'react-select';`
would the component use the React library in the global namespace or would browserify pull in a second copy of react as a dependency and use that?

I would prefer for the component to use React from global namespace.

**Comment by pjebs** [comment]
I understand there is a standalone version that uses React from global namespace. Is that also registered with npm by any chance?

**Comment by Urthen** [comment]
This version uses your existing installed react as a peer dependency.

**Comment by pjebs** [comment]
i was hoping there'd be a npm version which uses react from global namespace i.e. `var React = global.React;` instead of `var React = require('react');`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
