### ISSUE TITLE
VERY SERIOUS BUG: Drop down not always on top

### ISSUE THREAD

**Issue by pjebs** [JedWatson/react-select#1010]
The drop down list of multi choice select is sometimes underneath components when it should always be on top. See attached screenshots (This was in iOS 8 Safari):

![screen shot 2016-06-05 at 6 33 27 pm](https://cloud.githubusercontent.com/assets/5377970/15804462/4ee2a20e-2b4c-11e6-9a9d-fb77cc722e6c.png)
![screen shot 2016-06-05 at 6 33 31 pm](https://cloud.githubusercontent.com/assets/5377970/15804463/5a4991de-2b4c-11e6-9115-af1f4f8fbbe4.png)

**Comment by Moeface** [comment]
Having this same issue, no amount of z-index, position or display trickery seems to fix it.

**Comment by pjebs** [comment]
For now I'm just listening to when the dropdown comes up and and down and showing/hiding the textboxes. It's the best work-around I've found so far.

**Comment by Moeface** [comment]
For me, this is an issue with [Velocity](https://github.com/julianshapiro/velocity). It inlines a `transform: translateY(0)`, and `transform` prevents `z-index` from applying to it.

**Comment by prateekjahead** [comment]
I think the menu dropdown (the one with class **Select-menu-outer**) should always be appended as a child element in the body and positioned near the select input by some calculations. Otherwise if my select component is inside an element whose z-index is less than another sibling element, the dropdown would never be on top.

**Comment by prateekjahead** [comment]
HubSpot's [react-select-plus](https://github.com/HubSpot/react-select-plus) takes in _dropdownComponent_ as a prop which solves the issue.

**Comment by florentdestremau** [comment]
this does not solve my problem or maybe I missed something in the usage ?

**Comment by duanefields** [comment]
I'm not clear on what react-select-plus expects for `dropdownComponent` - I can provide a div for example, with a fixed height or what not, but the options don't appear. I was expecting it to just be a wrapper element, with the menu inside, but is it expecting me to provide the render options in there as well? (i.e. it is a custom menu dropdown, not a wrapper), it's unclear....

**Comment by dperetti** [comment]
@duanefields It looks like it should be of the form `dropdownComponent={props => <div>{props.children}</div>}` but @prateekjahead I don't see how it solves the issue since — [looking at the source](https://github.com/HubSpot/react-select-plus/blob/afbb399ed0fe2c222a75930e11d8de1585c3242d/src/Select.js#L1235) — this custom component is still rendered as a child of the Select component.

**Comment by prateekjahead** [comment]
@dperetti @duanefields So what I did was that I used the [Portal](https://react-bootstrap.github.io/react-overlays/#portals) component from [react-overlays](https://react-bootstrap.github.io/react-overlays) library so that the `dropdownComponent` is not rendered as a child of `Select` component, something like:
```
const dropdownComponent = ({children}) => (
  <Portal show rootClose={false}>
    {children}
  </Portal>
);
```
And used the prop `menuContainerStyle` to position it near/below the target element after making calculations in `onOpen` callback. Couldn't find any better solution. :|

**Comment by darianferrer** [comment]
I was able to fix this issue by using menuRenderer and setting position fixed, top and width for the menu element, some of this code is from react-select itself and I'm using typescript:

`private menuRenderer(props: ReactSelect.MenuRendererProps<any>): ReactSelect.HandlerRendererResult {
        const Option = (props as any).optionComponent;
        const bodyRect = document.body.getBoundingClientRect();
        const elementRect = (this.refs.reactSelect.wrapper as HTMLDivElement).getBoundingClientRect();
        const options = props.options.map((option, i) => {
            const isSelected = props.valueArray && props.valueArray.indexOf(option) > -1;
            const isFocused = option === props.focusedOption;
            const optionClass = classNames((props as any).optionClassName, {
                'Select-option': true,
                'is-selected': isSelected,
                'is-focused': isFocused,
                'is-disabled': option.disabled,
            });

            return (
                <Option
                    className={optionClass}
                    instancePrefix={(props as any).instancePrefix}
                    isDisabled={option.disabled}
                    isFocused={isFocused}
                    isSelected={isSelected}
                    key={`option-${i}-${option[(props as any).valueKey]}`}
                    onFocus={(props as any).onFocus}
                    onSelect={(props as any).onSelect}
                    option={option}
                    optionIndex={i}
                    ref={ref => { (props as any).onOptionRef(ref, isFocused); }}>
                    {(props as any).optionRenderer(option, i)}
                </Option>
            );
        });

        return <div className="Select-menu-outer" style={{ position: 'fixed', top: elementRect.top - bodyRect.top + elementRect.height + 2 + 'px', width: elementRect.width - 2 + 'px' }}>
            <div role="listbox" className="Select-menu" id="react-select-2--list">
                {options}
            </div>
        </div>;
    }`

**Comment by DocCaliban** [comment]
Why is this issue closed when it still is happening?

**Comment by DmitryGonchar** [comment]
Adding 

```
styles={{
    menuPortal: base => ({
        ...base,
        transform: 'translateZ(0)'
```

has fixed it for our case (elements which had `transform: translateZ` or `translate3d` set were shown above the dropdown). Or you can remove translateZ from those elements

**Comment by MenachemICTBIT** [comment]
After seeing the half dozen related issues, yet not finding a resolution, I have found one.

`<Select
menuPortalTarget={document.body}
            				menuPosition={'fixed'}
						/>`

Add these two options to your Select component. 

It appears to make us of the new React Portal feature.

**Comment by afrancht** [comment]
Your solution @MenachemICTBIT partially fixed it for me. Before only the first two could be seen. This issue has been around for 4 years!

It still doesn't fully fix it

![image](https://user-images.githubusercontent.com/19917183/102127712-1cb59c00-3e4d-11eb-9d03-3ee8e7b1f241.png)

**Comment by OlehBiletskyi** [comment]
> 


it worked for me

**Comment by OlehBiletskyi** [comment]
> After seeing the half dozen related issues, yet not finding a resolution, I have found one.
> 
> `<Select menuPortalTarget={document.body} menuPosition={'fixed'} />`
> 
> Add these two options to your Select component.
> 
> It appears to make us of the new React Portal feature.

it worked for me!

**Comment by Vikram0118** [comment]
I m facing the same bug now, nothing is working. Tried almost all possible ways. `menu` `menuportal` and even css styles.

**Comment by Anhaachan** [comment]
> I m facing the same bug now, nothing is working. Tried almost all possible ways. `menu` `menuportal` and even css styles.

same here.
