### ISSUE TITLE
Conflicts with css-colorguard

### ISSUE THREAD

**Issue by jfeldstein** [JedWatson/react-select#1012]
My Webpack build runs my styles through [css-colorguard](https://github.com/SlexAxton/css-colorguard), which detects "different, but too close to differentiate" colors within css.

Using css-colorguard config, I get the following warnings from react-select:

```
react-select.css
30:2    ⚠  #fff collides with #f9f9f9 (23:20) [css-colorguard]
52:2    ⚠  #fff collides with #f9f9f9 (23:20) [css-colorguard]
64:2    ⚠  rgba(0, 0, 0, 0.075) collides with rgba(0, 0, 0, 0.06) (51:22) [css-colorguard]
64:2    ⚠  rgba(0, 126, 255, 0.1) collides with #007eff (75:16) [css-colorguard]
69:2    ⚠  #aaa collides with #b3b3b3 (37:29) [css-colorguard]
216:2   ⚠  #fff collides with #f9f9f9 (23:20) [css-colorguard]
218:2   ⚠  #e6e6e6 collides with #d9d9d9 (37:16) [css-colorguard]
235:2   ⚠  #fff collides with #f9f9f9 (23:20) [css-colorguard]
236:2   ⚠  #666666 collides with #666 (225:20) [css-colorguard]
246:2   ⚠  #f5faff collides with #f9f9f9 (23:20) [css-colorguard]
248:2   ⚠  rgba(0, 126, 255, 0.04) collides with #007eff (75:16) [css-colorguard]
252:2   ⚠  #ebf5ff collides with #f5faff (285:20) [css-colorguard]
254:2   ⚠  rgba(0, 126, 255, 0.08) collides with #007eff (75:16) [css-colorguard]
258:2   ⚠  #cccccc collides with #ccc (37:24) [css-colorguard]
263:2   ⚠  #999999 collides with #999 (66:40) [css-colorguard]
277:2   ⚠  #ebf5ff collides with #f5faff (285:20) [css-colorguard]
279:2   ⚠  rgba(0, 126, 255, 0.08) collides with #007eff (75:16) [css-colorguard]
281:2   ⚠  rgba(0, 126, 255, 0.24) collides with #007eff (75:16) [css-colorguard]
315:2   ⚠  rgba(0, 126, 255, 0.24) collides with #007eff (75:16) [css-colorguard]
323:2   ⚠  #0071e6 collides with rgba(0, 113, 230, 0.08) (373:20) [css-colorguard]
328:2   ⚠  rgba(0, 126, 255, 0.24) collides with #007eff (75:16) [css-colorguard]
331:2   ⚠  #fcfcfc collides with #f9f9f9 (23:20) [css-colorguard]
331:2   ⚠  #fcfcfc collides with #fff (36:20) [css-colorguard]
332:2   ⚠  #e3e3e3 collides with #d9d9d9 (37:16) [css-colorguard]
332:2   ⚠  #e3e3e3 collides with #e6e6e6 (253:20) [css-colorguard]
337:2   ⚠  #e3e3e3 collides with #d9d9d9 (37:16) [css-colorguard]
337:2   ⚠  #e3e3e3 collides with #e6e6e6 (253:20) [css-colorguard]
342:2   ⚠  #fcfcfc collides with #f9f9f9 (23:20) [css-colorguard]
342:2   ⚠  #fcfcfc collides with #fff (36:20) [css-colorguard]
```

**Comment by Urthen** [comment]
Can you add ignore rules to css-colorguard? Seems like it shouldn't be inspecting any third-party libraries.

**Comment by jfeldstein** [comment]
> shouldn't be inspecting any third-party libraries

That's my sentiment, as well

You can ignore colors, but not files / globs

That's what I'm hoping to get in order to make these warnings go away.




~ Jordan

See what I'm into on AngelList <https://angel.co/jordan-feldstein>

**Comment by Urthen** [comment]
TBH sounds like the issue is with css-colorguard, not react-select. I don't think it makes much sense to make a third-party library change their color scheme to fit your your build process.

**Comment by jfeldstein** [comment]
Very fair. 

Just opened a [corresponding feature request](https://github.com/SlexAxton/css-colorguard/issues/44) in css-colorguard. 

I guess this was a heads up that the color scheme is likely more subtle than most people can detect (at least according to their math). May or may not be worth updating on your end. Thanks for commenting. 

Cheers

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
