### ISSUE TITLE
React Storybook to demonstrate components

### ISSUE THREAD

**Issue by pahans** [JedWatson/react-select#1016]
Hi,
We can use [react-storybook](https://github.com/kadirahq/react-storybook/) to demonstrate some use cases for each component. I can work on this issue if you're interested. I have done some [samples here](https://github.com/pahans/react-select/tree/react-storybook-integration). (Simply run `npm install` and `npm run storybook`)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
