### ISSUE TITLE
Add dependencies to bower.json

### ISSUE THREAD

**Issue by stevenpetryk** [JedWatson/react-select#102]
bower.json doesn't have any dependencies listed, which had me scratching my head about why the plugin wasn't working (I had no idea that classnames and react-input-autosize were required). If these were added to bower.json under the `dependencies` attribute, this may save people a lot of time :)

**Comment by dperetti** [comment]
+1

**Comment by JedWatson** [comment]
Good call, sorry about causing the confusion. I'll make sure all the deps are published to bower (classnames currently isn't) and get this updated.

**Comment by jetpacmonkey** [comment]
+1

**Comment by thizzle** [comment]
+1

**Comment by evandegr** [comment]
+1

**Comment by JedWatson** [comment]
Sorry guys have been v. busy and need to make sure all deps are even _on_ bower

If someone can check that out and submit a PR it would be very welcome.

**Comment by crittelmeyer** [comment]
Thanks Jed!
