### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by chi-zhang** [JedWatson/react-select#1022]
Hi, I'm running meteor with react-mdl and the react-select example of _Custom Placeholder, Option and Value Components_, but when I do the text search on merry, I got this **Uncaught RangeError: Maximum call stack size exceeded** error in the chrome browser console. Doing search of the other values seems ok. Did another test, and seems that if search for the first of last of the option values, no errors, but anything in between will cause this error thrown out in browser.

Event I stopped the meteor server and running purely the client side page, I got the same error.

Any ideas?

Thanks,

**Comment by dpickett** [comment]
Hi @chi-zhang I ran into this due to my text being centered with the `autosize` prop set to true. It took me a bit of digging into issues like #540 to arrive at that conclusion.

**Comment by chi-zhang** [comment]
Hi @dpickett well spot on, exactly the text alignment issue, working fine now.
You're a star :+1: thank you!
