### ISSUE TITLE
Add beforeOptionsRenderer and afterOptionsRenderer options

### ISSUE THREAD

**Issue by siggysamson** [JedWatson/react-select#1023]
Hi guys,
first, thanks for react-select! It looks really promising! We are thinking about using react-select but currently missing some functionality which is holding us back.

What we are looking for are `beforeOptionsRenderer` and `afterOptionsRenderer` options.
Example use cases:
- A menu for filtering the options (tabs/checkboxes)
- Headline/Explanation/Note/Label
- Menu/function to add new options (as an alternative / custom implementation of `allowCreate`)

I think this could be implemented fairly easy by adding them before/after the `.Select-menu` element. ([src/Select.js:897](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L944))

Would you be open to merge a PR that adds these options?

Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
