### ISSUE TITLE
link: this.renderLink() in Custom renderer gives "Error: Converting circular structure to JSON"

### ISSUE THREAD

**Issue by ahmed1490** [JedWatson/react-select#1024]
I copied the CustomeRender.js and put it in my react-storybook

![screenshot](https://cloud.githubusercontent.com/assets/623510/16009390/c668d272-317c-11e6-8c39-13c7a7c292b8.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
