### ISSUE TITLE
Open & Empty Select Doesn't Gets Stuck On Disable

### ISSUE THREAD

**Issue by kadishay** [JedWatson/react-select#1027]
Hi,

When i make external changes which effect the react select - they can clean the list and disable the react select.
In this case the select gets stuck opened and cannot be closed - expected result: disabling should collapse the select.

Here is an example - open the select - after two seconds it will automatically be cleaned and disabled = stuck.

https://plnkr.co/edit/pXthyHRlYZbbl7Es0Nuq?p=preview

Thanks for you great element, 
Yotam.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
