### ISSUE TITLE
optionRenderer does not render label, do we need labelRenderer?

### ISSUE THREAD

**Issue by arnekolja** [JedWatson/react-select#1031]
I was struggling with my select not showing the selected option correctly, as I removed labelKey and added optionRenderer. Then I noticed, that I indeed still need labelKey, because optionRenderer renders only the options in the dropdown, but not the selected option.

Is there a way to also render the selected option like the listed ones? If not, I suggest to add a labelRenderer to accomplish this! :-)

**Comment by JasonKleban** [comment]
Is this not `valueRenderer	func	undefined	function which returns a custom way to render the value selected function (option) {}`?

**Comment by arnekolja** [comment]
Oops, why didn't I see this? Went through all the options and didn't notice it. Sorry.
