### ISSUE TITLE
Support "Select ..." valueless option for clearing single-select

### ISSUE THREAD

**Issue by JasonKleban** [JedWatson/react-select#1034]
I don't think there's a clean way currently to support a "Clear selection" option in the menu as opposed to the 'x' next to the arrow.

Ideally, the valueless first "Select ..." option could be styled differently.  It would not be searchable, but it would always appear at the top of the list.

Already, when this special option is selected, I can replace it with `null` to mimic the behavior, so that's fine.  But I can't style the item differently, other than styling the `::first-child`, and then this option always has to be in the list, which means replacing the filter function.  And we can't just augment the filter function by handling only the special case and then deferring to the default implementation - we have to replace the whole filter function, right?  Similiarly, I could override the optionRenderer, but again I have to override the whole thing, not just for the special case.  It's too heavy.

Have I missed a way?

Thanks!

**Comment by JasonKleban** [comment]
It is not documented, but I found that I can add `style` or `className` to each option object.

So this should be documented as part of the supported interface?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
