### ISSUE TITLE
ID property in select

### ISSUE THREAD

**Issue by darklilium** [JedWatson/react-select#1038]
When im trying to get the event.currentTarget.id from a select in an onBlur (or any) event i cannot get it.
When i see the properties, i noticed the id parameter is not there.

Example:

my select: 
<Select id="ddlTipoContribuyente" className="factigis_selectInput" onBlur={this.onBlur} name="form-field-name" options={this.state.factigis_tipoContribuyente} onChange={this.onChangeTipoContribuyente}
                  value={this.state.factigis_selectedValueTipoContribuyente} simpleValue clearable={true} searchable={false} placeholder="Seleccione el tipo de contribuyente"/>

The onBlur event:

onBlur(e){

switch (e.currentTarget.id) {
      case 'ddlTipoContribuyente':
        console.log("wheres my onblur in this select?");
         break;
default:

}
}

**Comment by renanborgez** [comment]
i think because the ID props is not rendered,  and yeah, i miss it too

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
