### ISSUE TITLE
No results shows when managing isLoading on my own

### ISSUE THREAD

**Issue by abodnar** [JedWatson/react-select#1039]
I'm using the plain Select component and hanging isLoading tracking on my own. Whenever I type something in the field and waiting for the async to come back with suggestions, it shows "No Suggestions found" until the suggestions returns.

When looking through the react-select code, I noticed that in the renderMenu function the logic says if the there are no options, display the no results text. Obviously this is not handling while the async is running.

Example of my usage of the select component below. Let me know if you need more information.

```
                <Select
                    isLoading={this.props.suggestionsLoading}
                    multi={true}
                    onInputChange={getSuggestions.bind(this)}
                    options={this.props.suggestions}
                    onChange={this.updateState.bind(this, prefKey)}
                    noResultsText={"No Suggestions found"}
                    placeholder={"Suggestions..."}
                    searchingText={"Loading... Please wait."}
                    value={(prefs[prefKey].value !== null) ? prefs[prefKey].value : null}
                />
```

**Comment by frankievx** [comment]
I'm fairly certain I have the same exact problem. The results show when I click on the show dropdown button again which runs the render menu function again. 
`				<Select className='Select'
								name="Search"
								value='search'
								valueKey='snippet'
								options={options}
								optionRenderer={this.renderOption}
								onChange={enqueue}
								valueRenderer={this.renderValue}
								onInputChange={(input) => {
									externalSearch(input)
									return input;
								}}
								isLoading={isFetching}

				/>`

**Comment by frankievx** [comment]
So I just solved the issue that I was having. I was already conducting an async search, and when the results/options came back, it was filtering through the options again. Once I set {filterOptions:  false} was when I was getting results back.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
