### ISSUE TITLE
can i use iconfont in valueRenderer callback?

### ISSUE THREAD

**Issue by novys** [JedWatson/react-select#1040]
i want to custom label like this,
     handleSelectValueRender: function (option) {
        return '<i class="iconfont">&#xe636;</i>' + option.label;
    }
but it not working,how i can use icon in label

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
