### ISSUE TITLE
Blank ReactSelect and HTML form submit

### ISSUE THREAD

**Issue by vladra** [JedWatson/react-select#1041]
I have ReactSelect which can be emptied. In this case I need to be able to send empty value ("") to server, so server can nullify model attribute.

But if ReactSelect value is empty/blank, input field is not submitted. React component state is correct though (for example "").

I guess it is bug, because ReactSelect doesn't update input field with blank/empty values.

Any tips?

Thanks in advance

**Comment by tudorpavel** [comment]
@vladra, did you find a solution to this issue?

**Comment by vladra** [comment]
@tudorpavel Nope, I switched to https://github.com/jquense/react-widgets
