### ISSUE TITLE
usage of filterOptions and optionsRender in v0.9.1

### ISSUE THREAD

**Issue by Raffiki** [JedWatson/react-select#1044]
I have following Component:

```
<Select
  name="brand"
  value={expectation && expectation.brand}
  options={brands}
  filterOptions={this.filterOptions}
  onChange={(value, option) => this.updateBrand(item, value, option)}
  optionRenderer={this.renderOption}
/>
```

I want `filterOptions` to return a set of custom `options` when there are no matches:

```
if (filteredOptions.length == 0) {
  filteredOptions = partners.map((partner, idx) => {
    const partnerProps = getPartnerProps(partner)
    return {
      // label: filter,
      label: <span><strong>Create</strong>: {filter}</span>,
      value: `${filter}:${idx}`,
      create: true,
      partner: partner
    }
  })
}
return filteredOptions
```

however, this `label` is never shown. Instead I have this: `Add "[object Object]"?` So **1) the label is not rendered 2) I have the default "Add ...?" text** which I expected to be overriden.

Does anyone has an idea how to render custom filter options?

ps: I thought `renderOption` would come to the rescue, but this handler is never called for the **added** `options` from the `filterOptions` fn. I suppose the latter is by design (?)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
