### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getDOMNode' of undefined

### ISSUE THREAD

**Issue by gsklee** [JedWatson/react-select#105]
To reproduce:

1. Go to http://jedwatson.github.io/react-select/
2. Use the `CLICKABLE LABELS (LABELS AS LINKS)` example
3. Click on the field to reveal `selectMenuContainer`
4. While the menu container is opened, remove any item from the existing selection (eg. remove Vanilla)
5. `Uncaught TypeError: Cannot read property 'getDOMNode' of undefined`

**Comment by JedWatson** [comment]
Fixed, thanks @gsklee!
