### ISSUE TITLE
Decide between SASS and LESS

### ISSUE THREAD

**Issue by ryanzec** [JedWatson/react-select#1050]
I think the code should only have one version of the compilable css but right now there is both a SASS and LESS version.  This can be confusing when submitting a PR as I just had one where I updated the SASS however the LESS version is used to generate the compiled CSS.

I think having just 1 version will prevent confusion like that (and I would vote of SASS since it does seem to be more popular from the fact of pretty big libraries like Bootstrap moving away from LESS to SASS).

**Comment by naartjie** [comment]
@ryanzec having both does mean you can quickly drop `react-select` into a project which has already decided on one. I hit this use case yesterday, where I pulled it into a project which was using LESS, and I customised the styles easily. This would have been a bit more painful if I needed to add support for SCSS especially to be able to customise `react-select` styling.

I would vote to leave it, but truthfully I am not aware of the effort needed to maintain both SCSS and LESS in parallel.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
