### ISSUE TITLE
Add onKeyDown event handler

### ISSUE THREAD

**Issue by trorduja** [JedWatson/react-select#1051]
Thanks for making react-select :)

Could an event handler for onKeyDown be included? I think it could be solved in the same way as the onFocus and onBlur handlers. Would you be interested in a PR for this?

**Comment by guptariya09** [comment]
Can someone share how to use the onKeydown event?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
