### ISSUE TITLE
Scrolling past the bottom of list scrolls the page.

### ISSUE THREAD

**Issue by MCBrandenburg** [JedWatson/react-select#1053]
When at the bottom of the list, continued downward scrolling scrolls the page.

**Comment by mircea-dinoiu** [comment]
This issue is really annoying :(. There's no elegant way I could get around it.
For anyone else who is upset with this, I have a temporary workaround for it, but I'm not sure it works in all the scenarios:

```
const onWheel = (event) => {
        if (propagateWheelEvent === false) {
            const selectMenu = event.currentTarget.querySelector('.Select-menu');
            const height = selectMenu.clientHeight;
            const scrollHeight = selectMenu.scrollHeight;
            const deltaY = -event.deltaY;
            const scrollTop = selectMenu.scrollTop;

            if ((scrollTop === (scrollHeight - height) && deltaY < 0) || (scrollTop === 0 && deltaY > 0)) {
                event.preventDefault();
            }
        }
    };

return (
    <div onWheel={onWheel}>
        <Select {...props}/>
    </div>
);
```

Hope this helps somebody

**Comment by jpriollaud** [comment]
> This issue is really annoying :(. There's no elegant way I could get around it.
> For anyone else who is upset with this, I have a temporary workaround for it, but I'm not sure it works in all the scenarios:
> 
> ```
> const onWheel = (event) => {
>             const selectMenu = event.currentTarget.querySelector('.Select-menu');
> 
>             if (selectMenu != null) {
>                 const height = selectMenu.clientHeight;
>                 const scrollHeight = selectMenu.scrollHeight;
>                 const deltaY = -event.deltaY;
>                 const scrollTop = selectMenu.scrollTop;
> 
>                 if ((scrollTop === (scrollHeight - height) && deltaY < 0) || (scrollTop === 0 && deltaY > 0)) {
>                     event.preventDefault();
>                 }
>             }
>     };
> 
> return (
>     <div onWheel={onWheel}>
>         <Select {...props}/>
>     </div>
> );
> ```
> 
> Hope this helps somebody

So close!  But where would one add { passive: false } to prevent Chrome from breaking it? :
_Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312_

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
