### ISSUE TITLE
Option to choose filter input position

### ISSUE THREAD

**Issue by kirylkastko** [JedWatson/react-select#1056]
Hi everyone,

I would like to add an option for choosing the filter input position: inline or dropdown. I want to have a possibility to place filter input in dropdown like Select2 does.

Please let me know what do you think.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
