### ISSUE TITLE
Select.Async strange behaviour 

### ISSUE THREAD

**Issue by martin-jujou-sirca** [JedWatson/react-select#1058]
If you goto the examples page and select the GitHub contributors select you will notice "Dave brotherstone" come up.

If you then type "D" his name disappears and 2 others come up - dave should come up unless I'm missing something.

I have found the same sort of behaviour while working against my own Api. 

Seems that react select has the options internally but somehow they get filtered out - I have tried to turn caching off and this doesn't make a difference

**Comment by jooj123** [comment]
@jooj123
