### ISSUE TITLE
Query text wrapping to new line does not redraw the location of the dropdown

### ISSUE THREAD

**Issue by wbecker** [JedWatson/react-select#1059]
Steps to reproduce:
1. Go to http://jedwatson.github.io/react-select/, use the second (multiselect) selector and select Chocolate, Caramel and Vanilla.
2. Now write "Cookies and" - notice that the dropdown is directly below the text.
3. Continue writing so that the entire text says "Cookies and Crea" - Notice that the text is now too long to fit in a single line and it has wrapped to a second line. However the location of the dropdown has not updated. This means that the dropdown now covers the query text. If you mouse over the selector, or resize the screen it re-renders itself into the correct position.

**Comment by wbecker** [comment]
This same issue seems to happen in other cases, for example in the same box, if you select all the options and then select "I don't like chocolate" which causes the "Chocolate" box (which is selected) to now say "Chocolate (are you crazy?)". Because it now takes up more space, and drops over to another line and the outer box hasn't resized, it dangles over the normal text.

**Comment by vladtar** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
