### ISSUE TITLE
Dropdown extends beyond the bottom viewport edge

### ISSUE THREAD

**Issue by viveleroi** [JedWatson/react-select#1060]
If a selectbox is too close to the bottom of the viewport, the dropdown menu extends past the page and is no longer visible. Native selectbox behavior places the menu above the control which should happen here as well.

I'm using react-select v0.9.1

In `1.0.0beta13` it auto-scrolls the page so the menu is visible but that's terrible because the whole page jumps to make it fit.

**Comment by shimberger** [comment]
I have the same issue. It would also be nice to have an option to control direction of dropdown.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
