### ISSUE TITLE
Additional Documention for customizing menu options.

### ISSUE THREAD

**Issue by JakeCooper** [JedWatson/react-select#1061]
Currently there lacks documentation on how to produce something like this
![image](https://cloud.githubusercontent.com/assets/5499880/16533323/bf3afbc4-3f8c-11e6-9b56-86e78fd6c858.png)

Even despite it being in the examples page. Additional documentation for customizing menu options would be greatly appreciated.

**Comment by dongmingliy** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
