### ISSUE TITLE
minWidth on <input> tag is invalid

### ISSUE THREAD

**Issue by mattgi** [JedWatson/react-select#1063]
Hi,

There is a breaking change in your ReactInputAutosize library in React 15.2.0 that reports the above error.

For now, I have just downgraded back to 15.1, but this may be something you wish to fix (correcting it in react-input-autosize and bumping the version in this one).

To repro, just upgrade react and view a Select.

**Comment by wirmar** [comment]
Facbook developer explaining this warning: https://fb.me/react-unknown-prop

**Comment by mattparrilla** [comment]
@mattgi can you explain the broken behavior? I'm seeing the warning, but not any problems with the component.

**Comment by arman-mukatov** [comment]
I updated version, but still getting error..

@JedWatson, how to fix? thank you for the prompt reply!

**Comment by dlebedynskyi** [comment]
@JedWatson  can you please push npm version with this fix?

**Comment by gabrielenosso** [comment]
+1 for the npm push! :)

**Comment by katgironpe** [comment]
+1. Please merge this. I get `Unknown prop `minWidth` on <input>` warning, and it isn't a short warning. Quite a lengthy one. Very annoying.

**Comment by PengyuanZhao** [comment]
+1. Please merge this :)

**Comment by johnli611** [comment]
+1. Mission critical =)

**Comment by sweetticket** [comment]
+1

**Comment by jazoom** [comment]
+1

**Comment by JedWatson** [comment]
Just released to npm. Hopefully the last of the beta releases too. Y'all are lucky, I skipped watching a movie on my sunday evening to get this all tested and released 😄

**Comment by katgironpe** [comment]
@JedWatson Thank you!

**Comment by jazoom** [comment]
Dedication!

**Comment by iryan2** [comment]
Thank you, much appreciated!

**Comment by ayozebarrera** [comment]
I installed the 1.0.0-beta14 version but I still see the warning. What is wrong? thanks

**Comment by wirmar** [comment]
Are you sure its actually 1.0.0-beta14. You can check that with `npm ls --depth=0`.
I suspect in your package.json you declare `^1.0.0-beta14`. But since npm thinks 'beta9' is higher than 'beta14' (alphabetical order) it installs the wrong version. So you need to declare `1.0.0-beta14` (no `^`) in package.json.

**Comment by katgironpe** [comment]
I can confirm the issue is fixed @ayozebarrera

**Comment by ayozebarrera** [comment]
great @katgironpe. I think my problem is about @wirmar said... beta9 higher than beta14 on npm.

thanks!

**Comment by sergmetelin** [comment]
Can someone push bower version of the fix? it's still not fixed on bower :(

**Comment by andrewdonskikh** [comment]
Thanks! 1.0.0-beta14 -fixed.

**Comment by JoppeSchwartz** [comment]
This seems to be back in the rc1 release.

**Comment by alexedev** [comment]
+1

**Comment by nitinjadhav466** [comment]
I can confirm - its back in 1.0.0-rc.2

**Comment by Schlesiger** [comment]
Any updates on this? Appears it was a minor fix, but for some reason was then reverted in rc1 and rc2.

**Comment by StefanFeser** [comment]
+1

**Comment by ematipico** [comment]
+1

**Comment by mjhamm75** [comment]
What has happened with this?

**Comment by theodorosidmar** [comment]
+1

**Comment by educastellano** [comment]
Could it be possible to release a 0.9.2 with this fix? 🙃

**Comment by itsmeDrew** [comment]
Issue still persists for me on 0.9.1. Component works as expected, with this annoying error.

**Comment by hegelstad** [comment]
Need this. latest version of react and react-select with bower.
