### ISSUE TITLE
Select.Async lacks setValue / clearValue APIs

### ISSUE THREAD

**Issue by dmk23** [JedWatson/react-select#1065]
I have a need to reset Select.Async component when other components it depends on change.

However, looks like the setValue / clearValue APIs available in regular Select are not available for Async. I tried to use resetState but it only clears the options and not the selection.

These APIs should probably be ported over to Async. Alternatively the selection should be part of the state rather than the props, so it could be changed by regular setState calls ...

**Comment by m1m6** [comment]
+1

**Comment by sizovilya** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
