### ISSUE TITLE
Filtered options are unsearchable

### ISSUE THREAD

**Issue by avnersch** [JedWatson/react-select#1067]
When using the `filterOption` or `filterOptions` functions, the filtered options cannot be searched when typing input afterwards.

See: https://plnkr.co/edit/eVaFIBV5ttbOw17nzn85?p=preview
Steps:
1. The `filterThree` function is executed and returns an options array without `{ value: 'three', label: 'Three' }` option.
2. In the Select component, try to search for one, two or four.

The results are not narrowed down as before.

**Comment by bobony** [comment]
Yeah I am also seeing the same issue.
When ever we search and select an option. In onChange event its showing the value as an object with value and label

**Comment by avnersch** [comment]
Ah ok, this is by design - didn't understand it from the docs.
The `filterOption` function is also responsible to filter out searches - that's why the `filterValue` argument is available.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
