### ISSUE TITLE
Stable branch with React 15 support

### ISSUE THREAD

**Issue by mcoetzee** [JedWatson/react-select#1069]
Hi there,

I believe v1 beta is not yet production ready, so we should add React 15 support for the stable version of react-select (v0.9.1). I see v1 beta is being developed on master so I have created a new branch called `stable` from tag `v0.9.1` where I added support. Could you please also create a branch from tag v0.9.1 (`git checkout -b stable v0.9.1`) so that I can create a PR targeting this new `stable` branch. 

P.S. All tests pass and I have also tested on the dev server. The new warning added to React 15.2 only comes up once, so it's no big deal.

**Comment by janraasch** [comment]
See #875 as well.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
