### ISSUE TITLE
dropdown is covered by keyboard in iPad

### ISSUE THREAD

**Issue by lstkz** [JedWatson/react-select#1070]
If I focus the dropdown in iPad the dropdown is covered by keyboard.

Example.
Directory and Language are custom select
Form:
![image](https://cloud.githubusercontent.com/assets/4478684/16589239/8ea1f370-42d2-11e6-8e1c-d8a8286fbcb8.png)

Click on Language

![image](https://cloud.githubusercontent.com/assets/4478684/16589341/fda6beae-42d2-11e6-954e-08c3628622b5.png)

Can we scroll document automatically, so the select control will be visible?
Something like this 
![image](https://cloud.githubusercontent.com/assets/4478684/16589358/13c47bea-42d3-11e6-93d6-3cb4f3220fab.png)

**Comment by Alorse** [comment]
You could solve?
Apparently the author is no longer supporting.

**Comment by ThomsCass** [comment]
Hi,
Is a workaround available ?
Thanks

**Comment by janblecha** [comment]
have the same issue only on ipad 9,7" iOS 11.2

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by BugHunter727** [comment]
@bladey 
Hi, I still have an issue with an iPad running IOS 11-12.

https://user-images.githubusercontent.com/39057358/150190953-4929457a-c61f-4c42-9e18-d4fb7f31941f.mp4
