### ISSUE TITLE
Ensure onInputChange modifies the input value correctly with Async component

### ISSUE THREAD

**Issue by johnbintz-sonian** [JedWatson/react-select#1072]
With the base `Select` component, when input is entered into the input field, it is potentially passed through a provided `onInputChange` prop that can modify the value and return a new one to place into the field. We are using `onInputChange` to remove leading spaces from the input:

``` js
<Select onInputChange={(input) => input.replace(/^\s+/, '')} />
```

This works correctly with `Select`, but with `Async`, this replacement only happens if both [the `minimumInput` length is met](https://github.com/JedWatson/react-select/blob/master/src/Async.js#L125) and [the cache search executes](https://github.com/JedWatson/react-select/blob/master/src/Async.js#L129). Both the length and cache checks are done with the value that was returned from `onInputChange`, so the UI is now out-of-sync with what the component is using for its checks.

Also, in both of those checks, what's being returned is not what `loadOptions`, which the `Select` component treats as `onInputChange`, should be returning, since the return value of `onInputChange` for `Select` should be the new value of the input field, which can, of course, be returned unchanged.

I have a fork with [a commit](https://github.com/johnbintz-sonian/react-select/commit/a9d3858c83d2bb984d6cd5c67c5deb371c86e213) that fixes the functionality, so that we can left trim the input in an `Async` component, have the checks work correctly, and update the UI regardless of the length or cache checks. Let me know what you think of this.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
