### ISSUE TITLE
Issue with autoresizing width on multiselect option

### ISSUE THREAD

**Issue by rycastaneda** [JedWatson/react-select#1074]
here is a gif of the bug
![lantminer com au - plant equipment hire and rental online - admin panel20160707112235 1](https://cloud.githubusercontent.com/assets/4694510/16641696/c7d33104-4435-11e6-8b64-6c6ce3d9a874.gif)

Here is my element:

``` js
         <Select
                name="supplier"
                value={this.props.item.selected}
                options={this.props.item.suppliers}
                labelKey="data"
                valueKey="user_id"
                multi={true}
                autoBlur={true}
                openOnFocus={true}
                isLoading={this.props.item.loading}
                onFocus={this.props.getSuppliers.bind(null, this.props.item)}
                onChange={this.props.onChangeField.bind(null, this.props.item)}
            />

```

**Comment by mariusandra** [comment]
I solved it thanks to #1059 

What works for me:

```js
class Bla extends Component {
  updateSelect () {
    const { select } = this.refs
    const dom = ReactDOM.findDOMNode(select)
    setTimeout(() => {
      const height = dom.querySelectorAll('.Select-control')[0].clientHeight
      dom.style.height = `${height + 1}px`
    })
  }

}
```

and then 

```
<Select ref='select' ... onInputChange={this.updateSelect} onChange={this.updateSelect} ... />
```

or call this in your more complex callback handler

**Comment by mariusandra** [comment]
Correction, the function needs to be defined as:

```js
  updateSelect = () => {
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
