### ISSUE TITLE
z-index issue when other components use bootstrap input-group and form-control class

### ISSUE THREAD

**Issue by adirima-paix** [JedWatson/react-select#1076]
Hi there,

We recently had an issue with the z-index of the dropdown because other components on the page where using these 2 classes: 

_.input-group.form-control_ 

and this has a z-index of 2 while the _Select-menu-outer_ class has a z-index of 1 which caused the dropdown being shown below the other input fields. 

We managed to go around this by overriding the css class with another class and apply it to a div wrapper. However, maybe it would be better to increase z-index in the Select-menu-outer class in order to avoid other people having the same issue. 

Cheers,
Adriana

**Comment by ewittle** [comment]
+1 

I just made the same change because I have a react-select control in a react-bootstrap panel, and immediately below the react-select control is a react-bootstrap ListGroup. With react-bootstrap, the select ListGroupItem has a z-index of 2, meaning that it sits on top of anything styled with .Select-menu-outer. I would recommend setting the z-index of Select-menu-outer to at least 5 by default...

**Comment by ufukomer** [comment]
+1

**Comment by wmcmeans** [comment]
+1

**Comment by tgosp** [comment]
+1

**Comment by andy-j-d** [comment]
An alternate workaround, avoiding CSS changes, is to use `menuContainerStyle` i.e. 
    `<Select ... menuContainerStyle={{ zIndex: 5 }} />`
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L76
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L1023

**Comment by evgeniiteterin** [comment]
anyone solved this problem? menuContainerStyle={{ zIndex: 5 }} not work.

**Comment by michaelroevievictoria** [comment]
Hi I have a same problem with dropdown styling ? and also the zIndex:5 is not working.

Im using Material-UI for the table row 

<img width="234" alt="screen shot 2017-02-21 at 5 36 45 pm" src="https://cloud.githubusercontent.com/assets/6307916/23159127/8fe4364a-f85c-11e6-9954-1deea2727de7.png">

**Comment by turnerniles** [comment]
See prateekjahead's comment: https://github.com/JedWatson/react-select/issues/1010
"HubSpot's [react-select-plus](https://github.com/HubSpot/react-select-plus) takes in dropdownComponent as a prop which solves the issue."

**Comment by anikakalbrun** [comment]
I have the same issue:
menuContainerStyle={{ zIndex: 5 }} doesn't work,
react-select-plus doesn't work..

**Comment by DeeLindesay** [comment]
```
.Select-menu-outer {
    z-index: 1000;
  }
```
worked for us

**Comment by florentdestremau** [comment]
Hi, small update on my own soluiton (far from perfect but hey...)

```
                      <Select
                        placeholder="-  Sélectionner un club ou coach  -"
                        name="coachName"
                        value={searchOptions.coachs.filter(coach => coach.active)}
                        options={searchOptions.coachs}
                        onChange={coachs => this.setCoachs(coachs)}
                        onOpen={() => this.setState({ coachSelectOpen: true })}
                        onClose={() => this.setState({ coachSelectOpen: false })}
                        ref={select => this.coachSelect = select}
                        multi
                      />
                      {this.state.coachSelectOpen ? <div><br /><br /><br /><br /><br /><br /><br /><br /></div> : null }
```

**Comment by agirton** [comment]
I would recommend to just override the `.Select-menu-outer` styling. We would play an endless battle if someone needs it at 3, then 4.

**Comment by florentdestremau** [comment]
tried everything i could, no CSS styling would fix it. z-indexed all the html dom tree way up, nothing to do.. All the answers I saw did not work

**Comment by phwareboss** [comment]
DeeLindesay's answer worked for me too.
.Select-menu-outer {
    z-index: 1000;
  }

**Comment by brainloc** [comment]
still running into issue this tried everything suggested here, did we get a solid fix for this? Thanks!

**Comment by stanleyume** [comment]
Had this issue with file upload fields. Here's how I fixed it.
`.input-group .form-control, .input-group-btn .btn
{
    z-index: inherit !important;
}`

Would probably work for select fields too.

**Comment by phanimamilla** [comment]
.is-open {
	z-index: 100 !important;
}
This helped me solve the issue

**Comment by gil47** [comment]
@stanleyume's answer worked for me. Input-groups with date picker. Tnx.

**Comment by damianobarbati** [comment]
Not working for me either: anyone else managed to solve this?

**Comment by lucasdu4rte** [comment]
I have the same problem, the custom block and no defined z-index is overlapping the select container menu, I already tried changing the menuContainerStyle prop but it did not work

![captura de tela 2018-05-21 as 14 17 33](https://user-images.githubusercontent.com/22087517/40320350-c9d21a38-5d01-11e8-9b4f-999026e559a1.png)

**Comment by andrewmclagan** [comment]
Surely this can be addressed in the actual component and not with a bunch of work-arounds?

**Comment by rahulgrover** [comment]
I fixed it by giving it class prefix and then setting CSS on it.

<Select
  **classNamePrefix="my-select"**
  value={selectedActivity}
  onChange={this.handleActivityChange}
  options={activityDropdownOptions />

my-select then becomes **my-select__menu**

.my-select__menu {
  z-index: 5 !important;
}

**Comment by jossmac** [comment]
Please see the [styles API](https://www.react-select.com/styles)

**Comment by thomashibbard** [comment]
@jossmac  Where is this specific issue addressed in the docs?

**Comment by jossmac** [comment]
@thomashibbard Seriously? The [styles API](https://www.react-select.com/styles).

```jsx
<Select styles={{
  menu: provided => ({ ...provided, zIndex: 9999 })
}} />
```

Or if you prefer using CSS, checkout the [`className`](https://react-select.com/styles#using-classnames) approach:

```jsx
/* some-file.js */
<Select classNamePrefix="toms-select-component" />
```
```css
/* some-styles.css */
.toms-select-component__menu {
  z-index: 9999;
}
```

**Comment by everaldo** [comment]
@jossmac , I couldn't make it work for me.

**Comment by jossmac** [comment]
I think this has to do with a general misunderstanding of `z-index` and the stacking context.

MDN have a great page explaining [the stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context); please check it out.

```jsx
<div style={{ position: 'relative', zIndex: 1 }}>
  <Select styles={{
    menu: provided => ({ ...provided, zIndex: 9999 })
  }} />
</div>

{/* this div will always be above the Select, no matter how high you set the z-index */}
<div style={{ position: 'relative', zIndex: 2 }}>
  <div>Some other UI element</div>
</div>
```

* * *

Sorry folks, I'm going to lock this thread. We've provided all the necessary tools and documentation, at this point it's just noise.
