### ISSUE TITLE
Multi-select styling issues

### ISSUE THREAD

**Issue by ivanmkc** [JedWatson/react-select#1079]
When I use react-select according to the example: https://github.com/JedWatson/react-select/blob/master/examples/src/components/Multiselect.js

I see that when I select an item, which value appears in a blue box:

```
<div class="Select-value">
<span class="Select-value-icon">×</span>
<span class="Select-value-label">Caramel</span>
</div>
```

However, when I use it in my own project, it is rendered as:

```
<div class="Select-item">
<span class="Select-item-icon">×</span>
<span class="Select-item-label">Vancouver</span>
</div>
```

Any ideas why?
My rendering code is:
`<Select multi simpleValue id="selectCities" onChange={this.saveCity} options={cityOptions} placeholder="Select your cities"/>`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
