### ISSUE TITLE
Pushing enter without dropdown open adds a value

### ISSUE THREAD

**Issue by alex1712** [JedWatson/react-select#108]
When I push enter being in the input field, but without writing any character, the first available option is added.

Thank you very much for your work :)

**Comment by JedWatson** [comment]
@alex1712 this is the behaviour as designed, because by default the first option is focused when you open the control. You can use the keyboard to navigate up and down between different options when it is open.

Thanks :)

**Comment by alex1712** [comment]
Hi again,

thank you very much for your quick answer.

I understand this behaviour when an option is selected but sometimes happens also when the options are not shown. 

Example from your demo page (http://jedwatson.github.io/react-select/) would be:

1- Click on the 'CLICKABLE LABELS (LABELS AS LINKS):' selector
2- Remove one of the labels with the keyboard
3- Then the options are hidden
4- Press enter and one option it is going to be added.

I am using the last version of chrome in MacOs

Thank you again :)

**Comment by JedWatson** [comment]
I see - that's not as expected, thanks for the clarification!

I'll look into it.
