### ISSUE TITLE
Positioning react select to a specific item when opening

### ISSUE THREAD

**Issue by andreareginato** [JedWatson/react-select#1086]
Hi there.

I've been looking for a way to pre-select the position of the list to a specific item when opening it the first time and when an option is not selected.

The use case where I need it is one where there is a list of years (from 1900 to 2016). What I want to do is to set the opening list to 1970, the year that is selected the most as a mean.

I may be missing something, but both reading the docs, looking into the issues and checking the source code, I was not able to come up with a solution.

Below an image showing the initial state I would love to have (not current year)
<img width="754" alt="screen shot 2016-07-13 at 14 52 51" src="https://cloud.githubusercontent.com/assets/37480/16803907/5369822c-4909-11e6-8f0e-f50969016c17.png">

Thanks for your help and your time.

**Comment by willdavidow** [comment]
Been poking around on this issue for the last 30 minutes, and arrived at the conclusion that there are some bugs in the default `renderMenu` function. I believe I'm using the latest - version `1.0.0-beta12`:

Checking out this block of code, lines 715-767 in `src/Select.js`:

```
renderMenu (options, valueArray, focusedOption) {
		if (options && options.length) {
			if (this.props.menuRenderer) {
				return this.props.menuRenderer({
					focusedOption,
					focusOption: this.focusOption,
					labelKey: this.props.labelKey,
					options,
					selectValue: this.selectValue,
					valueArray,
				});
			} else {
				let Option = this.props.optionComponent;
				let renderLabel = this.props.optionRenderer || this.getOptionLabel;

				return options.map((option, i) => {
					let isSelected = valueArray && valueArray.indexOf(option) > -1;
					let isFocused = option === focusedOption;
					let optionRef = isFocused ? 'focused' : null;
					let optionClass = classNames(this.props.optionClassName, {
						'Select-option': true,
						'is-selected': isSelected,
						'is-focused': isFocused,
						'is-disabled': option.disabled,
					});

					return (
						<Option
							className={optionClass}
							isDisabled={option.disabled}
							isFocused={isFocused}
							key={`option-${i}-${option[this.props.valueKey]}`}
							onSelect={this.selectValue}
							onFocus={this.focusOption}
							option={option}
							isSelected={isSelected}
							ref={optionRef}
							>
							{renderLabel(option)}
						</Option>
					);
				});
			}
		} else if (this.props.noResultsText) {
			return (
				<div className="Select-noresults">
					{this.props.noResultsText}
				</div>
			);
		} else {
			return null;
		}
	},
```

It looks like the intended functionality is what you're asking for here, but it's broken... 

Focusing my attention on this block:

```
return options.map((option, i) => {
					let isSelected = valueArray && valueArray.indexOf(option) > -1;
					let isFocused = option === focusedOption;
					let optionRef = isFocused ? 'focused' : null;
					let optionClass = classNames(this.props.optionClassName, {
						'Select-option': true,
						'is-selected': isSelected,
						'is-focused': isFocused,
						'is-disabled': option.disabled,
					});

					return (
						<Option
							className={optionClass}
							isDisabled={option.disabled}
							isFocused={isFocused}
							key={`option-${i}-${option[this.props.valueKey]}`}
							onSelect={this.selectValue}
							onFocus={this.focusOption}
							option={option}
							isSelected={isSelected}
							ref={optionRef}
							>
							{renderLabel(option)}
						</Option>
					);
				});
```

First thing I did was drop some logging in the compiled version of the library at `lib/Select.js` to see changes live in my application; line numbers are a little different vs. what's located in the `src/Select.js` file, but most of the stuff is named the same, or similar enough to find it. 

`valueArray` is coming through empty - I haven't traced why, but `console.log(valueArray)` outputs `[]`. In addition to that, `focusedOption` is not pointing to what I would expect based on my data - I have a list of options `{ label: -10, val: -10 }` through `{label: 100, val: 100}` - pretty straightforward; it's always pointing to the first option here, `{label: -10, val: -10}` and what is selected (which I'd expect should also be focused by default) is something different...

What that means is that both `isSelected` and `isFocused` will be false 100% of the time :(

The change I made to get this working was to update the variable declaration for `isFocused` to match values of the current option vs. the current selected value for the Select.  **Definitely a duct tape/bandaid fix, but it does work as-expected now:**

`var isFocused = option.val === _this4.props.value;`

in this block of code, inside `lib/Select.js` - lines 761 - 821; my update is on line 782.

```
	renderMenu: function renderMenu(options, valueArray, focusedOption) {
		var _this4 = this;

		if (options && options.length) {
			if (this.props.menuRenderer) {
				return this.props.menuRenderer({
					focusedOption: focusedOption,
					focusOption: this.focusOption,
					labelKey: this.props.labelKey,
					options: options,
					selectValue: this.selectValue,
					valueArray: valueArray
				});
			} else {
				var _ret = (function () {
					var Option = _this4.props.optionComponent;
					var renderLabel = _this4.props.optionRenderer || _this4.getOptionLabel;

					return {
						v: options.map(function (option, i) {
							var isSelected = valueArray && valueArray.indexOf(option.val) > -1;
							var isFocused = option.val === _this4.props.value;
							var optionRef = isFocused ? 'focused' : null;
							var optionClass = (0, _classnames2['default'])(_this4.props.optionClassName, {
								'Select-option': true,
								'is-selected': isSelected,
								'is-focused': isFocused,
								'is-disabled': option.disabled
							});
							console.log("selected value", _this4.props.value, "focused? ", isFocused, "option ", option, "focusedOption", focusedOption);
							return _react2['default'].createElement(
								Option,
								{
									className: optionClass,
									isDisabled: option.disabled,
									isFocused: isFocused,
									key: 'option-' + i + '-' + option[_this4.props.valueKey],
									onSelect: _this4.selectValue,
									onFocus: _this4.focusOption,
									option: option,
									isSelected: isSelected,
									ref: optionRef
								},
								renderLabel(option)
							);
						})
					};
				})();

				if (typeof _ret === 'object') return _ret.v;
			}
		} else if (this.props.noResultsText) {
			return _react2['default'].createElement(
				'div',
				{ className: 'Select-noresults' },
				this.props.noResultsText
			);
		} else {
			return null;
		}
	},
```

I don't have time to completely fix this/create a PR today, but if I find time later this week I'll try to address the problem and see if @JedWatson will consider the PR.

**Comment by eucaos** [comment]
Hello I'm having exactly the same problem. 
I can't re-focus the last focused option in the context of dynamically updating the Options List. The first item is focused by default.

@JedWatson 
Any chance this fix gets merged into master or is there any other workaround ?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version (v3 and beyond).

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
