### ISSUE TITLE
Hover over disabled option should clear highlight

### ISSUE THREAD

**Issue by jscheid** [JedWatson/react-select#1087]
With one or more enabled options as well as one or more disabled options, when I hover over an enabled option and then over a disabled option, the highlight (background bar) is "stuck" on the enabled option, i.e. the previously hovered over enabled option is still highlighted. I would expect that either the highlight disappears altogether or, alternatively, that it is shown on the disabled option (perhaps with a different color indicating that the option is disabled). The current behaviour feels somewhat broken.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
