### ISSUE TITLE
allowCreate and newOptionCreator is not selecting the new value 

### ISSUE THREAD

**Issue by rgoldman-qb** [JedWatson/react-select#1088]
`addNewOption = (value) => {
    return { value, label: value };
  }`     

`<Select
  allowCreate
  options={[{ label: 'foo', value: 'foo' }, { label: 'bar', value: 'bar' }]}
  newOptionCreator={this.addNewOption}
/>`

when a user enters his own option it doesn't automatically select it, so if the user hits tab it wont save what they wrote and in addition  all the options get lost from the dropdown
any ideas?

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

Look for an updated RC with this functionality soon. 😎
