### ISSUE TITLE
Programmatic open/close

### ISSUE THREAD

**Issue by devlato** [JedWatson/react-select#1089]
Hey folks, 

is there any way to open the dropdown programmatically? 
i.e. pass something like 

``` jsx
<Select isOpen={true} />
```

**Comment by kbzak** [comment]
https://github.com/JedWatson/react-select/issues/305
https://github.com/JedWatson/react-select/pull/817

**Comment by iyn** [comment]
https://github.com/JedWatson/react-select/issues/305
https://github.com/JedWatson/react-select/pull/817

**Comment by adisak1618** [comment]
isOpen is not work for me

**Comment by agirton** [comment]
Hi @adisak1618, @devlato we don't have this prop available. Please give us feedback in this thread: #1989
