### ISSUE TITLE
theme support

### ISSUE THREAD

**Issue by piecyk** [JedWatson/react-select#109]
For better override styles (when you need to have 3 components whit different look) created something like props.theme, ref to gist

https://gist.github.com/piecyk/14cfd932aabd1989ff10

and usage

``` js
var theme = {
  SelectControl: 'my-Select-control',
  SelectPlaceholder: 'my-Select-placeholder'
};

var selectProps = {
  asyncOptions: loadOptions,
  onChange: this.onChange,
  theme: theme,
  name: "react-select-test"
};
return (<Select {...selectProps} />);
```

i want to created a pull request with this, but maybe is there a better solution... any thoughts?

**Comment by dcousens** [comment]
@jossmac you might have a better handle on this could be done.

**Comment by piecyk** [comment]
:+1:

**Comment by cedricdelpoux** [comment]
I'm interested by the theme support. Is a PR in progress about this ?

**Comment by jossmac** [comment]
@JedWatson might be time to convert to Radium, thoughts?

**Comment by piecyk** [comment]
@jossmac any news about this ?

**Comment by jossmac** [comment]
@piecyk depending on some research we need to do for a commercial project, it's looking like the components will be re-implemented using [styled-components](https://github.com/styled-components/styled-components)

**Comment by PeteJodo** [comment]
@jossmac if you re-implement using styled-components, will the reimplementation include a `theme` prop that would be able include some custom classes?

**Comment by jossmac** [comment]
@PeteJodo I'd like to provide more granular control of the component styles. Though the best pattern I've discovered so far uses [Glamor](https://github.com/threepointone/glamor) by itself.

**Theme**
Basically just a massive list of variables that you can override, things like `inputPaddingHorizontal` etc.

**CSS**
For when we haven't declared a theme variable for a property you'd like to change, an example might be that we have a background-color indicating disabled state but the consumer would like to dim the opacity.

**Renderers**
Let's say your design requires a different clear icon, or you find that tweaking `theme` and `css` aren't quite enough, you can provide your own component to replace ours completely.

I'll keep exploring different options.

**Comment by PeteJodo** [comment]
cool. I haven't heard of Glamor before. I actually completely forgot about the optional renderers. I should be able to just create my own with my own styles to get my desired result then

**Comment by jossmac** [comment]
FYI Glamor is what styled-components uses under-the-hood

**Comment by JedWatson** [comment]
v2 has a complete styling API now 👍
