### ISSUE TITLE
Keeping inputValue

### ISSUE THREAD

**Issue by khankuan** [JedWatson/react-select#1092]
Hi, is there a way to be able to set the inputValue based on a prop?

**Comment by michalvankodev** [comment]
Hi, I'm planning to write a PR for this as this is a feature that was requested in our project. I just wanna ask if maintainers are willing to have such a feature. It was requested multiple times when I search in the issues tab but every request is left ignored.

**Comment by lachiet** [comment]
Any updates on this? I'm also trying to make inputValue persist after the user select an option.
