### ISSUE TITLE
How to contain large numbers of selected values

### ISSUE THREAD

**Issue by brimby** [JedWatson/react-select#1096]
I have a react-select dropdown where I programmatically pre-select every option on load, so that the user has to "x" off any that they _don't_ want. Problem is, the list is huge and makes the widget huge in turn. Is there a property for keeping the value box limited in size with perhaps a scrollbar?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
