### ISSUE TITLE
filterOptions: false by default for Select.Async

### ISSUE THREAD

**Issue by elmeister** [JedWatson/react-select#1097]
Shouldn't we better set `filterOptions` for Select.Async by default to false, assuming `loadOptions` will do all required filtering? 
In my case label option isn't set, since custom `valueRenderer` / `optionRenderer` is used, this leads to unwanted additional filtering of results.

**Comment by k23Burke** [comment]
+1

This bug cost me hours in purgatory before finding this issue. Especially with custom optionRenderer why filter??

**Comment by elmeister** [comment]
Seems that issue is little bit more tricky — without `filterOptions` at all, for same query string, we will have already picked values in options list — because of cached search results.
So it might be useful to check if `key` property is set and use it, not default `label` value to filter options.

**Comment by hughlomas** [comment]
Thanks, this helped me fix an issue where I would receive results but the select would show the "no results" message.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
