### ISSUE TITLE
Implement onCloseResetsInput

### ISSUE THREAD

**Issue by frankievx** [JedWatson/react-select#1098]
This feature I felt would be useful considering that there is an onBlurResetsInput option. In my personal use case I do not want the input to be reset when I close the menu using the arrow. 

I have written code to add the option including additions to the readme and tests to cover the small new feature.

**Comment by frankievx** [comment]
# #1101

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
