### ISSUE TITLE
'select all' option for multiselect dropdowns?

### ISSUE THREAD

**Issue by okyere** [JedWatson/react-select#1099]
1. Great piece of software. Keep it up.
2. Is there a 'select all' option for multiselect dropdowns? I plan to use this library but the list to select from could be hundreds. A select all option will enhance usability. I couldn't find it in the docs or demo. Just wondering if it is in there somewhere. Thanks.

**Comment by MUHAMMAD-ATEEK** [comment]
you can implement it own. by setting selectedOptionsArray = OptionsArray

**Comment by okyere** [comment]
@MUHAMMAD-ATEEK I'm not sure how I'd do that. I'm new to Javascript and React. Can you guide how I can add a 'Select All' option to drop downs and multi select options? Thanks.

**Comment by Carlows** [comment]
I'm interested into this too, but I'd like the first option to be the 'select all' option, is there a way to do that?

**Comment by areinmeyer** [comment]
What I just implemented was adding a button below the <Select> for "Select All".  The button onClick event then maps over the array of value/display objects and creates a comma-separated string of the values that the handleSelectChange event expects and then the button.onClick calls that handleSelectChange.  

So my JSX looks something like this:

```JSX
<div>
<Select
        name={this.props.name}
        value={this.state.value}
        options={this.state.prompt.options}
        simpleValue={true}
        multi={true}
        onChange={this.handleSelectChange}
      />
      <Button onClick={this.handleClick} type="button" >Select All</Button>
</div>
```

The Button.handleClick takes the options array (my value/display objects) and creates the string that onChange takes.  My example isn't complete, but hopefully gives you a starting point.

**Comment by Ghanshyam-K-Dobariya** [comment]
@MUHAMMAD-ATEEK code sample any where ?
Bcz I get nothing here...

https://github.com/JedWatson/react-select/search?utf8=%E2%9C%93&q=selectedOptionsArray

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
