### ISSUE TITLE
Question: How do I change amount of results displayed

### ISSUE THREAD

**Issue by thevangelist** [JedWatson/react-select#1100]
How do I change the default number of results displayed? It seems it's 5 currently.

Thanks.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
