### ISSUE TITLE
Enhancement: (In case of multiselct) ability to not filter selected values from menu and toggle value selection by clicking on selected option

### ISSUE THREAD

**Issue by hingermayank** [JedWatson/react-select#1102]
While using react-select (for multi select), we came across a use case where we wanted the ability to retain the selected options in menu and to be able to toggle the selection of value from the menu itself and this can be controlled via a prop. 

Please see to it, if it is a valid use case. If valid, I can create a PR for this.

Thanks

<img width="332" alt="screen shot 2016-07-18 at 3 58 50 pm" src="https://cloud.githubusercontent.com/assets/6342096/16912302/e61b0050-4d00-11e6-9806-79ce51b77f75.png">

**Comment by DERIIIFranz** [comment]
That's definitly a highly demanded feature! You might want to have a look at #803 and the corresponding PR

**Comment by hingermayank** [comment]
The PR for #803 is not merged because of conflicts.

**Comment by arnireynir** [comment]
Can you merge this please, I need this.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
