### ISSUE TITLE
shasum check failed - Unable to pull latest version 1.0.0-beta14.tgz

### ISSUE THREAD

**Issue by vinayakpatil** [JedWatson/react-select#1103]
npm WARN package.json 360Components@0.0.2 No license field.
npm http request GET http://registry.npmjs.org/react-select
npm http 200 http://registry.npmjs.org/react-select
npm http fetch GET https://registry.npmjs.com/react-select/-/react-select-1.0.0-beta14.tgz
npm http fetch 200 https://registry.npmjs.com/react-select/-/react-select-1.0.0-beta14.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for C:\Users\VINAYA~1\AppData\Local\Temp\npm-9276-694318a8\registry.npmjs.com\react-select\-\react-select-1.0.0-beta14.tgz
npm ERR! Expected: f17ee09df93b9a0ecc4023c57fb941ec0107909b
npm ERR! Actual:   4ae7573c3b5004cd49f397bd703f64344a6c86de
npm ERR! From:     https://registry.npmjs.com/react-select/-/react-select-1.0.0-beta14.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\360Components\npm-debug.log

**Comment by willcosgrove** [comment]
When I download the file listed at the link in your error (https://registry.npmjs.com/react-select/-/react-select-1.0.0-beta14.tgz) and I run `shasum`, I'm getting the expected checksum.  It could be an issue with your connection, or it could be an issue with an edge server of npm's CDN.

But I don't think it's an issue with this project.

**Comment by vinayakpatil** [comment]
@willcosgrove Resolved this by updating my npm registry to https. Thanks!
