### ISSUE TITLE
[answer before v1.0] Why is multi onChange called with the option description instead of the option value?

### ISSUE THREAD

**Issue by wmertens** [JedWatson/react-select#1109]
See https://github.com/JedWatson/react-select/blob/master/test/Select-test.js#L1408, this seems to be by design, but I hope that this can be changed.

IMHO it doesn't make sense that you set `value` to a single value or an array of values, but then `onChange` gets called with an implementation detail, the description of the option, instead of the new `value`. `value` and `onChange` are a de-facto API for input elements, and they normally work with values from the same domain.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
