### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by ondrejhlavacek** [JedWatson/react-select#111]
When passing the disabled attribute with `true` value, the component with a value looks weird. 

![screen shot 2015-03-27 at 17 05 33](https://cloud.githubusercontent.com/assets/497675/6878893/9f361fc0-d4a3-11e4-86a0-71267f31294d.png)

**Comment by ribeiroct** [comment]
I don't think react-select disabled state is meant for use as a readonly component.

I ran into the same trouble, which i solved through the following css hack on my stylesheet (may be useful for other users until it's fixed on the code).

        .Select.is-disabled .Select-item-icon,
        .Select.is-disabled .Select-placeholder,
        .Select.is-disabled .Select-input,
        .Select.is-disabled .Select-arrow{
            display: none;
        }

**Comment by JedWatson** [comment]
@jossmac can you take a look at this? looks like something's gone out of sync since we added the disabled support.

**Comment by dcousens** [comment]
@ondrejhlavacek can you confirm this still exists?

**Comment by ondrejhlavacek** [comment]
@dcousens yes, still happening
![development_-_transformation_t2](https://cloud.githubusercontent.com/assets/497675/7874848/4650804c-056a-11e5-9cc1-87a10e82074b.png)

**Comment by dcousens** [comment]
ping @jossmac

**Comment by JedWatson** [comment]
Should be closed by #258
