### ISSUE TITLE
Select with searchable={false} is not activated by space

### ISSUE THREAD

**Issue by lerayne** [JedWatson/react-select#1111]
Accessibility issue: if my select is not searchable, it still can be focused, but the space button doesn't open it.

https://plnkr.co/edit/SU5BSGQ7VwXgDSHyd2aP?p=preview

**Comment by thecristen** [comment]
Also ran into this. I'm eagerly watching this pull request #1428

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
