### ISSUE TITLE
Easier way to style or provide complete example

### ISSUE THREAD

**Issue by L3V147H4N** [JedWatson/react-select#1112]
I think that styling is a huge part of Frontend Development and most of the times is a great way to distinguish your app from others; it would be awesome if the component provided some very easy way to style the Input, overriding the current classes is very tedious given that there are a lot of components involved:

![image](https://cloud.githubusercontent.com/assets/5846479/17030649/cac044f8-4f46-11e6-85e0-c896fbb2920b.png)

it would be great (for ex.) to pass styling objects inline via props: inputStyle, clearButtonStyle, etc

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
