### ISSUE TITLE
Cannot programmatically open menu / trigger mousedown (For testing)

### ISSUE THREAD

**Issue by jfeldstein** [JedWatson/react-select#1114]
https://plnkr.co/edit/uN6sdCanjlDsvxpg7a8i?p=preview

Looks like I'm not the only one having issues with selenium testing a page using react-select. 

My selenium cannot click on the elements (they're ignored), and I can't get javascript to fake it, either. 

What's going on? How can I programmatically open this menu to continue my test?

**Comment by liquid1982** [comment]
I have the same problem – I'm able to interact with the component via Selenium / SitePrism, but I am not able to do the same while using Poltergeist. I tried literally everything.

Here's my setup:
https://github.com/liquid1982/react-select-example

**Comment by liquid1982** [comment]
I found a way to make react-select work using Poltergeist – hope it helps

https://github.com/liquid1982/react-select-example

**Comment by YaakovMedinaAtTradAir** [comment]
Found this solution in Java for the WebElement instance "dropdownElement":

> Actions action = new Actions(driver);
> action.click(dropdownElement).build().perform();

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
