### ISSUE TITLE
Extract the dropdown out of input

### ISSUE THREAD

**Issue by villesau** [JedWatson/react-select#1116]
Hi!

Just a feature idea: Would it make sense to extract the dropdown element out of the component to allow it to be used individually without input element. It's not a first time i would like to use just the features of the dropdown and attach it into somewhere else. It might be a text area, input or something totally different. The dropdown would listen to key(down) events passed to it and this way it could be able to highlight active element, maybe return selected one, etc. Most of dropdowns have a lot of common logic, like scrolling back to top when list ends, return selected value when hitting enter/arrow/tab/some other key etc etc. For example i would like to implement it to follow caret position of the text input. This is probably something what most of dropdown/select libraries does not want to implement by them selves. and this is also the reason why i would like to use only the dropdown part, not the always visible select-component.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
