### ISSUE TITLE
handleInputChange doesn't fire after selecting an option

### ISSUE THREAD

**Issue by mwilliamson-healx** [JedWatson/react-select#1117]
We're using `handleInputChange` to detect changes in the entered value so that we can update `options` accordingly. However, when `multi={true}`, after an option is selected, `state.inputValue` is updated (to the empty string) without triggering `handleInputChange`. Should `handleInputChange` be triggered in that case? If not, is there a better way for us to listen for changes to the input value?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
