### ISSUE TITLE
Dependencies order 

### ISSUE THREAD

**Issue by didierfranc** [JedWatson/react-select#1122]
I get a problem with react-select as a dependency.

Running `npm install react-select -S` add this line to package.json 

```
"react-select": "^1.0.0-beta14"
```

but when I'm running npm install it install `react-select@1.0.0-beta9`

The problem is the version ordering of npm 

`npm view react-select`

```
versions:  [
     '1.0.0-beta1',
     '1.0.0-beta10',
     '1.0.0-beta11',
     '1.0.0-beta12',
     '1.0.0-beta13',
     '1.0.0-beta14',
     '1.0.0-beta2',
     '1.0.0-beta3',
     '1.0.0-beta4',
     '1.0.0-beta5',
     '1.0.0-beta6',
     '1.0.0-beta7',
     '1.0.0-beta8',
     '1.0.0-beta9' 
]
```
For the time being I setted the line to

```
"react-select": "1.0.0-beta14"
```

**Comment by bvaughn** [comment]
This issue has been resolved with the recent RC version. It should not be a problem going forward with future releases.

(Unfortunately it's not possible to fix the bad version numbers of previous releases.)

Cheers!
