### ISSUE TITLE
Doesn't work on mobile?

### ISSUE THREAD

**Issue by snakeyak** [JedWatson/react-select#1123]
Hi,

I'm using v1.0.0-beta14, it doesn't seem to be working on iOS at all. The select box is there, but taping any options does nothing.

Is it just me doing something wrong or is this a known issue? Works fine on desktop..

Thanks

**Comment by nuclearspike** [comment]
Same here. 

Check out: #1036

I removed FastClick and everything worked for me. It would be nice if react-select could work with fastclick.

**Comment by JedWatson** [comment]
I'm pretty confident this has been addressed in the latest version, if anyone can still reproduce it please let me know with steps explaining how. Thanks!
