### ISSUE TITLE
<div> can't be nested in <span> according to HTML spec

### ISSUE THREAD

**Issue by MilovanovM** [JedWatson/react-select#1128]
The component renders:
<img width="354" alt="div-span" src="https://cloud.githubusercontent.com/assets/1742065/17276507/5ebdabce-5734-11e6-8d9b-7750bb5f80c8.png">

**Comment by alainds** [comment]
I use your component and I do the same comment : the rendered HTML code is invalid. You can't put a <div> into a <span>. 
If <div> was replaced <span>for the 2 elements "Select-input"  and "Select-placeholder", it would resolve the problem.  (In the code of the plugin, it's just a parameter).
Thanks.

**Comment by JedWatson** [comment]
Closing as this has been resolved in v2, ref #2289
