### ISSUE TITLE
Possibly wrong propType?

### ISSUE THREAD

**Issue by iviireczech** [JedWatson/react-select#1132]
Hello, I have a question. Why is [tabIndex](https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L125) prop considered as a string? IMHO number would be more accurate. Currently I must do conversion like this `tabIndex={String(this.props.tabIndex)}`, otherwise I get "Warning: Failed prop type: Invalid prop `tabIndex` of type `number` supplied to `Select`, expected `string`."

**Comment by bvaughn** [comment]
Hey good point. Both types should be supported if nothing else.

**Comment by adamduren** [comment]
I've experienced this as well. Native field such as `input` expect only number. Possibly should be that for consistency.

**Comment by noah-conning** [comment]
Is this project dead?

**Comment by agirton** [comment]
@noah-conning no
