### ISSUE TITLE
Beta version releases are incorrectly formatted

### ISSUE THREAD

**Issue by billyjanitsch** [JedWatson/react-select#1133]
Hi, I just wanted to point out a slight mistake in how beta releases of this package are being published. They [should be](https://docs.npmjs.com/misc/semver#prerelease-tags) formatted as `1.0.0-beta.5` rather than `1.0.0-beta5`. The latter is invalid semver and causes problems with version tooling ([example](https://github.com/tjunnone/npm-check-updates/issues/260)) and with npm itself, e.g. #1122

**Comment by bvaughn** [comment]
It's too late to change this for the *beta releases but this has been fixed for the new rc releases, the latest of which is "1.0.0-rc.1". 😄

Cheers for pointing this out though @billyjanitsch!
