### ISSUE TITLE
Back space with multi asyncOptions doesn't remove selected

### ISSUE THREAD

**Issue by markbrown4** [JedWatson/react-select#1134]
In the Github users (Async with fetch.js) example on the [demo page](http://jedwatson.github.io/react-select/) if you select an option and then hit `delete` on a mac it should remove the item.

All of the other example usages work well with the backspace key.

**Comment by bvaughn** [comment]
The example you linked to has been [configured to _disallow_ backspace removal](https://github.com/JedWatson/react-select/blob/916ab0e62fc7394be8e24f22251c399a68de8b1c/examples/src/components/GithubUsers.js#L56) via the `backspaceRemoves={false}` property. (In other words the example is working as designed. Not a bug.)
