### ISSUE TITLE
Deactivate menu dropdown on mobile?

### ISSUE THREAD

**Issue by webdif** [JedWatson/react-select#1135]
Is there a way to deactivate the dropdown menu on mobile device, to use the built-in select of the OS for a better UX?

For now, I go for a pretty radical solution: render react-select only when `window.innerWidth > 720`…

**Comment by kenneho** [comment]
I'd like to deactive meny dropdown on desktop web browser as well.

**Comment by arkjoseph** [comment]
Yes, any one try to disable the field on mobile? im not sure if its annoying or a viable mobile solution so it would be nice to disable on touch devices.

**Comment by agirton** [comment]
If you would like to disable or hide this component for mobile users you will need to handle this on your side. Putting this in our package means we would need to be aware of the window width. Which would bloat our code base.
