### ISSUE TITLE
Setting initial/default label for Select.Async

### ISSUE THREAD

**Issue by yonaichin** [JedWatson/react-select#1138]
As title states, setting initial value for Select.Async is possible but failed to show the label due to the empty callback options from loadOptions.

Is there any workaround ?
I tried #861 but not quite fit the scenario.
Thanks in advance.

**Comment by tingwei628** [comment]
Here is my workaround...
I marked on Select  and depend on the state "isFirstTime"
```js
  constructor() {
    this.state = {
      isFirstTime: true,
    }
  }
render() {
return(<div>
<Select.Async
  loadOptions={(input, callback) => {
    if (this.state.isFirstime) {
      callback(null, options: [ { ... } ]); // your default options
      this.setState({
         isFirstTime: false,
      });
      rerurn;
    }
    callback(null, options: [ {  ...  } ]); // other options...
 }}/></div>);
 }
```

**Comment by yonaichin** [comment]
Thanks for the reply. 
I actually have this problem fixed with my workaround and send a PR.
For your refrences, https://github.com/JedWatson/react-select/pull/1180

**Comment by dstuecken** [comment]
I actually created another PR that will fix this issue as well: The ability to pass an options array to Select.Async.

**Comment by bvaughn** [comment]
FYI I am working on a refactor for `Async` that should address this issue. (See PR #1226)

**Comment by bvaughn** [comment]
Resolved via PR #1226.

Look for an RC2 to come out (hopefully) sometime today with this change.

**Comment by zhaoyi0113** [comment]
How does the initial value work? Is there an example for that? I tried `defaultOptions`, `defaultValues` but none of them work.

**Comment by zhaoyi0113** [comment]
I see why it doesn't work for me. The `defaultValues` in my component is also an async request. How can I make it work with async data?

**Comment by ngohieutp** [comment]
> I see why it doesn't work for me. The `defaultValues` in my component is also an async request. How can I make it work with async data?

As 2020, is there any solution?
