### ISSUE TITLE
Can't set an id on the multi input

### ISSUE THREAD

**Issue by markbrown4** [JedWatson/react-select#1139]
I couldn't see a way to set an id on the input for a multi select.
This is useful for cases where you want to create a label outside of the component and have clicks on the label cause the input to gain focus.

```js
const options = [{
  label: 'A',
  value: 'a'
},{
  label: 'B',
  value: 'b'
},{
  label: 'C',
  value: 'c'
}];

const el = (props)=> (
  <div>
    <label for="region">Region</label>
    <Select
      name="region"
      value={['a','b']}
      options={options}
      multi={true}
      joinValues={true}
    />
  </div>
)
```

**Comment by banderson** [comment]
I just noticed there's an `inputProps` prop which allows you to set the `id` on the input itself. Can you try that out?

**Comment by markbrown4** [comment]
It does indeed. Cheers!
