### ISSUE TITLE
Selection Doesn't Update UI

### ISSUE THREAD

**Issue by victoryforphil** [JedWatson/react-select#1148]
When I select an option the box doesn't show the updated selection. It even happens with the example.

https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

Result:
http://i.imgur.com/gC5tjkG.gifv

**Comment by odk211** [comment]
Hi,
react-select behaves like [Controlled Components](https://facebook.github.io/react/docs/forms.html#controlled-components) .
So, you should use `setState` manually at onChange handler.

e.g.
https://github.com/JedWatson/react-select/blob/master/examples/src/components/NumericSelect.js#L41

**Comment by victoryforphil** [comment]
Working Thanks!
