### ISSUE TITLE
Select.Async do not handle IME after update to v1.0.0-beta14

### ISSUE THREAD

**Issue by odk211** [JedWatson/react-select#1149]
First, thank you for the awesome component :)
It's really helpful!

After update to v1.0.0-beta14 from v1.0.0-beta13,
`Select.Async` do not handle IME well. (`Select` works well)
After every loadOptions call, the input is fixed and IME do not work.

I prepare a plnkr to show it, 
https://plnkr.co/edit/IjHgD1RboVuspyhUQbJM?p=preview

Could you help me ?
Thanks!

**Comment by KaihatsuOnline** [comment]
I have the same problem.
When inputting with Japanese Microsoft IME the composition is broken.

For example to type は one would first type the "h" key followed by the "a" key followed by enter to confirm the composition. However, in Select.Async after typing the "h" key, the composition is broken and the roman alphabet letter "h" is sent to the async search request. 

This is replicable on the React Select demo site: https://jedwatson.github.io/react-select/

A fix would be most appreciated.
Thank you for all the hard work.

**Comment by apearce** [comment]
Setting `ignoreAccents` to false solves this issue. It should probably be false by default anyway. What is odd is this prop was in well prior to beta13 but fro what I can tell the issue didn't arise until [this commit](https://github.com/JedWatson/react-select/commit/eefa8434827159faf44afc26d19d5a21e9517107) which came well after beta13 was released.

**Comment by odk211** [comment]
@apearce Thanks! it works for me! :)

**Comment by apearce** [comment]
I'm not sure this should be closed. It really is still a bug.

Note that I was able to reproduce the issue on Windows using the MS Japanese IME input and on a Mac using the [Google Japanese IME input](https://www.google.co.jp/ime/) but not on a Mac using the native Apple IME input.

**Comment by odk211** [comment]
@apearce I checked at my [plnkr](https://plnkr.co/edit/7lf9E2QxO20sKSqsUFmE?p=preview) with Windows10 default MS Japanese IME and Mac Google Japanese IME,  both worked.

**Comment by apearce** [comment]
@odk211 Did you try it with `ignoreAccents` set to `true` or `false`? It should work both ways. Only on a Mac using the native IME have I seen it work both ways, hence I feel this should still be open.

**Comment by odk211** [comment]
@apearce It works with `ignoreAccents={false}` and not with `ignoreAccents={true}`.

**Comment by odk211** [comment]
The plnkr code above is broken, so I create a new one. 
https://plnkr.co/edit/oPmYaj4mx5COcWNuRoSI

**Comment by odk211** [comment]
It seems this issue is already fixed 👍
