### ISSUE TITLE
How to remove "press backspace to remove ..." 

### ISSUE THREAD

**Issue by vgoklani** [JedWatson/react-select#1152]
I just updated to the latest beta, and I noticed that this is message is now displayed in the multi select box "Press backspace to remove..." 

How do I remove this message? 

When I now click on the select box, there is a faint blue vertical line that appears. I'm guessing this is related to the message? 

Thanks :)

Vishal

**Comment by Siern** [comment]
I found this lovely new feature today.
I cleared it by setting the "backspaceToRemoveMessage" to an empty string.

It would be nice to consider having a callback for localization text method.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
