### ISSUE TITLE
Clicking outside a Select on iOS9 does not close the Select

### ISSUE THREAD

**Issue by idrumgood** [JedWatson/react-select#1157]
Just as the title says. Desktop works fine, but tapping outside the component on iOS9 does not cause it to close.

Can be reproduced on React-Select example website: http://jedwatson.github.io/react-select/

**Comment by idrumgood** [comment]
Looks like it actually works fine on Android mobile (chrome) so it's iOS specific.

**Comment by MarcusOhman91** [comment]
Confirming this, works on android but not iOS.. Have you managed to find a workaround meanwhile @idrumgood ?

**Comment by idrumgood** [comment]
@MarcusOhman91 I have not, though I haven't really made much of an attempt.

**Comment by Zara603** [comment]
I have the same problem

**Comment by RyanBertrand** [comment]
iOS requires `cursor: pointer` to capture clicks/taps.  You should add a class to the body when the selector is open.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
