### ISSUE TITLE
Select is changing an uncontrolled input More info: https://fb.me/react-controlled-components

### ISSUE THREAD

**Issue by alex1012** [JedWatson/react-select#1159]
Warning: Select is changing an uncontrolled input of type hidden to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by StevenLangbroek** [comment]
See #1155

**Comment by bvaughn** [comment]
Jed's comment on PR #1155 makes me believe this issue should be resolved in the latest RC.

> @copas I looked into this, and have implemented a different fix by ensuring `stringifyValue` always returns a string. Thanks for the PR.

Indeed I am not seeing this in head of master so I'm going to close this issue. Thanks for the report!
