### ISSUE TITLE
Can not use Select.Async in React 0.13

### ISSUE THREAD

**Issue by hdminh247** [JedWatson/react-select#1160]
I can not use Select.Async with react 0.13, It return message "uppercase function is undefined"

**Comment by StevenLangbroek** [comment]
@hdminh247 can you be a bit more exact?

- What version of react-select are you using?
- What props are you passing in?
- You say it "returns message", do you mean it throws an error? If so: can you show the relevant bits of the stack trace?

**Comment by bvaughn** [comment]
Closing this issue due to lack of a response from @hdminh247.

Fwiw, react-select only supports React 0.14 and 15.0 so I think this might be a "won't fix" issue anyway.
