### ISSUE TITLE
No "read only" state

### ISSUE THREAD

**Issue by zeroskillz** [JedWatson/react-select#1161]
Simple issue, unless I missed it, there doesn't seem to be any read only state for this component, only disabled.

**Comment by fkretzer** [comment]
just set a `disabled=true` prop ;-)

**Comment by zeroskillz** [comment]
Readonly/disabled aren't quite the same, but it just occurred to me that **vanilla html selects do not have a read only state**...I'm guessing that's why there's no implementation here, so this would be more of a nice to have but not very important in the grand scheme of things.
