### ISSUE TITLE
Fix prerelease version numbers

### ISSUE THREAD

**Issue by herrstucki** [JedWatson/react-select#1162]
Unfortunately, when specifying `^1.0.0-beta14` in package.json (which is the default version range of `npm install --save`, npm thinks `1.0.0-beta9` is the latest version. Using a dot before the prerelease number solves that (i.e. `1.0.0-beta.14`).

**Comment by bvaughn** [comment]
It's too late to change this for the *beta releases but this has been fixed for the new rc releases, the latest of which is "1.0.0-rc.1". 😄

Cheers for pointing it out, @herrstucki!
