### ISSUE TITLE
How to prefill select value when it is Async with fetch.js?

### ISSUE THREAD

**Issue by ananddodia** [JedWatson/react-select#1166]
@JedWatson - I Need your help. please reply to below issue I am facing.
If any one else knows solution to this problem please help me.
I have made Async select with fetch.js. How can I make it prefilled when its in edit form scenario?
below is my code
`<Select.Async name={name} value={this.state.city} className={className} id={id} ref={ref} loadOptions={this.getCity} placeholder={placeholder} onChange={this.updateValue} autosize={false} clearable={false} minimumInput={1} backspaceRemoves={false} />`

value and label is already available from parent component.

**Comment by bvaughn** [comment]
FYI I am working on a refactor for `Async` that will invalidate this issue. (See PR #1226)

Once it's done, setting a value (as you've shown above) will work for initializing `Async`.

**Comment by bvaughn** [comment]
Resolved via PR #1226.

Look for an RC2 to come out (hopefully) sometime today with this change.
