### ISSUE TITLE
`name` prop isn't used

### ISSUE THREAD

**Issue by Calvein** [JedWatson/react-select#1168]
[Test on JSBin], the test isn't great but it works.
I simply have 2 selects, one uses the `name` prop while the other one uses the `inputProps` prop with a name:
```js
<Select
  options={options}
  name="test"
/>
<Select
  options={options}
  inputProps={{ 'name': 'test' }}
/>
```

The first one doesn't add the name, the second one does.

[Test on JSBin]: http://jsbin.com/zajafizoze/edit?html,css,js,output

**Comment by StevenLangbroek** [comment]
Yeah that seems to be correct. The "inputProps" get passed on to the search input, the "name" prop gets passed on to the hidden field.

**Comment by Calvein** [comment]
Geez, I was confused because the hidden input is only created after selecting a value. Sorry about that.
