### ISSUE TITLE
onChange handler return a object ?

### ISSUE THREAD

**Issue by darcusfenix** [JedWatson/react-select#1169]
Hi,

The onChange handler can return a object ? like this:

	Property	|	Type		|	Default		|	Description
:-----------------------|:--------------|:--------------|:--------------------------------
	onChange 	|	func	|	undefined	|	onChange handler: `function({name: "username", value:"darcusfenix"}) {}`

The property "name" is the attribute of input and "value" is like now. The property also can be REF of input.

Sometimes We have more than one Select and how we to know which input changed ?

**Comment by bvaughn** [comment]
Hi @darcusfenix,

> The property "name" is the attribute of input and "value" is like now. The property also can be REF of input.

I don't understand what you're asking/saying here.

> Sometimes We have more than one Select and how we to know which input changed ?

If you have multiple selects, you can bind to their `onChange` handlers like so:
```js
function onChange(selectId, value) {
  // selectId: identifies the Select
  // value: the normal parameter to onChange
}

const onChange1 = onChange.bind(this, 'selct-id-1');
const onChange2 = onChange.bind(this, 'selct-id-2');
```

**Comment by bvaughn** [comment]
I _think_ my response answers your only question- so I'm going to close this issue for now. Please let me know if you have remaining questions. :)
