### ISSUE TITLE
Is there a way to set focus?

### ISSUE THREAD

**Issue by mikecargal** [JedWatson/react-select#117]
I'm using a series of react-select components.  Whenever the user makes a selection on the first, then I render the second 9with values determined by the selected value of the first.  I'd like to then make the second component the "active" select component (rather than requiring them to tab to it).  I can't seem to find a way to specify this.  Am I missing a way to accomplish this?  (Or could I make an enhancement request if not).  I'd just like to be able to specify which react-select has focus when I do my render.

thanks

**Comment by vany-egorov** [comment]
+1

**Comment by Ismael** [comment]
You can add a ref to the select and then do this.refs.myselect.getInputNode().focus()

**Comment by mikecargal** [comment]
This isn't working for me.  getInputNode() is resolving to a ReactClass wth a focus method, and I'm calling it, but it's not changing focus to this control.
I have a set of select controls that I render one by one (where the contents of each is determined by the seletion from the previous control, so when I make a selection, I create the next select with it's options, I use your method to focus() it, but the control that was just selected retains the focus 9instead of moving it forward).  Is there something I need to do to unfocus that control?

**Comment by JedWatson** [comment]
I've just added a `focus` method and put it in the examples. Will be published in the next version.
