### ISSUE TITLE
Inconsistent multiselect onChange value when empty

### ISSUE THREAD

**Issue by jakezatecky** [JedWatson/react-select#1170]
The value parameter supplied to the `onChange` function when clearing out multiple selections is inconsistent. If you clear out selections using the right-most "x", the value `null` is returned. Otherwise, if you clear out the selections using the "x" on the individual items, eventually an empty string (`''`) is returned. Preferably, one or the other would be returned consistently.

``` jsx
const options = [
    { value: 'one', label: 'One' },
    { value: 'two', label: 'Two' }
];

const logChange = (val) => {
    console.log(typeof val, val);
};

ReactDOM.render(
  <Select
    multi
    joinValues
    options={options}
    onChange={logChange}
    simpleValue
    value="one"
  />,
  document.getElementById('example')
);
```

See test case below. Clear the selection using the right-most "x" and then clear the selection of the left-most blue "x". Two different values are returned.

https://plnkr.co/edit/UJ6oNaqRa5FOVHCGSani?p=preview

**Comment by hbarudin** [comment]
I have this as a comment in my code, but it's helpful as reference here:
```
    // parameter supplied to onChange is:
    //    - an array of option objects if multi = true
    //    - a single option object if multi = false
    //    - Select.props.resetValue (`null` by default, but can
    //      be set as a prop) if Select was cleared via the "X" button
    //    - an empty array if last token was deleted
```

So many options!

**Comment by mwilliamson-healx** [comment]
We have a wrapper around `Select` in our codebase, so I've just added something to the effect of the below to work around this:

```javascript
    var {resetValue, ...otherProps} = this.props;
    <ReactSelect
        {...otherProps}
        resetValue={resetValue === undefined && otherProps.multi ? [] : resetValue}
    />
```

**Comment by JedWatson** [comment]
@jakezatecky thanks for the clear report and plunker test case!

I've just merged #1177, would you mind confirming that resolves this issue?

cheers.

**Comment by jakezatecky** [comment]
I built the master branch and verified that the array/string value is now being consistently returned.

**Comment by JedWatson** [comment]
Great! Thanks for letting me know @jakezatecky
