### ISSUE TITLE
Add css class to the Select-control dynamically

### ISSUE THREAD

**Issue by dalkir** [JedWatson/react-select#1171]
Sometime you'd need to add a class to div.Select-control when you are validating the form like example, change the background to red when the select field is wrong. I'd like to help with this.

**Comment by JedWatson** [comment]
Couldn't you do this by wrapping the `<Select>` component inside an `invalid` class and targeting it using css like:

```css
.invalid .Select-control { background: red; }
```

This component already has a crazy number of props, I'd prefer not to add more unless they're actually critical.

**Comment by bvaughn** [comment]
👍  for Jed's suggested workaround. It's reasonable easy using the existing react-select Api.

Going to close this issue for now. 😄 Cheers!
