### ISSUE TITLE
Trigger Select / Reflect search input text on arrow up/down key press

### ISSUE THREAD

**Issue by lakshyaranganath** [JedWatson/react-select#1172]
Is there support to trigger the onChange handler when the arrow up/down keys are pressed?

What I'm trying to achieve is basically when someone searches for a text and is scrolling through the options using arrow keys, I want the text in the search box to reflect what their current highlighted option is (preferably, trigger selects without closing the menu).

If there is an event I can listen to for the arrow up/down keys that will give me the current option highlighted that would be great since I can update that as the currently selected value, and that might solve my problem.

Not really sure how to go about this. Any help is appreciated.

**Comment by bvaughn** [comment]
Once the next release candidate rolls out (soon) there will be a way for you to accomplish this using the new `onInputKeyDown` prop. Read more here: https://github.com/JedWatson/react-select#overriding-default-key-down-behavior-with-oninputkeydown

**Comment by bvaughn** [comment]
I'm going to close this issue since I believe the next RC should satisfy your request. Please let me know if not or if you have any questions. :)

**Comment by semireg** [comment]
Is there an example of how this is actually done?

**Comment by kanario03** [comment]
Hello,

this events do not work when you are with a dropdown opened.
