### ISSUE TITLE
Allow using other icons not only arrow

### ISSUE THREAD

**Issue by BreahnaDavid** [JedWatson/react-select#1176]
I need to use a magnifier instead of arrow at the right of select-input.
So i hid through css select `Select-arrow` then spend time to align
bootstrap icon instead of arrow ( fa fa-search fa-lg` ).
It would be very useful if we can pass own class instead of  `Select-arrow`.

I want to start working on it, if it is possible.
Thank you

**Comment by bvaughn** [comment]
Added support via PR #1191. This can be done by specifying your own renderin (in a similar way as `optionRenderer`, `menuRenderer`, etc.):

```js
function arrowRenderer () {
  return (
    <span>+</span>
  );
}

function render () {
  return (
    <Select
      arrowRenderer={arrowRenderer}
      {...otherProps}
    />
  );
}
```

**Comment by topher515** [comment]
If anyone gets here via google, note that after `v2.0.0`, `arrowRenderer` no longer exists and instead you use "components" system to make this change.

See the "Dropdown Indicator" example at https://react-select.com/components#replaceable-components
