### ISSUE TITLE
Remove arrow when input disabled

### ISSUE THREAD

**Issue by adirima-paix** [JedWatson/react-select#1179]
Hey, 

As an improvement, when it's disabled, you could remove the arrow as user is not able to use it anyways? 

Thanks, 
Adriana

### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by bvaughn** [comment]
How about a decreased opacity? That way it reinforces the fact that it's disabled while still looking like a drop-down. If we hide the arrow entirely it might be ambiguous whether it's a drop-down or a regular form input. (Which may or may not actually matter, but still...)

For example, here's a 0.35 opacity for the arrow:
<img width="421" alt="screen shot 2016-09-04 at 1 23 48 pm" src="https://cloud.githubusercontent.com/assets/29597/18229217/ea803cec-72a2-11e6-8e41-2287e3a957dd.png">

Compared to the enabled state:
<img width="412" alt="screen shot 2016-09-04 at 1 24 44 pm" src="https://cloud.githubusercontent.com/assets/29597/18229219/fa4fb292-72a2-11e6-9481-e7994f44778f.png">

**Comment by bvaughn** [comment]
Implemented in commit 00dd299.
