### ISSUE TITLE
Github users (Async with fetch.js)

### ISSUE THREAD

**Issue by tidjungs** [JedWatson/react-select#1181]
Github users (Async with fetch.js) witch single value crash
i cant type backspace when finish search

**Comment by bvaughn** [comment]
@tidjungs Can you provide more information about how it "crashes" ? The demo does not crash for me (in single or multi mode).

I do notice that multi select mode doesn't delete an entry when you type backspace like a non-async `Select` does. I don't think that's intentional.

**Comment by shashikanthgadgay** [comment]
@bvaughn Backspace doesn't work when you search for something for which results aren't available. It throws a undefined error at [Async.js](https://github.com/JedWatson/react-select/blob/master/src/Async.js#L155)

**Comment by bvaughn** [comment]
FYI I am working on a refactor for `Async` that should address this issue. (See PR #1226)

**Comment by bvaughn** [comment]
Resolved via PR #1226.

Look for an RC2 to come out (hopefully) sometime today with this change.
