### ISSUE TITLE
Fix design for RTL

### ISSUE THREAD

**Issue by Abzoozy** [JedWatson/react-select#1190]
I am proposing to add RTL support for few cases in RTL design where the select doesn't show up properly in multi-select here's one case:
<img width="587" alt="screen shot 2016-09-04 at 12 46 09 am" src="https://cloud.githubusercontent.com/assets/3064764/18227611/3c02a950-723b-11e6-8a0c-cb4868bcffe2.png">

but in RTL:
<img width="592" alt="screen shot 2016-09-04 at 12 46 26 am" src="https://cloud.githubusercontent.com/assets/3064764/18227616/5999a568-723b-11e6-82d2-607d43462ccc.png">

fix for the case:
<img width="597" alt="screen shot 2016-09-04 at 12 56 54 am" src="https://cloud.githubusercontent.com/assets/3064764/18227617/630ee2ca-723b-11e6-8d78-473ca19a255b.png">

I would be glad to help you fix such issues.

**Comment by bvaughn** [comment]
Hi @Abzoozy. Please feel free to submit a PR for RTL support if you have the opportunity. Assuming it does not add much complexity to the project- I'm sure we'd be happy to support it. 😄
