### ISSUE TITLE
onChange callback has 2 params, but comment in propTypes has one

### ISSUE THREAD

**Issue by meg2208** [JedWatson/react-select#120]
The comment on propTypes for the onChange component [here](https://github.com/JedWatson/react-select/blob/aefba37db363f1655819fa980e26c856d79c190a/lib/Select.js#L33) do not match the actual onChange handler [here](https://github.com/JedWatson/react-select/blob/aefba37db363f1655819fa980e26c856d79c190a/lib/Select.js#L275).

**Comment by dcousens** [comment]
Feel free to submit a PR @meg2208.

**Comment by dcousens** [comment]
https://github.com/JedWatson/react-select/blob/master/lib/Select.js
