### ISSUE TITLE
Combine Creatable and Async

### ISSUE THREAD

**Issue by traumatic** [JedWatson/react-select#1200]
Hello, I was wondering whether someone extended the Select.Async component with the behaviour of the Select.Creatable component? The use case is that a user may select predefined values from the given list (async) and in addition want to create new values.

Would be great if someone can refer to an existing project.

Thanks!

**Comment by bvaughn** [comment]
I'm going to go with a child-function patter for this so that `Creatable`, `Async` and `VirtualizedSelect` (from [react-virtualized-select](https://github.com/bvaughn/react-virtualized-select)) can all be composed. So it will look something like this:

```js
return (
  <Creatable {...outerProps>
    {(childProps) => <Async {...childProps} />}
  </Creatable>
)
```

**Comment by bvaughn** [comment]
PR #1207 adds partial support for this feature. You can compose an `Async` in a `Creatable` or vice versa. Unfortunately as the PR points out- the 2 don't seem to play nicely together. Additional time will need to be spent ironing out the details. (I'm traveling this week with limited time and Internet access and I haven't had the chance to dig into it yet.)

**Comment by bvaughn** [comment]
PR #1210 (potentially) finishes this work out with the introduction of a new HOC, `AsyncCreatable`. It ties `Async` and `Creatable` together in a way that's simple to use externally. For example:

```jsx
import React from 'react';
import Select from 'react-select';

function render (props) {
  return (
    <Select.AsyncCreatable {...props} />
  );
}
```

**Comment by traumatic** [comment]
Hi Brian, great work!! I'll close this issue and we'll continue discussion around pr [#1200](https://github.com/JedWatson/react-select/pull/1210).

**Comment by bvaughn** [comment]
PR #1210 😉

If you have the chance to test that branch, please do. I'd welcome more sets of eyes on it.
