### ISSUE TITLE
Override "Create option "{label}"" in Creatable

### ISSUE THREAD

**Issue by rubencodes** [JedWatson/react-select#1202]
Is there an equivalent to the `addLabelText` option in the newest version of this package? It seems right now it defaults to "Create option "{label}"", but I would like to be able to customize this.

**Comment by mpigsley** [comment]
@rubencodes It looks like you can override it with the `promptTextCreator` prop that has the signature `(label: String): String`.

**Comment by rubencodes** [comment]
Wonderful! I'll try this. I didn't see it in the documentation; should I
make a pull request adding it?
-- 
Ruben Martinez Jr

**Comment by mpigsley** [comment]
Yeah, I had to dive into the source to find it. Makes sense that it would be in the documentation 👍

**Comment by JedWatson** [comment]
Closed by #1206
