### ISSUE TITLE
Pass props to valueComponent

### ISSUE THREAD

**Issue by mehrdaad** [JedWatson/react-select#1208]
in my Select component I have sth like:  
    
    <Select
    valueComponent={GravatarValue}
								/>
My problem is that I can't pass props to ``GravatarValue``. how can I do that?

**Comment by bvaughn** [comment]
You could use an approach like this:

```js
function createGravatarValue (yourProps) {
  return function GravatarValueWrapper (selectProps) {
    return (
      <GravatarValue
        {...yourProps}
        {...selectProps}
      />
    )
  }
}

function createSelect (props) {
  return (
  )
}
```

**Comment by bvaughn** [comment]
You could use an approach like this:

```js
function createGravatarValue (yourProps) {
  return function GravatarValueWrapper (selectProps) {
    return (
      <GravatarValue
        {...yourProps}
        {...selectProps}
      />
    )
  }
}

function createSelect (props) {
  const GravatarValueWrapper = createGravatarValue(props)

  return (
    <Select
      {...props}
      valueComponent={GravatarValueWrapper}
    />
  )
}
```

**Comment by bvaughn** [comment]
Essentially, wraps the props you want to pass (outside of `Select`) up in a closure and then stitch them together with props from `Select` and pass both along to `GravatarValue` (or whatever value renderer you're using).

Cheers!
