### ISSUE TITLE
Is possible use this without react.js as standalone?

### ISSUE THREAD

**Issue by nunoguerra** [JedWatson/react-select#121]
This plugin is awesome, I have a project with jQuery and I use the selectize.js (https://github.com/brianreavis/selectize.js) but it's is buggy.

I would like to know if is possible use react-select as standalone javascript?

Thanks and keep good work!

**Comment by shipstar** [comment]
@nunoguerra Have you tried https://select2.github.io/? react-select seems heavily inspired by that, and select2 is jQuery-based, so it should be a good fit if you like this project.

**Comment by brianblocker** [comment]
:+1: for checking out select2, this is a component built FOR react, based on the standalones already out there :)

**Comment by dcousens** [comment]
This is a react component,  non-react use is not really within the realm of this libraries responsibilities.
