### ISSUE TITLE
Doesn't recognize some special characters like ö,ä

### ISSUE THREAD

**Issue by heaks** [JedWatson/react-select#1214]
I have Select.Async component with some options (e.g. loadOptions={this._loadOptions}). But it doesn't work well with special characters (ö,ä). It doesn't find an option which contains "ä", no matter what you type "ä" or "a". Any solutions ?

**Comment by knegusen** [comment]
I believe there is a prop for this that is not documented. I searched in the source code and found `ignoreAccents` and when setting that one to false it did not replace special characters with common ones (like å -> a). You can find the map in the file stripDiacritics.js. Don't know if this is the correct solution though.

**Comment by markoandersson** [comment]
I just encountered the same issue. Yes, setting `ignoreAccents` to `false` works. 

It seems that this concerns only `Async` component as I'm using basic `Select` component and special characters are working with it just fine. I'm also using custom `filterOptions`-function with `Select.Async` so maybe it's combination of those things.

**Comment by thevangelist** [comment]
Thanks @markoandersson! You saved my day!

**Comment by JedWatson** [comment]
This is better documented now
