### ISSUE TITLE
Implement autoLoad={false} in Select.Async 

### ISSUE THREAD

**Issue by f0urfingeredfish** [JedWatson/react-select#1216]
In the current documentation ```autoLoad={false}``` is listed as an option to stop the Async Select from loading when the component mounts. 
https://github.com/JedWatson/react-select#async-options

This isn't currently implemented. 
Look at:
https://github.com/JedWatson/react-select/blob/master/src/Async.js#L82

FIX:
Add autoLoad as an option with a default of true. 
Check autoLoad on componentDidMount to determine if it should fetch.

**Comment by bvaughn** [comment]
FYI I am working on a refactor for `Async` that should address this issue. (See PR #1226)

**Comment by bvaughn** [comment]
Resolved via PR #1226.

Look for an RC2 to come out (hopefully) sometime today with this change.
