### ISSUE TITLE
Clear focused option when the menu is reopened or make it configurable

### ISSUE THREAD

**Issue by jludev1** [JedWatson/react-select#1217]
Sometimes when the menu is opened there are two options highlighted in different ways - one for focused option and one for selected option. To some users the current behavior is confusing as this behavior is inconsistent with native html drop downs or native dropdowns on some OSs.
Suggest to focus on the selected option every time the menu is opened. Or expose a parameter to support this behavior.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
