### ISSUE TITLE
Auto resize when removing multi selections.

### ISSUE THREAD

**Issue by lucasferronato** [JedWatson/react-select#1218]
Look at the distance between the react-select and the checkbox below:
![pt1](https://cloud.githubusercontent.com/assets/22180873/18490236/78875fda-79d7-11e6-9cdb-49560c210399.png)

When you select lots of options both divs .Select-control and .Select are resized:
![pt2](https://cloud.githubusercontent.com/assets/22180873/18490249/89b01c5c-79d7-11e6-9c17-f254eb2ad95c.png)

When you remove those selections while the menu is closed it resizes only .Select-control div leaving a blank space between react-select and checkbox.
![pt3](https://cloud.githubusercontent.com/assets/22180873/18490283/a729ca8a-79d7-11e6-9a75-0aadb92aad68.png)

Removing with menu open works fine.
When you remove the last option it resizes correctly.

**Comment by sunny-g** [comment]
Giving the `.Select-control` the property `height: auto;` seems to work.

**Comment by lucasferronato** [comment]
@sunny-g yeah, it actually worked... thanks. (I thought I did tried this before but it seems i didn't)

**Comment by mladen107** [comment]
What I did in my project was changing "display:table" implementation to "display:flex" and that fixed this issue. You have to update some children too to shrink and grow properly.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
