### ISSUE TITLE
When multi=true, drop down list doesn't display after adding one option

### ISSUE THREAD

**Issue by jtadmor** [JedWatson/react-select#122]
It seems that once one option is selected, the option list no longer displays when the caret icon is clicked, and requires that the user begin to type in order to see it. This seems to hold for both async option loading and just passing in an array.

**Comment by pollen8** [comment]
Similar thing for me.
I noticed that if I add value="" to the select then it starts working again. However, when you load up the select its populated with a tag ''.

**Comment by pollen8** [comment]
ok this was my fault. I was using

```
<Select required name="contact-name" asyncOptions={getOptions} onChange={self.updateValue} style={{width: '100%'}} multi={true} ref="contacts" />
```

and at the same time in updateValue() I was altering this.state.contacts

As soon as I changed that to this.state.contactsSelected things started working again:

````
updateValue: function (newValue) {
		var c = this.state.contactsSelected.slice();
		c.push(newValue)
		this.setState({ 'contactsSelected': c })
	},
````

I guess that react-select is using state.contacts internally?

**Comment by dcousens** [comment]
Possibly related to https://github.com/JedWatson/react-select/issues/70
