### ISSUE TITLE
standalone.html fails

### ISSUE THREAD

**Issue by bshields-idatainc** [JedWatson/react-select#1225]
The <script src="..."> all lack a protocol (like 'https:') and default to 'file:', and therefore aren't found when simply launching the page from the OS (using Chrome on OS X).

Also, does the standalone.html really require the 3D rendering library (three.js) that is referenced on line 18?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
