### ISSUE TITLE
How to set the default selected value while very first time loading

### ISSUE THREAD

**Issue by rahulkag** [JedWatson/react-select#1229]
`<Select defaultValue ="Category" />	`

Some thing like above code so that we can set he default selected value into select box.

**Comment by Cein-Markey** [comment]
Have you tried `<Select value="Category" />`?

**Comment by rahulkag** [comment]
Thanks Cein-Markey. 

I was trying this but some thing went wrong into my code only so that I was assuming some like 'defaultValue'.

But finally I have fix this.
