### ISSUE TITLE
add margin-right so text is not mixed with the clear value icon

### ISSUE THREAD

**Issue by psimek12** [JedWatson/react-select#1230]
Can we please add **margin-right: 35px;** to the **.Select--single > .Select-control .Select-value'** selector?

It resolves issue with text being mixed with the clear value icon.

Thanks

**Comment by TheTFo** [comment]
I ran into this too, the rule above clears it up.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
