### ISSUE TITLE
Cursor blinks slightly below its normal position.

### ISSUE THREAD

**Issue by nikhilgoyal104** [JedWatson/react-select#1233]
![fireshot capture 83 - amap_ui - http___localhost_8040_ _amap_platforms_lenovo_create__k zp11sg](https://cloud.githubusercontent.com/assets/20395920/18664576/d47c7a0a-7f40-11e6-8efd-a51418d51687.png)
![fireshot capture 82 - amap_ui - http___localhost_8040_ _amap_platforms_lenovo_create__k zp11sg](https://cloud.githubusercontent.com/assets/20395920/18664577/d47d52b8-7f40-11e6-96f3-4ac0e7ade90d.png)

Can someone point out why this is happening ?

**Comment by MilllerTime** [comment]
For a rendering issue like this, it would be super helpful for everyone to know the browser and OS you were using when you noticed this.

For issues in general, it would be helpful to know the version of react-select you're using.

This will help others reproduce your issue and offer help! 😃

**Comment by akrikos** [comment]
Mac OSX 10.11.6 using 1.0rc2 in Chrome, FF, Safari, and Opera I see this happening. I think @nikhilgoyal104's is ~2px further down than mine though.

I fixed it with:
```
.Select-input > input {
  padding-top: 4px;
}
```
But I get the feeling that there's something else going on. Dunno what though.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
