### ISSUE TITLE
Gravatars not working in documentation-page when using HTTPS

### ISSUE THREAD

**Issue by Pyppe** [JedWatson/react-select#1234]
Stumbled on https://jedwatson.github.io/react-select/ (note the HTTP**S**). Noticed that the `react-gravatar` used in that page is not working with HTTPS. Avatars are not loaded due to mixed content:

```
Mixed Content: The page at 'https://jedwatson.github.io/react-select/' was loaded over HTTPS, but requested an insecure image 'http://www.gravatar.com/avatar/b0d8c6e5ea589e6fc3d3e08afb1873bb?d=retro&r=g&s=15'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
