### ISSUE TITLE
is there any way to expand the options list by default, without clicking the selection menu ? 

### ISSUE THREAD

**Issue by iiitmanikanta** [JedWatson/react-select#1235]
### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by andreme** [comment]
Use openOnFocus and focus the select?

**Comment by jayfunk** [comment]
That doesnt appear to work. I have tried most of the props to try and get the component into a state where the options list is always displayed.

**Comment by the-spyke** [comment]
You need to set "autofocus" and "openOnFocus" to true. Alternatively, you can call "focus" instance method in your own "componentDidMount" function with "openOnFocus" set to true.

**Comment by vickingbg** [comment]
"autofocus"={rue and "openOnFocus" = true works for me. Thanks !
