### ISSUE TITLE
Async shared cache (probably not wanted)

### ISSUE THREAD

**Issue by TheSharpieOne** [JedWatson/react-select#1236]
#1226 introduced a new ~~bug~~ undocumented feature 😄 , shared cache. This is probably not wanted as it causes issues. The [object which is used as a default prop](https://github.com/JedWatson/react-select/pull/1226/files#diff-149b30fde0306e461dc519d4853f1e50R26) is used by all of the async components by default. Because of this, and how objects and references work, everyone shares the same cache unless they specifically supply their own cache object. This of course causes issues when two async component which utilize two different API endpoints both have the same cached results for a given input. This can be seen in the updated docs that were part of the PR that is mentioned above. The "official" docs website isn't updated yet. Simply enter a value into the async field (it will fetch it), then remove the value (making the input '') this will trigger `loadOptions` for the cache of `''` which matches the cache for the contributors and it will load the contributors as options. (Note: that because the shape/properties are different between the two selects, the async will show blank options. Looking at the data, it is in fact the contributors).

So you don't have to deploy the new docs or run them locally, here is this: http://www.webpackbin.com/EkyrD3shW

**Comment by Aktof** [comment]
Agreed, I small quick fix I'm currently using is passing and object as the cache prop. Will create a P.R. as a fix.

```
<Select.Async
    ...
    cache={{}} />
```

**Comment by aackerman** [comment]
Yep, I'm running into this behavior as well :(

**Comment by aconran** [comment]
Just ran into this in 1.0.0-rc2; looks like the fix was released with 1.0.0-rc3.
