### ISSUE TITLE
onChange event fires in different order than "native" form/select

### ISSUE THREAD

**Issue by headquarters** [JedWatson/react-select#1238]
I am trying to submit a normal HTML form using the onChange event for react-select, but it submits the old value rather than the new value. I'm using version 0.9.1. I think this is because the `fireChangeEvent` function is called before `setState`, so the form gets submitted before the hidden input field value is actually set: https://github.com/JedWatson/react-select/blob/d8fe544f32dc28e1f72592671f7c70bddae3258a/lib/Select.js#L320

The default HTML behavior is that the change event on a select item will change its selected value before a form that is submitted. Here's a codepen to demonstrate that behavior: http://codepen.io/michaelehead/pen/pENByp

The behavior as of 0.9.1 is that the "old" value gets submitted. Here's another codepen showing that behavior (codepen handled fake POSTs better than plunkr, so I went with that for demos): http://codepen.io/michaelehead/pen/KgaPYK

If the direction of the project is to mimic the behavior of normal HTML elements, then I think the fireChangeEvent function should be a callback to setState (which would require some tweaks to fireChangeEvent in terms of checking old vs new state). If this isn't really in line with the direction of the project, feel free to close this issue as wont-fix. :)

If the issue is worth exploring further, I'd be happy to put up a PR to address it. Thanks!

**Comment by jnachtigall** [comment]
@headquarters Not sure if this is still an issue (because in `master` branch I cannot find the relevant code snippet that you cited).

Anyway, I got around this in my application by:
```
  handleOnChange = curVals => {
    this.setState(
      {
        myAppsValues: curVals
      },
      this.submitForm
    );
  };
```

```
  submitForm = () => {
    console.log('Submitting the form via JS');
    // There are many browser quirks when it comes to submit()
    // so just using jQuery to handle these
    $(this.searchForm).submit();
    return;
  };
```

```
      <form
        ref={form => {
          this.searchForm = form;
        }}
      >
        <Select.AsyncCreatable
          ...
          onChange={this.handleOnChange}
          ...
          value={myAppsValues}
        />
    </form>
```
That is, passing the call to submitting the form as a callback to setState.

So I think this can be closed? 

If still valid, I guess if there was a PR the maintainer(s) seem to be open towards it. They just do not seem to have time :-/

**Comment by headquarters** [comment]
@jnachtigall Thanks for the response. I'm no longer working on the project that was using react-select, so I can't try out your solution right now, but it looks like a good approach. I can't find the line I referenced in the original issue either, so I bet the library has diverged so much since I opened this issue that it's not relevant any more. I'm going to close it.
