### ISSUE TITLE
VirtualizedSelect Error: Uncaught Invariant Violation: findComponentRoot

### ISSUE THREAD

**Issue by nlokare** [JedWatson/react-select#1239]
Hi @JedWatson @bvaughn,

Looks like I am having issues with VirtualizedSelect. I've tried passing the component the options from a state variable which is set in the callback of `$.get("/endpoint')` in `componentWillMount`. 

I then tried to implement the example and am still getting the same error. I can send along more code if that helps, but it's essentially the example.

**Comment by bvaughn** [comment]
Which "example" are you referring to?

The one on the [demo site](http://jedwatson.github.io/react-select/) (source code [here](https://github.com/JedWatson/react-select/blob/master/examples/src/components/Virtualized.js)) seems to work fine.

Please provide a repro case (Plunker would be great, git repo that we can check out and run would be fine too).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
