### ISSUE TITLE
searchPromptText is showing instead of noResultsText when there are no results in ReactSelect.Async 1.0.0-rc2

### ISSUE THREAD

**Issue by moodysalem** [JedWatson/react-select#1242]
Seems related to the merged refactor in this line

https://github.com/JedWatson/react-select/commit/64335f8d0016aecbca8dfe9d4a11a61551b9f5bd#diff-149b30fde0306e461dc519d4853f1e50R139

**Comment by f2net** [comment]
I confirm this issue: @JedWatson could you correct the pointed line?
Thank you very much!

**Comment by robertmaloney** [comment]
RC2 actually didn't have support for `noResultsText` (see [here](https://github.com/JedWatson/react-select/blob/2b144481d773807827befd75b443a6a7568b3e1d/src/Async.js)). RC3 was released today and does have it (without default prop though). This can be closed.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
