### ISSUE TITLE
AsyncCreatable lower cases entries - v1.0.0-rc.2

### ISSUE THREAD

**Issue by traumatic** [JedWatson/react-select#1244]
Hi,

AsyncCreatable is fantastic. Found a minor thing. All upper case letters get converted into lower case letters when entering a new String to input box.
Tested it with the example GithubUsers.js file in v1.0.0-rc.2.

Thanks

**Comment by TheSharpieOne** [comment]
There is an [`ignoreCase` props which defaults to `true`](https://github.com/JedWatson/react-select/blob/2e37a5d36f39f8ec690f649b169eeea6dabc1ca4/src/Async.js#L10). When the prop is true, it will [lowercase the input](https://github.com/JedWatson/react-select/blob/2e37a5d36f39f8ec690f649b169eeea6dabc1ca4/src/Async.js#L130-L132). Try setting it to `false`.

**Comment by jstrouse** [comment]
Except when you do that the filtering on the data returned is now case-sensitive. Also see issue #1106

**Comment by traumatic** [comment]
I closed this issue as I believe it is covered by [issue 1106](https://github.com/JedWatson/react-select/issues/1106)
