### ISSUE TITLE
Ability to set multiple delimiters with multi-select field types.

### ISSUE THREAD

**Issue by sinistersnare** [JedWatson/react-select#1245]
Hello, I am not sure if this is the correct venue for feature requests, so please let me know if this should be moved.

I would like to know if it could be possible to set the delimiters for multi select fields.

My use case is as follows, for context:

I have a  Creatable multi-select field where users can enter words and have them split up. Right now, users need to type Enter or Tab to complete the word, and that is good. However, when users type space, I would like it to cut off the word too. This removes the ability for users to type multiple words in a single tag. 

I looked for an option to set an array of keycodes, but was unable to find the correct method to do so. This feature is available in [react-tag-input](https://www.npmjs.com/package/react-tag-input) and would love to have it in this library.

Sorry for rambling a bit, but please let me know if this is possible or if this feature is wanted. I would love to help out if you would like.

**Comment by andreme** [comment]
You can use shouldKeyDownEventCreateNewOption

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
