### ISSUE TITLE
Select multi, close dropdown when clicking selecting option - v1.0.0-rc.2 

### ISSUE THREAD

**Issue by traumatic** [JedWatson/react-select#1246]
Hello,

Is there an option to change the default behavior that if _multi_ is set to _true_ the dropbox is closed once an option has been selected? Currently, if _multi_ is _true_ the dropbox remains open unless I click outside of the Select component.

Thanks

**Comment by IvanLeonenko** [comment]
You can try setting `autoBlur={true}` property.

**Comment by traumatic** [comment]
Thanks Ivan! That works like a charm ...

**Comment by Dibakar-Halder** [comment]
thank you i also struggled a bit

**Comment by kdramana99** [comment]
> You can try setting `autoBlur={true}` property.



> You can try setting `autoBlur={true}` property.

Hello,

I am using ant design <Select />. Is there an option to change that if multi is set to true the dropbox is need to be closed once an option has been selected Currently, 
if multi is true the dropbox remains open unless I click outside of the Select component. 

Here is my code:
***************************************************
const { Select, Radio } = antd;

const Option = Select.Option;

const children = [];
for (let i = 10; i < 36; i++) {
  children.push(<Option key={i.toString(36) + i}>{i.toString(36) + i}</Option>);
}

function handleChange(value) {
  //console.log(`Selected: ${value}`);
}

function handleSelect(value) {
  console.log(`Selected Value: ${value}`);  
}
class SelectSizesDemo extends   React.Component {
  state = {
    size: 'default',
  };

  handleSizeChange = e => {
    this.setState({ size: e.target.value });
  };

  render() {
    const { size } = this.state;
    return (
      <div>
        <Radio.Group value={size} onChange={this.handleSizeChange}>
          <Radio.Button value="large">Large</Radio.Button>
          <Radio.Button value="default">Default</Radio.Button>
          <Radio.Button value="small">Small</Radio.Button>
        </Radio.Group>
        <br />
       
        <br />
        <Select  
          closeOnSelect={true}    
          autoBlur={true}
          showArrow={true}
          allowClear={true}
          autoFocus={false}
          mode="multiple"
          size={size}
          placeholder="Please select"
          defaultValue={['a10', 'c12']}  
          onChange={handleChange}
           onSelect={handleSelect}
          style={{ width: '100%' }}
        >
          {children}
        </Select>
        <br />       
      </div>
    );
  }
}

ReactDOM.render(<SelectSizesDemo />, mountNode);
**********************************************************
closeOnSelect & autoBlur is not working correctly to close the dropdown after making selection. 

Thanks
Venkat

**Comment by kdramana99** [comment]
Hello,

I am using ant design <Select />. Is there an option to change that if multi is set to true the dropbox is need to be closed once an option has been selected Currently, 
if multi is true the dropbox remains open unless I click outside of the Select component. 

closeOnSelect & autoBlur is not working correctly to close the dropdown after making selection. 

Thanks
Venkat

**Comment by caub** [comment]
`autoBlur` doesn't seem supported anymore, what's the way now?

**Comment by caub** [comment]
this PR should do it https://github.com/JedWatson/react-select/pull/1691

hopefully

**Comment by arihantR** [comment]
There's a prop that you can pass to your dropdown - closeMenuOnSelect={true}. Although it is true by default, so on selection your dropdown should get close. Generally to avoid auto close we use closeMenuOnSelect={false}.  Check if this works for you. eg -> <Select closeMenuOnSelect={false} />

**Comment by deshaXii** [comment]
just add this property 
  menuIsOpen

**Comment by prathamesh-voltup** [comment]
There is no such an option to auto close dropdown when select or remove values from option, it is given 'closeOnSelect' but it's not working. Please do something devs...

**Comment by iomerkoyuncu** [comment]
Hi, in material ui, it is `disableCloseOnSelect` prop. For anyone using mui.
