### ISSUE TITLE
Creatable component doesn't allow input key down handling.

### ISSUE THREAD

**Issue by IvanLeonenko** [JedWatson/react-select#1247]
First of all, thanks for a nice component.

Creatable component has own handler of `onInputKeyDown`, which doesn't check if there's user's handler provided. So setting a handler for `onInputKeyDown` has no effect.

Doesn't work:

    <Creatable
        onInputKeyDown={this.inputKeyDownHandler}
    />

I think, Creatable should call user's handler as well, otherwise it breaks defined API.

Going to create pull request on that.

**Comment by JedWatson** [comment]
Fixed by #1248

**Comment by andfelzapata** [comment]
@JedWatson Very nice Component, thank you ! I have this issue with 1.0.0-rc.2. Is there any chance this update could be merged to it  ?
