### ISSUE TITLE
If options are being returned by a call or async but all options are returned when the call returns.

### ISSUE THREAD

**Issue by anuprai11** [JedWatson/react-select#1250]
Consider the case where I have a component called my-comp which is rendering a reat-select and I need to load the options from some call or promise. A general thing to do in this case is to make the call during my-comp' constructor, componentDidMount and when I get the options I again render my component this time providing react-select with the fetched options.

But now applications don't want many of there components having state(I am not sure about that, I just like dat).

One hack I found for this is using react select-Asyc and sending options on the first call and ignoring the rest and sending the options I fetched the first time. But in this case for each input rather then just filtering options react select will think of new options and set in its state which seems like a hack.

So is there a some solution already in react-select that I am not able to figure out or something could be done about this?

**Comment by anuprai11** [comment]
I thought if there was a select component like async, creatable which would handle this case and send options to select

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
