### ISSUE TITLE
react-select choice dissapears once selected

### ISSUE THREAD

**Issue by foodaka** [JedWatson/react-select#1251]
When i make a choice, the value does not show in the select bar. I have multi-choice available, and allowCreate to be true. Im using "react-select": "^0.9.1". I have the value sent through redux and stored as {selectTags}. It still allows me to select correctly, it just does not show in the bar.

```

var options = [
    { value: 'scuba', label: 'scuba' },
    { value: 'freedive', label: 'freedive' },
    { value: 'wreck', label: 'wreck' },
];

                <Select
                  name="form-field-name"
                  options={options}
                  onChange={this.handleTagInput.bind(this,0)}
                  allowCreate={true}
                  multi={true}
                  value={selectTags}
                />

**Comment by foodaka** [comment]
oops value issue in redux

**Comment by M3lkior** [comment]
Which issue in redux @foodaka  ?

**Comment by foodaka** [comment]
my value data from redux was not passing to component so it wouldnt show correctly

**Comment by leonzinger** [comment]
Hey @foodaka could you please show me how you handled it? I am struggling with the same issue now

**Comment by foodaka** [comment]
u need to pass it a value, and your onchange must update state, which updates the value

```
 <Select
                  name="form-field-name"
                  options={options}
                  onChange={this.handleTagInput.bind(this)}
                  allowCreate={true}
                  multi={true}
                  value={this.props.REDUXVALUE}
                />
```

**Comment by foodaka** [comment]
from docs

The value property of each option should be set to either a string or a number.

When the value is changed, onChange(selectedValueOrValues) will fire.

**Comment by leonzinger** [comment]
@foodaka Thank you very much! that helped!
