### ISSUE TITLE
Clearing value in multi select causes option list to expand

### ISSUE THREAD

**Issue by jamaica474** [JedWatson/react-select#1252]
Given multiselect with several options selected:
![0390b46807ac2ef6d68958bfa393018a](https://cloud.githubusercontent.com/assets/7143553/18844059/a726a2d0-83e9-11e6-918f-0fbc3eb36e7a.png)

When I click on either 'X' (clear single or clear all):
![yniu5k 1](https://cloud.githubusercontent.com/assets/7143553/18844162/13714cec-83ea-11e6-93f4-dc32e46a4077.jpg)

Option list expands: 
![5lf9ix](https://cloud.githubusercontent.com/assets/7143553/18844198/4a0eb7ee-83ea-11e6-916a-ab7aa6e7b558.jpg)

I would say this behavior is unexpected, when user clicks clear select should only clear itself, nothing else should happen.,

**Comment by dylanfpaul** [comment]
+1

**Comment by puckybreg** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
