### ISSUE TITLE
Remove Creatable's new option on close

### ISSUE THREAD

**Issue by apucacao** [JedWatson/react-select#1256]
Hey all,

The new `Creatable` component works really well! Thank you.

On thing I am trying to figure out is how I can make sure that the "Create option XYZ" option gets removed when the select closes. Some users are confused that they are presented with that option, even though there is nothing typed in the field.

Looking at the list of props, I don't see an option for this. Am I missing something?

Thanks,

Alexis

**Comment by MilllerTime** [comment]
This sure looks like a bug. "Create option XYZ" should only be visible when "XYZ" is the current input value. I'm running into the same issue as you in a few situations:

- When `onBlurResetsInput` or `onCloseResetsInput` causes the input to be reset, it's not removing the custom create option from the menu.
- If "Sycamore" is an existing option, and I type "Syc", then select "Sycamore", the value is added and the input is cleared, but "Create option Syc" remains in the menu.
- If I select some options, then type "XYZ", "Create option XYZ" shows as expected. At that point, if I click clear all, all options as well as the input field is cleared. However, again, the "Create option XYZ" is not removed.

Worse still, when `multi={false}`, the "Create option XYZ" persists even if you select it.

Seems the only way to clear the new option is to type a character and then delete it, or for multi select mode, to add the custom option.

This is confusing for end users. While the current functionality is awesome, hopefully this can be improved.

**Comment by MilllerTime** [comment]
Also noticing the following behavior which may or may not be intended.

If I type "XYZ" as a new option and add it, then immediately remove it, "Create option XYZ" is displayed in the menu again even though the input is empty. While it might be a convenience for some use cases to re-add a deleted custom option, the option is out of sync with the input field at that point.

**Comment by raianand** [comment]
It happens because Creatable sets value of input in its instance and not in state.

https://github.com/JedWatson/react-select/blob/master/src/Creatable.js#L156

onBlurResetsInput and onCloseResetInput just sets value in the component state. So as a workaround, you can add onBlur and onClose props to set inputValue. Here i am assuming you are using default values of onBlurResetsInput and onCloseResetInput. You can change it as per your requirements.

```
onBlur={() => {if(this.selector){this.selector.inputValue=''}}}
onClose={() => {if(this.selector){this.selector.inputValue=''}}}
ref={(c) => this.selector = c}
```

**Comment by MilllerTime** [comment]
Nice find @raianand, that works! While the component internals are [deliberately undocumented](https://github.com/JedWatson/react-select#methods), this seems like a fairly straightforward fix. In fact if fixing the component internals is also this simple, I might give it a shot.
