### ISSUE TITLE
Events for add and remove item in multi mode

### ISSUE THREAD

**Issue by switz** [JedWatson/react-select#1258]
It would be nice to have handlers for adding and removing an individual item in multi mode.

`onChange` returns the entire array of values, but sometimes it's useful to track what has been added or removed. I propose two new handlers:
1. `onAddValue`
2. `onRemoveValue`

which each pass the value that has been added or removed respectively. If anyone has any problems with this or suggestions on how to improve it please share your feedback. I'm happy to send a PR if you are open to accepting it.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
