### ISSUE TITLE
cannot set cache=false in Select.Async

### ISSUE THREAD

**Issue by sfmcintyre** [JedWatson/react-select#1259]
According to the README:

"Caching can be disabled by setting `cache` to `false`"

I think the desired behavior for `cache = false` is to ensure that options are NOT filtered as more specific inputs are entered, rather the options are populated by a new call to prop `loadOptions` each time the input changes. The issue is that the initial call to `loadOptions` returns a set of options based on the first input, and these options ARE filtered as more specific inputs are typed, despite that i have `cache` set to `false`

I'm using version `1.0.0-rc.2` with the component configured as follows

```
<Select.Async
    value={this.state.value}
    loadOptions={this.loadAutocompleteOptions}
    cache={false}
    onChange={this.handleChange}
    onInputChange={(input) => { this.setState({ value: input })}
/>
```

**Comment by TheSharpieOne** [comment]
I cannot reproduce this using the following sample: http://www.webpackbin.com/Nka5R2oaW
Here is the results I see: Notice the duplicated network requests indicating it did not cache and reuse the responses.
![cache-false](https://cloud.githubusercontent.com/assets/664714/19055316/4d0da3a4-8991-11e6-94dd-f00ddf6bd616.gif)
If you have a more specific example showcasing the issue, you should add a link to it.

**Comment by dreampulse** [comment]
I have the same issue!

**Comment by dreampulse** [comment]
I solved the issue!
The filter is broken, just pass `filterOption={() => true}` as an option to disable filtering

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
