### ISSUE TITLE
Limiting number of options displayed in dropdown

### ISSUE THREAD

**Issue by super-cache-money** [JedWatson/react-select#126]
For example, how would one only show the 5 closest matches to input text in the dropdown, despite having 1000 options which are searchable.

**Comment by dcousens** [comment]
@super-cache-money how are they sorted?

**Comment by Wutnudel** [comment]
If you are only concerned about the display this css may help you out:

    .Select-option:nth-child(n+6) {
      display: none;
    }
    .Select-option:last-child,
    .Select-option:nth-child(5) {
      border-bottom-right-radius: 4px;
      border-bottom-left-radius: 4px;
    }

I know this isn't pretty at all but as long as this doesn't impact your performance too hard it may be a quick-and-dirty workaround until this is implemented.

**Comment by nslobodchuk** [comment]
I'm in a similar situation. I've got 4000 options and would like to either limit the number of options displayed or start filtering only if the input is longer than 3 characters. Do you know if there's a way to do this?
Thanks in advance.

**Comment by chriddyp** [comment]
I'm in a similar case where I have just 6 options and I'd like to display all 6 options at once instead of requiring the user to scroll down just to see 1 more item.

Is CSS still the best way to do this?

**Comment by sttevan88** [comment]
+1

**Comment by onelz** [comment]
+1

**Comment by ramonvicelli** [comment]
+1

**Comment by aappddeevv** [comment]
Oh, I just hit this as well. To fit visually, I need to limit it to the dropdown just showing 2-3 options and scroll the rest.

**Comment by sahilanguralla** [comment]
+1

**Comment by curliq** [comment]
+1

**Comment by javierojeda94** [comment]
Any updates on this?

**Comment by shaayaansayed** [comment]
+1

**Comment by douxsey** [comment]
You can user the props `maxMenuHeight={200}`

**Comment by toninofox** [comment]
In the meantime I added this workaround:

```
const MenuList = props => {
  return (
    <components.MenuList {...props}>      
      { Arrays.isArray(props.children) ? props.children.slice(0, 10) : props.children }
    </components.MenuList>
  );
};
```

Where 10 is my limit

```
export default () => (
  <Select
    defaultValue={colourOptions[1]}
    options={colourOptions}
    components={{ MenuList }}
  />
);
```

In this way you will still be able to search inside the list but you will display just the first 10 elements of the list

**Comment by cbmek** [comment]
Why not just go with `AsyncSelect`?

Example with limit:

```jsx
<AsyncSelect
    loadOptions={(inputValue, callback) => {
        callback(selectOptions.slice(0, 50))
    }}
    defaultOptions={true}
    value={value}
    onChange={(val) => this.onValueChanged(val)}
/>
```

Example with limit and simple serach:

```jsx
<AsyncSelect
    loadOptions={(inputValue, callback) => {
        callback(selectOptions.filter(x => x.label.toLowerCase().includes(inputValue.toLowerCase())).slice(0, 50))
    }}
    defaultOptions={true}
    value={value}
    onChange={(val) => this.onValueChanged(val)}
/>
```

**Comment by vitexikora** [comment]
Quick temp solution:
```jsx
const resultLimit = 10
let i = 0
return <Select filterOption={({label}, query) => label.indexOf(query) >= 0 && i++ < resultLimit} />
```

**Comment by rasnick** [comment]
Solution provided by @vitexikora worked for me, but I'd like to point out that 'label' will be the visual option for the user, so I'd rather use value, which _should be_ sanitized and/or normalized.
```javascript
const resultLimit = 10
let i = 0
return <Select filterOption={({value}, query) => value.indexOf(query.toLowerCase()) >= 0 && i++ < resultLimit} onInputChange={() => { i = 0 }} />
```

**Comment by Carchuli** [comment]
@vitexikora solution worked for me also! Im dealing with 50k options, and with this solution I can search between that all records. The only issue is that it only displays the 10 first values, I will try to make it async using `onMenuScrollToBottom` prop to make it 'async' and load 10 more values

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
