### ISSUE TITLE
Multiple values for same key?

### ISSUE THREAD

**Issue by m4recek** [JedWatson/react-select#1261]
Hi,
we want to search through multiple values which points to same key. Is it possible?

So our data object look something like code bellow. Search should be executed on privateName, publicName and id, but there should be just one result even if more then one value is hit. (maybe with indication which it was).

```
[
  ...
  { 
    label: 'Private name',
    value: {
      privateName: 'Private name',
      publicName: 'Public name',
      id: '12321324421412'
    }
  }
  ...
]
```

**Comment by andreme** [comment]
You can use the filterOption function:
`<select options={[{label: 'test', value: 1, keywords: 'bla blub test'}]} filterOption={(option, filter) => option.keywords.indexOf(filter.toLowerCase()) >= 0} />`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
