### ISSUE TITLE
How to keep menu closed after selecting a value when multiselect? 

### ISSUE THREAD

**Issue by torbjornlu** [JedWatson/react-select#1262]
Hi, first, thanks for a great component!

I would like the menu to be closed, after I have selected a value in multi select. Is that possible? I have tried scrollMenuIntoView={false} and openOnFocus={false} without success.

Thanks
/Torbjörn

**Comment by DanielHeath** [comment]
To close the whole control, you can keep a ref to the `Select` and call `this.refs.select.closeMenu()`.

**Comment by torbjornlu** [comment]
Thanks @DanielHeath, it solved my problem.
