### ISSUE TITLE
How do i highlight selected item in dropdown

### ISSUE THREAD

**Issue by amit1911** [JedWatson/react-select#1264]
I want to apply a css class to the current selected item when the dropdown is open. Something like the following.

![capture](https://cloud.githubusercontent.com/assets/3509404/18984271/2adc4674-8724-11e6-858c-6a57459512b5.PNG)

As you can see the current selected item is highlighted in red when the dropdown is opened. This is done by passing the className to the option that is currently selected as follows:-

```
const options = data.map((item) => {
    let className = item.isDefault ?
        'highlight-selected-item ' :
        '';

    return {
        label: item.profileName,
        value: item.profileName,
        className
    };
});
```

I think it would be great if the Select component can take a prop like `optionSelectedClassName` so that we don't have to manually see which item is selected and add a className to that.

**Comment by amit1911** [comment]
Just found a simpler way of doing this by going through the codes. The 'is-selected' class is added to the item that is currently selected. So just adding the following worked for me.
```
.Select-option.is-selected {
    color: red;
}
``` 
I guess this needs to be added to the documentation.

**Comment by chloerice** [comment]
I too wanted to change the color of the selected menu option. The adjoining .is-selected amit1911 mentions doesn't work with the current version, however .is-focused did:

````
.Select-option.is-focused  {
    background-color: rgba(1, 198, 136, 0.15);
}
````

**Comment by harsimarriar96** [comment]
I've been trying the same thing but it is not working at all. The documentation for styling would be in depth.

**Comment by jackblackCH** [comment]
> This will work.
> 
> ```
> const CustomStyle = {
>   option: (base, state) => ({
>     ...base,
>     backgroundColor: state.isSelected ? {Color1} : {Color2},
>     ':active': {
>       backgroundColor: state.isSelected ? {Color3} : {Color4}
>     }
>   })
> }
> <Select styles={customStyle} >
> ```

This should be mentioned in the docs.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
