### ISSUE TITLE
Allow to use react-select as a search autosuggester control

### ISSUE THREAD

**Issue by istarkov** [JedWatson/react-select#1266]
For now is the only problem to use `react-select` as a search input with autosuggest (like google search) is that loaded options is autofocused on a first non disabled option
at [getFocusableOptionIndex](https://github.com/JedWatson/react-select/blob/0b3622402d2dbbbd2d87600f2b99ec17097f8417/src/Select.js#L986-L1002), 
so even you haven't select any option, you will get first on enter press. 

Just removing [this check](https://github.com/JedWatson/react-select/blob/0b3622402d2dbbbd2d87600f2b99ec17097f8417/src/Select.js#L998-L1000) will solve this problem.

What are you think about some additional boolean prop like `optionAutoFocus` which will disable default option select logic?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
