### ISSUE TITLE
Multiline comment in sass mixin included in all output files

### ISSUE THREAD

**Issue by jasonblanchard** [JedWatson/react-select#1269]
If you import the `react-select/scss/select.scss` mixin directly into your project like this:

```
@import 'react-select/scss/select';
```

This comment at the top of the file

```
/**
 * React Select
 * ============
 * Created by Jed Watson and Joss Mackison for KeystoneJS, http://www.keystonejs.com/
 * https://twitter.com/jedwatson https://twitter.com/jossmackison https://twitter.com/keystonejs
 * MIT License: https://github.com/JedWatson/react-select
*/
```

ends up in _all_ files that include the mixin (which is especially annoying if you centralize your mixin imports in a single application mixin that you use everywhere else).

It looks like [this is the standard sass behavior for multiline comments](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments), but it's surprising to see this in the build.

I would recommend using `//` comments for those comments so that they do not end up in the build.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
