### ISSUE TITLE
Text reflows on firefox

### ISSUE THREAD

**Issue by DanielHeath** [JedWatson/react-select#1272]
Plunker: https://embed.plnkr.co/XDh6yYukc7cWWXuAtJRD/

`Select-aria-only` needs to `float` so it's out of layout, otherwise it causes text reflows on firefox.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
