### ISSUE TITLE
Cannot scroll through long options list use up/down arrow key

### ISSUE THREAD

**Issue by phongtattuan** [JedWatson/react-select#1273]
Hello!

I have an issue on scroll through a long options list, the list's scrollbar did not scroll when I press up/down arrow key.
This issue also occur on demo page: http://jedwatson.github.io/react-select/

Is there anyway to fix this issue?

Thanks in advance.

**Comment by lordalaqua** [comment]
+1. I have the same issue, the scrollbar position does not seem to follow the focused option when using the keyboard.

**Comment by omrimor** [comment]
+1. Same issue here.

**Comment by didierfranc** [comment]
+1 same issue 😭

**Comment by phongtattuan** [comment]
is there any update ? 😭

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
