### ISSUE TITLE
promptTextCreator causes weird behaviour if the exact value is returned

### ISSUE THREAD

**Issue by andyhmltn** [JedWatson/react-select#1274]
##  Use Case

We came across this bug when trying to use `react-select` as a normal textbox with prefilled suggestions underneath for number formatting. So if you typed `123` the options `123k, 123M & 123B` would appear. In this use case, having 'Create option "x"' display felt weird so we opted for just returning the exact value using `promptTextCreator` instead, like so: `promptTextCreator={ (value) => value }`
## Problem

As you can see here:

https://plnkr.co/edit/cCNZlY2wHPSuZ7F4hNSQ?p=preview

React select behaves weirdly when creating new options. It requires two enters / two clicks to create a single option and fire the onChange event. The initial enter / click does not fire the onChange event and it appears like nothing is happening. My guess would be that something weird is happening with the step that's stripping out the create text before passing it off to the `onChange` but I'm not familiar with the source so I could be wrong.

Bonus points: It would be nice to hide the first option on `Creatable` for this use case 😄

**Comment by Firfi** [comment]
I can reproduce this issue with the latest react-select. I used "promptTextCreator={(label) => `${label} `}" as a weird workaround

**Comment by lorenzos** [comment]
+1!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
