### ISSUE TITLE
Remove selected value from options list

### ISSUE THREAD

**Issue by stinoga** [JedWatson/react-select#1276]
I have an option I'd like to hide from the dropdown menu when selected. Is there a way to do that? I tried removing it from the options when selected, but then it doesn't show as the selected value.

**Comment by medv** [comment]
The item gets a class, so you can hide through css. Or you can supply the select react component with a custom option renderer which gets passed an argument of the selected value(s). You can check against that and return null. Just a theory.

**Comment by gareys** [comment]
`.Select-option.is-selected {
  display: none;
}`

**Comment by geminiyellow** [comment]
@gareys 

yep, i want same options in multi dropdown, the css can only hide in one.
emoving it from the array of options is the "correct" way.

**Comment by marianzburlea** [comment]
Same issue here. can't control the "Select-option" div.

**Comment by marianzburlea** [comment]
Just found a solution that works, I've added to the option object a className property like:
```{
label: 'my option',
value: '2',
className: 'hide'
}```
and in css I have:
```/* this hides the value in the drop down list options /
.hide {
display: none;
}
/ This shows the selected value */
.Select-value.hide {
display: inherit !important;
}```

**Comment by hovissimo** [comment]
Just use `.Select-option.is-selected { display: none; }` ?

Works great for me

**Comment by l3v1k** [comment]
Found `hideSelectedOptions` prop, thinks this issue should be closed. ⭐️
@stinoga @JedWatson

**Comment by askshinde** [comment]
> 
> 
> Found `hideSelectedOptions` prop, thinks this issue should be closed. star
> @stinoga @JedWatson

It hides form option but still shows in the search field as selected option

**Comment by bladey** [comment]
Hi all -

Thanks for your solutions to this issue.

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by Moment-timezonevise** [comment]
I uncovered the answer https://sentimentaldmitri.github.io/sLC4hveXMKDSJyT1ERQQ4B3eCHv3iMYNuvmn5vsHP3t8bD4ohSZi3xfafx/
