### ISSUE TITLE
Add maxlength prop to AsyncCreatable

### ISSUE THREAD

**Issue by stinoga** [JedWatson/react-select#1280]
It would be nice to be able to set a maxlength on the combobox input through a prop so we can limit the length on tag creation if needed.

**Comment by AlinCiocan** [comment]
What happened to this issue? Any updates?

**Comment by cal0610** [comment]
This feature would be very useful.

**Comment by cal0610** [comment]
Just some quick look into the source code, found that you can actually pass inputProps to the component...

e.g.
<Select
       inputProps={{ maxLength: 5 }}
        {...this.props}
   />

**Comment by krnlde** [comment]
@cal0610 doesn't work for me, also it is not documented in @types/react-select

**Comment by tmeisenh** [comment]
You can provide a custom Input to the Select's component props that has a maxLength set.

**Comment by mponizil** [comment]
@tmeisenh what if `maxLength` needs to be parameterized as well? Surely we don't want to define `MaxLengthInput` on every render...

```
const MyFieldWithMaxLength = (props) => {
  const MaxLengthInput = (inputProps) => <components.Input maxLength={props.inputMaxLength} {...inputProps} />
  return <Select components={{ Input: MaxLengthInput }} />
}
```

**Comment by ruben0626** [comment]
Why did we close this one?

**Comment by ebonow** [comment]
A working solution to this is writing a custom Input component and leveraging selectProps.

``` JS
const Input = props => {
  const { maxLength } = props.selectProps;
  return <components.Input {{...props }} maxLength={maxLength} />
}

const MySelect = props => <Select components={{Input}} maxLength={props.maxLength} ... />
```

**Comment by ajinbramantio** [comment]
how to use maxlength in AsyncPaginate ?

**Comment by krnlde** [comment]
Since we are already asking completely unrelated questions in closed issues: How much sugar do I need for pancakes?

**Comment by ebonow** [comment]
@ajinbramantio did you even try the solution posted?
