### ISSUE TITLE
Firefox displays items in two rows

### ISSUE THREAD

**Issue by heaks** [JedWatson/react-select#1287]
Firefox shows items like this
![screen shot 2016-10-07 at 5 01 47 pm](https://cloud.githubusercontent.com/assets/17325467/19192772/05ef51bc-8cb0-11e6-983f-d8df79f07aef.png)
And Google Chrome shows them in one row
![screen shot 2016-10-07 at 5 01 58 pm](https://cloud.githubusercontent.com/assets/17325467/19192803/21f7c1a0-8cb0-11e6-90a2-edb18c835d24.png)
As we can see "Cookies and cream" has 2 rows. Can it be fixed somehow ?

**Comment by MilllerTime** [comment]
Looks like this was already reported, with an explanation of why the wrapping happens: https://github.com/JedWatson/react-select/issues/1272

**Comment by rafaelquintanilha** [comment]
Adding the following to `dist/react-select.css` did the trick for me.

```
span.Select-value-label {
  white-space: nowrap;
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
