### ISSUE TITLE
Cursor to enter new option unexpectedly jumps onto new line

### ISSUE THREAD

**Issue by fzoozai** [JedWatson/react-select#1296]
![new_option_error](https://cloud.githubusercontent.com/assets/10197484/19266320/50f88baa-8fa9-11e6-86c9-cb8f28297e52.png)

My code snippet for the <Creatable /> component is like that:

``` jsx
<Creatable
  autosize={false}
  backspaceRemoves={false}
  options={optionsArr}
  onChange={(newValue) => {
    console.log('newValue', newValue);
    this.setState({
      recipe: update(this.state.recipe, { medicine: { $set: [...newValue] } }),
    });
  }}
  multi
  placeholder="Welche Medikamente möchten Sie anfordern?"
  clearAllText="zurücksetzen"
  value={this.state.recipe.medicine}
  matchPos="start"
/>
```

**Comment by MarkLeMerise** [comment]
Which browser and version are you using to visit [the demo site](http://jedwatson.github.io/react-select/)? The issue you are seeing could be related to that. I am running Chrome 53 (macOS Sierra) and don't see this behavior.

**Comment by fzoozai** [comment]
Thx for your response. In my case its not working out in any browser including the latest chrome version. I think need to add a flag or something like that. I am still trying to find a solution.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
