### ISSUE TITLE
Server Side Rendering Issue

### ISSUE THREAD

**Issue by rahul-ofb** [JedWatson/react-select#1297]
Hi, 

I'm getting this error :

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) ole="combobox" aria-expanded="false" ari
>  (server) ole="combobox" aria-activedescendant="re

Even though I'm using instanceId.

**Comment by artf** [comment]
Same here but slightly different

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
(client) eactid="138"\>\<input role="combobox" aria
(server) eactid="138"><input aria-expanded="false

On '1.0.0-rc.2', with 'instanceId'. The problem disappears only when the input is disabled

**Comment by hoangzinh** [comment]
Any update on this PR?, I have same issue with it :(

**Comment by fiatjaf** [comment]
Same here, but slightly different.

**Comment by idangozlan** [comment]
+1

**Comment by bertho-zero** [comment]
You can add an `instanceId` props.

**Comment by Andriy-Kulak** [comment]
Same comment as above.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
