### ISSUE TITLE
Select (chrome) -> deleting elements does not update height

### ISSUE THREAD

**Issue by Dammic** [JedWatson/react-select#1301]
Hello!

I would like to point an issue I had using your library, I'm using Google Chrome (54.0.2840.59 m), which seems to be a crucial piece of information (as this issue does not exist on Firefox). When I select multiple elements inside Select in the way that the elements render in multiple lines and then delete any of those selected, the Select does not change it's height. Only deleting all of the elements changes it's height.

Here is a screenshot to demonstrate the issue. I've shown it on the example application available in your project, but the same issue is present in the newest version downloaded directly from github:
https://postimg.org/image/pq03k7uob/

Thanks in advance for your time!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
