### ISSUE TITLE
Is it possible to retain text in InputBox after a value is selected in multi select dropdown? 

### ISSUE THREAD

**Issue by ronaksvyas** [JedWatson/react-select#1302]
I have a huge multiselect list in which if a user selects one item after typing "Ac"(say), the text "Ac" from the inputbox is lost. The user will again have to type the same text("Ac" in this case) to select something which matches the pattern. I don't know if this is a popular use case but is it possible to retain text after selection in multi select?

**Comment by ronaksvyas** [comment]
I commented the following line: https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L664

It seems to work in my case. Is there any more obvious way to do it? Will this change affect the functionality of multiselect in any way?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
