### ISSUE TITLE
Add infinite scroll for async loading

### ISSUE THREAD

**Issue by juliensnz** [JedWatson/react-select#1303]
Hello everyone,

This lib is really awesome and a really good replacement/alternative to select2. However there is one missing feature that I really need: infinite scroll for async loading.

So I would like help and implement it and propose a PR. Before doing so, I would like to know if this idea is OK for you and if you are open to contributions for this kind of features.

Without getting in a lot of details, the idea is to add a scroll detection on the dropdown element and detect if you are at the end of the list. If it's the case, the `loadOptions` will be triggered with a  new `page` argument. The results will be append to the result list infinitely.
We could handle the last page (and avoid unnecessary loading) if the server returns an empty response or give the ability to the developper to handle it.

What do you guys think?

**Comment by TheSharpieOne** [comment]
Have you seen #1237?

**Comment by nafg** [comment]
There's https://github.com/vtaits/react-select-async-paginate

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
