### ISSUE TITLE
Minimize dist size

### ISSUE THREAD

**Issue by mbrevda** [JedWatson/react-select#1304]
Currently, it seems react-select includes all its options in the dist build. This means that even if a given component isn't being used, like Async, it will nevertheless be included and the build will be ~46k. How can this be minimized?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
