### ISSUE TITLE
How to disable and enable the select where used in multiple places

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#1307]
This is my Code 
In render I will do  like this.
DATA wil be lik tat 

"passes1": [{
        "passNo": "one ",
        "expiryDate": "10-OCT-16"
    }, {
        "passNo": "two",
        "expiryDate": "10-OCT-16"
    }, {
        "passNo": "three",
        "expiryDate": "10-OCT-16"
    }],

```
   newOption = passes1.map(function(passes,i ){
            return {key :{i} ,label: passes.passNo +","+ passes.expiryDate, value: passes.passNo +","+ passes.expiryDate}
        });
```

<Select disabled={true} placeholder="Please Select Complimentary Passes" searchable={this.state.searchable}  ref="stateSelect" autofocus options={this.state.option} className="democlass" name="selected-state"  value={this.state.selectValue} onChange={this.updateValue} clearable={this.state.clearable} noResultsText="AllCompilmentaryPassesAlready" /> 

I attach the Screen Shot for you reference

**Comment by lakshmanpraakash** [comment]
![react-select enable and disable](https://cloud.githubusercontent.com/assets/22720009/19410656/1daa135e-930f-11e6-9fab-e3869477b6d4.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
