### ISSUE TITLE
Text highlighting from the end of the string doesn't work

### ISSUE THREAD

**Issue by simondiep** [JedWatson/react-select#1312]
When looking at the react-select demo site today, I tried to highlight some text I had entered and couldn't.

I typed in 'abcdefg', and clicked after the 'g' and dragged left until the a.

I noticed it didn't highlight any of the characters.

When I tried again, this time from the 'a' to the 'g', it worked.

This also worked, if I click on the 'f' and drag to the 'a'.

This applied for all nine of the fields on the demo site.

**Comment by kevinhaas** [comment]
Still an issue. If you're right on the last letter, you can manage to highlight right to left. If you're even a pixel past the last letter, you can't drag left at all.

Seems like the actual input for the text is only the width of the text? I haven't looked too closely.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
