### ISSUE TITLE
Feature request: close icon on the right

### ISSUE THREAD

**Issue by mbonaci** [JedWatson/react-select#1313]
Hi,
you did an awesome job with this project, thx for sharing :)
Would it be possible to do a small change that would allow specifying token's close icon position via props (where one would be able to specify non-default value `right` for prop named something like `closeIconPosition`).
It would look like this (I just switched positions of `renderRemoveIcon()` and `renderLabel()` in `Value.js` and moved the icon's border from right to left):
![image](https://cloud.githubusercontent.com/assets/497926/19456601/87e293e0-94c2-11e6-896b-66c5eb3a1ef0.png)
I know it's possible to "override" token with my own component, but this seems like an overkill and I would guess others would find this useful, esp. given that earlier, jQuery UI plugins' versions of these tokens, AFAICR all had close icon on the right :)
Thanks for looking into this.

**Comment by otisg** [comment]
+1, I think this is a much more common "layout".  For example, I was just writing a blog post in WordPress today and noticed "x" for their tags input is to the right of the tag value.

**Comment by kyleknighted** [comment]
This can be quickly achieved just using CSS.

```css
    .Select-value-icon {
      border: 0;
      float: right;
    }
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
