### ISSUE TITLE
Add option to prevent cycling through options items when using keyboard navigation.

### ISSUE THREAD

**Issue by mbebenita** [JedWatson/react-select#1314]
The current behavior moves the `focusedIndex` to `0` when navigating past the last option in the list. While this may be nice in some situations, it would be nice to optionally prevent cycling through option items and simply stop when reaching the end of the list.

P.S. Great project!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
