### ISSUE TITLE
Add more maintainers

### ISSUE THREAD

**Issue by hakunin** [JedWatson/react-select#1315]
Hey guys,
by the number of pull requests and the history of some enhancements that are taking a long time to land (optgroups is one), I suggest adding more maintainers to this repo.

It looks like tons of people are using this package already so it would be nice if all wasn't on a shoulders of one (although great) guy.

Maybe someone from a big company, like Hubspot (which recently made a public fork so people can have optgroups) could be a maintainer?

**Comment by jooj123** [comment]
Myself and others @ domain are also happy to help where we can - we are heavy users of react select

**Comment by MarkLeMerise** [comment]
I completely agree with the sentiments expressed in this issue, but I think a good way to contribute for now would be to [open the other issues and start helping people](https://twitter.com/dan_abramov/status/792495771807518720).

**Comment by tnrich** [comment]
@JedWatson, thanks very much for creating this excellent tool. I'm using it in multiple places within my app. 

However it appears to be suffering from lack of attention:  for example there are two separate PRs to add an "alwaysOpen" prop to the component, neither of which has been merged. 
https://github.com/JedWatson/react-select/pull/1015
https://github.com/JedWatson/react-select/pull/817

This tool is being used by many people so, please either add more maintainers to this repo or start responding to people's PRs. 

Thanks,
Thomas

**Comment by silvenon** [comment]
Hey guys, I'm starting a fork of react-select, the goal is to eventually take over the project. I'll probably post my updates in #1403.

**Comment by MarkLeMerise** [comment]
@silvernon, that seems like the direction this needs to go, but have you reached out to @JedWatson via email or social media about it? Either way, I'm happy to help if we need contributors to get this project thriving again.

**Comment by silvenon** [comment]
Good idea. I'll try [tweeting](https://twitter.com/silvenon/status/812436794985893888) him first.

**Comment by JedWatson** [comment]
Consolidating this to #1481
