### ISSUE TITLE
Unable to select text in the input box

### ISSUE THREAD

**Issue by freeranger** [JedWatson/react-select#1317]
I want to be able to select all the entered text by default when the input gets the focus (and be able to change which bit is selected once I have the focus - left-mouse drag) but neither seem to work.
I have an onFocus method:

``` javascript
onFocus={(event) => {
                    console.log('Focus');
                      var target = event.target;
                      setTimeout(function() {
                          target.select();
                       }, 0);
                    }}
```

but it doesn't do the job - it is called (I get the log message) but the text does not get selected, and nor can I use the mouse (or keyboard) to select the text in the box.
Use of the timeout is because various people report this doesn't work in general with Chrome without a tiny delay but I have tried without the timeout element and still no joy :/

If you want to see the problem in action, on your demo pages, it is not possible to select the text in the input box either....

**Comment by praveenkumargjll** [comment]
Hi,
Same for me.. Is this can be fixed

**Comment by Rall3n** [comment]
The `input` element that is being focused does not have the text that is shown when you focus the component. There is another element behind the actual `input` element which has the current values `label` as text.

To access it, you have to use a `ref` on the `Select` component and get the element which does have the text from its internal refs to elements.

```jsx
onFocus = (e) => {
    const selectInstance = this.selectRef.current.select;
    if (!selectInstance.hasValue()) return; // No value, nothing to select.

    var textElem = selectInstance.controlRef.querySelector("[class*=singleValue]"); // Element which has the text.

    // Following code is from https://stackoverflow.com/a/4183448/6612182
    if (window.getSelection && document.createRange) {
        // Every browser
        var sel = window.getSelection();
        var range = document.createRange();
        range.selectNodeContents(textElem);
        sel.removeAllRanges();
        sel.addRange(range);
    } else if (document.selection && document.body.createTextRange) {
        // Microsoft
        var textRange = document.body.createTextRange();
        textRange.moveToElementText(textElem);
        textRange.select();
    }
}
```
[CodeSandbox example](https://codesandbox.io/embed/react-codesandboxer-example-bvqb6)

**Comment by bladey** [comment]
Hello -

Thanks for your assistance @Rall3n and @zeevl!

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by jim-alexander** [comment]
I made the actual input `position: relative` and that worked for me because It made the input fill the width of the parent (which was the root issue)

```typescript
const styles = (): StylesConfig => ({
    // This is just the div wrapper:
    input: (initialStyle) => ({
      ...initialStyle,
      input: {
        position: 'absolute',
      },
    }),
  })
```
