### ISSUE TITLE
Clear removes even values that have clearableValue:false

### ISSUE THREAD

**Issue by Seldaek** [JedWatson/react-select#1318]
`Select::getResetValue()` returns `[]` for multiselects which is generally fine but when you have values that do not allow clearing I think they should not be cleared by the clear button.

I worked around it by providing my non-clearable values as `resetValue={...}` but still thought I'd report it.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
