### ISSUE TITLE
Escaping out of Creatable leaves value to be created on blur/tab

### ISSUE THREAD

**Issue by davelnewton** [JedWatson/react-select#1320]
When using `<Creatable />` if I:
- Type in a tag that doesn't exist (e.g., create a new tag) then...
- ... hit escape (e.g., "Never mind, don't want this",
- ... the new tag disappears from the input **BUT**
- ... when I `TAB` away from the input it gets created anyway

I have not investigated why this happens yet, but will. IMO this is confusing UX since there's no active input field: I don't expect anything to be created if I escaped then go away from the field.

I'm currently working around this via `shouldKeyDownEventCreateNewOption` (removing `TAB`).

**Comment by jsnmoon** [comment]
Hi Dave,

This behavior occurs due to [this line](https://github.com/JedWatson/react-select/blob/da2f22237b07c812980ad3c79607e93071d68350/src/Creatable.js#L267-L276). Indeed, using tab to indicate option creation does seem confusing.

Jason

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
