### ISSUE TITLE
on iOS it doesn't scroll to the Select element if touched it's in the bottom of the page

### ISSUE THREAD

**Issue by aboutlo** [JedWatson/react-select#1321]
I know focus and ios mean nightmare. By the way, that's the use case:
1- Open the demo page http://jedwatson.github.io/react-select/
2- You get ![img_1822](https://cloud.githubusercontent.com/assets/1236268/19625624/68db8c52-9915-11e6-81d7-f38fc5458ede.PNG)
3- Select the State input
4- The focus doesn't scroll to the input
![img_1823](https://cloud.githubusercontent.com/assets/1236268/19625623/68d5c8a8-9915-11e6-879c-6785b01b6bcc.PNG)

I managed with an ugly workaround: 

in React

```
...
onClick () {
    this.refs.providerSelect.focus()
  }
...

<div className="Select-wrapper" >
        <Select ref="providerSelect"
          name="provider"
          options={[{label:'bla bla', value: 1}]}
          autoBlur={true}
          placeholder="Type to search"
        />
        <button onClick={onClick} >Select...</button>
</div>

```

in CSS

```
/* iOS workaround to focus properly the Select */
.Select-wrapper {
  position: relative;

  button {
    position: absolute;
    top: 0;
    right: 0;
    width: 100%;
    height: 100%;
    opacity: 0;
  }
}
```

Is something should be managed here https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L368 ?

**Comment by ImmoStanke** [comment]
In case anyone else has this issue, 
`onFocus={()=>{document.activeElement.scrollIntoView()}}`
worked for us. But YMMV based on what devices/versions exactly you need to support.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by mleister97** [comment]
This is acutually still an issue. The hotfox on @ImmoStanke works. Thanks.
