### ISSUE TITLE
Custom Click on an option when using 'optionRenderer' function

### ISSUE THREAD

**Issue by rahul2tiw** [JedWatson/react-select#1323]
I am using the optionRenderer function , and have some button in an option in a dropdown and wants a click event on the same.

Snapshot of Code:

`abc = (evt, option) => {
    console.log(option, 'This is clicked')
  }`

 `func1 = (a) => {
    return (<div>{a.name} <div onClick={(event) => this.abc(event, a)}> Edit Button</div></div>)
  }`

 `renderAsyncSelect = () => {
    const { clearable, labelProperty, multi, onValueClick,
      placeholder, searchable, valueProperty, className } = this.props
    const { value } = this.state`

```
return (
  <div>
    <Select.Async
      autoBlur={true}
      autoLoad={true}
      autoSize={false}
      backspaceRemoves={false}
      className={className}
      clearValueText=""
      clearable={clearable}
      labelKey={labelProperty}
      loadOptions={this.autoSuggest}
      matchProp={labelProperty}
      multi={multi}
      onChange={this.handleOnChange}
      onValueClick={onValueClick}
      placeholder={placeholder}
      searchable={searchable}
      value={value}
      valueKey={valueProperty}
      optionRenderer={this.func1}
    />
  </div>
)
```

Here in code, func1 is responsible for rendering the options and I have tried to bind a click Event on a Edit button with every option but the function 'abc' do not fire. Can anyone help me out to achieve this?

**Comment by ahgz7** [comment]
+1

**Comment by sahiljain112** [comment]
+1. Facing the exact same problem.

**Comment by agirton** [comment]
Hi @rahul2tiw if you need to add an onClick it would be better to use a custom optionComponent. optionRenderer is only meant for display.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
