### ISSUE TITLE
Combobox input width not updating until key-up even in IE 11

### ISSUE THREAD

**Issue by ssshake** [JedWatson/react-select#1326]
I have no idea why but it appears that in IE11 the combobox is resizing only on key up events, which causes this jank in this gif. 

![fnuwlbskrx](https://cloud.githubusercontent.com/assets/1675868/19698717/6f70d964-9abe-11e6-8d31-1d559f21b1dd.gif)

In all other browsers it seems certain that it resizes on keydown even. I have no idea why.

**Comment by mauretanec** [comment]
**@ssshake**: I have been able to get rid of this IE11 quirk by setting following styles:

`.Select-input { width: 100%; }`
`.Select-input > input { min-width: 100%; }`

If you do not want to have it throw whole line then just wrap it in container with specific width. We use Bootstrap so we just put it in DIV with certain Bootstrap class like `col-lg-4`.

**Comment by humphries40** [comment]
@mauretanec Thanks for that answer! Was running into this today and wasn't looking forward to the CSS troubleshooting.

**Comment by ssshake** [comment]
thanks

**Comment by mahlero** [comment]
@mauretanec Thanks for your fix. As of now, there is another DIV wrapped around `.Select-input`. To make things work, I had to add an additional style: 
`
.Select-value-container > :last-child { width: 100% }
`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
