### ISSUE TITLE
Typed text does not show up in input section

### ISSUE THREAD

**Issue by StokeMasterJack** [JedWatson/react-select#1328]
Had the following code and everything worked perfectly:    

```
render() {
        return (
            <div>
                <Select.Async value={this.state.value} onChange={this.onChange}
                              loadOptions={this.getOptions}
                />
            </div>
        );
}
```

Then I added a web component and suddenly React-select started rendering incorrectly. No text would show up in the input box.

```
render() {
        return (
            <div>
                <link rel="import" href="/components/paper-button/paper-button.html"/>
                <paper-button/>
                <Select.Async value={this.state.value} onChange={this.onChange}
                              loadOptions={this.getOptions}
                />
            </div>
        );
}
```

It took me hours to isolate the problem. I finally figured out that if I moved the link tag out of the React component and into the head section of my html then it works. But, other than React-select, I have been using this technique (import a web component from within a React component) just fine.

Not sure if this is a problem with polymer or with react-select. 

I tried to create a plunk but I couldn't get polymer to load correctly from a CDN.

One other things to note: It didn't really matter which web component I was importing.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
