### ISSUE TITLE
Using with Formsy

### ISSUE THREAD

**Issue by janmyler** [JedWatson/react-select#133]
Hi, I am using [Formsy](https://github.com/christianalfoni/formsy-react) to implement forms with validations. I have a set of form components – they all implement custom behavior I need, but use some other implementations under the hood (Material-UI components, React Select, etc.). 

I have an owner component implementing connection with Formsy form component, however, anytime this owner component re-renders (when its state is changed), the selected value does not get rendered in Select and I am not exactly sure why.

When I disable updates of the owner component, the Select component seems to work just fine, but then I cannot really show validation errors and other things in my wrapper component.

Any ideas what might be the cause of it?

**Comment by yale** [comment]
:+1: , I am having this same issue with formsy.

**Comment by keeth** [comment]
I was able to make Select work with Formsy without too much trouble, here's what I did, in case it helps...

https://gist.github.com/keeth/1870a553055b008cee99

It expects options like 

    var options = [
      { value: 'one', label: 'One' },
      { value: 'two', label: 'Two' }
    ];

I have not dug into the validation side of it, but the state updates seem to work.. what does your onChange handler look like?  Getting that right seems like the most important thing to me.

**Comment by yale** [comment]
Thank you @keeth, I will try this out soon!

**Comment by janmyler** [comment]
Thanks a lot @keeth! I gave it a quick try and it seems to work for me also. If I remember right, the mistake I did was using `value` instead of `selectedOptions` in the `onChange` handler.

**Comment by dcousens** [comment]
Thanks @keeth,  going to close this.  Let me know if it needs to stay open.
