### ISSUE TITLE
No more focus() method on Select.Async?

### ISSUE THREAD

**Issue by mcls** [JedWatson/react-select#1330]
Hi, 

There used to be a focus method on Select.Async, but it was removed here: https://github.com/JedWatson/react-select/commit/ed8d087d4d5d1c46b0b1f7a11c71eb3949be5dd1#commitcomment-19591843

I was wondering if I can add it again, or whether it was consciously removed?

The reason is that I'm focussing a `Select.Async` element when the props change (not just when mounting, as with autofocus).

Thanks

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
