### ISSUE TITLE
event.stopPropagation() on keydown (i.e. Esc key) should check for existing value

### ISSUE THREAD

**Issue by antitoxic** [JedWatson/react-select#1335]
I'm hitting a problem where all my `Esc` key presses are captured by `react-select`.

Judging by:

``` js
case 27:
    // escape
    if (this.state.isOpen) {
        this.closeMenu();
        event.stopPropagation();
    } else if (this.props.clearable && this.props.escapeClearsValue) {
        this.clearValue(event);
        event.stopPropagation();
    }
    break;
```

If I have a clearable select and I want to clear it with `escapeClearsValue` , then there is no way to capture Esc key presses in ancestors. 

`react-select` should check if there is a value to be cleared and if not it shouldn't stop the event propagation.

**Comment by antitoxic** [comment]
Further more, `clearValue()` also stops propagation.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
