### ISSUE TITLE
AsyncCreatable Created option return className

### ISSUE THREAD

**Issue by msaglietto** [JedWatson/react-select#1338]
Hello ... 

Im using AsyncCreatable on a project and I found out that when you create a new option it returns a object  like 
`Object {value: "new", label: "new", className: "Select-create-option-placeholder"}`

Here is the example that returns the selected option to the console 
http://www.webpackbin.com/4y5MMilgz

Version 1.0.0-rc.2

**Comment by alexjesp** [comment]
Comes from this line https://github.com/JedWatson/react-select/blame/master/src/Creatable.js#L259

**Comment by cal0610** [comment]
How do you get it not to return the className as this is part of object I want to send to the back end. 

I could use lodash to omit it but would prefer to do it cleaner.

Thanks

**Comment by kkseven07** [comment]
any solutions? Wtf why is there a classname??

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
