### ISSUE TITLE
Please update selectValue to pass event to onChange

### ISSUE THREAD

**Issue by reharik** [JedWatson/react-select#1339]
I need the event to be passed to my custom onChange eventhandler, this is how I can distinguish one select from an other.  Currently, I get the selected option ( label, value ) but I have no way of knowing which element triggered the event, because my onChange is abstracted and used by several (all) components.

It seems that if you just include the argument "event" in the selectValue signiture ( and then pass it to setValue ) that would be all you need.

src/Option.js ln 31 handleMouseDown(event)  calls this.props.onSelect and passes options and the event.  
this.props.onSelect maps to src/Select ln 589 selectValue(value).  If you would just change that to selectValue(value, event) I should be good to go.

Thanks you,

R

**Comment by reharik** [comment]
actually crap, I don't know what that object is, but it's not an event. I don't think.  Not sure why, but it doesn't have target or anything like that on there, so I don't know if there is a fix for my situation.

**Comment by KidsOnShred** [comment]
I'm having the same issue. I'm dynamically adding <Selects /> to a list and need the event to distinguish them. Any plans to update this?

**Comment by mmkari** [comment]
Same here. Writing a higher order component for form management requires that the callback functions it provides can distinguish between the different form elements by name and store the values in proper sections of the container's state. This is also necessary for the parent component to pass values down to the correct select-element and be able to control it.

**Comment by drifteaur** [comment]
I managed to solve it by passing my element's ID  like this, but passing the event as a second argument would be nicer.

	let component = this;

	<Select
	    value={ ... }
	    options={ ... }
	    onChange={function(value) {
	        component.logChange(someUniqueKey, value);
	    }}
	/>

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
