### ISSUE TITLE
is-selected class is not set when option selected

### ISSUE THREAD

**Issue by tecnoloco** [JedWatson/react-select#1340]
In the example bellow the class "is-selected" is not set when option is selected. 
I am using versions:
react ^15.0.0
react-select@1.0.0-rc.2
classnames@2.2.5

`
import React, {Component} from 'react';
import Select from 'react-select';
class Select2Dropdown extends Component {

    constructor(){
        super();
        this.state={

        }
    }

    render(){
        const {
                input,
                disabled,
                required,
                label,
                placeholder,
                dataOptions,
                onSelect,
                select2Config,
                dataLabelProperty,
                meta:{touched, error, dirty}
            } = this.props;

        let options = [
            { value: 'one', label: 'One' },
            { value: 'two', label: 'Two' }
        ];
        const onChange =(val)=>{
            this.setState({value: val})
        }
        const onOpen =()=>{
            
        }

        return(
            <div className={'form-group ' +((disabled)? 'form-group-disabled': '')}>
                <label className="form-group-label">{label} {(required)?<span>*</span>:''}</label>
                <Select
                    {...select2Config}
                    options={options}
                    value={this.state.value}
                    className={'Select-form-control ' + ((error && touched && !disabled)? 'from-control-error': '')}
                    onOpen={onOpen}
                    onChange={onChange}
                    />
                {touched && error && !disabled && <div className="form-group-error-container">{error}</div>}
            </div>
        );
    }

};

export default Select2Dropdown;
`

**Comment by glortho** [comment]
In case anyone else has this issue a likely problem is that the `value` you're passing in is not a reference to the same options object in the array of options.

See here https://github.com/JedWatson/react-select/blob/916ab0e62fc7394be8e24f22251c399a68de8b1c/src/utils/defaultMenuRenderer.js#L21

This is checking basic referential equivalence, so the value object must be a reference to an object in the options array. I think it'd be better to match something like `selectedOption.value` against `option.value` (as is being attempted here https://github.com/JedWatson/react-select/blob/ef3a4687bc67684809c3a2648143a1c325ee987e/src/Select.js#L584 ). In the meantime, if you must maintain a different object as your `value`, just find the equivalent object in your `options` array and pass that down instead. Something like this:

```
const myValue = { label: 'foo', value: 'bar' };
const selectedOption = myOptionsArray.find( option => option.value === myValue.value );

<ReactSelect options={ options } value={ selectedOption } />
```

**Comment by tproenca** [comment]
```
const myValue = { label: 'foo', value: 'bar' };
const selectedOption = myOptionsArray.find( option => option.value === myValue.value )

<ReactSelect options={ myOptionsArray } value={ selectedOption } />
```
That didn't work for me. It doesn't even show the select item in input text field.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
