### ISSUE TITLE
isValidNewOption should run onChange of the Creatable input, not on render (?)

### ISSUE THREAD

**Issue by Paul-Hess** [JedWatson/react-select#1345]
<Select.Creatable
    {...otherProps}
    isValidNewOption={({ label }) => isValidEmail(label)}
    noResultsText='validating'
    />
I think the isValidNewOption should not run directly on render, I would like to validate onChange of what is the value of the Creatable input and set an error state if invalid and the user has not entered anything new in the input after a set amount of time. As is the noResultsText just hangs there or if I try to set Error state, well I cannot as the validation method runs even when the text input is not focused. 
Thoughts? 
Thanks for making this really useful component.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
