### ISSUE TITLE
Standalone - classes is not a function

### ISSUE THREAD

**Issue by Maxim-Filimonov** [JedWatson/react-select#135]
When i try to look at example of using the component without bundling via browserify or webpack I get the following errors on the latest master(https://github.com/JedWatson/react-select/commit/3ceff3698675a597ac0537291ed143ce3cb9e24e):
`classes is not a function`
I'm getting the same error when I try to use `dist/react-select.js` in my project

**Comment by mariochavez** [comment]
Did you find a workaround for this?

**Comment by Maxim-Filimonov** [comment]
i did hjack the component and created webpack distribution instead of using browserify. Not sure it's necessary i'm just more familiar with webpack. I can share it later today

**Comment by aleemb** [comment]
+1 the distributable appears to be broken

**Comment by dcousens** [comment]
Is this still the case?

**Comment by aleemb** [comment]
Actually this was my fault, I didn't realise `classNames` library is a dependency that needs to be included manually without which it is [unable to resolve](https://github.com/JedWatson/react-select/blob/25c77bdb0e87395b3b0dddba5bd9beafe3177c9c/dist/react-select.js#L9) the var.

**Comment by streamride** [comment]
repeated that bug using npm install

**Comment by aldanor** [comment]
So what is the proper way to do this?

**Comment by aleemb** [comment]
@aldanor install via NPM or if you're using the `js` directly then include download and include the dependencies:

* https://github.com/JedWatson/classnames/releases
* https://github.com/JedWatson/react-input-autosize/releases

**Comment by aldanor** [comment]
Weird, it's able to pick up `react-input-autosize` automatically from npm but not `classnames`, will double check.
