### ISSUE TITLE
react-select when the value not in option list issue

### ISSUE THREAD

**Issue by songliling** [JedWatson/react-select#1356]
I have some problem when I use react-select

description:
when the value not in option list , it is not display in the input ，I want to it display still;

need some help   thx;

**Comment by 1ron** [comment]
allowCreate=true?

**Comment by bfaure** [comment]
ur a bum

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
