### ISSUE TITLE
Simulate 'change' doesn't work for select

### ISSUE THREAD

**Issue by nbotalov** [JedWatson/react-select#1357]
Hi, i'm adding tests to my pagination component based on Select

PageSizeSelector.js
```
class PageSizeSelector extends PureComponent {
    ..
    render() {
        const {pageSize} = this.props;
        return <Select
            options={this.pageSizeOptions}
            value={pageSize}
            onChange={(option) => this.pageSizeChangeFunc(option.value)()}
            clearable={false}
        />
    }
}
```

PageSizeSelector.test.js
```
import {mount} from 'enzyme'
...
it('changing pageSize', () => {
        let size = 0;
        const onPageSizeChanged = (pageSize) => size = pageSize;

        const wrapper = mount(
            <PageSizeSelector
                pageSize={10}
                onPageSizeChanged={onPageSizeChanged}
            />
        );

        wrapper.find('Select').simulate('change', {target: {value: 50}});
        expect(size).to.eql(50);
    })
```
onPageSizeChanged isn't called.
If replace simulate line with

```
   wrapper.find('Select').find('input').simulate('change', {target: {value: 50}});
```
get exception
```
- TypeError: str.replace is not a function
        at stripDiacritics (node_modules/react-select/lib/utils/stripDiacritics.js:7:13)
        at filterOptions (node_modules/react-select/lib/utils/defaultFilterOptions.js:13:50)
        at filterOptions (node_modules/react-select/lib/Select.js:992:11)
        at render (node_modules/react-select/lib/Select.js:1116:45)
        at node_modules/react/lib/ReactCompositeComponent.js:793:21
        at measureLifeCyclePerf (node_modules/react/lib/ReactCompositeComponent.js:74:12)
```

Using react-select@^1.0.0-rc.2
Looked at https://github.com/airbnb/enzyme/issues/400 as well
Thanks

**Comment by Cramsden** [comment]
+10000000000000000 🎱

**Comment by stephane-ruhlmann** [comment]
@nbotalov hey, went across the same problem... Only solution I found was to simulate a selection through key-down events:
```
wrapper.find('.Select-control').simulate('keyDown', { keyCode: 40 }); // you can use 'input' instead of '.Select-control'
wrapper.find('.Select-control').simulate('keyDown', { keyCode: 13 });
expect(size).to.eql('your first value in the list')
```

**Comment by keithkml** [comment]
See https://stackoverflow.com/questions/41991077/testing-react-select-component/46201546#46201546

**Comment by fqlx** [comment]
How has this not been fixed?

**Comment by qaiken** [comment]
I had to add the `classNamePrefix` prop to the `Select` component otherwise I didn't get any "control" classes to latch onto.

**Comment by sumanmaity112** [comment]
this [stackoverflow link](https://stackoverflow.com/questions/41991077/testing-react-select-component/46201546#46201546) shows how to simulate `keyDown` event. But if I do so, its not calling the `onChange` function.

**Comment by Rall3n** [comment]
The following should:
1. Find the `Select` component in your wrapper.
2. Get its instance.
3. Set the value to `{ label: "...", value: 50 }`

```js
wrapper.find('Select').instance().selectOption({ label: "...", value: 50 });
```
If you can you should use the original options from your `options` array for tests.

**Comment by ZeroDarkThirty** [comment]
@Rall3n Thanks! Your solution worked for me!

**Comment by otalandim** [comment]
@Rall3n your solution worked for me!

And case I want remove?
`wrapper.find('Select').instance().removeOption({ label: "...", value: 50 })`?

**Comment by soonoo** [comment]
It seems functions like `selectOptions` and `removeOptions` are in `wrapper.find('Select').instance().props`,  not in `wrapper.find('Select').instance()`

**Comment by soonoo** [comment]
> The following should:
> 
>     1. Find the `Select` component in your wrapper.
> 
>     2. Get its instance.
> 
>     3. Set the value to `{ label: "...", value: 50 }`
> 
> 
> ```js
> wrapper.find('Select').instance().selectOption({ label: "...", value: 50 });
> ```
> 
> If you can you should use the original options from your `options` array for tests.

It seems functions like `selectOptions` and `removeOptions` are in `wrapper.find('Select').instance().props`, not in `wrapper.find('Select').instance()`

**Comment by artdent** [comment]
The react-testing-library solution has been extracted into a helper package: https://github.com/romgain/react-select-event

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by Shhzdmrz** [comment]
Using react-select version 3.1.1 still its not working. Any plan to resolve this issue sooner?

**Comment by Shhzdmrz** [comment]
This works for me but there is some catch.

```js
const simulateSelectChange = (
    component: ReactWrapper<{}, {}, React.Component<{}, {}, any>>,
    selector: string,
    option: string,
    printLog: boolean = false
) => {
    component.find(`${selector} div.select__input input`).simulate('change', { target: { value: option } });
    if (printLog) {
        console.warn(component.find(`${selector} .select__menu`).debug());
    }

    component.find(`${selector} .select__menu div[children="${option}"]`).simulate('click');
}

//and call it like this

simulateSelectChange(component, '#select-component-id', 'selectOption'),
```

Issue in that:
1. To select an option you need to pass full option value to select the option.
1. you cannot simulate integer list unless you make it as string.
2. Simulate for Async Select will not work with this.

**Comment by memsenpai** [comment]
> It seems functions like selectOptions and removeOptions are in wrapper.find('Select').instance().props, not in wrapper.find('Select').instance()

Not sure, it related to result of `wrapper.find..`. you must find correct Select element.

**Comment by akhilgkrishnan** [comment]
> The following should:
> 
> 1. Find the `Select` component in your wrapper.
> 2. Get its instance.
> 3. Set the value to `{ label: "...", value: 50 }`
> 
> ```js
> wrapper.find('Select').instance().selectOption({ label: "...", value: 50 });
> ```
> 
> If you can you should use the original options from your `options` array for tests.

Not working

**Comment by InSuperposition** [comment]
This answer helped me, I was not mocking a button value (`react-select@3.1.1` ) for the `MouseEvent`.

https://stackoverflow.com/a/52977609/1402195

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
```js
 const toggleDropdownButton = wrapper
      .find(".my-select__indicator")
      .at(0)
      
  toggleDropdownButton.simulate('mouseDown', {
    button: 0 
  });
  ```

**Comment by stu01509** [comment]
It's working for me on mocha and enzyme , `reactSelect` is imported from 'react-select'

```js
wrapper.find(reactSelect).at(0).props().onChange({ value: 'Engadget' });
```
