### ISSUE TITLE
Feature: Use option.title in option menu

### ISSUE THREAD

**Issue by CliffChaney** [JedWatson/react-select#1359]
Excellent component! I'm just starting to use it. One small suggestion is an option to use the option.title in the option menu - instead of the option.label. Normally, I'd then format the option.title as something like "Label: description." Anyway, you have a feature to override the option renderer and I can play with that. So this obviously isn't critical. Cheers!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
