### ISSUE TITLE
multi select can't work when value is number.

### ISSUE THREAD

**Issue by adispring** [JedWatson/react-select#1361]

**Comment by apartyka** [comment]
Yes. I see this as well and was bummed to find it doesn't work.

```
var options = [
  {
    label: "some label"
    value: 18692
  },
]
```

The only potential workaround I can see is converting options.value(s) to strings, but that is messy...

**Comment by miguelsaddress** [comment]
I am having the same issue... I am trying to convert the value to a string, but not much success with it (AKA: Not working).... did you get to solve it?

**Comment by slavik-m** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
