### ISSUE TITLE
React-select overlaps following content in Chrome if selection updated in componentDidMount

### ISSUE THREAD

**Issue by akrikos** [JedWatson/react-select#1362]
Test case + fix: https://jsfiddle.net/8efz9gdy/4/

If I update the selected options in the `componentDidMount` lifecycle method with enough options to cause react-select to need another line for options, react-select sizes itself incorrectly in Chrome.

The `Select-control` element appears to be the correct size (2 lines) but the `Select` element is the original single line height.

**Comment by nbrochu** [comment]
+1

Was having the same issue in Chrome 55. Fixed worked. Thanks.

**Comment by radumardale** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
