### ISSUE TITLE
React-Select loadOption ls called every time when submitting a form with Redux-Form

### ISSUE THREAD

**Issue by ripitrust** [JedWatson/react-select#1369]
Hi 
I am using react-select inside a [redux-form](https://github.com/erikras/redux-form)

I notice that the loadOptions will be called (hence the http fetch) every time when the form is submitted.

This creates lots of network overhead, and also, if I redirect the page after submit,  react will complain that the component is unmount and can not setState

Not sure if this is react-select issue of redux-form issue

This happens even with cache option is on

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
