### ISSUE TITLE
Fixed header and footer on the dropdown menu

### ISSUE THREAD

**Issue by rdiazv** [JedWatson/react-select#1370]
I need to do two things on the menu:
1. Use a custom search input fixed on top of the menu.
2. Add a fixed button at the bottom of the menu.

Is there any way to do them? (I'm currently using 1.0.0-rc.2). If not, I can create a PR adding props `menuFooter` and `menuHeader`, or something like that.

**Comment by adamcai76** [comment]
Is `menuFooter` and `menuHeader` implemented?

**Comment by agirton** [comment]
Hi @rdiazv it sounds like you need to customize the `renderOuter`.  We currently don't support this, but I've heard more uses cases where people need to swap out the entire menu. Will look at this again after 1.0 final.

**Comment by kiranbabu189** [comment]
is the feature added?

**Comment by kyleholzinger** [comment]
I figured this issue may have been left behind, but this feature is now in v2 via the replaceable components API. I think this is good to close
