### ISSUE TITLE
Can we use google places?

### ISSUE THREAD

**Issue by SanskarSans** [JedWatson/react-select#1371]
Can we use google places api to show google places?

Thanks

**Comment by joshbedo** [comment]
I second this can't find a working library with the google geocoding api

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
