### ISSUE TITLE
Createable handleDelete?

### ISSUE THREAD

**Issue by RohanDamani** [JedWatson/react-select#1372]
There is no option to handleDelete when new items are created via the Creatable component.  When used with React-Redux, there is no way to dispatch an action to remove tags, or is there?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
