### ISSUE TITLE
Not showing all the options while scrolling down.

### ISSUE THREAD

**Issue by vijayst** [JedWatson/react-select#1377]
I have 10000 options in the select. All the options are not displayed when I scroll down the select.
https://plnkr.co/edit/5JfcsXXlZSj8sXOCQf4B

**Comment by Siignature** [comment]
Same issue. When setting a maxHeight, scroll doesn't display all options.

**Comment by bladey** [comment]
Hi @vijayst and @Siignature,

Could you please provide a Code Sandbox link running the latest version of `react-select` with an example of your issue.

The `plnkr.co` link does not appear to be working.

**Comment by bladey** [comment]
Here is a Code Sandbox with over 10,000 items, I'm able to select the last option, could you provide a few more details?

https://codesandbox.io/s/react-select-v3-sandbox-gxnhs

I'll close this issue for now in case it's now redundant.
