### ISSUE TITLE
Breaking changes between beta14 and rc1

### ISSUE THREAD

**Issue by jonathanasquier** [JedWatson/react-select#1379]
I'm having a `Uncaught TypeError: Cannot read property 'scrollWidth' of undefined` which could be related to https://github.com/JedWatson/react-input-autosize/issues/31 using `rc1` and not when using `beta14`.
Is this by design?
Should React or any other package be updated when moving to `rc1`?
Thanks!

**Comment by hueypeard** [comment]
Hi @jonathanasquier, I'm having the same issue. autosize={false} on the Select component seems to be a temporary fix.

**Comment by JedWatson** [comment]
As per the issue referenced above, I believe this has been resolved and can be closed
