### ISSUE TITLE
rerender component would reset the selected value

### ISSUE THREAD

**Issue by ruoshan** [JedWatson/react-select#138]
in `componentWillReceiveProps`:

```
142     componentWillReceiveProps: function componentWillReceiveProps(newProps) {
143         if (JSON.stringify(newProps.options) !== JSON.stringify(this.props.options)) {
144             this.setState({
145                 options: newProps.options,
146                 filteredOptions: this.filterOptions(newProps.options)
147             });
148         }
149         if (newProps.value !== this.state.value) {
150             this.setState(this.getStateFromValue(newProps.value, newProps.options));
151         }
152     },
```

IMHO, the second `if` will be true almost everytime, and when the parent component needs to rerender itself, the selected value is gone, but I think the selected value should be kept :)

**Comment by marksteve** [comment]
I get around this using `LinkedStateMixin`:

```js
render() {
  let something = this.linkState('something')
  return (
    <Select
      value={something.value}
      onChange={something.requestChange}
    />
  )
}
```

**Comment by dcousens** [comment]
Are you saying the second branch is always evaluated because `react-select` is maintaining its own state, and therefore if you pass it in you are resetting it?

**Comment by ngokevin** [comment]
I got around this by using componentShouldUpdate to stop the select from resetting when the state changes. If the select component already has options, don't reset.

**Comment by exitface** [comment]
+1 - If you're using this as part a more complex component it will reset the state of the select upon re-render. Attempting to hijack the onChange event and set the values appropriately results in all sorts of errors and duplication of values.

**Comment by gbmhunter** [comment]
+1, I am having this issue also. @marksteve or @ngokevin could you please elaborate on your solution please?

**Comment by emragins** [comment]
@gbmhunter going with the idea @ngokevin mentioned, I may have gotten around this with 
```
shouldComponentUpdate: function (nextProps, nextState) {
        if (nextProps.value &&
            nextProps.value == this.refs.select.state.value)
            return false;
    },
    render: function () {
        return (
                    <Select ref="select"  .../>
          );
    }
```

At least it works in a 1 minute test...

**Comment by harlow** [comment]
> If you're using this as part a more complex component it will reset the state of the select upon re-render. Attempting to hijack the onChange event and set the values appropriately results in all sorts of errors and duplication of values.

Agreed. Any thoughts on this? Auto setting state seem like a reasonable solution?

**Comment by jossmac** [comment]
Will reopen if necessary, please comment if this is still an issue.
