### ISSUE TITLE
Selecting the same option twice

### ISSUE THREAD

**Issue by latusaki** [JedWatson/react-select#1383]
Looking at the documentation, I can't find how to track if an item has been selected, when that item was already the selected option.

E.g
On a dropdown with options [1,2,3] user selects 3, onChange(3) is fired. What function should I use to track if the user selects 3 again ? onValueClick does not return anything when values are selected from the dropdown

**Comment by qodesmith** [comment]
@latusaki Are you storing the value from `onChange` in state? In the `onChange` fxn just check the state against the value passed in.

**Comment by latusaki** [comment]
If I recall my issue correctly, there is no onChange event, if the already selected option is clicked again. Which is what I wanted to achieve. In the end I did something hacky, displaying the placeholder text as if its the actual selection, so the 'selected' item can be clicked again (because I don't set it as selected in the component)

**Comment by ayozebarrera** [comment]
@latusaki Did you solve this?

**Comment by latusaki** [comment]
@ayozebarrera I assume the 'hacky' solution was were I left it.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
