### ISSUE TITLE
onChange() called when the item selected is selected again

### ISSUE THREAD

**Issue by vivekmoosani** [JedWatson/react-select#1387]
If I select the same option repeatedly, onChange is being triggered. 

Pl check this jsfiddle. https://jsfiddle.net/vivekmoosani/0Lfkb582/

**Comment by Ahmtdnz** [comment]
Hi @vivekmoosani ,

You can use  `componentWillUpdate(nextProps, nextState)` 
or  
if ( ) `
if(! this.state.val == val.value){
        console.log('Do Something...');
      }else{
        console.log('Do nothing...');
      }
`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
