### ISSUE TITLE
How can I hide SelectMenuContainer when all options selected

### ISSUE THREAD

**Issue by Nusinka** [JedWatson/react-select#1389]
When all options selected I need to hide menu with title "No results found". How can I do it?
![2016-11-25 14 47 54](https://cloud.githubusercontent.com/assets/13483840/20625838/605794b8-b31e-11e6-9c01-619a8bd62bf2.png)

**Comment by L5eoneill** [comment]
I was able to hide the text using styles:
`noOptionsMessage: (styles) => ({...styles,
    display: 'none'}),`
But that left the box still showing.

So I made a custom Menu component:

    const Menu = (props) => {
      const shouldShowMenu = props.options.length > props.getValue().length;

      return (
        shouldShowMenu && <components.Menu {...props} />
      );
    };
Then your component just needs to be like:
`<Select components={{Menu}}... />`

If you aren't already, do your import of react-select like:
`import Select, {components} from 'react-select';`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
