### ISSUE TITLE
No default.css in dist directory

### ISSUE THREAD

**Issue by pscanf** [JedWatson/react-select#139]
In `0.4.7` there is no `default.css` in the `dist` directory. Is it intentional?

Thanks :-)

**Comment by binarykitchen** [comment]
Yes, I agree, we need the default CSS in the dist folder. Your latest version is breaking my app. 

Furthermore, I cannot `@import "react-select/less/select.less";` because it's written in LESS whereas the rest of my app is in SASS ...

**Comment by jetpacmonkey** [comment]
Also, it's still referenced in the `README`. Maybe it was just removed by accident?

**Comment by tw0517tw** [comment]
need it back. +1

**Comment by rovolution** [comment]
Yea i had this issue as well.

@JedWatson next time a style sheet name/path is changed, could you do a major version update instead? I would consider that a major API change, and [according to semve]([http://semver.org/), that would be a major bump.

**Comment by elevee** [comment]
+1 on the stylesheet! This library seems awesome but it's rendering all strange :(

**Comment by JedWatson** [comment]
Sorry guys, this was a bug, not an intended change - it shouldn't have been removed :(

Adding it back in now
