### ISSUE TITLE
Uncaught TypeError: (0 , g.default) is not a function

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#1393]
Hey,

When I add the library to my project and try to use any examples of the wiki I always have this error. Can you help me with this?

`react-select.min.self-2d3bef0….js?body=1:1 Uncaught TypeError: (0 , g.default) is not a function(…)Select_render @ react-select.min.self-2d3bef0….js?body=1:1_renderValidatedComponentWithoutOwnerOrContext @ react.self-0d1d65e….js?body=1:16085_renderValidatedComponent @ react.self-0d1d65e….js?body=1:16112performInitialMount @ react.self-0d1d65e….js?body=1:15636mountComponent @ react.self-0d1d65e….js?body=1:15515mountComponent @ react.self-0d1d65e….js?body=1:7637performInitialMount @ react.self-0d1d65e….js?body=1:15650mountComponent @ react.self-0d1d65e….js?body=1:15515mountComponent @ react.self-0d1d65e….js?body=1:7637mountChildren @ react.self-0d1d65e….js?body=1:14615_createInitialChildren @ react.self-0d1d65e….js?body=1:11381mountComponent @ react.self-0d1d65e….js?body=1:11197mountComponent @ react.self-0d1d65e….js?body=1:7637performInitialMount @ react.self-0d1d65e….js?body=1:15650mountComponent @ react.self-0d1d65e….js?body=1:15515mountComponent @ react.self-0d1d65e….js?body=1:7637mountChildren @ react.self-0d1d65e….js?body=1:14615_createInitialChildren @ react.self-0d1d65e….js?body=1:11381mountComponent @ react.self-0d1d65e….js?body=1:11197mountComponent @ react.self-0d1d65e….js?body=1:7637performInitialMount @ react.self-0d1d65e….js?body=1:15650mountComponent @ react.self-0d1d65e….js?body=1:15515mountComponent @ react.self-0d1d65e….js?body=1:7637performInitialMount @ react.self-0d1d65e….js?body=1:15650mountComponent @ react.self-0d1d65e….js?body=1:15515mountComponent @ react.self-0d1d65e….js?body=1:7637mountComponentIntoNode @ react.self-0d1d65e….js?body=1:20779perform @ react.self-0d1d65e….js?body=1:8664batchedMountComponentIntoNode @ react.self-0d1d65e….js?body=1:20800perform @ react.self-0d1d65e….js?body=1:8664batchedUpdates @ react.self-0d1d65e….js?body=1:17861batchedUpdates @ react.self-0d1d65e….js?body=1:7292_renderNewRootComponent @ react.self-0d1d65e….js?body=1:20959_renderSubtreeIntoContainer @ react.self-0d1d65e….js?body=1:21045render @ react.self-0d1d65e….js?body=1:21066mountComponents @ react_ujs_mount.self-5293119….js?body=1:87(anonymous function) @ react_ujs_native.self-69da92a….js?body=1:9fire @ jquery.self-660adc5….js?body=1:3233fireWith @ jquery.self-660adc5….js?body=1:3363ready @ jquery.self-660adc5….js?body=1:3583completed @ jquery.self-660adc5….js?body=1:3618`

**Comment by Dagur** [comment]
I'm getting the same error:

> react-select.js:1785 Uncaught TypeError: (0 , _classnames2.default) is not a function(…)Select_render @ react-select.js:1785
(anonymous function) @ react.js:6690
measureLifeCyclePerf @ react.js:5971
etc.


```javascript
render: function render() {
		var _this8 = this;

		var valueArray = this.getValueArray(this.props.value);
		var options = this._visibleOptions = this.filterOptions(this.props.multi ? this.getValueArray(this.props.value) : null);
		var isOpen = this.state.isOpen;
		if (this.props.multi && !options.length && valueArray.length && !this.state.inputValue) isOpen = false;
		var focusedOptionIndex = this.getFocusableOptionIndex(valueArray[0]);

		var focusedOption = null;
		if (focusedOptionIndex !== null) {
			focusedOption = this._focusedOption = options[focusedOptionIndex];
		} else {
			focusedOption = this._focusedOption = null;
		}
this --->	var className = (0, _classnames2['default'])('Select', this.props.className, {
			'Select--multi': this.props.multi,
			'Select--single': !this.props.multi,
			'is-disabled': this.props.disabled,
			'is-focused': this.state.isFocused,
			'is-loading': this.props.isLoading,
			'is-open': isOpen,
			'is-pseudo-focused': this.state.isPseudoFocused,
			'is-searchable': this.props.searchable,
			'has-value': valueArray.length
		});
```

**Comment by Dagur** [comment]
There's a solution here https://github.com/JedWatson/react-select/issues/582#issuecomment-163389322

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
