### ISSUE TITLE
Unable to clear selection if value is boolean false

### ISSUE THREAD

**Issue by sgaestel** [JedWatson/react-select#1394]
I use a Select with 3 possible values: `true`, `false` and `null` (`null` being the default)
The select is clearable.
When I select the `true` option, no problem to clear the select.
However, if I select the `false` option, the clear button is not displayed.

See https://plnkr.co/edit/rZPhbvO3ajW2MxIoJYmm?p=preview

**Comment by wesleysmyth** [comment]
Having the same issue

**Comment by sgaestel** [comment]
I submitted a PR to fix the issue, just waiting for it to be merged

**Comment by bodia-uz** [comment]
Same issue with `1.0.0-rc.3`

**Comment by sgaestel** [comment]
Will be solved once https://github.com/JedWatson/react-select/pull/1395 is accepted and merged
