### ISSUE TITLE
Empty select should translate to empty string

### ISSUE THREAD

**Issue by silvenon** [JedWatson/react-select#1400]
The hidden input field disappears when the select menu is empty, which isn't consistent to how `<select>` elements work, where you select an empty value in case you want to "remove" that field.

What do you think?

**Comment by tudorpavel** [comment]
I'm using a multiple select with Rails and at first I thought this is a bug with `react-select`. But the way the default Rails view helper works is that an extra hidden input with an empty value is added to the form besides the `<select multiple="multiple">` tag.

My solution was to simply add this hidden input in React myself. I hope it helps you figure out what to do in your case.

I don't think there's an option of `react-select` that adds this hidden empty input for multi select. Should it have this option?

**Comment by silvenon** [comment]
I also add the hidden field as a temporary hack, but I think this should be solved in the core.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
