### ISSUE TITLE
Invalid prop `options` of type `object` supplied to `Select`, expected `array`.

### ISSUE THREAD

**Issue by wzup** [JedWatson/react-select#1402]
Need to pass `object` to  `options` , not array. How to enable?

Your example:
```
var options = [
    { value: 'one', label: 'One' },
    { value: 'two', label: 'Two' }
];
```

I need to pass:
```
{
    123: {id: 123, value: 'one', label: 'One'},
    125: {id: 125, value: 'two', label: 'Two'},
    127: {id: 127, value: 'three', label: 'Three'}
}
```

**Comment by Stas-Buzunko** [comment]
Why do you need to pass object?

**Comment by theskillwithin** [comment]
Warning: Failed prop type: Invalid prop `value` of type `array` supplied to `Value`, expected `object`.

**Comment by agirton** [comment]
Hi @wzup we don't support passing an object, you will need to convert this to an array. @theskillwithin for options it needs to be a flat array. It looks like the value you selected was an array.
