### ISSUE TITLE
Need help for maintainance?

### ISSUE THREAD

**Issue by julien-f** [JedWatson/react-select#1403]
Hi @JedWatson,

It seems that you do not have the time to maintain this package by yourself, do you need help?
To be honest, I do not have time to invest much time in it myself but I can help in opening the management :)

IMHO, the best approach would be to migrate this repo in a GitHub organization (because it allows other people to add maintainers if you're not available) and to add a bunch of maintainers.

Who can and wants to help?

**Comment by silvenon** [comment]
@julien-f awesome alternative to those awful "Is this project abandoned?!" issues. 👍 I want to help, I believe this is the best React select solution.

**Comment by BreahnaDavid** [comment]
@julien-f :+1: I'm interested to work on it since I have used it everywhere

**Comment by turnerniles** [comment]
See also https://github.com/JedWatson/react-select/issues/1315. Some issues I see have been fixed and can be closed as well.

**Comment by julien-f** [comment]
@turnerniles You're right, this issue is a duplicate! :)
But I'm reluctant to close it as it increases the visibility of the problem overall.

**Comment by julien-f** [comment]
@JedWatson you here? :)

**Comment by silvenon** [comment]
I think one of us should fork the repo and start merging in contributions, but I'm not ready to take that on just yet. 😅

**Comment by sontek** [comment]
Yeah, Looks like @JedWatson is MIA.  Has anyone done a fork yet?  There are 113 PRs so a fork could have a ton of features/bug fixes immediately.  I'm willing to help!

**Comment by silvenon** [comment]
I created one just now: [silvenon/react-select](/silvenon/react-select). I have lots of free time ATM, so I'll do as much work as possible. I'll start by rewriting tests to Jest, so we can start off with a strong test suite.

**Comment by sontek** [comment]
@silvenon Thanks for doing it!  You might want to reach out to the people in tickets:

https://github.com/JedWatson/react-select/issues/1432
https://github.com/JedWatson/react-select/issues/1315

Since they were also wondering why it isn't supported anymore.

**Comment by sontek** [comment]
@silvenon Looks like you haven't made any progress either?

**Comment by silvenon** [comment]
@sontek I decided to wait for @JedWatson input first, so I know in which direction we should proceed. https://twitter.com/jedwatson/status/812549810758643712 Thanks for the ping.

**Comment by shinzui** [comment]
@silvenon How long are you planning to wait before proceeding?

**Comment by silvenon** [comment]
@shinzui no longer 😄 I asked him whether he's willing to transfer ownership, move it to an organization or (last resort) I continue with my fork. If I get no response, tomorrow I'll start working on the fork.

**Comment by JedWatson** [comment]
Hey everyone - thanks for all the constructive offers to help, and sorry for the complete lack of response, I ended up taking a much needed complete break over the holidays. (I have about 2k unread GitHub notifications at the moment, just to put things in perspective! It really gets on top of you)

I'm back at work this week so I'll jump in tomorrow & put a plan in place - would love to get some assistance triaging the issues / fixes that are important or good to go then we can figure out how to take better care of maintenance longer term.

@silvenon what timezone are you in? It might be helpful to jump on Skype / hangouts to sync up. I'm in Sydney so UTC+10

Thanks!

**Comment by silvenon** [comment]
@JedWatson I'm in Zagreb, UTC+1. I'm also "silvenon" on Skype, so feel free to add me and propose a time when you're free.

**Comment by silvenon** [comment]
#1481 🎉

**Comment by JedWatson** [comment]
Consolidating this to #1481
