### ISSUE TITLE
Document behavior of simpleValue

### ISSUE THREAD

**Issue by dallonf** [JedWatson/react-select#1405]
After searching for a way to make `onChange` return the actual value of an option instead of the option object itself, I tried `simpleValue` on a whim, and it did exactly what I wanted!

But the only place it's mentioned in the documentation (aka the README) is in relation to multi-value selects:

> The `onChange` event provides an array of selected options or a comma-separated string of values (eg `"1,2,3"`) if `simpleValue` is true

It should probably be added to the prop table. I'm happy to do a PR for this, just wanted to check first that it's not deprecated or anything.

**Comment by febeling** [comment]
That should be an old API and not actually working any longer. The new API is `joinValues`. This change happened around beta9–beta12 if I'm not mistaken.

**Comment by dallonf** [comment]
We're on `1.0.0-rc.2` and it's still working! Might want to put a deprecated warning on it.
In any case, `joinValues` still isn't documented as a way to get the value field as the argument of `onChange` instead of the option object.

**Comment by febeling** [comment]
I was referring to the multi usage. Please ignore the noise.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
