### ISSUE TITLE
Creatable Not Working

### ISSUE THREAD

**Issue by dhruv004** [JedWatson/react-select#1409]
I have tried to import the creatable component but I get the following error.

> warning.js:45Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `MyComponent`.

> invariant.js:39Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `MyComponent`.

This is my code
```
import React,{Component} from 'react';
import Select from 'react-select';

class MyComponent extends Component{
     constructor(){
          super();
          this.state = {
             "value":""
          };
      }
      handleOnChange = (value) => {
              this.setState({
                  "value":value
              });
       }

       render(){
          const {value} = this.state;
          let options =  [
        				{ value: 'R', label: 'Red' },
        				{ value: 'G', label: 'Green' },
        				{ value: 'B', label: 'Blue' }
        			]
           return(
                           <Select.Creatable
                                options={options}
                                onChange={this.handleOnChange}
                                value={value}/>
           )
      }
}
```
this is the same as if I do
`import {Creatable} from 'react-select';`
Instead if I do the following then it works fine i.e. with

>  allowCreate={true}

`<Select allowCreate={true}
              options={options}
              onChange={this.handleOnChange}
              value={value}/>`

What am I doing wrong.Any help would be good.

**Comment by mcorteel** [comment]
`Creatable` and `AsyncCreatable` only exist in V1.0, it's not in the stable version. And these new components will deprecate `allowCreate` (from what I could gather). So I guess you are using the stable version.
It's already available in master though.

**Comment by evisong** [comment]
Got the same issue. We're already forked from v1.0 to our private repo and add some logics for internal project use, so we're not easy to roll back to v0.9. 

Any plan to fix this? Thanks.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
