### ISSUE TITLE
Multi-select: Select-clear-zone spans entire height of select box

### ISSUE THREAD

**Issue by turnerniles** [JedWatson/react-select#1410]
The Select-clear-zone spans the entire height of the select box when using multi select. When using many select options it's easy to mistakenly click and have all of the options clear. Is there a reason for having the hit area span the entire height of the select box? Would alternative CSS be appropriate? The Select-arrow-zone to trigger the select drop down also spans the entire height of the select box.

![image](https://cloud.githubusercontent.com/assets/8146241/20892136/e58169f2-bada-11e6-92e7-02266e54bd03.png)

**Comment by teripaquitinho** [comment]
we are experimenting the same problem... any solution found yet on this?

**Comment by turnerniles** [comment]
I could not figure out a solution. I ended up just hiding the 'x' and adding a clear all button in a different area.

**Comment by teripaquitinho** [comment]
ah i'm trying overriding the css by adding somethign like this... it's a bit of an hack but seems to work

```
Select--multi .Select-clear-zone {
    width: 17px;
    position: absolute;
    right: 20px;
    top: calc(50% - 12px);
    z-index: 100;
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
