### ISSUE TITLE
onFocus prop does not work when focusing with arrow keys

### ISSUE THREAD

**Issue by mikestone14** [JedWatson/react-select#1413]
[`focusAdjacentOption`](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L703-L760) handles focusing options using the arrow keys in the UI. However, there doesn't seem to be an easy way for a parent component to get the focused option when it is focused using arrow keys (since no callbacks/props fire in that function).

**Comment by alabels9** [comment]
Having the same issue with a custom render for the options. The keyboard navigation focus is lost. Tried to overwrite with CSS, but to no avail. Any more ideas to try would  be welcome!

**Comment by JedWatson** [comment]
What's the actual use-case here? I expect it would need to account for mouse-driven focusing as well, not just keyboard focus.

With a custom renderer, you already get the `isFocused` prop... what more do you need?

**Comment by lacymorrow** [comment]
I have a no-mouse, arrow-key only driven use-case for focusing to adjacent elements.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
