### ISSUE TITLE
Select-value-icon span value html text times renders as incorrect unicode

### ISSUE THREAD

**Issue by sachetsharma** [JedWatson/react-select#1417]
This is same issue as #314 Select-item span value html text times renders as incorrect unicode. Could you please make same fix for the Select-value-icon.

**Comment by ludwinas** [comment]
I'm having the same issue. It seems that in `[/lib/Value.js](https://github.com/JedWatson/react-select/blob/master/lib/Value.js#L75) ` the `×` character is still being used instead of `&times;`.

**Comment by easadler** [comment]
I used the advice from #314 and it now works if you need a quick solution.
```html
<meta charset="UTF-8">
```

**Comment by rsimonton** [comment]
Anyone have a viable work-around for this?

**Comment by ludwinas** [comment]
@rsimonton we fixed it by making sure we were setting `UTF-8` as the charset for that page. I hope this helps!

**Comment by rsimonton** [comment]
@ludwinas unfortunately that's not working on my end.  Still rendering incorrectly despite setting charset for the page.  Hmm.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
