### ISSUE TITLE
No results found click handler or special component

### ISSUE THREAD

**Issue by tnrich** [JedWatson/react-select#1419]
Hey there,

Thank you for this most excellent tool.

I'm trying to implement something like what you can see in the following image: 
![image](https://cloud.githubusercontent.com/assets/2730609/20995521/804e2e3e-bcac-11e6-83fe-440fdffd9fd0.png)

Ideally I'd even be able to have a custom component in there so I could add a little + button or something of the sort. 

I didn't see anything quite like this yet in the docs. Does this exist already? And if not, can this use case be added? It seems like it should be fairly simple given that "noResultsText" is already an accepted prop.

Thanks!

**Comment by tnrich** [comment]
Well, whaddya know! It looks like this already works. So maybe just tweaking the docs is all that's needed. 

Here's a pic of my custom component for proof:
![image](https://cloud.githubusercontent.com/assets/2730609/20995672/6b4c2fbc-bcad-11e6-8b69-941595f23652.png)

I'll put a PR in to update the docs. Thanks!

**Comment by JedWatson** [comment]
> Thank you for this most excellent tool.

You're welcome 😄
