### ISSUE TITLE
support for tagging

### ISSUE THREAD

**Issue by lamuria** [JedWatson/react-select#142]
Hi,

does this lib has Tagging support?

If yes, can you show me an example?

**Comment by lamuria** [comment]
no responses..

**Comment by dcousens** [comment]
@lamuria do you mean like in the [clickable labels example](https://jedwatson.github.io/react-select/)?

**Comment by beeant** [comment]
I need tagging support too, it's something like the first example in selectize example: http://brianreavis.github.io/selectize.js/

**Comment by beeant** [comment]
→ https://github.com/JedWatson/react-select/pull/151
