### ISSUE TITLE
select widget continues to show placeholder when value prop is present

### ISSUE THREAD

**Issue by dbalasub** [JedWatson/react-select#1423]
![react-select widget](https://cloud.githubusercontent.com/assets/8262998/21034993/da3f564c-bd70-11e6-930d-0a934ca1f8fe.png)
![react debugging chrome plugin shows the element with the props](https://cloud.githubusercontent.com/assets/8262998/21035005/eb2b5bf4-bd70-11e6-8938-e39306db1de8.png)

Look at the above screen shots, the value is populated but the widget still shows the placeholder. Took me a while to get this far and make this work with meteor, ( i am new to both).

Any pointers would be appreciated.

**Comment by areinmeyer** [comment]
@dbalasub Can you add a snippet of your code that calls react-select?  I had that problem when my options array did not contain an object with `label` and `value` keys.  The select stored the value properly in my event handler, but did not display what I had selected.

**Comment by dbalasub** [comment]
Here it is, the only way for me to get the selected value to show up here is set the placeholder

const defaultValue = (this.props.cityOf == 'dep')
      ? 'From?'
      : 'Where to?';
    const value = this.state.value
      ? this.state.value
      : defaultValue;
    console.log('in autocomplete render ',this.state.value);
    return (

      <AsyncComponent
      name="form-field-name"
      value = {this.state.value}
      onChange={this.onChange.bind(this)}
      loadOptions={this.getOptions.bind(this)}
      placeholder={value}
      autoload={false}
      />

**Comment by areinmeyer** [comment]
What is `this.getOptions.bind(this)` returning?  It looks like you're trying to use just a string as the value and display but you've not set `simpleValue={true}`.  I'd back up out of using the async component for now and do a simple implementation of react-select with a hardcoded list that you can change later to be loaded async to get it working.  What I see doesn't look wrong, but the onChange or loadOptions functions could be doing something that react-select doesn't like.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
