### ISSUE TITLE
Issue with tab-index when using multiple Select.Async in Safari

### ISSUE THREAD

**Issue by AreWeThereYeti** [JedWatson/react-select#1426]
Hey there
Im using multiple  Select.Async component on a page, and i have noticed a strange issue in safari when selecting using **Tab** in Safari. 

When selecting the value with the **Tab**-button, the focused component will be the first Select.Async component on the page, instead of fx the following input. 
The screen shot below is an example of the setup. Im using the component in a row with other input field types.

<img width="267" alt="skaermbillede 2016-12-12 kl 11 52 30" src="https://cloud.githubusercontent.com/assets/2631877/21096780/86712e48-c061-11e6-9de9-2c775c4b2691.png">

Im guessing that this issue can be solved with some tabindex attributes, but I think its strange that the focused component is the first on page instead of the next in context. 

Best regards
Mikkel

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
