### ISSUE TITLE
IE11:Creatable: Arrow keys don't work

### ISSUE THREAD

**Issue by michelemendel** [JedWatson/react-select#1427]
Select (and Select.async) works fine in Chrome (54) and IE11 and Creatable works fine in Chrome, but with IE11 the arrow keys don't work. I can write and select with the mouse, but not scroll or go left and right on the text.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
