### ISSUE TITLE
Rendering a link as the no results text

### ISSUE THREAD

**Issue by RGGWebDesigns** [JedWatson/react-select#1429]
Very simple, is it possible to render a clickable link instead of the "No results found" text?

**Comment by maksimsemenov** [comment]
Yes. You actually can pass a node to `noResultsText` option. For example:
```
...
noResultsText={<a href='youdestination.com'>Try this link</a>}
...
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
