### ISSUE TITLE
lake of documentation for `optionComponent` and `optionRenderer`

### ISSUE THREAD

**Issue by optyler** [JedWatson/react-select#1431]
Hi, 

I can saw in the documentation that we can customize options rendering with `optionComponent` and `optionRenderer` props but I can't figure out how they work.
Documentation is pretty light on the subject and I did not found any example in the issues / example / google. 
Have you guys any example on how implementing custom option rendering like this capture : 
![capture d ecran 2016-12-14 a 11 06 40](https://cloud.githubusercontent.com/assets/10259/21177909/70d1e9dc-c1ed-11e6-838d-728fea4f385a.png)

Thanks a lot.

BTW, your work is AWESOME!

**Comment by optyler** [comment]
Well, I found [an example with the Gravatar thing](https://github.com/JedWatson/react-select/blob/master/examples/src/components/CustomComponents.js) seems great for now.

**Comment by clarkritchie** [comment]
Aha, I was looking for this, too.  Many thanks for linking to the example!  👍

**Comment by VladPoe** [comment]
Is it still possible to find the example?
Wanna get it too, but /examples/ returns 404

**Comment by exiadb** [comment]
[CustomComponents example](https://github.com/JedWatson/react-select/blob/v1.x/examples/src/components/CustomComponents.js)

The file moved to v1.x branch.

**Comment by Rall3n** [comment]
@Natansab The prop `optionsComponent` was replaced by the [Components framework](https://react-select.com/components) in **v2** which offers much more options to customize the `Select` component. The [documentation](https://react-select.com/components) should get you started.

**Comment by Natansab** [comment]
Thank you @Rall3n! One thing that is not clearly explained in the doc, for the Components framework at least, is the ability to access the values through the "data" props passed to the components element. getValue() returns only the data of the selected value.

**Comment by Rall3n** [comment]
Well, the documentation at that point references the [Props documentation](https://react-select.com/props#option). You can find all props that are being assigned to each of the components under the section [Components](https://react-select.com/props#components).
