### ISSUE TITLE
What is the release schedule?

### ISSUE THREAD

**Issue by malucky** [JedWatson/react-select#1432]
There are several important fixes that have been merged into master but have not been released.
The current repo approach of not committing the build file avoids conflict, but it also makes pointing to specific github commit via npm not possible. The current viable workaround is to fork the repo, build the files, and point to the forked repo, which is not ideal.

I would like to propose a few alternatives:
1) have a loose release schedule (preferably a shorter schedule i.e. 1/week for bug fixes)
2) create a hook on new commit to run the build task and push to a separate branch (i.e. latest-build)
3) commit the build file changes - rebasing latest before testing and merging as part of contributing process

thanks

**Comment by silvenon** [comment]
Hey @malucky, I'm starting a fork of react-select to fix important issues like this. I'll probably post my progress in #1403.

**Comment by JedWatson** [comment]
Thanks for the suggestions @malucky - going to be actioning this, see #1481

I'll also get a new release with fixes out asap.

**Comment by malucky** [comment]
👍 thanks @JedWatson! sounds great
