### ISSUE TITLE
Select.js:645 Uncaught TypeError: Cannot read property 'props' of undefined(…)

### ISSUE THREAD

**Issue by pelatimtt** [JedWatson/react-select#1433]
I'm trying to run a simple example but I get an error. The page is not rendered and I see this error in teh Chrome console:

Select.js:645 Uncaught TypeError: Cannot read property 'props' of undefined(…)

The strange fact is that if I set the options=[] and value=undefined the components renders

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
