### ISSUE TITLE
How to render an input inside an option?

### ISSUE THREAD

**Issue by alexeychikk** [JedWatson/react-select#1434]
Is it possible?
Input inside an option never gets focus. Please, can you help me? Here is the fiddle:
https://jsfiddle.net/ds5bboh3/1/

**Comment by mujz** [comment]
I'm having this issue too. Can we get an answer about this please?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
