### ISSUE TITLE
Data loss through `simpleValue` / `joinValues` change for multi-select

### ISSUE THREAD

**Issue by febeling** [JedWatson/react-select#1435]
This is not quite a bug report. I rather want to highlight something that has bitten me and cause some data loss at my place.

A while back the `simpleValue` API got dropped and multiple hidden fields got populated instead. A bit later the mechanism got reinstated, but using a different name, `joinValues`. I hope I got the course of events right here.

I use this UI element as a multi-select in production, with a beta version and recently bumped the version up. The above change became effective, and whenever a user open an resource for editing and saved it, all but the first of the multiple values got dropped. So significant data loss was caused (which was thankfully restored from backups).

I think these changes were probably all in line with the semantics of the version designations, and I was being a bit enterprising with using a beta in production. Still this report as a heads up to other users to check if the same applies for them.

And one might even consider adding a warning about the changed API when it is still used, maybe even raising an exception. But the latter is likely a bit much for an API that came and went all before version 1.0.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
