### ISSUE TITLE
Creatable not support input.focus().

### ISSUE THREAD

**Issue by m-basarab** [JedWatson/react-select#1437]
Hi. I am trying to focus on Creatable using:
ref={(input)=>{
    if(input!=null){
        input.focus();
    }
}};
, but I can't.
https://plnkr.co/edit/LaTJN70HFRNRuFMR6vpn?p=preview

**Comment by jxodwyer** [comment]
@m-basarab have you tried passing in the `autofocus` prop? 

You could adjust your example to this:
```
<Select.Creatable
    autofocus
    name="form-field-name"
    value="one"
    openOnFocus={true}
    options={options}
    onChange={logChange}
  />
```

**Comment by AlexanderTserkovniy** [comment]
@jxodwyer `autofocus` does not allow to create the `label` for `Creatable`. That is for instance my issue.

So I want to have label alongside with `Creatable`, how could I achieve that?

Just standard html label which makes focus on click on it.

Thanks.

**Comment by the-spyke** [comment]
@jxodwyer How is this related if `Creatable` doesn't  expose `Select`'s instance method `focus`? The same issue was with `Async` component, before it was fixed in [RC2](https://github.com/JedWatson/react-select/blob/master/src/Async.js#L179).

May I submit a pull request with `focus` method?

**Comment by jxodwyer** [comment]
Since the example was essentially calling `focus` right away I thought `autofocus` was sufficient. Yeah, that makes sense to me.

**Comment by mattraykowski** [comment]
This appears to be the case for ```AsyncCreatable``` as well.

**Comment by Grisu118** [comment]
This should be fixed I think, so Issue could be closed
@JedWatson Are you planning a publication on npm soon?

**Comment by jnachtigall** [comment]
@JedWatson Could you close this, it is fixed.

**Comment by JedWatson** [comment]
Thanks for the heads up @jnachtigall
