### ISSUE TITLE
"Large Dataset" demo is broken

### ISSUE THREAD

**Issue by Nesciosquid** [JedWatson/react-select#1438]
The "Cities" selector in the demo page at http://jedwatson.github.io/react-select/ is intended to show how a large list of options can be virtualized.

However, I think you're running into an issue where the virtual list isn't displaying correctly. When I scroll down the list, the values jump around a whole bunch, and most of the list shows up white/empty.

I had this same problem when using `react-virtualized`, I think after one of the recent updates to that library.

**Comment by Nesciosquid** [comment]
FWIW -- I'm using Chrome on a Win10 PC.

**Comment by tongrhj** [comment]
To help picture the error, scrolling down the list leads to values jumping around, then to this, then to a completely white/empty list.
[![https://gyazo.com/ff3a26c29056c627b15dfb2f1aa2c241](https://i.gyazo.com/ff3a26c29056c627b15dfb2f1aa2c241.png)](https://gyazo.com/ff3a26c29056c627b15dfb2f1aa2c241)

**Comment by Nesciosquid** [comment]
This happened to me a couple months ago because of a react-virtualized
update I didn't notice while updating other packages. I think they changed
the API somewhat.

**Comment by GenoD** [comment]
@Nesciosquid is there a solution to this problem as of yet? Could I use an earlier version of react-virtualized or is it listed as a dependency for version of React-select that optimizes large datasets?

**Comment by Nesciosquid** [comment]
I think the virtualized demo on the react-select demo page is outdated.

Instead, I think we want to look at the demos for the actual `react-virtualized-select` component: http://bvaughn.github.io/react-virtualized-select/

Use that, it looks good.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
