### ISSUE TITLE
support for required inputs?

### ISSUE THREAD

**Issue by chellberg** [JedWatson/react-select#144]
I wasn't able to find a way to get a required input working with react-select. 

Passing required={true} into <Select /> didn't do anything.    

Passing required=true into inputProps did made the input required, but this required input isn't updated by react-select, so the form became unsubmittable.   

Is there somewhere else required=true should be passed or is this not a supported feature yet? I might circle back to this later in the week if anyone has advice/guidance on adding this.  

Thanks!

**Comment by dcousens** [comment]
@chellberg what do you expected with `required`?   This is a behaviour you should be handling at the parent level,  whether or not this component has input is irrelevant to top level state.
