### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by alexandermontgomery** [JedWatson/react-select#1440]
I am on version react-select@1.0.0-rc.2 and the plugin is giving me the error above. 

Every interaction with the dropdown causes 
`Warning: React can't find the root component node for data-reactid value`
followed by
`Uncaught TypeError: Cannot read property 'firstChild' of undefined`

The error does not appear until after I click to open the dropdown. It will render on the page no problem with no errors, but when I starting interacting those errors are triggered consistently.

I know this is usually caused by two versions of React (I am on react@0.14.5) but I checked the react-select package.json and react is indeed listed as a peer dependency. I can't figure out why this is happening and don't really have any other ideas because from what I can see I only have one version of React.

Love the plugin by the way - very configurable and exactly what I need in a dropdown.

Anybody have any ideas on what I can try?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
