### ISSUE TITLE
Multi-Select: Options selected in multi={true} mode show "A-" instead of "x" icon to close them.

### ISSUE THREAD

**Issue by francisgwhitesell** [JedWatson/react-select#1446]
Using the <Select> element with multi={true} and then selecting any option causes the option to show in the top of the multiselect as expected, but instead of rendering as they do in demos with an "x" icon where a user can cancel an option, they render with [accented] "A-". See screenshot.

https://cloud.githubusercontent.com/assets/2829262/21397045/44bba620-c770-11e6-9e08-36989dbf891f.png

**Comment by doytch** [comment]
Did you ever figure this out @francisgwhitesell ? I started hitting it now as well.

**Comment by doytch** [comment]
Found the cause of the error in my builds, the charset header wasn't being properly set to utf-8.

**Comment by francisgwhitesell** [comment]
Awesome - I never worked out a way around it, so I had to use a different
approach for that project.

**Comment by agirton** [comment]
Since this issue is outside the component going to close. Users can use the `arrowRenderer` if they choose to use a different style or icon.
