### ISSUE TITLE
Cannot read property 'option' of undefined

### ISSUE THREAD

**Issue by thezanke** [JedWatson/react-select#1447]
# Problem
If you try to use arrow keys in a Select with zero options after tabbing to it it throws `TypeError Cannot read property 'option' of undefined`.

## Demo
https://plnkr.co/edit/CYKgXtDCN8N3F16StNTq?p=preview
Steps to reproduce:
1. Focus the top input element
2. Tab to the Select element
3. Push up or down arrow key

**Comment by tsechingho** [comment]
I encounter this issue and bug me very much.

the fix by @thezanke could work but it is not yet accepted.

if anyone looks a workaround, you could try to use `cache` to resolve, like
``` js
    <Select.Async
      name='business[city_name]'
      placeholder='City'
      autoload={true}
      cache={{ '': [{ label: '', value: null, disabled: true }] }}
      value={cityName}
      loadOptions={loadCityOptions}
      onChange={onCityChange}
      searchPromptText='Type > 3 charaters to search'
    />
```
