### ISSUE TITLE
support for disabled options

### ISSUE THREAD

**Issue by pashap** [JedWatson/react-select#145]
Is there anyway to pass a disabled attribute to an option?

```javascript
exports.US = [
    { value: 'AL', label: 'Alabama', disabled: true },
    { value: 'AK', label: 'Alaska' },
```
![disabled-option](https://cloud.githubusercontent.com/assets/1840830/7356478/ffb55a34-eced-11e4-82c9-3b57d4628685.png)

**Comment by MasterSlowPoke** [comment]
On the outside chance anyone's seeing this page like me and trying to get an option disabled in v2, it's now `isDisabled`.

**Comment by horacioh** [comment]
@MasterSlowPoke is this only for v2? is this available on v1?

**Comment by tuanalumi** [comment]
Why is this not documented anywhere?

**Comment by T04435** [comment]
docs: https://react-select.com/props

**Comment by iamyahia** [comment]
> Why is this not documented anywhere?

Take a look of the below URL and search for isDisabled

**Comment by iamyahia** [comment]
> Why is this not documented anywhere?


@tuanalumi  Take a look at the below URL and search for isDisabled

https://react-select.com/props
