### ISSUE TITLE
Name on hidden input is not working

### ISSUE THREAD

**Issue by octavianusb** [JedWatson/react-select#1455]
For example you can check in console the hidden input, you will find that there doesn't exit an name attribute, but using inputProps={{ name: 'name-for-input' }} you will be able to add name attribute. Here is the example: https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

**Comment by fabien-tanguy** [comment]
Could not figure out how to set the name attribute in component. Does not work

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
