### ISSUE TITLE
Customizable classNames

### ISSUE THREAD

**Issue by Monar** [JedWatson/react-select#1457]
### Problem 

As of version `v1.0.0-rc.2` class names property has fixed values, with small exception when passing single string property to some of the elements. This is problematic in project which will have name collisions with `Select` class names.

`react-select` is using BEM-like naming convention and its great, but it covers only one of many BEM-like naming conventions. This is an another problematic element for project that already settled on a different BEM variation.

There is also one more limitation of this approach. It's impossible to use it with [css-modules](https://github.com/css-modules/css-modules).

### Solution 
Provide name generator as a property.

For this purpose I've implemented [bemNames](https://www.npmjs.com/package/bem-names) simple generator of BEM-like class names, and modified `react-select` with it. You can check how it looks like [here](https://github.com/Monar/react-select/blob/master/src/Select.js). 

This is how I've introduced `react-select` to our app. At the moment change is 100% backward compatible and is able to generate class names matching our project naming convention.

**Comment by devrelm** [comment]
I'm not sure if bringing in an external library is necessary, though I can see how allowing the user to configure the element and modifier separators would be helpful. In either case I'd like to bring up another point, which is that this (as implemented) doesn't look like it'd work well (or even at all) with the `className` prop/option.

I'd like to suggest that in addition to sticking closer to [more widely used BEM naming standards](http://getbem.com/naming/), we also allow `className` to take a space-delimited string of block names which get propogated through to Select's children. This could also help to close #1144, since if a client wants to use multiple base names (say, the default `Select`, plus their own `Select-dark`), then they would be carried through to all the other elements.

This could be done with or without `bem-names`, and would open up for much greater customizability.

**Comment by Monar** [comment]
Ok, to clarify few things. 

Suggested implementation does not change how `className` props/option work. You can check it for your self. `bem-names` also is not a hard coded into to the component. It just describes API of class name generator, and is used by default implementation. 

@devrelm could you help me and locate where in the specification are described this kind of modifiers (I did not find it :disappointed:): 
```js
className="Select Select--multi is-searchable has-value"
```

In project I'm working right now, we decided not to write this kind of loose modifiers, due to legacy styling in the project. So it looked like this in our project:

```js
className="Select Select--multi Select--searchable Select--has-value"
```

Now we moved to [css-modules](https://github.com/css-modules/css-modules), and `bem-names` helped a tone we only changed two lines per component. 

There are two ways We can approach class name customization:
 
The first one is by passing a block name through this component. 
Pros are that it **does the job done**, but on the con side it **does nothing more** than that. 

The second one is by passing generator function (`bem-names` is just a good generic generator).
Pros:
* does the job done
* allows to integrate this component with any project using any class naming convention. 
* allows to apply [css-modules](https://github.com/css-modules/css-modules) without a need to define styles in `:global` scope.
* makes transition between different styling solutions much easier. 

Cons:
* except for a negligible performance difference, I can't see one. 

I'm all for any of those two solution with slight tilt towards generator function.

Bonus: You can check [here](https://github.com/Monar/react-select/tree/classnames-free) how would look a `react-select` without `classnames` and only with `bem-names`.

**Comment by devrelm** [comment]
It sounds like I may have spoken without completely understanding your implementation. I'll take another deeper look and get back to you, but if it is as you describe then it sounds good and should probably have a pull request opened.

Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
