### ISSUE TITLE
"Create Option" text in Creatable is not modifiable by props. 

### ISSUE THREAD

**Issue by metti222** [JedWatson/react-select#1459]
"Create Option" text in Creatable is not modifiable by props.

**Comment by optyler** [comment]
Hi,

I just found how you could achieve that. In my case I want to internationalise the strings with `react-intl` it gives this code : 

in my translation file `fr.yml`
```yml
ReactSelect:
  CreateLabel: Créez {label}?
```

```jsx
<Select
    promptTextCreator={(label) => intl.formatMessage({ id: 'ReactSelect.CreateLabel' }, { label })}
/>
```

**Comment by jsnmoon** [comment]
As @optyler has mentioned, the prompt text is modifiable using Creatable's `promptTextCreator` prop. 

However, there is an outstanding bug (#1464) that will pass the entire label as the callback value instead of just the value.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
