### ISSUE TITLE
npm install not getting latest file for AsyncCreatable.js 

### ISSUE THREAD

**Issue by Vinayaktech** [JedWatson/react-select#1460]
I have installed npm install react-select --save which installed 1.0.0-rc.2 which contain AsyncCreatable.js as below

```
import React from 'react';
import Select from './Select';

const AsyncCreatable = React.createClass({
	displayName: 'AsyncCreatableSelect',

	render () {
		return (
			<Select.Async {...this.props}>
				{(asyncProps) => (
					<Select.Creatable {...this.props}>
						{(creatableProps) => (
							<Select
								{...asyncProps}
								{...creatableProps}
								onInputChange={(input) => {
									creatableProps.onInputChange(input);
									return asyncProps.onInputChange(input);
								}}
							/>
						)}
					</Select.Creatable>
				)}
			</Select.Async>
		);
	}
});
module.exports = AsyncCreatable;
```

but in master AsyncCreatable.js is updated with commit https://github.com/JedWatson/react-select/pull/1374. this restrict me to use AsyncCreatable.js and it only shows Create item even if loadOptions return array of items.

**Comment by alexjesp** [comment]
@Vinayaktech Seems like the repo #1374 didn't include the `npm run build` step? Meaning the dist & lib files don't include the changes from that PR 😞

**Comment by maxnowack** [comment]
It would be great if someone can run the build step and publish a new version to npm.
ping @JedWatson

**Comment by cmodzelewski** [comment]
Thanks for catching this, @Vinayaktech ! I spent half the day trying to debug this exact issue: I was staring at master in GitHub saying to myself "This SHOULD be working, but..." and pulling my hair out. 

Seems like it should be a super straightforward thing for @JedWatson or someone to build/publish to npm so we can continue using React-Select: It's a great piece of code that has been saving us tons of time - this little hiccup notwithstanding. 😄

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
