### ISSUE TITLE
Virtual keyboard not opening in Edge

### ISSUE THREAD

**Issue by Eirik-** [JedWatson/react-select#1461]
On Edge, it is not possible to type on the virtual keyboard while the dropdown is displayed.

When using a Windows touch device and the Edge browser, the virtual keyboard won't appear when selecting the React-Select component.

Tested on http://jedwatson.github.io/react-select/ 

Closing the dropdown by clicking on the arrow icon will make the keyboard appear - so it might have something to do with which field is focused. The input field appear highlighted when the dropdown is closed.

On safari iOS 8,9,10 there is no issues.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
