### ISSUE TITLE
Why limit the option values to string, number & boolean

### ISSUE THREAD

**Issue by aobo-y** [JedWatson/react-select#1462]
I wish to treat the `Immutable.map` as the option value to `react-select`, everything works fine except the following line forbid it to correctly render the `label`

https://github.com/JedWatson/react-select/blob/master/src/Select.js#L586

I am curious why cannot allow to pass other types either `object` or `immutable` as value, since basically `react-select` just treat the first shallow equal option as selected

https://github.com/JedWatson/react-select/blob/master/src/Select.js#L589-L591

```javscript
		for (var i = 0; i < options.length; i++) {
			if (options[i][valueKey] === value) return options[i];
		}
```
therefore as long as `options[i][valueKey] === value`, why does the `type` matters?

**Comment by begincalendar** [comment]
@JedWatson Could we please get some feedback on this?

I'm not familiar with the internals, but I did some experimentation and non-string/number/boolean values appeared to work fine.

I realise that there is some stringification going on for producing the "input" elements, but if we aren't using that feature is there anything else preventing us from doing this?

**Comment by begincalendar** [comment]
@agirton

**Comment by th3fallen** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
