### ISSUE TITLE
Issue with screen reader (Jaws) in IE11

### ISSUE THREAD

**Issue by fterlid** [JedWatson/react-select#1463]
When using Jaws and IE11, the wrong option is read if the user types in the input field.

For example: In the Multiselect in the [example page](http://jedwatson.github.io/react-select/), if the user types "am", The "Caramel" option is currently highlighted/selected, but Jaws reports "Chocolate" to be the currently selected option.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
