### ISSUE TITLE
the dropdown expand behind button 

### ISSUE THREAD

**Issue by Peakdrum** [JedWatson/react-select#1467]
I am trying to expand the dropdown and it appear behind a button. Can you please help? 
![react-select-error](https://cloud.githubusercontent.com/assets/15135266/21705885/61231f5a-d3f5-11e6-92a3-2b2d25eafc82.png)

**Comment by RohanDamani** [comment]
This is a CSS issue, add a z-index to the class corresponding to the dropdown

**Comment by chobo2** [comment]
I have 2 selects on my page. I did this fix and only one of them gets fixed.

**Comment by turnerniles** [comment]
See prateekjahead's comment: https://github.com/JedWatson/react-select/issues/1010
"HubSpot's [react-select-plus](https://github.com/HubSpot/react-select-plus) takes in dropdownComponent as a prop which solves the issue."

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
