### ISSUE TITLE
Tags- handleDelete option to make component compatible with Redux

### ISSUE THREAD

**Issue by RohanDamani** [JedWatson/react-select#1469]
An option to handleDelete is necessary to customize the onChange/click handler when deleting a tag, for use with frameworks like redux where you have to dispatch an action to change state, instead of using setState.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
