### ISSUE TITLE
after selecting value - still 'Select-placeholder' appears rather than 'Select-value'

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#1470]
after choosing a value from the list - how can i see it updating inside the 'Select-control' ?

Thanks.

**Comment by TimMeade** [comment]
Also.    Still stays on value or the placeholder.

**Comment by User8765** [comment]
Apparently I passed the 'label' instead of the 'value' - which is the key.
maybe you have the same problem?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
