### ISSUE TITLE
Help finalising 1.0 and the future

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#1481]
Hi everyone! Happy New Year 🎉 

Thanks for all the support with react-select. There's been a heap of really positive feedback, issues raised and PRs on the project, and it's getting an incredible amount of usage. With over 5,700 stars, 1,300 forks and more than 270k downloads per month on npm react-select has been way more popular than I could ever have expected. It's crazy and awesome.

As everyone watching the issue tracker can tell, the flip side to the popularity and broad usage is that as one of several open source projects I maintain I've ended up buried under a mountain of issues and PRs that I'd love to stay on top of but in the last few months haven't been able to.

But it's a new year, and time to get back on top of things, so I need some help 😄 

Immediately, there are a heap of issues and PRs to triage - more than I could tackle in a week, full time. 

So my plan is currently this:

1. Get help identifying the PRs that fix immediate issues (not major changes or functional additions) or any critical issues without fixes that would block releasing 1.0.0 as stable.
2. Merge those, ensure the demos and docs are up to date, and release.
3. Add some maintainers to help with the ongoing triage and establish a regular release schedule
4. Establish a roadmap for major improvements and new features we can work on this year

It would be really helpful if anyone tracking a PR that's *ready to merge* (and fixes issues, no major additions) could link to it with a brief explanation below. The same with any issues that I *really* need to deal with pre-1.0.0. I'll then organise these into a project so we can track progress.

Also, a few people have offered to help out as a maintainer - if that's you, I'd like to get a canonical list of who's currently interested (and has time) so please add your name in the comments.

Finally, if you're using the project somewhere cool, feel free to add that too. It's really nice to know.

Thanks!

**Comment by MarkLeMerise** [comment]
Hey, @JedWatson, I should be able to set some time aside to help. One common thread I've seen in issues is the need for reproducibility. At one point I was working on a CodePen and/or JSFiddle template for easy issue reproduction. Not sure if that's in the to-do list anywhere but I think it'd help many people!

**Comment by banderson** [comment]
@JedWatson reporting for duty 🙋‍♂️

I work with @tburnham and we created HubSpot/react-select-plus to address blockers we had, but of course we'd rather help push the core project forward instead of diverging. Volunteering to contribute however we can!

**Comment by jooj123** [comment]
@JedWatson happy new year !
Add me to that list please

Chatted briefly to you at the react meetup - I work at domain. 
Happy to help where I can :)

**Comment by hoodwink73** [comment]
Hello @JedWatson et al.
I really appreciate react-select. 

A project which extends input fields gets large in breadth by various user requirements and edge cases. I had seen the same happening to [selectize-js](https://github.com/selectize/selectize.js).

Thank you for your efforts.

Here's is something which I am awaiting for in the stable version.

When a user writes anything inside a `Creatable` component but does not commit the value to the field and blurs away, the prompt text on the component fails to reset itself on the next focus.

![react-select-prompt-text problem](https://cloud.githubusercontent.com/assets/1285699/21960795/3ca6dc38-db1c-11e6-9d1f-15c21b219440.gif)

The pull request #1306 already addresses this. You guys, @bvaughn and @JedWatson, have already taken a look at it.

There are also some outstanding issues related to this like #1256, which you can close if the pull request is merged.

Hope you guys have a great year ahead.

**Comment by vagnerj** [comment]
Hello, 
 this PR #1331 is ready to merge and fixes missing focus() method for Async.Select, I suppose more devs would be happy :)

credits to the PR issuer!

**Comment by nraynaud** [comment]
Hi, 
this PR #1406 focuses the next item after a click instead of selecting the first of the list. 
It's convenient for very long lists.

**Comment by dave-clover** [comment]
I am very interested in becoming a maintainer. My company (Clover Health) uses this library extensively and we'd like to contribute back to the original repo. We have a fork with a number of important bug fixes.

A general comment since this is the thread about the future: too many PRs are merged without tests. I'm particularly interested in helping expand their coverage.

**Comment by banderson** [comment]
@dave-clover I'm also interested in helping to push the testing initiative forward. Down to work together however we can to make this project more stable 👍

**Comment by agirton** [comment]
Hi @JedWatson I use this component extensively and would love to join as a maintainer or really help where we can.

**Comment by balloob** [comment]
Happy new year to you too! This project is awesome.

To reduce the flow of new issues, it would help to put out another RC on NPM so people would at least no longer report issues that have already been addressed.

**Comment by shinzui** [comment]
Is it possible to set some expectations? I am torn between forking and applying the needed patches, or waiting for you to start releasing fixes.

**Comment by robertmaloney** [comment]
Not sure where to put this, but I noticed that the Plunker bug reporting template didn't support ES6, so I ported it over to JSFiddle. You can fork it here: https://jsfiddle.net/3L1913xc/

**Comment by chriddyp** [comment]
> Finally, if you're using the project somewhere cool, feel free to add that too. It's really nice to know.

Huge thanks to all of the maintainers! We've been using react-select over at Plotly in our online chart creator (https://plot.ly/create). React-select has been an absolute godsend. We use the search, multi-select, and custom renders. Our users love the dropdown. Big thanks!

![column-dropdown](https://cloud.githubusercontent.com/assets/1280389/22572496/69316a98-e972-11e6-9d62-1267a7d31016.gif)

**Comment by seanlindo** [comment]
I'm very much interested in joining an open source project and contributing back. No hyperbole, I depend on this library heavily along with `react-virtualized-select` to help sourcers and recruiters do everything from tagging candidates to searching a list of 1,000+ industries. 

Would love to help!

**Comment by dherran** [comment]
As stated in the previous thread for the 1.0 pre-launch, I'd be happy to help out with bugfixes or reviews. I have a fork with a multi-select feature waiting to be merged and I use react-select in one major side project.

**Comment by MrLeebo** [comment]
@JedWatson, thank you for contributing your time and energy into making this!

#773 is ready to merge. Fixes a bug where clearing a non-multi select control's selection by pressing Backspace causes the onChange event to pass `[]` instead of `null`.

I'd be happy to help get the Issue List under control by closing duplicates or "please debug my code for me"-type issues as a maintainer, also.

**Comment by beardedtim** [comment]
@JedWatson My team and I use this package for one of our projects and I would love to help the repo wherever I can.

**Comment by mcorteel** [comment]
@JedWatson The issues list is getting a little out of hand, is there a plan for the future?
There seems to be a huge community using your component (and waiting for a stable 1.0), should the community fork your work and continue maintaining it elsewhere or do you think that you will find time to maintain it in the near future?

Anyway, thanks a lot for this great component!

**Comment by julien-f** [comment]
If the list of issues is too big to triage, it may be useful to close the least recently updated ones with a message saying that the issue has been closed automatically but the users should feel free to comment on it if it's still relevant.

**Comment by bvaughn** [comment]
@mcorteel Would you be interested in contributing? If so, I bet Jed would love to get your help with some of these issues and PRs!

**Comment by mcorteel** [comment]
Why not, at least I can help triage issues.

**Comment by dave-clover** [comment]
Consider using a milestone or project to identify critical fixes needed for a 1.0 release.  A lot of issues are feature requests and can definitely be delayed until a stable 1.0 release is ready.  There are so many open issues right now it's a little overwhelming to figure out where to start.

Apologies for saying this again, but we need more tests in PRs.  I'm seeing a lot of regressions being reported.

**Comment by Stenerson** [comment]
@JedWatson #1436 is ready to merge (even contains doc and a test 😱)

It adds an option to @bvaughn's excellent `Creatable` component that will optionally place the "Add" row on the bottom of the list rather than the top. This is particularly important when you don't want to encourage your users to add a new item but you want the option to be available in case they need it. Having the creatable item show up at the *end* of the list greatly reduces my users from adding new items accidentally.

Thanks - and count me in for helping triage, answer questions and contribute additional PRs in the future. I ❤️ react-select!

P.S. Merging #1436 will also allow you to close #1416

**Comment by broncha** [comment]
@JedWatson This tiny fix https://github.com/JedWatson/react-select/issues/1805 can also go in the next release :)

**Comment by marlonmleite** [comment]
Is this repository abandoned?
Since May we have no release. I am impressed as something so good, it has many bugs and several PR and ISSUES opened.
We have a lot of problems in this lib here in the company and we are starting to hate him lol

**Comment by agirton** [comment]
@marlonmleite this project has not been abandoned. We've just been busy with our full time responsibilities outside of open source.

**Comment by marlonmleite** [comment]
@agirton Do you need help? Depending I can contribute. I see many open PR and many issues with critical errors.
Is there a new release forecast?

**Comment by bvaughn** [comment]
> We have a lot of problems in this lib here in the company and we are starting to hate him lol

Probably just poorly chosen words, but... 😄 `react-select` is MIT licensed, meaning that you are free to fork it at any point if a [for-profit] business is using it and isn't happy with the response time of [volunteer, unpaid] contributors.

I realize there's a time investment in ramping up on a new project like this, but on the other hand, worst case is you've gotten a great head start essentially for free from the community.

**Comment by JedWatson** [comment]
I'm very happy to announce that 1.0 is out of beta, finally - with massive thanks to some major contributors including @gwyneplaine, @Noviny, @bvaughn and @agirton for their help.

**Comment by bvaughn** [comment]
Partaaaaay 🎊 🎈 Great work Jed!

**Comment by agirton** [comment]
Woohoo 🎉🍾! Great work @JedWatson!
