### ISSUE TITLE
Filtering Menu not visible inside ag-grid cell

### ISSUE THREAD

**Issue by YPBS** [JedWatson/react-select#1483]
I am using ag-grid with react-select. Issue is, when user starts typing in react-select the component is always bound within container of ag-grid cell due to which its filtered options are not displayed. 

Please find link to screenshot: http://imgur.com/XLanEE3 ,  I tried setting z-index, height on 'Select-menu-outer' class but nothing worked out. 

Is there any property/style that can be modified to display the dropdown menu beyond height on ag-grid cell.

**Comment by turnerniles** [comment]
See prateekjahead's comment: https://github.com/JedWatson/react-select/issues/1010
"HubSpot's [react-select-plus](https://github.com/HubSpot/react-select-plus) takes in dropdownComponent as a prop which solves the issue."

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by Sampathsampi** [comment]
Guys.
I m also facing the same issue
you got the solution for the issue.
