### ISSUE TITLE
Uncaught TypeError: Cannot read property 'PropTypes' of undefined

### ISSUE THREAD

**Issue by thoshith** [JedWatson/react-select#1484]
This warning is not going away. Even after lot of research didn't get any clue about this.
Its getting react select from https://npmcdn.com/react-select@1.0.0-rc.2/dist/react-select.js

react-select.js:36 Uncaught TypeError: Cannot read property 'PropTypes' of undefined
    at Object.<anonymous> (react-select.js:36)
    at Object.1../Select (react-select.js:207)
    at s (react-select.js:1)
    at react-select.js:1
    at Object.<anonymous> (react-select.js:707)
    at Object.5../Async (react-select.js:1847)
    at s (react-select.js:1)
    at e (react-select.js:1)
    at react-select.js:1
    at react-select.js:1

### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by jonfairbanks** [comment]
Seconding this. `Cannot read property 'PropTypes' of undefined` error causes React-Select inputs to not open breaking functionality.

**Comment by iNeedCode** [comment]
I'm also getting the error although my form is processing correctly.

```
Uncaught TypeError: Cannot read property 'PropTypes' of undefined
    at Object.<anonymous> (react-select.js:36)
    at Object.1../Select (react-select.js:207)
    at s (react-select.js:1)
    at react-select.js:1
    at Object.<anonymous> (react-select.js:707)
    at Object.5../Async (react-select.js:1847)
    at s (react-select.js:1)
    at e (react-select.js:1)
    at react-select.js:1
    at react-select.js:1
```

Any idea why this is popping up?

**Comment by frozegnome** [comment]
Getting the same error on my end: `TypeError: Cannot read property 'PropTypes' of undefined` 

Hoping someone could shed some light on this

**Comment by thoshith** [comment]
Guys there was double import.. removing this import statement resolved the warning in console.
https://npmcdn.com/react-select@1.0.0-rc.2/dist/react-select.js

**Comment by thoshith** [comment]
As mentioned in readme.. 
We should import all the dependencies also if we are manually importing the js.
else just a line a react require should be fine.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
