### ISSUE TITLE
Select never loads up, just keeps 'loading' from async

### ISSUE THREAD

**Issue by dnbr2002** [JedWatson/react-select#1485]
So I think im pretty close but I can't get the dropdown to load.  It just keeps 'loading' it seems.  

![react_loader](https://cloud.githubusercontent.com/assets/19315113/21955761/6c15f13a-da3f-11e6-9eb0-a6ac9c2be6ad.JPG)

Im using async fetch which is retrieving my data nicely.  Here is my fetch:

var getTier1 = (input) => {
  fetch(`/tier/` + 1)
    .then(function (response) {
      return response.json();
    }).then(function (json) {
      console.log('REACT::EVENTERHOME::CDM::PARSEDJSON', JSON.stringify(json));
      console.log('REACT::EVENTERHOME::CDM::PARSEDJSON', { options: json });
      return { options: json };
    }).catch(function (ex) {
      console.log('REACT::EVENTERHOME::ERROR GETTTING TIER1-', ex)
    })
}

here is my render:

       <Select.Async
          name="form-field-name"
          loadOptions={getTier1}
          />

my console logs look good in the dom.  Im seeing the data.  here is snip of the it.

![comps](https://cloud.githubusercontent.com/assets/19315113/21955830/bc562f92-da40-11e6-889f-811cdf26dc0e.JPG)
  

So am i missing anything??  I just installed react-select yesterday so Im assuming I have the latest and greatest version for my project.  Please let me know if Im missing anything.

**Comment by hyeomans** [comment]
hey could it be that you're not returning the fetch promise?
Instead of:
```
var getTier1 = (input) => {
fetch(/tier/ + 1)
...
```

can you do:
```
var getTier1 = (input) => {
return fetch(/tier/ + 1)
....
```

**Comment by dnbr2002** [comment]
@hyeomans so i tried using the return but I get this error now.  

Basically I switched back to what the original example had:

    var getOptions = (input) => {
      return fetch(`/eventers/` + 1)
      .then((response) => {
        console.log('REACT::EVENTERHOME::CDM::PARSEDRESPONSE', JSON.stringify(response.json));
      return response.json();
    }).then((json) => {
          console.log('REACT::EVENTERHOME::CDM::PARSEDJSON', JSON.stringify(json));
      return { options: json };
    });
    }

    <Select.Async
      name="form-field-name"
      loadOptions={getOptions}
      />

But all i get is this now.  

![image](https://cloud.githubusercontent.com/assets/19315113/21996847/2a2c707a-dbfa-11e6-8b6f-624fa32eabf1.png)


I was able to make it work but not using Async.  Basically I loaded the items into an array and just passed the array to options in Select.  It works.   Its just not the Async methodology.

**Comment by hyeomans** [comment]
@dnbr2002 that's strange, could you post the whole file?
As a side note, I had a similar problem, and reading through this [example](https://github.com/JedWatson/react-select/blob/master/examples/src/components/Contributors.js) I was able to get it working.

**Comment by dnbr2002** [comment]
I appreciate the help but I decided to go with a selectable table.  It fit my needs better for what I wanted to do.  If I need a drop down I'll revisit this then.  Im going to close the issue for now.   Probably some user error on my end.  Thanks again!
