### ISSUE TITLE
When searching - line of search goes beyond the width

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#1486]
![image](https://cloud.githubusercontent.com/assets/5032785/21962350/744d39ba-db2c-11e6-82d1-352f4412bc36.png)

is there a way to control this?

**Comment by User8765** [comment]
solution: 
set prop 'autosize' - false

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
