### ISSUE TITLE
How to debug & change css of the outer menu wrapper?

### ISSUE THREAD

**Issue by wellnine** [JedWatson/react-select#1487]
Hi Jed. I want to debug and change some position of the dropdown menu wrapper but how I can do this if the dropdown is always closed when I am trying to select it in a devtool ? How I can do that? Thanks!

P.S. maybe it will be good to allow user to disable that feature (hide menu on an outside click).

**Comment by alansalnikov** [comment]
I've run into this as well. How I've been able to get at the styles is throw a `debugger` in onBlur and then, in chrome dev tools at least, you can go to the elements tab and mess around with the styles while the script is paused.

**Comment by wellnine** [comment]
Thank you a lot. Because I disabled this possibility into the plugin source code and it's a little bit boring to do it again when I want to change something. Your solution looks nice and better.

**Comment by joaoahmad** [comment]
@wellnine you can use react dev tools and change `isOpen` state too.

**Comment by agirton** [comment]
@wellnine @joaoahmad recommendation is the best way to debug the CSS . This allows our API surface to be small.

**Comment by janakp2411** [comment]
Thanks @alansalnikov  it's working onBlur={()=> { debugger}}

**Comment by tuanluu-agilityio** [comment]
Thanks @alansalnikov @joaoahmad 
``` 
onBlur={()=> { debugger }}
```
Its work fine! :)
