### ISSUE TITLE
Select.Async prefill

### ISSUE THREAD

**Issue by Smike16** [JedWatson/react-select#1488]
Hello, everybody!

I have the following issue:

I'm using Select.Async component. User fills the form and saves it. And then user can open the page with filled form. But how can I show filled value in async select? (options are not loaded yet)

PS. Thank you for for react-select!

**Comment by holyman2k** [comment]
do something like 
    getItems(input, callback) {
        const { selecteditem } = this.props;
        if (input.length == 0 && selecteditem) {
            const defaultItem = { ...selecteditem, value: selecteditem.id.toString(), label: selecteditem.label };
            callback(null, { options: [defaultItem], complete: true });
            return;
        } else {
            searchForItem(callback);
        }
    }

**Comment by Smike16** [comment]
thank you holyman2k for reply, ill try it in monday

**Comment by jariwalabhavesh** [comment]
@holyman2k 
complete: true is not working, beacuse i am returning it true still it will call loadOptions function again when i am searching in textbox.

**Comment by Smike16** [comment]
oh, guys, my bad, forgot to write here. i've tried it and it didn't work out.

**Comment by jpacora** [comment]
complete: true is not working here too.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
