### ISSUE TITLE
Types.Select with comma in text getting cut off 

### ISSUE THREAD

**Issue by WingedToaster** [JedWatson/react-select#149]
I have found a bug where if I put a comma in the label in the options the text after the comma gets cut off. The value in the respective hidden input field appears to be correct so this appears to be only an issue with the text that is displayed. I have tried both an array of string and an array of dictionaries.

```
income: {
    type: Types.Select,
    options: [
        {value: 'Less than $20,000', label: 'Less than $20,000'},
        {value: '$20,000 to $49,999', label: '$20,000 to $49,999'},
        {value: '$50,000 to $79,999', label: '$50,000 to $79,999'},
        {value: '$80,000 to $99,999', label: '$80,000 to $99,999'},
        {value: '$100,000 to $149,999', label: '$100,000 to $149,999'},
        {value: '$150,000 or more', label: '$150,000 or more'}
    ]
},
```

![select-bug-example-1](https://cloud.githubusercontent.com/assets/4502315/7363401/7394e068-ed3f-11e4-8c23-fcfc6c8a2b9d.png)
![select-bug-example-2](https://cloud.githubusercontent.com/assets/4502315/7363402/7396a312-ed3f-11e4-8536-984c47dc1c9c.png)

**Comment by WingedToaster** [comment]
It appears this issue is occurring because <code>this.getStateFromValue</code> is called twice in Select.js when making a new selection: once by the <code>setValue</code> and once again by <code>componentWillReceiveProps</code>. If I comment out <code>this.fireChangeEvent(newState);</code>, I stop getting the extra call to <code>componentWillReceiveProps</code> but I'm not sure at this point what other issues that might cause. Thoughts?

**Comment by WingedToaster** [comment]
fork for reference: https://github.com/WingedToaster/react-select/commit/50fe1cfd993193115199a3803dc6a2f2dc0c42c0

**Comment by WingedToaster** [comment]
In case anyone from Keystone happens across this, I created <a href="https://github.com/keystonejs/keystone/pull/1442">PR #1442</a> on keystone as a work around for this issue.

**Comment by olwen1987** [comment]
Isn't is good to ignore splitting when delimiter is not provided than applying a default delimiter of ',' for the initial values that are passed? Somehow the Hack for this of using "|" doesnt look good .
