### ISSUE TITLE
default value is not showing up for Async Options React-Select

### ISSUE THREAD

**Issue by anvk** [JedWatson/react-select#1491]
Hi there,

I tried to use React-Select + Async Options in my project and was not able to make it display value when the page is just loaded.

It is easy to reproduce in the React-Select GithubUsers.js example. If I set default state value to be 872310 (which is Jed Watson GitHub user ID) React-Select will show Select... entry like nothing is selected. Also if I set multi={true} I would be able to see `x` icon to remove selection but still not value showing in the React Select.

Has anyone faced the same problem by any chance?

**Comment by anvk** [comment]
Nevermind. Fixed it by adding `initialized: false` into state of my component and pulling selected item from API based on the initial value inside of `loadOptions` following by setting `initialized` to be `true`

**Comment by ashgaliyev** [comment]
@anvk Can you share your solution? I've stuck with the same problem. I need to show the selected value in `AsyncSelect` but `defaultValue` is not working.

**Comment by harry-sm** [comment]
@anvk 
Could you explain what you did further?
