### ISSUE TITLE
Support for ES6 inheritance

### ISSUE THREAD

**Issue by derwaldgeist** [JedWatson/react-select#1492]
First off, thanks a lot for this good customizable control!

One thing, I am missing a lot is support for ES6 class inheritance. If you, for instance, want to create your custom values or options, you always have to copy the whole event handling part of the base implementation to make things work correctly. It would be much nicer and less error-prone if you could just inherit from the base class and add your own render method.

**Comment by VyvIT** [comment]
Why not use [HOC](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e#.7c92o6il1) for such case?

**Comment by hakunin** [comment]
Because when the only way to get the behaviour you need is to override a method (in my case the handleBlur one) you can't use it.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
