### ISSUE TITLE
How to access Value.onRemove from custom valueRenderer

### ISSUE THREAD

**Issue by tilds** [JedWatson/react-select#1493]
Hi, I am trying to create a multi select with a custom valueRenderer.

I would like the ability to remove individual values so I need something similar to the renderRemoveIcon () in Value.js.

But I can't figure out how to access the onRemove function from my valueRenderer.

Am I missing something, or how would you implement removing individual values from a multiselect with a custom valueRenderer?

**Comment by tonisostrat** [comment]
Check out this [comment](https://github.com/JedWatson/react-select/issues/1263#issuecomment-285890229).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
