### ISSUE TITLE
when there are two Async Select on the page both have autoload, only once loadOption function is called

### ISSUE THREAD

**Issue by holyman2k** [JedWatson/react-select#1494]
When there are two Async Select on the page both have autoload, only the first Select's loadOptions function is called.

**Comment by mantis** [comment]
@holyman2k i'm new to react and this control - but I've got three async selects on the page doing ajax queries from different url's and it seems to be working fine - so your issue may be elsewhere ;/

**Comment by holyman2k** [comment]
I get an error if I'm using callback.  I fixed the issue by returning the ajax call promise

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
