### ISSUE TITLE
Update Demo code: arrow navigation doesn't work there

### ISSUE THREAD

**Issue by ivanzusko** [JedWatson/react-select#1497]
First of all, want to say THANK YOU, @JedWatson , for such a great tool!

Guys, please, update [Demo page](http://jedwatson.github.io/react-select/) with latest code, because on Demo page navigation with arrows does not work. But, at the same time, the latest code I've forked from you works perfect on my local machine.

Thanks in advance!

P.S. it seems that npm package is not the fresh one too...

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
