### ISSUE TITLE
Shouldn't the isLoading state be set to true even if using autoload=true?

### ISSUE THREAD

**Issue by mikecargal** [JedWatson/react-select#150]
It looks like isLoading is not set to true in handleInputChange().  Shouldn't it also be set to true in autoloadAsynOptions?  WIthout that then you don't get the spinner while waiting for options to load when using autoload.

**Comment by mikecargal** [comment]
Guess I should have done this before posting the issue. 

By adding:
```javascript
  this.setState({isLoading: true});
```
to the autoLoadAsyncOptions function, I get the desired (at least, my desired) behavior)

**Comment by dcousens** [comment]
@mikecargal mind making a PR?

**Comment by dcousens** [comment]
> It looks like isLoading is not set to true in handleInputChange()

https://github.com/JedWatson/react-select/blob/master/src/Select.js#L397

@mikecargal is this issue still current? If so, do you mind making a PR?

**Comment by mikecargal** [comment]
Ah, I see what happened.  I said (in my first comment) that it was *not* set to true in handleInputChange().  I meant that, it *was* set to true there (apologies), but should also be set in autoLoadAsyncOptions() (At lest that fixed the issue for me).  It is still an issue.  Unfortunately, my company is still working through open source policies and has not approved us making PRs (yet, I'm working on it).

**Comment by dcousens** [comment]
@mikecargal any updates?

**Comment by mikecargal** [comment]
Sorry, should have responded.  

In this particular case, I ran into enough custom needs that I had to take the time develop my own, custom, component, so I don't foresee putting work into this particular component.

**Comment by dcousens** [comment]
Understandable.  Do you know if this is still a bug?

**Comment by mikecargal** [comment]
I don't, sorry

**Comment by gwyneplaine** [comment]
Closing this issue, if for some reason you feel that what I've described above doesn't correctly address your problem, please feel free to create a new issue. Mostly doing this for clarity ad to reduce our issues list down to a sane and relevant number of actionable tasks.
