### ISSUE TITLE
Add a prop to suppress menu rendering

### ISSUE THREAD

**Issue by john-hu** [JedWatson/react-select#1504]
As a user of AsyncCreatable, I want to hide the dropdown menu when no result is found. In this case, I would like to use Creatable to create an item for me where looks like a plain textbox.

BTW, I am using AsyncCreatable to write an email input box. In the case no result found, I would like to hide it.

**Comment by AlexanderTserkovniy** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
