### ISSUE TITLE
Multi select es6 example

### ISSUE THREAD

**Issue by elhenceapoorve** [JedWatson/react-select#1505]
Hello,
Is there an example for es6 Multi Select or can someone please post a snippet if you have it handy. I appreciate very much

**Comment by seanlindo** [comment]
`<VirtualizedSelect name="job-function-select"
                                    disabled={this.props.searchFormState.isError || this.props.searchFormState.isLoading}
                                    isLoading={this.props.searchFormState.isLoading}
                                    onChange={this.props.formHandlers.handleJobFunctionChange}
                                    options={this.props.searchFilters.jobFunctions}
                                    multi={true}
                                    value={this.props.searchFormValues.jobFunction}>
                                </VirtualizedSelect>`

**Comment by rubencodes** [comment]
Is there something you'd specifically like to see? All components/options are compatible with ES6... 

For example:
```
const { options, optionsLoading } = this.props; 
const { selectedOptions } = this.state; 
<Select
    value={ selectedOptions }
    isLoading={ optionsLoading }
    options={ options.map(({ id, name }) => ({ label: name, value: id })) }
    onChange={ (selectedOptions) => this.setState({ selectedOptions }) }
    multi />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
