### ISSUE TITLE
Adding a left/right variable to Value.jsx for placement of the remove icon.

### ISSUE THREAD

**Issue by ryanabooth** [JedWatson/react-select#1509]
For our project, and I think most of the web, it's expected for the remove/delete action to be on the right side of a label (Value in this case).

Can I submit a PR to allow you to specify which side the action is rendered, and default it to left?

(just sending this because on the contributing guidelines)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
