### ISSUE TITLE
Size of the box is not consistent

### ISSUE THREAD

**Issue by jeanmichelcote** [JedWatson/react-select#1510]
When the page loads, it looks fine. CSS loads and all.

But as soon as I click on the arrow to make a selection, the box shrinks to about 50px and even though I manage to select an option (although I only see the firsts few letters of the options), the placeholder still shows along with the 'x' (clear value), both superimposed. And all squished within the 50px box.

In other words, it does not show as intended, I am sure of that.

Any idea what causes this and how to fix?
Thanks

**Comment by jeanmichelcote** [comment]
So if I give a width in fixed pixel, like 150px, instead of the default '100%' to 'Select-control' class, it fixes the problem.

**Comment by jeanmichelcote** [comment]
So I went ahead and modified the `react-select/dist/react-select.css` file directly and it obviously fixed the problem.

But now, even though I select any option, the placeholder text always show and never goes away.

What is wrong?

**Comment by agirton** [comment]
Hi @jeanmichelcote this sounds like it has something to do with some dynamic css. Can you create a jsfiddle/codepen to reproduce this?

**Comment by jeanmichelcote** [comment]
Well, it is going to be hard to reproduce in a codepen, I am using the popular [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) as a base which, in turn, has integrated [styled-components](https://github.com/styled-components/styled-components) for the styling.

Not sure what to do next...
