### ISSUE TITLE
No reaction on value change

### ISSUE THREAD

**Issue by qwelias** [JedWatson/react-select#1511]
I'm using it with redux-form, and thus far I can't see any way of handling autofilled value.

A simple use case:
- 2 async react-select fields
- when first changes it autofills second's value
- second should trigger loadOptions to display a value (not happening)

**Comment by Ethaan** [comment]
did you find a workaround?

**Comment by qwemaze** [comment]
@Ethaan have to autofill the whole value and not just identificator.

**Comment by hbulgarini** [comment]
Hello @qwemaze  ! when you say "autofill the whole value" do you mean to set up the value attribute like t value={props.input.value} ?

Could you please paste the code of your workaround? Because i have the same need and it's being difficult to accomplish it ( update one select and trigger different actions beside changing the value of the dropdown itself )

Thanks!

**Comment by k8martian** [comment]
@hbulgarini , I think what @qwelias means is the value is actually an object with key and value inside. I managed to get the value populated but the select field did not show the value text and instead just showing the cross button(cancel button). Did you managed to get it work? mind to share? Thanks.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
