### ISSUE TITLE
complete:true is not working in loadOptions callback in 1.0.0-rc.2

### ISSUE THREAD

**Issue by jariwalabhavesh** [JedWatson/react-select#1514]
I am returning loadoptions callback with complete: true still it will call loadoptions function again on typing in textbox

```
loadOptions(input, callback) {
        const {AbInstance, filter } = this.props;
        return getDataFromServer({ AbInstance, filter }).then((response) => {
            callback(null, {
                options: response,
                complete: true
            });
        }, (error) => {
            callback(error, null);
        });
}
```

` <Select.Async value={value} clearable={clearable} disabled={disabled} onChange={onChange} valueKey={valueKey} labelKey={labelKey} loadOptions={loadOptions} backspaceRemoves={backspaceRemoves} autoload={true} searchable={true} noResultsText={noResultsText} placeholder={selectPlaceholder} searchPromptText={searchPromptText} autofocus={autofocus} />`

autoload is true so when select load first time it will call loadOptions function, and my loadOptions function taking all data from server and returning in callback with options and complete : true.

Still when ever i search in textbox it will calling loadOptions function again, i thing it should return data from cached result instead of calling loadOptions function again

Any idea, i am using 1.0.0-rc.2

**Comment by james-gardner** [comment]
Not working for me either on 1.0.0-rc.3.

**Comment by james-gardner** [comment]
Line 84 of Async.js and onwards. If anyone can give me a pointer around where the check for 'complete' should go then I'll make a PR. I would imagine that we force the use of the cache.

**Comment by shlajin** [comment]
Yes, bothers me as well. I made a search by "complete" substring through whole repository and there's indeed nothing related. Anybody know if this feature coming anytime soon?

**Comment by Rauttis** [comment]
Same issue here, loadOptions is ran multiple times despite `complete: true`

**Comment by gazpachu** [comment]
@JedWatson any idea of when will this get fixed? I mean the `complete: true` will actually work? I'm suffering this issue in a project in production, having to call the endpoint everytime the user types anything in the input. Thanks!

**Comment by kinyat** [comment]
RC 5 still have this issue :(

**Comment by juancarlosfarah** [comment]
I have the same issue with v1.0.1. Is this still broken?

**Comment by ryanhomer** [comment]
There were major changes in `Async.js` between v1.0.0-beta14 and the next tagged version, v1.0.0-rc.3, in which all references to `complete` were removed. Odd to see such a big change going from beta to RC.

**Comment by cclarks** [comment]
Was this ever fixed? I have the same issue persisting with v1.2.1.

**Comment by frankie-ug** [comment]
Still getting the same issues in v1.2.1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
