### ISSUE TITLE
Function onMenuScrollToBottom can not fires when the menu is scrolled to the bottom

### ISSUE THREAD

**Issue by Viktor-the-great** [JedWatson/react-select#1516]
resize the window in the browser chrome v55 and scroll to bottom.
https://plnkr.co/edit/HKvicJntbuxEH2PYPZid?p=preview
result is callback onMenuScrollToBottom is not called. A problem with this code block:
```javascript
handleMenuScroll (event) {
	if (!this.props.onMenuScrollToBottom) return;
	let { target } = event;
	if (target.scrollHeight > target.offsetHeight && !(target.scrollHeight - target.offsetHeight - target.scrollTop)) {
		this.props.onMenuScrollToBottom();
	}
}
```
When the browser is resized, scrollTop returns the fractional value, that why (target.scrollHeight - target.offsetHeight - target.scrollTop) is not equal to zero.
I propose to do so
```javascript
handleMenuScroll (event) {
	if (!this.props.onMenuScrollToBottom) return;
	let { target } = event;
	if (target.scrollHeight > target.offsetHeight && target.scrollHeight - target.offsetHeight - target.scrollTop < 1) {
		this.props.onMenuScrollToBottom();
	}
}
```

**Comment by dvijeshpatel** [comment]
hi @Viktor-the-great , can you tell me is issue fixed?

**Comment by Viktor-the-great** [comment]
the issue is no more relevant

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
