### ISSUE TITLE
Select.Async doesn't use default `noResultsText`

### ISSUE THREAD

**Issue by robertmaloney** [JedWatson/react-select#1518]
The README says that `noResultsText` has a default message of `No results found`, but because `Select.Async` uses the prop in order to handle `searchPromptText`, it must be manually passed in to be used.

See [here](https://github.com/JedWatson/react-select/blob/63a59dcececbc46e341a0b77be8af5b4da790c1d/src/Async.js#L164-L177).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
