### ISSUE TITLE
Is there anyway to set initial value that doesn't match options?

### ISSUE THREAD

**Issue by hyzhak** [JedWatson/react-select#1520]
Hello, I use `<Select>` control that should have the value defined from outside (by router url) and options are loading async depends on gotten value. Is there any way how to set initial value that doesn't match options?

Here is the basic example that doesn't work properly (It should have defined input field, but it is empty):

```javascript
var options = [
    { value: 'one', label: 'One' },
    { value: 'two', label: 'Two' }
];

function logChange(val) {
    console.log("Selected: " + val);
}

ReactDOM.render(
  <div>
    <h1>Update Value</h1>
    <div>How could set initial value that doesnt match options?</div>
    <Select
        name="form-field-name"
        value="three"
        options={options}
        onChange={logChange}
    />
  </div>,
  document.getElementById('example')
);
```

[https://plnkr.co/edit/yBDlgS?p=preview](https://plnkr.co/edit/yBDlgS?p=preview)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
