### ISSUE TITLE
onClose doesn't seem to fire when the menu is closed as a result of selecting an option

### ISSUE THREAD

**Issue by conradchan** [JedWatson/react-select#1524]
Hi all, thanks for the great library. 

I've added a component like so:
```
                    <ReactSelect.Async
                        cache={false}
                        clearable={false}
                        loadOptions={this.loadOptions}
                        multi={true}
                        onChange={this.onChange}
                        onOpen={this.setIsOpen}
                        onClose={this.setIsClosed}
                        onInputKeyDown={this.onInputKeyDown}
                        placeholder="Test"
                        value={someValues}
                    />
```
It seems from the debugger that setIsClosed (callback on onClose) is never fired after selecting an option (although it is fired when I close the menu by clicking away from the component).

The plunkr links in the template no longer work but hopefully this is enough to repro. I'm on 1.0.0-rc.3

For context, I'm trying to make it so that hitting when ENTER in the component calls a method if the menu is closed. I was planning to store isDropdownOpen using these callbacks so I could use that in onInputKeyDown. If there's a better way of doing this I'd love to hear it! Thanks.

**Comment by boycriedwolf** [comment]
+1, literally just faced this exact same issue

**Comment by piecyk** [comment]
@conradchan can you elaborate more what is your use case ? If you use `multi=true` then selecting value will not close menu....

**Comment by conradchan** [comment]
I'd like to have hitting the ENTER key call some method (i.e. to add the values at the time to some external list), but only if the dropdown menu is not shown. I was planning to track whether the dropdown menu was open or not using the onClose and onOpen callbacks when I hit this issue.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
