### ISSUE TITLE
Open Options / Async Request on Focus

### ISSUE THREAD

**Issue by feralbyte-luispinto** [JedWatson/react-select#1525]
Hi,

I Don't know if there is a some option / way to do this, i couldn't find it on documentation.

I would like to open options (Async ajax call) onFocus (with empty search), i dont want to use autoload, to avoid unecessary server calls.

Sorry my english,
Best Regards

**Comment by Dartv** [comment]
@feralbyte-luispinto How did you solve it?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by bladey** [comment]
Duplicate issue #2660 has more information.

**Comment by shpsyte** [comment]
Hello, any update on this?

**Comment by ebonow** [comment]
Greetings @shpsyte and others,

If you want to load a set of default options when the Select is rendered, you can use `defaultOptions={true}`

If you want to load a set of default options when the Select is focused, you can use the onFocus handler to call the lookup and set the default options to state.

Demo here: [codesandbox](https://codesandbox.io/s/react-select-default-options-onfocus-wcp2q)

```js

const promiseOptions = inputVal => someApiCall(inputVal);

export default class WithPromises extends Component {
  state = {
    isLoading: undefined,
    defaultOptions: []
  };

  onFocus = () => {
    if (!this.state.defaultOptions.length) {
      this.setState({ isLoading: true });

      promiseOptions("").then(defaultOptions => {
        this.setState({ defaultOptions, isLoading: undefined });
      });
    }
  };

  render() {
    return (
      <AsyncSelect
        loadOptions={promiseOptions}
        onFocus={this.onFocus}
        defaultOptions={this.state.defaultOptions}
        isLoading={this.state.isLoading}
      />
    );
  }
}
```

I will be marking this issue as closed, but if there are any other questions or concerns, this can be discussed further or reopened if necessary.
