### ISSUE TITLE
Proposal: Display error message when the Promise fails

### ISSUE THREAD

**Issue by oomathias** [JedWatson/react-select#1528]
When using `Select.Async`, if the promise fails the message displayed is `noResultsText` which is incorrect. The server may be overloaded or whatever, but it doesn't mean that there are no results.

Proposal: 

Add an `errorText` props, and/or even better use the error message sent back by the promise.

```js
errorText="Oops! Something bad happened."
```
/
```js
promise.then(
  (data) => callback(null, data),
  (error) => callback(error) // <= use this
)
```

**Comment by oomathias** [comment]
If anyone is interested, I did that as a workaround:

```js
.catch((error) => {
  callback(null, {
    options: [{
      value: 'error',
      label: 'Oops! Something bad happened.',
      disabled: true,
  }],
})
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by lazycipher** [comment]
Any direct support for this or still needs the workaround?
In `"react-select": "^3.0.8"` I had to use 
```js
callback([
        {
          value: 'error',
          label: err.message || 'Oops! Something went wrong!',
          isDisabled: true
        }
      ]);
```

**Comment by tylercollier** [comment]
It's too bad that this is the best strategy. I'm on version 5.3.2. I can confirm you need to do what @lazycipher shows, and not what @oomathias shows (any more). As in, it's not a node-style callback. To the callback you may pass only one argument, not `cb(null, ...)`. And it's `isDisabled: true`, not `disabled: true`.
