### ISSUE TITLE
Add a boolean for keeping the input value upon selection

### ISSUE THREAD

**Issue by omriavigdor** [JedWatson/react-select#1529]
Hi! Great library! :-)

I'd like to have a boolean exposed to determine whether to keep the input value after a value is selected from the list. Today, it gets cleared automatically in Select.js:617 (and in line 625, but I'm more interested in the multi case). 
I even have that change at hand, should you accept my proposal :-)

Thanks!

**Comment by dherran** [comment]
Already done here #882

**Comment by palashkaria** [comment]
@omriavigdor If I get this correct, what you are talking about is about setting <input> box's value to currently selected value, right?

@dherran's change is about something else I think

**Comment by omriavigdor** [comment]
@palashkaria Suppose I have a searchable multi-select. I input a search term and the list is filtered. However, when I choose 1 item, it's added to the box and the search term is gone. I would like to have a boolean ('false' by default to keep the current behavior) that will allow me to keep the search term, even after choosing an item. Sounds reasonable?

**Comment by jacobworrel** [comment]
any progress on this? or any known workaround?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
