### ISSUE TITLE
Package versioning made breaking changes pass for minor fixes

### ISSUE THREAD

**Issue by adrienharnay** [JedWatson/react-select#1531]
Hi,

With the way your package is versioned, today I ran npm i and got rest-select updated with some breaking changes, which should not happen (only with minor fixes).

Would you consider changing the way of versioning react-select?

Thanks in advance,

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
