### ISSUE TITLE
Support ignoring punctuation as: props.ignorePunctuation

### ISSUE THREAD

**Issue by wi-ski** [JedWatson/react-select#1534]
Hi there,

I recently ran into an issue where punctuation was causing the options list to not render when I typed terms that lacked the necessary punctuation.

Naturally - I wanted a prop (bool or regex) that would help me get around this. I thought this type of behavior would/could be in the same vein as the `ignoreAccents` && `ignoreCase` options.

https://plnkr.co/edit/Aq2rsSGqnWsdSzkT7EQE?p=preview

The above plunker illustrates my issue pretty well.

Provide `I'm` -> returns a populated list.
Provide `Im` -> returns empty list

Here's the PR: #1535

It has: 

a. The feature described above. Behavior is: Takes a boolean and defaults to this regex: `/[.,\/'#!%\^?&\*;:{}=\-_`~()]/g` (ignoring the characters in the options list) or can take a custom regex to ignore.
b. Pretty decent test coverage.
c. Updated Readme.

Unfortunately CI is failing with an issue that I cannot comprehend.  Any help would be totally appreciated. 0_0

**Comment by willdembinski** [comment]
Here's a PR I could some guidance on.  Any hints/suggestions/thoughts as to why this is failing CI? #1533
