### ISSUE TITLE
Categories Feature

### ISSUE THREAD

**Issue by fabioespinosa** [JedWatson/react-select#1536]
Thanks to the creators of react-select.

It is awesome, I use it in my website and it does wonders.

I know this is not the place to say this but I couldn't figure out any other way, I was thinking in implementing a new feature, what would you guys think.

Having categories, in react-select, so for example, say you wanted to search for a country or a city, as you start typing the first 5 countries that match will appear at the top of the dropdown with a top label saying "Countries" and perhaps an icon. Then the first 5 cities that match will appear at the bottom of the dropdown with a top label saying "Cities" and perhaps a cities icon as well.

I know the countries and cities example is probably not a real world one. However I've found myself wishing for this functionality in more than one occasion.  

What would you think of this new feature? Are there any plans of making it possible? Is it possible to achieve this right now? Or should I just get on to work with it. 

Thanks a lot.

**Comment by kevingilbert100** [comment]
To my knowledge, this is not possible.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
