### ISSUE TITLE
Dropdown is getting overlapped by second react-select. 

### ISSUE THREAD

**Issue by Jaikant** [JedWatson/react-select#1537]
Hey guys,  I have now been struggling for a few hours. I am having two react-select components.
The dropdown from the component on top is getting overlapped by the below component.

I added a z-index of 999 to  .Select-menu-outer, but it doesn't change anything. 
I have attached a screenshot of the issue. 

<img width="313" alt="screen shot 2017-02-07 at 4 29 22 pm" src="https://cloud.githubusercontent.com/assets/3472565/22688517/a6f310e6-ed52-11e6-9e7d-2937070edaa9.png">

**Comment by evgeniiteterin** [comment]
anyone solved this problem? menuContainerStyle={{ zIndex: 5 }} not work.

**Comment by turnerniles** [comment]
See prateekjahead's comment: https://github.com/JedWatson/react-select/issues/1010
"HubSpot's [react-select-plus](https://github.com/HubSpot/react-select-plus) takes in dropdownComponent as a prop which solves the issue."

**Comment by MaxInMoon** [comment]
By the way, zIndex doesn't has any effect on `position: static` elements

**Comment by mustafawm** [comment]
this worked for me
```
.Select-menu {
    position: fixed !important;
}
```

then I had to give fixed width to both the `input` and the `dropdown`, here is the css I changed:

```
.Select {
    width: 444px !important;
    margin-right: 5px;
    z-index: 0 !important;
}

.Select.is-open {
	z-index: 1 !important;
}

.Select-menu {
    position: fixed !important;
    width: 440px !important;
    margin: 1px;
}

```

**Comment by MaxTrans** [comment]
This Worked for me
.is-open {
	z-index: 100 !important;
}

**Comment by damianobarbati** [comment]
Not working for me either: anyone else managed to solve this?

**Comment by brianarpie** [comment]
v1.2.1

```
.Select.is-open {
    z-index: 1000 !important;
}
```

worked for me

**Comment by lounsbrough** [comment]
Any update on getting this resolved?

**Comment by d3mp** [comment]
@lounsbrough, this is worked for me:

v2.4.2
`const selectStyles = {
  menu: styles => ({
    ...styles,
    zIndex: 999
  })
};`

**Comment by lounsbrough** [comment]
@d3mp, yes, we implemented something like this and it's working in our environment.

Thanks.

**Comment by juliankigwana** [comment]
@d3mp is right. You need to target the element that has the absolute style, which is the menu.

```

menu: (styles, state) => ({
    ...styles,
    zIndex: state.menuIsOpen ? 100 : 1
})
```

**Comment by benkindt** [comment]
@d3mp thanks, this works! Use it like:
```
const selectStyles = { menu: styles => ({ ...styles, zIndex: 999 }) };
<Select styles={selectStyles} />
```

**Comment by Luke-Markham** [comment]
> @d3mp thanks, this works! Use it like:
> 
> ```
> const selectStyles = { menu: styles => ({ ...styles, zIndex: 999 }) };
> <Select styles={selectStyles} />
> ```

worked for me

**Comment by simonkaspersen** [comment]
This issue was made in 2017, and still is a issue? 
None of the solutions above works. The dropdown menu is hidden behind other components. `CSS`, `selectstyles` og `portal-component` was not successful.

**Comment by Jonny-B** [comment]
Same here. Menu is still falling behind.

**Comment by flexdinesh** [comment]
@simonkaspersen @Jonny-B are which version of `react-select` are you using?

Would you be able to create a codesandbox that replicates the behaviour? Would be easier to help if there's a code example in a codesandbox.

Also, you can try portalling as suggested here — https://github.com/JedWatson/react-select/issues/3263#issuecomment-445809701

**Comment by simonkaspersen** [comment]
@flexdinesh Have tried with the 3 last versions.

Will try. I am currently writing away some of the `react-select`-boxes

**Comment by simonkaspersen** [comment]
So I needed a combination of:
```js
menuPortalTarget={document.querySelector('body')}
```

and: 
```js
const selectStyles = {
    menuPortal: base => ({ ...base, zIndex: 9999 }),
    menu: provided => ({ ...provided, zIndex: "9999 !important" })
};

<Select 
    styles={selectStyles}
/>
```

**Comment by jossmac** [comment]
Default behaviour is correct, please see this [CodeSandbox](https://codesandbox.io/s/stacked-react-selects-ss98v).

**Comment by Dylan-Buth** [comment]
After messing with this for a while, and just going through every element removing styles until it worked, I realized the `overflow-x: auto` on a parent element was causing the issue.

**Comment by asadrazashah** [comment]
> So I needed a combination of:
> 
> ```js
> menuPortalTarget={document.querySelector('body')}
> ```
> 
> and:
> 
> ```js
> const selectStyles = {
>     menuPortal: base => ({ ...base, zIndex: 9999 }),
>     menu: provided => ({ ...provided, zIndex: "9999 !important" })
> };
> 
> <Select 
>     styles={selectStyles}
> />
> ```

**Comment by MenachemICTBIT** [comment]
After seeing the half dozen related issues, yet not finding a resolution, I have found one.

`<Select
menuPortalTarget={document.body}
            				menuPosition={'fixed'}
						/>`

Add these two options to your Select component. 

It appears to make us of the new React Portal feature.

**Comment by jperestrelo** [comment]
Thanks @MenachemICTBIT I Was struggling with the same without finding any satisfactory solution, this worked like a charm!

**Comment by MenachemICTBIT** [comment]
@jperestrelo Glad to hear it. I really struggled with this one as well.

The next problem then becomes that, since the menu is `position:fixed`, if you need to scroll the page the menu won't scroll with you. I managed a slight hack where I added an event listener that closes the menu when you scroll outside the menu itself (allowing scrolling inside the menu).

**Comment by debuurjongen** [comment]
I had a problem with a relative position of the Select component (fixed position was not an option), fixed it by creating a wrapper containing the status of open menu and updating the z-index based on state:

`const selectStyles = {
    container: () => ({ 
      position: 'relative',
      minWidth: '100%',
      maxWidth: 'auto', 
    })
};

const SelectWrapper = () => {

  const [menuIsOpen, setMenuIsOpen] = useState(false);

  return(
    <Select 
      styles={selectStyles}
      onMenuOpen={() => setMenuIsOpen(!menuIsOpen)}
      onMenuClose={() => setMenuIsOpen(!menuIsOpen)}
      styles={{ ...selectStyles, container: () => ({ ...selectStyles.container, zIndex: menuIsOpen ? 999 : 1 })}}
    />
)}`

**Comment by GodAlmighty990** [comment]
This solution worked for me.

const selectStyles = { menu: styles => ({ ...styles, zIndex: 999 }) };
<Select styles={selectStyles} />

I am creating an app with bootstrap react falcon theme using their wizardInputs and this worked for me. My wizardInput was bleeding through my react select menu. Hope this helps someone

**Comment by BagusJatikusuma** [comment]
> This solution worked for me.
> 
> const selectStyles = { menu: styles => ({ ...styles, zIndex: 999 }) }; I am creating an app with bootstrap react falcon theme using their wizardInputs and this worked for me. My wizardInput was bleeding through my react select menu. Hope this helps someone

thank you. it works.

**Comment by AshwinNema** [comment]
> @lounsbrough, this is worked for me:
> 
> v2.4.2 `const selectStyles = { menu: styles => ({ ...styles, zIndex: 999 }) };`

It helped. Thanks

**Comment by Dalton-Klein** [comment]
> > @lounsbrough, this is worked for me:
> > v2.4.2 `const selectStyles = { menu: styles => ({ ...styles, zIndex: 999 }) };`
> 
> It helped. Thanks

This did not work for me. No change in behavior.

**Comment by GodAlmighty990** [comment]
try this
const customStyles = {
 menu: base => ({
      ...base,
      // override border radius to match the box
      borderRadius: 0,
      // kill the gap
      marginTop: 0,
      zIndex: 999 // add the zIndex to your menu
    }),
}


 <Select
              name="keyword"
              required={true}
              className="mb-3"
              styles={customStyles}
              components={animatedComponents}
              closeMenuOnSelect={true}
              options={keywords}
              defaultValue={responder?.length ? responder[0]?.responder?.keyword?.map((el) => { return {title: el.title, _id: el._id}}): ""}
              getOptionLabel={({title}) => title}
              getOptionValue={({_id}) => _id}
            
            
            />

**Comment by GodAlmighty990** [comment]
> > > @lounsbrough, this is worked for me:
> > > v2.4.2 `const selectStyles = { menu: styles => ({ ...styles, zIndex: 999 }) };`
> > 
> > 
> > It helped. Thanks
> 
> This did not work for me. No change in behavior.

try this

const customStyles = {
   menu: base => ({
      ...base,
      // override border radius to match the box
      borderRadius: 0,
      // kill the gap
      marginTop: 0,
      zIndex: 999
    }),
}

<Select
              name="keyword"
              required={true}
              className="mb-3"
              styles={customStyles}
              components={animatedComponents}
              closeMenuOnSelect={true}
              options={keywords}
              defaultValue={responder?.length ? responder[0]?.responder?.keyword?.map((el) => { return {title: el.title, _id: el._id}}): ""}
              getOptionLabel={({title}) => title}
              getOptionValue={({_id}) => _id}
              onChange={(keyword) => setUpload({...upload, keyword: keyword === null ? [] : keyword})}
              isMulti
              placeholder="select Keywords"
              isSearchable={true}
              errors={errors}
              innerRef={register({
                required: "Add your Keyword"
              })}
            />

**Comment by amal-octilus** [comment]
hey guys mine is indside a model from headlessui
none of the above worked for me

below is my select component
```
import Select from "react-select";

function SearchableSelect({
    name,
    options = [],
    className = "",
    isMulti = false,
    customStyles = "",
    ...props
}) {
    return (
```
        <Select
            className={`basic-single h-10 ${className}`}
            classNamePrefix="select"
            defaultValue={props?.defaultValue ?? isMulti ? "" : options[0]}
            isMulti={isMulti}
            isClearable={true}
            isSearchable={true}
            name={name}
            options={options}
            styles={customStyles}
            {...props}
        />
    );
}

export default SearchableSelect;


<Modal show={showModal} className="!overflow-y-auto">
                    <form
                        onSubmit={submit}
                        className="space-y-5"
                        id={cellData?.id}
                    >
                        <div className="p-8">
                            <div className="grid grid-cols-1 gap-x-10 gap-y-5 md:grid-cols-2">
                                {modalContent == "editContent" &&
                                    editFormData?.map((d, i) => {
                                        return (
                                            <div key={i}>
                                                {!!d?.selectable && (
                                                    <BaseFormControl
                                                        name={d?.name}
                                                        label={d?.label}
                                                        placeholder={d?.label}
                                                        error={errors[d?.name]}
                                                        renderInput={({
                                                            type,
                                                            ...props
                                                        }) => (
                                                            <SearchableSelect
                                                                customStyles={
                                                                    customStyles
                                                                }
                                                                isMulti={true}
                                                                 options={
                                                                     d?.options
                                                                 }
                                                                {...props}
                                                            />
                                                        )}
                                                        onChange={(val) => {
                                                            setData(
                                                                d?.name,
                                                                val?.map(
                                                                    (d) =>
                                                                        d?.value
                                                                )
                                                            );
                                                        }}
                                                        onBlur={(e) =>
                                                            validate(
                                                                e,
                                                                d?.type,
                                                                d?.name,
                                                                clearErrors,
                                                                setError
                                                            )
                                                        }
                                                    />
                                                )}
                                            </div>
                                        );
                                    })}
                            </div>
                            <div className="flex justify-end gap-2 pt-[1.5rem]">
                                <button
                                    className="btn btn-primary"
                                    onClick={submit}
                                >
                                    Update
                                </button>

                                <button
                                    onClick={() => setShowModal(false)}
                                    type="button"
                                    className="btn"
                                >
                                    Close
                                </button>
                            </div>
                        </div>
                    </form>
                </Modal>

**Comment by AliBayatpour** [comment]
The same issue: none of the solutions worked, and react select shows over the popup...

**Comment by m-nathani** [comment]
This issue was still happening to me on   

```json
"react-select": "^5.8.0",
```

![image](https://github.com/JedWatson/react-select/assets/13331386/da91ad55-080b-41aa-815a-26f5b6a2de30)


```js
    <SelectTimeInput
      name="closesAt"
      placeholder="Close time"
      aria-label="close at time"
      ....
      // menuPortalTarget is needed to avoid dropdown getting overlapped by second dropdown
      // https://github.com/JedWatson/react-select/issues/1537
      menuPortalTarget={document.body}
    />
```

and solution for it was this: `menuPortalTarget={document.body}`  .

**Comment by rubylnic** [comment]
> menuPortalTarget={document.body}

thank you very much!

**Comment by shashankNivoda** [comment]
> v1.2.1
> 
> ```
> .Select.is-open {
>     z-index: 1000 !important;
> }
> ```
> 
> worked for me

This didn't work for me. Even though its we are on the same version.
My teammate suggested this CSS which worked out for me,

```
.Select-menu-outer {
    position: relative;
    z-index: 10;
  }
  ```

**Comment by 7shashank** [comment]
> v1.2.1
> 
> ```
> .Select.is-open {
>     z-index: 1000 !important;
> }
> ```
> 
> worked for me

This didn't work for me. Even though its we are on the same version.
My teammate suggested this CSS which worked out for me,

```
.Select-menu-outer {
    position: relative;
    z-index: 10;
  }
  ```

**Comment by tarcisiowcastro** [comment]
> This issue was still happening to me on
> 
> ```json
> "react-select": "^5.8.0",
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/13331386/305775944-da91ad55-080b-41aa-815a-26f5b6a2de30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTg2NjksIm5iZiI6MTcyOTI5ODM2OSwicGF0aCI6Ii8xMzMzMTM4Ni8zMDU3NzU5NDQtZGE5MWFkNTUtMDgwYi00MWFhLTgxNWEtMjZmNWI2YTJkZTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAwMzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNGJkY2Y3MWI3OGZkMGE5NmZiYmQ3ODljODc1OGVkMzNmNmZkYTViMjdjZmYwYzZlMzkwZTFhZjcxOWI1ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vUuLV-4BHsHAfxF_6UejIT6SOLMb_XVEiczL5CnMJ44)
> 
> ```js
>     <SelectTimeInput
>       name="closesAt"
>       placeholder="Close time"
>       aria-label="close at time"
>       ....
>       // menuPortalTarget is needed to avoid dropdown getting overlapped by second dropdown
>       // https://github.com/JedWatson/react-select/issues/1537
>       menuPortalTarget={document.body}
>     />
> ```
> 
> and solution for it was this: `menuPortalTarget={document.body}` .

Thanks!

**Comment by tadiraman** [comment]
This worked for me!

```
  .Select__menu {
    position: relative;
  }
```

**Comment by elisabetta-p** [comment]
> This issue was still happening to me on
> 
> "react-select": "^5.8.0",
> 
> ![image](https://github.com/JedWatson/react-select/assets/13331386/da91ad55-080b-41aa-815a-26f5b6a2de30)
> 
>     <SelectTimeInput
>       name="closesAt"
>       placeholder="Close time"
>       aria-label="close at time"
>       ....
>       // menuPortalTarget is needed to avoid dropdown getting overlapped by second dropdown
>       // https://github.com/JedWatson/react-select/issues/1537
>       menuPortalTarget={document.body}
>     />
> 
> and solution for it was this: `menuPortalTarget={document.body}` .

this worked for me with `react-select: 5.10.1`!
