### ISSUE TITLE
Firefox browser with latest update 51.0.1 crashing on Windows

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#1538]
I have confirmed this issue, by removing react-select component from my pages and it works fine then. Else, browser goes into (Not Responding) mode.
This is live issue we are facing in our app on production. Please resolve it at earliest.

**Comment by peixian** [comment]
Heyo: https://github.com/JedWatson/react-select/issues/1521

**Comment by sabapk** [comment]
Resolved this issue.

So our code base, was using react-select `Select` Component syntax with each prop to be on new line.
So, we changed our code style to write props inline and surprisingly this one change resolved our issue of browser crashing.

`<Select options = {timezones} value = {timezone} />`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
