### ISSUE TITLE
Weird focus behaviour wiht react-datepicker

### ISSUE THREAD

**Issue by tume** [JedWatson/react-select#1539]
There is already issue in react-datepicker: https://github.com/Hacker0x01/react-datepicker/issues/730 

Posting here also because not certain which component should fix this. 

I have repository for reproducing it here: https://github.com/tume/select-datepicker-conflict

You can see the issue when first opening the calendar and then switching to react-select.
I have some more speculation about the cause in react-datepicker issue but it looks like to be problem with onBlur/mousedown event ordering if I'm correct. Would appreciate if you have any comments on this or how to fix it....

**Comment by buz-zard** [comment]
Same here:
`"react-datepicker": "^0.40.0"`
`"react-select": "^1.0.0-rc.3"`

Also focusing on ordinary input doesn't flicker, just react-select input produces this.

**Comment by ibcWillJust42** [comment]
same problem

**Comment by gilbertKaradja** [comment]
I am starting to think its a problem with react-slect

**Comment by swbullis** [comment]
@gilbertKaradja I think your might be right here.  From what I can gather so far it looks like it might be react-select not allowing https://github.com/Pomax/react-onclickoutside to work or vice versa.

**Comment by JedWatson** [comment]
I'm pretty sure this is an issue with the way react-datepicker is asynchronously refocusing the input when it is blurred. I don't totally understand the use case for that though, so it might be important to support. Will comment on that project to learn more.

**Comment by theGABS** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
