### ISSUE TITLE
Removing completely the create new option label

### ISSUE THREAD

**Issue by junibrosas** [JedWatson/react-select#1543]
The library is very cool and very customisable. I am having a hard time removing completely the "Create option 'x'" label. I can use promptTextCreator={(label) => ''} but there is still empty tag remain. I want to completely remove the label but still able to add new option via key down.

**Comment by sandinosaso** [comment]
How about:

`promptTextCreator={(label) => label ? `Adding ${label}` : undefined}`

**Comment by joaoeffting** [comment]
@sandinosaso It doesn't worked to. Still a "empt" space in the selects 

![problema_select](https://cloud.githubusercontent.com/assets/7833788/24776384/ddf7940a-1af6-11e7-8426-386d5d1df416.png)

**Comment by brunoarueira** [comment]
Hey @joaoeffting and @junibrosas,

I have found a solution for this problem, it's a workaround.

```
<Select.Creatable
  onChange={this.onChange}
  promptTextCreator={() => false}
  newOptionCreator={({ label, labelKey, valueKey }) => {
    const show = !label

    const option = {}
    option[valueKey] = label
    option[labelKey] = label
    option.className = classnames(
      'Select-create-option-placeholder',
      [styles.hide_placeholder]: show,
    )
    return option
  }}
  value={this.props}
  options={this.props.options}
  isLoading={this.props.fetching}
  labelKey="name"
  valueKey="id"
/>
```

```
.hide_placeholder {
  display: none !important;
}
```

The main trick is:

- First set the ```promptTextCreator``` to return false:

```
  promptTextCreator={() => false}
```

- And after, define a ```newOptionCreator``` to handle that option, like so:

```
  newOptionCreator={({ label, labelKey, valueKey }) => {
    const show = !label

    const option = {}
    option[valueKey] = label
    option[labelKey] = label
    option.className = classnames(
      'Select-create-option-placeholder',
      [styles.hide_placeholder]: show,
    )
    return option
  }}
```

It's still a thick line, but someone could improve this. My css skills are limited.

**Comment by jnachtigall** [comment]
@brunoarueira I simply used this to disable (not show) the `promptTextCreator`:
```
.Select-create-option-placeholder {
  display: none;
}
```
Not sure why you need to use `newOptionCreator` for this because the `promptTextCreator` has a uniq css class with `.Select-create-option-placeholder` that can be used for this.

**Comment by brunoarueira** [comment]
@jnachtigall Great, when I return to the feature which uses the react-select I'll try your suggestion! Thanks, btw

**Comment by bbinoy** [comment]
You can just use ```isValidNewOption=false```

**Comment by dwightware4** [comment]
> You can just use `isValidNewOption={() => false}`

I'm really confused about why this solution is so well received. This doesn't merely hide the create label, it completely disables the create functionality....if you don't want the create functionality, then why would you even be using Creatable in the first place?

I'm still struggling to find a way to hide the create label in the dropdown without completely breaking all functionality.
