### ISSUE TITLE
How to modify local react-select source?

### ISSUE THREAD

**Issue by rubencodes** [JedWatson/react-select#1553]
Hello,

I'm modifying the locally-installed copy of `react-select` in my node_modules directory, but the changes I make don't seem to be taking effect. (Tried restarting the server a few times, clearing the local cache, modifying the files in the `src/`, `dist/`, `.min.js`, nothing seemed to work). I was wondering if react-select did anything special with where it pulled the build from? Thanks.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
