### ISSUE TITLE
Clear button overflows `value` when placed in narrow container

### ISSUE THREAD

**Issue by jochenberger** [JedWatson/react-select#1554]
If a `Select` is placed inside a narrow container element, the clear button overflows the value text.
![react-select](https://cloud.githubusercontent.com/assets/370733/22967739/fb55d0f4-f367-11e6-9a57-cc62ade9e377.png)

https://jsfiddle.net/5e0g6qjt/1/

**Comment by dekelb** [comment]
Setting `padding-right` on the relevant selector will fix this:

    .Select-placeholder, .Select--single > .Select-control .Select-value {
        padding-right: 40px;
    }

**Comment by JedWatson** [comment]
Fixed by #1866
