### ISSUE TITLE
1.0.0-rc.3 not working?

### ISSUE THREAD

**Issue by jamesmarrs** [JedWatson/react-select#1557]
Hello, didnt look too much into it, but i switched to 1.0.0-rc.3 and the multiselect didnt work for me. I upgraded from 1.0.0-rc.2. Multi select loadOptions didnt reload correctly when selecting/de-selecting. Didnt know if anyone had similar issues, figured I would report it! I downgraded back to 1.0.0-rc.2 and everything worked fine. Thanks for the library and contributions <3

```
<Select.Async
  name="tags"
  cache={false}
  clearable={false}
  multi={true}
  onChange={this.reactSelectChange.bind(this, "tags")}
  loadOptions={this.tagOptions.bind(this)}
  value={this.state.tags}
/>
```

**Comment by milankalinic** [comment]
When searching for the same sting, like "microsoft" and hit enter, nothing happens, but if you do it again, search for "microsoft" and hit enter, then the option appears. This works in rc.1 no problems, here not.

**Comment by clarkritchie** [comment]
I also observed this with 1.0.0-rc.3.

**Comment by iadunn13** [comment]
I've found what causes this to happen.
In https://github.com/JedWatson/react-select/commit/732ba55866d4b3bafbefa40c20923cba70804a70 a modification was added to the render definition in lib/Async.js that will clear out the multi-Select's options whenever you select a value.
See lib/Async.js line 241
```
239    onChange: function onChange(newValues) {
240        if (_this3.props.multi && _this3.props.value && newValues.length > _this3.props.value.length) {
241            _this3.clearOptions();
242        }
243        _this3.props.onChange(newValues);
244    }
```
Commenting out the call to `_this3.clearOptions` will fix the issue, and I can't think a reason why the options are even being cleared out here in the first place.  Hopefully we can get some input from @JedWatson on what should be happening here so we can get it fixed.

**Comment by agrosner** [comment]
There is some weirdness where you will get the same list of dropdown options accross all multiselect async components in rc2. Rc3 fixes that issue, but this issue remains where the clear options call destroys the result cache until you type a space in the field again. Its not ideal.

**Comment by w3-3w** [comment]
Maybe this is the same issue as #1542 ?

**Comment by milankalinic** [comment]
No, it is not the same.

**Comment by agirton** [comment]
So thought about this and my app expects the options to be cleared out as the user will be making a new call with possibly different search criteria. But to handle the variety of use cases what about a `asyncClearsOptions` prop? To keep existing behavior it would be `true`.

**Comment by ericnewcomer** [comment]
Clearing the options on selection seems like the right thing, the behavior I'm seeing (as described in 
 the since closed #1753) is that a new set of options with no input is not fetched after selection -- which definitely seems like a bug.

**Comment by agirton** [comment]
Hi @ericnewcomer apologize if this isn't related. It seemed based on the request. Feel free to reopen, but why would you want to refetch the data again with no input? It seems if that were the case wouldn't you want to just keep the options around?

**Comment by ericnewcomer** [comment]
It's definitely related, just trying to ensure this case is captured here.

Aren't the options getting cleared the options from the previous entry? ie, I search "Adam" select "Adam Girton" then it closes. When I enter it again, I'd expect a new set of options with "" as the input just as it does upon first using it.

**Comment by dmk23** [comment]
Whether or not "Clearing the options on selection seems like the right thing" the current behavior is a failure because after clearing there is no reload of options. This makes it impossible to use this widget for any kind of multi-selects, so we had to subclass/override this behavior to make it work for our project

Would be nice of course to have a proper fix as part of the core project

**Comment by Frit** [comment]
+1 @dmk23, today found same issue with clearOptions. This behaviour confuses many devs.

**Comment by JedWatson** [comment]
If I understand this correctly, I've fixed it, and will release it soon as rc.9

The menu will always close by default for both single and multi-select when an option is selected, but you can change that with the closeOnSelect={false} prop.

To keep suggestions from the Async component after selecting an option, also set onSelectResetsInput={false}

**Comment by dmk23** [comment]
How about onClearResetsInput?

We don't really need to a re-query on every select, but just to fix the current behavior on clear...
