### ISSUE TITLE
Adjacent text does not vertically align properly

### ISSUE THREAD

**Issue by Fauntleroy** [JedWatson/react-select#1562]
Example: https://plnkr.co/edit/ohtZmY?p=preview

Testing out input text alignment breakage: http://codepen.io/Fauntleroy/pen/pRYMby

When text is next to an input it should align with the baseline of the text within in the input. Due to the structure of `react-select`, this does not happen. A simple (maybe) restructuring of the markup of this component along with some hidden text might fix this issue.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
