### ISSUE TITLE
Persist placeholder for multi-select with current values

### ISSUE THREAD

**Issue by rossfishkind** [JedWatson/react-select#1566]
Currently, if you have the selector set to `multi={true}` and your selector has current values, the input associated with the selector will no longer have a placeholder value. This functionality makes sense and is appropriate for the vast majority of use cases, however, I was wondering if it was possible to persist the placeholder even when values exist in the multi-select.

## Here is my use case:
I want to turn this selector, which currently has 2 values and with `autosize={false}`: (notice the blank space under the tags is where the input field is)

![image](https://cloud.githubusercontent.com/assets/331101/23107686/3785da96-f6b6-11e6-942b-5e98915c2d9f.png)

into this:

![image](https://cloud.githubusercontent.com/assets/331101/23107693/7965f7d4-f6b6-11e6-88f4-2ebd16a941bc.png)

If it's not possible in the current implementation, I would imagine adding an attribute called `persistMultiPlaceholder` that would be defaulted to `false`. I would certainly be willing to try my hand at the addition if it's something that fits with the path of `react-select`.

Thanks! :)

**Comment by mslav** [comment]
Bump

**Comment by filiptc** [comment]
Makes a lot of sense for my use-case as well, where the selected values (multi) are rendered outside of react-select.

**Comment by emmya** [comment]
Is there an update here? Still having this issue

**Comment by tskj** [comment]
This would be a really useful feature for me as well. +1

**Comment by bleachdugu** [comment]
Is there an update for this issue ? I really need to keep the placeholder here

**Comment by Rall3n** [comment]
`react-select v1.x` did not have the possibility to keep the placeholder or manage the display of components on your own. You have to use an external label/placeholder for that.

`react-select v2^` gave us the possibility to customize each and every component the `Select` component uses with the ["Components Framework"](https://react-select.com/components). A functioning example for this specific use-case (keeping the placeholder) can be found [here](https://github.com/JedWatson/react-select/issues/2152#issuecomment-470889515).

**Comment by bladey** [comment]
Thanks for the answer @Rall3n, I'm now going to close this issue as a solution has been given in #2152.

If anyone feels this issue is still relevant and you'd like us to review it, or have any suggestions regarding this going forward - please leave a comment and we'll do our best to get back to you!
