### ISSUE TITLE
Plunker example is not working?

### ISSUE THREAD

**Issue by Vadorequest** [JedWatson/react-select#1568]
I was about to write an issue, then saw the Plunker link. But the basic example isn't working for me.

https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview
![image](https://cloud.githubusercontent.com/assets/3807458/23135495/38c3b110-f799-11e6-9546-0f11dc60c88a.png)

Basically, when I click on an option, nothing happens. I experience the same issue with my own code, the Select component is rendered, but it doesn't work (and it's not `disabled`). But my code may be wrong. I'm a bit concerned about the Plunker example though, it should work. All examples at https://jedwatson.github.io/react-select/ work fine, but it's using 0.9.1. Maybe the RC versions just don't work?

**Comment by Vadorequest** [comment]
For the record, I just downgraded to `0.9.1` and it seems to work fine.

**Comment by zaraustra** [comment]
I just installed it too, the last version isn't working at all not even with plain code as:
`
                    <Select
                        name="form-field-name"
                        value='1'
                        options={[{value: '1', label: 'one'},{value: '2', label: 'two'}]}
                        onChange={(e) => {console.log(e)}}
                    />`

the log is correct but nothing else happens

**Comment by sjockers** [comment]
For reference: Seems to be a general issue with `1.0.0-rc.3` – #1557

**Comment by jmellolb** [comment]
Thanks for the downgrade tip, that 'solves' the issue I was having on a clean npm install. Red flag...

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
