### ISSUE TITLE
openOnFocus={false} doesn't prevent opening when focused

### ISSUE THREAD

**Issue by hakunin** [JedWatson/react-select#1580]
Hi,
I am trying to prevent the menu from opening on click (the component is styled as a user picker this  behavior needs to be avoided) but it doesn't seem to work.
https://plnkr.co/edit/GqaFR7?p=preview

Looking at the code, setting false seems to have no value and using `onFocu`s doesn't seem to have a way of preventing it either.
https://github.com/JedWatson/react-select/blob/5aef30df9dba378886f06684f7128216c0f340f6/src/Select.js#L417

**Comment by lauterry** [comment]
Hi @hakunin 

A fix have been made : https://github.com/JedWatson/react-select/commit/ffa1f2d327460171e79def227696e6406b400eeb

Have to wait for the next release

Best regards

**Comment by lauterry** [comment]
Hi @JedWatson 

When do you think you can publish a new release with this fix https://github.com/JedWatson/react-select/commit/ffa1f2d327460171e79def227696e6406b400eeb please ?

Best regards

**Comment by AttilaGal** [comment]
Noticed this behaviour in our application as well, it's quite annoying on mobile devices.  We are using version 1.0.0-rc.3 Any update on when this might get released?

kind regards

**Comment by adelavina** [comment]
Waiting for a rc with this too. :(
Thanks.

**Comment by MV88** [comment]
should this issue be closed by #1527 ?

**Comment by lpalasz** [comment]
cannot wait for this fix

**Comment by jmcrthrs** [comment]
The following pull request fixed this issue:

https://github.com/JedWatson/react-select/pull/1527

However the commit in that pull request has been overwritten by the following commit:

https://github.com/JedWatson/react-select/commit/549d20ac9d9b8afa346681148acbfced7b3fbfe3?diff=unified#diff-04191649796841200b33375bdff7c78fL366

**Comment by vutoan266** [comment]
It still run wrong for me:
<Select
                            name="destination"
                            clearable={false}
                            value={this.state.destination}
                            options={districts}
                            placeholder="District"
                            arrowRenderer={()=> undefined}
                            searchable={true}
                            openOnFocus={true}
                            onChange={(val) => {
                              val && this.setState({destination: val.value});
                              !val && this.setState({destination: null});
                            }}
Anyone help me. Many thanks

**Comment by Vizantiyec** [comment]
Still works wrong in `"react-select": "^1.0.0-rc.5",` will you fix it in `rc.6`? and when you plan to make the release of it.
Best regards!

**Comment by jesstelford** [comment]
Looks like this was shipped in `1.0.0-rc.6`: https://github.com/JedWatson/react-select/blob/master/HISTORY.md#v100-rc6--2017-09-10
