### ISSUE TITLE
Clear select with single={true} returns null instead of ''

### ISSUE THREAD

**Issue by adrienharnay** [JedWatson/react-select#1582]
Hi,

When clearing a multi select (single={false}), onChange is called with `''`. But when clearing a single select (single={true}), onChange is called with `null`.

I think it should be called with `''` in both cases.

Thanks in advance!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
