### ISSUE TITLE
How to filter/sort the selectedObject, using Select.creatable

### ISSUE THREAD

**Issue by michaelroevievictoria** [JedWatson/react-select#1583]
Hi I'm new in React.. any Idea how to filter all the selected data
my code is like this one., (example: data": [{ "name": "ADMIN"}, {"name": "SALES"}, {"name": "FINANCE"}],,

    this.state = {
      formData: {
        selectedEntitlements: []
      }
}
,
`  //-------------------- MULTISELECT----------------------//

  onEntitlementFilterChange = (value) => {
    this.setState({ formData: _.set(this.state.formData, 'selectedEntitlements', value) }) 
  }
`

`
                <Select.Creatable
                  multi={true}
                  options={this.state.entitlements}
                  onChange={this.onEntitlementFilterChange.bind(this)}
                  value={this.state.formData.selectedEntitlements}/>
`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
