### ISSUE TITLE
options got but the drop down not show

### ISSUE THREAD

**Issue by uniquemo** [JedWatson/react-select#1584]
Select2.js：
`import {Component, PropTypes} from 'react';
import Select from 'react-select';
import 'react-select/dist/react-select.css';
import './select.less';

export default class CustomSelect extends Component {
  render() {
    const {loadOptions} = this.props;
    const Class = loadOptions ? Select.Async : Select;

    return (
      <Class
        {...this.props}
      />
    );
  }
}

CustomSelect.propTypes = {
  clearable: PropTypes.bool,
  loadOptions: PropTypes.func,
  noResultsText: PropTypes.string
};

CustomSelect.defaultProps = {
  clearable: false,
  noResultsText: '没找到结果'
};`

use：
`<Select2
              ref='bd-search'
              className='select-llg'
              placeholder='请输入mis账号'
              value={data.bdId}
              valueKey='userId'
              labelKey='name'
              autoload={false}
              options={this.state.BDOptions}
              onInputChange={(value) => {
                this.searchMis(value);
              }}
              onChange={(item) => {
                this.updateData('bdId', item.userId);
              }}
              optionRenderer={(option) => {
                return `${option.name}（${option.key}）`;
              }}
            />`

`searchMis = (value) => {
    return ajax({
      url: `/api/user/login/${value}.json`,
      desc: '获取mis推荐'
    }).then(res => {
      this.setState({BDOptions: res});
      return {options: res};
    });
  };`

**Comment by levilansing** [comment]
i believe you have to set the `valueKey` to 'key' or 'name' (whichever is your unique value) or it won't include any options because they don't have a value.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
