### ISSUE TITLE
Way to prioritize prefix matches

### ISSUE THREAD

**Issue by wojcikstefan** [JedWatson/react-select#1594]
When searching, I'd love a way to prioritize "startsWith" matches vs "includes" matches.

### Steps to reproduce

1. Go to http://jedwatson.github.io/react-select/.
2. Type "South" in the "States" React-Select component.

### Actual result

"New South Wales" is first, "South Australia" is second.

<img width="439" alt="screen shot 2017-03-08 at 5 11 14 pm" src="https://cloud.githubusercontent.com/assets/1718372/23726603/cf4f3f2e-0422-11e7-83cd-a1261a95beae.png">

### Expected result

I'd expect "South Australia" to be the first match and "New South Wales" to be second as a less-ideal match.

**Comment by tonisostrat** [comment]
I personally think that would make this library too opinionated. You are free to implement your own [filterOptions](https://github.com/JedWatson/react-select#filtering-options) that orders the results in the drop-down in any way you see fit.

**Comment by wojcikstefan** [comment]
Ah, that should work, thank you @tonisostrat !
