### ISSUE TITLE
Single select propagates an array instead of an object in onChange()

### ISSUE THREAD

**Issue by gao-sun** [JedWatson/react-select#1596]
I have a `<Select>` component with `{ multi: false, searchable: true }`. Firstly I selected an option, and when I pressed backspace, it deleted the value and propagated the new value in `onChange()`. However, the new value is an empty array instead of `null` or something else.

I got a warning when setting the new value to `<Select>`, it says:

> Warning: Failed prop type: Invalid prop `value` of type `array` supplied to `Value`, expected `object`.
> &nbsp;&nbsp;&nbsp;&nbsp;in Value (created by Select)
> &nbsp;&nbsp;&nbsp;&nbsp;in Select

**Comment by MrLeebo** [comment]
@gao-sun This will be resolved by #773

**Comment by nealoke** [comment]
@MrLeebo any idea when this will be merged? :)

**Comment by MrLeebo** [comment]
@nealoke It's not up to me. I'd certainly like to see it merged since I'm getting emails about it every couple of weeks for the last year. Perhaps @agirton can help?

**Comment by nealoke** [comment]
@MrLeebo aah sorry my bad, I thought you had commit rights :)

**Comment by Dammic** [comment]
I would love if it was merged. Life would be easier if you could just rely on the same behaviour of both backspace and clear button.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
