### ISSUE TITLE
onInputChange() result is not used

### ISSUE THREAD

**Issue by startswithaj** [JedWatson/react-select#1597]
This code:
https://github.com/JedWatson/react-select/blob/master/src/Async.js#L151
```
              if (ignoreAccents) {
			inputValue = stripDiacritics(inputValue);
		}

		if (ignoreCase) {
			inputValue = inputValue.toLowerCase();
		}

		if (onInputChange) {
			onInputChange(inputValue);
		}

		return this.loadOptions(inputValue);
```

should be 

```
              if (ignoreAccents) {
			inputValue = stripDiacritics(inputValue);
		}

		if (ignoreCase) {
			inputValue = inputValue.toLowerCase();
		}

		if (onInputChange) {
			**inputValue** = onInputChange(inputValue);
		}

		return this.loadOptions(inputValue);
```

**Comment by min20** [comment]
Creatable.js onInputChange has same issue:
https://github.com/JedWatson/react-select/blob/master/src/Creatable.js#L172

`
onInputChange (input) {
	const { onInputChange } = this.props;

	if (onInputChange) {
		onInputChange(input);
	}

	// This value may be needed in between Select mounts (when this.select is null)
	this.inputValue = input;
},
`
