### ISSUE TITLE
InputValue with proceeding spaces breaks cache (chrome)

### ISSUE THREAD

**Issue by startswithaj** [JedWatson/react-select#1598]
Take the following scenarios:

```
inputValue = '    test'
options = []
cache = {}
cache[inputValue] = options;
```
cache then  == { ' test': [] }

```
inputValue = ' \ \ \ \ test'
options = []
cache = {}
cache[inputValue] = options;
```
cache then  == { ' test': [] }

More than one proceeding space on an object key is striped.

This means that the cached result for ' test' is return for '   test' and ' \ \ \ \ test'.

**Comment by startswithaj** [comment]
Because of https://github.com/JedWatson/react-select/issues/1597 you can't work around it.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
