### ISSUE TITLE
There are too many issues on this repo.

### ISSUE THREAD

**Issue by scottsword** [JedWatson/react-select#1599]
### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by FezVrasta** [comment]
The boilerplate should note as follow:

> Any issue opened without a minimal reproducible example created using the provided Plunker link will be summarily closed.
