### ISSUE TITLE
Repositioning values in multi select

### ISSUE THREAD

**Issue by williamboman** [JedWatson/react-select#1606]
Thoughts on adding support for repositioning values in a multiselect? Preferably via drag/drop.

**Comment by songyanho** [comment]
#1720

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
