### ISSUE TITLE
option to not autoload options

### ISSUE THREAD

**Issue by jayenashar** [JedWatson/react-select#1607]
hi there,

i want the options to not appear on mousedown , but rather only to appear after the user has typed some input.  kind of like the autoload option for async, but for non-async use.  maybe even a minChars attribute?

thanks

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
