### ISSUE TITLE
Creatable doesn't allow create option anywhere but first in the list.

### ISSUE THREAD

**Issue by tmc** [JedWatson/react-select#1614]
AFACIT It's a bit tough to get Creatable to place the new option last in the list.

**Comment by mcorteel** [comment]
#48 already mentions this problem.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
