### ISSUE TITLE
[Question] Is there a way to use the search functions without the dropdown/options? 

### ISSUE THREAD

**Issue by MarcMagnin** [JedWatson/react-select#1622]
As I'm using this component on the same page with some options and I need another free text search input (without suggestions), can we reuse that component for doing such thing?
ie: Free async text search and get the benefits of the styles and the cross to clear the content for searched text.

Many thanks

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
