### ISSUE TITLE
react-select seems to break the bootstrap grid 

### ISSUE THREAD

**Issue by AnishJoseph** [JedWatson/react-select#1628]
I am using the bootstrap 3  grid system - when one of the elements is a react-select element the alignment of the grid gets messed up. 
The test case can be found at 
https://plnkr.co/edit/eVBVPJWx5y2rJRDH9ixX?p=preview

**Note:** You may have to **expand the output pane in plunker** to see the alignment issue. If one removes the select tag then the elements line up as expected. With the Select tag, an offset seems to be created

**Comment by MrLeebo** [comment]
@AnishJoseph The react-select control is just a little bit taller than the others. You can resolve it by adding 

```
.Select {
  height: 34px;
}
```

to **styles.css**

or by arranging each horizontal row of fields into `<div class="row">` elements

**Comment by AnishJoseph** [comment]
Thanks MrLeebo.  I solved the issue by removing the form-inline class and adding form-control to the react-select. Works for me.
