### ISSUE TITLE
when use redux with react-select, the isSelect of option is false.

### ISSUE THREAD

**Issue by lubyxu** [JedWatson/react-select#1630]
### when use redux with react-select, the isSelect of option is false.

my reducer is like this:
`case PROJECT_SUCCESS:
            return state.merge({
                isFetching: false,
                projects: action.res,
                error: null
});`
`case PROJECT_SELECT:
            return state.set('value', action.value);`

when I select a option, the option does not be marked as selected. 
I found the error in the line:33 of the file "defaultMenuRenderer.js".
 `var isSelected = valueArray && valueArray.indexOf(option) > -1;`. 
So, I corrected as `var isSelected = valueArray && !!_.find(valueArray, option)`, temporarily.

the react-select is awesome~~~ waiting for you next version.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
