### ISSUE TITLE
onClick function remove click?

### ISSUE THREAD

**Issue by Stas-Buzunko** [JedWatson/react-select#1637]
Here is video how onClick function uses something like event.preventDefault which causes date-picker's onOutsideClick to be ingored. Any other click closes date-picker. How can I fix this?
http://quick.as/qrxzhajxv

**Comment by export-mike** [comment]
Hey @Stas-Buzunko I'm going to need a bit more context, 

where are you referring to event.preventDefault is being called?

whats the expected behaviour?

can you provide us with some example code, I.e. a jsfiddle or something to reproduce the issue and we'll then go from there.

**Comment by gwyneplaine** [comment]
Hey @Stas-Buzunko as above, please provide us with more context so we can  triage this appropriately

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
