### ISSUE TITLE
Use react-select Creatable in Redux  ,how to add options created to options in state

### ISSUE THREAD

**Issue by CeleKing** [JedWatson/react-select#1638]

**Comment by export-mike** [comment]
Hey @CeleKing  I'm going to need a bit more context,

whats the expected behaviour?

can you provide us with some example code, I.e. a jsfiddle with what you have or something and we'll then go from there.

**Comment by joefraley** [comment]
I think I understand this.

```javascript
@connect(...) <-- re-render on state changes
const input = (props) =>
  <ReactSelect.Creatable value={props.value} options={[a, b, c]} onChange={this.props.update}/>
```

the options in this case get reset to the starting array whenever the redux state updates, because the component is re-rendered wholesale and thus loses track of its internal state (the appended options list).

so you need to keep track of those options in your state machine now and thread them up and down

```javascript
@connect(...) <-- re-render on state changes
const input = (props) =>
  <ReactSelect.Creatable value={props.value} options={this.props.options || [a,b,c]} onChange={this.props.update}/>
```

**Comment by joefraley** [comment]
actually i'm not 100% sure what's going on.

see: [![Edit React-Select w/ React-Redux](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wjoQ4jmvz)

the options seem to remain intact even with redux calling the shots.

**Comment by Kovensky** [comment]
The problem is that <Creatable/> never notifies you that an option is being added; it just mutates its input.

https://github.com/JedWatson/react-select/issues/1477

**Comment by vrbarros** [comment]
I have some similiar problem here and I found the following solution:
`
 options={[
                        { value: 'Communication' },
                        { value: 'Finance' },
                        ...created.split(',').map(item => {
                          return { value: item };
                        }),
                      ]}
`

Where the first values are default values, and the created is an state that loads with the initial data of the select component.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
