### ISSUE TITLE
If you are using Async component as in the example of gitHubUsers. What is happening is after multiple space the options are not loading though the response is coming from fetch.

### ISSUE THREAD

**Issue by mansisce** [JedWatson/react-select#1641]
### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by idrumgood** [comment]
I think I'm experiencing this same error. I'm using an async options loader and it works great until I have a space in my search. The ajax request is returning valid users, but the component does not display them as options. They are not passed into the optionRenderer despite being returned from loadOptions.

**Comment by idrumgood** [comment]
On the examples page: http://jedwatson.github.io/react-select/  Contributors (Async) example.

Type 'Jed' into the component and see that 'Jed Watson' is an option.

Type 'Jed W' and see that no options are displayed.

**Comment by paul-veevers** [comment]
@idrumgood did you end up finding a solution for this?

**Comment by idrumgood** [comment]
My workaround was to pass the component a `filterOption` function that just passes through the option.

**Comment by paul-veevers** [comment]
That worked, thank you!

For anyone else with the issue, just add this prop:

`filterOption={a => a}`

**Comment by hitchcockwill** [comment]
Thanks for the fix there @paul-veevers. I've been struggling with this issue for a while now.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
