### ISSUE TITLE
Modal Support? Mousedown bubbles outside of React-select element for target (menu option) after it's removed

### ISSUE THREAD

**Issue by rorydownes** [JedWatson/react-select#1642]
**See example here**: https://embed.plnkr.co/WvHLgU/

See the example for a react-select element rendered inside of a parent, in my specific use case this parent is a modal.

When an option is selected the mousedown event is propagated to it's parent. However because react-select's onChange was first triggered setState was called with isOpen = false. Upon re-rendering the target menu option is no longer mounted to it's corresponding DOM parent.

In the modal therefore a check to see if the clicked event was made on a child of the modal's root node will always fail, causing the modal to immediately close.

**Comment by PeteJodo** [comment]
I believe this is related to this http://stackoverflow.com/questions/24415631/reactjs-syntheticevent-stoppropagation-only-works-with-react-events

**Comment by PeteJodo** [comment]
It works if the parent component uses `onMouseDown`. Don't know if there's another solution.

**Comment by stahlmanDesign** [comment]
I think describes my same problem.

I use **react-contextmenu** to provide a few menu items on right-click. One menu item opens a **react-skylight** popup containing a **react-select** dropdown.

![explanation](https://user-images.githubusercontent.com/972804/28227463-061ea1c2-68a8-11e7-8794-d8016619ad83.jpg)

I can click in the dropdown, but when I make a selection and release, the popup closes. This happens even if I remove the onChange event on the Select component.

If I simply close the popup with 'cancel' or the 'x' button, the context-menu remains open, as I left it before the popup was shown.

But when I use the react-select dropdown, the popup closes _and_ the context menu goes away, leading me to think the event is bubbling, signaling a click outside the context menu.

Either the hidden menu is causing the popup to disappear, or the popup is re-rendered as described by @rorydownes.

Either way, I think that if I could prevent the bubbling in react-select the problem would go away.

**Comment by landonwilkins** [comment]
I had success with `event.stopImmediatePropagation();` at the bottom of the the parent component's `onClick` handler

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
