### ISSUE TITLE
Creatable option to modify selected option as new

### ISSUE THREAD

**Issue by sonhgc00016** [JedWatson/react-select#1643]
Have any options make Creatable can modify selected option and make the modified option as new?

**Comment by Dammic** [comment]
I too would welcome that feature.
An example user case could look like this like this:
Easier creation of user-configurable tags. One has a select with some initial values like 'after ...' , 'before ...' (also the already-prepared one like 'before afternoon'. The user could select one of those options from a select menu and then add his own piece of information into the selection, ex. 'after midnight"

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
