### ISSUE TITLE
Creatable ref property

### ISSUE THREAD

**Issue by blacktemplar** [JedWatson/react-select#1644]
Creatable is missing the property ref (the documentation states Creatable has all properties of Select, but Select has a ref property and Creatable not).

Can we add the ref property to Creatable instances?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
