### ISSUE TITLE
Display treeview

### ISSUE THREAD

**Issue by fgiarritiello** [JedWatson/react-select#1647]
Hi, thanks for the hard work on this cool component.
Question: is there a way to display a treeview inside the dropdown where I can select multiple nodes?

Thanks.

**Comment by cbergmiller** [comment]
Hi @fgiarritiello!

This can be done with a custom-option-renderer that is supplied via the `optionRenderer` prop.
I put some code in a gist to get you started: https://gist.github.com/cbergmiller/46b085418985ad23d29cabce62561140

You will have to annotate your options with `level` and `isLastLeaf ` atrributes.
Please report back if this works for you. Perhaps there is enough interest to develop this feature further.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
