### ISSUE TITLE
Inconsistent up/down scrolling via arrow keys

### ISSUE THREAD

**Issue by robbford** [JedWatson/react-select#1649]
I'm seeing inconsistent scrolling where down-arrow scrolls one option at a time into view, whereas up-arrow scrolls a menu-full at a time (more like paging).

This can be observed with the 'States' example built/running locally from 1.0.0-rc.3.

First, select the 'United States' option so there are more states loaded into the list.

To observe arrow-key down scrolling one option at a time into view:
1. Press down-arrow to open the menu. Alaska should be selected.
2. Arrow key down to Arkansas, then once more which scrolls California into view, again to scroll Colorado into view. 

To observe arrow-key up scrolling a menu-full of options at a time into view:
1. Select Wyoming (last in the list) 
2. Arrow key up to Virginia, then once more to Virgin Islands. Observe that instead of scrolling just this option into view, a menu-full of previous options is scrolled into view showing:
South Dakota (clipped)
Tennessee
Texas
Utah
Vermont
Virgin Islands

Is this by-design? If so, is there a means of achieving consistent up/down scrolling, preferably one option at a time?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
