### ISSUE TITLE
[Call setState in lifecycle function] Async.js 

### ISSUE THREAD

**Issue by zhangzhinan** [JedWatson/react-select#1651]
When i'm used width inferno, it throw me an error.

According to React Docs said:

https://facebook.github.io/react/docs/react-component.html#componentwillupdate

Note that you cannot call this.setState() here. If you need to update state in response to a prop change, use componentWillReceiveProps() instead.
![image](https://cloud.githubusercontent.com/assets/16774464/24755100/7fa9dd30-1b0b-11e7-9ed8-5fa484e64dbe.png)

**Comment by agirton** [comment]
Hi @zhangzhinan `componentWillReceiveProps` seems like the better approach here. Since it's just syncing the props. Open to PR's to fix this :smile:

**Comment by jochenberger** [comment]
This was fixed in #1651 and should be closed.
