### ISSUE TITLE
why react-select will manipulate the options value

### ISSUE THREAD

**Issue by zackshen** [JedWatson/react-select#1654]
this.testOptions = [...]
```javascript
<Creatable
    options={this.testOptions}
    multi={true}
    value={value}
    onChange={::this.handleChange}
/>
```
why react-select will directly manipulate the `options` ? @sunny @Aeon @drd @spicyj @unity

**Comment by slavab89** [comment]
Can you explain what you mean? How are the options modified? What do you see happening?

**Comment by zackshen** [comment]
this.testOptions will changed when input something into Creatable , if i remove the tags in Creatable , this.testOptions content would not change.

**Comment by slavab89** [comment]
This does indeed happen. There is already an issue open about this.
https://github.com/JedWatson/react-select/issues/1477
This is really a bug but there is no fix for this yet.

One way to work around that is to wrap the Select in a component that manages an internal state of the currently selected / available options

```js
import { map, isEmpty, unionBy } from 'lodash';

class SelectWrapper extends PureComponent {
  constructor(props) {
    super(props);

    const { options, value, multi } = props;
    if (isEmpty(options)) {
      this.state = {
        options: multi ? map(value, v => ({value: v, label: v})) : [{ value, label: value }]
      };
    } else {
      this.state = {
        options: [...options]
      };
    }
  }

  componentWillReceiveProps(nextProps) {
    const { value, creatable, multi } = nextProps;
    if (value && value.length && creatable) {
      const moreOptions = multi ? map(value, v => ({value: v, label: v})) : [{ value, label: value }];
      this.setState({
        options: unionBy(this.state.options, moreOptions, 'value')
      });
    }
  }
  
  render() {
    return <Select options={this.state.options} .... />
  }
}
```

**Comment by zackshen** [comment]
@slavab89, thanks, i use this.testOptions = [...options] to resolve this problem like your method.
