### ISSUE TITLE
Strange behaviour using "Cities (Large Dataset)" example

### ISSUE THREAD

**Issue by bargri** [JedWatson/react-select#1657]
Tried the "Cities (Large Dataset)" example here:

http://jedwatson.github.io/react-select/

and when I type i "Dub" I get no matches. Then with "Dubl" I get two Dublins. Then when I return to "Dub" again, via backspace, I have three matches: Dublin, Dublin and Dubuque.

Running in Chrome Version 57.0.2987.133 (64-bit), Mac OS 10.12.3.

**Comment by BenNG** [comment]
The scroll is broken as well 

Version 59.0.3071.86 (Official Build) (64-bit)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
