### ISSUE TITLE
Return event onChange

### ISSUE THREAD

**Issue by anthonator** [JedWatson/react-select#166]
Currently `onChange` returns the new value for `Select`. It should return an event just like every other component that responds to `onChange` in React.

**Comment by cmnstmntmn** [comment]
yes, this is bad becauze you can't make chainable selects :(

**Comment by jketcham** [comment]
Has there been any updates on this? Would love to have this feature for the same reason @cmnstmntmn  gave.

**Comment by vmendoza** [comment]
I agree, an event with event target will simplify my code so much. Right now I need a event handler for every Select, with event.target.name or id, I can have a single onChange handler.

**Comment by anton-kabysh** [comment]
Hey, this feature is highly expected.

**Comment by dixalex** [comment]
+1. Really need this feature.

**Comment by jmarceli** [comment]
+1 I'm also looking for that option

**Comment by brianreavis** [comment]
@anton-kabysh et al: pull requests are welcome.

**Comment by jk171505** [comment]
+1. Another one.

**Comment by jk171505** [comment]
Some workaround:

```javascript
var eventTarget = context.refs[propName];
setTimeout(function() {
    console.log(eventTarget.state.value, eventTarget.state.values);
    // or
    console.log({[propName]: eventTarget.state.value});
}, 0);
```

and Select setup looks like this:
```html
<Select ref="selectThe1st" ... onChange={this.eventHandler.bind(null, 'selectThe1st', this)} />
```

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
