### ISSUE TITLE
Select.Async not updating auto-suggest box. Updates after I unfocus-refocus on input field.

### ISSUE THREAD

**Issue by qbolt** [JedWatson/react-select#1660]
The promise is resolving, but the auto-suggest box isn't displaying the text it should. If I unfocus and refocus on the input field, then it updates the box and displays the auto-suggested values.

Note: I have a binding assignment in my constructor.

```
getOptions(input) {
    if (!input) return Promise.resolve({ options: [] })
    return fetch('http://localhost:8080/api/users/query/' + input)
      .then(response => response.json())
      .then(json =>
        json.map(option => {
            return { label: option.firstName, value: option }
        })
      )
      .then(options => { return { options } })
  }

  // Render function that react will call
  render() {
    return (
      <div className="searchContainer">
        <form action="">
          {createRadioButtons(this.onRadioButtonSelect)}
        </form>
        <Select.Async
          loadOptions={this.getOptions}
          ref={(input) => { this.inputRef = input }}
          placeholder={this.state.placeholder}
          onChange={this.onSelect}
        />
        {this.props.children}
      </div>
    )
  }
```

**Comment by paul-veevers** [comment]
@qbolt did you end up finding a solution for this?

Related issue: https://github.com/JedWatson/react-select/issues/1641

**Comment by paul-veevers** [comment]
For anyone else with this issue, there's a solution in https://github.com/JedWatson/react-select/issues/1641#issuecomment-301057671

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
