### ISSUE TITLE
Deprecation warnings with React 15.5.3

### ISSUE THREAD

**Issue by sebastianiorga** [JedWatson/react-select#1661]
1. Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
2. Warning: AutosizeInput: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Solution for first one:
1. Add prop-types package.
2. Any file that has 'React.PropTypes' in it: add an import for PropTypes, remove the React. prefix.

Not sure about the exact fix for the second one. I guess adding create-react-class to dependencies if refactoring to classes isn't viable?

Thanks for building this package, dude!

**Comment by delveintechnolabs** [comment]
@JedWatson : i see a open PR #1658 . Can you please merge into master. I just updated my react version and started getting errors in console. (I see that travis build has failed on that PR but i am sure that would be a 1 min fix)

Looking forward to a merge and version upgrade.

Thanks

**Comment by GitShaffi** [comment]
Facing same issue! Looking forward to a merge and version upgrade.

**Comment by akash-bhardwaj** [comment]
Same issue. When to expect this fix?

**Comment by andrerpena** [comment]
Please!

**Comment by haunguyen90** [comment]
Please fix the new deprecation warnings from fb-react

**Comment by hiramhibbard** [comment]
I also would love to see this updated as well. I'm a little worried that there haven't been any new commits in over a month.

**Comment by MichaelDeBoey** [comment]
These are fixed with #1658 and are now released 🙂

**Comment by sebastianiorga** [comment]
Updated and everything works fine for me. Thank you once again for this great package :)
