### ISSUE TITLE
Couldn't find docs for .closeMenu() function

### ISSUE THREAD

**Issue by yasuf** [JedWatson/react-select#1662]
Maybe this is a known issue but I wouldn't mind adding this part of the documentation if it's not being worked on right now

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
