### ISSUE TITLE
Owners of elements with role="combobox" must have role listbox or textbox.

### ISSUE THREAD

**Issue by jrubstein** [JedWatson/react-select#1668]
According to the [spec](https://www.w3.org/TR/wai-aria/roles#combobox), combobox elements need to have an owner with listbox or textbox role.

The markup created by the component does not have it. Complete markup below:

```
<div class="Select select Select--single has-value">
    <div class="Select-control"><span class="Select-multi-value-wrapper" id="react-select-7--value"><div class="Select-value"><span class="Select-value-label" role="option" aria-selected="true" id="react-select-7--value-item">Crazy things - 3123</span>
    </div>
    <div id="account" aria-errormessage="personal.account-error" aria-invalid="false" autocomplete="off" role="combobox" aria-expanded="false" aria-owns="react-select-7--value" aria-activedescendant="react-select-7--value" class="Select-input" tabindex="0" aria-readonly="false" style="border: 0px; width: 1px; display: inline-block;"></div>
    </span><span class="Select-arrow-zone"><span class="Select-arrow"></span></span>
</div>
</div>
```

Also the id (react-select-7--value in this case) is duplicated.

**Comment by egoens** [comment]
@jrubstein The url to the spect you referenced here is returning a 404.

The W3C specs https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/#combobox should outline the best practices here for the combobox implementation. This example is probably the most appropriate reference for visually describing the interaction that is desired here https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/combobox/aria1.1pattern/listbox-combo.html#ex3_label. 

As I understand it, the most important aspects of this implementation should be as follows:
1. The input should include an `aria-labeledby=[popup-id]` attribute that references the popup `id`
2. The popup should include the attribute `id=[popup-id]` defined by the input `aria-labeledby`.
3. The popup should also include the attribute of `role="listbox"`
4. The wrapper for the interaction can/should include an attribute of `aria-owns="[popup-id]"`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by seanlaff** [comment]
Presently, the combobox has 
```
aria-controls="popup_id"
aria-owns="popup_id
aria-haspopup="true"
```
which seems like almost everything- however the popup is still missing the `role="listbox"` attribute
