### ISSUE TITLE
Bug: Selector shows empty boxes

### ISSUE THREAD

**Issue by aleemb** [JedWatson/react-select#167]
On the [demo page](http://jedwatson.github.io/react-select/):

1. Clear out the `Clickable Labels`
2. Focus in select box and type anything then hit escape. Shows box with null element instead of being empty.

![image](https://cloud.githubusercontent.com/assets/46616/7472258/0bf103cc-f34a-11e4-82d6-307d5b7b5574.png)

**Comment by rgrzelak** [comment]
This fixes it:
https://github.com/JedWatson/react-select/pull/162

**Comment by dcousens** [comment]
Fixed by #162
