### ISSUE TITLE
Can I use option-group in react-select ? 

### ISSUE THREAD

**Issue by sahidhossen** [JedWatson/react-select#1678]
### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by benhowell** [comment]
You might want to look at [react-select-plus](https://github.com/HubSpot/react-select-plus)

**Comment by agirton** [comment]
Hi @sahidhossen we currently don't have this in core. But you can create an option group using your own `SelectOption` using the `optionComponent`.

**Comment by tlkiong** [comment]
@agirton Given that this feature is now in v2, this issue should be closed already right?

**Comment by sahidhossen** [comment]
You can close this issue now. I got the solution 👍 .

**Comment by ttlpta** [comment]
@sahidhossen Can you show to everyone your solution?

**Comment by NiceGuyNimni** [comment]
I guess he can't :(

**Comment by junhui75165** [comment]
@sahidhossen 
Can you share your solution ?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
