### ISSUE TITLE
NFR: Add undo support

### ISSUE THREAD

**Issue by aleemb** [JedWatson/react-select#168]
Not sure if this is in the scope but would be nice if undo/redo support was added. I think this is achievable by pushing/popping the states in a stack.

**Comment by dcousens** [comment]
Could you elaborate on what you might expect this to do?  Any perhaps why it couldn't be done by the parent component?

**Comment by aleemb** [comment]
Please feel free to close this as this is not critically important but if you add two selections, `ctrl+z` could undo those selections. I believe react makes this fairly easy due to statefulness.

On a related note, I felt the need for this because I hit escape to dismiss the dropdown and then hitting it again deleted all my selections which I am sure will bite a lot of users. So maybe `escape` should not act as a `delete all` especially since the key is already overloaded to dismiss the dialog.

**Comment by TrevorBurnham** [comment]
This would be especially helpful after pressing backspace to remove an item in multi-select. It's an easy mistake to make, and you may not remember what you deleted.
