### ISSUE TITLE
Backspace on selected gives warning

### ISSUE THREAD

**Issue by eduardoinnorway** [JedWatson/react-select#1680]
If you empty a select with backspace, it will give you a warning it got an empty "array" to the value prop when it is expecting an object.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
