### ISSUE TITLE
Match "value" first on list?

### ISSUE THREAD

**Issue by eduardoinnorway** [JedWatson/react-select#1681]
Why does it not mach the exact search "string" first on the result list as default?

On your own example you write "South", then it gives you:

- New south wales
- South Australia

I think that match is more relevant than ordering in any other form.

Is there a way to make the match with starting string, be first on the list?

**Comment by agirton** [comment]
Hi @eduardoinnorway we don't sort the options but you can accomplish this in your own `filterOptions`.

**Comment by rsslldnphy** [comment]
hi @agirton , i realise this is a few years ago now but i've also run into this issue and i'm not sure i understand how `filterOptions` can help here. i had a look at the docs [here](https://react-select.com/props) which suggest it is a function taking a single option and returning a boolean:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1231200/76404269-19e9c000-637e-11ea-93b6-c723641983b9.png">

so can be used to determine inclusion in the search but not ordering - unless i'm misunderstanding something? thanks!

(my particular use case: i have a select for gender which contains among other things "female" and "male" in that order. when i type "male" it matches "female" first and "male" second, and at that point there's nothing i can type to disambiguate further.)

**Comment by agirton** [comment]
Hi @rsslldnphy, it’s not so much on sorting but filtering/matching the data. So in your filter options you can change how this library matches the item. Sounds like you want exact match in those cases.

**Comment by rsslldnphy** [comment]
Hi @agirton , I believe what the OP was asking for is the same as what I am after - we want the exact match to appear first in the list, but still want to see non-exact matches.

In the OP's example, the drop-down would show "South Australia" and then "New South Wales".

I don't think it's possible to accomplish this with a matching function, only a sorting one. I'd be happy to have a go at putting a PR together if this is something you'd want to add. The two obvious approaches I can see would be either making this the default behaviour or allowing the configuration of a sorting function.

**Comment by bladey** [comment]
Hi all,

Thanks for sharing the implementation advice above!

@rsslldnphy if you'd like to create a PR for this you are most welcome, if there is demand for it, I'd happily review it.

I'll close this issue for this as it's been deemed not possible unless we make an enhancement and PR - however if you feel the issue should remain open, please do let me know.
