### ISSUE TITLE
Multiple values from single key

### ISSUE THREAD

**Issue by schoettler** [JedWatson/react-select#1686]
I'm trying to add _suggestions_ on tag groups, ideally clicking 1 option would add 3 values (3 separate tags). Is this possible on the current API?

I tried a custom `valueRenderer` function, returning multiple _values_ from a nested `options` object as follows, but it gives me 1 tag with line breaks, instead of 3 separate tags. Sample:
```
const suggestions = {
  label: 'Cheeseburger',
  value: '',
  type: 'suggestion',
  options: [
    {
      label: 'Bread',
      value: 'bread'
    },
    {
      label: 'Beef',
      value: 'beef'
    },
    {
      label: 'Cheese',
      value: 'cheese'
    }
  ]
}
```

```
<Select
  valueRenderer={(item) => {
    return item.type === 'suggestion'
      ? item.options.map(nestedOption => {
        return (
          <option label={nestedOption.label} value={nestedOption.value} key={nestedOption.value} />
        )
      })
      : <option label={item.label} value={item.value} />
  }}
  {...props}
/>
```

**Comment by agirton** [comment]
@schoettler could you handle this in the `onChange` handler? This way you can flatten it back out to what the module requires.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
