### ISSUE TITLE
Where is searchPromptText supposed to appear?

### ISSUE THREAD

**Issue by merlinpatt** [JedWatson/react-select#1688]
The README mentions that there is a field `searchPromptText` with default text `Type to search`. Where is this supposed to be? Is it supposed to be used in conjunction with another property?

**Comment by agirton** [comment]
Hi @merlinpatt this is only applicable to the Async component. This is so the user will see some text in the dropdown and they are prompted to search.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
