### ISSUE TITLE
autofocus doesn't work when "autofocus" property is changed.

### ISSUE THREAD

**Issue by acierto** [JedWatson/react-select#1692]
So basically autofocus is looking only at **componentDidMount** and never recalculated in **componentDidUpdate**

**Comment by cbergmiller** [comment]
Could you explain you use case?
The behavior of `autofocus` is described in the docs [here](https://github.com/JedWatson/react-select#further-options) (it is only focused on mount).

**Comment by nortonwong** [comment]
This behavior also matches broader spec. In HTML and in React, it is intended that [`autofocus` only applies on the initial mount](https://github.com/facebook/react/issues/5534#issuecomment-158972163).

To focus your Select component, store its ref and call `ref.focus()`.

**Comment by avremel** [comment]
@cbergmiller See here for use case:
https://stackoverflow.com/questions/46570762/control-focus-dynamically-for-input-fields?noredirect=1#comment80498328_46570762

**Comment by dwoowb** [comment]
@acierto did you end up finding a solution to this? :)

**Comment by dwoowb** [comment]
So in my particular case, I was conditionally assigning the `disabled` prop based on fetching data from an API. With `autoFocus={true}` `handleInputFocus()` is triggered only on initial mount as @nortonwong described but `handleInputFocus()` immediately returns if `disabled` is true. And like @acierto pointed out `componentDidUpdate()` doesn't consider autoFocus, only `componentDidMount()` so when `disabled` is updated to be `false` the input doesn't get focused.

Ultimately in my case I think react-select's behavior is fine as it makes sense that `disabled` should override `autoFocus`. If for whatever reason I need to continue to disable until my data is fetched then I may consider adjusting this lib to focus/open any time it goes from a disabled to enabled state (but not the inverse)

**Comment by acierto** [comment]
@dwoowb As authors of this lib decided to do it only on mount I basically went with @nortonwong solution

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
