### ISSUE TITLE
error coming from AutoresizeInput dependency

### ISSUE THREAD

**Issue by mac-s-g** [JedWatson/react-select#1694]
## Problem Description
The `react-input-autosize` dependency is throwing an error when React-Select is imported.

Here is the error:
```
ERROR in ./~/react-input-autosize/lib/AutosizeInput.js
Module not found: Error: Can't resolve 'create-react-class' in '/react/node_modules/react-input-autosize/lib'
 @ ./~/react-input-autosize/lib/AutosizeInput.js 7:18-47
 @ ./~/react-select/lib/Select.js
```

## Cause
It looks like a patch version of `react-input-autosize` was published today.  The changes are causing the error above.

Here is how `react-input-autosize` is currently included with `react-select`:

`"react-input-autosize": "^1.1.0"`
see: https://github.com/JedWatson/react-select/blob/master/package.json#L15

## Quick Fix
You can quickly fix the issue by removing the carrot from your dependency version:

Replace the line linked above with: 
`"react-input-autosize": "1.1.0"`

I fixed the error in my project by explicitly adding `"react-input-autosize": "1.1.0"` as a dependency to my project.

I hope this is helpful, I :heart: your component!

**Comment by dandonahoe** [comment]
Related with additional information about a fix:

https://github.com/JedWatson/react-input-autosize/issues/84

**Comment by castrolem** [comment]
So, it's not fixed fixed yet right?

**Comment by mooncakelmn** [comment]
Seems not fixed yet, set it to fixed version for now as well...

**Comment by baijifeilong** [comment]
"react-input-autosize": "1.1.0" did not work for me
"create-react-class": "^15.5.2" worked for me

**Comment by malikimprowised** [comment]
@baijifeilong I just faced this problem. Please `react-input-autosize": "1.1.0` this line to package.json of your project. It seems that newer version of `react-input-autosize` cause the error.

**Comment by lauterry** [comment]
Hi

Moving to react-select 1.0.0-rc.4 had fixed the issue.

Please close this issue if so.

Best regards.

**Comment by dandonahoe** [comment]
Verified, works. Thanks!

**Comment by agirton** [comment]
This has been fixed with the latest release, closing.

**Comment by peebles** [comment]
```bash
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/react-select/lib/Select.js:39 
```

I am using:

```bash
# grep react-select package.json 
    "react-select": "^1.0.0-rc.5",
```

LIne #39:

    var _reactInputAutosize2 = _interopRequireDefault(_reactInputAutosize);

**Comment by peebles** [comment]
I should note however, that ^1.0.0-rc5 actually installed 1.0.0-rc6.  If I back off to 1.0.0-rc5, then the build (from create-react-app) succeeds without an error.

**Comment by srigowrideo** [comment]
hello everyone !! i am not able to open any program on visual studio code ,i am getting textual examination and it contains junk data so what to do and how to proceed further this code is a react code
