### ISSUE TITLE
"Module create-react-class not found" because of the floating dependency react-input-autosize

### ISSUE THREAD

**Issue by ebourmalo** [JedWatson/react-select#1697]
There's a regression with the latest version of `react-input-autosize`.
Build is failing because of a dependency with the module `create-react-class`, [more info on the related issue](https://github.com/JedWatson/react-input-autosize/issues/84)

The PR is coming (fix the dependency `react-input-autosize` to fixed version 1.1.0).

**Comment by mac-s-g** [comment]
#1694

**Comment by marcellodesales** [comment]
:( Just got the same error... what's a current workaround?

**Comment by sprjr** [comment]
@marcellodesales you can depend on `react-input-autosize@1.1.0` in your project to avoid the updated version getting placed in this libs `node_modules/`.

**Comment by denis-mludek** [comment]
Same problem here.. :(

**Comment by lauterry** [comment]
Hi

Moving to react-select 1.0.0-rc.4 had fixed the issue.

Please close this issue if so.

Best regards.

**Comment by agirton** [comment]
Closing as this has been fixed in the latest release.
