### ISSUE TITLE
Smaller height for options with empty strings

### ISSUE THREAD

**Issue by elefantino** [JedWatson/react-select#1699]
If an option contains an empty string, it has a smaller height than the other options with some text. You can test it in the example demo http://jedwatson.github.io/react-select/ by creating an empty string option in Custom tag creation (Single Value)

A possible solution is to add a min-height to Select-option class in menu.scss

`.Select-option {
	min-height: $select-input-internal-height;
        ...
}
`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
