### ISSUE TITLE
Multi Select doesn't update selected value labels after remote fetch

### ISSUE THREAD

**Issue by aleemb** [JedWatson/react-select#170]
If I have selected values `value="a"` and then I remotely options from server of the form `{value: 'a', label: 'Apple'}`, the select box should update to show "Apple" instead of "a" once the values have been fetched. 

The value field is set as `value={this.state.value}`. It appears the value must change for the selected values to be updated. The change can be anything, for my purposes I am forcing the change by setting the value to null and then to non-null to force it to update.

**Comment by elevee** [comment]
I have this exact same problem. Trying to prepopulate a field and it gives the data value (usually an id like 67) instead of the display value (e.g. "Claude Monet"). It's definitely a timing issue. Could force a rerender but seems a little hack-y.

**Comment by aldanor** [comment]
Interested in this as well -- seems to be an issue on 0.5.4 still.

**Comment by eipark** [comment]
+1.

**Comment by GodGinrai** [comment]
+1

**Comment by outerlook** [comment]
Hi! Was this issue fixed? I think I'm facing it

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
