### ISSUE TITLE
Remove arrow and functionality

### ISSUE THREAD

**Issue by jozr** [JedWatson/react-select#1700]
Passing a function that returns `undefined` to the `arrowRenderer` prop will remove the arrow, but not the functionality of the arrow. How can I completely remove the arrow and functionality?

**Comment by agirton** [comment]
Looks like that is not supported ATM. Could always open a PR so the arrowRenderer also encompasses the event handlers. That way if you pass in undefined those handlers wouldn't be added. 😄 Until then disabling pointer events on the `Select-arrow-zone` class will prevent mouse/touch events.

**Comment by Kristiyan96** [comment]
If anyone is still wondering how to remove the arrow, the last example on [this](https://react-select.com/creatable) docs page shows a workaround:

const components = {
  DropdownIndicator: null,
};
