### ISSUE TITLE
Move project to an Org and add more maintainers

### ISSUE THREAD

**Issue by glentakahashi** [JedWatson/react-select#1701]
@JedWatson are there others that can help maintain this project? It's still the best react/select library around, but there are quite a few PR's/features that have been sitting in the queue unaddressed for a long time

**Comment by glentakahashi** [comment]
I also found https://github.com/JedWatson/react-select/issues/1403, which suggested moving this to an organization instead of personal repo. The action there was to consolidate into the Release 1.0.0 issue, but no action has been taken there for 3 months either. Could we re-open this issue? 

Also pinging some people who might want to weigh in on this. @bvaughn @giladgray @mcorteel @BreahnaDavid @MarkLeMerise  @TrevorBurnham @jooj123 @silvenon

**Comment by bvaughn** [comment]
I think that moving this to an organization with more owners would be great for the community and Jed both. I'm a fan 👍 

That being said, I can't speak for Jed here as I didn't create this project.

**Comment by MichaelDeBoey** [comment]
I also think it's best to move this repo (together with other repo's like [`react-input-autosize`](https://github.com/JedWatson/react-input-autosize)) into an organization with more owners, who can maintain the project better, so @JedWatson doesn't have to sit on top of the pile of issues an PR's 🙂

**Comment by mcorteel** [comment]
Agreed.

**Comment by hiramhibbard** [comment]
Voting for this as well. This package will no longer work with the next version of React if it doesn't get updated before then.

**Comment by paramaggarwal** [comment]
@JedWatson please consider moving this project to the community at https://github.com/reactjs

**Comment by MichaelDeBoey** [comment]
@JedWatson: Defo agree with @paramaggarwal 🙂

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
