### ISSUE TITLE
Async component update options in weird way

### ISSUE THREAD

**Issue by jpomykala** [JedWatson/react-select#1708]
onChange method

```
  onChange(selected) {
    this.setState({ selected });
  }
```

load more options - `data.data` contains proper array
```

  loadOptions(query, callback) {
    Axios.get('/suggestions', { params: { query } })
      .then(({ data }) => ({ options: data.data }))
      .then(suggestions => callback(null, suggestions));
  }
```
          

Async component
```
<Select.Async
            multi
            autoload
            cache={false}
            ignoreAccents={false}
            ignoreCase={false}
            value={selected}
            clearable={false}
            loadOptions={this.loadOptions}
            onChange={this.onChange}
            valueRenderer={d => <SuggestionOption data={d} />}
            optionRenderer={d => <SuggestionOption data={d} />}
          />
```
I typed first two letters and i'm getting results
![screen shot 2017-05-06 at 12 01 03](https://cloud.githubusercontent.com/assets/1548104/25771520/5946cada-3254-11e7-8fe4-bfd37e25362e.jpg)

i typed another one and results gone
![screen shot 2017-05-06 at 12 01 09](https://cloud.githubusercontent.com/assets/1548104/25771521/5cdbb6b0-3254-11e7-9242-2f3ba66fceaf.jpg)

moreover sometimes results are not showing at all, even REST api return array with suggestions

**Comment by evelan** [comment]
Hmm I added 
```
labelKey="title"
valueKey="title"
```
because I getting objects like `{ title: 'something', type: 'SOME_TYPE' }` that is why i'm using valueRenderer and optionRender to handle this. But still i think it's some kind of bug.

**Comment by Enclave88** [comment]
I have the same issue, by the way. And the same decision.

**Comment by agirton** [comment]
Hi @evelan if the options don't match the default `labelKey` or `valueKey` you will see this issue. This may be something we should clarify as I've seen it come up a few times now. The odd part is the first set of results shouldn't show.

**Comment by nicolasazrak** [comment]
I found that filterOption tries to match with given label and key if you don't specify a default (https://github.com/JedWatson/react-select/blob/master/src/utils/defaultFilterOptions.js). If you have different fields and you are already doing a server side filtering you can use `filterOption={() => true}`

**Comment by MartijnHols** [comment]
I got it to work with `filterOptions={options => options}`.

**Comment by madou** [comment]
Is anyone looking into this? There must be a problem we can fix somewhere in `Select`. Happy to look into it if noone is yet.

**Comment by brianedelman** [comment]
+1 for this still being an issue

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
