### ISSUE TITLE
The option list is empty when remove/add twice the previously selected options

### ISSUE THREAD

**Issue by florianlebrenn** [JedWatson/react-select#1709]
Case to reproduce this bug:
1. Go to https://jedwatson.github.io/react-select/ on "Contributors (Async)" example
2. Remove "Jed Watson"
3. Re-Add "Jed Watson"
4. Remove "Jed Watson" again
5. When I try to select an option, the select list is empty. Only "Type to search" is displayed

Is it a bug or a specific case?
If it isn't a bug how to force the rendering of the option list?

Thanks in advance.

**Comment by agirton** [comment]
Hi @florianlebrenn This is because the component is mounted with contributors, this may not always be the case. You would have to handle the logic to always show a list that's loaded asynchronously.
