### ISSUE TITLE
Changing required programatically doesn't work

### ISSUE THREAD

**Issue by NGuldager** [JedWatson/react-select#1710]
If the required attribute is bound to a variable it sets the required attribute on the input field correctly when changing from `false` to `true` but doesn't remove it again when it is changed from `true` to `false`.

**Comment by agirton** [comment]
HI @NGuldager looks like it's due to this right here: https://github.com/JedWatson/react-select/blob/9943711e256d61aab937445c1f69502de43f780b/src/Select.js#L197. It's just checking for `falsy` values. I don't see any open PRs to fix this. Would you like to fix this?

**Comment by karaggeorge** [comment]
@agirton Here is a PR to fix this issue:
https://github.com/JedWatson/react-select/pull/1839

**Comment by JedWatson** [comment]
Fixed by #1839
