### ISSUE TITLE
disabled=true causes Firefox 52 to crash on Windows 7

### ISSUE THREAD

**Issue by broadhu2** [JedWatson/react-select#1712]
`<ReactSelect
                                    disabled={true}
                                    className="class"
                                    searchable
                                    labelKey="label"
                                    valueKey="value"
                                    simpleValue
                                    options={this.state.options}
                                    onChange={this.handleSelect}
                                    value={this.state.input} />`

Passing true for disabled prop in this example causes Firefox 52.0.2 (32-bit) on Windows 7 to crash. Does not crash when disabled is set to false or when disabled prop is not specified. 

Possibly related to https://github.com/JedWatson/react-select/issues/1521 

I see that there is a pull request with a fix for this https://github.com/JedWatson/react-select/pull/1556
When will this be approved?

**Comment by agirton** [comment]
Hi @broadhu2 #1556 was merged. Closing.
