### ISSUE TITLE
valueRenderer called several times

### ISSUE THREAD

**Issue by asdkalluri** [JedWatson/react-select#1713]
I'm not sure if this is expected behaviour.

- My renderValue funtion is called several times and I don't see a pattern to it. I expect it to be called just once when a new value is entered.
- Also, all the values already rendered are being passed to the renderValue once again.

FYI : I make ajax calls to validate the input and render them differently based on the ajax result. And that delay adds up.
Any suggestions?

```

<AsyncCreatable
            value={this.state.selectValues}
            multi={true}
            autoload={false}
            valueRenderer={this.renderValue.bind(this)}
            loadOptions={this.getOptions.bind(this)}
            isLoading={this.state.isLotAsyncLoadingExternally}
            onChange={this.someFunction.bind(this)}
/>
```

```
 renderValue(option) {
        console.log(option.label);
     axios(...);
}
```

**Comment by agirton** [comment]
@asdkalluri this seems like a bad area to put an effect due to render can be called multiple times if state or props change. Could you do this within your `getOptions`?

**Comment by asdkalluri** [comment]
I use the 
> AsyncCreatable
which lets users enter their own values. I wouldn't have to validate if I got rid of the Creatable.
For now, I'm working around it using "onChange"
