### ISSUE TITLE
Any way to disable client side filtering for Async

### ISSUE THREAD

**Issue by arthurchipdean** [JedWatson/react-select#1714]
I'm creating an autocomplete/ suggestion tool that fetches options from the server. Some of the options are synonyms and do not exactly match what the user is typing and it seems like these are automatically being filtered out. Is there anyway to disable this behavior and just display the results from the server? I don't see any options listed to do this.

Thanks!

**Comment by G710** [comment]
Thank you, I was wondering why my results were not showing. I found a way to diable the client filtering by setting a custom filter function as follows:

```
filterOptions={(options, filter, current_values)=>{return options;}}
```

Where options is the complete array, filter is the user input and current_values are the currently selected values.

**Comment by arthurchipdean** [comment]
That worked for me! Thanks :)

**Comment by dsullivan7** [comment]
For those trying to do this from v2 onwards, I found that the following worked:

```
filterOption={() => true}
```

**Comment by Ahmad-Wali-Sh** [comment]
But the Thing with this solution is, it override `filterOption={createFilter({ ignoreAccents: false,})}` and it would not be performance optimized.
any solution?
