### ISSUE TITLE
Option to always show the clean button.

### ISSUE THREAD

**Issue by diasbruno** [JedWatson/react-select#1715]
Hi. 

This feature consists on changing the `clearable`option to accept a `number` between `0..2`.

```js
export const NEVER_SHOW_CLEAN = 0;
export const SHOW_CLEAN =  1;
export const ALWAYS_SHOW_CLEAN = 2;
```
Maybe we can choose better names for the constants, but for now it looks ok.
I still need to write the tests.

Patch is available on my fork [diasbruno/react-select#feature/option-to-show-clean-button](https://github.com/JedWatson/react-select/compare/master...diasbruno:feature/option-to-show-clean-button).

I'll finish and submit a PR, if you all approve this idea.

**Comment by agirton** [comment]
Hi @diasbruno always showing the clear button feels like a poor UX. Users may think that there is some value already so they would click to clear. If it doesn't do anything then it would feel broken. Thoughts?

**Comment by diasbruno** [comment]
@agirton it can be useful to trigger some actions, but only on very specific implementations (very uncommon for this kind of component).
yeah, I understand what you mean by poor UX, but to be considered poor, we would needs to know the full context and how it works. this is where this feature can help.

**Comment by diasbruno** [comment]
@agirton Since this implementation would be helpful on rare cases, I think it's ok to reject this feature.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
