### ISSUE TITLE
React v15.5.4 gives PropTypes and React.createClass depreciated warning

### ISSUE THREAD

**Issue by OsamaShabrez** [JedWatson/react-select#1717]
With react 15.5 importing PropTypes or using React.createClass is depreciated, more information here: [https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

I am currently using 15.5.4 and react-select is throwing warnings for the same reason. Is this something already reported or a fix around this problem other than downgrading my react version?

Everything was working great until react version 15.4.2 which I had before.

**Comment by seb-bizeul** [comment]
@OsamaShabrez  you can look at this pull request :
https://github.com/JedWatson/react-select/pull/1658
This is just a matter of time ...

**Comment by bsdo64** [comment]
#1658 This pull request is submitted but doesn't merged since a month ago..

**Comment by seb-bizeul** [comment]
@bsdo64 Sorry, I've updated the reference ...

**Comment by inoas** [comment]
Or https://github.com/JedWatson/react-select/pull/1658 ...
Hopefully one will make it into master rather soon!

**Comment by MichaelDeBoey** [comment]
This is fixed with #1658 and is now released 🙂
