### ISSUE TITLE
scroll not working in ios app

### ISSUE THREAD

**Issue by PankajJatav** [JedWatson/react-select#1721]
I am using react-select withe meteor. But the scrollbar not working in ios app.

**Comment by agirton** [comment]
Hi @PankajJatav I've tested react-select on iOS Safari. However was able to get it scroll. It seems that there must be something in your application that is preventing this. Are you able to provide a reproducible build? 

Thanks!

**Comment by PankajJatav** [comment]
@agirton Please check the issue in iOS app ie ipa.

**Comment by agirton** [comment]
Hi @PankajJatav, I'm sorry but I don't have the ability to test this within a iOS WebView. If the menu can't be scrolled it is due to a limitation with the WebView. This doesn't sound like an issue with react-select as we aren't doing anything special but just using `overflow auto`. With that said we do use `-webkit-overflow-scrolling: touch;`. But this shouldn't be an issue with iOS 7 and higher.

**Comment by MaxInMoon** [comment]
@PankajJatav do you use fastclick?

**Comment by PankajJatav** [comment]
No, I was not using fastclick. I removed the fastclick package.

**Comment by agirton** [comment]
Hi @PankajJatav I tried this package within a iOS Web View (Twitter's) and was unable to reproduce. It sounds like there is something within your application that is preventing the scrolling.

**Comment by PankajJatav** [comment]
Hi @agirton
I remove the fastclick because I was unable to select any option. Then I notice overflow scroll doesn't work in ios App. So I customize the package according to my need.
It will be great if you can run the app in ios simulator or iphone not in browser. Then you can reproduce the issue.

**Comment by MaxInMoon** [comment]
@PankajJatav I get this working on iOS, using fastclick , after adding `needsclick` class  (fixes select option bug) to every dom element of my custom option component

**Select**
```
      <Select
        ...
        optionComponent={MyOptionComponent}
      />
```
**MyOptionComponent**
```javascript
      <div className="needsclick"
           onMouseDown={this.handleMouseDown}
           onMouseEnter={this.handleMouseEnter}
           onMouseMove={this.handleMouseMove}>
          <p className="needsclick" >{children}</p>
      </div>
```

So with this code, I can select an option, and scroll too (on iOS, Android, Chrome, Safari and Firefox)

**Comment by agirton** [comment]
Hi @PankajJatav were you able to get it working? It sounds like you had to make some changes to React Select. If so what were those changes?

**Comment by thiagocoelho** [comment]
@agirton 

I'm using meteor and I have this problem too.

Using react-virtualized-select or react-select, both in latest stable version.

I can open the select but when I try to tap any option the select closes instantly.

It happens ONLY in iOS using Webview.

I'm not using fastclick or anything related.

@PankajJatav have you solved this?

**Comment by agirton** [comment]
Hi @thiagocoelho I’ve tried reproducing this by visiting the demo site via Twitter WebView and unable to. We will need a way to reproduce this.

**Comment by thiagocoelho** [comment]
@agirton Hello!

I've tested my app using the Twitter WebView too. In fact it's working!

Maybe the problem can be something related to Meteor / Cordova, some type of conflict or bug. I'm in a rush to solve this, I can't guarantee but I will try to create a simple demo app using Meteor to isolate the react-select and make some tests.

Just in case you want to see http://www.pokermaps.com.br/clubes

Thanks!

**Comment by thiagocoelho** [comment]
@agirton 

I notice that if I HOLD the desired option for one sec or more when the select is opened it works.

The problem occur only when I try to tap the option (the select closes without selecting the desired option).

Maybe you have any clue about this strage behaviour to help me?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
