### ISSUE TITLE
Focus autocomplete value before "Create" (Screenshot incl)

### ISSUE THREAD

**Issue by yarnball** [JedWatson/react-select#1722]
Hi,

Great work on this.

I would like to make it so "Create" is not the first/auto highlighted option when a user starts typing. 

Is it possible to make it match the value first, then give the option to create the value below it? 

I created a screenshot to help explain.

![screen shot 2017-05-14 at 9 34 54 pm](https://cloud.githubusercontent.com/assets/13043067/26033393/bffbaf52-38ee-11e7-9773-b9308f40e839.jpg)

**Comment by Stenerson** [comment]
@yarnball, see #1436

**Comment by yarnball** [comment]
Thanks, I've checked this out and tested it- but using the prop
`showNewOptionAtTop={false}` has no effect.

I even created a codesandbox to show my attempt- https://codesandbox.io/s/680RlO3vz

**Comment by Stenerson** [comment]
@yarnball, this change hasn't been merged yet so if you want it to work you'll probably have to fork this project or patch my changes somehow into your codebase. 

Keep in mind that build files are not checked in as a part of any changes to this project so you'll probably need to run `npm run build` from the react-select directory in your `node_modules` directory for any patched changes to take effect.

**Comment by agirton** [comment]
Closing as this will be fixed by #1436.
