### ISSUE TITLE
can you please support hint and description for select option values?

### ISSUE THREAD

**Issue by adamshe** [JedWatson/react-select#1724]
customized render will be even more flexible with icon prefix etc.
I could be wrong, but I didn't find it in example. overall, this control is great in firefox. but not in chrome.

Thanks

**Comment by agirton** [comment]
The Option can be customized to your liking, e.g. https://github.com/JedWatson/react-select/blob/master/examples/src/components/CustomComponents.js#L10 is this what you're looking for?

**Comment by agirton** [comment]
Hi @adamshe havent heard back so going to close this. If the pointed out feature doesn't work feel free to reopen.
