### ISSUE TITLE
Arrow down to select item is broken in 1.0.0-rc.4

### ISSUE THREAD

**Issue by MarkSMT** [JedWatson/react-select#1725]
Arrow down to select items from react select async is broken, check for it in the provided examples.

Version: ^1.0.0-rc.4

**Comment by yarnball** [comment]
+1

This is happening to me too with the non Async version of 1.0.0-rc.4

Also, I cannot hover/highlight my items>Are you able to?

**Comment by agirton** [comment]
@MarkSMT thank you for reporting. I'm looking into this.

**Comment by MarkSMT** [comment]
@yarnball it is broken as well, it all still works in rc3 though

**Comment by agirton** [comment]
Hi @yarnball, @MarkSMT this fix was just merged. Hoping to get a new release out soon.

**Comment by MarkSMT** [comment]
@agirton muchos gracias bro
