### ISSUE TITLE
Question: Can Select show items ordered?

### ISSUE THREAD

**Issue by jcabrerazuniga** [JedWatson/react-select#1735]
Hi
   Is there any option to order the items placed in a Select component?

thanks
Jose

**Comment by agirton** [comment]
Hi @jcabrerazuniga you can do the sorting before you pass them into the Select component. e.g.

```
const states = require('../data/states');
<Select options={states.sort((a, b) => a.value - b.value)} />
```

*Note* this implementation is purely for demo and I don't recommend using this type of approach of sorting within the render.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
