### ISSUE TITLE
when `labelKey` and `valueKey` are set to same field, value is not set

### ISSUE THREAD

**Issue by leojh** [JedWatson/react-select#1737]
If you have a list of values as such:
```
const values = [{ name: 'name1' }, { name: 'name2' }]
```
and it's passed to the `options` property with both `labelKey` and `valueKey` set to `name`, the component does not seem to have the right `value` set. For example, row highlighting and up/down arrow selections don't work.
```
<Select
  options={values}
  labelKey='name'
  valueKey='name'
/>
```

**Comment by agirton** [comment]
Hi @leojh this should be fixed in the next release. The focus was broken in the rc.4 release.

**Comment by agirton** [comment]
This has been fixed in rc5
