### ISSUE TITLE
Add multi-select limiter

### ISSUE THREAD

**Issue by dcousens** [JedWatson/react-select#174]
Adding a custom limiter would enable developers the ability check what is currently selected, and do things like:
- artificially limit the number of options a user can select (https://github.com/JedWatson/react-select/issues/148) based on their own logic, or
- Enforce minimum number of options

You could do this through a `limited` prop, which stops the user from selecting more options, but they can still be `clearable` and not `disabled`

That way this functionality should be easy enough to add for any level of control.

**Comment by codeorelse** [comment]
Is anyone working on this atm?

**Comment by kfajardo** [comment]
yes please. up?

**Comment by dcousens** [comment]
These features are possible AFAIK through https://github.com/JedWatson/react-select#multiselect-options

**Comment by JeanOsorio** [comment]
I know this issues is close, but limited the selector with the prop limited is not working for me. Also here in the documentation (https://github.com/JedWatson/react-select#multiselect-options) I did not see the limited prop. What I'm doing wrong.

**Comment by dcousens** [comment]
@JeanOsorio open a new issue?
