### ISSUE TITLE
Arrow keys not working in select.async

### ISSUE THREAD

**Issue by si2030** [JedWatson/react-select#1740]
First post on Github so I appologies beforehand if this is not quite written correctly.

This is a help request.

I have set up a select.async component which works.. mostly.  It does everything its suppose to do including get the data and load it. It also works if I use my mouse wheel and click to select so the mouse works.

However, if I try and use the arrow keys it just sits there and it does nothing. I am using React version 15.4.1. I am also using react-select version 1.0.0-rc4.

Here is the way I have structured the component.

`                  <Select.Async
                    {...inputProps}
                    onChange={onSuburbChange}
                    valueKey="id"
                    labelKey="suburbName"
                    loadOptions={this.handleSuburbSearch}
                    backspaceRemoves={true}
                  />`

and here is my suburb search that returns the suburbs.

`      handleSuburbSearch = (query) => {
        const { selectData } = this.props
        const companyStateId = selectData.companyStateId
        if (!query || query.trim().length < 2) {
          return Promise.resolve({ options: [] })
        }
        const queryString = {
          query: query,
          companyStateId: companyStateId,
        }
        return getSuburbs(queryString)
          .then(data => {
            return { options: data }
          })
      }`

So I have faithfully add in those options and used them correctly as I receive and display a dropdown of suburbs.

I have no idea why this would action the pressing if an arrow key.

Let me know any other requirements you need.

**Comment by agirton** [comment]
Hi @si2030 this is fixed in master. We will be publishing a new version within the next week.

**Comment by mir3z** [comment]
Still not working for me in `^1.0.0-rc.5`
