### ISSUE TITLE
Async.loadOptions should have an API to clear/restrict currently selected values

### ISSUE THREAD

**Issue by dmk23** [JedWatson/react-select#1742]
I have a case where Async widget values are filtered/controlled by other form elements

For example, we may have selectors for item_X and item_Y and want to make sure that item_Y can be only selected from a subset of compatible with currently chosen item_X's

The problem is if I open a form with existing selections of item_X/item_Y and start editing by removing a few item_X. When this happens my react app issues loadOptions on item_Y widget to successfully reset the available values. However, there is no way to check that the **currently selected** choices for item_Y are compliant with the changed item_X restrictions. Since loadOptions is async I cannot check the new state to see if the currently selected values are valid.

loadOptions should have an API for validating the currently selected values

**Comment by agirton** [comment]
Hi @dmk mind opening a PR? We can review your proposed changes there.

**Comment by dmk23** [comment]
I don't have any code to submit right now, just opening this up as a discussion item. I am sure this functionality could be useful to many others and it is just a matter of who might need it most urgently...

**Comment by agirton** [comment]
@dmk23 if you build it they may come 😉

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
