### ISSUE TITLE
clearOptions call in Async.render looks like a bug

### ISSUE THREAD

**Issue by dmk23** [JedWatson/react-select#1743]
I have run into some strange behavior with multi-select async widgets. After adding any selection from the list all the options would disappear and I could not continue selecting additional items

After tracing the react-select code I discovered that Async.render method clears the options if new selection is larger than the old one, which is what happens when you select anything in a multi-select.

For now I solved the problem locally by subclassing / overrding Async. However this looks like bug in the module that should be fixed. I'm also curious what was the original intent behind this call to clearOptions

**Comment by agirton** [comment]
Hi @dmk23 this is current expected behavior. We expect the options to clear out so the user can make an API call to find options. Does your loadOptions return the full list instead of a small subset?

**Comment by dmk23** [comment]
This behavior either makes no sense or doesn't work as intended

There are no follow-up API calls, all options just clear after selecting the first one. And this clearing does not trigger a reload, it just removes all options.

Even if you want to trigger a full reload after each item selection this ought to be a configurable option and not a forced behavior. If the query is the same, why do a reload?

**Comment by agirton** [comment]
Hi @dmk23 I understand your concern.

But many times after selecting an option, the user would be entering a new value and we have no way of knowing if the options already pulled down are the same as what would be pulled in from the API.

**Comment by dmk23** [comment]
This is, in fact, a bug, not a feature

Existing values are already being deduped by defaultFilterOptions, I've observed it by tracing

The call to clearOptions does nothing other than preventing selection of ANY second value

**Comment by agirton** [comment]
Hi @dmk23 this is the expected behavior in the current feature so your request to prevent clearing the options is a new feature. 😊

**Comment by agirton** [comment]
This is also related to #1557. Going to close this, we can continue the convo there 😊
