### ISSUE TITLE
Is it possible to search for custom option value, or all option values.

### ISSUE THREAD

**Issue by vedran-milic** [JedWatson/react-select#1744]
I'm trying to make a select filter, which searches for city or postal code. In this case city is label and code is value in options object. How can I set up component to searches for both city and code when typing?

**Comment by agirton** [comment]
Hi @vedran-milic this is the default behavior to match against label or value. Is this not working for you?

**Comment by vedran-milic** [comment]
Hi @agirton it's not matching value for me. Btw value in my json file is a number. Could it be that? Anyway this is my code:
```javascript
import options from '../../../data/static/cities.json';
const filterOptions = createFilterOptions({ options });
optionRenderer(option) {
    return (
      <div
        key={option.key}
        style={option.style}
        onClick={() => option.selectValue()}
      >
        {option.option.label}, {option.option.value}, {option.option.coordonnees_gps}
      </div>
    )
  }
<Field name="redux-form-field-name" type="text" component={props =>
  <VirtualizedSelect
    filterOptions={filterOptions}
    optionRenderer={this.optionRenderer}
    type="text"
    {...props.input}
    placeholder="Start typing..."
    options={options}
    onBlur={() => {
      props.input.onBlur(props.input.value)
    } }
  />
}/>
```

**Comment by agirton** [comment]
It looks like it's the `createFilterOptions` that is your problem. I would recommend to look into that and see what prop it's searching on. Closing this as it's not an issue with this package.

**Comment by vedran-milic** [comment]
@agirton Thanks, I will

**Comment by vedran-milic** [comment]
@agirton Solved it with adding indexes to <code>createFilterOptions</code>. Like this 
```javascript
const filterOptions = createFilterOptions({
  indexes: ['label', 'value'],
  options
});
```
