### ISSUE TITLE
1.0.0-rc.4 breaks keyboard navigation

### ISSUE THREAD

**Issue by EnriqueVidal** [JedWatson/react-select#1745]
About a week ago I upgraded from 1.0.0-rc.3 to 1.0.0-rc.4 to get rid of the `PropTypes` warning introduced in React 15.5, however I just noticed that navigating react-select options with the keyboard or highlighting when hovering the mouse over does not work.

Did something change in between that would cause this or am I using the component wrong? this is how a simple select looks like:

```es6
          <Select
            className="react-select-sm"
            clearable={false}
            labelKey="name"
            valueKey="id"
            placeholder="Customers"
            options={customers}
            value={form.customer}
            onChange={setCurrentCustomer}
          />
```

In this case `form.customer` is an object with proeprties `name` and `id` and options is just an array of similar objects, everything works with the exception of navigating the options. I rolled back to rc3 and it works there without any change.

Please advise.

**Comment by agirton** [comment]
Hi @EnriqueVidal this is fixed in master. We hope to get a new release soon.

**Comment by EnriqueVidal** [comment]
Thanks, I'll be checking the releases then.
