### ISSUE TITLE
Items in dropwdown aren't highlighted on hover

### ISSUE THREAD

**Issue by chrismv48** [JedWatson/react-select#1747]
The first item in the list is highlighted, but other items aren't highlighted when the cursor is over it. I'm using bootstrap to style adjacent form elements, but I've tried removing those classes and the issue persists. All other styling looks fine. Here is an example component where this is happening: https://github.com/chrismv48/debate_platform/blob/master/app/javascript/components/edit_new_premise.js

**Comment by agirton** [comment]
Hello! This is an issue in rc4. This will be fixed in the next release.

**Comment by blunatic** [comment]
Looks like this is still an issue in rc5, but it seems to be a bit more inconsistent. I don't have a fiddle or plunkr to post, but I have two components using react-select and for some reason one of them doesn't properly set the `is-focused` class name on hover, while the other does fine.

I'll update this with details if I can find out why.

**Comment by Superjisan** [comment]
So if anyone else gets stuck on this, I figured this out. You need to include a `valueKey` to ensure that hover items are properly highlighted. Strange little bug/feature
