### ISSUE TITLE
Add Inline-Version

### ISSUE THREAD

**Issue by chrys1110** [JedWatson/react-select#1748]
Could you add an inline-block style variant with auto-width depending on its content? Similar to a regular <select />-tag.
Just inserting inside an inline-block div doesn't do it. Since then it's still not autosized.

**Comment by agirton** [comment]
Hi @chrys1110 feel free to open a PR with proposed changes. 😊

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
