### ISSUE TITLE
onMenuScrollToBottom does not work in chrome 58.0

### ISSUE THREAD

**Issue by OsamaShabrez** [JedWatson/react-select#1749]
I am using Google chrome version 58.0.3029.110 (64-bit) on macOS 10.12.4 and `onMenuScrollToBottom` does not work while it does work in Firefox 53.0.3 and Safari 10.1

**Comment by agirton** [comment]
Hi @OsamaShabrez thanks for reporting. Do you have a Canary version of Chrome to see if you run into this issue on there also?

**Comment by OsamaShabrez** [comment]
Tested on Canary Chrome Version 60.0.3109.0 (Official Build) canary (64-bit); it does not work there either.

**Comment by cbergmiller** [comment]
It's working with Chrome 58.0.3029.110 on Windows 10.

**Comment by OsamaShabrez** [comment]
I can confirm it is still not working in MacOS

**Comment by deevus** [comment]
Not working for me either on 59.0.3053.3 dev (64-bit)
