### ISSUE TITLE
Select uses addEventListener/removeEventListener, which don't exist in IE8

### ISSUE THREAD

**Issue by StefanBilliet** [JedWatson/react-select#175]
Hi

In Select.js->componentWillMount(), you add/remove event listeners for when clicking outside the element. Apparently, IE8 doesn't support addEventListener/removeEventListener; it only supports attachEvent/detachEvent (the name of the click event is also different).
It's fairly simple to fix: https://github.com/StefanBilliet/react-select/commit/f0b004833b9f5a7545773425f36d28e4eea84ef5
My question is, are you open to these kinds of fixes?

With kind regards
Stefan Billiet

**Comment by dcousens** [comment]
@StefanBilliet we are open to these kind of fixes.   Please make a PR and we'll put it through the review cycle :)
Before making the PR, please read the CONTRIBUTORS file.

**Comment by julen** [comment]
Hey, this was fixed in #193, and it should be closed.

**Comment by dcousens** [comment]
Thanks @julen
