### ISSUE TITLE
Switch from Creatable Options to Data Options if the values of the options match

### ISSUE THREAD

**Issue by Keith-Ball** [JedWatson/react-select#1750]
# Scenario
I wish to allow users to paste data into the Select field, or to import data from a separate file, and doing this will create "Creatable" options.

After the user as pasted/imported the values in, they have the option of selecting a value from a different dropdown that invokes an API call that fills those selects with actual data from some repository. I believe an example of this might be:

```
var things = [];
var createdValues = [
{ label: "1", value: 1 },
{ label: "1", value: 2 }
];

const fetchThings = () => {
  API.fetchData((data) => {
     // Data contains an object that is { label: "New value", value: 1 }
     this.things = data;
  })
}

ReactDOM.render(
  <Select 
     name="form-field-name1"
     onChange={fetchThings}
     />
  <Creatable
    name="form-field-name2"
    options={things}
    value={createdValues} />,
  document.getElementById('example')
);
```
# Expected

I expect that the created option of "{ label: "1", value: 1 }" would be replaced with "{ label: "New value", value: 1 }"

# Actual

The option "{ label: "New value", value: 1 }" is not selectable, which is good, but my option of "{ label: "1", value: 1 }" doesn't change.

**Comment by Keith-Ball** [comment]
I expect this would be considered a new feature, rather than a bug.

**Comment by agirton** [comment]
Hi @Keith-Ball this would be great to have, but could be tricky to nail the right UX for all use cases. Would you be interested in building this?

**Comment by Keith-Ball** [comment]
Unfortunately I'm pretty swamped right now, so I doubt I'd be able to help develop it. However, I was able to create a hacky work-around for my purposes. Perhaps you can apply it when it's built out. This is psudo-code, so it might not work 100%.

```
componentDidUpdate() {
    const { selectedOptions, selectOnChange, data } = this.props;

    if (selectedOptions && data) {
        if (SELECT_IS_MULTI) {
            const newData = selectedOptions.map(existing => {
                const matchingData = data.find(d => d.value === existing.value);
                // This should be a flag to remove custom tags if they don't exist in the new data, or not.
                if (!matchingData) return null;
                if (matchingData === existing) return existing;
                return matchingData;
            }).filter(data => data !== null);
            if (newData !== selectedOptions) {
                selectOnChange(newData);
            }
        } else {
            const newData = data.find(d => d.value === selectedOptions.value) || '';
            if (selectedOptions !== newData) {
                selectOnChange(newData);
            }
        }
    }
}
```

An interesting thing I noticed was that this does not stop new options from being built via-creatables. This is because the new options are added to the list of data, so when it does `data.find(e => e.value === selectedOptions.value)` it's able to find the "new" data option.

This also doesn't take Async requests into consideration, though what I'm doing is more-or-less lazy loaded async by manually setting the data.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
