### ISSUE TITLE
Basic example doesn't work - clicking option highlights item below it.

### ISSUE THREAD

**Issue by sergiotapia** [JedWatson/react-select#1751]
Version: "react-select": "^1.0.0-rc.3",

Just a simple multi implementation:

```
<Select
  name="form-field-name"
  multi={true}
  options={[
    { value: "one", label: "One" },
    { value: "two", label: "Two" },
    { value: "three", label: "Three" },
    { value: "four", label: "Four" },
    { value: "five", label: "Five" }
  ]}
/>
```

https://gfycat.com/DaringIndolentCaecilian

I'm confused because this seems like the absolute most basic example. Let me know if you need more information.

**Comment by agirton** [comment]
Hi @sergiotapia can you please attempt this using the latest version `1.0.0-rc.5`?

**Comment by sergiotapia** [comment]
@agirton I figured out the issue, it was because the select component provided by this library is meant to be a controller input. I needed to set it's value and keep track of it. 

I used state, on the change handler I set the state, and on the value property I used that set state.

The example should probably mention this front and center so the first example people see works.

**Comment by agirton** [comment]
Hi @sergiotapia the first example does include the value. Going to close as it seems you got it figured out. 😊

**Comment by tractorcow** [comment]
Same issue is happining on http://jedwatson.github.io/react-select/

Enable "multi select" on the numeric values demo and you can see the same issue.
