### ISSUE TITLE
Async searchable can't expand until character entry

### ISSUE THREAD

**Issue by ericnewcomer** [JedWatson/react-select#1753]
The plunker seems to be broken, but thankfully this behavior is exhibited by the current examples.

Looking at the async multiselect example, when you initially click on it, it behaves as one would expect, loading the options with an input of "", yielding an unfiltered list. Once you select one of the options in the list, you can no longer click on the arrow to open the list again (which I would expect would initiate a new query of ""). If you type a single character in the box and then delete it, you can get the box to initiate a new query. 

To me, this does not sound like the expected behavior. I would expect it to initiate an empty query on trying to expand the dropdown. Also, if I give it focus, I would expect the same empty query to initiate just as it does the first time it gains focus.

Can one of the maintainers of the project weigh in on this behavior and help me understand if this is intentional or not? Happy to look into this if it is indeed a bug.

<img width="391" alt="async init" src="https://cloud.githubusercontent.com/assets/211652/26425340/05fbcc46-409a-11e7-9a3f-3ff41f8e3b07.png">

**Comment by ajbdev** [comment]
Some of my team just reported the exact same issue to me today, so it does seem that this breaks most people's expectations as to how the dropdown should function.

**Comment by agirton** [comment]
Hi @ericnewcomer this is related/dup of #1557 feel free to continue the discussion there.

**Comment by bernatfortet** [comment]
@agirton could you re-open this issue since #1557 is closed and has no mention of this problem?

Also, has anybody found a solution to loadOptions when selecting/opening menu?

**Comment by vladlucapitech** [comment]
I'm having the same issue, I think loadOptions call on selecting/opening menu may be a good idea.

**Comment by Dartv** [comment]
This is so must have. Why is this not implemented yet?
