### ISSUE TITLE
Paste items with line breaks in IE

### ISSUE THREAD

**Issue by asdkalluri** [JedWatson/react-select#1754]
When i paste items (coming from an MS Excel use case) which look like this
```
item1
item2
item3
```
into the Select box, the results looks like this:
- _IE_ : item1
- _Chrome_ : item1 item2 item3

Basically, Chrome takes the line breaks and doesn't lose data. IE does.
Is there a workaround for this?

I started with something like this:
```
 onInputKeyDown={((event) => {
                if (event.ctrlKey && event.keyCode == 86) {
                  ....
                //Get the clipboard data from IE
            }
//How do i change the input here?
}
```

**Comment by cbergmiller** [comment]
You can manipulate the input value with [onInputChange](https://github.com/JedWatson/react-select#updating-input-values-with-oninputchange). In your case you probably need to normalize the line-breaks, but that's just a guess.

**Comment by agirton** [comment]
Hi @asdkalluri can you confirm if using the suggested method by @cbergmiller fixes your issue? Since we are a controlled component the values that enter should be normalized.

**Comment by agirton** [comment]
Closing as we haven’t heard back
