### ISSUE TITLE
Refactoring (ES6 classes, JSX files)

### ISSUE THREAD

**Issue by cbergmiller** [JedWatson/react-select#1755]
Is there any interest in refactoring react-select to use ES6 classes instead of `React.createClass`?
The use  of JSX file extensions would be another suggestion, possibly along with the use of a newer bundler (NWB or CRA?).
Also some of the test files are huge and hard to browse. They could be split in multiple files.

I would be willing to invest time if this aligns with the projects roadmap.

**Comment by agirton** [comment]
Hi @cbergmiller there is a proposed PR #1702. We have to figure out if we want to bring this in before or after 1.0 release.
