### ISSUE TITLE
Passing a custom input component as the search component

### ISSUE THREAD

**Issue by AchinthaReemal** [JedWatson/react-select#1757]
Hi,

Is it possible to pass a custom input field component for react-select ?

**Comment by agirton** [comment]
Hi @AchinthaReemal, we use https://github.com/JedWatson/react-input-autosize, not sure I see value in allowing to use your own. This could greatly change the way the select behaves, which may cause further issues down the road. It also increases our API surface.

**Comment by agirton** [comment]
Hi @AchinthaReemal I misspoke, we don't allow a custom input, but if you use `autosize` false. Then you can pass in `inputProps` to customize. Hope this helps.

**Comment by AchinthaReemal** [comment]
@agirton thanx for the info, but what I'm looking for is a way to pass an input component all together. So it seems like I have to find an alternative to get around this issue. Thanx again.
