### ISSUE TITLE
How to blur the select placeholder div after choose?

### ISSUE THREAD

**Issue by amerllica** [JedWatson/react-select#1763]
In [demo page](http://jedwatson.github.io/react-select/) the first option, "Victoria", after I choose it, the select placeholder div, still focus, how I blur it after change?

**Comment by cbergmiller** [comment]
Try setting the `autoBlur` prop:
https://github.com/JedWatson/react-select#further-options

**Comment by amerllica** [comment]
I guessed it is my solution. but I know where I use it to make `true` the `autoBlur` value?

**Comment by cbergmiller** [comment]
To enable (set to true) a boolean prop in React you can write
```JSX
<Select value={someValue} onChange={handeChange} autoBlur/>
```

**Comment by amerllica** [comment]
Thanks jed. you're my man
