### ISSUE TITLE
Left-Right Arrow key navigation between tabs

### ISSUE THREAD

**Issue by KokoChris** [JedWatson/react-select#1767]
I was wondering if there is any way to do left-arrow key navigation between  tags in order to delete
tags added earlier?

If there is no way to do it right now would you be interested in said functionality? How would you go about it? I understand that backspace functionality would need to be altered.

**Comment by agirton** [comment]
Hi @KokoChris this would be interesting to have. There is no way to jump between the tags but you're more than welcome to work on such feature :smile:. One area you will need to be aware of is if the menu is closed or not, because that might impact navigating the menu options.

**Comment by nickswope** [comment]
this feature was released with [2.0.0-beta-3](https://github.com/JedWatson/react-select/blob/master/HISTORY.md#v200-beta3--2018-05-14) and is working in latest release so this issue can be closed

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
