### ISSUE TITLE
Can't input uppercase in Select.Async

### ISSUE THREAD

**Issue by AlingChen** [JedWatson/react-select#1769]
Hi,
I can't input uppercase in Select.Async. Is there any way to resolve it?
Thanks

**Comment by agirton** [comment]
HI @AlingChen It looks like you are looking for the prop `ignoreCase` to be set to false. Does this solve your issue?

**Comment by agirton** [comment]
@AlingChen haven't heard back so closing this out. Feel free to reopen if the prop didn't solve your issue.
