### ISSUE TITLE
default InputValue

### ISSUE THREAD

**Issue by lexxizz** [JedWatson/react-select#1770]
Hello! 
How can I set the default InputValue?
Thank you.

**Comment by cbergmiller** [comment]
Hi @lexxizz !

Could you explain what behavior you are looking for?
Did you mean default option?
Select is designed to be a "controlled" component. The controlling component would usually be used to preselect a default option by `props.value`.

**Comment by agirton** [comment]
Hi @lexxizz closing out as we have not heard back from you. Feel free to reopen if @cbergmiller suggestion did not solve your use case. Thanks!
