### ISSUE TITLE
Select.Async multi doesn't work

### ISSUE THREAD

**Issue by dizel3d** [JedWatson/react-select#1771]
![2017-06-02_12-25-09](https://cloud.githubusercontent.com/assets/593571/26719836/bbcce2ee-478e-11e7-949c-022709fd28e3.gif)
[Recommended plunker](https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview) doesn't work, so I put the code here below.
```ts
class Foobar extends React.Component<null, {value: string[]}> {
    constructor(props) {
        super(props);
        this.state = {
            value: []
        };
    }

    options = [
        { value: 'one', label: 'One' },
        { value: 'two', label: 'Two' }
    ];

    loadOptions = (input, callback) => {
        callback(null, {options: this.options});
    };

    onChange = (options) => {
        this.setState({
            value: options.map(x => x.value)
        });
    };

    render() {
        console.log('state', this.state.value);
        return (
            <div>
                <p><b>Select</b> works well</p>
                <Select
                    multi
                    value={this.state.value}
                    options={this.options}
                    onChange={this.onChange}
                />
                <p>but <b>Select.Async</b> breaks as soon as you select an option</p>
                <Select.Async
                    multi
                    value={this.state.value}
                    loadOptions={this.loadOptions}
                    onChange={this.onChange}
                />
            </div>
        );
    }
}
```

**Comment by dizel3d** [comment]
Adding of `key={this.state.value.length}` is a workaround.
```jsx
<Select.Async
    multi
    key={this.state.value.length}
    value={this.state.value}
    loadOptions={this.loadOptions}
    onChange={this.onChange}
/>
```

**Comment by dekelb** [comment]
You can also check this pr #1612

**Comment by antonycourtney** [comment]
Thanks @dizel3d for reporting this and workaround. I am also getting bit by this issue trying to use react-select for the filter editor in [Tad](http://tadviewer.com/). The proposed workaround of setting `key` does help, but then the overall select control seems to lose keyboard focus each time a value is added to the selected set.

**Comment by dizel3d** [comment]
@antonycourtney, `key` changing forces React to replace the element in DOM tree, so it leads to focus losing.

**Comment by antonycourtney** [comment]
@dizel3d Yep, understood. All the more reason to hope for a real fix. :-)

**Comment by vincentlabatut** [comment]
Hi same problem here, here's my workaround with 1.0.0-rc.3:
I don't use Async but regular Select
have a "loading" boolean in the state and map it to the isLoading and disabled attributes. Also adjust the placeholder.

```JSX
<Select
    isLoading={this.state.errortypeLoading}
    disabled={this.state.errortypeLoading}
    value={this.state.errortype} multi={true}
    options={this.state.errortypeOptions}
    onChange={this.handleSelectChanged.bind(this,'errortype')}
    placeholder={this.state.errortypeLoading ? "Loading..." : "Error type"} 
/>
```

in the in the getInitialState, fetch the values :
``` javascript
    getInitialState() {
        let component = this;
        fetch('api/TestData/Qualif/GetErrorTypes', {
            method: 'get',
            headers: {
                'Accept': 'application/json',
            }
        }).then(function(response) { 
            return response.json();
        }).then(function(j) {
            console.log(j); 
            component.setState( { errortypeLoading: false, errortypeOptions: j });
        }).catch(function(error) {
            console.log('error '+ error); 
        });

        return { errortype: this.props.filter.errortype, errortypeLoading: true, errortypeOptions: [] };
    }
```

**Comment by ndbroadbent** [comment]
I've tried downgrading to `1.0.0-rc.2`, but then there's a serious bug when using multiple Selects. They all seem to share the same options instead of loading them individually.

**Comment by timini** [comment]
is this fixed yet?

**Comment by nbudin** [comment]
Async with multiple selection seems to work fine in 2.0 (which is a total rewrite and probably requires changing your code that uses the react-select components, but does seem to fix the problem).

**Comment by cmbasnett** [comment]
This is still broken in 2.1.1. Selecting any option makes it impossible to see or select further options.

**Comment by DarkLegend** [comment]
Having the same issue as @cmbasnett with 2.1.1
The first value selects fine, but afterwards the options returned by laodOptions are never shown anymore.

**Comment by javastud** [comment]
@DarkLegend can you send a fiddle or codesandbox... I couldnt get it working with latest release

**Comment by AtulVerma12** [comment]
it is fixed please use this.
import AsyncSelect from "react-select/lib/Async";
<AsyncSelect
                    getOptionLabel={({ name }) => name}
                    getOptionValue={({ id }) => id}
                    loadOptions={this.promiseOption}
                    isMulti
                    onChange={option => this._handleChangeInSelect(option)}
                  />

**Comment by knowsarzehmeh** [comment]
@AtulVerma12, can you please accompany this with a codepen, cos it's not working for me

**Comment by knowsarzehmeh** [comment]
@AtulVermal12, please shed more light on your fix

**Comment by bladey** [comment]
Hi all! I'd appreciate a Codesandbox link to replicate this issue so I can investigate, thank you.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone can provide a Codesandbox example, please let me know and the issue will be re-opened.
