### ISSUE TITLE
Required validation error placed on top of options

### ISSUE THREAD

**Issue by 1Jesper1** [JedWatson/react-select#1772]
When using the required attribute on the selectbox the validation error message is on top of the options  menu when clicked. The message reshows after a click on the input field.
I would like to see the options menu placed over the error message.

Plunker: [https://plnkr.co/edit/RxrQEX?p=preview](https://plnkr.co/edit/RxrQEX?p=preview)
Default required selectbox behaviour: [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_select_required](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_select_required)

**Comment by cbergmiller** [comment]
Hi @1Jesper1!

Thanks for reporting this issue!
I am afraid there is not a lot that can be done to improve the built-in browser form-validation (HTML5) in the Select code.
The validation message itself cannot be styled, see [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#Customized_error_messages)

You can try to set the `autosize` prop on Select. This will affect the way the input element is rendered. The validation box may be displayed centered andno longer overlap your options.
You also could drop the HTML5 validation in favor of a scripted solution. Take a look at [redux-form](http://redux-form.com/6.7.0/examples/syncValidation/) or [react-redux-form](https://davidkpiano.github.io/react-redux-form/).

Here is a link to a blog post about [form validation in react](http://moduscreate.com/reactjs-form-validation-approaches/).

Does this solves your problem with Select?

**Comment by 1Jesper1** [comment]
Hello @cbergmiller , thanks for the advise. Unfortunately it seems setting the `autosize `property does not affect the display. I'm interested why the validation error displays each time you click in the input field. There is no need to show it after clicking on the input field  I think. This behaviour is not present in the default select required.

**Comment by agirton** [comment]
Hi @1Jesper1 it's most likely due to the way it's rendered. What's the main benefit of using HTML5 required? Even though it's a native feature, it lacks the ability to style so it's a suboptimal feature.

**Comment by 1Jesper1** [comment]
Hello @agirton, personally I use it because it's just giving the select component the required property of true. Maybe we can improve this behaviour?

**Comment by Vishal1419** [comment]
I would like to have custom error message for required. How can I change that?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
