### ISSUE TITLE
How to get value before perform clear input ?

### ISSUE THREAD

**Issue by nzhtrtlc** [JedWatson/react-select#1775]
I have a clearable Select and i can get value with onChange listener.
Problem is i can not get the value before i clear the input.

**Comment by agirton** [comment]
Hi @nzhtrtlc you will need to this in your app. onChange we don't keep around the previous state. If you are using React's State system you can get this through lifecycle methods.

**Comment by nzhtrtlc** [comment]
I have a state but i update the state select's onChange metod, so that when i clear the input value returns empty onchange method so state updates as empty.
I solved problem with an alternative way. But i think it'll be cool if you can add this future.

**Comment by agirton** [comment]
@nzhtrtlc that would mean we would have to keep the value in our state, which is what we removed in 1.0. This can be solved in user land, going to close this out.
