### ISSUE TITLE
using onInputChange for logging

### ISSUE THREAD

**Issue by crashspringfield** [JedWatson/react-select#1784]
I'm trying use onInputChange for tracking, but can't even get the function to be called. Here's an abridged version of my code:

    updateInput = () => {
        console.log('updateInput')
        console.log(input)
        return input
    }

    render = () =>
      <Select.Async onInputChange={this.updateInput} />

It doesn't log anything, so I assume it's not even being called. However, when I use `onInputKeyDown` it works.

**Comment by agirton** [comment]
Hi @crashspringfield I'm not seeing this behavior. What version are you running? We have tests that guard against this breaking (https://github.com/JedWatson/react-select/blob/master/test/Async-test.js#L427). Can you provide a test case where it's failing?

**Comment by crashspringfield** [comment]
I'm using version 1.0.0-rc.1. I'll try to create a test case.

**Comment by agirton** [comment]
Hi @crashspringfield are you able to update to the latest version? We are on rc5 now.

**Comment by agirton** [comment]
Hi @crashspringfield closing this out as we have not heard back from you. Feel free to reopen if there is a case we are not accounting for. Thanks!
