### ISSUE TITLE
Object.Assign is not supported in Internet Explorer

### ISSUE THREAD

**Issue by phamcharles** [JedWatson/react-select#1785]
Supported in Microsoft Edge (Edge browser). Also supported in Store apps (Microsoft Edge on Windows 10). See Version Information.
Not supported in the following document modes: Quirks, Internet Explorer 6 standards, Internet Explorer 7 standards, Internet Explorer 8 standards, Internet Explorer 9 standards, Internet Explorer 10 standards, Internet Explorer 11 standards. Not supported in Windows 8.1.

See more at https://docs.microsoft.com/en-us/scripting/javascript/reference/object-assign-function-object-javascript

In the code base there is a polyfill for Object.Assign called object-assign by Sindre Sorhus but it is not being used.

**Comment by agirton** [comment]
@phamcharles looks like there is a polyfill from the older babel. Which I hope to upgrade soon. I would recommend you use a polyfill in your project.

**Comment by agirton** [comment]
Hi @phamcharles closing this as this can and should be done by the user.
