### ISSUE TITLE
Optional rendering of arrow

### ISSUE THREAD

**Issue by rmmjohann** [JedWatson/react-select#1788]
It would be nice if the rendering of the arrow would be optional.
Implemented with #1761

**Comment by yih-en** [comment]
I totally agree. Currently, I avoid the rendering of the arrow by setting ```arrowRenderer={()=>{}}``` and ```  <style>{
      `.Select-arrow-zone {
         width: 5px;
      }`
    }
    </style>``` in my component, which is quite ugly. Would be nice if the PR will be merged to the master sooner.

**Comment by agirton** [comment]
Hi @rmmjohann no need to open an issue when there is a PR. Let's move the discussion to the PR #1761. Thanks!
