### ISSUE TITLE
Add value which is not in a list

### ISSUE THREAD

**Issue by barsukov** [JedWatson/react-select#179]
How it possible to add value when it is not in a list of options? I recceived every time empty value:(
like create = true? is it support?

**Comment by dcousens** [comment]
@barsukov can you elaborate on what it is you're trying to do?  Maybe a [pseudo] code example?

**Comment by barsukov** [comment]
Ok I will try to explain it here.
Like in Selectize lib I want to have ability to add Item when nothing is found like that
![screenshot 2015-05-12 12 42 19](https://cloud.githubusercontent.com/assets/1594996/7585495/6bf0486e-f8a4-11e4-91f8-d2705b9db9dc.png)
Instead of 
![screenshot 2015-05-12 12 43 32](https://cloud.githubusercontent.com/assets/1594996/7585525/849d966e-f8a4-11e4-8f41-0244a8a5053a.png)
I found the PR here in development which provide functionality like ``<Select ... creatable={true} />
https://github.com/JedWatson/react-select/pull/101
This functionality Is very very very important, without it this component should not be usable...

**Comment by anthonator** [comment]
I've been able to accomplish something like this when using `asyncOptions`.

Here's an example.

```js
import React from 'react';
import Select from 'react-select';

class TagSelect extends React.Component {
  render() {
    return (
      <Select {...this.props} asyncOptions={ this._handleAsync } delimiter=',' multi={ true } />
    );
  }

  // private

  _handleAsync(input, callback) {
    setTimeout(function() {
      callback(null, {
        options: [
          { value: input, label: input }
        ]
      });
    }, 500);
  }
}

export default TagSelect;
```

**Comment by barsukov** [comment]
This solution is good , but it looks like 

![](http://s1.developerslife.ru/public/images/gifs/841b3185-92b7-4515-af6b-5506606e052e.gif)

**Comment by barsukov** [comment]
@anthonator and your example works only in one direction, What if I want to have the search for existance options(like I received from server, and if I did not found anything I want to add this value) So useful case I am really did not understand why it is not out of the box ;(

**Comment by anthonator** [comment]
You should be able to do that.

Here's a real world example of me fetching tag values from the server and also adding the user's input at the top so the user can select what they're currently typing as an option.

If you wanted to only show the user's input if nothing was returned from the server you should be able to tweak something like this to make that work.

```js
_handleAsync(input, callback) {
    let options = [];

    if (!_.isEmpty(input)) {
      options.push({ value: input, label: input });

      TagQueries.autocomplete(this.state.data.get('id'), input)
        .then(() => {
          TagStore.get(this.state.data.get('id')).forEach((tag) => {
            options.push({ value: tag.get('id'), label: tag.get('name') });
          });

          callback(null, { options: options });
        });
    } else {
      callback(null, { options: options });
    }
  }
```

**Comment by dcousens** [comment]
Added in https://github.com/JedWatson/react-select/pull/151
