### ISSUE TITLE
Unsure how to use focus

### ISSUE THREAD

**Issue by JHRms** [JedWatson/react-select#1790]
Hey @JedWatson ,

In my project, I have two dropdowns using <Select ...>. After choosing an option from the first dropdown, I want to autofocus to the second dropdown (to avoid having to click TAB). I saw some of your documentation for focus, but I have absolutely no idea how to use it. Any step by step help would be appreciated!

**Comment by agirton** [comment]
Hi @JHRms in order to focus another select you will need to first get reference to the other select. E.g 
```
<Select ref={node => this.secondSelect = node} {...otherProps} />
```
Then in your first select you would call `this.secondSelect.focus()` in the `onChange` handler.

**Comment by JHRms** [comment]
With the project I am working on, I have the <Select ...> within a component. For instance:

class Component1 {
   <Select ...>
}

And I am calling this component two separate times in another component. So it is like: 
class MainComponent {
   <Dropdown1 ...>
   <Dropdown2 ...>
}

These dropdown components calls the component with the Select individually:
class Dropdown1 {
   <Component 1 ...>
}
class Dropdown2 {
   <Component 1 ...>
}

rather than:
<Select ...> 
<Select ...>.

So with my case, I can't use ref in the <Select ...> because it would apply to both of the dropdowns. How would I handle the focus now?

**Comment by agirton** [comment]
@JHRms you can still get the reference to each of Select components. Based on your setup, you will just need to pass those from Component to Dropdown then to MainComponent. Then in the main component pass the second reference to the first Select component.

**Comment by JHRms** [comment]
I am trying to implement it like this, if I am understanding this correctly:

class MainComponent {
   <Dropdown1 onChange={function_call} {...otherProps}>
   <Dropdown2 ref={node => this.secondSelect = node} {...otherProps}>
}

function_call {
...
this.secondSelect.focus();
...
}
------
class Dropdown1 {
   <Component 1 onChange={this.props.onChange} {...otherProps}>
}
class Dropdown2 {
   <Component 1 ref{this.props.ref} {...otherProps}>
}
-----
<Select {...props}>

When I do this, I am "this.secondSelect.focus is not a function" and the ref that is passed is undefined. Any idea what the problem is?

**Comment by agirton** [comment]
@JHRms doesn't look like you are trying to access the Select's ref. You can't obtain it through a parent component without passing it up.

**Comment by JHRms** [comment]
I'm not too sure what you mean. In my project, I have the <Select> inside of a Stateless component. So it is:
const Component1 = (...) => (
   <Select ...>
)
Where would I place the ref (and how would I access it) amongst the Dropdown1, Dropdown2, and MainComponent?

**Comment by agirton** [comment]
@JHRms This is not really react-select specific but more so React. Here's an example:

In your Stateless component you need to pass in a method that will get the reference of the Select.
E.g.
```
function Component1(props) {
    return (
        <Select ref={props.getSelectRef} {...props} />
    )
}
```
Then where you declare your stateless component you assign it to a local variable to the Parent component.
```
class Dropdown1 {
  render() {
    return (
      <Component1 getSelectRef={node => this.selectNode = node} {...props} />
    )
  }
}
```
See the React docs for more info: https://facebook.github.io/react/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components

**Comment by agirton** [comment]
Let us know if you have any new issues but closing this out as it's been more than a week.
