### ISSUE TITLE
Accessibility issues...

### ISSUE THREAD

**Issue by LarsFinley** [JedWatson/react-select#1791]
@JedWatson Is there any way you could make this accessible by using tabIndex to navigate and enter to select?

**Comment by agirton** [comment]
Hi @LarsFinley I'm not an accessibility expert but users can use tab, arrow keys and enter to select or move around the dropdown. Is there a different behavior you had in mind?

**Comment by agirton** [comment]
Closing out issue as we haven't heard back.

**Comment by rojo59** [comment]
The accessibility problem is that on focus, a screen reader will read out "combo box".
