### ISSUE TITLE
react-select fields validation for empty input

### ISSUE THREAD

**Issue by Cod3Guy** [JedWatson/react-select#1794]
### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by agirton** [comment]
Hi @Cod3Guy what is the issue you are facing?

**Comment by agirton** [comment]
Let us know if you have any new issues but closing this out as it's been more than a week.
