### ISSUE TITLE
SearchPromptText displayed and style-able if !async

### ISSUE THREAD

**Issue by Drecula** [JedWatson/react-select#1795]
Hi,

We need a different prompt for placeholder and searchPromptText, with the ability to uniquely style searchPromptText.

So, something like:

`$search-prompt-text-color:          #868686;
$search-prompt-text-bg:             #F5F5F5;

	.Select-search-prompt-text {
		color: $search-prompt-text-color;
		background: $search-prompt-text-bg;
	}
`
I haven't chased down the code to make this change yet. Before I do, please let me know if this is something you'd like in react-select.

Thanks!

Andre

**Comment by agirton** [comment]
Hi @Drecula you should be able to style them differently with `.Select-placeholder` and `.Select-noresults`.

**Comment by Drecula** [comment]
Not just style...also need different prompt text.

The desired behavior is to show the first prompt when blurred, then the second prompt on focus.

**Comment by agirton** [comment]
Search prompt in the Async component is inside the menu, same as no results if it's not. Since noResultsText and placeholder can be a String or Node you can style to your hearts content there. Does that work for you?

**Comment by Drecula** [comment]
No, they're different strings for each prompt. Ideally, placeholder would also accept a function, which would make any sort of dynamic behavior simple.

**Comment by agirton** [comment]
Since it accepts a React node you can do the dynamic behavior on your end right?

**Comment by Drecula** [comment]
Thanks. Is there an event that's fired when the dropdown is opened?

**Comment by agirton** [comment]
There is an onOpen and onClose event.

**Comment by Drecula** [comment]
Awesome. Thanks again!!!

**Comment by agirton** [comment]
No problem!
