### ISSUE TITLE
Add Flow type definitions

### ISSUE THREAD

**Issue by TomiS** [JedWatson/react-select#1801]
It seems to me this lib doesn't provide Flow type definitions. Are there any plans or decisions made related to this? Would PR be welcome?

**Comment by agirton** [comment]
Hi @TomiS thank you for your interest! Adding flow or typescript definitions is a low priority with the amount of PR's we have open. With that said, you are more than welcome to open a PR to add, just not sure how soon we would add.

**Comment by TomiS** [comment]
@agirton Thanks for your answer. I noticed the list of open tickets and PRs and assumed this might be the case. If you are busy with more urgent things, an alternative would be to commit types into [Flow-typed](https://github.com/flowtype/flow-typed). I assume the release candidate status of this lib means api will not be changing so this might be good time to add type definitions somewhere.

**Comment by TomiS** [comment]
I ended up creating a PR to flow-typed because the workflow there was already available  https://github.com/flowtype/flow-typed/pull/975
