### ISSUE TITLE
read-only semantics

### ISSUE THREAD

**Issue by mlajszczak** [JedWatson/react-select#1802]
Is there any way to simulate read-only semantics using react-select? I want my select to send data via form and at the same time I prevent users from changing selected value.
In my use-case it might be just disabled + data is submitted via form (which is slightly different from read-only semantics in HTML).

If it's not possible currently, are you open to PRs that introduce this feature?

**Comment by agirton** [comment]
Hi @mlajszczak great question! This package is a controlled component so users are responsible for managing their own data. So disabling the input will prevent users from interacting with the input, but they can still see the value. You can see how this works on our demo page: http://jedwatson.github.io/react-select/ does this work for you?

**Comment by mlajszczak** [comment]
Thanks for answering so promptly!

So my question was more about hidden inputs that are generated by react-select component. When I disable it, those hidden inputs are disabled as well. As a consequence, they don't get submitted when I submit the form that contains them.

I'm more interested in such a feature that users can't change selection, but underlying inputs are enabled. Looking at the examples from your link I can't find anything like that.

I mentioned "readonly" per analogy to HTML attribute (see: https://developer.mozilla.org/pl/docs/Web/HTML/Element/Input).

**Comment by mlajszczak** [comment]
Friendly ping?

**Comment by agirton** [comment]
@mlajszczak we can look into a read only mode after 1.0 final. Since you need this, do you manage form state within the form? 

Instead of trying to read the state within the HTML form what if you managed the state either in React or some other state management library?

**Comment by mlajszczak** [comment]
My use case is a bit complicated because I'm rewriting quite large application in React "bottom-up", integrating React with legacy jquery/HTML code. Thus, in this particular case I rely on built-in HTML form functionality as some other part of the form are not rewritten in React yet.

Well, for me lack of readonly mode is not a blocker but it would be convenient to have it (it's basically for update form that doesn't allow to change particular fields, but it would be still convenient to send them with POST).

**Comment by agirton** [comment]
I see. Ok will put this in as something we should consider after 1.0 is final. Thanks for the extra context!

**Comment by Scull007** [comment]
Hello, any answer? Right now i need create one more hidden input with defaultValue when my react-select use props.isDisabled = true.

**Comment by ebonow** [comment]
Greetings,

By a readOnly Select, I am guessing that you want to disable the ability to type in the input and to keep the menuOptions closed.

To create a readOnly Select...

``` JS
const Input = props => <components.Input {...props} readOnly={props.selectProps.isReadOnly} />

const MySelect = ({ isReadOnly, ...props }) => 
  <Select 
    {...props} 
    components={{Input}} 
    menuIsOpen={isReadOnly ? false : props.menuIsOpen}
    isReadOnly={isReadOnly}
  />
```

In an effort to address still relevant issues, I'll be closing this, but can re-open if need be.

**Comment by Reflex-Gravity** [comment]
@ebonow I would like to improve this a bit by disabling `backspaceRemovesValue` too.

```
const Input = props => <components.Input {...props} readOnly={props.selectProps.isReadOnly} />

const MySelect = ({ isReadOnly, ...props }) => 
  <Select 
    {...props} 
    components={{Input}} 
    menuIsOpen={isReadOnly ? false : props.menuIsOpen}
    isReadOnly={isReadOnly}
    backspaceRemovesValue={!isReadOnly}
  />
```
