### ISSUE TITLE
Wrapping of values when used in width constrained parent

### ISSUE THREAD

**Issue by broncha** [JedWatson/react-select#1805]
Hi,

I recently had to use this where the parent had a max-width constraint, and when the labels are long, they are wrapped and interferes with the close icon.

This is how it looks
![screen shot 2017-06-21 at 12 23 49 pm](https://user-images.githubusercontent.com/46905/27370499-8aee3658-567c-11e7-9d3a-36048cc9ff80.png)

This can easily fixed by having `.Select--multi .Select-value` to be `inline-flex`  instead of `inline-block`.

This is the result

![screen shot 2017-06-21 at 12 25 09 pm](https://user-images.githubusercontent.com/46905/27370531-b4abd3ba-567c-11e7-80fd-400aa65c3966.png)

Its a tiny fix. If you want a PR for this I can create one. Thanks for the awesome component! 
Cheers

**Comment by agirton** [comment]
Hi @broncha the only issue I see with using `inline-flex` is some people have to support browsers that don't support this feature. Since this can be handled on your end, I would rather not introduce something new that may break other users.
