### ISSUE TITLE
Question: Refreshing options list and multiple values with line break

### ISSUE THREAD

**Issue by rmwettig** [JedWatson/react-select#1806]
Hi all,
I have two issues using react-select:

1)
When selecting multiple options the whole select box extends its width instead of making a line break and place the selected value on the next line (as demonstrated in the Github Users example).

Is this behaviour just a CSS styling issue?

2)
How can I force an update of the shown options list?

Options are loaded asynchronously into a redux state. These options are then passed down to the react-select component. However, the loaded options are only shown when deselecting the select component and reselecting it.

Browser: Chromium Version 55.0.2883.75 Built on 8.6, running on Debian 8.7 (64-bit)

Let me know if you need more information.

Thank you very much for your answers!

**Comment by agirton** [comment]
Hi @rmwettig 

1. You will need to set a max-width on your select and it will grow in height instead of width.
2. Are you able to provide a demo of what your issue is? The menu should open when the select has focus and then once the values become available should then show inside the menu.

**Comment by rmwettig** [comment]
Hi @agirton 

While working on a minimal example it turned out that react-select works behaves as expected. 
This  issue can be closed.

Thank you for your time :)
