### ISSUE TITLE
Specifying an option object as 'value' and providing an object to the onChange event

### ISSUE THREAD

**Issue by Drecula** [JedWatson/react-select#1808]
Hi,

I have an array of objects, and need to have the whole object provided in handleChange() versus a 'value' prop, which AFAIK won't allow me to define the whole object as a value.

Is there a way to do this with react-select, or do I have to mutate my array to make it an array of k/v with v = the attributes I need.

If this feature doesn't exist, please consider this a feature request.

Thanks!

`const options = [
  {name: 'option1', prop2: 'foo', prop3: 'bar', prop4: 'is a prop'}
]
`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
