### ISSUE TITLE
Select does not reset correctly w/ asyncOptions

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#181]
This bug can be seen on the example page.

When the menu is open, the options don't reset as expected - If you type 'ab', then select 'abc', if you reopen the menu the previous results are still visible (including 'ab').

Then if you clear the select value (click the x) it doesn't reset back to the original "one, two..." options unless you type something and press backspace again.

**Comment by deseman** [comment]
+1

**Comment by gwyneplaine** [comment]
resolved in v2
