### ISSUE TITLE
Creatable doesn't allow commas?

### ISSUE THREAD

**Issue by Farmse** [JedWatson/react-select#1811]
Not sure if this is intended but if you goto your own examples, specifically Github users (Async with fetch.js). If you make it a single value non-creatable you can type "whatever, whatever" but if you make it creatable as soon as you hit the comma it "creates" the value.

**Comment by agirton** [comment]
Hello @Farmse comma is a valid character to create a new option. If you would like to override this behavior you can supply your own `shouldKeyDownEventCreateNewOption` prop.

**Comment by Farmse** [comment]
ah I see; my mistake
