### ISSUE TITLE
Initial options with Async

### ISSUE THREAD

**Issue by pn-y** [JedWatson/react-select#1815]
Hi
Is there any way to set up initial options when using Async?
I have few selects on a page and want to turn autoload off because each select doing a query to the backend, but in this case, a user will have no choices without typing search query.  
So, I want to make one query to the backend to get initial options and pass them to each select.

**Comment by agirton** [comment]
Hi @pn-y if you need to make one request for all I would recommend for you to not use Async and just do the API call in the componentDidMount hook.

**Comment by pn-y** [comment]
I need one request for all to get initial options. Then each of inputs should do their own requests. That's the point.

**Comment by agirton** [comment]
If you need to do one request to get initial options for all of your selects, I would recommend to handle this on your side. 

This could be done in some parent component that manages all of them.

**Comment by pn-y** [comment]
Thanks!
