### ISSUE TITLE
[Question] Triggering a callback when there are no results

### ISSUE THREAD

**Issue by kevinrogerteng** [JedWatson/react-select#1818]
I was wondering if there was work around to triggering a callback where there are no options based on the value? 

```
<Select
            ref="stateSelect"
            name="selected-state"
            placeholder="Select State"
            autofocus
            simpleValue
            clearable
            searchable
            value={this.state.selectedState}
            options={this.state.options}
            onChange={this.onChange}
            onNoResult={this.onNoResults}
/>
```

I was thinking of using `optionRenderer`, but this doesn't trigger when there are no options.

BTW, great work!

**Comment by agirton** [comment]
Hi @kevinrogerteng whats the use case for the no result callback? We do show text but it sounds like you need more than that.

**Comment by kevinrogerteng** [comment]
@agirton Thanks for the reply! The use case is quite similar to `Async Creatable` where rather than having the button/function to create within the `<options />` I would have a button shown externally instead. 

<img width="315" alt="screen shot 2017-06-26 at 9 25 54 am" src="https://user-images.githubusercontent.com/5142306/27549659-8538a9ae-5a51-11e7-8e72-428944632f7b.png">

It's a really tiny use case and personally, just a nice to have.

**Comment by agirton** [comment]
Hi @kevinrogerteng I see. Thank you for the use case! In most cases users can obtain when there are no options available it may be confusing on when to use this callback. 

The `Creatable` just wraps the `Select` component, it seems like this could be built on the user side.

**Comment by kevinrogerteng** [comment]
@agirton Yeah, that makes sense! I'll look into `Creatable` a bit more. It was just an out of the blue question. Thank you though!
