### ISSUE TITLE
i can't reach to the event data (name,value etc..) 

### ISSUE THREAD

**Issue by mikdatdogru** [JedWatson/react-select#1819]
hi;
i can't reach to event.target data because there is only value in callback of onChange, 
I have to write a new function just with property differences for each selectbox, when i use more then one selectbox in the page.

how can i reach to the target datas (name,value etc..) of selecbox in onChange mode ?

![image](https://user-images.githubusercontent.com/10121255/27511875-133420c8-5938-11e7-97f6-4fe5f642eec6.png)

**Comment by agirton** [comment]
Hi @mikdatdogru we don't support this use case, however you can solve this on your end by creating a closure e.g.

```
onChange(name) {
  return value => {
     this.setState(prevState => ({
        data: {
           ...prevState.data,
           [name]: value
        }
     })
  }
}
```

**Comment by mikdatdogru** [comment]
thanks for answer.
I solved this way

```
 <Select 
    value={this.state.make}
    onChange={value => this.onChangeSelect('make', value)}
    options={this.state.make.map(item => ({
       label: item.name,
       value: item.value,
     }))}
              />  
```

```
  onChangeSelect(name, value) {
    this.setState({
      data: {
        ...this.state,
        [name]: value,
      },
    });
  }
```
