### ISSUE TITLE
Keep placeholder present after selecting option in multiselect  ?

### ISSUE THREAD

**Issue by mslav** [JedWatson/react-select#1828]
The placeholder disappears as soon as an option is selected, how can I keep it present until options run out?

**Comment by agirton** [comment]
Closing this as a duplicate of #1566

**Comment by mslav** [comment]
I'm wondering if there was ever a solution found for this?

**Comment by rahuliet** [comment]
you can add a span with "placeholder text" above react-select.However this would not give floating effect of Material UI

**Comment by rakeshpatra** [comment]
You can set prop `controlShouldRenderValue` to `false`,
else if you want to hide the selected option and show the placeholder when the menu is open, you can try as below.
```
controlShouldRenderValue={!this.state.menuIsOpen}
onMenuOpen={() => this.setState({ menuIsOpen: true })}
onMenuClose={() => this.setState({ menuIsOpen: false })}
```
