### ISSUE TITLE
Select component UI does not update when value access this.state.variable.subvariable

### ISSUE THREAD

**Issue by keehun** [JedWatson/react-select#1832]
Here is the simplified setup that **works**:

```
constructor(props) {
	super(props);
	this.state = {
		selectedName: "",
	};
}

render() {
	return (
		<Select.Async
			value={this.state.selectedName}
			placeholder="Type Something"
			loadOptions = {(input, callback) => {
				var returnedNames = this.props.data.allNames.edges.map(function(edges) {
					return {value: edges.node.theName, label: edges.node.theName};
				});
				callback(null, {
					options: returnedNames,
					complete: true
				});
			}}
			onChange = {(newValue) => {
				if(newValue) {
					this.setState({selectedName: newValue.value}, function () {
					});
				} 
			}}
		/>
	)
}
```

However, as soon as I change the code to the following:
```
constructor(props) {
	super(props);
	this.state = {
>>>		selectedName: {"theName":""},
	};
}

render() {
	return (
		<Select.Async
			value={this.state.selectedName}
			placeholder="Type Something"
			loadOptions = {(input, callback) => {
				var returnedNames = this.props.data.allNames.edges.map(function(edges) {
>>>					return {value: edges.node, label: edges.node.theName};
				});
				callback(null, {
					options: returnedNames,
					complete: true
				});
			}}
			onChange = {(newValue) => {
				if(newValue) {
>>>					this.setState({selectedName: newValue.value.theName}, function () {
					});
				} 
			}}
		/>
	)
}
```
It does not work. I've highlighted the differences with `>>>`.

Basically, what I want to do is to hold the entire JSON object in `loadOption`'s value field and just pull out a field to display when a user selects something. Is this not possible? Does `loadOption`'s `value` and `<Select/>`'s `value` have to always match? For some reason, I imagined that they're separate.

When I set a string as `value` in `loadOptions` it works, _**but not**_ when I set it as a JSON object and then `setState` a property in the JSON object in `onChange()` ... Is there a way around this? Am I doing something wrong?

Thank you

**Comment by ryantan** [comment]
If values as not simple strings it'll be hard for the component to check equality. To get other properties via the string value why not look it up in the options array? e.g.

`let yourObject = yourOptionsArray.find((item) => item.value === selectedValue);`

**Comment by ryantan** [comment]
And small technicality: A "JSON of an object" is a string. What you are referring to as a "JSON object" is just a plain old javascript object a.k.a. POJO.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
