### ISSUE TITLE
Select horizontal alignment issue...

### ISSUE THREAD

**Issue by steviesama** [JedWatson/react-select#1834]
I'm using react-select in tandem with react-bootstrap, though I'm not sure if it's really at odds with bootstrap. I have the following problem:

![problem](https://i.imgur.com/QMNELNn.png)

Type is an instance of select, and if I set both the react-bootstrap form-control and the react-select to overflow: hidden...no problems, alignment wise, except obviously you can't see the select dropdown, but if I leave it be I get this. I had it lining up with input groups with dropdowns and inputs just fine, but this just doesn't seem to want to work.

Below is the relevant JSX for the 2 components. All that is in ```inlineBlock``` is a ```display: inline-block``` equivalent.

```
<FormGroup validationState={this.validate('company_name', 'string')}
   style={inlineBlock} className='col-60'>
  <ControlLabel>Name</ControlLabel>
  <FormControl inputRef={((input) => this.firstInput = input).bind(this)}
    type='text' className='btn-block'
    value={this.state.company_name}
    placeholder='Unique string that identifies this app instance; will display as *Base App Name (App Instance Label)*'
    onChange={(e) => this.onTextChange('company_name', e)}/>
  <FormControl.Feedback/>
</FormGroup>
<span className='col-1'></span>
<FormGroup validationState={this.validate('state_name', 'string')}
  style={inlineBlock} className='col-39'>
  <ControlLabel>Type</ControlLabel>
  <Select Multi
    value={this.state.state_id}
    options={this.state.states}
    onChange={value => {
      this.setState({state_id: value});
  }}/>
</FormGroup>
```
Any help would be appreciated.

### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by steviesama** [comment]
I found a workaround. Overriding the following from ```table``` to:
```
.Select-control {
	display: inline-table;
}
```
Which leaves it hanging 2px too low so applying:
```
var selectFix = {
  'position': 'relative',
  'top': '-2px'
};
```
Puts it back in alignment.

![problem](http://i.imgur.com/5eNamcD.png)

**Comment by josephrussell** [comment]
Thanks @steviesama, this is helpful. I was using bootstrap then switched to Bulma had saw the same issue and you encountered in both frameworks. This lines it up with the rest of the horizontally aligned controls, top: -1px looked closer in my case.

**Comment by agirton** [comment]
HI @steviesama I'm not sure this is a react-select bug. Based on your image it looks like due to the sizing of the two FormGroup.

**Comment by steviesama** [comment]
@agirton Ah, sorry I didn't see this when it was posted. I don't know. I've just dealt with it. I'm not sure what to do to fix the problem.

**Comment by dmk23** [comment]
I got to this issue by search for `validationState`

There is another problem in this example, take a look at the formatting of the first vs. second `FormGroup`

The first `FormGroup` (for "Name") shows the error red color around the label, the help text and the element. However for the Select component (for "Type) the element itself is NOT highlighted in red

Anyone has any suggestions for fixing this? This could be releated issue to `react-bootstrap` integration

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
