### ISSUE TITLE
Focus changes on Tab press when selecting option (bug)

### ISSUE THREAD

**Issue by karaggeorge** [JedWatson/react-select#1838]
Currently open PR that fixes this: https://github.com/JedWatson/react-select/pull/1837

When **Tab** is enabled as a select key, an option is highlighted and **Tab** is pressed, the option should be selected but the focus should remain on the select component. A new **Tab** press after that would focus the next element. 

This only works on a Creatable Select, and only when the highlighted option is the "Create new ..." one.

### Actual:
- Pressing **Tab** in one of the existing options:
![gifs1](https://user-images.githubusercontent.com/8822835/27650067-c9982ae6-5c01-11e7-963d-7483699d864f.gif)
You can see that after pressing **Tab**, the checkbox is focused (not desired)

- Pressing **Tab** in the "Create new ..." option:
![gifs2](https://user-images.githubusercontent.com/8822835/27650102-e2f7c7d0-5c01-11e7-9fe4-ff7b7df6acc9.gif)
This works properly

### Expected:
- This is what should happen when pressing **Tab** in one of the existing options:
![gifs3](https://user-images.githubusercontent.com/8822835/27650136-f6b6246a-5c01-11e7-92d3-0a24a6fb3cea.gif)
The item is selected and the focus remains on the select component

## Fix
It seems like the Tab press event is prevented with `event.preventDefault()` only in the Creatable.js and only if the selected option is the "Create new...". In any other case it defaults to Select.js 's `handleKeyDown()` which does not actually call `event.preventDefault()`

Went ahead and fixed it and created a PR: https://github.com/JedWatson/react-select/pull/1837

Also added same effect for **Enter** key press, where the first enter press should select the option without firing a enter key event

**Comment by lamoglia** [comment]
Small PR... I would like to see it merged soon....

**Comment by JedWatson** [comment]
Closed by #1837
