### ISSUE TITLE
Default selection

### ISSUE THREAD

**Issue by frazboyz** [JedWatson/react-select#1840]
It would be nice to have a default value attribute on React Select that you set to true for example and React Select by default selects the first option in the options array.

**Comment by agirton** [comment]
Hi @frazboyz,

What if someone doesn't want the first option to be selected? I think adding an extra prop increases our API surface area and it can be easily solved in user land. Thoughts?

**Comment by danzawadzki** [comment]
@frazboyz but is there any option to set default value? I need to somehow be able to set for example <option value="home">Home</option> as selected in default.

**Comment by agirton** [comment]
@danzawadzki this package is a controlled component so you would select the value in your code.
