### ISSUE TITLE
Encoding issues with Select.async

### ISSUE THREAD

**Issue by sabarasaba** [JedWatson/react-select#1841]
When entering a string such as 'ä á à' in the input box and pressing space react-select will end up removing them and replacing the input values with 'a a a'. Same happens when you just enter one of them and then press space. It doesnt seem to be happening in non-async components.

You can reproduce this error using the 'Github users (Async with fetch.js)' demo at http://jedwatson.github.io/react-select/.

**Comment by johann-sonntagbauer** [comment]
@sabarasaba have you checked the ignoreAccents prop. Please turn it off.

**Comment by sabarasaba** [comment]
@johann-sonntagbauer Ah super, i was only searching for "encoding" "utf8", didnt thought about "accents". That fixes the issue, thank you very much!
