### ISSUE TITLE
Separator different from comma in case multi=true 

### ISSUE THREAD

**Issue by adinu** [JedWatson/react-select#1842]
currently i am experiencing a problem that if i have a value in my multiSelect box that includes ',' comma it split it to two lines (because we split it by ',' which is the seperator) 

i have tried to use multiSelect=false/true (so in the onChange i will get an object and not a string seperated with commas) but nothing is working properly 

this is currently how my select looks like:
<Select simpleValue ={false} ref={this.selectRef} clearableValue={true} className="select_box" value={this.allFilters.industry} placeholder={Translation.t('SearchByCriteria.Industry')}
                        name="Industry" options={this.getFilters(this.props.filtersOptions[1].industry)}
                        multi={true} onChange={this.onChangeIndustry} noResultsText={false}/>

we are currently using "0.9.1" version of the plugin.

**Comment by agirton** [comment]
Hi @adinu are you able to upgrade to one of the RC's?
