### ISSUE TITLE
Append Options to body and calculate position

### ISSUE THREAD

**Issue by dahliacreative** [JedWatson/react-select#1845]
So I'm using react-select and it's awesome, but I am using it inside modal windows which have overflow: auto on them, as most modals do. 

Because the options are appended to the select element, they get cut off when at the bottom of the modal, if you appended them to the body and positioned them then they could sit outside the modal and always be visible.

Thanks

**Comment by agirton** [comment]
Hi @dahliacreative we currently don't support rendering things in a portal. It seems like there is quite the discussion in #810 and you can see if that solves the issue: https://github.com/JedWatson/react-select/issues/810#issuecomment-284573308
