### ISSUE TITLE
Should add option when delimiter is input

### ISSUE THREAD

**Issue by anthonator** [JedWatson/react-select#185]
If my delimiter is a comma this shouldn't be possible.

![screen shot 2015-05-12 at 3 37 36 pm](https://cloud.githubusercontent.com/assets/420061/7596600/d6eb9890-f8bc-11e4-91bf-e0961e08a876.png)

**Comment by dcousens** [comment]
If you're delimiter is a comma,  then don't provide `"asdf,asdf"` as a label?  How would you expect a user to do that anyway?

**Comment by anthonator** [comment]
I didn't provide `asdf,asdf` as an option. A user did.

Given [this use case](https://github.com/JedWatson/react-select/issues/179) a user can create new labels. If a user were to enter the delimiter it should start a new label rather than allow a user to create a label containing the delimiter

**Comment by dcousens** [comment]
@anthonator willing to make a PR for this in light of #151?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
