### ISSUE TITLE
props value is not show

### ISSUE THREAD

**Issue by alexaung** [JedWatson/react-select#1852]
Hi,
state vale is not selected if assign the value as follow
`<Select
                            name="departmentId"
                            placeholder="Click to select a department" 
                            value={this.state.employee.departmentId}
                            options={this.props.departments}
                            onChange={this.onChangeDepartmentSelect}
                            />  `

if I hard code the value, it is show 
`<Select
                            name="departmentId"
                            placeholder="Click to select a department" 
                            value="1"
                            options={this.props.departments}
                            onChange={this.onChangeDepartmentSelect}
                            />  `

**Comment by agirton** [comment]
Hi @alexaung,

This sounds like it's something in your project. But what version are you running?

**Comment by alexaung** [comment]
I am using 
react-select 1.0.0-rc.5 and reactjs 15.6.1. 
 By the way, I found the issue. If value is integer (1,2,3,4), it does not selected. If value is string (E1, E2, E3, E4), it is working.

Sorry for late reply.

**Comment by agirton** [comment]
Hi @alexaung can you please provide a test case showing this is true?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
