### ISSUE TITLE
If we can have a configuration that the default focusedOption is the 1st one or just null, meaning that that the focusedIndex is  -1 at first?

### ISSUE THREAD

**Issue by sw-frontend** [JedWatson/react-select#1863]
My case is that when the options list opens. no option is focused by default.

**Comment by sw-frontend** [comment]
If the config is set as true, from UI aspect, when the option list opens, no option is focused by default.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
