### ISSUE TITLE
The selected item does not show in the box or input

### ISSUE THREAD

**Issue by moh3n65** [JedWatson/react-select#1867]
After tried everything such as different versions of graphql and react-select I realised the below Plunker has the same issue.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/dHygFMWWqVwaRAfpEmbn?p=preview

**Comment by agirton** [comment]
Hi @moh3n65 this plunker is not updating the value so this is not a bug with the component. See our examples of how to update the value with setState.
