### ISSUE TITLE
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

### ISSUE THREAD

**Issue by DeividasK** [JedWatson/react-select#1869]
Hi,

`Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.` is an annoying React  warning, which seems to disappear once I rebuild the project by running `npm run build` or `gulp clean && NODE_ENV=production gulp build` (as in package.json file).

Since [contributing guidelines](https://github.com/JedWatson/react-select/blob/master/CONTRIBUTING.md) specifically prohibit making a PR with build files, I did not open one. However, it would be really nice to get rid of those warnings, especially given that it's just a single `build` away.

**Comment by gusdaud** [comment]
This is happening for me too. It's really annoying.

**Comment by agirton** [comment]
Hi @DeividasK, @gusdaud this will be fixed when we make a release. Until then you should be able to use a previous version where createClass is used.

**Comment by gusdaud** [comment]
@agirton you mean a major release or a patch ? Do you know for when is it expected ?

**Comment by lord-xeon** [comment]
@agirton, is there any word on when a release will be made that will fix this?

**Comment by natnmt** [comment]
@agirton The warning is also being displayed in here. Any ETA for the fix?

**Comment by terry90** [comment]
Waiting for it too

**Comment by stevenmusumeche** [comment]
@agirton any idea on a release date?

**Comment by martinbliss** [comment]
Has this been fixed? I'm getting this warning while using `react-data-grid` and I'd like to be able to tell the author to upgrade to get rid of this super annoying warning.

**Comment by agirton** [comment]
@martinbliss this was released with https://github.com/JedWatson/react-select/blob/master/HISTORY.md#v100-rc6--2017-09-10. So it has long been fixed.
