### ISSUE TITLE
Add `has-options` in the class once options are available in context menu

### ISSUE THREAD

**Issue by carlosmmelo** [JedWatson/react-select#187]
When a react-select component depends on an API call to be done in order to store the available options in the class of `Select-menu`, When you try to click it it will display the `Select-menu` context empty then this context menu will be closed once the DOM gets updated with the available options.

For automated tests using Selenium Webdriver, this is a big headache, there is no way for me to wait for this to happen.

Unless we have add an attribute in the .Select css class of `has-options` once the options are available.

Like we already have a `is-focused` and/or `is-searchable` in the `Select` class of this component.

This way we would be able to tell the  Webdriver to wait for that element to have the `has-options` attribute so that we could know when the options are available for a dropdown.

![image](https://cloud.githubusercontent.com/assets/5649650/10615445/df80d89a-772d-11e5-9390-606a3f1d3e3c.png)

**Comment by dcousens** [comment]
@jossmac is this suitable/standard?

**Comment by carlosmmelo** [comment]
hey guys, any updates on this?

**Comment by jossmac** [comment]
I think this is suitable, can we get a PR @carlosmmelo?

**Comment by jossmac** [comment]
Ping @JedWatson any objections?

**Comment by JedWatson** [comment]
I'm OK with this

**Comment by carlosmmelo** [comment]
@jossmac I wish I could, but I dont really know how to add this.

Is it just by adding a bool proptype [here](https://github.com/JedWatson/react-select/blob/979fb0754b93fef88ca5f2642e2dc8a4508099b0/dist/react-select.js#L339)
And then add it as a key:value pair in the [rendering function](https://github.com/JedWatson/react-select/blob/979fb0754b93fef88ca5f2642e2dc8a4508099b0/dist/react-select.js#L1083)? 

Also where are the props gets defined? as in the logic of setting the property of an object (to define if the `select-menu` has at least 1 option, then set this `has-options` to `True`)

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
