### ISSUE TITLE
Generic type 'Component<P, S>' requires 2 type argument

### ISSUE THREAD

**Issue by junibrosas** [JedWatson/react-select#1873]
The new update on typescript (2.4.1) has some compatibility issue with the react-select types.

"node_modules/@types/react-select/index.d.ts(472,40): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s)."

**Comment by agirton** [comment]
Hi @junibrosas we don't use Typescript anywhere in the codebase, so not sure where it gets these types from. Maybe from some other repo?

**Comment by jrehwaldt** [comment]
Potentially: https://www.npmjs.com/package/@types/react-select

**Comment by JoeRall** [comment]
@junibrosas  You should try updating your version of @types/react to latest. It should resolve that issue. I just installed @types/react version 16.0.2 and I'm all set. I'm also using Typescript version 2.4.2. In version 2.3 [Generic parameter defaults](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html) were released which is related to this typings change. It's a nice feature if you're doing a lot with generics.

I hope this info helped.

**Comment by junibrosas** [comment]
@JoeRall You are correct. I installed the latest `@types/react`, `@types/react-select`, and `typescript`, and now package error ts errors are gone. Now i have like 263 ts errors in my source code but this is better than library ts errors.

`npm install @types/react@16.0.2 @types/react-select typescript@2.4.2 --save-dev`

**Comment by JoeRall** [comment]
@junibrosas Glad to hear!

@agirton I guess this issue is safe to close.

**Comment by agirton** [comment]
Thanks!
