### ISSUE TITLE
Double click support?

### ISSUE THREAD

**Issue by Drecula** [JedWatson/react-select#1878]
I need to perform an action if the user single clicks an option from the list, and select the option on double click.

Is there some way to accomplish this with the existing API, or am I indeed making a feature request?

Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
