### ISSUE TITLE
[Internet Explorer 11] autoBlur={ true } lose tabIndex context

### ISSUE THREAD

**Issue by enheit** [JedWatson/react-select#1885]
If to add `autoBlur` property to `Select` component and press `Tab` button, focus will be set to the first focusable element of the page instead of next one.

P.S. If `autoBlur` is `false` - everything work fine.

**Comment by adailey14** [comment]
+1 Just discovered this same issue.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
