### ISSUE TITLE
Creatable in 1.0.0 Uncaught TypeError: Can't add property 2, object is not extensible

### ISSUE THREAD

**Issue by typeofgraphic** [JedWatson/react-select#1888]
I am trying to work with the Creatable component, but get the following error:

`Creatable.js:120 Uncaught TypeError: Can't add property 2, object is not extensible`

I suspect I am not actually using it correctly, but the explanation in the docs is decidedly unhelpful... 

> The Creatable component enables users to create new tags within react-select. It decorates a Select and so it supports all of the default properties (eg single/multi mode, filtering, etc) in addition to a couple of custom ones (shown below). The easiest way to use it is like so:

```
import { Creatable } from 'react-select';

function render (selectProps) {
  return <Creatable {...selectProps} />;
};
```
I am currently using Creatable in place of Select, I'm sure I am missing something but not quite sure what. Thanks in advance

**Comment by typeofgraphic** [comment]
Added the `onNewOptionClick` property, this removes the error and passes out an object with a label and value. 

Would be great to see the docs updated to make it easier to get this running.

**Comment by nsarafa** [comment]
@typeofgraphic ran into the same issue. we should open a pull to make this more clear inside the documentation. perhaps provide the default use example with the `onNewOptionClick` rather than the `onChange`, or `onClick` event

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
