### ISSUE TITLE
Ability to close dropdown list

### ISSUE THREAD

**Issue by jtadmor** [JedWatson/react-select#189]
Hi,

Thanks for all the hard work putting this together. One issue that I have is that I would like to be able to close the dropdown list when it is open, either at will or through a parameter that would close it when a selection is made.

Currently, if @props.mutli is true, the list stays open, requiring the user to click elsewhere in the UI in order to move on. While I understand the logic behind this, this behavior is not always desirable and it would be nice to have some control over it.

**Comment by bdefore** [comment]
+1

**Comment by dcousens** [comment]
Related to https://github.com/JedWatson/react-select/issues/190,  either submit a PR or help @otake with his work :)

**Comment by DERIIIFranz** [comment]
+1
