### ISSUE TITLE
A onKeyDown prop can be added?

### ISSUE THREAD

**Issue by prashantkhode** [JedWatson/react-select#1892]
Hello,
thanks for react-select,

1) I was wondering, if we can add a prop called onKeyDown.
which will be like onKeyDown event of <input> (DOM),

2) the normalize prop, which is a callback function
is called after change which is ok for select(it is called after selecting a value), but for Select.AsyncCreatable
when we start to type the text then it doesn't get called, and when finished typing text and we focus out from it.
then the normalize gets called and formats the input text.
could it be called on
       * onKeyDown for Select.AsyncCreatable and  onBlur for Select 
            or 
       * adding a new prop to Select.AsyncCreatable telling that call the normalize when a key is pressed ?.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
