### ISSUE TITLE
&times; in Value.js turns into ? upon build

### ISSUE THREAD

**Issue by Tatzel-wurm** [JedWatson/react-select#1893]
```&times;``` entity in method renderRemoveIcon of file Value.js should be inserted as ```dangerouslySetInnerHTML={{ __html: '&times;' }}```, like in defaultClearRenderer.js

**Comment by diegoarcega** [comment]
for me it is turning into a bloody ` "__html": "input#undefined::-ms-clear {display: none;}",` or  "__html": "input#da3sdda5s123::-ms-clear {display: none;}",

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
