### ISSUE TITLE
compatibility with React version 16 (fiber)

### ISSUE THREAD

**Issue by crobinson42** [JedWatson/react-select#1899]
This issue tracks `react-select`'s compat w/ the impending React version 16

[https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html](https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html)

**Comment by mikecousins** [comment]
I added PR #1897 which should resolve this.

**Comment by gwyneplaine** [comment]
@crobinson42 thanks for lodging this, compatibility with react 16 has been incorporated into the latest release. closing this issue
