### ISSUE TITLE
Match the right option when hit 'Enter'?

### ISSUE THREAD

**Issue by fraserxu** [JedWatson/react-select#19]
When user type in the input, if he knows what to type, he may expect to select the right option when type in the value and  hit `Enter`.

For example, If there's a list of countries I need to select ['China', 'Japan', 'USA'], when I finish typing `China` and I expect to select `China` when I hit Enter. Currently I need to arrow key down and select it or by mouse click.

**Comment by jpsfs** [comment]
Hi!

Sorry for digging-up this topic but although I understand the feature, I have a situation where this doesn't apply well.

I have a situation where I need something like the google autocomplete feature, where the user will type something but I don't want to pre-select anything. Do you think it's possible to provide a flag to enable/disable this behavior?

Cheers!
