### ISSUE TITLE
Can't trigger open state without a click

### ISSUE THREAD

**Issue by otake** [JedWatson/react-select#190]
I don't see a way to trigger open the menu from anything else besides a mouse click. Am I missing something?

I tweaked it so I can pass in a prop to trigger the menu open. Is that something you would like to  see in a PR?

**Comment by dcousens** [comment]
@otake I imagine so,  yes.  That PR would be welcome.

**Comment by nickbouton** [comment]
+1 via #189

**Comment by DERIIIFranz** [comment]
+1

**Comment by Paveltarno** [comment]
Looks like #817 can help with this

**Comment by JedWatson** [comment]
Being discussed elsewhere: #817 #962 #1015 #1950
