### ISSUE TITLE
As a developer i see double checkbox for each item.

### ISSUE THREAD

**Issue by cllyldrm** [JedWatson/react-select#1900]
![capture](https://user-images.githubusercontent.com/5938044/28746405-594c4398-7494-11e7-8a1d-901a7d12559b.PNG)

I see double checkbox for each item, how do i fix it ?
You can see from picture.

**Comment by agirton** [comment]
Hi @cllyldrm it seems you have submitted an issue on the wrong repo. This UI is not part `react-select` at all.
