### ISSUE TITLE
Custom menuRender bug causes dropdown menu to render on unfocused clear

### ISSUE THREAD

**Issue by turnerniles** [JedWatson/react-select#1901]
Continuing this react-virtualized-select [issue ](https://github.com/bvaughn/react-virtualized-select/issues/71) which actually is a react-select issue. react-select issue [#1348](https://github.com/JedWatson/react-select/issues/1348) is a related issue.

this._openAfterFocus gets set to true when using the react-select custom menuRenderer and you click clear when the dropdown is not focused. This causes the dropdown menu which is not the desired behavior. You can see this bug in the react-select [demo](http://jedwatson.github.io/react-select/) in the **Cities (Large Dataset)** example.

If we delete the line: [291](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L291), it fixes the issue but I'm not sure if it breaks anything else. All react-select tests pass and all examples seem the same to me with the line deleted.

**custom menuRender (react-virtualized-select) unfocused clear bug:**
![react-virtualized-select-unfocused-clear](https://user-images.githubusercontent.com/8146241/28739906-fcbe6880-73cc-11e7-9307-01e415b80414.gif)

**default menuRender (react-select) desired behavior:**
![react-select-unfocused-clear](https://user-images.githubusercontent.com/8146241/28739925-1f734440-73cd-11e7-87c7-99c7cb46eb21.gif)

**Comment by turnerniles** [comment]
It seems @agirton's new PR https://github.com/JedWatson/react-select/pull/1902 fixes this issue.

**Comment by turnerniles** [comment]
@agirton when will 1.0.0-rc.6 be published with the #1902 change?

**Comment by gwyneplaine** [comment]
Thanks for logging this issue @turnerniles, the fix for this is now in the latest release candidate.

**Comment by turnerniles** [comment]
Thank you @gwyneplaine!
