### ISSUE TITLE
How to view applied styles of React-select inner elements on DevTools

### ISSUE THREAD

**Issue by isaacalves** [JedWatson/react-select#1906]
If I have a react-select open (in a searchable state) and I click on anywhere on DevTools (in an inner element, for instance) the select will close and the elements will disappear.

How can I inspect styles on DevTools of React-select element?

And why does that happen? That doesn't happen, for instance, with bootstrap-select, which is also a non-native select component that populates a hidden select input.

I've actually taken so far more than an hour to style this simple select component (and I haven't finished yet) while I took less than 20 minutes to apply the same styling to a bootstrap-select a couple days ago. I know this is only a matter of a paradigm-shift, but please, someone point me out in the right direction.

***SOLUTION***

https://github.com/facebook/react-devtools

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
