### ISSUE TITLE
Change value text when dropdown is open

### ISSUE THREAD

**Issue by ariannedee** [JedWatson/react-select#1907]
### Description
I would like to change the value text to something like "Type to search" when the dropdown is open. Currently, the `renderValue` function only passes `option` but not the `isOpen` state.

The use case for this is that users have not noticed that you are able to search and only think that you can choose a value from the dropdown.

![context-chooser](https://user-images.githubusercontent.com/2425730/28889802-104c7238-777a-11e7-895f-5387ddbad528.gif)

**Comment by ariannedee** [comment]
#1908 fixes this.

**Comment by kolyabres** [comment]
There is an option `searchPromptText`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
