### ISSUE TITLE
Allow nested options

### ISSUE THREAD

**Issue by milosdakic** [JedWatson/react-select#191]
Would be awesome to have nested `options` within `options`.

```
var options = [
  {
    value: 'one',
    label: 'One',
    options: [
      value: 'n-one',
      label: 'Nested One'
    ]
  }
];
```

When an option has more possible options, there would be a `more` property which indicates to the user that they need to perform a action to return more results or something similar. Render if `options` available otherwise if `more` is set, retrieve more options.

**Comment by dcousens** [comment]
Could you give a real world example of this? I'm struggling to understand where it might be useful.

**Comment by milosdakic** [comment]
Nested options would allow you to do something like this:
![image](https://cloud.githubusercontent.com/assets/95560/7693042/c00ff4b6-fe0e-11e4-95b3-73fb34f594c4.png)

**Comment by brianreavis** [comment]
Optgroup implementations get really hard to maintain. Isn't this solvable by just representing the hierarchy in the label? With custom rendering (https://github.com/JedWatson/react-select/pull/216) rendering out a good breadcrumb wouldn't be hard at all.

**Comment by iddan** [comment]
But still, you can't get a title for optgroup with custom render
