### ISSUE TITLE
Weird behaviour with Select.Async and loadOptions

### ISSUE THREAD

**Issue by milushov** [JedWatson/react-select#1910]
Sorry, that's a question actually

I have following code and very weird behavior (on the gif below). The question is -- what I'm doing wrong? Why options not shown immediately after the `getOptions` func done? Why they shown only after the click outside? That's super confusing.. I need your help guys!

![react-select-weird](https://user-images.githubusercontent.com/424326/28966636-fd97ab74-791f-11e7-9c78-48f4579b679f.gif)

```coffeescript
getOptions = (value) =>
  return Promise.resolve({options: []}) unless value
  api.geocoder(value).then (data) =>
    countries = [
      {value: 'A', label: 'A'}
      {value: 'B', label: 'B'}
    ]
    console.info(countries)
    {options: countries}

<Select.Async
  className="ads-filter__select"
  value={@props.country_code}
  onChange={(option) => @props.onChange('country_code', option)}
  clearable={false}
  placeholder={I18n.t('ads.country')}
  loadOptions={getOptions}
/>
```

**Comment by adrianojdesouza** [comment]
I think component will research in client side, look your list of countries it does not have the term "nyc"
try this
`react
filterOptionAsync(option) {
  // Make a logic here, just return true for test
  return true
}

<Select.Async
  className="ads-filter__select"
  value={@props.country_code}
  onChange={(option) => @props.onChange('country_code', option)}
  clearable={false}
  placeholder={I18n.t('ads.country')}
  loadOptions={getOptions}
  // Add props filterOption
  filterOption={this.filterOptionAsync}
/>`
[Read more about filterOption](https://github.com/JedWatson/react-select#filtering-options)

**Comment by adrianojdesouza** [comment]
```javascript
filterOptionAsync(option) {
  // Make logic here, just return true for test
  return true
}

<Select.Async
  className="ads-filter__select"
  value={@props.country_code}
  onChange={(option) => @props.onChange('country_code', option)}
  clearable={false}
  placeholder={I18n.t('ads.country')}
  loadOptions={getOptions}
  // Add props filterOption
  filterOption={this.filterOptionAsync}
/>
```
[Read about this option](https://github.com/JedWatson/react-select#filtering-options)
