### ISSUE TITLE
onMouseDown does not trigger on mouse click

### ISSUE THREAD

**Issue by elghali** [JedWatson/react-select#1914]
`  <Select.Creatable
                options={this.state.options}
                onChange={this.saveOption}
                placeholder="Option"
                onMouseDown={this.mouseDownHandler}
              />`

on left mouse click the `mouseDownHandler` is not being called, i want to prevent opening the dropdown menu on left mouse click

**Comment by optyler** [comment]
Hi, did you found something new about this? I have an issue similar, but with a regular click...

check this out : https://stackoverflow.com/questions/47393999/react-select-cant-stoppropagation-on-valuerenderer-component

**Comment by elghali** [comment]
thank you, but I need this for the `onFocus` or `onMouseDown` event, anyway, I tried to use `e.stopPropagation` on `onFocus`, but it doesn't seem to work also

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
