### ISSUE TITLE
add option to display values on top instead of inside of select

### ISSUE THREAD

**Issue by zangrafx** [JedWatson/react-select#1915]
Hi

I'd like to have an option to display values above  select instead of inside. In my case I have multiselect dropdown where users are supposed to check as many options as they want so the layout was designed to display them above select component.

I have forked this repo and already created what suits my needs by adding new prop "valueOnTop".

This is how it looks like with minimum additional css:

![screen shot 2017-08-08 at 20 35 35](https://user-images.githubusercontent.com/4070130/29089070-66f6a31e-7c7b-11e7-8eea-b68f7207e6d0.png)

I can make PR.

Thanks

**Comment by agirton** [comment]
Hi @zangrafx thank you for the suggestion, however this style is not a direction that we would like to take.
