### ISSUE TITLE
Placeholder value overlapped by clear/select icons

### ISSUE THREAD

**Issue by kevinhos** [JedWatson/react-select#1916]
It looks like very long select values will be overlapped by the clear and select icons when selected.

![screen shot 2017-08-08 at 4 48 43 pm](https://user-images.githubusercontent.com/18267875/29096307-f0dc330e-7c59-11e7-9395-1d19fbaee334.png)

**Comment by jochenberger** [comment]
dupe of #1554

**Comment by JedWatson** [comment]
Fixed by #1866
