### ISSUE TITLE
Autosize property does not seem to work (when 'false')

### ISSUE THREAD

**Issue by snarlynarwhal** [JedWatson/react-select#1918]
Autosize property does not seem to work. I just added the prop `autosize={false}` to my `Select` element. Did I miss a step?

**Comment by rcgillet** [comment]
Just wondering, did you by chance have a `<label>` surrounding your `<Select>`? I noticed that in my project at work and once I got rid of that, it worked just fine. Could be a completely different thing, but just figured I'd ask just in case because no one seems to be responding.

**Comment by snarlynarwhal** [comment]
I don't remember and ended up just using a different solution - don't remember what though haha.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
