### ISSUE TITLE
z index in table header

### ISSUE THREAD

**Issue by foodaka** [JedWatson/react-select#1919]
Hi there, cant seem to find this anywhere. I have my react select in a table header. and the content does not flow above the table row when select is open.

<img width="297" alt="screenshot 2017-08-10 16 13 37" src="https://user-images.githubusercontent.com/8342048/29162816-1a0123c2-7ded-11e7-9526-5db8dd284f78.png">

ive tried many variations of still cant get it. any suggestions?

`
.select-hack {
   position: relative;
   width: 100%;
    margin-bottom: 20px;
    border-collapse: separate;
    :global .Select {
        position: absolute !important;
        width: 100%;
        z-index: 999 !important;
    }
}
`

**Comment by futbolistua** [comment]
I have the same issue. It happens when container has `overflow hidden`. So will this behavior be fixed?

**Comment by agirton** [comment]
Hi @foodaka and @futbolistua we don't have plans to fix this for 1.0 as it would require a bigger change to the project. As @futbolistua pointed out this issue happens if the container has overflow hidden. In order to fix this the dropdown would have to be a fixed element and be programmatically positioned based on the input area.

**Comment by foodaka** [comment]
ok thanks for the reply

**Comment by bruno-sartori** [comment]
This is not a feature, is a major bug.

**Comment by Chikel** [comment]
I have the same issue with `overflow: auto`.

**Comment by ex3ndr** [comment]
Any ETA on this? This is very important for many apps.

**Comment by simonpinn** [comment]
👍

**Comment by sabbiu** [comment]
What is the progress in this? I am also looking for this use case.

**Comment by takion** [comment]
me too with react-table

**Comment by sabbiu** [comment]
@takion I was also looking for it to work with react-table. This helped me, https://github.com/JedWatson/react-select/issues/810#issuecomment-284573308

**Comment by takion** [comment]
@sabbiu thank you for the info

**Comment by takion** [comment]
@DonkovtsevArthur great, thanks for the info

**Comment by wrichman** [comment]
Would someone be able to post a working example of the two together?

**Comment by meldaban** [comment]
Yo tenia este problema, estoy usando material table, y lo solucione configurando el estilo del header del zIndex porque estaba en 10 y lo puse en cero.

<MaterialTable
options={{
headerStyle:{backgroundColor: '#767E9F',color: 'white', fontWeight:'bold' , **zIndex:0**}
}}
></MaterialTable>


![image](https://user-images.githubusercontent.com/33173218/147535560-a26a5607-8791-4be7-981b-15388738eb3f.png)
