### ISSUE TITLE
Ability to set input value on multi

### ISSUE THREAD

**Issue by anthonator** [JedWatson/react-select#192]
It would be nice to have the ability to set the input value and not just the display value. In the event that a rerender is executed within `asyncOptions` it will reset in the input value. This is common within Flux.

Here's an example:

``` js
  let options = [];

    if (!_.isEmpty(input)) {
      this.setState({ data: this.state.data.set('value', input) });

      options.push({ value: input, label: input });

      TagQueries.autocomplete(this.state.data.get('id'), input)
        .then(() => {
          this.props.tags.forEach((tag) => {
            options.push({ value: tag.get('id'), label: tag.get('name') });
          });

          callback(null, { options: options });
        });
    } else {
      callback(null, { options: options });
    }
  }
```

Whenever `TagQueries.autocomplete` is called it dispatches an event which causes a rerender of the component. Once the rendering occurs the input box gets wiped out. I'm saving the input value in state but I don't have anywhere to put it. If I use `value` it creates a new "tag" when all I really want is a value in the input box.

**Comment by dcousens** [comment]
So,  the issue is that if a re-render occurs where some of the previous labels have new `value`s,  new "tag"s are created, instead of the `value` replaced?

**Comment by anthonator** [comment]
All I really want to do is set the value in the input box. Not create new labels.

**Comment by jarsbe** [comment]
Any update here, is it possible pass the input value (just the query text) down as props?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
