### ISSUE TITLE
Styling, 1px width difference between components

### ISSUE THREAD

**Issue by isaacalves** [JedWatson/react-select#1920]
In certain screen widths, there's a 1px difference in width between `Select-control` and `Select-menu-outer`, respectively the select button container and the select list container. They are siblings and I have applied  `border: 1px solid $gray` style to both of them. I tried to apply that style to other elements but had strange results.

In a specific scenario, both have a `width: 100%` style applied to it, but `Select-control` has computed width of `183px` and `Select-menu-outer` has computed width of `183.98px` thus the 1px difference.

![screenshot 2017-08-10 12 12 10](https://user-images.githubusercontent.com/1765942/29168125-7b85a4e2-7dc5-11e7-8b3e-2e3d9708c4c8.png)

![screenshot 2017-08-10 12 13 22](https://user-images.githubusercontent.com/1765942/29168124-7b66e890-7dc5-11e7-99bd-2db21ccb69f5.png)

**SOLUTION**

Apparently `Select-control` original width of 183.98 is rounded down (instead of up) because of `display: table`. I fixed it then by applying `display: table` to `Select-menu-outer` and haven't had any side-effects so far.

**Comment by gogoku** [comment]
Has anyone found a solution for this??

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
