### ISSUE TITLE
React-select's height for long text option bug

### ISSUE THREAD

**Issue by kliu4** [JedWatson/react-select#1921]
If there are options with long text, the option will block the right part. See:

![screen shot 2017-08-10 at 11 36 55 am](https://user-images.githubusercontent.com/3431017/29188271-407fef0c-7dd8-11e7-9f54-ca6954a8b0aa.png)

**Comment by juhose** [comment]
I have this same problem including that long options will get cut.
I will put here some pictures to demonstrate the situation.
![screen shot 2017-08-11 at 13 49 55](https://user-images.githubusercontent.com/27725149/29210551-c96c1e8e-7e9c-11e7-82a6-035541a322c4.png)
![screen shot 2017-08-11 at 13 49 48](https://user-images.githubusercontent.com/27725149/29210555-ccfd163e-7e9c-11e7-9c9c-fdfcfebb74e1.png)

**Comment by juhose** [comment]
Ping

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
