### ISSUE TITLE
Custom classNames

### ISSUE THREAD

**Issue by wzup** [JedWatson/react-select#1922]
Can you elaborate on [that](https://github.com/JedWatson/react-select#custom-classnames)? Not clear. Provide examples please

> The built-in Options renderer also support custom classNames, just add a className property to objects in the options array.

**Comment by agirton** [comment]
Hi @wzup please look at the examples to see how we do this: https://github.com/JedWatson/react-select/blob/master/examples/src/components/CustomComponents.js
