### ISSUE TITLE
How to pass search text to optionComponent?

### ISSUE THREAD

**Issue by resting** [JedWatson/react-select#1926]
Am using `optionComponent` to render the items and it uses the `Highlighter` component.
How do I pass the search text to the component?

Calling `Select` like below:
```
<Select
 ...
 optionCompnent={FilteredComponent}
/>
```

Edit: How do I add a hover effect to the item?

Update: Looking at [this](https://github.com/JedWatson/react-select/blob/master/src/utils/defaultMenuRenderer.js), I guess it's not possible to pass the search input in?

**Comment by ryantan** [comment]
Technically you can wrap FilteredComponent in a HOC that accepts the search text like so:

```
const FilteredComponentWithSearchText = ({ searchText, ...props }) => {
  return (<FilteredComponent searchText={searchText} {...props} />);
}
```

And use it in place of your original component:

```
<Select
 ...
 optionCompnent={FilteredComponentWithSearchText}
/>
```

Warning: this is untested code, please give it a try and let me know if it works :p

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
