### ISSUE TITLE
Fallback to native select on mobile

### ISSUE THREAD

**Issue by isaacalves** [JedWatson/react-select#1927]
Is it possible to have it fallback to native select on mobile?

**Comment by agirton** [comment]
Hello @isaacalves we don't support this feature. You would need to handle this on your side.

**Comment by raghunayyar** [comment]
I think this is a super handy feature to have especially when a ton of options are coming in.

**Comment by Subha** [comment]
We are also having issues displaying Dropdown in Mobile devices the last row does not come up if the select is at the bottom of the page. Would be really useful if native select is supported or any insight on how to implement this is greatly appreciated. I am unable to attach the video here so attaching a snapshot .

![screen shot 2017-11-30 at 1 10 29 pm](https://user-images.githubusercontent.com/12513265/33447020-ebaf92e8-d5cf-11e7-8123-f0768c1747c7.png)

**Comment by petertenhoor** [comment]
+1 for this feature request. Would be nice to have the option to offer the native select behaviour for touch devices.

**Comment by Kujbor** [comment]
+1

**Comment by simon-online** [comment]
+1

**Comment by apuntovanini** [comment]
+1

**Comment by akeuk** [comment]
+1

**Comment by AtaS** [comment]
+1 (especially for not-multi/single select boxes)

**Comment by alexlamazing** [comment]
Could anyone help to implement this feature?

**Comment by zaguiini** [comment]
+1

**Comment by mikdatdogru** [comment]
+1

**Comment by BenGedi** [comment]
+1

**Comment by Bundas** [comment]
+1

**Comment by Greg-mso** [comment]
+1

**Comment by ioetbc** [comment]
+1

**Comment by Fsss126** [comment]
+1

**Comment by SetupCoding** [comment]
+1
