### ISSUE TITLE
Clear button clickable area takes up entire height of select

### ISSUE THREAD

**Issue by JakeSidSmith** [JedWatson/react-select#1929]
```json
"react-select": "1.0.0-rc.5"
```

If you have a bunch of items selected then the clickable area becomes huge, but is not obvious that it will clear the selected items.

I would suggest moving the click handler to the cross icon itself.

<img width="248" alt="screen shot 2017-08-16 at 10 18 36" src="https://user-images.githubusercontent.com/5850625/29356662-d714a104-826c-11e7-8feb-75ee82e8c079.png">

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
