### ISSUE TITLE
shouldKeyDownEventCreateNewOption should hook on KeyPress instead of KeyDown 

### ISSUE THREAD

**Issue by rpominov** [JedWatson/react-select#1934]
`event.keyCode` has different meaning on `KeyDown` and `KeyPress`. On `KeyDown` it refers to code of actual physical key on keyboard, while on `KeyPress` it refers to a character that will be typed. See https://stackoverflow.com/a/11030750

Because currently it's hooked to `KeyDown` event, it's impossible to enter other characters that share physical key with the comma.

For example on the following keyboard with the default `shouldKeyDownEventCreateNewOption` I'm unable to enter "<" and "Б". Also the default callback doesn't handle comma key in the number row. And I can't add it either because I would need to sacrifice "6" and "^".

![image](https://user-images.githubusercontent.com/825702/29476221-995c4050-846b-11e7-969d-31391ebf9dcc.png)

See also #345

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
