### ISSUE TITLE
Render Select components dynamically

### ISSUE THREAD

**Issue by psyanite** [JedWatson/react-select#1937]
Hi, I was wondering how I can render Select components dynamically: 
https://stackoverflow.com/questions/45767589/how-to-use-react-select-to-update-selected-options-dynamically

Thanks for reading my question in advance

**Comment by psyanite** [comment]
Fixed this by wrapping it with my custom `Filter` component, then `onChange` would call the parent `onChange(this.props.id, items)` to let the parent know which filter was updated and what the items are, and removed the stupid `kind` property from my options.

**Comment by mnmistake** [comment]
Link is down any other reference?
