### ISSUE TITLE
PR: Add support for `module` property in `package.json`

### ISSUE THREAD

**Issue by amilajack** [JedWatson/react-select#1938]
I am willing to make a PR to add support for the [module property](https://github.com/rollup/rollup/wiki/ES6-modules#es6-friendly-libraries). Would this be welcome?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
