### ISSUE TITLE
feature request: child options of options?

### ISSUE THREAD

**Issue by ucscHexmap** [JedWatson/react-select#1939]
We are currently using react-select2-wrapper and would like to move to your react-select. However we are using the two-tiered functionality where an option may have child options such as the standard html select and the functionality offered by the original select2.

You can see this live on our application in the map selector in the upper left of the UI:

https://tumormap.ucsc.edu/?p=Gliomas

Some of our maps are standalone, such as "Gliomas", the map displayed, while others are groups of maps, such as "Pancan12".

Do you have any plans to support this?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
