### ISSUE TITLE
Select Option - Event Propagation

### ISSUE THREAD

**Issue by hwhelchel** [JedWatson/react-select#1945]
I use a third party analytics tool called Heap to track product metrics. It relies on being able to record DOM events as they happen.

I'd like to be able to log when a user clicks a `.Select-option` in react select but because `event.stopPropagation` is called Heap doesn't have the opportunity to log the event.

Can the onMouseDown event on the `Option` component bubble up through the DOM?

**Comment by mantissa7** [comment]
Don't forget that by using tab, arrow keys and enter a user can also select an option with no mouse interaction

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
