### ISSUE TITLE
Add support for Symbols as option values.

### ISSUE THREAD

**Issue by benmoose** [JedWatson/react-select#1947]
Lets say I have two arrays, and I want to use React Select to allow a user to create a mapping from `people` to `pets`.
```
const people = ['amy', 'bob', 'callum']
const pets = ['cat', 'dog']
```

Next to each item in `people` there is a React Select dropdown allowing the user to select which item from `pets` to map that person too, or a `None` option if they are not mapped to a pet. Currently, the `value` on the `None` option is a string constant: `'_none'`.

However, since my arrays are user-generated, and I want to allow any string value in my arrays, it is possible that the string `'_none'` could appear in one of my arrays, which would break my implementation.

To work around this I'd like to use a `Symbol` as the value of the `None` option, because then it would always be unique and never clash with a literal string value of `'_none'`, but when I do this I get an error.

```
Uncaught TypeError: Cannot convert a Symbol value to a string
```

I think this error is thrown at [/src/utils/defaultMenuRenderer.js L37](https://github.com/JedWatson/react-select/blob/master/src/utils/defaultMenuRenderer.js#L37).

I could use `.toString()` on my Symbol, but that would raise the same conflict concerns as above.

Are there any reasons not to support `Symbol` types as values?
Do you have possible work arounds?
If not, I'd be happy to send a PR to add support for symbols as values.

Let me know if you need any clarification on my problem.
Thanks for the awesome library ❤️

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by Nokel81** [comment]
I think that this is still a relevant feature. @bladey

**Comment by ebonow** [comment]
Greetings @Nokel81 ,

The library has changed quite a bit since this issue was posted. Currently an option would need to to consist of an object that either contains a label or value, or defines a method to derive the label or value. The value of the option would need to be unique and the type is a string for purposes of string comparisons. 

The core of this ask seems to be around supply a unique key which may not be known, but seems to be just as easily solved by using either the label or a unique id.

Is there something I am missing as to why you think this is relevant?

**Comment by Nokel81** [comment]
I think that the value (only, not label) should be able to a symbol, or for that matter a number or a boolean.

As for comparisons all of those work fine with strict equality.

**Comment by ebonow** [comment]
I did a quick test and it seems like a Symbol "should" work. Are you seeing otherwise?

**Comment by Nokel81** [comment]
Ah oops I was using 3.X. Though I still don't see why they need to be stringified.

**Comment by ebonow** [comment]
The default behavior of react-select is to stringify both the value and label so typing can filter on both. This can be modified by setting a `stringify` function on customFilter
