### ISSUE TITLE
Change value to an array

### ISSUE THREAD

**Issue by gsklee** [JedWatson/react-select#195]
Right now, the component's value is a string (eg. `a,b,c`), and every time there is a change, the new value needs to be manually split before being able to be updated back into the state:

``` javascript
onChange = (newValue) => {
  this.setState({
    selection: newValue.split(',')
  });
}
```

This causes a problem when the last element in the select is being deleted, an empty element will pop up inside the select due to the following fact:

``` javascript
''.split(',');
// [""]
```

Can we change this string-based behavior into one that is array-based and prevent this glitch fundamentally?

**Comment by dcousens** [comment]
@gsklee this is on the road map.

**Comment by shuvalov-anton** [comment]
+1. It's hurts me, really

**Comment by dcousens** [comment]
@shuvalov-anton I know,  when we allocate time to this, it'll be one of the first things to change.  Until then, PRs are definitely welcome.

**Comment by dantman** [comment]
This will only apply when `multi` is enabled, right?
