### ISSUE TITLE
Stateful CSS classes should always be chained

### ISSUE THREAD

**Issue by csswizardry** [JedWatson/react-select#1951]
Hey!

I don’t actually use react-select myself, but I’m currently doing an audit for a client who does. I noticed that you use [stateful CSS classes that aren’t associated with anything](https://github.com/JedWatson/react-select/blob/af0aa5ae14dd741c3dd1c9b06733569f413c88ba/scss/control.scss#L65).

This selector:

```css
.is-open > .Select-control {
  […]
}
```

…means that, if I have react-select inside of my own modal component, like so:

```html
<div class="modal  is-open">
  […]
</div>
```

…we’d end up with a false positive, and your CSS would kick in when it shouldn’t.

- - -

As a general rule, all stateful classes (e.g. `.is-open`, `.has-dropdown`, etc.) should always be chained with something:

```css
.Select.is-open > .Select-control {
  […]
}
```

The new snippet leaves us immune to false positives and subtree collisions.

Thanks, 
H

**Comment by nicubarbaros** [comment]
True, I had a hard time on changing the style of the plugin.

**Comment by agirton** [comment]
Hi @csswizardry thank you for the suggestion! Let me open a PR to fix this.
