### ISSUE TITLE
Pre-selected options/values dissapear whilst loading options asynchronously.

### ISSUE THREAD

**Issue by samdjstevens** [JedWatson/react-select#1954]
I think what I am encountering is a bug, but if I am simply going about this wrong way I apologise!

I am using the async option loading to avoid loading a large dataset all at once. I also need to be able to have pre-existing values/options be selected on load.

To achieve this, I set the `options` option to be the pre-existing values on load, and also set the `loadOptions` option to be my async callback.

I have set the async callback to return *both the existing options and the ones found via my callback*. This works fine, except during the execution of the async callback (the API load), all the options seem to disappear, meaning that my pre-selected values disappear too. They return as soon as the async callback is executed.

Weirdly, this behaviour seems to stop if I remove one of the pre-existing values.

I have included a little example GIF of the behaviour as I probably haven't explained this very well...

<img src="http://i.imgur.com/LSZxgtQ.gif">

Any help is much appreciated.

**Comment by agirton** [comment]
Hi @samdjstevens i'm not sure 100% but I have a feeling your experiencing this due to you are setting the `options` as the `value` and the `options`. Is this correct? Can you share a bit of code or a reproducible case?

**Comment by samdjstevens** [comment]
Hi @agirton -  thanks for the reply.

Here's an example of what I'm passing for `options` and `value`:

options:
```
[
    {value: "1", label: "one"},
    {value: "2", label: "two"}
]
```

value:
`1,2`

I think the issue is something to do [with this line](https://github.com/JedWatson/react-select/blob/ec5bd6d372b0d01d78134e2bef037f9d05533dae/src/Async.js#L190) - changing from:

`options: (isLoading && loadingPlaceholder) ? [] : options`

to

`options: (isLoading && loadingPlaceholder) ? [] : options`

seems to make the issue go away

**Comment by gabchang** [comment]
I confirm there is a problem when setting options with Async.

Tried to add initial options with an empty array, on 1st load + select option, it is not displayed.
When passing undefined instead of [], or a non-empty array, it works.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
