### ISSUE TITLE
It seems like setting matchPos="start" suddenly makes the component only recognize lower-case inputs

### ISSUE THREAD

**Issue by mhintz** [JedWatson/react-select#196]
Great component! Really liking it, above all the other options out there. I found one thing which seems like it's a problem, but I'm not sure. 

It looks like when I set the matchPos="start" attribute, then the component only matches lower-case inputs (even when the labels start with upper case letters). I'm pretty sure it has something to do with the way line 519 works, but that's such a monster boolean statement that I don't really feel qualified to tackle it. Hopefully someone with more knowledge of the component can take a look.

matchPos="start"

input:
"Somevalue"
expected:
<suggested> "Somevalue"
got:
<suggested> (none)

input:
"somevalue"
got:
<suggested> "Somevalue"

Thanks much!

**Comment by dcousens** [comment]
Fixed in #215
