### ISSUE TITLE
Async class has a one-character lag when getting the inputValue

### ISSUE THREAD

**Issue by begincalendar** [JedWatson/react-select#1960]
I would link to a Plunker for this, but due to #1727, it's not so straight forward (when trying to link to v1.0.0rc-5).

Anyway, if you use v1.0.0rc-5 of "react-select" and you have code similar to this:

```
const loadOptions = (input) => {
  const sleep = new Promise((resolve) => setTimeout(resolve, 2000));
  return sleep.then(
    () => ({
      options: [],
      complete: false
    })
  );
}

ReactDOM.render(
  <Select.Async 
    autoload={false} loadOptions={loadOptions} multi={true} 
    noResultsText='No results found'/>,
  document.getElementById('example')
);
```

...and you type a single character, the menu renders with "Type to search", instead of "No results found".

If you revert to v1.0.0rc-3, it appears to work as it should.

I believe the problem is caused by the way that the `Async` class gets the `inputValue` from the `Select` class. It's getting `inputValue` from `Select`'s state, before `State` has a chance to update its copy to the latest version, meaning `Async` is always behind by one character.

**Comment by JedWatson** [comment]
@begincalendar you're right, the state wasn't being synchronised correctly. Thanks for the detailed report - I've fixed it now 😄
