### ISSUE TITLE
onChange is being triggered by input

### ISSUE THREAD

**Issue by cristianfraser** [JedWatson/react-select#1964]
https://plnkr.co/edit/dHygFMWWqVwaRAfpEmbn?p=preview

When passing an `onChange` function as props to `Select`, typing anything on the input won't trigger `onChange` because the input is the one changing, so that's OK.

But when the input is empty and backspace is pressed, `onChange(value)` is triggered with `value = []`. This shouldn't happen.

This can be seen in the example plunker.

**Comment by cephuo** [comment]
I believe this is the expected behaviour.
There are these 2 options for disabling it:
```
deleteRemoves={false}
backspaceRemoves={false}
```

**Comment by kstratis** [comment]
@cephuo Basically it doesn't. At least not as of version 2.1.1.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
