### ISSUE TITLE
Cannot override onInputKeyDown event handler

### ISSUE THREAD

**Issue by sarav1234** [JedWatson/react-select#1968]
I tried to override the onInputKeyDown in order to execute a search on my application when the user clicks on the ENTER key. However, the event handler I passed it as a prop onInputKeyDown does not execute.

```
<Select
        tabIndex={@props.tabIndex}
        inputProps={input_props}
        allowCreate={@props.allowCreate}
        autoload={@props.autoload}
        cacheAsyncResults={not @props.allowCreate}
        className={classnames(className, @props.className)}
        delimiter=","
        multi={@props.multi}
        onBlur={@handleBlur}
        onChange={@onSelect}
        onInputKeyDown={@onInputKeyDown}
        placeholder={@props.placeholder}
        id="select-input-box"
        ref="select"
        value={@props.value || ''}
        {...options}>
      </Select>

```
```
 onInputKeyDown: ->
    alert "key pressed"
    if (event.keyCode is 13)
      # event.preventDefault() # to override the behavior
      alert "enter pressed"`
```

**Comment by GlebDolzhikov** [comment]
have you pass an event in on onInputKeyDown function ?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
