### ISSUE TITLE
Question: 0.91 or 1.0.0-rc6?

### ISSUE THREAD

**Issue by Eric24** [JedWatson/react-select#1972]
For someone just getting started using react-select, should I stick with 0.91 or would it make sense at this point to use 1.0.0-rc6?

**Comment by STEVEOO6** [comment]
I would recommend using 1.0.0-rc6 (actually 1.0.0-rc5 at the moment due to the following bug https://github.com/JedWatson/react-select/issues/1971).

**Comment by JedWatson** [comment]
Version `1.0.0-rc.7` should see that regression fixed, we're about to draw a line in the sand and release 1.0.0 (which will be very similar to rc7, we just want to make sure there are no more issues with that) so I'd recommend starting with the rc's.
