### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by yrshaikh** [JedWatson/react-select#1973]
I am trying to setup react-select in my project which using react with jsx. I get this error on adding this line after npm install react-select.

import Select from 'react-select';

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by miketierney** [comment]
I suspect that this and #1974 are related.

I'm also seeing this error - reverting to 1.0.0-rc.5 fixes the issue, so it's something that was introduced in the latest release.

**Comment by agirton** [comment]
Closing as a duplicate of #1971
