### ISSUE TITLE
Need tests for: menu does not open on click if `searchable` is `true`

### ISSUE THREAD

**Issue by jochenberger** [JedWatson/react-select#1980]
Follow-up for https://github.com/JedWatson/react-select/commit/27462611929254d91a82b6b7b8cbdec6b9ca80a1#diff-04191649796841200b33375bdff7c78fR231

**Comment by JedWatson** [comment]
Thanks @jochenberger

**Comment by jochenberger** [comment]
`git bisect` blames f7cd6c2fa5b9b157a39ccaa22ebad421a5c224e2

**Comment by jochenberger** [comment]
Or rather #1580.

**Comment by jochenberger** [comment]
Maybe the default value for `openAfterFocus` should be `true`.
I wonder why the `Select -> with simple options -> should show the options on mouse click` test does not fail.

**Comment by JedWatson** [comment]
`openAfterFocus` is intended to control whether the menu opens when the control is focused (which it doesn't by default, this is by design)

However the menu *should* open when the control is clicked on (regardless of whether it was previously focused or not), this is the regression in the fix you've linked to.

Not sure why the test isn't failing 😞

**Comment by jochenberger** [comment]
The test succeeds because `handleInputFocus` is called before `handleMouseDown`. In the browser (Firefox at least), it's the other way around. That's why, in the test, the menu is opened in https://github.com/JedWatson/react-select/blob/v1.0.0-rc.7/src/Select.js#L257

**Comment by jochenberger** [comment]
Oh, I get it, the tests focus the select from `beforeEach`:
```
...
    at Select.handleInputFocus (/home/jochen/git/upstream/react-select/src/Select.js:320:14)
...
    at Object.focus (/home/jochen/git/upstream/react-select/node_modules/react-dom/lib/ReactTestUtils.js:349:18)
    at findAndFocusInputControl (/home/jochen/git/upstream/react-select/test/Select-test.js:130:24)
    at createControl (/home/jochen/git/upstream/react-select/test/Select-test.js:150:4)
    at Context.<anonymous> (/home/jochen/git/upstream/react-select/test/Select-test.js:261:15)
```
So there is no test for "no focus -> click -> should show menu". Should we create one or modify the existing test case?

**Comment by jochenberger** [comment]
See also #1527

**Comment by JedWatson** [comment]
I've updated this to reflect fixing the tests for this, let's track also fixing the issue over in #1994

**Comment by JedWatson** [comment]
I found the issues with the tests for this and comprehensively fixed them. Required quite a bit of digging, see the commit for more details.
