### ISSUE TITLE
Object.assign breaks IE

### ISSUE THREAD

**Issue by codeclown** [JedWatson/react-select#1987]
We recently updated our dependencies and noticed a bug affecting IE11 (all IE versions, for that matter).

**Screenshots from IE11 developer console**

![image](https://user-images.githubusercontent.com/211543/30321486-e40e00be-97be-11e7-9197-a4eb8c26da3e.png)

![image](https://user-images.githubusercontent.com/211543/30321501-f3e4b1c2-97be-11e7-8da6-ed7224b71267.png)

**Line in question**

https://github.com/JedWatson/react-select/blob/53f9bbc5680235a29bb225b6e788c0b0046f763f/src/Select.js#L757

**Comment by JedWatson** [comment]
Sorry about that - fixed now

**Comment by codeclown** [comment]
Thank you for quick fix, really appreciate it!
