### ISSUE TITLE
using `,` in a simple value with lazy loading will cut the result

### ISSUE THREAD

**Issue by iam4x** [JedWatson/react-select#199]
workaround: set a `delimiter` option with a random string that cannot be reproduced.

**Comment by dcousens** [comment]
@iam4x can you give reproduction code?

**Comment by iam4x** [comment]
```javascript
var Select = require('react-select');

var value = null;

var handleChange = function (inputValue) { value = value };

var getOptions = function(input, callback) {
    setTimeout(function() {
        callback(null, {
            options: [
                {
                  value: 'A long, value, with, comma',
                  label: 'A long, value, with, comma' 
                },
                {
                  value: 'A another, long value with comma, foo', 
                  label: 'A another, long value with comma, foo' 
                }
            ]
        });
    }, 500);
};

<Select
    name="form-field-name"
    value={value}
    onChange={handleChange}
    asyncOptions={getOptions}
/>
```

When you type `A long value...` and click on a dropdown result it will cut the text in the input to before the first comma. But the value will be correct, it's only the placeholder.

**Comment by WingedToaster** [comment]
Is this related to https://github.com/JedWatson/react-select/issues/149 as well?

**Comment by iam4x** [comment]
@WingedToaster It is.

Have you tried to change the delimiter option? Worked for me.

**Comment by WingedToaster** [comment]
I'm actually using this control in a <a href="https://github.com/keystonejs/keystone">keystone</a> model. It seems like the keystone <code>select</code> type doesn't accept the <code>delimiter</code> parameter to pass it along to this control. I will see what I can figure out and submit a PR on keystone.

**Comment by WingedToaster** [comment]
In case anyone from Keystone happens across this, I created <a href="https://github.com/keystonejs/keystone/pull/1442">PR #1442</a> on keystone as a work around for this issue.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
