### ISSUE TITLE
Cannot read property 'bool' of undefined

### ISSUE THREAD

**Issue by imbhargav5** [JedWatson/react-select#1992]
## Accessing PropTypes from "react" instead of "prop-types"
https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L1212

PropTypes should be used from "prop-types" package and not from "react". All other proptypes are from the prop-types package, except for this one. Not sure how this error came to pass. I can submit a PR if you need.

**Comment by gwyneplaine** [comment]
@imbhargav5 thanks for raising this, a fix for this is currently in master and will make it into the next rc

**Comment by imbhargav5** [comment]
Alright, feel free to close the PR if it's a dup.
