### ISSUE TITLE
Runtime error when using dist version: "TypeError: PropTypes is undefined"

### ISSUE THREAD

**Issue by mcorteel** [JedWatson/react-select#1996]
An example is worth a thousand explanations, so here it is:
https://plnkr.co/edit/InSmkd0lCg84J3QDjSAW?p=preview

When I load the dist version of react-select, I get a runtime error:
```
TypeError: PropTypes is undefined            react-input-autosize.js:399:2
TypeError: PropTypes is undefined            react-select.js:23:2
ReferenceError: Select is not defined        script.js:11:1
```

It worked up to 1.0.0-rc.3 (which is what the [plunker I forked](https://plnkr.co/edit/dHygFMWWqVwaRAfpEmbn?p=preview) used BTW), but I haven't been able to upgrade since then. Is there a new dependency?

@JedWatson This is the issue I mentionned in #1727

**Comment by mcorteel** [comment]
OK, it seems including prop-types solves this one (yep, I should have seen this coming):
https://plnkr.co/edit/InSmkd0lCg84J3QDjSAW?p=preview

Did I miss this in the documentation or is it just because there is no "real" documentation for 1.0?

**Comment by JedWatson** [comment]
Sorry, that's on me - I didn't update the example in the readme, have done that now.
