### ISSUE TITLE
Deprecated React.Proptypes

### ISSUE THREAD

**Issue by PatrikMatiasko** [JedWatson/react-select#1997]
## Deprecated React.Proptypes

Can you replace React.Proptypes with prop-types in these files ?

- /react-select/dist/**react-select.es.js**  (line 1736) _React.PropTypes.bool -> PropTypes.bool_
- /react-select/src/**Select.js**  (line 1060) _React.PropTypes.bool -> PropTypes.bool_

Now React generates deprecated warnings to console.

Thanks

**Comment by jochenberger** [comment]
#1992

**Comment by JedWatson** [comment]
Fixed by #1991
