### ISSUE TITLE
TypeScript import is broken after rc.05

### ISSUE THREAD

**Issue by mfursov** [JedWatson/react-select#2001]
It's now impossible to import ReactSelect in TypeScript.

This problem is related to this issue: https://github.com/JedWatson/react-select/issues/1983 (see @noah79 comment)

To workaround this issue in my TypeScript project I created the following proxy module:

---
import * as ReactSelect from 'react-select'
export default ReactSelect['default']

**Comment by labkey-nicka** [comment]
We'd been running into this before with the 0.9.x releases and just recently opted to use the `allowSyntheticDefaultImports` [ts compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html). Definitely useful in [this scenario](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default). We are currently running the `react-select@1.0.0-rc10` and `@types/react-select@1.0.55`.

For typings problems I'd recommend opening issues against the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository directly as this repo doesn't maintain its own type definition. There you can discuss it directly with the .d.ts authors.

**Comment by mfursov** [comment]
Ok, I added `allowSyntheticDefaultImports:true` and with
`import ReactSelect, {Option} from 'react-select'` style imports have a version that works.

Thank you!
