### ISSUE TITLE
Select.Async not working correctly from 1.0.0-rc.6 onwards

### ISSUE THREAD

**Issue by acordiner92** [JedWatson/react-select#2004]
I have a basic select set up as follows which works perfectly fine on 1.0.0-rc.5 but once I update to rc.6 onwards, it causes an issue where for example search say sydney it will provide a list of options however upon selecting a option it is not shown in the Select input field despite the suburb value being correctly returned from onChange. I have had a look into the Async.js code and from what I've gathered (not 100% sure) it appears to be that upon selecting an option, the inputValue field gets set to "" and causes the Async this.state.options field to become [] and therefore the value has nothing to match against. So not sure if there is a bug or I need to now change something in my implementation for Select.Async. Any help would be much appreciated. 
render:
```
 <Select.Async
                loadOptions={handleGetGoogleSuburbs}
                onChange={handleSuburbSelect}
                value={suburb}
 />
```

handlers:
```
handleGetGoogleSuburbs(input: string, optionsCallBack: any) {
    getAutoSuggestions(input)
      .then(predictions => {
        const options = predictions.map(x => {
          return { value: x.place_id, label: x.description };
        });
        optionsCallBack(null, { options });
      })
      .catch(() => {
        this.predictions = [];
        optionsCallBack(null, { options: [] });
      });
  }

```
```
handleSuburbSelect(selectRes: { value: string; label: string }) {
    if (!selectRes) {
      this.setState({ suburb: "" });
      return;
    }

    this.setState({
      suburb: selectRes.value
    });
  }
```

**Comment by ciaoben** [comment]
Same behavior here!

**Comment by SBoudrias** [comment]
I can also reproduce this issue.

**Comment by bickle66** [comment]
I was having this issue passing a string to the <Select.Async value={ this.state.string }>

But it seems to now accept a { value: '', label: '' } object, presumably to match up the values better instead of by string.

So the documentation is a bit off.

**Comment by agirton** [comment]
Hi @acac99, what @bickle66 said is correct. You need to pass in your `selectRes` object. This will also make your code much simpler as you can just use the `selectRes` reference when you are updating the `suburb` state. Let us know if this fixes your issue.

**Comment by jscheid** [comment]
>  This will also make your code much simpler

I can tell you have good intentions with this change, but I fail to see how this is an improvement.

I don't want to store the whole option, all that matters is the value anyway. The label is just that, a label. This is also different from how normal HTML5 `<select>` tag works.

I now have to keep extra state for this. My store just deals in plain values, so now I have to keep the whole option in `this.state` to make Select.Async happy and keep that state in sync with store's value, it's really messy.

Or I need to access async loaded options to search for my value, but I believe that would have to use internal APIs? Or I need to couple the select component to the async load function more tightly so that I can access the options loaded so far. None of these feel right.

Would you reconsider this change? Or at least make it so that I can pass in just `{ value: value }` with no label or a dummy label and it will work ok?

**Comment by agirton** [comment]
Hi @jscheid what I meant by code much simpler is that their handler would go from
```
handleSuburbSelect(selectRes: { value: string; label: string }) {
    if (!selectRes) {
      this.setState({ suburb: "" });
      return;
    }

    this.setState({
      suburb: selectRes.value
    });
  }
```
*to*
```
handleSuburbSelect(selectRes) {
    this.setState({
      suburb: selectRes
    });
  }
```

So no longer would they need to do any equality check in the handler. 

I understand that you may have an extra bit of state in your app logic, but in my experience this hasn't been a very small point. To change this current behavior it would be a breaking change and we don't plan on making this big of a change before 1.0.

**Comment by jscheid** [comment]
Hi @agirton, thanks for your reply. What do you think of the compromise I was suggesting, one where passing in just the `{ value }` would be enough? That would not be a breaking change unless I'm missing something?

**Comment by acac99** [comment]
@agirton @bickle66  Thanks for the update! Will update my accordingly

**Comment by thinegod** [comment]
@jscheid  +1. Isn't this how the non-async select works?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
