### ISSUE TITLE
IE11 bug. Losing focus after freezing input type

### ISSUE THREAD

**Issue by walerun** [JedWatson/react-select#2006]
If we have focused text input and then we freeze UI by doing long running computations on typing (in my case it is creating a search index for dropdown options) IE11 loses focus after a while and dropdown closes.

It's similar to another IE11 bug related to the scrollbar. And fix for this may similar solution. So going to make PR.

See Example (tested in IE11)
https://plnkr.co/edit/aG2Gfu084SBWZrnpEYyy?p=preview

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
