### ISSUE TITLE
Search From Label and Value Both

### ISSUE THREAD

**Issue by solka03** [JedWatson/react-select#2007]
I have a very simple question for multi search option. I am passing options as below where the label is a text and value as an integer.

[
	{ label: 'Chocolate', value: 1 },
	{ label: 'Vanilla', value: 2 },
	{ label: 'Strawberry', value: 3 },
	{ label: 'Caramel', value: 4 },
	{ label: 'Cookies Cream', value: 5 },
	{ label: 'Peppermint', value: 6 },
]

When I search for 4 it displays label 'Caramel'. If I search for 'Caramel' that also give me 'Caramel' . 

Is this intended behavior of react-select when I search something that will search from both - label and value?  If this is not intended behavior then this must be considered as a defect.

**Comment by agirton** [comment]
Hi @solka03 yes this is the intended behavior.

**Comment by maxlibin** [comment]
anyway to filter this? for example i want to search only from value?

**Comment by solka03** [comment]
You can use below option in configuration.



   - matchProp: "label", "value" or "any": whether to match the value,
   label or both values of each option when filtering

Regards,
Kamlesh

**Comment by maxlibin** [comment]
@solka03 i figured out, thanks 👍
