### ISSUE TITLE
Select.Async error with 1.0.0-rc.10

### ISSUE THREAD

**Issue by garrettmurphy** [JedWatson/react-select#2008]
Our app is React + Redux + Redux Form with heavy use of react-select, particularly the Async version.

After updating from rc.9 to rc.10, we're getting an error in existing code. Here's a sample (sorry, Plunkr is blocked for me at work):
```        
    const getTenantList = (searchString) => {
        return new Promise((resolve, reject) => {
            resolve({
                options: [
                    { value: 'bob', label: 'BOB' },
                    { value: 'john', label: 'JOHN' }
                ]
            });
        });
    };   
...                             
<Select.Async
  name="tenant"
  value={{ value: '', label: '' }}
  loadOptions={getTenantList}
/>
```
If I remove the Async, it works as expected (empty dropdown), but if I put it back, I get the following warning and error:

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `ServiceDefinitionsForm`.
>     in ServiceDefinitionsForm (created by Form(ServiceDefinitionsForm))
>     in Form(ServiceDefinitionsForm) (created by Connect(Form(ServiceDefinitionsForm)))
>     in Connect(Form(ServiceDefinitionsForm)) (created by ReduxForm)
>     in ReduxForm (created by Connect(ReduxForm))
>     in Connect(ReduxForm) (created by ServiceDefinitions)
>     in div (created by ModalBase)
>     in div (created by Modal)
>
> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `ServiceDefinitionsForm`.

As stated, this works fine in rc.9. Any guidance would be much appreciated.

**Comment by nathanvogel** [comment]
Same issue here when updating to rc.10, using this 
```
<Select
        name="domain-select"
        value={this.props.selectedDomainKey}
        options={this.props.domains}
        onChange={this.props.onDomainSelected}
        noResultsText="Aucun résultat"
        placeholder="Domaine..."
      />
```
where `props.domains` is an array of objects loaded asynchronously  with Redux.

I get the same error as garretmurphy with `object` instead of `undefined`.
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Comment by andymac4182** [comment]
I am getting this same error with RC10 and typescript

```
const options: ReactSelect.Options = [{ value: '0', label: '25mw' }, { value: '1', label: '200mw' }, { value: '2', label: '500mw' }];

<ReactSelect name="form-field-name" value="0" options={options} />
```

**Comment by AndreasPresthammer** [comment]
In rc6 it suddenly changed its module export. The ReactSelect component is now exposed under 'default' export. This doesnt match the typescript typings in @types/react-select. Not sure if this an intended change though.

**Comment by rameshvishnoi90904** [comment]
Getting Same Error

**Comment by nathanvogel** [comment]
Following koebeen's recommendation on #741, I changed 
`var Select = require("react-select");`
to
`import Select from "react-select";`
and now it works :)

**Comment by JedWatson** [comment]
I'm going to close this, v1 is stable now and I although there are some edge cases, I'm not sure how to better support all the ways it can be imported and bundled.

Thanks everyone for the investigation and suggestions - hopefully this will help anyone else debugging similar issues.
