### ISSUE TITLE
1.0.0.rc10 async "caching" error

### ISSUE THREAD

**Issue by timhwang21** [JedWatson/react-select#2009]
Bug: When user types faster than responses can finish, "intermediary" search queries do not ever get attempted.

Example: 
![sep-15-2017 18-31-47](https://user-images.githubusercontent.com/5831434/30505685-42eb4f6a-9a44-11e7-843a-682cb8198547.gif)

I type "asdf" while throttling the network. Queries are fired for "a", "as", "asd", and "asdf". However, when I start deleting letters, the queries for the first three search strings are never attempted. Note the placeholder text says 'Type to search' rather than 'No results.'

**Comment by timhwang21** [comment]
Some more detail: it seems like part of the issue relates to the "intelligent caching" of input strings that have already been fetched. When the user types faster than the fetches can complete, it seems like "no options" are being cached for the intermediate search strings.

**Comment by timhwang21** [comment]
Ah, it seems like the original issue is due to the component hitting the Github API rate limit 😄 oops.

Regardless, I think there is room for optimization here: 

Let's say the user types `'asdf'`. Queries will be sent for `'a'`, `'as'`, `'asd'`, and `'asdf'`. However, because [only the most recent callback is ran](https://github.com/JedWatson/react-select/blob/master/src/Async.js#L99), only the last result is cached, even though the first three requests may complete successfully.

@JedWatson what do you think about moving lines 104-106 outside the `if (callback === this._callback)` block? This means that completed network requests will still be cached, even if they're not used. The result would be that when the user hits delete from `'asdf'`, there won't be a redundant request sent for `'asd'`, as we've already cached that response. If it sounds good to you, I can file a PR. Thanks!

**Comment by timhwang21** [comment]
A related issue occurs when handling paginated endpoints:

Let's say I do a search for `'Bob'`. Three requests are fired for `'B'`, `'Bo'`, and `'Bob'`, but only the third is cached.

Then, I clear the input and search for `'Bob'` again. Upon entering `'Bo'`, the search is re-fired, and upon entering `'Bob'`, I cache hit and a new `this._callback` is not set, so the callback for `'Bo'` is fired, resetting the options array with a new set of options.

This normally would be fine, but with paginated endpoints, the options for `'Bob'` may not be a subset for those of `'Bo'` (there may be a hundred `'Boa'`s for example). Thus, we end up in a state where the search string is `'Bob'` but the options are for `'Bo'`, which can result in `'No results found.'`. 

The solution suggested above should fix it, but do you think it would also be good to set `this._callback = null;` in the cache hit condition? Thanks!

**Comment by JedWatson** [comment]
Thanks for the comprehensive issue report and fix, @timhwang21 

Closed by #2012
