### ISSUE TITLE
Async loadOptions needs to support nextProps as a parameter

### ISSUE THREAD

**Issue by dmk23** [JedWatson/react-select#2011]
I have dynamic forms that may re-order their elements based on input

With multiple `Select.Async` components (subclassed) this creates a situation when a select for Widget A may receive props for Widget B. This results in Widget A select containing WIdget B options

I tracked down the solution to overriding  componentWillReceiveProps : 
```
    componentWillReceiveProps(nextProps) {
        if (nextProps.name != this.props.name) {
	    this.setState({
	        isLoading: true,
                options: [],
            });            
            this.loadOptions('', nextProps); // re-load options (!!!)
            return;
        }
        // copied from super
	if (nextProps.options !== this.props.options) {
	    this.setState({
	        options: nextProps.options,
	    });
        }
    }
```
The problem here is that I cannot call existing `loadOptions` because it relies on current props, while here I need to pass nextProps. So I have overriden it (first two lines only):

```
    loadOptions (inputValue, nextProps=null) {
        const { loadOptions } = nextProps || this.props;
```
These fixes ought to be rolled into the core, at the very least `loadOptions` should be fixed to support passing nextProps, to support custom behavior in `componentWillReceiveProps`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
