### ISSUE TITLE
Incorrect example in async docs?

### ISSUE THREAD

**Issue by timhwang21** [JedWatson/react-select#2015]
Referring to this block [here](https://github.com/JedWatson/react-select#async-options-with-promises):

```javascript
mport Select from 'react-select';

/*
 * assuming the API returns something like this:
 *   const json = [
 *      { value: 'one', label: 'One' },
 *      { value: 'two', label: 'Two' }
 *   ]
 */

const getOptions = (input) => {
  return fetch(`/users/${input}.json`)
    .then((response) => {
      return response.json();
    }).then((json) => {
      return { options: json };
    });
}

<Select.Async
  name="form-field-name"
  value="one"
  loadOptions={getOptions}
/>
```

Because async selects do not maintain an `options` array after a selection is made, [`expandsValue()`](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L493) needs the entire option object to be passed to `value` in order to work properly. Both the async examples do this. Thus, the `value` in the example should be `{ value: 'one', label: 'One' }`.

If I've made an error, please let me know. Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
