### ISSUE TITLE
Customize prompt text when creating a new option in Creatable

### ISSUE THREAD

**Issue by aldafy** [JedWatson/react-select#2019]
Hello!
We're using react-select in our project and we need the abilty to customize prompt text (instead of default "Create option"), and I implemented it as prop. I think it would be useful for others.
Here is an example:
```
<Creatable
  options={some_options}
  multi={false}
  promptText="My custom prompt"
/>
```

**Comment by aldafy** [comment]
It can be done much easier, then i supposed. Sorry, closing issue :)

**Comment by aldafy** [comment]
It can be done much easier, then I supposed. Sorry, closing issue :)

**Comment by garysed** [comment]
@alpolishchuk, How can this be done?

**Comment by alpolishchuk** [comment]
@garysed, there is a prop, called promptTextCreator, where you can pass a function, that returns desired prompt text, i.e.

```
promptTextCreator(value) {
  return 'My custom prompt'
}

<Creatable
  ...
  promptTextCreator={promptTextCreator}
/>
```

**Comment by tlkiong** [comment]
To those that come here, the prop name is now `formatCreateLabel`.

So:

```
formatCreateLabelCreator => (value) {
  return 'My custom prompt'
}

<Creatable
  ...
  formatCreateLabel={formatCreateLabelCreator}
/>
```

**Comment by rhenaldkarrel** [comment]
I'm looking for this prop in v5.2.2... anyone know it?
