### ISSUE TITLE
IE11 foucs Issue in v0.9.1 Live version

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#2022]
![image](https://user-images.githubusercontent.com/16321079/30852734-67cbb322-a2ca-11e7-9cd9-21ec1db3f63b.png)

Add this line in v0.9.1 which will fix the focusout issue in IE11. please add this ASAP.

**Comment by agirton** [comment]
Hi @srikanth-pmap can you upgrade to the latest version?

**Comment by srikanth-pmap** [comment]
@agirton Latest version is causing some rendering issues in my project. adding that line solves the problem in IE.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
