### ISSUE TITLE
Options "Create new item" position

### ISSUE THREAD

**Issue by GruFFix** [JedWatson/react-select#2023]
Hello, tell me, how can I put the option "Create new item" at the end of the list, after the result of issuing? By default, it is at the top of the list.

https://github.com/JedWatson/react-select/blob/7523c20f83b917e838d5c99fc7afa807eb6a5e7d/src/Creatable.js#L79

unshift adds an element to the end of the list

**Comment by kylemh** [comment]
https://github.com/JedWatson/react-select/pull/1436

I believe there's already a PR for this, but it's on hold until the 1.0.0 release.
