### ISSUE TITLE
Element ref was specified as a string (value0) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner)

### ISSUE THREAD

**Issue by AnnatarHe** [JedWatson/react-select#2025]
# Are you asking a question?

No, just a proposal

# Are you reporting a bug or runtime error?

Yes. all error just after I upgrade react to version 16.

```md
Element ref was specified as a string (value0) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).
```

My code is here: 
```html
<Select
    name="foo"
    value={this.state.input.get('foo')}
    options={fooOptions}
    placeholder="foo"
    onChange={this.metaUpdateInput('foo')}
/>
```

and I review this repo, notice this line may occur this error:

```html
ref={'value' + index}
```
in [src/Select Line 929](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L929)

React 16,
React-Select 1.0.0-rc.10

**Comment by ahashem** [comment]
check this one:
https://github.com/JedWatson/react-select/issues/606

**Comment by bring2dip** [comment]
Same error is occurring for me. Any solutions yet?

**Comment by AnnatarHe** [comment]
@bring2dip I abandon this package and code a select component for my project with same interface.

**Comment by bring2dip** [comment]
@AnnatarHe Can you share your code with me?

**Comment by AnnatarHe** [comment]
@bring2dip [very simple implementation](https://github.com/AnnatarHe-Athena/webapp/blob/master/src/components/select/Select.jsx)

**Comment by bring2dip** [comment]
@AnnatarHe i have used it with redux-form so it is a bit difficult for me to implement it in your way. Looks like i have to wait for this issue to be solved.

**Comment by AnnatarHe** [comment]
@bring2dip Sadly.😭

**Comment by victorfau** [comment]
I have the same problem !!

**Comment by uiuxguy** [comment]
I'm getting this error with the following implementation:

```
import React, {Component} from 'react'
import ReactSelect from 'react-select'
import styled from 'styled-components'

const Select = ({
  creatable,
  input,
  labelKey,
  options,
  placeholder,
  promptTextCreator,
  valueKey,
}) => {
  const {onChange} = input
  const handleChange = event => onChange(event !== null ? event[valueKey] : '')
  const SelectWithCreatable = creatable ? ReactSelect.Creatable : ReactSelect
  const StyledSelectWithCreatable = styled(SelectWithCreatable)``

  return (
    <StyledSelectWithCreatable
      {...input}
      labelKey={labelKey}
      onChange={event => handleChange(event)}
      options={options}
      placeholder={placeholder}
      promptTextCreator={promptTextCreator}
      valueKey={valueKey}
    />
  )
}

...

export default Select
```

Error:
```
Uncaught Error: Element ref was specified as a string (value0) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).
    at invariant (invariant.js:42)
    at coerceRef (react-dom.development.js:6736)
    at createChild (react-dom.development.js:6998)
    at reconcileChildrenArray (react-dom.development.js:7303)
    at reconcileChildFibers (react-dom.development.js:7672)
    at reconcileChildrenAtExpirationTime (react-dom.development.js:7780)
    at reconcileChildren (react-dom.development.js:7771)
    at updateFragment (react-dom.development.js:7808)
    at beginWork (react-dom.development.js:8273)
    at performUnitOfWork (react-dom.development.js:10244)
    at workLoop (react-dom.development.js:10308)
    at HTMLUnknownElement.callCallback (react-dom.development.js:540)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:579)
    at invokeGuardedCallback (react-dom.development.js:436)
    at renderRoot (react-dom.development.js:10386)
    at performWorkOnRoot (react-dom.development.js:11000)
    at performWork (react-dom.development.js:10952)
    at batchedUpdates (react-dom.development.js:11070)
    at batchedUpdates (react-dom.development.js:2323)
    at dispatchEvent (react-dom.development.js:3414)
```

**Comment by rstims** [comment]
Im also seeing this error as well, but only when testing with enzyme/mocha...

**Comment by knoxjeffrey** [comment]
I finally resolved this by making an edit in my webpack setup to specifically state where to use the required version of react. Something similar to the following, with an alteration to the node modules path, will hopefully help some people:

`resolve: {
    alias: {
      'react': path.resolve(__dirname, '../../node_modules', 'react')
    }
  }`

**Comment by koftunka** [comment]
@knoxjeffrey Thank you! Alias works for me. Noticed that to be a pattern for monorepo setup which involves multiple components referencing same libraries

**Comment by erik-sn** [comment]
For others running into this issue where the webpack alias or reinstalling `node_modules` did not work, I came across a case that affects the second, less common part of the error message referring to the refs.

We had an implementation where JSX was being stored in Redux and then rendered as a child from another connected component (a Modal in our case). In this case React is not aware of the child JSX as I guess it was not explicitly passed as a prop.

So the `Element ref was specified as a string (value0) **but no owner was set**` is what was affecting this problem.

**Comment by benjasHu** [comment]
In my case, simply upgrading `react` and `react-dom` to version **16.2.0** did the trick.

**Comment by dsacramone** [comment]
Still seeing this error even after updating to 16.2.0 for both react and react-dom....
any other solutions?

**Comment by seelts** [comment]
Another possible solution is to use `joinValues` property.
If you just need to get value from the select and don't rely on (native) form submitting this will help.

`<Select joinValues ... />`

**Comment by threecity** [comment]
@seelts you just solved a nightmare problem I've been dealing with for almost a year. When using `npm link` to work locally on a module which includes react-select, it would crash on any change. Can you please explain a little more clearly about how `joinValues` negatively impacts native form submitting (I'm assuming you mean native HTML not `react-native`) so since I'm using `redux-form` I'm alright?

1000x thanks!

**Comment by FabioPicci** [comment]
@seelts thank you very much!

**Comment by brainlessdeveloper** [comment]
If you use Yarn, try running `npx yarn-deduplicate` to address the React duplication in `yarn.lock`. This solved the problem for me without needing `joinValues` or the Webpack `resolve.alias`.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
