### ISSUE TITLE
Select.Async search not working properly

### ISSUE THREAD

**Issue by yuval-stratoscale** [JedWatson/react-select#2026]
![oct 2 2017 11-40 am](https://user-images.githubusercontent.com/21288243/31073436-7d4765ee-a774-11e7-948d-926bfadd6418.gif)
I am having problems integrating Select.Async in my app.
I tried to understand from your playground page how the component should behave and found it problematic.
In the video attached when the select option list opened, one of the options is "jakub neichcial", when i tried to search for keyword "jaku" it returned empty list.

Please assist

**Comment by lrecknagel** [comment]
I can confirm this issue on the demo website (http://jedwatson.github.io/react-select/) at Contributors (Async) with single value and as well on a current project I am using Select.Async.

**Comment by dinkzilla** [comment]
So I am having a similar issue. Looking over the source of this example hoping it was same, I think I see your problem.

If you look at the getContributers function, it is looking for substring matches in the user's github account name, not their display name. 

```
		var options = CONTRIBUTORS.filter(i => {
			return i.github.substr(0, input.length) === input;
		});
```

So presumably Jakub's account name does not contain the substring 'jaku'. This looks like an issue with the implementation of the example, not actually a bug in the code itself.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
