### ISSUE TITLE
Broken compilation with a newer react version

### ISSUE THREAD

**Issue by jcabrerazuniga** [JedWatson/react-select#2028]
I have been using for a while React-Select and I just got the next error after I run  npm install and npm run watch:

React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of ...

This error appeared on a file that I did not modify for a while and all was working fine until today when I believe react-select stopped working. As soon as I deleted the <Select my code started to run again. Since it has been compiling perfectly until I made npm install I suspect there is a conflict with a newer react package. 

Can you please tell me how to install a react version that is compatible with your Select control until you update your component?

Thx

**Comment by camilosad** [comment]
having the same issue
`react-select@1.0.0-rc.10` & `react@15.6.2`

**Comment by jcabrerazuniga** [comment]
I had to do:    npm uninstall react-select@1.0.0-rc.10
and run
                      npm install react-select@1.0.0-rc.5

to be able to continue working.

**Comment by camilosad** [comment]
@jcabrerazuniga that worked, thanks!

**Comment by agirton** [comment]
Hi @jcabrerazuniga I'm using `react-select@1.0.0-rc.10` & `react@15.6.2` in production and not experiencing this. Can you please provide a reproducible case?

**Comment by jcabrerazuniga** [comment]
I will try. My code has been working fine using react-select@1.0.0-rc.5. Last time I downloaded my project from my repository and executed npm install, during runing time, it failed everywhere I used react-select until I uninstalled  react-select@1.0.0-rc.10 and installed react-select@1.0.0-rc.5 again. At present my code is fine. I have the feeling something was changed on the specs.

**Comment by SCullman** [comment]
Weired, I am getting the same error today, but going back to  react-select@1.0.0-rc.5 doesn't fix it.
All I can say that react-select is now also  broken on my machine.

**Comment by ajhenri** [comment]
+1

**Comment by SCullman** [comment]
It is working for me again, also with rc10 after modifying the import statement in my project.

**Comment by jcabrerazuniga** [comment]
how did you used the import?

**Comment by SCullman** [comment]
Well, I was using f#/fable, with gets transpiled to JS:
I switched from ```import "*" "react-select"``` to  ```importDefault "react-select"```.

**Comment by gwyneplaine** [comment]
@jcabrerazuniga are you still having issues with your react-select build?

**Comment by jcabrerazuniga** [comment]
For now, and until we release our app we will stay with react-select@1.0.0-rc.5. After we release I will have time to get deeply into this problem. thanks for asking

**Comment by jcabrerazuniga** [comment]
Some information:
In windows 10, without any modification to my code, I have to continue going backwards to npm install react-select@1.0.0-rc.5 . However, this is not the case if using npm (installed through nvm) in Ubuntu 16.04LTS.

**Comment by yocmen** [comment]
for me, it dont work on mac or ubuntu, i downgraded to rc5 and all works, is a import issue i think, in my code i import it like this -> import Select from 'react-select'; rc5 works, >rc5 broke all.

**Comment by jcabrerazuniga** [comment]
I have been importing using:

var Select = require('react-select');

could this be the trouble?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
