### ISSUE TITLE
Clicks on control (not menu) propagate to ancestors

### ISSUE THREAD

**Issue by jakelazaroff** [JedWatson/react-select#2029]
Basically, if you have this component in an element with an `onClick` handler set, and you click to open the menu, the `onClick` handler on the ancestor will also get called. This is because the select opens on mouseDown events but lets click events pass through.

Plunker: https://plnkr.co/edit/cHG2iZhtGC5r5FFMtyMS?p=preview

I fixed the issue on my [fork of the repo](https://github.com/jakelazaroff/react-select). May I open a PR with the fix?

**Comment by agirton** [comment]
Hi @jakelazaroff! I wonder if the better avenue is for us to not use `mousedown`. Thoughts @JedWatson?

**Comment by jakelazaroff** [comment]
The native select activates on `mousedown` I believe, so y'all should stay consistent with that.

I actually realized there's an easy (and cleaner IMO) solution: Placing an element as the direct parent of the select with an `onClick` handler that stops the event from propagating. So I would actually advocate closing this issue now 😀 

Plunker: https://plnkr.co/edit/WPr6WhbnWqBpLJLHkyIB?p=preview

Thanks for the great library!
