### ISSUE TITLE
Custom renderer of options

### ISSUE THREAD

**Issue by janmyler** [JedWatson/react-select#203]
This is only a question. For example we're using this component with the `asyncOptions` functionality for displaying autosuggestions for flight/hotel/car bookings. It would be super cool if it were possible to be able to define custom renderer for the options, not just a simple string.

I can imagine it complicates things, but having the possibility to apply styles or include things such as icons… I'd like to hear your opinion on this.

**Comment by nickbouton** [comment]
+1

**Comment by ekoeryanto** [comment]
hello, I have issue when creating netlify cms widget, it throws `TypeError: Cannot read property '__reactAutoBindPairs' of undefined`
