### ISSUE TITLE
React-Select problems with CSP.(Content Security Policy)

### ISSUE THREAD

**Issue by fernandops26** [JedWatson/react-select#2030]
# React-Select problems with CSP.
This is a Bug.

I am using CSP, style-inline: self , because need my app completely ensure, but the message when I use react-select is the next:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-..'), or a nonce ('nonce-...') is required to enable inline execution.

Check this image, the style is inyected inline.
![react-select](https://user-images.githubusercontent.com/11939055/31155512-6d7751aa-a874-11e7-8647-e57017a02ec2.png)

**Comment by agirton** [comment]
Hi @fernandops26! :smile: 

The input you see in the DOM is being rendered from [`react-input-autosize`](https://github.com/JedWatson/react-input-autosize/blob/master/src/AutosizeInput.js#L130). If your CSP prevents the style tag then you have a few options: 

1. `inputRenderer` prop and render your own input component, 
2. Not use `autosize` (e.g. `autosize={false}`), 
3. Fork the `react-input-autosize` and alter the how it outputs the styling and use that as the `inputRenderer`
4. Create a PR for `react-input-autosize` to not output a style tag.

Does this work for you?

**Comment by fernandops26** [comment]
@agirton the second option worked just fine for me. Thanks.

**Comment by cordoval** [comment]
@agirton what do we loose setting autosize to false? just curious, i am sure option 2 is just a bad patch

**Comment by cordoval** [comment]
https://github.com/JedWatson/react-input-autosize/issues/110

**Comment by agirton** [comment]
Hi @cordoval you loose the ability for the select to grow as new options are added.

**Comment by JedWatson** [comment]
I've added a prop to `react-input-autosize` that can be used to work around this (via react-select's `inputProps` prop)

See https://github.com/JedWatson/react-input-autosize#csp-and-the-ie-clear-indicator

**Comment by kristiehowboutdat** [comment]
It seems like this is broken in V2. How can we set the `react-input-autosize` props in v2?

**Comment by ThibG** [comment]
Indeed, this is broken again because of using the `emotion` library, and the only way to get away with it seems to switch to nonce-based CSP and pass the nonce to `emotion` according to https://emotion.sh/docs/@emotion/cache#nonce

**Comment by wegry** [comment]
With `react-select@3.1`, this issue didn't seem to be present with my project's relatively strict CSP setup.

**Comment by ebonow** [comment]
Greetings, 

Can someone confirm that this is still an issue? There is a NonceProvider component mean to deal with this issue, though it would certainly be helpful to have some documentation and implementation around this.

**Comment by ebonow** [comment]
@wegry I'm not certain if you have had an opportunity to try using the NonceProvider. Please let us know if this is still an issue for you.

**Comment by wegry** [comment]
@ebonow I am indeed familiar with NonceProvider. I found this issue when trying to remove react-select from my project’s main webpack chunk.

Unfortunately, the project has another library that necessitates relaxed CSP, so we haven’t gotten the chance to use it for real.

**Comment by ebonow** [comment]
@wegry any issues with us closing this issue then? If you run into problems when you do get a chance to use it for real, then please feel free to let us know or open a new issue.

Additionally, it might be worth mentioning that an unstyled react-select without any Emotion dependency is something that has been discussed as something that we'd like to work towards, though there's quite a bit to untangle before we get to that point.

**Comment by wegry** [comment]
No objections from me about closing this.

The dropping of emotion as a required dep would be lovely for us.
