### ISSUE TITLE
IE11 Last character entered gets removed when previous async request comes back

### ISSUE THREAD

**Issue by ssshake** [JedWatson/react-select#2033]
Please see screenshot. It looks like when you are typing out someones name, in IE11 (maybe in others but can't reproduce), the last character gets stripped out of the input.

It appears to happen when the prior async request comes back. I'm speculating that when the prior async request comes back it is updating the input box with it's original query. It appears that the most recent request does fire a query but it doesnt update the selector. 

From what I can tell in the network tab, the prior request resolves before the most recent so not sure why the most recent isn't updating the input box.

![31156832-849639c2-a884-11e7-9e68-b32d075ce249](https://user-images.githubusercontent.com/1675868/31184758-4fc71922-a8f8-11e7-98a9-e90f7c066ac9.gif)

```

                <Select.Async
                    value={this.state.value.id}
                    onChange={this._onChange}
                    autoload={false}
                    cache={false}
                    openOnFocus={true}
                    filterOption={() => true }
                    optionRenderer={this._optionRenderer}
                    labelKey={labelKey}
                    labelId={"id"}
                    loadOptions={this.getUsers}
                    placeholder='Search for an employee..'
                />

```

**Comment by ssshake** [comment]
anyone have an opinion on this?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
