### ISSUE TITLE
Make Select component onChange return full option like Creatable

### ISSUE THREAD

**Issue by bruno-sartori** [JedWatson/react-select#2039]
Let's say i have the options:  

`
[ 
   { label: 'test', value: "5911d526e09c9933a03e6003", someOtherKey: "lorem ipsum" },
   {label: 'test2', value: "590a0412b38bc33b802bc891", someOtherKey: "blablabla" }
]
` 

In Creatable's onChange handler i receive the first argument with the full option, but the Select component returns only the value field.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
