### ISSUE TITLE
how to differentiate between enter key pressed on option and enter pressed on input box

### ISSUE THREAD

**Issue by kiranbabu189** [JedWatson/react-select#2044]
How can i differentiate when a user selects one of the option by pressing enter and a user pressing enter key in input box.
 
what im trying to do is when the user press enter key, i want to navigate to a separate page, not to the default option.

**Comment by agirton** [comment]
Hi @kiranbabu189 can you clarify this:
> what im trying to do is when the user press enter key, i want to navigate to a separate page, not to the default option.

Are you wanting to prevent enter when they have a option highlighted or when the they are in the input?

**Comment by kiranbabu189** [comment]
yes, by default a option will be selected among the list. so hitting enter key without selecting any will select that option.

**Comment by yanosh-igor** [comment]
Is there any solution for this? Also what to achieve similar behavior.

**Comment by kiranbabu189** [comment]
created a custom one with HTML input box and ul>li ..:P

**Comment by IsenrichO** [comment]
I am also having an issue with this. I am working on a reusable component and have created a bespoke wrapper around react-select that passes several custom `components`. For example, by default I use a Material-UI List for the `MenuList` component and Material-UI's `MenuItem` for the `Option` component. The result I'm trying to achieve is that specific options in the menu can be individually disabled. I'm finding that I can get those select options to be disabled – at least, they properly appear disabled in appearance and also cannot be selected by click. However, when navigating with the keyboard arrow keys, the disabled options can be focused on and hitting the Enter key _will_ add the item. Looking to prevent that. How can I do that?

In the screenshot below, notice how the `Silicon` option has focus. It is supposed to be disabled, but using the keyboard allows me to navigate to it and hitting Enter adds the item which I'm trying to explicitly prevent.
<img width="410" alt="screen shot 2018-09-16 at 13 26 12" src="https://user-images.githubusercontent.com/11098273/45600596-4359a380-b9b4-11e8-87b1-913fe17750f2.png">

**Comment by tung-dang** [comment]
this is my workaround: 

- Pressing Arrow Up --> set `isFocusInMenuList` from `false` --> `true` and let ReactSelect continue to handle the up key
- Pressing Arrow Down --> set `isFocusInMenuList` from `false` --> `true` and do not let ReactSelect the down key because the 1st option is always selected behind the stage of ReactSelect
- Basing on value of `isFocusInMenuList`, we have to style highlight of current selected option manually.

```
export class SearchSelect extends PureComponent<
  SearchSelectProps & InjectedIntlProps,
  SearchSelectState
> {

  componentWillUpdate(
    prevProps: SearchSelectProps,
    prevState: SearchSelectState,
  ) {
    if (this.state.inputValueText !== prevState.inputValueText) {
      // every time users type more in input, we want to focus on input, not on options menu
      this.setState({
        isFocusInMenuList: false,
      });
    }
  }

  renderSelectOption = (optionProps: SelectOptionProps) => {
    const { isFocusInMenuList } = this.state;
    const { isFocused, data } = optionProps;
    const focusClassName = isFocused && isFocusInMenuList ? 'focus' : '';

    return (
      <Styled.SelectOption className={focusClassName}>
        {optionProps.children}
      </Styled.SelectOption>
    );
  };

  getCustomComponents(): SelectCustomComponents {
    return {
      ...
      Option: this.renderSelectOption,
      ...
    };
  }

  // this handler is triggered when pressing Enter on input or on menu option
  onKeyDown = (event: KeyboardEvent<HTMLElement>) => {
    const {
      isFocusInMenuList,
      isLoading,
      peopleResult,
      teamResult,
    } = this.state;

    switch (event.key) {
      case 'ArrowUp':
        if (!isFocusInMenuList) {
          this.setState({
            isFocusInMenuList: true,
          });
        }
        break;

      case 'ArrowDown':
        if (!isFocusInMenuList) {
          this.setState({
            isFocusInMenuList: true,
          });

          // when pressing arrow down first time,
          // because first option in menu is always selected, ignore this key
          event.preventDefault();
        }
        break;

      case 'Enter':
        if (
          !isFocusInMenuList ||
          isLoading ||
          !this.hasSearchResult(peopleResult, teamResult)
        ) {
          // pressing Enter on input
          event.preventDefault();
          this.setState(
            {
              selectedOption: null,
            },
            this.handleSelectedOption,
          );
        }
        // if pressing enter on menu list, let react-select handles it
        break;

      default:
        break;
    }
  };



  render() {

    return (
      <Styled.SelectWrapper>
        <AsyncSelect
          ...
          components={this.getCustomComponents()}
          onKeyDown={this.onKeyDown}
          ...
        />
      </Styled.SelectWrapper>
    );
  }
}

export default injectIntl(SearchSelect);
```

**Comment by akhilesh-94** [comment]
Did anyone find a solution for this issue?

> <Select
{...otherProps}
onKeyDown={event => {
                          const { isLoading } = this.state;
                          switch (event.keyCode) {
                            case 13: // ENTER
                              if (!isLoading) {
                                event.preventDefault();
                              }
                              break;
                            default:
                              break;
                          }
                        }}
/>
I tried the above, but when I am pressing enter on the suggested item from the menu, it is still trying to prevent the default behaviour.

**Comment by shyaniv7** [comment]
you can access the second parameter `action`
https://react-select.com/advanced#action-meta

```
 handleOnChange = (value, { action }) => {
    if (action === 'select-option') {
      // do something
    }
  };


 render() {
   return (
     <Select onChange={this.handleOnChange} ... />
   )
 }
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by yard2010** [comment]
> A lot of the above is unnecessary. In v2 you can access react-select's internal `state` from a `ref`, and simply check the `menuIsOpen` prop. Outlined here: [#2798 (comment)](https://github.com/JedWatson/react-select/issues/2798#issuecomment-423416246)

Thank you for providing the only working solution to this problem. Can we update the documentation to reflect this solution? Also, this solution feels hacky, Is there a better solution to this problem (identifying whether the enter clicked on the input or on an option)?

**Comment by ebonow** [comment]
@yard2010 what did you find lacking in @shyaniv7 's answer here: https://github.com/JedWatson/react-select/issues/2044#issuecomment-535608129

**Comment by yard2010** [comment]
@ebonow  I want to be able to send the form when the user presses enter on the input when the menu is closed (i.e. not currently selecting, and focused) for accessibility concerns. I've tried to naively add an onKeyDown event listener in which I check for Enter keypress and send the form. The problem with this approach is that when the user is using the enter key to select an option while the dropdown is opened, it will send the form, which is not my intention - I want 1 enter key press to select the option (just like a native select) and another keypress to send the form, and that's why I need to know whether the menu is opened or not when handling the keypress.

Let me know if I wasn't clear, I'm new here :)

**Comment by ebonow** [comment]
@yard2010 this functionality already works to my knowledge.

Have you had an opportunity to see my comments and code example from yesterday?
https://github.com/JedWatson/react-select/issues/2798#issuecomment-789070824

**Comment by yard2010** [comment]
@ebonow thank you. With the clarification you provided, this is not an issue anymore. Thanks again!

**Comment by Odometerscarred619** [comment]
@bladey https://raw-prejudiced.github.io/XWa8XXRNsgIpD0XYlGnfdMfX6opexqB2j4LX5vXXoBkl9dDuilR_kNyjBNDlY4CVKqUMMPVcBQ/

**Comment by yard2010** [comment]
^ Do not click this link, it looks like a phishing attempt. Please report to GitHub if you can.
