### ISSUE TITLE
Option for prefix-only search [feature request]

### ISSUE THREAD

**Issue by daisy1754** [JedWatson/react-select#2045]
Hi, this is an feature request to add an option to restrict `searchable` to only match the prefix of labels and values. For instance, I want to implement state selector for US states as shown in demo site http://jedwatson.github.io/react-select/ but restrict the search to only match prefix. 

Currently, searchable option matches any substring, so if user enters "NO" to enter North Dakota, react-select also shows Illi**no**is. Similarly, when user enter ND (as abbreviation of North Dakota),  react-select shows I**nd**iana. 

![screen shot 2017-10-09 at 9 52 03 pm](https://user-images.githubusercontent.com/980077/31369903-7aee5910-ad3c-11e7-823c-d5fbf29f5be8.png)
![screen shot 2017-10-09 at 9 51 51 pm](https://user-images.githubusercontent.com/980077/31369906-7c7da4b6-ad3c-11e7-9d84-379880d7dff7.png)

For this type of input, we expect user to enter from the first character so it'd be great if react-select support an option to restrict search to only match prefix of words.

**Comment by agirton** [comment]
Hi @daisy1754 we do have a `matchPos` prop that you can set. If you set it to `start` it will only check the start of the string. Also if you would like to customize this you can pass in your own `filterOptions` prop. See docs for more info: https://github.com/JedWatson/react-select#advanced-filters. Does this work for you?

**Comment by daisy1754** [comment]
Ah, this is exactly what I wanted. I don't know why I look over this.. Thanks @agirton !
