### ISSUE TITLE
React 16 Production environment: findDOMNode was called on an unmounted component.

### ISSUE THREAD

**Issue by ncphillips** [JedWatson/react-select#2046]
We tried upgrading to React 16 but react-select is preventing us from doing so because of an issue with calling findDOMNode on an unmounted component.

The error is below:

![image](https://user-images.githubusercontent.com/824015/31389392-53eafe98-ada7-11e7-9de2-609ead2d1132.png)

I'm trying to get some more information now.

**Comment by agirton** [comment]
Hi @ncphillips can you provide a reproducible case? It seems the menu is open and is focused when the `Select` is unmounted?

**Comment by ncphillips** [comment]
This was a really weird bug. 

* I'm using Typescript and the import used to be: `import * as Select from 'react-select'`.
* We switched it to `import Select from 'react-select'` 

That fixed it. I don't know why.

**Comment by mrtrandinhvn** [comment]
I'm having the same problem and I can reproduce by using your [creatable demo](https://github.com/JedWatson/react-select/blob/master/examples/src/components/Creatable.js)

The error occurs at the exact line that @ncphillips mentioned.

**Comment by ziodave** [comment]
Updating to 1.3.0 fixed it for me.
