### ISSUE TITLE
ASYNC autoload anomaly

### ISSUE THREAD

**Issue by uganof** [JedWatson/react-select#2047]
In ASYNC (in example Contributors is verificable),
set autoload={false} 

search element (i.e. press "j" or "d")
1. is launched event onLoadOptions with input = "d" (or "j")
2. is launched event onLoadOptions with input = "" 

this happens only once

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
