### ISSUE TITLE
Building a forked production base

### ISSUE THREAD

**Issue by alexmattson** [JedWatson/react-select#2050]
At the company Im at, we currently build our select components on top of react-select. It has become a blocker here to support auto-flipping of the selects. I was hoping it would be possible to fork the repo, implement in a separate code base and then deprecate and merge back to react-select when that feature is implemented. 

My question is: Are you removing the files to build the production folders (ie gulpfile.js, ...)? If so is it possible to get ahold of those files? or am I just missing something in the build process?

Thanks!

**Comment by greggb** [comment]
Have you tried the [npm scripts?](https://github.com/JedWatson/react-select/blob/master/package.json#L78). Looks like you should be able to just `npm install && npm run build` to get a production package. You can see what the scripts do here https://github.com/JedWatson/react-select/blob/master/package-scripts.js

**Comment by alexmattson** [comment]
@greggb those scripts are never imported into the package.json so running `npm run build` is going to run `gulp clean && NODE_ENV=production gulp build` which looks like it should be calling out to a `gulpfile.js` which should be importing the build script you mentioned. Then you would be running the correct build script. But there is no gulpfile so that is why Im a bit confused.

**Comment by greggb** [comment]
@alexmattson I might be missing something as I just happened to stumble on this issue, but I believe those are part of [nps](https://www.npmjs.com/package/nps). Have you tried running `npm run build` to see what happens? The `contributing` doc may be out of date - I don't see gulp anywhere in the repo.

**Comment by alexmattson** [comment]
@greggb find out it was conflicting with local setup so it was not a problem of the this codebase. Im going to close this.
