### ISSUE TITLE
Select.Async not working with Typescript

### ISSUE THREAD

**Issue by nickyhajal** [JedWatson/react-select#2052]
Running `1.0.0-rc.10` with @types/react-select `1.0.59`.

If I use `Select.Async` I get the following error: 

`error TS2339: Property 'Async' does not exist on type 'typeof ReactSelectClass'.`

Any thought on how to resolve this issue?

Thanks!

**Comment by richbeales** [comment]
import { Async as SelectAsync } from 'react-select';

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
