### ISSUE TITLE
Preserve value in input when selecting an option

### ISSUE THREAD

**Issue by roman01la** [JedWatson/react-select#2054]
Is it possible to force _searchable_ `Select` to preserve a value in the input after one of the options where choosen? This would allow to edit a value in the input later. Currently a value is displayed within a `span` element, so it's not possible to edit or select it. This is confusing for users, imo.

If it's not possible to do, do you accept PRs? I'd appreciate a quick guide if you know how to do it better. Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
