### ISSUE TITLE
Warning: getDefaultProps is only used on classic React.createClass definitions

### ISSUE THREAD

**Issue by gusdaud** [JedWatson/react-select#2060]
Hey,

I'm getting this message (when using with React 15.3.2):
```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```

I see that you're in process of adapting the library for newer React versions (including 16 I hope). Is this being to be fixed as well ?

**Comment by stevenmusumeche** [comment]
Same issue while trying to update to React 16.

**Comment by gusdaud** [comment]
Hey, I've found out that setting `autoSize={false}` solves this message 👍 .

It happens that when autoSize is true it instantiates a react-input-autosize component that is not adjusted for the latest versions of react.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
