### ISSUE TITLE
How to point to label and value without change in array?

### ISSUE THREAD

**Issue by bogutski** [JedWatson/react-select#2068]
I have array of objects. How to point to label and value without change in array?
```
    {
      "code": "ALB",
      "alpha2": "AL",
      "name": "Albania",
      "phoneCode": "355"
    },
    {
      "code": "DZA",
      "alpha2": "DZ",
      "name": "Algeria",
      "phoneCode": "213"
    },
```

No result:

```
                        <Select
                            name="form-field-name"
                            isLoading={true}
                            options={this.props.listCountries}
                            matchProp="name"
                            valueKey="code"
                        />
```

**Comment by littletower** [comment]
try using `labelKey` instead of `matchProp`, `valueKey`should be fine

**Comment by bogutski** [comment]
thank you. I`ll try. I used 
` options={this.props.list.map(option => ({ label: option.displayVal, value: option.val }))}`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
