### ISSUE TITLE
how can i set the id of the hidden input?

### ISSUE THREAD

**Issue by snadn** [JedWatson/react-select#207]
how can i set the id of the hidden input?

**Comment by dcousens** [comment]
Can you elaborate on what you mean?

**Comment by snadn** [comment]
At first, I want to set an id on the input, but now is not necessary.

![image](https://cloud.githubusercontent.com/assets/1269858/7875365/bb4f5c9a-05ee-11e5-83c4-3b3cbc93bb6c.png)

**Comment by dcousens** [comment]
@snadn should I close this issue?

**Comment by snadn** [comment]
@dcousens yes.
