### ISSUE TITLE
input text looks weird on IE 10 Win7

### ISSUE THREAD

**Issue by nicecue** [JedWatson/react-select#2070]
I changed input box's font size to little bigger.

![ie](https://user-images.githubusercontent.com/714316/31711421-ff83037c-b432-11e7-9285-28e928c44915.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
