### ISSUE TITLE
onChange should be fired on button release, not on press

### ISSUE THREAD

**Issue by arthwood** [JedWatson/react-select#2071]
Selecting an option is triggered by "onPress" event which causes menu to hide an thus revealing underlying component which may be triggered by "onRelease" event. In my scenario this is `material-ui/DatePicker` component.

Apart from the described scenario, turning the event to "onRelease" seems to be better UX - user may want to drag out from the options menu to prevent option from being selected.

Another thing (also addressed in other issues) is passing original event to `onChange` handler. 
Let's assume that `onChange` is now triggered by "onRelease" event, but still causes problems described in first paragraph. Having access to original event would allow to call stop propagation and fix the problem.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
