### ISSUE TITLE
Typescript missing types

### ISSUE THREAD

**Issue by Razinsky** [JedWatson/react-select#2072]
Hi,

first of all, I just started using react-select a few hours ago and I must say that it's very good, very clean and simple. Great job!

I'm working with Typescript and I already found some missing things:

- Argument `isOpen` is not defined in prop `arrowRenderer`
- Prop `clearRenderer` is not defined

I can work around those easily but I thought it worth mentioning!

**Comment by jakeboone02** [comment]
Shouldn't that be addressed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/index.d.ts)?

**Comment by couzic** [comment]
Here's a quick fix:

```ts
declare module 'react-select' {
   interface ReactSelectProps<TValue = OptionValues> {
      clearRenderer?: any
   }
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
