### ISSUE TITLE
Current search deleted on tab change

### ISSUE THREAD

**Issue by fabioespinosa** [JedWatson/react-select#2076]
Awesome work on this component, it is awesome and I use it as the main search for www.losestudiantes.co 💯 

The issue: When you type to search and then change tabs and go back again, the current search is deleted. Wondering if this was intended or is it a bug.

Thanks for the work done here 👍

**Comment by agirton** [comment]
Hi @fabioespinosa cool site! This behavior is intended. If you don't want blur to reset the input you will need to use `onBlurResetsInput`

**Comment by fabioespinosa** [comment]
Thanks @agirton ! Will use that then 👍
