### ISSUE TITLE
Where can I find an example of usage. 

### ISSUE THREAD

**Issue by muman613** [JedWatson/react-select#2079]
Hello,

I am trying to use the select component and failing miserably. I learned REACT just a month ago and am trying to use it with material-ui... But my sample application displays very strange.

Versions:
Node 8.5.0
npm 5.2.0

Packages installed:

analyzer-frontend@1.0.0 /mnt/muman-fw-gitroot/javascript-171011/REACT/analyzer-frontend
├── @types/react@16.0.15
├── @types/react-dom@16.0.2
├── electron@1.7.9
├── material-ui@0.19.4
├── react@16.0.0
├── react-dom@16.0.0
├── react-select@1.0.0-rc.10
├── ts-loader@3.0.3
├── typescript@2.5.3
└── webpack@3.8.1

I can upload my sample to github if someone has a few cycles to spare a fellow code-jockey.

I would love to use this component in our analyzer.

Thank you,
Michael Uman

**Comment by muman613** [comment]
I see that there are examples in the package but there are no instructions on how to build that project. If you can point me to instructions on using the example project I would appreciate it.

Thanks

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
