### ISSUE TITLE
React Multi has broken with prop autosize=false

### ISSUE THREAD

**Issue by fernandops26** [JedWatson/react-select#2082]
Are you reporting a bug or runtime error?
### Bug

I have a problem when I am using the prop autosize={false} and multi={true} the height of the component is extremely long, See:
![dropdown broken](https://user-images.githubusercontent.com/11939055/31855726-8c432ac2-b676-11e7-9e29-fb38bd30c523.png)

*  Test Case:
https://plnkr.co/edit/xLJjLV5YQuTZTWA5XIWs?p=preview

**Comment by ducdigital** [comment]
Confirm the issue. Remove arrowRenderer actually works
