### ISSUE TITLE
What to put in the value option

### ISSUE THREAD

**Issue by BbosaH** [JedWatson/react-select#2083]
I wonder what to put in the value field in my react-select element. currently it works . But onChange it never displays the changed name in the field. someone  help me out. This is my select element that complains that value is not defined. When i remove value. It will never show anything to the user what he has selected.
          `const select_topics = topics.map((topic)=>{
            return { value : topic.id , label : topic.name}
           })`
          `<Select 
              name="form-field-name"
              value={value}
              options={select_topics}
              onChange={this.handleSelectChange}
             />`

**Comment by macko911** [comment]
Hi,
which version of react-select are you using? Also what exactly are you passing as the `value` prop?

The `value` prop needs to be in the same format as it is passed down in the `options` prop, in your case it should look like this:
```
const value = {
  value: topic_id
  label: topic_name
}
```
Make sure the value prop isn't, for example, only a string of the topic id.

Hope this helps.

**Comment by BbosaH** [comment]
Well like i showed you, I create my` select_topics` after a map function. I dont understand the answer you gave. Automatically say `topic_id` is undefined even `topic_name`.   I need atleast a simple explanation of how the `value` field is generated. in My case how?

**Comment by rlueder** [comment]
@BbosaH I had the same question and it turns out I overlooked this sentence in the README:

> The live demo is still running v0.9.1.
> To build the new 1.0.0 examples locally, clone this repo then run [...]

Cloning the repo and running the examples from **/react-select-master/examples** locally clarified the usage for me.

Here's the most basic implementation that should help you pass the selected values back into the input field:

```
import React from "react"
import Select from "react-select"

import "react-select/dist/react-select.css"

var options = [
  { value: 'one', label: 'One' },
  { value: 'two', label: 'Two' }
]

class Filters extends React.Component {
  constructor(props) {
    super(props)
    this.state = {value: ""}
    this.handleChange = this.handleChange.bind(this)
  }

  handleChange = newValue => {
    this.setState({
      value: newValue
    })
  }

  render() {
    return (
      <Select
        name="filterFlightNumber"
        multi={true}
        options={options}
        onChange={this.handleChange}
      />
    )
  }
}

export default Filters
```

Other helpful links:
[Input field not updating when option is selected](https://github.com/JedWatson/react-select/issues/828)
[React Docs - Controlled Components](https://reactjs.org/docs/forms.html#controlled-components)

**Comment by madnight** [comment]
@rlueder I have the strange problem, that when my options values are returned by a sync function, then it does not work, however if i write the whole thing statically (literally) then it works (is a like in @BbosaH post).

Works:
```
var options = [
  { value: 'one', label: 'One' },
  { value: 'two', label: 'Two' }
]

```
Won't work:
```
const select_topics = (i) =>  [
  { value: i, label: i }
]
var options = select_topics(1)

```
