### ISSUE TITLE
Add React.Element type to the promptTextCreator

### ISSUE THREAD

**Issue by Afelua** [JedWatson/react-select#2093]
I think it's really useful to add new type to the promptTextCreator such Element type. Some designers require show not only text information (Add new value) but also need to add some manipulations to the promptTextCreator text and stylise it.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
