### ISSUE TITLE
Allow styling in placeholder class

### ISSUE THREAD

**Issue by kmestre** [JedWatson/react-select#2095]
Hi,
During a development using react-select there was a need to change styling in case of error on "Select-placeholder" class:

`<div className="Select-placeholder">{this.props.placeholder}</div>`

Since there is already props available to change styles for Select-control, and other classes, is it possible to have this feature for "Select-placeholder" please?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
