### ISSUE TITLE
Focused option should scroll into view

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#21]
I've noticed that when you're navigating the list of options with the keyboard, it is possible to focus an option that's lower than the scrollHeight of the menu.

It should make sure that the currently focused option is always scrolled into view.

**Comment by JedWatson** [comment]
Fixed by #37

**Comment by moklick** [comment]
nice! thanks

**Comment by lemurry** [comment]
Currently experiencing same issue with component with custom rendering items.

**Comment by Arhane** [comment]
@lemurry Probably you didn't set `innerRef`
