### ISSUE TITLE
IE: Scroll with mouse drag won't work

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#2102]
Hi,

In IE, when trying to scroll by dragging the scrollbar with the mouse - the dropdown is closed immediately.

any inputs?

**Comment by ChristianKLund** [comment]
Sound like the same issue as this one. https://github.com/JedWatson/react-select/issues/1020

**Comment by DaveCole** [comment]
This appears to have re-appeared with v2 of react-select, anyone have a fix?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
