### ISSUE TITLE
Prop removeSelected not available

### ISSUE THREAD

**Issue by deathwebo** [JedWatson/react-select#2103]
Hello!

I was trying to use the `removeSelected` prop to keep the selected options in a multi select available, just as the [doc says](https://github.com/JedWatson/react-select#multiselect-options)

Is this option not available yet ? Is it only available on a non-stable release ?

Thanks for the awesome library!

**Comment by buob** [comment]
Yeah, this option was just merged 6 days ago (if you look at [this commit](https://github.com/JedWatson/react-select/pull/1891/commits/fc6c47d19d980bc35ab8aee09d20708625581469) it says it's only in master, as opposed to being in any releases as well).

**Comment by smiket** [comment]
I pulled down the repo and built locally - the option is there for me.  However the NPM code does not seem to have the code in the lib folder.  I copied my locally built lib folder to my consuming project and the option takes effect (works properly).  Maybe just a build/pub thing?

**Comment by smiket** [comment]
Adding to above comment - it looks like this recent change set configured the build artifacts to publish to NPM.  So it could be that the code and the built lib/dist folders are out of sync, and perhaps another publish (including a fresh build) might resolve this.  Hope it helps - let me know if I am off track here.  And thanks for an awesome control :)

https://github.com/JedWatson/react-select/commit/78f269a772fa8d343ae584a78821ab6342a9423f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by B-Reif** [comment]
Has there been any progress on this?

Also, is there a good workaroun for the time being? I've built react-select locally and the example page works, but I haven't had much luck trying to use `npm link` with the built folder.

**Comment by unit57** [comment]
Just checking up on this update too. I see its only been a day since B-Reif asked, but I could really use this feature or a work around too.

**Comment by eugenegodun** [comment]
I doesn't work for me too.

**Comment by fedde-s** [comment]
I (a random passer-by) just noticed that release [v1.0.0](https://github.com/JedWatson/react-select/releases/tag/v1.0.0) was published a few hours back; maybe that solves your issues.

**Comment by eugenegodun** [comment]
@fedde-s thanks, it was fixed.

**Comment by Sawan1994** [comment]
@deathwebo @buob @smiket @B-Reif @unit57 
removeSelected has been renamed to [hideSelectedOptions](https://react-select.com/upgrade-guide) in v2.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
