### ISSUE TITLE
Creatable doesn't clear suggestions in other inputs

### ISSUE THREAD

**Issue by mauriciogtaborda** [JedWatson/react-select#2104]
i have a problem with creatable suggestions.
The input show selected values in other fields like suggestions.
 
I create options in creatable input and i chose other creatable input and I get the same options created in the other field.

**Comment by kimorq** [comment]
I can confirm this for v1.0.0-rc.10

**Comment by karaggeorge** [comment]
This is probably related to this: https://github.com/JedWatson/react-select/issues/2124

If those components are using the same `options` prop, the modifications done by one of them can reflect on the other

**Comment by kimorq** [comment]
The bad thing about this is that the created options from other inputs will show up in inputs that don't have the Creatable option.

**Comment by kimorq** [comment]
As a temporary fix I would suggestion doing a deep clone of the options:
options={[...yourOptionsArrayHere]}

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
