### ISSUE TITLE
Add a property addableValue like clearableValue

### ISSUE THREAD

**Issue by Bastorx** [JedWatson/react-select#2107]
Hello, I will explain our case and make you a proposition.

We are in a situation where some values exists in the Select we want to let them, but disable the possibility to add them. (Like an admin have the possibility to add this value but not a moderator).

Example: *params1* *params2*
The params2 can be see by all users but only add by an administrator
We use clearableValue: false when the moderator is connected on the option params2
But it could be interesting to have the possibility to add a "addableValue: false" and the option will be hide. (But could be display if the administrator select this)

Thank you

**Comment by Bastorx** [comment]
I found another way:

{
   data: value,
   value: value.id,
   label: "params",
   clearableValue: canEditThisValue(value.id),
   style: !canEditThisValue ?  
      { display: isAlreadyDisplay(value.id) ? "inline-block"  :  "none"  }
      : undefined
}

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
