### ISSUE TITLE
Close dropdown when clicking on select

### ISSUE THREAD

**Issue by MaaikeB** [JedWatson/react-select#211]
right now the dropdown only closes when clicking somewhere outside of the select-control.
so: the user opens the dropdown by clicking on the select element, but has to move the mouse outside the element in order to close it (if he doesn't want to select any of the options)

it would be nice to add functionality so the dropdown opens when clicking on the select-control, and closes when clicking on it while the dropdown is open

**Comment by nkbt** [comment]
Clicking on the select itself should not close menu (only focus cursor inside the input), here is a solution - click on arrow should close menu.

**Comment by JedWatson** [comment]
I agree with @nkbt, that seems like the correct behaviour. Otherwise placing the cursor at a different point in the text (with the mouse) would also close the menu, which would be unexpected.

If there's strong disagreement let me know and we can reopen the issue for discussion.

**Comment by raulmatei** [comment]
Hi guys, I feel I should add my input on this too. My opinion is that for non-searchable version it should have the HTML `<select/>` behavior, which is closing the dropdown when user clicks on the select-control and probably for the searchable version, it should close when clicking on the arrow.

**Comment by nkbt** [comment]
@raulmatei that totally makes sense. I am going to update component to support this behavior.

**Comment by brianreavis** [comment]
> for the searchable version, it should close when clicking on the arrow.

On this I disagree, for the the same reason that clicking a textbox shouldn't remove its focus.

**Comment by MaaikeB** [comment]
created PR #243  with suggested fix for this issue
for searchable select elements the feature will not apply.

**Comment by raulmatei** [comment]
@brianreavis - I understand your point, but isn't the arrow indicating that you can hide/close the dropdown by clicking on it (without losing the focus on the select-control input element)?

**Comment by nkbt** [comment]
That seems like a usual behavior of `<select>`. if you click on the input itself (not only the arrow) - it will toggle popout. So this additional PR looks fair.

**Comment by JedWatson** [comment]
Sorry I left this for so long - fell completely off my radar. I agree this behaviour makes sense when the select is not searchable, so I've merged #243 and will release a patch soon.
