### ISSUE TITLE
the input fields on IE11, when typing very fast, some keys will disappear randomly  

### ISSUE THREAD

**Issue by YehongYou** [JedWatson/react-select#2110]
the issue happen on the IE 11, when typing the input field, especially on the dropdown one.
when u type very quick, some keys of the sentences will disappear randomly.

**Comment by christopherblaser** [comment]
same problem

**Comment by JedWatson** [comment]
I believe this is actually a react bug, if you're using 15.6.1 or greater it should be fixed.

See react-input-autosize#72

Please reopen if that's not the problem

**Comment by christopherblaser** [comment]
Yep! Looks like it's fixed now after upgrading react. Thanks!
