### ISSUE TITLE
React 16: Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by mrtrandinhvn** [JedWatson/react-select#2112]
https://user-images.githubusercontent.com/824015/31389392-53eafe98-ada7-11e7-9de2-609ead2d1132.png

```
react-select: v1.0.0-rc.10
react: 16
Browser: Chrome 61
```

I tried to setup a plunker but encountered
 so many errors like "require is not defined", etc.
I can reproduce this issue easily with [your creatable example](https://github.com/JedWatson/react-select/blob/master/examples/src/components/Creatable.js):

**Comment by cslinmiso** [comment]
I am facing the same issue...

**Comment by weiliang903** [comment]
Me too.
`Uncaught Error: Unable to find node on an unmounted component.     invariant.js?7313:42`

**Comment by ZeroDarkThirty** [comment]
Facing the same issue

**Comment by YusukeHidaka** [comment]
I'm facing same issue...

**Comment by yonatanmn** [comment]
Anything new here?

**Comment by yyccQQu** [comment]
me、too

**Comment by eckdanny-osi** [comment]
supporting 2 projects atm that use `react-select`, one on react `16.3.2` and another (updated today) on `16.5.2`. Only seeing `Unable to find node on an unmounted component` on the 16.5 app

**Comment by victor95pc** [comment]
Me too, guess I try something else lol

**Comment by SheldonWatson** [comment]
Me too, where is the author?

**Comment by antonvstepanov** [comment]
The same when using select inside reactstrap modal

**Comment by victor95pc** [comment]
The reason I had errors was because I was using different versions of React, one global and other via NPM, but I refactored the whole code to remove it and after that it started working

**Comment by antonvstepanov** [comment]
Update from react 16.5 to 16.6 fixed this issue for me

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
