### ISSUE TITLE
Issue with Creating new Values

### ISSUE THREAD

**Issue by dan-ator** [JedWatson/react-select#2114]
I have a dropdown menu and I do not want the user to be able to create new values, which I thought was the default behavior, but it still allows creation. I posted this as a question on Stack, but I thought maybe it was a bug. The link here has the relevant code snippet.

https://stackoverflow.com/questions/46977832/how-do-i-disable-ability-to-edit-an-enum-field-in-react-select

I am on version react-select@1.0.0-beta13

**Comment by karaggeorge** [comment]
Use Select instead of Creatable? The normal Select component shouldn't allow for new options to be created

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
