### ISSUE TITLE
do a final release

### ISSUE THREAD

**Issue by pdeva** [JedWatson/react-select#2118]
This has been in RC for years now.
why not just do a 1.0.0 release and make further updates releases of their own, eg 1.0.1, 1.0.2 etc..

**Comment by MaxInMoon** [comment]
Too much bugs I think, people seem to use the rc.5/rc.6 for stability reasons (specially for Async Select)

**Comment by JedWatson** [comment]
I wanted to actually fix all the regressions before calling it. I think we have now.

1.0.0 is out.
