### ISSUE TITLE
Basic usage not working

### ISSUE THREAD

**Issue by ongterence** [JedWatson/react-select#2120]
I'm currently attempting to use this package, and I started by copying the example code from the documentation verbatim, and it does not work. The Select input field shows up, but no dropdown menu is rendered displaying all the available options, nothing is saved, nothing works. Anybody else have issues with the documentation example code?

**Comment by lilasquared** [comment]
does this help? https://github.com/JedWatson/react-select/issues/828

**Comment by ongterence** [comment]
a little bit. i managed to figure out how to get it sort of working a little bit, as in it seems to successfully load the options now and i seem able to enter something into the field but still no dropdown list of all the options is rendered. isn't the default supposed to have the dropdown?

**Comment by MaxInMoon** [comment]
Check that you have the right plugin css code for the `Select-menu-outer` element, and that your code doesn't contain: 
```scss
input {
  overflow: hidden;
}
```

**Comment by JedWatson** [comment]
Also ensure you're including the css if things don't look correct. I've added that to the usage now... going to close this because there's no bug we can fix directly, it sounds like it's usage related.

**Comment by righen** [comment]
@JedWatson 

Actually i have the same problem as @ongterence .
