### ISSUE TITLE
Modifying props?

### ISSUE THREAD

**Issue by mrkam2** [JedWatson/react-select#2124]
Is it modifying props which is counter-react practice?

https://github.com/JedWatson/react-select/blob/44eded2a08b6aba02b48ba2927141ab3c2f14833/src/Creatable.js#L36

**Comment by MilllerTime** [comment]
Indeed. There is an existing discussion about this in issue #1477, although it hasn't seen any activity in a while 😕

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
