### ISSUE TITLE
Creatable: when `promptTextCreator` returns only the entered text, changes don't fire on first Enter key press

### ISSUE THREAD

**Issue by tmikoss** [JedWatson/react-select#2125]
When `promptTextCreator` of `Creatable` returns only the user-entered label, you can't select the newly entered value on first Enter keypress, only the second one will trigger changes.

From what I managed to debug, this is due to the new entry being pushed into `options` prop somewhere along the way, and then failing the uniqueness check.

Minimal reproduction: https://github.com/tmikoss/react-select-creatable-bug-repro/blob/master/src/index.js (repo root is runnable, built by `create-react-app`).

**Comment by alexanderzobnin** [comment]
Faced the same issue.

**Comment by pidov** [comment]
+1 on this one

**Comment by Khvalin** [comment]
yeah, the issue is a pretty annoying one

**Comment by JedWatson** [comment]
Fixed by #2140
