### ISSUE TITLE
openOnClick prop doesn't work

### ISSUE THREAD

**Issue by elghali** [JedWatson/react-select#2127]
Hi, I don't want the menu to open on click but only when the user writes some characters that do exist in the `options`, so I tried to use the `openOnClick={false}` prop but it didn't do the job, so I wrapped the `Select` comp within a `span` which doesn't allow it to open and it works, but the problem is that now even when the arrow is clicked it won't open either,
```  
     dontOpenOnClick = () => {
    this.conditionSelector.select.closeMenu();
  }
   <span onFocus={this.dontOpenOnClick}>
                <Select.Creatable
                  ref={(node) => this.conditionSelector = node}
                />
   </span>

**Comment by CodeMeNatalie** [comment]
+1

**Comment by karaggeorge** [comment]
It seems like the implemented functionality for this is that `openOnClick` is talking about opening the menu when clicking on a not-focused select. This behavior works. If you click a not-focused Select, the menu will not open, but the Select will get focused. If, however, you click a focused Select, the menu will open normally.

Willing to write a PR if that was not the desired behavior.

**Comment by elghali** [comment]
I really can't seem to find the use case, this is my test code
```             <Select 
              options={optionsSelect}
              name="form-field-name"
              value="one"
              openOnClick={false}
            />
```
and I tried to click on the select while it's not-focused, but it immediately opens, so I can't find how does the behavior really works

**Comment by karaggeorge** [comment]
@elghali 
Here's a very simple test case: https://plnkr.co/edit/coSxiEvUgxjdwedhMtyK?p=preview
Try clicking on the select. It will focus it, but won't open it

**Comment by elghali** [comment]
ok, but now even when you click on the arrow it doesn't open if it doesn't already have focus! and that's the main problem

**Comment by karaggeorge** [comment]
That's what I was saying in my first comment. I don't know what the purpose of the prop was in the first place. If the prop is there to make sure that the first click on the component focused it but doesn't open it, then not opening on the arrow click would also be acceptable.

**Comment by elghali** [comment]
Exactly

**Comment by gwyneplaine** [comment]
hi @elghali the intention of the **openOnClick** prop is to enable the behaviour where clicking on an unfocused select will open the menu, as @karaggeorge has correctly surmised. Therefore setting **openOnClick** to false won't do what you're expecting, the example case that was provided above is very much the expected behaviour.

**Comment by JedWatson** [comment]
Closed by #2165 

I've come around to the idea that clicking the dropdown icon should always open the menu, regardless of the `openOnClick` prop.

**Comment by elghali** [comment]
Thank you @JedWatson, when will it be published to npm?

**Comment by JedWatson** [comment]
@elghali It'll be included in 1.1.0, within the next day or so. I'm just working through the other PRs that might need to be merged into that release first.

**Comment by elghali** [comment]
@JedWatson awesome thank you

**Comment by elghali** [comment]
Any news for the 1.1.0 release? @JedWatson, I apologize for the insistence

**Comment by JedWatson** [comment]
@elghali just published it

**Comment by huynhvo-asnet** [comment]
@JedWatson Can we handle a specific case of typing number of characters to show dropdown list? 
Ex: user must at least typing 3 characters to show dropdown?

**Comment by elghali** [comment]
Thank you very much @JedWatson

**Comment by AuthorProxy** [comment]
@JedWatson can we autoopen only when minimal number of characters entered?
