### ISSUE TITLE
Programatically set value of search input?

### ISSUE THREAD

**Issue by ksloan** [JedWatson/react-select#2135]
Can I set the value of the search input programatically? I want to prompt the user with a recommended search term.

**Comment by zivester** [comment]
Also curious to how this is done.  I have some weird race conditions of some sort, where I want to programatically clear the search input.  The Component does not clear, but the rest of my application has the correct state.

```
<Select value={this.props.value} />
```

If `this.props.value` is updated, I would like the component to re-render itself.

**Comment by Veronica1026** [comment]
Yeah, I also need this feature...how can we do this?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
