### ISSUE TITLE
Clear icon is not rendered if value is false (boolean type) or 0 (number type)

### ISSUE THREAD

**Issue by elefantino** [JedWatson/react-select#2136]
If there is a value 0 or false selected, the clear icon disappears. I guess 0 and false are still meaningful values and don't mean that nothing is selected. The problem is in the method getValueArray of Select component, more precisely in the last line
'return expandedValue ? [expandedValue] : [];'
There should be more comprehensive comparison as it's done for multi select above 'if (value === null || value === undefined', not just 'expandedValue ? ...'

```
getValueArray (value, nextProps) {
		/** support optionally passing in the `nextProps` so `componentWillReceiveProps` updates will function as expected */
		const props = typeof nextProps === 'object' ? nextProps : this.props;
		if (props.multi) {
			if (typeof value === 'string') {
				value = value.split(props.delimiter);
			}
			if (!Array.isArray(value)) {
				if (value === null || value === undefined) return [];
				value = [value];
			}
			return value.map(value => this.expandValue(value, props)).filter(i => i);
		}
		var expandedValue = this.expandValue(value, props);
		return expandedValue ? [expandedValue] : [];
	}

```

I can make a PR with a fix

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
