### ISSUE TITLE
when i search 1, the result had lots of others

### ISSUE THREAD

**Issue by liwanchong04719** [JedWatson/react-select#2137]
![image](https://user-images.githubusercontent.com/14052734/32595823-544badba-c56c-11e7-8bac-8f091dc79c5c.png)

**Comment by igoralemasow** [comment]
By default **react-select** searches over `value` and `label` keys, you can configure it with the following filtering options:

* `matchPos`: `"start"` or `"any"`: whether to match the text entered at the start or any position in the option value

[https://github.com/JedWatson/react-select#filtering-options](https://github.com/JedWatson/react-select#filtering-options)

**Comment by liwanchong04719** [comment]
@igoralemasow  thank you

**Comment by gwyneplaine** [comment]
thanks for the prompt reply @igoralemasow. 
@liwanchong04719  closing this issue
