### ISSUE TITLE
Deleting the selected item

### ISSUE THREAD

**Issue by GruFFix** [JedWatson/react-select#2138]
Tell me, how can I remove the selected item from the list of options?
```
getListOption = term => {
    if (term) {
      this.listsSearchPromise = List.searchName(term);
      return this.listsSearchPromise
        .then(listsName => {
          return { options: listsName };
        })
        .catch(err => {
          NotificationProvider.showErrorMessage(err);

          return { options: [] };
        });
    } else {
      return Promise.resolve({ options: [] });
    }
  };
```

```
handleNameChange = (list) => {
    const { title } = list;
    const listEntries = [...this.state.listEntries, list];

    this.setState({ listName: title, listEntries });
  };
```
Need to make multi-select emulation, only with a single choice, where you can catch the selected element, and how to get a list of options?

**Comment by Chopinsky** [comment]
Something like [this example](
https://github.com/JedWatson/react-select/blob/master/examples/src/components/Contributors.js)?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
