### ISSUE TITLE
react-select somehow cancels the click event for react-datepicker to hide?

### ISSUE THREAD

**Issue by a-eid** [JedWatson/react-select#2141]
here is gif showing off the problem.

![](https://media.giphy.com/media/xUOxf3IdZBnFeBJ7sQ/giphy.gif)

Anybody could help me find out why would this be happening?

**Comment by emrekeskinmac** [comment]
input names can be the same

**Comment by bachbach** [comment]
I've got the same issue. I found a workaround which was:

1. add `inputRenderer` prop (can be simple div)
2. keep reference to select in your component
3. wrap select with ClickOutside component from `react-click-outside` package
4. handle `onClickOutside={() => selectRef.state.isOpen && selectRef.handleInputBlur()}`

**Comment by michalpokojski** [comment]
actually there is another workaround

```
class CustomDatePicker extends DatePicker {
  deferFocusInput = () => {
    this.cancelFocusInput()
  }
}
```
read this issue https://github.com/Hacker0x01/react-datepicker/issues/730

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
