### ISSUE TITLE
Add prop to allow duplicate options with different values.

### ISSUE THREAD

**Issue by harish9312** [JedWatson/react-select#2145]
**Feature**
I searched for a prop to allow duplicate options with different values.
like
menuItems = [{ value:1, label:'Data' ,{ value: 5, label:'Data' }}];
I am in a situation where I need to implement a dropdown with the list of first names of user so there is a condition that there may be more that one user with the same firstName but there user Id is different so can some one please suggest that how I can achieve this?

**Comment by Chopinsky** [comment]
Maybe appending the user id to the label as well? Otherwise end users won't be able to select the correct name either because the display name would look identical to all the duplicates.

**Comment by calasyr** [comment]
It would be useful to be able to specify hidden information that would only be visible when you hover over an option.  Or displayed whenever there were duplicates.  Maybe the first approach would be the most workable and consist to use.

I've been asked to replace a tree navigation with this and there are duplicates.  It would be useful to be able to see the parentage of duplicate labels.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
