### ISSUE TITLE
Showing "Create OPTION" label prematurely

### ISSUE THREAD

**Issue by DanZeuss** [JedWatson/react-select#2148]
Is there a way to be showing the CREATE label only when the fetch calls were ended?

For example: 

1. The user start to type a name;
2. The fetch method is called after the user ends to type (I'm using ```_.debounce```);
3. The fetch returns nothing (an empty array);
4. Then, the new label option is shown to the user.

Currently, the new option label is shown according the user start to type:

![create option persists after field is cleared](https://user-images.githubusercontent.com/24215587/32852968-e4e29786-ca20-11e7-875d-8cfeb8f7842f.gif)

**Comment by kimorq** [comment]
totally agree, this is a must.

**Comment by DanZeuss** [comment]
@JedWatson maybe do you know any solution for this "issue"?

**Comment by rickarubio** [comment]
As a workaround, I'm currently using ```isValidNewOption```.

The basic idea is that when loadOptions is first called, I'll set a boolean flag ```isLoading``` to true. When the options are finished fetching, I'll set ```isLoading``` to false.

A "creatable" option will be considered valid only if ```isLoading``` is false. Otherwise ```isValidOption``` will return false so we don't prematurely render the creatable option.

In my constructor for the component which will render the select component, I am doing this:

```js
constructor(props) {
    super(props);

    this.state = {
      isLoading: false
    };

...etc
```

Then my component select component is looking like this:

```js
render() {
    return (
      <VirtualizedSelect
        async={true}
        onBlur={this.handleWithEditBlur}
        autoFocus={this.props.autoFocus || false}
        openOnFocus={this.props.openOnFocus || false}
        optionHeight={35}
        selectComponent={TetheredAsyncCreatableSelect}
        placeholder={this.props.searchPlaceholder || 'Search'}
        autoload={true}
        labelKey={LABEL_KEY}
        loadOptions={this.loadOptions}
        onChange={this.handleChange}
        value={this.state.selectValue}
        valueKey={VALUE_KEY}
        promptTextCreator={(company) => `Create company ${company}`}
        autoBlur={true}
        onNewOptionClick={this.createNewCompany}
        showNewOptionAtTop={false}
        isValidNewOption={this.isValidNewOption}
      />
    );
  }
```

My loadOptions function looks like this:

```js
loadOptions(query) {
    this.setState({isLoading: true});

    return requestManager('GET', url)
      .then((options) => {
        this.setState({isLoading: false});
        return { options: options };
      }
    )
  }
```

and the isValidNewOption is just:

```js
isValidNewOption() {
    // We want to not display the creatable label if the async options are
    // still loading
    return !this.state.isLoading;
  }
```

Let me know if that helped or if you have a better way of doing this, thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
