### ISSUE TITLE
Customize native validation message

### ISSUE THREAD

**Issue by ipiz** [JedWatson/react-select#2149]
# Feature request

Customize native validation message

Similar to this example https://stackoverflow.com/questions/5272433/html5-form-required-attribute-set-custom-validation-message
```html
<input type="text" id="username" required placeholder="Enter Name"
    oninvalid="this.setCustomValidity('Enter User Name Here')"
    oninput="setCustomValidity('')"  />
```
Fiddle https://jsfiddle.net/ytuee7wr/

![image](https://user-images.githubusercontent.com/1954163/32898089-1d4aba0e-cadf-11e7-8847-8fef04f35555.png)

**Comment by ipiz** [comment]
Closing this, sorry i have achieved this by passing inputProps
```jsx
<Select
  inputProps={{
    onInvalid: (e) => e.target.setCustomValidity('Invalid Custom message'),
    onInput: (e) => e.target.setCustomValidity(''),
  }}
/>
```

**Comment by zehguilherme** [comment]
I'm trying to do the same, but in a ReactJS project.
All inputs.

[GitHub project](https://github.com/zehguilherme/next-level-week)
