### ISSUE TITLE
transpilation bug

### ISSUE THREAD

**Issue by pieterlukasse** [JedWatson/react-select#2157]
This code https://github.com/JedWatson/react-select/blob/master/src/Select.js#L1075
seems to get incorrectly translated to:
https://github.com/JedWatson/react-select/blob/master/dist/react-select.es.js#L1736  (why the extra `!this.props.multi ?` part?)

This leads to errors when trying to implement `renderMenu`. I.e. `params.valueArray` will be null.

**Comment by fedde-s** [comment]
The ‘correct’ version of the code was introduced in pull request #1850, which was merged on 25 October. The last release was on 13 September… I think we'll have to wait for @JedWatson to push a new minor release to npm?

**Comment by fedde-s** [comment]
Looks like release [v1.0.0](https://github.com/JedWatson/react-select/releases/tag/v1.0.0) solves this! I can't seem to close the issue for you though.

**Comment by JedWatson** [comment]
This should be solved now
