### ISSUE TITLE
create tether props like react-selectize to be able to use react-select inside overflow hidden elements

### ISSUE THREAD

**Issue by bruno-sartori** [JedWatson/react-select#2161]
Can you make use of tether or another dependency to attach the dropdown like [react-selectize](https://github.com/furqanZafar/react-selectize) do to fix #1919 ???

**Comment by ArthurBugan** [comment]
UP!

**Comment by agirton** [comment]
Hi @bruno-sartori this will be taken into consideration now that we are in 1.0, there has been a PR (https://github.com/JedWatson/react-select/pull/1677) for this, but pulling in another dependency doesn't seem like the right choice.
