### ISSUE TITLE
dangerouslySetInnerHTML from AutosizeInput breaks jest snapshot

### ISSUE THREAD

**Issue by trealex2** [JedWatson/react-select#2167]
Our jest snapshots are not working after 1.0.0 because the `AutosizeInput`'s `style` tag sets a random hash in `dangerouslySetInnerHTML`.

This is the failing line in the snapshot:

```
                              <style
                                    dangerouslySetInnerHTML={
                                      Object {
    -                                   "__html": "input#_645q33q4k0gm::-ms-clear {display: none;}",
    +                                   "__html": "input#_vpm4tij8jm21::-ms-clear {display: none;}",
                                      }
                                    }
                                  />
                                  <input
                                    aria-activedescendant="react-select-2--value"
```

This is the lines in `react-input-autosize`:

```
renderStyles () {
		const { injectStyles } = this.props;
		return injectStyles ? (
			<style dangerouslySetInnerHTML={{
				__html: `input#${this.state.inputId}::-ms-clear {display: none;}`,
			}} />
		) : null;
	}
```

The `react-input-autosize` doc says this is a fix for IE and Edge and breaks some CSP policies. 
Since it's a problem for 1 browser, should it be `false` by default and you inject the style if you have the problem?

**Comment by tobilen** [comment]
confirmed here

**Comment by JedWatson** [comment]
I've just published a new version of `react-input-autosize` with a fix for this.

**Comment by trealex2** [comment]
Thanks for the quick fix! I'll try it next friday!

**Comment by tobilen** [comment]
fixed, thanks for the quick reply 👍
