### ISSUE TITLE
Selecting an option in non-closeOnSelect multiselects clears the search string

### ISSUE THREAD

**Issue by fedde-s** [JedWatson/react-select#2168]
If I configure the Select component to accept multiple values (`multi={true}`) and to stay open when a value is selected (`closeOnSelect={false}`), and then use the rendered widget to search the list of options, the search string is cleared as soon as I click one of the options. This was not the behaviour I intuited in this setup, as I expected to be able to select another option from the filtered list.

This Plunker, if I'm using it correctly, should demonstrate the use-case I mean:
https://plnkr.co/edit/W3PFzfr9YKZSkuLp4N3O?p=preview

Would you agree that it makes sense to change this behaviour for the `closeOnSelect={false}` scenario? Even if not, I think a way to enable it might be useful, particularly when the list of options is expected to be very long.

**Comment by danielgriese** [comment]
Did you try setting `onSelectResetsInput={false}`?
This did the trick for me in conjunction with closeOnSelect={false} and multi={true}.

**Comment by fedde-s** [comment]
Ah! The non-default option I was suggesting already exists? I see that it requires a newer release than the Plunker uses, but it seems to work 👍   Thanks, @danielgriese!
