### ISSUE TITLE
Initial value when using asyncOptions?

### ISSUE THREAD

**Issue by brianreavis** [JedWatson/react-select#217]
What's the correct way to set the initial value of a select when using `asyncOptions`?

Ideally this is what I'm looking for:

``` js
var initialOptions = [{value: "1", label: "One"}];
<Select value="1" options={initialOptions} asyncOptions={...} />
```

The problem is that the component doesn't play nice with both `options` and `asyncOptions` being set. The `componentWillReceiveProps` method seems to inadvertently reset the options loaded asynchronously with the ones specified as props.

Am I doing something wrong, or do we need to implement an `initialOptions` prop (like `initialValue` for regular input elements)?

Related: https://github.com/vschoettke/react-select/commit/78845b0e30f53b21daff3139d745507458f92da4

**Comment by carlosrberto** [comment]
same issue here

**Comment by wizhippo** [comment]
Wish that was the case.  It does correctly show the label afterwards but the call to asyncoptions is then passed an object if you you do not have autoload=false.  If you do have autoload=false then the label appears as the placeholder instead of the selected value.

**Comment by CWSites** [comment]
With the latest version, this should work using the `defaultValue` prop.

**Comment by JedWatson** [comment]
Looks like this is fixed 👍
