### ISSUE TITLE
Contributors (Async) example - suggested names disappear

### ISSUE THREAD

**Issue by NeilJS** [JedWatson/react-select#2177]
In the Contributors (Async) [here](http://jedwatson.github.io/react-select/), some of the names in the list disappear (zero results) when you type more of the letters. For example, when the whole list is initially shown, we can see "Dave" is a name but as we type "D", only Daniel and Dimitry remain in the autocomplete. Same issue with Jakub. Also, adding the surname or using _just_ the surname brings back zero results (whilst these issues do not exist for other examples on the page, such as the "Custom Placeholder, Option, Value, and Arrow Components" example.

**Comment by Chopinsky** [comment]
This example actually filters the github username, instead of the actual contributor names. Meaning if the contributors' username do not match their actual name, they would be filtered out by typing their full name. That said, this is not a bug, but a feature that's not very obvious in the example.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
