### ISSUE TITLE
Unclearable Select single: content overflows over arrow-zone

### ISSUE THREAD

**Issue by Jen-ni** [JedWatson/react-select#2178]
The problem is demonstrated in the attached picture:

![image](https://user-images.githubusercontent.com/16971079/33306135-cedb10aa-d419-11e7-9847-3f6f81cf884d.png)

Solution could be:

.Select--single>.Select-control .Select-value, .Select-placeholder
    padding-right: 25px; (instead of 10px)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
