### ISSUE TITLE
Creatable component doesn't pass required attribute to input

### ISSUE THREAD

**Issue by egemon** [JedWatson/react-select#2189]
Here is example:
https://plnkr.co/edit/JGqcML1sRPGkmcX05n7y?p=preview
Documentation says that Creatable pass all default Select props to Select, but it seems like false at least for required attr. Please take a look.

**Comment by chubbsMcfly** [comment]
Same issue, I've tried using both the required prop as well as passing required:'true' through on the inputProps

**Comment by Dashue** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
