### ISSUE TITLE
Background of options is transparent 

### ISSUE THREAD

**Issue by AtulKondekar** [JedWatson/react-select#2194]
Background of options is transparent  

![transparent -select](https://user-images.githubusercontent.com/34239253/33553778-0b335872-d920-11e7-8e06-4684472495d6.png)

````
<div  className="col-xs-12 col-sm-12 col-md-6 col-lg-6 m-b-15" style={{paddingTop: 26,backgroundColor:'#fff'}}>
                                    <Select value={this.state.parentComboValue} name={this.state.parentComboLabel} onChange={(event) => {

                                        this.setState({
                                            parentComboValue: event.value,
                                            parentComboLabel: event.label
                                        })
                                    }} options={this.state.parentCombo} clearable={false} style={{backgroundColor:'#fff'}}>

                                    </Select>
                                    <text className="errorColor">{this.state.parentComboError}</text>
                                </div>
````

**Comment by sun2rise** [comment]
any news about it?

**Comment by sun2rise** [comment]
@AtulKondekar I think I have the solution:
you only need to override the `.Select-menu-outer` `z-index` property with the value you need.
Currently z-index in that class is 1.

**Comment by damianobarbati** [comment]
@sun2rise I have the same problem: how did you solve? Can you post a snippet about overriding the class you mentioned?

**Comment by sun2rise** [comment]
Hi @damianobarbati, sorry for the delay

you can create a reactSelectFix.css like this:
```css
.Select-menu-outer {
  z-index: 100 !important;
}
```

and then you can load this rule where/when needed like this:
```js
import './ProSelectFormFix.css';
```

without using andy className or inline js css

**Comment by damianobarbati** [comment]
@sun2rise thanks but it does not work.

**Comment by sun2rise** [comment]
@damianobarbati which version are you using?

**Comment by devjones** [comment]
For version 2, you need to style the menu component

```
    const selectStyles = {
      menu: base => ({
        ...base,
        zIndex: 100
      })
    };
```

Then you can reference the Select component via:
```
<Select styles={selectStyles}>
```

**Comment by patryck100** [comment]
> ```css
> z-index: 100 !important;
> ```

I did something using styled-components and it worked just fine.

`export const SelectContainer = styled(Select)`
  width: 200px;
  margin: auto;
  margin-top: 30px;
  z-index: 100 !important; //fix opacity problem of select dropdown
`;`
