### ISSUE TITLE
Dropdown won't open when the all multi options selected

### ISSUE THREAD

**Issue by kennyhyun** [JedWatson/react-select#2197]
When the all options have been selected, the drop down will not open.
It may be intended but if it's true, it's nice to have some inform like...

- disabling (blur) the triangle icon
- drop down with a placeholder like 'no available options left'

Captured this from the demo page.

![image](https://user-images.githubusercontent.com/5399854/33635378-dbca9968-da6b-11e7-9888-71e7fa09d090.png)

Is that intended? or is it possible to show some message in such case?

**Comment by stanislav-grin** [comment]
Anyone please?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
