### ISSUE TITLE
Edit New Option

### ISSUE THREAD

**Issue by nickwild-999** [JedWatson/react-select#2199]
When a new option has been created is there anyway to edit this or do you have to create a new option. 

For example the use enters Czmpaign 1 as a new option by mistake, but I can't see how to edit that to be Campaign1.

**Comment by abdelwahed-mohamed** [comment]
any news on this ??

**Comment by lbelavoir** [comment]
This feature is related to #1868 even is the question is about AsyncCreatable I think the idea of the feature is the same.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
