### ISSUE TITLE
version 1.1.0. When click right arrow open dropdown list , it  can't close through click not select area.

### ISSUE THREAD

**Issue by johnmeng24** [JedWatson/react-select#2200]
`import 'react-select/dist/react-select.min.css';

import React, { PureComponent } from 'react';

import Select from 'react-select';
import autoBind from 'react-autobind';
import classNames from 'classnames/bind';

const loadOptions = [
  { value: 1, label: 'john test1' },
  { value: 2, label: 'john test2' },
];

class CustomSelect extends PureComponent {
  constructor() {
    super();
    autoBind(this);
    this.state = {
      selectedProduct: 1
    }
  }

  handleProductChanged(value) {
    this.setState({
      selectedProduct: value
    })
  }

  render() {
    return (
      <div style={{width: 200}}>
        <Select
          value={this.state.selectedProduct}
          simpleValue
          onChange={this.handleProductChanged}
          options={loadOptions}
        />
      </div>
    );
  }
}

export default CustomSelect;`

**Comment by gex** [comment]
i think i have the same issue. when i open the select by clicking on the small arrow then the only way to close it is clicking on the arrow again. i cannot close it by clicking on other parts of the select or clicking somewhere else on the page. i found an [example](https://plnkr.co/edit/h8u0Q8v0I9sAW5L7Coud?p=preview) in #2151 while i was checking the open issues so i didn't make another one. but i make some gifs :)

clicking on the value:
![react-select-1](https://user-images.githubusercontent.com/15120752/33942059-0b2bbcf6-e015-11e7-81ef-d3dfdf5a0305.gif)

clicking on the arrow:
![react-select-2](https://user-images.githubusercontent.com/15120752/33942067-10e1d73e-e015-11e7-97ca-b078132f3500.gif)

**Comment by Kerumen** [comment]
I have the same issue as well, `react-select@1.1.0`.

**Comment by david-jam** [comment]
@Kerumen I think the issue talked here is same as I encountered now right?
https://github.com/JedWatson/react-select/issues/2239

**Comment by Kerumen** [comment]
Yes, if you open the dropdown by clicking on the arrow, you won't be able to close it until you click on the arrow again.

**Comment by david-jam** [comment]
@Kerumen so it seems we are waiting for fix @JedWatson

**Comment by Pixelatex** [comment]
so, any idea when this release will be coming?

**Comment by johnmeng24** [comment]
it's fixed in latest version

**Comment by Pixelatex** [comment]
The 2.0.0 release that's now marked as alpha?
