### ISSUE TITLE
Selector has wrong height if autosize=false and arrowRenderer=null

### ISSUE THREAD

**Issue by kozakdenys** [JedWatson/react-select#2202]
The issue appears if `autosize={false}` and `arrowRenderer={null}` on the same time.
Can be related to this issue https://github.com/JedWatson/react-select/issues/2082
An example of code https://plnkr.co/edit/i5Cdg3e8f8JPBZowFLMj?p=preview

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
