### ISSUE TITLE
Remove Theme from react-select

### ISSUE THREAD

**Issue by lifeiscontent** [JedWatson/react-select#2204]
Hey @JedWatson ,

first off, thanks for the great library.

I was wondering if you'd be okay with me adding a seperate stylesheet that just adds structural CSS and removes the theme in react-select.

Most of the time, when I'm creating a react-select element, I'll need everything except the theme.

So, if you're okay with this idea, I'll get started on it.

I haven't worked in this codebase before, so if you can point me to the right files I should be editing when working on this feature, that'd be cool.

Thanks!

**Comment by JedWatson** [comment]
We've implemented custom styling comprehensively in v2: https://deploy-preview-2289--react-select.netlify.com/styled

This doesn't implement specifically what you want, but I think we could work it a bit more to implement "base" styles and various "themes" that people can opt into (similar to how we've done the `Animated` components)

I'm working to finalise the API at the moment so let me know if you've got any feedback - if nothing else, it should make it much easier to remove "presentation" styles that are applied by default.
