### ISSUE TITLE
onBlur not closing the Dropdown.

### ISSUE THREAD

**Issue by Subha** [JedWatson/react-select#2206]
I have a similar issue in my project and was able to recreate the issue when i cloned this repo today.

Steps to recreate:

1. Click the dropdown Arrow.
2. Without selecting any options I selected another dropdown and the dropdowns never got closed.

I have attached a snapshot of my issue. 

Expected Behaviour:

I expect the onBlur gets called when I clicked on the next dropdown(arrow Button). But the onBlur never got fired. 

Is anyone facing this issue? 

![screen shot 2017-12-11 at 4 11 10 pm](https://user-images.githubusercontent.com/12513265/33855595-5fbdf96a-de93-11e7-9c2b-44d58770dd51.png)

Any help is greatly appreciated.

Thank you
Anu

**Comment by Chopinsky** [comment]
I think this is related to issue #2182

**Comment by JedWatson** [comment]
@Chopinsky is correct, fixed by #2213
