### ISSUE TITLE
Option render optimization

### ISSUE THREAD

**Issue by profimediacz** [JedWatson/react-select#2207]
Hi @JedWatson ,

I do an optimization of our application in React. I'm using library why-did-you-update and there are too many avoidable rerenders of option component. 

For example if I hover one option, all options call render method. 

We using select with hundreds options and there are be feel small lags on hovering each option.

Could you start to use React PureComponent for all components where you expect very often unnecessary rerender?

Best

**Comment by profimediacz** [comment]
We pass this by creating own Option and Value component, but this is not very comfortable solution.

**Comment by jvega** [comment]
extend the option component from React.PureComponent or use recompose and wrap the option component with an enhancer that checks if the component should be updated

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
