### ISSUE TITLE
The default delimiter does not change

### ISSUE THREAD

**Issue by roysG** [JedWatson/react-select#2210]
This is my code:
`<Select.Creatable
                    multi={true}
                    delimiter={' '}
                    options={[]}
                    onChange={this._handleSelectTags}
                    placeholder="type your tags"
                    rtl={this._rtl}
                    value={this.state.valueTags}
                />`

I want to change the default delimit from ',' (default) to ' '.
I can't override it, do i miss something or that a bug?

v - 1.1.0

**Comment by roysG** [comment]
any update?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
