### ISSUE TITLE
Enter event

### ISSUE THREAD

**Issue by ayozebarrera** [JedWatson/react-select#2217]
Hi, good work!

I think the problem comes with #212...

Every input item on a form, if its focused, it will submit the form **(if not empty!)** if you press enter key... but react-select will open the list... why? I don't see any good reason for that...

Anyway, if this will be the behaviour, how can I solve it? 

thanks

**Comment by alexxmde** [comment]
Same issue here

**Comment by sstern6** [comment]
Having the same problem

**Comment by thiagolelis-luizalabs** [comment]
You can override the onInputKeyDown function, like this:

```
    onInputKeyDown(event) {
        switch (event.keyCode) {
            case 13: // ENTER
                event.preventDefault();
                break;
        }
    }
```

And on Select

```
<Select
    {...otherProps}
    onInputKeyDown={onInputKeyDown}
/>
```

**Comment by sstern6** [comment]
@thiagolelis-luizalabs thanks but wasnt this issue fixed and is supposed to be intended functionality, not supposed to be overwritten?
