### ISSUE TITLE
CSS does not load using the documented way. 

### ISSUE THREAD

**Issue by sakshij** [JedWatson/react-select#2220]
In the documents it says, `import 'react-select/dist/react-select.css';` will load the css. However, the component appears un-styled. 

However it works fine using `import '!style-loader!css-loader!react-select/dist/react-select.css';`
Raised a PR for the same: https://github.com/JedWatson/react-select/pull/2219

**Comment by mateossh** [comment]
Thanks for help, @sakshij ;)

**Comment by kstratis** [comment]
Thanks for the snippet! Worked great for my case!

**Comment by midnightcodr** [comment]
Doesn't work for me. There are no *.css files under **node_modules/react-select/dist**

Installed using `npm install react-select`

Other information:
"react-select": "^2.0.0-alpha.8"

**Comment by zhaoyi0113** [comment]
It doesn't work for me. There is no `*.css` file under `node_modules/react-select/dist` folder.

**Comment by RahulReddy75** [comment]
Any update on this issue?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
