### ISSUE TITLE
react select is very large 52KB

### ISSUE THREAD

**Issue by samuelcolvin** [JedWatson/react-select#2223]
React select `v1.1.0` is apparently very large, 52KB, 13.5KB when gzipped. This is almost half the size of react-dom itself.

Why is this? Is there anything which can be done to reduce it?

See [here](https://cdn.rawgit.com/samuelcolvin/2e88e58c142cc9633d6da5d75b779f43/raw/3e4f118c3ed401dc03c2cac575826d5fecb2b6ed/report.html) for a `BundleAnalyzerPlugin` report.

![image](https://user-images.githubusercontent.com/4039449/34052559-d3bf4b32-e1ba-11e7-93aa-ec330aeac7f2.png)

For reference the code is [here](https://github.com/tutorcruncher/socket-frontend) or let me know if you need any more details on this particular setup. But I'm not doing anything weird just using `react-select` with a fairly vanilla `create-react-app` app.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
