### ISSUE TITLE
Placeholder prop in Custom Components

### ISSUE THREAD

**Issue by aravindsrivats** [JedWatson/react-select#2224]
I love how easy it is to setup react-select. 

I was setting up my component using the examples.  The CustomComponent examples provides a reference to the `placeholder` prop for the valueComponent. 

https://github.com/JedWatson/react-select/blob/master/examples/src/components/CustomComponents.js#L58

But the property is not being passed to the component.  I can submit a PR to fix this.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
