### ISSUE TITLE
Creatable: "newOptionCreator" should not be used for creating the "placeholder" option

### ISSUE THREAD

**Issue by UselessPickles** [JedWatson/react-select#2229]
The "newOptionCreator" prop is currently used for two completely distinct and incompatible purposes:

1) Convert raw user input into an Option (its primary purpose).
2) Generate the "new option" placeholder option with the "prompt" text as its label.

This makes it very difficult to use "newOptionCreator" for its primary purpose, because the "label" passed into "newOptionCreator" is sometimes the user input to be processed, and other times is the "prompt" message for the placeholder option. In order to properly implement "newOptionCreator", the incoming "label" must be tested to see if it is actually the "prompt" message, rather than raw user input.

The Creatable component should internally take care of creating the placeholder option in terms of the new option that was created by passing the raw user input to "newOptionCreator".

Here's the problematic code in the "filterOptions" method of Creatable:

```ts
		if (isValidNewOption({ label: this.inputValue })) {
			const { newOptionCreator } = this.props;

			const option = newOptionCreator({
				label: this.inputValue,
				labelKey: this.labelKey,
				valueKey: this.valueKey
			});

			const isOptionUnique = this.isOptionUnique({
				option,
				options: excludeOptions.concat(filteredOptions)
			});

			if (isOptionUnique) {
				const prompt = promptTextCreator(this.inputValue);

                                /// !!!!!!!! HERE'S THE PROBLEM !!!!!!!!!!
				this._createPlaceholderOption = newOptionCreator({
					label: prompt,
					labelKey: this.labelKey,
					valueKey: this.valueKey
				});

				filteredOptions.unshift(this._createPlaceholderOption);
			}
		}
```

My proposed solution:
```ts
const prompt = promptTextCreator(this.inputValue);

this._createPlaceholderOption = {
    // The "base" of the placeholder option should the same as the new option it represents.
    // NOTE: Intentionally creating the option again here instead of reusing "option" to avoid any
    //            bugs caused by shallow copying.
    ...newOptionCreator({
        label: this.inputValue,
        labelKey: this.labelKey,
        valueKey: this.valueKey
    }),
    // Override the label with the desired prompt
    [this.labelKey]: prompt,
    // Somethign like this may also be useful for custom option renderers?
    isNewOptionPlaceholder: true
};
```

**Comment by dchasepdx** [comment]
I'm having issues with this as well. For me `newOptionCreator` appends a string to the new option being created. This has the side effect of appending that string to the  "Create Option" placeholder text.

**Comment by ondrejhlavacek** [comment]
The same issue here. Workaround is that the `promptTextCreator` function has to return the same string that is then used as the label in `newOptionCreator`.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
