### ISSUE TITLE
Allow custom loader (feature request)

### ISSUE THREAD

**Issue by iamvanja** [JedWatson/react-select#2230]
It should be possible to pass a loader component so that [`renderLoading`](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L761) can check if there is a prop passed and render that instead of the default loader.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
