### ISSUE TITLE
Build seems to be out of date with source code

### ISSUE THREAD

**Issue by gabrielbenjamim** [JedWatson/react-select#2236]
I noticed it when I was checking this fix #2185 (missing in the builded code)

**Comment by fedde-s** [comment]
I think the built code tracked in the repo might reflect the last release rather than the latest state of the `master` branch, issue report #2157 was based on the same confusion.

**Comment by JedWatson** [comment]
We found some regressions in master that blocked the release, after updating the builds. It should all be in sync again as of the 1.2.0 release yesterday.
