### ISSUE TITLE
Auto Scroll to select option not work in searchable case

### ISSUE THREAD

**Issue by shikelong** [JedWatson/react-select#2237]
How to scroll to select option? Seem no props / method provided now.

The gif: 
![gif](https://user-images.githubusercontent.com/4499997/34189922-f09fbc70-e578-11e7-9332-3200737a381e.gif)

Regards.

**Comment by yuri-sakharov** [comment]
Hi @shikelong.
This is the bug and looks fixed in https://github.com/JedWatson/react-select/pull/2245

Please check it on demo: https://deploy-preview-2245--react-select.netlify.com/

**Comment by shikelong** [comment]
Thank you!
