### ISSUE TITLE
tab key 

### ISSUE THREAD

**Issue by niyingg** [JedWatson/react-select#2238]
#The tab key does not work when the manual input string does not select option

![image](https://user-images.githubusercontent.com/13973458/34190484-fea9cbd2-e57b-11e7-8321-ea106a88f76d.png)
input
When I move the mouse to the input and focus the input，why the cursor does not appear？
![image](https://user-images.githubusercontent.com/13973458/34190519-33f812a8-e57c-11e7-8873-e0e077301488.png)

**Comment by yuri-sakharov** [comment]
Hi @niyingg 
Description unclear for me. Can you please add screen record gif and describe more(browser, react-select version, which component, props)? 

Thanks.

**Comment by niyingg** [comment]
of course,thank you!
I have two problems. but I already  resolved them.
first. I didn't find the cursor when I focused the input. It's due to CSS.
second. when I input some string and the select option doesn't match. then I press the tab key. the cursor didn't move to the next input. I found it is due to the props tabSelectsValue.
if I set tabSelectsValue={false},  It worked.
