### ISSUE TITLE
feature request: let write value that is not in the list 

### ISSUE THREAD

**Issue by webmobiles** [JedWatson/react-select#2240]
It's possible to add a feature to allow type values that are not on the list ? by example i  need add cities that are not on the list or some lists are not really from a database (have no  id) but the important thing it's capture the text, not the id value or key.

**Comment by webmobiles** [comment]
I've realize the future exists

**Comment by samarti** [comment]
How did you do it?

**Comment by webmobiles** [comment]
you must to use  <Creatable>
