### ISSUE TITLE
new width of react select not respected by component next to it

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#2248]
I have such component

[screenshot](https://ibb.co/n6h7Zm)

when I add more and more tags such that they don't fit - you can see position of other components (which are located next to react select) like the black "X" button are not updated, **e.g. the "X" should move to the right since width of react-select has increased**. However, it doesn't. Can someone help what is wrong?

This is how those components (each row) is created:

```
(<div style={{ display: "flex",  verticalAlign: "middle"  }}>
                        <Checkbox style={{ marginTop: 9, width: 40 }} checked={data.checked} onCheck={(e, value) => {
                        this.updateTreeNodeCheckedById(data.id, value);
                        }} />
                        <Select
                            value={data.value}
                            simpleValue                          
                            placeholder={data.label} 
                            multi  
                            style={{marginTop:"5px", width: "300px", maxWidth:"300px"}}       
                            onChange={(value)=>{ this.updateTreeNodeValueById(data.id, value)}}
                            options={[{value:0, label:"სატესტო1"},{value:1, label:"სატესტო2"}, {value:2, label:"სატესტო3"},{value:3, label:"სატესტო4"}]}
                        /> 
                        <IconButton onClick={() => {
                            this.deleteTreeNode(data.id)
                        }}>
                            <ClearBtn />
                        </IconButton>
                    </div>)
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
