### ISSUE TITLE
How to use react-select for conditional dropdown.

### ISSUE THREAD

**Issue by yharish991** [JedWatson/react-select#2251]
Let's say i have two dropdowns A and B, options in dropdown B should be populated based on the selected value from dropdown A. 
How can this be done?

**Comment by jmarmolejos** [comment]
Hi @yharish991, please don't take it the wrong way but the issues page of a github repo should not be used for support requests/how to's. That said, the answer to your question is that basically you have to implement this functionality yourself and will depend on your project's setup. I put together a quick n' dirty example on how to do this with just using setState here: https://stackblitz.com/edit/react-mvqwr7

What I did was to set 2 collections with the options and filter the second one with the value selected from the first one. Hope this points you in the right direction.

**Comment by yharish991** [comment]
@jmarmolejos thanks for the help, sorry for the wrong way for creating issue. closing it

**Comment by ColossalSquid** [comment]
dfdfvdvzdvzdvfdzv kvjakvndv
