### ISSUE TITLE
Async multi-select removing values on search

### ISSUE THREAD

**Issue by itsalysialynn** [JedWatson/react-select#2256]
Hi everyone, 

I'm having a weird issue when searching on an async multi-select.  When I visit my page, I have five users already loaded in the value (Tammy, Sherri, Tonia, Jessica, Jamie).  When I start to search on that input to add more users, some of these values disappear depending on what I'm searching for.  
i.e. I search for "j" now I can only see "Jessica" and "Jamie" as values.  But, this doesn't change my state, I still see all five until I actually select something from this search, and then they are gone from the state aside from "Jessica," "Jamie" and my new selection.  I'm currently using 1.0.0-rc.3 but I tried switching to re.9 with no resolution. 

Here is my code: 

```
<Select.Async
    loadOptions={this.getUsers}
    multi
    disabled={this.state.sending}
    value={this.state.userIds}
    onChange={users => this.setState({ userIds: users })}
    placeholder="Search for Users" />

  userSearch = (search, types, callback) => (
    Fetch.ajax({
     ... get the data
    }).done(({ users }) => {
      const options = this.formatUsers(users)
      callback(null, { options })
    })
  )

  getUsers = (search, callback) => {
    this.userSearch(search, ['Admin'], callback)
  }

  formatUsers = users => (
    _.map(users, user => (
      { label: user.name, value: user.id }
    ))
  )
```

**Comment by erlanggatjhie** [comment]
Hello!

I also had the same issue today and I'm using react-select 1.1.0. After looking at the source code, I found out that `getValueArray` and `expandValue` function in `Select` component might be the culprit. `getValueArray` is one of the function that is responsible to render the selected values on the screen. 

```javascript
getValueArray (value, nextProps) {
	const props = typeof nextProps === 'object' ? nextProps : this.props;
	if (props.multi) {
		if (typeof value === 'string') {
			value = value.split(props.delimiter);
		}
		if (!Array.isArray(value)) {
			if (value === null || value === undefined) return [];
			value = [value];
		}
		return value.map(value => this.expandValue(value, props)).filter(i => i);
	}
	var expandedValue = this.expandValue(value, props);
	return expandedValue ? [expandedValue] : [];
}

expandValue (value, props) {
	const valueType = typeof value;
	if (valueType !== 'string' && valueType !== 'number' && valueType !== 'boolean') return value;
	let { options, valueKey } = props;
	if (!options) return;
	for (var i = 0; i < options.length; i++) {
		if (String(options[i][valueKey]) === String(value)) return options[i];
	}
}
```

When we pass in an array of a string into the value property (`this.state.userIds` in your case) of the `Select` element, it will go to this code inside `getValueArray`:

```javascript
return value.map(value => this.expandValue(value, props)).filter(i => i);
```

It will call `expandValue` function for each element of the value and if we look at the `expandValue` function, because of the type of value is `string`, it will go to this code:

```javascript
for (var i = 0; i < options.length; i++) {
	if (String(options[i][valueKey]) === String(value)) return options[i];
}
```

And this is where the problem is. It will compare each selected value with the options that are loaded asynchronously and return undefined if the selected value is not present in the options. So in your case, it will return only Jessica and Jamie and the rest of the items will be undefined:

```javascript
// coming back to this code in getValueArray().
// Here, I replace the map function with your data to clarify what i'm saying
return [undefined, undefined, undefined, { label: 'Jessica', value: 'id1' }, { label: 'Jessica', value: 'id2' }].filter(i => i);
```

Then all the undefined values will be filtered out and the component will render the remaining two.

I'm not sure how to fix this cleanly and the temporary solution that I had is to not pass in an **array of a string into the value props** but instead pass in an **array of an object that has the same data structure as the options**. In your case, I would do:

```javascript
// where this.state.users are in this format:
// [{ label: 'Jessica', value: 'id1' }, { label: 'Tammy', value: 'id2' }, ...]
<Select.Async
    loadOptions={this.getUsers}
    multi
    disabled={this.state.sending}
    value={this.state.users}
    onChange={users => this.setState({ users: users })}
    placeholder="Search for Users" />

  ...
```

**Comment by itsalysialynn** [comment]
@erlanggatjhie that worked perfectly, thank you so much!!

**Comment by itsalysialynn** [comment]
@erlanggatjhie I'm now having an issue where the items selected are not being removed from the dropdown list.  I'm not using the ```removeSelected={false}``` prop.  I'm curious if this is being caused by the new format of the values.  Would appreciate your thoughts.

**Comment by erlanggatjhie** [comment]
Hello @itsalysialynn ! I can't seem to reproduce this issue on version 1.1.0. One thing that you might need to double check is whether the value of the selected item and the dropdown item are the same one. If they are the same one, they should get filtered out.

You can also try to filter the options in your `userSearch` function.

**Comment by ahmehri** [comment]
This issue is very important and I think it should get attention of the maintainers.

**Comment by Venmathi2510** [comment]
Hello .. Even I'm facing the similar issue.

I have the initial state rendered from db values and on edit of the form, when i try to add more users, the first user(say John) which i'm adding as new is getting added correctly where as the when I type for adding the next user (i.e on key press) the user(i.e John) which I added is removed automatically. I'm able t add only one user at a time along with the users which are already on state. 

FYI,
While creating it as new (0 users), i'm able add more than one user. where as while editing it this weird behavior is happening. 

**Below is my code:**
 <Select.Async
                        name="Users"
                        value={this.state.Users}
                        matchPos="any"
                        loadOptions={this.getOptions.bind(this)}
                        onChange={this.handleSelectChange.bind(this)}
                        multi={true}
                        options={this.props.options}
                         placeholder="Select Authorized User(s)"
                         removeSelected={this.state.removeSelected}
                        joinValues={true}
                        />

**--------**

handleSelectChange = (value) =>  {
    this.setState(Object.assign({}, this.state, { Users: value}));
};
  };

**--------**
getOptions = (input, callback) => {
      callback(null, {
        options: input !== ''? this.props.getUsers(input):'',
        complete: true
      });
  };

Please help me out.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
