### ISSUE TITLE
Multiple 'Failed prop type: Select: prop type' warnings

### ISSUE THREAD

**Issue by Bezilon** [JedWatson/react-select#2257]
Simply using the example my project blurts out several warnings for the Select props which are not even undefined by default. Example:

> Warning: Failed prop type: Select: prop type `trimFilter` is invalid; it must be a function, usually from React.PropTypes.

trimFilter should be false by default and the PropType is not even set to be a function on any file I have even by accident.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
