### ISSUE TITLE
onMenuScrollToBottom not working with 6 item

### ISSUE THREAD

**Issue by kenzouno1** [JedWatson/react-select#2258]
I have large data and i want menu on scroll to bottom will load more data with ajax. If set default size = 6 have scroll but event onMenuScrollToBottom  not work

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
