### ISSUE TITLE
Keep open dropdown when using Async with closeOnSelect not working

### ISSUE THREAD

**Issue by jaypandya73** [JedWatson/react-select#2260]
Hi guys,

I want to keep open drop-down menu of search when searching users/lists from with `Select.Async` after selecting option from drop-down.

I've seen similar issues and as @JedWatson given suggestions here https://github.com/JedWatson/react-select/issues/1542#issuecomment-328919546, I've tried to do the same but no luck.

here is code which I'm using:
```javascript
  getList(input) {
	if (!input) {
	  return Promise.resolve({ options: [] });
	}
    return axios.get(`http://localhost:4000/api/v1/search?search=${input}`)
    .then(response => {
      this.setState({
        searchedOptions: response.data.ideas
      })
      return { options: response.data.ideas };
    })
  }


<Select.Async
      closeOnSelect={false}
      onSelectResetsInput={false}
      backspaceRemoves={true}
      value={this.state.value}
      onChange={this.onChange}
      onValueClick={this.gotoItem}
      valueKey="id"
      labelKey="title"
      loadOptions={this.getList}
      noResultsText={'No result found :('}
      cache={false}
      />
```
Can any one can tell me how to keep open drop-down menu with Async after selecting option from it?
Any help would be appreciated 🙏

**Comment by alexandersoto** [comment]
@jaypandya73 try also setting `autoBlur={false}`. It doesn't quite leave the dropdown open, but it does reopen it after a selection is made. I know the default is supposed to be `false`, but setting it explicitly seems to make a difference.

**Comment by masihtamsoy** [comment]
I am using "react-select": "^2.0.0-beta.5".

`<AsyncSelect
    className='select-container'
    classNamePrefix='select-internal'

    closeOnSelect={false}
    closeMenuOnSelect={false}
    onSelectResetsInput={false}
    
    isMulti

    cacheOptions
    defaultOptions
    loadOptions={promiseOptions}
/>`

This works for me.

**Comment by masihtamsoy** [comment]
I am using "react-select": "^2.0.0-beta.5".

`<AsyncSelect
className='select-container'
classNamePrefix='select-internal'
isMulti
closeOnSelect={false}
closeMenuOnSelect={false}
onSelectResetsInput={false}
cacheOptions
defaultOptions
loadOptions={promiseOptions}
/>`

This works for me.

**Comment by nilansht** [comment]
@masihtamsoy  Were u able to keep it open in Windows ? Below Windows 10 ?? anywhere ?

**Comment by rheydt** [comment]
I also have this issue with Async. Although the dropdown stays open, the options clear (because the input clears), defeating the purpose of leaving it open at all.

Have tried setting a bunch of props I've seen mentioned in various issues: 
`<AsyncSelect
        autoload={false}
        cacheOptions={true}
        loadOptions={this.getLoadOptions(loadOptions)}
        value={value ? value.map(this.translateOption) : this.state.value} 
        **closeOnSelect={false}
        closeMenuOnSelect={false}
        onSelectResetsInput={false}
        removeSelected={false}
        hideSelectedOptions={false}
        autoBlur={false}**
      />`

**Comment by rovolution** [comment]
I figured out a work-around for this...

**Comment by celso-wo** [comment]
@rovolution Your solution worked for me.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by andresfaj** [comment]
@rovolution Your solution is still working, year 2023, thanks

**Comment by helloitsmix** [comment]
I had a similar problem, I wanted to do this:

1. At the first focus event of my select some `defaultOptions` pop up

![1](https://github.com/JedWatson/react-select/assets/49068524/85292525-4cb7-4f9c-8c55-a1556d6559b7)

2. When I search something some `searchOptions` pop up

![2](https://github.com/JedWatson/react-select/assets/49068524/ea0fa203-0501-464a-9888-8ed3f3fd249a)

3. And they REMAIN even after I selected one of them!

![3](https://github.com/JedWatson/react-select/assets/49068524/5b95a54e-0986-4ac1-95c8-6c0c679d43fb)

4. When I close the menu my `searchOptions` aren't needed anymore

![4](https://github.com/JedWatson/react-select/assets/49068524/ba21b180-0232-4bcc-a1ef-4fad14b3b119)

5. And the `defaultOptions` come back

![5](https://github.com/JedWatson/react-select/assets/49068524/c47d8890-dd68-43fa-b3b9-4d7415e7bd31)

Here's how I did it:

```JavaScript
<AsyncSelect
  isMulti
  closeMenuOnSelect={false}
  onFocus={getMultiOptions} // function that sets the defaultOptions
  loadOptions={loadOptions} // function that sets the searchOptions
  onMenuClose={() => setSearchOptions([])} // function that empties the searchOptions
  defaultOptions={searchOptions.length > 0 ? searchOptions : defaultOptions}
  onChange={s => setMultiSelected(s)}
  value={multiSelected}
/>
```
