### ISSUE TITLE
Pasting value to Async doesn't show resuts on the list.

### ISSUE THREAD

**Issue by hubertglowiak** [JedWatson/react-select#2264]
Hello.

During testing I found that pasting value to Async doesn't actually work. It fires getOptions, it returns array from BE but results doesn't show on the list. Fe. I've got 10 users in DB, all of them are named user1, user2, ...  . When I filter for "user" I get all of them in the response but they aren't actually passed to the list. Is it a bug?

 <Async
          {...input}
          cache={false}
          clearable={false}
          ignoreCase={false}
          name={input.name}
          value={input.value}
          loadOptions={getOptions}
          placeholder={placeholder}
          onBlur={() => input.onBlur(input.value)}
          noResultsText="No results found."
        />

Thanks for help!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
