### ISSUE TITLE
Dropdown arrow button works on mobile, but not on desktop.

### ISSUE THREAD

**Issue by hunter-digital** [JedWatson/react-select#2267]
https://github.com/hunnuh/good-jobs

Live Demo:

http://goodjobshere.org/

This has been a real head-scratcher for me. It seems I have all the props right; but that damn button just won't work. Clicking within the field does indeed work as intended.

**Comment by yuri-sakharov** [comment]
Hi,
Please provide more data (steps to reproduce) because description is unclear.

**Comment by JedWatson** [comment]
I can't work this out... it looks like you're using Preact (which I haven't personally tested) which means I couldn't use react devtools to work out what's going on with your props.

Please see if you can reproduce it in a code sandbox and reopen with more information, then we might be able to work out what's going on :)

(see https://codesandbox.io/s/y2p1808251 for a simple codesandbox to start with)

**Comment by emilyyount** [comment]
I am also using Preact and if you click directly on the down caret arrow, nothing happens. If you click anywhere else in the select, it works. I'm afraid I'm on deadline and do not have time to make a separate example, but I can confirm this is an issue.

**Comment by wketting** [comment]
We ran into this same issue in combination with Preact. Workaround is to add custom arrow renderer, e.g. default arrowRenderer as custom arrow renderer:
`const arrowRenderer = () => <span className="Select-arrow" />;
`

**Comment by piotrkochan** [comment]
In preact it does not work at all as expected. The dropdown icon is missing. After select item, if You try to select again then all options are blue (like selected).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
