### ISSUE TITLE
different input in onInputChange and loadOptions

### ISSUE THREAD

**Issue by blackberry4311** [JedWatson/react-select#2271]
I have AsyncComponent using react-select that will load data when input character > 3 as below:
 
```
<AsyncComponent
        className={this.props.className}
        multi={this.state.multi}
        value={this.state.value}
        onChange={this.onChange}
        onBlur={this.props.input.onBlur}
        onFocus={this.props.input.onFocus}
        valueKey="name"
        labelKey="name"
        onInputChange={(input) => { console.log(input) }}
        backspaceRemoves={this.state.backspaceRemoves}
        loadOptions={(input) => {
          return this.getEducation(input)
        }}
      /> 
```

let me demonstrate my issue:
when I type some thing like "d", input of onInputChange and loadOptions is the same. But when I keep type "d", input of onInputChange will become "đ" (this is what I expected) but input of loadOptions still "d". And the loadOptions will send wrong input to my API.

When I delete character "đ" above and input another "d", input of onInputChange received new input but loadOptions was not.I try to use many unicode character like "ê" ,"ư" and the same result as above
Any solution for this ?
  
 I'm using react-select 1.2.0

**Comment by khacthanh244** [comment]
I same issue .

**Comment by blackberry4311** [comment]
anyone have solution for this ?

**Comment by TrevorBurnham** [comment]
I believe this is WAD: You need to set `ignoreAccents={false}`. Otherwise, accents are removed from the input value before it's used for search.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
