### ISSUE TITLE
Accepting PR? Keep dropdown menu open when waiting for 'loadOptions' to return

### ISSUE THREAD

**Issue by jnachtigall** [JedWatson/react-select#2281]
At the moment the `AsyncCreatable` always collapses (closes) the dropdown when executing the `loadOptions` promise/callback. Then when the results are fetched then the dropdown is expanded (opened) again. For quick ajax responses this results in some kind of "flashing" of the menu. See this screencast:
![react-select-flashes](https://user-images.githubusercontent.com/3307404/34820534-20044b94-f6c1-11e7-84e9-0816e9f189c0.gif)

I would rather like to have it open all the time like e.g. www.google.com does it when presenting its search suggestions in the dropdown.

It's rather simple to implement this, just change (comment out) this src:
https://github.com/JedWatson/react-select/blob/99acc31346acacaee23cefecd2ab9b13e3d672bb/src/Async.js#L133-L140

I just did this and it looks like I want now:

![react-select-keep-open](https://user-images.githubusercontent.com/3307404/34820535-2022797a-f6c1-11e7-951d-35b179de6472.gif)

Would you accept a PR for this, maybe using a new `Async` prop called `keepMenuOpenDuringLoading`?

**Comment by JedWatson** [comment]
Left a comment on that PR - definitely happy to fix this.

**Comment by flexdinesh** [comment]
Closing this issue. Pl refer to this [comment](https://github.com/JedWatson/react-select/pull/2292#issuecomment-602154695) for more info.
