### ISSUE TITLE
Accepting PR? <Del> should work like normal when `Creatable` and deleteRemoves is `true`

### ISSUE THREAD

**Issue by jnachtigall** [JedWatson/react-select#2282]
**Steps to reproduce:**

1. Go to the last example *Custom tag creation* at http://jedwatson.github.io/react-select/
2. Type in some stuff, create a typo and use the `<Del>` (delete) to fix it. 

**Expected results:**

For Creatable and when deleteRemoves is disabled, then like in any other text input field, as a user I want to be able to use the `<Del>` key

**Actual results:**
Just nothing happens when pressing `Delete` key.

**Solution:**

Would you accept a PR on this? It seems to be a simple matter of just moving the event.preventDefault() inside the `if` clause at:

https://github.com/JedWatson/react-select/blob/7bc9363ad139546e296778774b7d16e7cdf72d55/src/Select.js#L548-L553

At the moment the `<del>` is just always captured.

**Comment by jnachtigall** [comment]
Interestingly, the `backspace` does it exactly this way and works as expected:

https://github.com/JedWatson/react-select/blob/7bc9363ad139546e296778774b7d16e7cdf72d55/src/Select.js#L474-L479

It's just a one liner, so happy if you want go ahead :)

**Comment by JedWatson** [comment]
Thanks for going ahead with the PR, happy to have this fixed!
