### ISSUE TITLE
react-select causing issues when converted from react to angular on mobile (iPad/android)

### ISSUE THREAD

**Issue by raju508** [JedWatson/react-select#2283]
We are using angular and react in our application with majority being written in angular. In one of our react components, we are using react select for the drop down. When we convert from react to angular using react2angular/ngreact/react-in-angular npm, the react-select isn't working as it should be. When clicked on the select, it opens and immediately closes. This is happening only on iPad and android. It is working fine on Desktop. Looks like the touch events are triggering twice (just an assumption). Can you please let me know if there is a possible workaround for this issue?

**Comment by JedWatson** [comment]
I'm definitely open to a PR that solves this if someone can isolate what needs to be fixed (and ensure it doesn't cause problems for other use-cases)

But otherwise I'm not familiar enough with Angular or react2angular/ngreact/react-in-angular to help, sorry!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
