### ISSUE TITLE
filterOptions currentValues is null when not in multi mode

### ISSUE THREAD

**Issue by nabati** [JedWatson/react-select#2297]
`filterOptions(..., currentValues)` sets currentValues to null if not multi-mode is enabled. When multimode is enabled, you get an array as described. I think this behavior is unexpected and isn't described in the docs either.

Plunkr. https://plnkr.co/edit/1FzkjTZ2lbbb5mko2Naz?p=preview

**Comment by djdu** [comment]
I got into same issue as well. When the select is not in "multi" mode and clear the selected value I get the null error.

> must be a `string` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
