### ISSUE TITLE
Unable to use library

### ISSUE THREAD

**Issue by javierggi** [JedWatson/react-select#2302]
I am unable to correctly use the library, the process I am following to use it is the following:

1. install in my react project: 
`npm install --save react-select`
2. import the library
`import Select from 'react-select';`
3. Copying one of the examples in the sample page:
`<Select
        name="form-field-name"
        value={value}
        onChange={this.handleChange}
        options={[
          { value: 'one', label: 'One' },
          { value: 'two', label: 'Two' },
        ]}
      />`
using the required variables.

The message I am getting on my console is:

> Uncaught SyntaxError: Unexpected identifier
>     at Object.../node_modules/react-select/dist/react-select.es.js (bundle.js:5606)
>     at __webpack_require__ (bundle.js:20)
>     at eval (eval at ./components/LoginWizard/LoginWizard.js (bundle.js:6798), <anonymous>:32:20)

**Comment by divmgl** [comment]
This is unrelated to this package. It looks like you're having some transpiler problems. Make sure Babel is properly set up then try again.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
