### ISSUE TITLE
Down arrow is not opening the menu.

### ISSUE THREAD

**Issue by guptar8jan** [JedWatson/react-select#2309]
Using version "1.2.1", down arrow won't open the menu. I see this work in demo examples and I am using the same code.

```jsx
<Select
  id="state-select"
  ref={(ref) => { this.select = ref; }}
  onBlurResetsInput={false}
  onSelectResetsInput={false}
  autoFocus
  options={options}
  simpleValue
  clearable={true}
  name="selected-state"
  disabled={false}
  value={true}
  onChange={this.onChange}
  searchable={false}
/>
```

**Comment by emilyyount** [comment]
I am experiencing the same issue.

**Comment by alexsasharegan** [comment]
Likewise. Using Chrome 66.0.3359.181 on Mac.

**Comment by alexsasharegan** [comment]
Found that my 1password extension was causing some kind of keydown collision. 1password X on chrome to be more specific.

**Comment by jossmac** [comment]
@alexsasharegan thanks for the heads up!

@guptar8jan @emilyyount are you using 1password?

**Comment by emilyyount** [comment]
Yes, I also use 1password.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
