### ISSUE TITLE
Disabling client side filtering in Creatable creates multiple promptTextCreator options on MouseOver/OptionFocus

### ISSUE THREAD

**Issue by jnachtigall** [JedWatson/react-select#2313]
When doing a `Creatable` or `AsyncCreatable` and disabling client side rendering with
```js
// Disable client side filtering by react-select because do it ourselves
filterOptions={(options, filter, currentValues) => {
  return options;
}}
```

See this image here:

![react-select-placeholders](https://user-images.githubusercontent.com/3307404/35148421-5b9c6cc0-fd12-11e7-9b40-dce36b765353.gif)

then on Hovering the options with mouse or keyboard arrow keys, then the `promptTextCreator` placeholder option is added multiple times.

See this https://plnkr.co/edit/4ATHhvxtKTAkkoZE4anW?p=preview in order to reproduce and for a workaround which I found to be filtering out the placeholder here. 
```js
filterOptions={(options, filter, currentValues) => {
  const res = options.filter(
    opt => opt.className !== 'Select-create-option-placeholder'
  );
  return res;
}}
```
But I really think this is exactly the bug, that the placeholder creatable option is passed to `filterOptions`. After filtering it out, then it still shows but only once.

I tried looking into the source of react-select in order to fix and submit a PR, but could not find the source of this bug.

**Comment by Chopinsky** [comment]
This is order, because the call to `isOptionUnique` should have captured the duplicate placeholders and prevented this from happening:
https://github.com/JedWatson/react-select/blob/99acc31346acacaee23cefecd2ab9b13e3d672bb/src/Creatable.js#L70

**Comment by ger86** [comment]
Same issue here. Any solution besides the workaround?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
