### ISSUE TITLE
Access refs inside Select (eg: this.menuContainer)

### ISSUE THREAD

**Issue by mattJaymes** [JedWatson/react-select#2315]
Feature request: access refs inside of Select.

@JedWatson Looking at the source code I can see refs (this.menuContainer, this.menu) throughout. I want to position the dropdown menu relative to text as it is typed into the input and need to use .getboundingclientrec(). Am I just missing something and it's possible to get access to the refs inside Select?

Awesome library! Thanks for all of your work.

**Comment by palashkaria** [comment]
As a workaround for now, I am using 

<Select ref={ref} /> and then using the selectRef
`selectRef.select.select.menuContainerRef` (or any other refs stored in `this`

**Comment by palashkaria** [comment]
As a workaround for now, I am using 

<Select ref={ref} /> and then using the selectRef, I do:


`selectRef.select.select.menuContainerRef` (or any other refs stored in `this`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by Joao611** [comment]
This is relevant to me. I want to scroll to the menu opened by a Select when it's out of view, and I could use a ref to do this. I could not find a way to get a ref, even when replacing the Menu component to use a forward ref.

There's a ``selectRef.current.select.menuListRef``, but it returns ``null``.

**Comment by ebonow** [comment]
Greetings @Joao611 ,

`menuListRef` returns null at the time of `onMenuOpen` which is a known issue that is logged here. https://github.com/JedWatson/react-select/issues/4243

One way to do this is to apply a setTimeout of 1. I have a quick sandbox example here of scrolling the `focusedOptionRef` to the top of the menu, but same can be done to access the `menuListRef` which can then be used to access its parentNode
https://codesandbox.io/s/react-select-scroll-onmenuopen-8ozk1

In regards to the select reference, it depends on the type of Select
**Select** = selectRef.current.select
**AsyncSelect** = selectRef.current.select.select
**CreatableSelect** = selectRef.current.select.select
**AsyncCreatableSelect** = selectRef.current.select.select

Finally in regards to your update, targeting the menu class like that will cause you issues as it is dynamically generated by Emotion. You can use `classNamePrefix` to create more reliable classNames 
In your example, with `classNamePrefix = 'react-select'`, the querySelector can be `#unique-select-id .react-select__menu`
