### ISSUE TITLE
Multiselect Select Box Expanding on multiple selection

### ISSUE THREAD

**Issue by vnallamhawk** [JedWatson/react-select#2318]
Hi Team,

I have used multiselect dropdowns in one of my form pages. 
When multiple values are selected in the screen, the box is expanding and moving the form button further down the page as shown in the screenshot. Is there a way to prevent this and make it to display in single line. For e.g. using custom text like 2 items selected, 3 items selected etc or anyother workaround. Please help on this issue. It has taken much of my time.
![react-selectissue](https://user-images.githubusercontent.com/16745172/35210857-1a4a53b2-ff11-11e7-980d-5921c781981b.png)

**Comment by spacecowboyian** [comment]
I'd love to see what you've done. I need a fix presently.

**Comment by mdmusaib** [comment]
could you forward me your fixes, so that I can handle it

**Comment by bladey** [comment]
Hi @vnallamhawk, if you could provide your solution that would be great!

For now I'm closing the issue until we get a response.
