### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by dcousens** [JedWatson/react-select#232]
Includes:

- #230
- #225
- #223 - adds support for customizing less (feature added)
- #215 - adds case-insensitive search (feature added)
- #213
- #212
- #205
- #210 - patch (@JedWatson, you still need to verify this)
- #206
- #204
- #209 - Fixes #201
- #193 
- #230 
- #151 - adds custom tags/tag creation

As shown above,  this would represent a minor version bump.
That would be `0.5.0` or `0.4.10`?

There does not appear to be any breaking changes.

**Comment by dcousens** [comment]
Please wait on https://github.com/JedWatson/react-select/pull/197 to be merged before publish.

**Comment by iam4x** [comment]
I think that a minor should change the last digit, so go for `0.4.10` ?

**Comment by brianreavis** [comment]
If we're following semver, `0.5.0` is the way to go. 
> Given a version number MAJOR.MINOR.PATCH, increment the:
> "MINOR version when you add functionality in a backwards-compatible manner"

**Comment by iam4x** [comment]
@brianreavis Thank's for the information :+1:

**Comment by JedWatson** [comment]
I'm going to release anyway despite #197 not being ready. There's too many other improvements and fixes that I want to publish. Let's try and wrap `onAdd`/`onCreate` etc soon and it can be published in a subsequent version. I don't think it's going to cause an issue for anyone if we release without that for now.

**Comment by JedWatson** [comment]
`0.5.0` is in the wild, going to close this now.
