### ISSUE TITLE
onChange does not fire when options change

### ISSUE THREAD

**Issue by z-vr** [JedWatson/react-select#2327]
### Thanks for using react-select!

I feel like when options change, the value should change to `null`.

https://plnkr.co/edit/iLKXF8GI3nKA1fFAkBTA?p=preview

Thank you.

**Comment by Alonmeytal** [comment]
+1

**Comment by azulkipli** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
