### ISSUE TITLE
Click Event is not triggered on select parent node

### ISSUE THREAD

**Issue by bibobibo** [JedWatson/react-select#2330]
If the react-select component is not focused, and you bind a click event on react-select parent component, when you click the react-select component, the parent click event will not be triggered.

Imagine you have one drop-down component which is wrapped by clickOutside, when its status is open, and one outside click event will change its status to close. In this case, if you click react-select component, the drop-down component can't be closed automatically.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
