### ISSUE TITLE
Async cache is empty

### ISSUE THREAD

**Issue by drakoniprincessa** [JedWatson/react-select#2331]
It was a problem to create the same environment in plunker. So in plunker example it works fine.
https://plnkr.co/edit/kGXvEPJHzrSRlzKdTO1e?p=preview

In my project (react 16.2.0 react-select 1.2.1) 
Async component returns nothing for cached options (after first loadOptions). With option cache={false} it works fine. But it is still a bug.

**Comment by sancau** [comment]
The exact same thing for me. Also used cache={false} as a workaround but it feels wrong.
react: 15.6.1
react-select: 1.2.1

**Comment by frankie-ug** [comment]
Has anyone been able to fix this? Getting the same error
react: 16.2.0
react-select: 1.2.1

**Comment by geraintdong** [comment]
I have just the same error
react: 16.7
react-select: 1.3

**Comment by flexdinesh** [comment]
Hey @drakoniprincessa [v1 of react-select is no longer maintained](https://github.com/JedWatson/react-select/pull/3786). 

We recommend maintaining your own v1 fork if you want to address `v1` issues. We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest versions.

We highly recommend [upgrading from v1 to v2](https://react-select.com/upgrade-guide). Chances are this issue might already be fixed or non-existent in v2.

I'm closing this issue/PR now. Feel free add your thoughts in #3981 and reference this issue/PR if needed.
