### ISSUE TITLE
No Styles

### ISSUE THREAD

**Issue by alexcroox** [JedWatson/react-select#2333]
Started using this lib today

```
import Select from 'react-select'
import 'react-select/dist/react-select.css'

<Select
  name="project"
  value={form.project}
  onChange={compose(onChange('project'), getValue)}
  options={projects}
/>
```

I'm getting no styling for the select, and looking at the css injected to my header I see

```
.react-select__Select__nNX0E {
  position: relative;
}
```

And in the DOM I see rendered:

![ss](https://cl.ly/p8us/Screen%20Shot%202018-01-28%20at%2016.29.10.png)

The classnames don't match...

**Comment by alexcroox** [comment]
This is a webpack css-loader config issue on my end, apologies

**Comment by stoil** [comment]
@alexcroox Do you use babel-plugin-react-css-modules or react-css-modules in your project? If yes how did you manage to bypass the convertion of the classnames? I am struggling to fiigure this out.
