### ISSUE TITLE
The State change is not changing the value. It still displays Select.

### ISSUE THREAD

**Issue by sourabh635** [JedWatson/react-select#2334]
`<Select name="select-value" value={this.state.someValue} onChange={this.updateSomeValue.bind(this)} options={someValueList} onSelectResetsInput={true} clearable={false} searchable={true} />`
when the value it selected it doesn't update the value but the state is being changed. As it works in some components and dosen't work at other other components.

**Comment by divmgl** [comment]
We need more code to identify where the problem is. In particular, we need to know the state of `someValueList` and `this.state.someValue`.

If you want the `Select` component to update correctly **without** the `labelKey` and `valueKey` properties, your `options` will need to include a `label` and `value` property.

If you don't want to make a new object for your options, you need to include `labelKey` and a `valueKey` which represents what selected value. Your `value` must match the value in the object in order for it to display correctly.

**Comment by shammond42** [comment]
I am seeing this too. This code
```
        <Select
          name='form-field-name'
          value='two'
          onChange={this.handleSelectChange}
          options={[
            { value: 'one', label: 'One' },
            { value: 'two', label: 'Two' },
          ]}
        />
```
 Renders like this (Ignore the drive input).
<img width="840" alt="screen shot 2018-03-21 at 21 21 20" src="https://user-images.githubusercontent.com/12108/37745899-d79958e0-2d4d-11e8-9029-49e194632d11.png">


However, this code seems to work.

```
      <Select
          name='form-field-name'
          value={{value: 'one', label: 'One'}}
          onChange={this.handleSelectChange}
          options={[
            { value: 'one', label: 'One' },
            { value: 'two', label: 'Two' },
          ]}
        />
```

<img width="851" alt="screen shot 2018-03-21 at 21 19 22" src="https://user-images.githubusercontent.com/12108/37745842-903d46aa-2d4d-11e8-912c-a7f2aaf5ffc1.png">

**Comment by sourabh635** [comment]
@divmgl Thanks for the suggestion i will test it.

**Comment by jessecano** [comment]
> 
> 
> I am seeing this too. This code
> 
> ```
>         <Select
>           name='form-field-name'
>           value='two'
>           onChange={this.handleSelectChange}
>           options={[
>             { value: 'one', label: 'One' },
>             { value: 'two', label: 'Two' },
>           ]}
>         />
> ```
> 
> Renders like this (Ignore the drive input).
> <img alt="screen shot 2018-03-21 at 21 21 20" width="840" src="https://user-images.githubusercontent.com/12108/37745899-d79958e0-2d4d-11e8-9029-49e194632d11.png">
> 
> However, this code seems to work.
> 
> ```
>       <Select
>           name='form-field-name'
>           value={{value: 'one', label: 'One'}}
>           onChange={this.handleSelectChange}
>           options={[
>             { value: 'one', label: 'One' },
>             { value: 'two', label: 'Two' },
>           ]}
>         />
> ```
> 
> <img alt="screen shot 2018-03-21 at 21 19 22" width="851" src="https://user-images.githubusercontent.com/12108/37745842-903d46aa-2d4d-11e8-912c-a7f2aaf5ffc1.png">

@shammond42 This worked awesomely!!!
