### ISSUE TITLE
Clear icon does not go away after clearing when using `resetValue`

### ISSUE THREAD

**Issue by smrq** [JedWatson/react-select#2338]
Repro: https://plnkr.co/edit/1xmeaW9ni5e9Fiu1oNEn?p=preview

Note in the repro how the clear icon is present from the beginning (even though it starts out at the default value).  After selecting another option and then clearing, the clear icon is still present.  Clicking the clear icon when already at the default has no effect, as you might expect.

Digging into the code, it looks like it just checks for whether the value is non-null (for a single select) when deciding whether to render the clear icon.  It should probably check whether the value is equivalent to the resetValue.

**Comment by flexdinesh** [comment]
Hey @smrq [v1 of react-select is no longer maintained](https://github.com/JedWatson/react-select/pull/3786). 

We recommend maintaining your own v1 fork if you want to address `v1` issues. We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest versions.

We highly recommend [upgrading from v1 to v2](https://react-select.com/upgrade-guide). Chances are this issue might already be fixed or non-existent in v2.

I'm closing this issue/PR now. Feel free add your thoughts in #3981 and reference this issue/PR if needed.
