### ISSUE TITLE
Missing CSS

### ISSUE THREAD

**Issue by nyamba** [JedWatson/react-select#2347]
it looks css file is missing! 
![missing css](https://user-images.githubusercontent.com/309936/35720871-80f933f4-082a-11e8-917e-097fe57a92a0.png)

**Comment by JedWatson** [comment]
Sorry, I mis-tagged the last `alpha` release 😞 

All fixed up now, I'll be more careful with that for the next release.

I'd recommend depending specifically on the version you're using though, or you'll be automatically upgraded to the next version when it's released (and it will contain breaking changes)
