### ISSUE TITLE
Events for add/remove multiple values

### ISSUE THREAD

**Issue by bluejamesbond** [JedWatson/react-select#235]
Are there any events for add/remove multiple values as opposed to change in values?

**Comment by brianreavis** [comment]
An `onAdd` property is being tracked here: https://github.com/JedWatson/react-select/pull/197. It'd make sense to add an `onRemove` to go along with it, though. I'm going to close this and a note there.

**Comment by brianreavis** [comment]
Okay, my bad – turns out that pull request was for something else. Re-opening!

**Comment by bluejamesbond** [comment]
I have added the feature here: https://github.com/bluejamesbond/react-select  
It is fairly straightforward so you can just add them directly to the main lib if you feel that is fit.

**Comment by dcousens** [comment]
@bluejamesbond want to make a PR?
