### ISSUE TITLE
name prop is not passed to hidden input

### ISSUE THREAD

**Issue by smiile** [JedWatson/react-select#2350]
The name prop doesn't work as documented. It's not on the hidden input nor elsewhere in the DOM hierarchy.

**Comment by JedWatson** [comment]
@smiile which version are you using?

**Comment by smiile** [comment]
@JedWatson I'm using 1.2.1

**Comment by MobiusHorizons** [comment]
I see the same issue on 1.2.1

**Comment by MobiusHorizons** [comment]
@smiile I was able to work-arround it by passing `inputProps={{name : "form element name"}}`

**Comment by smiile** [comment]
Thanks, it works!

**Comment by MobiusHorizons** [comment]
@JedWatson i did notice that while it does update the name property on the input, the input does not contain the selected value, and therefore the validity is wrong (ie if you set `required` and select an option, it still thinks nothnig is selected)
