### ISSUE TITLE
Force drop-down menu to open

### ISSUE THREAD

**Issue by Lefteris008** [JedWatson/react-select#2358]
Hello,

I followed [the advice Jed gave](https://github.com/JedWatson/react-select/issues/1989) regarding force opening the drop-down menu but I couldn't figure how to do it. I have opened [a thread on Stackoverflow](https://stackoverflow.com/questions/48672167/react-select-open-select-on-selected-value-click-multiselect), but so far I haven't received any answers.

What's the procedure of calling `focus()` function? I have tried referencing the component via `ref` attribute but I had no luck in succeeding.

**Comment by abdulrahman-khankan** [comment]
If it's for debug purposes, I managed to force it by changing the internal state.isOpen through the React Chrome plugin

In my case I wanted to tweak the CSS and needed to focus on the container (`Select-menu-outer`) to change its CSS.

![react-select-state](https://user-images.githubusercontent.com/7988466/39925026-60111326-552a-11e8-80ee-1fcba003ec87.png)

**Comment by skylarmb** [comment]
for future googlers: you can also use `defaultMenuIsOpen={true}`
