### ISSUE TITLE
When select data it shows value

### ISSUE THREAD

**Issue by omerfaruk** [JedWatson/react-select#237]
Hi,
When i select data in my select it show value of selected data.If i select second time the same item it shows label.
For Example:
Data:[{value:1,label:A},{value:2,label:B},{value:3,label:C}]
if i select A it shows 1 selected in select list as label.If i select A again i can see A as label.

```
         <Select onChange={this.handleChange}
           ref={this.props.id}
           value={this.state.selectedValue}
           options={ops}
               noResultsText ='Sonuç bulunamadı'
               clearValueText="Temizle"
           />
             handleChange:function(newValue){
           console.log(newValue)
              this.setState({"selectedValue": newValue || null});
           },
              getExternalData:function(input, callback){
              var that =this;
              console.log("It worked")
                var optionItems =[{}];

    $.ajax({
        type: "POST",
        url: this.props.dataUrl,
        data:  this.props.ajaxData ,
        success: function (resultData) {
            resultData.map(function (option) {
                optionItems = optionItems.concat({'value':option[that.props.optionValue],'label':option[that.props.optionText]});
    });

            that.setState({
                result: resultData,
                veriYuklendi:true,
                optData:optionItems
            });
        }
    });
},
```

**Comment by omerfaruk** [comment]
I solved my problem i change optionItems to this
              optionItems = optionItems.concat({'value':"'"+option[that.props.optionValue]+"'",'label':option[that.props.optionText]});

my value is number when i convert it to string '3' it worked.But i think its a bug

**Comment by jeroenbourgois** [comment]
I just encountered the same behaviour. @JedWatson are you accepting PR? Otherwise I might look into it.

**Comment by jketcham** [comment]
Also experienced this.  What would be nice is if Select looked for the current value in the options prop and displayed the corresponding label instead of the value.

**Comment by nuragic** [comment]
Hi, I just installed react-select from npm and I'm experiencing this bug to... any plan to fix it? Thanks!

**Comment by jaraquistain** [comment]
I just ran into this too. Luckily I tried switching to string values and that seemed to work. It'd be great to see a fix for this so other's stop running into it. Doing something like `[{value: 1, label: "January"},{value: 2, label: "February"}...]` is probably pretty common

**Comment by bruderstein** [comment]
This is solved by #362

**Comment by JedWatson** [comment]
Merged! Thanks for the fix @bruderstein, you're smashing it.

**Comment by jaraquistain** [comment]
Thanks guys!
