### ISSUE TITLE
Strange white box rendered when searchable set to false

### ISSUE THREAD

**Issue by vincentwoo** [JedWatson/react-select#2370]
When running react-select in nonsearchable mode and adding a background color to the select, focusing the select causes a white box to be displayed. Here's a minimal reproduction case:

https://plnkr.co/edit/KV06xl2x1an1xFHg4RMI?p=preview

I think this has something to do with the input DOM structure in searchable/nonsearchable mode. When searchable, Select-input has an input child, when nonsearchable, these elements are the same element.

**Comment by Antamokhin** [comment]
To solve this strange white box i use custom inputRenderer, which just return "null". Then the box will not be rendering.

But there is one more problem. When the inputRenderer method  return "null" or something like clear <div/>, the ability to hide options-menu by clicking outside the component is lost. :( Menu can be hided only by click on option or value rows. 


Sorry for my very very bad english :(

**Comment by fulbert81** [comment]
I used a clear "div" to solve the white box, however I encountered another problem, focus doesn't work with custom inputRenderer. 

Can we have the div with class Select-input removed when searchable is false, or let it have height zero or is there another way to remove the white box.
