### ISSUE TITLE
Default behavior for Creatable not working, react-select 1.2.1, React 16.2

### ISSUE THREAD

**Issue by dan-ator** [JedWatson/react-select#2371]
In case this is a bug and not just my own issues:
https://stackoverflow.com/questions/48769854/react-select-creatable-component-not-acting-in-default-manner
```
function optionsForSelect(field) {
  return field
    .values
    .map((fieldOption) => {
      return {value: fieldOption, label: fieldOption};
    });
}

function PatientSelectInput({field, options, value, onChange, disabled}) {
  const className = field.id + '-select';
  return (
    <label className={cx('input-label', className)}>
      <div className="label-text">{field.displayName}</div>
      <Creatable
        value={value}
        onChange={(selectedValue) => onChange(selectedValue ? selectedValue.value : null)}
        disabled={disabled}
        onBlurResetsInput={false}
        onCloseResetsInput={false}
        options={options} />
    </label>
  );
}
```
It is a functional component. When it renders, I can type in a new option but when I hit tab or enter or click on the automatically generated "Create Option..." the newly created option disappears. I just want the default behavior.

**Comment by lukaszgolder** [comment]
You have to merge options with created values as it was pointed out in this comment:
https://github.com/JedWatson/react-select/issues/1390#issuecomment-356063911

I am keeping customOption in the state and changing them using `onNewOptionClick` callback

**Comment by jossmac** [comment]
@lukaszgolder thank you for providing an answer
