### ISSUE TITLE
Some suggestions and feature requests based on internal implementation / testing.

### ISSUE THREAD

**Issue by treshugart** [JedWatson/react-select#2374]
I'm consolidating some feedback form working with react-select on an internal calendar component. @JedWatson and @jossmac are aware of some of these, but I wanted to put them all down in one place.

> Option to disable the auto-width of the Menu component.

When replacing the menu component, the dropdown as a whole contains styling and becomes a full width container. When creating custom menus for things like a calendar, that may not work well stretched, this can look funny. You could override the styles to make it transparent, but then it'd be odd if the menu is clicked and the dropdown doesn't close.

The workaround I found here is to replace the entire menu with a custom one.

A possibly more elegant solution would be to have an `<Select autoWidth />` option, or something that tells the select to do the width calculation. Maybe a better solution to avoid bloating the API would be to simply pass down the width as a prop to the styles function.

> Fire an event when the clear button is clicked.

This is necessary when you're controlling the value as your value will prevent the clear button from doing anything. We need to hook into this and be able to manually clear our controlled value.

> A way to control the open state of the dropdown menu.

This is necessary when you're doing some fancier stuff, like with a datepicker. I want to close the menu when a date is selected, or when some internal state meets certain criteria.

The workaround here is to conditionally render the menu component based on internal state.

> The input width is forced to match dropdown.

This breaks `flex-basis: 0` when putting selects in a flex parent. This doesn't seem to be a problem if you replace the menu entirely.

**Comment by Zertz** [comment]
> A way to control the open state of the dropdown menu.

This would be awesome, the workaround is slightly awkward compared to, say, exposing the `menuIsOpen` prop.

**Comment by jossmac** [comment]
@treshugart I think we've addressed all of these concerns. Would be great if you could confirm:

> Option to disable the auto-width of the Menu component.

**Solution**: use the `styles` property:

```jsx
<Select styles={{
  menu: (css) => ({ ...css, width: 300 })
}} />
```

> Fire an event when the clear button is clicked.

**Solution**: the consumer's `onChange` fn is called with meta `{ action: 'clear' }`

> A way to control the open state of the dropdown menu.

**Solution**: the default export is still controlled, but there's now a named export `SelectBase`, which is uncontrolled.

> The input width is forced to match dropdown.

**Solution**: use the `styles` property:

```jsx
<Select styles={{
  control: (css) => ({ ...css, width: 100 })
}} />
```

* * *

Closing for now, please let me know if you need it re-opened.
