### ISSUE TITLE
Selected value is not rendered when using Select.Async with Custom Component

### ISSUE THREAD

**Issue by sjsingh85** [JedWatson/react-select#2380]
Bug

Sample provided by MaterialUI Team integrating the react-select with static values works fine. But when we use Select.Async nothing is rendered in the input field.

The original (working) test with "Select" is at https://codesandbox.io/s/py61x4kz3j 

The code with issue using "Select.Async" is here: https://codesandbox.io/s/rmqooy0z8o

In the valueComponent - the children and value props are coming as undefined/null.

I have been using react-select from past 2-3 days only hence don't know much about it but based on initial analysis - it looks like that the [shouldShowValue](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L836) in the renderValue function returns false because inputValue in the state is still having the typed characters. When I manually set inputValue to empty, the selected value shows up.

**Comment by sjsingh85** [comment]
Figured out the issue - the [expandValue ](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L61) function was sending no value as it was expecting an array object to find value in options. Setting simpleValue: false makes it return the actual value from the object.

**Comment by vjustov** [comment]
Im commenting here for prosperity, i was having a very similar problem. But my solution came with setting `onSelectResetsInput: false`. also while inspecting and debugging `shouldShowValue`
