### ISSUE TITLE
Prop to add search bar in dropdown

### ISSUE THREAD

**Issue by dmk255** [JedWatson/react-select#2393]
Good afternoon!

I love the implementation of [react-select](https://github.com/JedWatson/react-select) and am looking forward to using it in my project. 

Is there a way to add a search bar (a la [react-widgets - DropdownList](https://jquense.github.io/react-widgets/api/DropdownList/)) to the dropdown? In testing with our designer and users we've found that users do not always realize the dropdown is searchable and appeared to overwhelmingly prefer the DropwdownList widget due to that one feature.

That said, I love the react-select's customizability and feature set and hope to be able to use it.

Demo Gif:

![dropdown_with_search](https://user-images.githubusercontent.com/6778796/36546082-713a7cbe-17b8-11e8-8315-adc155e834ce.gif)

Preferable Interaction:
- Add a boolean prop: `searchBar` which will add a search bar as the first "item" in the drop down.
- On click of the dropdown the search bar is set to active so the user can immediately type.

I'm happy to answer any questions!

> Note, I also made an [SO question](https://stackoverflow.com/q/48930622/3735630) about this

**Comment by jossmac** [comment]
@dmk255 thank you for creating a StackOverflow question, we appreciate it.

At the moment we're hard at work on v2, where this will be easy to implement.

More info and docs http://bit.ly/react-select-v2

**Comment by neha-ot** [comment]
Hi @jossmac, I know this issue is closed. But i was trying to find this feature in V2 and couldn't find it. The link mentioned above is broken too. Can you please help me get to the documentation for the above requirement?
Thank you.

**Comment by Rall3n** [comment]
@neha-ot Documentation is linked as always on the project home or reachable through https://react-select.com. You should look for the [Components framework](https://react-select.com/components) which would suit your needs.

**Comment by jossmac** [comment]
Thanks @Rall3n for answering

@neha-ot sounds like a "popout" style select. After you've looked through the component API documentation, checkout the [advanced#experimental](https://react-select.com/advanced#experimental) section.
