### ISSUE TITLE
How to get permission to create a PR?

### ISSUE THREAD

**Issue by jiangweiliu-aa** [JedWatson/react-select#2406]
After reading contributing guideline, i haven't found how to get permission to create a PR.

**Comment by hollandmatt** [comment]
You don't need permissions to create a PR - anyone should be able to do it, but it might be polite to have a discussion with the maintainers via Issues beforehand 😄

**Comment by jiangweiliu-aa** [comment]
Thanks for your reply! Yet, looks like the latest reply from maintainer in issue is 24 days ago.  I'm wondering if I can give some contribution.

**Comment by jacktrades** [comment]
@jiangweiliu-aa this doesn't directly answer your question, but you might want to check out the v2 PR #2289 for status and links to more info.  There seems to be a lot of recent development activity there.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
