### ISSUE TITLE
Viewport not autoscrolling on input focus - iOS Safari

### ISSUE THREAD

**Issue by m4ttsch** [JedWatson/react-select#2419]
I have two side by side inputs. One is a standard text input, and the other is a react-select input. On iOS Safari, when I focus on the text input, the viewport adjusts such that the field can still be seen when the keyboard is extended. For the react-select input, this is not the case; the keyboard blocks the input. 

![img_0443](https://user-images.githubusercontent.com/19544466/37013578-bd3f9f36-20c8-11e8-9799-8233bc309341.jpeg)
![img_0444](https://user-images.githubusercontent.com/19544466/37013584-be49d018-20c8-11e8-923b-ca85795c4b97.jpeg)

Am I missing a prop here, or is this a legitimate bug? Thanks!

**Comment by jossmac** [comment]
@m4ttsch the behavior is as expected using the default select, something else must be happening.
