### ISSUE TITLE
v2 Calendar Picker Example

### ISSUE THREAD

**Issue by s-dezign** [JedWatson/react-select#2421]
Hi, sorry for bothering you. 
I'm very interesting in testing Calendar Picker as in your [v2 Examples](https://deploy-preview-2289--react-select.netlify.com/home) . But the link is broken. Is it possible restore the file with that example, please? 

Thanks very much!

**Comment by ajaymathur** [comment]
I am see it under experimental section:

Direct link: https://deploy-preview-2289--react-select.netlify.com/home#experimental

**Comment by kshreve** [comment]
@ajaymathur - Calendar no longer under experimental. Do you know where else I could see it?

**Comment by gwyneplaine** [comment]
@s-dezign  and @kshreve  its now under the advanced section in the docs 
https://deploy-preview-2289--react-select.netlify.com/advanced#experimental
