### ISSUE TITLE
Options are blank when change in Async mode

### ISSUE THREAD

**Issue by jimerino** [JedWatson/react-select#2427]
I'm using the Async mode to filter a HUGE list of objects (I don't want to use another component as VirtualSelect and depend on another component)

I have a huge list of {id:... , name:...} elements

var hugeList = [{id: ..., name: ...}, ...]

I use the async callback to filter over the hugeList (and only get elements when 3 letters has been written in the search text input):

getSelectOptions(input, callback) {
        var inputlower = input.toLowerCase();
        var data = (input.length > 3 ? hugeList.filter((item) => { return item.name.toLowerCase().indexOf(inputlower) != -1 }) : null);
        var dataSelect = (data == null ? null : data.map((element) => { return { value: element.id, label: element.nombre } }));
        var dataCallback = {
            options: dataSelect,
            complete: true
        };
        callback(null, dataCallback);
    }

    render() {
            return <Select.Async
                multi={false} value={this.state.value} valueKey="github" labelKey="name"
                loadOptions={(input, callback) => { this. getSelectOptions(input, callback) }}
                filterOptions={(options, filter, currentValues) => {
                    // Do no filtering, just return all options
                    return options;
                }}
                autoload={false}
                onSelectResetsInput={false}
             />

This works and filter the list but appears all filtered values in blank. Only when add a customRender, the options are shown.

optionRenderer={(option) => {return option.label;}}

**Comment by ajaymathur** [comment]
@jimerino Can you please create a reproducible example at codesandbox. It would really help in resolving this ( or suggesting the right approach )

**Comment by jimerino** [comment]
Sure,

Here you are an example:

https://jsfiddle.net/sfnnfdL8/17/

You can see 2 Async.Select.

The first has a basic optionRenderer: optionRenderer={(option) => { return option.label;}}
The second doesn't have any optionRenderer and all items appears in blank

Another issue is the selected value doesn't appears (but is selected because the react state is modified and the selectedOption get a value).

Without these issues I can obtain a fast Select for large options without using any external library (as react-virtualized-select)

**Comment by jossmac** [comment]
@jimerino it sounds like there's a few solutions available.

We're focusing on v2 right now -- please comment if this is still a concern, and needs to be re-opened.
