### ISSUE TITLE
CSS behavior

### ISSUE THREAD

**Issue by ItsTarik** [JedWatson/react-select#2428]
in multi select mode, if the tag is long enough, the css breaks up : 
![image](https://user-images.githubusercontent.com/10453938/37248062-dbd9fb50-24c7-11e8-96cb-d18e91f6436d.png)
is that normal behavior ?

**Comment by ajaymathur** [comment]
We can use custom renderer for these scenarios, here is a simple example with custom renderer for multi-select : https://codesandbox.io/s/3xnwqxmo9p

![image](https://user-images.githubusercontent.com/9667784/37457908-6fa2a0d0-2897-11e8-8921-7c124e0fc2d0.png)

**Comment by ItsTarik** [comment]
yes that's if we want to control the render behavior, but the default behavior crashes the css, it's a rare use case but i think it should be fixed.

**Comment by ajaymathur** [comment]
Seems there is a PR is for this - https://github.com/JedWatson/react-select/pull/2442

**Comment by ItsTarik** [comment]
@ajaymathur yes that's it.
