### ISSUE TITLE
Use sass partials

### ISSUE THREAD

**Issue by guetar** [JedWatson/react-select#2434]
I am using create-react-app with SASS Preprocessor as explained in https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc

I don't want to eject.

However when I run yarn build-css or yarn watch-css, I get Errors like: "Error: It's not clear which file to import for '@import \"spinner\"'. Canditates: spiner.scss spinner.css"

This is because node-sass build also compiles sass-files in node_modules.

![react-select-scss](https://user-images.githubusercontent.com/2599193/37336532-f6aec4a6-26b1-11e8-926c-d1bb540d1431.PNG)

Excluding node_modules from node-sass build is not possible as explained in https://github.com/sass/node-sass/issues/1759

So the simplest solution would be to use sass-partials as I am now (I copied all files in scss/ and prefixed them with _)

Why not use them in react-select natively? So it would be possible to include them instead of copying, because thy do not get compiled into seperate files...

**Comment by jossmac** [comment]
@guetar sounds like a good idea, though right now we're focusing on v2.

More info and docs http://bit.ly/react-select-v2
