### ISSUE TITLE
Scroll on touch screen on top of a select will open it.

### ISSUE THREAD

**Issue by YoYuUm** [JedWatson/react-select#244]
If you scroll on touch screen on top of a select, this will open itself when the scroll ends. 

I would say the expected behaviour is that this happens only on click.

**Comment by jljorgenson18** [comment]
+1 , this behavior is fairly annoying on mobile

**Comment by azaharakis** [comment]
I've had a play with this here:
https://github.com/azaharakis/react-select/commit/b4a04c750b53cc8edacd22cc5e35cdd4fc63712a
The commit message states where i'm at
