### ISSUE TITLE
Custom optionComponent per option

### ISSUE THREAD

**Issue by franciscolourenco** [JedWatson/react-select#2441]
# Are you making a feature request?

*   What's your use case? 

Different options having different / enhanced content and complex formating.

*   What interface do you have in mind?

```js
options = [
	{value: 'a', optionComponent: A},
	{value: 'b', optionComponent: B}
]
```

**Comment by jossmac** [comment]
@franciscolourenco @webrgp you can actually do this in v1 by forking your component based on the props provided to your `optionComponent`, something like:

```jsx
const Option = (props) => {
  return props.someCondition ? <OptionA {...props} /> : <OptionB {...props} />
}
```
