### ISSUE TITLE
[V2] when having multiple value in multi select it create multiple input with same name

### ISSUE THREAD

**Issue by ajaymathur** [JedWatson/react-select#2443]
**Given** - delimeter is not passed.

Related code:

https://github.com/JedWatson/react-select/blob/v2/src/Select.js#L1263

Is this expected behaviour? If not I would love to help get it fixed. 🙂

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
