### ISSUE TITLE
[BUG CRITICAL] Refused to apply style from 'https://unpkg.com/react-select@2.0.0-alpha.8/dist/react-select.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by Vadorequest** [JedWatson/react-select#2452]
Something has changed on https://unpkg.com/react-select@2.0.0-alpha.8/dist/react-select.css whihc is the official CSS way of rendering react-select. Basically, they deleted the file, or made some change that makes it unavailable right now.

All applications based on react-select, which are using this css file from https://unpkg.com/ are failing right now.

This happened like 30mn ago.

Workarounds while waiting for an official solution from react-select authors/contributors:

- Use my personal CDN: https://storage.googleapis.com/studylink-loan-advisor/react-select-v1.2.1.min.css *(temporary solution, don't rely on this for long-term solution, only use this if you are in a hurry)* see https://github.com/JedWatson/react-select/issues/2452#issuecomment-374762320
- Local import `import 'react-select/dist/react-select.css';` (or alike, using bower, etc.)
- Copy the official CSS file and host it on your own CDN https://raw.githubusercontent.com/JedWatson/react-select/v1.2.1/dist/react-select.min.css

**Comment by tsnieman** [comment]
I'll throw a +1 in; I went to use this package and found that `node_modules/react-select/dist/react-select.css` wasn't present at all. I will also note that going back to alpha 7 via `npm i -S react-select@v2.0.0-alpha.7` does not make this css file show up.

Related issues?: #1592

**Comment by Vadorequest** [comment]
I tried all alpha version and none work, I have no idea how unpckg works and who has access to those files, neither why they got deleted, but the fastest workaround I can think of is to use another CDN.

If someone has a version of the CSS file available somewhere it'd would be nice, I just looked into the react-select repo and couldn't find the dist folder for the alpha versions either. I guess we need to recompile it and put it on another CDN (or fix the existing one)
https://github.com/JedWatson/react-select/tree/v2.0.0-alpha.8/dist

Either way, I'll move it to my own CDN, this just can't happen in production, it's way too sensitive. I wonder how many people have been affected.

**Comment by lgoudriaan** [comment]
I have this issue too 😭

**Comment by crimclark** [comment]
as a workaround you can just pull the file directly from the repo and host it yourself for now - https://raw.githubusercontent.com/JedWatson/react-select/v1.2.1/dist/react-select.min.css

**Comment by Vadorequest** [comment]
Beware the version though, the link given by @crimclark is for 1.2.1, not 2.0.0-alpha.8

**Comment by lgoudriaan** [comment]
If you have installed this via a package manager you can get the file from your dist folder locally :)

**Comment by Vadorequest** [comment]
It's not that simple @lgoudriaan. I just checked and I installed the react-select@1.2.1 as node package, but I was using the 2.0.0-alpha for the css, I don't know why really.

I'm gonna give it a try with the 1.2.1 and see how it goes.

**Comment by Vadorequest** [comment]
I tried with the https://raw.githubusercontent.com/JedWatson/react-select/v1.2.1/dist/react-select.min.css but it didn't work, I got the file, but the MIME was wrong and style was broken as well.

If you need a quick fix for 1.2.1, here is my own CDN link:
https://storage.googleapis.com/studylink-loan-advisor/react-select-v1.2.1.min.css

Note that I don't know how much time it'll stay there, probably a few weeks/months at least, use it if you need a quick fix, but better switch over a more official/stable link once this issue is resolved.

I have no idea why my app tried to load the 2.0.0-alpha8 version, and I don't know if I was using the 1.2.1 or the 2.0.0-alpha 8 prior to the bug (because the link https://unpkg.com/react-select/dist/react-select.css seems to redirect to a dynamic page), but **it works** with 1.2.1 as it did before.

**Comment by tvsudhir3** [comment]
We may import CSS from library itself.
```javascript
import 'react-select/dist/react-select.css';
```

Worked for me.

**Comment by zhaoyi0113** [comment]
Same here, there is no css file in the dist directory

**Comment by jgcmarins** [comment]
@tvsudhir3 where did you used this import?
I've tried import and got this:
```
ERROR in ./node_modules/react-select/dist/react-select.css
Module parse failed: Unexpected token (8:0)
You may need an appropriate loader to handle this file type.
|  * MIT License: https://github.com/JedWatson/react-select
| */
| .Select {
|   position: relative;
| }
```

**Comment by Vadorequest** [comment]
@jgcmarins You didn't configure your webpack with a plugin that loads CSS files, that's why. 

>You may need an appropriate loader to handle this file type.

I can't guide you through this, though.

**Comment by tvsudhir3** [comment]
@jgcmarins Webpack config (in this context, if it helps):
```
module: {
  rules: [
    ...
    {
      test: /\.css\/,
      use: [{ loader: 'style-loader'}, { loader: 'css-loader' }],
    }
    ...
  ],
},

resolve: {
  ...
  extensions: ['.css']
  ...
}
```

**Comment by jgcmarins** [comment]
solved this adding [`css-loader`](https://github.com/webpack-contrib/css-loader) to my `webpack` config file.

**Comment by 416serg** [comment]
Still no official fix? 😢

**Comment by blb451** [comment]
Having the same issue (already resolved a temporary fix).

**Comment by Vadorequest** [comment]
@JedWatson Ping, did you notice this issue?

**Comment by JedWatson** [comment]
I'm trying to sort this out now

**Comment by Vadorequest** [comment]
@JedWatson Better change the doc so that new users take the 1.2.1 version from now on, nobody wants to do a major upgrade without being notified first. ;)

**Comment by vidurajith-darshana** [comment]
It works for me..Thanks @JedWatson
