### ISSUE TITLE
Refused to apply style from 'https://unpkg.com/react-select@2.0.0-alpha.8/dist/react-select.css'

### ISSUE THREAD

**Issue by joshualimpj** [JedWatson/react-select#2454]
hello, everything was working fine until an error from react-select causes all the styles for react-select to stop working.

CONSOLE:
Refused to apply style from 'https://unpkg.com/react-select@2.0.0-alpha.8/dist/react-select.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by joshualimpj** [comment]
@danilags Thanks buddy! Life saver <3

**Comment by jossmac** [comment]
@danilags glad you got to the bottom of this, and thank you for posting the solution 🙂
