### ISSUE TITLE
[V2] Cyress tests required - as these scenario cannot be covered in unit test

### ISSUE THREAD

**Issue by ajaymathur** [JedWatson/react-select#2469]
Props:

- **captureMenuScroll** - When the user reaches the top/bottom of the menu, prevent scroll on the scroll-parent
- **scrollMenuIntoView** - Whether the menu should be scrolled into view when it opens

@RajaBellebon @gwyneplaine : Please feel free to add or remove scenarios from this list

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
