### ISSUE TITLE
The 'Type to search...' property is not exposed in index.d.ts for ReactSelectProps

### ISSUE THREAD

**Issue by nagylzs** [JedWatson/react-select#2478]
Please add it so it can be used from typescript! Similar to: backspaceToRemoveMessage addLabelText clearValueText etc.

**Comment by nagylzs** [comment]
The same is true for "Loading..." text, when isLoading is set to true

**Comment by jossmac** [comment]
@nagylzs unfortunately we don't use TypeScript internally.

If you would like this feature, please open a PR with the necessary updates and reference this issue, thanks 🙂

**Comment by nagylzs** [comment]
I have posted this to the wrong place indeed. It went to DefinitelyTyped - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27060
