### ISSUE TITLE
React-Select Component Is Mutating Passed-In 'options' Prop

### ISSUE THREAD

**Issue by JonasMS** [JedWatson/react-select#2484]
```jsx
createNewOption () {
  const {
    isValidNewOption,
    newOptionCreator,
    onNewOptionClick,
    options = [],
  } = this.props;

  if (isValidNewOption({ label: this.inputValue })) {
    const option = newOptionCreator({ label: this.inputValue, labelKey: this.labelKey, valueKey: this.valueKey });
    const isOptionUnique = this.isOptionUnique({ option, options });

    // Don't add the same option twice.
    if (isOptionUnique) {
      if (onNewOptionClick) {
        onNewOptionClick(option);
      } else {
        options.unshift(option); // <==== mutating passed-in options =====

        this.select.selectValue(option);
      }
    }
  }
}
```

`options.unshift(option)` is mutating an object in state, which, on a re-render causes weird behavior.

The react-select component shouldn't be manipulating passed-in props, and consumers shouldn't need to create an immutable copy of props before passing them into the component, right?

* * *

Edit by @jossmac - line ref:
https://github.com/JedWatson/react-select/blob/db32763af34921aecca64e699c1eef26311a4e0f/src/Creatable.js#L36

**Comment by thienanle** [comment]
@JonasMS Yes I agree. `Creatable` is mutating the `options` prop which seems very wrong. The developer should be responsible for updating `options` when a new option is created.
