### ISSUE TITLE
[v2.0.0.alpha-8] can not open options

### ISSUE THREAD

**Issue by owcc** [JedWatson/react-select#2486]
![kapture 2018-04-03 at 14 40 56](https://user-images.githubusercontent.com/5770548/38233415-144b85ac-374d-11e8-8fae-7bd6997dc886.gif)

+ react v16.2.0
+ react-select v2.0.0.alpha-8

```js
...
<Flex full>
        <Select
                multi
                value={taskPost.getSnapshot('userId')}
                options={userList.getUserList()}
                onChange={({ value }) => { taskPost.update('userId', String(value)); }}
          />
</Flex>
...
```

it seems that `options` quickly close after it open (`menuIsOpen` state flash)?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
