### ISSUE TITLE
className does not appear to be applying to the container div, after updating to this beta8 version

### ISSUE THREAD

**Issue by daniellecloss** [JedWatson/react-select#2488]
I have a simple react select implementation, where we pass in a className, to apply custom styling.  After updating to 2 beta8, the custom classname is no longer getting passed to the container component.  I believe the problem may be here:
https://github.com/JedWatson/react-select/blob/f33d77a006efbfb91a287725a783a745fb199255/src/components/containers.js#L37

Is it possible that there is a different way to apply a custom css class to a react-select now?

**Comment by jossmac** [comment]
Hi @daniellecloss, thanks for raising this issue.

Could you tell us which version you were running when the component was behaving as expected?

**Comment by bazfer** [comment]
Having the same issue using SASS: the CSS attributes defined in the classes are not being applied to the DOM nodes even though they are tagged with the className and classNamePrefix passed as props. My workaround is to define the classes in the top level index.css and even then each attribute is requiring the '!important' tag.

**Comment by jossmac** [comment]
@bazfer could you please provide a reproduction of the issue, so we can diagnose the problem?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
