### ISSUE TITLE
New tests need Babel plugin

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#249]
@craigdallimore this may be something you can help with ...

The new tests are failing on invalid syntax because JSX and ES6+ syntax isn't being transpiled by Babel.

**Comment by craigdallimore** [comment]
Cripes, taking a look

**Comment by craigdallimore** [comment]
@JedWatson I'm very sorry about this, I'm trying to recreate the failure. I've cloned fresh, run `npm install && npm test` and had them pass. Below you'll find a link to a TravisCI example.

A few questions:

Babel is declared [here](https://github.com/JedWatson/react-select/blob/master/package.json#L17), is that not what you mean?

Is there a CI for this or somewhere I can see the failing test output?

[Here is an example of my fork tested on Travis CI](https://travis-ci.org/craigdallimore/react-select/builds/66859432), where I can see them pass on `Node 0.12` and `iojs`. The only difference between this fork and master is the presence of a `.travis.yml` file to let Travis know how to run the tests.

**Comment by JedWatson** [comment]
Aah this may be my bad - it looked like a syntax error but may be a node 0.10.x issue. Full debug output:

```
Jeds-iMac:react-select Jed$ npm run test

> react-select@0.4.9 test /Users/Jed/Development/packages/react-select
> mocha --compilers js:babel/register



  Select test

/Users/Jed/Development/packages/react-select/node_modules/jsdom/lib/jsdom.js:3
`jsdom 4.x onward only works on io.js, not Node.js™: https://github.com/tmpvar
^
    1) "before all" hook

  Value component
    2) "before all" hook


  0 passing (12ms)
  2 failing

  1) Select test "before all" hook:
     SyntaxError: Unexpected token ILLEGAL
  

  2) Value component "before all" hook:
     SyntaxError: Unexpected token ILLEGAL
  
```

I'm going to re-run on another machine with node 0.12.x now.

**Comment by craigdallimore** [comment]
Hey @JedWatson. Here is Node `0.10`, `0.11`, `0.12` and `iojs` on Travis, if it helps https://travis-ci.org/craigdallimore/react-select/builds/66872074

Possibly something is selecting the wrong version of JSDOM. You could try removing you local `node_modules` and reinstalling them?

**Comment by JedWatson** [comment]
OK so this works on my macbook, not my desktop. Must be environment-specific, I'll update some things and try to resolve it locally. Thanks for the verification, this seems safe to close.
