### ISSUE TITLE
Custom tag edit feature

### ISSUE THREAD

**Issue by jai1331** [JedWatson/react-select#2490]
I have been using react-select recent times in my application, it works perfectly but there's a use case while adding new custom tags in select and user will edit it which is a valid feature.

I really need this feature in my app, so I have started to do it on my own to edit the custom tags and somehow managed to get it like below :
![7axhz](https://user-images.githubusercontent.com/8530380/38290413-c25d9454-37f8-11e8-8ec1-916557172381.gif)

This works for a single custom tag and I need this to work for all custom tags .But I'm struck when editing second custom tag, the input field shown in both custom tags.

Code is available [here](https://stackblitz.com/edit/react-select-custom-tag-edit-new)

similar functionality available in [react-selectize](http://furqanzafar.github.io/react-selectize/#/?category=multi&example=tags)

Any help on this would be helpful. reference [stackoverflow link](https://stackoverflow.com/q/49598138/4061006)

**Comment by jossmac** [comment]
Hi @jai1331, that's really cool!

Unfortunately it's not something that belongs in core. In version 2 you can replace the `MultiValue` component with your own, making this sort of customization easier.

More info and docs http://bit.ly/react-select-v2
