### ISSUE TITLE
When use the menuRenderer keys doesn't work

### ISSUE THREAD

**Issue by jovstern** [JedWatson/react-select#2495]
Hi, i'm using un the menuRender mode to render my options list and the keys (up, down, enter)
doesn't effect on the items, whats the best way to deal with it?

**Comment by Tamakimouto** [comment]
You have to handle that yourself using a combination of `focusedOption`, `selectValue`, and maybe `onChange`.

**Comment by jossmac** [comment]
Thank you for responding @Tamakimouto!
