### ISSUE TITLE
Unable to select if we have checkboxes just under this control

### ISSUE THREAD

**Issue by Kapil-Vermani** [JedWatson/react-select#2498]
I have a use case in my react app in which my check boxes are coming under react select component so whenever i am trying to select value from react-select then value is not getting select but state of check box is getting changes.

So is there a way by which all the other controls in that fieldset goes to background (should not change state)  when select box was opened.

**Comment by jossmac** [comment]
@Kapil-Vermani could you please provide an example using https://codesandbox.io

I think I understand the problem, but not why it might be happening. An example would really help.

**Comment by flexdinesh** [comment]
Hey @Kapil-Vermani  [v1 of react-select is no longer maintained](https://github.com/JedWatson/react-select/pull/3786). 

We recommend maintaining your own v1 fork if you want to address `v1` issues. We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest versions.

We highly recommend [upgrading from v1 to v2](https://react-select.com/upgrade-guide). Chances are this issue might already be fixed or non-existent in v2.

I'm closing this issue/PR now. Feel free add your thoughts in #3981 and reference this issue/PR if needed.
