### ISSUE TITLE
Allow any type in value

### ISSUE THREAD

**Issue by bashmish** [JedWatson/react-select#25]
HTML options tag doesn't allow value to be any other type than string. But this component should allow this because it is usually more convenient to make values as integer ids. Developers shouldn't always make conversion from string to int and vice versa themselves.

**Comment by RusAlex** [comment]
IMHO it must stay as strict as possible and do not allow non-strings to be values.

**Comment by dcousens** [comment]
Agreed, stricter is easier.  Just pre-format your data.

**Comment by dcousens** [comment]
Closed in favour of #45.
