### ISSUE TITLE
Allow clicking mid-input to modify input contents (have a patch ready)

### ISSUE THREAD

**Issue by bx98pjni9g88jnz** [JedWatson/react-select#250]
Currently when typing in the input you can use the arrow keys to navigate around the string and make adjustments to the input.

It is currently not possible to click in the middle of some text in the input to make the same modifications (you have to use the arrow keys to get to where you want to make the modification).

This can be fixed in the `handleMouseDown` function with a `setTimeout 0`, e.g. (rough es5 / non es6 playing around with it modification)

``` javascript
// ... begin of fn
setTimeout(function() {
    if (this.state.isFocused) {
        this.setState({
            isOpen: true
        }, this._bindCloseMenuIfClickedOutside);
    } else {
        this._openAfterFocus = true;
        this.getInputNode().focus();
    }
}.bind(this), 0);
// ... end of fn
```

If this is acceptable I'll make a pull request with the proper changes following the guidelines.

**Comment by JedWatson** [comment]
Thanks @trevorsenior, would definitely appreciate a PR for that!

**Comment by karavaev-evgeniy** [comment]
+1

**Comment by Firfi** [comment]
+1 
Please make PR appreciable again
