### ISSUE TITLE
Issues when used with input-based popovers (re.g. eact-datepicker)

### ISSUE THREAD

**Issue by mvoica** [JedWatson/react-select#2513]
The example (https://github.com/mvoica/react-datepicker-select) is based on v 1.2.1 because I found a way to prove if can be fixed. Version 2.0 changes things dramatically (in the rendering of the input)

the case happens when the drop-down is to be used without the search. In this case, the v 1.2.1 renders a div instead of the input.

The example is tested in Chrome Version 65.0.3325.181 (Official Build) (64-bit)

So, with the repo, click on the 1st input, then click on the first drop-down. You will notice that the focus is stolen from the input. And that is fine I guess. 

Now for the actual issue: click the 2nd input - which opens the react-datepicker.
Click on the 1st drop-down. The drop-down flashes, but does not stay open.

This works though if we explicitly pass a simple div for rendering to the DropDown (through the inputRenderer prop, so ours is used instead of the default one). Which is what the 2nd drop-down does. In this case (for some reason), the datepicker disappears, and the drop-down stays open. However, in this case, the drop-down is no longer closing when clicking outside (as it does when the default div is used)

The 3rd drop-down will get wrapped with react-onclickoutside (in an awkward way, true) - but that does the trick, the drop-down opens when it should, and the outside click is registered and closes the drop-down. Which is exactly what I wanted

If I swap the library version with 2.0.0 - alpha, and I adjust the prop-names changes, all 3 drop-downs still exhibit the issue (because version 2.0.0 does not support a custom inputRenderer prop from what I see).

**Comment by jossmac** [comment]
> because version 2.0.0 does not support a custom inputRenderer prop

```jsx
const CustomInput = props => {
  // replace the component with whatever you want
  return <input {...props} />;
}

<Select components={{ Input: CustomInput }}
```

More info and docs http://bit.ly/react-select-v2

* * *

NB: In the future, please use a service like [CodeSandbox](https://codesandbox.io/) rather than creating a repo that people to download and run.
