### ISSUE TITLE
Creatable with onInputChange with no return gives promptTextCreator undefined

### ISSUE THREAD

**Issue by mantissa7** [JedWatson/react-select#2514]
I've noticed what *may* be considered a bug in Creatable. It's not necessarily a bug as I suppose the code is doing what it should be, but the implementation is slightly confusing and caught me off guard. 

When using Creatable with the onInputChange prop, if the prop func returns nothing, the the prompTextCreator doesn't "work".  the code at line 119 in Creatable.js sets `this.inputValue` to the result of `onInputChange`. When nothing is returned, the value is set to undefined. When promptTextCreator tries to run, it sees only undefined and not what is currently written in the field.

I've created an example at [StackBlitz](https://stackblitz.com/edit/react-select-creatable-oninputchange?file=index.js).

my proposal is to change line 119 (v1.2.1):

```js
onInputChange (input) {
	const { onInputChange } = this.props;

	// This value may be needed in between Select mounts (when this.select is null)
	this.inputValue = input;

	if (onInputChange) {
		this.inputValue = onInputChange(input) || this.inputValue; // fix is here
	}

	return this.inputValue;
}
```

I haven't tested this yet but I imagine this addresses the issue. 

While this may not be a bug as such, it might be a nice quality-of-life thing, as it took me a while to find out why it suddenly wasn't working.

**Comment by okopr** [comment]
In version 1.2.1 is this probably solved: https://github.com/JedWatson/react-select/blob/v1.2.1/src/Creatable.js#L112-L123

Thank you :+1:

**Comment by flexdinesh** [comment]
Hey @mantissa7 [v1 of react-select is no longer maintained](https://github.com/JedWatson/react-select/pull/3786). Chances are this issue might already be fixed or non-existent in v2.

I'm closing this issue/PR now. Feel free add your thoughts in #3981 and reference this issue/PR if needed.
