### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by craigdallimore** [JedWatson/react-select#252]
Hey @JedWatson and team

Would you be amenable if we add in some config for a CI service? I'm presently using [Travis-CI](https://travis-ci.org/craigdallimore/react-select/builds/67097990) on a fork to run the tests on a few versions of node - and iojs - once I've pushed. It will send me an email if the tests fail, so I'm less likely to miss broken tests.

If you follow that link you might see a branch failing and a branch passing - the difference being the presence of a `.travis.yml` [file](https://github.com/craigdallimore/react-select/blob/master/.travis.yml) that configures the service.

There are a couple of services out there - I only have experience with Travis, but I see [Codeship](https://codeship.com/pricing) has a free tier as well. No doubt there are others.

Your thoughts?

**Comment by JedWatson** [comment]
I use TravisCI on Keystone as well, it's great, and I'd be happy to add it. If you are happy to submit a PR with the config, I'll flick the switch in Travis.

**Comment by craigdallimore** [comment]
Nice!

**Comment by craigdallimore** [comment]
@JedWatson config PR submitted :)
