### ISSUE TITLE
[v2] can't open drop down

### ISSUE THREAD

**Issue by Slind14** [JedWatson/react-select#2522]
**Version** `2.0.0-alpha.9+` (alpha.8 works fine)
**React** `15.6.2`

Clicking on the drop throws:
```
modules.js?hash=a26da2b5d483e004a82b8a58a9acd9ea20f419f0:18139 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Select`.
    in Select (created by StateManager)
    in StateManager (created by TableView)
    in div (created by PopoverContent)
    in PopoverContent (created by TableView)
    in div (created by Popover)
```

**Comment by gwyneplaine** [comment]
@Slind14  thanks for reporting this, can i confirm that this is happening still in the latest beta release? If so, please provide us with a replication case (ideally in codesandbox) so we can find out what's causing this.

**Comment by Slind14** [comment]
[![Edit 719kl231nq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/719kl231nq)

**Comment by gwyneplaine** [comment]
@Slind14  thanks for the sandbox, a fix for this is in #2544

**Comment by JedWatson** [comment]
Just merged the fix, will publish with `beta.2` shortly

**Comment by gwyneplaine** [comment]
@Slind14 beta.2 is out, and with it a fix for this issue. Thanks again for reporting!
