### ISSUE TITLE
[v2] css tag being set

### ISSUE THREAD

**Issue by Slind14** [JedWatson/react-select#2523]
**Version** `2.0.0-alpha.8`
**React** `15.6.2`

When react select is being rendered it throws this warning:

```
Warning: Unknown prop `css` on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by Unknown)
    in Unknown (created by css)
    in css (created by IndicatorSeparator)
    in IndicatorSeparator (created by Select)
    in div (created by css)
    in css (created by Unknown)
    in Unknown (created by IndicatorsContainer)
    in IndicatorsContainer (created by Select)
    in div (created by css)
    in css (created by Unknown)
    in Unknown (created by Control)
    in Control (created by Select)
    in div (created by css)
    in css (created by Unknown)
    in Unknown (created by SelectContainer)
    in SelectContainer (created by Select)
    in Select (created by StateManager)
    in StateManager (created by Header)
    in div (created by Header)
    in ul (created by Nav)
    in Nav (created by Header)
    in header (created by Header)
    in Header (created by Main)
    in div (created by Main)
    in Main (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by RouterContext)
    in App (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by RouterContext)
    in div (created by Body)
    in Body (created by RouterContext)
    in RouterContext (created by Router)
    in Router
```

**Comment by gwyneplaine** [comment]
Thanks for reporting this @Slind14, can you confirm that this is still happening in the latest beta release? If it is,  please provide us with a replication case,  ideally in code sandbox, so we can reproduce the bug.

**Comment by pgee70** [comment]
i have same warning on version v2.0.0-beta.1 / 2018-04-20

**Comment by Slind14** [comment]
See console on load/render:
[![Edit 719kl231nq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/719kl231nq)

**Comment by falconmick** [comment]
can confirm, same for me

**Comment by gwyneplaine** [comment]
@falconmick  @pgee70 @Slind14 this issue should now be fixed in beta.2, 

@ConneXNL, this sounds like a separate concern, please create a new issue and provide us with a replication case (preferably in a [codesandbox](https://codesandbox.io/s/new))

**Comment by Slind14** [comment]
Great thank you. Now it is only the touch support that is blocking me :)

**Comment by matthewcorreia** [comment]
hello, i also get this warning using the Async version in react-select v2.0.beta-8. 
this is a CodeSandbox of exactly the example from the v2 documentation:

https://codesandbox.io/s/40lw4kv264
