### ISSUE TITLE
onInputKeyDown event not working as expected on composition mode

### ISSUE THREAD

**Issue by simsim0709** [JedWatson/react-select#2531]
# Are you reporting a bug or runtime error?
Maybe bug.

Please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

What I like to do is I want to limit input value length.
For example, I want to only allow users to type by 5.
Like this:
if user type "abcde", then next key should not be added.
It's working fine, when I implement `onInputKeyDown`. But, if keyboard is IME(composition mode)
it's not working as expected. Although, `onInputKeyDown` event is triggered, value is added.
Like this:
"가나다라마", then next key is still added. 

There is Plunker, please check this out.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/dHygFMWWqVwaRAfpEmbn?p=preview

**Comment by jossmac** [comment]
Ref #1149

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
