### ISSUE TITLE
Cannot read property 'offsetTop' of null while opening options menu.

### ISSUE THREAD

**Issue by swarchen** [JedWatson/react-select#2533]
### Thanks for providing such a nice component!

# Dependency vesions

`
"react": "^16.3.2",

"react-dom": "^16.3.2",

"react-select": "^1.2.1"
`
# How does it happend

While I opening the option menu like below
![2018-04-20 10 31 18](https://user-images.githubusercontent.com/11629463/39027820-3eaa4342-4486-11e8-9cfd-0de9662df638.png)

In the meantime I checked devtools. Find out that menu are properly rendered. But `findDOMNode(this.focused)` in the ComponentDidMount lifecycle returns null caused the TypeError.

![2018-04-20 10 27 59](https://user-images.githubusercontent.com/11629463/39027846-641f5018-4486-11e8-86da-ca9c47dc6f7b.png)

![2018-04-20 10 28 20](https://user-images.githubusercontent.com/11629463/39027888-a2b2a4a6-4486-11e8-9eed-5028664f9a4b.png)

BUT!

It totally works while I using lower version of react@^15.5.4 and react-dom@^15.5.4 without any code change.

Is there someone met the same problem like me ?

**Comment by dudenamedjune** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/06564be0-93e6-44c6-8479-62051bb40ae4-7c010302-2659-4457-9f13-38c55107d715-v1.png?transparent=1&palette=1&width=246)

**Comment by jossmac** [comment]
Sorry gents, I cannot reproduce this.

**Comment by donatoaz** [comment]
I am getting this error... I saw on #899 that it can be an issue with conflicting versions of react-dom, but in my case I have only one version, 16.4.1, and still getting this error.
