### ISSUE TITLE
[v2] Not able to change input color

### ISSUE THREAD

**Issue by lesha1201** [JedWatson/react-select#2540]
`version: 2.0.0-beta.1`

**Description:**
There is no way to change `color` of `input` using glam because it's overridden by default input styling.

**Example:**
![Image of Yaktocat](https://i.imgur.com/EGtAUlx.gif)
https://codesandbox.io/embed/0x5mqr4yow

**Solution:**
I think we should set` color` of `input` to inherit and add default color to its parent element.
I'm going to fix it.

P.S. my first contribution.

**Comment by lesha1201** [comment]
I've fixed it but tests didn't pass because snapshots are different. Should I commit only changes in Input.js or change snapshots first?

**Comment by gwyneplaine** [comment]
@lesha1201  would love to see your fix for this issue, please commit the changes in input.js, and submit a PR, we can fix the tests once the PR is up 😄

**Comment by JedWatson** [comment]
Fixed by #2546

**Comment by lesha1201** [comment]
@Jucesr It's already in 2.0.0-beta.2. Now when you change color in input it will be applied to input element.
```
const styles = {
  control: base => ({
    ...base,
    background: "#152033"
  }),
  singleValue: base => ({
    ...base,
    color: "#fff"
  }),
  input: base => ({
    ...base,
    color: "#fff"
  })
};
```
Like here https://codesandbox.io/embed/0x5mqr4yow

**Comment by ketysek** [comment]
Hi there,
it's not possible to change another basic css attributes on input, like text-transform, font-weight, letter-spacing etc :-(

**Comment by abdes-zakari** [comment]
thanks @lesha1201

**Comment by froii** [comment]
What about Multi Value ? 
multiValue has two div inside and it doesn`t work..
