### ISSUE TITLE
documentation: 

### ISSUE THREAD

**Issue by pgee70** [JedWatson/react-select#2541]
in the readme.md file, the section 
`
import Select from 'react-select';
import 'react-select/dist/react-select.css';
`

in the distribution i pulled (## v2.0.0-beta.1 / 2018-04-20) there is no react-select.css file.

**Comment by gwyneplaine** [comment]
@pgee70  those are react-select v1 docs, please look for react-select v2 docs [here](bitly.com/react-select-v2)
