### ISSUE TITLE
V2 – very opinionated className prop

### ISSUE THREAD

**Issue by poulet42** [JedWatson/react-select#2550]
Hello,
I migrated from v1.x to v2 and was really happy to see the new `menuPlacement` prop and the new features overall. 👏 
However, the changes made to className prop make it extremely hard to have multiple classnames on root element : 
Most of third-party components I use are wrapped like this : 

```
import cx from 'classnames';
import RSelect from 'react-select';
import "./styles.scss";

const Select = ({className, ...props}) => (
  <RSelect className={cx("Select", className)} {...props} />
)
```
It allows me to give a base class and add contextual classes / modifiers.

now, if I add a contextual className to this component, because of the new behaviour here is what's rendered : 

```
<div class="Select OopsClass css-zckpcq">
	<span ... class="css-17l7ekz">X results available.</span>
	<div class="Select OopsClass__control css-1qdiza0">
		<div class="Select OopsClass__value-container Select OopsClass__value-container--hasValue css-14wb226">
			<div class="Select OopsClass__single-value css-1hd5ane">
				...
```

I know I could rewrap my component and style its wrapper, but I think I shouldn't have to, this shouldn't be a default behaviour for the className prop in my opinion. What do you think ?

**Comment by ericblade** [comment]
I haven't dug into this a whole lot, but I was experimenting with V2 yesterday (thinking it was V1), and it seemed really quite difficult to deal with it when using CSS Modules.  So, seems related.
