### ISSUE TITLE
[V2] ClassName order

### ISSUE THREAD

**Issue by nmaves** [JedWatson/react-select#2560]
I think I am very close to getting things work with styled-components but I think the order of the class names is an issue.

Given the following code

```
export const Select = styled(ReactSelect)`

  &__dropdown-indicator {
    padding: 4px;
  }

  ${width};
  ${space};
`
```

I get 

```
<div role="button" class="sc-csuQGl iRvGtw__indicator sc-csuQGl iRvGtw__dropdown-indicator css-1c0gw5t">...</div>
```

Notice the class name appended after the styled-component generated classname.  This prevents me from overriding the defaults.

`iRvGtw__dropdown-indicator css-1c0gw5t`

**Comment by pr0da** [comment]
I think the class names order does not affect the specificity, so the order of the class names in the class attribute does not matter. Probably the style tags order is the problem here, so styled components should inject the style tag after react-select's style tag.

**Comment by cbovis** [comment]
@nmaves this likely isn't useful anymore but may help others in this situation... I had the same issue as yourself and managed to solve with the following:

```
const StyledCurrencySelector = styled(CurrencySelector)`
  width: 200px;

  && &__control {
    background-color: transparent;
  }
`;
```

The additional && is a styled-components helper which increases specificity.

**Comment by casvil** [comment]
@nmaves @JedWatson 
How is (in this case) `css-1c0gw5t` generated? How can I overwrite it?

Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
