### ISSUE TITLE
New Styles API

### ISSUE THREAD

**Issue by davekeehn** [JedWatson/react-select#2561]
The class based system is superior.  We base out Look&Feel with SASS variables.
With this new api it looks like I need to use the value of the variable of the current version of another groups SASS files.  Now when they change the value of a variable, we have to remember and take the extra time to update the value and hardcode it into every instance or have some const somewhere.
As opposed to doing _nothing_ (disregarding incompatibilities between releases.)

**Comment by jossmac** [comment]
If you prefer CSS, version 2 supports `className` and `classNamePrefix` properties.
