### ISSUE TITLE
[v2] TypeError: cx is not a function

### ISSUE THREAD

**Issue by Hongbo-Miao** [JedWatson/react-select#2563]
The date picker demo is broken
https://deploy-preview-2289--react-select.netlify.com/advanced#experimental

When you click the select, it shows blank page with this error in the console

![image](https://user-images.githubusercontent.com/3375461/39275105-e6932d10-4898-11e8-90d2-fb3aa8716695.png)

**Comment by gwyneplaine** [comment]
Thanks @Hongbo-Miao, a fix for this is in #2564

**Comment by gwyneplaine** [comment]
This has been merged in and has been released as part of react-select v2.0.0-beta.2
