### ISSUE TITLE
allowCreate initial value is empty if not on options

### ISSUE THREAD

**Issue by valtido** [JedWatson/react-select#2566]
Bug, consider the following;

```
 <Select
        name="form-field-name"
        value={selectedOption}
        onChange={this.handleChange}
        options={[
          { value: 'one', label: 'One' },
          { value: 'two', label: 'Two' },
        ]}
 />
```

If `selectedOption = {value:'three', label:'three'}` nothing get's displayed.

Should there not be a switch to declare that if not on `options` add it to the list?

**Comment by ugg0t** [comment]
btw, for select.async passing value as a whole option (just like you did `value={{value:'three', label:'three'}}`) works fine
