### ISSUE TITLE
Any way I can set maxlength when searching?

### ISSUE THREAD

**Issue by pablote** [JedWatson/react-select#2571]
I tried asking this on stackoverflow as suggested here, but there's no response so far: https://stackoverflow.com/questions/49242789/does-react-select-support-maxlength-in-search.

Is this simple enough that I could code it myself if pointed in the right direction?

thanks

**Comment by jossmac** [comment]
Thanks for using StackOverflow first, we appreciate it. Glad you found the solution, and answered for the next person 🙂

**Comment by vidit1** [comment]
any solution for v2, inputProps has been removed from props of react-select.

**Comment by therise3107** [comment]
this is how you can apply maxLength 

pass `maxLength` as a props or define in your file 
```
<Select
...
onInputChange={inputValue =>
            (inputValue.length <= maxLength ? inputValue : inputValue.substr(0, maxLength))
          }
....
/>
```

**Comment by hesetiema** [comment]
any solution for antd v3 ?
