### ISSUE TITLE
Plnkr for react-select v2/@next

### ISSUE THREAD

**Issue by Bartuz** [JedWatson/react-select#2574]
I wanted to report a bug for react-select v2 branch but I couldn't make react-select work at all in plnkr.co. Could anyone share with me plnkr with working react-select2 template? Here is my sketch: https://plnkr.co/edit/vGh10W823x1RSBiMAiwX?p=preview

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
