### ISSUE TITLE
Clicking outside the browser dismisses menu

### ISSUE THREAD

**Issue by ericblade** [JedWatson/react-select#2575]
I'm trying to debug what is going on inside this component, when the menu is up, but clicking outside of the browser, such as into the chrome debugger, closes the menu.  Right clicking "Inspect" inside the menu also causes a close, and causes the inspector to go to the element that would be below the menu. (edit: this is in v2, which i just realized i have)

**Comment by canda** [comment]
Same on v1, how can we inspect the menu elements (for development purposes)?

**Comment by combizs** [comment]
If you locate the `<Select ... />` element in the dom inspector, you can add a breakpoint to its parent element.  That way, if the menu tries to close, it would be stuck in a debugger state in which you would still be able to inspect the dom element.  Steps to inspect actual menu while it is open: 

Inspect around the elements and/or parent of the menu element, right-click → "Break on" → "subtree modifications"

![image](https://user-images.githubusercontent.com/749396/39550378-e78686ae-4e15-11e8-89f9-f4b68dfea75f.png)

**Comment by ericblade** [comment]
Well, good to learn about some debugging features I wasn't aware of, so thank you for that.  I still find it slightly strange, that the menu closes when clicking outside the browser. Though maybe I'm wrong

**Comment by canda** [comment]
nice, what I did was to hardcode the prop `menuIsOpen`

**Comment by ericblade** [comment]
@canda just add that prop to the <Select > ?

**Comment by canda** [comment]
Main select component `<Select isMenuOpen />`

**Comment by gwyneplaine** [comment]
thnx @ericblade, as specified above, we expose a 'menuIsOpen' prop for you to take control of whether the menu is shown or not. <Select menuIsOpen/>.

issue closed

**Comment by codercodingthecode** [comment]
My issue with this still persisted on version 3.x

In my case I have default is open, however, due to not having focus once the component renders, I can click outside and nothing happens.
The solution here was to use ```autofocus={true}```, so the component activates its focus and works on blur without having to do anything else in local state management to control that.
