### ISSUE TITLE
CreatableSelect, multi, in mobile app yiy cant click the 'x' on created items

### ISSUE THREAD

**Issue by yarrichar** [JedWatson/react-select#2577]
Pretty much as the title says. If you use CreatableSelect on mobile in multi select mode then you cant use the x to get rid of items you created.

This can be reproduced in the demo. Just switch chrome to show as for a mobile app. Create some items and try and click the x. I've reproduced this on a real mobile as well.

**Comment by AVeselovski** [comment]
Still no solution for this one?

**Comment by jossmac** [comment]
Resolved by #2762
