### ISSUE TITLE
Async Select with multi and simpleValue causes selection to become hidden while searching

### ISSUE THREAD

**Issue by MrLeebo** [JedWatson/react-select#2579]
In v1.2.1, for a configuration such as

```jsx
<Select.Async 
  value={value} 
  onChange={onChange} 
  loadOptions={loadOptions} 
  multi 
  simpleValue
/>
```

After you select the first option, if you begin typing a new search into the textbox, the previous selection will disappear until you clear your search.

## Repro steps

1. From the /examples folder, edit `Contributors.js` by adding `simpleValue` to the `<Select.Async>` component
2. Start the demo
3. Clear the Contributors component 
4. Click on "Jed Watson"
5. Press "z"

## Expected

The Jed is still visible, and an untagged "z" is next to it.

## Actual

Jed disappears, leaving only the "z"

## Extra Info

The previous selection remains if your new search criteria matches the selection. The component behaves with the prop `simpleValue={false}`.

**Comment by roginfarrer** [comment]
Hey @jossmac, can you describe how this was resolved in v2? `simpleValue` doesn't seem to exist in v2 and it's not documented, so I can't really tell how this was resolved.

**Comment by jossmac** [comment]
@roginfarrer that's correct. There is no longer a `simpleValue`.
