### ISSUE TITLE
Why does setting 'modules:true' in my webpack config break styling

### ISSUE THREAD

**Issue by DougWoodCDS** [JedWatson/react-select#2580]
currently in my react app I am using react-select (1.2.1)  and in the index.js file I have
..
import 'react-select/dist/react-select.css';
..

Everything is fine. the Select compoenent works great, all css etc.

However, I needed to import another component **"react-rte": "^0.16.1"**, and in order to do this I needed to update my webpack config to support css modules.

I highlighted the one  line that I changed in my webpack config ( basically just added **modules:true** ):

```
          {
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  modules: true,   // NEW LINE HERE
                  importLoaders: 1,
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                 ...

```
Now all the styling/classes etc. in react-select is gone.
I sort of understand why this is happening but don't know of the  correct way to fix this ?
any help would be greatly appreciated...!

**Comment by bugzpodder** [comment]
does this help? https://github.com/JedWatson/react-select/issues/1324

**Comment by ericblade** [comment]
fwiw

````
import '!style-loader!css-loader!react-select/dist/react-select.css';
````

is how i go about dealing with this in packages that import css globally, but i'm using modules in my app.

**Comment by jossmac** [comment]
Please see #1324
