### ISSUE TITLE
how to clear cache result with ASYNC

### ISSUE THREAD

**Issue by shorif2000** [JedWatson/react-select#2582]
i have the following

```jsx
<Async 
  autoload={false}
  multi={false} 
  value={this.state.selectValue} 
  onChange={this.updateValue} 
  valueKey="value" 
  labelKey="label" 
  loadOptions={this.getCommsmatrices} 
  onValueClick={this.gotoCommsmatrix}
  cache={false}
/>

getCommsmatrices (input, callback) {
  input = input.toLowerCase(); 
  let options = this.state.options.filter(i => {
  	return i.label.toLowerCase().includes(input) == true;
  });

  let data = {
  	options: options,
  	complete: true 
  };

  setTimeout(function() {
  	callback(null, data);
  }, ASYNC_DELAY);
}
```

once my results are loaded it stays cached. i want to trigger this cache clean externally. how can this be done?

i want to clear the cache in the following function. I have tried setting `isLoading` but it does not work.

```js
updateCommsMatrix(service_id){
  this.setState({ isLoading: true });
  this.updateValue(null);

  if(service_id > 0){
    let self = this;
  	this.props.fetchCommsmatricesByService(service_id)
      .then( response => {
        let data = response.payload.data.body.recordset.record;
        let options = self.populateOptionsObject(data, 'id', 'filename');
        options.unshift({ value: '0', label: 'All' });
        return options;
      })
      .then( options => self.setState({options:options,isLoading: false}));
  } else {
    this.setState({ options:{ value: '0', label: 'All'},isLoading: false });
  }

  this.props.dispatch(change('SecurityExemptionsNewForm', 'service_id', service_id));
}
```

**Comment by JedWatson** [comment]
@shorif2000 @pedalpete could you specify which version of react-select you are using?

**Comment by pedalpete** [comment]
I'm on 1.2.1

**Comment by shorif2000** [comment]
@JedWatson im on 1.2.1

**Comment by jossmac** [comment]
Possibly related to #2661

**Comment by mforman1** [comment]
@JedWatson I'm using v2, please advise on how to clear the cache on this version. Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
