### ISSUE TITLE
Content Overflowing in IE 11 (2.0.0-beta.2)

### ISSUE THREAD

**Issue by kidroca** [JedWatson/react-select#2583]
# Content Overflowing in IE 11 (2.0.0-beta.2)

- Text Input (Select Value) appears with scrollbar next to the indicator icons 
- Dropdown menu content is overflowing outside the menu

![image](https://user-images.githubusercontent.com/12156624/39568313-7450fefc-4eca-11e8-8e3f-4a4277a3def0.png)

## Plunk example 

https://codesandbox.io/s/4j2y5k6y09

I'm not sure whether IE 11 is targeted for support, Edge seems to work fine 

*Edit: Not IE 10 -> IE 11*

**Comment by jprosevear** [comment]
IE10 has been unsupported by MS for > 2 years:
https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

**Comment by kidroca** [comment]
Oops, sorry my bad this is IE 11

**Comment by gwyneplaine** [comment]
@kidroca  thanks for this, we'll look into patching this

**Comment by gwyneplaine** [comment]
Closed by #2593 #2596
