### ISSUE TITLE
Placeholder text misaligned in multiselect component

### ISSUE THREAD

**Issue by aloverso** [JedWatson/react-select#2586]
## Steps to reproduce 

1. [Visit the live demo](http://jedwatson.github.io/react-select/)
2. Use the Multiselect example with "Stay open when an Option is selected" = true
3. Select enough options so that they overflow onto a second line

![screen shot 2018-05-04 at 11 14 45 am](https://user-images.githubusercontent.com/36281289/39635746-61c04442-4f8c-11e8-9214-a5ca1c653b34.png)

4. Click outside the multiselect to lose focus and close the menu
5. Click the 'X' button to remove all selected options
6. The placeholder text and the down-arrow is now a few pixels misaligned from vertical center (too close to the top of the input field)

![screen shot 2018-05-04 at 11 13 43 am](https://user-images.githubusercontent.com/36281289/39635704-430f7d1a-4f8c-11e8-82a2-0deda2593c7d.png)

## Notes

It seems tied to these specific scenarios (the stay-open menu, the multiple lines of options, and the clicking-outside to lose focus before clicking 'x'). 

Any advice/workarounds/fixes would be appreciated

**Comment by JedWatson** [comment]
Is this consistent across browsers or only reproducible in (one | some)?

**Comment by ened** [comment]
<img width="1160" alt="screen shot 2018-05-22 at 10 34 22" src="https://user-images.githubusercontent.com/269860/40339163-b6090804-5dab-11e8-860c-ce493b9ab216.png">

I'm able to reproduce this using v1.2.1 and Chrome.
