### ISSUE TITLE
Placeholder text does not reflect current selection if state is updated during onChange

### ISSUE THREAD

**Issue by pfgherardini** [JedWatson/react-select#259]
Hi,

I am having a weird problem where the placeholder text does not get updated to reflect the current selection if I modify the state of the parent in an event handler for the onChange event. The following code

```
var TextParagraph = React.createClass({

    getInitialState: function() {
        return({curVal: ""});
    },

    handleOnChange: function(val) {
        console.log("New state " + val);
        this.setState({curVal: val});
    },

    render: function() {
        var opt = [
            { value: 'one', label: 'One' },
            { value: 'two', label: 'Two' }
        ];


        return(
            <div className="TextParagraph">
                <Select options = {opt} onChange = {this.handleOnChange} />
                <p>This is the state</p>
                <p>{this.state.curVal}</p>
            </div>
        );      
    }

});
```

Shows the correct state in the text paragraph but the placeholder text never gets updated to reflect the selection. If I comment the `this.setState({curVal: val});` line, the placeholder works correctly, but obviously the state is not updated.

Thanks in advance for your help,

Federico

**Comment by pfgherardini** [comment]
Ok I figured it out. You need to pass the value back as a prop to the <Select> element.
So the following line

```
<Select options = {opt} onChange = {this.handleOnChange} />
```

should be

```
<Select value = {this.state.curVal} options = {opt} onChange = {this.handleOnChange} />
```

Maybe it might be worth mentioning in the "Usage" section of the Readme as the example that is currently there is slightly misleading

**Comment by gravitypersists** [comment]
This seems like a bug - removing the event handler allows the select menu to be changed. Was the intention behind this to make it like a controlled component?

**Comment by pfgherardini** [comment]
I think the idea is that you use the event handler to store the state somewhere (for instance in a Flux store or in the parent component) and then pass the state back to the Select element so that it knows to display what is currently selected.

**Comment by gravitypersists** [comment]
Right - however, if you've no intention of controlling state like this, this behavior probably shouldn't be automatic unless the value is declared in the prop of the component in the first place.
