### ISSUE TITLE
[V2] Theme is not customisable

### ISSUE THREAD

**Issue by eemeli** [JedWatson/react-select#2590]
The `v2` branch exports three `const` values from `src/theme.js`: `borderRadius`, `colors` and `spacing`. The latter two are objects, which allows for the theme to be modified externally, but `borderRadius` is just a `number`, so it cannot. Could it also be wrapped in an object to make this possible?

**Comment by eemeli** [comment]
Ah, bother. As the theme isn't actually exported, the theme as a whole is not customisable from an ES6 context, as the package.json `jsnext:main` and `module` values direct packagers to use `dist/react-select.es.js` rather than `lib/index.js`.

So could the theme be exported, and made customisable? As an alternative to clobbering the base theme, could something similar to the `styles` props be implemented for the theme? This would make react-select v2 much easier to customise.

**Comment by JedWatson** [comment]
I think this would make sense.

I'd like to clean up the `theme` export, to make it easy to apply simple re-skins (e.g some colours, spacing, border radius etc.) then we could pass it down to to components in `commonProps`

Then a new `theme` prop on `Select` could support two modes:

* `theme={themeObject}` ("clobber mode")
* `theme={base => ({ ...base, primaryColor: 'pink' })}` (extend mode, like `styles`)

Open to PRs 😄

**Comment by eemeli** [comment]
I'm not sure if it makes sense to have the theme completely replaceable, rather than just overridable. The core code refers to particular theme values in multiple places, and those could very easily be left undefined by complete replacement.

**Comment by isitrita** [comment]
@JedWatson When do you plan make release with theme? We are really waiting for this!

**Comment by Dandry** [comment]
It looks that this feature has already been merged, however I fail to accomplish custom theming. Even though I pass the theme object as presented, the colors do not change. What is more, [`CodeSandbox link`](https://codesandbox.io/s/1oz7n0wok4?module=/example.js) on the  [`doc's subpage`](https://react-select.com/styles#using-classnames) shows custom theming example, but the result also does not get colors changed. Also, it seems that Typescript type definitions are missing for this `theme` prop.

**Comment by Dandry** [comment]
@JedWatson I also need this desperately! Thanks!

**Comment by giocodes** [comment]
How come this works on the docs:
https://react-select.com/styles#overriding-the-theme

But not on the live code or locally? 
https://codesandbox.io/s/1oz7n0wok4?module=/example.js

Are the docs on a later version than 2.0.0 ?

**Comment by jkeruzec** [comment]
Can't we access latest beta version from npm to test the customable theme ?

**Comment by renschler** [comment]
hey I'm new to front end and react for that matter. I'm trying to set a border radius and color and width for the <Select/> component via a className. Adding `border: 1px solid #e4e4e4;` to the css class creates a new border, it doesn't update the existing border on the <Select/> component. I'm not sure if I should file a separate issue or if this is the same as what is described above.

**Comment by akx** [comment]
@renschler You will need to customize the theme object's border value(s) to do that; the `<Select>` itself is not the actual visible component.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
