### ISSUE TITLE
[v2.0.0-beta.2] Lost focus prevents the menu from being clicked/blurred away

### ISSUE THREAD

**Issue by menelike** [JedWatson/react-select#2591]
I am currently facing a very strange bug which behavior

1. can not be reproduced with help of the demos (like https://codesandbox.io/s/p8r7wnqw7)
2. could not be set up on reproducible test scenario

so that I'm sorry that I can't give the proper detailed description.

The following happens when `onChange` is passed to `Select` together with custom `components` and after the first `onChange` call in which no event handling is done at all.
As some point the `DummyInput` (`!searchable`) looses focus and it never receives the focus again. (At this point the `document.activeElement` is set to body).

![mai-08-2018 19-21-00](https://user-images.githubusercontent.com/4238881/39772384-6bf1773a-52f5-11e8-8a27-ec09af19eb42.gif)

I was able to fix that with replacing
https://github.com/JedWatson/react-select/blob/b52bb4d006bd769eb25ff1c9c933623a20c6a138/src/Select.js#L363-L365

with

```
  onMenuOpen() {
    this.props.onMenuOpen();
    this.focusInput();
  }
```

so that everytime the Menu opens also the current `this.input` becomes focused. I have absolutely no idea if that's the right place, hopefully it leads you guys to the right direction.

**Comment by JedWatson** [comment]
Thanks for the comprehensive report @menelike 

I can see how adding the `focusInput` call could workaround this, and I can't see any harm in adding it. So I'll apply that change.

It would be great if we could see the implementation of your custom components - are they including anything that could make them focusable (e.g. `tabIndex`) and perhaps somehow interacting with the active focus on mount?

**Comment by alanuecker** [comment]
Hi @JedWatson,

here is a basic version of our custom component https://codesandbox.io/s/3270k301r1 at @risetechnologies. We use [MDC](https://material.io/develop/web/) for our UI so it took a bit of styling to replace our current Select Menus but the other parts of the implementation should be pretty basic and straightforward.
There is no `tabIndex` set and we do not interact with the focus intentionally so it took @menelik and me a bit of research an guessing to figure out how to fix this problem or at least prevent it.
