### ISSUE TITLE
[2.0.0-beta.2] Components Option render function issue with innerProps

### ISSUE THREAD

**Issue by devon-pl** [JedWatson/react-select#2599]
While overwriting the Option component I found issue with passing innerProps to the div. Documentation example says: 

```
import React from 'react';
import Select from 'react-select';

const CustomOption = ({ innerProps, isDisabled }) =>
!isDisabled ? (
    <div {...innerProps}>// your component internals</div>
) : null;

class Component extends React.Component {
    render() {
        return <Select components={{ Option: CustomOption }} />;
    }
}
```

But when passing innerProps, I'm getting warning:

**React does not recognize the `innerRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innerref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.**

Code to reproduce:

```
const optionRenderer = props => {
    return (
        <div {...props.innerProps}>
            {props.data.label}
        </div>
    );
};

render() {
    return (
        <Select
          placeholder="Select language"
          defaultValue={{ value: "EN", label: "English" }}
          options={[
            { value: "GB", label: "English" },
            { value: "RU", label: "Russian"}
          ]}
          components={{
            Option: optionRenderer
          }}
      />
   );
}
```

**Comment by devon-pl** [comment]
It's been fixed in 2.0.0-beta.3, thanks!

**Comment by gwyneplaine** [comment]
@devon-pl, thanks for this! Yup, fixed in beta.3

**Comment by alexanderwallin** [comment]
I'm getting this error in `2.0.0-beta.6`, where `innerRef` is `undefined`.

**Comment by bradzawacki** [comment]
I'm also seeing this in `2.0.0-beta.6` with react/react-dom `16.4.1` and using either the documentation example or the OP's example.

**Comment by kgwebsites** [comment]
The error seems to go away with 2.0.0-beta.7
