### ISSUE TITLE
[V2] TODOs

### ISSUE THREAD

**Issue by gwyneplaine** [JedWatson/react-select#2600]
## Before RC 

- [x]  screen-reader accessibility with Aria Live Regions.
- [x] implementing cx function to support a base classname. 
- [ ] select v2 as monorepo.
- [x] examples and docs improvements. 
- [ ] cypress tests refactor.

**Comment by IanVS** [comment]
Can you explain what you intend by `cypress tests refactor.`?  I'm trying to work on a PR, but struggling with the way the cypress tests are structured, they seem very brittle.  I have my own ideas of how to improve them, and would be willing to submit a PR, if there's any chance it can be merged.

**Comment by naheeyahh** [comment]
Will there be plans to make V2 selenium testable? Because "Select-option" and "Select-control" are no longer accessible by the web driver it is impossible to test V2 with selenium.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
