### ISSUE TITLE
[2.0.0-beta.2][Feature Request] Pass extra info to MultiValueLabel Component

### ISSUE THREAD

**Issue by hh54188** [JedWatson/react-select#2606]
What I want do is custom both option label and MultiValueLabel.

I custom option label success which by adding react element to `label`  property in option data. However, I found the MultiValueLabel props only contain my custom option label component instance. and classname. So I can't get my entire option data to custom another MultiValueLabel. 

Or I have to store information in option label component in advance. Then get it in like this:

```javascript
const CustomMultiValueLabel = (props) => {
  const {children}  = props
  const {myInfo} = children.props
  //  More 
}
``` 

I think it's a trick and it is not good code.

So why just add the third parameter in props like option data or something similar ?

**Comment by vpark** [comment]
Doesn't just binding the this.props solve your problem?

```
      <Select
        components={{
          MultiValueLabel: CustomMultiValueLabel.bind(null, this.props),
          Option: CustomOption,
        }}
      />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
