### ISSUE TITLE
[2.0.0-beta.3] stylesheet error

### ISSUE THREAD

**Issue by juliankmazo** [JedWatson/react-select#2608]
Hi there!

First of all, thanks a lot for maintaining this project!

Looks like there is an issue with the latest release. I have a production application pointing to https://npmcdn.com/react-select/dist/react-select.css and it gets redirected to consume the latest version:

https://npmcdn.com/react-select@2.0.0-beta.3/dist/react-select.css
<img width="823" alt="screen shot 2018-05-14 at 7 44 52 pm" src="https://user-images.githubusercontent.com/7906134/40030276-4b82bc98-57af-11e8-9fb2-dbc85e24f27c.png">

**Comment by gwyneplaine** [comment]
@juliankmazo thanks for this, this has now been fixed
