### ISSUE TITLE
Documentation for V2 not accessible

### ISSUE THREAD

**Issue by fabricehong** [JedWatson/react-select#2609]
### Thanks for using react-select!

Before creating an issue...

# Are you asking a question?
no

# Are you reporting a bug or runtime error?
no

# Are you making a feature request?
no

Your [link](https://deploy-preview-2289--react-select.netlify.com/) the documentation of V2 is not accessible.

**Comment by 1412108** [comment]
+1

**Comment by gwyneplaine** [comment]
@fabricehong  are you saying that you can't access it, or are you commenting on a11y accessibility?

**Comment by fabricehong** [comment]
Hi @gwyneplaine . The server was down for several days / weeks. Now it seems reachable again, so the issue can be closed.

Thank you
