### ISSUE TITLE
[V2] Missing <Select disabled> prop

### ISSUE THREAD

**Issue by eemeli** [JedWatson/react-select#2610]
React Select v1 supports a `disabled` prop on `<Select>` (e.g. as demo'd in the [first example](http://jedwatson.github.io/react-select/)), but v2 does not. Is this intentional, or missing functionality?

**Comment by tommyalvarez** [comment]
@eemeli https://deploy-preview-2289--react-select.netlify.com/upgrade-guide

disabled => renamed to => isDisabled

**Comment by eemeli** [comment]
Ah, drat, had missed that change. Apologies.
