### ISSUE TITLE
[V2] focusedOption when rendering custom MenuList

### ISSUE THREAD

**Issue by PengyuanZhao** [JedWatson/react-select#2612]
In V2, I want to completely replace the MenuList including its children (the options). But then the option loses the default highlighted color when it is "focused". How could I keep that in V2?

In V1, there is a `focusedOption` prop which could be used to highlight the option manually. 

Thanks!

**Comment by hrnik** [comment]
@gwyneplaine Can you help with the answer, or clarify place where we can ask this question?

I also have this problem, need `focusedOption` for integrate react-virtualized or react-window.

**Comment by dzbiku** [comment]
Anyone fixed it?

**Comment by mike391** [comment]
+1 this is important

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
