### ISSUE TITLE
Why do you collect code in a single bundle?

### ISSUE THREAD

**Issue by retyui** [JedWatson/react-select#2614]
**Problem:**
I try reduce my bundels size. In my project I use one import:
```js
import Select from 'react-select'; // 84 KB
```
I would like to have the opportunity to do so:
```js
import Select from 'react-select/dist/Select';
```

**Describe the solution you'd like**
Why do you collect code in a single js bundle?
Use flatten struct!
Like as: `lodash-es`, `date-fns`, `react-router`, `ramda`, `recompose`

**Comment by TrySound** [comment]
@retyui recompose will remove path imports in the next major release. We rely on treeshakability which works well as you can see [here](https://github.com/acdlite/recompose/blob/master/.size-snapshot.json#L16-L19).

**Comment by retyui** [comment]
@TrySound 
![image](https://user-images.githubusercontent.com/4661784/40385275-b7f69498-5e0e-11e8-85a9-c55eb0abf6c3.png)

**Comment by TrySound** [comment]
@retyui I show you example. That size number is generated with webpack itself. Treeshaking works well in webpack 4. Just use it. Use tooling to be sure that treeshaking works.

Path imports is import hell. It's illness when file has more imports than code. Treeshaking solve this.
