### ISSUE TITLE
Allow to close menu externally

### ISSUE THREAD

**Issue by ejdzipi** [JedWatson/react-select#2619]
Hi, 
I need to make multiple select allow maximum number of selected values. When max. number of options are selected, I don't want menu to show. 
Possible solution is to propagate closeMenu() function to be called from refs.
Can you please investigate this? 
Thanks

**Comment by 1412108** [comment]
I think you totally can implement it by yourself - disable or hidden arrow button when option reach max number

**Comment by ejdzipi** [comment]
That's not a problem, but how can I close the menu, when max number of options is reached? closeMenu() is not accessible from refs

**Comment by jossmac** [comment]
You can access `closeMenu()` via ref.
