### ISSUE TITLE
Disabling while empty in multiselect mode causes box to collapse

### ISSUE THREAD

**Issue by ianobermiller** [JedWatson/react-select#262]
Probably missing a min-height when collapsed. Reproduced in the examples.

![react-select-disable](https://cloud.githubusercontent.com/assets/897931/8267323/97757556-1710-11e5-8948-681166b56c26.gif)

**Comment by JedWatson** [comment]
@ianobermiller I've fixed this and #261, and pushed a new version `0.5.1`.

Thanks a lot for the clear issues and gif examples, they made it really easy to understand and track down what was wrong!

**Comment by ianobermiller** [comment]
Absolutely! I know how frustrating to have to ask for lots more info just
to repro!
