### ISSUE TITLE
V2 [2.0.0-beta.4] Css styling missing styling options or not working

### ISSUE THREAD

**Issue by tommyalvarez** [JedWatson/react-select#2626]
Hi,

Reading the v2 docs i didn't find a way to customize the option background color during click, but without release. I think the prop is normally called :active in css. The only available options are isDisabled, isSelected, isFocused which allows you to style disabled, selected and hovered option... but not clicked-hold ones. I leave a gif screencast for better explanation. See how it turns bluish on click

![awesomescreenshot-2018-05-18t11-59-52-755z](https://user-images.githubusercontent.com/2272455/40233629-28fe25cc-5a7a-11e8-91f1-9ad6a2a5161a.gif)
 
Also i can't seem to define border color on focus on the control component:

```
const selectStylesSelect = (hasError) => {
    const color = chroma(selectOptionColor)
    return {
      control: styles => {
        return { ...styles,
          'borderColor': hasError ? '#d9534f' : styles.borderColor,
          ':hover': {
            'borderColor': hasError ? '#d9534f' : color.alpha(0.5).css()
          },
          ':focus': {
            'borderColor': hasError ? '#d9534f' : color.alpha(0.5).css()
          }
        }
      },
      option: (styles, { data, isDisabled, isFocused, isSelected }) => {
        const color = chroma(selectOptionColor)
        return {
          ...styles,
          backgroundColor: isDisabled
            ? null
            : isSelected ? color.css() : isFocused ? color.alpha(0.3).css() : null
        }
      },
      singleValue: (base, state) => {
        const opacity = state.isDisabled ? 0.5 : 1
        const transition = 'opacity 300ms'

        return { ...base, opacity, transition }
      }
    }
  }
```
Am i missing something? It always default to a bluish border whe control component has focus (by using tab)

**Comment by fc** [comment]
To set the `:active` color on an option, do this:
```
  option: (base) => ({
    ...base,
    ':active': {
      backgroundColor: 'red',
    },
  }),
```

> Also I can't seem to define border color on focus on the control component

I also found this unintuitive but found a solution.

```
  control: (base, state) => {
    const borderColor = state.isFocused ? '#ff0000' : '#000000';
     /* some stuff */
    return {
      ...base,
      boxShadow: 'none', // <-- this is why it seems like you can't set the border color.
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor,
      // Remove default hover style unless you need it
      '&:hover': {},
      '&:focus': {
        borderColor,
      },
    };
  },
```

The one other gotcha I ran into when creating a custom components and wondering where some extra pixels were coming from is that the `input` and `placeholder` need to have their `margin` set to `0` since it was bumping up the height - may or may not be desired in your situation.

General debugging advice is call `console.log(base)` to figure out what is getting set.

**Comment by tommyalvarez** [comment]
@fc Thanks! Though i think it would be wise to add the prop isActive to the option state along the others, otherwise you start to think something is missing/incomplete.

**Comment by Kadrian** [comment]
Well, what about the isActive prop? Can't find the documentation here :-/

**Comment by ePaulo** [comment]
Bump (3.5 years later!).  So... any plans to add an isActive (isActivated?) state prop for "option:"... so others don't have to spend an hour searching for this thread to solve how to change the default blue background color for an "active" select option.  :-(
OR... please update your documentation to explain how to do it... and add a similar note on how to control the default blue outline/border color when the select box is being used ( ie. use '&:hover': {outline: 'none'} ).  If such tidbits of useful info is in your docs then do tell where they are... I obviously could not find them.  :-(

**Comment by jasondainter** [comment]
Agree 100% with ePaula. Sank a lot of hours into this blue issue!
