### ISSUE TITLE
[V2] Warning: Prop `id` did not match. 

### ISSUE THREAD

**Issue by andreyrodionov** [JedWatson/react-select#2629]
Getting this error in console.

Warning: Prop `id` did not match. Server: "react-select-5-input" Client: "react-select-2-input"

**Comment by gwyneplaine** [comment]
@andreyrodionov  please use the id prop on the select. By default if no id is defined, we increment an instancePrefix as a global variable (i.e. react-select-1, react-select-2). We do this to ensure that if you have multiple selects on the same page, they aren't all referenced by the same Id.

**Comment by KidkArolis** [comment]
I think it's `instanceId` prop, not `id` prop?

**Comment by gwyneplaine** [comment]
apologies @KidkArolis  is correct, please set the `instanceId` prop @andreyrodionov

**Comment by jjm340** [comment]
I used the instanceId property and I'm still getting this same issue with v1.2.1

**Comment by kovachwt** [comment]
I have the same issue with AsyncSelect with version 2.0.0.
Added an instanceId and an id, it does not help, the error is still there.

**Comment by MaxInMoon** [comment]
I resolved it this way

```js
<Select
  instanceID="demandeType"
  id="demandeType"
  ...
/>
```

**Comment by nisargrthakkar** [comment]
I'm getting this same issue

**Comment by nolandg** [comment]
Well I got it to work fine with no warning once I added `instanceId` but this reliance on a unique ID makes this component difficult to integrate with an SSR app. If internally it increments a counter to automatically add an ID, that counter needs to be forcibly reset on every render of the app and this does not appear to be happening. Is there a way to achieve this?

Use case: I render the app on the server at least twice to properly extract all the data each component needs to render, eg. GraphQL and Apollo's `getDataFromTree` function. When I render the app twice on the server and once on the client, all the `react-select` id's are off and warnings are generated and my React rehydration is inefficient.

There needs to be a way to tell `react-select` "do not increment ID's, I'm just pre-rendering you" or to reset the counter.

**Comment by nolandg** [comment]
As a workaround, I think I'll need to create my own SSR-aware React context and manage the `react-select` IDs myself.

Or does someone have a suggestion on how I could implement this within `react-select`?

**Comment by pawel2105** [comment]
`instanceId` as a prop works for me when the component is itself receiving a prop called `id` and using that value as the value for `instanceId`.

**Comment by bkyam** [comment]
I'm building out a site with Nextjs, and foudn that passing inputId fixed the issue.

```
<Select
				id={this.props.id}
				instanceId={this.props.id}
				inputId={this.props.id}
				defaultValue={this.props.options[`${this.props.defaultValue}`]}
				isDisabled={this.props.isDisabled}
				isFocused={this.props.isFocused}
				isSelected={this.props.isSelected}
				onChange={this.handleChange}
				name={this.props.name}
				options={this.props.options}
				menuPlacement='auto'
				components={{ DropdownIndicator }}
				styles={theme == 'dark' ? darkStyle : lightStyle}
			/>

```

**Comment by onukselcuk** [comment]
This is so annoying all Select components need 3 ids. 
1. id
2. instanceId
3. inputId

**Comment by pom421** [comment]
id and instanceId was enough to remove the warning in my case (Next.js 9.5)

**Comment by viniciusdacal** [comment]
could seem like a stupid question, but why is id needed in react-select? This is probably the first time I see Id being required or even used in a react-lib to be fair. Is that really necessary for the lib internals, could we use something else instead?

**Comment by paulm17** [comment]
Just instanceId was enough for me to fix this issue.

**Comment by ebonow** [comment]
> could seem like a stupid question, but why is id needed in react-select? This is probably the first time I see Id being required or even used in a react-lib to be fair. Is that really necessary for the lib internals, could we use something else instead?

I know this has been asked a while ago, but wanted to reply since I have gotten additional information about this question.

1) instanceId is used to keep id's in sync between SSR and client-side hydration.
2) unique id's are needed for implementing accessibility functionality

**Comment by TheGP** [comment]
Why there is no better explanation inside an error message or mention of it in the docs on the first page??

**Comment by smitd21** [comment]
Select component needs an instanceId, id mandatory
So Just add

id="long-value-select"
instanceId="long-value-select"

to your Select component it will remove the Warning :)

**Comment by hsglc** [comment]
just passed "id" prop works for me.

**Comment by Defite** [comment]
> I'm building out a site with Nextjs, and found that passing inputId fixed the issue.

No, it's really not fixing anything, unfortunately

**Comment by jacobsfletch** [comment]
If you're on React 18 you can create this id with the [`useId`](https://reactjs.org/docs/hooks-reference.html#useid) hook:

```js
import React, { useId } from 'react'
import ReactSelect from 'react-select'

export const YourComponent: React.FC = () => {
  const id = useId();
  return (
    <ReactSelect
      instanceId={id}
      ...
    />
  )
}
```

**Comment by klarstrup** [comment]
Should we move to use `useId()` inside `react-select`? It would require a larger hooks refactor of `Select`, I don't know if anything is blocking that at the moment.

**Comment by hdntc** [comment]
so apparently this is closed but is the solution in this thread working for anyone? I just get basically the same error but w/ the className instead, using nextjs v13

**Comment by peterdonaghey** [comment]
The solution is not working for me - using CreatableSelect
<img width="181" alt="image" src="https://github.com/JedWatson/react-select/assets/97884561/cc86e93c-454c-4963-bd1e-e47a9b8f7ed6">

still getting the same error
<img width="444" alt="image" src="https://github.com/JedWatson/react-select/assets/97884561/981b381a-9c8b-4d8b-a8be-0c6c8ac7f515">

**Comment by klarstrup** [comment]
What solution @peterdonaghey ?

**Comment by peterdonaghey** [comment]
@klarstrup edited the comment to make that more clear

**Comment by simon-abbott** [comment]
> so apparently this is closed but is the solution in this thread working for anyone? I just get basically the same error but w/ the className instead, using nextjs v13

Using `instanceId={useId()}` fixed the id error for me, but now I'm also getting the `className` error: ``Warning: Prop `className` did not match. Server: " css-1q5atpo-Input" Client: " css-n9qnu9"``. Interestingly though, this new `className` error only seems to happen in Safari, I can't reproduce it in Firefox or Chrome.

**Comment by Wyverex42** [comment]
This issue is still very much alive, unfortunately.

Setting `instanceId` gets rid of the initial warning but now it's `react-dom.development.js:86 Warning: Prop `className` did not match. Server: " css-1qpkzkj-ValueContainer" Client: " css-kktkhw-ValueContainer2"`.

This in Chrome, in contrast to @simon-abbott's findings. 

How do I fix this?
