### ISSUE TITLE
Trigger Close not working on Mobile.

### ISSUE THREAD

**Issue by mahavrilla** [JedWatson/react-select#263]
When I'm using the demos on Mobile(IOS 8.4 Safari)  after selecting one or more values in multi select, I cannot close the drop down by clicking on the red X. This is also present in single select options.

**Comment by RichieAHB** [comment]
I am also experiencing this on mobile safari on iOS 8.3. After using the multi select it appears all close buttons break.

**Comment by evilfer** [comment]
I'm having the same problem on Android 5.0.2 / Chrome 42, none of the buttons work. With a selected option and the dropdown closed, the 'x' button simply opens the dropdown, instead of clearing the selection.

**Comment by bulby97** [comment]
+1. Add onTouchEnd fix the problem

**Comment by adarshmuthappa** [comment]
+1

**Comment by oztek22** [comment]
any update on this bug?

**Comment by suryakun** [comment]
Any solution for this bug??

**Comment by gwyneplaine** [comment]
fixed in v2.
