### ISSUE TITLE
[V2] Initial styles before custom styles cause glitch on page loading

### ISSUE THREAD

**Issue by k4mr4n** [JedWatson/react-select#2633]
Hey all

Im giving custom style to hide the  `indicatorsContainer: (base, state) => ({ display: 'none' })` but when page is loading before this style applies, the indicator shows and cause glitch specially on slow connections which last for seconds

is there any way to fix this?

**Comment by gwyneplaine** [comment]
@k4mr4n could you supply us with a reproducible case for this, preferable in a CodeSandbox [here](https://codesandbox.io/s/new)

**Comment by k4mr4n** [comment]
@gwyneplaine found the issue, and its happening because of server side rendering.
and this should be the solution https://deploy-preview-2289--react-select.netlify.com/advanced#ssr---univeral-rendering

thank you

**Comment by hugotox** [comment]
Sorry guys, I got the same issue. @k4mr4n the link you posted is dead. What's the fix?

**Comment by k4mr4n** [comment]
Hey @hugotox the fix that worked was implementing hard coded css.
ex:
```
.css-1cq4x0a {
      padding: 4px 0 0 0;
      .css-9p8w3j {
        font-size: 24px;
      }
    }
```

**Comment by hugotox** [comment]
Just to confirm, is that the official way to apply styles to the react-select in a server-side rendered page?
