### ISSUE TITLE
[v2 docs] Highlight styled object when hovering style key

### ISSUE THREAD

**Issue by williamboman** [JedWatson/react-select#2642]
![style-react-select](https://user-images.githubusercontent.com/6705160/40415547-699385dc-5e7b-11e8-8838-1dd511b6adaf.gif)

It's not very easy to understand which style key style which part of the select component. I think by having a static, always opened, Select component that changes its style in reaction to mouse hover on the style keys would make it easier to digest. Perhaps have all style objects be `opacity: 0.5` by default, and when hovering a style key apply `opacity: 1`. Thoughts?

**Comment by toddcoulson** [comment]
Yes this part of the documentation could stand to use some examples for each of the keys on how to use.

**Comment by eferrervaughn** [comment]
Anyone have a first stab this? or a workaround to figure it out?

**Comment by toddcoulson** [comment]
I have tried to rework several of these properties with the css and within the styles property, I could not find a way to get the component to autosize to fit the largest option in the drop down.

**Comment by trietlam** [comment]
@eferrervaughn I manage to guess the style key by setting `classNamePrefix`. Then on dev tools you can see the class names corresponding to each components

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
