### ISSUE TITLE
The v2 dropdown indicator clears the input visually, but not the value when onInputChange handles menu-close

### ISSUE THREAD

**Issue by AddictArts** [JedWatson/react-select#2645]
If I click the dropdown indicator and it closes the menu the visual "value" is clear, but not the actual input value. If you click the select area it does not clear the visual "value".

# Test case
```js
  handleSelectChange = (option, change) => {
    if (change.action === 'select-option') {
      this.inputValue = option.value
    }
  }

  handleInputChange = (newValue, change) => {
    const inputValue = newValue.replace(/\W/g, '')

    if (change.action !== 'menu-close') {
      this.inputValue = inputValue
    }

    return this.inputValue
  }

  render() {
    return <AsyncSelect
      cacheOptions
      defaultOptions
      loadOptions={ this.promiseOptions }
      openMenuOnClick={ false }
      placeholder={ 'Enter...' }
      noOptionsMessage={ () => 'No Match for Entry' }
      isClearable={ true }
      onChange={ this.handleSelectChange }
      onInputChange={ this.handleInputChange }
    />
```

I looked at v2 code and got to the below. Which I am handling, so I didn't find why visually it clears.
v2 Select.js
```js
  onMenuClose() {
    this.onInputChange('', { action: 'menu-close' });
    this.props.onMenuClose();
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
