### ISSUE TITLE
React-select doesn't set input=name and input=placeholder

### ISSUE THREAD

**Issue by ematipico** [JedWatson/react-select#2648]
I checked on Stackoverflow and here and couldn't find anything. I also inspected inside the examples of the website and nothing. The documentation says that it should set the property name of the input (it's hidden I know) but I cannot see anything. Is it something that will be fixed in v2.0? 

If it's not a bug, how can I fix the problem? I am doing a particular test/case where I need to check the name of the input (also needed to collect the values)

**Comment by jossmac** [comment]
In both `v1` and `v2` the property `name` will be passed to a hidden input for form consumption.
