### ISSUE TITLE
[V2] Make menuIsOpen accessible in components?

### ISSUE THREAD

**Issue by silversteez** [JedWatson/react-select#2649]
Loving this library, but I have an issue with a possible solution...

I have customized Option and the SingleValue to display an icon to the left of the label text. Currently if there is value selected and the menu is opened and the user has not entered any search input, SingleValue will display with the search input cursor will be blinking on the left side. Because I have added icons, the cursor now blinks _beneath_ the icon instead. Would love to be able to customize the display of SingleValue (or possibly just hide it) whenever the menu is open and search is enabled, but currently menuIsOpen does not seem to be accessible in any child components.

**Comment by silversteez** [comment]
Never mind! Found `props.selectProps` which has all the extra good stuff. :)

**Comment by mike391** [comment]
How do you access this on the inputcomponent?

**Comment by meechanism** [comment]
For anyone else asking the same as mike391, `selectProps` are now available on input component. Ref https://github.com/JedWatson/react-select/issues/3052

**Comment by mike391** [comment]
Awesome, thanks!
