### ISSUE TITLE
can you please add 1 more option to matchProp?

### ISSUE THREAD

**Issue by Vishal1419** [JedWatson/react-select#2654]
This is a feature request.

The documentation states that matchProp can be only one of : label, value or any. But that does not fit for my particualr use case.

Here is my code (which is impossible to search on):
```
            options={contacts.map(contact => ({ 
              value: contact.id,
              label: `${contact.name}\n${contact.phone}`.split ('\n').map ((item, i) => <p key={i} className="react-select-multiline-option">{item}</p>),
            }))}
```

In the above example, I am trying to show react select as follows:

![react app - google chrome_2](https://user-images.githubusercontent.com/19953475/40630825-c2acffdc-62f3-11e8-9f7e-5d351782b3e0.jpg)

As you can see that I can show an option in multiple lines. But when I try to search anything I don't get any results. I have used matchProp="label".

For this use case, if there was another property called search, then I would have written my code as follows to achieve my goal:

```
            options={contacts.map(contact => ({ 
              value: contact.id,
              label: `${contact.name}\n${contact.phone}`.split ('\n').map ((item, i) => <p key={i} className="react-select-multiline-option">{item}</p>),
              search: `${contact.name}\n${contact.phone}`,
            }))}
            matchProp="search",
```

This will allow me to search even if I am displaying anything in label.

Well you may argue, that I should use value property for searching. I can do that, but there will also be an issue. I want id of the selected Item. If I mix the id with name and phone and when I try to get selected item's id, I will have to do string manipulations. Then selection will work as expected, but searching will have an issue. As I don't want to search on id property.

Thanks for this great control.

**Comment by Vishal1419** [comment]
Got a css hack!!

Here is my fully working code:

```
    .Select-value-label {
      white-space: pre-wrap;
    }

    .Select-option {
      white-space: pre-line;
    }

```

Here is the select:

```
  options={contacts.map(contact => ({ 
    value: `${contact.id}`,
    label: `${contact.name}\n${contact.phone}`,
  }))}
  matchPos="any"
  matchProp="label"

```

**Comment by srbuser** [comment]
can you add the code how these css are applied to select dropdown?
