### ISSUE TITLE
Using newOptionCreator prop with Creatable only allows one new option to be created

### ISSUE THREAD

**Issue by rblakejohnson** [JedWatson/react-select#2657]
I'm using the newOptionCreator prop to add a property to the newly created option before saving the data to an endpoint. Maybe there's a better way to do this. Any pointers would be appreciated. Here's a reduced example of the issue: [https://codesandbox.io/s/xro102n334](https://codesandbox.io/s/xro102n334)
1. Try creating an option that is not in the list
2. Try creating another option that is not in the list and you're not allowed to create it.

**Comment by rblakejohnson** [comment]
I tried a different approach using onNewOptionClick. I successfully added the data to the newOption this way https://codesandbox.io/s/ykk983kqzz but I had to manage the state and the menu doesn't close when the newly created option is selected. So I'm going with this approach but would like to know if the newOptionCreator could work better.
I found this about manually closing the menu [https://stackoverflow.com/questions/44549186/how-to-close-menu-onnewoptionclick](https://stackoverflow.com/questions/44549186/how-to-close-menu-onnewoptionclick) that suggested using a ref and then calling this.mySelect.closeMenu() in the onNewOptionClick function but I couldn't get it to work. Also tried the linked issue.

**Comment by jossmac** [comment]
@gwyneplaine pretty sure this is resolved in v2, can you confirm?

**Comment by IanVS** [comment]
As far as I can tell, there's no longer any `newOptionCreator` in V2.  I _think_ we should use `getNewOptionData` instead, right?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
