### ISSUE TITLE
Trying to get a basic example working

### ISSUE THREAD

**Issue by albert-kam** [JedWatson/react-select#266]
Hi, i'm still quite new at using 3rd party react components and cannot get a simple example working. 

Here's my code 

```
<!DOCTYPE html>
<html>
  <head>
    <title>Test a simple select</title>
    <script src="/resources/js/react.js"></script>
    <script src="/resources/js/JSXTransformer.js"></script>
    <script type="text/jsx" src="/resources/js/classnames.js"></script>
    <script type="text/jsx" src="/resources/js/react-select.min.js"></script>
    <script type="text/jsx" src="/resources/js/react-input-autosize.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/resources/css/react-select.css">
  </head>
  <body>
        <div id="example"></div>
        <script type="text/jsx">
            var options = [
                { value: 'one', label: 'One' },
                { value: 'two', label: 'Two' }
            ];

            function logChange(val) {
                console.log("Selected: " + val);
            }

            console.log("options: " + toString(options));
            React.render(
                <Select
                    name="form-field-name"
                    value="one"
                    options={options}
                    onChange={logChange}
                />,
                document.getElementById('example')
            );
        </script>
  </body>
</html>
```

From the javascript console, i get these 

```
Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
Warning: Only functions or strings can be mounted as React components.
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
```

I wonder where i mess up.

Please share your insights, thank you.

**Comment by aldanor** [comment]
Same thing here, using the bower version.

**Comment by mxaly** [comment]
+1

**Comment by ranicas** [comment]
+1

**Comment by carlo** [comment]
Thanks, @misak113!

**Comment by mordonez-me** [comment]
This do not work when using requirejs, any solutions?

**Comment by misak113** [comment]
When u use requirejs it should work automatically, because dependency is required in right order. However maybe requirejs is not supported for this package. I recommend use browserify if it is possible.
But my experience with this package react-select is not good. So let try to find another or basicaly develop self solution. I did it and it was not dificult.

**Comment by creativewax** [comment]
hi there,

i am really sorry but i keep having an issue where i keep getting an error like so

Cannot find module 'react-don'

i have tried installing everything via bower and done as above and this doesn't solve my issue as well, any help appreciated :)

<!DOCTYPE html>
<html>
<head>

    <title>Test a simple select</title>

    <link rel="stylesheet" type="text/css" href="css/react-select.css" />

    <script src="bower_components/react/react.min.js"></script>
    <script src="bower_components/classnames/index.js"></script>
    <script src="bower_components/react-input-autosize/dist/react-input-autosize.min.js"></script>
    <script src="bower_components/react-select/dist/react-select.min.js"></script>

</head>
<body>
<div id="example"></div>
<script type="text/jsx">
    var options = [
        { value: 'one', label: 'One' },
        { value: 'two', label: 'Two' }
    ];

    function logChange(val) {
        console.log("Selected: " + val);
    }

    console.log("options: " + toString(options));
    React.render(
            <Select
                    name="form-field-name"
                    value="one"
                    options={options}
                    onChange={logChange}
            />,
            document.getElementById('example')
    );
</script>
</body>
</html>

**Comment by TigerC10** [comment]
@creativewax - You're talking about Issue #526
