### ISSUE TITLE
Feature Request: async cache-busting

### ISSUE THREAD

**Issue by timhwang21** [JedWatson/react-select#2661]
# Request

The ability to empty `<Select.Async/>`'s cache.

# Use Case

We have a fairly search endpoint with parent-child data, where we only want to reveal the child data when the parent value is already "enabled" somewhere.

Example: there is a location 'New York' in USA and 'York' in the UK. When supplying 'York' to our search API, it will return nothing if neither USA or UK are enabled, `[New York]` when USA is enabled, and `[New York, York]` when both USA and UK are enabled.

The problem is that because the search string is the same, the smart cache prevents the new request from being made.

# Proposed Interface(s)

## 1. Second argument to [`loadOptions()`](https://github.com/JedWatson/react-select/blob/master/src/Async.js#L87)

Something like `invalidateCache: boolean`. Pretty straightforward. For future proofing, maybe an `options` object would be good as well.

## 2. Allow `ref`s to provide access to an instance method `invalidateCache()`

Would instantly empty the cache. This method provides the most flexibility but is also a bit messy and imperative. A similar approach is used in [`react-virtualized`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md#forceupdategrid) `forceUpdateGrid()`.

```
<Select.Async ref={node => this.Async = node}/>

// when desired
this.Async.invalidateCache();
```

It's a pretty trivial feature to implement, so depending on how acceptable the proposed interfaces are, I can send a PR asap. Thanks! :)

(Question re: v2 -- are releases for v1 still planned / PRs for v1 still accepted?)

**Comment by timhwang21** [comment]
So, I've found that option 2 sort of works as-is by using a ref `node => this.node = node` and doing `this.node._cache = {}` wherever you want it. Sort of imperative, but it works and I think it's an acceptable solution, so I can just make a documentation PR if that's preferred. Thanks!

**Comment by jossmac** [comment]
@gwyneplaine pretty sure this is resolved in v2, can you confirm?

**Comment by timhwang21** [comment]
This issue is resolved for me, so closing this. Thanks all!

**Comment by rangelvarnier** [comment]
> Esse problema foi resolvido para mim, fechando isso. Obrigado a todos!

Could you show an example of how you solved this problem? I'm using V2 and it does not clear the cache

**Comment by jechlin** [comment]
This really does not work in v2.4.3. Setting cacheOptions to a different value than previously does not clear the cache, nor could I make the workaround suggested above work.

**Comment by oudoulj** [comment]
I use **v3.0.4** and I'm struggling with some kind of funky behavior probably due to the cache.
I have `cacheOptions={false}` in an _async select_ being populated through _fetch/promise_ calls but it does not seem to be doing what its name says.
The console.log shows the correct data at each call but the list is populated with partly wrong data 😕 
Any update on either a fix or a workaround on this matter ?
Thanks!
