### ISSUE TITLE
Right click in search box not showing required options

### ISSUE THREAD

**Issue by ac13793** [JedWatson/react-select#2664]
Right click in `react-select` search-box not giving required options.
In genenal when we right click in any input box, below options are shown.
![image](https://user-images.githubusercontent.com/5982099/40763379-663119ca-64c2-11e8-91a1-d87317116501.png)

In `react-select` search input box, it is showing as below:
![image](https://user-images.githubusercontent.com/5982099/40763421-81bd82b4-64c2-11e8-8be4-fc242444dbdd.png)

It is because of `div` is getting used to show placeholders instead of `placeholder` property of input box

**Comment by jossmac** [comment]
Unfortunately we need some smoke and mirrors to make react-select behave as expected in other respects.

Please note that if a user clicks in the "actual" input they will be presented with the applicable menu:

![image](https://user-images.githubusercontent.com/2730833/42299841-c0982a62-8050-11e8-996c-c667acbc816d.png)
