### ISSUE TITLE
Creatable - should allow asynchronous creation of options (when depending on further user input or an API call when adding new options)

### ISSUE THREAD

**Issue by m-andrew-albright** [JedWatson/react-select#2665]
# Feature Request for `Creatable`

Allow `newOptionCreator` to work with `Promise`s, such that options can be asynchronously created.  Should also handle rejected `Promise`s elegantly such that cancelling the creation of a new tag is possible by rejecting the `Promise`.

>What's your use case? (Tell us about your application and what problem you're trying to solve.)

In my application, the user should be able to add tags to the system, specifying both text and color; the color specification is intended to be done in a popover color-picker component, which requires user input, which is of course asynchronous
>What interface do you have in mind? (What new properties or methods do you think might be helpful?)

It would be best if the existing `newOptionCreator` could just be "smart" and handle `Promise`s in stride, but it would be almost as good to allow providing `newOptionCreatorAsync` (or similar) to specify that the function should return a `Promise` that resolves to the newly created option OR rejects to cancel.

>Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

😅 Alas, I can't!  This would be very helpful for my team, however, so when the time comes for me to implement the business feature, if the functionality does not yet exist in `react-select`, I may be able to spend some time and contribute it msyelf.

**Comment by jossmac** [comment]
@gwyneplaine pretty sure this is resolved in v2, can you confirm?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
