### ISSUE TITLE
noResultsText disables Tabbing

### ISSUE THREAD

**Issue by Tamakimouto** [JedWatson/react-select#2666]
Not sure if this counts as a bug or feature request.

There's an example of this on the [live demos.](http://jedwatson.github.io/react-select/)
Scroll down to "GitHub users (Async with fetch.js)" and click into it, notice how you can't tab out of the field; now click into the previous field and start tabbing, it'll tab over the field normally.

**Comment by jossmac** [comment]
Hi @Tamakimouto,

This is actually inline with native select behaviour -- once the menu is open you cannot tab out of the field.
