### ISSUE TITLE
add openedPlaceholder props

### ISSUE THREAD

**Issue by lauterry** [JedWatson/react-select#2671]
Hello

It would be nice to have a focusedPlaceholder props.

The use case is to replace the placeholder when the user open the Select.

For instance, when the select is closed, I want to display "All countries" and when the user opens the Select, I want to display "Please select a country"

Best regards

**Comment by jossmac** [comment]
Hi @lauterry,

Thanks for opening this issue, sounds like a great use case. Whilst currently unavailable, you can achieve this in v2 with something like:

```jsx
const Placeholder = ({ isFocused }) => (
  <span>{isFocused ? 'Please select a country' : 'All countries'}</span>
)

<Select
  ...
  components={{ Placeholder }}
/>
```

**Comment by L5eoneill** [comment]
In v2, Placeholder does **not** have an 'isFocused' property. It would be nice if it did!

**Comment by apennell** [comment]
I found the property available as `props.selectProps.menuIsOpen` and was able to accomplish @jossmac's suggestion by adjusting the code to the following:
```js
const Placeholder = ({ selectProps: { menuIsOpen } }) => (
  <span>{menuIsOpen ? 'Type to search...' : 'Select...'}</span>
);
```

**Comment by L5eoneill** [comment]
Awesome! Thanks

**Comment by jossmac** [comment]
My bad, apologies @L5eoneill. Nice catch, thank you @apennell!
