### ISSUE TITLE
[v2] Allow for unclearable (preset) options

### ISSUE THREAD

**Issue by daggmano** [JedWatson/react-select#2675]
Implement unclearable options in v2 (as provided by `clearableValue: false`) in previous version.

**Comment by Ishneetkaur** [comment]
Implement unclearable options in v3 (as provided by clearableValue: false) in the previous version.

**Comment by ebonow** [comment]
Greetings,

Based on the reply to the PR https://github.com/JedWatson/react-select/pull/2683, I will be closing this issue.

It would seem that this inspired the [Fixed Options](https://react-select.com/home#fixed-options) example on the react-select documentation in case anyone wanted to inquire further on how to implement something like this.
