### ISSUE TITLE
Already selected option gets the role option, and it shouldn't

### ISSUE THREAD

**Issue by nikini** [JedWatson/react-select#2676]
After the option has been selected, the element in the DOM that displays the option still has the `role="option"`. That should not be the case since that is not standard.

### How the resulting html looks like
```
<div class="Select-value">
    <span class="Select-value-label" role="option" aria-selected="true" id="react-select-2--value-item">
        One
    </span>
</div>
```

### Where can you see it
The default Plunker link replicates this behaviour: https://plnkr.co/edit/dHygFMWWqVwaRAfpEmbn?p=preview

### Possible solution
Add an extra `role` property to the `ValueComponent` and when you're rendering it in the selected values section, then don't provide any role.

**Comment by jossmac** [comment]
https://www.w3.org/TR/2010/WD-wai-aria-20100916/roles#option
