### ISSUE TITLE
Select/Multiselect input typing

### ISSUE THREAD

**Issue by milencheto** [JedWatson/react-select#2678]
Is there any way to forbid typing in the select/multiselect input field?
![2018-01-04_1420](https://user-images.githubusercontent.com/10586251/40981551-da2e9e9a-68e3-11e8-9334-e53446283f64.png)

**Comment by omaotzu** [comment]
searchable={false} ?

**Comment by milencheto** [comment]
yes, it is! Thank you very much :)

**Comment by jsms90** [comment]
`isSearchable` if you're using v2 :+1:

**Comment by omaotzu** [comment]
@jsms90 cheers man! havent migrated yet but will be needing that when I do

**Comment by jossmac** [comment]
@milencheto in the future, please close issues when they are resolved.
