### ISSUE TITLE
[v2] common props for <Input />

### ISSUE THREAD

**Issue by mike1808** [JedWatson/react-select#2680]
Hi all! I was migrating my old code to the v2 and it is amazing. However, I have several obstacles making to hack and patch.

What is the motivation not to include `commonProps` to `<Input>` component?

**Comment by marcselman** [comment]
I noticed the same thing.

**Comment by samueldepooter** [comment]
Looking for the same thing! No update on this yet? Can take a look to create a PR for it.

**Comment by mike1808** [comment]
@samueldepooter I didn't create PR because I thought the author had some intentaions for it, but I guess, they just didn't need that for that time.

**Comment by samueldepooter** [comment]
> @samueldepooter I didn't create PR because I thought the author had some intentaions for it, but I guess, they just didn't need that for that time.

@mike1808 yes it's a quick fix. Not sure why you wouldn't want these props present. Hopefully it can be answered soon 👍

**Comment by gwyneplaine** [comment]
@mike1808 we've passed a majority of the needed props from common props into the Input component now.
selectProps being the latest to be added to the set of props to be passed down as of v2.2.0

Closing this issue now

Feel free to reopen if this is still an issue.
