### ISSUE TITLE
plnkr link in issue boilerplate presents a broken example

### ISSUE THREAD

**Issue by Olliebaba** [JedWatson/react-select#2681]
The example in this link appears to be broken. It also is using react v15 and react-select v1
https://plnkr.co/edit/dHygFMWWqVwaRAfpEmbn?p=preview

**Comment by jossmac** [comment]
@Olliebaba the link you provided is working for me.

Please comment with more information if this is still a concern, and needs to be re-opened.

**Comment by Olliebaba** [comment]
@jossmac  - I guess, it just seems to me that it's broken. Since `value` is a static string, the value does not update on change. I thought this was odd behavior as a boilerplate. And I was mentioning versioning because it does not reflect latest (or recent) `react-select`. Not sure if `react` version would need to be updated along side it.

If all of this is by design, please ignore me. :)

**Comment by jossmac** [comment]
@Olliebaba I understand the confusion. The plunker exists to help consumers demonstrate their issue, so we can better diagnose the problem. It makes as few assumptions as possible about the state of their application.
