### ISSUE TITLE
[v2] Backspace on single select results in [] rather than {}

### ISSUE THREAD

**Issue by ernestopye** [JedWatson/react-select#2682]
# Are you reporting a bug or runtime error?
Bug. To reproduce, you can use the link below. Note: This is NOT in isMulti mode. [] makes sense for isMulti.
[Code Sandbox](https://codesandbox.io/s/x977z5p7wo)

1. Select a value.
2. Click on the select to expand the options menu.
3. While the menu is still open, hit backspace.
4. Actual: onChange is called with []
5. Expected: onChange is called with {}

This seems to be an issue that has happened in the past.

Let me know if I can provide any other details. The code sandbox above is simply one of your examples, but with an added console.log call from onChange, nothing else.

**Comment by Darep** [comment]
Also ran into this 🙂 Solved for now with a wrapping onChangeHandler:

```javascript
  onChangeHandler = (value, actionMeta) => {
    if (this.props.onChange) {
      // fix react-select returning [] on clear
      if (Array.isArray(value) && value.length === 0) {
        this.props.onChange({}, actionMeta);
      } else {
        this.props.onChange(value, actionMeta);
      }
    }
  };
```

**Comment by vincentjames501** [comment]
Just ran into this one today. Definitely doesn't make sense to return an empty array if it's a single select. The item or null is what makes sense to return IMO.

**Comment by someden** [comment]
https://github.com/JedWatson/react-select/blob/18219f5271705ef150ad16177db43f0c44f0413d/src/Select.js#L802-L810

`single select, by default, IS NOT clearable`, but `backspaceRemovesValue` by default is `true`, so single select can be cleaned by backspace, it is very confusing.

**Comment by grassick** [comment]
I've created a PR (https://github.com/JedWatson/react-select/pull/3110) and put a temporary corrected version up at `github:mWater/react-select#fix_2682_built` for anyone else who is blocked by this bug.

**Comment by Thebarda** [comment]
Here is a workaround that works with search input and clearable select :
```javascript
onSelectChange = item => {
    // Prevent backspace in input (item.length === undefined)
    if (item === null || item.length === undefined) {
      // Write your code here
    }
  }
```

I hope it help someone

**Comment by kstratis** [comment]
Basically if that’s the case, then why fire onChange in the first place?
