### ISSUE TITLE
[v2] Google Chrome Console Noise

### ISSUE THREAD

**Issue by koofka** [JedWatson/react-select#2684]
Using the v2 react-select component during for a current dev project and noting a great deal of "suggestion" console noise for two issues.  Using Mac OSX 10.12.6 and have observed this behavior on both Chrome versions 66 and 67 dev tools.  

One warning  each time you open a select menu with a scrollable list of options when the Chrome console returns:

react-select.es.js:571 [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Secondarily have also noticed an occasional warning that appears related to the react-input-autosize dependency which reports the following to the Chrome console:

AutosizeInput.js:49 [Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

The autosize deprecation warning also appears referenced in that repos project issues: https://github.com/JedWatson/react-input-autosize/issues/138

Functionally these don't appear to be of great concern, but am a bit worried that they may come up as issues during QA.

Thanks much and very cool component.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
