### ISSUE TITLE
Add props continueOnSelect, stopContinuing

### ISSUE THREAD

**Issue by keerthis** [JedWatson/react-select#2685]
# Are you making a feature request? Yes
Provide as much information as possible about your requested feature. Here are a few questions you may consider answering:

*   What's your use case? (Tell us about your application and what problem you're trying to solve.)
My case is to have a singe field in form to help fill multiple other fields by providing standard format of input pattern. Using react-select to show all the "templates" of patterns as drop down option and keep filtering the template as the user starts typing in a particular pattern. The problem is one section of this party needs to be type ahead search, so i need the drop down options to load from remote when it come to this section of the input. Now once the user clicks on one of the options, then currently there is no way to "continue typing" as this is not the end of the pattern.
*   What interface do you have in mind? (What new properties or methods do you think might be helpful?)
My solution is to have "continueOnSelect" prop which will on 'selectValue' method set the 'updatedValue' to the rendered label value and in 'shouldShowValue' will return false for "continueOnSelect" untill "stopContinuing" is sent as true. These flags will work only when closeOnSelect is false.

Let me know if this looks like a valid feature to have. I have already implemented this changes in a flok on my project and works like a charm. I will raise a PR here too.

**Comment by jossmac** [comment]
Hi @keerthis thank you for raising this issue before creating a PR!

Unfortunately, this isn't really something we intend to support. I recommend having different input elements to support your needs:
- the first would be async, to select a "template"
- once a "template" is selected, provide the next relevant input element (and maybe hide the first?)
