### ISSUE TITLE
v2 documentation not showing data structure

### ISSUE THREAD

**Issue by JuhQ** [JedWatson/react-select#2691]
If you look at for example this url https://deploy-preview-2289--react-select.netlify.com/advanced#replacing-builtins and open the source code.
You can see line `import { colourOptions, groupedOptions } from '../data';` which tells us _absolutely_ nothing what the data structure should be.

Please, please, for the examples, please create the variable and its content in the example and not in some visible file that we can not access! This is frustrating and infuriating, this is just **bad** documentation.

**Comment by JuhQ** [comment]
The least we could do is to add link to https://github.com/JedWatson/react-select/blob/v2/docs/data.js in those examples :)

**Comment by matttk** [comment]
The docs don't seem to show anything. I'm currently fighting with CreatableSelect and have the same problem and more. Nice to see at least what the mystery data is.

**Comment by yazeed** [comment]
Hmm, any update here? I'm still looking for anywhere that shows the colourOptions data structure.

**Comment by jkrclaro** [comment]
> Hmm, any update here? I'm still looking for anywhere that shows the colourOptions data structure.

If it's of help to anyone looking, react-select looks for dictionary of keys ["value", "label"] as per the initial options in the Getting Started guide, e.g.

```
const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
]
``` 

I do think it would be much better if colourOptions would be written out somewhere though.

**Comment by bladey** [comment]
Hi all,

You can see the data structure now in the Codesandbox link next to the example, direct link is here - https://codesandbox.io/s/bzdhr?module=/example.js&file=/docs/data.js
