### ISSUE TITLE
Autosize={false} does not seem to work

### ISSUE THREAD

**Issue by jeshals** [JedWatson/react-select#2693]
As per the documentation on Github the autosize attribute when passed with value of {false} does not seem to restrict the width of the input, the input element keeps expanding based on the input.

This issue was raised years back and I am wondering if the issue was fixed?

https://github.com/JedWatson/react-select/issues/860

Please help with a solution.

**Comment by wimbush** [comment]
I'm still having this issue.

**Comment by prateek3255** [comment]
I'm also having this issue

**Comment by spideyinf** [comment]
Hi there,

I also have this issue and thinking of finding a css way... It will be nice if you can look at this

**Comment by jossmac** [comment]
@jeshals, @wimbush, @prateek3255, @spideyinf can someone please provide a [sandbox](https://codesandbox.io) with the issue occurring in v2?
