### ISSUE TITLE
[V2] Is there an NPM Package?

### ISSUE THREAD

**Issue by chobo2** [JedWatson/react-select#2696]
Hi

I don't see any mention of an npm package for version 2. Is there one?

**Comment by CNaismith** [comment]
Hi @chobo2 

You can install v2 of react-select by doing `npm install react-select@next`. As of now `@next` is targetting 2.0.0-beta.6. You can see this by going to the versions tab on npm.

**Comment by zhammer** [comment]
More info on the readme:

## v2.0.0 Beta

A major update to React-select is coming! v2 is all new with some major API improvements, a powerful
new styles and components API, and support for some long-requested features like option groups.

To install the new version:

```
yarn add react-select@next
```

Check out the [v2 documentation](https://deploy-preview-2289--react-select.netlify.com)
and [upgrade guide](https://deploy-preview-2289--react-select.netlify.com/upgrade-guide).

**Comment by chobo2** [comment]
@CNaismith 

Weird, I tried that but it did not work, I must have typed it in wrong .

@zhammer 

I was not aware that yarn and npm share the same command, as I don't really  know anything about yarn

**Comment by gwyneplaine** [comment]
Looks like this is resolved @chobo2 
closing
