### ISSUE TITLE
closeOnSelect Multi Select Box

### ISSUE THREAD

**Issue by chobo2** [JedWatson/react-select#2697]
Hi

In version 1 there was "closeOnSelect" for multi select but I am not seeing this in the v2 documentation.

Thanks

**Comment by smoleniuch** [comment]
Hi,

In version 2 you should use 'closeMenuOnSelect' property.

Cheers!

**Comment by chobo2** [comment]
ah, cool.

am I using it right though?`  <Select closeOnSelect="false" isMulti options={options} />`

**Comment by gwyneplaine** [comment]
thanks @smoleniuch, as specified above @chobo2 this case is covered in our docs. 
please use the closeMenuOnSelect prop 
```javascript
<Select closeMenuOnSelect={false} isMulti options={options}/>
```

Please don't use 'false' as a string, the closeMenuOnSelect expects a boolean value, the string 'false' will coerce to true.
