### ISSUE TITLE
[v2] - Options.title Missing?

### ISSUE THREAD

**Issue by framerate** [JedWatson/react-select#2699]
Love this module!

We just upgraded to v2 and were previously passing in options like:

```
{
  value: 'x',
  label: 'y',
  title: 'z'
}
```  

(like here: https://github.com/JedWatson/react-select/blob/7c0ffe4a757175146ac0c922bb039013dba29d7b/examples/src/components/Multiselect.js#L7)

But we noticed that title (for the browser to display the title on hover) is no longer getting passed down. I tried to locate where this change happened but I'm having trouble locating it. Is this an easy fix? Or could you point me in a direction and I can issue a PR?

Thanks!

(cc: @ctoppel)

**Comment by sahibjotsaggu** [comment]
@framerate I don't think this is possible if you just use the built-in option component. But if you create a custom option component, it can be done:

https://codesandbox.io/s/03wn2v4mml (hover over the options to see the colour hex code)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
