### ISSUE TITLE
onOpen and onClose features do not work

### ISSUE THREAD

**Issue by jeshals** [JedWatson/react-select#2700]
<Select
          className="s_d_f"
          id={id}
          name="searchInput"
          onClose={() => this.toggleOptions(false)}
          onOpen={() => this.toggleOptions(true)}
          placeholder={label}
          required={required}
          tabIndex="-1"
          value={this.state.selectedValue}
          options={this.state.valueOptions}
        />

**Comment by jossmac** [comment]
![image](https://user-images.githubusercontent.com/2730833/42298885-99edc61a-804b-11e8-8773-403c6d4932e8.png)

Tested in CodeSandbox -- the issue must be elsewhere in your code

**Comment by mitulmarsonia** [comment]
I have same issue. Can you please help me out ?

**Comment by cicco94** [comment]
Hi, use the onMenuOpen and onMenuClose events
![react-select](https://user-images.githubusercontent.com/18578156/73470678-2989e800-4380-11ea-96db-79a2b975b4fd.PNG)
