### ISSUE TITLE
[v2] There is nothing different when isLoading={true}

### ISSUE THREAD

**Issue by trungdq88** [JedWatson/react-select#2703]
Is this a bug? (can be reproduced on the main demo page: https://deploy-preview-2289--react-select.netlify.com/home)

![promotion](https://user-images.githubusercontent.com/4214509/41328914-ba7a3a16-6ef4-11e8-9314-eb2bc32bce4e.gif)

**Comment by mike1808** [comment]
@trungdq88 yes, it is a bug. See #2688

**Comment by gwyneplaine** [comment]
Closing this to keep track of the issue and solution in #2688, thanks for reporting this @trungdq88
