### ISSUE TITLE
ie11 errors

### ISSUE THREAD

**Issue by ryanrain** [JedWatson/react-select#2705]
hello all, my apologies in advance for this half-ass bug report... hopefully i'll remember to improve it once i meet this deadline :)

just a quick note that beta 6 presented fatal errors for me in ie11 upon initial click on the component including an inability to find includes on the array prototype. including a [shim bundle](https://github.com/airbnb/js-shims) fixed things.

```
        <Select
          options={options}
          onChange={(e: ReactSelectResult) => this.handleChange(e)}
          name={this.props.input.name}
          placeholder="Select a Specialty..."
          maxMenuHeight={190}
          styles={customStyles}
          defaultValue={options[0]}
        />
```

thanks!

**Comment by jprosevear** [comment]
Related to #2701

**Comment by gwyneplaine** [comment]
Closing this to keep track of the issue in #2701  thanks for reporting @ryanrain
