### ISSUE TITLE
[V2] Option to disable CSS-in-JSS entirely

### ISSUE THREAD

**Issue by majelbstoat** [JedWatson/react-select#2706]
I have a NextJS app that is server side rendered, which uses the built in styled jsx. I'd really rather not have to add emotion-server to the application, just so there's no flash of unstyled select boxes. I would also much prefer to keep my style definitions to one system and one format.

I absolutely adore the functionality of react-select, but enforcing a specific CSS-in-JS solution for a component that will have to live within so many different kinds of environments seems like a misstep. IMO, the things it offers, like theming, should be done at an application- or framework-level, not a single component level.

Using className alone somewhat gets me there, but I now have two sets of CSS classes and two styling systems competing for primacy on the page, which is hard to debug, diagnose, and manage.

I realise that it's probably not going away, and assuming that is a non-starter, can we have the ability to just disable emotion, and do all the styling ourselves? That will be painful, but at least there will only be one authority.

**Comment by SilencerWeb** [comment]
I like this idea. It was awesome to style like [here](https://github.com/JedWatson/react-select/issues/1679#issuecomment-307016615) using styled-components in v1, but not anymore, now they provide adding className to any element but it's crazy to add all classNames by yourself, in v2 styling became much more complicated than it used to be in v1

**Comment by gwyneplaine** [comment]
@JedWatson  this is a valid line of inquiry, and may be in lined with roadmap for an unthemed select export. Would be nice to get your thoughts on this.

**Comment by jordmccordgcv** [comment]
This is a very valid point and a reason for me not currently upgrading to the latest version, I use this library in several projects and all implementations have custom styles, some of which already use CSS-in-JS libraries. I'm interested to find out the rational behind this decision?

**Comment by wszgxa** [comment]
> While we encourage you to use the new Styles API, it's good to know that you still have the option of adding class names to the components to style via CSS.

It's hard to add CSS by class name. Because `emotion` will add css in `<style>....</style>`. If you add CSS by `<link rel="stylesheet" href="xx/main.css">`, you must add many `!important` in your CSS file to rewrite the base css.

**Comment by edmorley** [comment]
This is a blocker for us using react-select unfortunately.

The use of emotion means:
* CSP violations since requires `unsafe-inline` (see also #2917)
* bundle size bloat (see https://bundlephobia.com/result?p=react-select@2.1.1)

If there was a (tree-shakeable) way to disable emotion when using react-select, it would avoid both issues.

**Comment by WitoTV** [comment]
This is as well blocking me from using react-select. I have all styles compiled to one style.css file so I would love to have an option to get rid of inline styles and see some normal classes not `css-1hwfws3`.
Using existing classes makes it really hard to even try to write my own styling that makes any sense...

Please give us option to disable CSS-in-JSS.

**Comment by eckdanny-osi** [comment]
The docs indicate `react-selec`t is friendly with css-modules. I too am looking to avoid translating a bunch of [s]css to css-in-js. Ideally I'd like to opt out of css-in-js entirely, style components with our existing sass constructs, and pass className mappings via props or context.

Does a working example of using css-modules exist?

**Comment by bbay** [comment]
is this open to consideration?
It would be really nice to have the option to either embrace css-in-js or disable it.

For projects that are not yet into the css-in-js craze it makes sense to just disable it and use the good 'ol stylesheets.

**Comment by simondiep** [comment]
I'm working on updating a legacy app from v1 to v2 and came across this issue.  My component now looks really weird.  Any chance backwards-compatibility could be added?

**Comment by sedenardi** [comment]
This issue and the bundle size issue mentioned in https://github.com/JedWatson/react-select/issues/2972 have led our team to hold off indefinitely from upgrading to V2. Unfortunately I don't have any experience with emotion, so don't feel comfortable submitting a PR to address the issue (nor do I know if it would be accepted, given the lack of comment from contributors to this issue).

We love this package and are very grateful for all the hard work the contributors have put into it.

**Comment by ArranJacques** [comment]
This makes working with react-select incredibly frustrating as it forces an opinionated way of styling the components on you. It would be incredibly useful to have an option to disable css-in-js completely and instead just pass standard class names to the components. This then gives us the freedom to choose how we style the components.

**Comment by lukewhitmore** [comment]
I wholeheartedly agree .. we need to be able to disable CSS-in-JS.

The fact that this route has been chosen, and is impossible to override has stopped us from using react-select.

**Comment by charlex** [comment]
Emotion seems to be racking up performance hits in my tests. Would be nice if there was a way to simply turn it off. 

Perhaps there could be a webpack plugin that excludes emotion and we maintain a community CSS file?

**Comment by jharris4** [comment]
In case it helps anyone, I literally just forked react-select at version 1.30 into a new package called `react-select-css`, and also upgraded the components to no longer use deprecated lifecycles (warnings in React 16.9).

I haven't gotten around to making a README etc, but it's published to npm and working great for me: https://www.npmjs.com/package/react-select-css

**Comment by StarpTech** [comment]
Great issue and I experience the same. I don't want to use a component that adds unnecessary complexity / size to my application.

By the way, that is the big strength of Cascading StyleSheet that you aren't coupled to the specific component :smile:

Providing only a default theme in a SASS file and working with `className` and `classNamePrefix` would be great. 

- In emotion, you could use https://emotion.sh/docs/nested
- In styled-components https://styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting

This approach would be compatible with CSS and CSS-in-js solutions without adding any overhead.

### Example in CSS/SASS
```jsx
<style>
.react-select {
   padding: 4px;
 }
</style>

<Select css={select}></Select>
```
### Example in styled-components
```jsx
const Thing = styled.div`
  .react-select {
    padding: 4px;
  }
`
<Thing>
	<Select></Select>
</Thing>
```

### Example in emotion
```jsx
const select = css`
  .react-select {
    padding: 4px;
  }
`
<Thing>
	<Select css={select}></Select>
</Thing>
```

**Comment by onionhammer** [comment]
This library doesn't work too well with CSS modules OOTB as far as I can tell.

In React if I import styles via

`import styles from some.module.css`

there is no effective way to utilize the `styles` to style the react-select.

**Comment by gregmartyn** [comment]
@onionhammer we're able to get it to work with what feels like a hack:
jsx:
```
<Select
	className={style.location}
	classNamePrefix={style.location}
```

and in css
.```
.location {
	{rules for the select itself here}
	& .location__control {
		{rules for the select's control here}
	}
}
```

more info https://react-select.com/styles#using-classnames

**Comment by ebonow** [comment]
Greetings, 

A solution has been posted here to disable the default styles: https://github.com/JedWatson/react-select/issues/2872#issuecomment-654251799 While the generated classNames will still be present in the DOM, the corresponding styles will not be added to the page.

```jsx

const styleProxy = new Proxy({}, {
    get: (target, propKey) => () => {}
});

<Select styles={styleProxy} {...} />
```

Here is a working demo to illustrate it: [codesandbox](https://codesandbox.io/s/react-select-unstyled-tx8z9?file=/src/App.js)

This should satisfy this condition such that this issue can be closed. If anyone has any other questions or concerns, feel free to reply and this can be re-opened if necessary.

**Comment by timakhalaya** [comment]
> Greetings,
> 
> A solution has been posted here to disable the default styles: [#2872 (comment)](https://github.com/JedWatson/react-select/issues/2872#issuecomment-654251799) While the generated classNames will still be present in the DOM, the corresponding styles will not be added to the page.
> 
> ```js
> const styleProxy = new Proxy({}, {
>     get: (target, propKey) => () => {}
> });
> 
> <Select styles={styleProxy} {...} />
> ```
> 
> Here is a working demo to illustrate it: [codesandbox](https://codesandbox.io/s/react-select-unstyled-tx8z9?file=/src/App.js)
> 
> This should satisfy this condition such that this issue can be closed. If anyone has any other questions or concerns, feel free to reply and this can be re-opened if necessary.

This approach in no good at all

**Comment by Methuselah96** [comment]
We're planning on create an "unstyled" version of react-select where you can bring your own styles.

**Comment by timakhalaya** [comment]
> We're planning on create an "unstyled" version of react-select where you can bring your own styles (or turn them off completely).

That would solve a ton of issues then 🚀

**Comment by loicnestler** [comment]
@Methuselah96 is there any ETA for this?

**Comment by Methuselah96** [comment]
No, there's no ETA at the moment. The top two priorities are fixing menu positioning and creating an unstyled version but it's hard to estimate how soon we can finish those up since the amount of time we can work is not always consistent.

**Comment by zedtux** [comment]
@Methuselah96 any progress on that "unstyled" version please ?

**Comment by Uni2K** [comment]
How is it going with the unstyled version? It would be great to have a prop to disable "emotion css" completely.

**Comment by addlistener** [comment]
I guess this is still relavant? 

Especially if you need your own instance of emotion there's conflict

https://github.com/emotion-js/emotion/issues/2383
