### ISSUE TITLE
[2.0] Disabling options doesn't work anymore

### ISSUE THREAD

**Issue by TheSuperFly** [JedWatson/react-select#2709]
Hello, 

Disabling an option doesn't work anymore.

The documentation says we should just add a `disabled: true` to the options to make it grayed but now it's not working, even by setting `isOptionDisabled={() => false}`.

Any ideas?

**Comment by smoleniuch** [comment]
Hi,

Can you point the link to the documentation where it states that passing disabled property to the options marks it as disabled?I can not find it.

Anyway, `isOptionDisabled` works, [here](https://codesandbox.io/s/6vnkjm2n4r) is working example.

Your function return false so the option is not disabled.

Cheers!

**Comment by gwyneplaine** [comment]
@TheSuperFly, as specified by @smoleniuch above, we expose an isOpbionDisabled prop of the following shape (option) => !!option.isDisabled, which defaults to checking for a 'isDisabled' property on your option.

**Comment by jack8966** [comment]
@gwyneplaine, but the document says:
`You can use a disabled property to indicate whether the option is disabled or not.`
This might misleading other peoples, thx!!!

**Comment by jonlambert** [comment]
The example above is not working correctly. I'm unable to disable options through either `isOptionDisabled` or by passing `isDisabled` as a parameter to the option.

**Comment by dlikhten** [comment]
The examples use a 'disabled' property which was misleading.

**Comment by lzhuor** [comment]
@dlikhten Absolutely!!! I was stuck here because of the example!!!
