### ISSUE TITLE
Bogus characters in Select-input when searchable={false}

### ISSUE THREAD

**Issue by aldanor** [JedWatson/react-select#271]
This happens on version `0.5.1` via bower.

When using `searchable={false}`, the `Select-input` contains bogus symbols, and the resulting DOM looks like this:

``` html
<div class="Select has-value" data-reactid=".0.0.1">
  <input type="hidden" name="form-field-name" value="one" data-reactid=".0.0.1.0">
    <div class="Select-control" data-reactid=".0.0.1.1">
      <div class="Select-placeholder" data-reactid=".0.0.1.1.0:$placeholder">One</div>
      <div class="Select-input" tabindex="0" data-reactid=".0.0.1.1.1">Â&nbsp;</div>
      <span class="Select-arrow-zone" data-reactid=".0.0.1.1.2"></span>
      <span class="Select-arrow" data-reactid=".0.0.1.1.3"></span>
    </div>
  </div>
</div>
```

![screen shot 2015-06-25 at 00 52 25](https://cloud.githubusercontent.com/assets/2418513/8344092/85a18870-1ad4-11e5-9f1e-fb59d0d61ec8.png)

This doesn't seem to occur when using the default `searchable={true}`.

**Comment by bruderstein** [comment]
Is this still an issue with >=0.6.0?

**Comment by VitaliP** [comment]
yes it does 

issue is " " when u create empty searchable div (not input) 

using \u00a0 instead of nbsp should help

but not sure why it just can't be empty
