### ISSUE TITLE
[v2.0] autoload

### ISSUE THREAD

**Issue by tommyalvarez** [JedWatson/react-select#2710]
In the v2 documentation it says prop autoLoad was removed and to check Async component. Well... i did check the async component in the v2 docs and it says nothing regarding autoloading options as soon as the component mounts. So my question is, how can i disable pre-fetching options on mount until user actually searches something?

**Comment by JonathanWbn** [comment]
I asked myself the same thing.

This is how it looks to me: There is a new prop called [defaultOptions](https://react-select.com/props#async-props), that when being set to `false` (which is the default), will behave in the same way that `autoLoad={false}` did, meaning not calling `loadOptions` until something is typed.

There seems to be a change however regarding the little message below from 'Type to search' to always just showing 'No options'. However, you can get there again by passing the custom `noOptionsMessage` like so: `noOptionsMessage={({ inputValue }) => !inputValue && 'Type to search'}`

But these are just my suspicions, would be cool to get some clarification on this and to maybe add a little note in the [upgrade guide](https://react-select.com/upgrade-guide).

**Comment by jakeboone02** [comment]
@JonathanWbn Also, there's a note above `defaultOptions` in the [TypeScript definitions for Async](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/lib/Async.d.ts#L8) that says
```
When set to `true`, the results for loadOptions('') will be autoloaded.
```
That's the opposite of what you're talking about, but it should also be included in the documentation.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
