### ISSUE TITLE
[V2] MenuList being re rendered when hovering over the options

### ISSUE THREAD

**Issue by avivshafir** [JedWatson/react-select#2711]
The new v2 version looks awesome! I love the css-in-js with emotion and the components API.
So first many thanks for maintaing this library!

I am trying to integrate virtualization, similar to the react-select-virtualized library,
I provided the select component my custom MenuList component, which is re rendered on every hover over the options, causing lags and slow scrolling behaviour.

here is a demo:
https://codesandbox.io/s/qko9vw1yzw

Is this a bug or am I missing something?

**Comment by jprosevear** [comment]
I took the same tactic with react-virtualized (providing an menu list component) and am also struggling to get the rendering correct.

**Comment by jprosevear** [comment]
@avivshafir one thing I've noticed is that you don't need to put the VirtualList inside a MenuList component, so far it seems you can use VirtualList directly

**Comment by avivshafir** [comment]
@jprosevear you can but the component is still being re rendered causing a performance problem,
when I add this code to the component
```
shouldComponentUpdate() {
    return false;
  }
```
the MenuList component will not re render but I there are still significant lags and the browser console prints 
```
[Violation] 'scroll' handler took 298ms
[Violation] 'mouseover' handler took 161ms
```

**Comment by Lolobstant** [comment]
Hello, i was just wandering, do you have any idea on how this would work with nested option groups ?

**Comment by Janpot** [comment]
The scrolling is a lot better for me, but the hover effect still has quite some lag, as well as typing

**Comment by IlianYotov** [comment]
Also keyboard up and down doesn't work

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by gabsn** [comment]
There is still a re-rendering issue when hovering on options. I've very surprised a lib with such a wide adoption has still this kind of perf issue.

**Comment by JanderSilv** [comment]
The problem persists: https://stackblitz.com/edit/react-ts-sxucwt?file=MenuList.tsx

**Comment by mtpbzz** [comment]
For anyone coming across this. I worked around the issue by providing a custom Option component and explicitly declared the props i'd need (your props may vary), like so: `const Option = ({value, isSelected, label, innerProps: { onClick }}) =>`

I then handle the hover state with css.

This avoids a re-render on every hover.
