### ISSUE TITLE
[v2.0 docs] Missed comma 

### ISSUE THREAD

**Issue by SilencerWeb** [JedWatson/react-select#2712]
Missed comma in the docs on the page https://deploy-preview-2289--react-select.netlify.com/styles#style-object

![image](https://user-images.githubusercontent.com/20713191/41457546-78f1f8e0-709d-11e8-9ab0-c5d643b0c7c1.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
