### ISSUE TITLE
[v2.0] Unnecessary underscores in className

### ISSUE THREAD

**Issue by SilencerWeb** [JedWatson/react-select#2714]
it is `react-select__--is-disabled` now but it should be `react-select--is-disabled`

![image](https://user-images.githubusercontent.com/20713191/41496096-83f8cf08-7150-11e8-9863-03c8e9d1c6c6.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
