### ISSUE TITLE
What is the difference between default import and import Creatable from 'react-select'?

### ISSUE THREAD

**Issue by SilencerWeb** [JedWatson/react-select#2715]
What is the difference between default import and import Creatable from 'react-select'? I tried to use both and noticed no difference.

**Comment by smoleniuch** [comment]
[Creatable](https://deploy-preview-2289--react-select.netlify.com/home#creatable) as name mentions, it allows you to create select option on the fly.Check out the example, type some text that does not exists in available options and press create option.

Anyway the examples in [docs](https://deploy-preview-2289--react-select.netlify.com/home) are interactive, you can play around in the codesandbox.

Cheers!

**Comment by gwyneplaine** [comment]
thanks for the succinct answer @smoleniuch, hope that answers your query @SilencerWeb. 
closing this issue now
