### ISSUE TITLE
[v2.0] react-select v2 Missing type annotation for U

### ISSUE THREAD

**Issue by erksdee** [JedWatson/react-select#2716]
Hi, I'm getting the below error when running flow. Could someone please advise ?

Environment
OS: macOS High Seirra - Version 10.13.4
Node version: v9.6.1
NPM version: 5.7.1

<img width="1220" alt="screen shot 2018-06-18 at 9 46 20 am" src="https://user-images.githubusercontent.com/7500305/41513345-ab59a0ca-72dd-11e8-851c-85fe559735c7.png">

**Comment by gwyneplaine** [comment]
Hi @erkan1991  which version of flow are you running?

**Comment by erkan1991** [comment]
Hi @gwyneplaine, the flow version i'm running is `^0.2.3`. However I have manage to get it passing locally with the below updated code block.

File: `react-select/src/Select.js`
Line number: `1172:14`

```
if (isMulti) {
      const selectValues: Array<any> = selectValue.map(opt => {
      let isFocused = opt === focusedValue;
        return (
          <MultiValue
            {...commonProps}
            components={{
              Container: MultiValueContainer,
              Label: MultiValueLabel,
              Remove: MultiValueRemove,
            }}
            isFocused={isFocused}
            isDisabled={isDisabled}
            key={this.getOptionValue(opt)}
            removeProps={{
              onClick: () => this.removeValue(opt),
              onMouseDown: e => {
                e.preventDefault();
                e.stopPropagation();
              },
            }}
            data={opt}
          >
            {this.formatOptionLabel(opt, 'value')}
          </MultiValue>
        );
      });

      return selectValues;
    }
```

**Comment by SilencerWeb** [comment]
@erkan1991 but the current flow version is 0.74, try to upgrade flow and run it again

**Comment by DavidBabel** [comment]
@erkan1991 If you use a return at this point, i guess you are in a function.

The solution is to not let flow infer the return type, and specify it manually : 

```js
function yourFunction(array) : Array<any> {
  return array.map( ... );
}
```

Kind of the same solution you found, but without modifying your code.

**Comment by acro5piano** [comment]
Hi, I faced the same issue.
When I set the function return type explicitly, then the error gone.

```ts
// Error

class Foo {
  id: number

  toParams {
    id: this.id
  }
}
```

```ts
// No Error

class Foo {
  id: number

  toParams: Object {
    id: this.id
  }
}
```

Hope this helps. Thanks

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
