### ISSUE TITLE
Unable to remove/hide pre selected values from main options array 

### ISSUE THREAD

**Issue by dsuraj72** [JedWatson/react-select#2718]
Hello,

For below example, I'm able to select **value 1** multiple time. How can we auto hide the selected value from main **options** array?

Thanks.

**Sample Code**

```
import React, { Component } from 'react';
import Select from 'react-select';

export default class Test extends Component {
  constructor() {
    super();
    this.state = {
      options: [{value: "1", name: "One"}, {value: "2", name: "Two"}],
      selected_values: [{value: "1", name: "One"}]
    }

 handleSelectChange = (value) => {
    this.setState({ selected_values: value });
  }

 render(){
   return(
    <div>
       <Select
              closeOnSelect={false}
               multi
               onChange={this.handleSelectChange}
               options={options}
               placeholder="Select"
               removeSelected={true}
               value={selected_values}
         />
    </div>
  )
}
}
```

**Comment by dsuraj72** [comment]
Hi, Any solution/fix for this?
Thanks.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
