### ISSUE TITLE
react-select should work more like a real DOM select

### ISSUE THREAD

**Issue by pixeldrew** [JedWatson/react-select#272]
I was expecting react select to have child <option> elements which would populate the dropdown.

Something like:

``` jsx
render() {
  return ( 
    <Select onChange={this.onChange}>
      <option val="blah">something else</option>
    </Select>
  );
}

onChange(e) {
   console.log(e.target.value) // unlike a react.DOM select e is the value of the select
}
```

Retrieving the values of the this.props.children array to get the value of the options would be cleaner for a more declarative style and would also allow react-select to be an easier drop in replacement.

Also, the onChange event handler doesn't send a synthetic event, instead it just sends the value of the select. Sometimes it's useful to get the target component.

**Comment by PetrSnobelt** [comment]
+1 for adding synthetic event to onChange

**Comment by jmarceli** [comment]
+1 l also needs event target inside `onChange` handler

**Comment by petetnt** [comment]
This would also solve getting the value out of the ref directly.

```
foo() {
  console.log(this.refs.reactSelect.value); //should be whatever is selected instead of undefined
}

render() {
  return ( 
    <Select ref="reactSelect">
      <option val="blah">something else</option>
    </Select>
  );
}
```

**Comment by ximus** [comment]
:+1:

**Comment by gwyneplaine** [comment]
Synthetic event is now sent through onChange in v2.
Making react-select api as close to native as possible is definitely one of our goals. 
However in this particular case, passing the list of options as data instead of dom elements allows us to operate on the to be instantiated options in much more powerful ways.
