### ISSUE TITLE
[v2]

### ISSUE THREAD

**Issue by richardadjogah** [JedWatson/react-select#2720]
My use case requires me to have my error message when no options are present live outside of the menu itself. While I can hide `.Select__menu-notice--no-options` via CSS, this conflicts with custom styles I've applied to the menu itself. I think a logical fix for this would be to simply allow users to opt out of the noOptionMessage feature entirely and prevent the menu from rendering. I've opened a pull request to this effect: https://github.com/JedWatson/react-select/pull/2719

**Comment by gwyneplaine** [comment]
@richardadjogah thanks for the PR, could you provide us with a [codesandbox](https://codesandbox.io/s/new) of your usecase, it'll allow us to better reason about the context of #2719.

**Comment by richardadjogah** [comment]
Sure thing, here's the simplest version of the issue. Just type in invalid search text:
https://codesandbox.io/s/7jqzyxqrw6

We have some custom styles applied to the Menu component, but in the naive case where we are hiding the `noOptionsMessage` container, the padding and border on the menu itself are still visible. While it would be theoretically possible to work around it with some more complex styles. a simpler solution would just be to let users opt out of using the `noOptionsMessage` feature and remove the DOM elements entirely.

**Comment by JedWatson** [comment]
Made possible with #2754
