### ISSUE TITLE
[v2.0] Matching against label not value

### ISSUE THREAD

**Issue by ollieh-m** [JedWatson/react-select#2721]
I think this is a feature request, unless I'm missing something. The matchProp option available in react-select v1 isn't available in v2. It would be nice to still be able to limit filtering to match against just the label, or just the value. 

I believe this is possible through the filterOption prop, but could it be achieved without having the provide the whole filter function?

**Comment by gwyneplaine** [comment]
Hi @ollieh-m, we export a 'createFilter' method that allows you to create a predefined filterOptions function based on a passed in configuration object. This object takes a 'stringify' function of the following shape (option) =>  string. Using this you can specify which property of your options you wish to match on.

**Comment by ollieh-m** [comment]
That's great, thanks for the prompt and helpful reply. Got it working.

**Comment by MarekJavurek** [comment]
> @gwyneplaine Is there a way to filter by `value` and `label` at the same time?

Thats by default mate.
