### ISSUE TITLE
Is the library forgotten?

### ISSUE THREAD

**Issue by kkseven07** [JedWatson/react-select#2722]
It's such a great library, however there are several bugs which are not fixed for a big period. Also a great number of issues not answered.

**Comment by gwyneplaine** [comment]
Hi @kkseven07, absolutely not. We've just been focused on roadmap for v2, we should be cutting out a new release for v2 inclusive of fixes to bugs raised in a number of issues. 

We're doing our best to get on top of v1 issues as well, but if you have a critical bug that you'd like addressed, please feel free to submit a PR, we're always looking for help :)
