### ISSUE TITLE
Scroll on mobile devices does not work with menuShouldBlockScroll as true

### ISSUE THREAD

**Issue by catalinredes** [JedWatson/react-select#2726]
Scroll on mobile devices does not work when "menuShouldBlockScroll" is true.

For my use case I need to block scroll outside the menu when menu is open and to work inside the menu.

I attached the select configuration in codesandbox link bellow
https://codesandbox.io/s/olwy71p73q

Version: "2.0.0-beta.6"

**Comment by jossmac** [comment]
@catalinredes could you please elaborate on which parts of the desired behaviour is "not working"?

**Comment by catalinredes** [comment]
@jossmac scroll outside menu is blocked (as it should be) and scroll inside menu is not working (only on mobile device)

**Comment by jossmac** [comment]
Thanks for the clarification, @catalinredes!

**Comment by jossmac** [comment]
Resolved by #2756
