### ISSUE TITLE
React Select [v2] focus outline color

### ISSUE THREAD

**Issue by acollazomayer** [JedWatson/react-select#2728]
Hi i want to change the focus outline color, how can i do this

Thanks

**Comment by koofka** [comment]
There is a built in css class you can use to update the styles on focuse. ` .styled__control-is-focused.`

**Comment by jprosevear** [comment]
Or base the styling in as a prop, see the upgrade guide.

**Comment by Iulia-Soimaru** [comment]
Is there a way to change the `borderColor` on `focus`? Right now it is `blue`, but I would like to change it to something from my themes, as well as update color on `error`.
I found that the style is applied [here](https://github.com/JedWatson/react-select/blob/a1e1069d2fa02cfeb47401ae57b096606ea17ca9/scss/control.scss#L61), maybe there is a way to override it in StyledComponents.

I tried:
```
<Select
    styles={{
        ...styles,
        control: (base, state) => ({
            ...base,
            borderColor: 'orange',
        }),
    }}
/>
```

**Comment by sergiulucaci** [comment]
@Iulia-Soimaru you can do this via props like:

```
```

**Comment by sergiulucaci** [comment]
@Iulia-Soimaru you can style the `borderColor` via props like:

```
<Select
    styles={{
        ...styles,
        control: (base, state) => ({
            ...base,
            '&:hover': { borderColor: 'gray' }, // border style on hover
            border: '1px solid lightgray', // default border color
            boxShadow: 'none', // no box-shadow
        }),
    }}
/>
```

**Comment by Iulia-Soimaru** [comment]
I ended up doing this (boxShadow was the styling that needed to be changed)
```
<Select
    styles={{
        ...styles,
        control: base => ({
            ...base,
            boxShadow: `0 0 0 1px 'orange'`,
        }),
    }}
/>
```

**Comment by ixaml** [comment]
This doesn't seem to work for me. I can change the boxShadow, backgroundColor, ... but can't get rid of the blue border on focus.

**Comment by EricLiuZero** [comment]
> I ended up doing this (boxShadow was the styling that needed to be changed)
> 
> ```
> <Select
>     styles={{
>         ...styles,
>         control: base => ({
>             ...base,
>             boxShadow: `0 0 0 1px 'orange'`,
>         }),
>     }}
> />
> ```
styles is undefined
`
const customStyles = {
  control: base => ({
    ...base,
    boxShadow: `1px solid rgb(145, 187, 221)`
  })
};

<Select
  styles={customStyles}
  value={value}
  onChange={this.handleChange}
  options={options}
/>
`

**Comment by attilavago** [comment]
This is ridiculous. You need to be a rocket scientist to style a bloody component...

**Comment by reggieofarrell** [comment]
You can also access the `state` of the Select component and style based on that.  I do agree that it's a bit messy.  This is how I did it...

```javascript
const brandColor = '#46beed';

const customStyles = {
  control: (base, state) => ({
    ...base,
    boxShadow: state.isFocused ? 0 : 0,
    borderColor: state.isFocused
      ? brandColor
      : base.borderColor,
    '&:hover': {
      borderColor: state.isFocused
        ? brandColor
        : base.borderColor,
    }
  })
};
```

**Comment by MrJadaml** [comment]
`outline` is the standard css attribute you would use to modify the focus state outline (for accessibility and the like).

It does not help that attributes like that are defined in the source with the use of `!important` which is a bad practice and causes headaches for anyone wishing to modify that attribute.

https://github.com/JedWatson/react-select/blob/master/src/components/Control.js#L46

Sadly you will want to probably fight fire with fire, as last styles win. So using `!important` yourself -- though maybe add a comment to the link above so your fellow teammates don't totally hate you 😜 and at least understand why that is being included.

**Comment by kimfucious** [comment]
I'm using a custom css, and I just want to apply the same styles on the ReactSelect input using a classname, like `.custom-control-input`.  Is there an easy way to do that?

**Comment by Rall3n** [comment]
@kimfucious your query does not have anything to do with this issue. Please ask questions over at StackOverflow (as per maintainers request in the issue template) or if you have a problem create another issue.

But I think taking a look into the [styles documentation](https://react-select.com/styles#using-classnames) should solve your request.

**Comment by kimfucious** [comment]
Thanks @Rall3n , you're a ⭐️ !

I think one of the reasons people, including myself, have commented here (despite obviously breaking the contribution/issue rules), is because it's like the top hit when gGoogling "how to style react select control border", and the docs are frankly kinda hard to read for most mere mortals, or at least mentally diminished ones, such as myself.

Regardless, I gave up on attempting to use className(s), as it became overly complex.

Working from @reggieofarrell 's excellent example, I found it easier to directly style the component with custom styles like this.

```js
 const customStyles = {
    option: (styles, state) => ({
      ...styles,
      color: state.isSelected ? "#FFF" : styles.color,
      backgroundColor: state.isSelected ? "#F3969A" : styles.color,
      borderBottom: "1px solid rgba(0, 0, 0, 0.125)",
      "&:hover": {
        color: "#FFF",
        backgroundColor: "#F3969A"
      }
    }),
    control: (styles, state) => ({
      ...styles,
      boxShadow: state.isFocused ? "0 0 0 0.2rem rgba(120, 194, 173, 0.25)" : 0,
      borderColor: state.isFocused ? "#D0EAE2" : "#CED4DA",
      "&:hover": {
        borderColor: state.isFocused ? "#D0EAE2" : "#CED4DA"
      }
    })
  };
```

**Comment by mlongman** [comment]
This was the easiest solution I found, especially if your application is themed.
```
.Select.is-focused {
      box-shadow: 0px 0px 10px themed('common', 'inputBoxShadowFocus');
  }
```

**Comment by lakesare** [comment]
If you use `classNamePrefix="hi"`, then you'll be able to use proper classNames (otherwise react-select won't add this classes at all):
`.hi__control--menu-is-open { border-color: red; }`.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by warapolj-dev** [comment]
const selectStyles = {
    control: (styles, { isFocused }) => ({
        ...styles,
        backgroundColor: '#fff',
        boxShadow: 'none',
        borderColor: isFocused ? '#40c1ac' : '#d4d4d4',
        ':hover': {
            borderColor: '#40c1ac'
        }
    }),
    option: (styles, { data, isDisabled, isFocused, isSelected }) => {
        return {
            ...styles,
            backgroundColor: isSelected ? '#40c1ac' : '#fff',
            cursor: isDisabled ? 'not-allowed' : 'default',

            ':active': {
                backgroundColor: '#40c1ac',
                color: '#fff',
            },
            ':hover': {
                backgroundColor: isSelected ? '#40c1ac' : 'rgba(64, 193, 172, 0.1)',
                color: isSelected ? '#fff' : '#40c1ac',
            },
        };
    },
};

**Comment by warapolj-dev** [comment]
this worked for me.

![Screen Shot 2563-06-12 at 18 47 30](https://user-images.githubusercontent.com/43536740/84499643-2f53ea80-acdd-11ea-9616-0bc5a0e14982.png)

**Comment by IlyaVel** [comment]
Yeah, for me too.
Thank you for the solution!

**Comment by 8brandon** [comment]
This is also how it's styled in the `provided` and probably the most performant way to do this. 
![Uploading Screenshot 2021-02-02 at 12.02.28.png…]()

**Comment by juanektbb** [comment]
I was having an issue with an internal focus:
![image](https://user-images.githubusercontent.com/42067604/115635449-68ed7d00-a314-11eb-9526-5b72e33e606f.png)

I resolved it like this:
```    
control: (base, state) => ({
  ...base,
  "*": {
    boxShadow: "none !important",
  },
}),
```

**Comment by cpnvr** [comment]
This is what ended up working for me (it applies secondary style when either mouse is hovering over menu OR when select menu is open -- this may be the use case that others are looking for too so I'm posting here):

```
control: (provided, state) => ({
      ...provided,
      borderColor: state.isFocused ? colors.orange : colors.blue,
      "&:hover": {
        borderColor: colors.orange,
      },
    }),
```

**Comment by fngadiyo** [comment]
I don't know why we make it this complicated just to style a component. Why putting default blue input boxShadow in the first place and why can't I change it without "!important" marks? I don't understand. This is my customStyle to get rid of that pesky boxShadow 
`
  const customStyles = {
    control: (styles) => ({
      ...styles,
      boxShadow: 'none !important',
      '*': {
        boxShadow: 'none !important',
      },
    }),
  };`

**Comment by aashimgarg** [comment]
const customStyles = {
    control: (styles) => ({
      ...styles,
      boxShadow: 'none !important',
      '*': {
        boxShadow: 'none !important',
      },
    }),
  };

**Comment by aashimgarg** [comment]
```
 <Select className="styles" />
   .styles {
    input:focus-visible {
      outline : 0px !important;
    }
  }
```
This one worked for me!

**Comment by umerfarooq69** [comment]
Yeah bro i got it thank you for the help

Regards



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/05/22,
01:41:40 PM
Remove

**Comment by noah-devika** [comment]
This is the first thing that appears in google search, if anyone is coming here looking to know how to style this without using the inline styles (ie. from an external `scss` file) the following works:

```html
<Select
    className={styles.select}
/>
```

```scss
.select {
    div[class*='xg-control'] {
      border: solid thin variables.$inputBorder;
      box-shadow: variables.$inputBoxShadow;
    }
}
```

**Comment by srosato** [comment]
For me on `chakra-react-select^4.7.2` I had to both use `focusBorderColor` prop and styling in order to unify the border color.

```tsx
<AsyncSelect
     focusBorderColor={'orange'}
     // ...
/>
```

```tsx
 control: (provided, state) => ({
   ...provided,
   boxShadow: 'none !important',
   // ...
})
```

Using `state.isFocused ? 0: 0` did not work for me for the `boxShadow` prop.

**Comment by chukwudinweze** [comment]
After going through the solutions above, this is what worked for me

```styles={{
            control: (base) => ({
              ...base,
              zIndex: 9999,
              border: "1.5px solid #c9ccd0",
              boxShadow: "none !important",
              "*": {
                boxShadow: "none !important",
              },
              "&:hover": {
                border: "1.5px solid #7e22ce !important",
              },
            }),
          }}```

          
Using` state.isFocused` ? `brandColor: otherColor` did not work for me

**Comment by anshul-kai** [comment]
It isn't `hover` that solves this problem, it's `focus-within`.

```
styles={{
          control: (base, state) => ({
            ...base,
            border: '1px solid #e2e8f0',
            '&:focus-within': {
              border: '1px solid red'
            }
          })
        }}
```
