### ISSUE TITLE
Add optional title attribute to options?

### ISSUE THREAD

**Issue by HankMcCoy** [JedWatson/react-select#273]
For my use case it would be nice to add an optional title attribute to select options. Theoretical example use:

```js
<Select
  value="one"
  options={[
    {
      value: 'one',
      label: 'One',
      // Adds a title attribute to the option DOM element.
      title: 'The first element in this example list.'
    }
  ]}
/>
```

Is this something you folk would be open to? If so I'd be happy to work on a PR.

**Comment by shanecalhoun** [comment]
This is great. Just what I needed. Now it would be nice to be able to one line ellipse the text instead of wrap it but we will find a css solution for that.
