### ISSUE TITLE
Selecting inputtext with leftmouse from end of input doesn't work well

### ISSUE THREAD

**Issue by 1Jesper1** [JedWatson/react-select#2731]
http://jedwatson.github.io/react-select/

Selecting the inputtext from the end of the input to the start with the left mouse doesn't work well.
You have to click precisely on the end of the input to be able to start selecting the input with the left mouse.

**Comment by jossmac** [comment]
This isn't really a bug... You're attempting to select text within an `<input /` from outside of that input.

**Comment by 1Jesper1** [comment]
Hello @jossmac , what do you mean "outside the input"? I'm selecting the text from the last character of the text in the inside of the input to the first character of the text in the inside of the input. Selecting the text inside the input in the selectbox was easier before.

**Comment by 1Jesper1** [comment]
Compare it with selecting text in a html5 input. [https://www.w3schools.com/html/html_form_input_types.asp](https://www.w3schools.com/html/html_form_input_types.asp)

**Comment by jossmac** [comment]
> Selecting the inputtext from the end of the input to the start with the left mouse doesn't work well.

The actual `<input />` element auto-sizes based on content, it's only ever as wide as the content within, so an attempt to select from "the end of the input" is not actually an input. I recommend inspecting the DOM structure form dev tools to get a better idea of how it's laid out.

Sorry mate, didn't mean to dismiss your claim, just pointing out that there's some smoke-and-mirrors to make react-select behave as it does.

**Comment by 1Jesper1** [comment]
Ah, thanks for the clarification.
