### ISSUE TITLE
[v2] Creatable unconditionally re-renders during componentWillReceiveProps

### ISSUE THREAD

**Issue by jprosevear** [JedWatson/react-select#2735]
https://github.com/JedWatson/react-select/blob/v2/src/Creatable.js#L88

In componentWillReceiveProps, setState is called unconditionally, whether or not options and newOptions have changed, force a re-render every time the parent re-renders (not great for large list of options).  I'm thinking something like:

```
componentWillReceiveProps(nextProps: Props) {
      const {
        allowCreateWhileLoading,
        createOptionPosition,
        formatCreateLabel,
        getNewOptionData,
        inputValue,
        isLoading,
        isValidNewOption,
        value,
      } = nextProps;
      let options = nextProps.options || [];
      let { newOption } = this.state;
      if (isValidNewOption(inputValue, cleanValue(value), options)) {
        newOption = getNewOptionData(inputValue, formatCreateLabel(inputValue));
      } else {
        newOption = undefined;
      }
      options = (allowCreateWhileLoading || !isLoading) && newOption
            ? (createOptionPosition === 'first' ? [newOption, ...options] : [...options, newOption])
            : options;

      if (newOption != this.state.newOption || options != this.state.options) {
        this.setState({
          newOption: newOption,
          options: options
        });
     }
    }
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
