### ISSUE TITLE
Selected value is not shown when I remove it from options

### ISSUE THREAD

**Issue by jaidi** [JedWatson/react-select#2747]
So, I have a view where I show multiple select fields. If a value has been selected in one field, It should not show in the options of other fields (All select fields have same source for options)
So, when a value is selected, I remove it from options. But then the magic of react-select kicks in and the selected value is not shown in the field, I don't understand why you need to have this value in options array. It is a simple string that gets passed. It does not have to be dependent on options array.

**Comment by jossmac** [comment]
The value is only relevant with a corresponding option -- it doesn't make sense to have one without the other.

This isn't a bug, so I have to close the issue. I hope you find a solution, maybe try [StackOverflow](http://stackoverflow.com/questions/tagged/react-select)
