### ISSUE TITLE
Select-input doesn't wrap long lines of text

### ISSUE THREAD

**Issue by fmoliveira** [JedWatson/react-select#2757]
## Issue & Steps to reproduce
Just type a long line of text in the input and you can notice the width of `.Select-input` element grows indefinitely.

![react-select-example](https://user-images.githubusercontent.com/3985462/42054134-f028e51c-7ae9-11e8-9d29-2fdb996b2de1.png)

## Expected Results
When you type a long line of text, it should be wrapped just like an usual HTML5 `<input />` element does.

**Comment by nabeelnazirvf** [comment]
I am having this same issue. Can anyone please suggest a fix. 
thanks
