### ISSUE TITLE
[v2] Bug - Label with htmlFor not triggering focus

### ISSUE THREAD

**Issue by brunocramos** [JedWatson/react-select#2763]
When using label with htmlFor, its referenced element is not triggering focus. Here is a sandbox with an example:

https://codesandbox.io/s/3r4l5o2qwp

**React**: 16.3.2
**React-Select**: 2.0.0-beta.6

### Test case steps

- Clicking "first" triggers focus on the first select, which is the default html select behavior.
- Clicking "second" does nothing

This prevents us from advanced styling with label, such as this case:

![image](https://user-images.githubusercontent.com/4956907/42134963-e0127228-7d1a-11e8-8a16-b923bf4eb15a.png)
![image](https://user-images.githubusercontent.com/4956907/42134966-e7b7eda0-7d1a-11e8-88aa-9edce9aa6f67.png)

The text element in the first image is a label on top of react-select, and clicking on it does not open/focus the select. I can only start typing clicking outside the label.

**Comment by someden** [comment]
Use `inputId` instead `id`
```
<label htmlFor="second">second</label>
<Select options={options} name="second" inputId="second" />
```

**Comment by brunocramos** [comment]
@someden awesome, that did the work. Thanks

**Comment by T04435** [comment]
You can add `openMenuOnFocus` to open the menu on label click.
