### ISSUE TITLE
[v2] Proper flow types for state manager HOC

### ISSUE THREAD

**Issue by mike1808** [JedWatson/react-select#2769]
When you wrap a component with `stateManager` HOC all its flow types are not working.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
