### ISSUE TITLE
Undocumented breaking change in beta7

### ISSUE THREAD

**Issue by trungdq88** [JedWatson/react-select#2776]
Hello, I just updated from beta6 to beta7 and find out this breaking change:

# Beta 7

![beta7](https://user-images.githubusercontent.com/4214509/42303064-4436cba6-8049-11e8-916f-c541fe734d67.png)

# Beta 6

![beta6](https://user-images.githubusercontent.com/4214509/42303070-498ccef2-8049-11e8-90e5-a3a529a34e19.png)

I intend to report a bug but then I though it could be an intended API change because it's still in beta.

Although it cost me about an hour to investigate this, I'm not upset. I'm just wish you can spend a little bit more effort to document the breaking changes between versions, it will help a lot of people.

Thank you for creating this awesome library. Have been using this since 1.x, really appreciate.

**Comment by jossmac** [comment]
Hi @trungdq88,

Thanks for letting us know
