### ISSUE TITLE
Uncaught TypeError: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by mannebusk** [JedWatson/react-select#278]
Getting this error when rendering the component. It seems to come from the setState call in componentWillMount. I'm pretty new to React, so i could not figure out what is going wrong here.

Where react throws error:
![screen shot 2015-06-29 at 11 16 40](https://cloud.githubusercontent.com/assets/3019230/8404916/1e077596-1e51-11e5-92cc-e6ccb29eea18.png)

Where it is triggered in react-select:
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L133
![screen shot 2015-06-29 at 11 17 57](https://cloud.githubusercontent.com/assets/3019230/8404927/36839a3c-1e51-11e5-9ef5-9b1d91b61c55.png)

I am using React 0.13.3 and react-select 0.5.2 with browserify.

**Comment by mannebusk** [comment]
Ok, it works when I install it via bower and fetches the select from window.Select instead of using require(). What are the difference in those builds?

**Comment by keffidesign** [comment]
I have the same error in 0.5.2 version
0.5.1 works fine

**Comment by mannebusk** [comment]
Had the same problem with 0.5.1. It turned out that it was caused by having React included multiple times. I had a module symlinked via npm that also included React.

**Comment by Reggino** [comment]
@mannebusk thanks. You pointed me in the right direction. I had the same issue
