### ISSUE TITLE
Orderable Value Display

### ISSUE THREAD

**Issue by Deiru2k** [JedWatson/react-select#2780]
Hello! Over the course of my work with react select me and my company have encountered a need to sort displayed values in Multi-select without changing the underlying value of the select.

To that extent, I have created a pull-request with the feature I would like implemented for your review and feedback.
However I am currently lacking tests, as I am unsure how to test the behavior in question. Any feedback / input would be appreciated.
PR in question: https://github.com/JedWatson/react-select/pull/2779

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
