### ISSUE TITLE
Show only the matched options on typing on the select input

### ISSUE THREAD

**Issue by Gunner17** [JedWatson/react-select#2782]
I have started using react-select very recently. 
When the select input is blank and 1. I click on the select input Or 2. I click on the inverted arrow situated at the right side of the select input, I get to see all the options in the result list that I have supplied to the Select component by default. Instead of that behavior, when I type something on the input only the matched options should appear in the result list. Is there a way to achieve that?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
