### ISSUE TITLE
[v1] Async Creatable problem with default promptTextCreator

### ISSUE THREAD

**Issue by GiuseppeCiccone** [JedWatson/react-select#2784]
I'm having some issues with Async Creatable component.
When I select "Create option "test option"" instead of just passing "test option" to onChange callback the whole text is passed: "Create option "test option"" .
How can I fix this?
Thanks in advance
![image](https://user-images.githubusercontent.com/25909848/42469094-003f3cdc-83b7-11e8-9bf4-bddcc1927df3.png)

```
<Select.AsyncCreatable
  name="auto-complete"
  loadOptions={this.autoComplete}
  value={this.state.value}
  ignoreCase={false}
  onChange={(value) => this.setState({ value })}
/>
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
