### ISSUE TITLE
Close menu on clear

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#2785]
Hi, is there a way to close the menu after clearing selection on non searchable select?
I am creating the Select with option: { searchable: false }

My expectation when I selected one option and I clear the selection with the X icon, that the selection will be cleared and menu closed
The behaviour at the moment is: the selection is cleared, and the menu opens to show all available options

Are there any other options that need to be set? Is there a callback I can override to meet my expectations?

**Comment by kolyabres** [comment]
@igotrim Did you find a way how to solve this problem? I have to implement the same behavior.

**Comment by icflorescu** [comment]
I finally found a way to solve this; **you'll have to handle `onClearIndicatorTouchEnd` of the inner select component**.

Since it's kind of hackish, you might want to implement a custom component extending `react-select`:

```
class CustomSelect extends Select {
  ...

  attachClearIndicatorTouchEndHandler = (ref) => {
    if (ref) {
      // eslint-disable-next-line no-param-reassign
      ref.select.onClearIndicatorTouchEnd = () => {
        ref.onChange(null);
      };
    }
  };

  render() {
    const { isClearable, isSearchable } = this.props;
    <Select
      ref={!isSearchable && isClearable && this.attachClearIndicatorTouchEndHandler}
      isClearable={isClearable}
      isSearchable={isSearchable}
      ...
    />
  };

  ...
}
```

**Comment by austingayler** [comment]
@icflorescu thanks! got it working with
```
class Timeframe extends React.Component {
  constructor(props) {
    super(props);
    this.ref = React.createRef();
  }

  attachClearIndicatorTouchEndHandler = ref => { ... }

  render() {
          <Select
            ref={
              this.attachClearIndicatorTouchEndHandler && this.ref
            }
```

**Comment by austingayler** [comment]
@icflorescu got it working, thanks! 

For me:
```
class Select extends React.Component {
  constructor(props) {
    super(props);
    this.ref = React.createRef(); 

...

  attachClearIndicatorTouchEndHandler = ref => { ... }

...

<Select
  ref={this.attachClearIndicatorTouchEndHandler && this.timeframe}
```

**Comment by DaClone** [comment]
Another way to get around this is to use a custom `ClearIndicator` and whatever you want to do to the `onClick` prop of the component you return.

An example would be:
```
const SomeComponent = (props) => {
  const selectRef = useRef(null);
  const handleClearValue = (clearValue) => () => {
   
     //Do whatever, selectRef is available here...
    
    //Don't forget to actually clear the value
    clearValue();
  }

  return (
    <Select ref={selectRef} components={{ 
      ClearIndicator: (props: any) => {
        const { clearValue, ...forwardProps } = props;
        return <components.ClearIndicator 
          onClick={handleClearValue(clearValue)} 
          {...forwardProps}
        />;
      }
    }} />
  );
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
