### ISSUE TITLE
[v2] formatCreateLabel does not make any effect

### ISSUE THREAD

**Issue by gitowiec** [JedWatson/react-select#2786]
I want to change the "Create new ..." menu option. I am passing `formatCreateLabel` handler which returns something like `<span style={{ color: "red" }}>Add {inputValue}</span>;` But this does not show up if I type in proper email address (in isValidNewOption handler I test every inputValue with email-validator). The expected "Create new... " option possibly shows up if I remove `formatCreateLabel` from the props of &lt;Creatable/&gt;... Is it a bug or thanks god I do something wrong?
Here is my test case:
[![Edit ReactSelect v2 tryouts](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6jj4y3zz1w) (example.js)

**Comment by mnpreetkaur** [comment]
This issue is not reproducible with react-select 2.2.0
[Working Example](https://codesandbox.io/s/74mj917w8x)

**Comment by ylacaute** [comment]
Hi @gitowiec, it works for me.

```
<Select formatCreateLabel={(value) => <span>What you want here</span>}
   ...
/>
```

**Comment by reverie** [comment]
This repros for me in 3.0.3 when also passing `getNewOptionData`.

**Comment by josecoelho** [comment]
I was not able to reproduce the problem as well.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by aliyousuf-scalematters** [comment]
It seems that `formatCreateLabel` does not do anything if you have already defined the `getOptionLabel` prop.

It looks like `getOptionLabel` takes precedence over `formatCreateLabel`.

Here is the issue reproduced: https://codesandbox.io/s/recursing-montalcini-3jzu0

**Comment by alyyousuf7** [comment]
It seems that formatCreateLabel does not do anything if you have already defined the getOptionLabel prop.

It looks like getOptionLabel takes precedence over formatCreateLabel.

Here is the issue reproduced: https://codesandbox.io/s/recursing-montalcini-3jzu0

**Comment by Rall3n** [comment]
@alyyousuf7 You have to look at the `Add ...` option as if it were a normal option.
It has a `value` and a `label` property.

The first will result in what you typed into the search input.
The latter will result in what `formatCreateLabel` returns.

In your example you return the `value` property in `getOptionLabel`. This will of course result in there being nothing representing the output of `formatCreateLabel`.

**Comment by alyyousuf7** [comment]
It makes sense now. I got confused because the typings for `getOptionLabel` mentioned only `string` as the return type.

**Comment by fredrivett** [comment]
Following this thread with a similar issue, and trying to work out the solution based on @Rall3n's comment. Can anyone provide a code snippet or updated codesandbox link of how to fix this?

I'll keep digging and edit this comment with the solution when I find it.

**Comment by singleseeker** [comment]
> This may help someone else: in my instance, the issue I was having was due to having `formatOptionLabel` return `option.name`, when the created options only had `option.value` (the string input) and `option.label` (the value returned by `formatCreateLabel`).
> 
> I fixed it by having `formatOptionLabel` return `option.name ?? option.label`.

Any online demo? For me, it is still not working.
