### ISSUE TITLE
[v2] Feature Request: onBlurResetsInput as props for v2 for Select and Async

### ISSUE THREAD

**Issue by manongguard** [JedWatson/react-select#2789]
I saw that v1 is accepting onBlurResetsInput as props and was hoping v2 could also have that functionality?

**Comment by ericfong** [comment]
I am looking for demo / code replacement for onBlurResetsInput in v2 too. Thanks

**Comment by Iulia-Soimaru** [comment]
I'd be happy to see `onBlurResetsInput ` or similar functionality available too

**Comment by reverie** [comment]
@JedWatson Any hope here?

**Comment by Rall3n** [comment]
Feature not needed. The funcionality is already build into the select. For solution please see following comment: https://github.com/JedWatson/react-select/issues/3189#issuecomment-442792535

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
