### ISSUE TITLE
`autoload={true}` doesn't call `asyncOptions` handler

### ISSUE THREAD

**Issue by iam4x** [JedWatson/react-select#279]
Code example:

```
<Select
          {...this.props}
          value={this.state.value}
          asyncOptions={this._getOptions}
          onChange={this._handleChange}
          autoload={true} />
```

(NOTE: I use ES7 async/await into `this._getOptions`)

**Comment by iam4x** [comment]
After investigation, `this.setState` callback in `componentWillMount` from `lib/Select.js` is never called in my code. Is this specific to me? I'm using React ES6 Classes

**Comment by iam4x** [comment]
Okey this is a ReactJS bug, https://github.com/facebook/react/issues/1740

**Comment by iam4x** [comment]
PR submitted

**Comment by ivome** [comment]
+1 I'm having the same issue here

**Comment by exitface** [comment]
Same issue and not using ES6/7. Commit fixes the issue.

**Comment by shriah** [comment]
calling `asyncOptions` handler inside `componentWillMount` also breaks the server side rendering because it fails on `setState`
