### ISSUE TITLE
[v2] MultiValueLabel not receiving selected value

### ISSUE THREAD

**Issue by denchp** [JedWatson/react-select#2791]
We need to be able to create 'semi creatable' components.  That is, when specific options are chosen, we want to override the Multi-value Label to include a text box that the user can then customize the rest of the value if if isn't already specified (for example, choosing an option like 'First Name', the MultiValueLabel would read "First Name:" followed by a text box).

We're done up to the point where we're trying to generate the MultiValuelabel.  The function is receiving a react component instead of the value object.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
