### ISSUE TITLE
No focus after clearing selection

### ISSUE THREAD

**Issue by azellsworth** [JedWatson/react-select#2793]
We found an issue where the input focus cursor is not shown after clearing a selection. See gif below.

Of note: The focus cursor will be shown if clearing the default selection.

![no focus cursor after selecting and clearing](https://user-images.githubusercontent.com/8904715/42603233-cfb8b590-8521-11e8-9324-5f9cb851685a.gif)

Thank you ahead of time for working on this!

Adam + Paulette from [Mavenlink](https://www.mavenlink.com/careers/engineering)

**Comment by ryandhaase** [comment]
This may need to have the `v2` label added

**Comment by akhilaudable** [comment]
Any activity on this issue? I am facing the same problem in Safari. In other browsers, it works fine.

**Comment by akhilaudable** [comment]
https://github.com/JedWatson/react-select/blob/77ae92885cdf73fd9def359379f7e08d68f5f849/src/Select.js#L932

Why setTimeout is added here?

**Comment by bladey** [comment]
Hello @azellsworth,

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
