### ISSUE TITLE
addEventListener wont work in componentdidmount()

### ISSUE THREAD

**Issue by rullymartanto** [JedWatson/react-select#2795]
I am working with google maps

Select
                                            placeholder="Waypoint"
                                            className="form-group"
                                            id='CustomerRouteWaypointId'
                                            name="CustomerRouteWaypointId"
                                            value={WP.CustomerRouteWaypointId}
                                            onChange={this.SelectChange('CustomerRouteWaypointId')}
                                            options={this.createWaypointItems()}
                                        

I am trying to addeventlistener in componentdidmount()

 let WaypointId = document.getElementById("CustomerRouteWaypointId");
        WaypointId.addEventListener("change", function(e) {
            console.log('select OK');
        }, false);

but it wont work..

Any idea ?

Thaniks

**Comment by TrySound** [comment]
@rullymartanto This is a bug tracker of unrelated project. Use http://stackoverflow.com/ for such kind of questions.

**Comment by rullymartanto** [comment]
it is can work if using basic html <select > and it wouldn't work if using    react-select

**Comment by TrySound** [comment]
Provide an example in https://codesandbox.io/s/new please
