### ISSUE TITLE
Options aren't rendered

### ISSUE THREAD

**Issue by olleolle** [JedWatson/react-select#2797]
There is a city autocomplete. Start typing:
1. `n` - it goes to the server and options are rendered
2. `ne` - the same
3. `new` - the same
4. `new ` - the same
5. `new y` - it goes to the server and options **aren't** rendered
6. `new yo` - it goes to the server and options are rendered

**Comment by janouser11** [comment]
I am having the same problem!

Its always the same combination as well where they aren't rendered.  Can not seem to find the pattern. 

Any solutions?

**Comment by olleolle** [comment]
@gwyneplaine 
It's happened when loadOptions function loads data from the server.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
