### ISSUE TITLE
[v2] Enter in input does not submit forms

### ISSUE THREAD

**Issue by denchp** [JedWatson/react-select#2798]
Example:
https://codesandbox.io/s/zrm89776zp

If the input has focus, with the menu closed, pressing enter should submit a containing form.

*   What's your use case? (Tell us about your application and what problem you're trying to solve.)
We're using it as an input in a form.

*   What interface do you have in mind? (What new properties or methods do you think might be helpful?)
Don't prevent default when enter is pressed unless the menu is open.  From the look of it, right now it's at the end of the switch case:  https://github.com/JedWatson/react-select/blob/v2/src/Select.js

**Comment by BertrandFritsch** [comment]
I second @denchp on this. Right now, the user has to leave the select field with a tab, then hit the enter key to submit the form.

**Comment by aaslami** [comment]
I am getting the same behavior here too.
This is a regression of this
https://github.com/JedWatson/react-select/pull/2539/commits/7cf28130f86527f15013ed09906138c7edc4ad41

**Comment by goldbuick** [comment]
I'm getting the same behavior as well. This is a regression of
https://github.com/JedWatson/react-select/pull/2539/commits/7cf28130f86527f15013ed09906138c7edc4ad41

**Comment by sarink** [comment]
I found a workaround:  Attach a `ref`, use the `onKeyDown` prop`, check for `event.key === 'Enter' && !theRef.state.menuIsOpen` - this means that the user pressed enter while the menu was closed, so you can submit the form :)

**Comment by AntCas** [comment]
Having a similar issue. When the user clicks a dropdown menu option they are unable to submit using ENTER unless they click on the field or hit another key first.

 The problem is related to the “menuIsOpen” state on the Creatable component (see gif). When I click on the field you can see the menuIsOpen state changes for "false" and then I'm able to submit. 

![react-select issue](https://user-images.githubusercontent.com/6935841/55255150-46213500-5230-11e9-8abc-1dd3de1be228.gif)

**Comment by LiborOl** [comment]
Was this issue fixed? It works now after upgrading from `2.2.0` to `3.1.0`.

**Comment by bladey** [comment]
Thanks for the feedback @LiborOl! If this is indeed not fixed, we'll reopen the issue.

**Comment by yard2010** [comment]
Hey, can we reopen this issue? It's not fixed - you can verify that by checking the original sandbox link OP posted.

> I found a workaround: Attach a ref, use the onKeyDown prop, check for event.key === 'Enter' && !theRef.state.menuIsOpen - this means that the user pressed enter while the menu was closed, so you can submit the form :)

I managed to solve this issue by using this workaround, but this is not documented anywhere except this 3 years old Github comment. Can you please point me how can I add a PR to add this to the docs? Is there a better way to call a function when enter pressed on the control when the menu is closed?

**Comment by ebonow** [comment]
Greetings @yard2010 

This is no longer an issue and should remain closed as it no longer requires any type of workaround. Regarding the original example...

1. The codesandbox example is pointing to an outdated beta version of react-select.
2. The select is missing a `name` prop which is required of any input field within a form.

Here is a modified fork of the provided example (maintaining the 5th Element theme of the original of course) using react-select version 2.4.4 and displaying the form data being retrieved properly from the form:
[MULTIPASS Codesandbox demo](https://codesandbox.io/s/react-select-form-data-mng2g?file=/src/index.js) 

Please let me know if you have any questions or concerns regarding nay of the above.

**Comment by yard2010** [comment]
@ebonow that's exactly what I was looking for, thank you for taking the time to explain!
