### ISSUE TITLE
When re-rendering, new options are given a label that match their ID instead of their specified label

### ISSUE THREAD

**Issue by Bargs** [JedWatson/react-select#28]
For example, I might pass an options array that looks like this:

```
var options = [
    { value: '1', label: 'Red' },
];
```

If the app gets some new data and I need to re-render the component, I might pass a new options array that looks like this:

```
var options = [
    { value: '1', label: 'Red' },
    { value: '2', label: 'Blue' }
];
```

After the re-render, the new option's html will have a label of "2" instead of "Blue".

The problem appears to lie in `initValuesArray`, which in this case is getting triggered by `componentWillReceiveProps`. `initValuesArray` is passed a new value from `newProps`, but it attempts to look up the label in `this.state.options`, which has not yet been updated with the new props. It seems like `getStateFromValue` should have two parameters, one for the value and one for the options array.

I could try to submit a pull request if you agree. Or am I misunderstanding something about how the component should be used?

**Comment by JedWatson** [comment]
You're correct, and sorry this took so long to get to. I've fixed updated `initValuesArray` to accept new options from `componentWillReceiveProps`. Please let me know if you still have issues with it (PR welcome if so!)

**Comment by Bargs** [comment]
Thanks! I'll give it a go as soon as I can.
