### ISSUE TITLE
[v2] MultiValueLabel component not receiving commonProps

### ISSUE THREAD

**Issue by xxx** [JedWatson/react-select#2801]
Hi,

I'm trying to find a way to replicate `onValueClick` in v2, and my attempt in setting a custom component for MultiValueLabel only receives `className` and `children` props, which seems to run counter to [the docs](https://deploy-preview-2289--react-select.netlify.com/components) that state

> Every component receives commonProps which are spread onto the component.

I'm doing something roughly like

```javascript
const multiValueLabel = (propz) => {
  console.log(propz) // just className and children here.

  return <components.MultiValueLabel {...propz} />
}

return <AsyncCreatable {...} components={{ MultiValueLabel: multiValueLabel }} />
```
I'm not sure if I'm missing something. Really, I'm just wanting to get to the actual option data and set up a click handler.

**Comment by rootelement** [comment]
Hey! I'm not sure if this helps you, but I'm using react-select for an admin tool I'm building and I actually was able to build a MultiValueLabel like this.

Note: I'm actually using a custom-built enhancement of https://www.npmjs.com/package/react-avatar called `<EventHostAvatar />` as the multi-select label component.

But what I found is that you can accept a "data" property in the const function and use that:

My returned data is a rest GET with a complex object graph, but the "hosts" array looks like this:
```json
hosts.data = [
{"id": 1, "firstName": "James", "lastName": "Bond"},
{"id": 2, "firstName": "Dr", "lastName": "Who"},
...
]
```

My value label function:
```javascript
const MultiValueLabel = ({props, data}) => {
  return (
    <components.MultiValueLabel {...props}>
      <EventHostAvatar hostName={data.firstName+' '+data.lastName} hostId={data.id} />
    </components.MultiValueLabel>
  );
};
```

```javascript
return (
      <Select
        components={{MultiValueLabel}}
        isMulti
        getOptionValue={opt => opt.id}
        getOptionLabel={opt => opt.firstName + ' ' + opt.lastName}
        options={hosts.data}
       />
    );
```

And the resultant (not completely styled) component looks like this:
<img width="478" alt="screen shot 2018-09-24 at 8 37 25 pm" src="https://user-images.githubusercontent.com/5400156/45986472-b52b9000-c039-11e8-8dc1-173faca4375b.png">

And just for complete-ness, i'm using `"react-select": "^2.0.0"` in my package.json

It actually works quite well. I may replace the `getOptionValue` and `getOptionLabel` props with custom components there as well.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
