### ISSUE TITLE
Displayed option is included in Ctrl+A >> Copy no matter what

### ISSUE THREAD

**Issue by Slapbox** [JedWatson/react-select#2803]
I've tried every CSS style under the sun to prevent this, but Ctrl+A still grabs the text in this box when it's not focused. I would go to StackOverflow, but I do not believe this is a CSS styling issue that I can correct, or I believe I'd have been able to by now. I know this package has some styling quirks.

I tried `user-modify` `user-select` on the top level elements as well as using `.Select *` and with `!important` but none make any differences. I've tried several other ideas as well which now slip my mind, but nothing works. Is there something I can do here? Something I'm overlooking? Thanks very much!

**Comment by Slapbox** [comment]
Anyone have any thoughts on this? It's seriously problematic.

**Comment by Slapbox** [comment]
This is an issue in version `1.1`, `1.3` and `2.0`

**Comment by Vynlar** [comment]
Try applying `user-select: none` to the `placeholder`, `singleValue` and `multiValueLabel` using the `styles` prop in v2. If I understand your issue, this solution prevents the text inside of the select field from being selected when pressing Ctrl-A.

**Comment by Slapbox** [comment]
Thanks for your reply @Vynlar. Unfortunately I'm back on V1 and V2 looks very difficult to upgrade to from a styling standpoint, since I've used static CSS. Unfortunately though, in V1 and V2, setting those properties on every single element all the way down with ridiculous specificity and `!important` on the rule just has no effect whatsoever. Even setting the style properties directly on the elements themselves fails to modify this behavior.

**Comment by Slapbox** [comment]
Unbelievably enough, the problem persists even when setting the entire element to `display: none;`....

**Comment by Vynlar** [comment]
Would you be able to create an isolated example using a tool like Codepen? That would help in the investigation.

**Comment by Slapbox** [comment]
I'm not sure this is specific to `react-select` anymore. I will re-open this if further research leads me back to `react-select`. Thank you again for your help.
