### ISSUE TITLE
onChange return value is inconsistent

### ISSUE THREAD

**Issue by najisawas** [JedWatson/react-select#2804]
https://codesandbox.io/s/jp38mx52x9

Select an item using the component.
Clear the value using the clear (`X`) button.
Notice the console logs (`null`).

Select an item using the component.
Clear the value using the backspace button.
Notice the console logs (`[]`).

I believe as a single-select component the value returned should either always be `null` or an empty object `{}`, while in a multi-select component the value returned should either always be `null` or an empty array `[]`

**Comment by bugzpodder** [comment]
dupe of #2682?
