### ISSUE TITLE
[v2] Async doesn't accept `filterOption`

### ISSUE THREAD

**Issue by nadeemkhedr** [JedWatson/react-select#2808]
Not sure if its a bug or its a design decision, `Async` component in the proptypes expects `filterOption` but when it renders `< SelectComponent>` it always set it to `null`  

https://github.com/JedWatson/react-select/blob/f1cb4eee0ed27f991023a3abe5f64d3a9e05ab86/src/Async.js#L170

If its a design decision to remove it, I can share why we do need it in our project, currently this is the only thing that is blocking me from upgrading

**Comment by JedWatson** [comment]
This was a specific decision, but I've realised that simply defaulting the prop would cover the same default behaviour I wanted while unblocking you - so I've implemented that in #2822
