### ISSUE TITLE
[V2] [Feature Request] Ability to specify the minimum length for performing a search

### ISSUE THREAD

**Issue by kevin-lindsay-1** [JedWatson/react-select#2811]
Looking for the ability to prevent the "search" option from occurring until you type in a specific number of characters.

I'm basically looking for the feature that already exists on React-Bootstrap-Typeahead:
https://ericgio.github.io/react-bootstrap-typeahead/#behaviors
`minLength`: Require minimum input before showing results

**Comment by nadeemkhedr** [comment]
you can do that manually in `loadOptions` no ? check the length of the query if less than expected return an empty promise

**Comment by kevin-lindsay-1** [comment]
Ah, didn't see that. Will use that in future; I've encountered similar components that do this strangely, though, and if you did something like `input.value.length > 3`, it updates strangely, because in those components, the `input.value` state (or what have you) is updated **after** the check, not before.

Thoughts on this would be appreciated.

**Comment by mixaildudin** [comment]
Like, really? Is this the true way of setting minimum input length? This looks too dirty for such an easy thing, and I cannot even imagine why not have this out of the box

**Comment by zhil** [comment]
Sample code (inspired by https://github.com/JedWatson/react-select/issues/4638 and other issues)

```
const loadOptions = (inputValue, callback) => {
        if (inputValue.length < 3) {
            callback([]);
        } else {
            // load options from backend
        }
    }
    const noOptionsMessage = (input) => {
        if (input.inputValue.length === 0) {
            return "Type to search";
        } else if(input.inputValue.length < 3) {
            return "Search input must be at least 3 characters";
        } else {
            return "No options";
        }
    }
<AsyncSelect
            isClearable
            cacheOptions
            loadOptions={loadOptions}
            noOptionsMessage={noOptionsMessage}
            // ... other props
        />
```
