### ISSUE TITLE
[V2] When closeMenuOnSelect is false, the focus highlight jumps to the 1st option after each selection

### ISSUE THREAD

**Issue by wdcryer** [JedWatson/react-select#2813]
Here is an example I tested in Chrome: https://codesandbox.io/s/nwxvq7y3m

After you select options other than the first, the focus option jumps to the first, then jumps back down when you move your mouse. This looks pretty jumpy. It seems like it can be fixed by setting focusOption to null rather than options[0] when lastFocusedOption can't be found (in Select.js getNextFocusedOption function). This makes it so no options are focused after making a selection until you move your mouse to another option.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by Methuselah96** [comment]
Note that this happens particularly when selecting the last option.

**Comment by Methuselah96** [comment]
Follow https://github.com/JedWatson/react-select/issues/4370 for any further updates on this.
