### ISSUE TITLE
[V2] Accept integer values on list

### ISSUE THREAD

**Issue by rhuanbarreto** [JedWatson/react-select#2815]
I was testing a CreatableSelect with integers as values and it doesn't work properly.

Here is the plnkr showing this: https://plnkr.co/edit/C6NGWUdBDSbWWFXlfg3O?p=preview

**Comment by ahmedelgabri** [comment]
Here is a clear codesandbox of the issue https://codesandbox.io/s/zn51181074 & this is the problem https://github.com/JedWatson/react-select/blob/2654ce0505d9e3820e169109cc413778fc20f843/src/Creatable.js#L40-L43

Numbers has no `toLowerCase()` prop on them

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
