### ISSUE TITLE
[V2] publish new release 

### ISSUE THREAD

**Issue by nadeemkhedr** [JedWatson/react-select#2819]
It has been two months for this fix but it's still not published 

https://github.com/JedWatson/react-select/blob/1704201829743cbb99b2bdf23bdbd65216ee025c/src/Async.js#L72

I am using `react-select@2.0.0-beta.7`

**Comment by gwyneplaine** [comment]
@nadeemkhedr we're looking at releasing a new release of 2.0.0 soon, this fix will be included as part of that release. Thanks for your patience, will ping you on here once again once this release is out :)

**Comment by JedWatson** [comment]
It's out!
