### ISSUE TITLE
react-select cannot popup over the datagrid content

### ISSUE THREAD

**Issue by hipertracker** [JedWatson/react-select#282]
Is there any way to use https://github.com/JedWatson/react-select as a part of rendered column's title? It is rendered, but it cannot popup out of the header content. Some part are rendered BEHIND the react-datagrid content.

**Comment by JedWatson** [comment]
@hipertracker you closed this, is the problem resolved?

**Comment by hipertracker** [comment]
No, but the problem may not belong here.  I was able to [reproduce the same bug](https://github.com/hipertracker/datagrid-multiselect-issue) using another multi-select library.  My problem is related to [FixedDataTable](https://facebook.github.io/fixed-data-table/) and [ReactDataGrid](http://zippyui.com/react-datagrid/#/) libraries. They have problems with replacing default  column content with more complex React component. I am trying to build more customisable DataTable component using different filters for every column.

**Comment by JedWatson** [comment]
Cool, thanks for letting me know :+1:
