### ISSUE TITLE
select form is not rendered correctly 

### ISSUE THREAD

**Issue by shangsunset** [JedWatson/react-select#283]
Hi,
i installed react-select via npm and included `'react-select'` in a react file, but the form is not rendered correctly for some reason(the first is normal select tag, the second one is using react-select tag)
`ops` is an array of objects: `[{"value":0,"label":"administrator"},{"value":1,"label":"instructor"},{"value":2,"label":"TA"}]`.

am i missing something?
this is my code and screenshot. thanks.
```javascript
import Select from 'react-select'

<Select
  className="form-control"
  placeholder="Select user role(s)"
  name="users_role"
  multi={true}
  options={ops} />

```

![screen shot 2015-06-29 at 7 22 05 pm](https://cloud.githubusercontent.com/assets/3700269/8420749/2ecf6fc6-1e94-11e5-923f-3638a33600ec.png)

**Comment by brianreavis** [comment]
You seem to be missing the [stylesheet](https://github.com/JedWatson/react-select/blob/master/dist/default.css)

**Comment by shangsunset** [comment]
oh so i need to manually put the stylesheet in the html file or ? im using gulp for react

**Comment by brianreavis** [comment]
Yeah, that's correct
