### ISSUE TITLE
[V1] Doesn't change focus from input (IE11)

### ISSUE THREAD

**Issue by slesarevns** [JedWatson/react-select#2833]
When we click on input and after open the select list it's doesn't change focus (at IE11) from input filed to select as result we have a bug like on screenshot above. Could anyone help me please solve current issue (also I tried change z-index but it's doesn't solve the problem) ? 

![reacselect](https://user-images.githubusercontent.com/10522353/43076910-7afe1132-8e8e-11e8-98a1-9a541aa522fb.jpg)

![react-select](https://user-images.githubusercontent.com/10522353/43076408-d4565f98-8e8c-11e8-9c7c-2b78cd263503.jpg)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
