### ISSUE TITLE
unpkg error

### ISSUE THREAD

**Issue by ashnur** [JedWatson/react-select#2834]
https://unpkg.com/react-select@2.0.0/dist/ doesn't have `react-select.css` since today. 
I am not sure if this is their mistake or the build has changed?

**Comment by 416serg** [comment]
+1 and this isn't the first time this is happening 😢

**Comment by isitrandomenough** [comment]
still ?

**Comment by ashnur** [comment]
@416serg @isitrandomenough just use https://github.com/paypal/downshift instead react-select, it's better in many ways anyway.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
