### ISSUE TITLE
[1.3.0] This version introduces a breaking change to the UI

### ISSUE THREAD

**Issue by ematipico** [JedWatson/react-select#2835]
Looks like a `span` has been changed into a `div`. This is breaking all the snapshot tests. Is it normal?

![image](https://user-images.githubusercontent.com/602478/43078227-c5b42b60-8e81-11e8-95c3-106eb97b91d5.png)

And

![image](https://user-images.githubusercontent.com/602478/43078242-cecf7682-8e81-11e8-8b0e-b9ffe079dfbd.png)

**Comment by Janpot** [comment]
From [the docs](https://jestjs.io/docs/en/snapshot-testing)
> The snapshot artifact should be committed alongside code changes, and reviewed as part of your code review process. Jest uses pretty-format to make snapshots human-readable during code review. On subsequent test runs Jest will simply compare the rendered output with the previous snapshot. If they match, the test will pass. If they don't match, either the test runner found a bug in your code that should be fixed, **or the implementation has changed and the snapshot needs to be updated**.

Your snapshot needs to be updated. This is not a breaking change.

**Comment by skvale** [comment]
It's possible we weren't using react-select as intended, but this was a breaking UI change for us.

after 1.3.0:
![screen shot 2018-07-25 at 11 49 15 am](https://user-images.githubusercontent.com/5314713/43215096-dd0a4058-9000-11e8-9163-2a0a5851df23.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
