### ISSUE TITLE
[V2] Default value must be object

### ISSUE THREAD

**Issue by Stardog** [JedWatson/react-select#2841]
Previously in V1, I could set the value as a string. The Select would use that value, match it against the option array, and default the selection. In V2, the default value must be a copy of the option it is matching against.
Example: https://codesandbox.io/s/y2x614o9nz

As the matching value I am retrieving is typically an id, I would now have to search the options, make an extract of the object that contains the matching value, and use it to initialize the state. It was much easier to just manage the value alone. Trying to initialize the Select with a simple {value: '1'} without a label doesn't work as it expects the label.

Perhaps I am missing a change or a new prop, but this was a surprise when trying to update.

**Comment by RomaMoisiuk** [comment]
Also when you choose an option the value becomes an object like a `{ value: 'a', label: 'A' }` . That's really bad. I need to rewrite logic for all Select components.

**Comment by morloy** [comment]
Yes, feels really weird to reconstruct an entry from options list in the value field.

**Comment by tsteele2013** [comment]
@cbergmiller your wrapper component doesn't account for the use of keys besides `label` and `value`. Is there any way to extend that component to work with `getOptionLabel()` and `getOptionValue()` functions?

**Comment by shawnxusy** [comment]
For folks using `react-final-form` or similar form management libraries, there is a cleaner workaround by using the provided `parse` and `format` functions to auto-cast.

```
// Example by using react-final-form
// No need to cast between value and option manually
import { Field } from 'react-final-form';
import Select from 'react-select';
import { find } from 'lodash';

const SelectInput = ({ name, options }) => (
  <Field 
    name={name}
    parse={val => val && val.value}
    format={val => find(options, o => o.value === val)}
    render={({ input, meta }) => (
      <Select 
        {...input}
        options={options}
      />
    )}
)
```

**Comment by greg606** [comment]
thanks @shawnxusy it actually works the same for redux-form. 
For multi you must use:
``
format={val => map(val, item => find(options, o => o.value === item))}
parse={val => val && map(val, item => item.value)}
``

**Comment by gtaylor44** [comment]
Preference in favour of value being a string. Very frustrating. 

This is my workaround for time being...

`<Select value={ options.find(o => o.value === this.state.selectedOption) } options={options} onChange={...} />`

**Comment by eliseumds** [comment]
That's big, and that's exactly why one *should not use vendor libraries directly* and instead wrap them so that breaking changes like this one become less painful.	

```js
import MyAmazingSelectComponent from 'somewhere';

<MyAmazingSelectComponent
  beautifulProp={1}
  value={input.value}
  onChange={callbackJustLikeBefore}
/>
```

**Comment by jossmac** [comment]
This keeps coming up. Part of the problem is documentation, for sure, but if you still really want to use simple value I've created a wrapper. You can get it [from npm](https://www.npmjs.com/package/react-select-simple-value) or take a look at [the source](https://github.com/jossmac/react-select-simple-value/blob/master/index.js) and grab whatever you want.

#### Usage

```jsx
<SimpleValue options={[...]} value="blue">
  {props => <Select {...props} />}
</SimpleValue>
```

#### Supports

- simple `value`
- simple `defaultValue`
- grouped options
- custom `getOptionValue`

*Does not support the `isMulti` property*

---

#### Trivial Alternative

```jsx
const getValue = (opts, val) => opts.find(o => o.value === val);

const MySelect = ({ value, ...props }) => (
  <ReactSelect value={getValue(props.options, value)} {...props} />
);
```

**Comment by Floriferous** [comment]
This is a list of breaking changes, shouldn't they be documented in `History.md` or `Releases` at least?

I saw the only 2 breaking changes that were documented, thought upgrading would be a breeze, but now I'm 2 hours in and ready to downgrade :)

**Comment by SirwanAfifi** [comment]
> Preference in favour of value being a string. Very frustrating.
> 
> This is my workaround for time being...
> 
> `<Select value={ options.find(o => o.value === this.state.selectedOption) } options={options} onChange={...} />`

This doesn't let you to choose a new item in the list

**Comment by Pyot** [comment]
Here is solution for select with headers 
`<Select options={options} value={options.map(group => {
                                        return (group.options.find(o => {
                                            return (o.value === field.value)}))
                                    })} onChange={(e) => {this.props.selectChangeValue(e, field.name)}}/>`
but is taking a lot of browser resources.
Any idea when we will get value not whole object with value and label?

**Comment by JohnDDuncanIII** [comment]
So, just to be clear, there is no longer a `valueKey` prop that will let us automatically map the value string to an attribute in the `options` array, correct?

## v1
<img width="185" alt="Screen Shot 2019-07-03 at 10 34 32 AM" src="https://user-images.githubusercontent.com/9257785/60600698-a5866800-9d7e-11e9-9628-5f9cac5a0e09.png">

<img width="1421" alt="Screen Shot 2019-07-03 at 10 34 45 AM" src="https://user-images.githubusercontent.com/9257785/60600712-b040fd00-9d7e-11e9-8c71-15f93b4180c7.png">

Although I'm almost done with the v1 to v3 upgrade, I'm a bit worried about the memory/performance implications of this, as we have hundreds of selects around our site, many of which can theoretically grow to hundreds of options with deeply dehydrated foreign keys (and many shared components that pass the id values down to Django querymethods on our backend).

**Comment by MWalid** [comment]
This can be done with `isOptionSelected`, and a wrapper component. You don't have to set the value manually.
