### ISSUE TITLE
Still having issues with unique key error when using object values

### ISSUE THREAD

**Issue by jmargaglione** [JedWatson/react-select#2844]
Using 2.0.0, I am still getting an error when I use object values with string labels.

This is the error I get:

`Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

I created a sandbox showing the behavior [here](https://codesandbox.io/s/8ylly7ppz2?module=%2Fexample.js).

Just select 'Option1' and 'Option 2' and it will emit the error to the console.

**Comment by Dakkers** [comment]
I'm no expert, but taking a look at your example makes me assume that it's coercing the `value` property to a string or something like that (hence `[object Object]` ?) which wouldn't be unique. what you can do is set the values to be e.g. `1, 2, 3` and then add an additional property called `firm` that is the `Firm` object

**Comment by robotanz** [comment]
Looks like the value should not be an object. Try to provide options like this: { value: "Option 1", label: "Option 1", data: new Firm({ legalName: "Option 1" }) },

And then use the data field to access your object, and value would contain some unique key. Worked in my case to get rid of these warnings.

**Comment by erfansamieyan** [comment]
Hi, the issues seems to be still open as I'm facing it. @robotanz suggestion seems fine but still I think it is good to have a fix in the repo itself. Can a prop like `toString` or `customKey` be passed so when it's provided something like `customerKey(value)` be set instead of value itself? 
I think that's the simple solution for fixing this bug.

**Comment by drewhaines** [comment]
I found that if I define `getOptionValue`, I can still keep the value an object but have react-select generate unique keys for the options.

For example, I am doing something like this:
```
const TestSelect = props => {
  const { testOptions } = props;

  const options = testOptions.map(test =>
      ({label: test.name, value: {id: test.id, name: test.name}})
    )

  const getOptionValue = option => option.value.id;

  const handleChange = option => setValue(option.value)

  return (
    <Select {...{ ...props, options, getOptionValue, handleChange }} />
  );
};
```

**Comment by armand1m** [comment]
to solve this: I just added a `toString()` method in the objects I pass as a value to react-select, so I can tell it how to create a key for that specific value

**Comment by armand1m** [comment]
```ts
/** useSpreadsheetData.ts */
import { useEffect, useState } from "react"
import { parse } from "papaparse"

type Entry = {
    view_name: string
    field_name: string
    table_name: string
}

const url = "someurl"

export const useSpreadsheetData = () => {
    const [state, setState] = useState<ReadonlyArray<Entry>>([])

    useEffect(
        () =>
            parse(url, {
                header: true,
                download: true,
                complete: response => setState(response.data),
            }),
        []
    )

    return state
}
```

```ts
/** SelectFields.tsx */
import * as React from "react"
import Select from "react-select"
import { useSpreadsheetData } from "./useSpreadsheetData"

export const SelectFields = props => {
    const state = useSpreadsheetData()

    return (
        <Select
            isMulti
            onChange={props.onChange}
            options={state.map(value => ({
                value: {
                    ...value,
                    /**
                     * The method above is to avoid React Select from spamming
                     * the console with key errors since it is using this object
                     * as a value for every select option
                     **/
                    toString: () => `${value.field_name}-${value.view_name}`,
                },
                label: `${value.table_name} (${value.view_name})`,
            }))}
        />
    )
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by Vaibhavthanki** [comment]
Hello- 

I found one soluction that when you are dealing with object in values at that time you have to pass the additional key.

This is the data which i feed to the react select :-

let subServiceData = data?.map((val) => {
          return {
            value: { parentId: val.parent_service_id, childId: val._id },
            label: val.sub_service_name,
            id: `${val.parent_service_id} ${val._id}`,
          };
        });
                
and then you have to pass this props in side the react select props :-
        
getOptionValue={({ id }) => id}

this code works for me well. However if you still got error please leave a comment and we"ll solve it.
