### ISSUE TITLE
[v2] Feature request: Group required html props under a single key.

### ISSUE THREAD

**Issue by allanhortle** [JedWatson/react-select#2849]
## Context
I just tried to implement custom versions of all the components. (Super cool feature btw)

It was super hard to figure out which props were part of the non-essential react-select api (styling / classes / state booleans) and which props were necessary to pass to my html elements to make the select actually function (callbacks / aria values / input configurations). 

I know the docs explain what each prop does individually but it is very hard to determine which ones as a group are needed for each component. I ended up digging through the source code to see how you had constructed each component. This task spread across the twenty-something custom components gets daunting quite quickly.

## Feature Request
I was wondering if you could add a single prop named something like `htmlProps` that contains all of the values that the html element requires. This could be spread on to the html element to achieve the basic level of interaction.

---

Issues with similar problems:
https://github.com/JedWatson/react-select/issues/2801
https://github.com/JedWatson/react-select/issues/2680
https://github.com/JedWatson/react-select/issues/2656

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
