### ISSUE TITLE
[v2] Value without passing in the entire object?

### ISSUE THREAD

**Issue by chobo2** [JedWatson/react-select#2856]
Hi

I am using version 2  and I noticed that if I try to select something pragmatically it never works for instance if I have

```
const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
] 
```

and I try to do something ike

```
StateVar = "chocolate"
<Select options={options} value={this.StateVar} />
```

nothing will be selected unless `StateVar =   { value: 'chocolate', label: 'Chocolate' }`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
