### ISSUE TITLE
ArrowRenderer not working

### ISSUE THREAD

**Issue by rgupta2** [JedWatson/react-select#2859]
I need to render my own ArrowRenderer in my app written in Typescript but am unable to use ArrowRenderer in latest react-select.

I have tried versions "react-select": "2.0.0" and "react-select": "2.0.0-beta.7" alongwith "@types/react-select":"1.3.0",

Following's the code where ArrowRenderer is not getting called.

```

import React from 'react';
import ReactSelect, { Creatable, ReactSelectProps, ArrowRendererProps } from 'react-select';
import classNames from 'classnames/bind';

import { Chevron } from './Chevron';
import styles from './Select.css';

const cx = classNames.bind(styles);

export interface Props extends ReactSelectProps {
  className?: string;
  creatable?: boolean;
  type?: 'default' | 'bare';
  valid?: boolean;
}

export const ArrowRenderer = (props: any) => {
  console.log('this got called');
  const { isOpen} = props;
  return <Chevron isOpen={isOpen} />
};

export class Select extends React.Component<Props, {}> {
  static defaultProps = {
    type: 'default',
    valid: true,
    creatable: false
  };

  render() {
    const { className, creatable, type, valid } = this.props;
    const Component = creatable ? Creatable : ReactSelect;
    return (
      <Component
        arrowRenderer={ArrowRenderer}
        searchable={false}
        clearable={false}
        simpleValue
        {...this.props}
        className={cx(className, 'my-select', type, { invalid: !valid })}
      />
    );
  }
}
```

**Comment by rgupta2** [comment]
@JedWatson I went through the documentation of latest version and came across how ArrowRenderer functionality has been moved to DropDownIndicator in components.

```
import React from 'react';
import EmojiIcon from '@atlaskit/icon/glyph/emoji';
import Select, { components } from 'react-select';
import { colourOptions } from '../data';

const DropdownIndicator = (props) => {
  return components.DropdownIndicator && (
    <components.DropdownIndicator {...props}>
      <EmojiIcon
        primaryColor={colourOptions[2].color}
      />
    </components.DropdownIndicator>
  );
};

export default () => (
  <Select
    closeMenuOnSelect={false}
    components={{ DropdownIndicator }}
    defaultValue={[colourOptions[4], colourOptions[5]]}
    isMulti
    options={colourOptions}
  />
);
```

When I tried use similar code in my TypeScript app, it complains about components not being present as a prop. 

The latest @types/react-select version seem to support only version 1.3.0 and not react-select 2.0.0

Please advise.

**Comment by claasahl** [comment]
@rgupta2 The typescript definitions for V2 ([@types/react-select](https://www.npmjs.com/package/@types/react-select)) were recently published on npm.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
