### ISSUE TITLE
[v2] Typescript typings for v2?

### ISSUE THREAD

**Issue by pondrejack** [JedWatson/react-select#2860]
Is there a specific repo outside of @types/react-select or a working branch of @types/react-select for v2 typings? There are a lot of missing types like isMulti, isClearable, etc. Been working on PRing what I run into but new ones keep popping up.

**Comment by burtek** [comment]
I'd love to know that too. @JedWatson suggested that "he'd consider that after the final release of 2.0.0" (https://github.com/JedWatson/react-select/pull/2289#issuecomment-379993069), but I did not find anything as for now

**Comment by Jtango18** [comment]
@pondrejack Have you got a fork you can share that you've been working on this in? I'd be happy to contribute to improving the mappings. The [Prop Update Guide](http://react-select.com/upgrade-guide#prop-update-guide) should be pretty usable in order to sort this. Lemme know if you want some help.

**Comment by Jtango18** [comment]
@JedWatson I'm keen to help with this, but also read your comments  [here](https://github.com/JedWatson/react-select/pull/2289#issuecomment-379993069) and understand your potential reluctance in adding official TS support. Is that still your mindset? If so, I'm happy to do the work and lodge a pull-request with the @types crew. If you'd prefer official support be here, happy to work towards that too. Lemme know what you'd prefer.

**Comment by jonfreedman** [comment]
I'm also happy to help on a PR for the definitions with @DefinitelyTyped

**Comment by burtek** [comment]
Same here :)

**Comment by m1lk1way** [comment]
same 👍

**Comment by Jtango18** [comment]
Hi @jonfreedman @burtek @m1lk1way 

I've created a new repo where I'm working on some of this in isolation. Basically just fleshing out an initial index.d.ts file which I'm slowly fleshing out based on the current @DefinitelyTyped one, and digging through the v2.0 docs and source code. 

Feel free to test it out in your own TS projects and see if you can find anything wrong with it. More than welcome to submit a PR if you have some time to expand on it.

See it here: https://github.com/Jtango18/updated-react-select-ts-defs

HTH

Cheers

JT

**Comment by jonfreedman** [comment]
Just to close this out typings for v2 have been published overnight @ https://www.npmjs.com/package/@types/react-select

**Comment by aakashsigdel** [comment]
@jochenberger The typings are not working as it complains 
```
ERROR in node_modules/@types/react-select/lib/components/Option.d.ts(17,12):
TS2314: Generic type 'MouseEventHandler' requires 1 type argument(s).
ERROR in node_modules/@types/react-select/lib/components/Option.d.ts(18,16):
TS2314: Generic type 'MouseEventHandler' requires 1 type argument(s).
```

**Comment by Wezea** [comment]
@jochenberger  I'm still facing this issue.

`node_modules/@types/react-select/lib/components/Option.d.ts
 TS2314: Generic type 'MouseEventHandler' requires 1 type argument(s).`

**Comment by jonfreedman** [comment]
@aakashsigdel @Wezea do you have an example of how you're interacting with MouseEventHandler so we can incorporate into the DefinitelyTyped tests?

**Comment by FredyC** [comment]
I had the same issue, but installing `@types/react 16.4.13` fixed it because a default for generic argument is specified for `MouseEventHandler` there.

**Comment by davad** [comment]
Are the typings up to date now? I'm getting the following typing error when I try to pass the `defaultValue` prop to `<Select>`:

Property 'defaultValue' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactSelectClass<T>> & Readonly<{ children?: ReactNode; }> & Readonly<ReactSelectProps<T>>'

I tried installing @types/react-select, but it didn't make a difference. Are the types in the main react-select package up to date now? Should I put together a PR to add this prop to @types/react-select?

**Comment by FredyC** [comment]
@davad That property is already there, so it's most likely some issue in your local installation.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2b6e08299d0793602eae13f5ea1a77fe18981c13/types/react-select/lib/Select.d.ts#L205

**Comment by davad** [comment]
@FredyC Found the problem. Someone else had already added an old version of @types/react-select to the project. Updated to 2.0, and it's working right now.

Thanks!

**Comment by quangdac** [comment]
@here I faced this error but In my project, I use yarn to manage the package. If i change to run `npm install`, it resolved the error.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
