### ISSUE TITLE
Selection options clear in multi-select after a selection is made. (uses async data)

### ISSUE THREAD

**Issue by Moebats** [JedWatson/react-select#2864]
Hi, 

I am a beginner with React using react-select to list a bunch of account objects but my options list clears after any one item is selected.  I am waiting for the list to accounts to come in through redux so I changed the const option variable to let.  

      
      let options = [];
      class AccountSelector extends React.Component {
        state = {
          selectedOption: null,
        }
        handleChange = (selectedOption) => {
          this.setState({ selectedOption });
          console.log(`Option selected:`, selectedOption);
        }
        componentDidMount () {
          this.props.getAllWatchedAccounts();
        }

        componentWillReceiveProps(nextProps) {
          if (nextProps.watchedAccounts){
            let accountsArray = _.map(nextProps.watchedAccounts);
            //I add a label property to each account since it doesn't have one
            accountsArray.forEach(element => {
              element.label = element.name;
            });
            options = accountsArray;
        } 

        }

        render() {
          const { selectedOption } = this.state;

          return (
            <Select
              isMulti
              value={selectedOption}
              onChange={this.handleChange}
              options={options}
            />
          );
        }
      }
I am not sure why the selection list clears after I select any one account?  Eventually I also want to be able to have pre selected accounts show up in the list.  Thanks.

**Comment by ReactGirl** [comment]
Is it not a similar issue that I'm having here? ( but in this case is with async)
[https://codesandbox.io/s/7yp7zr9r9x](example)

**Comment by ben-xD** [comment]
Well, I had an issue that sounds very similar, and I had to comment out the value prop to prevent the selection from disspearing after clicking.

```
          <Select
            onChange={(e) => setCurrentTimezone(e.value)}
            defaultInputValue={Intl.DateTimeFormat().resolvedOptions().timeZone.toString()}
            // value={currentTimezone} <-- this was the culprid
            options={timezones}
          />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
