### ISSUE TITLE
[V2] Dropdown with options are being cleared after Async request

### ISSUE THREAD

**Issue by ReactGirl** [JedWatson/react-select#2866]
Does anyone have this problem? 
See the two examples, one is from the docs, with "fake" data it works, but not when you actually perform a request.
[SandBox here](https://codesandbox.io/s/7yp7zr9r9x)

**Comment by hielkehoeve** [comment]
Yes. In my case I have 500 products but load only 25 initially. 
- When immediately selecting an option the value is shown after clicking it.
- When searching for a product (using the input field), selecting an item the value is not shown after clicking it. The select is cleared.

Tried overriding all methods to fix this but to no avail.

**Comment by ReactGirl** [comment]
The value is the first parameter by the way:
` <AsyncSelect
            // This is the example that the list is cleared
            cacheOptions
            defaultOptions
            value={this.state.selectedTitle}
            loadOptions={this.searchTitles}
            onChange={(value, property) => {
              console.log(property)
              this.setState({ selectedTitle: value })
            }}
          />`

However this is not my problem. My problem is the Open menu does not display the options after the search is done.

**Comment by hielkehoeve** [comment]
```The value is the first parameter by the way:```
This does not matter because of the { } around value and property.

**Comment by ReactGirl** [comment]
Try that in the sandbox and you will see that Im right.

**Comment by zigav** [comment]
Hey @ReactGirl, did you manage to solve this by any chance? I am having the same issue, and not entirely sure how to go about it.

**Comment by ReactGirl** [comment]
@zigav Not really. I think that async version is lacking of documentation and no one cares.

**Comment by Rall3n** [comment]
@ReactGirl You set the prop `defaultOptions` to `true` in your Async setup, which tells the Async component to get the default options from `loadOptions` prop. If the prop returns values (or a promise which should resolve in values) the component binds them onto the `defaultOptions` state to render as default options.

From the docs:
> The default set of options to show before the user starts searching. When set to true, the results for loadOptions('') will be autoloaded.

The request you make in your `loadOptions` function is returning an error on first render. So there can not be any values to set as default options.

**Comment by ReactGirl** [comment]
@Rall3n Thaks. So basically it is needed to have some "default" value passed to the loadOptions function.

`<AsyncSelect
            // This is the example that the list is cleared
            cacheOptions
            defaultOptions
            value={this.state.selectedTitle}
            loadOptions={this.searchTitles}
            onChange={(property, value) => {
              console.log(property)
              this.setState({ selectedTitle: property })
            }}
          />`

Then:
`searchTitles = movieTitle => {
    console.log('searching for', movieTitle)
    let searchTerm = movieTitle;
    if (!movieTitle || movieTitle===' ') {
      searchTerm = 'alien'
    }
    
    const urlRequest = `${SEARCH_URL}${NEW_API_KEY}${LANGUAGE}${QUERY}${searchTerm}${END_OPTIONS}`
//axios code here
`

**Comment by ReactGirl** [comment]
@Rall3n Thanks. 
So basically it is needed to have some "default" search as the loadOptions functions will be invoked by the first time. 
Fixed: 
https://codesandbox.io/s/7yp7zr9r9x
