### ISSUE TITLE
[Question] Multitouch collapse intended?

### ISSUE THREAD

**Issue by catamphetamine** [JedWatson/react-select#2868]
Hi.
I noticed that if I open the demo website on an iPhone and touch down with one finger, then touch down with the second finger and lift the second finger up then the select collapses.
Is this intended or did you mean ignoring multitouches completely?
If the latter then I know how to change the code.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
