### ISSUE TITLE
onChange not working with Formsy

### ISSUE THREAD

**Issue by ihd2911** [JedWatson/react-select#2869]
Following is my code, in this handleChange is not working.
I need to get value on change to get cities.

```
<SelectFormsy
className="mb-16"
name="state"
label="state"
value={state}
onChange={this.handleChange}
>
          {stateReducer.state.map((s, idx) => (
                 <MenuItem key={idx} value={s.stateName}>{s.stateName}</MenuItem>
           ))}
</SelectFormsy>
```

Constructor
` this.handleChange= this.handleChange.bind(this);`

Function
```
 handleChange= (event) => {
        console.log(['state',event.target]);
        this.setState({stateId:event.target.value});
    }
```

**Comment by scruffles** [comment]
I suspect this is the same issue:
https://github.com/JedWatson/react-select/issues/1631

The event doesn't have a target because it isn't the original react event

**Comment by cyrilf** [comment]
This is what I came up with: https://gist.github.com/cyrilf/109fc97a22cd080abcc5068a30976696
Not perfect and a bit hacky, but it solved my use-case where I really needed an `event`

Hope it helps :v:
