### ISSUE TITLE
'Select All' when in multi-value mode

### ISSUE THREAD

**Issue by aaronpowell** [JedWatson/react-select#287]
We have a scenario where we use the multi-value mode but we want a way to have the users easily select all the options, or at least all the filtered options.

While I could have a button outside the dropdown that they click on and just add them all to the state (which in turn updates the control) it'd look better all bundled together, and additionally if it's external of the control I can't access the filter value to select the subset.

**Comment by susielu** [comment]
I would also find this feature useful. Thanks for putting together a commit.

**Comment by AlexEscalante** [comment]
Please have a look at this if you still need this feature:

https://medium.com/@alex_escalante/react-select-alloptionoptions-with-a-single-click-1ebf5a33fe31
