### ISSUE TITLE
[V2] Disable default styles

### ISSUE THREAD

**Issue by burtek** [JedWatson/react-select#2872]
There is no easy way to disable all default styles to use CSS styling. I need to pass:

`styles={clearIndicator: () => ({}), container: () => ({}), control: () => ({}), ...}`

Which is (needless to say) very ugly. Please, provide a prop (i.e. `noDefaultStyles`) to be able to disable default styles.

**Comment by vikasraok** [comment]
+1

**Comment by Andries-Smit** [comment]
There is pull request open for this #3113

**Comment by Zacaria** [comment]
+1

**Comment by iJoyCode** [comment]
+1

**Comment by MobileD2** [comment]
+1

**Comment by ytkonaft** [comment]
+1

**Comment by ymazhar** [comment]
+1

**Comment by at-cuongtran** [comment]
I almost never use default style ever, maybe a theme, so it would be very helpful if we can just disable it

**Comment by iJoyCode** [comment]
+1

**Comment by Zacaria** [comment]
Hello guys, don't stay stucked here.
Patch yourself the lib and use https://www.npmjs.com/package/patch-package.

This will be much faster 😄

**Comment by Rall3n** [comment]
If you don't want to use an object with all the styles set to an empty function, why not use a [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy):

```jsx

const styleProxy = new Proxy({}, {
    get: (target, propKey) => () => {}
});

<Select styles={styleProxy} {...} />
```

It's much cleaner than a complete object.

**Comment by Methuselah96** [comment]
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by ebonow** [comment]
@Rall3n's answer appears to resolve this question.

Here is a working [codesandbox demo](https://codesandbox.io/s/react-select-unstyled-tx8z9?file=/src/App.js)

As a result, I will be closing this now, but if there are any other concerns or questions regarding this, please feel free to reply and this can be reopened if necessary.

**Comment by studnik18** [comment]
Hello. I just used the Proxy solution, but the style tags are still injected - I mean the styles for `Svg` and `a11yText`. I can't figure out how to disable them.

**Comment by unloved** [comment]
+1
