### ISSUE TITLE
[V2] ClassNamePrefix doesn't work properly if more then one classNamePrefix is provided

### ISSUE THREAD

**Issue by burtek** [JedWatson/react-select#2873]
### Example:

```jsx
<Select classNamePrefix="custom-select my-select" {...} />
```

### What happens:

Subcomponents get className `custom-select my-select__control`, `custom-select my-select__placeholder` etc.

### What should happen:

Subcomponents should get classNames `custom-select__control my-select__control`, `custom-select__placeholder my-select__placeholder` etc.

### Idea

The idea behind this is, that I want to create a custom component using (and styling by CSS) `react-select`. I pass `classNamePrefix="custom-select"` and write all CSS BEM styles for this selector. But I also want to be able to pass additional classNamePrefix to my CustomSelect to be able to add additional styles in some places. What I do is:

```jsx
<Select classNamePrefix={`custom-select ${this.props.classNamePrefix}`} {...} />
```

But it doesn't work as intended

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
