### ISSUE TITLE
[v1] Lost all GitHub docs and sources

### ISSUE THREAD

**Issue by lepinejf** [JedWatson/react-select#2880]
[https://jedwatson.github.io/react-select/](https://jedwatson.github.io/react-select/)

We're not ready to upgrade `react-select` yet and I would like to use AsyncSelect with fetch.js, but all the documentation is gone.

Help.

**Comment by mike1808** [comment]
There is a link the README of the repo. https://v1.react-select.com/

**Comment by lepinejf** [comment]
You're a champ ! Thanks !
