### ISSUE TITLE
Using grouped options with custom data shapes (Feature Request?)

### ISSUE THREAD

**Issue by JustinTBrown** [JedWatson/react-select#2882]
It would be nice to have a prop for <Select> similar to `getOptionLabel` for specifying children names when working with grouped data. Currently only children titled `options` are recognized but grouped data might not use that convention (in my case it might be called `industries`). I also asked a question about this (https://stackoverflow.com/questions/51639180/specify-group-children-other-than-options) on StackOverflow.

(Apologies, I don't know why markdown is not currently being rendered on this, or why even line breaks are not being respected.)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
