### ISSUE TITLE
Is it any posiblity to use this plugin in react-native project?

### ISSUE THREAD

**Issue by EdisonDevadoss** [JedWatson/react-select#2884]
I have react-native project in install this plugin in in my project. But its not working.

If this plgin work inside the react-native project, can you help me?

**Comment by Vynlar** [comment]
Unfortunately, react-select will not work with React Native. There are a lot of browser-specific APIs used to make everything work internally.

**Comment by EdisonDevadoss** [comment]
@Vynlar Thank you for your informations.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
