### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by FIVIL** [JedWatson/react-select#2887]
Hi, i was wondering why all the code examples which is referenced at https://jedwatson.github.io/react-select/ wont work and sources are not available it keeps giving 404

**Comment by Vynlar** [comment]
That is the link to the documentation of version 1 of this library. See [react-select.com](http://react-select.com/home) for the new version 2 documentation.

**Comment by FIVIL** [comment]
@Vynlar  Ty

**Comment by Vynlar** [comment]
Addressed in #2897
