### ISSUE TITLE
[v2] [help wanted] FilterOptions prevent create action CreatableSelect

### ISSUE THREAD

**Issue by lbelavoir** [JedWatson/react-select#2889]
### Use case

I have tried to add a `filterOption` props on a `CreatableSelect` the result is the `filterOption` works but I have lost the `Create ...` option in the select dropdown.

The filter options are pretty standard:
```
const filterOptions = createFilter({
  ignoreCase: true,  
  ignoreAccents: true,
  matchFrom: 'start'
})
```

### Live example
https://codesandbox.io/s/j3834v8o3

### Result previews
<img width="672" alt="screen shot 2018-08-02 at 3 30 29 pm" src="https://user-images.githubusercontent.com/3958890/43614637-11d9701a-9669-11e8-816d-5707f80ae55e.png">

<img width="674" alt="screen shot 2018-08-02 at 3 27 26 pm" src="https://user-images.githubusercontent.com/3958890/43614514-9e454bc4-9668-11e8-8c8b-801312d38c5a.png">

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by lbelavoir** [comment]
This is still an issue on `react-select@3.1.0`, can you please consider a fix ?

**Comment by bladey** [comment]
Thanks @lbelavoir!

**Comment by drbeat** [comment]
Just ran into the same issue.

**Comment by ebonow** [comment]
@lbelavoir Your live example does not correspond with what you provided as the codesandbox example is not Createable which is maybe why you might not be seeing a create option.

[Please refer to this codesandbox](https://codesandbox.io/s/react-select-creatable-filteroptions-t58w7) and verify that the issue is still present. If so I can reopen the issue.

**Comment by lbelavoir** [comment]
Still a failure and v2 see the [example](https://codesandbox.io/s/react-codesandboxer-example-forked-hbhp6?file=/example.js) but working correctly on `3.1.1` !

**Comment by ebonow** [comment]
@lbelavoir It looks like your import seems a bit off.

Try changing your import from:
`import CreateSelectable from "react-select";`

for V3 use:
`import Createable from "react-select/creatable";`
https://codesandbox.io/s/react-select-creatable-filteroptions-v311-092x3?file=/src/App.js

or for V2 use:
`import { Createable }  from "react-select";`
https://codesandbox.io/s/react-select-creatable-filteroptions-v244-t58w7?file=/src/App.js


That should hopefully be working for you better.

**Comment by rodbs** [comment]
It's not working for me.
I've created this filter to filter by the beginning of the word, but then the "Create" option disappears (v 3.1.1).
Does anyone know why? is it supposed to be fixed?

```
 <CreatableSelect                
                  onChange={handleChange}
                  onInputChange={handleInputChange}
                  onCreateOption={handleCreate}
                  options={wordSelect}
                  createOptionPosition={2}
                  filterOption={customFilterOption}
                />
```
 ```
const customFilterOption = (option, rawInput) => {
    const words = rawInput.split(" ");
    return words.reduce(
      (acc, cur) =>
 
        acc && option.label.toLowerCase().startsWith(cur.toLowerCase()),
      true
    );
  };
```

**Comment by ebonow** [comment]
@rodbs Please try using `filterOptions` instead of `filterOption` and see if it works better for you.

Demo: [codesandbox](https://codesandbox.io/s/react-select-custom-filter-options-vgqcx)

**Comment by rodbs** [comment]
@ebonow 

It's weird.
Using `filterOptions` the create option works but the filtering doesn't (doesn't filter by the beginning of the input).
Using `filterOption`, the filtering option works but the create new option disappears.

**Comment by ebonow** [comment]
sorry @rodbs updated response above

**Comment by rodbs** [comment]
@ebonow It works now, Thanks!
