### ISSUE TITLE
disable auto close clicked on renderer

### ISSUE THREAD

**Issue by maxlibin** [JedWatson/react-select#2890]
I have created a tooltip inside renderer, however I want to able to select text inside this tooltip, problem is when i clicked the dropdown will close, any idea how can I fix this?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
