### ISSUE TITLE
[v2] ("loadingMessageCSS" and "noOptionsMessageCSS") or ("loadingMessage" and "noOptionsMessage")

### ISSUE THREAD

**Issue by claasahl** [JedWatson/react-select#2892]
Should these fields be named `loadingMessage` and `noOptionsMessage`? 

https://github.com/JedWatson/react-select/blob/b34589446345a6d90e353a97ab7eff1700423e33/src/styles.js#L46

https://github.com/JedWatson/react-select/blob/b34589446345a6d90e353a97ab7eff1700423e33/src/styles.js#L53

**Background**: `defaultStyles` does not include `loadingMessageCSS` and `noOptionsMessageCSS`, but `loadingMessage` and `noOptionsMessage`.

https://github.com/JedWatson/react-select/blob/b34589446345a6d90e353a97ab7eff1700423e33/src/styles.js#L62-L85

**Comment by IanVS** [comment]
Yes, from testing it out, it does seem that the docs are incorrect.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
