### ISSUE TITLE
[V2] add documentation example showing use of formatOptionLabel

### ISSUE THREAD

**Issue by jonfreedman** [JedWatson/react-select#2893]
In order to clarify the documentation it would be great to add an example showing how to use formatOptionLabel to customise the format of a colourOption using the `color` property value.  As I found out myself, there's a couple of ways to achieve this (see https://github.com/JedWatson/react-select/pull/2879) and I think that PR is the wrong way?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
