### ISSUE TITLE
Reverting to a simple text input when no options exist

### ISSUE THREAD

**Issue by rkmcdonnell** [JedWatson/react-select#2895]
Hello,

I'd like users to be able to be able to enter any input, even if it's not in the list of options.  I've searched these issues and SO, but haven't been able to find a simple way to do this.  Creatables offer one way to handle inputs not in the options array, but I would prefer if the options list simply disappeared and the user enters their custom input into the text field manually (as opposed to clicking "Create [option]").  This seems to be standard behavior on some similar projects to react-select - am I missing something?  Seems like it would be a useful feature.  Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
