### ISSUE TITLE
Unable to Add React-Select in Project

### ISSUE THREAD

**Issue by lemscorner** [JedWatson/react-select#2896]
Hi,

I tried using react-select in a new project and it worked perfectly with no issues. I then tried using react-select in one of our existing projects and encountered a weird issue.

Whenever I add an `import Select from 'react-select'` I get the following error when loading my application:

> Exception thrown and not caught

The error is then pointed to:

    function _inherits(subClass, superClass) {
        if (typeof superClass !== "function" && superClass !== null) {
            throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
        }
        subClass.prototype = Object.create(superClass && superClass.prototype, {
            constructor: {
                value: subClass, enumerable: false, writable: true, configurable: true
            }
        });
        if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;
    }

I'm not sure what I missed.

I'm using webpack to repackage my solution. Below is my json config file:

    {
        "name": "web",
        "version": "0.1.0",
        "description": "",
        "main": "index.js",
        "scripts": {
            "start": "npm-run-all --parallel open:src lint:watch test:watch",
            "open:src": "babel-node tools/srcServer.js",
            "lint": "node_modules/.bin/esw webpack.config.* src tools",
            "lint:watch": "npm run lint -- --watch",
            "test": "mocha --reporter progress tools/testSetup.js \"src/**/*.test.js\"",
            "test:watch": "npm run test -- --watch",
            "clean-dist": "npm run remove-dist && mkdir dist",
            "remove-dist": "node_modules/.bin/rimraf ./dist",
            "build:html": "babel-node tools/buildHtml.js",
            "prebuild": "npm-run-all clean-dist test build:html",
            "build": "babel-node tools/build.js",
            "postbuild": "babel-node tools/distServer.js"
        },
        "repository": {
            "type": "git"
        },
        "keywords": [
            "react",
            "redux"
        ],
        "author": "Mobile Development Team",
        "license": "ISC",
        "dependencies": {
            "babel-polyfill": "6.8.0",
            "bootstrap": "3.3.6",
            "jquery": "2.2.3",
            "react": "15.0.2",
            "react-dom": "15.0.2",
            "react-redux": "4.4.5",
            "react-responsive-modal": "^3.2.0",
            "react-router": "2.4.0",
            "react-router-redux": "4.0.4",
            "redux": "3.5.2",
            "redux-thunk": "2.0.1",
            "toastr": "2.1.2"
        },
        "devDependencies": {
            "babel-cli": "6.8.0",
            "babel-core": "6.8.0",
            "babel-loader": "6.2.4",
            "babel-plugin-react-display-name": "2.0.0",
            "babel-preset-es2015": "6.6.0",
            "babel-preset-react": "6.5.0",
            "babel-preset-react-hmre": "1.1.1",
            "babel-register": "6.8.0",
            "cheerio": "0.22.0",
            "colors": "1.1.2",
            "compression": "1.6.1",
            "cross-env": "1.0.7",
            "css-loader": "0.23.1",
            "enzyme": "2.2.0",
            "eslint": "2.9.0",
            "eslint-plugin-import": "1.6.1",
            "eslint-plugin-react": "5.0.1",
            "eslint-watch": "2.1.11",
            "eventsource-polyfill": "0.9.6",
            "expect": "1.19.0",
            "expose-loader": "^0.7.5",
            "express": "4.13.4",
            "extract-text-webpack-plugin": "1.0.1",
            "file-loader": "0.8.5",
            "font-awesome": "^4.7.0",
            "jsdom": "8.5.0",
            "mocha": "2.4.5",
            "nock": "8.0.0",
            "npm-run-all": "1.8.0",
            "open": "0.0.5",
            "react-addons-test-utils": "15.0.2",
            "react-select": "^2.0.0",
            "redux-immutable-state-invariant": "1.2.3",
            "redux-mock-store": "1.0.2",
            "rimraf": "2.5.2",
            "seamless-immutable": "^7.1.3",
            "style-loader": "0.13.1",
            "url-loader": "0.5.7",
            "webpack": "1.13.0",
            "webpack-dev-middleware": "1.6.1",
            "webpack-hot-middleware": "2.10.0"
        }
    }

**Comment by mitin001** [comment]
@lemscorner Why is react-select listed as a devDependency? Shouldn't it be a dependency?

**Comment by KrzysztofMadejski** [comment]
@lemscorner can this issue be closed?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
