### ISSUE TITLE
Add className support in options objects

### ISSUE THREAD

**Issue by emattias** [JedWatson/react-select#290]
I need to add an image to every option in the select (see my attached image). My idea is that if you add a className property to every option object the class will be added to the .Select-option div.

![screen shot 2015-07-02 at 09 57 20](https://cloud.githubusercontent.com/assets/351537/8472341/c2990ace-20a0-11e5-9889-d1b37e199cdf.png)

**Comment by brianreavis** [comment]
I'd check out the relatively new "optionRenderer" property for cases like this. It allows for even more granular control – each option can have its own markup that you define.

**Comment by bruderstein** [comment]
Yes, this is exactly what optionRenderer is for - see the example with gravatars. 

I was going to close this, but actually I'm thinking supporting this would only be a matter of adding to the default `<Option>` component, so we're not really adding any unnecessary complexity to `<Select>`.  I know @JedWatson has some plans for being more flexible with options, but not sure if that fits in or not.
