### ISSUE TITLE
You seem to be using a value for 'content' without quotes, try replacing it with `content: '" "'`

### ISSUE THREAD

**Issue by FerusAndBeyond** [JedWatson/react-select#2904]
I'm getting the following error: 

```
You seem to be using a value for 'content' without quotes, try replacing it with `content: '" "'`
```

In my own application and in a random example linked from react-select.com, [example](https://codesandbox.io/s/485olxq064?module=/example.js), if you check in the developer console the error should be displayed, at least on chrome.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
