### ISSUE TITLE
[V2] Feature Request: Disable Focus

### ISSUE THREAD

**Issue by wootencl** [JedWatson/react-select#2905]
Would be nice if there was the ability to disable the focus of react-select. By disabling focus I mean allow the user to click `react-select`, have it open/respond accordingly, _but_ it would _not_ take focus as it currently does.

The reasoning/use case behind this for me specifically is the scenario where you're in a text editor and (for example) you want to create a font size selector with `react-select`. You would then highlight the text you wish to modify then click on `react-select` to open a menu of font size choices. At current this would not work as your text selection will be wiped by `react-select`'s built in functionality to automatically put focus on its input.

Proposing the addition of a new `disableFocus` (or something along those lines) prop. Have a good idea of how to go about accomplishing this within the code so happy to create a PR, etc. if this is something you all would be willing to merge into the core library. 

Aside, thanks for the excellent module/component 🙂.

**Comment by kvarela** [comment]
Not sure if this falls under the same feature request, but is there a way to turn off the blue highlight that appears when the Select is focused?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
