### ISSUE TITLE
Options having same key when trying to add options with the same values.

### ISSUE THREAD

**Issue by mannebusk** [JedWatson/react-select#291]
When you are running create mode and create two options with the same value. React throws a warning "Encountered two children with the same key", and only renders the first one. The state still holds all typed options.

**Comment by the4dpatrick** [comment]
+1 

Just ran into the same problem today

**Comment by brianreavis** [comment]
What's the use case for allowing multiple copies of the same option?

**Comment by pindia** [comment]
I get this even before creating the option, as soon as I mouse over the "Add {label}?" item. This is for an input with `allowCreate` true, but `multi` false.

**Comment by mannebusk** [comment]
I don't think you should be able to add the same option twice. And if you wanted to add the same option multiple times, they would have to have an id to differentiate them even if they have the same label.

**Comment by mannebusk** [comment]
@pindia I updated the pull request with a fix for that. The "Add {label}?" option had the same key as the "normal" options when you type in a option vlaue that already exists.

I also changed so that an option can't be added multiple times.

**Comment by somlor** [comment]
Also having this issue. :+1:

**Comment by randavidovitz** [comment]
I think #421, fixes it ?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
