### ISSUE TITLE
Navigate

### ISSUE THREAD

**Issue by FIVIL** [JedWatson/react-select#2912]
Hi, is it possible to navigate to lets say another page while a user selects one of the options??
and if yes then how?? i couldnt find any resource regarding to this in docs.

**Comment by ixrock** [comment]
@FIVIL 

```jsx
function Navigation() {
  var options = [
    { value: "/", label: "Home" },
    { value: "/about", label: "About" },
  ];
  return (
    <Select
      defaultValue={options[0]}
      onChange={({ value }) => location.href = value}
    />
  )
}
```

**Comment by FIVIL** [comment]
@ixrock 
tnx, this works but the problem is that it makes entire app to reload (page will refresh) and this is kind of undesired with react

**Comment by ixrock** [comment]
@FIVIL of course. It's just example of what you've been asking.
Check this https://reacttraining.com/react-router/web/guides/philosophy for more understanding about routing and reloading a page state in react apps.
