### ISSUE TITLE
The React Select is Uncontrolled 

### ISSUE THREAD

**Issue by chungchi300** [JedWatson/react-select#2913]
### Thanks for using react-select!

Before creating an issue...

# Are you reporting a bug or runtime error?
Bug

# Are you making a feature request?
No

*   What's your use case? (Tell us about your application and what problem you're trying to solve.)
I want to make it as controlled component. When it's props is undefined,it should remain undefined

**Comment by Pruxis** [comment]
I found the solution apperantly the magic trigger that decides wether or not your component is controlled is to set the inputValue also as a controlled value.

**Comment by gwyneplaine** [comment]
@chungchi300 please add more information and a codesandbox reproduction for your issue for us to triage it effectively, as of right its too nebulous. 

v2 is definitely controlled if you specify a value prop, default value prop, inputValue prop or defaultInputValue prop. 

Closing this issue in the meantime, happy to be of more assistance when more information is provided.
