### ISSUE TITLE
Position OptionsLits in scrolling v2

### ISSUE THREAD

**Issue by GruFFix** [JedWatson/react-select#2927]
Hi. I'm using property `menuPortalTarget` in React Select V2 to display a lit of options with React.Portal.

The error  occurs if the Select is inside the block with overflow: scroll / auto

```
const portalTargetElement = document.getElementById('select-menu-portal');

<AsyncSelect
    noOptionsMessage={() => t('No data')}
    loadingMessage={() => t('Loading...')}
    options={options}
    isSearchable={isSearchable}
    blurInputOnSelect={false}
    styles={customStyles}
    label={placeholder}
    menuPortalTarget={portalTargetElement}
    loadOptions={loadOptions}
    onBlur={() => onBlur(value)}
    onChange={option => onChange(option)}
    value={value}
    formatOptionLabel={formatOptionLabel}
    components={{
        Menu,
        DropdownIndicator,
        Option,
        Control,
        ValueContainer,
        SingleValue,
        MenuList,
        IndicatorSeparator: null,
    }}
    {...rest}
/>
```
`<div id="select-menu-portal">` is inside the `<body>`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
