### ISSUE TITLE
Trying to override MultiValueContainer in react-select, but it is not receiving the Option data

### ISSUE THREAD

**Issue by winterspan** [JedWatson/react-select#2929]
I'm attempting to override the MultiValueContainer so that I can optionally show an icon next to the MultiValueLabel. I tried this already with the MultiValueLabel Component, but the docs suggest that it does not receive the option data, but the MultiValueContainer does. So I'm now attempt that...
e.g.

```
<CreatableSelect
   components={MultiValueContainer: CustomMultiValueContainer}
...

const CustomMultiValueContainer = (props) => {
    return (
        <components.MultiValueContainer {...props}>
            { props.option.showIcon &&
              <i class="user-icon" >
            }
            {props.children}
        </components.MultiValueContainer>
    )
}

```
When I do this, the only thing in props is the two children (the MultiValueLabel and MultiValueRemove). How do I get access to the option data here?

**Comment by winterspan** [comment]
Turns out I just needed to use the stable release version of react-select v2. Beta-6 had broken the functionality. MultiValueContainer/MultiValueLabel now receive the underlying option data as expected.

**Comment by Paddy-Hamilton** [comment]
@winterspan Im finding the same issue, but can seem to find what would be considered the "stable" release of v2. what version are you running?

Cheers

**Comment by IanVS** [comment]
I think this issue should be closed?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
