### ISSUE TITLE
value state update not updating the select list  - react-select

### ISSUE THREAD

**Issue by AirborneEagle** [JedWatson/react-select#2932]
Okay, although this is not a bug, it has come about from lack of information.
I have put this information out there to hopefully help someone else. I spent too long figuring this out.
 
GIVEN: I have a state controlled react-select list with dynamic options ( also state controlled)
WHEN: a background function updates the options and changes the value state
THEN: the select list options update as expected. It also clears any pre-selected value but the list does not select the new value. only shows the placeholder text.

The select list would not update to show the new value when the state was changed.

A new record was created, background functions would setState({ selectOptions: newListofOptions })
then it would setState({ selectedOption: valueOfNewRecord })

The list would go back to having nothing selected and showing the placeholder. Even though the options are updated and contain the new value.

SOLUTION:
IF:
 <ReactSelect value = {this.state.selectedOption}  />

THEN: 

this.state.selectedOption must equal an object like { label: "option A", value: "optionAValue" } 

this.state.selectedOption = "optionAValue"      <---- this does not work

I found that if onChange={this.handleChange}
then
    handleChange(option) {
        this.setState({
            selectedOption: option,
        })
    }

----- Option does not equal the selected value, but rather it is the option OBJECT  --> {label:"option name", value: "optionValue"}

**Comment by Isarstyle** [comment]
had the same issue as in an old version of the react-select the value was working as a string, now you have to pass the label/value object to display any kind of value.

**Comment by jossmac** [comment]
Please see [the docs](http://react-select.netlify.com/props#prop-types). The shape of `value` is:

```js
value: Object | Array<Object>
```

---

Closing in favour of #2920
