### ISSUE TITLE
Inconsistent arguments passed to getStyles()

### ISSUE THREAD

**Issue by jossmac** [JedWatson/react-select#2935]
The `getStyles` call for `menuPortal` receive an object derived from target/menu placement as the second argument rather than `props` as all other components.

The `<MenuPortal />` component receives `commonProps` like other components, they just need to be passed on correctly; at least `selectProps`.

Ref #2838

**Comment by plondon** [comment]
Similar issue here https://github.com/JedWatson/react-select/issues/2947

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
