### ISSUE TITLE
[Question]: What happened to "shouldKeyDownEventCreateNewOption"

### ISSUE THREAD

**Issue by shezankazi** [JedWatson/react-select#2938]
I just upgraded to v2 and am missing `shouldKeyDownEventCreateNewOption` on my `CreatableSelect`. Is there a new way to implement this?

**Comment by lxender** [comment]
It has been removed from v2 for some reason. My idea would be to handle it by using onKeyDown to set field in the state to the current key and checking in onCreateOption if the wanted key was pressed

**Comment by karlingen** [comment]
Take a look at the example called **Multi-select text input**, found at https://react-select.com/creatable

Particularly this logic:
```jsx
handleKeyDown = (event: SyntheticKeyboardEvent<HTMLElement>) => {
    const { inputValue, value } = this.state;
    if (!inputValue) return;
    switch (event.key) {
      case 'Enter':
      case 'Tab':
        console.group('Value Added');
        console.log(value);
        console.groupEnd();
        this.setState({
          inputValue: '',
          value: [...value, createOption(inputValue)],
        });
        event.preventDefault();
    }
  };
```

[Demo](https://codesandbox.io/s/n81o5?module=/example.js)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
