### ISSUE TITLE
GroupHeading does not receive most props

### ISSUE THREAD

**Issue by plondon** [JedWatson/react-select#2947]
Forked sandbox: https://codesandbox.io/s/w661ojq8mk

See image, the GroupHeading component does not receive props, such as `selectProps`

<img width="819" alt="screen shot 2018-08-17 at 2 28 42 pm" src="https://user-images.githubusercontent.com/5640772/44282809-3d906700-a22a-11e8-92da-576e4f488684.png">

**Comment by yurii-lubynets** [comment]
@plondon is this issue fixed? How can I receive selectProps in the GroupHeading component?

**Comment by plondon** [comment]
@yurii-lubynets it's not fixed but there was a similar issue opened and the maintainers are dealing with almost 1k issues 😬

**Comment by plondon** [comment]
Here's the other issue: https://github.com/JedWatson/react-select/issues/2935
