### ISSUE TITLE
valueRenderer works only if multi={true}

### ISSUE THREAD

**Issue by FrancescoCioria** [JedWatson/react-select#296]
I tried using ```valueRenderer``` without ```multi``` set to true but it didn't work.
I gave a look at the code and found out that ```valueRenderer``` is only used inside [this if block](https://github.com/JedWatson/react-select/blob/bbefe623c26d476eae75aef7b0263f98f89d620d/src/Select.js#L712-L723)

**Comment by nonken** [comment]
+1 Would be awesome if this would work with non-multi as well

**Comment by paltman** [comment]
:+1: would love to have this as well

**Comment by 0xCMP** [comment]
@JedWatson @brianreavis Would this be something you guys would like to have fixed? I need to fix this anyways for my self and I'd be happy to submit the PR.

**Comment by brianreavis** [comment]
Yeah, that's be awesome! Thanks @0xCMP
