### ISSUE TITLE
Missing 2.0.0 tag

### ISSUE THREAD

**Issue by jprosevear** [JedWatson/react-select#2962]
Looking to track down a bug that may have occurred after 2.0.0, however the 2.0.0 tag on git and 2.0.0 release on github are missing.

However the npm repo shows 2.0.0. as the latest release:
https://www.npmjs.com/package/react-select

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
