### ISSUE TITLE
Unknown small element showing up on focusing on empty input

### ISSUE THREAD

**Issue by Gunner17** [JedWatson/react-select#2968]
I am using react-select 1.2.1 and trying to load the options asynchronously by myself. 
But, when I click/focus on the empty input I see some unknown element (hardly visible) showing up below the input, it affects the bottom border radius of the search input box. I am not quite sure what is that element or why is it showing up? I had tried to prevent it by setting : 
noResultsText={''}. But it has not effect. Please help me figure out how to stop this weird behavior!
It seems like that the Select control may be trying to show some result by itself when the search string is empty, but I don't want to show any text at all even when there is not search result and setting the noResultsText to {''} did not help as well.
(Is there a way to attach screenshot here ?)

Here is my JSX for the Select control :

`<Select
					onInputChange={this.handleTextChange}
					onChange={this.handleSelectChange}
					isLoading={this.state.isLoading}
					options={this.state.options}
					placeholder={this.props.placeholder}
          			removeSelected={this.state.removeSelected}
					simpleValue
					value={this.props.value}
					arrowRenderer={this.props.search ? null : this.arrowRenderer}
					noResultsText={''}
				/>`

**Comment by flexdinesh** [comment]
Hey @Gunner17 [v1 of react-select is no longer maintained](https://github.com/JedWatson/react-select/pull/3786). 

We recommend maintaining your own v1 fork if you want to address `v1` issues. We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest versions.

We highly recommend [upgrading from v1 to v2](https://react-select.com/upgrade-guide). Chances are this issue might already be fixed or non-existent in v2.

I'm closing this issue/PR now. Feel free add your thoughts in #3981 and reference this issue/PR if needed.
