### ISSUE TITLE
Allow validation with the required property

### ISSUE THREAD

**Issue by vmendoza** [JedWatson/react-select#297]
Validation is a huge part of web dev, and the current component does not play well with tools such as Jquery validation

**Comment by neemzy** [comment]
Huge +1 on this

**Comment by amitthakkar22288** [comment]
+1

**Comment by WhatAKitty** [comment]
+1

**Comment by pvieira91** [comment]
+1 for this, it would be great

**Comment by IanVS** [comment]
This worked for a while in V1, but was removed in V2.  :(

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
