### ISSUE TITLE
Paste values

### ISSUE THREAD

**Issue by omidnikrah** [JedWatson/react-select#2977]
Hi, Is there any way to paste values into the Multi-select text input?

**Comment by jossmac** [comment]
![paste-values-multi](https://user-images.githubusercontent.com/2730833/44757581-3d219580-ab73-11e8-86a3-7d75fffd158d.gif)

**Comment by omidnikrah** [comment]
I want to paste something like `purple, Red, Ocean` and React-select converted that into the tags.

**Comment by jossmac** [comment]
Okay I see; you'll need to take control of the `value` and `inputValue`. Something like:

```jsx

class MySelect extends Component {
  onChange = (value) => {
    this.setState({ value });
  };
  onInputChange = (inputValue) => {
    this.setState({ inputValue }, () => {
      // logic for splitting on comma, and finding matching options
      const value = splitValue(inputValue);
      this.onChange(value)
    });
  };
  render() {
    return (
      <Select
        onChange={this.onChange}
        inputValue={this.state.inputValue}
        value={this.state.value}
      />
    );
  }
}
```

---

In the future, please don't file GitHub issues to ask questions. Use StackOverflow and tag your question with [#react-select](http://stackoverflow.com/questions/tagged/react-select)

**Comment by omidnikrah** [comment]
Thanks for helping me

**Comment by omidnikrah** [comment]
What is the `onInputChange`? You don't call that anywhere.

**Comment by jossmac** [comment]
updated

**Comment by omidnikrah** [comment]
But something else, I'm using `AsyncCreatable` and when I paste something, first `AsyncCreatable` call my API and if is not exist I can add it.
Is there any way to when pasting something, ignore API call?

**Comment by jossmac** [comment]
Mate, i'm not support. I'm just a guy that helps maintain this repo. I have a full-time job like you.

**Comment by omidnikrah** [comment]
Yes, Thanks :)

**Comment by ThierryCols** [comment]
> Yes, Thanks :)

have you tried the `allowCreateWhileLoading` props ?

**Comment by omidnikrah** [comment]
@ThierryCols No, but I think it's not what I need. I wrote a tags input component from scratch.
