### ISSUE TITLE
react-select.com link doesn't work

### ISSUE THREAD

**Issue by nikhilag** [JedWatson/react-select#2978]
I am not able to access the documentation or examples because react-select.com doesn't load. 
v1.react-select.com works but not react-select.com

**Comment by JimyJacob** [comment]
Same here

**Comment by watert** [comment]
Same here

**Comment by jossmac** [comment]
This may be an issue with netlify and subdomains; for now please try http://www.react-select.com or go directly to http://react-select.netlify.com

**Comment by JimyJacob** [comment]
Thank You @jossmac

**Comment by gwyneplaine** [comment]
This issue appears to be resolved. Closing now
