### ISSUE TITLE
removeSelected is missing??

### ISSUE THREAD

**Issue by kaushik-nimble** [JedWatson/react-select#2979]
# removeSelected is missing?
I don't find this prop in current doc. How can I achieve this functionality? I want item to be available in list.

**Comment by jossmac** [comment]
Hi @kaushik-nimble,

In version 2 `removeSelected` is now `hideSelectedOptions`. Please see the [Upgrade Guide](http://react-select.netlify.com/upgrade-guide#prop-update-guide) if you have other concerns.
