### ISSUE TITLE
how to get value

### ISSUE THREAD

**Issue by shangsunset** [JedWatson/react-select#298]
Hi,
how do you get selected value in single and multi-select?  `this.refs.{whatever}.getDOMNode().value` is not working and i didnt find a answer elsewhere. 

thanks.

**Comment by brianreavis** [comment]
Like other form controls in React, use the `onChange` property to watch for changes. How to go about it is documented in the [readme](https://github.com/JedWatson/react-select).

**Comment by cheton** [comment]
Here is my wordaround:
```js
onSubmit() {
    let node = React.findDOMNode(this.refs.myselect)
        .querySelector('input[name="form-select"]');
    console.log(node.value);
}
render() {
    return (
        <Select
            ref="myselect"
            name="form-select"
                :    :    :
        />
    );
}
```

**Comment by robertfw** [comment]
I also want to get the value without having to use a callback, as I'm handling changes on form submission, not as they change. 

I'm currently using the following work around:
```
let value = this.refs['my_select'].refs.value.value;
```

While fugly, it's less fugly than tracking state
