### ISSUE TITLE
free text

### ISSUE THREAD

**Issue by stevemao** [JedWatson/react-select#2984]
# Are you making a feature request?
Yes

So I use this component for type ahead/autocomplete/suggestions. But users are not limit to choose an option from the dropdown list. `onChange` will be triggered once user hit enter. Currently a work around is to pop current user input into `options`.

**Comment by gwyneplaine** [comment]
@stevemao, at first glance this seems like something that can be accomplished using the Creatable component we export http://react-select.com/creatable. 

Is there any reason why this may not be the case, also could you provide us with a sandbox of your current use case? This will make it easier for us to determine how to best approach this request 👍

**Comment by stevemao** [comment]
Yeah I think it can. I was new to this module so I just did a global search on type ahead/autocomplete/suggestions/free text, couldn't find anything. Maybe we could add these keywords?
