### ISSUE TITLE
[v2] No way to manually set isLoading on async select box

### ISSUE THREAD

**Issue by standayweb** [JedWatson/react-select#2986]
So I'm using the isLoading prop on the normal Select to show a loader in the select box after you select something while it is fetching data to populate some fields below.

Somewhere else in the app I am trying to do the same with the async select component and it doesn't seem to work, I think it should be possible to override the isLoading prop.

**Comment by fkarlin** [comment]
I think I have the same problem as you, if you mean the text "Loading ..." that appears? I want to be able to delete it or alternatively edit the text.

**Comment by standayweb** [comment]
@fkarlin I'm talking about the indicator not the text

**Comment by ebonow** [comment]
This is still an issue! The isLoading prop gets completely ignored by the AsyncSelect. 

```javascript
    constructor(props: Props) {
      super();
      this.state = {
        defaultOptions: Array.isArray(props.defaultOptions)
          ? props.defaultOptions
          : undefined,
        inputValue: '',
        isLoading: props.defaultOptions === true ? true : false,
        loadedOptions: [],
        passEmptyOptions: false,
      };
    }
    componentDidMount() {
      this.mounted = true;
      const { defaultOptions } = this.props;
      if (defaultOptions === true) {
        this.loadOptions('', options => {
          if (!this.mounted) return;
          const isLoading = !!this.lastRequest;
          this.setState({ defaultOptions: options || [], isLoading });
        });
      }
    }
```

**Comment by Mawaheb** [comment]
has this been fixed?

**Comment by aurels** [comment]
Will this PR be merged ? :-)

**Comment by oudoulj** [comment]
Sorry for the [duplicate](https://github.com/JedWatson/react-select/pull/3690#issuecomment-516452843) but I'm still trying to figure out how to **always** hide the _"Loading..."_ and the _3 dots_ on the right while typing in an Async select [v3].
How do I do that ?
Thanks!
![Async select](https://i.ibb.co/g7B51y0/Screenshot-30-07-2019-16-41-18.png)

**Comment by firrae** [comment]
Trying to understand this, but is `isLoading` now an option on async-select/async-creatable? I just want to set it when I load in the data in the background because I manually handle it currently.

**Comment by ebonow** [comment]
> Sorry for the [duplicate](https://github.com/JedWatson/react-select/pull/3690#issuecomment-516452843) but I'm still trying to figure out how to **always** hide the _"Loading..."_ and the _3 dots_ on the right while typing in an Async select [v3].
> How do I do that ?
> Thanks!
> ![Async select](https://camo.githubusercontent.com/faeac25f0f10a8db868c7c75a1f01d90458a38d4/68747470733a2f2f692e6962622e636f2f673742353179302f53637265656e73686f742d33302d30372d323031392d31362d34312d31382e706e67)

Replace the LoadingIndicator component with null

```
<Select {...yourOtherProps} components={{ LoadingIndicator: null }} />
```

**Comment by oudoulj** [comment]
> LoadingIndicator:

I had already tried `components={{ LoadingIndicator: null }}` to no avail.
It worked with Styles and loadingIndicator/loadingMessage like I explain [here] though (https://github.com/JedWatson/react-select/pull/3690#issuecomment-522943841).

**Comment by Mujaddadi** [comment]
I am still facing this issue in Async selector

**Comment by lxm7** [comment]
I'm doing this currently to fix it:

`useEffect(() => {
    // Force state isLoading to false on initial render
    ref.current.state.isLoading = false;
}, [])`

**Comment by HarshaLaxman** [comment]
I fixed it by calling the callback in the 'getOptions' function

`
if (input.length < 3) {
      callback(null, {
        complete: true,
        options: [],
      });
}
`

**Comment by tonypee** [comment]
Really... async loading is broken... in a component that loads and shows options?

**Comment by AdnanBoota** [comment]
Any update for V3, manually add spinner on isLoading?

**Comment by ebonow** [comment]
> Any update for V3, manually add spinner on isLoading?

The fix for this was addressed in this PR and is supported in the current version of react-select.
https://github.com/JedWatson/react-select/pull/3690

**Comment by igor-martins-ugowork** [comment]
Hi, I am with react select version 5.8.0. I am using AsyncSelect and setting the isLoading property to false or undefined. The intention is to avoid the "..." while typing anything, but it seems to ignore the property and keeps the "...".

**Comment by eddielu** [comment]
I am experiencing the same thing as you @igor-martins-ugowork . AsyncSelect appears to ignore the `isLoading` property. Did you ever find a way around it?
