### ISSUE TITLE
value and label keys should not be hard coded

### ISSUE THREAD

**Issue by stevemao** [JedWatson/react-select#2987]
I don't use `value` and `label` keys for value and label, so I have a `getOptionLabel` and  `getOptionValue` to get them.

https://github.com/JedWatson/react-select/blob/2654ce0505d9e3820e169109cc413778fc20f843/src/Creatable.js#L41-L42

They just use the hardcoded `value` and `label` key on the option. They should come from `getOptionLabel` and  `getOptionValue`

**Comment by stevemao** [comment]
Looks like https://github.com/JedWatson/react-select/pull/2956 will fix this bug

**Comment by gwyneplaine** [comment]
thanks for this @stevemao, closing this in favor of tracking progress on it in a single issue 
#2953
