### ISSUE TITLE
Module not found: Can't resolve 'react-select/dist/react-select.css'

### ISSUE THREAD

**Issue by lausellduane** [JedWatson/react-select#2991]
I got this error today with the latest version react-select@2.0.0. There was thread about this error it was closed on January but the issue is not resolved. I read that for v2 the CSS is loaded by react-select and It doesn't need to be imported manually but I still get the error even after deleting the manual import from the file.

**Comment by FredyC** [comment]
Check the docs, V2 is a complete overhaul and it is no longer exporting any CSS. You have to either stick to v1 or use the new styling options.

**Comment by gwyneplaine** [comment]
@lausellduane  as specified above, v2 does not export a react-select.css file. This is not a bug and an intentional decision to move towards a default styling method using css-in-js.
