### ISSUE TITLE
[V2] Default behavior of isOptionSelected sets isSelected for all options

### ISSUE THREAD

**Issue by FredyC** [JedWatson/react-select#2997]
Might not be a that big issue since `isOptionSelected` can be overridden, but it's at least confusing for a newcomer (like me). For some reason, I was unable to replicate the issue in the sandbox provided by you, so I made my own. When you open the menu you can see everything isSelected.

https://codesandbox.io/s/o10nrr4o9y

Apparently, the `getOptionValue` returns `undefined` by default so this check always ends up true.

https://github.com/JedWatson/react-select/blob/f70ce3578bc1e12a83ba44fb583043a1e16a18e3/src/Select.js#L818

**Comment by gwyneplaine** [comment]
Hi, @FredyC  this is not a bug. isOptionSelected by default checks against the value property of your options objects. You've specified a key property, which is fine so long as you use the getOptionValue prop to specify the check on the [key] property. 

See the following sandbox for an example of how to go about doing this: 
https://codesandbox.io/s/w23pvjyq6k

Thanks for logging the issue though, as this is not made super clear in the docs. I've created a separate issue to ensure that this information is captured for other users looking to get started 
https://github.com/JedWatson/react-select/issues/3006
