### ISSUE TITLE
How to disable "Hide dropdown menu if click occurred outside of menu"?

### ISSUE THREAD

**Issue by BenGedi** [JedWatson/react-select#301]
Please see my codio example,

I made some changes to the css file, the `container` position is absolute and the `option list` position is relative instead of absolute, so when now when i click on the input its position changes (because the option list is relative and the container is absolue), and it triggers the `eventOccuredOutsideMenu`, 
the option list opens up and imminently closes, because the input is not stays in the same place as it was when the click first occur.

How can i disable the `eventOccuredOutsideMenu`?
**or even better**, make the option list count as like it was a part of the menu (select input), so it wont trigger the `eventOccuredOutsideMenu`.

My codio Example: https://codio.com/BenGedi/react-select

**For initialize please do:**
- right click on index.html -> preview static.
- click on the search input to see the bug.

_optional: copy the preview url and paste it into your browser._

Thanks, 
ben

**Comment by prasadsampath** [comment]
hi, Did you find a workaround for this?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
