### ISSUE TITLE
Filtering Sensitivity (searchable)

### ISSUE THREAD

**Issue by hakanozkaptan** [JedWatson/react-select#3012]
Hello I have city array like this and I use searchable feature.

[Munich, Berlin, New York, San Fransisco, Boston, Oslo]

When i typing "O". I want to show first **Oslo** then New York, San Fransisco, Boston. 
How can i do.

**Comment by sahibjotsaggu** [comment]
@hakanozkaptan Have you taken a look here: https://react-select.com/advanced?

Check out the "Custom filterOption with createFilter" section. You could create a custom filter.

**Comment by hakanozkaptan** [comment]
Thank you.
I updated to v2 and I used "Match from the start"
