### ISSUE TITLE
[v2] Custom styles not passing data for components.Option

### ISSUE THREAD

**Issue by khuezy** [JedWatson/react-select#3015]
# Are you reporting a bug or runtime error?
Click on the Select and see the error
https://codesandbox.io/s/00zqzj8mjv

I'm trying to get the `option` callback to pass the `data` of my option, but it is returning `undefined` when I'm using a custom component.

**Comment by WagnerSilveira** [comment]
I am facing the same problem

**Comment by sahibjotsaggu** [comment]
https://codesandbox.io/s/32mq9qvwoq

**Comment by khuezy** [comment]
Thanks @sahibjotsaggu !

**Comment by IanVS** [comment]
@sahibjotsaggu the sandbox is dead.  Can you share your solution here?

Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
