### ISSUE TITLE
Data Source Update and selected 'label' update issue

### ISSUE THREAD

**Issue by vaikoovery** [JedWatson/react-select#3019]
When I have translation feature on the website, I would like to update the data options of the select as well. If an option is selected and language change happens then, options get updated however the selected label doesn't get updated to the latest translation data (or vise versa)

I've tried to reproduce the issue here.
https://codesandbox.io/s/k0k9rz375

The checkbox in the page can be considered as language change trigger.

When the options get updated, the corresponding label of previously selected value should be displayed.

**Comment by sahibjotsaggu** [comment]
@vaikoovery https://codesandbox.io/s/jn4nnzkxqv
