### ISSUE TITLE
Source links in docs all point to non-existent pages

### ISSUE THREAD

**Issue by d07RiV** [JedWatson/react-select#3022]
All "(Source)" links in docs point to files like https://github.com/JedWatson/react-select/tree/master/examples/src/components/States.js which don't seem to exist.

**Comment by DaskJeeves** [comment]
Seriously, this is pretty frustrating. You removed all the examples that show people how to use it

**Comment by jshah** [comment]
There's a new site for docs now: https://react-select.com/components

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
