### ISSUE TITLE
Very hard to see v1 props documentation

### ISSUE THREAD

**Issue by theGABS** [JedWatson/react-select#3024]
Hi, react select is awesome, but I still use v1. And I spend 10 minutes each time when I wanna find this page https://github.com/JedWatson/react-select/tree/v1.x 

On current github page exist link to this http://v1.react-select.com/ - and when I go here from github and see link to github (correct v1) I just don't open, because it is looks like infinity loop :( 

I believe you should understand what I wrote, but my english is not perfect.

**Comment by sahibjotsaggu** [comment]
You can create a bookmark for https://github.com/JedWatson/react-select/tree/v1.x so you don't have to spend 10 minutes each time.

**Comment by axlekb** [comment]
Thanks for that advice, @sahibjotsaggu, however, that still means folks still may still spend 10 minutes trying to find the old docs the first time.

**Comment by theGABS** [comment]
@sahibjotsaggu LOL:) , of course after several time when I repeated this now I can. But I just wanna it will be changed for other people who still use v1

**Comment by sahibjotsaggu** [comment]
@theGABS @axlekb I think a good way to do this could be by putting a note at the top of the master branch README.md.

Something like:

**If you are looking for the v1 source code, go here: [link]**

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
