### ISSUE TITLE
Documentation > Advanced  - Custom filterOption with createFilter displays the same code

### ISSUE THREAD

**Issue by Nasmar** [JedWatson/react-select#3025]
On the Documentation under Advanced (Here: https://react-select.com/advanced )

Under "**Custom filterOption with createFilter**" and "**Custom filterOption with createFilter**" the same code example is linked, also the same headline is used.

The "Using a custom filter to always display this option on search" doesn't seem to show the code for that, but instead shows the code for the above filterOption display.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by bladey** [comment]
Hi @Nasmar,

Thanks for bringing this to our attention.

It looks like this has since been resolved - react-select.com/advanced

Please let me know if I'm wrong and I'll reopen this issue!
