### ISSUE TITLE
[v2] Change the label for multiple selection (documentation not so helpful)

### ISSUE THREAD

**Issue by adibalcan** [JedWatson/react-select#3026]
For multiple selections, I have tried to change the behavior of MultiValueContainer to show 
**the number of selections if the selections number is greater than 2** else **enumerate the selections** (the current behavior). 

The documentation is not helpful enough for me to understand how to override this component in order to obtain desired behavior.

**Comment by sahibjotsaggu** [comment]
Can you show the code that you have tried?

**Comment by vdesdoigts** [comment]
Hello, have you find a solution?

**Comment by adibalcan** [comment]
We have abandoned the feature that uses this in our application.

Many thanks,

Adrian Balcan
+40 733 981 260

*TheWebMiner.com <http://thewebminer.com/>*

Check out our new product, FeedCheck <https://feedcheck.co>!

**Comment by IanVS** [comment]
Sounds like you could close this issue then?

**Comment by adibalcan** [comment]
yes

Many thanks,

Adrian Balcan
+40 733 981 260

*TheWebMiner.com <http://thewebminer.com/>*

Check out our new product, FeedCheck <https://feedcheck.co>!

**Comment by curiousPup** [comment]
is there still no solution available for this?

**Comment by adibalcan** [comment]
In the following image, you will see a multi-select composed by styled
Checkboxes:

[image: image.png]

First 2 checkboxes are not selected but the last three are selected. These
were my desired output, but I obtained this by using classic checkboxes
with no visibility and stars as labels.

Many thanks,

Adrian Balcan
+40 733 981 260

*TheWebMiner.com <http://thewebminer.com/>*

Check out our new product, FeedCheck <https://feedcheck.co>!
