### ISSUE TITLE
Clear dropdown when user chooses an option from another dropdown

### ISSUE THREAD

**Issue by kennyhuynh125** [JedWatson/react-select#3028]
Hi everyone,

I am having an issue where I need to clear the current chosen option of a dropdown when the user selects an option from another dropdown.

For example, I have two dropdowns, both starting with placeholder Select...
User selects option 'A' from first dropdown.
User then selects option 'Hello' from second dropdown. When the user selects this, it should clear the option 'A' from the first dropdown and bring it back to the placeholder Select.... or an empty string.

I tried using the value props but that didn't seem to work. I also tried using defaultInputValue but that didn't work as well.

Any ideas, tips, or solutions on how to fix this?

Thanks!

**Comment by sahibjotsaggu** [comment]
@kennyhuynh125  You can make the values of both the selects 'controlled' (use state to control them) and then onChange, just set the value of the other dropdown to empty.

**Comment by kennyhuynh125** [comment]
@sahibjotsaggu I tried that, but then when I add the value props and select an option on the dropdown, the option doesn't show up on the dropdown. The state changes in the background, but it still shows my placeholder ('Select...')

**Comment by sahibjotsaggu** [comment]
@kennyhuynh125 Let's see some code please.

**Comment by kennyhuynh125** [comment]
@sahibjotsaggu  sorry about the late reply. One question, could it be because im passing in props to the value props? As in, I have a component that renders the Select component, and I have another component that passes in props to the values/options/onChange fields.

**Comment by sahibjotsaggu** [comment]
@kennyhuynh125 No, that doesn't seem like a problem but I won't be able to tell for sure until I can see some code.

**Comment by Luke-Chatburn** [comment]
I had this problem, you need to set the value of the select every time, so i stored some state for selectedValue. Then when you want to clear a select you can just set it to an empty string or null. Hope this helps.

`<Select placeholder='Select first value...' value={selectFirstValue} onChange={onFirstValueChange} />
<Select placeholder='Select second value...' value={selectSecondValue} onChange={onSecondValueChange} />

onFirstValueChange (selectedOption) {
  return this.setState({
    selectFirstValue: selectedOption, 
    selectSecondValue: '', 
  });
}

onSecondValueChange (selectedOption) {
  return this.setState({
    selectFirstValue: '', 
    selectSecondValue: selectedOption, 
  });
}`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by sekersalih** [comment]
yes , problem is continue
