### ISSUE TITLE
Default selected items don't appear when using transitions if select is hidden

### ISSUE THREAD

**Issue by huw** [JedWatson/react-select#3029]
# Steps to reproduce:

1. Create a component that initially hides its children using `display: hidden`
2. Put a React Select in this component, and make it a multi-select
3. Enable animations
4. Add some default selected items

# Expected behaviour

The default selected items should appear inside the select box

# Actual behaviour

The default selected items do not appear. In particular, they have a width of 0:

<img width="486" alt="screen shot 2018-09-12 at 2 59 43 pm" src="https://user-images.githubusercontent.com/2456132/45403180-86f29b80-b69c-11e8-80a8-0626580b09c1.png">

This is because the React transition has not correctly expanded their widths to their ordinary widths.

[This behaviour is replicated in this sandbox.](https://codesandbox.io/s/23lmm10yzy) Click the button to expand the Expander.

**Comment by s20lee** [comment]
When the component is Multi-value and is animated, it gets wrapped with <Collapse /> component:

In [https://github.com/JedWatson/react-select/blob/master/src/animated/MultiValue.js](url):

![image](https://user-images.githubusercontent.com/33851384/46057744-4deb0a00-c125-11e8-96c6-008d99eaa7ea.png)

And, if you look into the Collapse component in [https://github.com/JedWatson/react-select/blob/master/src/animated/transitions.js](url), it sets width of the component as 'auto':

![image](https://user-images.githubusercontent.com/33851384/46057945-5abc2d80-c126-11e8-8f59-ba3e185dc055.png)


Because of this, if the component is initially 'display:none', those default value components have width of  0. 

Unless there is a width props passed down to the child component, I think you can use 'visibility: hidden' instead of 'display:none'. It's just a workaround, but at least it works.

**Comment by kstratis** [comment]
Any updates on this one?

**Comment by madou** [comment]
I think the fix would be to not set the width of the item until the element starts leaving the DOM. Just in time stuff :)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by desbrowne** [comment]
If anyone needs a solution, this worked for our project. Basically, when Exit is called for a MultiValue, width is set directly on the ref div. The next state change sets the width to 0 and the CSS width transition does its magic. A small side benefit is that there is no measuring required at mount.

// Collapse.tsx
```tsx
import * as React from 'react';
import { Transition } from 'react-transition-group';

const transition = `width 260ms ease-out`;
interface Props {
	children: any;
	in: boolean;
	onExited: () => void;
}
const Collapse: React.FC<Props> = ({ children, in: inProp, onExited }) => {
	const ref = React.useRef<HTMLDivElement>(null);
	const handleExit = React.useCallback(() => {
		if (ref.current) {
			const { width } = ref.current.getBoundingClientRect();
			ref.current.style.width = `${width}px`;
			ref.current.style.transition = transition;
		}
	}, []);
	return (
		<Transition
			enter={false}
			mountOnEnter
			unmountOnExit
			in={inProp}
			timeout={300}
			onExited={onExited}
			onExit={handleExit}
		>
			{state => (
				<div
					ref={ref}
					style={
						state === 'exiting' || state === 'exited'
							? {
									overflow: 'hidden',
									whiteSpace: 'nowrap',
									width: 0,
									transition,
							  }
							: undefined
					}
				>
					{children}
				</div>
			)}
		</Transition>
	);
};

export default Collapse;
```

// AnimatedMultiValue.tsx
```tsx
import * as React from 'react';
import { MultiValueProps, OptionTypeBase, components } from 'react-select';

import Collapse from './Collapse';

interface Props extends MultiValueProps<OptionTypeBase> {
	in: boolean;
	onExited: () => void;
}
const AnimatedMultiValue: React.FC<Props> = ({ in: inProp, onExited, ...props }) => (
	<Collapse in={inProp} onExited={onExited}>
		<components.MultiValue {...props} cropWithEllipsis={inProp} />
	</Collapse>
);

export default AnimatedMultiValue;
```

```tsx
// usage
const components = makeAnimated();
components.MultiValue = AnimatedMultiValue as React.FC<MultiValueProps<OptionTypeBase>>;
return (
	<Select 
		components={components} 
		value={value}
		options={options}
		onChange={handleChange}
	/>
);
