### ISSUE TITLE
zIndex on document.body (dropdown)

### ISSUE THREAD

**Issue by wesleywong** [JedWatson/react-select#3030]
Is there a way that we can assign a class inside menu container? Currently I used below code to open dropdown and attach to body.

`menuPortalTarget={document.body}`

the problem for this is the init div (dropdown) z-index is 1 by default and class name default is something css-*(randomly). I wonder that I can just assign my own class something similar like classNamePrefix ?

The issue now is dropdown menu is hidden on modal popup. I was trying to change the zIndex but have no solution yet.

Please advise, thanks

**Comment by ZackKnopp** [comment]
From their example of portalling you can pass styles to the menuPortal component, see [here](https://react-select.com/advanced#portaling)

`styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}`

Full component example:
```
<Select
  defaultValue={colourOptions[0]}
  isClearable
  styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
  menuPortalTarget={document.body}
  isSearchable
  name="color"
  menuPosition={isFixed ? 'fixed' : 'absolute'}
  menuPlacement={portalPlacement}
  options={colourOptions}
/>
```

**Comment by jf97** [comment]
Since there might be the possibility of multiple <Select /> components, and you really only need the zIndex to be big when the component is active, this solution worked for me: 

```
const customStyles = {
            container: (base, state) => {
                return ({
                    ...base,
                    zIndex: state.isFocused ? "999" : "1"  //Only when current state focused
                })
            }
        }

return <Select 
   ...
   styles={customStyles}
/>
```

**Comment by vzsky** [comment]
I have tried all above solutions but nothing works.
Anyway, I found this and it worked for me.

```styles={{menu: (styles) => Object.assign(styles, {zIndex: 1000})}}```

Yep, simply add this into the Select property like, 

```
<Select
            styles={{menu: (styles) => Object.assign(styles, {zIndex: 1000})}}
            options={options}
 />
```

hope this help :)

**Comment by bladey** [comment]
Hi all,

Thanks for all your helpful answers.

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by srinivasmerugu** [comment]
> ```
> const customStyles = {
>             container: (base, state) => {
>                 return ({
>                     ...base,
>                     zIndex: state.isFocused ? "999" : "1"  //Only when current state focused
>                 })
>             }
>         }
> 
> return <Select 
>    styles={customStyles}
> />
> ```
> 
> Since we only need the zIndex to be high when the component is focused, use a conditional styling for the container. Otherwise if you happen to have multiple components (or other components requiring a high zIndex) it might cause problems if all of them have the same 999 zIndex.

hi @lbj1960 I like this conditional adding of zindex however it was not adding 9999 zindex when I tried your approach .. Am I missing something here?
