### ISSUE TITLE
【bug】react-select 1.x searchable will cause the Firefox 62 crash

### ISSUE THREAD

**Issue by CherishLY** [JedWatson/react-select#3031]
The browser will be crash when i use the searchable attribute or the disabled  attribute and it's value is true on the version of Firefox is 62  on the windows.
when i click the area around the select that add the disabled attribute, the browser also crash

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
