### ISSUE TITLE
Typings of State wrong because of wrapping StateManager

### ISSUE THREAD

**Issue by LeopoldLerch** [JedWatson/react-select#3033]
I am using react-select together with Typescript. Just found an issue there, don´t know if it is correct here:

I am making an reference to the select-component in my parent component in order to be able to get it´s selected values later on. I found out that this is possible by accessing it´s state. However, it seems that the state i am getting there is not the state of the select. I found out that the actual Select is wrapped into a "StateManager" which has it´s own state. 

In the select itself, the values would be stored in a property called "SelectedValues", and that´s what typescript is offering me when accessing the state in my ref. However, in runtime it does not work, because the actual state object, which is the one of the "StateManager" does not have this property, but holds it in a "value" property. 

So the typings are not correct here. Altough the typed State would be correct for the actual Select-Component, this state is not reachable because it is wrapped into the StateManager.

**Comment by claasahl** [comment]
Hi @LeopoldLerch 

The typescript typings are maintained [here](https://github.com/DefinitelyTyped/DefinitelyTyped). If you are only interested in getting the selected values, you might be looking for the `onChange` callback (see [example](https://codesandbox.io/s/8145ljpzyj)).

Are you willing to share a minimal example, which illustrates your point?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
