### ISSUE TITLE
blinking text on multiple select

### ISSUE THREAD

**Issue by brunoreis** [JedWatson/react-select#3035]
I have react-select working in a project with bootstrap. I'm seeing the following behavior when I type. Any ideas what could be wrong? 
![blinking-react-select](https://user-images.githubusercontent.com/217240/45492042-a7286600-b741-11e8-96de-56202d94c601.gif)

**Comment by sahibjotsaggu** [comment]
There is most likely a CSS `transition` property coming from either bootstrap or something else.

**Comment by uidev547** [comment]
.Select-input > input {
		-moz-transition: none;
		-ms-transition: none;
		-webkit-transition: none;
		transition: none;
	}

**Comment by sahibjotsaggu** [comment]
Can you post the entire code on CodeSandbox and link it here?

**Comment by uidev547** [comment]
I experienced the same thing in one of my project, as the input applied with css transition. Please check in your code base if transition has applied to input. 

This issue is not from react-select library.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
