### ISSUE TITLE
Autosize doesn't work, width is broken, input sizing issue

### ISSUE THREAD

**Issue by wimbush** [JedWatson/react-select#3039]
The width of the element only grows on type. 

This means some of the input data is not visible since the box is only 50px wide.

This has been reported as fixed, but I don't think it is.

Let me know if I can provide more info.

**Comment by wimbush** [comment]
*UPDATE* - by moving the select element outside of all parents, I removed the issue.

Now I'm digging to see which parent CSS is incompatible.

**Comment by jt3k** [comment]
reopen issue . this is a bug
