### ISSUE TITLE
Documentation example differ from reality

### ISSUE THREAD

**Issue by bologer** [JedWatson/react-select#3040]
Go to [this](https://react-select.com/styles#overriding-the-theme) example and then go to [Codesandbox](https://codesandbox.io/s/1oz7n0wok4?module=/example.js) and you will see that the result of the example differ from what is shown on the example page.

Example is supposed to be changed based on provided theme styles, but this is not happening. Not really sure what it is related to.

In documentation: 
![image](https://user-images.githubusercontent.com/9879933/45584173-75450a00-b8cf-11e8-9a84-257f57062bc3.png)

In sandbox: 

![image](https://user-images.githubusercontent.com/9879933/45584178-7d04ae80-b8cf-11e8-9d3f-984483f2f6df.png)

**Comment by sahibjotsaggu** [comment]
https://github.com/JedWatson/react-select/pull/2839

Read the last couple comments.

**Comment by bologer** [comment]
@danpoq hm, I'm a bit confused, any date when it will be released?

**Comment by SamalaSumanth0262** [comment]
Same issue with theme overiding ,got any solution?
 @sahibjotsaggu

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
