### ISSUE TITLE
Docs: expand code examples by default?

### ISSUE THREAD

**Issue by axlekb** [JedWatson/react-select#3041]
In the docs, can you expand the example code by default?

I've been a v1 user for a long time, but am having a bunch of trouble digesting these new v2 docs.  The new documentation often contains a vague/unhelpful description of a `prop`, so I try look for an example where that `prop` may be used.  Unfortunately the code examples are collapsed by default, and not findable using browser, so I have to open each one to see if it is used there, and often find no example.

Would be great to have them expanded by default.

**Comment by Luke-Chatburn** [comment]
Would be great to have examples of all props.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
