### ISSUE TITLE
Feature request: Options list to be added on top of all the elements on the page

### ISSUE THREAD

**Issue by georgel-pop** [JedWatson/react-select#3044]
I have this select component used inside of a popup and everytime I open the select list is increasing the popup body height in order to have space for the opened list and this creates unexpected problems of rendering on ios(ipad). Also I need to always check if I have space down or up to control where to render the list.

I would like to have the possibility to render this options list in a specific div outside of the body popup so it can be placed on top of any element in the dom. 

As first solution I was thinking that could be used a popover('react-popover') to add this options list on a main dom so it can be placed on top of any element on the page. This solution would be ideal as the popover also calculates the space on the viewport and is placing the list on the right direction without any other calculations needed.
https://reactstrap.github.io/components/popovers/

Another possible solution it can use React Portal to add the list to a main div based on an id as a property.
https://reactjs.org/docs/portals.html

![screen shot 09-17-18 at 04 35 pm 001](https://user-images.githubusercontent.com/20664961/45630360-d966fa00-ba98-11e8-93ae-0f8bb3629c75.PNG)
![screen shot 09-17-18 at 04 35 pm](https://user-images.githubusercontent.com/20664961/45630400-ea177000-ba98-11e8-80ee-76ccf7d4d438.PNG)
![screen shot 09-17-18 at 04 35 pm 001](https://user-images.githubusercontent.com/20664961/45630540-2f3ba200-ba99-11e8-9869-f9baec24fce8.png)

**Comment by RamYadlapalli** [comment]
Did you try using portaling feature in react-select V2, it might solve your problem as it can render dropdown as a portal which can be attached to any DOM element
Refer: https://react-select.com/advanced#portaling

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
