### ISSUE TITLE
Opinion of react-styled-select lib ? based on react-select

### ISSUE THREAD

**Issue by DougWoodCDS** [JedWatson/react-select#3045]
Hi,
I was just searching around for resources on using react-select with styled-components and ran across this library.
[https://github.com/agutoli/react-styled-select](url)
it looks promising but was wondering if anyone had opinions on this approach, or was actually using this library.
Thanks for any input.

**Comment by rlech** [comment]
imho is the v2.0 js-css styling just for trolling devs using react-select in production with scss.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
