### ISSUE TITLE
Doesn't display the selected option (Single Select & getOption)

### ISSUE THREAD

**Issue by katsos** [JedWatson/react-select#3048]
I have an array of strings and using `getOptionValue` and `getOptionLabel` I want to use them in Select component.
If Select is in "multi" mode, it is working properly, if not, it doesn't display the selected option.

React v15 +
React Select v2

live example: https://codesandbox.io/s/v0kp0607x7

**Comment by sahibjotsaggu** [comment]
https://codesandbox.io/s/n155n953p4

Just do that instead of using `getOptionLabel` and `getOptionValue`

**Comment by katsos** [comment]
This is not an option in our project because I have to update parent onChange and the array is huge and it ia coming from backend dynamically. Plus there are 10+ Select components in a page.  
So if I do it your way, I have to deserialize on `onChange` and serialize on `value` props, after every change.

**Comment by sahibjotsaggu** [comment]
`getOptionValue` and `getOptionLabel` won't work on primitives (like strings)... They take in objects and return strings so you have to reformat your array of strings into an array of objects.

**Comment by katsos** [comment]
In multi mode it works just fine. It's definitely a bug!

**Comment by sahibjotsaggu** [comment]
@katsos Oh, I didn't see that part in your initial comment. Yes, looks like a bug. Feel free to submit a PR.

**Comment by ShonP** [comment]
+1

**Comment by theskillwithin** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
