### ISSUE TITLE
AsyncSelect Grouped Options

### ISSUE THREAD

**Issue by davidyin1212** [JedWatson/react-select#3051]
Hey I am not too clear if this falls into something I'm doing wrong, a bug, or a feature request so I'm posting it here to clarify. But it seems like the grouped api for options does not work for AsyncSelect let me give an example:
```promiseOptions(inputValue = "") {
    return new Promise((resolve, reject) => {
      Promise.all([
        api.fetchAllBusinessServicesList(inputValue),
        api.fetchTechnicalServicesList(inputValue),
      ])
        .then((options) => {
          let technicalServices = get(options[1], "data.services", [])
          let businessServices = get(options[0], "data.business_services", [])
          console.log(technicalServices)
          console.log(businessServices)
          let asyncOptions = [
            {
              label: "Technical Services",
              options: getOptions(technicalServices),
            },
            {
              label: "Business Services",
              options: getOptions(businessServices),
            },
          ]
          console.log(asyncOptions)
          resolve(asyncOptions)
        })
        .catch((e) => {
          console.log(e)
          let asyncOptions = [
            {
              label: "Technical Services",
              options: [{ value: "test", label: "test" }],
            },
            {
              label: "Business Services",
              options: [],
            },
          ]
          console.log(asyncOptions)
          resolve(asyncOptions)
        })
    })
  }
```
The above is my promiseOptions function the point is to return a promise which resolves into groups options format eg:
```
[
{label: "group1" options: [{value:"test", label:"test"}]},
{label: "group2" options: [{value:"test", label:"test"}]},
]
```
I then pass it into the component below as such:
```
<AsyncSelect
        isMulti
        closeMenuOnSelect={false}
        cacheOptions
        defaultOptions
        loadOptions={this.promiseOptions}
        onChange={handleChange}
        value={value}
      />
```
And I don't notice anything when I make changes to input nor do I see any of the groups I made. So my question is am I doing something wrong, is their a bug with this, or is this feature for groups not implemented yet for the AsyncSelect Component thanks.

**Comment by guiyep** [comment]
Is it possible to someone to review this?

**Comment by bladey** [comment]
Hello @guiyep,

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
