### ISSUE TITLE
Input component does not have selectProps as a prop

### ISSUE THREAD

**Issue by amirnafei** [JedWatson/react-select#3052]
All the react-select components (like ValueContainer, Menu, ...) have selectProps included among their props (as it is described in the documentation) while this is not happening for the Input component.

**Comment by gwyneplaine** [comment]
thanks for raising this @amirnafei, Input component has now been updated to be passed selectProps as of v2.2.0. 
Closing this issue now

**Comment by thefran1412** [comment]
Hi! I'm having the same problem in version `3.1.0`. This is my code:

``` javascript
const styles = {
	input: (provided, state) => {
		console.log(state.selectProps) // this outputs: undefined
		return {
			...provided,
			color: state.selectProps.txtColor
		}
	},
}
```

**Comment by trevorglick** [comment]
just ran into this, we're on react-select 3.0.8 this is what the state object shows in the input api:
`aria-autocomplete: "list"
aria-label: undefined
aria-labelledby: undefined
autoCapitalize: "none"
autoComplete: "off"
autoCorrect: "off"
id: "react-select-19-input"
onBlur: ƒ (event)
onChange: ƒ (event)
onFocus: ƒ (event)
spellCheck: "false"
tabIndex: "0"
theme: {borderRadius: 4, colors: {…}, spacing: {…}}
type: "text"
value: ""`

**Comment by cchoiniere** [comment]
Can this issue be re-opened? Looks like as of 3.0.X that state no longer has selectProps. This makes it difficult to control styles as needed.

**Comment by tavurth** [comment]
I'm having an issue with this now, was wondering for the last hour why my `react-hook-form` wasn't working, turned out to be this component.

**Comment by tavurth** [comment]
I'm having an issue with this now, was wondering for the last hour why my `react-hook-form` wasn't working, turned out to be this component.

**Comment by stcalica** [comment]
selectProps does not work for my component when passing into the custom styles object. 
In my case, I'll need to create different variants just for width alone.

**Comment by markovone** [comment]
looks like `styles.menuPortal` cant access selectProps either

**Comment by tavurth** [comment]
What's the reason this issue is closed?

**Comment by ebonow** [comment]
Greetings, 

It was closed because it has been merged into master. I would have to do a bit more digging to find where it was added in, but it was a recent addition such that selectProps should be accessible to the Input component. 

```jsx
  const styles = {
    input: (css, state) => ({ ...css, color: state.selectProps.color })
  };

  return (
    <>
      <Select color="blue" options={basicOptions} styles={styles} />
    </>
  );
};
```

[codesandbox demo
](https://codesandbox.io/s/react-select-input-selectprops-uw45k)
