### ISSUE TITLE
[v2] Unexpected render state for controlled inputValue 

### ISSUE THREAD

**Issue by njradford** [JedWatson/react-select#3053]
When using a Select component and providing an inputValue. The value is not rendered fully within the Select component until it is clicked.

[Example A](https://i.imgur.com/0wElGXC.png)
[Example B](https://i.imgur.com/hwmM6jw.png)

```javascript
import React from 'react';

import Select from 'react-select/lib/Select';

type Props = {

}

type State = {
  inputValue: string
}

class IssueExample extends React.Component<Props, State> {
  constructor(props) {
    super(props);
    this.state = {
      inputValue: 'Controlled input test'
    }
  }

  private handleInputChange = inputValue => {
    this.setState({
      inputValue
    })
  };

  public render() {
    return (
      <Select inputValue={this.state.inputValue} onInputChange={this.handleInputChange}/>
    );
  }
}

```

**Comment by yairEO** [comment]
I've solved this by hacking the CSS on my end with:

    .select-prefix__input > input{ opacity: 1 !important; }

Apparently the opacity of the input is `0` until clicked... I'm not sure if this is a good solution, I think not, but for now it works.
