### ISSUE TITLE
All Option components being re-rendered due to cx and getValue props changing at each render

### ISSUE THREAD

**Issue by adam1658** [JedWatson/react-select#3055]
Hi there, thanks for a great select component!

I am using a custom Option component and have noticed poor performance when moving through the options with the keyboard or mouse hover.
My Option component extends React.PureComponent, so shouldn't update unless it's props change. So when moving focus from one option to the next, only 2 Options should re-render (the one losing focus, and the one gaining focus).
I have noticed however, that all my Options are re-rendering, because the `cx` and `getValue` props are changing.
This really slows the render down in my application when moving focus - it takes ~60ms to re-render the list when re-rendering all my options (~150 of them)

I can work around it by implementing shouldComponentUpdate on my custom Option like this:
```js
shouldComponentUpdate(nextProps) {
    return !shallowEqual( // true if each key value pair in the provided objects is equal (===)
        omit(this.props, ['cx', 'getValue']), // omit returns a copy of the provided object, without the 'cx' or 'getValue' keys
        omit(nextProps, ['cx', 'getValue']),
    );
}
```

Here's a codesandbox which logs to the console when an Option is updating and `cx` or `getValue` changes seemingly unnecessarily: https://codesandbox.io/s/ypy2p2vqp9?module=%2Fexample.js
Open the console, open the select then move focus up and down with the keyboard. This codesandbox doesn't feel laggy like it does in my real world application, but does show the props changing.

Thanks,
Adam

**Comment by hrafaelveloso** [comment]
Does this issue have one workaround? I'm facing the same problem.
