### ISSUE TITLE
Creatable with grouped options

### ISSUE THREAD

**Issue by sarink** [JedWatson/react-select#3056]
Is there support for using option groups within a Creatable? It looks like there are a lot of problems with this. Everything from the type definitions (ie, `OptionType | OptionType[]`) to the callbacks (`isValidNewOption, getOptionLabel, getOptionValue`) seem to be broken in this case.

Is there any workaround today?

Demo: https://codesandbox.io/s/8z099x6572 (start typing in the select box)

**Comment by sarink** [comment]
Update: Just found this issue https://github.com/JedWatson/react-select/pull/2659

**Comment by ebonow** [comment]
Just stopping by to post that this has been resolved at some point in v2 as it appears to be working in react-select v2.4.4 since there is an open PR pointing to this issue.

demo: [codesandbox](https://codesandbox.io/s/react-select-pr-3338-creatable-support-with-groups-je1bn)
