### ISSUE TITLE
Feature request: add marks for all clickable elements

### ISSUE THREAD

**Issue by gdh1995** [JedWatson/react-select#3062]
>  What's your use case? (Tell us about your application and what problem you're trying to solve.)

I want to use the browser extension [Vimium](https://github.com/philc/vimium) (or some other tools) to click most "clickable" items on webpages.

>  What interface do you have in mind? (What new properties or methods do you think might be helpful?)

Currently, Vimium's `LinkHints.activateMode` checks DOM attributes and tagNames to learn whether elements are clickable.

But React Select renders all nodes using `<div>`, `<span>` and `<svg>` and appends no special information to them (except CSS styles for `:hover`, which is hard to tell from and (might) expensive to detect):

![image](https://user-images.githubusercontent.com/5547703/45927835-26047680-bf6c-11e8-97e5-a8491a9f21e4.png)

As a result, Vimium won't mark those buttons clickable, which is a little inconvenient.

>   Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

A common case (for Vimium) to mark them is to add `role=button` to those wanted elements.

--------

I know that this feature can be implemented by users of this library, but it would be better that this popular project adds native supports ^_^

The source of this idea is from https://github.com/philc/vimium/issues/3139, where a user reports Vimium can not hint React Select's transparent 2px-wide inputs. The issue may be solved by updating Vimium, while it's not so easy to mark other elements.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
