### ISSUE TITLE
Async Select 2.0 customize selected option

### ISSUE THREAD

**Issue by sarveshascbe** [JedWatson/react-select#3070]
After user selects an option from the dropdown the selected option label is displayed in the value of async select. 

For example: if my selected option label contains text "Sarvesh Ramamoorthy <sarveshatcbe@gmail.com", after selection would display the same. 

I need to customize so that the value displayed after selecting an option from the options dropdown i should display "Sarvesh Ramamoorthy" without email. 

I do store the actual data object in a javascript array in value field of options array. Example : First element of array would have structure like : {FirstName: "Sarvesh", LastName : "Ramamoorthy", Email : "sarveshatcbe@gmail.com"}

How should this be resolved, if not if its an existing issue please do fix it as soon as possible.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
