### ISSUE TITLE
Update react-select on npm

### ISSUE THREAD

**Issue by isitrita** [JedWatson/react-select#3077]
Hi, could you publish react-select 2.1.0 on npm?
Last updated version there is 2 months ago version.

**Comment by 7c78** [comment]
I want to use custom `theme` prop to set height of the component. It is not available in v2.0.0. Please publish new version to npm!

**Comment by socca1157** [comment]
Agreed, please update NPM..

**Comment by 7c78** [comment]
look like maintainers of this repo have no intent to answer any issue, and to close issue neither.

**Comment by denchp** [comment]
An NPM update would be great - and some bug fixes to come soon?

**Comment by waynebrantley** [comment]
2.1.1 is on npm
https://www.npmjs.com/package/react-select
@isitrita suggest you close the issue?

**Comment by CWSites** [comment]
npm is updated however for some reason when I run `npm install react-select` it doesn't install the latest version, this is the first time I have installed this project and it installed the older version

`"react-select": "^1.2.1"`

**Comment by gwyneplaine** [comment]
As above @isitrita thanks for the issue, as above 2.1.1 is released and many more bugfixes are on the way. 

@7c78 as always any help with triaging issues is greatly appreciated, we're doing our best on this end, but there aren't many of us and we do have other responsibilities too, appreciate the patience
