### ISSUE TITLE
Feature request: Allow passing props to custom components

### ISSUE THREAD

**Issue by mikkelwf** [JedWatson/react-select#3081]
My usecase is as such:

I want to add a button/content below the `MenuList`. 
This is done by making a custom menu: 
```
const Menu = ({actionRenderer, ...props}) => {
  return components.Menu && (
    <Fragment>
      <components.Menu {...props}>
        {props.children}
      </components.Menu>
      {actionRenderer && actionRenderer()}
    </Fragment>
  )
}
```

But as far as i've read in the documentation, it's impossible to pass your own props through the `Select` to you own components..?

May a whitelist solution like this could work..?
```
<Select
   ...
   actionRenderer={()=> ...}
   passProps={['actionRenderer']}
```

**Comment by TotallWAR** [comment]
I have the same problem.

**Comment by TotallWAR** [comment]
@mikkelwf i have found solution. You can pass your custom props to Select. And then you can take it in your custom component from `props.selectProps.yourCustomProp`

**Comment by maxmarchuk** [comment]
@TotallWAR This works for most components. However, not all components have access to `selectProps`. e.g. `Input` doesn't receive them

**Comment by mikkelwf** [comment]
`selectProps` is working fine.. So i'm closing this..

**Comment by maxmarchuk** [comment]
@mikkelwf The original issue was resolved, but I'm still curious why the `Input` component doesn't receive `selectProps`. Should I create a new issue?

**Comment by Vnam92** [comment]
@maxmarchuk i have the same problem, please open new issue)
