### ISSUE TITLE
Feature request: Allow closing the menu from custom components

### ISSUE THREAD

**Issue by mikkelwf** [JedWatson/react-select#3082]
As far as I can see, there is no way to trigger a blur / closing of the menu from custom components. 

The only API is the `setValue` and `clearValue`.

I'm trying to add a button to the `Menu` after the `MenuList`, and being able to trigger a blur when clicking the button would be nice.

**Comment by rebirthtobi** [comment]
Needed this also and also is there a way to stop the closing of the options dropdown even when an option is clicked?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
