### ISSUE TITLE
AsyncCreatable search functionality is broken

### ISSUE THREAD

**Issue by Redmega** [JedWatson/react-select#3084]
[![Edit react-select async search issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5zj032j04k?view=preview)

When searching through an `AsyncCreatable`, whether or not `isSearchable` is passed, the options list does not filter based on the `inputValue` provided by the user.

I couldn't find an issue quite demonstrating this, or describing the situation exactly, so therefore I've opened a new issue.

Is this something that I can look into and try to fix (If so, I would appreciate a nudge in the right direction as far as where in the file you think the problem might lie), or is it a case of me not using the right combination of props?

**Comment by mohsinhere** [comment]
I have the same issue with v1. The demo also doesn't search  when the option creatable is enabled.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
