### ISSUE TITLE
input field is not getting updated after passing value object 

### ISSUE THREAD

**Issue by bharamgundea77** [JedWatson/react-select#3085]
After passing array of values to the component input field values are not getting updated. 
- I am passing a whole object as { label: string, value: string }
- Props for the component is getting updated but state of component in not screenshot attached 

![image](https://user-images.githubusercontent.com/34537820/46271895-4637c500-c56c-11e8-8370-383dda068fec.png)

**Comment by Sawan1994** [comment]
Hi @bharamgundea77 , Could you plz share snippet of your code?

**Comment by gwyneplaine** [comment]
@bharamgundea77 if this is still an issue please open an issue with a codesandbox reproduction of your problem.
