### ISSUE TITLE
List not easily scrollable on older Android devices

### ISSUE THREAD

**Issue by matthew-socialcore** [JedWatson/react-select#3088]
We are building against react-select 2.0.0

When we create `<Select/>s` with a large number of  options, on older versions of Android the scroll behaviour seems to become unreliable.

See attached video:
[WhatsApp Video 2018-09-30 at 2.16.01 PM.mp4.zip](https://github.com/JedWatson/react-select/files/2434373/WhatsApp.Video.2018-09-30.at.2.16.01.PM.mp4.zip)

Steps to repro:
- Create `<Select>` with large list of options such that the list can be scrolled.
- Render this `<Select>` on a page that scrolls.
- Load page on mobile Android (Samsung S7).
- Attempt to scroll through options within dropdown.

Expected behaviour:
- List should scroll easily

Actual behaviour:
- List does not scroll 100% of the time.
- 'Pushing' before scrolling will work, but a 'hasty' or 'light' scroll will scroll the entire screen.

It seems like the touch events are not being captured in priority by the widget, and instead go to the frame.
I'm not sure what react-select can do about this, because the event will be dispatched by the mobile browser.

However, the behaviour is bad enough to be considered breaking, as such we are removing react-select from our project. I found it strange there was no mention of this on github, so filing this issue in case 
a) we're doing something wrong/there's something we can do to counteract
or
b) it really is an issue - in which case the package seems completely broken for use-cases with scrolling lists on mobile.

**Comment by matthew-socialcore** [comment]
@gwyneplaine mentioning you to try to get some traction, looks like you're a maintainer.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
