### ISSUE TITLE
onChange for input field (when typing...)

### ISSUE THREAD

**Issue by ctpayc** [JedWatson/react-select#309]
Hi, any callback or method for catch "onChange" for input value when typing? In my case i need to load options (with asyncOptions) every time when input change. For example, we have 5 000 000 users, and i need select somebody with name "Martin"... i want to call to backend for get options when input change...
Thanks

**Comment by benrlodge** [comment]
+1. @ctpayc, right now as a workaround I'm wrapping the select component with a wrapper component with an onKeyUp event that is triggered with any keyup on the child select component. I'm not using it for asynchOptions, but I figure you can do something like this:

```javascript
class SelectContainer extends React.Component {
  render(){
    return (<div onKeyUp={this.props.inputChange}>{this.props.children}</div>)
  }
}

class SidebarFilter extends React.Component {

  constructor(props){
    super(props);
    this.inputChange = this.inputChange.bind(this);
  }

  inputChange(){
    this.getOptions( () => {
      this.render()
    })
    // ...add some callback this.render()
  }

  getOptions(cb){
    // .. asynch operation
    if(cb){cb();}
  }

  render() {
    return (
      <SelectContainer inputChange={this.inputChange}>
        <Select
          name="repolist"
          value="Filter Modules..."
          asyncOptions={getOptions}
        />
      </SelectContainer>
    );
  }
}
```

**Comment by ctpayc** [comment]
Thank you, @benrlodge !!! It is very helpful, but i have some problems with use asyncOptions... in Usage react-select said "The function takes two arguments String input, Function callback and will be called when the input text is changed." - but it called only 1 time when you start typing (from first symbol...), maybe i wrong with it... But i found good solution for me, think this react way... i use state for options value. What you think about it?
```javascript

class SelectContainer extends React.Component {
  render(){
    return (<div onKeyUp={this.props.inputChange}>{this.props.children}</div>)
  }
}

class SidebarFilter extends React.Component {

  constructor(props){
    super(props);
    this.state = {
      options: MyStore.getOptions(),
      errors: []
    }
    this.inputChange = this.inputChange.bind(this);
    this._onChange = this._onChange.bind(this);
  }

  componentDidMount() {
    MyActions.loadOptions();
    MyStore.addChangeListener(this._onChange);
  }

  componentWillUnmount() {
    MyStore.removeChangeListener(this._onChange);
  }

  _onChange(){
    this.setState({options: MyStore.getOptions()});
  }

  inputChange(){
    var inp = this.refs.inputvalue.state.inputValue;
    MyActions.searchMyOptions(inp);
  }

  render() {
    return (
      <SelectContainer inputChange={this.inputChange}>
        <Select
          ref="inputvalue"
          name="repolist"
          value="Filter Modules..."
          options={this.state.options} />
      </SelectContainer>
    );
  }
}
```

**Comment by bruderstein** [comment]
This should work now, with asyncOptions. There are specific tests that check that asyncOptions is called on every input change.  Make sure you're not returning `complete: true` as part of your response, otherwise `react-select` will assume it can simply filter the existing results.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
