### ISSUE TITLE
No styles

### ISSUE THREAD

**Issue by Mujaddadi** [JedWatson/react-select#3092]
After installing the package, I linked the package into my component but didn't get any styles.  I had to explicitly import the styles as 

`import 'react-select/dist/react-select.css';` 

According to the doc this should not be necessary. Any idea why it's behaving like that?

**Comment by jschill** [comment]
If you installed 1.x, you need to import the css.

**Comment by Mujaddadi** [comment]
I just did npm install without any specific version. So I think it should be version 2 but I will confirm it anyway.

**Comment by danmolitor** [comment]
I'm having the same issue. Initial ```npm install react-select --save``` gave me version ^2.1.0, I also tried version 2.0.0. I'm not seeing any of the styles when I look in the chrome inspector.

**Comment by danmolitor** [comment]
I believe my issue is actually linked to using a shadow-dom. Is there a way to import the stylesheets through a shadow-dom?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by OlaoluwaM** [comment]
Hi! My team and I are looking to upgrade the version of `react-select` we use, but need the styles from the `dist/react-select.css` that seems to no longer be available in the package. Is there an upgrade path in this case or a workaround at least?
