### ISSUE TITLE
Tag react-select with react topic tag so it can be found in explore

### ISSUE THREAD

**Issue by Yahkob** [JedWatson/react-select#3093]
Was just looking through react trending repositories in Github Explore but didn't see react-select since there is no 'react' topic associated with this repo. Pretty sure it would be on the first page of highest star react repos
![screen shot 2018-10-04 at 3 59 19 pm](https://user-images.githubusercontent.com/5547203/46507671-8e661a00-c7ee-11e8-9c59-b827c41d0a2e.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
