### ISSUE TITLE
Opening and closing animation

### ISSUE THREAD

**Issue by gabrielPacio** [JedWatson/react-select#3098]
@JedWatson 

Hi! I'm planning to fork and add a feature for open/close animation/transition. Hopefully, I can contribute back with my solution to the project.

That's why, before working on it, I'd like to ask you and the community:

There are three main ways to do that. By allowing the components to receive a callback function for actions as open and close. By getting events _before_ the open and close. By having specific classes for states of after/before closing.

Each have advantages and disadvantages. Which one of those approaches would you start with?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
