### ISSUE TITLE
Label props not working

### ISSUE THREAD

**Issue by vieiramanoel** [JedWatson/react-select#3099]
I'm trying to change default 'Select...' string at react-select field, tried all props somehow related to _label_ cited on docs, none of them works.
e.g:
```javascript
<Select
  isMulti
  value={selectedOption}
  onChange={this.handleSelection}
  options={options}
  label="Main Person"
/>
```

Still got 
![image](https://user-images.githubusercontent.com/12820045/46621589-39801780-cafe-11e8-9757-226a48867ff5.png)

instead of "Main Person" on select component

**Comment by sushant24** [comment]
Did you try the **placeholder** prop as mentioned [here](https://react-select.com/props) ?

`
<Select
  isMulti
  value={selectedOption}
  onChange={this.handleSelection}
  options={options}
  placeholder="Main Person"
/>
`

Sample sandbox - https://codesandbox.io/s/5ymrxx8ol

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
