### ISSUE TITLE
Working with multiple Select menus

### ISSUE THREAD

**Issue by d4ncer** [JedWatson/react-select#310]
I'm working on a pseudo dashboard and the page I'm working on currently has a list of items each with its own dropdown menu from which a user can select some options. I'm attempting to set up a way for the Select menu onChange to fire an event with which I can update the related store accordingly, but the current onChange only gives me the update value/values of the Select menu, and not any reference to it (via name/id/key/ref) for me to correctly update the right item in the store. 

Am I doing something wrong? 

P.S. - I did make a minor edit on my local copy of the library to include the name (this.props.name) in the onChange callback, but I wasn't sure if this was the right way to go about it. 

Any help would be appreciated!

**Comment by d4ncer** [comment]
Never mind, figured it out using a wrapper.

**Comment by andreamazz** [comment]
I think this should be reopened. The change event should provide a reference to the target. Currently there is no easy way to figure out which Select performed the change.

**Comment by d4ncer** [comment]
You can wrap the Select to be used with an identifier on props (I use ```name```)

```javascript
...
handleChange: function() {
  var args = Array.prototype.slice.call(arguments);
  args.push(this.props.name); // this.props.name can be anything you want to use to identify the <Select />
  this.props.handleSelectChange.apply(this, args); // Whatever your change handler is
},

render: function() {
  var props = this.props;
  return (
    <Select
      {...props}
      onChange={this.handleChange}
      />
  );
}
...
```
