### ISSUE TITLE
How can I return className in version 2.0?

### ISSUE THREAD

**Issue by anorudes** [JedWatson/react-select#3101]
Hi, thanks for the great component! :)

I see that in the new version, the styles now need to be inline, because all classes are made through css modules.
Can I return the old classes for Select-control, Select-input and others?

**Comment by anorudes** [comment]
Ok, i found ```classNamePrefix``` in props :)

I think that it is necessary to describe in readme.md that it's need for additional classNames inner elemets. 
It seemed to me that without prefixes default classes should be.

**Comment by dtonys** [comment]
Someone might want to update the upgrade guide

https://react-select.com/upgrade-guide

```
Using classNames
If you provide the className prop to react-select, all inner elements will be given a className based on the one you have provided.
```
