### ISSUE TITLE
How can I change the z-index of the overlay?

### ISSUE THREAD

**Issue by abhisheksoni27** [JedWatson/react-select#3102]
I've a few fields below the Select control and the overlay's contents (the div that appears after you click select) overlaps the other fields present below. Shouldn't it have a high z-index value?

How can I set that?

**Comment by cutterbl** [comment]
I'm doing some styling work myself right now, and see that the default styles for the Menu component are showing a _z-index_ of '1'. You can override this by passing in a _styles_ property to your component

`styles={{menu: (styles) => Object.assign(styles, {zIndex: 1000})}}`

**Comment by gwyneplaine** [comment]
@abhisheksoni27 the above is the correct way to go about doing this, thanks @cutterbl 
-closed-

**Comment by derekcannon** [comment]
And if you're using a portal for your menu, you can use `menuPortal` for the `zIndex` styling override.
https://github.com/JedWatson/react-select/issues/1085#issuecomment-475404898
