### ISSUE TITLE
React select is throwing an error

### ISSUE THREAD

**Issue by Chethannp** [JedWatson/react-select#3105]
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

react-dom.development.js:14550 The above error occurred in the <AutosizeInput> component:
    in AutosizeInput (created by Select)
    in div (created by Select)
    in div (created by Select)
    in div (created by Select)
    in Select (created by City)
    in City (created by Location)
    in div (created by layout__Div)
    in layout__Div (created by Location)
    in div (created by layout__Div)
    in layout__Div (created by Location)
    in div (created by layout__Div)
    in layout__Div (created by Location)
    in span (created by Location)
    in Location (created by Header)
    in div (created by layout__Div)
    in layout__Div (created by Header)
    in div (created by layout__Div)
    in layout__Div (created by Header)
    in div (created by generic__Container)
    in generic__Container (created by Header)
    in div (created by Header)
    in Header (created by PD)
    in div (created by PD)
    in PD (created by UniversalComponent)
    in UniversalComponent (created by Route)
    in Route (created by Routes)
    in Switch (created by Routes)
    in ScrollToTopCore (created by Route)
    in Route (created by withRouter(ScrollToTopCore))
    in withRouter(ScrollToTopCore) (created by Routes)
    in Routes (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in ThemeProvider (created by App)
    in Provider (created by App)
    in App
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.

![react-select](https://user-images.githubusercontent.com/7566931/46672709-c5289f80-cbf5-11e8-8d75-0b75b0ebe364.png)

**Comment by Chethannp** [comment]
But this works fine on create-react-app!

**Comment by gwyneplaine** [comment]
@Chethannp please provide us with a [codesandbox](https://codesandbox.io/s/new) of your issue. 
We can not replicate or triage this with just the information you've provided.

**Comment by CWSites** [comment]
@JedWatson, recommend closing since original reporter hasn't updated.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
