### ISSUE TITLE
When using multi select , the drop down shows No-Options after selecting a value

### ISSUE THREAD

**Issue by abhagupta** [JedWatson/react-select#3106]
In Multi-Select version, when a value is selected, nothing shows in the drop down. I see `No Options`.   When no value is selected, I see some options.
My code is straight from the docs:
```import React from 'react';

import Select from 'react-select';
import { colourOptions } from './data';

class Search extends React.Component {
   
    render(){
        return (
            <Select
                defaultValue={[colourOptions[2], colourOptions[3]]}
                isMulti
                name="colors"
                options={colourOptions}
                className="basic-multi-select"
                classNamePrefix="select"
            />
        );
        
    }
}

export default Search
 
```

**Comment by juFelipe** [comment]
did you found a way to fix this?

**Comment by xnart** [comment]
#2864 seems like same issue.

**Comment by xnart** [comment]
Check if your _colourOptions_ similar as this :

```
export const colourOptions = [
  { value: 'ocean', label: 'Ocean },
  { value: 'blue', label: 'Blue' }
];
```

An option must have **value** key.

**Comment by williamluke4** [comment]
@xnart Is correct either ensure that all options have a **value** key or use the ```getOptionValue``` prop

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
