### ISSUE TITLE
Source links are broken on example website

### ISSUE THREAD

**Issue by eric79** [JedWatson/react-select#3116]
Try clicking the Source links here:

https://jedwatson.github.io/react-select/

It looks like the repository structure has changed since that page was made.

I sure would love to see the source for the github users example.  😄

**Comment by cutterbl** [comment]
You need the [new site](https://react-select.com)

**Comment by eric79** [comment]
Ah, okay, thanks.  Maybe the old one should just be taken down, then?

**Comment by gwyneplaine** [comment]
thanks for the response @cutterbl and thanks for lodging this @eric79, closing this issue as it's been sufficiently resolved.
