### ISSUE TITLE
onClick ability in custom indicator

### ISSUE THREAD

**Issue by tpakhoa1996** [JedWatson/react-select#3117]
So Im using react select with a custom indicator which is an edit indicator when an option is selected. My method is creating a custom indicator container, adding a button into it and handling onClick on that button. But somehow when I click, it just opens and closes the selection menu. It doesnt trigger my custom button. When I use jQuery to simulate the the click event on the element, it works just fine. Thus, I think react-select somehow stop onClick event to be triggered on any other custom component.

**Comment by burzumumbra** [comment]
@tpakhoa1996 I'm having the same Issue, just testing on the example for custom clear indicator, and nothing.
https://codesandbox.io/s/1o2ko7n4qq

**Comment by tpakhoa1996** [comment]
> @tpakhoa1996 I'm having the same Issue, just testing on the example for custom clear indicator, and nothing.
> https://codesandbox.io/s/1o2ko7n4qq

This is not a clean solution but because my company need it to be done in few hours. My solution was creating a custom clear indicator and somehow the onClick event is captured in that component.

**Comment by burzumumbra** [comment]
@tpakhoa1996 could you share a code snippet? For some reason my custom clear indicator component do not trigger onClick.

**Comment by juanecabellob** [comment]
@burzumumbra that worked this is my custom indicator: 
```
renderClearIndicator = (props) => {
    const { classes } = this.props;
    const clickHandler = () => this.handleClear(props);

    return (
      <IconButton
        classes={{
          root: classes.clearButton,
        }}
        onMouseUp={clickHandler}>
        <ClearIcon />
      </IconButton>
    );
  }
```

This is my handler function:
```
handleClear = (props) => {
    const { dispatch } = this.props;
     // update `redux-form`'s field
    dispatch(
      change(
        'form',
        'fieldName',
        '',
      )
    );

    props.setValue(null, 'clear');
  }
```

**Comment by 32teeths** [comment]
Facing the same issue , Need a dropdown indicator to have custom onClick listener when the menuIsOpen . Any help is appreciated .

**Comment by PhilippePerez** [comment]
I did overcome the issue by canceling the mouse down event when done in the context of my
custom buttons. For this i am using a <div > to intercept the event.
A bit of details below which are part of a large code i can't publish but you'll get the idea.
I am also relying on the document 'component' mechanisms provided to override the '**IndicatorsContainer**'

static icwaStyles = makeStyles((theme: Theme) => createStyles({
        root: {
            display: 'flex',
            alignItems: 'center',
        },
    }));

[...]    

static IndicatorsContainerWithActions = (props: any) => {
        const classes = UxAutocompleteSelect.icwaStyles();
        return <div className={classes.root}>
            /*
            Renders default indicators
            */
            <components.IndicatorsContainer {...props} />
            /*
            Custom indicators on the right hand side
            The trick
            */
            **<div
                onMouseDown={(e: React.MouseEvent<HTMLElement>) => {
                    e.stopPropagation();
                    e.preventDefault();
                }}>**
                {props.actions && props.actions.map((action: UxAction) => {
                    const Icon = getIconByName(action.id, true);
                    return <Tooltip key={action.id} title={action.caption} placement="bottom">
                        <IconButton
                            id={action.id}
                            onClick={() => {
                                window.alert('clicked!');
                            }}
                            {...action.renderProps}
                        >
                            <Icon/>
                        </IconButton>
                    </Tooltip>;
                })
                }
            </div>
        </div>;
    };

**Comment by burzumumbra** [comment]
> I did overcome the issue by canceling the mouse down event when done in the context of my
> custom buttons. For this i am using a
> 
> to intercept the event.
> A bit of details below which are part of a large code i can't publish but you'll get the idea.
> I am also relying on the document 'component' mechanisms provided to override the '**IndicatorsContainer**'
> ![shot](https://user-images.githubusercontent.com/25633027/66566186-97f23280-eb64-11e9-97f2-33481fa2e94b.png)

Thanks, @PhilippePerez this is the solution. Sadly a little late for me, hope that for others just got in time. 

I did update the code example for anyone searching for a quick check on this solution.
https://codesandbox.io/s/react-codesandboxer-example-fmxdi

And a code snippet for the lazy ones.

`const ClearIndicator = props => {
  const {
    children = <CustomClearText />,
    getStyles,
    innerProps: { ref, ...restInnerProps }
  } = props;
  return (
    <div
      {...restInnerProps}
      ref={ref}
      style={getStyles("clearIndicator", props)}
    >
      <div
        style={{ padding: "0px 5px" }}
        onMouseDown={e => {
          e.stopPropagation();
          e.preventDefault();
        }}
      >
        <button
          onClick={() => {
            alert("onClick Executed, thanks to @PhilippePerez");
          }}
        >
          Close new
        </button>
      </div>
    </div>
  );
};`

**Comment by burzumumbra** [comment]
@tpakhoa1996 I see @PhilippePerez contribution as a "Fix" for this issue, so @JedWatson can close it.

**Comment by aaronfordnet** [comment]
Just a heads up, the workaround posted by PhilippePerez doesn't seem to work on touchscreen devices
