### ISSUE TITLE
Can't use react-select Library

### ISSUE THREAD

**Issue by GeekeuzZ** [JedWatson/react-select#3119]
Importing react-select with : npm install react-select --save 
But I can't import the Select component from the react-select (I have already verify in package.json file and it's installed ). An error is shown : "Super expression must either be null or a function, not undefined in react-select".

**Comment by RamYadlapalli** [comment]
Mostly you might be doing something wrong while importing. You can share your exact code. Basic usage of react-select is shown below 


import React, { Component } from 'react'
import Select from 'react-select'

const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
]

const MyComponent = () => (
  <Select options={options} />
)

**Comment by GeekeuzZ** [comment]
`import React from 'react';
import Select from 'react-select';
export default class Sanction extends React.Component {
  state = {
    selectedOption: null,
  }
  handleChange = (selectedOption) => {
    this.setState({ selectedOption });
    console.log(`Option selected:`, selectedOption);
  }
  render() {
    const scaryAnimals = [
      { label: "Alligators", value: 1 },
      { label: "Crocodiles", value: 2 },
      { label: "Sharks", value: 3 },
      { label: "Small crocodiles", value: 4 },
      { label: "Smallest crocodiles", value: 5 },
      { label: "Snakes", value: 6 },
    ];

    const { selectedOption } = this.state;

    return (
      <div>
        <Select
          value={selectedOption}
          onChange={this.handleChange}
          options={scaryAnimals}
        />
      </div>
    );
  }
}
`

**Comment by GeekeuzZ** [comment]
import React from 'react';
import Select from 'react-select';
export default class Sanction extends React.Component {
  state = {
    selectedOption: null,
  }
  handleChange = (selectedOption) => {
    this.setState({ selectedOption });
    console.log(`Option selected:`, selectedOption);
  }
  render() {
    const scaryAnimals = [
      { label: "Alligators", value: 1 },
      { label: "Crocodiles", value: 2 },
      { label: "Sharks", value: 3 },
      { label: "Small crocodiles", value: 4 },
      { label: "Smallest crocodiles", value: 5 },
      { label: "Snakes", value: 6 },
    ];

    const { selectedOption } = this.state;

    return (
      <div>
        <Select
          value={selectedOption}
          onChange={this.handleChange}
          options={scaryAnimals}
        />
      </div>
    );
  }
}

**Comment by RamYadlapalli** [comment]
Mostly not a react-select issue, i am able to get your code working here without any issue
https://codesandbox.io/s/x2zzv7m004

**Comment by mishra1947** [comment]
Same error is comming. 
react-select.esm.js:71 Uncaught TypeError: Super expression must either be null or a function, not undefined
    at inherits (react-select.esm.js:71)
    at react-select.esm.js:553
    at Object.<anonymous> (react-select.esm.js:623)
    at __webpack_require__ (bootstrap f52a95b2469ee8924c4f:19)
    at Object.defineProperty.value (select.js:3)
    at __webpack_require__ (bootstrap f52a95b2469ee8924c4f:19)
    at Object.defineProperty.value (project_basicdetails.js:6)
    at __webpack_require__ (bootstrap f52a95b2469ee8924c4f:19)
    at Object.defineProperty.value (project_new.js:8)
    at __webpack_require__ (bootstrap f52a95b2469ee8924c4f:19)

**Comment by gwyneplaine** [comment]
Closing this, as it appears to be a build configuration issue and not an issue with react-select specifically.

**Comment by mishra1947** [comment]
This issue is comming with v2 otherwise it is working fine with v1.
