### ISSUE TITLE
onBlur called on Firefox not on Chrome/Chromium

### ISSUE THREAD

**Issue by Thebarda** [JedWatson/react-select#3122]
Hello there !

I am here to report a behavior bug about onBlur function
On Firefox, after select a value, Select component seems to loose focus thus call onBlur.
It's not the case on Chrome and Chromium (I don't know the behavior on Safari and ie...)

Here is a code sandbox to reproduce this bug : [https://codesandbox.io/s/3ykyjk8rl5](https://codesandbox.io/s/3ykyjk8rl5)
Just choose a value and look at the code sandbox console.

I don't know if it's a behavior bug about Chrome or Firefox

**Comment by maximeroma** [comment]
I have a similar issue. On my desktop when i select an option event onChange is called. On another events onChange and onBlur are called. Both on Chrome

**Comment by leojh** [comment]
we're seeing something similar, any tips you can give?

**Comment by Thebarda** [comment]
@leojh It seems fixed since I created the issue. My codesandbox used `react-select: 2.0.0` and I upgraded it to `react-select: 2.4.2` and I no longer have this issue
