### ISSUE TITLE
[V2] Input commonProps / selectProps

### ISSUE THREAD

**Issue by samueldepooter** [JedWatson/react-select#3125]
Hi!

I'm currently developing a custom `Creatable`. With it I'm trying to maintain the placeholder on the input when I have options selected.

- Current behaviour: placeholder is **not** shown when options are selected
- Wanted behaviour: placeholder is persisted

I tried doing it with a custom `Input` element but noticed that the element is not receiving `selectProps` (from `commonProps`). [This line is where Input is created & as you can see it's not passed.](https://github.com/JedWatson/react-select/blob/18219f5271705ef150ad16177db43f0c44f0413d/src/Select.js#L1317)

I was wondering what's the reasoning behind it? I could make a PR to fix this.

Mentioned before in #2680

**Comment by gwyneplaine** [comment]
thanks @samueldepooter , this issue is now resolved in this PR https://github.com/JedWatson/react-select/pull/3303 released as part of v2.2.0
