### ISSUE TITLE
Improve support for CSS Custom Properties in theme config

### ISSUE THREAD

**Issue by woutervanvliet** [JedWatson/react-select#3127]
### Thanks for using react-select!
... and thank you for making it.

# Are you making a feature request?
Our project relies heavily on CSS Custom Properties (custom variables), and I'm pleasantly surprised to see that I can just use them to use our brand colours in the select element. However, this doesn't work as well for spacing units - as they are calculated at javascript runtime.

If, however, all expressions that use spacing units would be replaced by css calculations the custom properties would function perfectly. A snippet like this:

```ts
export const groupCSS = ({ theme: { spacing } }: GroupProps) => ({
  paddingBottom: spacing.baseUnit * 2,
  paddingTop: spacing.baseUnit * 2,
});
```

Would become

```ts
const maybeAsPx = (value: number | string) {
  if (typeof value === 'string') {
    return value;
  }
  return `${value}px`;
}
export const groupCSS = ({ theme: { spacing } }: GroupProps) => ({
  paddingBottom: `calc(${maybeAsPx(spacing.baseUnit)} * 2)`,
  paddingTop: `calc(${maybeAsPx(spacing.baseUnit)} * 2)`,
});
```

Where `maybeAsPx` would of course be defined somewhere else, or maybe the entire theme config would be processed a single time by it. 

This improvement would also make life easier for those using relative units as any string value would be interpreted directly at the css level.

**Comment by woutervanvliet** [comment]
If this is something you're interested in, I might have some time to work out a PR myself.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
