### ISSUE TITLE
Feature: Async options functionality similar to Select2

### ISSUE THREAD

**Issue by saysmaster** [JedWatson/react-select#3130]
Trying to use react-select i find some limitations in the async aspect of it. I am comparing it to Select2's async functionality.

### Option availability
- **react-select**: You need to type at least one character to see any available options.
- **Select2**: Upon focusing in the search-input element, the dropdown opens and is populated with some data.

### Option count
- **react-select**: All options that match the text are coming form async loading. Doesn't work well with large datasets.
- **Select2**: Data are coming in a paged way. The function that retrieves the data from the server is passed many arguments like `term` (the text the user has typed so far), `pageSize` (the maximum items the server should send back with the request), `page` (the page requested by the component) etc. Works really well with large datasets. The user can scroll down the available options while the component is fetching them in an infinite-scroll kind of way.

**Drawback of Select2**: It is not a react component and any select2 react wrappers out there are buggy.

It would be great if react-select adopts the kind of functionality and user experience found in Select2 concerning async options.

**Comment by gwyneplaine** [comment]
@saysmaster, thanks for opening this issue. 
the `defaultOption` on the AsyncSelect component allows you to set an initial static option set on mount as an array of options / or (if set explicitly to true) to call the loadOption function on mount. 

Both of these cases are designed to facilitate for the option availability issue you described above. 
As for Option count, we're currently looking into the best way to go about supporting either pagination or easier virtualisation within react-select v2 please stay tuned.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
