### ISSUE TITLE
Sidebar broke in documentation pages

### ISSUE THREAD

**Issue by elboletaire** [JedWatson/react-select#3134]
Sidebar elements (.css-so7v2t as seen in the inspector right now) need to have a `white-space` property set to `inherit`, `pre-line` or `pre-wrap` in order to make the text jump to the next line.

![imatge](https://user-images.githubusercontent.com/153305/47366549-39773e80-d6de-11e8-8a0c-461249b154ed.png)
(see the sidebar, the `Storing strings with non multi select` link)

Removing the `white-space: nowrap` or setting it as said above fixes the issue:

![imatge](https://user-images.githubusercontent.com/153305/47366611-5a3f9400-d6de-11e8-8b77-90b66ad0e9d5.png)

**Comment by gwyneplaine** [comment]
thanks for this @elboletaire, I've made minor edits to this docs page, which fix this issue along with some minor tone of voice updates so will be using those instead of this PR 
closed
