### ISSUE TITLE
Documentation: Are the style keys documented anywhere? 

### ISSUE THREAD

**Issue by renschler** [JedWatson/react-select#3135]
There's a list of style keys here:
https://react-select.com/styles
<img width="546" alt="screen shot 2018-10-23 at 6 15 41 pm" src="https://user-images.githubusercontent.com/3973468/47396325-df7f7480-d6ef-11e8-8f1c-4bdb94878f02.png">

and here there's a list of style modifier methods:
https://react-select.com/props#select-props
<img width="468" alt="screen shot 2018-10-23 at 6 16 30 pm" src="https://user-images.githubusercontent.com/3973468/47396353-fb831600-d6ef-11e8-885d-c4bbca2b9958.png">

But I don't see anywhere where it actually explains what those names stand for or control. Is this documentation somewhere? I feel like a picture with things labeled would be incredibly helpful.

**Comment by degr** [comment]
I found how this work:
<Select className="react-select" classNamePrefix="react-select" />
then look into DOM, you will see elements with classes:

react-select__control
react-select__placeholder

**Comment by renschler** [comment]
thanks I ended up doing that @degr.

Later, I also found that the section on [replaceable components](https://react-select.com/components#replaceable-components) gives a little overview on what each thing is, I didn't find it obvious to look there for it though.

**Comment by nbrustein** [comment]
It would have really helped me if there had been a link to that replaceable components page near the list of style keys at https://react-select.com/styles#style-object

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
