### ISSUE TITLE
Select-item span value html text times renders as incorrect unicode

### ISSUE THREAD

**Issue by Siliconrob** [JedWatson/react-select#314]
Within the lib\Value.js code that creates the 'Select-item' element value '×' is coded as such, but this inconsistent in how web browsers render from IIS.  Currently rendering as such 'Ã—'.  Needs to push the html text code &times; instead to be consistent across all web browsers.

**Comment by garethdown44** [comment]
This can be fixed by adding:

<meta charset="UTF-8">

to the HTML.

**Comment by Siliconrob** [comment]
Did you test that in all browsers and rendering engines?  Particularly IE versions from IIS because that doesn't work consistently, whereas render from the string character code will work in every browser consistently.  Is there a reason it is better to not be explicit and consistent when rendering an 'x' than just getting the unicode string character and instructing any HTML renderer to do this.

**Comment by JedWatson** [comment]
We're actually now using `&times;` for this, which AFAIK works correctly everywhere... I think this can be closed?

**Comment by Siliconrob** [comment]
Yes &times; is consistent across browsers

**Comment by garethdown44** [comment]
@Siliconrob - Chrome 48, IE 11, Firefox 41.

Please note that it *only* works correctly with IIS if you set the charset. Might be worth mentioning in the docs.

**Comment by Siliconrob** [comment]
I did this.  I'm trying to be patient, but what kind of garbage is this shit you keep talking about.  Do you peruse github to make arguments for boredom?

Being nitpicky about something merged that is explicit and correct without need for extra configuration is preferable to some other render edge case.  Regardless of that the owner has stated he is using the html times character now, which is correct against all renderers without use of UTF8 or not configuration and what I did internally first the only thing is that it can look slightly different when rendered than the string charge from code character.  I did not want to make any change to view perception when I originally did this so I chose the JavaScript char option instead of times html character change, even though I like the times html character change as the best option and I full support changing to use that instead in the latest versions.

**Comment by JedWatson** [comment]
Just to clarify, @Siliconrob actually said (the html times character) is consistent across browsers, confirming that it works everywhere and this can be closed. HTML escape codes mean there's no need for configuration.

Unfortunately because it wasn't escaped in a code comment with backticks (`&times;`), GitHub rendered it as the &times; character which may have led to confusion. I've edited the comment to escape the value.

**Comment by garethdown44** [comment]
@Siliconrob - I'm not sure why you're getting upset, my suggestion was to @JedWatson to mention something in the docs, and to help anyone who views this issue in the future who comes up against the same problem I did today.

When running under IIS:

![image](https://cloud.githubusercontent.com/assets/145924/10912365/0e2a60da-8241-11e5-959a-02aea1c03273.png)

![image](https://cloud.githubusercontent.com/assets/145924/10912373/17583682-8241-11e5-9e30-5c7aaab4d371.png)

After you add this:

![image](https://cloud.githubusercontent.com/assets/145924/10912390/2eb55e18-8241-11e5-89eb-aaf6bfe4d244.png)

![image](https://cloud.githubusercontent.com/assets/145924/10912395/350c44c0-8241-11e5-96a9-c7f85eb4c67e.png)

![image](https://cloud.githubusercontent.com/assets/145924/10912402/3a1ca8d8-8241-11e5-9b76-717efc2174ab.png)

I'm sorry that you have become upset by what I posted earlier, it wasn't my intention. I was merely trying to help.

**Comment by JedWatson** [comment]
@garethdown44 that's odd... which version are you using? I don't remember off the top of my head which version we changed this, but if you can check the version and whether the source code includes `&times;` instead of &times; that would be great.

**Comment by garethdown44** [comment]
It's the latest from npm - 0.9.1.

The source code has `&times;` here, in lib\Select.js:

![image](https://cloud.githubusercontent.com/assets/145924/10914604/1f3e94b8-824b-11e5-9789-8a441cca3d78.png)

but in lib\Value.js

![image](https://cloud.githubusercontent.com/assets/145924/10914577/02963d70-824b-11e5-9da2-c174b4daa2bf.png)
