### ISSUE TITLE
Options are filtered by default when inputValue is set

### ISSUE THREAD

**Issue by aceofspades** [JedWatson/react-select#3141]
Forked the example, and only added the inputValue to "blue". When opening drop-down, the options are not present.

https://codesandbox.io/s/5xnx7k3rwp

**Comment by cutterbl** [comment]
One, change your `package.json` to load 2.1.1 (latest). Two, what is it you're trying to accomplish? When I add the `inputValue` prop to your select in the codesandbox the only value it displays is "Blue", but you can't select it. In my experience and testing, use of the `inputValue` prop just creates issues. So, what is it you're trying to accomplish?

**Comment by aceofspades** [comment]
@cutterbl Isn't `inputValue` used to reflect the currently selected value?

**Comment by cutterbl** [comment]
No, `inputValue` is actually an internal value used for filtering options. `value` is the value of the control, represented as an object that matches the previously selected option.

**Comment by cutterbl** [comment]
Take a look at this [adjustment to your sandbox](https://codesandbox.io/s/kxql67nz5r).

**Comment by gwyneplaine** [comment]
@aceofspades as above; inputValue is to specify the search term, the value prop is used to specify the selected option.  please see the [docs](https://react-select.com/home) for more information

**Comment by aceofspades** [comment]
@cutterbl @gwyneplaine Thanks, I really tried with the docs, it doesn't seem clear there that you need to provide the object from options and not the value like before. It's hard to even find the place that the value parameter is buried way down the API page. Got it working now though.
