### ISSUE TITLE
using react-select as select only without option for entries

### ISSUE THREAD

**Issue by Danny-weebo** [JedWatson/react-select#3147]
Hey, I'm trying to prevent the user from any type of entries inside the input, so `react-select` will be used as a simple <Select> html tag, I faced this issue while I was trying to search for solution

/issues/758

but its mainly about auto-complete .. I want to prevent the use of typing anything at all (when opening the select), just a selection. and idea how can it be done ?

thanks.

**Comment by Danny-weebo** [comment]
yeah I missed this option, thanks again!

**Comment by vikjsdev** [comment]
> @Danny-weebo For future reference, questions like this are best left for StackOverflow, and don't really fall into the repo bug tracker. That said, what you're looking for is the `isSearchable` prop. If you set this to `false`, then the user will use your select like a standard select, without the ability to type and filter in the Control.
> 
> `<Select {...otherProps} isSearchable={false} />`
> 
> The [API docs](https://react-select.com/props) are really helpful here. It's a lot of information (it's a powerful component), but worth reading through.

thank you!!!

**Comment by just-be-weird** [comment]
For me passing `isSearchable` didn't work, what worked was `searchable` . Here is the code snippet `<Select {...otherProps} isSearchable={false} searchable={false} />` .. thanks!

**Comment by premraval-pr** [comment]
> @Danny-weebo For future reference, questions like this are best left for StackOverflow, and don't really fall into the repo bug tracker. That said, what you're looking for is the `isSearchable` prop. If you set this to `false`, then the user will use your select like a standard select, without the ability to type and filter in the Control.
> 
> `<Select {...otherProps} isSearchable={false} />`
> 
> The [API docs](https://react-select.com/props) are really helpful here. It's a lot of information (it's a powerful component), but worth reading through.

Thank You, this was exactly what I needed 👍

**Comment by christinavarghese06** [comment]
> @Danny-weebo For future reference, questions like this are best left for StackOverflow, and don't really fall into the repo bug tracker. That said, what you're looking for is the `isSearchable` prop. If you set this to `false`, then the user will use your select like a standard select, without the ability to type and filter in the Control.
> 
> `<Select {...otherProps} isSearchable={false} />`
> 
> The [API docs](https://react-select.com/props) are really helpful here. It's a lot of information (it's a powerful component), but worth reading through.

Thank you so much , wasted hours to resolve this issue. This really helped.
