### ISSUE TITLE
Missing onHover styles with custom Option component

### ISSUE THREAD

**Issue by cutterbl** [JedWatson/react-select#3159]
When using a custom Option component, the onHover styling (background color) no longer applies. I want to say this was working in 2.1.0, as long as you were copying `innerRef` and `innerProps` to the custom Option, but appears to be missing from 2.1.1. [An example can be shown in this codesandbox](https://codesandbox.io/s/p5k5198kpm).
**[Side Note]**: I changed the versions in codesandbox, and tried 2.0.0 and 2.1.0, and neither of these applied the onHover styling either.

**Comment by hedikasmanto** [comment]
Hi,

I had same problem with your case, and I found solution on the option script : 

https://github.com/JedWatson/react-select/blob/master/src/components/Option.js

And I have update your given example : https://codesandbox.io/s/6zxnx9kmxz

Hope this solution will solve your problem

**Comment by tachang** [comment]
@hedikasmanto Thank you for this. Basically copying what the default component does gives you all the normal styles.

**Comment by Gajesh-LH** [comment]
I have implemented the same. It is working fine but I am facing an issue. More than one option is showing as selected.

Demo link: http://recordit.co/5Cz5MRzl49

**Comment by cutterbl** [comment]
@hedikasmanto Thanks for that. Should've dug in the source myself. Guess I got lazy this time ;)
