### ISSUE TITLE
What is the best practice for customizing the styles for react-select?

### ISSUE THREAD

**Issue by andrerpena** [JedWatson/react-select#316]
First, thank you for this lib. I'm really enjoying it.

React-select's style is quite consistent with Bootstrap. However I still need to fine tune it so it's 100%. As I'm kind of new to node.js I'm not sure if the way I'm about to go is the best. Here's how I'm thinking of doing it:

I create my own `select.less` file in my project, but then I import the `less` files from the `node_modules` folder. Something like this:

	@select-input-bg:                  #fff;
	@select-text-color:                #333;
	@select-input-border-color:        #ccc;
	@select-input-border-radius:       4px;
	@select-input-placeholder:         #aaa;
	@select-input-border-focus:        #08c; // blue

	@select-padding-vertical:          8px;
	@select-padding-horizontal:        10px;

	@select-arrow-color:               #999;
	@select-arrow-width:               5px;

	@select-menu-zindex:               1000;
	@select-menu-max-height:           200px;

	@select-option-color:              lighten(@select-text-color, 20%);
	@select-option-focused-color:      @select-text-color;
	@select-option-focused-bg:         #f2f9fc; // pale blue
	@select-option-disabled-color:     lighten(@select-text-color, 60%);

	@select-noresults-color:           lighten(@select-text-color, 40%);

	@select-clear-color:               #999;
	@select-clear-hover-color:         #c0392b; // red

	@select-item-border-radius:        2px;
	@select-item-gutter:               2px;
	@select-item-padding-vertical:     3px;
	@select-item-padding-horizontal:   5px;
	@select-item-font-size:            1em;
	@select-item-color:                #08c; // pale blue
	@select-item-bg:                   #f2f9fc;
	@select-item-border-color:         darken(@select-item-bg, 10%);
	@select-item-hover-color:          darken(@select-item-color, 5%); // pale blue
	@select-item-hover-bg:             darken(@select-item-bg, 5%);
	@select-item-disabled-color:       #888;
	@select-item-disabled-bg:          #f2f2f2;
	@select-item-disabled-border-color: darken(@select-item-disabled-bg, 10%);

	@import "node_modules/react-select/less/control.less";
	@import "node_modules/react-select/less/menu.less";
	@import "node_modules/react-select/less/mixins.less";
	@import "node_modules/react-select/less/multi.less";
	@import "node_modules/react-select/less/spinner.less";

You can see that the only difference from the original `select.less` file is that I'm importing from the `node_modules` directory.

I didn't try it yes, it's just the way I'm thinking of doing. The only gotcha I see is that, when I update my `npm` package, I may lose some variables that were introduced, becuase I'm cloning the `select.less` file.

Do you have a better idea? Thank you.

**Comment by dantman** [comment]
In LESS later variables are supposed to override earlier variables. So you should be able to just `@import` `select.less` and then override specific variables.

**Comment by andrerpena** [comment]
Thank you @dantman. I'm sorry for the late. Yes, it worked.

For me, `react-select` gets pretty consistent with Bootstrap just by doing this:

    @import '../../../node_modules/react-select/less/select';
    @select-input-height:  34px;
