### ISSUE TITLE
Close Menu when click outside not working on Highcharts 

### ISSUE THREAD

**Issue by vadimka123** [JedWatson/react-select#3164]
See video in archive 

[react-select-click-outside-bug.zip](https://github.com/JedWatson/react-select/files/2538044/react-select-click-outside-bug.zip)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
