### ISSUE TITLE
No such property as "styles"

### ISSUE THREAD

**Issue by roberthchapman** [JedWatson/react-select#3165]
Hi, when I try to restyle a Select using the latest version with your recommended technique on your styling page, I find that there is no such property as "styles" on Select so that <Select styles={customStyles}... generates an error.  How are you supposed to do this when it says there is  no such property as shown in your simple example?

Thanks,
Rob

**Comment by cutterbl** [comment]
For future reference, it is better to ask questions on StackOverflow, and use the "Issues" to post bugs and feature requests.

I have included a (very) simple example in this [codesandbox](https://codesandbox.io/s/y042010mkv).

**Comment by roberthchapman** [comment]
Thanks for the example but it didn't really address the issue I raised at all, which was that Select has no such property called "styles" and creates a Typescript error.  It has "style" of course but no "styles".  I have made sure to install the latest types file as well but how are you meant to get this working when there is no such property as "styles"?

**Comment by cutterbl** [comment]
So someone needs to update the TS type descriptor files? I (personally) don't write a lot of TypeScript, but [looking at the repository for these](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/lib/Select.d.ts), there is absolutely an entry for `styles` on line 194.

**Comment by cutterbl** [comment]
It may help to see your code...

**Comment by roberthchapman** [comment]
There's not really much to see beyond what I showed:
import Select from 'react-select'
<Select styles={customStyles}>
 is enough to generate the problem using the customStyles object from your /styles page on the react-select website, not because of the customStyles object of course but just because there is no such property as styles. I could show you the current code I am using but it doesn't address the fact styles doesn't exist...

<Select placeholder='Active' style={{height:40, flex:1, alignItems:'center', fontFamily:'"Roboto", "Helvetica", "Arial", sans-serif'}}
options={this.activeValues()} disabled={isProcessing} labelKey='label' valueKey='value'
onChange={((active: IActive) => this.onChangeActive(active))} clearable={false}
value={this.state.active.value} name={this.state.active.label}/>

I don't understand how if there is an entry for styles how VS Code still tells me there is no such thing?

**Comment by cutterbl** [comment]
I can't tell you either. Just a user who likes to help out, but I've never used react-select with TS. The property is definitely defined in the descriptor files, according to that repository. I couldn't tell you why VSCode isn't recognizing that.

**Comment by roberthchapman** [comment]
ok, thanks for trying to help.  It's an infuriating issue as it's something so basic that just doesn't work, but don't know if it's affecting other people at all

**Comment by kaityhallman** [comment]
@roberthchapman you're not the only one having this issue - i'm also having the same issue. seems like when i installed `@types/react-select` i have something quite different than what i expected in my node modules than what shows from the link posted above

a fix for this would be very nice.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
