### ISSUE TITLE
Cannot Clear selection using provided 'clear' Button

### ISSUE THREAD

**Issue by sscholle** [JedWatson/react-select#3167]
'react-select': version "2.0.0"

JSX:

```
          <FormSelect
            isClearable={this.state.cohort_report_cohort !== null}
            isSearchable={false}
            onChange={option =>
              this.updateValue('cohort_report_cohort', option.value)
            }
            defaultValue={this.state.cohort_report_cohort}
            options={this.props.cohort_options}
            placeholder="Select Cohort..."
          />
```

Example:

![clear-not-working](https://user-images.githubusercontent.com/2486065/47857404-35d86b80-ddf2-11e8-86eb-61cc8347035a.gif)

Any advice would be appreciated.

**Comment by cutterbl** [comment]
One, shouldn't your `isClearable` just be there? it won't show the 'x' if there's no value in the field. Second, what does your `updateValue` method look like? And `onChange` method signature also provides an `action` that you can key off of for specific types of changes.

`onChange={(option, {action}) => this.doSomething(option, action)}`

**Comment by Pessu** [comment]
I have the same problem. Cannot click on the x icon. Looks exactly the same as in the example above.

**Comment by noreek** [comment]
_option_ variable is NULL in case of clearing (in provided example inside onChange). So passing _option.value_ to updateValue method fails - check your console for error.

To fix it:
`
this.updateValue('cohort_report_cohort', option ? option.value : null);
`

**Comment by Rall3n** [comment]
@Pessu or @sscholle could you provide an example with [CodeSandbox](https://codesandbox.io/s/k5rvn9z3lv)? Having your exact code and a live example with the error might help solving it.

**Comment by alynnlp** [comment]
This is what my OnChange event has to look like. It needs to check for null options when the Cross Button is clicked. and return**

setQueryValue = (selectedOption: Page) => {
    const { onChange } = this.props;
    if (!selectedOption) {
      onChange({ name: '', value: '' });
      return;
    }

    const page = {
      name: selectedOption.name,
      value: selectedOption.value,
    };
    onChange(page);
  };

**Comment by sscholle** [comment]
> One, shouldn't your `isClearable` just be there? it won't show the 'x' if there's no value in the field. Second, what does your `updateValue` method look like? And `onChange` method signature also provides an `action` that you can key off of for specific types of changes.
> 
> `onChange={(option, {action}) => this.doSomething(option, action)}`

@cutterbl having had a deeper look at the docs, i do see the 'action' object second parameter as you show in your example: i think it was a matter of RTFM. so please guys look at the [API Docs](https://react-select.com/props) under `onChange` prop.

**Comment by gustavowebjs** [comment]
Try this
` onChange={data =>
                                            this.setState({
                                                state : data
                                                    ? data.value
                                                    : ""
                                            })
                                        }
                                        isClearable={state}`

**Comment by sagargupta2001** [comment]
Add this
`if (!event) return;`
to onChange handler.
