### ISSUE TITLE
Hitting Esc on an empty input throws `Uncaught TypeError: Cannot read property 'stopPropagation' of undefined`

### ISSUE THREAD

**Issue by stevehollaar** [JedWatson/react-select#317]
This is reproducible on the first example on the live demo: http://jedwatson.github.io/react-select/
![image](https://cloud.githubusercontent.com/assets/918252/8711472/04692810-2b07-11e5-8027-bcc9c033b122.png)

**Comment by bruderstein** [comment]
This is fixed in 7e51041e6 (included v0.5.6)

Note that a secondary bug is then introduced (meaning if "clearable=false", you can still press escape to clear the value).  This is then fixed in 240c8a0a, which is not included v0.5.6.

**Comment by bruderstein** [comment]
This has now been completed fixed and merged.
