### ISSUE TITLE
filteroption stringify method params should be clarified

### ISSUE THREAD

**Issue by waynebrantley** [JedWatson/react-select#3171]
https://codesandbox.io/s/6zkrl4p7wz

Open the drop down.  Type the letter 'a'.
You will see that even though there is only one item that starts with an 'a' two show up.
Add an 'l' to the search - you now are looking for 'al' - again two show up.
Finally make the search the word 'all' and it will only show the one item the matches.

Same issue - different scenario
Open the drop down.  Type the letter 't'.
You will see that even though there is only one item that starts with an 't' two show up. (Note it excludes the 'all' from above - correctly)

Open the drop down.  Type the letters 'no'.  It correctly filters.

**Comment by waynebrantley** [comment]
Well, I figured it out.
https://codesandbox.io/s/20zjxrl9qn

I needed filterOption

However, on filterOption the stringify method, I would expect object to have 'key' and 'value'.  Turns it out it has 'value' and 'label'.   Perhaps if that is correct - the documentation should indicate what is being passed in?

**Comment by cutterbl** [comment]
Actually there's a fairly decent example in the [Advanced documentation.](https://react-select.com/advanced#custom-filter-logic). It shows how to use the built-in `createFilter` with the `filterOptions`, which covers a lot of use cases out of the gate. There isn't a good example of a 'custom' filter currently, though I have a PR in.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
