### ISSUE TITLE
[V2] Toggle menu with CSS instead of removing it.

### ISSUE THREAD

**Issue by SFPink** [JedWatson/react-select#3174]
I have implemented React Select V2 with ease today (good job on a great plugin). 

Is there a way to have the select menu render and not remove itself on close but instead use CSS to toggle visibility? 

For a little more context I have added the React-Select to a dropdown menu, however on select of an option my menu closes as well. My menu uses this condition to determine if it should be closed "!this.menu.contains(event.target)" however when this code fires the React-Select menu no longer exists on the DOM or exists somewhere else therefore the menu thinks the click was outside the menu.

Regards

**Comment by SFPink** [comment]
Another better option might be to not close the menu on select and then close it myself manually, would this be possible?

**Comment by gwyneplaine** [comment]
@SFPink we supply a menuIsOpen prop on the select, please use this to programmatically control the component
``` type=javascript
<Select menuIsOpen={true} />
```

**Comment by SFPink** [comment]
@gwyneplaine Thanks, I reworked my menu so I no longer need a work around. Good to know none the less.
