### ISSUE TITLE
Expose onOptionHover internal

### ISSUE THREAD

**Issue by andrearosr** [JedWatson/react-select#3178]
### Use case

I have implemented a custom Option component that supports nested groups. I can select the appropriate sub-option by setting the `innerProps.onClick` value to a custom version of `selectOption`:
```
nestedInnerProps.onClick = () => selectOption(nestedOption);
return (
    <components.Option {...props} innerProps={nestedInnerProps}>
    ...
```

however, when I hover over any sub option, all the sub-options in the same group are "focused", because the `onOptionHover` internal points to the parent option.

My proposal is to expose the `onOptionHover` internal, the same way that the `selectOption` is, as a prop passed down to the components.

**Comment by autra** [comment]
My use case: I have a select containing different regions of a country. I also have a map of this country displayed. If I understand this correctly, this would also allow me to highlight the regions on the map as the user hover the corresponding options in the select.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
