### ISSUE TITLE
How to obtain the previous value of the dropdown?

### ISSUE THREAD

**Issue by spunbell** [JedWatson/react-select#3179]
Hi, I need to handle the previous value of the dropdown before the onChange function is called and the value is changed. How can I get this to work in this library?

**Comment by prashand** [comment]
Looking to do this myself and finding no way of doing this

**Comment by ebonow** [comment]
Greetings @prashand ,

You'd likely want to make it a controlled input with the value.

```jsx 
const [ value, setValue ] = useState();
const onChange = opt => {
  // value is your previous value
  // opt is your new value
  // Do comparison stuff and then set new value
  setValue(opt);
}

return <Select value={value} onChange={onChange} {...otherProps} />
```
