### ISSUE TITLE
onChange firing twice with multi={true} & searchable={false}

### ISSUE THREAD

**Issue by nickbouton** [JedWatson/react-select#318]
I'm running the following setup:

- `react-select-0.5.5`
- `react-input-autosize-0.5.0`
- `classnames-2.1.3`

When using a `multi={true}` select with `searchable={false}`, the `onChange` event appears to fire twice on every selection. It also doesn't seem to be properly removing selected options from the dropdown menu as expected based on [what's in the related readme section](https://github.com/JedWatson/react-select#multiselect-options).

**Note:** The `onChange` event doesn't seem to double-fire when `searchable={true}`, FYI, only when `false`.

I pared down my code to an absolutely basic example (basically what's in the readme + the two extra flags mentioned) and it's still happening. Not sure if this is a recently introduced issue or if it's been happening for a while, I only switched my multi-select to non-searchable today and ran into the issue. Tried rolling back to `react-select-0.5.2` to double-check and had the same issue.

Here's the code I tried (mine was inside a component so slightly altered for readability):

```
var Select = require('react-select');

var options = [
    { value: 'one', label: 'One' },
    { value: 'two', label: 'Two' }
];

function logChange(val, opts) {
    console.log("Selected: %o, %o", val, opts);
}

<Select
    name="form-field-name"
    value="one"
    options={options}
    multi={true}
    searchable={false}
    onChange={logChange}
/>
```

... and here's the console output in Chrome from clicking both list items once.

![image](https://cloud.githubusercontent.com/assets/169988/8713292/d7bcaa66-2b1b-11e5-984c-8dd677bf0667.png)

**Comment by NSinopoli** [comment]
I've also encountered this exact issue. Thanks for your great writeup, @nickbouton.

See #229 as well.

**Comment by seanmcl** [comment]
+1
