### ISSUE TITLE
"disabled: true" does not work in options list

### ISSUE THREAD

**Issue by givethemheller** [JedWatson/react-select#3180]
See comment below - disabled seems to be non functional in an option list.

**Comment by givethemheller** [comment]
Pretty self explanatory. On the primary demo page, the index. select Blue from the list. It does not show up as disabled. You are able to select it.

https://react-select.com/home

Constant from the data.js file is listed below, just so you know im not crazy

```export const colourOptions = [
  { value: 'ocean', label: 'Ocean', color: '#00B8D9', isFixed: true },
  { value: 'blue', label: 'Blue', color: '#0052CC', disabled: true },
  { value: 'purple', label: 'Purple', color: '#5243AA' },
  { value: 'red', label: 'Red', color: '#FF5630', isFixed: true },
  { value: 'orange', label: 'Orange', color: '#FF8B00' },
  { value: 'yellow', label: 'Yellow', color: '#FFC400' },
  { value: 'green', label: 'Green', color: '#36B37E' },
  { value: 'forest', label: 'Forest', color: '#00875A' },
  { value: 'slate', label: 'Slate', color: '#253858' },
  { value: 'silver', label: 'Silver', color: '#666666' },
];```

**Comment by cutterbl** [comment]
Did you forget the `isOptionDisabled` prop? This prop takes a method with `option` as it's argument, that you use to determine which options are disabled. I have a [codesandbox](https://codesandbox.io/s/z64y6k9xlm) that shows this in use.

Your use case would look a little like this:

`<Select {...otherProps} isOptionDisabled={(option) => option.disabled} />`

**Comment by givethemheller** [comment]
I think that approach is counter intuitive to the components intent. It's intended to be a direct replacement to a standard HTML select component and as such should respond to standard HTML option data in a functionally similar fashion. 

This behavior is a regression from 1.X

Happy to cut a fork an a PR for this. It appears that all it needs is that we need a default prop function.

**Comment by cutterbl** [comment]
@givethemheller I agree that that sounds more standard, though I like how the team gave a flexible option. Perhaps if you wrote a PR that implemented `isOptionDisabled` like that as a `defaultProp`, so that it could be overridden? That would retain the current flexibility, while providing a more convention-over-configuration like option out of the box.

**Comment by givethemheller** [comment]
We're on the same page. I'll pen it up.

**Comment by givethemheller** [comment]
Opened a PR. https://github.com/JedWatson/react-select/pull/3194

Had to declare an internal function. The use of default props runs in conflict to using a check on props to determine how to respond to the options disabled.

**Comment by Rall3n** [comment]
If you set `isDisabled` on an option, it should give the expected behaviour.
Example: https://codesandbox.io/s/r40rolxywn

**Comment by cutterbl** [comment]
@Rall3n I understand @givethemheller 's thought process on this though. `disabled` is a standard HTML attribute, so the logic is that an option definition object would match that. If `label` is the display text, and `value` is the select value, then by that logic `disabled` should disable the option.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
