### ISSUE TITLE
Typescript options -> value: number typing throws string.toLowerCase on search

### ISSUE THREAD

**Issue by givethemheller** [JedWatson/react-select#3181]
Not sure if this should be resolved as a bug or as a custom search function. We are using TS.

```
interface selectOptions = {
   value: string | number
   label: string
}

```
It craps on the number format for value. I think the right solution here could be to create an indexed array of value/label combos with a forced type of string. Will follow up in time, if I can, but here's the report. :-/

**Comment by givethemheller** [comment]
Would suggest the following in Creatable.js

`const compareOption = (inputValue, option) => {
  const candidate = String.toString(inputValue).toLowerCase();
  return (
    String.toString(option.value).toLowerCase() === candidate ||
    String.toString(option.label).toLowerCase() === candidate
  );
};`

**Comment by johnking** [comment]
I just found the same issue.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
