### ISSUE TITLE
Async fetch show all options regardless of matching input field value

### ISSUE THREAD

**Issue by si-harps** [JedWatson/react-select#3184]
Thanks for the great library.

I have a use case whereby I'd like to allow users to populate via async fetch not necessarily matching the input value.

For example, I have several books which have a title and isbn fields. A user needs to be able to enter the ISBN which will return 1 book object by its title. Because the input value (the ISBN) doesn't match any of the titles returned, the dropdown appears to be empty.

**Comment by ajaymathur** [comment]
Hey @si-harps , If I have understood your issue correctly we can use the `loadOptions` prop here.

Please see code sandbox example here -> https://codesandbox.io/s/o8m7o5r4z

I am matching the color value too, and so please observe the `filterColors` function here.

**Comment by si-harps** [comment]
Hey @ajaymathur thanks for the response. Would the above work for the following scenario? 

If you look at the attached screenshot you'll notice that the 3rd input field in the "Formats" section contains an ISBN value. From the network inspector you will see a request to was made via the loadOptions prop method.

The response contains a subset of 1 "book" object but of course, the title isn't listed in the available options because the input field doesn't match. I can't use the ISBN as the label or value as i would need to post the object iD on form submission.

Sorry if i'm overlooking anything from your previous answer and appreciate the assistance!

![screen shot 2018-11-12 at 09 36 57](https://user-images.githubusercontent.com/2602859/48339098-362cfe00-e65f-11e8-97e2-083b827780a9.png)

**Comment by ajaymathur** [comment]
@si-harps Can you create a codesandbox which represents your exact use case? You can fork https://codesandbox.io/s/o8m7o5r4z 

Having a codesandbox will give clear understanding of the scenario and solution. 🙂

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
