### ISSUE TITLE
Createable does work according to example/docs

### ISSUE THREAD

**Issue by mfreeman-xtivia** [JedWatson/react-select#3186]
So this has been driving me for nuts for hours and I'm just not convinced that it works as advertised in the simplest example here at [here](https://react-select.com/creatable)

The example below reflects a simple adaption (no Typescript) of the example there and *NOTHING* I can do in terms of props will get it to generate the "_Create xxx_" display of the new option being entered  in the control that appears at the bottom of the options list in the sample.

Can you tell me if the sample is broken, there's a bug somewhere, or I just don't get it?
```
import React from "react";
import ReactDOM from "react-dom";
import Creatable from 'react-select'

function App() {
  let options = [{ label: 'Item11', value: 1 }, 
                 {  label: 'Item12', value: 2 }]
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
     <Creatable options={options}/>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by ajaymathur** [comment]
Hey @mfreeman-xtivia , can you please take a look at https://codesandbox.io/s/jlx4zn1oj9

In the code above you need to include creatable like this ( from docs )

```js
import Creatable from 'react-select/lib/Creatable';
```

**Comment by rovnyart** [comment]
@ajaymathur can you please tell me why the hell my sandbox crashes on typing in select? am i missing something? Basically, i just copied code from your sandbox... https://codesandbox.io/s/qljvvm4984

**Comment by ajaymathur** [comment]
Well from the error I can see if the value of the option is string it works. [codesandbox](https://codesandbox.io/s/lyzyzq4kjz) 
I am at work right now so I cannot dig into and tell you the exact reason, I will check it once I am home. 🙂

**Comment by ajaymathur** [comment]
@rovnyart Team is already aware of the issue and there is a PR to fix this. Please take a look at https://github.com/JedWatson/react-select/pull/2990 🙂

**Comment by ajaymathur** [comment]
@mfreeman-xtivia Is your question answered in my comment above?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
