### ISSUE TITLE
Unable to programmatically hide react-select component

### ISSUE THREAD

**Issue by angkj** [JedWatson/react-select#3187]
Hi, I am attempting to add the display="none" attribute into the <Select> tag, but it does not work. Is there any way to make the <Select> tag disappear or appear depending on the selection of another previous <Select> tag?

**Comment by Rall3n** [comment]
@angkj 
If you only want to disable the component, then you can use the `isDisabled` prop. The component would still be visible, but the user can´t interact with it.
```jsx
<Select isDisabled={previous_selection != CERTAIN_VALUE} {...} />
```

If you want to completely hide the component from the user, then you can use conditional rendering. The component would only be rendered/mounted if the condition equals `true`.
```jsx
{previous_selection != CERTAIN_VALUE && <Select {...} />}
```

**Comment by angkj** [comment]
Great, your solution actually worked for me! I will be closing this. I was hoping in future versions the `display` tag would be included. I think it will be useful to have it. Cheers mate
