### ISSUE TITLE
Option: Behave as text field

### ISSUE THREAD

**Issue by agonsalves** [JedWatson/react-select#3190]
I know this seems weird, but there should be an option for the react-select field to simply behave as a regular text field with no select behavior, but have a lot of the same visual modification options. Maybe it can be another component.

The logic behind this suggestion: If you're constructing a form that is a combination of text fields and select fields, you will want them to be visually cohesive. However, if you're going to go through the fairly arduous process of modifying the appearance of the react-select field, then you might as well be able to reuse some of that work when modifying the other fields.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by thealjey** [comment]
@bladey I do believe that this feature would be very useful
it doesn't actually seem like it should be particularly difficult to implement
though, I do understand that it would probably have the lowest possible priority
it is just a small "quality of life" improvement

**Comment by ebonow** [comment]
I agree @thealjey and have [created a Discussion topic here ](https://github.com/JedWatson/react-select/discussions/4302) so we can discuss more in depth about the merits, side effects and desired behavior.

Perhaps you and others would be willing to contribute to the discussion there. Meanwhile, we would like to put an emphasis on separating feature requests from defects by closing older issues like this.
