### ISSUE TITLE
text not wrapping when it's too long.

### ISSUE THREAD

**Issue by paigeflourin** [JedWatson/react-select#3192]
word wrap doesnt seem to work when i input long text inside the select text field:

![word wrap](https://user-images.githubusercontent.com/6951524/48250212-82e2c000-e438-11e8-9f30-b162660c07a5.PNG)

my package json:

 "react-select": "^2.0.0",

my code;

    <CreatableSelect
            components={components}
            inputValue={inputValue}
            isClearable
            isMulti
            menuIsOpen={false}
            onChange={this.handleChange}
            onInputChange={this.handleInputChange}
            onBlur={this.handleBlur}
            onKeyDown={this.handleKeyDown}
            value={value}
          />

**Comment by paigeflourin** [comment]
nvm stupid of me to not notice the latest version.

**Comment by niyaza3** [comment]
@paigeflourin  what is the solution or this issue ?

**Comment by muhalik** [comment]
Same here.... any solution @paigeflourin 
if there is no solution for this then i have to leave react-select and move to any other library.
