### ISSUE TITLE
Document removal of `onNewOptionClick` and `promptTextCreator` in V2

### ISSUE THREAD

**Issue by IanVS** [JedWatson/react-select#3202]
It seems that `onNewOptionClick` was removed from `Creatable` in V2, but it is not mentioned in the [prop update guide](https://react-select.com/upgrade-guide#prop-update-guide)

There are a few open issues about it as well, so it might be worth cleaning those up with whatever the replacement is (I'm still figuring that out, but I think it's listening to the `onChange` meta type).

Edit: I found another one as well.  `promptTextCreator` seems to now be `formatCreateLabel` (https://github.com/JedWatson/react-select/issues/2019)

And `isOptionUnique`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
