### ISSUE TITLE
Editable MultiValue

### ISSUE THREAD

**Issue by paigeflourin** [JedWatson/react-select#3204]
i need the items created to be modified as well  as per user requirement but i dont see anything in the docs that says this can be done.

**Comment by paigeflourin** [comment]
> After clicking on an item you want the value itself to be editable?

yes.

**Comment by Skhoshhal** [comment]
After a target property is autocomplete, the user could be able to modify the value in the textbox (e.g., add something).
I didn't found some way to do this, Is It Possible ?

**Comment by paigeflourin** [comment]
@Skhoshhal ended up creating one myself https://codesandbox.io/s/o4kx95rory

**Comment by ebonow** [comment]
Greetings @paigeflourin 

I was going through code issues looking to close out non-relevant issues, and came across your code example. It's fantastic and I'll play around with it some more, to see how this could perhaps be easier ported over for others or possible as a PR into the repo.

I'll mark this issue as closed and thank you so much for creating and sharing this!
