### ISSUE TITLE
multiselect styling issues

### ISSUE THREAD

**Issue by rohankk2** [JedWatson/react-select#3208]
There seem to be styling issues in safari browser. I tried using react multiselect with safari and face the following styling issues:

1.  ##
<img width="1058" alt="screen shot 2018-11-16 at 6 04 39 pm" src="https://user-images.githubusercontent.com/29401337/48655319-264c4b80-e9ca-11e8-9382-66e0e41d5d0e.png">

The boxes are really fat and the |  between the placeholder and the arrow is displaced. 

On chrome it works neatly

<img width="973" alt="screen shot 2018-11-16 at 6 05 59 pm" src="https://user-images.githubusercontent.com/29401337/48655333-4ed44580-e9ca-11e8-9ff3-e465add1bd59.png">

Second thing is when i use multiselect on one dropdown and it becomes fat there is a huge gap in the other multiselect dropdowns as seen below: 

<img width="661" alt="screen shot 2018-11-16 at 6 10 07 pm" src="https://user-images.githubusercontent.com/29401337/48655400-226cf900-e9cb-11e8-85ac-24beba716f88.png">

ive marked the buggy areas in black.

**Comment by gwyneplaine** [comment]
@rohankk2, closing this for now, please feel free to file another issue with a sandbox reproduction

**Comment by rohankk2** [comment]
Hey I fixed this by changing some css. Thanks a lot!
