### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by anarasimhan** [JedWatson/react-select#3211]
Are the type definitions published for the latest version of react-select (2.1.1). The type definitions seems to be old (2.0.6). 

Thanks
Anand

**Comment by danieldelcore** [comment]
Hi there, 
Type defs have now [been added for v3](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/index.d.ts#L1)

**Comment by flexdinesh** [comment]
Thanks @danieldelcore! 

@anarasimhan as Daniel mentioned type defs have been updated for v3. I'm closing this issue. Feel free to open it if this doesn't help.
