### ISSUE TITLE
add "margin-top: -1px" to ".Select-input > input"

### ISSUE THREAD

**Issue by pierre-b** [JedWatson/react-select#322]
Hi guys,
First, thank you for this awesome component !

I noticed the .Select-input > input on Chrome added an extra pixel pushing the whole Select higher than expected.

Adding a "margin-top: -1px" to ".Select-input > input" fixed it. Useful to keep twitter bootstrap inputs aligned with the Select.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
