### ISSUE TITLE
onMenuScrollToTop and onMenuScrollToBottom not fired on navigate with keyboard

### ISSUE THREAD

**Issue by vtaits** [JedWatson/react-select#3220]
https://codesandbox.io/s/xvx5566q2w

`scrollIntoView` receives only dom-elements. Needs to fire handlers after set scroll.

**Comment by vtaits** [comment]
@rleos workaround for touch devices is add `captureMenuScroll={true}` prop.

**Comment by rleos** [comment]
Hm, true, didn't know that. Thx for that.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
