### ISSUE TITLE
Creatable no longer displays default values as tags

### ISSUE THREAD

**Issue by sonirico** [JedWatson/react-select#3224]
I would infer from the docs that passing `value={[{label: 'foo', value: 'bar'}]}` to the component should render objects in the `value` prop as interactive tags which can be deleted, as long as the `value` key from the object list is present in the `options` prop as well.

With the following code:

```jsx
<CreatableSelect
                isMulti
                onChange={this.handleChange}
                defaultValue={[{label: 'foo@bar.com', value: 'foo@bar.com'}]}
                options={[{label: 'foo@bar.com', value: 'foo@bar.com'}]} />
```

When the component is first mounted, it should be seen:

![imagen](https://user-images.githubusercontent.com/9306588/48872392-28a70f00-ede9-11e8-8214-089ea477769a.png)

However, I see this:

![imagen](https://user-images.githubusercontent.com/9306588/48872416-42485680-ede9-11e8-81b4-b5edfa6cc07f.png)

Bug? Feature?

Edit: Neither `value` nor `defaultValue` component props work

**Comment by gwyneplaine** [comment]
@sonirico  thanks for raising the issue.
I'm as of yet unable to replicate your issue, the sandbox below has this working as expected. 
https://codesandbox.io/s/509rn44n1p

Could you provide us with a sandbox of your own, it'll make it easier for us to triage this issue

**Comment by sonirico** [comment]
OK, my fault. High order component was overriding default props. Definetly, coding after lunch wreaks havoc.

Thank you so much for your help!
