### ISSUE TITLE
TSLint raise error for arrowRenderer in v.1.3.0

### ISSUE THREAD

**Issue by StefanoSega** [JedWatson/react-select#3226]
Using v1.3.0 of React Select TSLint raise an error relate to the property `arrowRenderer`.

The error is
```
[ts] Property 'arrowRenderer' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Select<IDropdownOptionType>> & Pick<Readonly<{ children?: ReactNode; }> & Readonly<Props<IDropdownOptionType>>, "children"> & Partial<...> & Partial<...>'. [2339]
```

the property looks like this:
```
arrowRenderer={() => (
                <KeyboardArrowDownIcon
                  className="dropdown-filter-icon"
                  style={{
                    fontSize: '16px',
                  }}
                />
              )}
```

`IDropdownOptionType` is a custom type that I use for the options

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
