### ISSUE TITLE
i want to remove clickability outside of close button when we give multi select, when we select multiple items size of dropdown increasing and clickability area of close button is also increasing

### ISSUE THREAD

**Issue by preethiv123** [JedWatson/react-select#3230]
i want to remove clickability outside of close button when we give multi select, when we select multiple items size of dropdown increasing and clickability area of close button is also increasing. how can i give clickability only to cross button

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
