### ISSUE TITLE
Control loses focus after entering 2 characters

### ISSUE THREAD

**Issue by erfansamieyan** [JedWatson/react-select#3237]
When I enter the second character, Control loses the focus and I have to pick the my choice from the suggestion which may be a lot! When I re-click it gets cleared. The odd thing is that I the problem happens only when the code is deployed and pushed to dev. There is no problem in local build. Any ideas on that? I saw kinda same problem in #2702  which seems still an open issue. But it says that the problem happens when we put an Input component inside the render() but in my code I didn't do this and Control component which contains Input is defined outside of the class. Here is part of my code. 
``` 
function inputComponent({ inputRef, ...props }) {
  return <div ref={inputRef} {...props} />;
}

const Control = props => {
  const { selectProps, innerRef, children, innerProps } = props;
  return (
    <Input
      classes={{
        root: selectProps.classes.inFieldRoot,
        input: selectProps.classes.inFieldInput,
      }}
      inputComponent={inputComponent}
      disableUnderline
      inputProps={{
        inputRef: innerRef,
        children,
        ...innerProps,
      }}
      {...selectProps.textFieldProps}
    />
  );
};
.
.
.
const components = () => ({
  Control,
  MultiValue,
  Option,
});
.
.
.
class InFieldChipAutoComplete extends Component<Props> {
.
.
.
render() {
      return
       (<Select
          components={components()}
          onInputChange={value => onTextChange(value)} // passed from parent 
          .
          .
          .
           />);
       }
} 
```

**Comment by Rall3n** [comment]
@erfansamieyan Could you provide a working example with your error in [CodeSandbox](https://codesandbox.io)? (Fork one of the examples from [react-select.com](https://react-select.com))

**Comment by erfansamieyan** [comment]
Unfortunately the code I'm working on has so many complexities with lots of dependencies, and I really can't put them all in CodeSandBox. I tried to reproduce the problem by writing a code similar to mine but it didn't happen. The only thing I can say is that I am using `onInputChange` in order to get filtered suggestions from the server, and about defining Input inside the render as you can see in the code it's been defined outside. Actually I defined `components` as function and called it like components(). Do you think it may cause same problem as defining the Input inside the render? Other than that I have no idea why it's behaving like that. 
And there is another thing which may be considering is that I passed the style of input in return like this:
```        
        <Select
            styles={{
              ...styles,
              indicatorsContainer: () => ({ display: 'none' }),
              input: () => ({
                color: theme.palette.type === 'dark' ? 'white' : 'black',
              }),
            }}
            .
            .
            .
         />
```

**Comment by erfansamieyan** [comment]
My problem was as I suspected. Defining that `components` as a function and using it like `components()` is exactly like defining each of those components like `Control`  inside the render and since I had used `onInputChanged` the problem which was mentioned in #2702 happened to me too. So I changed it to:
```
const components = {
        Control,
        Menu, 
        .
        .
     }
```
And the problem was solved!
