### ISSUE TITLE
The payloads for onChange seem inconsistent.  

### ISSUE THREAD

**Issue by stoplion** [JedWatson/react-select#3238]
The payloads for onChange seem inconsistent.  
Seems like keys could always be named `action` and `option`. I.E. The `action` of `remove-value` is 'removing' the `option`. etc, the keyname 'removedValue' is seems unnecessary. 
![image](https://user-images.githubusercontent.com/231343/49057012-be101d80-f1b2-11e8-9f70-94b4c958fe63.png)

**Comment by stoplion** [comment]
dupe

**Comment by danielgolden** [comment]
Where's the original?
