### ISSUE TITLE
Is there currently a way for users to enter a custom value?

### ISSUE THREAD

**Issue by brandondurham** [JedWatson/react-select#324]
I'm using this with a WYSIWYG-type of tool. For some fields I would love to offer an array of options, but also allow the user to enter their own value. For example: I’m offering several preset font-size options, but would love for them to be able to enter their own.

Is this possible without somehow extending?

**Comment by anavarro9731** [comment]
Yes, it's called TAGS MODE on the Live Demo Page.
You need to set these two properties multi={true} allowCreate={true}
the docs need updating as allowCreate is not listed as an option.

**Comment by brandondurham** [comment]
GREAT! Thank you!
