### ISSUE TITLE
adding key value pair to 

### ISSUE THREAD

**Issue by rohankk2** [JedWatson/react-select#3243]
So my list is as follows:

[{id:0,value:c,label:'N',key:'N'},{id:1,value:c,l:'A',key:'A'},{id:2,value:c,label:'B',key:'want to access this'}]

When I select one of the options lets say option with label B. I am only able to see the value and label params of that object how can i access the key param when I do a onchange ?

for ex:

onChange = { opt => somefunction} 

I am able to see opt['label'] but not opt['key'] even though i specified it when I pushed my list into the react select module

**Comment by Rall3n** [comment]
@rohankk2 Would you mind providing a code example? I was able to access the custom attribute of my option as it was passed to the `onChange` prop.

Here is an working example in [CodeSandbox](https://codesandbox.io/s/rm02q6pw0q). (Check the console when selecting options.)
