### ISSUE TITLE
filter option is not called if options are changed in parent.

### ISSUE THREAD

**Issue by rohankk2** [JedWatson/react-select#3244]
When I change my options array in the parent and pass it to the select. although the labels change the filter option which should remove certain labels only does so after you interact with the dropdown, i.e, select something or enter some value in the search bar.

options=[{label:'ALL',value:'ALL',key:'ALL'}]
through some other code if this option changes to :   
options=[{label:'A',value:'ALL',key:'ALL'},{label:'ALL',value:'ALL',key:'ALL'}]
and filter options is to show only those with label A 

I still see both the options. If I search or select something then I see only one option.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
