### ISSUE TITLE
Allow text wrapping for long options

### ISSUE THREAD

**Issue by ishtiaque-khan** [JedWatson/react-select#3246]
### Thanks for using react-select!

Long option labels get cut off. There should be some way to control that via emotion. For example being able to wrap the text around with emotion could be a solution.

![overflow](https://user-images.githubusercontent.com/37980794/49331190-81ce2a00-f5c3-11e8-8524-6f6a43e49757.png)

Sandbox: https://codesandbox.io/s/xrk0xz9y9p

**Comment by Rall3n** [comment]
`react-select` provides a [Styling framework](https://react-select.com/styles#style-object) via the `customStyles` prop. The [documentation](https://react-select.com/styles#style-object) should give you a clear idea of how to use it.

**Comment by gwyneplaine** [comment]
@ishtiaque-khan see the above linked docs on how to use the styling api to affect the changes you're after. 

closing this issue

**Comment by entozoon** [comment]
Coulda said how to do it..
