### ISSUE TITLE
React select multi options blur on select option

### ISSUE THREAD

**Issue by anubhavr19** [JedWatson/react-select#3247]
React select options automatically hide once we select option. I am using multi select. My code is below there. 

```

                            <Select
                              clearable={false}
                              name="keySkill"
                              id='keySkill'
                              value={this.state.data.keySkill}
                              onChange={(e) => this.onChangeSkills(e, 'keySkill')}
                              options={UTILITY.technologies}
                              placeholder='Please select keySkill'
                              multi={true}
                           />
                          

```

**Comment by ebonow** [comment]
You are looking for the prop: `closeMenuOnSelect`. Set this to false for your multi-select.

Thank you and please close this if it meets your needs.

**Comment by anubhavr19** [comment]
> @anubhavr19 : You are looking for the prop: `closeMenuOnSelect`. Set this to false for your multi-select.
> 
> Thank you and please close this if it meets your needs.

I have use this prop but its not working.

**Comment by TallOrderDev** [comment]
@anubhavr19 Could you please post your code leveraging the above mentioned prop. Without more info or code it'd be nearly impossible to guess what is going wrong! Thanks!

**Comment by gwyneplaine** [comment]
@anubhavr19 as mentioned above, please create issues with a [codesandbox](https://codesandbox.io/s/new) reproduction, it'll make it easier for us to diagnose. 

Closing this issue now, if your problem persists, please feel free to create a new issue with a codesandbox reproduction.
