### ISSUE TITLE
can't override outline, marked as important

### ISSUE THREAD

**Issue by amaan75** [JedWatson/react-select#3248]
I am very new to the issues/bug/feature thing, so sorry if i mark it as the wrong thing or if its not the correct place to be posting/asking this. 

i wanted to override the outline property of react-selectV2 and couldn't do it because it is marked as 
outline : 0 !important

i want to do it with css only, inline styles is not an option for us.
this is the style  that i used to override the css, but emotion, shows up below my custom css in the index html so i can't seem to override it.

```css
.react-select__control--is-focused{
    outline:2px dotted  !important;
    outline-offset:1px;
    }
```

so the first red boundary is my css and the second red boundary is the provided emotion css
also, in the screenshot there is no important, because i edited it using chrome devTools, sorry for posting a misleading image.
<img width="598" alt="screenshot 2018-12-04 at 8 58 56 am" src="https://user-images.githubusercontent.com/11543299/49417257-0aef8780-f7a3-11e8-9393-a8b22a577d17.png">

it would be great if you could consider removing that !important from there or if there is another way to override this using css please inform me about it?
Thanks

**Comment by yuri-sakharov** [comment]
Hi, work good for me as you wrote 
`.bzm-select__control--is-focused {
        outline: 2px dotted black !important;
    }`
Are you able to override another props?

**Comment by yuri-sakharov** [comment]
I imported my style less and it's works 
`import './select.less';`

**Comment by amaan75** [comment]
> I imported my style less and it's works
> `import './select.less';`

can you check it in this repo please?

[testrepo](https://github.com/amaan75/pmnet)

or atleast tell me where i am going wrong in this. btw i am using plain css

**Comment by amaan75** [comment]
Umm, i actually wrote that because it wasn't working, so as a workaround i was using focus and blur event to add a new css class to it which would use the outline on the react-select-container. And i just copied the css from the compiled css from scss and that works. But the question still remains is the !important in outline by default really required?

**Comment by yuri-sakharov** [comment]
I don't know

**Comment by MrJadaml** [comment]
@yuri-sakharov, yes the use of `!important` is bad practice. I am also running into issues as a result of  that attribute being set as `!important` by default.

**Comment by hanabalon** [comment]
I got the same problem, how do you solved it?

**Comment by timtmok** [comment]
I still get this problem. It's kind of weird to have to add in a very specific css selector to override the default style. You can never override the container style because the default one will take precedence. I'd have to wrap the component in another container with a class name to make a more specific selection.

**Comment by amaan75** [comment]
> I still get this problem. It's kind of weird to have to add in a very specific css selector to override the default style. You can never override the container style because the default one will take precedence. I'd have to wrap the component in another container with a class name to make a more specific selection.

you can switch to scss, and with that it somehow works, `ihaven't` put in enough research in it to know why it does work with scss, but i know that it does. try this.
`.react-select-container{
    width: 180px;
    .react-select__control--is-focused{
      outline:2px dotted #333333 !important;
      outline-offset:1px;
      }
  }`

**Comment by amaan75** [comment]
sorry, closed it by mistake

**Comment by pstephenwille** [comment]
Why is it so hard to override the blue focus outline?

**Comment by Rall3n** [comment]
The Outline is not handled by the `outline` css property.
It is instead created using a border on the `Control` component.
It is defined as follows:
```jsx
  borderColor: isDisabled
    ? colors.neutral10
    : isFocused
    ? colors.primary
    : colors.neutral20,
  borderRadius: borderRadius,
  borderStyle: 'solid',
  borderWidth: 1,
```

No `!important`, so you can overwrite it yourself using `!important` in your stylesheet.

-----

But you could also overwrite the style definition for the component to remove the outline property entirely:
```jsx
<Select
    styles={{
        control: ({ outline, ...provided }) => provided // Removes `outline` from the styling
    }}
/>
```

**Comment by bladey** [comment]
Thanks for the reply @Rall3n!

@amaan75 if this doesn't help please let us know and we'll re-open the issue.
