### ISSUE TITLE
IE11 Vertical Alignment issue

### ISSUE THREAD

**Issue by dep** [JedWatson/react-select#3250]
This is present in `react-select@2.1.1` but we also noticed this in `2.0.0`.

Screenshot:

![](http://dl.dpeck.net/ds0hDl+)

There is an alignment issue where more spacing appears below the text than above it. Thank you in advance!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
