### ISSUE TITLE
Request for formatCreateLabel

### ISSUE THREAD

**Issue by malmil** [JedWatson/react-select#3255]
I think this is more a feature request rather than an issue.
Can't seem to find an easy way to do this.

*   What's your use case? 
When using formatCreateLabel in CreatableSelect I want to pass my own customized text + the input value from user. So formatCreateLabel should take two params  where the inputValue should be optional.

formatCreateLabel={() => 'Add', inputValue }

**Comment by ebonow** [comment]
formatCreateLabel already passes input value as the argument.

```javascript
const formatCreateLabel = (inputValue => 'Add ' + inputValue);
```

Please close this if this fulfills what you are looking for.

**Comment by malmil** [comment]
Yes! Thank you

**Comment by matenka-andrii** [comment]
Hi Guys. Thanks for a great plugin. Why do I can't use any symbols except [a-zA-Z0-9]?

`
_formatCreateLabel = (value) => {
    return `Create:.,\' ${value}`;
};
`
