### ISSUE TITLE
React-select onMouseOut Event

### ISSUE THREAD

**Issue by mouadecl** [JedWatson/react-select#3256]
Hello,

There's an issue with the react select dropdown box, cause when i scroll down through the items, each item got grey background color (which is normal), but once I removed the mouse from the item to the outside of the dropdown, the last item stayed colored in grey, which is abnormal.

Is there a way to fix this issue, using one of the parameters onmouseleave or onmouseout ?

**Comment by mouadecl** [comment]
Hello, 

There's an issue with the react select dropdown box, cause when i scroll down through the items, each item got grey background color (which is normal), but once I removed the mouse from the item to the outside of the dropdown, the last item stayed colored in grey, which is abnormal.

Is there a way to fix this issue, using one of the parameters onmouseleave or onmouseout ?

**Comment by gwyneplaine** [comment]
@mouadecl please provide a [codesandbox](https://codesandbox.io/s/new) reproduction, so we can more effectively diagnose and resolve the bug you're reporting.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
