### ISSUE TITLE
@flow strict

### ISSUE THREAD

**Issue by zeorin** [JedWatson/react-select#3266]
Please consider switching to the [`@flow strict`](https://flow.org/en/docs/strict/) pragma:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/ui-utils/AutoSuggestion/index.jsx:4:8

Dependencies of a @flow strict module must also be @flow strict! (nonstrict-import)

     1│ // @flow strict
     2│ import * as React from 'react';
     3│ import { compose } from 'recompose';
     4│ import Select from 'react-select';
     5│ // Material Core
     6│ import { withStyles, withTheme, type Theme } from '@material-ui/core/styles';
     7│ import Typography from '@material-ui/core/Typography';
```

Beyond being a good idea because it makes your code more type-safe, it'll be great for projects that use `@flow strict` themselves, with the [`nonstrict-import`](https://flow.org/en/docs/linting/rule-reference/#toc-nonstrict-import) rule enabled, [since there is currently no way to exclude 3<sup>rd</sup> party dependencies from that rule](https://github.com/facebook/flow/issues/6628).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
