### ISSUE TITLE
How to open menu ONLY when user starts to type something? 

### ISSUE THREAD

**Issue by Steffi3rd** [JedWatson/react-select#3268]
Actually, right now when I click on the field, the menu is displayed.
I don't want this behavior.

That's why I set ` components={{ DropdownIndicator: null }}`

How to open menu ONLY when user starts to type something?

**Comment by ebonow** [comment]
@Steffi3rd  A few things that might give some clarity...

`DropdownIndicator` only represents the down-caret icon and is for presentation purposes only.

The props you are looking for seem to be: 
`openMenuOnFocusboolean` = (default: false)
Allows control of whether the menu is opened when the Select is focused

`openMenuOnClickboolean` = (default: true)
Allows control of whether the menu is opened when the Select is clicked

If this helps, please close this "issue".

**Comment by gwyneplaine** [comment]
@Steffi3rd here's an example of how you can use the menuIsOpen prop in conjunction with the onInputChange prop to do what you've asked. 

https://codesandbox.io/s/m59xvwlpkj

**In the future, please open this in stackoverflow instead, the issues section is filing bugs and feature requests only** 

closing this issue now
