### ISSUE TITLE
Clearing Input does not focus the option defined in focusedOption prop.

### ISSUE THREAD

**Issue by mike391** [JedWatson/react-select#3269]
When clearing the input of react-select, the `focused option` is still the previously selected value, it would make more sense to be the default `focusedOption` or the first option in the list instead.

**Comment by vnallamhawk** [comment]
is this issue still open ?

**Comment by mike391** [comment]
Update: PR Opened: [#3314](https://github.com/JedWatson/react-select/pull/3314)

**Comment by lukebennett88** [comment]
Hi @mike391
I was unable to reproduce this, but I think it may have been resolved already.
Please re-open if needed.
