### ISSUE TITLE
Value is not preselected.

### ISSUE THREAD

**Issue by Andreyco** [JedWatson/react-select#327]
**Use case:**
- passing array of Integers as options to component
- setting value prop to one of passed options. Value is Integer.

**Expectation:**
- existing value should be preselected

**Result:**
- nothing is preselected

**Note:**
- after casting value prop to String does preselect existing value.

**Comment by Blystad** [comment]
+1 I encountered the same bug.

**Comment by Andreyco** [comment]
Thank you!
