### ISSUE TITLE
[v2] Support for Emotion 10

### ISSUE THREAD

**Issue by aaronjensen** [JedWatson/react-select#3276]
react-select appears to depend on emotion 9. Similar to #3120, if I'm using a newer version of emotion (like 10) I'll have 2 versions of emotion at best (if it works). At the moment I'm running into typing errors between the two, but ideally we could upgrade react-select to emotion 10. If you're up for a PR doing this, I may have some time to pull that together.

Cheers!

**Comment by applebaum** [comment]
That would also fix SSR issues for Next.js users without needing to set up the whole emotion-server infrastructure.

**Comment by aaronjensen** [comment]
@gwyneplaine it looks like this was actually done and released here already: https://github.com/JedWatson/react-select/commit/4bad8b8dbe6ac5a4dacab1e712daf845c1bcdca9

**Comment by andrerpena** [comment]
@aaronjensen Thanks for the reply but I don't see it released on latest (2.4.2). I also don't see an alpha release. This issue should be open until it is released.

**Comment by aaronjensen** [comment]
@andrerpena when I wrote this, I believe 2.2.0 was the latest version and it was using `create-emotion` 10 and not depending on `emotion` at all: https://unpkg.com/react-select@2.2.0/package.json

We used it successfully w/ emotion 10 on my last project. Since it appears this was undone https://github.com/JedWatson/react-select/commit/214a161c86b68732d6b37894a6c7e42d6331b0d7 I'll reopen.

**Comment by andrerpena** [comment]
Thank you so much @aaronjensen. This is important to unlock Next.js users

**Comment by gwyneplaine** [comment]
create-emotion doesn't unlock zero-configuration SSR, actually it makes ssr more difficult as the same custom emotion instance needs to be passed to both the client side and server-side select. 

This is the primary reasoning behind the reversion in 2.3.0. For more details about this please see #3317 and #3346. 

I'm looking to release 3.0.0 with an upgrade to emotion 10 with a NonceProvider export which should both unblock CSP users and enable true zero-config SSR, you can see the details of that pr here #3321.

**Comment by leerob** [comment]
@gwyneplaine That would be amazing! The Next.js community is growing rapidly and would love to use `react-select`!

**Comment by lukehamilton** [comment]
When will this be rleased?

**Comment by ebonow** [comment]
Per the release notes, I believe we can consider this shipped and closed 
https://github.com/JedWatson/react-select/releases/tag/react-select%403.0.3
