### ISSUE TITLE
menuPlacement="auto" does not respect maxMenuHeight property

### ISSUE THREAD

**Issue by luiz290788** [JedWatson/react-select#3278]
When `menuPlacement="auto"` is set and the menu is flipped (moved to the top of the select) the maxMenuHeight property is not respected and the menu is huge.

Here is a sandbox with the issue
https://codesandbox.io/s/o7mrlm6z15

**Comment by luiz290788** [comment]
I found this pull request that probably solves the issue.
https://github.com/JedWatson/react-select/pull/3205

**Comment by Mihaela-Mac** [comment]
@luiz290788 That got merged, but installing the module with either `npm install react-select` or `npm install react-select@latest` does not bring the changes from that PR. Did you have any luck with this?

**Comment by dep** [comment]
This still appears to be an issue for me on `2.2.0`

**Comment by dep** [comment]
In the meantime you can give a `max-height` to the menu-list via CSS

**Comment by Mihaela-Mac** [comment]
@dep FYI, a new version has been published `2.3.0`. Updating has fixed the issue for me.

**Comment by matthova** [comment]
I'm still seeing this issue with 2.3.0 when using a menu portal

**Comment by dep** [comment]
I am also still seeing the issue.   `menuPlacement="auto"` still does not appear to respect the `maxMenuHeight` property.

**Comment by Mihaela-Mac** [comment]
Strange. It works for me and I use both menu portal and menu placement auto. Eg.
```
const menuPortalTarget = document.getElementById('root');
<Select
          maxMenuHeight={220}
          menuPlacement="auto"
          menuPortalTarget={menuPortalTarget}
/>```

@dep if you still have the `max-height` property I think you should remove it. At least for me it was causing some flickerish effect when the dropdown was at the bottom of the page (that happened with the previous version though).

**Comment by noraboamaah** [comment]
> When `menuPlacement="auto"` is set and the menu is flipped (moved to the top of the select) the maxMenuHeight property is not respected and the menu is huge.
> 
> Here is a sandbox with the issue
> https://codesandbox.io/s/o7mrlm6z15

the code sandbox worked for me!

**Comment by bladey** [comment]
Hi all,

Thank you everyone who had a part in addressing this question!
I'm now closing this issue as it appears to have been resolved via community comments.

However, if you feel this issue is still relevant and you'd like us to review it, or have any suggestions regarding this going forward - please leave a comment and we'll do our best to get back to you!

**Comment by amitava82** [comment]
This is still an issue.

**Comment by ebonow** [comment]
Thank you @amitava82 
This is a known issue as there is [several](https://github.com/JedWatson/react-select/issues/4493) [similar](https://github.com/JedWatson/react-select/issues/4336) [issues](https://github.com/JedWatson/react-select/issues/4108) related to or duplicated by this behavior that will be prioritized following the ongoing TypeScript refactoring.
