### ISSUE TITLE
react-select does not display selected items with column-count 

### ISSUE THREAD

**Issue by toddcoulson** [JedWatson/react-select#3289]
https://codesandbox.io/s/oj7ozo9rv9
In the following code, if a div holds react-select and uses column-count, the react-select element does not display items selected. I am not sure why css would break functionality, but it seems like it shouldn't.

**Comment by gwyneplaine** [comment]
@toddcoulson  thanks for raising this, this is an issue with interactions between column-count and transform 
https://bugs.chromium.org/p/chromium/issues/detail?id=84030
At the moment there's no good work around for this that I can think of, happy to field a PR for it thought if you have ideas. 

In the meantime we recommend using flex for column layouts as per the sandbox below. 
https://codesandbox.io/s/mzrp229768

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by andriyloza** [comment]
Issue is still present. We can not use `react-select` element inside block with `column-count`. Options jump to other column and content can jump to other column.
