### ISSUE TITLE
Menu stretched parent container's height. 

### ISSUE THREAD

**Issue by seeddyan** [JedWatson/react-select#3297]
When menu's has no space to open, it isn't appropriate to stretch parent container's height.
Like the picture below.
<img width="230" alt="2018-12-20 6 24 12" src="https://user-images.githubusercontent.com/3996319/50320330-ca17a280-0506-11e9-9728-d32ca695491f.png">

The elegant approach to fix this problem is to open menu according to the select container's position.
The similar functionality with an existing libraries: https://ant.design/components/select/

Please fix it and thanks for great job! 👍

**Comment by Rall3n** [comment]
@seeddyan could you provide an example with [CodeSandbox (fork it from here)](https://codesandbox.io/s/k5rvn9z3lv)? I might have a solution, but it´s better to have a complete reproduction of the issue.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
