### ISSUE TITLE
React Element in label of an option causes "circular structure to JSON" exception

### ISSUE THREAD

**Issue by 0xCMP** [JedWatson/react-select#330]
Related to #296 and #329 
```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at [object Object].render (/Users/cp/Code/***/src/shared/views/****/components/****.jsx:53:33)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/cp/Code/****/node_modules/react/lib/ReactCompositeComponent.js:789:34)
```

Where it blows up (Select.js, line 153):
```
	componentWillReceiveProps: function(newProps) {
		if (JSON.stringify(newProps.options) !== JSON.stringify(this.props.options)) {
```

The offending code I wrote:
```
let options = props.***.map(item => {
  let option = {
    item,
    value: item.id,
    label: <span>{item.title}</span>
  };
  if (+item.id === itemId) {
    currentItem = option;
  }
  return option;
})
```

**Comment by bruderstein** [comment]
Yes, custom components for label aren't (yet) directly supported, but as you mentioned by the linked issues / PRs, you can now use `singleValueComponent`, `valueComponent` and `optionComponent` (or the renderer equivalents, `valueRenderer` and `optionRenderer`, if you'd prefer) to render your values / options.

**Comment by prasannasv** [comment]
Apologies if this is the wrong place to ask questions. I am a noob to React and have the same problem. I want to add `<Label>` tag to my option values. I don't understand what `<optionComponent>` means (Google doesnt' help nor the related issues).
Here is my code snippet:
```javascript
          let options = rooms
              .map(room => ({ value: room.id, label: (<Label>{room.name}</Label>) }))
          roomPicker = (
            <div>
              <Select placeholder='Choose a room...' value={selectedRooms[index].roomId}
                options={options} clearable={false} onChange={value => onChangeRoom(index, value)}/>
            </div>
```

**Comment by prasannasv** [comment]
nvm. Figured it out. `optionRenderer` is another attribute of the `Select` tag that takes in a function that can do the custom display of an option. Once you specify that, there are no longer any circular structures.

**Comment by tachang** [comment]
I can't seem to find any reference to singleValueComponent

**Comment by dilip-pmap** [comment]
Same Issue for Me Also...  

Based on the condition ,   I will apply the options render if item is isCustomData Source then need show . label name otherwise normal label.

const dataSourceTypes = dapBuilderLookups.items.DataSourceTypes;
    dataSourceTypes.forEach((item) => {
        if (item.IsCustomDataSource) {
          item.Label = <div className="customDatasource-indicator" >{item.Label}</div>;
        }
    });
