### ISSUE TITLE
multi value select uses getOptionValue for react key, doesn't work for non-prim values.

### ISSUE THREAD

**Issue by toshok** [JedWatson/react-select#3306]
I use non-primitive values for my options (providing a getOptionLabel to turn them into strings.)  The problem is https://github.com/JedWatson/react-select/blob/916ef8f2813dbdd7bb5adb186ab3a085d40003c3/src/Select.js#L1478

uses the value for the react key.  When `isMulti={true}`, I see a lot of:

![image](https://user-images.githubusercontent.com/24245/50544899-b553a280-0bc9-11e9-91a2-868b581c2c2e.png)

**Comment by toshok** [comment]
maybe a `getOptionKey` prop would be appropriate?

**Comment by james-prado** [comment]
@toshok You could replace the `<MultiValue />` component and declare the key however you like:

```
import Select, { components } from 'react-select';
import uuidv4 from 'uuid/v4'; // Generate unique id

const MultiValue = (props) => {
    return <components.MultiValue {...props} key={uuidv4()} />;
};

const CustomSelect = (props) => {
  return (
    <Select
      components={{ MultiValue }}
      {...props}
    />
  )
}
```

**Comment by james-prado** [comment]
Nvm, this doesn't work because the custom component still gets wrapped for some reason :confused: 

![Screenshot from 2019-04-30 18-04-18](https://user-images.githubusercontent.com/13836920/56996413-7da63880-6b72-11e9-9ba4-427b58ccbc96.png)

**Comment by nicolas-zozol** [comment]
The good way to work with complex object value is to use `getOptionValue()`
and `getOptionLabel()`. It's not very clear but works very well, as we had exactly the same problem.


```jsx
const CustomSelect = (props) => {
  return (
    <Select
     getOptionValue=(option)=>option.user.id
     getLabelValue=(option)=>option.user.fullName
      {...props}
    />
  )
}


```

**Comment by bladey** [comment]
Hello -

Thanks for your assistance @nicolas-zozol.

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by RaGreen** [comment]
![image](https://user-images.githubusercontent.com/1823017/93886376-9d00b100-fce5-11ea-984f-93614758419d.png)
MultiValue component created by Select is throwing "Warning: Each child in a list should have a unique "key" prop." after selecting first value from Select with isMulti set to true.
