### ISSUE TITLE
contradicting getNewOptionData parameter type

### ISSUE THREAD

**Issue by nafg** [JedWatson/react-select#3311]
The docs say the second argument is a `Node`, and indeed in `componentWillReceiveProps` (https://github.com/JedWatson/react-select/blob/master/src/Creatable.js#L102) it's passed the result of `formatCreateLabel`.

However in `onChange` (https://github.com/JedWatson/react-select/blob/master/src/Creatable.js#L132) the second argument is the same as the first, a `string`. Indeed the implementation in `builtins` (https://github.com/JedWatson/react-select/blob/master/src/Creatable.js#L58) is typed to take two `string`s.

Am I missing something, or is this broken?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
