### ISSUE TITLE
Is it possible to pass the event to onInputChange so that we can decide what we want to do based on user input?

### ISSUE THREAD

**Issue by wyrmmm** [JedWatson/react-select#3312]
### Thanks for using react-select!

Before creating an issue...

# Are you asking a question?
No

# Are you reporting a bug or runtime error?
No

# Are you making a feature request?
Yes

*   **What's your use case? (Tell us about your application and what problem you're trying to solve.)**
I was trying to implement copy and pasting using the Creatable component. The onInputChange function is great in allowing us to respond to user input, but it doesn't allow me to detect what keys the user has pressed. For example, I would like to detect if the user has pressed Ctrl + v to paste from the clipboard. I imagine that there might be other kinds of behaviour that we might want to implement to based on the keys that the user has pressed.

*   **What interface do you have in mind? (What new properties or methods do you think might be helpful?)**
Would it be possible for the onInputChange function in the Select component to also receive the event object? Right now, it accepts two arguments.
```
onInputChange(newValue: string, actionMeta: InputActionMeta) {
    this.props.onInputChange(newValue, actionMeta);
  }
```
Could we change it to also accept an event object? E.g.:
```
onInputChange(event: SyntheticEvent, newValue: string, actionMeta: InputActionMeta) {
    this.props.onInputChange(newValue, actionMeta);
  }
```

*   **Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)**
NA

If this seems like the right thing to do, I don't mind creating a pull request.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
