### ISSUE TITLE
Using menuPortal target causes menu to stay in place

### ISSUE THREAD

**Issue by ashanren** [JedWatson/react-select#3313]
When you use the menu portal target options, open the menu options, and then scroll in any direction the option menu stays in place. This is recreatable in the demo on https://react-select.com/advanced#portaling if you open the console horizontally and open it large enough for the overflow scrollbar to appear in the modal.

**Comment by ashanren** [comment]
This got fixed with the 3.0 release

**Comment by benkindt** [comment]
I ran into this again. Sure this is fixed?

I have `menuPortalTarget={document.body}` and the element that produces the `overflow: scroll` is a div somewhere inside the body (only a part of the page is scrollable). 
Do I need to change the menuPortalTarget or where am I wrong?

**Comment by benkindt** [comment]
A workaround for this is to block scrolling with `menuShouldBlockScroll={true}`

**Comment by AmirTugi** [comment]
Is there any progress with a solution for this?
@ashanren are you sure they fixed it in v3.0? It's happening in the doc like @benkindt mentioned

**Comment by ranihorev** [comment]
@benkindt I tried that but there is an open issue with `menuShouldBlockScroll`:
https://github.com/JedWatson/react-select/issues/3929

**Comment by benkindt** [comment]
You're right @ranihorev . I'm not sure if I just wasn't aware of the mentioned issue or this once worked in an older version.
