### ISSUE TITLE
Feature Request: Range selection

### ISSUE THREAD

**Issue by ksnyder** [JedWatson/react-select#3325]
I love this library and it would be great if users could select a range of options (by holding down Shift or some other key) instead of having to build up their selections one at a time.  The use case is a long list of options where users always select a large number of options (about 10-40), and those options are usually in contiguous blocks.  For options not in a contiguous range, they could se the Ctrl key to select individual options.  Thanks.

**Comment by cristi0212** [comment]
It would be good if range will be implemented, like react-super-select.
With Shift + click to be selected entire range.
Tkank you!

**Comment by ebonow** [comment]
Moved from issues to discussions
