### ISSUE TITLE
How can i move dropdownIndicator to the left

### ISSUE THREAD

**Issue by eltonjothi** [JedWatson/react-select#3329]
As the title suggest how can i achieve this.

**Comment by maleja111** [comment]
I have to do this:
const dropdownIndicator = () => (
` <div style={{position: 'absolute', float: 'right !important', marginLeft: '5px'}} >
            <i className={'fa fa-search '} aria-hidden="true"></i>
        </div>
    );`

styles on valueContainer like this:
` const colourStyles = {
    control: styles => ({ ...styles, 
      backgroundColor: 'white',
    }),
    valueContainer: styles => ({ ...styles, 
      left: '35px',
      float: 'right !important',
      position: 'absolute',
      width: '91%',
    }),
    loadingIndicator: styles => ({ 
      ...styles, 
      left: '85%',
      float: 'left',
      position: 'absolute',
    }),
    option: (styles, { data, isDisabled, isFocused, isSelected }) => {
      return {
        ...styles,
        cursor: isDisabled ? 'not-allowed' : 'default', 
        ':active': {
          ...styles[':active'],
        },
      };
    },
  };`

and on the select:
`<Select
        components={{ IndicatorSeparator: null, DropdownIndicator  }}
        styles={colourStyles}
  />`

**Comment by maleja111** [comment]
my proposal with CSS
if someone else knows how to do it with the documentation it would be a great contribution

 const DropdownIndicator = () => (
        <div className={classes.dropdownIndicator} >
            <i className={'fa fa-search'} aria-hidden="true"></i>
        </div>
    );

**colourStyles** 

const colourStyles = {
    control: styles => ({ 
      ...styles, 
      backgroundColor: 'white',
      flexDirection: 'row-reverse',
    }),
    loadingIndicator: styles => ({ 
      ...styles, 
      left: '85%',
      float: 'left',
      position: 'absolute',
    })
  };

**The select**
<Select
  components={{ IndicatorSeparator: null, DropdownIndicator  }}
  isClearable={false}
  styles={colourStyles}
>
