### ISSUE TITLE
How to use value of objects?

### ISSUE THREAD

**Issue by Lekha30** [JedWatson/react-select#3333]
May be related to https://github.com/JedWatson/react-select/issues/858

# Are you reporting a bug or runtime error?
I am trying to use values of objects for the select options: 
option:1 {label: "Age-5", value:{name:"Age", value:"5"}}.
option:1 {label: "Age-5", value:{name:"Age", value:"5"}}.
option:1 {label: "Age-5", value:{name:"Age", value:"5"}}.

But When the options are chosen, they don't get matched against the selected values 👍 
![image](https://user-images.githubusercontent.com/6767299/50868966-2be07380-1406-11e9-89c7-cee6c5e77a3f.png)

I have tried `valueRenderer` option too, but can't quite get that to working. Any pointers to fix this is much appreciated.

Thanks

**Comment by reeversedev** [comment]
Have you tried `Object.values()`?

**Comment by mathesmyhotelshop** [comment]
I was able to use objects as options.

Having
```
const dogs = [ { id: 1, name: 'dog1' }, { id: 2, name: 'dog2' }, { id: 3, name: 'dog3' } ];
const selectedOption = dogs[0];
```
the code
```
<Select
    options={dogs}
    value={selectedOption}
    getOptionLabel={(dog) => dog.name}
    getOptionValue={(dog) => dog.id}
    onChange={console.log}
/>
```
will call `console.log` with the selected dog as object, e.g. `{ id: 2, name: 'dog2' }`.

I found this solution in the [advanced docs](https://react-select.com/advanced#replacing-builtins).

**Comment by Lekha30** [comment]
Thanks for that. I tried managing it using parse and format props
