### ISSUE TITLE
[v2] update flow to 0.91.0

### ISSUE THREAD

**Issue by DragorWW** [JedWatson/react-select#3336]
Flow [became stricter](https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8) after the release of version 0.85

After updating Flow in react-select, or my project, we get 58 error,  most problems in src/stateManager.js, other in src/Creatable.js

it also blocks updating projects that use react-select and flow >= 0.85.

![image](https://user-images.githubusercontent.com/1303845/50906170-18112d80-1457-11e9-80c1-b659a4439204.png)
![image](https://user-images.githubusercontent.com/1303845/50906201-2c552a80-1457-11e9-9bee-160a4fa2a25b.png)

Flow is better and stricter, I think it's a good idea to update it.

PS. I will try to make a fix if there are not many problems, and submit a pull request

**Comment by rajzik** [comment]
Is there any workaroud about this issue?

**Comment by TrySound** [comment]
@rajzik Add this package to `[declarations]` section in flowconfig

**Comment by pascalduez** [comment]
@TrySound Did you ever make `[declarations]` work? 
I tried with all the combinations I could thing of, no way.

```
[declarations]
<PROJECT_ROOT>/node_modules/react-select/
<PROJECT_ROOT>/node_modules/react-select/.*
.*/node_modules/react-select/
.*/node_modules/react-select/.*
.*/react-select/
.*/react-select/.*
```

**Comment by TrySound** [comment]
This worked for me. Didn't tried with react-select yet because coworkers already wrote a lot of untyped code.
```
.*/node_modules/react-window/.*
```

**Comment by pascalduez** [comment]
Actually it kinda work.
Without `[declarations]`: `Found 48 errors`
With `[declarations]`: `... 25 more errors (only 50 out of 75 errors displayed)`  

I went with `[untyped]` for now :\

**Comment by rajzik** [comment]
I have tried with `[declarations]`,
there were still errors with: 
`node_modules/react-select/src/Async.js`
`179| export default makeAsyncSelect(manageState(Select));`

only thing that "worker" was `[untyped]` to get rid of every error caused by react-select. 

@pascalduez :+1:

**Comment by DragorWW** [comment]
In my project, I temporarily created [flow file](https://gist.github.com/DragorWW/12d1eabd9eb11c259d12f71602aa28b7) (incomplete version) After merge #3350 I will delete.

**Comment by DragorWW** [comment]
Done because  #3350 merged
