### ISSUE TITLE
Handle enter key press when menu is close

### ISSUE THREAD

**Issue by jitenderchand1** [JedWatson/react-select#3340]
Hi, Very good plugin.

I want to perform some action when user press enter key while menu is closed but with the current version of react-select V2 nothing happen when you press enter key.

I have found many other old `github` issue for the same issue but either they are still open or been closed without been answered.

**Why I want this?**
At the moment I have 4 dropdown field and one search button. To perform search either I have to click the search button using mouse or have to tab through field to get to the search to perform search. I want to perform search whenever I pressed enter key on dropdown field when menu is close.

**Comment by xbojch** [comment]
You could pass the form onSubmit handler as a prop and then call it in an onKeyDown similar to the code below.

In case you can't pass the onSubmit handler as a prop you could trigger a submit event on the form. Perhaps that's a viable workaround for you.

```jsx
<ReactSelect
  ref={ref => this.select = ref}
  onKeyDown={event => {
      if (!this.select.state.menuIsOpen && 'Enter' === event.key) {
        event.preventDefault();
        document.querySelector('#YOUR-FORM-ID').dispatchEvent(new Event('submit'));
      }
  }}
  {...otherProps}
/>
```

**Comment by hugotox** [comment]
At least for the async select the state is always null:

![screen shot 2019-02-08 at 3 54 32 pm](https://user-images.githubusercontent.com/1758062/52512504-ed330a00-2bb9-11e9-9d46-75c3ce21a984.png)

Not sure if this fixes the issue https://github.com/JedWatson/react-select/pull/3411
