### ISSUE TITLE
How to add onClick to the "No option message"?

### ISSUE THREAD

**Issue by Steffi3rd** [JedWatson/react-select#3347]
Hi, 

I would like to allow the user to click on the no option message to do `something()`.
The idea is to replace the label by something like "Add your option", then `onClick` : 
- Execute `something()`
- And better, append the value to list of options.

Is there a way to do that please?

Thanks!

**Comment by Steffi3rd** [comment]
I just found "Creatable".
Maybe it can solve this issue.

**Comment by shipra1101** [comment]
Hi, I am also looking for something similar. Did you get the solution to this issue?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
