### ISSUE TITLE
how to give Select.Creatable an id on which I can change the css of the component (e.g. add a className)

### ISSUE THREAD

**Issue by Stathismi** [JedWatson/react-select#3359]
Below you can see the Select.Creatable element! I am trying to give the whole input component an id , by using id but the id is not linked to the component itself but the inputs of the component. I want to implement-add the below classname ("myFocus) on focus (similar to is-invalid of bootstrap).

 <Select.Creatable
                           allowCreate={true}
                           onInputChange={(inputValue) => this._inputValue = inputValue}
                           options={eventCategories}
                           optionRenderer={this.renderOption}
                           onChange={this.seteventCategories}
                           value ={this.props.eventDetails.eventCategories}
                           valueRenderer ={this.state[curLabelData] ? this.renderValue: this.renderStr }
                           id="Element1"
                           placeholder=" "
                           multi
                         />

.myFocus{
  border-color: #dc3545;
}
.myFocus:focus {
  border-color: #dc3545;
  box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
}

The way i try to add it is:
      document.getElementById("Element1").classList.add("myFocus")

Or is there any other way to check if there is at least one input in the component or not and display a red focus for example?
Thanks

**Comment by seanberrie** [comment]
className - apply a className to the control
classNamePrefix - apply classNames to inner elements with the given prefix

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
