### ISSUE TITLE
[v2] Feature request: Support selection of entire group

### ISSUE THREAD

**Issue by sag1v** [JedWatson/react-select#3364]
I think it is useful (to me it certainly is) to support a selection of an entire group.
That is, if we have a grouped options like [this example from the docs](https://codesandbox.io/s/w698nv1zv5?module=/example.js) then it would be awesome to allow the users to select multiple items with a single select instead of forcing them to select them one by one.

The visualization can be achieved in "user-land" if we wont use the native (nested) grouping  of `react-select` and instead use a `customOption`. 
But the implementation of filtering, like we got with the regular options can get messy.
We will need to filter all nested options of a selected group, as well as filtering a group if all its nested items were selected. This can also be achieved in "user-land" but can get quite messy.

I think `react-select` should support this out of the box. :fire:   
This can be opt-in or by default when using the grouped options.

**Edit**
Not sure if this request should be part of #2750

**Comment by rash2x** [comment]
I agree with @sag1v that this feature should be opt-in. We did some workaround to implement it, but it doesn't work as a native feature. 

The same thing with nested option groups (I suppose it's something like Tree Select). We also implemented it with the current API, but I think it should be opt-in as well.

**Comment by zgallagher08** [comment]
@rash2x are nested options in v3? Issue [2750](https://github.com/JedWatson/react-select/pull/2750) was closed without comment. Your comment above implies that it was implemented.

**Comment by ebonow** [comment]
Greetings,

Supporting entire selection is fairly straight forward from an implementation perspective 
``` JS 
const Group = (props) => {
  const onClick = () => props.selectProps.onChange(props.options);
  return <components.Group {...props} headingProps={{ ...props.headingProps, onClick }} />
};

const MySelect = props => <Select components={{Group}} />
```

[Here is a quick codesandbox example](https://codesandbox.io/s/react-select-selected-group-header-vmigz?file=/src/App.js)

In regards to nested Groups, there is already a [discussion for this](https://github.com/JedWatson/react-select/discussions/4315) while I inquire a bit into why the original PR was closed.

That said, I think it would be fair to close this issue out and so the conversation about nested groups can be had there.

**Comment by pdhruv93** [comment]
@ebonow is it also possible to append to existing selected options when clicked on group header?
