### ISSUE TITLE
Screen reader still reads tabbing instructions when `tabSelectsValue` prop is false

### ISSUE THREAD

**Issue by zkuzmic** [JedWatson/react-select#3367]
React-select still reads the tabbing instruction ("press Tab to select the option and exit the menu") when `tabSelectsValue` is set to `false`.

Example with `tabSelectsValue={false}`
https://codesandbox.io/s/zxvkolx6wp

**Solution:**
Only include that part of the screen reader instructions if `tabSelectsValue` is `true` (default).

**Comment by jayaranigarg** [comment]
@JedWatson : Any updates on this? It is difficult to use this prop as the narrator then misguides the users.

**Comment by jkjustjoshing** [comment]
@jayaranigarg I made an attempt at fixing this issue in the above PR, hope it helps!

**Comment by jayaranigarg** [comment]
@jkjustjoshing : Great....thank you for the PR! Looking forward to see this PR merged.

**Comment by bladey** [comment]
Thanks @jkjustjoshing, we'll review it as soon as we can.

**Comment by mohit181191** [comment]
@bladey Any plans to merge this PR? We are looking forward for this fix.

**Comment by Methuselah96** [comment]
We're hoping to merge and release the attached PR that fixes this as part of 3.2. We don't have an ETA at the moment, but my guess is that it will happen sometime in the next month.
