### ISSUE TITLE
Blurring with Tab key from "No Results Found" does not close dropdown.

### ISSUE THREAD

**Issue by mxdubois** [JedWatson/react-select#337]
Steps to reproduce:
1. Click to focus select box.
2. Begin typing something random like "fooarglebargle" to get "No Results Found"
3. Hit the tab key.

Observed: Dropdown (with the text "No Results Found") is still displayed and the next input in the form is focused.

Expected: Select remains focused and dropdown is hidden as it is when you hit the tab key on an existing option value. The select's initial value should be preserved.

(Great component, overall. Thanks for sharing it!)

**Comment by bruderstein** [comment]
Confirmed. I've got a fix and tests for this - https://github.com/bruderstein/react-select/tree/fix-337

However, the tests are sat behind PR #348 (as in, I need the changes in #348 to be able to merge) - when & if that is merged, I'll push a PR to fix this.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
