### ISSUE TITLE
onOpenMenu triggers even when menu is already opened

### ISSUE THREAD

**Issue by dannyhuly** [JedWatson/react-select#3373]
### Bug report
description:
`onOpenMenu` triggers even when menu is already opened 

expected result:
 `onOpenMenu` should triggers only when menu is opened

test case:
https://codesandbox.io/s/420oq96n4w
* open console
* click Select
* start typing in the input

**Comment by bladey** [comment]
Duplicate of #3335, closing this issue as #3335 has expanded information.
