### ISSUE TITLE
feature : use getDerivedStateFromProps  instead of componentWillReceiveProps

### ISSUE THREAD

**Issue by p2227** [JedWatson/react-select#3374]
hi, I found that there're many unsafe lifecycle in these repo , for example https://github.com/JedWatson/react-select/blob/98c8b2da36873318f2670919f6b66ce3df800eac/src/Async.js#L68

it 's recommend using  static getDerivedStateFromProps instead of componentWillReceiveProps, in order to adjust react 16.7+

**Comment by angshu** [comment]
hi, relating to the above, do you plan to support 16.7+ anytime soon?

**Comment by p2227** [comment]
> hi, relating to the above, do you plan to support 16.7+ anytime soon?

yes

**Comment by JedWatson** [comment]
We've updated the lifecycle methods so you won't get deprecation warnings anymore, and will remove `componentWillReceiveProps` in v4.
