### ISSUE TITLE
defaultMenuIsOpen doesn't trigger onMenuOpen

### ISSUE THREAD

**Issue by lucasveigaf** [JedWatson/react-select#3375]
When setting `defaultMenuIsOpen`, `onMenuOpen` isn't triggered on the initial opening. See: https://codesandbox.io/s/lyzx95oo37

I need this because I do some fetching and calculations based on the opening of the menu. Perhaps this behaviour is as intended, but if so, it should probably be documented.

Workaround: set both `autoFocus` and `openMenuOnFocus` props, which has a similar effect and triggers `onMenuOpen`.

**Comment by lecstor** [comment]
I have a button displaying a value which when clicked should be replaced by select with the menu open.
I expected `defaultMenuIsOpen` to do this for me but it doesn't. Or maybe it partially does bc it then takes 2 clicks on the select to open the menu. Not sure if this is possibly related to use of `menuPortalTarget` somehow.

Regardless, @lucasveigaf's workaround works for this too.

**Comment by akrigline** [comment]
This also affects somehow whether the menuPlacement prop is taken into affect with `defaultMenuIsOpen` set to true.

I had a `menuPlacement` of auto but with the `defaultMenuIsOpen`, it wasn't working. Using the above workaround does work though.

**Comment by codercodingthecode** [comment]
My issue is that I render 2 selectors after depending on a previous selector option.
The intended functionality is to auto open the first of the two new rendered selectors, however, somehow it doesnt work with either of the options above neither with the default menu is open prop.

**Comment by lukebennett88** [comment]
Unfortunately changing this behaviour now would be a breaking change, so if this is still an issue for people, I'd recommend controlling the component yourself.
We will take this into consideration for a future release.
