### ISSUE TITLE
Safari 11 menu doesn't open on value click

### ISSUE THREAD

**Issue by kpanyushin** [JedWatson/react-select#3376]
Is it possible to open menu when clicking on value? I hide the indicator using display: none on this element and everything works fine but in Safari 11

**Comment by andyfurniss4** [comment]
Also having this issue.

**Comment by prayas26** [comment]
facing same issue

**Comment by ebonow** [comment]
Greetings everyone,

I am unable to reproduce this either on a MacBook or on an iPhone Simulator. 

Can someone confirm if this is on iOS or OSX Safari while also confirming that the `openMenuOnClick` is set to true?

**Comment by ebonow** [comment]
In an effort to close out stale issue, I will be closing this. Please feel free to reply if there are any additional questions or concerns and we can reopen this if necessary.
