### ISSUE TITLE
menuPortal X-axis position is incorrect when window is scrolled horizontally.

### ISSUE THREAD

**Issue by matthova** [JedWatson/react-select#3379]
I'll try to dive into the code to see if there's an easy fix, but in the meantime, here's a barebones example forked from the template: https://codesandbox.io/s/l52kkxj5zz

I also verified I'm able to recreate this bug this with create-react-app and with code-sandbox, both using react-select v2.3.0

Love this library! ❤️ Excited to see if we can find a solution.

**Comment by matthova** [comment]
@Rall3n, thanks for the quick reply. I've updated my codesandbox to more accurately show the problem. It seems to still have the original issue described even when the container with the greatest width is targeted.

https://codesandbox.io/s/l52kkxj5zz

**Comment by matthova** [comment]
I've figured out a semi-solution. If you set the menuPortal styles to `position: fixed` then the field displays in the correct location. The only drawback is that the input is fixed, so any scrolling will look a  weird while the menu is open. I added a checkbox to the sandbox above so it can be rendered with either position absolute or fixed.

**Comment by Rall3n** [comment]
I might have found the problem. The MenuComponent is using `getBoundingClientRect` on the select container div to calculate its position, which is not wrong. But the component does not account for the scroll position of the window (by default) for the `left` position of the menu. So moving the scrolling of your site to a container element and setting the `menuPortalTarget` to a wrapper around the container (e.g. body) should solve your issue.

```jsx

<ScrollingContainer>
    <ContainerWithMoreWidth>
        <ContainerOffsettingSelect>
            <Select
                { ... }
                menuPortalTarget={document.body}
            />
        </ContainerOffsettingSelect>
    </ContainerWithMoreWidth>
</ScrollingContainer>
```

Also you should set the `overflow` of your body to `hidden`.

**Comment by matthova** [comment]
I've updated the example per your advice. Thanks for the guidance!
https://codesandbox.io/s/6vrmor1j7w

It appears to have the same issue as if the portal is set to position: fixed, where any scrolling keeps the menu in one place.

**Comment by matthova** [comment]
@Rall3n, this is the solution I ended up going with: https://codesandbox.io/s/43n7z1v374
I implemented my own portal, which tells the child the bounding rectangle of the parent element.

I'm wondering if the library could be modified to have a similar option, but in any case, this solution works for me 👍

**Comment by xoxox911** [comment]
@matthova, thanks for your decision!

**Comment by knegusen** [comment]
I think this works:
```jsx
<Select styles={{ menuPortal: base => ({ ...base, left: base.left + window.scrollX })}} />
```

**Comment by bladey** [comment]
Hi all,

Thanks for your assistance @Rall3n, @matthova, and @knegusen.

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.
