### ISSUE TITLE
undefined `event` in `clearValue()`

### ISSUE THREAD

**Issue by oluckyman** [JedWatson/react-select#338]
Twice hit `escape` when input is focused and you’ll get an error in the console `Uncaught TypeError: Cannot read property 'stopPropagation' of undefined`.  
So you had to pass `event` into `clearValue()` here: https://github.com/JedWatson/react-select/blob/master/src/Select.js#L407-L409
or check if `event` is `undefined` here https://github.com/JedWatson/react-select/blob/master/src/Select.js#L287-L289

**Comment by bruderstein** [comment]
This is fixed in 7e51041e6 (included v0.5.6)

Note that a secondary bug is then introduced (meaning if "clearable=false", you can still press escape to clear the value).  This is then fixed in 240c8a0a, which is not included v0.5.6.

**Comment by oluckyman** [comment]
great! thanks 🙏
