### ISSUE TITLE
React-Select gets slow with 1000++ data

### ISSUE THREAD

**Issue by SamYan** [JedWatson/react-select#3385]
I'm trying to list the cities the component gets very slow.

Test case (**ALREADY FIXED EXAMPLE**):
https://codesandbox.io/s/qly29opky4

**Comment by SamYan** [comment]
Solution: https://github.com/JedWatson/react-select/issues/3128#issuecomment-439207355

```
function Option(props: any) {
    const { onMouseMove, onMouseOver, ...newInnerProps } = props.innerProps

    return (
        <MenuItem
            buttonRef={props.innerRef}
            selected={props.isFocused}
            component="div"
            style={{
                fontWeight: props.isSelected ? 500 : 400,
            }}
            {...newInnerProps}
        >
            {props.children}
        </MenuItem>
    );
}
```

**Comment by ImSirDieALot** [comment]
In the example you provided, I do not see the slowing issue. It's loading up with in 1/10 of a second with all the options. I scrolled down fast too.

**Comment by SamYan** [comment]
> In the example you provided, I do not see the slowing issue. It's loading up with in 1/10 of a second with all the options. I scrolled down fast too.

You are tring already fixed example...

**Comment by ImSirDieALot** [comment]
> > In the example you provided, I do not see the slowing issue. It's loading up with in 1/10 of a second with all the options. I scrolled down fast too.
> 
> You are tring already fixed example...

My bad, I saw the issue was open so tried to check it out.

**Comment by SamYan** [comment]
> > > In the example you provided, I do not see the slowing issue. It's loading up with in 1/10 of a second with all the options. I scrolled down fast too.
> > 
> > 
> > You are tring already fixed example...
> 
> My bad, I saw the issue was open so tried to check it out.

No problem. Thanks for reply!

**Comment by yarindeoh** [comment]
> I'm trying to list the cities the component gets very slow.
> 
> Test case (**ALREADY FIXED EXAMPLE**):
> https://codesandbox.io/s/qly29opky4

This is the exact select I need to implement:) and in your fixed component, the performance is great. Did you do anything else beside the mouse over props in Option ?

**Comment by samyan** [comment]
Hello,No, only mouse over props.Regards.El 30 jun. 2019 10:50, Yarin Dekel <notifications@github.com> escribió:
I'm trying to list the cities the component gets very slow.
Test case (ALREADY FIXED EXAMPLE):
https://codesandbox.io/s/qly29opky4

This is the exact select I need to implement:) and in your fixed component, the performance is great. Did you do anything else beside the mouse over props in Option ?
