### ISSUE TITLE
How to show only results with exact matched?

### ISSUE THREAD

**Issue by Steffi3rd** [JedWatson/react-select#3394]
Hi, 

Actually, when I search `Mi`, ReactSelect shows me these results : 
```
- Microsoft
- Aminata
- Avami
- Miha
```

I would like to display only results started by what I search, so it would be only : 
```
- Microsoft
- Miha
```

Is it possible?

**Comment by amirqasemi74** [comment]
read about 'filterOption' prop;
see http://react-select -> Advanced Tab -> Custom Filter Logic

**Comment by m-adil** [comment]
Thanks @amirqasemi74 for redirecting us to [the right place](https://react-select.com/advanced#custom-filter-logic). 

Keeping that doc in view, all you need is to add `filterOption` property to the `<select/>` component:
```
import Select, { createFilter } from "react-select"

const filterConfig = {matchFrom: 'start'}
<Select
    ....
    filterOption={createFilter(filterConfig)}
    ...
/>
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
