### ISSUE TITLE
MenuList - customize with input element

### ISSUE THREAD

**Issue by lidoravitan** [JedWatson/react-select#3395]
I've tried to customize the MenuList component, well, it works fine. However, when I add an input element, Input behaves unexpectedly, you can't focus or edit or use input element as usual, do you have any idea? why? does it by purpose?

https://codesandbox.io/s/kkw9y8p2zv

**Comment by gwyneplaine** [comment]
Thanks for the issu @lidoravitan, however the sandbox you provided is an unconfigured single select, please provide a sandbox that accurately reflects your issue.

**Comment by lidoravitan** [comment]
Thanks for your response, Sorry I forgot to save the sandbox modifications, attached new link: https://codesandbox.io/s/zqxx0x989x

**Comment by mykhailo-zoomforth** [comment]
I have the same issue. Do you have any updates on this?

**Comment by cutterbl** [comment]
I opened an FR exactly for this type of functionality #3111 .

**Comment by bladey** [comment]
Hello -

This issue appears to be solved in #3111 as per above.

However, if you feel this issue is still relevant and shouldn't be closed, and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
