### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by jfcernel** [JedWatson/react-select#3396]
I'm getting a compile error in the indicators.js file;

 1 | // @flow
> 2 | import React, { type Node } from 'react';
    |                      ^
  3 | import { css, injectGlobal } from 'emotion';
  4 |
  5 | import type { CommonProps, Theme } from '../types';

It says unexpectedToken, expected ", " (2:21)

If I comment out this file it works but it is getting annoying to have to tell the entire team to deal with the issues themselves.

Thank you for your help.

npm says I'm on version 6.4.1

**Comment by barrychapman** [comment]
I have this same problem - how did oyu resolve it?

**Comment by bladey** [comment]
Hi @jfcernel,

I wanted to check in and see if you were still encountering this issue. We're triaging issues at the moment to sustain the project going forward, thanks!

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.
