### ISSUE TITLE
Can't set defaultvalue sufficiently

### ISSUE THREAD

**Issue by johneakin** [JedWatson/react-select#3397]
The only way I can get a default is if I use:
defaultInputValue='0'

however when I do this, and then click the drop down it only shows me the '0'
I have to click a second time before it shows the rest of the options.
Not a great user experience.

I have tried defaultValue and that does't work

**Comment by dehghani-mehdi** [comment]
I think you should paste some code here, so people can help

**Comment by GxDesign** [comment]
Experiencing this as well: 
`            <Select
                className='dropdown-select'
                value={selectedOption}
                defaultValue={options[0]}
                options={options}
>
`
Options render fine, cant set default.

**Comment by Rall3n** [comment]
@johneakin or @GxDesign would you mind recreating your problem with a fork of the following code-sandbox?
https://codesandbox.io/s/k5rvn9z3lv

**Comment by MaxiSantos** [comment]
@GxDesign I got the same problem but after testing with @Rall3n sandbox I realized you have to remove the `value` property in order `defaultValue` to work.

**Comment by smithaitufe** [comment]
Please what is the solution to this issue? I am trying to set defaultValue for the case of multiple select but it is not working.

**Comment by mrinnetmaki** [comment]
@Rall3n I created a fork that shows the problem, https://codesandbox.io/embed/react-codesandboxer-example-irf8o?fontsize=14. On initial load blue is selected, but it's also the only item on the list. Only after selecting it once, manually, you get to see the whole list of items.

**Comment by mrinnetmaki** [comment]
And the somewhat correct way of implementing the feature is in https://codesandbox.io/s/react-codesandboxer-example-sckc3?fontsize=14.
The thing is that for the `value` to work you need the reference to the option, just indicating the value string is not enough.

**Comment by Rall3n** [comment]
@mrinnetmaki you are using the wrong prop. `defaultInputValue` is specifically for the search input. What you need to use is the `defaultValue` prop. I think the same goes for @johneakin

**Comment by bladey** [comment]
Thanks for your assistance @Rall3n!

@mrinnetmaki @johneakin -

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.
