### ISSUE TITLE
Stop text entry in box (as this open keys boards on phones)

### ISSUE THREAD

**Issue by johneakin** [JedWatson/react-select#3398]
Is there a way to just make this dropdown select only?
Otherwise phones think it allows text entry and bring up their keyboard

**Comment by razh** [comment]
Set `isSearchable={false}`.

https://github.com/JedWatson/react-select#props

**Comment by kamilUcreate** [comment]
it does not work. Any help?

**Comment by razh** [comment]
@kamilUcreate Are you using react-select v1 (`searchable={false}`) or v2 (`isSearchable={false}`)?

**Comment by jkjustjoshing** [comment]
This probably isn't the best way to do it, but this should work in combination with the "Popout" example [here](https://react-select.com/advanced):

    <Select
        ...
        styles={{
            control: () => ({ display: 'none' })
        }} 
    />

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
