### ISSUE TITLE
MultiValue is not clickable with more than one Value

### ISSUE THREAD

**Issue by kwskii** [JedWatson/react-select#3399]
Hello,

When customizing the react-select on a multi value select I'm having issues trying to have each value be rendered as a <Chip /> component from https://material-ui.com/api/chip/.

My issue was the fact that I can't use the MultiValueRemove function as the onDelete function.

So with that in mind I gave up and am now just trying to make the Label clicklable so that I can open a modal with information about the clicked value.

I managed to achieve this with a custom object MultiValue but this only worked when I had one selected option, with more than 1 object selected whenever you clicked on either the label or the remove neither the onClick nor the onDelete would fire. (They were simple console.logs).

So if values is [X] clicking on X's label or X's delete will console.log() i.e the handlers fire.
If values are [X, Y] clicking on either X or Y doesn't do anything

Let me know if I can help explaining better or if I'm doing something not supported

**Comment by gwyneplaine** [comment]
@kwskii can you provide us with a [sandbox](https://codesandbox.io/s/new) of your code? 
It'll be easier for us to triage the issue that way.

**Comment by kwskii** [comment]
I managed to fix it. Sorry for the lack of sandbox.

This was due to onMenuClose and onMenuOpen I had a method to resize the component according to the menu size
