### ISSUE TITLE
Creatable Async Multi Select

### ISSUE THREAD

**Issue by The-Code-Monkey** [JedWatson/react-select#3412]
Does the isMulti prop not work with the Creatable Async component or am I doing something wrong?

when my api call brings back `[]` i get a single blank option inside of the menu meaning it will not allow me to create an option

**Comment by sarathantony** [comment]
@JedWatson : i also have this issue. { AsyncCreatable } wouldn't work form me either(maybe i'm using it wrong (i'm new to this)). can you please guide us.

**Comment by Rall3n** [comment]
@The-Code-Monkey @sarathantony It would be really helpful if one of you could provide a code example. It would help finding a solution for your issue.

**Comment by DaniloOliveira28** [comment]
Hi, I am having the same issue.

I am trying to create an async creatable multi select. I added and configured the AsyncCreatableSelect component according with data below.

`    <AsyncCreatableSelect 
      value={tagsState}
      onChange={handleChange}
      isClearable={false}
      isMulti
      isCreatable
      styles={selectStyles}
      menuPortalTarget={portalDom}
      loadOptions={loadOptions}
    />`

When I try to add a selection that does not exist, the component only return the "No options" message and do not allow me to create a new option.

See:
![multiselectasync](https://user-images.githubusercontent.com/7645601/61481849-89361e00-a96f-11e9-835b-31ceadf211ed.gif)

**Comment by akhor93** [comment]
Not sure why @DaniloOliveira28 isn't having any luck. I'm seeing success with:

`<AsyncCreatableSelect
        cacheOptions
        defaultOptions
        isCreatable
        isMulti
        loadOptions={loadOptions}
        formatCreateLabel={userInput => `Add "${userInput}"`}
      />
    );`

**Comment by DaniloOliveira28** [comment]
I have refactored my component and It worked as well. 

I think that was  some kind of user bug. 

Ty @akhor93

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
