### ISSUE TITLE
Doesnt work Creatable

### ISSUE THREAD

**Issue by froii** [JedWatson/react-select#3417]
HI! Thank you a lot for react-select 2 ! Very cool select. But i have one problem/bug with Creatable.
In v2 you change options to get values of key - labelValue and labelKey and if i dont use keys {label and value} in options object i cant add text to  formatCreateLabel or use Creatable ..
Please check - 
https://codesandbox.io/s/rjnojq10wn

I need to use not good way - i changed options for correct work. 
      options={options.map((option) => ({ value:  option[labelValue], label:  option[labelText]}))}  
but should be better way.

![image](https://user-images.githubusercontent.com/20191368/52483339-57e54500-2bbc-11e9-85c9-3654c8948ab7.png)

![image](https://user-images.githubusercontent.com/20191368/52483383-6f243280-2bbc-11e9-935a-9c48db719602.png)

**Comment by Rall3n** [comment]
@froii There is a prop called `getNewOptionData` that creates the object for the new option. The standard implementation uses the pattern `{ label, value }`. In your example you have to overwrite it to use `{ id, name }`.

```jsx
<CreatableSelect
    { ... }
    getNewOptionData={(inputValue, optionLabel) => ({
        id: optionLabel,
        name: inputValue,
        __isNew__: true
    })}
/>
```

**Comment by froii** [comment]
Oh! misunderstand this options, thank you a lot for your answer !

**Comment by froii** [comment]
it doesn't help - the text before value in search field does not show.

![image](https://user-images.githubusercontent.com/20191368/52900076-373f6f80-31fa-11e9-9cf1-dd27e75c3574.png)

i use - 
 getNewOptionData: (inputValue, optionLabel) => ({
      [labelValue]: optionLabel,
      [labelText]: inputValue,
      __isNew__: true
    }),
    getOptionValue: option => option[labelValue],
    getOptionLabel: option => TextField(option[labelText]),

**Comment by Rall3n** [comment]
I think you might have label and value switched in your `getNewOptionData`. Switching it should show the creation message.

**Comment by froii** [comment]
Yes, but problem was with formatCreateLabel . 
I watched this way to create text by formatCreateLabel field. 
https://github.com/JedWatson/react-select/issues/2786
But if i use formatCreateLabel with tags ( like in the example ) and getNewOptionData these hide text before inputValue or show text - no options  . 
But if i use string everithink is okay. but i cant make text bold :    
formatCreateLabel={ inputValue => (
     `Create Tag ${ inputValue }`
) }
For example - https://stackblitz.com/edit/react-jaasiq?file=index.js
and add two variants =
  formatCreateLabel={ inputValue => (
             <p> Create Tag { inputValue }</p>
             // `Create Tag ${ inputValue }`
          ) }

**Comment by Rall3n** [comment]
Your problem in your example is, that you use `option.name` for both value and label, but set `inputValue` in a new option to `option.id` so it cant find the new to select it. Changing `getOptionValue` should suffice to get `formatCreateLabel` to work.

```jsx
<CreateableSelect
    getOptionLabel={option => option.name}
    getOptionValue={option => option.name} // <-- This is the problem
    getOptionValue={option => option.id} // <-- should be
/>
```

**Comment by froii** [comment]
yeah! you are absolutely right!
Thank you a lot for answer.
I didn't check value that get.
Sorry for this
