### ISSUE TITLE
formatGroupLabel doesn't show element when the `options` is empty

### ISSUE THREAD

**Issue by DanZeuss** [JedWatson/react-select#3418]
# Bug
When a `group` element has the `options` empty, it doesn't show the element inside the list.

Take the example below
Example: https://codesandbox.io/s/32zjq1x37m

We have the following groups:
```
export const groupedOptions = [
  {
    label: 'Colours',
    options: [],
  },
  {
    label: 'Flavours',
    options: flavourOptions,
  },
];
```

The element `Colours` should at least appear showing `0` elements, while it doesn't show the element `Colours` as option. 

As we can see, we just get the `Flavours` while (IMHO) we should show the `Colors` and its length of options (in this case, `0`)
![image](https://user-images.githubusercontent.com/24215587/52500488-47859800-2bc5-11e9-86af-d358ee78b5f9.png)

It's very helpful if we want to see a tree and, even a root doesn't contain leafs, it should show the grou/root element

**Comment by c-moss-talk** [comment]
I prefer the current behavior because I'm not showing the count and seeing 'colours' over 'favours` would be visually awkward, but I could see a prop `showEmptyGroupLabels` being useful.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
