### ISSUE TITLE
Warning: flattenChildren(...): Encountered two children with the same key, `.$option-...

### ISSUE THREAD

**Issue by bezreyhan** [JedWatson/react-select#342]
This error gets logged to the console many times over every time a user hovers over the options menu.

![errors](https://cloud.githubusercontent.com/assets/6013763/8917241/c25b9300-3465-11e5-8118-9d24faed2036.png)

**Comment by brianreavis** [comment]
Do you have options that share the same value?

**Comment by bezreyhan** [comment]
I don't. Though, should that be a problem. Would it be better to key the items by index rather than value?

**Comment by brianreavis** [comment]
Mind posting the props you're using?

**Comment by bezreyhan** [comment]
Sorry, your correct I just scanned through it and found some doubles and triples: https://github.com/bezreyhan/countries/blob/master/country_calling_codes.json

**Comment by bezreyhan** [comment]
Should no two items share the same value?

**Comment by bezreyhan** [comment]
Keying the options by index or by label fixes the issue. Is there a reason why we don't do so? If not I can make a PR.

**Comment by edgesoft** [comment]
You can reproduce the same problem in the live demo http://jedwatson.github.io/react-select/ when adding new options to the CUSTOM RENDERING FOR OPTIONS AND VALUES:

**Comment by edravis** [comment]
+1 I will quote @bezreyhan:
> Keying the options by index or by label fixes the issue. Is there a reason why we don't do so? If not I can make a PR.

So, what are we waiting for?

**Comment by MorleyB** [comment]
+1

**Comment by walkerrandolphsmith** [comment]
Why is this issue closed? I still experience the symptoms of this issue. @bezreyhan I would love to help if you want to tackle this together. I don't have enough understanding of the problem or the described solution to feel comfortable doing it myself.

**Comment by akshaysinghi** [comment]
+1

**Comment by andy-j-d** [comment]
I've run into this issue with a country dropdown - multiple labels for one value, for example United Kingdom, England and Great Britain are all the same value.

My solution was to add an ID (using uniqueId from lodash) following the value and remove it on change.

```const countryOptions = countries.map(({ label, value }) => ({ label, value: `${value}-${uniqueId()}` }));```

`const onCountryChange = (value) => country.onChange(value ? value.split('-')[0] : '');`

`<Select options={countryOptions} {...country} onChange={onCountryChange} />`
