### ISSUE TITLE
menuPlacement="auto" issue

### ISSUE THREAD

**Issue by dana2208** [JedWatson/react-select#3421]
When opening the react-select with menuPlacement="auto" it opens it the first time down although there is not enough space and only afterwards it will open it up.
When debugging I see that in getMenuPlacement(_ref) it go through:
	// 1: the menu will fit, do nothing
      	if (viewSpaceBelow >= menuHeight) {
        	return { placement: 'bottom', maxHeight: maxHeight };
      	}
because the menuHeight there contains only the first element at the beginning therefore menuHeight is only 50px
But the second time it already knows that menuHeight is 150px and therefore it goes through:
	if (placement === 'auto' || isFixedPosition) {
        	// may need to be constrained after flipping
        	var _constrainedHeight = maxHeight;
        	var spaceAbove = isFixedPosition ? viewSpaceAbove : scrollSpaceAbove;
	
        	if (spaceAbove >= minHeight) {
          	_constrainedHeight = Math.min(spaceAbove - marginBottom - spacing.controlHeight, maxHeight);
        	}
	
        	return { placement: 'top', maxHeight: _constrainedHeight };
      	}
So the first time, and I don't know why, it calculates where it should open it when it has only the first element on the menu and therefore it opens down and then all the elements appear down and we can't see them.
Only the second time it calculates right becuase he already knows it has 3 elements to show (150px).

Can you tell me if it is a bug or if you have to fix this?

Thank you

**Comment by PepRoll** [comment]
I have this too.

**Comment by dana2208** [comment]
The last version of the react-select (2.4.1) fixed this so I am closing the bug.
Thanks

**Comment by hasakilol** [comment]
Seems the issue is happening again?

**Comment by Methuselah96** [comment]
@hasakilol Can you provide a CodeSandbox and a description of the bug you experiencing?

**Comment by hasakilol** [comment]
Refer to: https://github.com/JedWatson/react-select/issues/4493
