### ISSUE TITLE
react-select css not working on Gatsby Static Build

### ISSUE THREAD

**Issue by nsisodiya** [JedWatson/react-select#3422]
I have prepared a demo git repo - https://github.com/nsisodiya/react-select-gatsby-bug

Gatsby is static website creator. Static build don't contain the CSS and hence the first load experience is very bad. 

Here is the screenshot when JavaScript is disabled - (Rending only Static Content)

![image](https://user-images.githubusercontent.com/333455/52616622-28398400-2ebf-11e9-8c23-bb8ac73594f2.png)

Here is the expected content
![image](https://user-images.githubusercontent.com/333455/52616656-4606e900-2ebf-11e9-88f3-e8ac64a618a3.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
