### ISSUE TITLE
Not getting style

### ISSUE THREAD

**Issue by aakhan89** [JedWatson/react-select#3429]
React select not getting style...!

`import Select from 'react-select';

const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
]
return (
          <Select options={options} />
`

![image](https://user-images.githubusercontent.com/38126236/52864156-5fc45c80-315b-11e9-894b-2a1893f5ecbd.png)

**Comment by gwyneplaine** [comment]
@aakhan89 I can't get a good understanding of the problem from this issue. 
Please add a code-sandbox reproduction and a more descriptive summary of the issue you're facing.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
