### ISSUE TITLE
Pass a custom props to the native select

### ISSUE THREAD

**Issue by francocorreasosa** [JedWatson/react-select#3430]
I need to pass an automation attribute (`[data-something='select']`) to the native select component so I can query the select from tests and I can't find the way to do so. Tried with `inputProps`, `selectProps` and `commonProps`. None of them seem to work. 

I'll have no choice than passing the entire Select element to `components` just for a testing flag.

**Comment by cutterbl** [comment]
'Native select'? I'm not sure I get what you're asking/trying to do. Exactly what is it you're trying to accomplish?

**Comment by francocorreasosa** [comment]
I thought `react-select` used an hidden `<select>` element somewhere in the structure. But that does not seem to be the case.

**Comment by IanVS** [comment]
Hi, should this be closed, then?

**Comment by vitorreis** [comment]
@francocorreasosa you replace the The Option component as described in the doc and your test automation attributes/selector in the Custom option no? 
Reference: https://react-select.com/components#replacing-components

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
