### ISSUE TITLE
Still doesn't work on mobile

### ISSUE THREAD

**Issue by uyouthe** [JedWatson/react-select#3431]
I tried that `optionClassName="needsclick"` thing but it seems like it doesn't actually set the class name. 

Doesn't work on mac os chrome in touch mode and on iphone (Safari)

**Comment by uyouthe** [comment]
I tried `classNamePrefix="needsclick "`, so menu actually received the needsclick classname, just as all the other elements, but it still doesn't work

**Comment by uyouthe** [comment]
As a temporary solution, you may use this:
```
npm remove --save react-select
npm install --save react-select@2.0.0-beta.7
```

**Comment by gwyneplaine** [comment]
Hi @uyouthe, could you provide us with more details about your usecase? 
classNamePrefix appends BEM modifiers to the specified value, i.e. (needsclick__menu).

The fact that you mentioned it doesn't work on mac os chrome in touch mode / in iphone; leads me to think that you've tried this functionality and it works on desktop. 

If possible please provide a codesandbox reproduction of your issue as well, it'll give us a better understanding of your usecase and how to best resolve it 👍

**Comment by uyouthe** [comment]
https://react-select.com/home

None of them work on mobile and all of them work with mouse :)

**Comment by gwyneplaine** [comment]
@uyouthe, turns out this is a regression from a massive flow overhaul in 2.4.0.
Fix for this in the following PR, will be released as a patch shortly. 👍 
https://github.com/JedWatson/react-select/pull/3432

**Comment by gwyneplaine** [comment]
This is now shipped as part of 2.4.1, @uyouthe can you please validate that it resolves your issue? If yes, we can close this thread :)

**Comment by uyouthe** [comment]
Works perfectly.

**Comment by nishmeht7** [comment]
the drop down is still not working on mobile for me. I'm using v 3.0.4 and while typing in the input box from safari on my phone no drop down with options is rendered, while it is on my desktop. Any idea how to debug this?

**Comment by phil-andrews** [comment]
Same issue using 3.0.4

**Comment by phil-andrews** [comment]
Actually, mine was a redux-form issue. See [#2692](https://github.com/JedWatson/react-select/issues/2692) for solution if you're using redux-form.
