### ISSUE TITLE
AsyncCreatable remove the input value when value is created

### ISSUE THREAD

**Issue by sarzijan** [JedWatson/react-select#3433]
Hello,

I am trying to have an editable select, when a user creates a new option in asyncCreatable, I was able to achieve that with onInputChange, but when I select the create the option, the value is emptied, even if it is still in state. When click outside the select, the value is there and I can then continue with typing of the value. The value remains there also if I just click outside the select (no create option)

code: https://codesandbox.io/s/54vqnlxomx

do I need to use some props to have the input without clean?

Thanks

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
