### ISSUE TITLE
[Bug] - Enter doesn't select option in mobile

### ISSUE THREAD

**Issue by Bryze** [JedWatson/react-select#3434]
#Are you reporting a bug or runtime error?
Bug

This is reproducible in the example given on the react select page as well.

When we press enter in the mobile phone while typing in select, it doesn't select the first option.
This works fine on desktop but doesn't work at all in mobile

Reproducible in all select variants that are listed in the example page

Reference page - https://react-select.com/

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
