### ISSUE TITLE
React-select V1 - CSS issue related to onBlur event

### ISSUE THREAD

**Issue by phamquocduy** [JedWatson/react-select#3439]
Thanks for creating react-select!

Actually we are using react-select V1 1.2.1 and I have found very weird issue, maybe related to onBlur event but I am not sure. I have made a video about this for your better analyzing [test-video](https://streamable.com/ttr3b)

Steps to reproduce:

1. let's have 2 comboboxs very close to each other, choose something from the first one then scroll down to the last item, **do not choose anything yet**
2. click outside of the app (in video I have clicked to Excel)
3. click back to the **second** combobox
4. the panel of the **first** combobox is re-showing and disappearing immediately

**Comment by bladey** [comment]
Hello @phamquocduy,

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
