### ISSUE TITLE
Unexpected behaviour when type query in Russian

### ISSUE THREAD

**Issue by sergeylaptev** [JedWatson/react-select#345]
Hello, when I type some queries in Russian and use "б" letter, input always interrupt. The root of evil at this line https://github.com/JedWatson/react-select/blob/master/src/Select.js#L427. On a russian keyboard we have "б" letter, whereas in english it's ",". We can fix this, by checking charCode instead of key number.

**Comment by bruderstein** [comment]
Unfortunately charCode isn't set for keyDown events, only keyPress events. 
Please excuse my lack of knowledge about Russian, but I presume you do have a comma key on your keyboard (or at least, can enter one somehow), can you enter it in http://www.w3.org/2002/09/tests/keys.html and post the results here?

Keyboard events in browsers are broken, and i18n just makes it worse, so I'm not sure there's a good solution to this, but we can take a look :)

**Comment by webvit** [comment]
**Character     "б"**
Keyboard Event Properties:
<pre>
Data     keydown     keypress     keyup
keyCode     188     1073     188
charCode     —     1073     —
</pre>

**Comment by bruderstein** [comment]
Thanks for posting.  I meant can you post what happens when you press your "comma" key?

**Comment by webvit** [comment]
"comma [б]" key works as "enter" key, adds tags in multi mode
and delimiter option does not override "comma" to another symbol

**Comment by bruderstein** [comment]
Yes, but I need to know what http://www.w3.org/2002/09/tests/keys.html says, when you press your comma key, not your б key, so that we can work out how we can decide what the user pressed.

б is simply being treated as comma, because it has the same keycode.  On keyPress, we see the character, and I fear we may have to wait for keyPress before acting on ','.  However, I'd like to see what the w3 link above says when you press your version of your comma.  

Many thanks for assisting!

**Comment by webvit** [comment]
I understood,

**Firefox, Mac OS:**
<pre>
Data	keydown	keypress	keyup
keyCode   188 	0 	188
charCode   —   44   —
Character 	,
</pre>

**Chrome, Mac OS:**
<pre>
Data	keydown keypress keyup
keyCode   188	44	188
charCode	—  44	  —
Character	,
</pre>

**Safari:**
<pre>
Data	keydown	keypress	keyup
keyCode	  188	44	188
charCode	—	 44	—
Character	,
</pre>

**Comment by bruderstein** [comment]
ok, great, thanks. That was kinda what I was afraid of. I'll have a bit of a play and see if I can come up with a solution.

**Comment by alisag** [comment]
same problem with hebrew...

**Comment by Dicondur** [comment]
Hi were you able to find a solution to this?

**Comment by evgenymarkov** [comment]
We are faced with the same problem

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
