### ISSUE TITLE
Async select calls styles methods before async callback is called

### ISSUE THREAD

**Issue by op1ekun** [JedWatson/react-select#3456]
Version: 2.1.0

Use case:
In my project we use `react-select` in an electron window. That means we have a limited space for the options menu. Because of that we have to dynamically adjust its max height.
(Just aside note. We need to do the similar thing for the menu placement, as the options are dynamically loaded, and we can only asses the position when the menu is fully loaded).

What happens:
What happens is when `onLoading` method is called (the menu is still loading) I see the component styles prop methods firing before the async callback is called. This result is incorrect measurements as the menu is not ready yet. To make things worse no styles methods are called when the callback is eventually called. This flow works fine for synchronous Select as all options are available from the start, but fails for the Async.

What's expected:
All the styles prop methods should happen only after the async callback is called.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
