### ISSUE TITLE
custom MenuList with the Input component

### ISSUE THREAD

**Issue by dav-sap** [JedWatson/react-select#3458]
Tried to move the input component under the MenuList component because I don't want the search to overlap with the selected values, but I seem to get errors. Is there a way to do it?

https://codesandbox.io/s/9209v79o7w

Thanks..

**Comment by cutterbl** [comment]
I may be wrong, but I think you're trying to do what I requested in #3111 .

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
