### ISSUE TITLE
Scroll into view issue even when menuShouldScrollIntoView=false

### ISSUE THREAD

**Issue by torkelo** [JedWatson/react-select#3459]
When the menu is placed inside a scrollable div a bit down on the page the menu always triggers a scroll to bottom of this div even when menuShouldScrollIntoView=false. This is really a big issue as it scrolls the parent container so much so the react select input does not become visible.

There is a simple fix for this issue in PR #3262

**Comment by freewind** [comment]
Have exactly the same problem, hope it gets merged

**Comment by MichaelKostin** [comment]
I have the same issue. I also checked solution in PR. It works well.
