### ISSUE TITLE
Weird behavior when data contains `options` array

### ISSUE THREAD

**Issue by efstathiosntonas** [JedWatson/react-select#3462]
When data contains `options` property then the dropdown gets messy.

Here's an example, rename `options` property in `options` array to something else and it will work fine.

https://stackblitz.com/edit/react-qcbbw4?file=index.js

**Comment by Rall3n** [comment]
@efstathiosntonas It´s because `options` is a keyword that changes an option to an option group.

Type from documents:
```ts
type GroupType = {
  [string]: any, // group label
  options: OptionsType,
}
```

[Here is the line in the source code](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L1289) where its identified.

**Comment by efstathiosntonas** [comment]
Thanks for pointing it out, `options` is way too common word to be requested by the source code, it needs to be either a prop like `getOptionGroup` or change the `if` statement from to `item.options` to ex `item.optionsGroup`.

**Comment by Rall3n** [comment]
It serves continuity to use the same word for setting the options on the select to set the options for and identify the option group.

But if @gwyneplaine would not mind I can propose a PR for a `getGroupOptions` prop.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
