### ISSUE TITLE
Set label "All items" in select when all items are selected

### ISSUE THREAD

**Issue by jechazelle** [JedWatson/react-select#3463]
Hi, I would like to know how can I set a simple label "All items" in select when all items are selected ?

I searched in the options but I didn't found https://react-select.com/props

Thank you !

**Comment by JandersonConstantino** [comment]
Hi, it helps you?

```JSX
import React, { Component } from 'react'
import Select from 'react-select'

const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
]

class App extends Component {
  state = {
    selectedOption: null,
    text: 'Select items',
  }

  handleChange = (selectedOption) => {
    const allSelected = selectedOption.length === options.length
    const text = allSelected ? 'All items selected' : 'Select items'

    this.setState({
      selectedOption,
      text,
    })
  }

  render = () => {
    const { selectedOption } = this.state

    return (
      <>
        <label>{this.state.text}</label>
        <Select isMulti
          value={selectedOption}
          onChange={this.handleChange}
          options={options}
        />
      </>
    )
  }
}

export default App
```

**Comment by Rall3n** [comment]
@jechazelle [This issue](https://github.com/JedWatson/react-select/issues/2790#issuecomment-460636017) asked for something very similar to your request.
My solution there should be sufficent to fulfill what you ask for. You just have to change up the content of `ValueContainer`:

```jsx
const ValueContainer = ({ children, getValue, ...props }) => {
  var valueLength = getValue().length;
  var optionsLength = props.selectProps.options.length;

  // Check if values are equal to options and display `All` instead of number.
  var valueLength = optionsLength === valueLength ? "All" : valueLength;

  return (
    <components.ValueContainer {...props}>
      {!props.selectProps.inputValue &&
        `${valueLength} Item${valueLength != 1 ? "s" : ""} selected`}
      {React.Children.map(children, child => {
        return child.type === components.Input ? child : null;
      })}
    </components.ValueContainer>
  );
};
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
