### ISSUE TITLE
Feature Request: Slack-like keyword (boolean) search

### ISSUE THREAD

**Issue by daino3** [JedWatson/react-select#3464]
Hello,

First, thanks so much for this library - it's awesome.

I don't know if my request is currently possible with some already-provided tools/props, but I love the way slack handles keyword-based search. Any documentation/resources available to home-roll this feature? If not, is there potential to be included in v2? 

## screenshot
![screen shot 2019-03-05 at 10 05 47 am](https://user-images.githubusercontent.com/3923922/53819090-da002980-3f2e-11e9-8e37-c33ca7df1396.png)

I imagine this would be easy to do with a combination of `multi=true` and adding a single array prop, called "keywords". Something like:

```javascript
      <Select
            multi={true}
            keywords=['from', 'to', 'in']
      />
```

Then, if the component was `Async` the url params would encoded like: `?from=dain&in=general`.

**Comment by mike1808** [comment]
@daino3 what you are looking for is called Input field with Autocomplete. You can achieve it with react-select, but you will hack it a lot.
For now, I'll suggest to have a look at [CreatableSelect](https://react-select.com/creatable) (look at _Multi-select text input_, maybe that's enough for you).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
