### ISSUE TITLE
Rounded corners of Menu cut off by Option

### ISSUE THREAD

**Issue by c-moss-talk** [JedWatson/react-select#3465]
Reporting a BUG

Rounded corners of the `Menu` component are cut off by the `Option` component

<img width="32" alt="screen shot 2019-03-06 at 11 38 47 am" src="https://user-images.githubusercontent.com/40439344/53897575-6e888b80-4004-11e9-841d-3a620e51a647.png">

FIX: add `{ overflow: 'hidden' }` to `Menu` component 
<img width="39" alt="screen shot 2019-03-06 at 11 28 24 am" src="https://user-images.githubusercontent.com/40439344/53897579-70eae580-4004-11e9-9fba-b8020b62d8ef.png">

https://codesandbox.io/s/ly12l6yxxl

I can open a PR to add this to the default Menu styles--any concerns about how this impacts all possible renderings of the Menu?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
