### ISSUE TITLE
How to make handle action for disable option in react-select?

### ISSUE THREAD

**Issue by alembikovm** [JedWatson/react-select#3469]
I want to make custom event and dispatch him, when user click on disabled option in react-select dropdown. But any events dont work in this case, because input is disabled. Any ideas how to make this? Maybe i can wrap option in div, if this option disabled?

`
<Select
  value={this.state.cityOptions}
  onChange={this.handleChange}
  options={this.state.cityList}
  styles={customStyles}
  placeholder="City"
  name="cityOptions"
  isSearchable={false}
  isOptionDisabled={(option) => option.disabled}
/>
`

**Comment by pavog** [comment]
Maybe the formatOptionLabel function can help you. See [documentation](https://react-select.com/props) how to use it. You could try to wrap your returned option with a <div> and use a custom css class for disabled options (color: gray, cursor: default, ...).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
