### ISSUE TITLE
InnerRef is undefined

### ISSUE THREAD

**Issue by VincentLanglet** [JedWatson/react-select#3470]
Material UI recommend this way to use react-select
https://material-ui.com/demos/autocomplete/#react-select

In this example, there is this code
```
function Option(props) {
  return (
    <MenuItem
      buttonRef={props.innerRef}
      selected={props.isFocused}
      component="div"
      style={{
        fontWeight: props.isSelected ? 500 : 400,
      }}
      {...props.innerProps}
    >
      {props.children}
    </MenuItem>
  );
}
```

But the props.innerRef is undefined, so this props seems useless.
Is there something wrong with innerRef or it's an error with this example ?
I know nothing about ref/innerRef/buttonRef so I don't know what's for...

**Comment by Rall3n** [comment]
@VincentLanglet `innerRef` on `Option` component is only set if the option is highlighted by hover or keyboard selection. It is **not** useless in the context of react-select.

See the following line from the source code: https://github.com/JedWatson/react-select/blob/770ba08c6fcaba5190b0df9dfd4e2da98a2fef46/src/Select.js#L1643

**Comment by VincentLanglet** [comment]
@Rall3n Indeed, I missed that ! Thanks.

It's probably a silly question, but what's the impact of not passing `innerRef` ? I don't see differences.

**Comment by Rall3n** [comment]
For the component that receives the ref? None. For `react-select`? I can´t see any at the moment.

**Comment by VincentLanglet** [comment]
Thanks you
