### ISSUE TITLE
Unable to keep Menu open using onMouseOver with openMenuOnFocus={ true }

### ISSUE THREAD

**Issue by Quirksmode** [JedWatson/react-select#3474]
Hi, 

I need to open the React Select on Hover, which I have managed to get working by assigning a ref to the React Select component and attaching onMouseOver to an outer div container which forces the React Select to focus(). I also have an onMouseOut which forces the React Select to lose focus(). 

The issue I have is that onMouseOut is triggering the moment I try to interact with the menu. It seems to lose focus the moment I hover over any element within the menu, this causes it to open and close rapidly. If I apply pointer-events: none to the menu and it's options then it remains open, though obviously now I am unable to actually interact with it. 

How can interact with the menu without losing focus or triggering the onMouseOut?

My React Select code

```
<div
     className="navWorkspace"
     onMouseOver={ this.onMouseOver }
     onMouseOut={ this.onMouseOut }
>
    <Select
        ref={ el => this.navWorkspaceSelect = el }
        closeMenuOnSelect={ false }
        components={ {
          DropdownIndicator,
          Option,
          SingleValue
        } }
        onChange={ this.changeSelect }
        value={ workspaceSelect }
        options={ workspaceSelectOptions }
        isSearchable={ false }
        openMenuOnFocus={ true }
    />
</div>


onMouseOver() {
    this.navWorkspaceSelect.focus();
  }

  onMouseOut() {
    this.navWorkspaceSelect.blur();
  }
````

**Comment by LiorAgnin** [comment]
Having the same issue.
Did you solved it out?
@Quirksmode

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
