### ISSUE TITLE
Cascading Selects MultiValue not getting cleared

### ISSUE THREAD

**Issue by gitgaatachal** [JedWatson/react-select#3475]
### @JedWatson - First of all, thank you for creating such a fantastic library with so much of flexibility

# Not sure if this really is an issue

Source Code - https://codesandbox.io/s/l98n1o6lq7

I am creating a cascading kind of layout where I have two Select components for Roles and Users, the functionality I want is working fantastic except a use case where upon clearing/removing a role or clearing all roles, the Users Select component is not clearing the MultiValue items however the dataset is being cleared properly.

Please guide me as to how to achieve the said functionality, may be I am missing something or probably some kind of issue.

**Comment by gitgaatachal** [comment]
## VOILA

After spending a complete day, I have been able to workout a solution for the issue by using the value prop.

The more I am using it, the more I am getting into love with it 👍 Thanks @JedWatson 

Here is the solution :- https://codesandbox.io/s/l446vwz3ll

**Comment by pherm** [comment]
Hi guys, I have a issue like this. Can you explain my thoughts about how react select works with Cascading Selects? thank you ;)) Ps. I attach my code: https://codesandbox.io/s/new-react-select-forked-6yib1?file=/src/DATA_SHOPS.js
