### ISSUE TITLE
Unexpected end of JSON input 

### ISSUE THREAD

**Issue by erwinagpasa** [JedWatson/react-select#3476]
➜  viperjs git:(master) npm add react-select     
npm ERR! Unexpected end of JSON input while parsing near '...stylis/-/stylis-3.2.1'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbookpro/.npm/_logs/2019-03-14T05_46_53_806Z-debug.log

**Comment by Rall3n** [comment]
@erwinagpasa Would you mind submitting your `package.json` and the log of the npm command?

Also does this also happen in a new project? I could not reproduce your error.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
