### ISSUE TITLE
react-select not working in build

### ISSUE THREAD

**Issue by NIMISHAMORADIYA** [JedWatson/react-select#3477]
i am facing this error at build time.

when creating a build of react project react-select dropdown is not working, and we have also added some design(css) to react-select dropdown ..

Also I want to display error message using redux-form validation.

my code like this..

`  MaterialDropdown = ({ input, meta ,options}) => {
      
        return (<div className="react-select"><div className="react-select">
            <Select
                {...input}
                onBlur={() => input.onBlur(input.value)}
                placeholder={this.state.defaultval}
                name="material"
                options={this.GetMedium()}
               />
            {   
                this.renderError(meta)
            }
        </div>
}
.........inside reduxform....................
 <div className="form-group fields">
                         
                                                        <Field
                                                            id="material"
                                                            name="material"
                                                            component={this.MaterialDropdown}
                                                        />
                                            </div>`
#react-select #react-redux #react #reduc-form #redux

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
