### ISSUE TITLE
custom icon for each option

### ISSUE THREAD

**Issue by glapsable** [JedWatson/react-select#3480]
Hello I trying to make custom icon for any of option.
http://prntscr.com/n0h6nk

maybe is there possibility to add third key in options array? Or any other possibility?
```
const statusOptions = [
    { value: 'notStarted', label: 'Nierozpoczęte', icon: 'someIcon' },
    { value: 'started', label: 'Rozpoczęte', icon: 'someIcon' }
];
```
I need same effect as in home libraby homepage, but my icons will be svg, or jpeg, or png
https://react-select.com/home

pic for view => http://prntscr.com/n0u2p2

Thanks!

**Comment by mohsinhere** [comment]
Hi,

Were you able to achieve it?

Thanks!

**Comment by glapsable** [comment]
Hello,
Yes, i made it:

You need to make custom component. I found solution in docs. My solution below:

```
const customSingleValue = ({ data }) => (
    <div className="input-select">
        <div className="input-select__single-value">
            { data.icon && <span className="input-select__icon">{ data.icon }</span> }
            <span>{ data.label }</span>
        </div>
    </div>
);
```
and then: 
```
        <Select
            defaultValue={ options[0] }
            options={ options }
            styles={ selectCustomStyles }
            onChange={ changeSelectHandler }
            components={ {SingleValue: customSingleValue } }
        />
```

**Comment by mohsinhere** [comment]
Thanks mate! 👍

**Comment by niteshgrg** [comment]
for me this didn't work @glapsable can you also supply what customStyles did you use.

**Comment by dgwyer** [comment]
I'd be interested in this too. Any chance of seeing a working example?

**Comment by cobyrne09** [comment]
@niteshgrg @dgwyer https://codesandbox.io/s/friendly-field-y3u33. Maybe some of the confusion here is that the methods to get an icon to show up in the input versus the dropdown are different? This example, and the code above, are for getting an icon (or any html) to show up in the input.

**Comment by lossen** [comment]
Hello @glapsable 
Could you please share a working example?

**Comment by ozgrozer** [comment]
If you want to show custom icons both in options and selected value area you can use something like this.

```jsx
import Select, { components } from 'react-select'

const CustomSelectOption = props => (
  const { Option } = components
  <Option {...props}>
    <i className={`icon icon-${props.data.icon}`} />
    {props.data.label}
  </Option>
)

const CustomSelectValue = props => (
  <div>
    <i className={`icon icon-${props.data.icon}`} />
    {props.data.label}
  </div>
)

const options = [
  { value: 'item1', label: 'Item 1', icon: 'bar' },
  { value: 'item2', label: 'Item 2', icon: 'folder' }
]

<Select
  {...}
  options={options}
  components={{ Option: CustomSelectOption, SingleValue: CustomSelectValue }}
/>
```

**Comment by sebastianpaz** [comment]
Thanks mate @ozgrozer works like a charm!!!!

**Comment by AmRonak** [comment]
@ozgrozer  why react-select is adding extra div before singleValue?

**Comment by kirtirajsinh** [comment]
> If you want to show custom icons both in options and selected value area you can use something like this.
> 
> ```js
> import Select, { components } from 'react-select'
> 
> const { Option } = components
> const CustomSelectOption = props => (
>   <Option {...props}>
>     <i className={`icon icon-${props.data.icon}`} />
>     {props.data.label}
>   </Option>
> )
> 
> const CustomSelectValue = props => (
>   <div>
>     <i className={`icon icon-${props.data.icon}`} />
>     {props.data.label}
>   </div>
> )
> 
> const options = [
>   { value: 'item1', label: 'Item 1', icon: 'bar' },
>   { value: 'item2', label: 'Item 2', icon: 'folder' }
> ]
> 
> <Select
>   {...}
>   options={options}
>   components={{ Option: CustomSelectOption, SingleValue: CustomSelectValue }}
> />
> ```

How to do the same if I want to Pass the response coming from the API and want to map it as an option?

**Comment by tamsay** [comment]
> If you want to show custom icons both in options and selected value area you can use something like this.
> 
> ```js
> import Select, { components } from 'react-select'
> 
> const { Option } = components
> const CustomSelectOption = props => (
>   <Option {...props}>
>     <i className={`icon icon-${props.data.icon}`} />
>     {props.data.label}
>   </Option>
> )
> 
> const CustomSelectValue = props => (
>   <div>
>     <i className={`icon icon-${props.data.icon}`} />
>     {props.data.label}
>   </div>
> )
> 
> const options = [
>   { value: 'item1', label: 'Item 1', icon: 'bar' },
>   { value: 'item2', label: 'Item 2', icon: 'folder' }
> ]
> 
> <Select
>   {...}
>   options={options}
>   components={{ Option: CustomSelectOption, SingleValue: CustomSelectValue }}
> />
> ```

still saving lives in 2024. @ozgrozer thanks a million
