### ISSUE TITLE
Styling borders (among others) without using !important;

### ISSUE THREAD

**Issue by Phoenixton** [JedWatson/react-select#3481]
Hey there, thanks for the great component! 

I believe the issue has been [raised before](https://github.com/JedWatson/react-select/issues/2706), but I'm currently trying to style my react-select component and I'm hitting a wall. I'm using className for a bunch of reasons and without using !important; everywhere I am unable to modify the border styling of the component.

I am following the naming conventions described [here](https://react-select.com/styles#using-classnames) both for the className and the classNamePrefix and I'm trying to disable the border-radius so
 
```
.react-select__control {
  border-radius: 0px;
}
```

which should work but is getting overriden by a class (.css-vj8t7z) passed by react-select which appears to give its basic styling to the control element. Is there any way to disable that class? 

Obviously 

 
```
.react-select__control {
  border-radius: 0px !important;
}
```

works but it is not an adequate solution imo. Am I doing something incorrectly here or is this something one could contribute to?

**Comment by MrJadaml** [comment]
@Phoenixton I had run into the same issues. My first suggestion would be not to use the classNames approach but their encouraged styles object/emotion API.

Due to code styles constraints I had to go with the classNames and ran into similar issues. What you will likely need to do is drive for greater specificity in order to overwrite react-select's default styles.

Ours look something like this...

```
.select {
  margin: 10px;

  .react-select {
    &__control {
      border: 0;
      border-radius: 0;
    }

    &__indicator-separator {
      display: none;
    }

    &__menu {
      border-radius: 0;
      position: absolute;
      width: 100%;
      z-index: 100;
    }
```

```
import React from 'react';
import ReactSelect from 'react-select';
import './select.scss';

export const Select = ({ options, ...rest }) => (
  <div className="select">
    <ReactSelect
      className="react-select"
      classNamePrefix="react-select"
      options={options}
      {...rest}
    />
  </div>
);

export default Select;
```

I am still running into a few issues around `:focus` states because sadly react-select appears to have set `!important` on some of their default styles, tisk-tisk... 😞

**Comment by Phoenixton** [comment]
Thanks a lot for your answer, that's indeed what I ended up going for and what I'll keep going to use in the near future. It would be nice, as you mentioned, if we could have the guarantee that no styling had an `!important` attached to it. Thanks again!

**Comment by closingin** [comment]
> Due to code styles constraints I had to go with the classNames and ran into similar issues. What you will likely need to do is drive for greater specificity in order to overwrite react-select's default styles.

I do agree with this answer (and I implemented it this way too), but it hurts to have to do this as it completely makes the BEM classes useless. :confused: 

I don't think there's any other valid solution yet though.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
