### ISSUE TITLE
Seems the 'name' does not work, or the behavior is not expected 

### ISSUE THREAD

**Issue by rchancey** [JedWatson/react-select#3482]
I was expecting to have a label on the select if I sent the name, even a label.. but seems not the case. Is there a way to have the Select show a name or label? I can always wrap it but seems this would be built in?

**Comment by Rall3n** [comment]
@rchancey From the docs:
>__name__ `string`
Name of the HTML Input (optional - without this, no input will be rendered)

_Name_ is not label. _Name_ is the name which represents the value in the form data on submit.

If you want a label, use standard html behaviour: render a `<label>` element before the select and that should be it. If you want to focus on the select with the label, use `inputId` prop on the select to set an ID for the search input (which also handles focus) and set the same value for the `htmlFor` prop on the label.

```jsx
<label htmlFor="selectId">My cool input</label>
<Select
    { ... }
    inputId="selectId"
/>
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
