### ISSUE TITLE
Strange behaviour in Select defaultValue

### ISSUE THREAD

**Issue by norayr93** [JedWatson/react-select#3483]
Hi , i am trying solve a problem, which is related to defaultValue's strange behaviour.
I have 2 select components which are handled by single Select component. When i change the value of first component , the props changes , but the second components defaultValue doesn't change anyway.
```
const {value, options, className, handleOnChange, title, shouldBeDisabled, type} = props;
console.log(options, 'options');
console.log(options[0], 'defaultValue');

<Select
      className={className}
      classNamePrefix={`segment-builder-${type}`}
      title={title}
      defaultValue={options[0]}
      disabled={shouldBeDisabled}
      onChange={e => handleOnChange(e.value)}
      options={options} />
```
**Here are snapshots of my console.
This is the initial state of my component.**
![Screenshot from 2019-03-22 12-50-52](https://user-images.githubusercontent.com/36794263/54811384-02fc1a80-4ca2-11e9-9147-4ea3ba05a3ee.png)

**When the user changes the first select's option, you can notice that the props change and for the second container the defaultValue now is ```{value: "visitedContains", label: "Visited: contains"}``` , but the previous value is yet kept**
![Screenshot from 2019-03-22 12-52-17](https://user-images.githubusercontent.com/36794263/54811434-1c04cb80-4ca2-11e9-8c66-775ddfa1ff0d.png)

**Look at this pic, after changing first container's option the second container doesn't have _Since_  option**

![Screenshot from 2019-03-22 12-52-37](https://user-images.githubusercontent.com/36794263/54811723-c1b83a80-4ca2-11e9-993f-a931925c842a.png)

I have tried to find a solution from documentation , but couldn't . May be it's default behaviour or may be i have to add additional props to my Select component ?

**Comment by Rall3n** [comment]
@norayr93 The `defaultValue` prop is only used to set the value on first render. It will not update the value if changed afterwards. If you want to manage the value, use the `value` prop.

**Comment by norayr93** [comment]
My values are not in the same format as labels

`
[
    {value: 'date', label: 'Date'},
    {value: 'visitUrl', label: 'Visit URL'},
    {value: 'segment', label: 'Segment'},
    {value: 'read', label: 'Article Read Count'},
    {value: 'completed', label: 'Article Completed Count'},
    {value: 'clicked', label: 'Clicked Count'},
    {value: 'video20', label: 'Video View 20s'},
    {value: 'totalVideo', label: 'Total Video View Time'},
]
`

**Comment by norayr93** [comment]
The solution is this `

`value={options.filter(option => option.value === value)}`

Closing the issue.
