### ISSUE TITLE
Render selected value differently when menu is not open

### ISSUE THREAD

**Issue by shahlav** [JedWatson/react-select#3485]
I am using a `react-select` and used `formatOptionLabel` prop to format the options label. Whenever I select any option it is shown in Input and it is also getting that formatted label

I tried passing selectedIcon and removed it on onChange event and that did work, But for that I need to pass it in each option and remove on each onChange.

This is the handleValueChange
```
handleChange = (value) => {
    const { selectedIcon, ...restFields } = value;
    this.setState({
      someKey: restFields
    });
};

```

This is the formatLabel function I have used
```
const formatLabel = (data, restFields) => {
  if (restFields.selectValue[0].value === data.value) {
    return (
      <div>
        {data.selectedIcon}{data.icon}{data.label}
      </div>
    )
  } else {
    return (
      <div>
        {data.icon}{data.label}
      </div>
    )
  }
};
```

Is there a way to format selected value differently when menu is not open. and also I need to apply different styles to both of them.

For example: I want to show ✔️  inside options menu before selected values and when menu is close it should only show the selected value.

Feel free to answer on Stack-Overflow 
Question Link: https://stackoverflow.com/questions/55305653/how-to-remove-selected-symbol-from-react-select-input

**Comment by jamesonhill** [comment]
@shahlav the 2nd argument to formatOptionLabel is a meta data object and one of the keys is "context". You can have logic to render one way if context === "menu" and a different way if context === "value".

**Comment by shahlav** [comment]
Thanks @jamesonhill for answer! I'll surely try it.

PS: I've used other way to render that using CSS in `:before` pseudo selector when option `isSelected`.

**Comment by Colo-Codes** [comment]
> @shahlav the 2nd argument to formatOptionLabel is a meta data object and one of the keys is "context". You can have logic to render one way if context === "menu" and a different way if context === "value".

I think it wouldn't hurt to implement short explanations like this one in the documentation, as it could improve its clarity. I sometimes find myself doing a kind of guessing game when reading `react-select` documentation.
