### ISSUE TITLE
Add support for valueRendering for single select

### ISSUE THREAD

**Issue by jonthor89** [JedWatson/react-select#349]
It looks like there is only possible to change the rendering of the options for a single select dropdown, but not the value that is selected. 
I can see that you can customise your value for multi select with prop "valueRenderer" prop but I would like to do so for my single select value.

**Comment by bruderstein** [comment]
This is already merged and works (see commit 506ca9b4, PR #332)

**Comment by ecoleman** [comment]
Has this been released? With multi={false}, the valueRenderer is never triggered.. Tried latest release and master

**Comment by jonthor89** [comment]
This works perfectly with version 0.6.0
