### ISSUE TITLE
AsyncCreatable and redux-foprm

### ISSUE THREAD

**Issue by benoit-nadaud** [JedWatson/react-select#3490]
Hi,

I'm using AsyncCreatable with redux form, and it seems that my state is ok but redux-form state is not  updated when my asynccreatable component updates my "app state".

I did not find any wrapper component for asyncCreatable, i manage to find it for simple Select react-select component.

Anybody had to deal with it ?

**Comment by Rall3n** [comment]
@benoit-nadaud Would you mind following the issue template and provide a code example showing your problem?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
