### ISSUE TITLE
Can i change arrow (dropdown indicator) to my svg,png icon 

### ISSUE THREAD

**Issue by bonusbb** [JedWatson/react-select#3493]
in example : https://codesandbox.io/s/jz33xx66q9?module=/example.js

i want to use image (.svg , .png) instance emoji 

how to use that

**Comment by Rall3n** [comment]
@bonusbb Please don't post a questions to Github. Keep questions over at StackOverflow as per request by the maintainers in the issue template.

**Comment by michaelmota** [comment]
In the example you sent you just have to replace the EmojiIcon with the link of the image you want.

```
const DropdownIndicator = (
  props: ElementConfig<typeof components.DropdownIndicator>
) => {
  return (
    <components.DropdownIndicator {...props}>
      <img src="https://via.placeholder.com/30x30"/>
    </components.DropdownIndicator>
  );
};
```
And then on your component:
```
  <Select
    closeMenuOnSelect={false}
    components={{ DropdownIndicator }}
    defaultValue={[colourOptions[4], colourOptions[5]]}
    isMulti
    options={colourOptions}
  />
```

**Comment by kandasj** [comment]
how do you change for <AsyncSelect /> ?
components is not exported in react-select/async

**Comment by cpnvr** [comment]
If you're using the example above from @michaelmota make sure to add this line in your file:

`import Select, { components } from "react-select";`

> In the example you sent you just have to replace the EmojiIcon with the link of the image you want.
> 
> ```
> const DropdownIndicator = (
>   props: ElementConfig<typeof components.DropdownIndicator>
> ) => {
>   return (
>     <components.DropdownIndicator {...props}>
>       <img src="https://via.placeholder.com/30x30"/>
>     </components.DropdownIndicator>
>   );
> };
> ```
> 
> And then on your component:
> 
> ```
>   <Select
>     closeMenuOnSelect={false}
>     components={{ DropdownIndicator }}
>     defaultValue={[colourOptions[4], colourOptions[5]]}
>     isMulti
>     options={colourOptions}
>   />
> ```

**Comment by kushhemant** [comment]
I want to remove the Arrow and the vertical line just before that. How can I achieve it ?

**Comment by vladd11148** [comment]
> I want to remove the Arrow and the vertical line just before that. How can I achieve it ?

@kushhemant you need to use [customStyles](https://react-select.com/home#custom-styles). Inside it, set `dropdownIndicator` and `indicatorSeparator` to `display: "none"` like so:
`indicatorSeparator: () => ({ display: "none" }),`

**Comment by rognales** [comment]
> I want to remove the Arrow and the vertical line just before that. How can I achieve it ?

```
<Select
components={{
  DropdownIndicator: () => null,
  IndicatorSeparator: () => null,
}} 
/>
````

**Comment by sahilahluwalia** [comment]
> In the example you sent you just have to replace the EmojiIcon with the link of the image you want.
> 
> ```
> const DropdownIndicator = (
>   props: ElementConfig<typeof components.DropdownIndicator>
> ) => {
>   return (
>     <components.DropdownIndicator {...props}>
>       <img src="https://via.placeholder.com/30x30"/>
>     </components.DropdownIndicator>
>   );
> };
> ```
> 
> And then on your component:
> 
> ```
>   <Select
>     closeMenuOnSelect={false}
>     components={{ DropdownIndicator }}
>     defaultValue={[colourOptions[4], colourOptions[5]]}
>     isMulti
>     options={colourOptions}
>   />
> ```

how to this error?
`Cannot find name 'ElementConfig'`.

**Comment by aoliva31** [comment]
> > In the example you sent you just have to replace the EmojiIcon with the link of the image you want.
> > ```
> > const DropdownIndicator = (
> >   props: ElementConfig<typeof components.DropdownIndicator>
> > ) => {
> >   return (
> >     <components.DropdownIndicator {...props}>
> >       <img src="https://via.placeholder.com/30x30"/>
> >     </components.DropdownIndicator>
> >   );
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then on your component:
> > ```
> >   <Select
> >     closeMenuOnSelect={false}
> >     components={{ DropdownIndicator }}
> >     defaultValue={[colourOptions[4], colourOptions[5]]}
> >     isMulti
> >     options={colourOptions}
> >   />
> > ```
> 
> how to this typescript error? `Cannot find name 'ElementConfig'`.

Change it with DropdownIndicatorProps instead,
import Select,  { DropdownIndicatorProps } from "react-select";

**Comment by srjlulla** [comment]
The error `Cannot find name 'ElementConfig'` still remains.
