### ISSUE TITLE
Custom drop-down

### ISSUE THREAD

**Issue by dekhaus** [JedWatson/react-select#3494]
Hi

I'm interested in determining if its possible for me to completely customize the drop-down that appears in response to a user typing text into a select2 text field.

I want the text to generate output similar to what appears in Apple's Spotlight OS feature (see screenshot - in which I typed the text 'mini').

Is this possible using react-select and if so - how ?  Are there samples ?

I found this repo ( https://github.com/bvaughn/react-virtualized-select/ ) which seems like it supports what I want to do - but its no longer supported.

Thanks
Dave

![Screen Shot 2019-04-01 at 1 33 49 PM](https://user-images.githubusercontent.com/7830/55357887-f71f0e00-5482-11e9-8e86-d7d1cea8b49b.png)

**Comment by Rall3n** [comment]
@dekhaus Please ask questions over at [StackOverflow (tag `react-select`)](https://stackoverflow.com/questions/tagged/react-select) as per maintainers request in the [issue template](https://github.com/JedWatson/react-select/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
