### ISSUE TITLE
Keyboard doesn't work sometimes on iOS

### ISSUE THREAD

**Issue by rpominov** [JedWatson/react-select#3495]
The virtual keyboard sometimes doesn't work on iOS Safari.

I've recorded a screencast: https://www.youtube.com/watch?v=LYnOxhyzKSY

At 0:09 I click the "clear" button -> keyboard disappears -> then I click on input -> keyboard shows up, but doesn't work.

At 0:30 I click the "clear" button -> keyboard doesn't disappear, just stop working.

iOS version 12.1.4
Latest react-select version at the time of recording 2.4.2

**Comment by ezeeFlop** [comment]
Same behaviour

**Comment by simonflk** [comment]
Check out #3546 where I posted a workaround

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
