### ISSUE TITLE
How to set select option value based on form?

### ISSUE THREAD

**Issue by laxmikamala** [JedWatson/react-select#3497]
i have two forms midterm and finalterm, these two forms are wrapped into GradeCard. If my form is Midterm form is true then set select option is inprogress. If my form final term then only select option is pass,fail or retest.
My sample code is here

My selectoption 

[const studentStatus = [{ key: 'inprogress', value: 'Inprogress' }, { key: 'pass', value: 'pass' }, { key: 'fail', value: 'fail' }, { key: 'reset', value: 'reset' }]

const { MidTerm, FinalTerm } = true
const GradeForm = (MidTerm, FinalTerm,handleSubmit) => (
    <div style={{ color: '#808000' }}>
        <Form onSubmit={handleSubmit}>
            <Card title="MidTerm Form"
                align="left"
                size="small"
                type="inner"
                bordered={false}>
                <Card.Grid style={gridStyle}>
                    <MidTermForm MidTerm={MidTerm} />
                </Card.Grid>
            </Card>
            <Card title="FianlTerm Form"
                align="left"
                size="small"
                type="inner"
                bordered={false}>
                <Card.Grid style={gridStyle}>
                    <FinalTermForm FinalTerm={FinalTerm} />
                </Card.Grid>
            </Card>
            <Row style={{ marginTop: 10 }}>
                <Col span={14}>
                    <Field
                        label="Student Status"
                        name="studentstatus"
                        component={AntSelect}
                        selectOptions={studentStatus}
                        style={{ width: 200 }}
                        formitemlayout={formItemLayout}
                    />
                </Col>
            </Row>
            <Row style={{ padding: 0, margin: 0 }}>
                <Col align="right"><b>* %of the total grade for the year</b></Col>
            </Row>
        </Form >
    </div >
)
const GForm = withFormik({
    handleSubmit(values, { resetForm }) {
        resetForm();
        console.log(values)
    }
})(GradeForm)
export default GForm
const MidTermForm = (MidTerm) => (
    <div>
        <Row>
            <Col span={10} style={{ color: '#FFA500' }}><b>Topic</b></Col>
            <Col span={6} style={{ color: '#FFA500' }}><b>MaximuScore*</b></Col>
            <Col span={8} style={{ color: '#FFA500' }}><b>Student's Score*</b></Col>
        </Row>
           <Row>
            <Col span={10} style={{ color: '#FFA500' }}><b>Topic</b></Col>
            <Col span={6} style={{ color: '#FFA500' }}><b>MaximuScore*</b></Col>
            <Col span={8} style={{ color: '#FFA500' }}><b>Student's Score*</b></Col>
        </Row>
     <Row>
           <Col><Fields /></Col>
          <Col><Fields /></Col>
    </Row>
    </div>
)
const FinalTermForm = (FinalTerm) => (
    <div>
        <Row>
            <Col span={10} style={{ color: '#FFA500' }}><b>Topic</b></Col>
            <Col span={6} style={{ color: '#FFA500' }}><b>MaximuScore*</b></Col>
            <Col span={8} style={{ color: '#FFA500' }}><b>Student's Score*</b></Col>
        </Row>
     <Row>
           <Col><Fields /></Col>
          <Col><Fields /></Col>
    </Row>
      </div >
)
]

**Comment by Rall3n** [comment]
@laxmikamala Please ask questions over at [StackOverflow(tag `react-select`)](https://stackoverflow.com/questions/tagged/react-select)) as per maintainers request in the issue template.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
