### ISSUE TITLE
Wrong positioning for menu component when using portal

### ISSUE THREAD

**Issue by iJoyCode** [JedWatson/react-select#3499]
Hello, I've got strange positioning behavior from `react-select` with portal. Looks like it recalculate menu position only when something changes in Menu inner components.

Here is a example of problem:
![Image](https://i.imgur.com/ltOPGHX.gif)

It's can be reproduced only when you use portal for Menu component. Can I use any workaround for this situation?

**Comment by Bosn** [comment]
Similar problem here, when clicked blank area in mobile WeChat browser, will cause touch the incorrect position on page. When I touch the blank area in input, the radio control selected value changed... really weird.

**Comment by Rall3n** [comment]
It is not an error with this library, but a problem with `React` itself. React calls `render` before it updates the DOM, so the values for dimensions and positions you get in a `render` function might be outdated.

**Comment by chulanovskyi** [comment]
have you tried to use latest `useLayoutEffect` hook? Seems likes it's a perfect case for start using it :)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by iJoyCode** [comment]
Issue is still reproducible in the last version.
