### ISSUE TITLE
Remove reactify from package.json dependencies

### ISSUE THREAD

**Issue by julen** [JedWatson/react-select#35]
I was puzzled to see *react-select* pulling *reactify* when installing it via npm.

Forgive my ignorance on Browserify (webpack user here), but even after reading the related discussion on #8 I don't see how the library should depend on a build-related piece. That decision is up to the developers making use of *react-select*, and they are able to set such dependency in the *package.json* of their respective projects.

Therefore I believe *reactify* should be removed from the `dependencies` section of *react-select*'s *package.json*.

**Comment by JedWatson** [comment]
I would love to do that, but unfortunately it breaks the build process if you are using browserify and haven't included `reactify` as a dependency of the project where the build is happening.

It seems like a lesser of two evils thing: either

* webpack (or other build process) users get a package installed from npm that they don't need, or
* browserify users who aren't using reactify will get an obscure error

I'll see if I can work out a better strategy for both ecosystems...

**Comment by JedWatson** [comment]
TBH I am considering switching from JSX to `React.createElement(...` syntax.

I find JSX much clearer for visualising DOM structure but don't love the build-related mess it creates supporting both browserify and webpack.

**Comment by julen** [comment]
For library consumers the best thing is publishing code that needs no transformation — this issue and #26 wouldn't exist in the first place. And users of any other module bundlers wouldn't be affected either.

You can still keep using JSX for development (so `reactify` goes in `devDependencies`), but you only publish to npm the scripts transformed to React — you could whitelist files by using the [`files` field in `package.json`](https://docs.npmjs.com/files/package.json#files) or blacklist them in the [`.npmignore` file](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package).

(Note that you can also leverage `files`/`.npmignore` to reduce the download size to the bare minimum. Consumers will be happy to have faster downloads!)

**Comment by JedWatson** [comment]
@julen I think I'll go with your suggestion here if we don't come up with a better idea in #40, especially given #38. I'm already publishing code that doesn't need transformation for standalone use, was just expecting that if you've got a browserify / web pack build process in your project and are using React, JSX transformation wouldn't be an issue.

**Comment by JedWatson** [comment]
I've updated the build process to pre-build JSX to a `/lib` directory, which `package.json` is now pointed at. So this should be all cleaned up now.

**Comment by julen** [comment]
Just verified this on my side and everything works like a charm without special-casing :+1:

Many thanks!
