### ISSUE TITLE
autoFocus does not work on Safari mobile

### ISSUE THREAD

**Issue by csantos1113** [JedWatson/react-select#3501]
`autoFocus` does not work on Safari mobile.
The input shows the "focus" state, but the caret is not shown, which means that the `<input>` is not actually in focus so the keyboard is not shown.

https://codesandbox.io/s/93pz9n63py

### Chrome - focused ✔️
![2019-04-04 18 13 38](https://user-images.githubusercontent.com/9648559/55592570-ca7b2880-5706-11e9-81c7-47bce4b94223.gif)

## Safari - Mac - focused ✔️ 
![2019-04-04 18 15 26](https://user-images.githubusercontent.com/9648559/55592572-ca7b2880-5706-11e9-9c5f-270b73f46748.gif)

## Safari - Mobile - Not actually in focus ❗️
![2019-04-04 18 14 08](https://user-images.githubusercontent.com/9648559/55592571-ca7b2880-5706-11e9-9b3e-84226c7da42f.gif)

**Comment by Rall3n** [comment]
@csantos1113 Safari does not allow "real" focus without user interaction. With "real" focus I mean it sets the focused state so the `focus` events are called, but input is not allowed.

**Comment by karlingen** [comment]
@Rall3n do we have an official answer from Apple confirming that statement or is this just something you have discovered?

**Comment by Rall3n** [comment]
@karlingen 
Yes, we have. There was a comment about it in a ticket for WebKit. The comment was created March 2019, and states the following: 
>"We (Apple) like the current behavior and do not want programmatic focus to bring up the keyboard when [...] the programmatic focus was not invoked in response to a user gesture."

[Source](https://bugs.webkit.org/show_bug.cgi?id=195884#c4)

**Comment by csantos1113** [comment]
Closing in favor of Apple's decision. Nothing we can do

**Comment by pulkitdev** [comment]
@Rall3n  Autofocus is not working the first time but when we come back to the same page again, it's opening the keyboard by default. Is there any specific reason behind this?

**Comment by dipanshumahla** [comment]
> @Rall3n Autofocus is not working the first time but when we come back to the same page again, it's opening the keyboard by default. Is there any specific reason behind this?

facing the same issue

**Comment by damianoc90** [comment]
> @Rall3n Autofocus is not working the first time but when we come back to the same page again, it's opening the keyboard by default. Is there any specific reason behind this?

Same!

**Comment by Hyodori04** [comment]
i think caret is not active also .

**Comment by samrahsajid** [comment]
Any updates on this?

**Comment by maryia-tolkach** [comment]
Same!
