### ISSUE TITLE
[IE11] Scrollbar click for Select inside bootstrap modal

### ISSUE THREAD

**Issue by rafail-r** [JedWatson/react-select#3503]
There was an issue about this for version 1 #648
and another one #2698 but the problem now only happens inside bootstrap modals.

https://codesandbox.io/embed/yjlklpn7ox

![i11selectBug](https://user-images.githubusercontent.com/18389355/55722925-48457980-5a10-11e9-9dfd-41a1a061448b.gif)

any ideas how to fix?

**Comment by Rall3n** [comment]
Only solution I could think of is handling the `menuIsOpen` state by yourself.

```jsx
export default class SingleSelect extends Component {
  constructor(props) {
    super(props);

    this.selectRef = React.createRef();
  }

  state = {
    open: false
  };

  onDOMClick = e => {
    var target = e.target;
    var domNode = ReactDOM.findDOMNode(this.selectRef.current);
    
    // Checking if click was outside of select element
    if (!domNode.contains(target)) {
      this.setState({
        open: false
      });
    }
  };

  componentDidMount() {
    document.addEventListener("click", this.onDOMClick);
  }

  componentWillUnmount() {
    document.removeEventListener("click", this.onDOMClick);
  }

  onChange = () => {
    // Close select if value has been selected
    this.setState(
      {
        open: false
      },
      () => this.selectRef.current.blur()
    );
  };

  // Always open on focus
  onFocus = () => this.setState({ open: true });

  render() {
    return (
      <Modal isOpen={true}>
        <ModalBody>
          <Select
            name="color"
            options={colourOptions}
            ref={this.selectRef}
            menuIsOpen={this.state.open}
            onFocus={this.onFocus}
            onChange={this.onChange}
          />
        </ModalBody>
      </Modal>
    );
  }
```

[CodeSandbox](https://codesandbox.io/s/l4x5x1zx0q)

**Comment by rafail-r** [comment]
Thanks for that. I m having trouble making this work for 
isMulti={true}
closeMenuOnSelect={false}
removed the setState inside onChange but domNode.contains(target)) returns false when clicking an option

**Comment by Rall3n** [comment]
@rafail-r Would you mind sharing your current code?

**Comment by rafail-r** [comment]
[https://codesandbox.io/embed/qomj2zn16](CodeSandbox)
every time a new option is selected the menu closes because `domNode.contains(target)) `equals `true`

**Comment by Rall3n** [comment]
Might be some sort of race condition between Reacts `render` and the `onClick` listener on `document`. You could add the prop `classNamePrefix` to the `Select` component to add extra classes to the dom elements and check if the target does not have the class `classNamePrefix+"__option"`.

```jsx

const prefix = "myselect";

onDOMClick = e => {
    var target = e.target;
    var domNode = ReactDOM.findDOMNode(this.selectRef.current);

    if (!this.state.open) return; // If menu is closed we don´t want to check.

    // Check if target is not inside the select and if target does not have role `option`
    if (!domNode.contains(target) && !target.classList.contains(prefix+'__option')) {
        this.setState({
            open: false
        });
    }
};

<Select
    { ... }
    classNamePrefix={prefix}
/>
```

**Comment by alfechner** [comment]
I've the exact same issue. Managing the state by myself feels like re-implementing react-select logic.

I tried to wrap my head around what is causing this behavior in the first place. Does anyone have an idea what Bootstrap's Modal possibly could do to break this peace of functionality?

Any advice/idea on how to debug this issue? I'm not that experiences in JavaScript and a bit lost here :)

**Comment by ebonow** [comment]
Greetings, 

I encountered what I believe to be a similar if not related issue to another rendering/race-condition related to bootstrap.

https://github.com/JedWatson/react-select/issues/4171#issuecomment-741326124

Since the DOM at the time of the click is not in sync, you could also verify that the composedPath includes the bootstrap modalRef or selectRef (depending on what you are trying to accomplish)
```js
const onClick = e => {
  // Determine if click was inside select
  const clickInside = e.composedPath().includes(selectRef.current))
 ...
}
```

It's been a while since this issue has been addressed so I will close this for now and leave this here in case it is helpful. However, if there are any questions or follow up to this, I can re-open this and we can continue to work towards a resolution.
