### ISSUE TITLE
overflows available width in grid with grid-gap

### ISSUE THREAD

**Issue by flyon** [JedWatson/react-select#3504]
When using <Select> in a grid with a grid-gap
The <Select> component becomes larger (in width) than the available space, thus overflowing its parent div

```
<div
        style={{
          display: "grid",
          gridTemplateColumns: "20% 80%",
          gridGap: "20px"
        }}
      >
        <div>should not overflow &raquo;</div>
        <div>
          <Select
            className="basic-single"
            classNamePrefix="select"
            name="color"
            options={colourOptions}
          />
        </div>
      </div>
```
overflows.
![image](https://user-images.githubusercontent.com/341567/55780811-61ffc300-5adb-11e9-8f73-f93b0667eaeb.png)

when inspecting you can see it overflows the size of the div
![image](https://user-images.githubusercontent.com/341567/55780745-45638b00-5adb-11e9-9c74-508dd0031175.png)

https://codesandbox.io/s/yp9jovml99

**Comment by Rall3n** [comment]
@flyon Not an issue with `react-select`, but with your Grid setup When inspecting with Chrome I could see that the whole grid is overflowing. You have to include the `gap`into your relative width calculation: 
```css
grid-template-columns: 20% calc(80% - 20px)
```

**Comment by flyon** [comment]
@Rall3n you are right. I've never had this issue before with grids, but I see now that when using pixels for the gap and percentages for the columns you do indeed have to subtract the gutter width, tnx
