### ISSUE TITLE
TypeScript Examples for V2?

### ISSUE THREAD

**Issue by 129emma** [JedWatson/react-select#3509]
Hi, just wondering if it's possible we could have typescript live example for v2? 
I've faced many issues on that but couldn't find any examples for TypeScript.

Thanks!

**Comment by georgeshevtsov** [comment]
It is weird to have a typing library for react-select and not be able to do anything with it. How do you guys customize components for a select if you're using typescript? What type hosts innerProps?

**Comment by tx-steven** [comment]
Running into this same issue. Can't import/extend anything out of @types. Seems silly to have to write them all out when they are already defined.

**Comment by goodwin64** [comment]
Any updates on this issue?

**Comment by tx-steven** [comment]
@goodwin64 I was able to solve my problem by importing the types I needed from this path: `react-select/src/Select`. Doesn't really solve the issue but it is a workaround if you need to access types.

**Comment by danieldelcore** [comment]
I was struggling with this too... [After some digging around DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/test/examples/AsyncCallbacks.tsx#L5), i found an `examples/` directory where they import type definitions like this:

```javascript
import { OptionsType } from 'react-select/src/types';
```

It's not what i expected, but seems to be the way the authors defined the type-defs 🤷‍♂️

**Comment by danieldelcore** [comment]
@gwyneplaine, Might be worth closing this issue now since the import structure of `@types/select` has been changed to avoid requiring users to import like this:

```typescript
import { OptionsType } from 'react-select/src/types';
```
to this: 

```typescript
import { OptionsType } from 'react-select';
```

**Comment by gwyneplaine** [comment]
Thanks @danieldelcore  love your work, issue closed
