### ISSUE TITLE
Prevent delete option on multi select

### ISSUE THREAD

**Issue by jchapelle** [JedWatson/react-select#3514]
I want to be able to prevent the user to delete an option when the numbre of selected options for the select is 1. In other words, I need the select to have a minimum option selected of 1.
Is it possible to configure this ? With a minimumOtions configuration or with a method being called before accepting the removal ?

**Comment by fracz** [comment]
Did you solve it somehow?

**Comment by uvarov-frontend** [comment]
```
const [value, setValue] = useState(options[0]);
const checkNumberValue = (selectedOptions) => {
  if (selectedOptions.length > 0) setValue(selectedOptions);
};

<Select
  isMulti
  value={value}
  onChange={(selectedOptions) => checkNumberValue(selectedOptions)}
  options={options} />
```
