### ISSUE TITLE
react-select-async-paginate how to handle different sets of dropdownlist 

### ISSUE THREAD

**Issue by kkwokwai22** [JedWatson/react-select#3516]
Hi Team,

Thanks for a wonderful component first of all, but after using it for a while I came upon this roadblock. The component is great, but I have a hard time using it dynamically. For now I can only trigger the component dropdownlist base on the loadOptions function. 

Home Department drop down list is dependent on the selected company code value. The expectation is that when you focus on the Home department drop down, loadOptions is invoked which will retrieve the expected list of home departments. The problem is that the component only invokes loadOptions on mount and on scroll. So when the company code changes, if the component has already been mounted, the home department options list will not changed. 

Is there a way to clear the list once I change the company code. To summarize will you guys have a example I can look at with react-select-async-paginate where I can render dynamic dropdownlist. Please Help! thank you so much!

**Comment by Abror1997** [comment]
I have the same issue

**Comment by brandhilton** [comment]
> Hi Team,
> 
> Thanks for a wonderful component first of all, but after using it for a while I came upon this roadblock. The component is great, but I have a hard time using it dynamically. For now I can only trigger the component dropdownlist base on the loadOptions function.
> 
> Home Department drop down list is dependent on the selected company code value. The expectation is that when you focus on the Home department drop down, loadOptions is invoked which will retrieve the expected list of home departments. The problem is that the component only invokes loadOptions on mount and on scroll. So when the company code changes, if the component has already been mounted, the home department options list will not changed. 
> 
> Is there a way to clear the list once I change the company code. To summarize will you guys have a example I can look at with react-select-async-paginate where I can render dynamic dropdownlist. Please Help! thank you so much!

@kkwokwai22 Did you find a workaround for this? I'm running into the same problem.

**Comment by DmitryMasley** [comment]
@kkwokwai22 Only thing I came up is set `key=companyCode`. So once company code changes select gets unmounted and mounted again. Maybe it is not very effective, but for small form I think it is ok.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
