### ISSUE TITLE
:active not being set on option

### ISSUE THREAD

**Issue by comfroels** [JedWatson/react-select#3517]
# Are you reporting a bug or runtime error?
Bug

The following codesandbox should show how the `:active` style on options does not get applied while clicking an option. As the mouse down happens on the option the background should be turning pink, but is not.

https://codesandbox.io/embed/2wzm0rq38n

`:active` should be getting set as a mouse down event occurs on the option

**Comment by Rall3n** [comment]
Could not reproduce the error. `:active` styles were applied when clicking on an option.

**Comment by comfroels** [comment]
This is in Firefox, sorry I should've said that

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
