### ISSUE TITLE
How to remove dropdown list?

### ISSUE THREAD

**Issue by zhaoyi0113** [JedWatson/react-select#3521]
This is a question more than an issue. I wonder how I can remove the dropdown list for selection. I only want to keep the `text field`.

**Comment by Rall3n** [comment]
1.) Questions should be asked over at StackOverflow. The maintainers ask for this in the issue template.

2.) The library is not called `react-select` as a joke. The drop-down is a crucial part of the components. And even if you find a way to disable the drop-down, there is still plenty of code that creates too big of an overhead for a simple text field. You should search for a library that offers just a text field, or try creating your own.

**Comment by themre** [comment]
if you need to customize this component, there is very nice documentation about components: https://react-select.com/components
basically you do 
```
<Select component={{Menu: null}} />
```
and not menu will appear.

**Comment by marvintau** [comment]
I met similar situation. In my case, there is a controlled Select which contains no options. The values added to it come from several Selects, however, you could remove the selected options from it. In this case you wanted to disable the blank options menu, and dropdown list. You could do

```js
import Select, {components} from 'react-select';

//...

<Select component={{
  Menu:()=>(<></>),
  IndicatorsContainer:()=>(<></>)
}} />
```

where `<></>` means a document fragment.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
