### ISSUE TITLE
Clicking on Option which contains checkbox doesn't get selected but menu gets closed.

### ISSUE THREAD

**Issue by bharathnayak03** [JedWatson/react-select#3525]
https://github.com/JedWatson/react-select/blob/292bad3298f2cafad6767f2134bd79a9c27e4073/src/Select.js#L1100

This doesn't work in every case as In between blur events , document.activeElement will be pointing to body. as referred by this thread https://stackoverflow.com/questions/11299832/document-activeelement-returns-body

I had a use-case where I was using checkbox (wrapped inside a label) inside an option.
where onclick of checkbox label was trying to add focus to the checkbox which was triggering blur event for input box. instead of selecting the option it was causing the menu to close.

instead of using ``document.activeElement`` we can use  ``event.relatedTarget`` which works

**Comment by ebonow** [comment]
This is still an issue for me, but I just came up with a workaround. 

I am using Checkboxes as a child of a MultiSelect Option. The behavior of this is that clicking the (inline) checkbox itself closes the select menu as opposed to clicking on the option but outside the content area of the checkbox and its label which does not close the menu (with the select prop `closeMenuOnSelect` set to false when `isMulti` is true)

To fix this, I had to wrap a div around the checkbox in my custom Option component and set an onClick handler on the div to prevent event propagation.

```
const Option = ({ children, ...props}) => {
  const { isSelected, label, value, isMulti, data } = props;
  
  const onClick = (e) => {
    props.selectOption({...data});
    e.stopPropagation();
    e.preventDefault();
  }

  if (isMulti) {
     return (
       <components.Option {...props}>
         <div className="multi-select-option" onClick={onClick}>
            <Checkbox checked={isSelected} label={label} value={value} />
         </div>
       </components.Option> 
     );
  }

  // Other code for returning option component if not isMulti goes here but simply can be...
  return <components.Option {...props} children={children} />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by injyzarif** [comment]
I tried the above solution, but the problem with it was that clicking anywhere on the option works, but clicking on the checkbox itself doesn't work. This workaround solved it for me. The menu doesn't close, the checkbox status is correct, and clicking anywhere on the label selects the option.
`
export const CheckboxOption = (props: any) => {
  const {
    label,
    isSelected,
    data,
    selectOption,
    innerProps: { ref, options, onClick: innerOnClick, ...restInnerProps },
  } = props;
  // This click handler makes the whole label/option clickable, not just the checkbox.
  const onLabelClick = (
    event: React.MouseEvent<HTMLLabelElement, MouseEvent>,
  ) => {
    selectOption({ ...data });
    event.preventDefault();
  };

  // This click handler prevents the menu from closing when the checkbox is clicked.
  const onCheckboxClick = (
    event: React.MouseEvent<HTMLDivElement, MouseEvent>,
  ) => {
    innerOnClick(event);
    event.stopPropagation();
  };

  return (
    <label onClick={onLabelClick}>
      <input
        type='checkbox'
        {...restInnerProps}
        checked={isSelected}
        onChange={onCheckboxClick}
        onClick={onCheckboxClick}
      />
      {label}
    </label>
  );
};
`

**Comment by AkisKouzinopoulos** [comment]
Is this still an issue?

For anyone still trying to solve this, a workaround I found is to set the z-index: -1 to my custom component. That has the result to put my component below the row that react-select is creating, so my component looks like is clicked, but what really does is to listen to the click on the row.

```
...
return(
<components.Option
        {...rest}
        isDisabled={isDisabled}
        isFocused={isFocused}
        isSelected={isSelected}
        innerProps={props}
      >
        <CustomCheckbox
          isSelected={isSelected}
          isDisabled={isDisabled}
          style={{ zIndex: '-1' }} // Easiest possible fix for the issue when clicking on a custom element would dismiss the list Popup.
        >
          <div className={'px-6 text-t-primary'}>{children}</div>
        </CustomCheckbox>
      </components.Option>
)
...
```

**Comment by LinKassem** [comment]
> <components.Option
>         {...rest}
>         isDisabled={isDisabled}
>         isFocused={isFocused}
>         isSelected={isSelected}
>         innerProps={props}
>       >
>         <CustomCheckbox
>           isSelected={isSelected}
>           isDisabled={isDisabled}
>           style={{ zIndex: '-1' }} // Easiest possible fix for the issue when clicking on a custom element would dismiss the list Popup.
>         >
>           <div className={'px-6 text-t-primary'}>{children}</div>
>         </CustomCheckbox>
>       </components.Option>
> )
> ...
thanks @AkisKouzinopoulos 
but how will your CustomCheckboz appear on screen if the z-index is -1?

**Comment by AkisKouzinopoulos** [comment]
@LinKassem because the row created from the `Option` is transparent my checkbox is still visible, even though is behind it.
