### ISSUE TITLE
Make component controlled but keep the usual onClick/Clickaway behavior to open and close it.

### ISSUE THREAD

**Issue by Ericnr** [JedWatson/react-select#3544]
I need to make my select controlled just to be able to know when it is open or not but I don't want to give up on the default behavior of opening and closing it. Didnt find anything about it in the docs so I tried to reproduce it myself but failed to do so. Any tips to do this?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by kg-currenxie** [comment]
I want the same behavior. Any progress on this @Ericnr ?

**Comment by kevinhaas** [comment]
It's not possible it seems. I ended up using my projects clickAway listener and going full controlled on the open/close myself to get it to feel just right.

**Comment by Rall3n** [comment]
To provide a solution with actual code: Just use the `menuIsOpen`, ` onMenuClose` and `onMenuOpen` props to make the component controlled but keep the default behaviour.

```
const [menuIsOpen, setMenuIsOpen] = React.useState(false);

<Select
    menuIsOpen={menuIsOpen}
    onMenuOpen={() => setMenuIsOpen(true)}
    onMenuClose={() => setMenuIsOpen(false)}
/>
```
It's as simple as that.
