### ISSUE TITLE
Ability to use AsyncSelect from a CDN without bundling or transpiling.

### ISSUE THREAD

**Issue by ErnestoBorio** [JedWatson/react-select#3545]
I managed to use React-Select, Babel and other dependencies from the unpkg.com CDN. (As a requirement no bundling or transpiling are allowed)
But I can't get AsyncSelect to work that way. The only Async.js available in the CDNs I found it in uses module.exports which is not supported in browsers.
Any way to fix or work around this?
Thanks.

**Comment by razh** [comment]
For react-select **v2**, this is available as `Select.Async`.

https://github.com/JedWatson/react-select/blob/c22d296d50917e210836fb011ae3e565895e6440/src/index.umd.js#L18-L26

The UMD builds will be deprecated in 3.x: https://github.com/JedWatson/react-select/issues/3529

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
