### ISSUE TITLE
Every react-select on a page is rerendered when i type non english character.

### ISSUE THREAD

**Issue by YongPilMoon** [JedWatson/react-select#3547]
I have a couple of react-select on one page. But When I type non-English character text in any input other react select also rerendering and It makes a site slow a lot.
**When I type English there is no problem at all.**
![english](https://res.cloudinary.com/daqk5u0dg/image/upload/v1557423541/english.png)
**But non-English character(Korean) make a problem.**
![korean](https://res.cloudinary.com/daqk5u0dg/image/upload/v1557423541/korean.png)
I can't understand how this could happen.

**Comment by razh** [comment]
This should be fixed by https://github.com/JedWatson/react-select/pull/3563.

**Comment by gwyneplaine** [comment]
Thanks for raising this issue @YongPilMoon. This is resolved as part of #3563 which has since been merged and published. Please update to the latest version react-select to see this in effect.

**Comment by elibh159** [comment]
hi, 
I have a similar problem
but for character(Persian) make a problem.
Can you help me?
