### ISSUE TITLE
does not work in Firefox on touch+mouse hybrid devices (like a laptop with a touch screen)

### ISSUE THREAD

**Issue by do-pe** [JedWatson/react-select#3551]
The dropdown opens and then immediately closes again. You are not able to select anything.

It happens even on the latest version in the demos on react-select.com

It already was like that in 2.2.0 and maybe before that as well.

---

**Can be reproduced in a regular version of Firefox (no touch devices needed) on react-select.com:**

Use the devtools to go into the "responsive" mode (CTRL+SHIFT+M) and activate touch emulation.

The dropdown has to be initialized with touch already activated - so reload the page after activating touch emulation.

Tested in Firefox 66 on Windows 10.

---

I think the problem is as follows:
onControlMouseDown gets called when you touch it. The dropdown opens. Then onControlTouchEnd is called as well and that closes the dropdown again.

I tried myself at a fix, but I don't know if it's good enough or if it breaks anything else.

In Select.js:

```
  onControlTouchEnd = (event: SyntheticTouchEvent<HTMLElement>) => {
    if (this.userIsDragging) return;

    /* Firefox on a desktop touch device calls this after opening the menu, which
     closes it again. It fires both mousedown and touchend. */
    if (isTouchCapable() && isFirefox()) return;

    this.onControlMouseDown(event);
  };
```

```
  onDropdownIndicatorTouchEnd = (event: SyntheticTouchEvent<HTMLElement>) => {
    if (this.userIsDragging) return;

    /* Firefox on a desktop touch device calls this after opening the menu, which
     closes it again. It fires both mousedown and touchend. */
    if (isTouchCapable() && isFirefox()) return;

    this.onDropdownIndicatorMouseDown(event);
  };
```

added in util.js:

```
export function isFirefox() {
  try {
    return navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
  } catch (e) {
    return false;
  }
}
```

**Comment by do-pe** [comment]
It still happens in Firefox 67

**Comment by bkbooth** [comment]
Yep, I just discovered this issue happening for me too (Firefox 69). Is there a fix or workaround?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by pjjanak** [comment]
@bladey - I'm still experiencing this. I'm on Safari on an iPad but the behavior is the same as described.

**Comment by marwaemad** [comment]
still not working with last version on touches devices
