### ISSUE TITLE
componentWillReceiveProps will be deprecated in react 17

### ISSUE THREAD

**Issue by YonathanB** [JedWatson/react-select#3552]
https://github.com/JedWatson/react-select/blob/b37edfd3c71d37a41baf0d770031c26c92813e7c/src/Select.js#L390

[React doc](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops) said that **componentWillReceiveProps** will be deprecated in react 17.

Also, they said that we shouldn't use it because it's anti-pattern.

I'm new to React and wanted to know what you think about it?

**Comment by razh** [comment]
There is an open pull request to resolve this: https://github.com/JedWatson/react-select/pull/3487

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
