### ISSUE TITLE
Need to support IME composition in Select

### ISSUE THREAD

**Issue by ShawTim** [JedWatson/react-select#3561]
The Select box is great however i find that it doesnt support Chinese/Japanese charactor through IME composition.

B​rowser: Chrome is working. but firefox/IE11/Edge fails.

To reproduce this, simply go to the demo site:
https://react-select.com/creatable

1. go to any select box, type Chinese/Japanese through IME (e.g. use Cangjie for Chinese, type "hqi"+space for "我", which means me)
1. in Chrome you should be able to see the word "我" in textbox
1. in other browser you wont have anything in the textbox

Reference:
https://www.fxsitecompat.com/en-CA/docs/2018/keydown-and-keyup-events-are-now-fired-during-ime-composition/
https://developer.mozilla.org/en-US/docs/Mozilla/IME_handling_guide

**Comment by razh** [comment]
This should be fixed by https://github.com/JedWatson/react-select/pull/3563.

**Comment by gwyneplaine** [comment]
Thanks for raising this issue @ShawTim. As above, we shipped #3563 as part of 2.4.4, and should be carried over to 3.0.0 as well
