### ISSUE TITLE
Include `labels` option in `filterOption` parameters

### ISSUE THREAD

**Issue by silverwind** [JedWatson/react-select#3570]
I'm looking for a way to make a [filterOptions](https://react-select.com/props) decision based on all option labels present instead of only one at a time. Use case as follows:

With labels `foo`, `fooh` and `bar` and a input string `o` I want to show `foo` and `fooh` and with input string `foo`, I want to show only `foo`. Basically exact match if present and substring match otherwise. Without knowledge of the other options it is impossible to make the correct filter decision for label `fooh` because of lack of knowledge of other labels.

Proposing to add a `labels` array which holds all labels so the `filterOption` signature would become `{label, value, data, labels}, string`.

**Comment by razh** [comment]
You could potentially do this by keeping track of the option labels.

```jsx
const defaultFilterOptions = createFilter();

function CustomFilterSelect({ options }) {
  const filterOptions = useMemo(() => {
    const labels = options.map(({ label }) => label);

    return (candidate, input) => {
      const doesExactMatchExist = labels.includes(input);

      if (doesExactMatchExist) {
        return candidate.value === input;
      }

      return defaultFilterOptions(candidate, input);
    };
  }, [options]);

  return <Select options={options} filterOption={filterOptions} />;
}
```

**Comment by silverwind** [comment]
Hmm yes, holding the labels inside the component state could work. I did not consider it because my `filterOptions` function lived outside the component. It would make the function impure thought, which is not ideal.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
