### ISSUE TITLE
Value not displaying when chosen on react-select

### ISSUE THREAD

**Issue by jennypho** [JedWatson/react-select#3571]
I'm using react-select version 2 works with react-select V1 but want to keep the styling aspect that V2 has. The value won't show when selecting an item even though the state correlates with the selected value. It just shows the placeholder. But when I remove the value attribute it works. But I need to set the value when I'm updating information. 

When I set the value using state it doesn't show. 

//state
this.state ={
    modifierInfo: {
        modifierNum: ''
    }
}

//render
                            <div style={{marginBottom: '20px'}}>
                                <Label for="modifierNum">Choose Modifier</Label>
                                <Select options={this.state.modifierOptions}
                                        components={{MenuList}}
                                        id='modifierNum'
                                        placeholder='Search for Modifier'
                                        styles={customStyles}
                                        name='modifierIndex'
                                        value={this.state.modifierInfo.modifierNum}
                                        onChange={(e, {name}) => this.onChange(name, e.value)}
                                />
                            </div>

**Comment by razh** [comment]
**react-select** v2 no longer supports passing simple/primitive values to the `value` prop:

https://react-select.com/upgrade-guide#simple-value

If I'm guessing the shape of your data correctly, this would be:

```js
<Select
  options={this.state.modifierOptions}
  value={this.state.modifierOptions.find(
    ({ value }) => value === this.state.modifierInfo.modifierNum
  )}
/>
```
