### ISSUE TITLE
Handler when the user changes the option focused

### ISSUE THREAD

**Issue by lmvco** [JedWatson/react-select#3572]
I am using react-select 2.x

I read the API and I did not find any prop to provide a handler to be called when an option is focused (either using keys or mouse hover). Can anyone help me on this?

If it is not supported at all, will it be implemented in a short or medium term?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
