### ISSUE TITLE
Add Avatar to Custom Component

### ISSUE THREAD

**Issue by dongepulango** [JedWatson/react-select#3573]
Hi I wanted to add some avatar next to the text but the image won't show up. my code goes like this:

`const { Option } = components;`
`const CustomOption = (props) => (`
`   <Option {...props} className="custom-option">`
`       <img src={props.avatar} />`
`      <p>{props.value}</p>`
`    </Option>`
` );`

`<img src={props.avatar} />` doesn't show up

thanks.

**Comment by dongepulango** [comment]
Nevermind, my code is wrong. 
it must be: `<img src={props.data.avatar} />`

**Comment by ahmadkam72** [comment]
Hi 
I want to change options style and show some items like subtitles and .... 
Can you help me to do this?
Thank you.
