### ISSUE TITLE
[Urgent] Need display Permanent Option

### ISSUE THREAD

**Issue by sketchbrahma** [JedWatson/react-select#3577]
Need to show one option like create that should be visible after every key down events, means no need to filter this particular option by input keyword.

**Comment by gwyneplaine** [comment]
@sketchbrahma please refrain from marking issues as [Urgent] especially feature requests. 
Creatable is a superset of Select, you should be able to achieve the behaviour you've described above with onInputChange and the options array. 

I'm closing this issue.
