### ISSUE TITLE
How to make onChange only return value without the label

### ISSUE THREAD

**Issue by anton6** [JedWatson/react-select#3578]
Is there a way to make react-select only return the value during onChange?

At the moment it seems to return the pair { label, value }. The problem is that I don't really care or need the label, only the value.

Also when I set the prop value to only the value react list does not seem to like that, it also wants me to set value to { label, value } pair.

Why is it like this? Why can't react list input only be driven by the value, why does it make me care about the label when I only need the value? Label is only used to display the list item to the user, and I want to know which value user clicks on.

**Comment by yaoyonstudio** [comment]
I want this too.

**Comment by ebonow** [comment]
```Is there a way to make react-select only return the value during onChange?```

onChange allows you to do whatever you want including setting a reference to the value either in state or anywhere else. It doesn't return anything.

```Also when I set the prop value to only the value react list does not seem to like that, it also wants me to set value to { label, value } pair. Why is it like this? Why can't react list input only be driven by the value, why does it make me care about the label when I only need the value?```

If your select is async, then there is no way to know what to display as a the label. It also keeps the usage consistent of a selected item. Also consider that in advanced cases, there might be more data on the option that can be useful. The component is designed to be flexible and consistent and having a selected value without a label seems like a poor UX.

Perhaps you could wrap the react-select component and pass in a defaultValue that can be used to filter through your options and select the item onLoad like I am doing.

**Comment by yaoyonstudio** [comment]
@ebonow Thanks, I think you're right, your explanation make sense.

**Comment by anton6** [comment]
For reference: https://react-select.com/async
