### ISSUE TITLE
Include whether option is contained within group in state provided to custom styles

### ISSUE THREAD

**Issue by abrenoch** [JedWatson/react-select#3593]
Hey guys,

I'm working with the custom styles feature of react-select, and am trying to provide different styling based on whether the option being rendered is part of an optgroup or not. The state object does not seem to contain whether or not the option is contained within a group or not.

Maybe something like:
```
const customStyles = {
    option: (provided, state) => {
        const { isFocused, insideGroup } = state;
        const style = {};
        if (isFocused) {
            style.backgroundColor = 'red';
        }
        if (insideGroup) {
            style.paddingLeft = '10px';
        }
        return {
            ...provided,
            ...style
        };
    }
};

<Select style={customStyles} />
```

Unless there is another way to achieve this, seems like it would be a useful addition!

**Comment by ebonow** [comment]
Greetings @abrenoch ,

This is already available to implement. So long as you are providing options, you can simply add `isGroup` to your group options.

Working demo: [codesandbox](https://codesandbox.io/s/react-select-group-option-styling-9mo4n?file=/src/App.js)

```js
const isGroup = (option) => {
  const setIsGroup = (opt) => ({ ...opt, isGroup: true });
  return !option.options
      ? option
      : { ...option, options: option.options.map(setIsGroup) };
};
  
return <Select options={options.map(isGroup)} {...otherProps} />
```

Then in your styles api you can access this from the state,
``` js
  const styles = {
    option: (css, state) => ({
      ...css,
      ...(state.data.isGroup && { color: "red" })
    })
  };
```

Let me know if this resolves your use-case.

**Comment by abrenoch** [comment]
@ebonow Thanks for the tip, I actually wound up doing basically what you suggested to at least mimic the effect of an optgroup.

I still think having something baked-in to better support optgroups would be preferable, but maybe outside the scope of this specific issue.

Seems like we could probably close this!
