### ISSUE TITLE
Could not find module in path: 'react-syntax-highlighter/prism-light' (Single example)

### ISSUE THREAD

**Issue by oudoulj** [JedWatson/react-select#3594]
On https://react-select.com/home
the link to the CodeSandbox example for the **_Single_** select list opens up
https://codesandbox.io/s/53pf1?module=/example.js
that has the following error :
```
DependencyNotFoundError
Could not find dependency: 'react-syntax-highlighter' relative to '/docs/styled-components.js'
```

I did install the react-syntax-highlighter dependency (10.3.0) as suggested but I get 
```
ModuleNotFoundError
Could not find module in path: 'react-syntax-highlighter/prism-light' relative to '/docs/styled-components.js'
```
Can you fix it please ? Thanks !

**Comment by tacnoman** [comment]
The same to me :/

**Comment by siegmergius** [comment]
Could not find module in path: 'react-syntax-highlighter/prism-light'

**Comment by shubhamgupta47** [comment]
This would solve the issue. 

`// @flow
/** @jsx emotionJSX */
import { jsx as emotionJSX } from "@emotion/core";

import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";
import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";

const customTomorrow = {
  ...tomorrow,
  'code[class*="language-"]': {
    ...tomorrow['code[class*="language-"]'],
    fontFamily: null // inherit from css
  },
  'pre[class*="language-"]': {
    ...tomorrow['pre[class*="language-"]'],
    fontFamily: null // inherit from css
  }
};

SyntaxHighlighter.registerLanguage("jsx", jsx);

export const Hr = () => (
  <div
    css={{
      backgroundColor: "hsl(0, 0%, 90%)",
      height: 2,
      marginBottom: "2em",
      marginTop: "2em"
    }}
  />
);

export const Note = ({ Tag = "div", ...props }: { Tag?: string }) => (
  <Tag
    css={{
      color: "hsl(0, 0%, 40%)",
      display: "inline-block",
      fontSize: 12,
      fontStyle: "italic",
      marginTop: "1em"
    }}
    {...props}
  />
);

export const H1 = (props: any) => <h1 css={{ marginTop: 0 }} {...props} />;
export const H2 = (props: any) => <h2 css={{ marginTop: "2em" }} {...props} />;

export const ColorSample = ({
  name,
  color
}: {
  color: string,
  name: string
}) => (
  <div
    css={{
      display: "inline-flex",
      marginBottom: "0.5em",
      alignItems: "center",
      minWidth: "10em"
    }}
  >
    <span
      title={color}
      css={{
        marginRight: "0.5em",
        display: "inline-block",
        borderRadius: 3,
        width: "1em",
        height: "1em",
        backgroundColor: color
      }}
    />
    <Code>{name}</Code>
  </div>
);

// ==============================
// Code
// ==============================

export const Code = (props: {}) => (
  <code
    css={{
      backgroundColor: "rgba(38, 132, 255, 0.08)",
      // color: '#0747A6',
      fontSize: "85%",
      padding: "1px 5px 2px",
      borderRadius: 4
    }}
    {...props}
  />
);

type PreProps = { children: string, language: string };

export const CodeBlock = ({ children, language, ...props }: PreProps) => {
  return (
    <PrismLight
      language={language}
      style={customTomorrow}
      customStyle={{
        borderRadius: 4,
        fontSize: 13,
        marginBottom: "1em",
        marginTop: "1em",
        overflowX: "auto",
        WebkitOverflowScrolling: "touch"
      }}
      {...props}
    >
      {children}
    </PrismLight>
  );
};
CodeBlock.defaultProps = { language: "jsx" };
`

**Comment by shubhamgupta47** [comment]
`// @flow
/** @jsx emotionJSX */
import { jsx as emotionJSX } from "@emotion/core";

import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";
import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";

const customTomorrow = {
  ...tomorrow,
  'code[class*="language-"]': {
    ...tomorrow['code[class*="language-"]'],
    fontFamily: null // inherit from css
  },
  'pre[class*="language-"]': {
    ...tomorrow['pre[class*="language-"]'],
    fontFamily: null // inherit from css
  }
};

SyntaxHighlighter.registerLanguage("jsx", jsx);

export const Hr = () => (
  <div
    css={{
      backgroundColor: "hsl(0, 0%, 90%)",
      height: 2,
      marginBottom: "2em",
      marginTop: "2em"
    }}
  />
);

export const Note = ({ Tag = "div", ...props }: { Tag?: string }) => (
  <Tag
    css={{
      color: "hsl(0, 0%, 40%)",
      display: "inline-block",
      fontSize: 12,
      fontStyle: "italic",
      marginTop: "1em"
    }}
    {...props}
  />
);

export const H1 = (props: any) => <h1 css={{ marginTop: 0 }} {...props} />;
export const H2 = (props: any) => <h2 css={{ marginTop: "2em" }} {...props} />;

export const ColorSample = ({
  name,
  color
}: {
  color: string,
  name: string
}) => (
  <div
    css={{
      display: "inline-flex",
      marginBottom: "0.5em",
      alignItems: "center",
      minWidth: "10em"
    }}
  >
    <span
      title={color}
      css={{
        marginRight: "0.5em",
        display: "inline-block",
        borderRadius: 3,
        width: "1em",
        height: "1em",
        backgroundColor: color
      }}
    />
    <Code>{name}</Code>
  </div>
);

// ==============================
// Code
// ==============================

export const Code = (props: {}) => (
  <code
    css={{
      backgroundColor: "rgba(38, 132, 255, 0.08)",
      // color: '#0747A6',
      fontSize: "85%",
      padding: "1px 5px 2px",
      borderRadius: 4
    }}
    {...props}
  />
);

type PreProps = { children: string, language: string };

export const CodeBlock = ({ children, language, ...props }: PreProps) => {
  return (
    <PrismLight
      language={language}
      style={customTomorrow}
      customStyle={{
        borderRadius: 4,
        fontSize: 13,
        marginBottom: "1em",
        marginTop: "1em",
        overflowX: "auto",
        WebkitOverflowScrolling: "touch"
      }}
      {...props}
    >
      {children}
    </PrismLight>
  );
};
CodeBlock.defaultProps = { language: "jsx" };
`

**Comment by shubhamgupta47** [comment]
`import A from 'a`

**Comment by shubhamgupta47** [comment]
`
import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";
import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";

const customTomorrow = {
  ...tomorrow,
  'code[class*="language-"]': {
    ...tomorrow['code[class*="language-"]'],
    fontFamily: null // inherit from css
  },
  'pre[class*="language-"]': {
    ...tomorrow['pre[class*="language-"]'],
    fontFamily: null // inherit from css
  }
};

SyntaxHighlighter.registerLanguage("jsx", jsx);
`

**Comment by shubhamgupta47** [comment]
`
fsdf
`

**Comment by shubhamgupta47** [comment]
`import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";
import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";`

**Comment by shubhamgupta47** [comment]
`import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";`
`import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";`
`import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";`

**Comment by shubhamgupta47** [comment]
`import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";
import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";'

**Comment by shubhamgupta47** [comment]
```
import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";
import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";

```

**Comment by shubhamgupta47** [comment]
Just replace the initial few lines with this: 

```
import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";
import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";

const customTomorrow = {
  ...tomorrow,
  'code[class*="language-"]': {
    ...tomorrow['code[class*="language-"]'],
    fontFamily: null // inherit from css
  },
  'pre[class*="language-"]': {
    ...tomorrow['pre[class*="language-"]'],
    fontFamily: null // inherit from css
  }
};

SyntaxHighlighter.registerLanguage("jsx", jsx);

```

This would work.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by luanecavalcantizup** [comment]
> import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
> import jsx from "react-syntax-highlighter/dist/esm/languages/prism/jsx";
> import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/prism";
> 
> const customTomorrow = {
>   ...tomorrow,
>   'code[class*="language-"]': {
>     ...tomorrow['code[class*="language-"]'],
>     fontFamily: null // inherit from css
>   },
>   'pre[class*="language-"]': {
>     ...tomorrow['pre[class*="language-"]'],
>     fontFamily: null // inherit from css
>   }
> };
> 
> SyntaxHighlighter.registerLanguage("jsx", jsx);

didn't work.. would be very helpful if you have a link to a codesandbox of this example working.

**Comment by luanecavalcantizup** [comment]
here is the working example https://codesandbox.io/s/codesandboxer-example-forked-tzkog?file=/example.js

**Comment by ManglaSourav** [comment]
Importing style directly from a file worked for me as shown below
`import materialDark from 'react-syntax-highlighter/dist/esm/styles/prism/material-dark';`
