### ISSUE TITLE
Code is wrong in documentation for `getOptionLabel`

### ISSUE THREAD

**Issue by elijahcarrel** [JedWatson/react-select#3597]
On the `custom getOptionLabel function example` section of [this page](https://react-select.com/advanced#advanced), the code is incorrect— it is a copy of the `Custom SingleValue Example` on [this page](https://react-select.com/components). The demo adjacent to it does actually show the desired functionality, however I have no way of seeing the code that generated that demo.

Thanks for looking into it!

**Comment by bladey** [comment]
Thanks @elijahcarrel, this has now been resolved!
