### ISSUE TITLE
Get an empty value of string when type `Tab` or `Enter` in `onInputChange`

### ISSUE THREAD

**Issue by zhaoyi0113** [JedWatson/react-select#3601]
I am using `"react-select": "^2.4.3"`.

There are two parameters in `onInputChange` function. The first one is a string indicating what type via keyboard; the other one is an action can be one of `"set-value", "input-change", "input-blur", "menu-close"`. But I found the first parameter is always empty when I type in `Enter` or `Tab` and the `action` for both of them is `input-change`. I wonder how I different the two key `Tab` and `Enter` here?

```
onInputChange={(e: string, { action }) => {
        if (action === 'input-change') {
           // how do I know whether it is triggered by `Enter` or `Tab` here ?
        }
      }}
```

**Comment by themre** [comment]
use `onKeyDown`?

**Comment by zhaoyi0113** [comment]
Ok I see I can use `inputValue` to fix this issue.

**Comment by Sarafaniuk** [comment]
I made it this way 

             switch (event.key) {
		  	case 'Enter':
			case 'Tab':
				event.preventDefault()
                                  Your logic....
				break
			default:
				break
		}
