### ISSUE TITLE
v3 is not es5-compatible 

### ISSUE THREAD

**Issue by stnwk** [JedWatson/react-select#3602]
Hi.

I tried upgrade our codebase to use `3.0.3`.
We are using [es-check](https://github.com/dollarshaveclub/es-check) to make sure our compiled build is still es-5 compatible because we need to support IE11 and we do not transpile (we do **compile** them, but not transpile e.g.: change syntax) our `node_modules`.

Unfortunately this `es-check` tells us the latest version of `react-select` does not include es5-compatible code.

Any chance we can get this back working?
Thanks :)

**Comment by stnwk** [comment]
Is there anything I can do to help you with this? Would be great if we could fix it, otherwise we're stuck on an older version of `react-select` 😕

@gwyneplaine maybe?

**Comment by monners** [comment]
Having the same problem on IE11.

**Comment by TrySound** [comment]
Did you check something not working in IE? It may support some es6 features.
https://github.com/JedWatson/react-select/blob/master/.browserslistrc#L2

**Comment by stnwk** [comment]
@TrySound The issue i am reporting has nothing todo with es6 features. I am talking about **es6 syntax**, which IE11 is not able to parse - hence the output should be in es5 syntax as it was before. This does not mean we can't use es6 features though, those are two different things :)

**Comment by TrySound** [comment]
I mean IE supports some es6 features. https://kangax.github.io/compat-table/es6/#ie11
Which files exactly did you check? And does it really not work in IE or you fully rely on es-check?

**Comment by stnwk** [comment]
I just tried again and was not able to reproduce this anymore 🤷🏻‍♂️
Sorry for bothering, I will close this issue and re-open it should I encounter it again.

Thanks for your help & input, really appreciated!
