### ISSUE TITLE
Can't persist input value in multi selection component

### ISSUE THREAD

**Issue by zhaoyi0113** [JedWatson/react-select#3605]
I use below code which is from your demo code to render a multi selection select component. But what I found is that when I type any characters and leave the focus before select any items, the characters are not persisted.

```
import React from 'react';

import Select from 'react-select';
import makeAnimated from 'react-select/animated';
import { colourOptions } from '../data';

const animatedComponents = makeAnimated();

export default function AnimatedMulti() {
  return (
    <Select
      closeMenuOnSelect={false}
      components={animatedComponents}
      defaultValue={[colourOptions[4], colourOptions[5]]}
      isMulti
      options={colourOptions}
    />
  );
}
```

As an example of that, see below screenshot. I typed `f` and move the focus on other component. Then the `f` will be removed from the `select` component. Is there a way to persist the `f` when it loses focus?

![image](https://user-images.githubusercontent.com/3355579/58872128-ba7fc500-8706-11e9-8e46-5d8d61268a29.png)

**Comment by Rall3n** [comment]
Try managing the `inputValue` on your own and only update the state value if the action in the `actionMeta` is not `input-blur` or `menu-close`:

```
state = {
    inputValue: ""
}

handleInputChange= ( inputValue, actionMeta ) => {
    if (actionMeta.action !== 'input-blur' && actionMeta.action !== 'menu-close') {
        this.setState({ inputValue });
    }
}

<Select
    { /* ... */ }
    onInputChange={this.handleInputChange}
    inputValue={this.state.inputValue}
/>
```

**Comment by zhaoyi0113** [comment]
Yes, `inputValue` works. Thanks.
