### ISSUE TITLE
Removing options from Creatable crashes the app

### ISSUE THREAD

**Issue by akshithdayanand** [JedWatson/react-select#3606]
Hi, 
My app crashes if I enter ,then remove values and then enter values again in creatable Multi-select text input(Demo can be found in the official website) [Creatable](https://react-select.com/creatable) 

**react-select v3.0.3**

**Reproduction steps:**

Go to the link, scroll to bottom and enter some values in the Creatable Multi-select text input.

Now, remove all the values you entered.
Once done, try entering a new value.
It wont accept any value.

**Console error:** 
![image](https://user-images.githubusercontent.com/23196262/58878112-2145b400-86f0-11e9-8790-5727c6066e48.png)

**Comment by phanduy12214** [comment]
Hi, a little change from the example source code could work:

`this.setState({
          inputValue: '',
          value: !value ? [] : [...value, createOption(inputValue)],
});`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
