### ISSUE TITLE
Redirect gh-pages to react-select.com

### ISSUE THREAD

**Issue by corysimmons** [JedWatson/react-select#3608]
Google tends to direct me to https://jedwatson.github.io/react-select/

All the source links are broken and I'm certain you want to consolidate the docs to one site.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by corysimmons** [comment]
![image](https://user-images.githubusercontent.com/224636/83116650-10791580-a09a-11ea-9eb5-318466aadae3.png)

Still a problem. Still a 5 second fix.

**Comment by bladey** [comment]
Thanks for your reply @corysimmons.

**Comment by JedWatson** [comment]
oof, thanks for surfacing this @corysimmons (again!)

I just pushed a redirect to the `gh-pages` branch, so it should be all fixed now.

**Comment by corysimmons** [comment]
No worries. Thanks for all your contributions to the ecosystem! =)
