### ISSUE TITLE
defaultValue is not filling values when componentdidmount rendered

### ISSUE THREAD

**Issue by mouerrr** [JedWatson/react-select#3609]
https://codesandbox.io/s/reactcodesandboxerexample-hduf1

**Comment by Rall3n** [comment]
More a problem with not understanding lifecycle of React than this library. `defaultValue` is only used on to get the values on initial render. `componentDidMount` is called after the first render. Updates in there and all updates after that result in re-renders.

You are better off either setting the value in `constructor` or managing the value on your own using the `value` and `onChange` props.

**Comment by mouerrr** [comment]
Hi, @Rall3n thank you, i've used value and it's worked.

**Comment by emjeard** [comment]
@Mouerr Hi, can you show how to user defaultValue after componentDidMount?
