### ISSUE TITLE
Is it possible to use it with textarea?

### ISSUE THREAD

**Issue by PetrSnobelt** [JedWatson/react-select#361]
Hi, I'm looking for autosuggest for textarea, is it possible to use react-select as autocomplete for textarea and if so can you add example?

Thanks

**Comment by bruderstein** [comment]
Not currently - the menu is rendered directly as a child of the main <Select> component.

However, the input box is an [auto-size input box](https://github.com/JedWatson/react-input-autosize), so you could probably manage to emulate a textarea using the <Select> component with a bit of CSS. Whether that then would handle well as "auto-complete" is another question, you'd need to allow entry of values that aren't in the options (`allowCreate=true`), but then disable rendering the "Add [text i just entered]?" option. I'm not sure this is inline with the goals of the project, but I can't answer that.

**Comment by gwyneplaine** [comment]
with the new v2 components api, you are welcome to try and replace the input with component you choose, so long as it conforms with our expected interface. 

see docs for details http://react-select.com/components
