### ISSUE TITLE
Custom MultiValueRemove does not work when using `menuShouldBlockScroll`

### ISSUE THREAD

**Issue by akinorimiz** [JedWatson/react-select#3614]
Hi
I'm trying to use custom `MultiValue` and replace default close buttons. 
However, it does not seem to work with `menuShouldBlockScroll` and `onClick` event is never invoked.
Is this an intentional behavior?

Here is a reproductive example:
https://codesandbox.io/embed/react-codesandboxer-example-3v1cv

**Comment by ZhevnyakVladislav** [comment]
Hi, I have the same issue while I'm trying to implement custom MenuList with input. 
When I user menuShouldBlockScroll is set to true, there s additional component called ScrollBlock wrap my input and handle all click. I can't handle my custom input behavior.

**Comment by bladey** [comment]
Hi @akinorimiz and @ZhevnyakVladislav,

I wanted to check in and see if you were still encountering this issue. We're triaging issues at the moment to sustain the project going forward.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.
