### ISSUE TITLE
Styling ignored on iPad

### ISSUE THREAD

**Issue by GeorgeWL** [JedWatson/react-select#3616]
# Are you reporting a bug or runtime error?
Please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Styling seems to be ignored on iPad.

**Comment by GeorgeWL** [comment]
Annoyingly it might be caused by some strange interaction between modules, rather than this module on its own, cause I can't get it to repeat the same behaviour on a barebones example such as the codesnadbox above.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
