### ISSUE TITLE
Async Docs Wrong

### ISSUE THREAD

**Issue by sshaw** [JedWatson/react-select#3618]
[The docs](https://react-select.com/home#async) use:

* `import Async from 'react-select/async';`
* `import AsyncSelect from 'react-select/async';`

But this is wrong and results in an error. Should be: `import { Async } from 'react-select';`

**Comment by sk14235** [comment]
Which version are you using?

**Comment by sshaw** [comment]
2.4.4 and yes, I see the docs are for 3.0 but this is mentioned 0.0 places.

**Comment by travisanderson** [comment]
I'm getting this same issue...but version 3.0.4 .  I cannot use async as a result.

**Comment by bladey** [comment]
Hi all,

This is the only error I found - https://github.com/JedWatson/react-select/commit/d159051489b308508c116c1c7855edfc3c1f6adc

The rest of the examples are valid and working (in Codesandbox) - https://github.com/JedWatson/react-select/commit/d159051489b308508c116c1c7855edfc3c1f6adc

If you're still having issues, please let me know what your build environment is.
