### ISSUE TITLE
Why trigger onMenuOpen when handle input change?

### ISSUE THREAD

**Issue by Cedcn** [JedWatson/react-select#3620]
https://github.com/JedWatson/react-select/blob/98f469eeb34c689f2697ffabd43c920077130bbc/packages/react-select/src/Select.js#L1086  

#3335

**Comment by cutterbl** [comment]
Pretty standard, really. User experience expectation here would be to begin filtering the list of options, if you were to type directly in the Select.

**Comment by ktarasov-clearscale** [comment]
I don't agree. 
Event should be triggered once the menu is opened. 
Why trigger the event on input?
Regarding the `onInputChange` handler, it is useless and confusing.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
