### ISSUE TITLE
Update TS Typings for v3

### ISSUE THREAD

**Issue by rathpc** [JedWatson/react-select#3621]
Creating an issue for this so it doesn't get lost in the migration thread here: https://github.com/JedWatson/react-select/issues/3585#issuecomment-496216129

The typings need to be updated to reflect v3 as mentioned in that issue comment. Thank you!

**Comment by Methuselah96** [comment]
I made a PR to update the types: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36464.

**Comment by rathpc** [comment]
Typings have been updated and merged, closing this now
