### ISSUE TITLE
replacing 'Menu' component as a react-virtualized-list ? 

### ISSUE THREAD

**Issue by 29er** [JedWatson/react-select#3622]
Just a question if this could be done without completely hacking the lib.
my select list may contain 20K rows, no way it would perform unless I use something like 
react-virtualized-list (https://github.com/bvaughn/react-virtualized) to be the Menu component. 
anyone ventured into doing something like this ? 
I am assuming I won't be able to use react-select, but wanted to ask before I created a custom one.

**Comment by Vitall** [comment]
@29er maybe https://stackblitz.com/edit/react-select-v2-virtualized?file=index.js this will help you

**Comment by vctormb** [comment]
@Vitall is there a properly way to fix the arrow navigation using virtualized? If you try to navigate through the options with arrow up and down it won't work.

**Comment by Vitall** [comment]
@vctormb I not found it (((

**Comment by vctormb** [comment]
@bvaughn is there a way to do it? Btw I'm using react window with this solution proposed by @Vitall

**Comment by Vitall** [comment]
@vctormb this is not my solution I found it on github is same comment

**Comment by bladey** [comment]
Hi @29er,

I wanted to check in and see if you were still encountering this issue. We're triaging issues at the moment to sustain the project going forward.

**Comment by 29er** [comment]
gosh this was so long ago. I don't even remember how i fixed it :) sorry !

**Comment by bladey** [comment]
No problem @29er, thanks for replying. I'll close this for now.
