### ISSUE TITLE
[iOS] Incorrect Korean string composed in Safari

### ISSUE THREAD

**Issue by karlingen** [JedWatson/react-select#3623]
Korean strings aren't being composed properly when using a Multi-select text input.

See the example **Multi-select text input** on https://react-select.com/creatable on an iOS device (or simulator) using safari.

react-select: `v3.0.4`
react: `16.8.6`

**Steps to replicate:**
1. Using a Korean keyboard type *du* to compose: `여`. 
2. Press enter. A tag is created.
3. Type *d* to compose: `ㅇ`

**Expected result:**

The character `ㅇ` is in a new word.

![image](https://user-images.githubusercontent.com/2265452/59453205-60a18e00-8ddd-11e9-8d92-f4e352ec8eea.png)
**Actual result:**

The character `ㅇ` is appended to the last character of the previous tag. Tapping backspace shows the characters from previous tag.

![image](https://user-images.githubusercontent.com/2265452/59453228-731bc780-8ddd-11e9-83ed-b2dd720edbe3.png)

**Comment by ebonow** [comment]
Greetings again @karlingen ,

I decided to follow up on some of the other issues you were experiencing and it seems that this one may have been resolved as well. 

I tested using iPhone Simulator `iOS v12.4`, react-select `v3.1.1` and when reproducing the steps you laid out, I was able to achieve the expected result. Would you mind verifying on your end and if this appears to be working for you now, and if so, please feel free to close this.

<img width="640" alt="Screen Shot 2020-12-19 at 7 20 33 PM" src="https://user-images.githubusercontent.com/1007579/102703078-0e41f880-4230-11eb-886d-f206380be0e6.png">

**Comment by ebonow** [comment]
In an effort to close out stale issues, I will be closing this. This appears to be resolved, but please feel free to reply if there are any additional questions or concerns and we can reopen this if necessary.
