### ISSUE TITLE
[Android] Multi-select text input not clearing value after pressing enter using Korean keyboard

### ISSUE THREAD

**Issue by karlingen** [JedWatson/react-select#3624]
See the example **Multi-select text input** on https://react-select.com/creatable on an Android device (or simulator) using Chrome.

react-select: `v3.0.4`
react: `16.8.6`

**Steps to replicate:**
1. Using a Korean keyboard type *du* to compose: `여`. 
2. Press enter. 

**Expected result:**

A tag is created with the label `여` and the input is cleared.

![image](https://user-images.githubusercontent.com/2265452/59456034-6f8b3f00-8de3-11e9-855f-68e4362e8e09.png)

**Actual result:**

A tag is created with the label `여`. The input is not cleared.

![image](https://user-images.githubusercontent.com/2265452/59456025-67cb9a80-8de3-11e9-8830-76465aadaadf.png)

**Comment by ebonow** [comment]
Greetings @karlingen , 

I have finally gotten a VirtualBox Android x86 iso up and running and then obtained the Korean Input apk. After doing some testing, I have not been able to reproduce the error described.

<img width="780" alt="Screen Shot 2021-02-10 at 12 27 35 PM" src="https://user-images.githubusercontent.com/1007579/107568475-e28e1f80-6b9b-11eb-98a1-95a6dac8b77b.png">

I will be closing this issue, but if you find this still to be an issue, please provide some more details and we can re-open and further investigate.
