### ISSUE TITLE
react-select performance issue for above 71.0.3578.80 chrome versions

### ISSUE THREAD

**Issue by zafarn8** [JedWatson/react-select#3627]
Hi,
I am using the react-select library for multi-selection. In my case, I have a type-ahead functionality in which the user can type and select the respective item from the list. In the list there are more than 1800 values from that user can select multiple items. My question is I am facing the performance issue in updated Google chrome versions If you select multiple items or remove the item from the selected list its taking much time for adding and removing for above 71.0.3578.80 chrome versions.
If you run the same code in 71.0.3578.80 chrome version or below this version its work fast as well as Safari browser and FireFox its work fast in any version. But only the above version 71.0 of chrome it's taking much time. 
Can anyone help me understanding and resolving this issue? is it my code issue or browser?
and how can I resolve this issue?

any help will be appreciated thanks in advance.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
