### ISSUE TITLE
Remove focus onMouseOut/onMouseLeave

### ISSUE THREAD

**Issue by sandbox4013** [JedWatson/react-select#3628]
I want to clean highlighted item, when leave list. Is it possible?
Boonville was initial selected, Easton highlighted by mouseover(hover). Green square is cursor position afterall.
![image](https://user-images.githubusercontent.com/49528851/59521985-44354c80-8ed6-11e9-91de-f698623eb7b1.png)

(UPD)Desired result
![image](https://user-images.githubusercontent.com/49528851/59935321-3a6f9400-9456-11e9-9816-c2c3577888a5.png)

**Comment by sandbox4013** [comment]
I found, that focused value placed in state of Select component, in focusedOption property. 
Maybe, there is way to setState this property? For example:

  onMouseLeave: () => setState({ focusedOption: selectedValue[0] }). //Reset focus to selected item*

*SelectedValue - another property, array, of Select's state, which keeps currently selected item. 

![image](https://user-images.githubusercontent.com/49528851/60397099-eea5a480-9b51-11e9-97c8-69cd4ccff78f.png)

I've tried to setState from Select component itself, just for test, but no luck too. Also, I'm not sure how to handle onMouseLeave, but it's less concern than reset focused item. 
![image](https://user-images.githubusercontent.com/49528851/60398615-09cce000-9b63-11e9-88c0-9bdecbc50419.png)

Please, help!

**Comment by Balachandar-K** [comment]
Anyway to achieve this. Please help, I'm also have to remove the focus onMouseOut

**Comment by bladey** [comment]
Hi @sandbox4013,

I wanted to check in and see if you were able to resolve this. We're triaging issues at the moment to sustain the project going forward.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.

**Comment by sidharthancr** [comment]
@bladey I need this feature as well please

**Comment by 3A43Mka** [comment]
I managed to solve it like this:
![image](https://user-images.githubusercontent.com/47483531/100375213-1c786c80-3016-11eb-84c8-77996f2884de.png)
Modifying style for `option` element with `:hover` pseudo class and using `state.isSelected` to not affect selected option
However I think there is a better option to do this.

**Comment by naadiya-ahmed** [comment]
Need a solution for this too -- Remove focus onMouseOut/onMouseLeave

**Comment by Helen-Zhao** [comment]
@bladey I also need this please - the default behaviour is confusing

**Comment by stanimirgeorgiev** [comment]
@bladey I also need this issue solved. So please think about resolving it

**Comment by stanimirgeorgiev** [comment]
I found out a simple solution which is far from optimal but working:
```typescript
export const MyComponentSelect = () => {
    const [isMouseOverMenu, setIsMouseOverMenu] = useState(false);
    const MenuList = (props: MenuListProps<any>) => {
        return (
            <div onMouseEnter={() => setIsMouseOverMenu(true)} onMouseLeave={() => setIsMouseOverMenu(false)}>
                <components.MenuList {...props} />
            </div>
        );
    };
    const Option = (props: OptionProps<any>) => {
        let remappedProps = props;
        if (!isMouseOverMenu) {
            remappedProps = { ...remappedProps, isFocused: false };
        }

        return <components.Option {...remappedProps} />;
    };

    return <Select<any> components={{ MenuList, Option }} />;
};
```

**Comment by tasawernawaz** [comment]
> I found out a simple solution which is far from optimal but working:
> 
> ```ts
> export const MyComponentSelect = () => {
>     const [isMouseOverMenu, setIsMouseOverMenu] = useState(false);
>     const MenuList = (props: MenuListProps<any>) => {
>         return (
>             <div onMouseEnter={() => setIsMouseOverMenu(true)} onMouseLeave={() => setIsMouseOverMenu(false)}>
>                 <components.MenuList {...props} />
>             </div>
>         );
>     };
>     const Option = (props: OptionProps<any>) => {
>         let remappedProps = props;
>         if (!isMouseOverMenu) {
>             remappedProps = { ...remappedProps, isFocused: false };
>         }
> 
>         return <components.Option {...remappedProps} />;
>     };
> 
>     return <Select<any> components={{ MenuList, Option }} />;
> };
> ```

@stanimirgeorgiev I tried this it works, but the problem is keyboard navigation doesn't highlight the options until my mouse is not over the menu.

**Comment by stanimirgeorgiev** [comment]
@tasawernawaz Thanks for the update. I also found out that problem and added another fix for it so the solution is getting really out of balance :( but it's works (kind of). I will update my example to show the added solution. I also moved the event callbacks to the `Menu` wrapper component instead of the `MenuList`. After both fixes there is a problem when moving out from one option and entering in another the previous one blinks for a second and then the hovering woks as expected (with React 18).

**Comment by romakravchuk** [comment]
@stanimirgeorgiev thanks for solution.  I think we could even simplify it to this 

`
export const MyComponentSelect = () => {
    const [isMouseOverMenu, setIsMouseOverMenu] = useState(false);
    
    const Option = (props: OptionProps<any>) => {
        return <components.Option {...remappedProps} isFocused={isMouseOverMenu ? false : props.isFocused} />;
    };

    return <Select<any> 
                      components={{ MenuList, Option }} 
                      onMenuOpen={() => {setIsMouseOverMenu(true)}}
		     onKeyDown={() => {setIsMouseOverMenu(false)}} 
                />;
};
`

onMenuOpen and onKeyDown will do the trick instead of using onMouseOver

**Comment by phuhd-0935** [comment]
Same issue
