### ISSUE TITLE
Creatable: Allow spacebar input for Creatable Select

### ISSUE THREAD

**Issue by joshuahatcher** [JedWatson/react-select#3629]
My organization has just made the upgrade from React Select v1 to v2. For the most part, all is going smoothly; however, one use case that is tripping us up.

We are using Creatable select in a section of our app, allowing users to custom-create values that are not in the initial list of options. If a user types the spacebar as the first character in their custom-created option, rather than incorporate that into the string of text (i.e. `Create " "` it just automatically selects the first currently-highlighted option (I'm sure this is intentional - the Enter key provides this behavior as well, which I can understand is convenient).

I was able to override the selection of the currently-highlighted option by adding an `onKeyDown` handler to the select and checking if the keydown event's keyCode was 32 (and preventing default + calling the `onCreateOption` function if so). That works reasonable well, but it skips the prompt of the text creator and just adds an option with a single space. Ergo, if someone wanted to add an option with the a space followed by some text - e.g. `" sometext"` - they would be prevented from doing so. See below:

```
function handleKeyDown(e) {
  if (e.keyCode === 32) {
    e.preventDefault();
    handleCreateOption(' ');
  }
}

<ReactSelect.Creatable
  isMulti={true}
  onChange={(selections) => handleChange(selections)}
  // ...etc.
  onCreateOption{(inputValue) => handleCreateOption(inputValue)}
  onKeyDown={(e) => handleKeyDown(e)}
/>
```

I understand the relevance of making the space and enter keys automatically select the first option, but I wonder if there could be an override for this behavior built in so that a custom option beginning with a space could be allowed? For what it's worth, we were able to get this behavior on React Select v1 by using the `filterOptions` function.

Please forgive me if there is already a workaround for this issue - I have looked through the docs and worked through a solution for a while and wasn't able to find anything. Thanks in advance for the assistance.

**Comment by dhandley12** [comment]
If you would like the space keystroke to behave like any other character you can do the following:

` 
let ref;

  handleKeyDown = (e) => {
      if(e.keyCode === 32) {
         e.preventDefault();
         this.ref.onInputChange(this.ref.state.inputValue + " ", "set-value");
      }
   };

      <Creatable
               // ...etc.
               onKeyDown={(e) => this.handleKeyDown(e)}
               ref={ref => {
                  this.ref = ref;
               }}
            />

`

Just be sure to format the `div `tags created by the `Creatable` class all have the following css applied to them to ensure they display mutliple concurrent spaces properly ` white-space: pre;`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by gtaylor44** [comment]
> If you would like the space keystroke to behave like any other character you can do the following:
> 
> ```
>   let ref;
> 
>   handleKeyDown = (e) => {
>       if(e.keyCode === 32) {
>          e.preventDefault();
>          this.ref.onInputChange(this.ref.state.inputValue + " ", "set-value");
>       }
>    };
> 
>   <Creatable
>       // ...etc.
>      onKeyDown={(e) => this.handleKeyDown(e)}
>      ref={ref => {
>         this.ref = ref;
>      }}
>     />
> ```
> 
> Just be sure to format the `div `tags created by the `Creatable` class to all have the following css applied to them to ensure they display multiple concurrent spaces properly ` white-space: pre;`

Small improvement:
`if(e.keyCode === 32 && this.ref.state.inputValue !== "") ...`

Without the extra condition, the cusor position will jump to the end unexpectingly when you move cusor to a position before selectionEnd and press space bar.

**Comment by alioshr** [comment]
This does not seem to work on v5. I want to do exactly this on v5, but ref.onInputChange does not seem to exist anymore.

**Comment by alioshr** [comment]
I confirm that this still works on v5. The bad thing is that the type of the ref does not include these properties ` .state.inputValue`  `ref.onInputChange`, so I had to ignore types, but it still works.
