### ISSUE TITLE
Show single value with MultiValueContainer

### ISSUE THREAD

**Issue by spedy** [JedWatson/react-select#3634]
I wish to show only one selected option in Multi Value Select V2.

Here is my code:

```
<Select
    options=this.props.options
    value={this.props.value}
    isMulti
    hideSelectedOptions={false}
    components={{
        Option: ({children, ...innerProps}) => {
            return (
                <components.Option {...innerProps}>
                    {this.optionRenderer(innerProps.data)}
                </components.Option>
            );
        },
        MultiValue : ({children, ...innerProps}) => {
            return (
                <components.MultiValueContainer {...innerProps}>
                    {children}
                </components.MultiValueContainer>
            )
        },
        MultiValueLabel: ({children, ...innerProps}) => {

            return (
                <components.MultiValueLabel {...innerProps}>
                    {this.showOnlyFirst(innerProps.data)}
                </components.MultiValueLabel>
            );
        }
    }}
    autoFocus={this.props.autoFocus}
/>
```

Why is the MultiValue returned as many times as there are values?

Shouldn't the MultiValueContainer be mapped over all of the values and MultiValue called only once?

Where can I put my check if there is more than one value selected, only render that single one... and not all of the values?

**Comment by Gsiete** [comment]
As written in the documentation, the MultiValue is used for **each** of the selected values:
> ### MultiValue
> Component used to display a selected option in the input when isMulti is true. 

What might work (I say might among other reasons because I'm not sure about all the details of what you need to implement), would be to make MultiValue return null when the option is not the first
```
        MultiValue : ({children, ...innerProps}) => {
            return this.isFirst(innerProps.data) 
                ? (
                    <components.MultiValueContainer {...innerProps}>
                        {children}
                    </components.MultiValueContainer>)
                : null;
        },```

**Comment by spedy** [comment]
@Gsiete Yeah in the end I went with a similar approach to yours. Worked fine thanks!
