### ISSUE TITLE
Up/down keys not working on iOS (safari)

### ISSUE THREAD

**Issue by karlingen** [JedWatson/react-select#3635]
The down arrow key to open the menu doesn't work on an iPad Pro with an external keyboard.
You also can't browse through the available options once you've manually opened the menu by tapping on the input. 

1. Using an iPad or iPhone with an external keyboard (or simulator on a mac), goto https://react-select.com/creatable
2. Tap the input inside the **Creatable Multiselect Example**
3. Press arrow down on your keyboard

**Expected behavior**
Menu opens and you can keep on pressing arrow down or up to browse through available options.

**Actual behavior**
The menu stays closed and nothing happens

**Comment by anhpt-bss** [comment]
hello, are you resolve it?

**Comment by anhpt-bss** [comment]
hello, are you resolved it?

**Comment by ebonow** [comment]
Greetings @karlingen ,

Created a [codesandbox](https://codesandbox.io/s/react-select-keyboard-arrow-check-keydown-iexhd) to log keydown presses.

Trying this in a simulator with iOS reveals that that Safari is or something else is hijacking the arrow clicks whenever a text input is focused and that these key presses work fine when not on the input.

Additionally, it is worth noting that the left and right arrow keys act as home/end keys in that it puts the cursor at the start or end of the text, but it still does not fire a keydown event. This further justifies that it seems to be doing weird things.

I did do a bit more research and found that this is not an isolated incident and there are other stackoverflow posts essentially saying the same thing. One thread I found informative was [here](https://github.com/gitpod-io/gitpod/issues/311) but it doesn't appear to be resolved when I tested it.

Not quite sure how to proceed with this. If Tim Cook says iOS users shouldn't use arrow keys in an input, who are we argue? :)

Im open to closing this, given the nature of the mobile environment choosing not to support arrow key down events. Im open to other feedback or consideration.

**Comment by karlingen** [comment]
@ebonow Thanks for your reply.
 
Apple must've fixed that odd behaviour on iOS 13.5 and 14, because I'm not seeing this issue on those versions. 
I'm only seeing it on iOS 12.4 and below.

Can you please confirm that you did your testing on a device running iOS < 13?

**Comment by ebonow** [comment]
@karlingen Confirmed. My iOS version is 12.4. If you are reporting that it works appropriately for later software versions, then thankfully it sounds like they may have resolved it. 

I think it is reasonable to close this issue especially if you are reporting that it is working now for new versions and that this is rooted in iOS. Thoughts?

**Comment by karlingen** [comment]
@ebonow Thanks. Yes, let's close this one :)

**Comment by ebonow** [comment]
Awesome! Thanks for your patience on this and for your prompt responses. I appreciate it.
