### ISSUE TITLE
Can not run npm test

### ISSUE THREAD

**Issue by whizsid** [JedWatson/react-select#3636]
When I run the `npm run test` in terminal it gives me an error like `(Cypress:31192): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused` and not opening the browser too. This is the full error

```
> cypress run --spec ./cypress/integration/select_spec.js


(Cypress:31192): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused
Cypress could not verify that the server set as your 'baseUrl' is running:

  > http://localhost:8000/cypress-tests

Your tests likely make requests to this 'baseUrl' and these tests will fail if you don't boot your server.

Please start this server and then run Cypress again.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @react-select/monorepo@1.0.0 test:cypress: `cypress run --spec ./cypress/integration/select_spec.js`
npm ERR! Exit status 1

```
My npm version is 6.9.0 and node version is v12.2.0. OS is ubuntu. I am running it behind the proxy

**Comment by barbalex** [comment]
Seems to me:
1. this is an issue happening in cypress, not in react-select
2. the error says exactly what is wrong: cypress could not connect to a server at the baseUrl provided by you

Did you check
- that the baseUrl is correct?
- that the server is running when you start cypress?
