### ISSUE TITLE
Flow error in Async : property onInputChange is missing

### ISSUE THREAD

**Issue by aanchalgera** [JedWatson/react-select#3637]
I just upgraded to v3 and I get this error in flow -
`Cannot create AsyncSelect element because property onInputChange is missing in props [1] but exists in
AsyncProps [2].
`
 
Is it a mandatory prop now?

**Comment by webskin** [comment]
I have the same error. In Async.js we have :
```javascript
export type AsyncProps = {
  /* The default set of options to show before the user starts searching. When
     set to `true`, the results for loadOptions('') will be autoloaded. */
  defaultOptions: OptionsType | boolean,
  /* Function that returns a promise, which is the set of options to be used
     once the promise resolves. */
  loadOptions: (string, (OptionsType) => void) => Promise<*> | void,
  /* If cacheOptions is truthy, then the loaded data will be cached. The cache
     will remain until `cacheOptions` changes value. */
  cacheOptions: any,
  onInputChange: (string, InputActionMeta) => void,
  inputValue?: string,
};
```

(https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Async.js#L24)

It seems that it is not used for the moment :

https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Async.js#L112

The workaround is to set :

`onInputChange={() => {}}`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
