### ISSUE TITLE
Adding an apply and cancel button in a react-select. Also prevent the selected one's from appearing in the top

### ISSUE THREAD

**Issue by velsonjr** [JedWatson/react-select#3638]
Is there any way I can implement this adding of apply and cancel buttons and then not to display selected one's at the top section. I am planning to use it for column wise filtering.Values that match the selected one's should get filtered.

Something like this: https://codesandbox.io/embed/ecstatic-waterfall-e87xz

But dont want to display the selected one's at the top

**Comment by BugsBunny338** [comment]
I'm as well interested in adding apply and cancel buttons. Any thoughts?
