### ISSUE TITLE
Is there a way to group multi-select values like how they are grouped in menu?

### ISSUE THREAD

**Issue by jayjaydluffy** [JedWatson/react-select#3640]
How do you think we can attain this, e.g. _Stress_ and _Fatigue_ are Challenges etc. and they should be "grouped" in ValueContainer?

![image](https://user-images.githubusercontent.com/13216855/59855324-5b2ce080-93a7-11e9-850b-2cfa7d5245ae.png)

Grouping options is supported out-of-the-box but I would like to show multi-values being grouped according to their groupings as options in menu. Can that be achieved by customizing MultiValue component? Can anyone please help?

**Comment by chilander1** [comment]
@jayjaydluffy Have you solved this? can you provide some example?

**Comment by bladey** [comment]
Hi @jayjaydluffy,

I wanted to check in and see if you were still encountering this issue. We're triaging issues at the moment to sustain the project going forward.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.
