### ISSUE TITLE
[Android] Option is not selected when pressing enter

### ISSUE THREAD

**Issue by karlingen** [JedWatson/react-select#3641]
See the example **Creatable Multiselect Example** on https://react-select.com/creatable on an Android device (or simulator) using Chrome.

Possible reason: `autocomplete="off"` is not respected.
If the user turns off autosuggestion in their keyboard settings, the enter button works.

react-select: `v3.0.4`
react: `16.8.6`
chrome: `75.0.3770.101`

**Steps to replicate:**
1. Add some text inside the input
2. Press enter. 

**Expected result:**

A tag is created and Input is cleared.

**Actual result:**

Tag is not created. The entered text is still visible in the input.

**Comment by karlingen** [comment]
Temporary workaround: 
```tsx
private onKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter') {
        document.dispatchEvent(new Event('compositionend'));
    }
}
```

[This guy](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L1210) is for some reason still false although the user is done editing.

**Comment by ssmereka** [comment]
👍 I'm seeing this same issue.

**Comment by ebonow** [comment]
Greetings, 

I am not able to replicate this issue in version 4.1 as I have tested in both the Chrome simulator and also in an Android virtual machine. @karaggeorge  or @ssmereka if either of you are able to still reproduce we can re-open this, but at this time it appears this is working as intended.

**Comment by FrancisLeigh** [comment]
Happening for moi.
