### ISSUE TITLE
Reset Values

### ISSUE THREAD

**Issue by shilpasingla** [JedWatson/react-select#3647]
There is no handle in multiselect component to reset value/chips. Resetting prop value/values to null/undefined/[]/"" does not work.

**Comment by shilpasingla** [comment]
Also when using MultipleSelect component onChange works for first value and not for the second time if we specify value or values prop.

**Comment by snyaggarwal** [comment]
any updates on this guys?

**Comment by DamieUk** [comment]
same issue..

**Comment by akharkhonov** [comment]
same

**Comment by Sankozi** [comment]
It does not work with undefined but works with null for me. Simple example - "Clear" button does not works. If undefined is changed to null everything works. 
```
class SelectTest extends Component<{}, any> {
    state = {} as any;

    render(): React.ReactNode {
        console.log("selected: ", this.state.selected)
        return <div>
            <ReactSelect
                options={[{value: "abc", label: "abc"}, {value: "hello", label: "hello"}, {value: "world", label: "world"}]}
                value={this.state.selected}
                onChange={newValue => {this.setState({selected: newValue})}}
            />
            <button type="button" onClick={evt => this.setState({selected: undefined})}>Clear</button>
        </div>
    }
}
```

**Comment by ShaileshInfyom** [comment]
any update on this?

**Comment by Rall3n** [comment]
> It should definitely work with undefined too.

**Bad practice on your end**. `undefined` is used to determine if a component is [controlled or not](https://reactjs.org/docs/forms.html#controlled-components). Vanilla React components (`<input>`, `<select>`) will raise an exception if you set the value to `undefined` (or even `null`). The `Select` component in this library will gracefully change to being uncontrolled.

-----
For the rest of the issue: I can´t see the problem. Using `null` or `[]` works as excepted.

**Comment by ebonow** [comment]
I am unable to reproduce this issue. Please refer to this [codesandbox](https://codesandbox.io/s/react-select-clear-multi-null-empty-9x5b9?file=/src/App.js) and let me know if you are somehow still experiencing an inability to clear the multiSelect setting the value to either `null` or `[]`
