### ISSUE TITLE
did not match className

### ISSUE THREAD

**Issue by arsendev** [JedWatson/react-select#3649]
Hello, I'm currently working on [next.js + react]. The problem here is [react-select], which works well, but it's a warning to the console. 
`[Warning: Prop 'className' did not match. Server: "cs-1g6gOOi" Client: "cs-w8afj7-Input"] `
continues to appear. Is there a solution? This is my code below.
```
<Select
  instanceId='gabrielflorit'
  name="department"
  className={joinStyle.select}
  classNamePrefix="select"
  options={country.array}
  placeholder={t('account.SELECT_COUNTRY')}
  onChange={e => conturySelectFocus(e)}
/>
```
![warning](https://user-images.githubusercontent.com/51102399/60061547-89f0e100-9730-11e9-9919-50b832f3bf25.PNG)

**Comment by tafelito** [comment]
dup of #3590

**Comment by maciejmatu** [comment]
@arsendev hope this helps https://github.com/JedWatson/react-select/issues/3590#issuecomment-517621520

**Comment by arsendev** [comment]
@maciejmatu 
I'm sorry I checked late. Oh, as an example shown, className did not match error does not occur. Thank you~!!

**Comment by mitchellhamilton** [comment]
This is fixed in newer versions of emotion: https://github.com/JedWatson/react-select/issues/3590#issuecomment-521861353
