### ISSUE TITLE
TypeError: __webpack_require__.i(…) is not a function in React-Select

### ISSUE THREAD

**Issue by shashankshahplutus** [JedWatson/react-select#3653]
I am using react-select plugin for multiple selection from dropdown.

For installation i have done

`npm install react-select --save`

which installed latest version 3.0.4 of react-select plugin

My code is
```

import React, { Component } from 'react';
import Select from 'react-select';

import urls from '../../../urls.json';

const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' },
];
class Reports extends Component {

  constructor(props) {
    super(props);

    this.state = {
      selectedOption: null,
    };

  }
  handleChange = selectedOption => {
    this.setState({ selectedOption });
    console.log(`Option selected:`, selectedOption);
  };
  componentDidMount() { }

  render() {

    return (
      <div>
        <div className="row">
          <div className="col-md-12">
            <h2>Reports</h2>
            <hr className="title-separator" />
            <Select
                value={this.state.selectedOption}
                onChange={this.handleChange}
                options={options}
            />
          </div>
        </div>
      </div >
    )
  }
}

export default Reports;
```

![image](https://user-images.githubusercontent.com/29222301/60253991-b81a2080-98ea-11e9-84c7-c5fe654796b3.png)
Please help!

**Comment by sobrinho** [comment]
Same issue here.

**Comment by SourabhRanka** [comment]
Same issue here

**Comment by mrstalon** [comment]
Same issue

**Comment by LucidNinja** [comment]
I had this issue because I started my proejct in Codesandbox. When I downloaded the project, I realised that they use an older version of React by default. Updating to the latest version of React (16.8.6) resolved the issue for me.

**Comment by bladey** [comment]
Thanks for the feedback @LucidNinja!

@shashankshahplutus, @sobrinho, @SourabhRanka, @mrstalon does this happen to solve the issue for you?

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone can provide further feedback, the issue will be re-opened.
