### ISSUE TITLE
Element selection and multi element remove doesn't work in Jira Simple Search

### ISSUE THREAD

**Issue by dluksza** [JedWatson/react-select#3654]
This issue is specific for react-select, embedded in Atlassian Jira Simple Search filed.

In ScriptRunner for Jira you can define custom script fields that can be included in various places of Jira. All the select based fields (like Issue Picker or Database Picker) are backed by `react-select`.

Recently we discovered that select components doesn't fully work in place, the Simple Search page. One can use keyboard to select elements from the dropdown menu (using arrow keys and enter) and clicking on remove all also works. But all the click actions on option(s) and single element remove are ignored.

I've spend a lot of time trying to find the root cause of this. I found that `onMouseDown` event is called for both actions (option selection and single element removal), it cancels the event propagation. But then (only in this context) `onClick` is not called. The react internal `noop` function is called, but it is not followed by `dispatchInteractiveEvent`. Don't know why click event is getting _lost_.

The workaround for us, was to provide custom `Component` and `MultiElementRemove` components that register `onMouseUp` callback that would call `innerProps.onClick`/`removeProps.onClick`. But this will execute `onClick` function twice in other areas.

**Comment by ebonow** [comment]
Greetings @dluksza  and sorry for the extremely late reply. I would be willing to bet that others (like myself) don't necessarily have the same level of context with react-select as they do Jira. I think you may have better luck getting a response to this in a different area, but before going too much further with this, simply wanted to ask if this is still an issue for you?

If so, I can try to get this in front of someone who may have more knowledge about it.

**Comment by ebonow** [comment]
Closing this, but happy to redirect these questions to others who might be better able to answer the question regarding the scope and association with Jira.
