### ISSUE TITLE
focused option starting at the selected option

### ISSUE THREAD

**Issue by csantos1113** [JedWatson/react-select#3656]
Seems that on **v3.0.0** there was a change introduced in the way the focused option is determined.

✅ **Here is an example of how it worked on v2.4.4: https://codesandbox.io/s/react-codesandboxer-example-sywkk**

![2019-06-27 15 26 48](https://user-images.githubusercontent.com/9648559/60294750-13024680-98f0-11e9-9e05-a201b41b376c.gif)

- Selected option ==> Blue background ==> "Purple" option
- Focused option ==> Light blue ==> Starts in "Purple" option and you could move from there.

Which is the same as the behavior of the native select inputs:
![2019-06-27 15 33 24](https://user-images.githubusercontent.com/9648559/60295145-03373200-98f1-11e9-9583-dcf98c8df418.gif)

----

❌ **Here is the same exact example running on v3.0.4: https://codesandbox.io/s/react-codesandboxer-example-3cutx**

![2019-06-27 15 30 52](https://user-images.githubusercontent.com/9648559/60294999-a471b880-98f0-11e9-96d5-828ad62514b8.gif)

- Selected option ==> Blue background ==> "Purple" option
- Focused option ==> Light blue ==> Starts in "Ocean" option.

----

Not sure if this is an issue, or if it was a change intentional made.
But, how can I get the focused option starting at the selected option?

**Comment by ankush29** [comment]
solved #bb9c1d7

**Comment by csantos1113** [comment]
Thanks @ankush29 - will be fixed on PR https://github.com/JedWatson/react-select/pull/3652

**Comment by guiyep** [comment]
Hello, 

I still this error happening in 3.0.4. Any idea when this is going to be merged?

Thanks for the good work!
Guiyep

**Comment by dicrescenzoa** [comment]
> Thanks @ankush29 - will be fixed on PR #3652

Waiting for this fix 👍 as well

**Comment by imnikij** [comment]
Hey @csantos1113 I am getting same error on v2.4,4, are you sure this occurs only for v3.0.0 and above ? Any fix for this ?

**Comment by guiyep** [comment]
Hello, Any update on this?

I still see this happening in 3.0.8.

Thanks!

**Comment by carlosriveroib** [comment]
yes, still happening in 3.0.8. Will you update this?

**Comment by nsobolev** [comment]
Go update, please! :)

**Comment by Gabriellvs60** [comment]
property theme defines the option colors...

export const StyledDropdown = styled(Select).attrs({
  menu: true,
  styles: {
    container: (e: any) => ({
      ...e,
      width: "100%"
    }),
    control: (e: any) => ({
      ...e,
      cursor: "pointer",
      width: "100%",
      border: "none",
      borderRadius: "0",
      
    }),
  
    valueContainer: (e: any) => ({
      ...e,
      padding: "11.5px 15px"
    }),
    menu: (e: any) => {
      return {
        ...e,
        borderRadius: 0,
        zIndex: "15",
        background: "white"
      };
    }
  },
  theme: (theme: any) => ({
    ...theme,
    borderRadius: 25,
    colors: {
      ...theme.colors,
      primary: colors.lipstick,
      primary25: "rgba(197, 31, 41, 0.25)",
      primary50: "rgba(197, 31, 41, 0.5)",
      primary75: "rgba(197, 31, 41, 0.75)"
    }
  })
} as Props)<typeof Select>`

**Comment by Zorak070** [comment]
This issue is still prevailing. Any solutions till now?

**Comment by dicrescenzoa** [comment]
> This issue is still prevailing. Any solutions till now?

this was the [PR](https://github.com/JedWatson/react-select/pull/3652) related to this issue, It seems that this it's taking more than a year to be resolved. I think that would be better to move on another library: 

https://github.com/furqanZafar/react-selectize/

**Comment by asazernik** [comment]
This seems to have been fixed in #3868 (though @andreme reports there's still a bug in the fix). Can we close this out?

**Comment by csantos1113** [comment]
Yes, let's close this.

I forked my own example and updated to latest react-select version `3.1.0` and it's working as expected now: https://codesandbox.io/s/react-codesandboxer-example-pcfsi

Thanks

**Comment by samselfridge-cnc** [comment]
If anyone is still running into this in 5.1.0, its because the object being passed into value isn't the same value from the options list.

@alexmnv pointed this out [here: ](https://github.com/JedWatson/react-select/issues/3648#issuecomment-537854271)

See [this sandbox, forked from the one above](https://codesandbox.io/s/react-codesandboxer-example-forked-smcv12?file=/example.js)

This didn't work for my use case sadly, but hoping it helps others in the future.
