### ISSUE TITLE
When click outside of the select, the select don't close

### ISSUE THREAD

**Issue by stanislaw7** [JedWatson/react-select#3657]
When I select one option from an select that has `isMulti` prop the select don't close when i click outside him.

Here's an example of the code that I'm using
`<Select 
            value={value}
            isMulti={multi ? true : false}
            className="select"
            classNamePrefix="select"
            isDisabled={editable ? false : true}
            placeholder='Selecione um valor'
            noOptionsMessage={() => ('Sem mais opções')}
            isSearchable={search ? true : false}
            closeMenuOnSelect={multi ? false : true}
            isClearable={false}
            onMenuOpen={() => setVisible(true)}
            onMenuClose={() => setVisible(false)}
/>
`

**Comment by FullMoon04** [comment]
How about using `menuIsOpen` prop?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
