### ISSUE TITLE
first add value in creatable multi select text input and then remove. Again add, there is a error in conole

### ISSUE THREAD

**Issue by ankush29** [JedWatson/react-select#3658]

**Comment by ankush29** [comment]
<img width="1440" alt="Screenshot 2019-06-29 at 9 50 36 PM" src="https://user-images.githubusercontent.com/11795347/60386883-db92c600-9ab8-11e9-91cf-70e319659a77.png">

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
