### ISSUE TITLE
'react-select' does not contain an export named 'components'.

### ISSUE THREAD

**Issue by JosipTomaic** [JedWatson/react-select#3659]
Hi,

I have followed the example for creating custom MenuList:

`import React from 'react';

import Select, { components } from 'react-select';
import { colourOptions, groupedOptions } from '../data';

const menuHeaderStyle = {
  padding: '8px 12px',
  background: colourOptions[2].color,
  color: 'white',
};

const MenuList = props => {
  return (
    <components.MenuList {...props}>
      <div style={menuHeaderStyle}>Custom Menu List</div>
      {props.children}
    </components.MenuList>
  );
};

export default () => (
  <Select
    defaultValue={colourOptions[1]}
    options={groupedOptions}
    components={{ MenuList }}
  />
)`

but I get an error:
`'react-select' does not contain an export named 'components'.`

Any suggestion why is this happening?

Best regards,
Thanks

**Comment by acrawford13** [comment]
Have you made sure you're using the latest version? As far as I recall there was no `components` export in v1. If your `package.json` says you're on v2, maybe try re-installing your packages?

**Comment by mvattuone** [comment]
I am also experiencing this, using v2 or v3. 🤷‍♂

**Comment by bladey** [comment]
Hi @JosipTomaic and @acrawford13,

I can't reproduce this issue in a Codesandbox using the code from @JosipTomaic.

See here - https://codesandbox.io/s/react-select-v3-sandbox-j45l9?file=/example.js

Are you still experiencing the issue?

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone can provide further feedback, the issue will be re-opened.
