### ISSUE TITLE
setValue same value display bug

### ISSUE THREAD

**Issue by khankuan** [JedWatson/react-select#366]
setValue with the same value causes `value` to be rendered on input instead of `label`. Affects resetValue.

**Comment by bruderstein** [comment]
I've probably not understood correctly what you mean here - are you calling setValue() on the instance and getting the wrong thing displayed?  I can't replicate this in a test, maybe you can tell me what I'm missing? See the tests at https://github.com/bruderstein/react-select/commit/6a8b945e99d52e02af879df345f24c055c7d9de0

**Comment by khankuan** [comment]
Realised bug was indirectly caused by using number values (already fixed here: 670cc09085ced8c1dd524a08e34c218fd1d0cb20)
