### ISSUE TITLE
Scroll on touchscreen not working when used in atlaskit/modal

### ISSUE THREAD

**Issue by FabioWanner** [JedWatson/react-select#3661]
I'm trying to use react-select in a atlaskit/modal (as described in the documentation [react-select/portaling](https://react-select.com/advanced#portaling)). Everyting works fine except scrolling the list of options with finger or pen on a touch screen. 

[Codepen Example](https://codesandbox.io/s/react-select-in-modal-96wty?fontsize=14)

**Versions used:**
"react-select": "3.0.4"
"@atlaskit/modal-dialog": "10.0.6"

**Comment by slofurno** [comment]
Had the same issue, looks like atlaskit was actively blocking touch scroll events

https://github.com/jossmac/react-scrolllock#touchscrollable

you can pass a custom menu component into react select to fix this

https://react-select.com/components

```javascript
const Menu = props => (
  <components.Menu {...props}>
    <TouchScrollable>
      {props.children}
    </TouchScrollable>
  </components.Menu>
)
```

**Comment by FabioWanner** [comment]
Thank you very much! This solves the problem!

Here the complete [Codepen Example](https://codesandbox.io/embed/react-select-in-modal-mtmks?fontsize=14) for anyone interested.
