### ISSUE TITLE
Need to add a class to options

### ISSUE THREAD

**Issue by peacepostman** [JedWatson/react-select#3667]
Hello, our use of react-select has a conflict with fastClick, how can we add a `.needsclick` class to each option easily ?

Best regards,

**Versions used:**
react-select 3.0.4
react 16.8.6

**Comment by EthanhBradburry** [comment]
Hi did you find a solution to this? Same boat

**Comment by peacepostman** [comment]
Hello, yes i've used the custom component implementation which can be found in doc. Simply adding the class in it solved our problem 😁
