### ISSUE TITLE
access hidden input via ref

### ISSUE THREAD

**Issue by SAudelOG** [JedWatson/react-select#367]
i´m trying to post my form via ajax, so i need to access the value of the hidden input via ref with React.findDOMElement, is it possible?

**Comment by bruderstein** [comment]
You get any changes via the `onChange()` call, normally you'd keep the new value somewhere (usually in state in a higher level component), and then use the same value in the `value` prop to react-select.  The first parameter to `onChange()` is the exact same value that is in the hidden field. 

Is that enough, or do you still need access to the field?

**Comment by SAudelOG** [comment]
ok! thanks i was a little confused but i see, it's better to save the state of the hidden input, instead of use ref to get its value.
