### ISSUE TITLE
Width is calculated wrong

### ISSUE THREAD

**Issue by mayarelmohr** [JedWatson/react-select#3672]
I have used react-select and it's an awesome library. but sometimes the dropdown appears collapsed like this.

<img width="388" alt="Screen Shot 2019-07-07 at 10 50 42 PM" src="https://user-images.githubusercontent.com/6134846/60773740-fcd36200-a109-11e9-8061-cd25e8847b01.png">

This issue happens on chrome. It's fixed when page is refreshed 

Your help is appreciated!

**Comment by TriStarGod** [comment]
How did you resolve this?
