### ISSUE TITLE
Change arrow and hide stick

### ISSUE THREAD

**Issue by HulioEglesias** [JedWatson/react-select#3678]
How can I hide a stick(in a blue square)? And Can I change an arrow(in a red square)?
![image](https://user-images.githubusercontent.com/15662060/61037897-680c8500-a3e5-11e9-977b-e37070664d4f.png)

**Comment by kkkrist** [comment]
That's what the `dropdownIndicator` and `indicatorSeparator` style props are for:

```jsx
<Select
  styles={{
    indicatorSeparator: () => {}, // removes the "stick"
    dropdownIndicator: defaultStyles => ({
      ...defaultStyles,
      color: 'purple' // your changes to the arrow
  })
  {...otherProps}
/>
```

**Comment by HulioEglesias** [comment]
Can I change blue to red?
![image](https://user-images.githubusercontent.com/15662060/61042916-8f1b8480-a3ee-11e9-9a02-1d03b59676be.png)

**Comment by kkkrist** [comment]
Well, the default arrow is an svg image. You can hide it via:

```jsx
<Select
  styles={{
    indicatorSeparator: () => {}, // removes the "stick"
    dropdownIndicator: defaultStyles => ({
      ...defaultStyles,
      '& svg': { display: 'none' }
    })
  }}
  {...otherProps}
/>
```

and then maybe construct an arrow out of the indicatorContainer-div pseudo-elements like we used to back in the day, like so:

```javascript
dropdownIndicator: defaultStyles => ({
  ...defaultStyles,
  '& svg': { display: 'none' }
  '&:after': {
    border: '…',
    transform: 'rotate(…)'
  }
})
```

and so on. You'll figure it out :-)

**Comment by Rall3n** [comment]
You can replace the dropdown icon using the [components framework](https://jedwatson.github.io/react-select). An example of another icon in use and how it is achieved can be found in the [documentation](https://jedwatson.github.io/react-select) or [here](https://github.com/JedWatson/react-select/blob/master/docs/examples/CustomDropdownIndicator.js).

**Comment by andyford** [comment]
@Rall3n thanks for that. BTW all the "(Source)" links on that documentation page https://jedwatson.github.io/react-select/ go to 404s

**Comment by mwei2018** [comment]
You can refer to https://codesandbox.io/s/react-codesandboxer-example-zl6zg
![image](https://user-images.githubusercontent.com/2967082/72600976-8680a980-394f-11ea-8199-7fd9df9df508.png)

**Comment by maleja111** [comment]
Is it possible to change the position of the dropdownIndicator to the right?

**Comment by mksbnt** [comment]
> Is it possible to change the position of the dropdownIndicator to the left?

`
   <Select isRtl="true" />
`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by mihailsitnic** [comment]
https://gist.github.com/mihailsitnic/528491b1460b6805452ebe0f8b8c825b
