### ISSUE TITLE
To move input text to left

### ISSUE THREAD

**Issue by HulioEglesias** [JedWatson/react-select#3679]
Now I have space before input text(like a padding-left), How can I remove this space?
![image](https://user-images.githubusercontent.com/15662060/61054541-14ac2e00-a409-11e9-8542-7c30ad2a0d88.png)

**Comment by dancherb** [comment]
Also having this issue - did you find anything? Have tried clearing margin, padding etc. on everything I swear. @HulioEglesias

**Comment by dancherb** [comment]
Continued trying alignItems, alignSelf, textAlign, width etc. with no luck. The following in my styles object did the job, though not pretty from a code perspective:

```
 singleValue: (provided, state) => ({
                ...provided,
                marginLeft: 0,
                position: "absolute",
                left: 0
            }),
        
            placeholder: (provided, state) => ({
                ...provided,
                marginLeft: 0,
                position: "absolute",
                left: 0
            }),
            
            input: (provided, state) => ({
                ...provided,
                marginLeft: 0,
                position: "relative",
                left: -8
            }),
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
