### ISSUE TITLE
Different component props for different options

### ISSUE THREAD

**Issue by rgllm** [JedWatson/react-select#3688]
Hello.

It is possible with the `components` props to use different components for different options? 
I want to render a component for the first select option and a different one for the others.

Is this possible?

Thanks.

**Comment by bladey** [comment]
Hi @rgllm,

I wanted to check in and see if you found a solution to this, or if it's still something you need solved. We're triaging issues at the moment to sustain the project going forward.

**Comment by rgllm** [comment]
Hi @bladey.

Yes, I found a solution. I changed the MenuList component and rendered inside the way I wanted.

```
        <components.MenuList {...props}>
          <div className="first">
          </div>
          {props.options.length > 1 && (
            <div className="more">
            </div>
          )}
        </components.MenuList>
```

**Comment by bladey** [comment]
Thanks for sharing the solution @rgllm, much appreciated!
