### ISSUE TITLE
onMenuOpen opens the menu instead of just listen

### ISSUE THREAD

**Issue by julianCast** [JedWatson/react-select#3693]
If we use the **onMenuOpen()** method, the select menu will be opened instead of  just (as I undertood) listen to the open menu event.

https://codesandbox.io/s/react-codesandboxer-example-8exw2

**Comment by bladey** [comment]
@JedWatson is this intended?

**Comment by Methuselah96** [comment]
Instead of calling `ref.select.onMenuOpen()` you should be passing your listener into the `onMenuOpen` prop. That should get the behavior you desire.
