### ISSUE TITLE
value property behavior question

### ISSUE THREAD

**Issue by jonfreedman** [JedWatson/react-select#3695]
Since v2 it's been possible to use your own object shape for options/values, could you please confirm if the example [here](https://codesandbox.io/s/react-codesandboxer-example-j5isr?from-embed) is the correct behavior? e.g. it's not possible to set the value if you're not using an object as a value type?

**Comment by jayesh-bhoot** [comment]
My problem is probably similar. If I pass to `value` prop one of the `options[i].value` (a string in my case), it does not work.

This does not work:
```
            <Select
                options={[
                    {label: 'hello', value: '1'},
                    {label: 'world', value: '2'}
                ]}
                onChange={(x) => console.log('x', x)}
                value={'1'}/>
```

But this works

```
            <Select
                options={[
                    {label: 'hello', value: '1'},
                    {label: 'world', value: '2'}
                ]}
                onChange={(x) => console.log('x', x)}
                value={{label: 'hello', value: '1'}}/>
```

Is this the expected behaviour? Or am I doing something wrong?

**Comment by jonfreedman** [comment]
> Is this the expected behaviour? Or am I doing something wrong?

I believe it's expected, the types for [value](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L245) and [options](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/types.js#L71) are supposed to be the same shape, but dealing with the fact that you can select multiple values.

My question is really around whether OptionType has to be an object, as most of the library is functional when it's just a string.

**Comment by eddiemonge** [comment]
> I believe it's expected, the types for value and options are supposed to be the same shape, but dealing with the fact that you can select multiple values.

Why in the world would it be that instead of being the actual value???

**Comment by jonfreedman** [comment]
I assume its for legacy reasons to remain as close to backwards compatible with the original version which was designed to have separate display label and underlying value but restricted to strings.

Interestingly the Material-UI project now has its own auto-complete control rather than recommending this project so there may be a tail off in popularity.

As you can see no committer has actually answered this...

**Comment by ebonow** [comment]
Greetings, 

As mentioned above, the `value` prop expects an object with a value property on it.

ie: 
🚫 `value = {1}` 
✅ `value={{value: 1, label: 'one' }}`

The "simple value" you are referring to is a legacy method that existed in version 1, but depreciated when moving to version 2.

You can read more about it [here](https://github.com/JedWatson/react-select/issues/3063) and [here](https://github.com/JedWatson/react-select/issues/2920) if you are interested in the background history of it. We also have a discussion section which can be better used to discuss feature requests which can be used to shape the direction of future features.
