### ISSUE TITLE
Diacritics search optimization

### ISSUE THREAD

**Issue by M-Yankov** [JedWatson/react-select#3696]
Hi,

I have cases when I need to load a lot of information in the `react-select` dropdown (~3000-5000 entries). All of them are translated in French, German, Spanish etc. (_depending on the context_).
When I start searching (typing), the dropdown hangs and not showing the characters immediately. I've found a solution for quicker response from the dropdown with improving part of the diacritics logic:
- https://u04u1.codesandbox.io/ (_https://codesandbox.io/s/react-select-demo-typing-diacritics-u04u1_)

The issue can tested with quick typing the word `cathedrale` and then deleting it with holding down backspace. 
The demo works with 5081 items with random french words.
The first dropdown has the default behavior, the second one has the improvement. The target of this example is to achieve better performance in the case with big lists with options that contains diacritics (characters with tilde).

The solution still is not the best, but I think it demonstrates better performance.

Sources:
- [select2 js line 300 replace character logic](https://github.com/select2/select2/blob/master/src/js/select2/defaults.js#L300)
- [select2 js the structure of the diacritics](https://github.com/select2/select2/blob/master/src/js/select2/diacritics.js)
- https://jsperf.com/diacritics/18
- [current logic for diacritics](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/filters.js)

I've tried to build the examples from docs, but a lot of `module not found` errors appeared. Also all of the tests failed pretending that `Enzyme` was not configure. If someone add some guidelines and advice how to easy build, run and add tests, I could add `pull request`

**Comment by bladey** [comment]
Hi @M-Yankov,

It appears PR https://github.com/JedWatson/react-select/pull/4034 might have solved this - which will be released shortly.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by M-Yankov** [comment]
@bladey  In which version to expect the new functionality?

**Comment by bladey** [comment]
@M-Yankov it's been merged into master, so I expect it will be in the next version which will be v3.1.1 or v3.2.0, it should be released next week - https://github.com/JedWatson/react-select/releases
