### ISSUE TITLE
React Select UI is distorted in the production webpack build when imported from a shared components library.

### ISSUE THREAD

**Issue by mridulsikka141090** [JedWatson/react-select#3698]
Hi,
I am facing with a grave issue here. I have created a shared components library which contains components using react-select dropdown.
While importing and using these components from library in another application, the react select reusable component works fine in development build but in production, the ui is distorted.
The options have either transparent background or the menu dropdown is automatically on the top section without providing the placement prop to it.
I am attaching some snippets to show for production build.
![Production](https://user-images.githubusercontent.com/44138483/62194850-f76cde80-b37a-11e9-98a2-ad426db7313f.png)
![Development](https://user-images.githubusercontent.com/44138483/62194851-f76cde80-b37a-11e9-9b6d-8fe2dc642ea1.png)

**Comment by anguspiv** [comment]
I am having a similar issue, where it always places the menu on top in a production build, but development build works fine. 

I am creating my Component Library using styled-components, and Rollup. react-select is installed as a peer dependency but seems to be always built into the final component library too. 

Here is my rollup config:

```
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import progress from 'rollup-plugin-progress';
import { terser } from 'rollup-plugin-terser';
import visualizer from 'rollup-plugin-visualizer';
import multiEntry from 'rollup-plugin-multi-entry';
import babel from 'rollup-plugin-babel';

import pkg from './package.json';

const deps = Object.keys(pkg.dependencies || {});

const peerDeps = Object.keys(pkg.peerDependencies || {});

const external = deps.concat(peerDeps);

const commonPlugins = [
  babel({
    exclude: /node_modules/,
  }),
  commonjs({
    include: /node_modules/,
    extensions: ['.mjs', '.js', '.jsx', '.json', '.node'],
    namedExports: {
      react: [
        'Component',
        'PureComponent',
        'Fragment',
        'Children',
        'createElement',
        'cloneElement',
        'createContext',
      ],
      'react-is': ['isElement', 'isValidElementType', 'ForwardRef'],
    },
  }),
  resolve({
    customResolveOptions: {
      moduleDirectory: 'node_modules',
    },
  }), // so Rollup can find `ms`
  multiEntry(),
  terser(),
  progress(),
  visualizer({
    filename: './docs/statistics.html',
    title: 'Brix',
    template: 'treemap',
  }),
];

const globals = {
  react: 'React',
  'prop-types': 'PropTypes',
  'styled-components': 'styled',
  polished: 'polished',
  'styled-reset': 'reset',
  'query-string': 'qs',
  'react-select': 'Select',
  'react-select/async': 'AsyncSelect',
  'react-dom': 'ReactDOM',
  'react-compound-slider': 'Slider',
};

export default [
  {
    input: 'src/**/index.js',
    output: [
      {
        name: 'brix',
        file: pkg.browser,
        format: 'umd',
        globals,
      },
      {
        file: pkg.main,
        format: 'cjs',
        globals,
      },
      {
        file: pkg.module,
        format: 'es',
        globals,
      },
    ],
    plugins: commonPlugins,
    external,
  },
];
```

But I am not sure what would be causing the issue

**Comment by jjstobbe** [comment]
I am experiencing the same issue. React-select dropdowns will open downwards on development builds, but will open upwards on production builds.

**I'm using webpack and it appears that using the `devTools` option of `cheap-module-eval-source-map` fixes the issue for me.**

The production build was using just `source-map` for that option and it was broken.

I have no idea why source-maps would be causing this issue. A more legitimate fix would be very much so appreciated.

**Comment by jjstobbe** [comment]
I dug a bit deeper down this rabbit-hole and found that it's mostly a fault of webpack's production minimizer. If you use the `UglifyJsPlugin` instead, everything works as expected.

i.e. in your webpack config
```
optimization: {
    minimizer: [ new UglifyJsPlugin() ],
}
```

**Comment by bladey** [comment]
Hi all -

Thanks for your assistance @jjstobbe, it's greatly appreciated.

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open the issue if necessary.

**Comment by MaorBenAmi** [comment]
UglifyJsPlugin is deprecated - any other suggestions?

**Comment by Methuselah96** [comment]
@MaorBenAmi It would be very helpful if you could create a sample repository demonstrating the issue.
