### ISSUE TITLE
There is no placeholder for CreatableSelect component

### ISSUE THREAD

**Issue by souuu** [JedWatson/react-select#3699]
Hello,
I'm asking why we don't have the placeholder option for a CreatableSelect component :( .
Thank you,

**Comment by Rall3n** [comment]
@souuu Can not confirm. The `placeholder` prop is still working with a `Creatable` component in `v3.0.4`.

**Comment by kiranbhalerao123** [comment]
Also not working on `async-creatable` in `v3.0.4`.

**Comment by Rall3n** [comment]
Could one of you ( @kiranbhalerao123 or @souuu ) provide a small reproducible example of this issue? Saying it won’t work does not help in this case.

**Comment by kiranbhalerao123** [comment]
Initially the placeholder is there but when clearing selected option, it disappears.
Here is my code. 
**"react-select": "^3.0.4"**

`import AsyncSelect from 'react-select/async-creatable' `

 ` <AsyncSelect
      isClearable={true}
      cacheOptions={true}
      loadOptions={loadOptions}
      defaultOptions={true}
      isMulti={isMulti}
      name="search"
      value={selected}
      onChange={onChange}
      onCreateOption={onCreateOption}
      placeholder={placeholder}
    />`

**Comment by kiranbhalerao123** [comment]
oh, it was my fault. I was updating the selected option to `{ label: null, value: null }` while clearing it. instead of  `null`.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
