### ISSUE TITLE
getOptionValue seems to be used both for the keys of multiselect, as well as for the returned value.

### ISSUE THREAD

**Issue by nanderv** [JedWatson/react-select#3700]
It would be nice to have a getOptionKey property, which sets the key when using multiple select. Currently, if I use objects as values, then I get ```[Object object]``` as a key, which isn't unique.

**Comment by Rall3n** [comment]
@nanderv It would be helpful if you could provide a minimal reproducable example.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
