### ISSUE TITLE
Unable to access demos/documentation on https://react-select.com/

### ISSUE THREAD

**Issue by benuleau** [JedWatson/react-select#3701]
I'm looking into some select libraries and react-select seems like a good fit for my needs; however, I can't access https://react-select.com/ to view demos or documentation. When I try to get to the site I'm presented with a 503 status code. After looking through similar issues (#2978), I tried going to https://react-select.netlify.com/ but this is also giving me a 503. Was this site moved or is there any workaround that will allow me to access the site?

**Comment by bichotll** [comment]
It's actually working for me.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
