### ISSUE TITLE
Cannot find file: 'react-select.browser.esm.js'

### ISSUE THREAD

**Issue by aakhan89** [JedWatson/react-select#3710]
when I starting my react server, I get the following.

`Cannot find file: 'react-select.browser.esm.js' does not match the corresponding name on disk: '.\node_modules\react-select\Creatable\dist\creatable'.`

**package.json**
"react-select": "^3.0.4",

**Comment by aakhan89** [comment]
@JedWatson @gwyneplaine 

Just tested with "react-select": "^3.0.3", same issue facing with "^3.0.3" version,

Can you please help out urgently

**Comment by aakhan89** [comment]
Sorry for inconvenience I had a mistake with **Import,** going to close this one

**Comment by tmacdonald** [comment]
@aakhan89 Can you please explain what the issue with your import was and how you resolved it? I'm running into a similar issue.

**Comment by aakhan89** [comment]
Just import 
```
import React from 'react';
import Select from 'react-select';
```

Package.json

"react-select": "^3.0.4",
