### ISSUE TITLE
formatGroupLabel Flow Types Error

### ISSUE THREAD

**Issue by webskin** [JedWatson/react-select#3711]
Flow generates this error when using `formatGroupLabel` returning a ReactComponent :

```sh
> flow "check"

Error ---------------------------------------------------------------------- src/components/StackSelectComponent.js:93:5

Cannot create `AsyncSelect` element because `React.Element` [1] is incompatible with string [2] in the return value of
property `formatGroupLabel`.

   src/components/StackSelectComponent.js:93:5
            v------------
    93|     <AsyncSelect
    94|       defaultValue={defaultValue}
    95|       isMulti={props.isMulti}
    96|       components={animatedComponents}
    97|       name="stacks"
    98|       cacheOptions
    99|       defaultOptions
   100|       loadOptions={promiseOptions}
   101|       className="basic-multi-select"
   102|       classNamePrefix="select"
   103|       formatGroupLabel={formatGroupLabel}
   104|       onInputChange={() => {}}
   105|     />
            -^

References:
   src/components/StackSelectComponent.js:46:3
          v-------------------------
    46|   <div style={groupStyles}>
    47|     <span style={spanStyles}>{data.label}</span>
    48|     <span style={groupBadgeStyles}>{data.options.length}</span>
    49|   </div>
          -----^ [1]
   node_modules/react-select/src/builtins.js:5:53
     5| export const formatGroupLabel = (group: GroupType): string => group.label;
                                                            ^^^^^^ [2]

```

builtins.js says that it must return a String :

https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/builtins.js#L5

![image](https://user-images.githubusercontent.com/1107719/62700968-76998c80-b9e3-11e9-8cba-472ac75de0f3.png)

And this builtin is used as type :

https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L138

![image](https://user-images.githubusercontent.com/1107719/62700946-6c778e00-b9e3-11e9-81e7-abe6a1e51517.png)

**Comment by webskin** [comment]
The workarround is to use `$FlowFixMe` comment :

```javascript
const formatGroupLabel = data => (
  // $FlowFixMe
  <div style={groupStyles}>
    <span style={spanStyles}>{data.label}</span>
    <span style={groupBadgeStyles}>{data.options.length}</span>
  </div>
);
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
