### ISSUE TITLE
closeMenuOnSelect is not respected on a <label> tag with htmlFor set

### ISSUE THREAD

**Issue by stilllife00** [JedWatson/react-select#3713]
Here's the codesandox to reproduce: https://codesandbox.io/s/react-codesandboxer-example-oxe6v

Because I have a custom <label> element with the attribute `htmlFor` set, the menu does not closes when clicking on the label. It does close when clicking the checkbox. I am not sure if I am wrongly passing the props down to the custom Option though.

**Comment by bladey** [comment]
Hey @stilllife00,

Your example has `closeMenuOnSelect` as false, I updated your example here - https://codesandbox.io/s/react-codesandboxer-example-kgfu6

Seems to work fine for me, let me know if it doesn't!
