### ISSUE TITLE
Deprecated lifecycle method warnings with React 16.9

### ISSUE THREAD

**Issue by GreenGremlin** [JedWatson/react-select#3715]
The following warning is shown upon upgrading to React 16.9.0:

```
    Error: Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
    
    * Move code with side effects to componentDidMount, and set initial state in the constructor.
    * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
    
    Please update the following components: Select in src/tests.entry.js (line 294578)
```

**Comment by nukbal** [comment]
I've got similar warning related to this one
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

      * Move data fetching code or side effects to componentDidUpdate.
      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

      Please update the following components: AutosizeInput, Select
```

**Comment by jairusd** [comment]
That means you have component using legacy lifecycle OR you are using a library which uses the legacy lifecycle, I don't see this as an issue, in fact, it is helpful to identify legacy code and warn you when you do use libraries that do still.

**Comment by TrySound** [comment]
@jairusd react-select is the library with legacy methods.

**Comment by rj-david** [comment]
@JedWatson, since react 16.9.0 started to show a warning for deprecated lifecycles, is it possible that you create a patch release with a quick fix of renaming the deprecated lifecycles in order to remove the warning.

I've created a pull request (PR) for this: https://github.com/JedWatson/react-select/pull/3716

Note that this is just a quick fix for now to remove the warnings. It still requires a fix to move the code from the deprecated lifecycles to other related lifecycles.

Thanks

**Comment by jairusd** [comment]
oh sorry guys i was drunk when i made that comment

**Comment by tonix-tuft** [comment]
What about running `npx react-codemod rename-unsafe-lifecycles`, will it work for libraries installed in `node_modules`?

**Comment by rj-david** [comment]
@tonix-tuft, I doubt if it would. If it does, it will be overwritten on your next `npm ci` or `npm install`

**Comment by rj-david** [comment]
By the way, my PR was merged to master. Just waiting for the next release

**Comment by alfred-pb** [comment]
@rj-david  thanks!

**Comment by metamn** [comment]
@tonix-tuft I've run `npx react-codemod rename-unsafe-lifecycles` and it didn't solved the problem. At least at my end.

```
cs@cs-swift:~/work/react-best-practices$ npx react-codemod rename-unsafe-lifecycles
? On which files or directory should the codemods be applied? .
? Which dialect of JavaScript do you use? JavaScript
Executing command: jscodeshift --verbose=2 --ignore-pattern=**/node_modules/** --parser babel --extensions=jsx,js --transform /home/cs/.npm/_npx/30639/lib/node_modules/react-codemod/transforms/rename-unsafe-lifecycles.js .
Processing 45 files... 
Spawning 3 workers...
Sending 15 files to free worker...
Sending 15 files to free worker...
Sending 15 files to free worker...
 SKIP src/components/LoadingData/LoadingData.js
 SKIP src/components/Link/Link.stories.js
 SKIP src/components/Repeat/Repeat.js
 SKIP src/components/LoadingDataApiAxios/LoadingDataApiAxios.js
 SKIP src/components/Link/index.js
 SKIP src/components/LoadingDataApiAxios/index.js
 SKIP src/components/Repeat/Repeat.stories.js
 SKIP src/components/Repeat/index.js
 SKIP src/components/Reset/Reset.stories.js
 SKIP src/components/Reset/Reset.js
 SKIP src/components/Logo/Logo.js
 SKIP src/components/LoadingDataGraphQLApollo/LoadingDataGraphQLApollo.js
 SKIP src/components/Logo/Logo.stories.js
 SKIP src/components/Reset/index.js
 SKIP src/components/Logo/index.js
 SKIP src/components/LoadingDataApiAxios/LoadingDataApiAxios.stories.js
 SKIP src/components/LoadingData/LoadingData.stories.js
 SKIP src/components/LoadingDataGraphQLApollo/LoadingDataGraphQLApollo.stories.js
 SKIP src/components/SemanticHTML/SemanticHTML.stories.js
 SKIP src/components/LoadingData/index.js
 SKIP src/components/LoadingDataGraphQLApollo/index.js
 SKIP src/components/Meta/Meta.stories.js
 SKIP src/components/LoadingDataGraphQLApollo/apolloClient.js
 SKIP src/serviceWorker.js
 SKIP src/App.js
 SKIP src/components/Meta/Meta.js
 SKIP src/components/Meta/index.js
 SKIP src/index.js
 SKIP src/components/SemanticHTML/SemanticHTML.js
 SKIP src/hooks/index.js
 SKIP src/components/SemanticHTML/index.js
 SKIP src/components/TypographicGrid/TypographicGrid.stories.js
 SKIP src/hooks/useData.js
 SKIP src/components/Description/Description.js
 SKIP src/components/Description/Description.stories.js
 SKIP src/components/Description/index.js
 SKIP src/components/TypographicGrid/TypographicGrid.js
 SKIP src/components/TypographicGrid/index.js
 SKIP src/hooks/useMarkdown.js
 SKIP src/hooks/useQuery.js
 SKIP src/components/Home/Home.js
 SKIP src/hooks/useDataAPI.js
 SKIP src/components/Home/Home.stories.js
 SKIP src/components/Link/Link.js
 SKIP src/components/Home/index.js
All done. 
Results: 
0 errors
0 unmodified
45 skipped
0 ok
Time elapsed: 1.500seconds 
```

**Comment by metamn** [comment]
@tonix-tuft I ran `npx react-codemod rename-unsafe-lifecycles` where the warning was shown `node_modules/react-dom` ... but no results:

```
cs@cs-swift:~/work/react-best-practices/node_modules/react-dom$ npx react-codemod rename-unsafe-lifecycles
? On which files or directory should the codemods be applied? .
? Which dialect of JavaScript do you use? JavaScript
Executing command: jscodeshift --verbose=2 --ignore-pattern=**/node_modules/** --parser babel --extensions=jsx,js --transform /home/cs/.npm/_npx/31217/lib/node_modules/react-codemod/transforms/rename-unsafe-lifecycles.js .
Processing 36 files... 
Spawning 3 workers...
Sending 12 files to free worker...
Sending 12 files to free worker...
Sending 12 files to free worker...
 SKIP index.js
 SKIP profiling.js
 SKIP server.js
 SKIP server.node.js
 SKIP server.browser.js
 SKIP test-utils.js
 SKIP unstable-fizz.browser.js
 SKIP unstable-fizz.js
 SKIP unstable-fizz.node.js
 SKIP unstable-native-dependencies.js
 SKIP umd/react-dom-unstable-fizz.browser.development.js
 SKIP cjs/react-dom-unstable-fizz.browser.development.js
 SKIP umd/react-dom-unstable-fizz.browser.production.min.js
 SKIP cjs/react-dom-unstable-fizz.browser.production.min.js
 SKIP cjs/react-dom-unstable-fizz.node.development.js
 SKIP cjs/react-dom-unstable-fizz.node.production.min.js
 SKIP umd/react-dom-test-utils.production.min.js
 SKIP cjs/react-dom-test-utils.production.min.js
 SKIP umd/react-dom-unstable-native-dependencies.production.min.js
 SKIP cjs/react-dom-unstable-native-dependencies.production.min.js
 SKIP cjs/react-dom-server.browser.production.min.js
 SKIP umd/react-dom-server.browser.production.min.js
 SKIP cjs/react-dom-server.node.production.min.js
 SKIP cjs/react-dom-test-utils.development.js
 SKIP umd/react-dom-test-utils.development.js
 SKIP cjs/react-dom-unstable-native-dependencies.development.js
 SKIP umd/react-dom-unstable-native-dependencies.development.js
 SKIP cjs/react-dom-server.browser.development.js
 SKIP cjs/react-dom.profiling.min.js
 SKIP cjs/react-dom.production.min.js
 SKIP cjs/react-dom-server.node.development.js
 SKIP umd/react-dom.production.min.js
 SKIP umd/react-dom.profiling.min.js
 SKIP umd/react-dom-server.browser.development.js
 SKIP cjs/react-dom.development.js
 SKIP umd/react-dom.development.js
All done. 
Results: 
0 errors
0 unmodified
36 skipped
0 ok
Time elapsed: 17.457seconds 
```

**Comment by ShajiKesavan** [comment]
even using this "npx react-codemod rename-unsafe-lifecycles" ,the warning still persists..what shouls i do to avoid this warning?

**Comment by rj-david** [comment]
@gwyneplaine when can we expect this for a new release? Thanks

**Comment by rj-david** [comment]
@zhenyu0519, is that package a dependency of this package?

**Comment by zachsa** [comment]
what about a way of just suppressing warnings? I'm sad that my component library is not completely up-to-date. But having a cluttered console during development makes me even sadder

**Comment by zachsa** [comment]
oops. wrongs repo...

**Comment by zachsa** [comment]
> @zhenyu0519, is that package a dependency of this package?

Sorry. I don't know what I was thinking. It's not.

**Comment by graue** [comment]
Thanks @gwyneplaine for merging #3716. Would you mind cutting a release with the change?

Also, is there any chance you're in touch with Jed and could help us get a similar fix for his other project, https://github.com/JedWatson/react-input-autosize/issues/163?

**Comment by chaudharykiran** [comment]
I have same warning. I re-implement my component using react hooks but the warning is still showing. Anyone have same issue. These warning should not be shown in functional component.

**Comment by blairmorris** [comment]
+1 to hoping for a release soon to get rid of these. We've cleared out all of ours in our app, but waiting for all these dependencies to catch up so I can reclaim my console again.

**Comment by denyo** [comment]
I just forked the repo and published a new package: https://www.npmjs.com/package/@denyo/react-select

**Comment by ranneyd** [comment]
@denyo your solution has this same issue:

https://github.com/JedWatson/react-select/pull/3487#issuecomment-533386290

So we need to fix this one too:
https://github.com/JedWatson/react-input-autosize

**Comment by leantide** [comment]
Hmmm, so the suggestion is to leave the original 17K star react-select with a trickle of support and jump over to a fork which will itself will incorporate a temporary fork of react-input-autosize which will receive how much maintenance? 

I personally will either wait on this repo to get over this hump or remove my dependency on react-select altogether. But that is just me.

**Comment by ranneyd** [comment]
@leantide my idea is switch to the fork with the fix in it, hard-code the version number (no `^`) so aren't subsequent updates I accidentally install, monitor this (and the other) threads,  and when they finally actually fix this repo switch back.

**Comment by leantide** [comment]
@ranneyd I wish you all the best. This is about the 5th library I've run into fundamental maintenance issues with. I am slowly learning that not all github stars are equal as many can be legacy stars. I need to reduce my dependencies.

**Comment by ranneyd** [comment]
@leantide I feel your pain, and I'm considering something similar. It's unfortunate because this is a very nice lib otherwise.

**Comment by ranneyd** [comment]
https://github.com/JedWatson/react-input-autosize/pull/166

**Comment by leantide** [comment]
I was able to fix this by migrating my project away from react-select. But it is not without sadness.

**Comment by marksark** [comment]
@JedWatson any updates on this issue? I don't think it's sustainable to keep this for a long term project if this issue won't be resolved :/

**Comment by JedWatson** [comment]
Hey everyone, sorry for the delay here. fwiw we do put a lot of time into maintaining this project, although this particular issue with the warnings in console caught us up.

The warnings should have been fixed comprehensively in the latest releases of both `react-select` and `react-input-autosize`. If you're still seeing problems, maybe try ensuring you've updated your dependencies in your `package.json` (and make sure you don't have old versions of either library specified in your lockfiles - that can cause older versions to be installed when you are expecting to be on latest)

**Comment by LeDinhPhuc** [comment]
"npx react-codemod rename-unsafe-lifecycles"  not support for node_module ???

**Comment by chinaqinxin** [comment]
这个是因为引入的库存在使用旧的生命周期么，我已经改写组建内部的生命周期了，还是报一个warring，怎么才可以解决
