### ISSUE TITLE
iOS - Native footer bar always displays ?

### ISSUE THREAD

**Issue by ohnomycocoa** [JedWatson/react-select#3724]
On iOS whenever you tap on the drop down, the native iOS footer bar is shown with two arrows and a 'Done' button. Is there any way to suppress this as it's less than ideal ?

![image](https://user-images.githubusercontent.com/20493269/63373284-8ae46e80-c37f-11e9-8efe-f492beb252c9.png)

**Comment by anhpt-bss** [comment]
hello, are you resolve it?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
