### ISSUE TITLE
async select fire loadOptions as user types

### ISSUE THREAD

**Issue by Kashio** [JedWatson/react-select#3725]
I'm trying to use fire loadOptions of async select as the user types so to bring new options from a server, and enable the user to choose the desired option like so:
```
    const onAddressChange = useCallback(value => {
        setAddress(value);
    }, [setAddress]);

    const onAddressSelect = useCallback(({value}, {action}) => {
        if (action === 'clear') {
            setAddress('');
        } else {
            setAddress(value);
        }
    }, [setAddress]);

    const getAddresses = useCallback(() => {
        return LocationService.find(address || '')
            .then(records => records.map(record => ({
                label: record.name,
                value: record.name
            })));
    }, [address]);

            <AsyncSelect
                value={{
                    label: address,
                    value: address
                }}
                onInputChange={onAddressChange}
                onChange={onAddressSelect}
                loadOptions={getAddresses}
                isClearable/>
```

My problem is that after I choose an option from the dropdown and the select is blurred then the `onInputChange` is called again for some reason with an empty string causing `address` to reset. Not sure what's causing this?

**Comment by Hyperkid123** [comment]
@Kashio that is because the input value is changed to empty string after you select something from the dropdown.

You should probably handle this scenario on your side.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
