### ISSUE TITLE
Display both Clear Indicator and Loading Indicator

### ISSUE THREAD

**Issue by stearruda** [JedWatson/react-select#3732]
There was an issue created a long time ago about that - #4 -, but I think it's not in this version any more.

I'm trying to make it work in an Asynchronous Select, but I don't know where to change in the code.

And in general how the position of Loading Indicator can be changed when the component is asynchronous? I feel that it has a fixed position for this specific situation.

**Comment by bladey** [comment]
Hi @stearruda!

I wanted to check in and see if this was still an issue for you. We're going through issues and triaging at the moment to see what needs attention.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone can provide further feedback, the issue will be re-opened.
