### ISSUE TITLE
Menu does not follow component when scrolling

### ISSUE THREAD

**Issue by matiosfree** [JedWatson/react-select#3734]
Hey guys. I found the issue when I'm adding these 2 props:
`
menuPosition="fixed"
portalPlacement="auto"
`

Then I open the menu and start scrolling the main scroll (not the menu scroll).
The menu stays in the same place. 
Ex.: https://codesandbox.io/s/react-codesandboxer-example-39q8c

I expect the menu to follow the main component.

PS. I'm using this Sekect in material-ui Dialog with long item list, that's why I need menuPosition="fixed" prop.

**Comment by benkindt** [comment]
Yes, this is buggy. The position is calculated only when hovering the dropdown again.
Related to #3349 & #3313

**Comment by benkindt** [comment]
A workaround for this is to block scrolling with 
`menuShouldBlockScroll={true}`

**Comment by samthomson** [comment]
@matiosfree Out of interest, why do you need a `fixed` position?
Asking as I just solved this by changing from `fixed` to `absolute`, and can't see any other difference (hoping I amen't breaking anything..).

**Comment by ranihorev** [comment]
@benkindt `menuShouldBlockScroll={true}` also blocks scrolling within the menu :(

**Comment by srinivasmerugu** [comment]
@benkindt As @ranihorev pointed the workaround provided by you menuShouldBlockScroll={true} blocks scrolling within the menu. 

Mostly, we are using react-select with portals ( menuPortalTarget={document.body}) on modals and slideIns.
 
Could you please let us know in which version of react-select the bug  #3734 is going to resolve.

**Comment by benkindt** [comment]
@srinivasmerugu I'm not sure if I just wasn't aware of the mentioned issue or this once worked in an older version.

**Comment by srinivasmerugu** [comment]
@benkindt this issue is happening only when we use menuPortalTarget={document.body} on modals/slidens in order to have the portals inside react-select. 

Without portals in older versions its just works fine on modals /slideins.

**Comment by srinivasmerugu** [comment]
> @srinivasmerugu I'm not sure if I just wasn't aware of the mentioned issue or this once worked in an older version.

Hey @benkindt Can you please let me know if this is going to include in next release as we would like to use the portaling inside the modals/slideIns without any scrolling issues.

Thanks in Advance!

**Comment by acidmk** [comment]
We also want to deal with this issue. Menu dropdown is producing scroll inside of modal dialog so we are setting ` menuPosition="fixed"` to bypass dialog body overflow. But in this mode dropdown won't follow the input.

**Comment by benkindt** [comment]
@srinivasmerugu I don't know if it will be fixed in future releases. I got the same issue in my current version - like I said, maybe I just wasn't aware of the issue and my workaround isn't so great :-)

**Comment by acidmk** [comment]
@benkindt the workaround is good but it block scroll

**Comment by benkindt** [comment]
@srinivasmerugu Good news. I found [this comment](https://github.com/JedWatson/react-select/issues/3929#issuecomment-604866966). I tested this and the workaround is working in version 3.0.4.
So use
> menuShouldBlockScroll={true}
with "react-select": "3.0.4",

**Comment by srinivasmerugu** [comment]
> @srinivasmerugu Good news. I found [this comment](https://github.com/JedWatson/react-select/issues/3929#issuecomment-604866966), which mentions that there was a bug introduced in v3.0.5. I tested it and the workaround is working in version 3.0.4.
> 
> > A workaround for this is to block scrolling with menuShouldBlockScroll={true}
> > *with "react-select": "3.0.4",

@benkindt We are using 3.1.0 version and its latest features .Could you please let me know if there is any plan of reverting the code which caused this issue.

**Comment by benkindt** [comment]
@srinivasmerugu you can follow the link to the mentioned comment. This thread is about the scrolling bug in particular, you may ask it there

**Comment by srinivasmerugu** [comment]
> @srinivasmerugu you can follow the link to the mentioned comment. This thread is about the scrolling bug in particular, you may ask it there. I'm using v3.0.4 as long as there is no progress

yeah @benkindt I just posted at https://github.com/JedWatson/react-select/issues/3929

**Comment by bladey** [comment]
Hello -

Thanks for reporting this issue.

This bug has been reported multiple times as per issue #4088.

A new master issue #4088 has since been created to keep track this this bug.

This new issue will exist as the source of truth going forward to investigate the issue, report findings, and implement a bug fix.

We'll take into account all the details above while investigating.

If you feel this issue has been wrongly closed as it isn't related to the new master issue #4088, please let us know and we'll take another look.

Thank you!

**Comment by Anhaachan** [comment]
> A workaround for this is to block scrolling with `menuShouldBlockScroll={true}`

what about block only vertical scroll?

**Comment by Destructoralfonso3** [comment]
@benkindt https://reactdev.space/questions/navigating-to-another-component-in-reactjs-by-scrolling
