### ISSUE TITLE
ActionMeta type doesn't expose name and option properties 

### ISSUE THREAD

**Issue by grsoares21** [JedWatson/react-select#3740]
The Typescript ActionMeta interface in types.d.ts exposes only an 'action' property although the JS object has a 'name' and an 'option' properties:
`export interface ActionMeta {
  action: ActionTypes;
}`

I believe there might be a reason for this but I can't imagine any.
I'd like to use the value of the 'option' that was selected or de-selected on my 'onChange' function.

I had to create my own custom Action interface to do that.

Thanks in advance.
-Gabriel

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
