### ISSUE TITLE
use multiple lines for multiple selected choices. React Select V2

### ISSUE THREAD

**Issue by jcabrerazuniga** [JedWatson/react-select#3741]
I am using React Select V2  ("^2.4.2"). If I use isMulti then If I select several options then they only appear in one line increasing the width of the box where the selected options are shown. Can this be multiline? This is important as I placed Select in a table cell and whenever I choose several options through the multi Select that column increases a lot.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
