### ISSUE TITLE
Feature Request: Auto scroll to preferred option

### ISSUE THREAD

**Issue by rbokel** [JedWatson/react-select#3743]
My select has a lot of options. 
To make it more convenient for the user i would like to scroll  to a "preferred" option, when the user opens the menu and  no value has been selected yet

**Comment by buszmen201** [comment]
I don't know if this is what you think of, but you can do this by little changing order of options (pick preferred as first) and set this one as `value={...}`. If you want to highlight it you can add custom styles eg:
```jsx
<Select
  ...
  styles={{
    option: (provided, state) => ({
      ...provided,
      backgroundColor: state.isSelected ? theme.palette.secondary.main : 'white',
      padding: 20,
      '&:hover': {
        backgroundColor: state.isSelected ? theme.palette.secondary.main : 'lightgray',
      }
    }),
  }}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
