### ISSUE TITLE
When multi, call asyncOptions again when the list starts to get empty

### ISSUE THREAD

**Issue by Marsup** [JedWatson/react-select#375]
Hi,

I'm using the component in multi mode with the asyncOptions
When using the mouse to add items to the choices, it will pick into the list until no more items are available but it won't call asyncOptions to offer more choice based on the same search string.

Is it expected or is it my implementation that's misbehaving ?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
