### ISSUE TITLE
TypeError: null is not an object (evaluating 'cache.registered')

### ISSUE THREAD

**Issue by Thibs38** [JedWatson/react-select#3753]
I tried to implement react-select in my projet, I started using the example provided on the official website but when I launch the app it crashes and I'm getting the following error:

TypeError: null is not an object (evaluating 'cache.registered')
- node_modules\@emotion\core\dist\core.browser.cjs.js:61:48 in render
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:12671:25 in updateContextConsumer

Here is my code:
```
import React, { Component } from 'react'
import Select from 'react-select'

const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
]

const Test = () => (
  <Select options={options} />
)

export default (Test)
```

And then I'm render the Test component somewhere else in my App

**Comment by buszmen201** [comment]
you should create controlled input

```jsx
const Test = () => {
  const [v, setV] = useState({value: '', label: 'Select anything'});
  return (
    <Select options={options} value={v} onChange={((value) => setV(value)} />
  );
};
```

**Comment by 2016CS112** [comment]
TypeError: null is not an object (evaluating 'cache.registered')
Same Error !!

**Comment by jaywardhan1990** [comment]
> you should create controlled input
> 
> ```js-jsx
> const Test = () => {
>   const [v, setV] = useState({value: '', label: 'Select anything'});
>   return (
>     <Select options={options} value={v} onChange={((value) => setV(value)} />
>   );
> };
> ```


I am facing the same issue. i tried your solution but didn't work for me

![Screenshot_20200304-183428](https://user-images.githubusercontent.com/40829561/75882746-c8a27380-5e47-11ea-94fa-d857097fcd48.png)
lease find below screenshot

**Comment by scottkriesberg** [comment]
I am having the same issue. When I try to render a select component, I get the error: TypeError: null is not an object (evaluating 'cache.registered'). Is there a fix for this?

**Comment by alanfoandrade** [comment]
Same error here! Any suggestions?

**Comment by Nnoromuche** [comment]
Well done with the development of this library. Can you provide an example of this library working in a non-class based react-native file please, thanks!

**Comment by Rall3n** [comment]
As it seems like no one likes to answer here with a cause of the issue:

**`react-select` is currently strictly programmed to be used in the web. It will definitely not work with `react-native`.**

**Comment by bladey** [comment]
Thanks for pointing this our @Rall3n. I'm going to close this issue since `react-native` is not supported.
