### ISSUE TITLE
`classNamePrefix` is not applied to `<input>` wrapper

### ISSUE THREAD

**Issue by Klinton90** [JedWatson/react-select#3754]
Our company has custom field appearance, which I want to apply to ReactSelect. Since we are not going to change that (in nearest future), easiest way for us is "Using classNames".

When I set `classNamePrefix` prop, it is not applied to all elements.
```
<div class="my-select__value-container my-select__value-container--has-value css-1hwfws3">
    <div class="my-select__single-value css-1uccc91-singleValue">Value</div>
    <div class="css-w8afj7-Input">
        <div class="my-select__input" style="display: inline-block;">
            <input autocapitalize="none" autocomplete="off" autocorrect="off" id="react-select-4-input" spellcheck="false" tabindex="0" type="text" aria-autocomplete="list" value="" style="box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 1; outline: 0px; padding: 0px; color: inherit;">
            <div style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 12px; font-family: &quot;Helvetica Neue&quot;, &quot;Liberation Sans&quot;, Helvetica, Arial, sans-serif; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;"></div>
        </div>
    </div>
</div>
```

Problem is in `css-w8afj7-Input` class/element, which is not customizable.
Version tested with is 3.0.4.

**Comment by gegham1** [comment]
Any updates ?

**Comment by reggie-it** [comment]
Any updates here? Trying to override using css modules as well

**Comment by ratmirslv** [comment]
You can use [https://react-select.com/styles#provided-styles-and-state](url)

`const CustomStyles={
input: base => ({
		...base,
		someStyle: "someValue",
}
<Select styles={customStyles}>`

**Comment by bladey** [comment]
Hello -

Thanks for your input @ratmirslv.

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by kevinhaas** [comment]
Why is this closed? It doesn't make sense that some of the elements (input in this case) don't receive a class with the prefix. So many issues in this repo are just closed for no reason.
