### ISSUE TITLE
Menu position does not recalculate when menu size changed

### ISSUE THREAD

**Issue by alexolefirenko** [JedWatson/react-select#3755]
Hello, here is a bug, when menu size changes it does not recalculate menu position. There are two async autocomplete try to put something in input area and you will see wrong positioning.
I have already tried to fix it but I think there should be clearer method to avoid this bug.

What are you thinking about it?

https://codesandbox.io/s/menuplacementauto-8wu04

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
