### ISSUE TITLE
Preserve focused option its getOptionValue() hashcode equality, not by its object indexOf === 

### ISSUE THREAD

**Issue by dko-slapdash** [JedWatson/react-select#3758]
In this code:
https://github.com/JedWatson/react-select/blob/97fbd4c3a24952ab103ca197d912f37c6057674e/packages/react-select/src/Select.js#L775-L780

The comparison would ideally be made not by indexOf(), but by comparing getOptionValue(focusedOption) with getOptionValue(options[i]).

Usecase:
1. `<Select>` is created with one set of options
2. The user presses arrow-down a couple times and focuses some option in a drop-down
3. The set of options in `<Select>` got rebuilt from scratch (i.e. `<Select>` got re-rendered)
4. CURRENT BEHAVIOR: the focus resets to the 1st option in the drop-down
DESIRED BEHAVIOR: the focus remains on the previously focused option.

P.S.
To work-around this case, I had to create the following ugly helper function:
```ts
/**
 * When the content of the popup options changes, react-select keeps the focused
 * option, but it does so by comparing options objects, not by comparing their
 * hash codes (returned by getOptionValue() prop)! Since we rebuild the list of
 * options every time, we then need to dedup the newly built options with the
 * previously built ones to keep the focused element intact.
 */
function dedupWithPrev(options: OptionType[], cache: Map<string, OptionType>) {
  return options.map(option => {
    const hash = getOptionValue(option);
    const cached = cache.get(hash);
    if (cached) {
      return cached;
    }
    cache.set(hash, option);
    return option;
  });
}
...
const [optionsCache] = useState(new Map<string, OptionType>());
<Select ... getOptionValue={getOptionValue} options={dedupWithPrev(options)} />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
