### ISSUE TITLE
How to select an element when I have something in the input

### ISSUE THREAD

**Issue by engp8691** [JedWatson/react-select#3759]
Hi. I am using react-select with Ag-Grid as an ag-grid editor. My situation is that I have one field has more than 200 options, so I give users to type some text and do a serverside fetch/refinery by loadOptions={promiseOptions}. Everything is working fine. I can use the mouse click to select the value. But I cannot use "Control + Space" keys to choose the value when I have some typed text in the input area. I can use enter to select the value also. But in ag-grid, enter key is hijacked and when I hit the enter key, Ag-Grid thinks the editing is done and the popup editor is gone. Is there anything I can do to keep "Control + Space" still valid even I have some text in the input area. The "control + space" keys can select/insert value in the input if there is not typed text.

Please help me with any suggestions

**Comment by flexdinesh** [comment]
Hey @engp8691! Would you be able to provide a codesandbox with the issue? It's pretty much impossible to comprehend without a working example.

**Comment by bladey** [comment]
Hi @engp8691!

As @flexdinesh mentioned, if you could give us a example that would be great.

I'm going to close this issue for now, please let me know if you have an example and you'd like us to reopen it!
