### ISSUE TITLE
Stylesheets are often broken in 3.x.x

### ISSUE THREAD

**Issue by volkanunsal** [JedWatson/react-select#3760]
I upgraded to version 3.0.4 over the weekend, but immediately rolled it back due to the frequency with which the css stylesheets are not getting loaded, especially on components that are loaded asynchronously. (This might be due to some changes in emotion 10.) 

I don't have a good way of replicating this behavior, unfortunately, but I'd be open to suggestions. In particular, the code is problematic after it has been optimized, minified and deployed to production.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
