### ISSUE TITLE
on Portaling - When Menu is open it allows the background to scroll. And isn't attach to it's parentElement

### ISSUE THREAD

**Issue by lokeshsp2311** [JedWatson/react-select#3763]
**"react-select":** "^2.4.1"
**"node":** ">=8.10.0"
**"react":** "16.6.0"

I am using the above version of packages. And Portaling also working fine. But On Scroll when the menu is open, only background will move but the menu remains static.

It should move with its corresponding **Input** Element.

Check the codesandbox below 
https://codesandbox.io/embed/react-codesandboxer-example-yjc61

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
