### ISSUE TITLE
onMenuClose is called only when clicking on the select

### ISSUE THREAD

**Issue by dana2208** [JedWatson/react-select#3764]
Hi,
When clicking on the select and opening the menu (in a multi combobox), only when I click on the select again the menu closes and calls the onMenuClose function.
If I click somewhere else in the screen, the menu closes but without calling the onMenuClose.
Is there a way to catch when the menu closes no matter if it closes when clicking on the select or elsewhere?
Thanks.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
