### ISSUE TITLE
laodOptions is called when async select is closed. It should be called when select is opened.

### ISSUE THREAD

**Issue by MuhammadZaidSE** [JedWatson/react-select#3765]
I am adding some users before opening the Async Select.
Now I want to load the added users in Select from server.

When I open the Async Select, it does not call loadOptions, and shows the old data.
loadOptions function is called when Select is closed.
So, the updated data is loaded is shown when I open the Async Select second time.

How can I load the latest data in Async Select when I open it for the first time?

**Comment by consciousnessdev** [comment]
I'd facing this too, when data fetched i'd setState, then new state changed by new value from data fetched, but still loading when dropdown was opened, but when closed then i open again it set fetched data value

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
