### ISSUE TITLE
React Select incompatible with react-jss (fires all site transitions on load)

### ISSUE THREAD

**Issue by sebrobpau** [JedWatson/react-select#3766]
There is a issue with how emotion loads scripts (I think), which causes elements to first get their default color before they get assigned the correct color from jss. This is normally unoticable, but when using transitions, they will trigger every time the page loads. 

The following example shows the problem. When the page loads, the button will slowly transition from gray to red, when it's supposed to only be red when not hovering.

```
import React from "react";
import {createUseStyles} from "react-jss";
import Select from "react-select";

const useStyles = createUseStyles({
    root: {},
    button: {
        transition: "all 5000ms ease",
        backgroundColor: "red",
        "&:hover": {
            backgroundColor: "blue"
        }
    }
});

const App = () => {
    const classes = useStyles();
    return (
        <div className={classes.root}>
            <button className={classes.button}>TEST</button>
            <Select />
        </div>
    );
};

export default App;

```

Currently lazy loading react-select as a workaround.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
