### ISSUE TITLE
Custom components not styled

### ISSUE THREAD

**Issue by bartoszhernas** [JedWatson/react-select#3767]
Following this example:
https://react-select.com/styles
Style composition for custom components

It doesn't style custom component even on the docs page.

Any idea how to fix it? 

My code that also doesn't work (TypeScript):

```
const UserSelectFieldSingleValue: React.FC<SingleValueProps<UserSelectUser>> = (props) => {
  const {
    cx,
    innerProps,
    data,
    children,
    getStyles,
    isDisabled,
  } = props;

  return <div
    {...innerProps}
    className={cx(
      css(getStyles('singleValue', props)),
      {
        'single-value': true,
        'single-value--is-disabled': isDisabled,
      },
      undefined
    )}
  >
    {data.user && <UserSelectUserComponent user={data.user}/>}
    {!data.user && "Creating new traveller..."}
    {children}
  </div>;
};
```

**Comment by bartoszhernas** [comment]
When using `style` prop, then all my options are displayed as focused, even though only one option should be focused:

```
const UserSelectFieldSingleValue: React.FC<SingleValueProps<UserSelectUser>> = (props) => {
  const {
    innerProps,
    data,
    children,
    getStyles,
  } = props;

  return <div
    {...innerProps}
    style={getStyles("singleValue", props)}
  >
    {data.user && <UserSelectUserComponent user={data.user}/>}
    {!data.user && "Creating new traveller..."}
    {children}
  </div>;
};```

**Comment by jrtilson** [comment]
Ran into this same problem today trying to use a custom option compoennt. (Using react-select 3.0.8)

I had a look through the package source and followed the same pattern as defined in the [Option source](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/Option.js) and managed to get it working. 

I think the key is having the custom component in it's own file, not importing React directly, and using Emotion's `jsx` instead. My custom component looks like this now:

```
/** @jsx jsx */
import { jsx } from '@emotion/core';

const MyCoolCustomOption = (props) => {
  const {
    children,
    className,
    cx,
    getStyles,
    isDisabled,
    isFocused,
    isSelected,
    innerRef,
    innerProps,
    data,
  } = props;
  return (
    <div
      ref={innerRef}
      css={getStyles('option', props)}
        className={cx(
          {
            option: true,
           'option--is-disabled': isDisabled,
           'option--is-focused': isFocused,
            option--is-selected': isSelected,
          },
          className,
        )}
        {...innerProps}
    >
      {/* custom component stuff */{
    </div>
  );
};

```

**Comment by bladey** [comment]
Thanks for the answer @jrtilson, much appreciated.

@bartoszhernas let me know if this doesn't solve your issue and I'll reopen and mark it for investigation.
