### ISSUE TITLE
Wrong type definitions

### ISSUE THREAD

**Issue by goodwin64** [JedWatson/react-select#3768]
# Are you asking a question?
No, I'm reporting an issue. I'm not sure it's the right place to post issue with typings and probably I have to create one in `DefinitelyTyped` so sorry in advance.

# Are you reporting a bug or runtime error?
Bug with typings.
Steps to reproduce:
1. Open sandbox https://codesandbox.io/s/react-typescript-9xs5h?fontsize=14
2. Open console
3. Open ReactSelect dropdown menu
4. See props listed in the console. Some of theme are present actually but not listed in `.ts` file. Some of them are listed among typings but `undefined` actually.

# Are you making a feature request?
Nope, it's about current implementation usage issues.

**Comment by danieldelcore** [comment]
It's probably best to raise this issue in DefinitelyTyped, since it is maintained separately to this repo.

**Comment by flexdinesh** [comment]
@goodwin64 if you're still having issues with type defs, pl follow up in DefinitelyTyped.
