### ISSUE TITLE
Edit Multiselect

### ISSUE THREAD

**Issue by vladfulgeanu** [JedWatson/react-select#377]
Hi everyone!

I just started using react-select, so I'm new to it and don't know, but is it possible to edit the already added `Multiselct` elements.

For example, the are already `Chocolate`, `Vanilla` and `Strawberry` as selected labels. Can I edit them? This is a really useful feature that I really need.

**Comment by bruderstein** [comment]
Can you explain exactly what you mean by edit? You can't natively change
the labels as a user, but you can change the selection via updating the
props, or clicking the x to remove a current selection. You're also free to
update the options via props too.

If you're looking for tagged input, where the user enters all the tags, I
think there's a control called react-tagged-input that does that.

**Comment by fullvlad** [comment]
I need to have tags like this:
`Imagination` `Instanity` `Power` `Mistery` `Strength` `Violence`
that are representative for a movie.
At first, when a movie's page is loaded, this field has some of these tags entered, and they have a score:
`Imagination(2)` `Instanity(1)` `Strength(3)`
 
I want after that, the user to be able to edit the number in the parenthesis, and also to add some new tags that are predefined, so to make something like this:
`Imagination(2)` `Instanity(3)` `Strength(3)`  `Power(2)`

**Comment by bruderstein** [comment]
You should be able to do this with your own `valueComponent`. You'd create a component that allows the user to edit the count, and takes the props of as described in the docs (see `Value.js` for the default).  Not sure how you communicate back to your parent component, but maybe you can set the number as a property of the option (or provide a callback in each option itself)

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
