### ISSUE TITLE
Display filtered options while loading remote

### ISSUE THREAD

**Issue by moeatsy** [JedWatson/react-select#3771]
In AsyncSelect I not found way to display list of options while loading new one.

For example i want to select city.
- User types "Ne" and we load 10 cities from server.
- Now our list contains 10 cities.
- User types "New" and react-select hides list before new items loaded

As I see it:
- It should show filtered options of these we already loaded + loading indicator.
- Or should show non-filtered options of these we already loaded + loading indicator.

Otherwise it produce annoying blinking of show/hide list.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
