### ISSUE TITLE
the ability to change the 'create' word in `Creatable` component when there is no item to select

### ISSUE THREAD

**Issue by blueturtle13g** [JedWatson/react-select#3772]
Hello, thank you for the great work you've done.
I'm using your component in a non-English language website. everything is fine just `Creatable` component which doesn't allow to me give it the word that is used when no item is found based on the search string.
![image](https://user-images.githubusercontent.com/38331860/65424017-5ac53b00-de17-11e9-9f08-33b562ed8e18.png)
for example, consider the above case in which I want to replace 'create' word with an equivalent word in the Persian language.
the only way I can think of, is getting the corresponding element and manipulate its inner HTML.

**Comment by Xartok** [comment]
In recent versions (tested on 3.0.4) you can use the `formatCreateLabel` prop, like this
```
<Creatable
    formatCreateLabel={(inputText) => `"${inputText}" Persian word for Create`}
/>
```
See [this link](https://react-select.com/props#creatable-props) for the corresponding doc.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
