### ISSUE TITLE
The [X] doesn't clear the last item of a multi-select

### ISSUE THREAD

**Issue by mikevbaker** [JedWatson/react-select#3774]
I've been using the select with the "isMulti" property. I used to be able to click the [X] next to each selected item until they were all gone and it reverted to the placeholder text. A little while ago I updated all the packages in the project which resulted in going from 2.1.2 to 3.0.4 of this package. I just noticed that I can no longer click the [X] on the last item and instead have to go to the right of the select and click that [X].

Today I tried updating to 3.0.5 and the issue remains. I looked through all the properties and I can't see any that mention clearing the last item being optional. If this is intentional behavior then I think we need an option to allow the clearing of the last item using that item's closer.

# Steps:
Select multiple items in a select box with isMulti option on
Click the [X] on each item until only one remains
Click the [X] on the last item

# Current behavior
The item doesn't disappear

# Expected behavior
The item should be removed and the placeholder text should remain

Thanks

**Comment by mikevbaker** [comment]
OOPS!

OK, it turns out it was my handler for the selection changed. Apparently the older version of the select used to pass an empty array of items when the last item was deleted but now I'm getting null. I added in null as valid argument in the validity check and my handler is getting called now.

Sorry for the distraction.

**Comment by changyu2hao** [comment]
I have the same issue, could you please give me more details about how did you solve it?

**Comment by mikevbaker** [comment]
> 
> 
> I have the same issue, could you please give me more details about how did you solve it?

Hi! Yeah, as I mentioned in my later comment, the behavior changed just a little. At first it returned an empty array when the last item was removed. After an update it instead returned NULL. So I added the null return as a valid return case and handled it just as if it returned an empty array. (either one would just refresh the data source without any filter) It's been a long time since that project so I hope I'm remembering correctly. I can dig it up again if you need... if I still have a snapshot of that VM...

**Comment by ejose19** [comment]
@mikevbaker I just got this, but handling it with value ?? [] instead, for me it seems like a bug because the "global" X returns empty array but clearing the last element with its own "X" return null, which is not consistent and most likely a bug.

**Comment by mikevbaker** [comment]
Actually I think I said that wrong. I didn't actually add it as a valid value, I just tested to make sure that `arg!==null` before trying to use it. My new code is this

`handleCategorySelect(arg) {`
`    let newCatList = [];`
`    if (arg !== null && typeof arg === 'object') {`
`	if (!arg.some(e => e.value === 0)) {`
`	    arg.forEach(function(element) {`
`	        newCatList.push(element);`
`	    });`
`	}`
`    }`
`    this.setState({ currentCategories: newCatList }, () => { this.loadProjects() });`

This comment editor won't let me format it right but you can see newCatList starts [], If arg is null all the reading of it is skipped and the end result is the empty list. HTH Mike

**Comment by japrogramer** [comment]
interesting. Is there an event listener for react-select that is fired when the selections are clear?
I tried to look for onClear but it's not as expected.

I would like to check the state of the selection when the clear button is clicked.

**Comment by mikevbaker** [comment]
The handler shown there is actually passed down from a parent component. I don't see an onClear available, just onChange. I think this is pretty typical. You wouldn't necessarily want to handle different events, handling the onChange is all you need. Adding a selection is a change, removing a single selection is a change, clearing all selections is a change.

**Comment by user09876090** [comment]
@mikevbaker Hi, I am using multi true property. I have a confusion that when I'm selecting an option from dropdown then onChange event is called and when I am removing a selected item then again onChange event is called. How can I differentiate if a new item was added or removed? because same event is called.

**Comment by mikevbaker** [comment]
The answer is that you don't. You just react appropriately for the collection that is currently selected. You can if you wish, but that's on you. Keep a separate list of what you consider the current selections. Loop through the items provided to see if you need to add or subtract from your list.
But you can just abandon what is there and re-render. React only deals with what's different between last render and this render.

⁣From Mike via mobile

**Comment by ebonow** [comment]
Greetings,

I'll try to answer a few questions but first some information about the onChange method and [action meta](https://react-select.com/advanced#action-meta)

The `onChange` method includes two parameters: 
- The new value
- context

The context parameter consists of a few different properties:
- action - Action can be one of the following values...
  -"select-option",
  -"deselect-option",
  -"remove-value",
  -"pop-value",
  -"set-value",
  -"clear",
  -"create-option"

The context parameter also contains
- option
- name
- removedValue (only returned when action is `remove-value`)

If you would like to see this in action, you can see this [codesandbox for a demonstration of logging the different actions and props
](https://codesandbox.io/s/react-select-logging-action-meta-40847)

Ok so now for individual questions:
@japrogramer 
> interesting. Is there an event listener for react-select that is fired when the selections are clear?
> I tried to look for onClear but it's not as expected.
> 
> I would like to check the state of the selection when the clear button is clicked.

Yes. Please see the below code example to see how you would do this...
``` JS 
const onChange = (value, context) => {
  if (context.action === 'clear') {
    console.log(`Current value is: ${value}`);  
    // This will always be null or if isMulti then [] (which is a known bug... but different story)
  }
}
```

@user09876090 

> Hi, I am using multi true property. I have a confusion that when I'm selecting an option from  dropdown then onChange event is called and when I am removing a selected item then again onChange event is called. How can I differentiate if a new item was added or removed? because same event is called.

This should answer your question about how to differentiate what happened and what the item was
``` JS 
const onChange = (value, context) => {
  if (context.action === 'select-option') {
    console.log('Item added', context.option);  
  }
  if (context.action === 'deselect-option') {
    //  only possible when hideSelectedOptions=false 
    console.log('item was removed by re-selecting option from the menu', context.option)
  }
  if (context.action === 'remove-value') {
    console.log('item was removed by clicking pressing X next to value', context.removedValue)
  }
}
```

@mikevbaker 
> The answer is that you don't. You just react appropriately for the collection that is currently selected. You can if you wish, but that's on you. Keep a separate list of what you consider the current selections. Loop through the items provided to see if you need to add or subtract from your list. But you can just abandon what is there and re-render. React only deals with what's different between last render and this render. ⁣From Mike via mobile Sent from BlueMail ​

The answer is that you can, you simply need to be aware of the second parameter passed into the onChange method.


If any of this is unclear, please feel free to follow up. I will close this issue again, but will happily resolve and all questions that I can answer or open a bug if you believe there to be one.
