### ISSUE TITLE
Enzyme `mount` cause error when renders react-select

### ISSUE THREAD

**Issue by vartemiev** [JedWatson/react-select#3776]
Hello!

I have problem with testing latest (3.0.5) version of react-select

code
```
...
import Select from 'react-select'

const Product = () => (
  <Select options={[]} onChange={() => null} />
);

export default connect(() => {}, () => {})(Product);
```

test suite

```
import { mount } from 'enzyme';

...
    const wrapper = mount(
        <IntlProvider locale="en" messages={{}}>
            <Provider store={store}>
                <Product />
            </Provider>
        </IntlProvider>
    );
 ...
```

When enzyme try to mount component with `Select`, console displays
`TypeError: Cannot read property 'registered' of null`

It's just FYI.
In react-select v2.4.4 all is ok.

**Comment by lbonatti89** [comment]
Same issue here. Someone???

**Comment by naiaramartin** [comment]
Same issue with 3.0.8...

**Comment by FranciscoZen** [comment]
Same issue here - 3.0.8 version

**Comment by rjones222** [comment]
Also the same issue with 3.0.8 version. Going to try vartemiev's solution "In react-select v2.4.4 all is ok."

**Comment by k1462015** [comment]
Based on the error code, it seems we need to make sure a `CacheProvider` is available:

```
import createCache from "@emotion/cache";
import { CacheProvider } from "@emotion/core";

const cache = createCache();

function withCacheProvider(
        children: React.ReactNode,
) {
        return (
            <CacheProvider value={cache}>
                {children}
            </CacheProvider>
        );
}

const component = mount(withCacheProvider(
     (
         <ComponentUnderTestThatUsesReactSelect />
     ),
));
```

That got all of my tests running without needing to downgrade my react-select version, however, may not be the best solution.

**Comment by jordanell** [comment]
Workaround by @k1462015 worked for me.

**Comment by bladey** [comment]
Thanks for workaround @k1462015, I'm now going to close this issue so we can keep on top of other issues in the repo.

However - if you'd like us to further investigate this if the workaround isn't good enough, please let me know.

**Comment by varzaman** [comment]
I'm also getting this issue without using enyzyme. Will investigate further.

**Comment by macgill4444** [comment]
@varzaman did you find a solution? We are also seeing with Next.js on the server render only. We are not using enzyme.

**Comment by varzaman** [comment]
Unfortunately not :/

I will try to remember which steps we took, but in the end it was taking up too much of our time.

**Comment by djErock** [comment]
Just updating this here as it is still an issue:

import React from 'react';
import createCache from '@emotion/cache';
import { CacheProvider } from '@emotion/react';
import { shallow, mount } from '../../../../testUtils/enzyme';
import MyComponent from './MyComponent';

const cache = createCache({ key: 'relatedcodestile' });

const withCacheProvider = (children) => {
  return <CacheProvider value={cache}>{children}</CacheProvider>;
};

... and then inside your test


    const wrapper = mount(withCacheProvider(<RelatedCodesTile {...props} />));
