### ISSUE TITLE
Wrong positioning calculation for menuPortal on layout with overflow: 'scroll'

### ISSUE THREAD

**Issue by SiarheiLazakovich** [JedWatson/react-select#3777]
Hello, I've got an issue with positioning calculation for menuPortal. Looks like position doesn't include hidden part of container.

Here is a example of problem:
<img src="https://image.prntscr.com/image/R_hGbjSeQIuPw3QxwDHXbw.gif">

[![Edit react-select-issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-select-issue-fb541?fontsize=14)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
