### ISSUE TITLE
TypeError thrown when using key down (instead of mouse click) to select items.

### ISSUE THREAD

**Issue by millturnK** [JedWatson/react-select#3780]
Hi there,
A TypeError is thrown when using key down and "enter" key press (instead of mouse click) to select items in a drop down box. I get no errors when using a mouse click. I am using react-select v 3.0.4 and react v 16.
Here is the full error:
Uncaught TypeError: Cannot read property 'type' of undefined at setFieldValue
Here is the code where I am using it:
<Select id="selACBrand" aria-label="airconditioner brand"
                                    onChange={this.handleBrandChange}
                                    options={this.state.brandArr.map((brand) => ({
                                        label: brand.value,
                                        value:brand.value
                                    }))}
                                    value={{label:this.state.brand, value:this.state.brand}}
                                    classNamePrefix="react_select_brand"
                            />

**Comment by joshtldr** [comment]
I had the same "Cannot read property 'type' of undefined" error. In my case, It was due to the LastPass Chrome extension. Disabled it and no more errors.

**Comment by jgladch** [comment]
Same issue here

**Comment by bladey** [comment]
Hi @millturnK and @jgladch, I've attempted to reproduce this issue based on @millturnK's example, here - https://codesandbox.io/s/react-select-v3-sandbox-guyp8?file=/example.js

I can't see the problem however, could you confirm it's still an issue?

**Comment by millturnK** [comment]
Hi @bladey ,
I am no longer supporting this application due to lack of funding so it's not an error for me anymore ;-). It is happening in a Vue.js app I'm developing because of the LastPass Chrome extension. So I think it's just a matter of catching and handling that error as it's not a show stopper - and nothing for you to worry about. Thanks for your help though :-).

**Comment by bladey** [comment]
Thanks @millturnK!
