### ISSUE TITLE
React-select not working

### ISSUE THREAD

**Issue by pramodmg** [JedWatson/react-select#3784]
react new version has broken the usage of the react-select ... can we please check on it . ? 

Error on the browser console: Uncaught TypeError: Cannot read property 'forEach' of undefined

**Comment by goldo** [comment]
@pramodmg I think its caused by react and not react-select: 
https://github.com/facebook/create-react-app/issues/7753

**Comment by pramodmg** [comment]
@goldo yeah i guess ... but do we need to fix or will react team fix it  ?

**Comment by goldo** [comment]
I havent digged into it, so Im not sure, but I think it’s react-scripts team’s job. Personnally  I downgraded react scripts

**Comment by pramodmg** [comment]
resolved
