### ISSUE TITLE
After one selection is made, all subsequent options appear selected.

### ISSUE THREAD

**Issue by claytongroth** [JedWatson/react-select#3796]
I am having an issue where the first selection I make yields normal options to select from that render properly:
![stepone](https://user-images.githubusercontent.com/37966122/66095434-b9e02980-e554-11e9-9979-2b3f3e4be4ea.png)

Then, when I blur and type something again, I get:
![steptwo](https://user-images.githubusercontent.com/37966122/66095464-d5e3cb00-e554-11e9-93dc-6afb52c7a703.png)

**Below is the component:**
```javscript
<AsyncSelect
    isClearable
    isDisabled={this.props.disabled}
    inputValue={this.state.query}
    autoBlur
    blurInputOnSelect
    placeholder={this.state.placeholder}
    // Fire the api here and get results async
    loadOptions={this.loadOptions}
    //just updates the state
    onInputChange={this.handleInputChange} 
    onChange={this.handleChange}
    components={
        {
            DropdownIndicator: () => null,
            IndicatorSeparator: () => null,
            NoOptionsMessage: () => <div>Start typing a destination</div>

        }
    }
/>
```

**Expected behavior:**
The component is styled in the same way before and after I select+blur it.

I am hoping there is some prop that I can tweak to prevent this behavior?

**Comment by Rall3n** [comment]
@claytongroth What is the value of the `value` attribute of your options? All options being selected would mean they all share the same value.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by suryavenkat506** [comment]
I have the same issue, solved it using the below approach. Select "options" should contain the key "value".
Example:
const countries =[
    { code: 'AD', label: 'Andorra', phone: '376' ,**value**:'' },
      {        code: 'AE',         label: 'United Arab Emirates',         phone: '971',         **value**:''       }
      {        code: 'IN',         label: 'India',         phone: '91',         **value**:''       }
]

If you remove the "value" from above list item then we are experiencing this problem. Hope this helps..!!
