### ISSUE TITLE
Selecting a value does not trigger form onChange 

### ISSUE THREAD

**Issue by panukettu** [JedWatson/react-select#3798]
https://codesandbox.io/s/damp-pond-i0dq0

Here you can see console.log from a regular `<select>` but not from `<Select>` from `react-select`.

**Comment by willlma** [comment]
I'm dealing with this issue as well. Seems react select is preventing the event from bubbling. I was hoping that including the hidden input would solve this, but no dice.

**Comment by bladey** [comment]
Hi @panukettu and @willlma,

I wanted to check in and see if you were still encountering this issue. We're triaging issues at the moment to sustain the project going forward.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.

**Comment by panukettu** [comment]
It sure seems that updating to latest version still has the bug occuring. It is quite clear from my example.

**Comment by muuuh** [comment]
Could you please look into this?

**Comment by Rall3n** [comment]
Hello @muuuh,

Would you please be so kind and create a new issue with an example of how the problem occurs?

If you like you can reference this issue.

**Comment by gormonn** [comment]
@Rall3n The problem is reproduced in 4.3.1
Added an event counter to the example, for clarity.
This approach is often used to catch any changes in the form. 
For example, in forms with uncontrolled components. ex: react-hook-form

https://codesandbox.io/s/polished-surf-ljlczn?file=/src/index.js

**Comment by gormonn** [comment]
https://github.com/JedWatson/react-select/discussions/5240

**Comment by twigs67** [comment]
Any update on this?

**Comment by cdeath** [comment]
this is because it's using an `input[type=hidden]` which does not fire the `change` event by default
but you can fire it manually on the `onChange` callback

1) set the `id` and `name` props on your react-select instance
2) on the `onChange` callback select the hidden input element and fire the event

example:
```
onChange=((option) => {
  // do something
  ...
  // then fire the change event
  // probably not the best approach but wrapping it in a setTimeout fixed sync issues for me
  setTimeout(() => {
    // seems like there is no internal ref to the hidden input so you have to select it
    document.querySelector(`#${id} input[type=hidden][name="${name}"]`)?.dispatchEvent(new Event("change"));
  }, 0);
})
```

best to create a wrapper around react-select so you don't have to do this every time, with `useId()` for example
you can also get the input name from the meta (2nd argument) of the `onChange` callback
