### ISSUE TITLE
Feature: allow node value instead of function for noOptionsMessage

### ISSUE THREAD

**Issue by GeorgeWL** [JedWatson/react-select#3800]
# Are you making a feature request?
Provide as much information as possible about your requested feature. Here are a few questions you may consider answering:

*   What's your use case? (Tell us about your application and what problem you're trying to solve.)

Sometimes you just want a simple text or fragment to be returned, and not have to supply a function to do so.

*   What interface do you have in mind? (What new properties or methods do you think might be helpful?)

Just allow the prop type to be `React.Node` or `string` or `()=>return value`

*   Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

It's a pretty common use-case. Semantic-UI for React does it pretty commonly.

**Comment by ebonow** [comment]
Greetings @GeorgeWL ,

On one hand this seems convenient, and on the other hand, there is already a `NoOptionsMessage` component which can be used to overwrite the JSX rendering. 

I would err on the side of keeping this as having an expected return type of `string` though it's likely JSX would work much the same way `getOptionLabel` is supposed to only return a string. https://github.com/JedWatson/react-select/issues/4134 It's in this comparison that I believe it should remain as is... accessibility.

The aria-live implementation is designed to read from a config and there are plans and PRs to allow this to be more flexible, but it is also reliant on strings to be read to the reader and unfortunately JSX stringified returns `[Object Object]` which is not very helpful. Are there ways around this? Yeah probably, but it's more complexity on top of redundant functionality. 

I appreciate the idea and think there is some merit and certainly the documentation could be better to explain this, but I think it would be more ideal to enforce a string option to standardize how react-select conveys information to assistive technology.
