### ISSUE TITLE
React-Select not working on Mac 

### ISSUE THREAD

**Issue by Avery246813579** [JedWatson/react-select#3801]
I am using version 3.0.8 and the package is working how it's suppose to be when I'm developing on my windows machine. Then when switching to my mac with the same code it's not working. The basic example from the README is also not working so it's nothing to do with my implementation. I have attached the error below. 

```
VM199 bundle.js:4681 Uncaught (in promise) Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of "SelectContainer".
```
```
The above error occurred in the <SelectContainer> component:
    in SelectContainer (created by Select)
    in Select (created by StateManager)
```

**Comment by bzalasky** [comment]
This almost certainly is an issue with your own modules and not an issue with react-select. If you review the way you're importing the module, and also ways in which your build system might behave differently on Windows and MacOS, you should be able to resolve your issue.

**Comment by DonkeyAfterDark** [comment]
I have zero issues running react-select on any environment. I'm currently using MacOS (Catalina)

**Comment by Avery246813579** [comment]
Yeah seems to be working in different projects on my mac. Guess there might be a conflict somewhere. Thanks.
