### ISSUE TITLE
Is it possible to make React Select behave like SyncFusion's Autocomplete 

### ISSUE THREAD

**Issue by pratik-chakravorty** [JedWatson/react-select#3807]
So SyncFusion has their autocomplete component where you can type some text, modify it(instead of removing the whole thing) and also have mouse cursor selection. My question is whether this is possible using React-Select.
SyncFusion Link: https://ej2.syncfusion.com/react/demos/#/material/auto-complete/default
Thanks.

**Comment by danielesalvatore** [comment]
@pratik-chakravorty did you find a way to reproduce this behaviour?

Thanks!

**Comment by danielesalvatore** [comment]
@pratik-chakravorty I found this: https://codesandbox.io/s/quirky-lehmann-nuhr0

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
