### ISSUE TITLE
Suggestion for the time when loading options in AsyncSelect

### ISSUE THREAD

**Issue by MarcosCunhaLima** [JedWatson/react-select#3808]
The problem is simple. We have two AsyncSelects and the second one options array is based on something that user has selected in the first.

So, I disabled the second AsyncSelect in order to prevent user from clicking on it. Unfortunately, even disabled, AsyncSelect tries to load options based on the *defaultOptions* prop which could be:

- False: Does not load options at beginning just when user change value typing something.
- True: Load options at beginning (ignoring isDisabled prop unfortunately).
- An Array: Shows this array at beginning.

In order to prevent AsyncSelect from loading billions of options in the second AsyncSelect, I had to set it to false.

The problem is (in this case when defaultOptions is false) when user just clicks in the dropDown button, it displays nothing. In order to kick loading options, the user has to type something (and shows the No options message in the dropDown area).

So, my suggestion is that AsyncSelect respects isDisabled (and does not load options) and, if I set it to true, it starts loading options.

Maybe I miss something?

**Comment by brunoracosta** [comment]
Any updates on this?

**Comment by MarcosCunhaLima** [comment]
Unfortunately not. I had to tell users that they need to type something in order to kick the search in and bring values to the component.

**Comment by ebonow** [comment]
I would suspect that something like this would serve your use case.

defaultOptions = [], 
isDisabled = !firstSelectHasASelectedValue, 
placeHolder = `Select a thing${!firstSelectHasASelectedValue ? ' (Select Thing 1 first)` : ''}`

This issue almost a year old so I will close it out, but if you would like to discuss further I would be willing to work this more.
