### ISSUE TITLE
First letter is chopped in Edge 

### ISSUE THREAD

**Issue by Eebo78** [JedWatson/react-select#3809]
When running in 1920x1080 resolution and 150% size of text, apps, and other items search text hides part of the text when running in Edge.

Goto https://react-select.com/async
and in Async with defaultoptions as true input lol, <- comma is important! Notice that the first letter disappears.

Works as expected in chrome

**Comment by Eebo78** [comment]
![ReactSelectBug](https://user-images.githubusercontent.com/1528600/66758517-b5920580-ee9e-11e9-8f79-2013dea15a50.PNG)

**Comment by DonkeyAfterDark** [comment]
Are you using Chromium edge?

**Comment by Eebo78** [comment]
No. Forgot to mention version

Version: Microsoft Edge 44.18362.387.0, Microsoft EdgeHTML 18.18362

**Comment by petteas** [comment]
I also expreience this issue

**Comment by treago** [comment]
Actually this issue is related to the dependency package - [react-input-autosize](https://github.com/JedWatson/react-input-autosize).
There is a workaround here [#100](https://github.com/JedWatson/react-input-autosize/issues/100)

**Comment by bladey** [comment]
Hi all,

As @treago mentioned, this is an issue with `react-input-autosize`.

If you disagree, please let me know and I'll reopen the issue.
