### ISSUE TITLE
The constrained menu placement case should be skipped when closeMenuOnScroll will evaluate to true

### ISSUE THREAD

**Issue by bzalasky** [JedWatson/react-select#3810]
At Lookout, we're using react-select on a page that allows users to configure a variety of options (which means that some of them are rendered towards the end of the page). 

In each case, there are no more than 5 or so options, so we like the height of the menu to adapt to the number of options. Moreover, these options are rendered inside a responsive Bootstrap table, so this requires us to use both the `menuPosition="fixed` and `closeMenuOnScroll={()=> true}` props to avoid overflow clipping issues in some cases.

For the second to last Select on this page, the menu doesn't flip to `menuPlacement="top"` as expected, instead, the height of the menu is constrained and it's rendered with `menuPlacement="bottom"`.

This isn't the behavior we want for this page, and it's not even a valid option given the way closeMenuOnScroll evaluates. The user can never meaningfully see or interact with any options that aren't visible without scrolling.

As a hack, we can resolve this issue by passing a `minMenuHeight="Infinity"` to short circuit the logic in: https://github.com/JedWatson/react-select/blob/b7868d23ccd0b9e623b277f971e89020d426fbdb/packages/react-select/src/components/Menu.js#L110

However, I thought it'd be better to raise this issue here.

I'd like to propose making closeMenuOnScroll a boolean prop (or otherwise understand the case for it being a function better). If it were a boolean prop, we could check its property in getMenuPlacement to decide on the best approach for placing the menu. If this isn't an option, I think we need to reconsider the implementation of this function.

**Comment by lukebennett88** [comment]
Hi @bzalasky,

In an effort to sustain the react-select project going forward, we're cleaning up old issues and pull requests.

As this suggestion would be a breaking change, I've added the 6.0 milestone to this issue, and will move it to the ideas section discussions
