### ISSUE TITLE
The input doesn't lose focus, after an option has been selected

### ISSUE THREAD

**Issue by iloveip** [JedWatson/react-select#3811]
The input doesn't lose focus, after an option has been selected (as you can see in this test sandbox https://codesandbox.io/s/k5rvn9z3lv). The focus is lost only if you click outside the input.

Is this an intended behavior or a bug?

**Comment by DonkeyAfterDark** [comment]
I believe that is how select boxes are intended to work. You can test this functionality out using base HTML here: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

Note that the focus does not leave the select box after selecting an item in the dropdown.

**Comment by iloveip** [comment]
Thank you very much! Are there any reasoning behind it?
