### ISSUE TITLE
isSelected not working

### ISSUE THREAD

**Issue by sarabs3** [JedWatson/react-select#3817]
I am trying to change the font weight to bold when option is being selected but `isSelected` is not working.
Here is the codesandbox link
https://codesandbox.io/s/react-codesandboxer-example-9gpp4

I try to debug it with `react-devtools` it's not getting `isFocused` `isDisabled` and everything else but not `isSelected` is not there.

**Props**
```
{
  "value": {
    "label": "Off Trade",
    "value": "offTrade",
    "id": 2,
    "questionKey": 3
  },
  "options": [
    "Object",
    "Object",
    "Object",
    "Object"
  ],
  "styles": {
    "control": "control()",
    "option": "option()",
    "indicatorSeparator": "indicatorSeparator()",
    "dropdownIndicator": "dropdownIndicator()"
  },
  "onChange": "fn()",
  "inputValue": "",
  "menuIsOpen": false,
  "onInputChange": "fn()",
  "onMenuClose": "fn()",
  "onMenuOpen": "fn()",
  "backspaceRemovesValue": true,
  "blurInputOnSelect": false,
  "captureMenuScroll": true,
  "closeMenuOnSelect": true,
  "closeMenuOnScroll": false,
  "components": {},
  "controlShouldRenderValue": true,
  "escapeClearsValue": false,
  "filterOption": "fn()",
  "formatGroupLabel": "formatGroupLabel()",
  "getOptionLabel": "getOptionLabel()",
  "getOptionValue": "getOptionValue()",
  "isDisabled": false,
  "isLoading": false,
  "isMulti": false,
  "isRtl": false,
  "isSearchable": true,
  "isOptionDisabled": "isOptionDisabled()",
  "loadingMessage": "loadingMessage()",
  "maxMenuHeight": 300,
  "minMenuHeight": 140,
  "menuPlacement": "bottom",
  "menuPosition": "absolute",
  "menuShouldBlockScroll": false,
  "menuShouldScrollIntoView": true,
  "noOptionsMessage": "noOptionsMessage()",
  "openMenuOnFocus": false,
  "openMenuOnClick": true,
  "pageSize": 5,
  "placeholder": "Select...",
  "screenReaderStatus": "screenReaderStatus()",
  "tabIndex": "0",
  "tabSelectsValue": true
}
```
**State**
```
{
  "ariaLiveSelection": "option Off Trade, selected.",
  "ariaLiveContext": "Select is focused ,type to refine list, press Down to open the menu, ",
  "focusedValue": null,
  "inputIsHidden": false,
  "isFocused": false,
  "menuOptions": {
    "render": "Array[0]",
    "focusable": "Array[0]"
  },
  "selectValue": [
    {
      "label": "Off Trade",
      "value": "offTrade",
      "id": 2,
      "questionKey": 3
    }
  ]
}
```

**Comment by cutterbl** [comment]
I would do this by setting the option styles. See [this documentation](https://react-select.com/styles#styles) for a little more clarity.

**Comment by sarabs3** [comment]
@cutterbl I am also doing that way. Have a look at below code.
```
...
option: (styles, state) => ({
  fontWeight: state.isSelected ? 900 : 400
})
```

But isSelected state is not being changed.

**Comment by crhayes** [comment]
@sarabs3 In your codesandbox you are styling the control, not the option. 

i.e. your code looks like:

```js
const customStyles = {
  control: (styles, state) => ({ // should be option, not control
    ...styles,
    fontSize: state.isSelected ? 40 : 20
  })
};
```

Making the code like this:

```js
const customStyles = {
  option: (styles, state) => ({ // should be option, not control
    ...styles,
    fontSize: state.isSelected ? 40 : 20
  })
};
```

will result in:

![image](https://user-images.githubusercontent.com/727536/67727196-d0946780-f9be-11e9-814e-d728ee274d07.png)

Please close issue if this answers your question.

**Comment by sarabs3** [comment]
I want to increase the fontSize of the selected option, something like this

![not-selected](https://user-images.githubusercontent.com/3119576/67765621-96849d80-fa72-11e9-90c0-9c33c3504c1b.png)

After selection

![selected](https://user-images.githubusercontent.com/3119576/67765636-9e444200-fa72-11e9-9a68-d278ca316e5e.png)

**Comment by crhayes** [comment]
@sarabs3 You can inspect the contents of `state` to see if there is anything useful for your use case.

`isSelected` exists in the `option` state but not in the `control` state, which I think makes, given that the options are what are actually selected.

If you inspect the `state` in the `control` method you'll see the property `hasValue`. That should work for your use case:

```
control: (styles, state) => ({
  ...styles,
  fontSize: state.hasValue ? 40 : 20
})
```

![image](https://user-images.githubusercontent.com/727536/67783905-52c57000-fa41-11e9-935c-7344c1b9d377.png)

![image](https://user-images.githubusercontent.com/727536/67783941-607af580-fa41-11e9-8849-50e14319863e.png)

**Comment by sarabs3** [comment]
hasValue works!!
Thank you @crhayes 
There is no such documentation for this. I suggest all the available states need to be documented.

**Comment by lexith** [comment]
This is still an issue. It works as intended (with isSelected) with multi select. But with a simple single-select neither `isSelected` nor `hasValue` actually change for me. 
You can use the `data` property in the style state object to determine if it's selected or not though.

**Comment by luksari** [comment]
I suppose that `isSelected` property doesn't exist in `Select` not marked as `isMultiple`. So you can use `state.data === state.selectProps.value` in single choice `Select` to apply different style based on state.   
Example:
```javascript
 option: (provided, state) => {
    return ({
      ...provided,
      color: state.data === state.selectProps.value ? `${theme.colors.primaryText}` : `${theme.colors.disabledText}`,
      '&:hover': {
        color: theme.colors.primaryText,
        background: theme.colors.disabledBackground,
      },
    });
  },```
