### ISSUE TITLE
Can't see caret when blur and focus back to the select

### ISSUE THREAD

**Issue by dayanlemos** [JedWatson/react-select#3819]
## Problem
Can't see caret when blur and focus back to the select

## Steps to reproduce: 
- Choose an option on a single select
- Move the focus to the next element using Tab key
- Move the focus back to the select using Shift + Tab.
- Verify the caret doesn't show up.

If you repeat the steps, then it's possible to see the caret.

## Screen captures
https://www.youtube.com/watch?v=-nuuLbMaN5c

**Comment by bladey** [comment]
Thanks for the report @dayanlemos, I'm going to close this in favor of #3832 which has a bit more information.
