### ISSUE TITLE
Using React Select in CodePen

### ISSUE THREAD

**Issue by dgwyer** [JedWatson/react-select#3820]
I'm having a little difficulty using the React Select component in CodePen:

https://codepen.io/dgwyer/pen/YzzGmab

How do you import the component into the pen when including it via a CDN rather than installing as a local dependency? e.g. Something like:

`const {Select} = 'react-select';`

Perhaps this method could be added to the docs too?

![scrn](https://user-images.githubusercontent.com/1482075/67140913-cf449b80-f256-11e9-89ab-050f6c738137.png)

**Comment by Sedaj** [comment]
Were you able to find a solution  ?

**Comment by dgwyer** [comment]
Not yet, I still can't get it to recognize the 'react-select' component.

**Comment by bladey** [comment]
Hi @dgwyer,

It appears you can use `react-select` via a CDN with the following code - https://stackoverflow.com/questions/53927307/how-to-import-from-react-select-cdn-with-react-and-babel

Let me know if this solves your issue.

**Comment by dgwyer** [comment]
@bladey Already doing that.

**Comment by bladey** [comment]
Thanks for replying @dgwyer - and you're saying it's still not working? Your Codepen is out of date and doesn't refer to the method above.

**Comment by dgwyer** [comment]
The codepen uses a CDN to load the react-select script.

See my original post: "How do you import the component into the pen **when including it via a CDN**"

**Comment by bladey** [comment]
Thanks for taking the time to reply to me @dgwyer, much appreciated.

**Comment by ebonow** [comment]
Greetings @dgwyer ,

I am combing through trying to resolve outstanding issues and figured I'd take a shot at this. I do not know if anything has changed from when you had last tried, but I was able to successfully create an account and project to run `react-select`

I followed the directions [here which was just posted 2 weeks ago](https://blog.codepen.io/2020/11/18/skypack-codepen/), so I will assume that this is a relatively new process, but one that worked for me.

Apparently there is a new feature that will allow a project to import npm modules from a cdn and the codepen bundler can be enabled to process them. The very bottom of the page has a link referring to the necessary build process for JSX projects and I copied the project example and adapted it to work with react-select.

[Please feel free to fork this project](https://codepen.io/ebonow/project/editor/XmBQWn) and let me know if it works for you. If not, we can always reopen the issue.

Cheers and best of luck!
