### ISSUE TITLE
React Select V2 -  add isHoverRemove to state

### ISSUE THREAD

**Issue by tzviyacohenduda** [JedWatson/react-select#3825]
use case:
When hover the `multiValueRemove`, I need to change the style of `multiValue`. 
Example: jira tags - when hovering the tag removal, the whole tag background become red.

is something like isHoverRemove can be added to state?  (like isSelected etc..)

**Comment by mmarchuk-jama** [comment]
You can actually do something like this for hovering functionality:

``` 
  const styleOverrides = {
      multiValueRemove: (base, state) => ({
        ...base,
        ':hover': {...your styles here},
      }),
    }
```

**Comment by bladey** [comment]
Thanks for the assistance @mmarchuk-jama.

@tzviyacohenduda did this end up assisting you?

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.
