### ISSUE TITLE
React-select multi doesn't refocus after selection in Firefox

### ISSUE THREAD

**Issue by grsoares21** [JedWatson/react-select#3834]
This is reproducible even in the main example for multi in React Select's home page.
https://react-select.com/home 

If you open it with Chrome, you can see it maintains the select focused once you select an option.
However if you try it on Firefox it will blur when you select and option.

Probably there's a workaround by manually calling the focus function, just wanted to report it for you guys to be aware.

**Comment by bladey** [comment]
Hi @grsoares21,

It looks like the latest version of Firefox has resolved this, if it is still an issue for you, could you please let me know.
