### ISSUE TITLE
Wait before sending AJAX call

### ISSUE THREAD

**Issue by radar** [JedWatson/react-select#384]
How can I get react-select to wait for someone to stop typing before making an async call so that I don't get calls like this?

![image](https://cloud.githubusercontent.com/assets/2687/9300271/73e5f87a-4507-11e5-85a0-124f4c14a775.png)

**Comment by janmyler** [comment]
Hi @radar, in our project, we use [throttle](https://lodash.com/docs#throttle) or [debounce](https://lodash.com/docs#debounce) methods from _lodash_ to wrap the function we pass into `asyncOptions` prop. 

If you want to wait for the user to stop typing for a certain amount of time, `debounce` is what you're looking for. Of course, any implementation of debouncing will do.

**Comment by radar** [comment]
Wonderful, thank you @janmyler!

**Comment by fletcher91** [comment]
For people not wanting to use external libraries for this, a simple timeout also does the trick:

```
window.clearTimeout(this.currentFetchTimeout);
this.currentFetchTimeout = window.setTimeout(() => {
          // Do some fetching and call callback();
});
```

**Comment by vgoklani** [comment]
Hi @janmyler could you please post a good snippet for how you implemented throttle/debounce with react-select? Thanks!

**Comment by marcelometal** [comment]
You can use [es6-promise-debounce](https://github.com/bollwyvl/es6-promise-debounce).

```
<Select.Async
...
loadOptions={debounce(this.getItem, 500)}
... />
```

**Comment by mikdatdogru** [comment]
thanks @marcelometal 

perhaps you may be afraid to use a package that does not actively develop like me.
so you can use the lodash.

```
import _ from 'lodash';

 <Select.Async
    ...
    loadOptions={_.debounce(this.getItem, 500)}
    ...
/>
```
