### ISSUE TITLE
On hover? cursor 'unset'

### ISSUE THREAD

**Issue by TextError** [JedWatson/react-select#3849]
Is there a way to set cursor 'unset' on hover?
  control: styles => ({
    ...styles,
    border: '1px solid var(--Shadow)',
    boxShadow: 'none',
    '&:hover': {
        border: '1px solid var(--Shadow)',
    },
    height: 41,
    ':hover': {cursor: 'unset'}
}),

i`ve tried !important and nothing happened, however cursor pointer is working.
thanks

**Comment by codercodingthecode** [comment]
can you add a codesandbox example?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
