### ISSUE TITLE
loadAsyncOptions fails when value of Select is null

### ISSUE THREAD

**Issue by bkotyik** [JedWatson/react-select#385]
loadAsyncOptions lacks a null checking of input variable in the first line.  If the value of a Select is null by default, loadAsyncOptions fails immediately. 

I think having null values bound to an input controller is not a bad practice at all, and the method should have a null check in the first line.

**Comment by janmyler** [comment]
+1 for this. Fixed the issue temporarily using `cacheAsyncResults={false}` to cut off the for loop throwing the error.

**Comment by PetrSnobelt** [comment]
+1. Workaround for me is passing empty string instead of null

**Comment by gabadi** [comment]
+1

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
