### ISSUE TITLE
Custom Styles documentation example

### ISSUE THREAD

**Issue by codercodingthecode** [JedWatson/react-select#3851]
https://github.com/JedWatson/react-select/pull/3850

Add explanation in the docs on how to access custom props for ```customStyles```

Pass in a custom prop

![image](https://user-images.githubusercontent.com/20182536/68552281-e0f30c00-03da-11ea-9028-ab834c6a9431.png)

Access to the custom prop in ```selectProps```
![image](https://user-images.githubusercontent.com/20182536/68552302-2d3e4c00-03db-11ea-8fc8-78837f66a3fe.png)

Consume the prop in customStyle composition as a prop.
![image](https://user-images.githubusercontent.com/20182536/68552328-71315100-03db-11ea-8bcc-a974b7d36e0f.png)

**Comment by JedWatson** [comment]
Fixed by #3850

**Comment by emilie-t-ledn** [comment]
Can we get more documentation and/or a CodeSandBox example about using `customStyles` with TypeScript. I can't seem to find the correct typing.

If I don't pass anything to `StylesConfig` like the screenshot above I get the follow error:
![image](https://user-images.githubusercontent.com/92823139/171447143-1d3ca55f-1ef1-4569-8dd8-9d466a6bc726.png)

If I pass a basic Option type, I get a different error

![image](https://user-images.githubusercontent.com/92823139/171447393-419d51b0-bb02-4450-924b-c6956c6c627e.png)

![image](https://user-images.githubusercontent.com/92823139/171447512-58a96fd8-5313-4043-b9a5-fcdf306cc013.png)

I don't get why `Option` is not assignable to `SelectOption` (note that I'm in a wrapper component)

Thanks

**Comment by codercodingthecode** [comment]
@emilie-t-ledn 
I'm not 100% sure what you were trying to achieve, but the warnings/error I was getting was only about semantics really.

The Component
![image](https://user-images.githubusercontent.com/20182536/171485597-7e627261-081f-4e78-8328-a682e037fa2c.png)

The Custom Style
![image](https://user-images.githubusercontent.com/20182536/171485783-d12d2c83-f87c-45ca-80ee-48e3ea9d8f0c.png)

I just simplified the props a little on the wrapper, which is where the issue was., if there is any reason you need it more customized for the wrapper props. You can start from this and build on top of it.
https://codesandbox.io/s/codesandboxer-example-forked-tr5e5x?file=/example.tsx

Unless I'm missing something, I don't think the docs need updating. I hope this works.

**Comment by emilie-t-ledn** [comment]
Then I would say the "Wrapping the Select component" section in https://react-select.com/typescript is wrong as I spent hours trying to fix the typing only to found out with your example that removing the generics fixed my issues. I'm relatively new to typescript, so maybe I was missing something. Thanks for the help though :)

**Comment by codercodingthecode** [comment]
> 

that's probably a fair point.
maybe open a new issue as this is closed already and tag this thread to it as a reference.
