### ISSUE TITLE
Multi Select: display only selected items count after x number of items are selected/shown in chips

### ISSUE THREAD

**Issue by veronicaerick** [JedWatson/react-select#3856]
Thank you for all of the work you do on RS :)

I am looking to customize the multiselect and wondering if you have a recommendation for how to achieve the desired results. 

Right now, with many selections the select component takes up a prohibitive amount of space for certain UIs. I'd like to utilize the chip display within the input but show only a few selected options (like 3/4 max) and then add a "badge" count for the number of selected options that aren't shown in the value container in the input. The options that are selected but are past the max number of chips allowed to show in the input should show as selected within the dropdown list. I've implemented part of this with using a custom `ValueContainer` to show only the first few chip selections, and then add a count of additional selections. I'm unsure of how I can utilize prop `hideSelectedOptions` to achieve this to show selected items in the list *only* when my max is met.. 

Here's what I have so far: https://codesandbox.io/s/custom-react-select-sjtib

Current:
<img width="544" alt="Screen Shot 2019-11-14 at 4 42 53 PM" src="https://user-images.githubusercontent.com/18318386/68907932-625ddd80-06fe-11ea-8ba4-a73bbf109027.png">

 
Desired: 
<img width="544" alt="Screen Shot 2019-11-14 at 4 41 22 PM" src="https://user-images.githubusercontent.com/18318386/68907775-dea3f100-06fd-11ea-8638-0928709d38d8.png">

**Comment by Valgoku01** [comment]
Hello @veronicaerick ,

I faced the same issue and I think you have to ask yourself how dynamic your component should be.
By looking at your code, you are considering that 3 items will be rendered. Right. But have you thought of smartphone and so one ? If you shrink the browser, your badge goes under your items, etc.
I've neven been keen on introducing static variables into JS dynamic world.

To answer your question, I solved it by implementing `ValueContainer` and displaying a `string` of my selected items. Then you can add your badge into the `DropDownContainer` (I think, I'm not in front of my code) by adding a `string `displaying the number of selected items and then your `children`, including the drop down.
Then with a bit of css you activate `ellipsis` of your displayed item `string` and you're good to go.

I didn't find any easy way to do what you are asking.

**Comment by jekozyra** [comment]
@Valgoku01 do you have an example of what you did? I'm facing a similar issue.

**Comment by ebonow** [comment]
Greetings,

Thought I would take a shot at this. 

I think the best way to approach this is to filter the available options provided to the Select. This way you could avoid using styling or more custom components

```
const selectedVals = values.map(x => x.value);
const hiddenOptions = selectedVals.length > 3 ? selectedVals.slice(0, 3) : [];
const options = colourOptions.filter(x => !hiddenOptions.includes(x.value))

return <Select options={options} .../>
```

I created a fork of your demo here:
https://codesandbox.io/s/custom-visible-multivalues-8zh8c?file=/example.js

A few small tweaks:
One small addition, I added some title text to the badge to allow desktop users to get a default tooltip displaying the missing chips when hovering on it the badge. 

I also thought the badge should only render when there are hidden selections to avoid the blue dot when there aren't more than 3 selected, so I updated the render conditional.

**Comment by ebonow** [comment]
Since there has been no reply, we will be closing this issue to focus on ongoing issues. Please feel free to reply if there are any other questions.

**Comment by thiagopnobre** [comment]
I was trying to do the same in an `AsyncSelect` and I managed to create a solution based on @ebonow 's solution.

So, I'm sharing a partial example of what I did to make it work, because this might help others:

```es6
import React, { forwardRef, useEffect } from 'react';
import { components } from 'react-select';
import AsyncSelect from 'react-select/async';

const LimitedChipsContainer = ({ children, hasValue, ...props }) => {
  if (!hasValue) {
    return (
      <components.ValueContainer {...props}>
        {children}
      </components.ValueContainer>
    );
  }

  const CHIPS_LIMIT = 2;
  const [chips, otherChildren] = children;
  const overflowCounter = chips.slice(CHIPS_LIMIT).length;
  const displayChips = chips.slice(overflowCounter, overflowCounter + CHIPS_LIMIT);

  return (
    <components.ValueContainer {...props}>
      {displayChips}

      {overflowCounter > 0 && `+ ${overflowCounter}`}

      {otherChildren}
    </components.ValueContainer>
  );
};

export default forwardRef((props, control, rules) => {
  const {
    loadOptions,
    options,
    placeholder,
    ...selectSearchProps
  } = props;

  return (
    <AsyncSelect
      className="select-search"
      classNamePrefix="select-search"
      placeholder={placeholder}
      loadOptions={loadOptions}
      components={{ ValueContainer: LimitedChipsContainer }}
      {...selectSearchProps}
    />
  );
});
```

The trick here is to understand that the first child of the `ValueContainer` is the array of selected options when the input has values. With this in mind, I could just make a slice (in my case showing the last two selected options) and return the chips, the counter and the remaning children after it.

But, do notice this: when the `hasValue` returns `false` you can't do a slice because the first child is not the array of selected options. Hence the guard-clause.

Hope this helps.

**Comment by colinscruggs** [comment]
> I was trying to do the same in an `AsyncSelect` and I managed to create a solution based on @ebonow 's solution.
> 
> So, I'm sharing a partial example of what I did to make it work, because this might help others:
> 
> ```js
> import React from 'react';
> import AsyncSelect from 'react-select/async';
> import { components } from 'react-select';
> 
> const LimitedChipsContainer = ({ children, hasValue, ...props }) => {
>   if (!hasValue) {
>     return (
>       <components.ValueContainer {...props}>
>         {children}
>       </components.ValueContainer>
>     );
>   }
> 
>   const CHIPS_LIMIT = 2;
>   const [chips, otherChildren] = children;
>   const overflowCounter = chips.slice(CHIPS_LIMIT).length;
>   const displayChips = chips.slice(overflowCounter, overflowCounter + CHIPS_LIMIT);
> 
>   return (
>     <components.ValueContainer {...props}>
>       {displayChips}
> 
>       {overflowCounter > 0 && `+ ${overflowCounter}`}
> 
>       {otherChildren}
>     </components.ValueContainer>
>   );
> };
> 
> export default ({ loadOptions, placeholder, ...selectSearchProps }) => (
>   <AsyncSelect
>     className="select-search"
>     classNamePrefix="select-search"
>     placeholder={placeholder}
>     loadOptions={loadOptions}
>     hideSelectedOptions={false}
>     isMulti
>     components={{ ValueContainer: LimitedChipsContainer }}
>     {...selectSearchProps}
>   />
> );
> ```
> 
> The trick here is to understand that the first child of the `ValueContainer` is the array of selected options when the input has values. With this in mind, I could just make a slice (in my case showing the last two selected options) and return the chips, the counter and the remaning children after it.
> 
> But, do notice this: when the `hasValue` returns `false` you can't do a slice because the first child is not the array of selected options. Hence the guard-clause.
> 
> Hope this helps.

Thank you for your implementation. I had to make some adjustments for my given use-case, but your code is exactly what I needed!

**Comment by Tooluloope** [comment]
Anyway to make it responsive without putting the CHIPS_Limit constant..

Like making sure it doesn't go multiline and once it reaches the end, it just adds up in the value container

**Comment by ebonow** [comment]
@Tooluloope , 

I suppose it would be possible by implementing an IntersectionObserver in the ValueContainer and doing some calculations on its children, but the work to produce this wouldn't be "simple".

**Comment by nasir-ansari** [comment]
Good implementation

**Comment by Chandan4862** [comment]
can we hover on '+n items selected' and display all the items there on a div

**Comment by binDongKim** [comment]
Wonder if we could handle this based on the selected chips width, not with the maxCount.
