### ISSUE TITLE
onChange fires twice on click for custom Options, documentation update?

### ISSUE THREAD

**Issue by jdolearydl** [JedWatson/react-select#3859]
Reproduced (only occurs when clicking directly on the text):
https://codesandbox.io/s/react-codesandboxer-example-z6tqt

When passing {...innerProps} to a custom option, the element receives the onClick again from innerProps and when clicking on a choice (only when clicking, not when pressing enter), the onChanged callback fires twice

**Comment by jdolearydl** [comment]
Note, this only occurs when clicking directly on the text in the option.  Maybe this has something to do with event bubbling?

**Comment by jdolearydl** [comment]
In my custom option, I'm using both components.Option AND spreading innerProps.
```js
    return <components.Option {...props}>
      <div {...innerProps}>
```
Is that the issue?  Should it be one or the other?

**Comment by yaeltu** [comment]
what does onClick in innerProps do?

**Comment by jdolearydl** [comment]
It fires the onChange callback passed to the selector, you can see it in action if you click on the text of an option in my codesandbox.

I think it's something that react-select uses internally.

**Comment by yaeltu** [comment]
When I tried to use my own changeHandler, it fired once.
So I'm thinking the problem is with the onClick that comes from the innerProps.

**Comment by yaeltu** [comment]
Another thing I have noticed:
If you wrap Select in a div, inside SingleSelect class, 
onChange fires once. Have no idea why.

**Comment by jdolearydl** [comment]
I'm going to close, as I believe this is related to using both innerProps and components.Option

**Comment by Mosquid** [comment]
@jdolearydl were you able to resolve the issue?
