### ISSUE TITLE
Async selector's "isLoading" prop not working

### ISSUE THREAD

**Issue by Mujaddadi** [JedWatson/react-select#3861]
I know that this issue has been reported earlier but I am not sure whether it is fixed or not. If I try to set the loading state manually by passing the `isLoading ` prop to the selector, it doesn't show loading effect.  I modified the example provided in the doc a bit- You can check it here.
[`Example`](https://codesandbox.io/s/react-codesandboxer-example-wcghf?fontsize=14&hidenavigation=1&theme=dark)

Without this prop working, we can't use react-select's Async functionality, if we are using any side effect library such as saga. The example given in documentation expects us to call the api inside the `loadOptions` function by using promises etc.

**Comment by alexristich** [comment]
Looks like it's fixed but not yet released: https://github.com/JedWatson/react-select/pull/3690#issuecomment-537376200.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
