### ISSUE TITLE
formatCreateLabel breaks with getOptionLabe/Value with isMulti

### ISSUE THREAD

**Issue by phamj88** [JedWatson/react-select#3862]
formatCreateLabel is not working with getOptionLabel/getOptionValue/getNewOptionData/isMulti
Functionality works, just the custom text in formatCreateLabel does not get applied.

Why does getNewOptionData pass the value and the formatCreateLabel text as parameters?
Am i supposed to do something with the createlabel?

https://codesandbox.io/s/relaxed-fermat-y8g6i

**Comment by IanVS** [comment]
Yes, you need to set the `label` (using whatever `labelKey` you're using) to the second parameter passed to `getNewOptionData`.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by alexkim205** [comment]
Bump
