### ISSUE TITLE
Dropdown panel does not overlay on top of divs

### ISSUE THREAD

**Issue by jakeleventhal** [JedWatson/react-select#3863]
I noticed that the dropdown does not overlay correctly on top of divs.

I made a sandbox that illustrates this clearly https://codesandbox.io/s/wonderful-fermi-itbx3

If you go to the bottom of the table and expand the dropdown, the other two options either render on top of the table or dropdown upwards to avoid getting cut off. `react-select` requires the user to scroll and expand the div.

**Comment by fallenmel** [comment]
have you solve the issue?

**Comment by fallenmel** [comment]
is there a fix or workaround on this issue?

**Comment by shlgug** [comment]
You need to put the menu portal on the document.body level and then solve a different issue whereby scrolling causing the dropdown to be mis-positioned.

Here is the solution that I used (using React Hooks):

```
import React, {useRef} from 'react'
import Select from "react-select";

const MyComponent = props => {
    const selectRef = useRef(null);
    const selectMenuRef = useRef(null);

    const Menu = props => {
        return (
            <div ref={selectMenuRef}>
                <components.Menu {...props}>{props.children}</components.Menu>
            </div>
        );
    };

    const positionMenu = () => {
        //Since we are using menuPosition={'fixed'} below to solve the issue where the dropdown was being cut-off, we need to solve a different issue whereby the positioning of the menu was incorrect on scroll 
        const menuContainerElement = selectMenuRef.current.parentElement;
        const selectRect = selectRef.current.select.controlRef.getBoundingClientRect();
        menuContainerElement.style.left = `${selectRect.left}px`;
        menuContainerElement.style.top = `${selectRect.bottom}px`;
    };

    const handleOnMenuOpen = () => window.addEventListener('scroll', positionMenu);

    const handleOnMenuClose = () => window.removeEventListener('scroll', positionMenu);

    return (
        <Select
            ref={selectRef}
            menuPortalTarget={document.body}
            menuPosition={'fixed'}
            components={Menu}
            onMenuOpen={handleOnMenuOpen}
            onMenuClose={handleOnMenuClose}
        />
    )
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by 1v** [comment]
Still relevant issue https://codesandbox.io/s/sweet-night-8553o
