### ISSUE TITLE
Not working inside carousel

### ISSUE THREAD

**Issue by guille-alibrate** [JedWatson/react-select#3864]
### Thanks for creating react-select!

Thanks for this awesome extensible lib.

# Error description
I've run in two similar issues these last days. One of them is that **react-select** stops working when placed inside a carousel (at least **Flickity**, specifically)

See this _sandbox_:
https://codesandbox.io/s/react-flickity-wx2go

Buttons works just fine. Also, **react-select** works fine outside the carousel. But place it inside, and it will never open. 

However, if you enable _mobile mode_ in chrome, react-select begins to work.

![image](https://user-images.githubusercontent.com/56847061/69449105-d587d500-0d38-11ea-9358-ca543158c39e.png)

Second issue I had these days was very similar. I'll not describe it here, but basically it was the opposite: react-select working on desktop mode and not working in mobile mode. 

I really can't figure out why. Is it something about events propagation/bubbling? I don't think so.

Any clue?

**Comment by bladey** [comment]
Hey @guille-alibrate,

Thanks for logging this issue.

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

However - if the issues you've outlined above are still relevant to you and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
