### ISSUE TITLE
onBlur not working with two react-select components of multiSelect

### ISSUE THREAD

**Issue by eran-or** [JedWatson/react-select#3867]
demo of the bug: 
https://codesandbox.io/embed/kind-dream-9kyqh?fontsize=14&hidenavigation=1&theme=dark

screenshot of the bug: 
![kind-dream-9kyqh - CodeSandbox - Google Chrome 11_25_2019 3_22_03 PM](https://user-images.githubusercontent.com/2806891/69544357-352feb80-0f98-11ea-9625-2cd04c991e9a.png)

when there is tow react-select components and one of them with closeOnSelect=false and isMulti=true

the onBlur is not working. also alot of bad things happened in real app and it's  not stable at all

code with demo and screenshot is provided

**Comment by bladey** [comment]
Hey @eran-or, thanks for the detailed issue. I'm having trouble reproducing this, `onBlur` appears to be working fine. Could you please provide a video of the issue from within the Codesandbox? Thanks!

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.
