### ISSUE TITLE
Make clear button an actual button

### ISSUE THREAD

**Issue by Wgil** [JedWatson/react-select#3874]
Hello,

I'm using `isClearable` prop and I'd like either to hide the clear button or make it an actual button so I can focus and use it as it since it's confusing to have this button and not be able to focus it using the keyboard.

Thanks

**Comment by ASchwad** [comment]
I build the same functionality. You should set IsClearable to false and create an extra button with an own stateHandler to clear the selected values. You should also define what your selectedValues are, in my case its this.state.selectedValues

`<Select
                            value={this.state.selectedValues}
                            isMulti
                            options={this.props.data}
                            classNamePrefix="select"
                            isClearable={false}
                            onChange={this.handleChange}
                        />`

`handleClearSelection = () => {
        this.setState({selectedValues: []})
      }`

`<Button onClick={this.handleClearSelection}>Clear Selected Values</Button>`

**Comment by ben-sykes** [comment]
Have you tried passing your own custom ClearIndicator component (i.e. an actual button like you mention) in? If so, what issue(s) did you run in to when attempting this?

Related documentation: https://react-select.com/components#replaceable-components

**Comment by Wgil** [comment]
@ben-sykes I missed that doc part! I'll try that out. Still, it'd be nice this would be the default

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
