### ISSUE TITLE
isSearchable still showing iphone keyboard menu

### ISSUE THREAD

**Issue by Mohammedalasaad** [JedWatson/react-select#3879]
Hi,
I think thats still not work good even with isSearchable=false ..
if we have another Input field on the same page and click on the select list it still shows iOS footer with "Done" button and arrow to jump between inputs in Safari "iPhone".
Any way to solve this?
https://i.ibb.co/jLh8RHc/Screenshot-2019-11-22-at-11-14-29.png

I am using the latest version 3.0.8
Thanks

**Comment by anhpt-bss** [comment]
hello, are you resolved it?

**Comment by Mohammedalasaad** [comment]
Hi, No really the problem still and I could not fix it yet! 
I will keep trying and see if I can fix it.

Regards

**Comment by bladey** [comment]
Hi @Mohammedalasaad,

I wanted to check in and see if you were still encountering this issue. We're triaging issues at the moment to sustain the project going forward.

**Comment by Mohammedalasaad** [comment]
Hi @bladey 
 I think it's from iPhone they show the arrows and Done word at footer. for all input fields.
So I don't think there is a way to fix this :)
Thanks a lot

**Comment by bladey** [comment]
Thanks @Mohammedalasaad!
