### ISSUE TITLE
asyncOptions Broke after setting "searchable" false

### ISSUE THREAD

**Issue by TCMiranda** [JedWatson/react-select#388]
Hello!
Just reporting some bug. I think the title says it all.

This is broke for me.

``` Javascript
<Select name="neighborhood" multi
    asyncOptions={ this.onGetNeighborhood }
    value={s.neighborhood}
    searchable={ true }
    onChange={ value => update('neighborhood', value) }/>
```

Gives me:

```
Uncaught TypeError: Cannot read property '0' of undefined
```

![captura de tela de 2015-08-18 13 07 58](https://cloud.githubusercontent.com/assets/10077439/9335403/304779ba-45aa-11e5-895a-e51742da47e1.png)

Using Webpack with Babel!

Thanks!

**Comment by bruderstein** [comment]
What does your `onGetNeighbourhood` pass to the callback?

**Comment by TCMiranda** [comment]
Hello @bruderstein 

I am formatting the values and passing them as follows:

```Javascript
//...
    .then( response => {

        const data = {
            options: response.data[0].map( e => ({ 
                value: e.name, 
                label: e.name 
            }) ),
            complete: true };

            this.setState({ neighborhoodData: data });

            cb(null, data);

```

It works without the `searchable={ false }`

Thanks!

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
