### ISSUE TITLE
When typing continuously, select input keeps expanding rather than wrapping in new line

### ISSUE THREAD

**Issue by dannnylin** [JedWatson/react-select#3880]
I have this scenario:
https://codesandbox.io/s/react-codesandboxer-example-4kz5f

If you keep typing continuously without stopping, the react-select component will keep expanding rather than keeping its original width.

**Comment by hnhegde** [comment]
I am encountering the same issue. How to fix the size of react-select? Would appreciate inputs from experts to resolve it.

**Comment by antonostrovsky** [comment]
Same here. Is it not possible to prevent the component from growing?

**Comment by ebonow** [comment]
Have you tried setting a width on the container? The input will stay constrained to the container so long as you specify a width.

```
const styles = {
    container: css => ({ ...css, width: '200px' }),
};

return <Select isMulti={true} styles={styles} ... />
```
If you wanted to constrain the multi values into one-line, this is possible too, but be forwarned that you will run into spacing issues quickly.
```
const styles = {
  // ...other styles...
    valueContainer: css => ({ ...css, "flex-wrap": "nowrap", "white-space": "nowrap", overflow: "hidden", 'text-overflow': 'ellipsis' })
}
```
You will need to decide how you want to let the user select 8 options and display that in some defined space. Do you want to flex them into unreadable widths (default behavior with the above changes) OR did you want to fit them full width but just cut them off (overflow: hidden) possibly only showing 2-3 values without any way for the user to identify what else they've selected?

If you choose the latter, then you would need to apply some styles on the multiValue components.

Personally, I render my multiValue as a single comma separated sorted value as a SingleValue component using checkboxes, text-overflow, and a tooltip (if over-flowing). 

<img width="347" alt="Screen Shot 2020-06-20 at 11 46 22 PM" src="https://user-images.githubusercontent.com/1007579/85216951-821e4980-b350-11ea-95f2-bf8f5f9073e5.png">

<img width="347" alt="Screen Shot 2020-06-20 at 11 46 22 PM" src="https://user-images.githubusercontent.com/1007579/85216940-674bd500-b350-11ea-9020-c3157725b022.png">


In any case, setting a width should be easy enough and should hopefully close out this issue.  Good luck!

**Comment by bladey** [comment]
Thanks for the assistance @ebonow.

@dannnylin, @hnhegde and @antonostrovsky could you please let me know if this solves your problem.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.

**Comment by uragecz** [comment]
Fixed width isn't possible sometimes.. what if we want to have 100% width on phone? This input breaks web with infinity resizing

**Comment by kurtwilliam** [comment]
I was able to solve this by adding these styles to the div with the class `react-select__input-container`

```
.react-select__input-container {
    overflow: hidden;
    white-space: pre-wrap;
}
```
