### ISSUE TITLE
Broken links to examples on this page

### ISSUE THREAD

**Issue by catherineluse** [JedWatson/react-select#3881]
https://jedwatson.github.io/react-select/

**Comment by Rall3n** [comment]
The documentation under https://jedwatson.github.io/react-select/ is an old version which was not disabled. 

The current documentation for the most recent version is located at https://react-select.com, with the one for version 1.x at https://v1.react-select.com. This one has functioning links to examples.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
