### ISSUE TITLE
How to stop the clearing of the data in Creatable component when user enters data in it.

### ISSUE THREAD

**Issue by SAGARACH65** [JedWatson/react-select#3882]
In the `Creatable` component when an option has been selected and the input field clicked, the cursor is shown at the beginning of the selected value and when the user starts typing the selected value gets cleared and new typed data is shown.

Is there any way to not clear the selected value and let the user start typing from where the cursor is present?

**Comment by bladey** [comment]
Hi @SAGARACH65,

I wanted to check whether PR https://github.com/JedWatson/react-select/pull/2176 would potentially solve your issue, please let me know.

Thank you!

**Comment by HTMLGhozt** [comment]
Unsure about the original poster, but after testing the PR it works for my _similar_ issue.

**Comment by bladey** [comment]
Thanks for the feedback @HTMLGhozt.

This issue will now be closed due to inactivity as there has been no response from the original author. If anyone has further feedback please let me know and the issue will be re-opened.
