### ISSUE TITLE
V3 hover Styling of custom Option components

### ISSUE THREAD

**Issue by hatton** [JedWatson/react-select#3883]
In #3159, we learned to copy the Option.js code in order to make custom Options highlight as the user moused over them, and to show the selected item.

However, I cannot get this to work with V3.0.8.

If you change [@fortezhuo 's Sandbox](https://codesandbox.io/s/6zxnx9kmxz) to react-select 3, the items lose all their styling. I.e., nothing highlights as you mouse over.

I have tried copying Option.js from V3's source: https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/Option.js, but that doesn't help.

What am I missing?

**Comment by hatton** [comment]
Looks like might be related to my lack of familiarity with emotion. I fixed my problem by changing

```
<article
      className={cx(
        css(getStyles("option", props)),
        {
          option: true,
```

to

```
<article
      style={getStyles('option', props)}
      className={cx(
        {
          option: true,
```

**Comment by johnnypovolny** [comment]
@hatton You got this working for option :hover? I have it set up the exact same as you do, and isSelected is only true for the actual singleValue which has been clicked on (and thus "selected").  The styling doesn't appear when you hover over the value, only for the option that's been clicked the most recently. Any ideas? Snippets below

Custom option: 
```
const CustomOptionOrSingleValue = (props) => {
  const { innerProps, innerRef, isDisabled, isFocused, isSelected, cx, getStyles, data: { label, value }, type, className} = props;
  const optionOrSingleValue = type === 'option' ? 'option' : 'singleValue';
  return (
    <div
      style={getStyles(optionOrSingleValue, props)}
      className={cx(
        {
          option: true,
          'option--is-disabled': isDisabled,
          'option--is-focused': isFocused,
          'option--is-selected': isSelected,
        },
        className
      )}
      ref={innerRef}
      {...innerProps}
    >
      {CUSTOM INNARDS HERE}
    </div>
  );
};
```
const styleObject = {
  singleValue: (styles, state) => ({
    ...styles,
  }),
  option: (styles, state) => ({
    ...styles,
    backgroundColor: state.isSelected ? 'red' : 'black',
  })
```

```
<Select
        styles={styleObject}
        components={{Option: CustomOptionOrSingleValue, SingleValue: CustomOptionOrSingleValue}}
        ....
/>

```

**Comment by hatton** [comment]
Yes. Rather than ::hover, I get this orange backround using isFocused:

![image](https://user-images.githubusercontent.com/8448/71209370-916cef00-2268-11ea-8f5a-501ff8a0035d.png)

from 

```
div
        {...innerProps}
        style={{
          ...getStyles("option", optionProps),
          backgroundColor: optionProps.isFocused ? saymore_orange : "white",
          fontWeight: optionProps.isSelected ? "bold" : "normal",
          color: "black"
        }}
```

Hope that helps.
