### ISSUE TITLE
Dropdown is abrupt closes right after expanding it

### ISSUE THREAD

**Issue by sgtkuncoro** [JedWatson/react-select#3886]
Hi, I found bug on firefox mobile screen, the dropdown is abruptly close right after expanding it

more detail please check the video

**Browser:** Firefox v71.0 (64-bit)
**OS:** Mac OS Mojave 10.14.6
**Mobile Screen:**  Samsung Galaxy S9/S9+ (360x740)
**Video:** https://www.loom.com/share/b82916939471485ca55344cc76797314
**CodeSandbox:** https://codesandbox.io/embed/k5rvn9z3lv?codemirror=1

**Comment by pedrogpimenta** [comment]
I have the same problem, don't even need to be on an actual mobile phone, Firefox with Touch emulation turned on has the same problem.

It's a `create-react-app` installation, it hasn't much going on, definitely no events that could collide with react-select (no event listeners at all).

Browser: Firefox v77.0.1 (64-bit)
OS: Windows 10

**Comment by aligreene** [comment]
I also have this issue. Only when changing to mobile or tablet view using Firefox.
