### ISSUE TITLE
Source links are broken in examples

### ISSUE THREAD

**Issue by nitinsurana** [JedWatson/react-select#3887]
Please navigate to https://jedwatson.github.io/react-select/
Click on any source links and notice that they're broken.
Unfortunately, the referred files are not even there in the repository anywhere; possibly things have changed quite a bit.

**Comment by alexristich** [comment]
The new documentation lives at https://react-select.com.

@JedWatson Would it make sense to add a notice at https://jedwatson.github.io/react-select/ linking to the new domain, or perhaps even redirect to the new domain?

**Comment by MilosJo** [comment]
@alexristich 
Hey I checked [https://react-select.com](https://react-select.com), but I cannot find examples that I have found on [https://jedwatson.github.io/react-select/](https://jedwatson.github.io/react-select/).
I would love to see source code for `GitHub users (Async with fetch.js) (Source)` example.

Any help appreciated.
Thanks

**Comment by alexristich** [comment]
It looks like they updated the examples in the newer documentation. I'm not sure the reasons for this, though it's possible (and likey) that the old documentation might even be out of date in some places.

Regarding Async, maybe this page helps: https://react-select.com/async. There are a few examples with accompanying code.

**Comment by Rall3n** [comment]
The documentation for version 2+ lives under https://react-select.com.

The old documentation has been moved to https://v1.react-select.com. All links there work as they should.

**Comment by MilosJo** [comment]
@Rall3n 
Thank you.
I can confirm that examples on this [https://v1.react-select.com](https://v1.react-select.com) page are working correctly.

Cheers!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
