### ISSUE TITLE
Select-input is visible when searchable={false} when using multi={true}

### ISSUE THREAD

**Issue by sambomartin** [JedWatson/react-select#389]
When

```
 <Select multi={true} searchable={false} disabled={disabled} onChange={this.onChange}
    value={this.props.value}
    options={options}
  />
```

Results in the control showing the select-input when using the `multi` option.

![image](https://cloud.githubusercontent.com/assets/1396237/9351895/e46b99da-4654-11e5-9de1-e1650175b3c4.png)

When compared with:

```
 <Select multi={true} xxxxxxsearchable={false} disabled={disabled} onChange={this.onChange}
    value={this.props.value}
    options={options}
  />
```

![image](https://cloud.githubusercontent.com/assets/1396237/9352274/eb4c1344-4657-11e5-9c80-169841bcaf2d.png)

This is element that is visible, that shouldn't be:

![image](https://cloud.githubusercontent.com/assets/1396237/9351937/33b6e7a6-4655-11e5-8226-ff0d1ec25759.png)

I can add a css rule to hide it, but wondered whether i'm doing anything wrong to cause it?

thanks

**Comment by vpatil** [comment]
+1, @sambomartin. Setting `display: none;` didn't work for me (seemed to break the toggling of the options list), so I had to add css to set height/margin/padding etc. to 0.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
