### ISSUE TITLE
React-select not scroll to select option on iphone

### ISSUE THREAD

**Issue by anhpt-bss** [JedWatson/react-select#3890]
https://api.media.atlassian.com/file/d68d3740-c9f5-443f-a553-66bbcc1346bd/artifact/video_640.mp4/binary?client=2d90ddfa-4fee-454f-ac32-e08b2b1a95c6&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIyZDkwZGRmYS00ZmVlLTQ1NGYtYWMzMi1lMDhiMmIxYTk1YzYiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmQ2OGQzNzQwLWM5ZjUtNDQzZi1hNTUzLTY2YmJjYzEzNDZiZCI6WyJyZWFkIl19LCJleHAiOjE1Nzc3NjQ0MDcsIm5iZiI6MTU3Nzc2MzQ0N30.5bpPtIzcjsycGZsAdit1B0nn7FhX_qjuQamSe-IceFI

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
