### ISSUE TITLE
onMenuClose doesn't trigger on mobile - closeMenuOnSelect is ignored

### ISSUE THREAD

**Issue by Vadorequest** [JedWatson/react-select#3893]
On mobile (Android 9), I'm experiencing two different issues. 

1. When I click on the react-select input, the keyboard is opened automatically (and sadly, can't do anything about it yet, see https://github.com/JedWatson/react-select/issues/3526) and I have to close it to see the available choices.
1. When I click on one of the choices, the menu gets closed (even though `closeMenuOnSelect` is false), and the `onMenuClose` isn't triggered either

This is particularly blocking when relying on `onMenuClose` to sync the selected choices with the state. In my case, I don't rely on the `onChange` event because I'm building a chatbot and I don't want to display the next message until the user is done selecting all its choices, therefore, I rely on `onMenuClose` event, but it doesn't perform well on mobile.

The only solution I can think of atm is to detect whether I'm running on mobile (great) and rely on onChange event when on mobile.

**Comment by elilambnz** [comment]
@Vadorequest does the recommended fix in #2771 solve your second issue?

**Comment by Vadorequest** [comment]
There were actually two issues here:

1. I found a workaround by disabling the search capability on mobile, so that the keyboard doesn't open, using `isSearchable={!isMobileDevice()}`
2. Using `blurInputOnSelect={false}` did fix my issue as stated in #2771 , thanks!

I'll close this issue then.
