### ISSUE TITLE
How do I add custom tooltips

### ISSUE THREAD

**Issue by mwei2018** [JedWatson/react-select#3896]
If the text is too long, how do I add tootip to the multiValueLabel, such as @atlaskit/tooltip
![image](https://user-images.githubusercontent.com/2967082/71885594-a527b900-3175-11ea-95c0-6c4942c0e6eb.png)

**Comment by cutterbl** [comment]
I would imagine you could do this by using your own, custom `MultiValueLabel` component. See [this area](https://react-select.com/components) of the documentation for some insight.

**Comment by mwei2018** [comment]
@cutterbl 

 I've done that thank you
