### ISSUE TITLE
How to provide key to multiple selects?

### ISSUE THREAD

**Issue by randal923** [JedWatson/react-select#3899]
Warning: Each child in a list should have a unique "key" prop.

I have multiple selects and I am trying to give them keys but I am not able to. Here is what I have right now: 

```
<Select
    placeholder="Select Director"
    key="directors"
    options={(directors ? directors : []).map(item => ({
        value: item._id,
        label: item.name,
    }))}
    onChange={this.addCastToState}
    value={this.state.directors}
    isMulti
/>
<Select
    placeholder="Select Actor"
    key="actors"
    options={(actors ? actors : []).map(item => ({
        value: item._id,
        label: item.name,
    }))}
    onChange={this.addCastToState}
    value={this.state.actors}
    isMulti
/>
```

**Comment by randal923** [comment]
My issue was that I was trying to setState for both selects in the same function. So, my
addCastToState function is like this:

```
addCastToState = (directors, actors) => {
      this.setState({ directors, actors });
};
```

This does not work, I had to create one function for each select, like this:

```
addDirectorsToState = (directors) => {
	this.setState({ directors });
};
addActorsToState = (actors) => {
	this.setState({ actors });
};
```

If anyone knows a way to do it in one function, please let me know.

**Comment by brinkofhumor** [comment]
Not that this has anything to do with what you are asking but you just solved a HUGE problem I've been having with trying to map a existing array to options. Thank you.
