### ISSUE TITLE
Issue with the OptionsType definition

### ISSUE THREAD

**Issue by josias-r** [JedWatson/react-select#3900]
When trying to access properties of the value passed to the onChange function, I get typescript errors, even though, those properties exist.

![Screenshot](https://user-images.githubusercontent.com/11424820/72208116-6f4d4200-349f-11ea-8629-0ca8e8095146.JPG)

As you can see from the screenshot, I have the DefinitlyTyped package installed.

**Comment by damianprzygodzki** [comment]
And also `OptionType` is not exported, so you can't type it by yourself.

My current workaround is:
```typescript
// Provide your own interface for option
interface OptionType {
  value?: string;
  label?: string;
}

const handleChange = ({value}: OptionType) => {
    if(!value) return;
    console.log(value);
  };

<Select onChange={handleChange} ...
```

**Comment by danieldelcore** [comment]
Hey that looks like the correct or at least acceptable approach for typescript users. 
Here's what i had, it relies on type guards to filter the different options: null, array, value.

```javascript
<Select
  {...props}
  onChange={value => {
    if (!value) {
      // Handle the undefined / null scenario here
    } else if (value instanceof Array) {
      // Handle an array here
      // You will likely get an array if you have enabled
      // isMulti prop
    } else {
      // Handle a single value here
    }
  }}
/>
```

**Comment by barrycarr** [comment]
I'm having a similar issue with antd 4.1.1

OptionsType, OptionData & OptionGroupData all need to exported so that they are available to client code.

**Comment by josias-r** [comment]
Thank you @danieldelcore, seems like a clean solution/workaround for now. I do think typescript would theoretically support the "automated" scenario though where the correct types are being interfered from the props.

**Comment by arthurmmedeiros** [comment]
Here's what worked for me based on what @damianprzygodzki suggested

```
import Select, { ValueType, OptionTypeBase } from 'react-select';

interface IOptionType extends OptionTypeBase {
    value?: number;
    label?: string;
  }

const MyComponent: React.FC = () => {
  const [campusId, setCampus] = useState<number>();


  function onChangeCampus(value: ValueType<IOptionType>) {
    const campusIdSelected = (value as IOptionType).value;
    if (campusIdSelected) {
      setCampus(campusIdSelected);
    }
  }
....
}
export default MyComponent;
```

**Comment by bladey** [comment]
Hi all,

It looks like this TypeScript issue has been resolved as per @damianprzygodzki, @danieldelcore, and @arthurmmedeiros responses.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

Thanks!

**Comment by AdrianMrn** [comment]
I agree with @josias-r in that the types should be able to infer the correct type of the selected option from the props. In this case, when `isMulti = false`, the `onChange` parameter can never be an array.

**Comment by Methuselah96** [comment]
@AdrianMrn The TypeScript types should be able to infer the correct types as of `@types/react-select@3.0.27` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49673).

**Comment by AdrianMrn** [comment]
@Methuselah96 My bad, you're right!

Sadly, the `Styles` type now requires 2 type arguments. I can't add the OptionType here, because I use the same style for all my select components. I also don't want to have to add it manually for each component, especially since I never had to, and it "just worked".

![image](https://user-images.githubusercontent.com/12762044/103788575-45414800-503f-11eb-9549-06b4749f5a2f.png)

**Comment by Methuselah96** [comment]
@AdrianMrn Perhaps you could use `Styles<OptionTypeBase, boolean>` (`OptionTypeBase` being imported from `@types/react-select) so that it will work with any of your components?

**Comment by AdrianMrn** [comment]
@Methuselah96 yeah I tried that, but then my components don't want to infer the type from their value anymore, and the selected option in onChange is `any` :(

I've just added a `//@ts-nocheck` to my styles file for now. I think the best solution would  be to make the style's type arguments optional, if this doesn't break anything else in the types, I might PR it at some point.

**Comment by Methuselah96** [comment]
@AdrianMrn That's a bit rough. There are some frustrating limitations/quirks to generics in TypeScript.

I'm skeptical that making the type arguments optional would work because that would just mean that they default to `OptionTypeBase` and `boolean` when the `styles` variable is declared (instead of picking up the generics from the component) and so it will have the same problem.

**Comment by AdrianMrn** [comment]
@Methuselah96 Oh well :/ I'll see if I can find some time to come up with a better solution at some point. Thanks for the help and discussion anyway, have a great 2021!

**Comment by macksal** [comment]
Could you make the `IsMulti` typeparam extend from `boolean | undefined`, then it can be inferred even when the `isMulti` prop is not supplied?

**Comment by Methuselah96** [comment]
In this particular case, I don't think it can be inferred even if it is `boolean | undefined` because the `Styles` variable is being declared and typed outside of the context of the component.

**Comment by J-Brk** [comment]
@bladey I don't see how this issue is fixed....

I just installed `react-select` and it has been a typescript disaster since the beginning. I tried the solutions above and are getting the error: "react-select has no exported member OptionTypeBase"

**Comment by Methuselah96** [comment]
@J-Brk That's because there were breaking changes in the types in v5. Please follow the [upgrade guide](https://react-select.com/upgrade#from-v4-to-v5) and then create a new issue or discussion if it's still unclear how to accomplish what you're trying to do.
