### ISSUE TITLE
Creatable doesn't work with getOptionValue and getOptionLabel props

### ISSUE THREAD

**Issue by mrjdavidfg** [JedWatson/react-select#3901]
When using `Creatable` component with `getOptionValue` and `getOptionLabel` props, the functionality to create new options does not work.

![creatable_issue](https://user-images.githubusercontent.com/20999009/72212777-d0314600-34b0-11ea-8a43-1868b794fe27.gif)

Sandbox simple example here: https://codesandbox.io/s/creatable-custom-label-value-xr63g

The current workarround I'm using is to map the options to `{ label, value }` format:

`options.map( opt => ({ label: opt.name, value: opt.id }) )`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by claudiutamas** [comment]
I'm using version 5.2.2 and the problem persists.

**Comment by chiptus** [comment]
should be re-opened, still happens

**Comment by Rall3n** [comment]
As already mentioned above using `getNewOptionData` fixes the issue. Standard implementation of an option is `{ label, value }`. If you use a custom option schema then you should also update the created option with this schema using the `getNewOptionData` prop.

```jsx
<Creatable 
   getOptionValue={({ id }) => id}
   getOptionLabel={({ name }) => name}
   getNewOptionData={(value, label) => ({ id: value, label: label, __isNew__: true })}
/>
```

------

A re-opening of this issue is not necessary.

**Comment by jaiganesh-i2i** [comment]
Thanks for your answer @Rall3n. While the answer helped to solve the issue, It takes a greate amount of time to debug and fix the issue to getOptionLabel and getOptionValue. Adding some coments in documentation should work.
