### ISSUE TITLE
Toggle Select creatability

### ISSUE THREAD

**Issue by oscarmorrison** [JedWatson/react-select#3905]
# Are you making a feature request? **Yes**

*   What's your use case?
As a user (of react-select), I would like to be able to toggle on a react-select field creatability or not.

*   What interface do you have in mind? (What new properties or methods do you think might be helpful?)
Perhaps on the `<Select canCreate={true} />` something of the sort.
I have times when the user has permission to create a new option, and sometimes the user doesnt.

*   Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)
I think this used to be the functionality in v1?

**Comment by ebonow** [comment]
Greetings @oscarmorrison ,

The CreateableSelect already has the ability to disable the ability to restrict the Select from creating new options. This can be done by conditionally setting 
- `isValidNewOption` always returns false if your "canCreate" is false
- `formatCreateLabel` return null if "canCreate" is false, and undefined if true (to allow default Create Option message to appear).

Here is a [codesandbox to verify this is working as expected
](https://codesandbox.io/s/react-select-toggle-createable-s31ed?file=/src/App.js)

``` JS
  const [isCreateable, setIsCreateable] = useState(true);
  const toggleCreatable = () => setIsCreateable(!isCreateable);
  const isValidNewOption = () => !!isCreateable;

  return (
      <Createable
        isValidNewOption={isValidNewOption}
        // if createable, return undefined to allow default behavior, else return null to remove
        formatCreateLabel={isCreateable ? undefined : null}
        options={options}
      />
```

This appears to resolve the functionality being asked so I will close the issue. Hope this helps!
