### ISSUE TITLE
Add a method to clear selected values 

### ISSUE THREAD

**Issue by priyanshu92** [JedWatson/react-select#3906]
First of all, a big thank you for making this amazing component. I have a small feature request to extend the existing functionality.

## Feature Request
Add a `clear` method (just like `focus` and `blur`) which consumers can call to clear the selected values.

I can send a PR if you want and think if this can help other users.

**Comment by flexdinesh** [comment]
@priyanshu92 There is already a `clearValue()` method exposed to clear selected values. You can access it through a ref like this - [clear value example](https://codesandbox.io/s/react-select-clear-value-3d2xn).

Feel free to shoot further questions or reopen this issue if that doesn't help you.

**Comment by aki-caffeine** [comment]
@flexdinesh
The linked program is written in javascript, is it possible to change it to typescript?

I'm having a type conversion error at the following location and I'm at a loss as to which type to use...

```
this.selectRef.select.clearValue()
```
