### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by randal923** [JedWatson/react-select#3909]
I am passing an array of objects to both options and values. I am passing them with a value and label just like what was advised here but when I setState I still get this key prop error.

```
addGenreToState = genre => {
    this.setState({ genre });
};

<Select
    options={(genres ? genres : []).map(item => ({
        value: item._id,
        label: item.name,
    }))} //example [{value: "1231321", label: "Fantasy"}]
    onChange={this.addGenreToState}
    value={(genre ? genre : []).map(item => ({
        value: item._id,
        label: item.name,
    }))} //example [{value: "12143234252", label: "Horror"}]
    isMulti
/>

```

**Comment by brinkofhumor** [comment]
You need to have a key after your mapping. 

options={(genres ? genres : []).map(item,key)=> ({
        key:key,
        value: item._id,
        label: item.name,

Search for array mapping javascript key help and I'm sure there will be some more information on it.

**Comment by randal923** [comment]
I have tried passing the key (index) like that before and I just tried it again but it did not work. I actually found a solution for this, I passed defaultValue instead of value and it worked.

**Comment by bladey** [comment]
Hi @randal923, it looks like this issue was resolved by yourself.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by hkung77** [comment]
@randal923 Could you explain what you meant by `defaultValue`?
