### ISSUE TITLE
how-to-fix-width-of-search-box-in-react-select-dropdown-component

### ISSUE THREAD

**Issue by jt3k** [JedWatson/react-select#3912]
https://stackoverflow.com/questions/44917956/how-to-fix-width-of-search-box-in-react-select-dropdown-component

**Comment by jt3k** [comment]
![Запись экрана 2020-01-22 в 03 58 10 (1)](https://user-images.githubusercontent.com/1261240/72857531-eddf8600-3cce-11ea-9068-4288eb8981ee.gif)

**Comment by flexdinesh** [comment]
Hey @jt3k, could you create a codesandbox that exhibits this behaviour? It'd be easier to see what's going on with code example in a codesandbox.

**Comment by bladey** [comment]
Hello @jt3k, if you could provide a Code Sandbox that would be ideal!

**Comment by bladey** [comment]
Hi all, this appears to be a duplicate of #3880, I'll close this issue as the original issue has a Code Sandbox link.

If you feel this issue is not the same and you'd like us to review it - please leave a comment and we'll do our best to get back to you.

**Comment by jt3k** [comment]
sorry friends, I was busy.
