### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code.

### ISSUE THREAD

**Issue by mikayelzarafyan** [JedWatson/react-select#3915]
react-dom.development.js:530 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: AutosizeInput, Select

**Comment by maximilianschmidt** [comment]
same error with 3.1.0 for me:

`Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code`

**Comment by lucasltv** [comment]
For me too! Same warning...

**Comment by JoeGreen1982** [comment]
Also getting the same error in 3.1.0....

**Comment by codewhynot** [comment]
The same error in 3.1.0

**Comment by 0xdevalias** [comment]
See also:
- https://github.com/JedWatson/react-select/issues/3745
- https://github.com/JedWatson/react-select/issues/3751

**Comment by Taally** [comment]
The same problem with "Update" component
![image](https://user-images.githubusercontent.com/22220219/81062705-24888780-8edf-11ea-91aa-583a3cc3de99.png)

**Comment by giacintayao** [comment]
I'm getting an error, not just a warning. 
index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: AutosizeInput, Select

**Comment by gempain** [comment]
In addition to the above, I am getting this one after I start selecting something:
```
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of NodeResolver which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by MenuList)
    in MenuList (created by MenuPlacer)
    in ScrollBlock (created by MenuPlacer)
    in NodeResolver (created by ScrollCaptor)
    in ScrollCaptor (created by ScrollCaptorSwitch)
    in ScrollCaptorSwitch (created by MenuPlacer)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by Menu)
    in Menu (created by MenuPlacer)
    in MenuPlacer (created by Select)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by SelectContainer)
    in SelectContainer (created by Select)
    in Select (created by StateManager)
```

**Comment by bladey** [comment]
Hi all,

Thank you to everyone who has provided information above.

As you may be aware, this bug has been reported multiple times as per issue #4094. On behalf of the maintainers I apologise it's taken awhile to get to this.

A new master issue #4094 has since been created to help keep track of this bug going forward.

This new issue will exist as the source of truth going forward to investigate the issue, report findings, and implement a bug fix.

**We'll take into account all the details above while investigating.**

If you feel this issue has been wrongly closed as it isn't related to the new master issue #4094, please let us know and we'll take another look.

Again, thank you.

**Comment by JanaSundar** [comment]
![Screenshot from 2020-08-12 16-37-21](https://user-images.githubusercontent.com/30264201/90008719-65e8ba00-dcba-11ea-9674-c5953558ae1e.png)

**Comment by Methuselah96** [comment]
@JanaSundar Follow https://github.com/JedWatson/react-select/issues/4094 to get the latest updates on this issue.

**Comment by junreyd** [comment]
Any updates for this bugs?

**Comment by golendercaria** [comment]
I've already bug in new blank project.

`Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: AutosizeInput, Select`

**Comment by ebonow** [comment]
@junreyd and @golendercaria 

Regarding an update on this, these have already been identified and are preparing PRs for a new release. You can read more about it here. https://github.com/JedWatson/react-select/issues/4293#issuecomment-743781662

**Comment by fadzrinmadu** [comment]
anyone can help me, I got this error too

**Comment by ebonow** [comment]
Greetings @fadzrinmadu ,

This issue was closed with the release of version 4. Can you please confirm which version of react-select you are using?

**Comment by shopglobal** [comment]
for me it's a react 18 dependency mismatch, it could be anything. Update depends in your package.json
