### ISSUE TITLE
Warning: Legacy context API has been detected within a strict-mode tree.

### ISSUE THREAD

**Issue by mikayelzarafyan** [JedWatson/react-select#3916]
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: MenuPlacer

**Comment by dpordomingo** [comment]
dupe from #3703

**Comment by dpordomingo** [comment]
This should be addressed by https://github.com/JedWatson/react-select/pull/3928

**Comment by bladey** [comment]
Closed in favor of issue #3703, will be resolved by #3928.

**Comment by markociglar** [comment]
It happens to me on 3.1.0 version (current).

**Comment by impulsivetomato** [comment]
I'm getting this too

**Comment by idrawdesigns** [comment]
Has this issue been resolved? getting the error on my side..

**Comment by alejandroyunes** [comment]
hello, I recently started receiving this warning, has anyone resolved this issue? thx in advance

**Comment by Loriick** [comment]
hello, I got this issue too.
has anyone known if this has been fixed ?

**Comment by KamaliyaVishal** [comment]
**This may help:**

> https://stackoverflow.com/questions/61647771/react-reactstrap-warning-legacy-context-api-has-been-detected-within-a-strict

**Comment by yuriburk** [comment]
Fixed?

**Comment by gal-instartsearchplus** [comment]
I got it now, please fix this issue.

**Comment by bladey** [comment]
Please refer to #3703.
