### ISSUE TITLE
Unable to edit selected value from AsyncSelect

### ISSUE THREAD

**Issue by AaronMcCloskey** [JedWatson/react-select#3917]
Currently, clicking on an AsyncSelect input doesn't allow you to edit the current selection, instead allows you to make a brand new search. 

Not sure if that functionality is there or not, currently. But it would be nice to be able to edit the current value. In my case, it's searching for an Address, just a bit of a hassle to type an address out again if you made an incorrect selection.

Came across these 2 current issues on my search

https://github.com/JedWatson/react-select/issues/1868
https://github.com/JedWatson/react-select/issues/1558

However, these fixes do not work for `AsyncSelect`.

```
handleFocus = element => {
  if (this.state.value) {
    // This works for regular Select but not Async
    this.select.state.inputValue = this.state.value.label;
  }
};
render() {
  const { isLoading, options, value } = this.state;

  return (
    <Async
      ref={ref => {
        this.select = ref;
      }}
      isClearable
      blurInputOnSelect={true}
      isDisabled={isLoading}
      isLoading={isLoading}
      onChange={this.handleChange}
      onCreateOption={this.handleCreate}
      onMenuClose={this.handleMenuClose}
      onFocus={this.handleFocus}
      loadOptions={this.getOptions}
      value={value}
    />
  );
}
```

Here is a [CodeSandbox][1] with the fix that works on `Select` but not on `Aysnc`

Does anyone have any suggestions? It would be greatly appreciated.

  [1]: https://codesandbox.io/s/create-select-with-fake-service-v9ki2

**Comment by punkrats** [comment]
Maybe this helps you: https://github.com/JedWatson/react-select/issues/1558#issuecomment-580961402

**Comment by AaronMcCloskey** [comment]
@punkrats That would like a charm, thank you!
