### ISSUE TITLE
Feature regressed and disappeared: Tab shifts focus

### ISSUE THREAD

**Issue by srevenant** [JedWatson/react-select#3918]
This apparently used to work properly, but now it's back to a double-tab to get out of a field.  Can we get it corrected?

Original issue and recent comments:

https://github.com/JedWatson/react-select/pull/708

**Comment by srevenant** [comment]
I created a PR: https://github.com/JedWatson/react-select/pull/3930

**Comment by lukebennett88** [comment]
Hi @srevenant.
As far as I can tell, what exists now is the expected behaviour. Pressing the tab key whilst the menu is open closes the menu, and pressing it a second time shifts your focus to the next selectable item.

**Comment by srevenant** [comment]
Sorry @lukebennett88 but the bug still exists.
The issue is slightly semantic, but creates a big UX friction imho.
I realize the difference is probably an opinion, so if anything a configurable option would be best.

Desired behavior:

1. Open menu.
2. Arrow key to option in menu
3. Press tab
4. Menu is closed AND Cursor moves to next field in form.

Current behavior:

1. Open menu.
2. Arrow key to option in menu
3. Press tab
4. Menu is closed, but cursor STAYS in menu — this is really confusing frankly, because typically tab means "go to next field."

It USED to work this way, and somebody changed it. I expect they changed it on purpose, but it's ... undesired :)
