### ISSUE TITLE
Click on select doesn't open dropdown

### ISSUE THREAD

**Issue by SebastianGalazka** [JedWatson/react-select#3921]
Hello

When i want to open or close select it's only work when i click dart. 
On click in select it doesn't open. 
When i click outside select it doesn't close. 
I use version 3.0.8.
` 
<Select
          isMulti
          placeholder={"..."}
          value={department}
          onChange={e => selectHandleChange(e, "department")}
          options={departmentList}
        />
`

**Comment by bladey** [comment]
Hey @SebastianGalazka,

I'm having trouble reproducing this, could you please create an example using the v3 Codesandbox link?

https://codesandbox.io/s/react-select-v3-sandbox-jgdch

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
