### ISSUE TITLE
AsyncCreatableSelect problem

### ISSUE THREAD

**Issue by ikito** [JedWatson/react-select#3924]
Hi, seems like AsyncCreatableSelect doesn't work on example page.
https://react-select.com/creatable

I'm trying to make test but can figure how it works.

**Comment by flexdinesh** [comment]
Hey @ikito, you can see what happens when you open devtools console.  In short, `onInputChange` callback is triggered with the created input and you can use that to perform userland task like adding it to the list of options or showing and error.

**Comment by flexdinesh** [comment]
I'm going to close this issue as the example works right. Pl feel free to open it if you need more clarification.
