### ISSUE TITLE
 how to set many select component association like department major grade class

### ISSUE THREAD

**Issue by tonys-Li** [JedWatson/react-select#3925]

**Comment by tonys-Li** [comment]
> _No description provided._

**Comment by tonys-Li** [comment]
such as department / major / grade / class / name

**Comment by tonys-Li** [comment]
thanks

**Comment by flexdinesh** [comment]
Hey @tonys-Li, there's not much info in this issue to follow up with. I'm gonna close it for now. Pl re-open if you think you can add more context later.
