### ISSUE TITLE
Type `data` as `OptionType` in Option component typings

### ISSUE THREAD

**Issue by rockchalkwushock** [JedWatson/react-select#3927]
I was making a custom `Option` component and wanting to type it correctly. I think maybe I came across and oversight in the typings. Shouldn't `data` be typed as the `OptionType`? At the moment it is typed as `any`.

```typescript
// 'react-select/src/components/Option'
export type OptionProps<OptionType extends OptionTypeBase> = PropsWithStyles &
  CommonProps<OptionType> &
  State & {
    ...
    data: OptionType, // Pass through OptionType here.
  };
```

If this is an oversight I'd be more than happy to submit the PR to fix this.

**Comment by ebonow** [comment]
Greetings @rockchalkwushock,

Sorry for the long wait for a reply on this. 

`Type OptionType` refers to the type of option. More specifically, it is one of either 'value' or 'option', (perhaps soon to also be 'group', but I digress...). You can see it is used in this context by the `formatOptionLabel` prop which is used to render JSX depending on whether it is intended to be in the menu or as the selected option.

`data` in the context you are referring to refers to the actual javascript object passed to the `Option`. While, it is expected that an option usually has a label and value, it can contain other information. This object is therefore correctly identified as `any`.

I will be closing this issue now but if you have any other questions or concerns, please feel free to reply.
