### ISSUE TITLE
React-select custom sorting for autocomplete results

### ISSUE THREAD

**Issue by dogzy123** [JedWatson/react-select#3934]
Hello, sorry for posting a question in issues I really tried to find an answer, but nothing found.

Is there an options to sort autocomplete results?
Like if I type: 'ge'

### Now:
'Al**ge**ria'
'Ar**ge**ntina'
'**Ge**rmany'
'**Ge**orgia'

### Would be nice to have
'**Ge**rmany'
'**Ge**orgia'
'Al**ge**ria'
'Ar**ge**ntina'

Thanks!

**Comment by quentindemetz** [comment]
Hi,

I think you can should use the `loadOptions` prop to perform your search "manually" through your options and put the results in the order you want.

**Comment by flexdinesh** [comment]
Hey @dogzy123, you can use `loadOptions` props to do what you want. More here — https://react-select.com/async

**Comment by flexdinesh** [comment]
Hey @dogzy123 I'm closing this issue now as this can be done following the docs. If you have further questions, feel free to reopen it.
