### ISSUE TITLE
IE11 Createble with scroll been scrolled down when clicking on "scroll up" arrow button

### ISSUE THREAD

**Issue by Eddie-HS** [JedWatson/react-select#3935]
The issue reproduced only in IE11
Limit the hight of createbleSelect.
Add enough values in order to scrollbar be visible.
Scroll to the bottom and then press several times on the "scroll up" arrow button. 
The focus will be fired and it will be scrolled to bottom every time.

https://codesandbox.io/s/react-codesandboxer-example-v93xi

I tried adding "onMouseDown" but I think it doesn't support this specific component.
Tote that this is been reproduced even on the documentation page also (https://react-select.com/creatable)

![creatable](https://user-images.githubusercontent.com/60566327/74643093-d7690500-517c-11ea-8cbd-2cef90f8b5b1.gif)

**Comment by bladey** [comment]
Hi @Eddie-HS,

I wanted to check in and see if you were still encountering this issue or found a solution. We're triaging issues at the moment to sustain the project going forward.

**Comment by Eddie-HS** [comment]
> Hi @Eddie-HS,
> 
> I wanted to check in and see if you were still encountering this issue or found a solution. We're triaging issues at the moment to sustain the project going forward.

yes, the issue still exists.

**Comment by lukebennett88** [comment]
Hi @Eddie-HS.
We have dropped support for IE11 in the latest major release of React Select, as such I am closing this issue.
