### ISSUE TITLE
Allow the user to copy the value in react-select dropdown

### ISSUE THREAD

**Issue by tathvampreeth** [JedWatson/react-select#3938]
**Describe Enhancement**
Allow the user to copy the value in the react-select dropdown.

Please respond, whether we can achieve that requirement or not?

I have researched a lot on this component, I didn't get any clue saying that we can achieve this or not.
So I request the team to please help me out to proceed further.

**Comment by flexdinesh** [comment]
Hey @tathvampreeth, can you explain a bit more in detail on what you are expecting?

In general, copying text from a web page is a browser/OS behaviour. Browsers allow highlighting text content on elements without a click event. Once highlighted, users can copy the content to the clipboard. Since the select option in `react-select` has click/key events, attempting to copy text from an option might not work as the events bubble and eventually close the options dropdown.

**Comment by flexdinesh** [comment]
@tathvampreeth You can also imlement a simple 'click to copy' button to do the job for you. `react-select` exposes a lot of internals and you can use one of those to get the input text. 

Here's an example codesandbox that might help —
https://codesandbox.io/s/react-select-copy-to-clipboard-thpvo

**Comment by PreethiIO** [comment]
> Hey @tathvampreeth, can you explain a bit more in detail on what you are expecting?
> 
> In general, copying text from a web page is a browser/OS behaviour. Browsers allow highlighting text content on elements without a click event. Once highlighted, users can copy the content to the clipboard. Since the select option in `react-select` has click/key events, attempting to copy text from an option might not work as the events bubble and eventually close the options dropdown.

Ok, so finally I can conclude saying that we cannot archive directly by using the react-select components to copy the dropdown value.

**Comment by PreethiIO** [comment]
> @tathvampreeth You can also imlement a simple 'click to copy' button to do the job for you. `react-select` exposes a lot of internals and you can use one of those to get the input text.
> 
> Here's an example codesandbox that might help —
> https://codesandbox.io/s/react-select-copy-to-clipboard-thpvo

Thanks, @flexdinesh for the suggestion will proceed further to use the 'click to copy' button to complete my requirement.

**Comment by tathvampreeth** [comment]
> Hey @tathvampreeth, can you explain a bit more in detail on what you are expecting?
> 
> In general, copying text from a web page is a browser/OS behaviour. Browsers allow highlighting text content on elements without a click event. Once highlighted, users can copy the content to the clipboard. Since the select option in `react-select` has click/key events, attempting to copy text from an option might not work as the events bubble and eventually close the options dropdown.

Ok, so finally I can conclude saying that by using react-select components we cannot archive copying a value from the select dropdown as click/key events are eventually closing the options dropdown.

**Comment by tathvampreeth** [comment]
> @tathvampreeth You can also imlement a simple 'click to copy' button to do the job for you. `react-select` exposes a lot of internals and you can use one of those to get the input text.
> 
> Here's an example codesandbox that might help —
> https://codesandbox.io/s/react-select-copy-to-clipboard-thpvo

Thanks, @flexdinesh for the suggestion. I will proceed further by using the 'click to copy' button to complete my requirement.

**Comment by shivaramIO** [comment]
@tathvampreeth Can you please tell how did you achieved this. I cant place the copy button below the select box. It doesn't look good. Where did you placed the copy button?

**Comment by airtonix** [comment]
> Hey @tathvampreeth, can you explain a bit more in detail on what you are expecting?
> 
> In general, copying text from a web page is a browser/OS behaviour. Browsers allow highlighting text content on elements without a click event. Once highlighted, users can copy the content to the clipboard. Since the select option in `react-select` has click/key events, attempting to copy text from an option might not work as the events bubble and eventually close the options dropdown.

I'm not sure you've investigated this fully enough to be able to make such authoritative statements: 

https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L220-L222

**Comment by ebonow** [comment]
Greetings,

I know this issue is stale but reading definitive statements that this is not possible, makes me believe that it might be worth setting the record straight about achieving this.

The major issue with copying the text is that the value does not exist in the input once its been selected and is in fact forced to be hidden while displaying the label (SingleValue or MultiValues)

It is very possible to make an "editable" Select that maintains the inputValue allowing the user to copy or edit the text.

Here is an example demonstrating this:
https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv

**Comment by ebonow** [comment]
I will be closing this to continue working through other questions and bugs. If there are other questions or comments, they can be opened in the Q&A section in the Discussions. Thank you everyone.

**Comment by xuanduz** [comment]
> 
thanks a lot <3
