### ISSUE TITLE
react-select custom virtualized menu

### ISSUE THREAD

**Issue by igoriok1994** [JedWatson/react-select#3939]
Hi everyone,

I'm using **react-select@3.0.8** and have a question. How can I create custom MenuList component with react-virtualized or react-select with default react-select styling?

I saw this [example](https://codesandbox.io/s/lxv7omv65l) and tried to modify it using cx / getStyles, but got some errors...

Maybe someone did this and can share the example?

**Comment by flexdinesh** [comment]
Hey @igoriok1994 would you be able to share a codesandbox example with what you tried and what didn't work? It'd be easier to help you with code examples.

**Comment by igoriok1994** [comment]
I tried like this.

https://codesandbox.io/s/bvaughnreact-window-integration-with-react-select-fw1mp?fontsize=14&hidenavigation=1&theme=dark

But still don't understand how to apply default styles and classNames to menuList and options.

**Comment by ebonow** [comment]
Greetings @igoriok1994 ,

Sorry that no one has responded earlier to you. I took a look at your code sandbox and it appeared that you had missed the components prop.

demo: [codesandbox](https://codesandbox.io/s/bvaughnreact-window-integration-with-react-select-forked-9m1np?file=/index.js)

In regards to styling, I am not sure what kind of styling you would like to apply. In the example I provided a way to add a className to the Option via the `cx` option as well as via the react-select styles prop. You can use the inspector to verify that the classNames were added as expected.

If you have any other questions please feel free to reply and we can reopen this if necessary.
