### ISSUE TITLE
Warning: Legacy context API has been detected within a strict-mode tree. Please update the following components: Transition, TransitionGroup

### ISSUE THREAD

**Issue by malejandro13** [JedWatson/react-select#3942]
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Transition, TransitionGroup

**Comment by punit-kulal** [comment]
Menu Placer is giving the same error as well.

**Comment by madhur-taneja** [comment]
Hey, @malejandro13 @punit-kulal do you have any update on this? I'm using `Reactstrap's` Collapse and the chrome dev tools console is showing the same error.
![Capture](https://user-images.githubusercontent.com/24964149/80164650-36bd1880-85f7-11ea-9a82-f5d51617cc85.PNG)

**Comment by bladey** [comment]
Hi all,

I'm closing this in favor of #3703 which logs the same issue so we can consolidate this and get it fixed.

If this is incorrect, please let me know.
