### ISSUE TITLE
Want to access <div> inside ValueContainer

### ISSUE THREAD

**Issue by kfoozminus** [JedWatson/react-select#3946]
### Are you making a feature request?
*   What's your use case?
I want to use custom `ValueContainer` where I need to access the `<div>` inside this (I want to get properties of this DOM node). currently I can see that `Control` component has `innerRef` props, but I don't know how it's possible to pass a ref to `Control` and use it in `ValueContainer`.

**Comment by ebonow** [comment]
Greetings @kfoozminus and thanks for your patience:

The recommended way would be to:
1. Create a ref
2. Pass the ref as a prop into the Select
3. Access the ref from the `ValueContainer` from `props.selectProps`
4. Set the ref on the child element

Here is an example: [Codesandbox](https://codesandbox.io/s/react-select-inner-inner-ref-value-container-4yuzv)

```js
const ValueContainer = ({ children, ...props }) => {
  const { vcChildRef } = props.selectProps;

  return (
    <components.ValueContainer {...props}>
      <div ref={vcChildRef} data-message="hello">
        {children}
      </div>
    </components.ValueContainer>
  );
};

const App = (props) => {
  const vcChildRef = React.createRef();

  return 
      <Select
        components={{ ValueContainer }}
        options={options}
        vcChildRef={vcChildRef}
      />
}
```

Hope this is helpful. I'll mark this as closed but if you have any other questions or follow ups let me know, and if necessary we can always reopen this.
