### ISSUE TITLE
Fix React lifecycles deprecation warning 

### ISSUE THREAD

**Issue by yoonwaiyan** [JedWatson/react-select#3948]
Hi, I've seen a pull request being merged to update the React lifecycle methods for version 3 (https://github.com/JedWatson/react-select/pull/3487) but we couldn't afford to update to version 3 for now. Is it possible to make a fix for version 2 as well?

**Comment by bladey** [comment]
Hi @yoonwaiyan,

I don't expect that we'll be able to get this implemented in version 2. In the best interest of supporting the broader community we have to direct our efforts towards the current major version - version 3 and beyond.
