### ISSUE TITLE
Error: 'createPortal' is not exported by node_modules/react-dom/index.js

### ISSUE THREAD

**Issue by dinfyru** [JedWatson/react-select#3956]
react-select 3.0.8
```
[!] Error: 'createPortal' is not exported by node_modules/react-dom/index.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
node_modules/react-select/dist/chunk-80640036.esm.js (13:9)
11: import { Component } from 'react';
12: import { jsx, keyframes, ClassNames } from '@emotion/core';
13: import { createPortal } from 'react-dom';
             ^
```

**Comment by utamanna** [comment]
Based on this comment in the [rollup-plugin-node-resolve issue](https://github.com/rollup/rollup-plugin-node-resolve/issues/58#issuecomment-255171853) you have to sometimes manually export custom named imports.

I fixed it by adding the following object to commonjs plugin in my rollup.config.js:
```
commonjs({
  namedExports: {
    "react-dom": ["createPortal", "findDOMNode"],
  },
})
```

**Comment by bladey** [comment]
Hello -

Thanks for your assistance @utamanna!

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by cipriandraghici93** [comment]
Hello, a similar issue appears again in version 5.3.2

```
Error: 'createPortal' is not exported by node_modules/react-dom/index.js, imported by node_modules/react-select/dist/index-a7690a33.esm.js

at /home/username/src/project-name/node_modules/react-select/dist/index-a7690a33.esm.js:12:9

10: import _defineProperty$1 from '@babel/runtime/helpers/esm/defineProperty';
11: import { Component, createContext } from 'react';
12: import { createPortal } from 'react-dom';
             ^
13: 
14: function _defineProperty(obj, key, value) {
```

**Comment by benbonnet** [comment]
yep same here; how come this error occurs ? does anyone has a clue ?

**Comment by marquito73** [comment]
> Based on this comment in the [rollup-plugin-node-resolve issue](https://github.com/rollup/rollup-plugin-node-resolve/issues/58#issuecomment-255171853) you have to sometimes manually export custom named imports.
> 
> I fixed it by adding the following object to commonjs plugin in my rollup.config.js:
> 
> ```
> commonjs({
>   namedExports: {
>     "react-dom": ["createPortal", "findDOMNode"],
>   },
> })
> ```

Thank you so much ! You save my time 🙏
