### ISSUE TITLE
TypeError: null is not an object (evaluating 'cache.registered')

### ISSUE THREAD

**Issue by jaywardhan1990** [JedWatson/react-select#3961]
I tried to implement react-select using vscode, but when I am launching the app it crashes and I'm getting the following error:

TypeError: null is not an object (evaluating 'cache.registered')

I have not found any solution for this yet. 

![Screenshot_20200304-183428](https://user-images.githubusercontent.com/40829561/75882358-018e1880-5e47-11ea-9915-bcf046811a80.png)

whenever i put below code for select dropdown it crashes:

 ```
<Select
            value={selectedOption}
            onChange={this.handleChange}
            //options={options}
            //isDisabled ='true'
            //placeholder="select employee"
            isMulti="true"
          />
```

**Comment by bladey** [comment]
Hi @jaywardhan1990, I'm going to close this in favor of #3753 as you've already posted there.
