### ISSUE TITLE
[ Help ] Reduce api call for Multiple Async Control using same api

### ISSUE THREAD

**Issue by rajtejani** [JedWatson/react-select#3962]
i am using async selects in table list where all control uses same api and i have also passed defauloptions so whenever page loads it calls same api multiple time.
so i want to reduce my api calls. is it possible in react-select?
![Screenshot 2020-03-07 at 11 30 13 AM](https://user-images.githubusercontent.com/49932204/76137827-4f816700-6067-11ea-8226-9bb321b813fd.png)

**Comment by alexristich** [comment]
Why don't you call the API outside of the components? It sounds like the select components you need aren't async, but rather the container/table that renders them.
You could call the API in componentDidMount (or with useEffect), then pass this state down to each `Select`.

**Comment by bladey** [comment]
Thanks for the assistance @alexristich.

@rajtejani could you please confirm whether the above answer has helped you?

We're triaging and closing issues at the moment to help sustain the project.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
