### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by miladnikad** [JedWatson/react-select#3963]
```
./node_modules/react-select/src/Select.js
SyntaxError: /Users/apple/Workspace/dashboard/node_modules/react-select/src/Select.js: Unexpected token, expected "," (3:32)

  1 | // @flow
  2 | 
> 3 | import React, { Component, type ElementRef, type Node } from 'react';
    |                                 ^
  4 | import memoizeOne from 'memoize-one';
  5 | import { MenuPlacer } from './components/Menu';
  6 | import isEqual from './internal/react-fast-compare';
```

**Comment by alexristich** [comment]
The type key is from Flow (hence the `// @flow` at the top). More info can be found here: https://flow.org/blog/2015/02/18/Import-Types/.

Where are you using `react-select` in your project? How are you referencing it?

**Comment by sknutsonsf** [comment]
I'm running into the same issue.  We don't use Flow, so it is not part of our build environment.

Do we need to have Flow installed & enabled to use this library?  It would sad if that was true.

**Comment by killerbytes** [comment]
This worked for me
` import { default as Select } from "react-select";`

**Comment by cototal** [comment]
I got this error when I let VS Code auto-generate the import for me. I didn't realize that it went into the `src` directory for the import.

```js
import Select from "react-select/src/Select";
```

Once I set it to the intended `import Select from "react-select"`, it worked fine.

**Comment by bladey** [comment]
Hi @miladnikad and @sknutsonsf,

I wanted to check in and see if either @killerbytes or @cototal's answers have solved your problem.

Thanks @alexristich, @killerbytes and @cototal.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.

**Comment by elisabetta-p** [comment]
I run into this problem just now.
I imported the select doing
`import Select from "react-select";` and `import { default as Select } from "react-select";` as suggested,
and got this error

```
SyntaxError: .../node_modules/react-select/src/stateManager.js: Unexpected token, expected "," (5:7)

  3 | import React, {
  4 |   Component,
> 5 |   type ElementRef,
    |        ^
  6 |   type AbstractComponent,
  7 |   type Config,
  8 | } from 'react';
```

then I tried to import the select as suggested, doing
`import Select from "react-select/src/Select";` 
and now I get
```
SyntaxError: .../node_modules/react-select/src/Select.js: Unexpected token, expected "," (3:32)

  1 | // @flow
  2 | 
> 3 | import React, { Component, type ElementRef, type Node } from 'react';
    |                                 ^
  4 | import { MenuPlacer } from './components/Menu';
  5 | 
  6 | import { createFilter } from './filters';

```

Version of react-select: 4.0.2

**Comment by Methuselah96** [comment]
@elisabetta-p This is likely an issue with your setup. Are you using Flow in your project?

**Comment by elisabetta-p** [comment]
@Methuselah96  Thank you for your quick response! There surely was something wrong with my code, since the error went away after I rewrote it (but no I don't use Flow). 
Thanks tho!
