### ISSUE TITLE
Menu of options disappear after clicked on scrollbar

### ISSUE THREAD

**Issue by vomchik** [JedWatson/react-select#397]
Menu of options disappear after clicked on scrollbar.

For more details see screencast
![screencast 2015-08-21 11-46-48](https://cloud.githubusercontent.com/assets/732085/9404745/ac3cf8d6-47fa-11e5-8f78-5b78839e4d9d.gif)

**Comment by vomchik** [comment]
This bug only in Chrome! In Firefox everything is good.

**Comment by vomchik** [comment]
If remove this condition https://github.com/JedWatson/react-select/blob/master/src/Select.js#L798-L800 and set handler onMouseDown in any case it is work correctly

**Comment by quoc99a** [comment]
I'm getting the same bug. I also tried both adding multi={false} and removing this condition https://github.com/JedWatson/react-select/blob/master/src/Select.js#L798-L800
Both of these don't work.

**Comment by vomchik** [comment]
Sorry,  this line you must leave ```menuProps.onMouseDown = this.handleMouseDown;```

**Comment by quoc99a** [comment]
Thank you @vomchik. It works like a charm. Hope to see this fix on next release.
