### ISSUE TITLE
isClearable is not displayed if Select has a defaultInputValue

### ISSUE THREAD

**Issue by lorenzosjb** [JedWatson/react-select#3970]
When the Select component is render the first time and has a **defaultInputValue**, the "X" does not appear even if the option **isClearable** is set.

My example is in [https://codesandbox.io/s/jolly-wind-0djks](https://codesandbox.io/s/jolly-wind-0djks).

Thanks

**Comment by Rall3n** [comment]
@lorenzosjb `defaultInputValue` is for the search input. It does not set a default selected option. For that you have to use `defaultValue`.

**Comment by lorenzosjb** [comment]
Thanks, but it didn't work.

I did this:

const getLocation = (label: string, value: string): OptionTypeBase => {
  const item: OptionTypeBase = {
    label,
    value
  };
  return item;
};

....

<AsyncSelect
        ...
        value={location !== '' ? getLocation(location) : null}
        ...

`

**Comment by jaskaransr93** [comment]
@lorenzosjb Please have a look at this [one](https://codesandbox.io/s/elastic-stallman-l1pt0)

**Comment by bladey** [comment]
Thanks for taking to time to help @jaskaransr93.

@lorenzosjb from what I can see the Codesandbox from @jaskaransr93 does what you need.

If not, please let me know!
