### ISSUE TITLE
Is there a way to style async components

### ISSUE THREAD

**Issue by wsalazar-peakactivity** [JedWatson/react-select#3971]
I've tried everything to style an async component. I've provided styles and theme options to the component but nothing works. I couldn't find anything online either. Is this something that is actively being worked on? I'm using react-select: 2.1.1. I'm currently not in a spot where I can upgrade. Any insight would be great.  Thanks.

**Comment by Bolza** [comment]
Same, i think after 3.10 styling has been broken. Both `styles` and `classNamePrefix` don't work anymore

**Comment by ebonow** [comment]
Greetings @wsalazar-peakactivity 
The styling for an Async Select is no different than a regular Select.

The complete styling api is located [here](https://react-select.com/styles).

You can also go through each of the components [here](https://react-select.com/components) and view the examples to see how each component can be styled.

Additionally [here is a codesandbox](https://codesandbox.io/s/react-select-v211-async-styling-6n33c) I quickly threw together that should be able to get you started as well. 

Please let us know if you have any other questions.
