### ISSUE TITLE
border around search input

### ISSUE THREAD

**Issue by bart-lewandowski-conichi** [JedWatson/react-select#3974]
Hello guys. I have problem with border around the search option 

<img width="278" alt="image" src="https://user-images.githubusercontent.com/46447784/76856989-c9c69e00-6854-11ea-8353-54c56dcec9d5.png">

was trying to get it through input prop but styles are applied to div where input is so still cant remove it 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/46447784/76857071-009cb400-6855-11ea-91d3-77b7ff6ffbde.png">

the border input:focus is thing I want to remove

**Comment by jaskaransr93** [comment]
Please share some more code

**Comment by bart-lewandowski-conichi** [comment]
`import React, { FunctionComponent } from "react";
import InfiniteCalendar, { Calendar, withRange } from "react-infinite-calendar";
import "react-infinite-calendar/styles.css";
import { IState } from "store/store";
import { connect } from "react-redux";

interface IDateRange {
  start: any;
  end: any;
}

interface IProps {
  onSelect(dateRange: IDateRange): void;
  lang: string;
}
const themeSettings = {
  accentColor: "#16416D",
  floatingNav: {
    background: "rgba(56, 87, 138, 0.94)",
    chevron: "#ff7359",
    color: "#FFF"
  },
  headerColor: "#16416D",
  selectionColor: "#3ABDC5",
  textColor: {
    active: "#FFF",
    default: "#333"
  },
  todayColor: "#ff7359",
  weekdayColor: "#3ABDC5"
};

const CalendarWithRange = withRange(Calendar);
const minDate = new Date();
const maxDate = new Date(new Date().setFullYear(new Date().getFullYear() + 2));

const DatePicker: FunctionComponent<IProps> = ({ onSelect, lang }) => {
  const locale = {
    locale:
      lang === "en"
        ? require("date-fns/locale/en")
        : require("date-fns/locale/de"),
    blank: lang === "en" ? "Select a date..." : "Datum auswählen ...",
    headerFormat: "ddd, MMM Do",
    todayLabel: {
      long: lang === "en" ? "Today" : "Heute",
      short: lang === "en" ? "Today" : "Heute"
    },
    weekdays:
      lang === "en"
        ? ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
        : ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"]
  };
  return (
    <>
      <InfiniteCalendar
        selected={false}
        Component={CalendarWithRange}
        onSelect={onSelect}
        width={550}
        locale={locale}
        theme={themeSettings}
        height={window.innerHeight / 2}
        minDate={minDate}
        maxDate={maxDate}
      />
    </>
  );
};

const mapStateToProps = (state: IState) => ({
  lang: state.UiReducer.lang
});

export default connect(mapStateToProps)(DatePicker);
`

**Comment by bart-lewandowski-conichi** [comment]
> Please share some more code
