### ISSUE TITLE
Whitespaces gets trimmed in select options when making tree hierarchy

### ISSUE THREAD

**Issue by coderrsid** [JedWatson/react-select#3975]
All the whitespaces is trimmed when any option in `<Select />` with spaces before the name of the label in it is rendered. 

## How options should look like 
![Screen-Recording-2020-03-18-at-7](https://user-images.githubusercontent.com/35633575/76967691-c2cf8680-694d-11ea-9780-eea8f35798a9.gif)

## How it looks like 
![Screen-Recording-2020-03-18-at-7 (1)](https://user-images.githubusercontent.com/35633575/76968002-396c8400-694e-11ea-8f0d-fd3170248c21.gif)

## The way i am trying to add spaces
--->  https://stackoverflow.com/questions/24432576/reactjs-render-string-with-non-breaking-spaces/45247559

**Comment by bladey** [comment]
Hi @coderrsid,

It appears this issue has been resolved in issue https://github.com/laurent22/joplin/pull/2566.

If this issue is still relevant, please let me know.
