### ISSUE TITLE
OnBlur calling onInputChange

### ISSUE THREAD

**Issue by 787acr** [JedWatson/react-select#3977]
![97E31EAB-D181-4BDE-A4CF-960DBA87D392](https://user-images.githubusercontent.com/45856133/77205327-069bca80-6acb-11ea-8a74-a43bbbc7e2a8.png)

I was wondering why is it necessary for the onInputBlur function to call onInputChange with an empty string even if I am controlling the inputValue and also calling the function to close the menu even though I am also controlling that? Doesn’t that defeat the purpose, specially if using the Async component.

**Comment by ajoslin103** [comment]
Is this why, only on Android, my users are reporting that the react-select and react-select/creatable drop downs are closing a second after they are opening?

**Comment by ebonow** [comment]
Greetings,

The intention for better or worse is to ensure that only valid selected input is shown in the Select. The rationale is likely similar to an actual select element where the only options displayed are valid provided options. Even with Async, it could be confusing to see text that isn't fully formed as a selected option after they've left the input.

I understand that this behavior is somewhat controversial to use an input as an autocomplete, hide the input on select with an absolutely positioned label on top, and then leave the input empty making it appear as though the text is the input.

As you mentioned though, you do have control of the onBlur, onFocus, and inputValue. This means you can reset the inputValue onFocus:

``` JS 
const [ value, setValue ] = useState();
const [ inputValue, setInputValue ] = useState();

const onChange = option => setValue(option);
const onInputChange = (text, { action }) => (action === 'input-change') && setInputValue(text);
const onFocus = () => value && setInputValue(value.label);

<Select onFocus={onFocus} value={value} inputValue={inputValue} ... />
```

I hope this helps and if you have any other questions, please feel to reply and can reopen if necessary.
