### ISSUE TITLE
"input" object of the styles object should receive the same state as the other components

### ISSUE THREAD

**Issue by Slapbox** [JedWatson/react-select#3982]
# Feature request/consistency request

*   What's your use case? Passing a theme object to the `<Select />` component and would like to access it
*   What interface do you have in mind? `state.selectProps` should exist in the context of this code:

```js
const reactSelectStyles = {
    control: (
        provided, { selectProps: { myTheme: theme } }
    ) => {
        color: theme.color, // Works great
    },
    input: (
        provided, { selectProps: { myTheme: theme } } // <<< Error: Cannot read property of undefined
    ) => {
        color: theme.color,
    }
}
```

This method of accessing also works fine for `dropdownIndicator`, `menu`, `singleValue`, `indicatorContainer`, `singleValue` and every other piece of React-Select that I've tried this with, except for `input`.

**Comment by Slapbox** [comment]
Is there some design reason for this?

**Comment by ebonow** [comment]
Getting more information about why this is. Will update when I know more.
