### ISSUE TITLE
get this error: Couldn't find package "react-select" on the "npm" registry.

### ISSUE THREAD

**Issue by dingzhanjun** [JedWatson/react-select#3983]
I got the error saying: 
Couldn't find package "react-select" on the "npm" registry.

when I tried."yarn add react-select", what could be the problem?

Thanks!

**Comment by dingzhanjun** [comment]
not related

**Comment by mxy2316868975javascript** [comment]
> not related

大佬解决了没，我也遇到相似情况

**Comment by dingzhanjun** [comment]
clean up your .npmrc
