### ISSUE TITLE
Components Input SetValue

### ISSUE THREAD

**Issue by philcon93** [JedWatson/react-select#3986]
# Feature request

Herro, we wish to have a multi-step select input where the select options helps start the user off, and then they finish it off with some custom text. We are using the CreatableSelect component with isMulti set to true. 

We use the select options for the 'key' of a query, and have the user fill out the 'value'. As an example, we have an option 'id:', which the user then needs to fill in the 'key', e.g 'id:n1002'. This key/value pair is needed so we can later figure out which filter needs to be added to the API query, e.g order id, customer name, order status etc.

We started off with [ant.design](https://github.com/ant-design/ant-design) Select component but it wasn't capable to edit the Input component. Which is how we came about the react-select component cos we can customizable the internal components.

A very good example of the desired end goal working is the Stripe dashboard:

- https://dashboard.stripe.com/dashboard.

![Screen Shot 2020-03-26 at 11 07 42 am](https://user-images.githubusercontent.com/13529653/77599909-13e50900-6f52-11ea-82ac-ab9c325f099e.png)

And here is an example of the flow with ant.design:

- https://codesandbox.io/s/select-multi-step-ant-design-demo-8ibr6

What I was hoping was possible, was for the components Input to have 2 additional props; **getValue**, **setValue**, similar to the other customizable components. This would then enable us to have a way to update the text input value (Not the select components value) when the user selects a particular option, then they finish the value off and it is added to the selects value.

Would love to know what you think on this one and if it's viable/ or have seen it done elsewhere

Cheers!

**Comment by philcon93** [comment]
Sorry I didn't see the `inputValue` prop. I think this is how I will be able to work this in... we'll give it a try!

**Comment by flexdinesh** [comment]
Hey @philcon93! Yeah there are so many things you can do with just the api that comes with `react-select`. Now that you got it resolved I'm gonna go ahead and close this issue. If you wanna discuss this further feel free to reopen it. Thank you!
