### ISSUE TITLE
Expose input onChange event to ReactSelect

### ISSUE THREAD

**Issue by mattbreeden** [JedWatson/react-select#399]
Would love to be able to easily access the onChange event for the input component (typing in the bar, not selecting a value).

**Comment by anton-kabysh** [comment]
+1. Eah, highly expected feature. For example, selector used inside popover which is collapsed by any click outside it. Now I am should intercept mouse events on the top of selector to avoid popover collapse. This is really hated boilerplate code.

**Comment by lomteslie** [comment]
I'd love to have this feature as well. Just submitted a pull request that would add this functionality.
