### ISSUE TITLE
Default Value does not get set when component rerenders

### ISSUE THREAD

**Issue by darthzeran** [JedWatson/react-select#3992]
I have a component that has a Select inside of it, and i start of with the defaultValue being set to `getFirstOption() || null`, since the options are set asynchronously.
When the options load, they are shown in the drop down menu, but the defaultValue never gets reset.  since now there is a first option to return, rather than null.

```
export default class SingleSelect extends Component<*, State> {
  state={
    options:[]
  }
  
  componentDidMount () {
    // async function call
    setTimeout(this.setState({options: [
      {value:1, label:1}, 
      {value:2, label:2}, 
      {value:3, label:3}, 
      {value:4, label:4}]}), 3000);
}

	getFirstOption = (array) => {
		if (array.length > 0) {
			return array[0]
		}
		return null
  }


  render() {
    return (
      <Select
			defaultValue={this.getFirstOption(this.state.options)}
        options={this.state.options}
      />
    );
  }
}
```

**Comment by alexristich** [comment]
My understanding of `defaultValue` is that it only sets the initial value on _render_ of the Select component.

For your use case, I might suggest an alternative approach:
```
<Select
  value={this.state.value || this.state.options[0])}
  ....
/>
```
This would require you to manage the selected option yourself, but in the end this is what you need to conditionally set a default value after the initial render.

**Comment by bladey** [comment]
Hello -

Thanks for your assistance @alexristich!

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However @darthzeran, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by Nick-bcm** [comment]
Have the same problem.
I'm working with redux-form, and have simple value in store. For example:
`options: [{ label: 'Nick', value: 1 }]`
in store:
`form: { userId: 1 }`
I find the value for Select like this:
`const getValue = (value, options) => options.find((option) => option.value === value)`
When component will load, i fetch data for this form. Options for Select is loading async, only after user type.
In result i have this situation:
```
<Select
  options={[]}
  value={undefined}
  onChange={handleChange}
/>
```
I found solution for this - `defaultValue`, but it's not working if set in async. [Example](https://codesandbox.io/s/react-select-default-value-forked-w0qli?file=/index.js)

**Comment by Nick-bcm** [comment]
UPD: found a workaround:
```
const value = getValue(this.state.value, this.options);

<Select
  options={this.options}
  value={value || this.state.defaultValue}
  onChange={value => this.handleChange(value)}
  defaultValue={this.state.defaultValue}
/>
```
