### ISSUE TITLE
Any non-typescript creatable examples?

### ISSUE THREAD

**Issue by joshbedo** [JedWatson/react-select#3998]
Trying to use react-select to create an input where people can add dynamic tags. Looked like the creatable examples are what I'm looking for but I couldn't seem to get them working. Is their any examples of creatables not using typescript? 

Every time I add a creatable I get this error
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function 
```

**Comment by a-liaukouski** [comment]
I have the same issue on using simple Select component after installing latest version using npm i react-select. If i install react-select using yarn add - the same code works fine. But my project is using npm so yarn is not an option. Thanks

**Comment by svartalf89** [comment]
Same for me, looks like it is a problem with npm package. Importing as es module `import Select from 'react-select';` produces `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`.
In particular I think there is something wrong with exports in `dist/react-select.esm.js`. Because importing as cjs works: (`const Select = require('react-select').default;`)

**Comment by joshbedo** [comment]
Any of you figure out a fix for this?

**Comment by svartalf89** [comment]
You can try using cjs `const Select = require('react-select').default;`

**Comment by joshbedo** [comment]
To use Creatable?

**Comment by ebonow** [comment]
Greetings @joshbedo 

[Here is a codesandbox example of a CreateableSelect.](https://codesandbox.io/s/react-select-toggle-createable-s31ed)

Let me know if this fulfills your needs or if you have other questions. I will mark this as closed, but can reopen this if there are verified issues with getting your instance to work.

**Comment by rovolution** [comment]
I am using `"react-select": "1.2.1"`, and the following error was popping up when i ran my tests:

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```


I followed @ebonow's advice and just changed my `Createable` import from:

```
import { Createable } from "react-select";
```

to:

```
import Createable from "react-select/lib/Creatable";
```

and it worked! 🥳
