### ISSUE TITLE
Can I get CreatableSelect cdn links?

### ISSUE THREAD

**Issue by rumu10** [JedWatson/react-select#4003]
_No details provided_

**Comment by bladey** [comment]
Hi @rumu10, as far as I'm aware there is no way to run `react-select` via a CDN at this time, you'll need to install it directly.

**Comment by ebonow** [comment]
It is possible per [this old StackOverflow post from about 18 months ago](https://stackoverflow.com/questions/53927307/how-to-import-from-react-select-cdn-with-react-and-babel).

The Codepen from the solution appears to still work so long as the old version works for you. I'm not sure that the current build includes fully compiled distro files. Hope this helps if you haven't moved on already.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
