### ISSUE TITLE
Where do we pass callback in loadOptions?

### ISSUE THREAD

**Issue by xyyimian** [JedWatson/react-select#4004]
in Async-Select, loadOptions need to be passed a callback. However, I don't know where we need to specify that callback. Thanks!

**Comment by bladey** [comment]
Hi @xyyimian could you please provide a Codesandbox example so I can help further - I pressume you have already looked at the code editor on this page - https://react-select.com/async

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
