### ISSUE TITLE
value in react-select component is not preserved

### ISSUE THREAD

**Issue by leojacob7** [JedWatson/react-select#4007]
I have data which is stored in the form as 

```
{name: "email"
uuid: "ca980e72-d0d1-460e-8d53-d60edadb27a6"
editable: false
hidden: false
pinned: false
data_type: "text"
show: true
isSelected: true
id: "ca980e72-d0d1-460e-8d53-d60edadb27a6"
label: "email"}
```

Because it is not of the form {label, value} I have used 

    getOptionValue and getOptionLabel

This is how my component looks like right now:

    Here option is a state value of type string

    <Select
              options={ fields }
              value={ activeSortObject.column.name === '' ? '' : option }
              getOptionLabel={ val => val.name }
              getOptionValue={ val => val.id }
              searchable
              placeholder={ trans( 'Find an option' ) }
              onChange={ this.fieldSelectorChange }
            />

I want to preserve the value of the selected value on reload also. Although first time it is preserved, on reload however I see the placeholder. I am passing the value of option and activeSortObject by connecting with redux. How can I prefill the value with the data I am getting. At the moment option is of type string

**Comment by leojacob7** [comment]
cc @JedWatson I am not sure if this comes as a bug. Please help.

**Comment by ebonow** [comment]
Greetings @leojacob7 

> Here option is a state value of type string

This is likely your issue. The `value` type should be an object representing the selectedOption and not just the string value of the object. For example...

``` JS 
const value = { 
  label: 'email',
  value: 'ca980e72-d0d1-460e-8d53-d60edadb27a6'
}

return <Select value={value} ... />
```

I'll be closing this issue, but please still let me know if you have any further questions and it can be re-opened if necessary.
