### ISSUE TITLE
Is there a way to edit option's values

### ISSUE THREAD

**Issue by techterbium** [JedWatson/react-select#4009]
# Are you making a feature request?
yes

Hello team, I am wondering, is there a way to edit the option values as possible [in this case](https://indrimuska.github.io/jquery-editable-select/)?

My use case is to let user either choose from one of the options available or otherwise, let him type something on his own _and as well_, edit the value at later point of time. 

I am aware that `Createble Select` will let user create an option, but we cannot edit it anytime later. I am looking for toggling between select and text-input

Thanks for the help with this.

**Comment by ebonow** [comment]
Greetings,

I agree that this could/should be a feature request as it seems a common enough use-case that takes a bit to get to.

In the meantime, here is an implementation of react-select with this functionality: https://codesandbox.io/s/epic-rgb-6nfdv

**Comment by ebonow** [comment]
I have created a discussion [here](https://github.com/JedWatson/react-select/discussions/4302) to have the community discuss this as a feature request more in depth. If you have any further thoughts regarding this, feel free to contribute there.
