### ISSUE TITLE
Wonky checkboxes on the demo page

### ISSUE THREAD

**Issue by aldanor** [JedWatson/react-select#401]
In both Safari 8 and Chrome Mac, selecting/deselecting "Multi-Select?" checkbox on the demo page causes the select box ("Values as Numbers") to size up and then down in height in a jittery way. The other two checkboxes also behave weird -- if you select one, it goes active->inactive->active.

**Comment by JedWatson** [comment]
@jossmac this sounds like something you could take care of...

**Comment by jossmac** [comment]
@aldanor any chance of some screenshots?

**Comment by aldanor** [comment]
![react-select-glitch 1](https://cloud.githubusercontent.com/assets/2418513/9430925/f4149ce6-49fc-11e5-8401-92a3cc2bd3cb.gif)

**Comment by jossmac** [comment]
@aldanor cheers mate. On it now

**Comment by aldanor** [comment]
@jossmac  yw :) The other two checkboxes are a bit buggy too, but only in Safari and not in Chrome so couldn't quite reproduce it here
