### ISSUE TITLE
How to use formatOptionLabel

### ISSUE THREAD

**Issue by erikroblarsen** [JedWatson/react-select#4010]
If you, like me, are struggling to understand the documentation on how to use react-select's formatOptionLabel to customize the list options (like rendering an element as JSX) then you'll appreciate this example: https://codesandbox.io/embed/reactselect-formatoptionlabel-bde1q. 

I didn't put it together. I stumbled on it after a quick Google search when I couldn't find any examples here in the forum. Hope it helps!

FYI, this really isn't an issue unless you count confusing documentation as an issue.

**Comment by SwenSchaeferjohann** [comment]
thank you @erikroblarsen , this saved me a good amount of time!

**Comment by gmoniava** [comment]
@erikroblarsen Yeah I stumbled this syntax, can't grasp what this means:

```
function(
Object,
{
context required One of<
"menu",
"value"
>
inputValue string required
selectValue required One of<
Object,
Array<Object>,
null,
undefined
>
}
) => react.Node
```

**Comment by duhaime** [comment]
@jedwatson, is it possible to have a separate format function for rendering the option once it's been selected? E.g. so in the dropdown users see "Option A (text to be removed upon select)", and once selected, users see "Option A"? StackOverflow does this for their tags :)

**Comment by rubimbura** [comment]
@duhaime did you manage to get the answer for your question, as I am struggling to have exact same solution.

**Comment by duhaime** [comment]
I just wrote my own multiselect because that seemed like it would be easier and faster :)

**Comment by varun-a-mhatre** [comment]
> @JedWatson, is it possible to have a separate format function for rendering the option once it's been selected? E.g. so in the dropdown users see "Option A (text to be removed upon select)", and once selected, users see "Option A"? StackOverflow does this for their tags :)

I came across this issue recently and used ChatGPT to get the answer, hopefully if anyone comes across this question/query in future they won't need to use ChatGPT. `formatOptionLabel` function takes  2 arguments and you can use the second argument to change the format based on context. To only show the customAbbreviation in dropdown (context = menu) only you can use the following code.

```javascript
const formatOptionLabel = ({ value, label, customAbbreviation }, { context }) => (
    <div  style={{ display: "flex" }}>
      <div>{label}</div>
      {context === 'menu' && (
        <div style={{ marginLeft: "10px", color: "#ccc" }}>
          {customAbbreviation}
        </div>
      )}
    </div>
  );
```
