### ISSUE TITLE
3.1.0: Selected value not focused/visible when using defaultMenuIsOpen or menuIsOpen

### ISSUE THREAD

**Issue by andreme** [JedWatson/react-select#4013]
Example: https://codesandbox.io/s/zealous-leaf-58ett?file=/src/index.js

@Tirzono Here you go, thanks for looking at this

**Comment by ebonow** [comment]
Greetings, 

Confirmed bug. I reviewed this with the latest build of react-select (V4.2.1), and does not properly scroll the focused option into view.

**Comment by manjushsh** [comment]
On v5.2.2, Selected value is focused/visible once user clicks on control.
