### ISSUE TITLE
Styling issue with very long labels

### ISSUE THREAD

**Issue by mik01aj** [JedWatson/react-select#402]
![screenshot 2015-08-24 16 50 38](https://cloud.githubusercontent.com/assets/3027415/9443804/8354d1e2-4a83-11e5-9cf5-db4b77f4545c.png)

I tried to fix it with some CSS, but I can't do it in a generic way, I need to specify the maximum width somewhere, and percents don't work well for some strange reason:
![screenshot 2015-08-24 17 12 11](https://cloud.githubusercontent.com/assets/3027415/9443835/add2b4ac-4a83-11e5-8a3f-ba363ef99b74.png)

I also tried an alternative: to add these rules to `.Select-item` instead. This way it works with `100%` but doesn't show the ellipsis.

![screenshot 2015-08-24 17 18 33](https://cloud.githubusercontent.com/assets/3027415/9443972/61d56dbe-4a84-11e5-8f95-a3fd636f4308.png)

**Comment by eisenjulian** [comment]
+1

**Comment by chrys1110** [comment]
Unfortunately this solution doesn't work anymore with the newest version. Tried some things but didn't work. Anyone has a new approach?

**Comment by camloken** [comment]
This seemed to work for me:
```
.Select-multi .Select-value,
.Select-value-label {
   display: inline-flex;
}```

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
