### ISSUE TITLE
Having issue with Sortable MultiSelect

### ISSUE THREAD

**Issue by tamjidtech** [JedWatson/react-select#4022]
works fine on codesand but getting error on my tsx file. 

And i am getting this error:

Type '{ axis: "xy"; onSortEnd: ({ oldIndex, newIndex }: { oldIndex: any; newIndex: any; }) => void; distance: number; getHelperDimensions: ({ node }: SortStart) => DOMRect; isMulti: true; options: ({ value: string; label: string; color: string; isFixed: boolean; isDisabled?: undefined; } | { ...; } | { ...; })[]; value: (...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<SortableContainerProps, any, any>> & Readonly<...> & Readonly<...>'.
  Property 'isMulti' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<SortableContainerProps, any, any>> & Readonly<...> & Readonly<...>'.

how can i solve this?

**Comment by bladey** [comment]
Hi @tamjidtech, could you please provide more information about your development environment and an example on Codesandbox (even though it's working there).

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
