### ISSUE TITLE
onWheel not working with custom scrolling library

### ISSUE THREAD

**Issue by samyan** [JedWatson/react-select#4028]
Hello. I have updated my react-select **v2.4.4** to **v3.1.0** and now i get that **MenuList** component with custom scrolling library (react-custom-scrollbars **v4.2.1**) stopped working with mouse wheel. If i try to click / hold scroll, is working. I've downgrade to 2.4.4 for get working again.

You can check it in:
[https://codesandbox.io/s/react-select-bug-nez1s](https://codesandbox.io/s/react-select-bug-nez1s
)

I dont know if it's a bug or any option i need to enable.

Thanks in advance.

**Comment by samyan** [comment]
Complete silence from devs?

**Comment by kyparyt** [comment]
I have the same issue.

**Comment by dbalas** [comment]
I have the same issue, I'm using react-custom-scrollbars

**Comment by Rall3n** [comment]
The `Select` component is capturing scrolling in the dropdown by default so they can handle the appropriate events for the props `onMenuScrollToTop`, `onMenuScrollToBottom`.

You can disable this behaviour by using the `captureMenuScroll` prop by setting its value to `false`. **BE AWARE** that this will disable the functionality of the above mentioned props.

**Comment by ebonow** [comment]
In an effort to maintain react-select, I will be closing this issue as it appears to be resolved. Please feel free to reply if this is a misunderstanding and we can reopen this if necessary.

**Comment by bbatta38** [comment]
> The `Select` component is capturing scrolling in the dropdown by default so they can handle the appropriate events for the props `onMenuScrollToTop`, `onMenuScrollToBottom`.
> 
> You can disable this behaviour by using the `captureMenuScroll` prop by setting its value to `false`. **BE AWARE** that this will disable the functionality of the above mentioned props.
> 
> <Select captureMenuScroll={false} {...} />

Thank you so much, you saved me from being frustrated for 5 hours.
