### ISSUE TITLE
How do I make the dropdown open at the top instead of bottom?

### ISSUE THREAD

**Issue by chirantan** [JedWatson/react-select#403]

**Comment by aldeka** [comment]
I too have this issue, where I have a dropdown near the bottom of the page and the dropdown menu breaks things when open because there is no room at the bottom. Being able to specify the direction that the dropdown opens would be a big plus.

**Comment by vinayakpatil** [comment]
Is there an easy way to do this?

**Comment by vjpr** [comment]
+1

**Comment by medv** [comment]
`.Select-menu-outer{top: auto; bottom: 100%}`

Of course then you would have to check how far you are scrolled and decide whether to open above/below. This would make a great addition.

**Comment by vitosamson** [comment]
wanted to share my approach to this, in case it helps anyone:

```js
import { findDOMNode } from 'react-dom';
import Select from 'react-select';

const MAX_MENU_HEIGHT = 200;
const AVG_OPTION_HEIGHT = 36;

class MySelect extends Component {
  constructor(props) {
    super(props);

    this.state = {
      dropUp: false,
    };

    this.determineDropUp = this.determineDropUp.bind(this);
  }

  componentDidMount() {
    this.determineDropUp(this.props);
    window.addEventListener('resize', this.determineDropUp);
    window.addEventListener('scroll', this.determineDropUp);
  }

  componentWillReceiveProps(nextProps) {
    this.determineDropUp(nextProps);
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.determineDropUp);
    window.removeEventListener('scroll', this.determineDropUp);
  }

  determineDropUp(props = {}) {
    const options = props.options || this.props.options || [];
    const node = findDOMNode(this.selectInst);

    if (!node) return;

    const windowHeight = window.innerHeight;
    const menuHeight = Math.min(MAX_MENU_HEIGHT, (options.length * AVG_OPTION_HEIGHT));
    const instOffsetWithMenu = node.getBoundingClientRect().bottom + menuHeight;

    this.setState({
      dropUp: instOffsetWithMenu >= windowHeight,
    });
  }

  render() {
    const className = this.state.dropUp ? 'drop-up' : '';
    
    return (
      <Select {...this.props} className={className} ref={inst => (this.selectInst = inst)} />
    );
  }
}
```

```scss
.drop-up .Select-menu-outer {
  top: auto;
  bottom: 100%;
}
```

the calculations may require some tweaking based on your page layout. it unfortunately doesn't work for async options since we don't have access to the loaded options via props. I also debounce the `determineDropUp` method to 100ms to avoid any thrashing from the resize and scroll listeners.

**Comment by hyperh** [comment]
+1

**Comment by medv** [comment]
@vitosamson looks good, though I would base my solution on measurement so that your css can be king in terms of determining how big something is and what are its limits (regarding your pixel constants at the top of the file).

**Comment by vitosamson** [comment]
@medv I don't think that's possible, since the menu would have to already be open in order to measure its height and the height of the options.

**Comment by medv** [comment]
@vinayakpatil that's generally when you render a proxy somewhere off-screen or below layers with the same style directive and gather data from it. For each differently-styled react-select component that would subscribe to this thinking, you would spawn a dummy proxy menu that has a single item and take readings from that, then your measurements are correct. It introduces a little performance loss due to this process, but it solves a lot of front-end questions for those of us that can use css really well in its full cascading glory.

**Comment by alanqthomas** [comment]
Thanks @vitosamson!  Here's the CSS I used in conjunction with what he already used to achieve a bit more visual consistency, i.e. margin fix for positioning, corner radii, remove `box-shadow`. Hope it helps.
```
.drop-up .Select-menu-outer {
	top: auto;
	bottom: 100%;
	margin-top: 0px;
	margin-bottom: -1px;
	border-bottom-right-radius: 0px;
	border-bottom-left-radius: 0px;
	border-top-left-radius: 4px;
	border-top-right-radius: 4px;
	box-shadow: none;
}

.drop-up.is-open > .Select-control {
	border-bottom-right-radius: 4px;
	border-bottom-left-radius: 4px;
	border-top-left-radius: 0px;
	border-top-right-radius: 0px;
}
```

**Comment by dmr** [comment]
In https://github.com/buildo/react-components/issues/800 they integrated an option for this behavior

```
menuPosition="top"
```

--> How do you feel about this option for react-select?

**Comment by vkmita** [comment]
+1

**Comment by geminiyellow** [comment]
+1 hope this issue can be close tomorrow.

**Comment by VD17593** [comment]
added to Select : 

`
menuContainerStyle={{top: 'auto',	bottom: '100%'}}
`

**Comment by mxtetrachord** [comment]
bump!

hey @JedWatson, i'd love to see some kind of response to this. this should be done by the library, not left to individual apps to hack together a solution. thanks!

**Comment by cathylollipop** [comment]
add to Select :

`menuPlacement = "top" 
`

**Comment by nguyenvanphuc2203** [comment]
> add to Select :
> 
> `menuPlacement = "top" `

it work!

**Comment by jossmac** [comment]
Ref #1602

**Comment by jossmac** [comment]
Use `menuPlacement`. Docs for the [props API](https://react-select.com/props). Thanks @cathylollipop

**Comment by zahramemar** [comment]
Add this props to your component menuPlacement="auto" .

**Comment by Spell-OnE** [comment]
`  const [isOpenAbove, setIsOpenAbove] = useState<boolean | null>(null)

  const refSelectField = useRef<HTMLDivElement | null>(null)
  const refSelectDropdownField = useRef<HTMLDivElement | null>(null)

  useLayoutEffect(() => {
    function positionDropdown() {
      if (refSelectField.current) {
        const selectRect = refSelectField.current.getBoundingClientRect()
        const spaceBelow = window.innerHeight - selectRect.bottom
        if (refSelectDropdownField.current) {
          if (spaceBelow < refSelectDropdownField.current.offsetHeight) {
            setIsOpenAbove(true)
          } else {
            setIsOpenAbove(false)
          }
        }
      }
    }

    window.addEventListener('resize', positionDropdown)
    positionDropdown()

    return () => {
      window.removeEventListener('resize', positionDropdown)
    }
  }, [onFocus])`

`        <div
          className={clsx(
            'absolute left-0',
            isOpenAbove
              ? 'bottom-auto top-0 -translate-y-full'
              : ' bottom-0 translate-y-full'
          )}
          ref={refSelectDropdownField}>{...custom dropdown}</div>`

**Comment by ahmad118128** [comment]
// Function to focus the select element
  const openSelect = () => {
    if (selectRef.current) {
      selectRef.current.showPicker();
    }
  };
  <div>
    <button type="button" onClick={openSelect}>
    Open Select
    </button>
    <select ref={selectRef} id="myCheck">
    <option value="option1">Option 1</option>
    <option value="option2">Option 2</option>
    <option value="option3">Option 3</option>
    </select>
  </div>
