### ISSUE TITLE
Can not edit search value

### ISSUE THREAD

**Issue by boyrest** [JedWatson/react-select#4030]
When I use creatable select, I can not edit search value after I searched. Now the element is div ,not input element. I can not focus on the value.

<img width="541" alt="WechatIMG642" src="https://user-images.githubusercontent.com/11408703/80297232-e9d27100-87b3-11ea-931a-3b2fac5dd241.png">
<img width="594" alt="WechatIMG643" src="https://user-images.githubusercontent.com/11408703/80297239-f5be3300-87b3-11ea-9525-df01ef291600.png">

**Comment by ebonow** [comment]
@boyrest I have run into a similar issue and came up with the following solution. I had posted on an earlier thread but tested this and believe this to be better in that it involves no extra styling to deal with the hiding that React-Select does to the Input and SingleValue


NOTE: isHidden prop does not seem to work properly hence the need to create a custom Input component to manually override the prop sent to the component.

```
import React, { useState } from 'react';
import Select, { components } from 'react-select';

export default EditableSelect = props => {

  // This needs to become a controlled component so track state
  const [ value, setValue ] = useState();
  const [ inputValue, setInputValue ] = useState('');

  const onInputChange = (inputValue, { action }) => {
    // onBlur => setInputValue to last selected value
    if (action === 'input-blur') {
      setInputValue(value ? value.label : '');
    }  
    // onInputChange => update inputValue
    else if (action === 'input-change') {
      setInputValue(inputValue);
    }
    return;
  }

  // Set state and call onChange prop sent to this HOC if defined
  const onChange = option => {
    setValue(option);
    props.onChange && props.onChange(option);
  }

  // A custom component is required to override the isHidden prop sent to the Input
  const Input = inputProps => <components.Input {...inputProps} isHidden={false} /> 

  // Since Input is never hidden, set controlShouldRenderValue prop to false
  return (
    <Select
      {...props}
      value={value}
      inputValue={inputValue}
      onInputChange={onInputChange}
      onChange={onChange}
      components={{ Input }}
      controlShouldRenderValue={false}
    />
)}
```

Let me know if you have any questions.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
