### ISSUE TITLE
Is it possible to have version 1 and version 3 in the same project ?

### ISSUE THREAD

**Issue by goxr3plus** [JedWatson/react-select#4032]
Hello :) , i absolutely love the new react-select-3 and would like to have it one project in which we already have react-select-1 .

Somewhere in the code there is this line :

```
import { AsyncCreatable } from 'react-select';
```

which i can't find any documentation about it in `react-select-3` , the developer of the project has left so i can't figure out .

What is the alternative of `AsyncCreatable` in react-select-3 ? If i can't replace it can i have like 2 versions of react-select-1 and react-select-3 in the same npm project without conflicts somehow :) ?

I saw this https://stackoverflow.com/questions/43770328/two-versions-of-same-npm-package-in-node-application but i don't know if i can do that for your project.

-------------------------------------------------------
@JedWatson  @flexdinesh 

Thank you so much please let me know .

**Comment by JedWatson** [comment]
Hi @goxr3plus sorry that's unclear in the documentation.

v3 does have AsyncCreatable, we split it out for code side reasons though, so now you need to import it like this:

```js
import AsyncCreatable from 'react-select/async-creatable';
```

I'm not sure about having both versions on the same page tbh; you might be able to hack it in by loading the old version from [unpkg](https://unpkg.com/) but I'd recommend upgrading everywhere to the new version if you can.

FWIW v3 should support all the same features v1 did, although the API has changed quite a bit. The [Upgrade Guide here](https://react-select.com/upgrade-guide) might help you.
