### ISSUE TITLE
HTML Validator error: Element style not allowed as child of element div

### ISSUE THREAD

**Issue by vargaLaszlo** [JedWatson/react-select#4033]
Hi there,

My site uses your awesome package. I have server rendered react and the W3C validator shows me this error:

**Error: Element style not allowed as child of element div in this context. (Suppressing further errors from this subtree.)
ectInner"><style data-emotion-css="2b097c-container">.css-2**

Is there a way to avoid the error?

greetz Laszlo

**Comment by ebonow** [comment]
Greetings @vargaLaszlo 

I did some research on this today, and it is related to the AutosizeInput rendered by the Input component and would only occur with Microsoft browsers.

[Here is the source of the issue:
](https://github.com/JedWatson/react-input-autosize/blob/0aa6225fb4ae4e30d51a23f75b36b15e709efdd0/src/AutosizeInput.js#L137)

Fortunately, there is a workaround. You can pass in a prop to the Input component to prevent it from doing this.

``` JS 
const Input = props => <components.Input {{...props}} injectStyles={false} />

const MySelect = props => <MySelect components={{ Input }} />
```

Please let me know if this does not resolve your issue and we can reopen this and continue to investigate.

**Comment by sylvestrevgen** [comment]
@ebonow Your solution is not resolve this issue. I use react-select in Gatsby project and have the same validation error. I wrote your solution but errors still be.

**Comment by sylvestrevgen** [comment]
@ebonow Here is this tag:
<img width="1089" alt="Screenshot 2021-03-09 at 11 52 49" src="https://user-images.githubusercontent.com/32303723/110452647-09be0b00-80ce-11eb-8deb-a0d41027f33e.png">

**Comment by oredavids** [comment]
I also have this issue in a NextJs application.

<img width="931" alt="Screen Shot 2021-06-02 at 9 36 10 AM" src="https://user-images.githubusercontent.com/21035422/120509732-01503600-c386-11eb-8ef3-15f1ca6a8fb9.png">

**Comment by kholiavko-roman** [comment]
Any solutions to avoid this errors?

**Comment by levipadre** [comment]
Same issue here, in a Nextjs project. My code if it helps:
```
const CountrySingleValue = (props: any) => {
    return (
        <components.SingleValue {...props} injectStyles={false}>
            <span className={`fi fi-${props.data.iso} me-2`}></span>
            <span className='d-none d-lg-inline'>{props.data.name}</span>
        </components.SingleValue>
    );
};
```
