### ISSUE TITLE
Defaultoptions not loading in IE 11 for AsyncCreatable select when creating using loop

### ISSUE THREAD

**Issue by vinu68** [JedWatson/react-select#4038]
I have creating select box using AsyncCreatable Array.map in ReactJs . On click of select box it should load default options in Menu. But its not loading in IE 11 browser . In Chrome its working fine. I have implemented it like as shown below:

> answersControls = question.answers.map((answer, index) => {
>            return (
>                 <div className="form-group" key={index}>
>                         <AsyncDropDown               
>                   className={'cw-select--custom'}
>                   name={'answer' + index}
>                   label={'Answer' + index}
>                   placeholder={'Search for answer'}
>                   loadOptions={this._getAnswers}
>                   defaultOptions={this.props.answers} 
>                   onChange={(val, actionMeta) => {
>                     this._handleAnswer(
>                       { index: index, value: val.value, label: val.label },
>                       actionMeta
>                     );
>                   }}
>                   isLoading={!this.props.answersLoaded}
>                   value={
>                     answer.label !== ''
>                       ? {
>                           label: answer.label,
>                           value: answer.value
>                         }
>                       : null
>                   }
>                 />
>                 </div>
> )
> })

Anyone please help me understand the issue.

**Comment by bladey** [comment]
Hi @vinu68, following up on this issue, I was wondering whether you found a solution to the IE11 issue.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
