### ISSUE TITLE
Input component does not have selectProps as a prop

### ISSUE THREAD

**Issue by vozghorkov** [JedWatson/react-select#4040]
All the react-select components (like control, menu, ...) have selectProps included among their props (as it is described in the documentation) while this is not happening for the Input component.

I`m using version 3.1.0. This is my code:

```
const customStyles = {
	input: (provided, state) => {
		console.log(state.selectProps) // this outputs: undefined
		return {
			...provided,
			color: state.selectProps.theme.color
		}
	},
}
```

**Comment by agmcleod** [comment]
I wonder if related to the fact that it doesn't seem to pass selectProps to the component? https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/Input.js#L51

**Comment by jrea** [comment]
+1, currently working around this with the `valueContainer` key.

```
valueContainer: (provided: ProvidedProps, state: SelectState) => {
    const { inputPaddingLeft } = state.selectProps;
    const paddingLeft = inputPaddingLeft != null ? inputPaddingLeft : provided.paddingLeft;
    return {
      ...provided,
      'div:nth-of-type(1)': { // 'input' key does not have selectProps
        paddingLeft,
      },
    };
  },
```

**Comment by ebonow** [comment]
Duplicate of #3982 

Closing this and getting more information. Will update in linked issue when I have more context and info.
