### ISSUE TITLE
isSearchable={false} still shows iOS footer on iphone6 with "Done" button

### ISSUE THREAD

**Issue by anhpt-bss** [JedWatson/react-select#4041]
_No details provided_

**Comment by anhpt-bss** [comment]
please!!!!!!!!!

**Comment by bladey** [comment]
@anhpt-bss, we get to issues as soon as we can. Could you please provide more information such as a video and a Codesandbox of the issue.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
