### ISSUE TITLE
Disable auto select of first option 

### ISSUE THREAD

**Issue by LuizGMiranda** [JedWatson/react-select#4042]
Hi,

I'm want to disable the auto select of the first option, how to this? Version 3.1.0

Thanks!

**Comment by manualva7** [comment]
If your intention is to put a placeholder, there is an option for that.

Please provide more information.

**Comment by LuizGMiranda** [comment]
Whenever I search for something and hit enter, it is selected or the first item. However I want to leave what I put without automatic item selection.

**Comment by manualva7** [comment]
You might want to look into creatable. https://react-select.com/home#creatable

**Comment by bladey** [comment]
This will be resolved when #4080 is merged.

**Comment by ebonow** [comment]
Greetings, this appears to be a duplicate of https://github.com/JedWatson/react-select/issues/2848. 

I will close this issue, but please feel free to subscribe to the mentioned issue to receive any updates regarding any updates in this PR being released.
