### ISSUE TITLE
async react-select fetching on every keystroke 

### ISSUE THREAD

**Issue by manualva7** [JedWatson/react-select#4043]
I love the ease of styling and functionality of react select. Props to you guys for doing an excellent job.

Recently I was requested to add an async option where I would fetch options if the option list amount was greater than 20 (all handled in the backend). I found it works great! However, the axios call is firing on every keystroke.

I've tried long and dead hours to figure this out. I'm almost there, but I'm stuck on this.

oncall is defined before the definition of the function component as oncall = false.
```
const promiseOptions = input =>
        new Promise( resolve => {
            setTimeout( () => {
                if (!oncall) {
                    oncall = true;
                    resolve(
                        axios.get(optionsUrl)
                            .then((response) => {
                                console.log(response)
                                oncall = false;
                                return response.data.data.filter(i => i.label.toLowerCase().includes(input));
                            })
                            .catch((error) => {
                                console.log(error);
                            })
                    );
                }
            }, 1000);
        });
```

This code works sometimes. It would be great if I can start a call after entering 3 letters, set a timer to call again only after the user has stopped typing for 1 second. I've managed to do this with 'onkeyup' on another search input in my app that doesn't use react-select. This plugin lacks the 'onkeyup' prop. I've also tried with settimeout without avail.

I appreciate any help.

**Comment by manualva7** [comment]
I figured it out.

`let allowCall = true;

    let results = (inputValue, data) => data.filter((key)=>key.label.includes(inputValue.toUpperCase()));

    const handleInputChange = (input) => {
        setValue({
            inputValue: input
        });
        return {value};
    };

    const handleGetResults = (inputValue) =>
        inputValue.length > 3 && allowCall &&
        postData(optionsUrl)
            .then(response => {
                return results(inputValue, response.data.data)
            })
            .catch((data) => {
                console.log(data)
            });

    const promiseOptions = inputValue =>
        new Promise(resolve => {
            setTimeout(() => {
                resolve(handleGetResults(inputValue));
            }, 1000);
        });

    let counter = setTimeout(()=>{
        allowCall = true
    },1000);

    const handleKeyDown = () => {
        allowCall = false;
        clearTimeout(counter);
        return counter
    };`

**Comment by manualva7** [comment]
EDIT:

Outside of your component and before defining it, you must add:

```
async function postData(url) {
    return await axios.get(url);
}
```
Then inside your component, add:

```
let allowCall = true;

    let results = (inputValue, data) => data.filter((key)=>key.label.includes(inputValue.toUpperCase()));

    const handleInputChange = (input) => {
        setValue({
            inputValue: input
        });
        return {value};
    };

    const handleGetResults = (inputValue) =>
        inputValue.length > 3 && allowCall &&
        postData(optionsUrl)
            .then(response => {
                return results(inputValue, response.data.data)
            })
            .catch((data) => {
                console.log(data)
            });

    const promiseOptions = inputValue =>
        new Promise(resolve => {
            setTimeout(() => {
                resolve(handleGetResults(inputValue));
            }, 1000);
        });

    let counter = setTimeout(()=>{
        allowCall = true
    },1000);

    const handleKeyDown = () => {
        allowCall = false;
        clearTimeout(counter);
        return counter
    };
```

Cheers

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing  issues that appear to be resolved.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by jisbruzzi** [comment]
I expected react-select async to have some sort of "cooldown" parameter to prevent browser from firing too many xhr requests

**Comment by ebonow** [comment]
Agreed. I have a point in the open docs improvement thread for this among a few other things that could use more visibility...
https://github.com/JedWatson/react-select/issues/3006#issuecomment-761839076
