### ISSUE TITLE
React-Select Selenium testing

### ISSUE THREAD

**Issue by deeajay** [JedWatson/react-select#4047]
We are trying to automate the testing of our application using selenium.
We successfully automated the previous version. But facing issues while working with latest.

Is there any solution for this?

**Comment by bladey** [comment]
Hi @deeajay, could you please provide more information about the issues you are facing with the latest version.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
