### ISSUE TITLE
Custom components

### ISSUE THREAD

**Issue by jibberishclient** [JedWatson/react-select#4049]
I'm just kinda confused on how to use custom components. I've been reading the docs and I saw a CustomOption component however when I tried to make my own I got an error. Essentially, I hate the default HTML select styling but I'm trying to make something like this:

https://codesandbox.io/s/admiring-lamport-sqfim?file=/src/App.js

I'd like to use Tailwind CSS classes to style both the "input" part of the select as well as the dropdown area. Namely I'd like to add some shadow and rounded corners, and change the font size, font family, and hover and selected background colors for the options. I know there's a theme CSS dict you can use but I'd prefer to use Tailwind by passing a className to custom components. How do I go about doing this?

**Comment by manualva7** [comment]
react-select styles are controlled by react-select. You can't just pass classes to the component.
https://react-select.com/styles

If your UI framework is controlled by a template, you just have to reference the styles directly from the template instead of hardcoding them. For example, I had to use theme.colors.primary, instead of using 'yellow' from an imported theme object. Hope that helps.

**Comment by ebonow** [comment]
@jibberishclient 
**className** string
Sets a className attribute on the outer component

**classNamePrefix** string
If provided, all inner components will be given a prefixed className attribute.

Is this what you are looking for?

**Comment by jibberishclient** [comment]
Ummmm I don't think so? I don't want to apply to all inner components, just the select items. And I don't think the tailwind classes would override the default classes.

**Comment by ebonow** [comment]
While using emotion should get you what you need by following the example and documentation here: https://react-select.com/styles#cx-and-custom-components

However, the provided example is currently broken both on the site and on the sandbox. Even after adding the missing reference to Emotion, I am still unable to apply any styling and the DOM class attribute is actually rendering as the string `[object Object]`.

Without knowing how to proceed by passing in the Tailwind CSS class names into the `cx` function of the custom components, I'd instead either use the classNamePrefix feature or passing the custom styling into the styles prop (examples given on the same page as the link provided above).

**Comment by ebonow** [comment]
@jibberishclient after some help, I was able to put together an example to demonstrate how using Custom Components and Emotion, you could add your own Tailwind supported CSS classNames.

https://codesandbox.io/s/react-codesandboxer-example-s6to7?file=/example.js

The example shows a custom Option component, but the same pattern should apply for both the Input and Menu.

Please let me know if this satisfies your use-case.

**Comment by bladey** [comment]
Thanks for providing such a helpful example @ebonow.

This issue will now be closed due to inactivity from the original author. If you have any further feedback, let me know and the issue will be re-opened.

**Comment by kulkarnipradnyas** [comment]
just write a console in custom component option and just hover over options , component rerenders on each hover.any one has solution for that?

**Comment by ebonow** [comment]
@kulkarnipradnyas - Yes, it happens because there are mouse events attached to add styling for when its focused. To remove this,
```
const Option = props => {
  delete props.innerProps.onMouseMove;
  delete props.innerProps.onMouseOver;
  return <components.Option {...props}>{props.children}</components.Option>
}
```

Or something similar but you would have to add your own CSS styling to indicate when its hovered.

**Comment by kulkarnipradnyas** [comment]
@ebonow  really thanx...it worked like magic... stoped rerendering...

**Comment by arcanis** [comment]
> @jibberishclient after some help, I was able to put together an example to demonstrate using Custom Components and Emotion so that you could add your own Tailwind supported CSS classNames.

One problem I have with this approach is that I need to both remove the "optional styling" options, and keep the "mandatory layout" ones (otherwise the elements' display is completely broken) - which is difficult as the default style are kind of a black box (I could make assumptions, but that would make me uncomfortable with react-select upgrades).

What would be perfect for me would be for react-select to ship with a "no style" theme that would literally just layout elements in a basic way, with all the pretty styling (borders, paddings, etc) being handled by the user via (ideally) class names or custom style properties.

**Comment by ebonow** [comment]
Greetings @arcanis ,

Do you have any examples of what constitutes as a mandatory layout?  There are very few cases I can think of:
- The `Control` component uses flex to position the `ValueContainer` and `IndicatorsContainer` 
- `SingleValue` uses position absolute to position itself over the `Input`

The beauty is that either of these can still be modified without breaking the Select. For example, if you want a Select that appears inline to text content, the above values could still both be modified [as in this example](https://codesandbox.io/s/react-select-inline-kk1u6?file=/style.css)

For the most part all optional and easy to override or completely toss out using the custom styles and not spreading the provided styles into the component.

For example:
```
const styles = {
  option: () => ({})
}
```
This would return an option with no internal styles applied to it which can be used as a blank slate approach. Yes, you'd need to add hover/selected styling to it yourself, but it's likely not a big deal of you are trying to use another 3rd party library to handle the styles or creating your own which can all be done without fear of conflicting styles.

Again, if you had more concrete examples of "optional" vs "mandatory" styles, I would be happy to help, but I am not certain I understand the concern as it stands.
