### ISSUE TITLE
how to do autocomplete using react select without loading that data at once only load the data on typing input characters

### ISSUE THREAD

**Issue by ajayupreti** [JedWatson/react-select#4050]
how to do autocomplete using react select without loading that data at once only load the data on typing input characters

**Comment by manualva7** [comment]
https://react-select.com/async

**Comment by ajayupreti** [comment]
@manualva7 that example is searching on already existing data but I want do to something like this -
**GitHub users (Async with fetch.js)** in this link - https://jedwatson.github.io/react-select/

**Comment by manualva7** [comment]
What have you tried so far?

**Comment by bladey** [comment]
Hi @ajayupreti, the examples provided on the async page (https://react-select.com/async#loading-asynchronously) are demonstrating how to load async data.

The first example has a `loadOptions` function, where is where you would be requesting your data from another remote source.

The timeout is added to demonstrate the time it would take to load options from another remote source.

```
const loadOptions = (inputValue, callback) => {
  setTimeout(() => {
    callback(filterColors(inputValue));
  }, 1000);
};
```

Please let me know if this makes sense.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
