### ISSUE TITLE
react select dropdown doesn't show on top with scrolling table

### ISSUE THREAD

**Issue by phungttran2018** [JedWatson/react-select#4052]
**I am working on an application where I have a scrolling table. Inside tablecell, I have react select dropdown. However, the dropdown will not display above the tablewrapper div. If i use a regular select component (<select), it will show above the table. Please see attachment.

On my code, it looks something like this. Note that this is just a short version of my code.**

styles ===> 
`    tableWrapper: {
        maxHeight: 400,
        overflow: 'auto',
        width: '100%',
    },
<div className={classes.tableWrapper}>
<Table>
    <TableHead/>
    <TableBody>
          tableData.map(.......
                    return (
                            <TableCell key={i} align="center" onClick={()=>this.setState({onScroll:false})}>
                                <Select
                                    // menuPlacement="auto"
                                    styles={{ menu: base => ({ ...base, zIndex: 1400, position: 'absolute' }) }}
                                    // menuPortalTarget={document.body}
                                    value={value[i]}
                                    onChange={(element) => this.handleChange(element, index)}
                                    options={options}
                                    clearable={false}
                                    backspaceRemoves={false}
                                    isDisabled={!obj.checkBox} />
                            </TableCell>
                        )
           )
    </TableBody>
</Table>
</div>
`
**Key point here is If i use menuPortalTarget={document.body} there seem to be a bug where the menu Drop down is literally not follow the component when user is scrolling as shown in issue https://github.com/JedWatson/react-select/issues/3734. I tried to use like block scrolling as well but block scrolling also block the scrolling of my menu dropdown. zIndex for select component won't work with div that have overflow: auto. Meanwhile waiting for issue 3734 to be fix, I am wondering is there anything we can change in css where we can have the menu dropdown show as the highest priority and show it like the default select ?**
 
![image](https://user-images.githubusercontent.com/32987401/82256265-9fa85f80-991b-11ea-86c8-79fd9edb82da.png)
![image](https://user-images.githubusercontent.com/32987401/82256307-b3ec5c80-991b-11ea-9eb3-97fbb9163f22.png)

If you can;t see the code above, here is a screen shot. I am not getting used to git hub so it doesn't look format right on my side.
![image](https://user-images.githubusercontent.com/32987401/82257156-2e69ac00-991d-11ea-9281-8b4e2bd10f76.png)

**Comment by benkindt** [comment]
> I tried to use like block scrolling as well but block scrolling also block the scrolling of my menu dropdown.

This works in version 3.0.4, if it helps you. I guess you tried it with a newer version.

**Comment by bladey** [comment]
Hello -

Thanks for reporting this issue.

This bug has been reported multiple times as per issue #4088.

A new master issue #4088 has since been created to keep track this this bug.

This new issue will exist as the source of truth going forward to investigate the issue, report findings, and implement a bug fix.

We'll take into account all the details above while investigating.

If you feel this issue has been wrongly closed as it isn't related to the new master issue #4088, please let us know and we'll take another look.

Thank you!
