### ISSUE TITLE
Option Attribute

### ISSUE THREAD

**Issue by hlarcher** [JedWatson/react-select#4053]
Is there a way to add an attribute to the option markup, id, class or something else?

**Comment by ebonow** [comment]
@himerus The best way to add attributes to an Option component is to create your own Custom Component. 

[Here is an example](https://codesandbox.io/s/react-codesandboxer-example-s6to7?file=/example.js) using custom components using Emotion for managing the internal component styling. The list of options you provide to the select can contain any extra information within the option data that which can then be passed to the Option component (demonstrated below).

You could also wrap either the components.Option or its children with markup. Here is an example of code taken from my own implementation of a custom Option using option data to easily add icons from our library as well as checkboxes for the multiSelect.
```
const Option = ({ children, ...props}) => {
  const { isSelected, value, isMulti, data } = props;
  const { icon, iconClassName='', className='' } = props.data;
  const optionTextClassName = CN('react-select__option-text', className, { 'react-select__option-text--no-icon': !icon });

  const onClickMultiOption = (e) => {
    props.selectOption({...data});
    e.stopPropagation();
    e.preventDefault();
  }

  return (
    <components.Option {...props}>
      { icon && <Icon className={iconClassName} name={icon} /> }
      { isMulti ? (
        <div onClick={onClickMultiOption}>
          <Checkbox checked={isSelected} label={children} value={value} />
        </div>
      ) : (
        <div className={optionTextClassName} children={children} />
      )}
    </components.Option>
  );
}

```

**Comment by bladey** [comment]
Thanks for such a detailed response @ebonow.

This issue will now be closed. @hlarcher if you have any further feedback please let me know and the issue will be re-opened.
