### ISSUE TITLE
Setting label in react-select

### ISSUE THREAD

**Issue by vigneshkbala** [JedWatson/react-select#4054]
I have table component and details component. the first column of table is Link and by clicking the link to navigate to details components along with row values using state prop. The detail components which having react-select control and i need to assign the value which we got it from table comp in the select when loading the details comp. after click on Link, componentdidmount method in details comp will be called and i used axios to fetch the master details and then assign the value in the select. The issue is the value is NOT assigning in the react-select drop down. How to resolve this. pls help..

**Comment by bladey** [comment]
Hi @vigneshkbala, could you please provide a Codesandbox link which demonstrates this issue so we can look into it further.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
