### ISSUE TITLE
WARNING in ../~/react-select/dist/Select-b0ada71d.browser.cjs.js

### ISSUE THREAD

**Issue by vincegerald** [JedWatson/react-select#4055]
I am having this warning right after installing the package.

![Untitled](https://user-images.githubusercontent.com/41583496/82566676-da75f600-9bae-11ea-9e46-ce8e56da91b8.png)

Thanks for the help. Much appreciated.

**Comment by bladey** [comment]
Hi @vincegerald, could you please provide more details about your install environment and a Codesandbox with what you are trying to achieve.

**Comment by ebonow** [comment]
This feels like a build issue. Would you also mind sharing your build config?

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
