### ISSUE TITLE
Creatable with sortable multiSelect functionality

### ISSUE THREAD

**Issue by vivekmpuh** [JedWatson/react-select#4056]
Hi,

How can I combine both Creatable and MultiSelect sortable functionality together.
something like user can create his own tags and re-order them if he want.

**Sortable MultiSelect example:** https://react-select.com/advanced#sortable-multiselect
**Creatable example:** https://react-select.com/creatable

I tried to implement it as shown in above links, but the sort is not working at all using creatable. 

live example will be really appreciated.
Thanks

**Comment by ebonow** [comment]
Sure why not?
I just forked the example, added a reference to Createable, and then wrapped it in the sortable HOC. Seems to be working as expected.

https://codesandbox.io/s/react-select-sortable-creatable-e1pqe?file=/example.js

I'll close this out for now, but happy to answer any question or re-open if there are any issues with this implementation.
