### ISSUE TITLE
Unable to set the text color of the selected value using classNamePrefix

### ISSUE THREAD

**Issue by francoisihry** [JedWatson/react-select#4057]
I have set the classNamePrefix :

```
<Select
                classNamePrefix="react-select"
                value={selectedOption}
                onChange={this.handleChange}
                options={options}
            />

```
then I created the css class react-select__single-value to display the selected value in red:

```
.react-select__single-value {
    color: red;
}

```
But I see that this css class is overwrited by the css-1uccc91-singleValue:

![image](https://user-images.githubusercontent.com/10637903/82684234-8886ac00-9c52-11ea-9a1c-8aaaec3b22bb.png)

Do you have an idea ?

**Comment by ebonow** [comment]
This is a CSS question regarding **specificity**

Try using the selector
```
.react-select .react-select__single-value {
    color: red;
}
```

or even...

```
.react-select__single-value.react-select__single-value {
    color: red;
}
```

Please try this and consider closing this question if this solution works for you.

**Comment by bladey** [comment]
Thanks for taking the time to help out @ebonow.

@francoisihry, please let us know if this solves your issue - for now I'm going to close the issue to keep our list under control. Let me know if it should be reopened.

**Comment by Sodabeh-Taherpanah** [comment]
No , It did not help.
