### ISSUE TITLE
Unable to select any menu option in firefox mobile view in ubuntu.

### ISSUE THREAD

**Issue by jarvistesting** [JedWatson/react-select#4065]
### Thanks for using react-select!

Firefox version : 76.0.1 (64-bit)
react-select version : 3.1.0

when we click on select it opens menu and within a sec. it get disapper automatically.
when we do double click on select then menu options doesn't disappear

**Comment by salletti** [comment]
Same problem with macosx:

```
import Select from 'react-select';

...

 const options = [
      { value: '', label: 'Select a value' },
      { value: 'chocolate', label: 'Chocolate' },
      { value: 'strawberry', label: 'Strawberry' },
      { value: 'vanilla', label: 'Vanilla' }
    ];

....

<Select options={options} defaultValue={options[0]} />
```

**Comment by ebonow** [comment]
@jarvistesting thank you for reporting this and sorry for the long wait for a reply here.

I believe there have been some fixes in mobile Firefox emulation per some testing I did regarding
https://github.com/JedWatson/react-select/issues/3886

Would you or anyone on Ubuntu kindly mind retesting that mobile Firefox can select an option from the select.

**Comment by ebonow** [comment]
@salletti I am on OSX and am not experiencing any issues with the described behavior.

**Comment by ebonow** [comment]
Due to a lack of activity, I will mark this ticket as closed but happy to re-open if anyone can reliably confirm that this is still an issue.
