### ISSUE TITLE
Dropdown options not scrolling when select is rendered on modal/dialog

### ISSUE THREAD

**Issue by Sridatta7** [JedWatson/react-select#407]
In Selectize, when the dropdown is rendered on a modal/dialog, we have an option of setting the attribute 'dropdownParent' to 'body' so that scroll applies to dropdown options (instead of the window).

Is there a way we could achieve the same behaviour in react-select?

**Comment by A11oW** [comment]
+1
If react-select rendered in modal of react-bootstrap then dropdown list, closes after click on scroll bar

**Comment by satya-dash** [comment]
In react-select only one option is visible and scroll function is not working for dropdown list.

**Comment by holyman2k** [comment]
look it's only an issue for edge/ie, it's still an issue non the less

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
