### ISSUE TITLE
Browser boundaries

### ISSUE THREAD

**Issue by m-reyes-h** [JedWatson/react-select#4070]
The component does not respect the browser boundaries. It try to make some more room if the option list is greater than the parent component or the browser it self

**Comment by bladey** [comment]
Hi @m-reyes-h,

Thanks for reporting this issue, could you please provide a code sandbox link which demonstrates the issue?

**Comment by m-reyes-h** [comment]
Here is an example, let me know if ...

[Sandbox](https://codesandbox.io/s/strange-brahmagupta-1ejrp?file=/src/App.js)

**Comment by bladey** [comment]
Thanks @m-reyes-h!

**Comment by bladey** [comment]
@m-reyes-h, @topolanekmartin has a good point here, a native browser select is an exception to a CSS select, you'll need to find a solution and style it so it renders appropriately for your use case.
