### ISSUE TITLE
CreatableSelect simplevalue not working

### ISSUE THREAD

**Issue by canercak** [JedWatson/react-select#4071]
I'm trying to make CreatableSelect work with simplevalue={true} as it works for normal multiselect. It generates value-label objects all the time such as [{value: "material", label: "material}]. What I need is just ['material'].  

I tried to changing the code as below without any succcess.
line 23 of creatable/dist/react-select.cjs.js and all others
```
  var optionValue = String(option).toLowerCase();
  var optionLabel = String(option).toLowerCase();
```
anyone who is experienced in the code can implement it or show me a way on how to do it?

**Comment by ebonow** [comment]
I'm not familiar with any simplevalue prop.

I think the most straightforward way would be to simply pass in your options mapped through as objects with labels and values. This should achieve what you are looking for. Let me know if I am missing anything.

```
var things = ['material']
var toOption = label => ({ label, value: label });

var [ options, setOptions ] = useState(things.map(toOption));

var getNewOptionData = inputValue => {
     var newOption = mapped(inputValue);
     setOptions([...options, newOption]);
     return newOption;
}

< CreatableSelect options={options} getNewOptionData={getNewOptionData} />

**Comment by ebonow** [comment]
I believe this can be closed as the documentation cites this specific prop as a section within the upgrade documentation.

https://react-select.com/upgrade-guide#simple-value

**Comment by bladey** [comment]
Thanks for your assistant @ebonow, much appreciated.

@canercak if this doesn't solve you're issue, please let us know.
