### ISSUE TITLE
When multi select is enabled it should pass data as Array but it passes simple string values separated by comma

### ISSUE THREAD

**Issue by hanzlahabib** [JedWatson/react-select#4072]
i am having form where i am selecting multiple tags, and when i submit it should pass data as array of tags but it passes as string tags separated by commas, 

is there anything i am missing? 

I can fix it in handleChange but i am looking for any built in flags that do this job

**Comment by ebonow** [comment]
Greetings @hanzlahabib ,

Form data is generally passed as a single comma delimited string and not an array. Ideally it would act no different than a Select with a multiple attribute on it. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple

If you would like to apply custom mapping to an array, that is likely a job better suited for onSubmit.

Let me know if I answered your question and if you have any others please feel free to reply and we can re-open this ticket and/or discuss this further.
