### ISSUE TITLE
Custom MultiValue but keeping default MultiValueRemove

### ISSUE THREAD

**Issue by bfiorito** [JedWatson/react-select#4073]
Hi guys,
I'm trying to simply customize a label with an icon, here's the code: 
```javascript 
const MultiValue = (props: ReactSelectProps) => {
            const {data} = props;
            return <div className="input-select-container">
                <div className="input-select-label-container">
                            <span className="input-select-icon">
                                <img src={data.icon} height={16}/>
                            </span>
                    <span className="input-select-label">{data.label}</span>
                </div>
            </div>
        }
```

and then passing components to Select
````javascript
<AsyncSelect
                ...
                components={{MultiValue: MultiValue, Option: Option}}
/>
````

But i'm not able to keep the default MultiValueRemove icon to remove current item.

I tried to customize MultiValueRemove and MultiValue then customize MultiValueLabel and MultiValueRemove but still not displaying the cross.

What am i doing wrong guys ?

Thanks in advance,
Bastien

**Comment by bfiorito** [comment]
Ok i figured out what was the problem.
{data.icon} is an URL so the icon is loaded asynchronously when the label is rendered.
The icon is displayed once loaded but shift content to the right because width of the label depending on actual content during rendering.
What's why i did not see the MultiValueRemove which was shift.

I had to simply fix height and width of the icon span to take in account the image size during label rendering.

Sorry for the noise guys

**Comment by kirtirajsinh** [comment]
```
 const customOption = () => {
    return(
      <>
        {joinedCommunities.map(community => (
          <div>
            <span>{community.name}</span>
          </div>
        ))}
      </>
    )
  }
```
                 `   <Select components={{option: customOption}} />`

Here's my Select component and I'm not able to see any options. I've checked that the joinedCommunities is not empty. Everything looks fine but still not able to achieve the options.
