### ISSUE TITLE
Multi select don't work with 'IsMulti' prop! You need to change this for 'multi'

### ISSUE THREAD

**Issue by dguerreros93** [JedWatson/react-select#4074]
the example code for a multi select in the Doc look like that:
`import React from 'react';

import Select from 'react-select';
import { colourOptions } from '../data';

export default () => (
  <Select
    defaultValue={[colourOptions[2], colourOptions[3]]}
    isMulti
    name="colors"
    options={colourOptions}
    className="basic-multi-select"
    classNamePrefix="select"
  />
);`

But, the "IsMulti" prop don't work.. the correct prop is "multi" and done!

**Comment by itsmadhusudhan** [comment]
It worked for me. The default value will be selected and upon selecting other it will be added to the selected list.

check if there is any problem with passing the default value.

```jsx
 <ReactSelect
      options={props.options}
      defaultValue={{
        label: 'monday',
        value: 'mon',
      }}
      isMulti
    />
```

I have tested this is latest version 3.1.0

**Comment by razh** [comment]
You're on version 1.x. `multi` was renamed to `isMulti` in the 2.x rewrite:

https://react-select.com/upgrade-guide#prop-update-guide

https://github.com/JedWatson/react-select/blob/26b7f221e3e2d88fa77042a9df81f5f84ea10ac4/docs/pages/upgradeGuide/props.js#L88

**Comment by bladey** [comment]
Thanks for your assistance @razh.

I'm now closing this issue as it appears to be answered.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you.
