### ISSUE TITLE
Display selected options outside the component

### ISSUE THREAD

**Issue by marcdelalonde** [JedWatson/react-select#4078]
Hi There !

I am using react-select for some of my projects and I am very excited about it.

However it would be awesome to have a native way to be able to display selected options outside the component and hide them inside it.

I am using css to achieve this, but maybe I missed this part in the doc ?

Thanks

**Comment by manvydasu** [comment]
What do you mean by hiding them inside it? Is it the same as not displaying them in dropdown options? You could just filter them out.

**Comment by bladey** [comment]
Hi @marcdelalonde, as mentioned by @manvydasu could you please provide some more information on what you are trying to achieve, such as a screenshot.

**Comment by marcdelalonde** [comment]
Hello @manvydasu & @bladey,

What I am trying to achieve is to keep exactly the same behavior, expect that I'm displaying the selected options list outside the react-select element, instead of having the list inside the input.
I am hiding the selected options list with a simple display: none, but maybe there is a native component option ?

Thank you

**Comment by ebonow** [comment]
@marcdelalonde 

> expect that I'm displaying the selected options list outside the react-select element

Does this mean that you are using a multi-select (isMulti = true)? 

If you are hiding the selected values, then there is a prop called `controlShouldRenderValue` that might be what you are looking for.

**Comment by bladey** [comment]
This issue will now be closed due to inactivity as there has been no response for further information. If anyone has further feedback please let me know and the issue will be re-opened.
