### ISSUE TITLE
HELP: How to replace SelectContainer/Control with a Button

### ISSUE THREAD

**Issue by tylercaceres** [JedWatson/react-select#4086]
I'm trying to create a simple button that will extend react-select.
So far I've tried using the Custom Components but there seems to be a lot of props.children that I have to keep using as I drill down.
Is there a simple way to replace the control box with a simple button that'll perform the same way?

Thanks in advance.

**Comment by bladey** [comment]
Hi @tylercaceres,

Are you referring to something like the `Experimental > Popout` example on this page? - https://react-select.com/advanced

**Comment by bladey** [comment]
This issue will now be closed due to inactivity. If anyone has further feedback, the issue will be re-opened.
