### ISSUE TITLE
How to use React Select with Google Places API?

### ISSUE THREAD

**Issue by FatehAK** [JedWatson/react-select#4092]
I was just wondering how to implement Places Autocomplete with react-select

**Comment by bladey** [comment]
Hi @FatehAK,

It appears 2 people have implemented this in the past few years, here:

https://github.com/akofman/react-select-places
https://github.com/javiercr/react-select-google-places

Their implementations might give you some clues on how to implement it in the latest version.

I couldn't find anything else however relating to using Google Places API.

**Comment by FatehAK** [comment]
Thanks @bladey will check them out
