### ISSUE TITLE
add button icon to select

### ISSUE THREAD

**Issue by MohsenEs** [JedWatson/react-select#4098]
How can I add a button to the end of select to open a modal by clicking?

**Comment by ebonow** [comment]
Hello @MohsenEs 

I am not clear what your question is. My best guess is one of the 3 options...
-----------------------I
I  Select......... 1*  I ▼ 2 * I 3*
-----------------------I

1. At end of selected option before the dropdown indicator
- You will need to create a custom ValueContainer component

2. Inside the select but next to the dropdownIndicator
- You will need to create a custom IndicatorContainer or Control component

3. To the far right of the select container?
- You will need to create a custom SelectContainer

There are several examples [here](https://react-select.com/components)

In your case based solely on best guess, it'd likely be something like : 

```
import Select, { components } from 'react-select';

const openModal = () => { /* Your code goes here */ };

const Control = ({ children, ...props }) => (
  <components.Control>
    { children } 
    <button onClick={openModal}>Open Modal</button>
  </components.Control>
)

return <Select components={{ Control }} ...>
```

Please share back if this is helpful or if you have any questions.

**Comment by A-n-d-r-e-a-s-M** [comment]
Hi,
if you write 
`components.Control {...props}>
        {children}
        <button onClick={openModal}>Open Modal</button>
    </components.Control>` (I fixed the code above)
then you will see the button at the end of the Select element. But, if you click on the button, the dropdown is opened. The same thing happens with IndicatorsContainer. How can I execute the button action without the dropdown action?

Regards,
Andreas

**Comment by MohsenEs** [comment]
That's exactly what I want, but does it get an error with your code? What's the problem?

index.js:1 The above error occurred in the <Control> component:

Uncaught TypeError: getStyles is not

`import React from 'react';
import Select, { components } from 'react-select';
import { colourOptions } from '../data';
const openModal = () => { /* Your code goes here */ };

const Control = ({ children, ...props }) => (
  <components.Control>
    { children } 
    <button onClick={openModal}>Open Modal</button>
  </components.Control>
)


export default () => (
  <Select
    closeMenuOnSelect={false}
    components={{ Control }}
    defaultValue={[colourOptions[4], colourOptions[5]]}
    isMulti
    options={colourOptions}
  />
);
`

**Comment by ebonow** [comment]
> Hi,
> if you write
> `components.Control {...props}> {children} <button onClick={openModal}>Open Modal</button> </components.Control>` (I fixed the code above)
> then you will see a button at the end of the Select element. But, if you click on the button, the dropdown is opened. The same thing happens with IndicatorsContainer. How can I execute the button action without the dropdown action?
> 
> Regards,
> Andreas

Thanks for finding the missing props I forgot to spread to the custom component. I updated the example code.

In regards to the menu component popping up, that does present a bit more complexity than I anticipated. 

My initial thought would be the following:
-  Wrap components.Control in a parent div and make the button a sibling
- Override the styling for the Control to have no border or box-shadow
- Apply the styling instead to the parent div making sure it is given the same (or custom styling) that the Control had. 

Another thought might be to apply an onClick event to the Control and identify if the target is the button, and if so, either cancel or blur and have it call the button click handler.

I can work on something a bit later but this would be my initial approach.

**Comment by ebonow** [comment]
@MohsenEs 

@A-n-d-r-e-a-s-M  found that I had missed passing in the rest of the props to the component.Control. I have updated it so it should recognize those missing props if you try now.

**Comment by MohsenEs** [comment]
Can you send me the explanation code you gave me?

**Comment by MohsenEs** [comment]
In fact, there was another way, using the input group, but if you put the button in the select, it will be more beautiful.
![2020-06-23_23-12-08](https://user-images.githubusercontent.com/46873097/85611015-cb320e80-b66c-11ea-9652-0d723a03a144.jpg)
![2020-06-24_22-46-26](https://user-images.githubusercontent.com/46873097/85611023-cc633b80-b66c-11ea-94bb-4c83d7c4c9d7.jpg)
![2020-06-24_22-46-36](https://user-images.githubusercontent.com/46873097/85611026-ccfbd200-b66c-11ea-8c16-76a50035a99c.jpg)

**Comment by ebonow** [comment]
> In fact, there was another way, using the input group, but if you put the button in the select, it will be more beautiful.
> ![2020-06-23_23-12-08](https://user-images.githubusercontent.com/46873097/85611015-cb320e80-b66c-11ea-9652-0d723a03a144.jpg)
> ![2020-06-24_22-46-26](https://user-images.githubusercontent.com/46873097/85611023-cc633b80-b66c-11ea-94bb-4c83d7c4c9d7.jpg)
> ![2020-06-24_22-46-36](https://user-images.githubusercontent.com/46873097/85611026-ccfbd200-b66c-11ea-8c16-76a50035a99c.jpg)

There's an issue with the way focus is given to the Control component that prevents the button to be pressed without opening the Menu. I will look at a solution and give explanation with it.

In regards to UI example, I very much agree and am using something very similar but with a wrapper around two react-selects. One to choose the type of dropdown and the other to select.

<img width="317" alt="Screen Shot 2020-06-24 at 1 37 31 PM" src="https://user-images.githubusercontent.com/1007579/85614042-225dc200-b620-11ea-992b-14ebe0bea67f.png">
<img width="321" alt="Screen Shot 2020-06-24 at 1 38 12 PM" src="https://user-images.githubusercontent.com/1007579/85614045-22f65880-b620-11ea-8818-6c8f19803057.png">
<img width="307" alt="Screen Shot 2020-06-24 at 1 38 23 PM" src="https://user-images.githubusercontent.com/1007579/85614046-22f65880-b620-11ea-8a69-91c3abd20bab.png">

The datacenter list uses progressive nested menus depending on provider > country > region selections but haven't included with the screenshots due to proprietary data in the list.

**Comment by ebonow** [comment]
I think the examples provide a better idea of what you are trying to do. You are not necessarily trying to put the Button in the Select, but rather next to it. It looks like you are using Bootstrap, but if not, the methodology should be similar.

1. Just wrap for your Button(s) and Select into an input-group
```
<div className="input-group">
  <div class="input-group-prepend">
    <button class="btn btn-outline-secondary" type="button">Button</button>
  </div>

  <Select>

  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button">Button</button>
  </div>
</div>
```
2. All that is missing is the styling. The container of the Select needs to be able to flex to fill the available space and the Control needs to adjust the border-radius to remove the rounded corners. This can be done using the `styles` prop found here: https://react-select.com/styles
```
const styling = {
  container: css => ({ ...css, flex: '1 1 auto', alignSelf: 'stretch' }),
  control: css => ({ ...css, borderRadius: 0 })
}
```

3. If you create it as a component, you could potentially pass in whatever content you want into either before or after and adjust the control's border-radius based on prepend/appended components which shoudl be straight forward enough for you to take from here.


In any case, here's a working sandbox. Let me know if this is what you were looking for.
https://codesandbox.io/s/react-select-input-group-with-bootstrap-xt7uv?file=/example.js

**Comment by MohsenEs** [comment]
Thanks, it's good. The only small problem is that when I put an icon or text in the button, a space is created. Where might the problem be?
![2020-06-25_13-09-44](https://user-images.githubusercontent.com/46873097/85687024-bb0a4580-b6e5-11ea-8fa5-2559d6189525.jpg)
![2020-06-25_13-10-17](https://user-images.githubusercontent.com/46873097/85687028-bc3b7280-b6e5-11ea-812d-8ec93e366583.jpg)

**Comment by MohsenEs** [comment]
That's right, I reduced the padding

**Comment by ebonow** [comment]
> That's right, I reduced the padding

@MohsenEs Vertical padding doesn't appear necessary on the buttons as it renders just fine for me with `padding: 0 0.75rem` 

In any case, glad you found what you were looking for and if you are satisfied, please close this ticket so we can keep the issue log tidy.
