### ISSUE TITLE
ScrollCaptor on unmount throw error as scroll target is null

### ISSUE THREAD

**Issue by jacobbrown0192** [JedWatson/react-select#4099]
Hey,

I am getting an error `Cannot read property 'removeEventListener' of null` when unmounting the ScrollCaptor. 

The problem is that when the select component menu mounts the scroll target in the ScrollCaptor doesn't get set. Not sure the exact cause but it has to do with me using a custom virtualized menu component and dynamically adding in the select and the menu items async loading. (if I am not doing one of these three it seems to work fine.)

Regardless it seems like the menu element doesn't load on mount as there are no items in the menu so the ScrollCaptor isn't able to set the scroll target on mount. The problem is that on unmount it attempts to remove listeners from the scroll target but as that is null it throws the error.

This works fine on mount as there is a short circuit here when it attempts to start listening:
https://github.com/JedWatson/react-select/blame/master/packages/react-select/src/internal/ScrollCaptor.js#L29

But there is no short circuit when it attempts to stop listening. Is there a reason for this?

@iulian-radu-at I noticed that you were the one that added in a short circuit for mounting the ScrollCaptor without a scroll target set. Do you know why one was added on start listening and not on stop listening?

**Comment by iulian-radu-at** [comment]
Hi @jacobbrown0192,

I added only in start listening because the crashed happened for me only there. At that moment, I did not expected to have a crash in stop listening.

I am sure that you hit the case were we should have the same check in stop listening code too.

In my case, it happened because of a time race condition (most likely). It looks like it can be your case too.

Cheers,
Iulian

**Comment by bladey** [comment]
Thanks for the detailed answer @iulian-radu-at.

This issue will now be closed. @jacobbrown0192 if you have any further feedback, let me know and the issue will be re-opened!
