### ISSUE TITLE
FilterOptions break with some internal undefined

### ISSUE THREAD

**Issue by sospedra** [JedWatson/react-select#410]
So, if I  set up the filterOptions like this (really dummy test, it just remove all the default filters):

```
filter: function (options, filter, currentValues) {
     return options
}
```

It breaks and prompt this error:
`Uncaught TypeError: Cannot read property 'length' of undefined`

[This piece of code](https://github.com/JedWatson/react-select/blob/b1ca2eddb85e66efdec16af4a10b79f18d7c2956/lib/Select.js#L265-L272):

```
getFirstFocusableOption: function getFirstFocusableOption(options) {
    for (var optionIndex = 0; optionIndex < options.length; ++optionIndex) {
        if (!options[optionIndex].disabled) {
            return options[optionIndex];
        }
    }
},
```

I've followed the stacktrace and it's always undefined. 

Any idea?

**Comment by eventhough** [comment]
@edravis It has been awhile but I just tried this in my app and it worked fine. Maybe you were not passing in an empty array to the options prop?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
