### ISSUE TITLE
classNamePrefix is not applied to the top most portal div

### ISSUE THREAD

**Issue by imyjimmy** [JedWatson/react-select#4107]
As documented in [Select.js](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L97), `classNamePrefix` is applied to all inner components, but it does not apply to the top-most portal div. Will there be some support for this, or an equivalent workaround?

**Comment by razh** [comment]
You can also specify `props.className`:

```tsx
<Select className="example" classNamePrefix="example-prefix" />
```

Which would result in approximately this HTML:

```tsx
<div class="example">
  <div class="example-prefix__control">
    <div class="example-prefix__value-container example-prefix__value-container--has-value">
      <div class="example-prefix__single-value">Example value</div>
      <div>
        <div class="example-prefix__input">
          <input type="text" />
        </div>
      </div>
    </div>
    <div class="example-prefix__indicators">
      <div
        aria-hidden="true"
        class="example-prefix__indicator example-prefix__dropdown-indicator"
      />
    </div>
  </div>
</div>
```

**Comment by bladey** [comment]
Thanks for the help @razh, does this resolve your problem @imyjimmy?

**Comment by imyjimmy** [comment]
I went with something else entirely, but this should also work. Thanks.

**Comment by bladey** [comment]
Thanks @imyjimmy.
