### ISSUE TITLE
Needs tests: #408 (clicking scrollbar hides menu)

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#411]
@bruderstein let me know if you think a different workflow would be better, but...

I've merged #408 (thanks @vomchik!) because I'd like to release a fix for that issue, but the PR didn't have tests.

Seems like a reasonable workflow in that case would be to (assuming no tests fail for a PR, of course) merge then create an issue to follow up with tests, so the fix can get out asap.

Otherwise we could wait for PRs to have tests added before they're merged. Not sure which will be the better process long term.

In any case, #408 has been merged, but there was a slight drop in coverage so let's get that under test!

**Comment by bruderstein** [comment]
That seems like a very reasonable workflow. I'll see what I can do, prob
won't be till next week though so someone might beat me to it!

**Comment by vomchik** [comment]
Sorry, but I haven't any idea how to test this bug :disappointed:

**Comment by bruderstein** [comment]
No worries - I'm not sure either, but maybe we can fake the same event that chrome was throwing. I'll see if I can reproduce it under test.

**Comment by vomchik** [comment]
I found one little bug after my changing :sob: 
If you stared search option and then selected any value list of option not disapier 

![screencast 2015-08-27 17-11-13](https://cloud.githubusercontent.com/assets/732085/9522698/bc86d2fa-4cde-11e5-9f48-b83f2aa5103b.gif)

Sorry.
How i can fix that?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
