### ISSUE TITLE
Creatable select "Create new" option does not show up when `defaultMenuIsOpen={true}`

### ISSUE THREAD

**Issue by ekscentrysytet** [JedWatson/react-select#4114]
# Are you asking a question?
No, reporting bug

# Are you reporting a bug or runtime error?
Bug. When `defaultMenuIsOpen={true}` and `isValidNewOption={() => true}` "Create new" option does not show up. It eventually starts to show up only when type any input or close and open menu again. Here's the sandbox: https://codesandbox.io/s/react-codesandboxer-example-1wl0i?fontsize=14&hidenavigation=1&theme=dark&file=/example.js
So I'm expecting "Create new" option to show up by default or are there any other ways it to be displayed by default?

**Comment by ebonow** [comment]
I looked at your Sandbox and was able to have success when adding the prop `openMenuOnFocus`.

This may or may not fit your use-case and it doesn't fix the issue of showing a new Createable Option when the input is blank, but hopefully this helps resolve your question about other ways for it to be displayed by default.

**Comment by bladey** [comment]
Thanks for your assistance @ebonow.

Does this help solve your issue @ekscentrysytet?

**Comment by ekscentrysytet** [comment]
@ebonow thanks for the workaround it exactly solves my case! @bladey yup, however I would still expect "Create new" option to show up when `defaultMenuIsOpen={true}` and `isValidNewOption={() => true}`. You may close the issue

**Comment by bladey** [comment]
Thanks @ekscentrysytet!
