### ISSUE TITLE
How to provide space between chips in multi select 

### ISSUE THREAD

**Issue by kamarajuPrathi** [JedWatson/react-select#4119]
<img width="455" alt="Screenshot 2020-07-10 at 10 45 25 AM" src="https://user-images.githubusercontent.com/25597219/87172843-7c09f180-c29a-11ea-9d04-af6063d37c26.png">

**Comment by ebonow** [comment]
https://react-select.com/styles#select-props

You could accomplish this with classNames but if you wanted to add margin with the custom styling method while only adding margin between multi-values, you could check the state/props of the option to check its index and add extra marginLeft if its index isn't 0

```
const extraMargin = 6;

const styles = {
  multiValue: ({ margin, ...css }, state) => ({ ...css, marginLeft: !state.index ? margin : extraMargin  })
};

return <Select styles={styles} />
```
