### ISSUE TITLE
React select passing props for components to useMemo

### ISSUE THREAD

**Issue by dileepthomas** [JedWatson/react-select#4121]
I am trying to use useMemo for the Option, MultiValue custom component in the react select.

When I tried it getting issue, am I missing something in the below code snippet?

Getting props undefined, what can be the issue, didn't find much reference on this 

Sample Snippet

```
import React, { useMemo } from "react";
import Select, { components } from "react-select";

const options = [
  { value: "chocolate", label: "Chocolate" },
  { value: "strawberry", label: "Strawberry" },
  { value: "vanilla", label: "Vanilla" }
];

const Option = useMemo(() => {
  return (
    <div>
      <components.Option {...props}>
        <checkbox checked={props.isSelected} onChange={() => null} />
        <label>{props.label}</label>
      </components.Option>
    </div>
  );
}, [props]);

const MultiValue = useMemo(() => {
  return (
    <components.MultiValue {...props}>
      <span>{props.data.label}</span>
    </components.MultiValue>
  );
}, [props]);

const CustomSelect = () => (
  <Select options={options} isMulti components={{Option, MultiValue}} />
);

export default CustomSelect;

```

Reproducible code [link](https://codesandbox.io/s/keen-spence-8hg48)

If i remo useMemo hook it works, but not understanding as it should work !! confused

**Comment by Rall3n** [comment]
@dileepthomas This is not a problem with this library, but instead a problem with your understanding of **hooks**.

Please read up on the proper usage of **React hooks** over at the [React documentation](https://reactjs.org/docs/hooks-intro.html).

**Comment by dileepthomas** [comment]
Yep, but as per the docs this how we need to do it in react when using the useMemo hook, isn't @Rall3n

**Comment by Rall3n** [comment]
@dileepthomas Definitely not. All hooks are designed to be only used **inside functional components**, like so (as described in the docs):

```jsx
const Options = (props) => {
    const memoValue = useMemo(() => { /* ... */ }, [ /* ... */ ]);

    /* ... */
} 
```

Not as components like you did:

```jsx
/* Just wrong */
const Option => useMemo(() => { /* ... */ }, [ /* ... */ ]);
```

**Comment by bladey** [comment]
Thanks for your help here @Rall3n.

@dileepthomas I'm going to close this now as @Rall3n points out this isn't `react-select` related.

Please let me know if you think otherwise.

**Comment by camcnz** [comment]
I can see what @dileepthomas is getting at. It would be great to have an example of how (if possible) to use react-select with memo and Hooks. 
For me currently React.memo(Select) doesn't work because you have to set double curly brackets '{{' in components={{SingleValue}}. This is creating a new object each render therefore triggering memo to rerender as it's a new prop.
