### ISSUE TITLE
Missing class names in rendered multi-select component

### ISSUE THREAD

**Issue by clmz** [JedWatson/react-select#4123]
Hello!
If I set a custom classname for the react-select component like this:

<ReactSelect 
...
className='react-select'>
the rendered component has divs with classnames like react-select__menu etc.

The element tree of a normal react-select:
![image](https://user-images.githubusercontent.com/47241471/87286313-0059b000-c4f9-11ea-9e55-eced4af3960f.png)

if I use the MultiSelect via prop isMulti, all these class names are missing. Only the parent div has a class named react-select, but there is for example no react-select__menu class for one of the child divs - there's a whitespace in the classname prop where this name should be.
The element tree of a multi react-select:
![image](https://user-images.githubusercontent.com/47241471/87286345-0a7bae80-c4f9-11ea-8ed4-288bc94ee3d9.png)

For me, the class names are very important for cypress tests, because I have no other way to access the correct div for testing.

**Comment by Rall3n** [comment]
@clmz Could you provide a minimal reproducible example of your issue?

**Comment by clmz** [comment]
@Rall3n 
kinda difficult because of the customizing, but I'll try:
I have a formik form:

`<Form isHorizontal col1={4} col2={8}>
                            ...
                           <Field
                                name="users"
                                type="multiselect"
                                label='users'
                                options={userOptions}
                                isLoading={isLoadingUserOptions}
                            /></Form> `

**Field** returns a FormikField, 'multiselect' is another custom cmp within this FormikField:

`<Group  name={name} label={label} ...>
<MultiSelect
                                choices={options || choices}
                                disabled={disabled}
                                searchable={props.searchable}
                                nonClearable={props.nonClearable}
                                placeholder={props.placeholder}
                                hasError={hasError}
                                disabledValues={props.disabledValues}
                                onValueChange={props.onValueChange}
                                usePortal={props.usePortal}
                                isLoading={props.isLoading}
                                formikFieldProps={fieldProps}
                                {...fieldProps.field}
                            />
</Group>`

**MultiSelect** finally returns the ReactSelect cmp:

` return (
        <div data-cy={`multiselect2-${props.name}`}>
            <ReactSelect
                name={props.name}
                value={getMultiSelectedOptions(props.value, props.name, options)}
                styles={styles}
                options={options}
                className="react-select"
                menuPortalTarget={portal}
                onChange={selectedOptions => {
                    // emulate standard input onChange event object
                    const value = selectedOptions ? selectedOptions.map(option => option.value) : [];
                    if (props.onValueChange) {
                        props.onValueChange(props.formikFieldProps, value, props.value);
                    } else if (props.formikFieldProps) {
                        props.formikFieldProps.form.setFieldValue(props.name, value);
                    } else if (props.emulateChangeEvent) {
                        props.onChange({
                            target: {
                                name: props.name,
                                value,
                            },
                        });
                    } else {
                        props.onChange(value);
                    }
                }}
                onBlur={() => {
                    // emulate standard input onFocus event object
                    if (!isFunction(props.onBlur)) {
                        return;
                    }
                    props.onBlur({
                        target: {
                            name: props.name,
                        },
                    });
                }}
                components={select2Components}
                isDisabled={props.disabled}
                isSearchable={props.searchable}
                isClearable={!props.nonClearable}
                isLoading={props.isLoading}
                placeholder={props.placeholder || django.pgettext('placeholder', '..auswählen')}
                noOptionsMessage={getNoOptionsMessage}
                menuPosition={props.menuPosition || 'absolute'}
                menuPlacement="auto"
                isMulti
            />
        </div>
    );`

Not sure if this helps a bit. The non-multi ReactSelect is handled in the same manner.

**Comment by ebonow** [comment]
@clmz Have you tried using the `classNamePrefix` prop?

**Comment by clmz** [comment]
@ebonow 
You're right - that works for me. I've not investigated in that direction because the naming of the inner components of the non-multi select was correct.
Thank you!

**Comment by ebonow** [comment]
> @ebonow
> You're right - that works for me. I've not investigated in that direction because the naming of the inner components of the non-multi select was correct.
> Thank you!

@clmz Excellent! If it's all working as expected then, would you kindly close the issue to help us manage the open issues list? Thank you.
