### ISSUE TITLE
Custom MenuList doesn't scrolling

### ISSUE THREAD

**Issue by LexaDel** [JedWatson/react-select#4124]
Hello!
I use react-select version 3.1.0 and I trying create Custom MenuList, but when I add div container with overflow then scroll doesn't work.
`const menuOptStyle = {
  overflowY: "auto",
  maxHeight: "200px"
};`
```
<components.MenuList {...props}>
      <div style={menuOptStyle}>
        <div style={menuHeaderStyle}>Custom Menu List</div>
        {props.children}
      </div>
</components.MenuList>
```

[Example](https://codesandbox.io/s/react-codesandboxer-example-xzfh6?file=/example.js)

**Comment by LexaDel** [comment]
Duplicate of #4028

**Comment by ebonow** [comment]
@LexaDel Greetings, it seems that you are trying to apply some styling to the MenuList, so I'd recommend applying the [styling through the styles prop.](https://react-select.com/styles)

[Here is a working forked example 
](https://codesandbox.io/s/react-codesandboxer-example-rxp4f?file=/example.js)
