### ISSUE TITLE
how can i saw  create new option at top by default 

### ISSUE THREAD

**Issue by kishan-tocca** [JedWatson/react-select#4127]
<CreatableSelect
                ref={r => (selectRef = r)}
                value={state.selectedOption}
                components={{ Option }}
                onChange={handleChange}
                options={state.options}
                isMulti
                getOptionLabel={option => option.label}
                getOptionValue={option => option.value}
                placeholder="Filter by location , name,...."
              />
like this is my setup

**Comment by ebonow** [comment]
Hello @kishan-tocca 

Have you tried this?
https://react-select.com/props#creatable-props

`createOptionPosition`
```
Sets the position of the createOption element in your options list. Defaults to 'last'
One of<"first", "last">
```

**Comment by kishan-tocca** [comment]
thanks for the solutions
