### ISSUE TITLE
MenuList with simplebar-react not scrollable

### ISSUE THREAD

**Issue by huboo** [JedWatson/react-select#4129]
**Bug: react-select@v3.1.0 with simplebar-react not scrollable** 

Old version 3.0.4 is able to scroll.

After upgrade to react@16.13.1 old version of react-select cause components update warning in browsers' console so upgrade to latest react-select@3.1.0

After upgrade the warning is gone but react-select MenuList with simplebar-react now not scrollable, this issue also happens in #3824 

With mentioned ticket's solution I create a codesandbox but it still not scrollable.
https://codesandbox.io/s/magical-thompson-j80lr

**Comment by Rall3n** [comment]
Possible duplicate or the same problem as in #4028.

Set the value of the prop `captureMenuScroll` to `false` and it should start working.

**Comment by huboo** [comment]
> Possible duplicate or the same problem as in #4028.
> 
> Set the value of the prop `captureMenuScroll` to `false` and it should start working.

Cool it solved the issue. Thank you very much!

**Comment by BhanuSingamsetty** [comment]
Set the value of the prop captureMenuScroll to false and it is working. But on pressing keyboard down arrow scrolling is not going to focused option.
