### ISSUE TITLE
Is there a way to use the dropdown without search?

### ISSUE THREAD

**Issue by yrabinov** [JedWatson/react-select#413]
I would like to know if there's a way disable search but still enable the dropdown.  In particular this is useful on mobile- I want the keyboard NOT to appear when the box is focused, and for the user to choose from options with no search / autocomplete.  

The disabled = true and searchable = false options don't have the desired effect, is there a way to do this?

**Comment by bruderstein** [comment]
Setting `searchable={false}` should do what you're describing, you shouldn't need to set `disabled`.  (Disabled actually disables the whole control, so you can't change the selection at all)

If that doesn't do what you need, can you explain what it does differently than expected/needed?

**Comment by yrabinov** [comment]
This does work, I had dependency issues causing an error, thanks!

**Comment by shubhankar30** [comment]
The prop is now isSearchable in React-select v2 for anybody who is interested. 
So, isSearchable={false} would do it.
