### ISSUE TITLE
adding ValueContainer not allowing to select option

### ISSUE THREAD

**Issue by kishan-tocca** [JedWatson/react-select#4141]
<CreatableSelect
                ref={r => (selectRef = r)}
                value={state.selectedOption}
                components={{ Option, ValueContainer }}
                onChange={handleChange}
                options={state.options}
                isMulti
                getOptionLabel={option => option.label}
                getOptionValue={option => option.value}
                placeholder="Filter by location , name, company name, job title..."
                createOptionPosition="first"
                allowCreateWhileLoading={true}
                onKeyDown={onKeyDown}
                onCreateOption={handleCreate}
                isClearable
                menuIsOpen={state.dropDownOpen}
                onInputChange={handleInputChange}
                onFocus={focused}
                filterOption={createFilter({ ignoreCase: false })}
                styles={customStyles}
                isSearchable={false}
                />
i have added value container , but after that its not allowing to select option and not showing blinker in input field to search and write 

    const customStyles = {
        valueContainer: base => ({
            ...base,
            paddingLeft: 35
        })
    }

    const ValueContainer = ({ children, ...props }) => {
        return (
            components.ValueContainer && (
                <components.ValueContainer {...props}>
                    {/* {!!children && ( */}
                        <img src={searchIcon} alt="search" style={{ position: 'absolute', left: 6 }} />
                    {/* )} */}
                    {children}
                </components.ValueContainer>
            )
        );
    };

    const Option = (props) => {
        return (
            <components.Option {...props}>
                <div>{props.data.label}</div>
                <div style={{ fontSize: 12 }}>{props.data.subLabel}</div>
            </components.Option>
        );
    };

**Comment by striccaa** [comment]
I have the same issue. Console logging {children} shows that the array of react nodes exists, however, for some reason, it doesn't render it as it should when putting it into the DOM.

**Comment by tdigambar-iconnect** [comment]
I am having the same issue with using Select

`<Select
            value= { getSelectedValue(filter, attrSelection) }
            onChange= { onChange }
            options= { filterOptions(filter) }
            components={{
              Option,
              DropdownIndicator,
              IndicatorSeparator,
              ClearIndicator,
              ValueContainer
            }}
            isMulti = { true }
            menuIsOpen = { true }
            className={ `filterList_contents ${filter.name === RATING
              ? 'filterList_contents-rating'
              : `${(filter.attributeValues.length <= MAX_LABELS_SHOW_SHADOW || filterAttrExists)
                ? 'filterList_contents-withoutboxshadow' : ''}`}` }
            controlShouldRenderValue = { false }
            hideSelectedOptions = { false }
            noOptionsMessage = { noOptionsMessage }
            placeholder = { placeholder }
            pageSize = { PAGE_SIZE } // Number of options to jump in menu when page{up|down} keys are used
            maxMenuHeight = { MAX_MENU_HEIGHT }
          />`
I have added ValueContainer as follow:
` const Option = ({ children, ...props }) => {
    return (
      <div className="filterList_contents_option">
        <components.Option { ...props } className="filterList_contents_option_item">
          <Checkbox
            labelValue = { children }
            isSelected = { props.isSelected }
          />
        </components.Option>
      </div>
    );
  };

  const noOptionsMessage = () => NO_OPTION_MESSAGE;

  const ValueContainer = ({ children, ...props }) => (
    <components.ValueContainer { ...props }>{ searchIcon } {children}</components.ValueContainer>
  );

  const DropdownIndicator = () => null;

  const IndicatorSeparator = () => null;

  const ClearIndicator = () => null;
`
after this, it's not allowing me to type into the search input bar

**Comment by ebonow** [comment]
@kishan-tocca 
Setting `isSearchable` to false will prevent the input from being rendered and thus nothing to type into. I can't imagine a scenario where a user would want a creatable select that was not searchable. I recommend removing that prop. 

@striccaa 
I am not able to diagnose an issue without any code.

@tdigambar-iconnect 
I was able to give my best shot at creating a codesandbox with your [code here](https://codesandbox.io/s/adoring-newton-ywzmd?file=/src/App.js)

- It's unclear what kind of things you are doing to your `value`, `options`,  and possibly `onChange` handler, but it seems more complex than necessary.
- Your Option component must either be wrapped in `<component.Option>` or you need to pass the innerRef to the root component `<div ref={props.innerRef} />`. 

After putting up the codesandbox, it seems to work as expected.


I will mark this issue as resolved, but if anyone has further questions or issues I would be happy to answer any concerns and re-open the ticket if necessary.
