### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by Methuselah96** [JedWatson/react-select#4142]
This is an issue to track the progress of converting this project to TypeScript. The plan is to do this incrementally in order to make the transition as smooth as possible and not make the review process too overwhelming. The overall plan is:

1. Incrementally convert `docs` to TypeScript.
  - TypeScript files can import Flow files if they have a corresponding TypeScript declaration file, so we'll just do a breadth-first conversion.
  - Import `react-select` types from `@types/react-select` in this step.
  - Fix types in `@types/react-select` to make it work with `docs`.
  - PRs:
    - Add TypeScript infrastructure (https://github.com/JedWatson/react-select/pull/4139)
    - Convert Webpack config to TypeScript (https://github.com/JedWatson/react-select/pull/4143)
    - Incrementally convert docs to TypeScript (part 1) (https://github.com/JedWatson/react-select/pull/4144)
    - Incrementally convert docs to TypeScript (part 2) (TODO)
    - etc.
2. Move Typescript declaration files from `@types/react-select` to this repository.
3. Incrementally convert main source files to TypeScript.

**Comment by bladey** [comment]
Thank you for all your efforts @Methuselah96, this looks great.

**Comment by Methuselah96** [comment]
@kylemh Thanks for all your help so far on PRs! I saw on https://github.com/JedWatson/react-select/issues/4293 that you're looking to help out with the TS conversion. Most of the work is actually already done (I have the entire code-base converted to TypeScript on [a branch](https://github.com/Methuselah96/react-select/tree/typescript-final), it's just a matter of getting it merged in.

The PRs I've made so far have been to incrementally convert the docs to TypeScript using the types that currently exist on DefinitelyTyped. When I run across a problem in the types, I make a PR to DefinitelyTyped. This works, however it's slow because there are no active reviewers for react-select on DefinitelyTyped. Would be willing to update the types on DefinitelyTyped to 3.1 (by adding [the `isLoading` prop to `AsyncSelect`](https://github.com/JedWatson/react-select/releases/tag/react-select%403.1.0)) and also add yourself as a definition author. That way we can review each others PRs and this process can be sped up quite a bit.

Thanks for all your hard work!

**Comment by kylemh** [comment]
Down; however, [that looks to already be done, no?](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/Async.d.ts#L28)

**Comment by Methuselah96** [comment]
I think that's in the `State`, but not in the `Props`.

**Comment by kylemh** [comment]
`Async` extends `State`. `Async` represents the inferred props on the default export of `/async`:

![Screen Shot 2020-12-15 at 10 36 08 AM](https://user-images.githubusercontent.com/9523719/102257322-7061cd00-3ec1-11eb-8c52-cb9a1f1054b4.png)

**Comment by kylemh** [comment]
I did reference the wrong line of code though. The `AsyncSelect` props extends the "NamedProps" face -> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/Select.d.ts#L215 which has [`isLoading`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2338e34f760b10c7599d22a58ce41295a9d7c286/types/react-select/src/Select.d.ts#L135)

**Comment by Methuselah96** [comment]
Thanks, I see what's going in now. It shouldn't be on the base `Select` props, it should only be on the `Async` props (correct me if I'm worng). Can you make a PR with that change as well as bumping the version number to 3.1?

**Comment by Methuselah96** [comment]
I see now, the PR that added the `isLoading` prop just made it so that it was passed through the `Select` properly. My bad. Can you just make a PR to bump the version number to 3.1 and add yourself as an author? Or you can find an actual change to make; there are quite a few of missing/incorrect types (for example, tightening up [these `styles` types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/styles.d.ts) so they don't pass `any` as the props).

**Comment by kylemh** [comment]
Certainly! My work week is a bit busy, but I'll come back to this at some point next week at the worst.

**Comment by Methuselah96** [comment]
No worries, I can relate. Just whenever you find the time.

**Comment by kylemh** [comment]
I'll make changes to the `styles` type you mentioned by EOD tomorrow. By "bump the version to 3.1", you mean for: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/index.d.ts#L1

Additionally, did we want to upgrade the minimum required version of TS to expand what we can use?

**Comment by Methuselah96** [comment]
Yeah, you got it. And don't forget to add yourself as a [definition owner](https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners) as well.

Regarding the minimum required version: Can you just remove the [`TypeScript version 2.9`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/index.d.ts#L10) that currently exists? DefinitelyTyped by default [sets the minimum version](https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-31-and-earlier) to any TypeScript version less than 2 years old, which is 3.3 right now. I'd like to try to stick with that default minimum version if possible unless there's a compelling reason why we need to use newer versions.

**Comment by kylemh** [comment]
TIL! On it.

**Comment by kylemh** [comment]
I'd like follow up with a PR after this one which simply adjusts comments ([like these](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/Select.d.ts#L56)) to JS Doc comments. It seems so minor, but VS Code users will begin to see intellisense and - cooler still - tools like `react-docgen-typescript` can parse JS Doc comments into markdown for tools like Storybook.
