### ISSUE TITLE
Add or clear current input value on blur and allow auto select on tab (for new values)

### ISSUE THREAD

**Issue by akum32** [JedWatson/react-select#415]
When new values are allowed:
1. On blur, add the current input value, so when the user clicks away, it will be automatically added.
2. On tab key press, add the current input value.

When new values are NOT allowed:
1. On blur, clear the current input value.

**Comment by CoreyTrombley** [comment]
:+1: for this to be added please.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
