### ISSUE TITLE
React select async dropdown is behind dialog / modal.

### ISSUE THREAD

**Issue by manualva7** [JedWatson/react-select#4150]
I can't seem to find a way to edit the parent (wrapper) for react-select. Its index is currently 1. I need to change it to 9991 (Dialog's index is at 999)

classNamePrefix and adding css doesn't work.

`menuContainerStyle={{zIndex: 9991}} `

doesn't work.

```
menu: styles => ({
        ...styles,
        backgroundColor: 'rgba(25,25,25,1)',
        marginTop: 0,
        zIndex: 9991
    }),
```

doesn't work either.

In element:

`<div class="css-ehwxqd"><div class=" css-16ettw9-menu"><div class=" css-4ljt47-MenuList"><div class=" css-16za5a0-NoOptionsMessage"><span class="MuiTypography-root MuiTypography-caption">Enter 3 or more letters</span></div></div></div></div>`

div with class css-ehwxqd has z-index 1. This class is apparently dynamic and can't be targeted so easily.

I don't want to resort to hacky code. Any help is greatly appreciated.

**Comment by manualva7** [comment]
The issue was in 
`menuPortalTarget={document.querySelector('body')}`

It shouldn't reside in body if it's in dialog.

So I've added a condition that only displays inside dialog if prop dialog is true.
`menuPortalTarget={inDialog ? document.querySelector('.MuiDialog-root') : document.querySelector('body')}`

No need to change or add css.

**Comment by Rall3n** [comment]
@manualva7 If your problem is resolved, then please mark this issue as closed.

**Comment by kkomelin** [comment]
The same problem here but the suggested solution is not clear to me.

**Comment by Asif-Saheer-k** [comment]
<AsyncSelect
        cacheOptions
        loadOptions={value ? setItems : setItems}
        defaultOptions
        isSelected={true}
        isClearable={isClearable}
        getOptionLabel={getOptionLabel}
        isOptionSelected={item => item.value === value}
        name={value ? value : 'stock'}
        value={value ? optionsArray.find(item => item.value === value) : value}
        placeholder=""
        onChange={handleFieldChange}
        className={`w-100  ${
          error ? ' form-control ps-0 py-0 is-invalid' : ''
        }`}
        styles={{
          menuPortal: provided => ({ ...provided, zIndex: 9999 }),
          menu: provided => ({
            ...provided,
            zIndex: 9999,
            fontFamily: 'sans-serif',
            fontSize: '12px',
            borderRadius: '0px',
            textTransform: 'capitalize',
            overflow: 'hidden'
          }),
          control: (base, state) => ({
            ...base,
            boxShadow: state.isFocused ? 0 : 0,
            borderRadius: '0px',
            border: '1px solid #b5b5b5',
            height: '10px'
          })
        }}
        menuPortalTarget={document.body}

      />
        menuPortalTarget={document.body}
        screen widthe less that 1500 showing this error
        |ResizeObserver loop completed with undelivered notifications.
    at handleError (http://asif.axisproerp.com:3001/static/js/bundle.js:889737:58)
    at http://asif.axisproerp.com:3001/static/js/bundle.js:889756:7\

**Comment by ankitpanchal534** [comment]
`menuPortal: (provided) => ({
            ...provided,
            zIndex: 9999,
            pointerEvents: 'all',
          }),`
          
   i was not able to scroll or select any option, it worked by adding "pointerEvents":"all" for me .

**Comment by rafaelcorreadev1** [comment]
> `menuPortal: (provided) => ({ ...provided, zIndex: 9999, pointerEvents: 'all', }), ` i was not able to scroll or select any option, it worked by adding "pointerEvents":"all" for me .

thanks man, it worked for me!!! was going crazy!!!
