### ISSUE TITLE
Custom styles supplied to the "styles" prop is not working.

### ISSUE THREAD

**Issue by Finale100** [JedWatson/react-select#4156]
When I pass in a custom styles object to the "styles" prop, the "input" styles don't get applied to the input element, the styles will be applied to the parent div.

Ex. 
`export const custom = {
  option: (provided, state) => ({
    ...provided,
    margin: "0px 0px 0px 0px",
    width: "100%"
  }),
  container: (provided) => ({
    ...provided,
    width: "50%"
  }),
  indicatorsContainer: (provided) => ({
    ...provided,
    display: "none"
  }),
  input: (provided, state) => ({
    width: "100px",
    border: "none",
    margin: "0px 0px 0px 0px",
    "marginBottom": "0px"
  }),
  menu: (provided) => ({ // styles for menu container
    ...provided,
    margin: " 0px 0px 0px 0px",
    width: "100%"
  }),
  valueContainer: (provided) => ({ // styles for menu container
    ...provided,
    "borderRadius": "3px",
    "boxShadow": "inset 0 1px 3px 0 rgba(0,0,0,.5)",
    border: "1px solid #979797"
  })
};`

<img width="1529" alt="Screen Shot 2020-08-04 at 2 46 11 PM" src="https://user-images.githubusercontent.com/38744967/89332418-5b4a7700-d661-11ea-85a2-e5716624d204.png">

Any recommendations would be recommended.

**Comment by ebonow** [comment]
Greetings @Finale100 ,

That is correct that the input styles are applied to the container of the input and not the input itself. This is something that can be accomplished by adding an `input` css selector like you would in css, but with styled components. 

``` JS
const styles = {
  input: (provided, state) => ({
    ...provided,
    'input': { 
      width: "100px !important", 
      border: "none", 
      margin: "0px 0px 0px 0px"
    }
})
```

Here you can see that the input is nested inside the input component styling (which as already stated refers to the Input container styling). Also notice that some of the input styling is injected directly into the style, so `!important` tags might be. necessary for some of the overrides.

[Here is a provided sandbox to see a live example. 
](https://codesandbox.io/s/react-select-input-style-6m6jr?file=/src/App.js)
Please feel free to reply if you have any questions.
