### ISSUE TITLE
After selecting an option from the menu the whole options menu is blue instead of the selected option

### ISSUE THREAD

**Issue by Finale100** [JedWatson/react-select#4157]
Like the title says, after I select an option, the whole options menu turns blue instead of just the option that was selected. I am also using the Select somewhere else in my app and it doesn't do it. I'm also using the same styles.

**Comment by Finale100** [comment]
looks when you pass in the array for "options" prop. Each object need to have a value key or else it wont know which option you have selected.

**Comment by DiegoBittencourtOfficial** [comment]
Sup Finale100! I'm having this exactly same problem. I'm currently using a function that returns a array containg the options, as follow:

```export function schoolingOptions() {
    return [
        { key: 0, label: 'Educação infantil' },
        { key: 1, label: 'Ensino fundamental' },
        { key: 2, label: 'Ensino médio' },
        { key: 3, label: 'Ensino técnico' },
        { key: 4, label: 'Ensino superior' },
        { key: 5, label: 'Pós-graduação' },
        { key: 6, label: 'Mestrado' },
        { key: 7, label: 'Doutorado' },
    ];
};```

As you can see there's a field called "key", also a different value for each one... still all options turn to blue after one is selected... so, any idea on how to fix this problem? Something I did wrong maybe?

**Comment by guifavere** [comment]
You can use the prop: **isOptionSelected**, and pass a function that identify the selected option.

**Example:**

`const selectedOption = 2;`
`const options = [{ key: 1, label: 'option 1' }, { key: 2, label: 'option 2'}];`

`const isOptionSelected = option => option.key === selectedOption`

`<AsyncSelect {...props} isOptionSelected={isOptionSelected}/>`

**Comment by MaxChu23** [comment]
Having `value` in each option instead of `id` or `key` helped me! 🎉
