### ISSUE TITLE
Official documentation's groupedOptions doesn't work in async select

### ISSUE THREAD

**Issue by alvamanu** [JedWatson/react-select#4164]
I forked an example posted here:
https://react-select.com/async#loading-asynchronously

then changed colourOptions to groupedOptions in the sandbox. Here it is: 
https://codesandbox.io/s/s581m?module=/example&file=/example.js

Type in 'v' you'll get the 'v' from FLAVOURS. Type in 'Vanilla', you'll get nothing.

I kept playing around with this issue and I got to a point where I did manage to console log correct results, however they're not being rendered.

Here's the sandbox:

https://codesandbox.io/s/distracted-golick-nu554?file=/example.js

**Comment by bladey** [comment]
Thanks for the report @mantissa7, we'll look at this as soon as we can.

**Comment by ebonow** [comment]
Greetings @alvamanu ,

Neither of the example sandboxes you linked to are using the grouped options (though the second includes an unused reference). It also makes sense that if you left the filtering as is, it would filter based on the `label` of each option, which in the case of the group options, is the group heading. 

If you wanted to filter the options within the group, would you have to filter through the `options` of each group and not the group label such that:
```js 
const query = inputValue.toLowerCase();

groupedOptions.map(group => {
  const { label, options } = group;
  const filteredGroupOptions = options.filter(option => option.label.toLowerCase().includes(query));
  return { 
    label, 
    options: filteredGroupOptions
  }
});
```

From that point you could go one step further and even filter out groups that have no options, but again you wouldn't be able to rely on the same filter logic for a group as you would for standard options.

Happy to revisit this with you if you have another sandbox demonstrating the behavior you were describing or if the explanation doesn't make sense or work. In the meanwhile I'll close this to help us tidy up, but again please feel free to follow up if there is a misunderstanding.
