### ISSUE TITLE
Red warnings: Using UNSAFE_componentWillReceiveProps, 

### ISSUE THREAD

**Issue by ndrean** [JedWatson/react-select#4165]
### Thanks for using react-select!

Before creating an issue...

# Are you reporting a bug or runtime error?
I have the following errors (code in using StrictMode)

- Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. ...Please update the following components: AutosizeInput, Select
- findDOMNode is deprecated in StrictMode
- Legacy context API has been detected within a strict-mode tree. The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
Please update the following components: MenuPlacer...

Please include a test case that demonstrates the issue you're reporting!
Coming soon
This is very helpful to maintainers in order to help us see the issue you're seeing.

Please note we are currently only directing our efforts towards the current major (v3) version and beyond.

We understand this might be inconvenient but it is in the best interest of supporting the broader community and to sustain the `react-select` project going forward.

To report bugs against react-select v3 please fork the following code-sandbox:
https://codesandbox.io/s/react-select-v3-sandbox-jgdch

To report bugs against react-select v2 please fork the following code-sandbox:
https://codesandbox.io/s/k5rvn9z3lv

To report bugs against react-select v1 please fork the following code-sandbox:
https://codesandbox.io/s/n34mq0743j

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

# Are you making a feature request?
Provide as much information as possible about your requested feature. Here are a few questions you may consider answering:

*   What's your use case? (Tell us about your application and what problem you're trying to solve.)
*   What interface do you have in mind? (What new properties or methods do you think might be helpful?)
*   Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

**Comment by Methuselah96** [comment]
@ndrean There's already an issue for this: https://github.com/JedWatson/react-select/issues/4094.

**Comment by bladey** [comment]
Closing as duplicate, please see #4094 as mentioned by @Methuselah96.
