### ISSUE TITLE
Add clearValue to async select

### ISSUE THREAD

**Issue by tomer-amir** [JedWatson/react-select#4167]
I am trying to do something like in #3906 but it seems that `clearValue` is not available when using the Async Select:
https://codesandbox.io/s/react-select-clear-value-forked-btqug?file=/example.js

![image](https://user-images.githubusercontent.com/63953532/90749405-161e7a00-e2dc-11ea-8fb3-85ac71f3461c.png)

**Comment by tomer-amir** [comment]
Found the issue...
When working with the async select, instead of doing:
```js
selectRef.select.clearValue();
```
I had to use:
```js
selectRef.select.select.clearValue();
```

That solved the issue: https://codesandbox.io/s/react-select-clear-value-forked-btqug?file=/example.js:247-284

**Comment by bladey** [comment]
Thanks for the question and coming back to answer it @tomer-amir, good suggestion for the docs!

**Comment by tomer-amir** [comment]
BTW, for `async-creatable` it's:

`this.selectRef.select.select.select.clearValue()`

![image](https://user-images.githubusercontent.com/63953532/91024707-fd2a0780-e600-11ea-9944-7689617e00b9.png)

**Comment by bladey** [comment]
:P
