### ISSUE TITLE
add button in select

### ISSUE THREAD

**Issue by MohsenEs** [JedWatson/react-select#4169]
How can I create a button plus?
![d](https://user-images.githubusercontent.com/46873097/90798698-84d4f500-e327-11ea-97db-178e103b627c.jpg)

**Comment by ebonow** [comment]
Greetings again,

What have you tried so far? I would suspect that you would want to write a custom ValueContainer
```
const ValueContainer = ({ children, ...props }) => (
    <components.ValueContainer {...props}>
        <button>+</button>
        { children }
    </components.ValueContainer>
)
```

If you flex the valueContainer and set the `flex` of the button component to `0 0 0`, the two should be in line with each other.

Let me know if this resolves your issue.

**Comment by MohsenEs** [comment]
tank 
but style what?
https://codesandbox.io/s/nice-goodall-3ykf2?file=/src/App.js

**Comment by ebonow** [comment]
The singleValue has position absolute, so you could add left style to it.

**Comment by MohsenEs** [comment]
You can explain in the example above

**Comment by ebonow** [comment]
You want to add style and react-select has [several ways of doing this](https://react-select.com/styles).

The selected value (singleValue component) overlaps the button so add left position.

```
const styles = {
  singleValue: inlineCss => ({ 
    /* component style functions provides existing inline css styles, which we return and overwrite/add other values */
    ...inlineCss,
   /* move singleValue text to right of the plus button*/
   left: '1.5rem'
});

<Select styles={styles} ... />
```

**Comment by bladey** [comment]
Thanks again for your help @ebonow.

@MohsenEs please reopen this issue if you still need assistance.

**Comment by MohsenEs** [comment]
hi
