### ISSUE TITLE
Css is missing

### ISSUE THREAD

**Issue by anilapu** [JedWatson/react-select#417]
When I include react-select in my project, It was working fine but style was not applied properly.
Am I missing to add anything?

**Comment by koelpinl** [comment]
Did you include the node_modules/react-select/dist/default.css?
It's working fine for me.

**Comment by anilapu** [comment]
I will include @koelpinl

**Comment by anilapu** [comment]
@koelpinl - when I tried I got `Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:3000/node_modules/react-select/less/default.less".`

**Comment by brianreavis** [comment]
@anilapu You should be including the CSS ([here](https://github.com/JedWatson/react-select/blob/master/dist/default.css)), not the LESS. Questions like these are more suited for [StackOverflow](http://stackoverflow.com/). As the library grows in popularity, it just gets too hard for project maintainers to tend to debugging of people's projects
