### ISSUE TITLE
using custom components when isMulti and !closeMenuOnSelect click outside do not close menu

### ISSUE THREAD

**Issue by taylorstyers** [JedWatson/react-select#4170]
### Summary
I'm using `react-select` version 3.1.0.  When I use a custom `ValueContainer` and `closeMenuOnSelect={false}`, the menu doesn't close when you click outside the menu.

![2020-08-20 11 35 19](https://user-images.githubusercontent.com/13973402/90800178-e8d0cc80-e2d9-11ea-81f2-0deb9b80c3a1.gif)

### Details
When I first open the menu and click away, the menu closes.  After I select items and click away, the menu doesn't close.  If I then unselect items, the menu still doesn't close when I click away.  I checked out [issue 2810 from v2](https://github.com/JedWatson/react-select/issues/2810), but I am defining the custom component outside of the render and it doesn't solve the problem.

### Code
```
const ValueContainer = ({ children, ...props }) => {
  const { getValue, hasValue, isMulti, selectProps: { placeholder } } = props;
  const numberOfValues = getValue().length;
  if (!hasValue || !isMulti) {
    return (
      <components.ValueContainer {...props}>
        {children}
      </components.ValueContainer>
    );
  }
  return (
    <components.ValueContainer {...props}>
      {`${numberOfValues} ${placeholder}`}
    </components.ValueContainer>
  );
};

const Select = (props) => {
  return (
    <span>
      <ReactSelect
        {...props}
        components={{
          ValueContainer
        }}
        closeMenuOnSelect={true}
        isMulti={true}
      />
    </span>
  );
};

```

**Comment by taylorstyers** [comment]
Looks like it's working as expected now.  I must have tweaked something that got it working ¯\_(ツ)_/¯

**Comment by chkal** [comment]
We are running in exactly the same problem. Any chance that you share you latest code?

**Comment by taylorstyers** [comment]
@chkal I'm really not sure what changed, but I hope this helps!  I confirmed that it's still working.

```
const Select = (props) => {
  const { isMulti, options, placeholder, onMenuClose, isClearable, value, getOptionLabel, getOptionValue, onChange } = props;
  return (
    <span>
      <ReactSelect
        options={options}
        placeholder={placeholder}
        isMulti={isMulti}
        onMenuClose={onMenuClose}
        isClearable={isClearable}
        value={value}
        getOptionValue={getOptionValue}
        getOptionLabel={getOptionLabel}
        onChange={onChange}
        components={{
          ValueContainer,
          Option,
        }}
        closeMenuOnSelect={!isMulti}
        hideSelectedOptions={!isMulti}
        styles={styles}
        {...props}
      />
    </span>
  );
};
```
Value container:
```
const ValueContainer = ({ children, ...props }) => {
  const { getValue, hasValue, isMulti, selectProps: { placeholder, inputValue } } = props;
  const numberOfValues = getValue().length;
  if (!hasValue || !isMulti) {
    return (
      <components.ValueContainer {...props}>
        {children}
      </components.ValueContainer>
    );
  }
  return (
    <components.ValueContainer {...props}>
      {
        !inputValue &&
        <components.Placeholder {...props}>{`${numberOfValues} ${placeholder}`}</components.Placeholder>
      }
      {children[1]}
    </components.ValueContainer>
  );
};
```

**Comment by chkal** [comment]
@chkal Thanks a lot for sharing your code.

In the meantime we also fixed the issue by adding `{children[1]}` as the last child of `<components.ValueContaine>`.

Thanks a lot! :beers:

**Comment by taylorstyers** [comment]
@mohuace I posted my [updated code above](https://github.com/JedWatson/react-select/issues/4170#issuecomment-682451932), which is still working.  Plus @chkal said how they fixed it.  ¯\_(ツ)_/¯

**Comment by mohuace** [comment]
Hey, could you guys have a look at this once [https://codesandbox.io/s/react-codesandboxer-example-forked-0kykq?file=/example.js] 
Inside handleChange function, I have implemented the logic for the dropdown...having a single select functionality for one of the groups and a multiselect for other groups. I have also added the component Control which is written to provide a tooltip functionality to the dropdown. 
In this scenario, I am facing the same issue i.e. when I click outside the dropdown, it doesn't collapse. But when I remove the handleChange function all together, the dropdown seems to be working fine. 
Any thoughts on this? 
Appreciate your help!

**Comment by chkal** [comment]
I experimented a bit with your sample. Just move your custom components out of the `App` component. This should fix this issue.

https://codesandbox.io/s/react-codesandboxer-example-forked-m05z9?file=/example.js

Not completely sure why this happens. But if you declare the custom components inside another component, you will get new components on each render, which is most likely a bad idea. :-)

**Comment by mohuace** [comment]
Ohh, I see. Thanks a lot @chkal , this was really helpful!

**Comment by Dror-Bar** [comment]
That requirement to add {children[1]} was so tricky to find. Is it even documented?

**Comment by chkal** [comment]
@Dror-Bar I don't think that this is part of the "public API" to be honest.

**Comment by Dror-Bar** [comment]
@chkal Sorry, perhaps you could help with something.
I noticed when I use ValueContainer, clicking outside the dropdown menu no longer closes the menu. Did you encounter this, or have any idea how to solve it?

**Comment by Endeavor42** [comment]
> I experimented a bit with your sample. Just move your custom components out of the `App` component. This should fix this issue.
> 
> https://codesandbox.io/s/react-codesandboxer-example-forked-m05z9?file=/example.js
> 
> Not completely sure why this happens. But if you declare the custom components inside another component, you will get new components on each render, which is most likely a bad idea. :-)

You can't create a functional component within another functional component.

You can check this 2-minute article that explains why:
https://dev.to/borasvm/react-create-component-inside-a-component-456b#:~:text=So%20the%20take%20away%20%2D%20NEVER,COMPONENT%20INSIDE%20ANOTHER%20FUNCTION%20COMPONENT.&text=Functions%20are%20not%20part%20of,called%20when%20component%20re%2Drender.

**Comment by ebonow** [comment]
This has come up in several times and is an easy mistake to make, and thought it might be worth mentioning that the following section was added to the documentation as part of the v3.2 release.

https://react-select.com/components#defining-components

**Comment by faizantroon** [comment]
Today i have come across with this issue and i resolved it by moving my custom components outside of React functional component, Basically you can't define functional component within another functional component because it cause re renders and it will not close the dropdown
