### ISSUE TITLE
Can't provide style for `indicatorContainer`

### ISSUE THREAD

**Issue by smeijer** [JedWatson/react-select#4173]
I can't provide a style for `indicatorContainer`, (not to be confused with `indicatorsContainer`)

The element is also not listed under [styles](https://react-select.com/styles#style-object) as being stylable, but it does contain styles (like `padding` and `color`), which I'm now unable to override.

```jsx
const styles = {
  // this one works
  indicatorsContainer: (provided) => ({
    ...provided,
    color: 'red',
  }),

  // THIS IS THE BUGGING ONE
  indicatorContainer: (provided) => ({
    ...provided,
    color: 'blue',
  }),
};

<Select styles={styles} />
```

![image](https://user-images.githubusercontent.com/1196524/90953735-6a596380-e46e-11ea-8ce9-98731ed419e8.png)

**Comment by chalas-ch** [comment]
Hello, I second this, I'm having the same problem.
Is this style it completely inaccessible ?

**Comment by smeijer** [comment]
@chalas-ch, as a workaround I'm currently overriding the `DropdownIndicator` component. It's not as easy as providing the style, but it's something.

```js
import Select, { components as SelectComponents } from 'react-select';

const components = {
  DropdownIndicator: (props) => (
    <SelectComponents.DropdownIndicator {...props}>
      <Chevron style={ myStyles } />
    </SelectComponents.DropdownIndicator>
  ),
};

<Select components={components} />
```

**Comment by codeReader52** [comment]
@smeijer Apologies in advance if I didn't fully understand/mis-understand your issue. I thought that there is something called `dropdownIndicator` in the css styles - I think that in fact will set the CSS in the "indicatorContainer" shown in devtool?  That should I don't think there has ever been an `indicatorContainer`. 
Code sandbox: https://codesandbox.io/s/dropdown-indicator-css-tissk?file=/example.js
![image](https://user-images.githubusercontent.com/50291496/91196118-159f3c80-e73d-11ea-94da-382b90df1e16.png)

**Comment by smeijer** [comment]
Thanks, @codeReader52! Looks like you're right. I guess the change in naming convention threw me off.

This works just fine:

```jsx
<Select
  styles={{
    dropdownIndicator: (provided) => ({
      ...provided,
      color: 'red',
      ':hover': {
        color: "yellow",
      },
    }),
  }}
/>
```

**Comment by PQALAB** [comment]
Y'all really tricked me with this one as well, glad I looked this up

**Comment by karltaylor** [comment]
Ya I was a bit stumped on this oen too, shouldn't it keep consistency? I didn't think it was possible to override style due to the difference in naming?

**Comment by acdvs** [comment]
A change needs to be made in the code and docs for this. Everything points to the `containersIndicator` being the key to overriding this element right now. There's a huge inconsistency.

**Comment by cjadhav** [comment]
Facing same issue, I wanted to adjust the spaceing of "indicatorContainer" not the "indicatorsContainer".
Only "indicatorsContainer" style is customisable.
I am using latest v.5.6.0.

**Comment by ParisRio** [comment]
> Facing same issue, I wanted to adjust the spaceing of "indicatorContainer" not the "indicatorsContainer". Only "indicatorsContainer" style is customisable. I am using latest v.5.6.0.

It is accessible through 'dropdownIndicator' even if the css naming convention refers it as 'indicatorContainer'.
