### ISSUE TITLE
Error with searching value in options

### ISSUE THREAD

**Issue by chandra10207** [JedWatson/react-select#4174]
## Error while searching a value in options

For eg. 

If my options contain the label "Red face and eyes". while searching on the field,  if user type "red face", an option with "Red face and eyes" appears. However, If the user input is "red eyes" then it shows no options.

Is there any option to search options by word or similar solution for my case?

My Code is,

```
const options = [
  { value: '0', label: 'Red face and eyes' },
  { value: '1', label: 'Dark red nose and lips' },
]

<Select
          name="symptoms-search"
          placeholder="Click here to search"
          value={this.state.query}
          components={animatedComponents}
          options={options}
          onChange={this.handleMultiChange}
          isMulti
          isSearchable
        />
```

Thank you.

**Comment by ebonow** [comment]
Greetings, 

This [page](https://react-select.com/advanced#custom-filter-logic) explains a bit more about the `filterOption` prop and `createFilter` method, but here would be a crude implementation to get you started.

```
  const filterOption = (option, input='') => {
    const label = option.label.toLowerCase();
    return input.toLowerCase().split().every(word => label.includes(word));
  }

<Select filterOptions={filterOption} ... />
```

Let me know if this helps and please close this issue if it does.

**Comment by chandra10207** [comment]
HI @ebonow,
I tried but still not working.

**Comment by chandra10207** [comment]
Thanks guys.

This works for me.

https://github.com/JedWatson/react-select/issues/3067
