### ISSUE TITLE
Minor flow issue in 3.1.0 update

### ISSUE THREAD

**Issue by vikalp-sajwan** [JedWatson/react-select#4176]
First and foremost, thanks to all the people who are involved in this awesome project.

### Are you reporting a bug or runtime error?
Setup up issue.
This is a flow error issue when using Async Select component. This was introduced in https://github.com/JedWatson/react-select/pull/3690 with changes in `isLoading` prop.
Can't reproduce in sandbox as this is related to setup.

### Reproduction steps 
- clone https://github.com/vikalp-sajwan/react-select
- run `yarn flow check`

The reproduction code is just the fork of this repository with a single component file using the Async Select.
https://github.com/vikalp-sajwan/react-select/blob/master/packages/react-select/src/Async-flow-test-component.js

### Issue

```
➜  react-select git:(flow-issue) ✗ yarn flow check
yarn run v1.22.4
$ /home/code/react-select/node_modules/.bin/flow check
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-select/src/Async-flow-test-component.js:38:10

Cannot create AsyncSelect element because undefined [1] is incompatible with boolean [2] in property isLoading.

     packages/react-select/src/Async-flow-test-component.js
      35│     return (
      36│       <div>
      37│         <pre>inputValue: "{this.state.inputValue}"</pre>
      38│         <AsyncSelect
      39│           cacheOptions
      40│           loadOptions={loadOptions}
      41│           defaultOptions
      42│           onInputChange={() => this.handleInputChange('green')}
      43│           isLoading
      44│         />
      45│       </div>
      46│     );
      47│   }

     packages/react-select/src/Async.js
 [2]  34│   isLoading: boolean,

     packages/react-select/src/Select.js
 [1] 160│   isLoading: boolean,



Found 1 error
```
### Issue Cause
Not sure, but seems the `defaultProps` value defined in Select.js is making it interpret as optional prop, which in turn means it could be `undefined`, causing the issue.

### Possible Solution
Making the isLoading prop optional is fixing the issue.

# Are you making a feature request?
No

**Comment by ebonow** [comment]
Greetings @vikalp-sajwan,

The issue you are experiencing has nothing to do with the Flow types but rather you have not declared `isLoading` [anywhere within the scope of your application](https://github.com/vikalp-sajwan/react-select/blob/master/packages/react-select/src/Async-flow-test-component.js) so it is quite literally not defined by the developer. Perhaps you meant to destructure it from props, but this does not appear to be issue with library so I will mark this as closed.

If you have any further questions or concerns, please feel free to reply and we can discuss further or re-open if necessary.

**Comment by ebonow** [comment]
@Methuselah96 can you confirm if this is still an issue or not. I tested this in master and wasn't able to replicate. It seems you had been discussing this issue in another [thread](https://github.com/JedWatson/react-select/issues/4142#issuecomment-745308689) so wanted to verify.

**Comment by Methuselah96** [comment]
Yeah, not sure, but the Flow types should no longer be relevant with the conversion to TypeScript (https://github.com/JedWatson/react-select/pull/4489).
