### ISSUE TITLE
Hide selected item in dropdown menu

### ISSUE THREAD

**Issue by AliaaHazizan** [JedWatson/react-select#4177]
Hi guys, please show me on how to hide the selected item from displaying in drop down menu list. Below is my current code. 

For example, if I select "A" from dropdown, and when i want to reselect it, "A" should not be displayed from the list.

import React, {useState} from 'react';
import {View, StyleSheet} from 'react-native';
import DropDownPicker from 'react-native-dropdown-picker';
import {Colors} from '../styles';

const Drop = () => {
  const [selectedValue, setSelectedValue] = useState(' ');

  return (
    <View style={{marginHorizontal: 40}}>
      <DropDownPicker
        items={[
          {label: 'A', value: '1'},
          {label: 'B', value: '2'},
          {label: 'C', value: '3'},
        ]}
        placeholder="Select an account"
        containerStyle={{height: 40}}
        style={styles.dropDownStyle}
        dropDownStyle={styles.dropDownStyle}
        //activeItemStyle={{color: 'red'}}
        itemStyle={styles.itemStyle}
        onChangeItem={(item) => {
          setSelectedValue(item.value);
        }}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  dropDownPickerStyle: {
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.whiteTwo,
  },
  dropDownStyle: {
    backgroundColor: Colors.white,
  },
  itemStyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
});

export default Drop;

![image](https://user-images.githubusercontent.com/61171898/91097868-0d8ac280-e693-11ea-869d-acdda1471be3.png)

**Comment by ebonow** [comment]
Greetings,

Have you tried the prop `hideSelectedOptions`?

If that doesn't work for you, I'd suggest updating the options you are providing the Select.

```
const items = [
  {label: 'A', value: '1'},
  {label: 'B', value: '2'},
  {label: 'C', value: '3'},
].filter(x => x.value !== selectedValue);

<DropDownPicker
  items={items}
  ...
/>
```

**Comment by AliaaHazizan** [comment]
thank you so much! Issue resolved!



![image](https://user-images.githubusercontent.com/61171898/91120381-1ea1f680-e6c8-11ea-9449-94eb866f7c3c.png)
