### ISSUE TITLE
Getting issue in all files of react-select

### ISSUE THREAD

**Issue by manisha-seclogic** [JedWatson/react-select#4179]
node_modules\react-select\src\theme.js: Unexpected token (3:12)

  1 | // @flow
  2 | 
> 3 | import type { Theme } from './types';
    |             ^
  4 | 
  5 | export const colors = {
  6 |   primary: '#2684FF',

**Comment by Methuselah96** [comment]
Are you importing from `react-select/src` by mistake?

**Comment by manisha-seclogic** [comment]
> Are you importing from `react-select/src` by mistake?

Yes the issue was this only 
Thank you

**Comment by hesamZandian** [comment]
I have this same issue and import react-select like this:
import Select from 'react-select'
but still not working for me.

**Comment by Methuselah96** [comment]
@hesamZandian Can you post the exact error message?

**Comment by AlekseiBobrov** [comment]
Hi, i have the same error:
ERROR in ./node_modules/react-select/src/theme.js 3:12
Module parse failed: Unexpected token (3:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // @flow
|
> import type { Theme } from './types';
|
| export const colors = {

It happens in 3 and 4 versions of react-select
