### ISSUE TITLE
focus() method fails when called (stored in redux)

### ISSUE THREAD

**Issue by dancherb** [JedWatson/react-select#4180]
In my Dropdown component, I run

```
componentDidMount = () => {
     this.props.set("focusDropdown", this.dropdownRef.focus)
}
```

This stores `focusDropdown` in redux (in `s.var.focusDropdown`).

In another component, I retreive `focusDropdown` with `mapStateToProps`. I then call `this.props.focusDropdown()`.

I get the following error - seems to be related to how `this` is passed through.

```
Cannot read property 'select' of undefined

focus
C:/xxx/node_modules/react-select/dist/chunk-b36baf1a.browser.esm.js:86
  83 | _createClass(StateManager, [{
  84 |   key: "focus",
  85 |   value: function focus() {
> 86 |     this.select.focus();
     | ^  87 |   }
  88 | }, {
  89 |   key: "blur",
```

Maybe it's weird to store ref methods in redux, but it's worked well for me so far in many situations. Thanks!

**Comment by Dakkers** [comment]
did you try something like:

```
this.props.set("focusDropdown", () => this.dropdownRef.focus())
```

**Comment by ebonow** [comment]
@dancherb we will be closing this ticket due to inactivity. You may follow up if you like, and we can re-open the ticket if necessary.
