### ISSUE TITLE
Test react-select cannot trigger selection event

### ISSUE THREAD

**Issue by gsstar9028** [JedWatson/react-select#4181]
Created a wrapper component (MultiSelect) that essentially returns a ReactSelect from react-select. Using React Testing Library to test it, I could trigger a focus event on the option I am selecting but couldn't trigger a selection. 

codesandbox: https://codesandbox.io/s/react-select-test-ni125?file=/src/__tests__/WrappedSelect.test.js:137-141

**Comment by gsstar9028** [comment]
> Created a wrapper component (MultiSelect) that essentially returns a . Using React Testing Library to test it, I could trigger a focus event on the option I am selecting but couldn't trigger a selection.
> 
> `test('renders a MultiSelect with placeholder correctly and is selectable', () => { const func = jest.fn(); const value = "option0"; const options = ["option0", "option1"]; let event; const { getByRole, getByLabelText, getByText, container, getByTextId } = render(<div onKeyDown={_event => { event = _event; event.persist(); }}> <MutiSelect value={value} onChange={option => func} options={options.map(option => ({ value: option, label: option, }))} isSearchable={true} isMulti={true} placeholder="Select option(s)" /></div>); getByRole('textbox', {id: "react-select-2-input"}); screen.getByText("Select option(s)"); // shows options once opened menu fireEvent.focus(getByRole('textbox')); fireEvent.mouseDown(getByRole('textbox')); screen.getByText("Select All"); const option0 = screen.getByText("option0"); const option1 = screen.getByText("option1"); fireEvent.keyDown(getByRole('textbox'), {key: 'ArrowDown', keyCode: 40}); // focused on 'option0' successfully **fireEvent.keyDown(getByRole('textbox'), { key: 'Enter', code: 'Enter' }); // does not trigger selection event?!** **expect(func).toHaveBeenCalledTimes(1); // FAIL**`

**Comment by ebonow** [comment]
Greetings, 

I'd be happy to help and work through it. Would you be so kind as to set up a codesandbox with the test cases so that it would be easier to work through?

**Comment by gsstar9028** [comment]
sandbox: https://codesandbox.io/s/react-select-test-ni125?file=/src/__tests__/WrappedSelect.test.js:137-141
not sure why its complaining about 'identifier 'test' already declared' though

**Comment by sabinasiddiqi** [comment]
+1

**Comment by singleseeker** [comment]
+1

**Comment by singleseeker** [comment]
@ebonow show time~!

**Comment by GeniaT** [comment]
That issue is also happening on <Select /> if I am not mistaken. I can assert the dropdown is opened on ArrowDown but can't select an option from it.

**Comment by ebonow** [comment]
Just wanted to follow up.

I have had an opportunity since first replying to this to view and add more tests to the react-select library,  but seem to be running into some issues with this implementation for some reason. 

There are plenty of examples here:
https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/__tests__/Select.test.js
which may help. I'll continue to keep looking at this and trying to figure out why this particular implementation isn't compiling or working with the provided example.

**Comment by dcousens** [comment]
Marking this as stale for now, please open a pull request if you have a resolution to the problem experienced.  Otherwise, a new issue if the problem comes back.
