### ISSUE TITLE
Prevent dropdown being closed in certain conditions (e.g. while modal open) - menuIsOpen not suitable

### ISSUE THREAD

**Issue by dancherb** [JedWatson/react-select#4182]
I've added a button within the dropdown in my Select component that opens a modal. However, the first time they click anywhere with this modal open, the dropdown closes by default.

I can set `menuIsOpen={modalOpen} ` on Select to keep the dropdown open while the modal is open. However - the dropdown still registers any clicks that happened while the modal is open, which "should have" closed the dropdown. So as soon as the modal is closed and menuIsOpen no longer applies, the dropdown also closes.

How can I change this behaviour? Ideally, a way to block any normal dropdown-closing behaviour - e.g. block `blurInput()` if a certain condition (`modalOpen`) is met. I've been digging around the source code and can't find a way to do this - any tips would be appreciated and then I can make the change myself locally. Thanks!

**Comment by ebonow** [comment]
@dancherb ,

Have you tried toggling the menuIsOpen prop between `true` and `undefined` (as false simply keeps the menu closed)? 

It is likely you may have other edge cases, so just trying to better understand how to get the desired result.

**Comment by bladey** [comment]
Thanks for the response @ebonow.

@dancherb please let us know if this doesn't solve your issue or have more information.
