### ISSUE TITLE
Get input 'name' attribute/prop onBlur

### ISSUE THREAD

**Issue by barrychapman** [JedWatson/react-select#4185]
How do people handle having multiple ones of these? I am trying to capture the elements 'name' property when onBlur is fired, but the only data I get inside the argument passed is not very helpful:

```
Class {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: FocusEvent, _dispatchListeners: ƒ, …}
bubbles: (...)
cancelable: (...)
currentTarget: (...)
defaultPrevented: (...)
detail: (...)
dispatchConfig: null
eventPhase: (...)
isDefaultPrevented: (...)
isPropagationStopped: (...)
isTrusted: (...)
nativeEvent: (...)
relatedTarget: (...)
target: (...)
timeStamp: (...)
type: (...)
```

Also, all the arguments in that argument appear to be null.

What can I do to get the name of the element on Blur? I need it in order to perform validation

**Comment by ebonow** [comment]
Greetings,

Have you tried `event.target.name` with `event` being the variable parameter passed back from the onBlur function similar to other react event handler methods.

**Comment by bladey** [comment]
Thanks for your help @ebonow!

@barrychapman please do let us know if this solves your issue, if not, please re-open it.
