### ISSUE TITLE
onPaste event handler

### ISSUE THREAD

**Issue by ondrejbartas** [JedWatson/react-select#4186]
Hello, 

firstly thanks for amazing React package.

I am working on project where we use react select to filter data from database (async loading distinct values from columns) and our users have sometimes huge lists of options they want to select. They have this list for example in csv, google spreadsheet etc. They would like to copy paste that list to react select.

So what I did was small hacking of refs to get to input element on which I started to listen on `paste` event. When paste was fired I looked at pasted text and desided what to do - ignore if no new line, do some 🧙 when multiple lines.

My code looks like something this: 

```jsx
<CreatableSelect
  isMulti
  value={this.state.value}
  ref={
    el => {
      // here I need to wait some time to get ref of input
      setTimeout(() => {
        el.select.select.inputRef.addEventListener('paste', event => {
          const paste = (event.clipboardData || window.clipboardData).getData('text');
          // some magic to find only valid options
          const pastedItems = paste.split('\n').filter(t => `${t}`.trim().length > 0);
    
          if (pastedItems.length > 1) {
            event.preventDefault();
            // and here I am calling change event on my state
            this.handleChange(
              uniqBy([...this.state.value, ...pastedItems.map(value => ({ value }))], ({ value }) => value)
            );
          }
        });
      }, 100);
    }
  }
/>
```

It would be amazing if react-select could have option like this built in, or if you could point me in direction how to get to inputRef.

Thanks

![react-select](https://user-images.githubusercontent.com/45809/91776850-9b643180-ebee-11ea-8593-312c27e00660.gif)

**Comment by ebonow** [comment]
Greetings,

The intended way would be to use a custom Input component. When adding props to custom components (like maxLength), I personally like adding them directly to the Select component itself so that I can access it via `props.selectProps` on the custom component.

```
import Select, { components } from 'react-select';

const onPaste = event => { /* your paste function handler */ }

const Input = props => <components.Input {...props} onPaste={props.selectProps.onPaste} />

return <Select components={{ Input }} onPaste={onPaste} ... />
  
};
```

You could also add an input id on the text input as a Select prop and attach/remove the event handler to the DOM onMount/onUnmount.


Let me know if this resolves your issue, and if so, please feel free to mark the issue as closed.

**Comment by bladey** [comment]
Thanks again for your help @ebonow!

@ondrejbartas I'm going to close this now since it's been a month, please re-open the issue if it's still an issue.
