### ISSUE TITLE
Add emptyLabel prop to prepend options list

### ISSUE THREAD

**Issue by barrychapman** [JedWatson/react-select#4187]
# Are you making a feature request? YES

Provide as much information as possible about your requested feature. Here are a few questions you may consider answering:

*   What's your use case? (Tell us about your application and what problem you're trying to solve.)
*   What interface do you have in mind? (What new properties or methods do you think might be helpful?)
*   Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

To add a property that will allow the setting of an 'Empty' option 'Label'.

Suppose I have a list of props coming back from an API:

```
[
     { label: "First", value: 1},
     { label: "Second", value: 2},
     { label: "Third", value: 3}
]
```

Now if I wanted an option that says 'Please select an instance`, it would essentially prepend the options array with that Label and empty value:

```
[
     { label: "Please select an instance", value: null},
     { label: "First", value: 1},
     { label: "Second", value: 2},
     { label: "Third", value: 3}
]
```

My usecase is that I have a module that has my repeatable Form fields in there, which can be added in a stateless manner to my Forms using default values and styling along with other UI treatment. We would then be able to call from our Forms:

```
const MyForm = () => {
     return (
           <>
                  <MyCustomSelect
                         name="somename"
                         options=MyOptionsArray
                         empty="Please select an instance"
                   />
           </>
     );
}

I do realize that this could be done by adding it to my array myself, but that would require a customization for every form element this occurs on. It may be easier to leverage it this way. Also, it may be useful to display it in a disabled manner in the drop down while it populates (if fetching from an API)

**Comment by ebonow** [comment]
Greetings,

I would disagree with making this a part of react-select core functionality. Placeholder already exists as a field descriptor. Instead, it should be fairly straight forward building out this functionality as it seems you are already creating a custom wrapper around your Select.

Does this resolve your use case?

```
const MyCustomSelect = props => {
  const { empty, options, ...selectProps } = props;

  const [ selectOptions, setSelectOptions ] = useState(options);

  // Anytime options or empty label changes, update options sent to Select
  useEffect(() => {
    setSelectOptions([ { label: empty, value: null }, ...options ]);
  }, [ empty, options ])
  
  return <Select options={selectOptions} ... />
}
```

**Comment by bladey** [comment]
Thanks again for your help @ebonow.

@barrychapman from your reaction to @ebonow's message it looks like this resolves your issue.

Please re-open if that's not right!

**Comment by barrychapman** [comment]
I was able to utilize this, however - the Placeholder functionality seems to not work when using custom inputs
