### ISSUE TITLE
Move building/testing dependencies to devDependencies in package.json

### ISSUE THREAD

**Issue by renaudl** [JedWatson/react-select#4192]
All dependencies are listed as dependencies while many of them are simply use for compilation (babel, @testing-library, enzyme, webpack...). 

This is a bit messy as it does not make clear what extra dep will be bundled in the resulting minified project. This also complexify identification of vulnerability with npm audit as the option --only=prod would not work.

I suggest these dependencies declaration in package.json be properly moved to the devDependencies section. I could help if there is an interest at it.

**Comment by Methuselah96** [comment]
The dependencies you are mentioning are for the monorepo as a whole, not the `react-select` npm package specifically, which can be found [here](https://github.com/JedWatson/react-select/blob/master/packages/react-select/package.json). That package.json should make it clear which dependencies will be bundled in the resulting minified project and make npm audit work properly.

**Comment by renaudl** [comment]
Hi there, that is correct. However, I wonder why @babel/runtime is a dependency and not a devDependency. Should I create a separate issue to discuss this very point?

**Comment by renaudl** [comment]
Closing the trail as it is all correct. Learnt something today. Thanks for the help.
