### ISSUE TITLE
onFocus and onBlur props not propogated to custom components

### ISSUE THREAD

**Issue by j-funk** [JedWatson/react-select#4193]
# BUG

This bug is quite popular and has been mentioned and closed a number of times:

https://github.com/JedWatson/react-select/issues/625

https://github.com/JedWatson/react-select/issues/3595

Here is a simple reproduction of the issue in V3: [V3 Sandbox Link](https://codesandbox.io/s/react-select-v3-sandbox-forked-cnlc3)

Steps to reproduce:
1. Go to sandbox and open Select, then click outside of the Select
2. Note that the console is indicating the OnBlur and OnFocus are properly called
3. Reopen and select any of the options, the Select will close automatically
5. Reopen Select, then attempt to Blur / lose focus by clicking anywhere outside of the Select
6. Notice that the console log does not indicate that the OnFocus or OnBlur events are being fired at all

**Comment by Rall3n** [comment]
Its not a bug, just two problems I see with your code:

1. When you have a values, the `Input` component from the `children` prop is missing inside the `ValueContainer` component. It handles the focus of the whole `Select` component. Simply filtering out everything that is not the `Input` component should suffice for it to work again.
```jsx
{Children.map(children, child => child.type === components.Input ? child : null)}
```
BUT

2. You define two different `components.ValueContainer` components. Even with the `Input` component it would re-render the whole tree down, causing the `Input` component to be replaced and breaking the focus handling. Refactor your code so you only define one `ValueContainer` component and handle the rest inside its children.

```jsx
return <components.ValueContainer { ...props }>
      {Children.map(children, child => !hasValue || child.type === components.Input ? child : null)}
      {hasValue && `${selectProps.messages.orderPageAnySelectPreText}: ${countSelectedVal}`}
  </components.ValueContainer>;
```

**Comment by bladey** [comment]
Thanks for your feedback @Rall3n.

@j-funk could you please let us know what you think of the above advice.

**Comment by j-funk** [comment]
@Rall3n would you be willing to create a live example demonstrating this similar to the one I've posted above?  Thanks for your help.

**Comment by LeadDreamer** [comment]
@Rall3n I just executed your suggestion in a fork, precisely as written, adding a mouseout similar to the blur.  Yet still, once the initial selection box is clicked, NO mouseout or blur event occurs UNLESS I active click outside the Select element, whether the menu has dropped or not.  Seems to miss the point of onBlur, or *at least* mouseout?

**Comment by LeadDreamer** [comment]
@Rall3n  also removed hasValue, so precisely the same children are being rendered regardless (temporarily allowing the "Selected: 0") - same result.

**Comment by LeadDreamer** [comment]
@Rall3n also removed the custom components altogether - same result.  Shouldn't ***at LEAST*** the mouseout event fire?

**Comment by LeadDreamer** [comment]
(I mentioned this because I have a whole "edit-in-place" structure going, that hides various input types including text, textarea, tel, number, date etc etc and *arrays* of the foregoing that activate as I mouse over, and return to normal on mouseout/blur.  The only parts that *don't* work that way are the ones using react-select..)

**Comment by j-funk** [comment]
@bladey sounds like it's still an issue -- see @LeadDreamer comments above.

**Comment by LeadDreamer** [comment]
I'll note on my first look through the source, in Select.js, I see this:

````
return options.reduce(
      (acc, item, itemIndex) => {
        if (item.options) {
          // TODO needs a tidier implementation
          if (!this.hasGroups) this.hasGroups = true;

          const { options: items } = item;
          const children = items
            .map((child, i) => {
              const option = toOption(child, `${itemIndex}-${i}`);
              if (option) acc.focusable.push(child);
              return option;
            })
            .filter(Boolean);
          if (children.length) {
            const groupId = `${this.getElementId('group')}-${itemIndex}`;
            acc.render.push({
              type: 'group',
              key: groupId,
              data: item,
              options: children,
            });
          }
        } else {
          const option = toOption(item, `${itemIndex}`);
          if (option) {
            acc.render.push(option);
            acc.focusable.push(item);
          }
        }
        return acc;
      },
      { render: [], focusable: [] }
    );
````

Specifically, the two lines:
````
          const { options: items } = item;
          const children = items
````

There is ***NO*** other reference ***or*** definition in the file to a variable or constant "items" - is this a bug?

**Comment by LeadDreamer** [comment]
@j-funk @bladey on line 1342 of packages/src/Select.js, you alias ````items.options```` to ````items````, and make no further us of the alias after the next line.  This seem intentionally obfuscating.  why not just:
````
          const children = item.options
            .map((child, i) => {
              const option = toOption(child, `${itemIndex}-${i}`);
              if (option) acc.focusable.push(child);
              return option;
            })
            .filter(Boolean);
````

which seems a lot more obvious?

**Comment by LeadDreamer** [comment]
In packages/src/Select.js, the only props passed down are those selected by

````
  getCommonProps() {
    const { clearValue, getStyles, setValue, selectOption, props } = this;
    const { classNamePrefix, isMulti, isRtl, options } = props;
    const { selectValue } = this.state;
    const hasValue = this.hasValue();
    const getValue = () => selectValue;

    const cx = classNames.bind(null, classNamePrefix);
    return {
      cx,
      clearValue,
      getStyles,
      getValue,
      hasValue,
      isMulti,
      isRtl,
      options,
      selectOption,
      setValue,
      selectProps: props,
      theme: this.getTheme(),
    };
  }
````
...which I note does not include many of the mouse events; the the ones that are invoked seem to be by SyntheticEvent, such as

````
  onInputBlur = (event: SyntheticFocusEvent<HTMLInputElement>) => {
    if (this.menuListRef && this.menuListRef.contains(document.activeElement)) {
      this.inputRef.focus();
      return;
    }
    if (this.props.onBlur) {
      this.props.onBlur(event);
    }
    this.onInputChange('', { action: 'input-blur' });
    this.onMenuClose();
    this.setState({
      focusedValue: null,
      isFocused: false,
    });
  };
````
...perhaps this is why we are *not* seeing mouseover/mouseout and other typical events?

**Comment by LeadDreamer** [comment]
I'm not really in a place to be able to fully build the packages, so I may well resort to stripping out those pieces I need and fixing them.

**Comment by LeadDreamer** [comment]
If I might suggest - rather then explicitly selecting the props you ***DO*** want to pass down, how about copying them ALL, then ***DELETING*** those you do ***NOT*** want to pass down?

**Comment by j-funk** [comment]
@LeadDreamer I get a notification for every comment you post here, would you consider compiling all comments into a single one and then just editing it instead?

**Comment by Rall3n** [comment]
@j-funk [Here is a sandbox](https://codesandbox.io/s/react-select-v3-sandbox-forked-cxyme) of your example with my changes. You can see by focusing, selecting an option and then clicking outside that the `focus` and `blur` events are triggered properly.

-----
> I just executed your suggestion in a fork, precisely as written, adding a mouseout similar to the blur. Yet still, once the initial selection box is clicked, NO mouseout or blur event occurs UNLESS I active click outside the Select element, whether the menu has dropped or not. Seems to miss the point of onBlur, or at least mouseout?

@LeadDreamer Keeping the focus after selection is by design. If you don´t want this, then use the `blurInputOnSelect` prop.

Furthermore, there is no prop registered for adding an event handler to the `mouseout` event. You might have to customize the component yourself to allow the use of a `mouseout` event handler. I suggest creating a custom `Container` component and adding a the event handler to the `innerProps` prop.

**Comment by LeadDreamer** [comment]
@Rall3n Well, you convinced me.  I wrote my own and dropped use of react-select.  Good luck!

**Comment by ebonow** [comment]
Thanks for your assistance @Rall3n 

A ValueContainer without an Input inside it has no element to receive focus or blur. I appreciate your contribution and putting together a working example. 

I will consider this closed but am open to reopening if there are further concerns.
