### ISSUE TITLE
Update second when change first select

### ISSUE THREAD

**Issue by majweb** [JedWatson/react-select#4196]
I warmly welcome.
I have 2 selects. The first one is filled in with api from the base. The second is filled during the onchange of the first select.
Everything works correctly.
I care about such a situation that when I change the first select, the second one will automatically choose the first item.

**Comment by ebonow** [comment]
Greetings,

It sounds like you want to automatically set the value of the 2nd select to its first option whenever the options change (as determined by the first select).

One way to handle this then is to wait for changes in the options for Select2 and whenever those options change, select the first option from the list, and set it as the value for Select2.

Here is one such implementation of how it can be done.

```
const [ options2, setOptions2 ] = useState([]);
const [ value2, setValue2 ] = useState(); 

const select2Ref = useRef();

const onChange1 = opt => {
 // ... some logic to determine props/options for 2nd select
 setOptions2(newOptionsToShowInSelect2);
}

const onChange2 = opt => setValue2(opt)

useEffect(function onNewOptions() {
  options2.length && setValue2(options2[0]);
}, [ options2 ])

return (
 <>
  <Select name="1stSelect" onChange={onChange1} ... />
  <Select name="2ndSelect"
    onChange={onChange2}
    options={options2}
   value={value2}
   ...
  />
</>
)
```

Please let me know if this helps and if it solves your problem, please feel free to close this issue.

**Comment by majweb** [comment]
Did not work.
In useeffect, I retrieve data for selects.
I have a selectedLand state that changes during the first select onChange.
This state wants value for the second select.

This select2
```
<Controller
as={<Select options={land} />}
control={control}
isDisabled={isLoading}
className={`${errors.land ? 'error-extended' : ''}`}
rules={{
 required: {
value: true,
message: 'Wybierz land'
 },
}}
name="land"
 isClearable
 noOptionsMessage={() => "Nie znaleziono landu"}
placeholder={"Region"}
styles={customStyles}
value={selectedLand ? selectedLand : ''}
 defaultValue={
 selectedLand ?
selectedLand
: { label: 'etst', value: 1 }
 }
value={selectedLand}
/>
```

**Comment by ebonow** [comment]
Then why not use a useEffect for Value2 which updates Select1?

It would be helpful if you could provide a code example in codesandbox.

**Comment by ebonow** [comment]
Here is a [recent example](https://codesandbox.io/s/react-select-include-exclude-selects-fo5uz) I did for another use-case for communicating between two selects.

While it may not exactly fit your use case, I hope that it provides some direction. I will close this issue now but if you wish to create a codesandbox for us to look at, I would be willing to take a look at it, and reopen this ticket if necessary.
