### ISSUE TITLE
Cursor height off when inside of an iframe on mobile (mostly iphones)

### ISSUE THREAD

**Issue by on2air** [JedWatson/react-select#4197]
I'm using select inside an iframe. when the menu opens, I message parent frame that increases the iframe size so that there is room for the menu to open.  Menu opens fine, but the mouse selector is off a 20-30 pixels, so when I select an item, it actually selects the item 4 spots up from where I clicked.  I'm seeing this in the chrome emulator as well as with real devices.

See video explanation here: https://www.loom.com/share/25a00c31648247ea92cc68f9dccaf0f6

and sample item here: https://www.jotform.com/201267462003141

**Comment by ebonow** [comment]
Greetings @on2air ,

I was not able to replicate the behavior you mentioned regarding selecting the wrong item... until I adjusted the Chrome virtual device zoom level to 75% as you had yours set in in your video.

Maybe this is a silly question, but have you tried adjusting the zoom to 100% or are you seeing this behavior on the hardware itself?

**Comment by on2air** [comment]
thanks for taking a look @ebonow . here is a customers video of what they are seeing: https://www.screencast.com/t/lWX726DZ

its slightly different issue than when inside the emulator, but basically the widget becomes nearly unresponsive after the first time.

**Comment by Rall3n** [comment]
@on2air Could you provide code or a basic example which shows the issue?

**Comment by ebonow** [comment]
> @on2air Could you provide code or a basic reproducible example which shows the issue?

The example can be found on the link provided in the first post. The browser emulator was only able to reproduce this for me when zoomed in. I was hoping to get around to firing up Xcode and trying to reproduce on an iPhone Simulator this weekend.

https://www.jotform.com/201267462003141

**Comment by on2air** [comment]
here is the real life example causing the issues: https://form.jotform.com/202257059905053?whichPower=|recCM52Kn8t71NBSd&whichTop1=|recCM52Kn8t71NBSd&whichTop2=|recCM52Kn8t71NBSd&hideMenstruation=no

(you have to go to question #4 to get to the select box)

I'm working on a simplified example to replicate it.  appreciate you taking a look.

**Comment by lukebennett88** [comment]
Hi @on2air.
Thanks for opening this issue. I couldn't get any of the Jotform links to work for me.
As this issue hasn't be active for some time, I'm going to close it. Please feel free to reopen if it's an ongoing issue. A CodeSandbox would also be super helpful if that's at all possible to put together.
