### ISSUE TITLE
Select component methods should be documented.

### ISSUE THREAD

**Issue by mik01aj** [JedWatson/react-select#420]
Looking at [the source](https://github.com/JedWatson/react-select/blob/master/src/Select.js), the following methods seem useful to me:

* `focus` (it is even used on the [demo page](http://jedwatson.github.io/react-select/)!)
* `setValue`
* `addValue`
* `removeValue`
* `popValue`
* `clearValue`
* `getInputNode`

There is *nothing* about them in the README.

**Comment by brianreavis** [comment]
As far as I know, those methods are only meant to be used internally (apart from `focus()`). The others should be avoided and be accomplished via props (following React's way of doing things).

**Comment by mik01aj** [comment]
Not everything can be accomplished through `props`, please see #409.

**Comment by brianreavis** [comment]
At it's current state, right – use of those methods you mentioned are an unfortunate hack around something that *should* be simple / achievable via props. My only point in that we shouldn't be documenting methods that aren't intended to be public (I'm not trying to invalidate #409).

**Comment by mik01aj** [comment]
Ok, I reopened #409 then.
