### ISSUE TITLE
Hide react-select menu without removing it from browser DOM

### ISSUE THREAD

**Issue by demonmovch** [JedWatson/react-select#4200]
Hello. Thanks for the great library! When react-select's menu is closed, it is removed from the browser dom. I have faced the situation where menu must not be removed from the dom. Is it possible to hide it without removing from the browser dom, for example set "display: none"?

**Comment by ebonow** [comment]
Greetings,

I am afraid that the code itself is wired to render null if the `menuIsOpen` prop/state is falsey.

If you wanted to override this behavior, you would likely need to set `menuIsOpen` to always be true and manage the menu open state in another variable which the custom Menu component relies on. I am not certain if there would be other side effects (ie: arrow button presses) but it might be a good starting point. 

You could try this thread and see if the working example at the end helps in anyway.
https://github.com/JedWatson/react-select/issues/4189

**Comment by demonmovch** [comment]
Thank you, Eric.
