### ISSUE TITLE
"onChange" prop in Async select does not work properly

### ISSUE THREAD

**Issue by fydsa** [JedWatson/react-select#4208]
Hello everyone,

I am using AsyncCreatableSelect and I've defined the "onChange" prop in the AsyncSelect component. But, when I select an item from the options list, although the value prop of the select component is set to the new value, the selected item does not show up in the container field! But, when I clear the "onChange" prop, the selected item does show up in the input field! The reason I used the "onChange" is to access the new value that is selected and I can have it but it does not appear in the container when it is selected. Here is an example of what is happening:
`
import React from "react";
import AsyncCreatableSelect from "react-select/async-creatable";

var colourOptions = [
  { value: "red", label: "Red" },
  { value: "blue", label: "Blue" },
  { value: "green", label: "Green" }
];

const filterColors = (inputValue) => {
  return colourOptions.filter((i) =>
    i.label.toLowerCase().includes(inputValue.toLowerCase())
  );
};

const promiseOptions = (inputValue) =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve(filterColors(inputValue));
    }, 1000);
  });

export default function App() {
  const handleChange = (newValue, action) => {
    console.log(newValue);
  };
  return (
    <div className="App">
      <AsyncCreatableSelect
        onChange={handleChange}
        cacheOptions
        defaultOptions
        loadOptions={promiseOptions}
      />
    </div>
  );
}
`

I really appreciate any help.

**Comment by ebonow** [comment]
Greetings @fydsa ,

It would be helpful if you could include your code about the Select in the render to better understand what props are being passed in.

**Comment by BogdanBulai** [comment]
I'm having the same issue.

**Comment by ebonow** [comment]
@fydsa @BogdanBulai 

There unfortunately is not information to proceed. If either of you are able to provide some code or even better a codesandbox, then please feel free to open a discussion in Q&A so the community can help diagnose the issue.
