### ISSUE TITLE
CreatableSelect does not support custom options (using the getOptionLabel prop)

### ISSUE THREAD

**Issue by frevds** [JedWatson/react-select#4209]
I'm using custom options { key, text } instead of { value, label }. 
If I specify getOptionLabel, creating new options does no longer work. 

```
      <CreatableSelect
        isMulti
        onChange={this.handleChange}
        options={[ { text: 'o', key: 'a' }, { text: 'p', key: 'b' }, { text: 'q', key: 'c' } ]}
        getOptionLabel={ (o) => o.text }
        getOptionValue={ (o) => String(o.key) }
      />
```

**Comment by Rall3n** [comment]
@frevds You also have to use `getNewOptionData` to create the option with the custom schema.

`getOptionLabel` and `getOptionValue` are only used on already existing options.

```jsx
<Creatable getNewOptionData={(inputValue, optionLabel) =>( { key: inputValue, text: optionLabel })} />
```

**Comment by frevds** [comment]
@Rall3n Ah, that makes sense. Many thanks.

**Comment by frevds** [comment]
@Rall3n Yes, that works and solves the issue - closing ticket.
