### ISSUE TITLE
Duplicate option key generated when entered value is the same as one of the options 

### ISSUE THREAD

**Issue by akum32** [JedWatson/react-select#421]
If i start typing '1' and options returned are: [{name: "Option 1", value: 1}, {name: "Option 2", value: 2}],  when the menu is built the same key is used for the 'Add 1?' and 'Option 1'. This results in the results never showing 'Option 1'.

Hence I think there should probably be a check to ensure the 'Add xxx?' doesn't appear when there is an exact match. What do you think?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
