### ISSUE TITLE
How to change color of scrollbar

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4211]
StackOverflow already has a question for this but the chosen answer does not work for me:
https://stackoverflow.com/questions/54413762/react-select-scrollbar-styling

I'm assuming there should be some way of doing it using the [styles](https://react-select.com/styles) prop in react-select.
My best guess is something in `menuList` under styles should be able to change the scrollbar color.

So something like
```tsx
<Select 
  styles={{
    menuList: (defaultStyles: any) => ({
    ...defaultStyles,
    /* Scrollbar styles */
    })
  }}
/>
```
should work but I'm not sure what to do to change the color of the scrollbar here.

### Third party library solution
I tried using react-custom-scrollbars as demonstrated in [this example](https://codesandbox.io/s/cocky-chatelet-o1qng?fontsize=14&file=/src/MySelect.js) and was able to change the color of the scrollbar. The problem with this solution is that, for some reason, the mouse wheel scroll stops working whenever I use a custom MenuList component in react-select. I don't know if this is a potential bug. But I'd like to avoid spend time making another library work just for changing the color of an element.
[Demo](http://www.absingh.com/react-select-custom/) | [Code](https://github.com/cseas/react-select-custom/blob/master/src/components/CustomMenuList.tsx)

### Suggestion
The documentation doesn't give details about what the styles object completely looks like. I had to dig into the repository to find [this file](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/Menu.js) to figure out what the default styles for menuList are. I'd recommend adding a complete structure of the styles in the documentation so the users can get an overview of what the complete default styles are for each component. That would make it easier to use the styles prop.

An example of how to customize the scrollbar would also be a helpful addition to the documentation.

**Comment by cseas** [comment]
**Update:**
I figured out the bug that was disabling the mouse wheel scroll when using `react-custom-scrollbar`.
`react-select` was capturing the menu scroll for some reason and that's why `react-custom-scrolbar` wasn't able to pick it up.
Setting `captureMenuScroll={false}` in `<Select />` made the mouse scroll start working for me.

Even though my use case is technically solved now, my original question still stands, is there a way to customize the scrollbar without using a third-party library? And if not, then an example using `react-custom-scrollbar` might be a useful addition to the "styles" documentation perhaps. I'd be happy to make a PR adding the example if that helps.

**Comment by ebonow** [comment]
Greetings @cseas ,

You can style the menuList scrollbars using the `styles` prop.

```
const styles = {
  menuList: (base) => ({
    ...base,
    height: "100px",

   "::-webkit-scrollbar": {
     width: "9px"
   },
   "::-webkit-scrollbar-track": {
     background: "red"
   },
   "::-webkit-scrollbar-thumb": {
     background: "#888"
   },
   "::-webkit-scrollbar-thumb:hover": {
     background: "#555"
   }
});

return <Select styles={styles} ... />
```

Here is an [example using a fork of your project](https://codesandbox.io/s/react-select-custom-menu-scrollbars-c3urr?file=/src/MySelect.js) (omitting the 3rd party library).

Let me know if this resolves your question about styling the menu scroll bars with the styles prop, and if so feel free to close this issue.

**Comment by cseas** [comment]
Thanks a lot, @ebonow !
I was able to change the color of the scrollbar using your example without any third party lbrary.
