### ISSUE TITLE
Feature Request: an `onMenuOpen` event that doesn't trigger on each input keystroke

### ISSUE THREAD

**Issue by cullylarson** [JedWatson/react-select#4214]
**Feature Request**

If you click on a select input and start typing, the `onMenuOpen` event triggers on each keystroke. Presumably because the menu closes and re-opens on each keystroke. So, it's technically true that the menu opens on each keystroke. However, this is not helpful if you're conceptually considering the menu to open once when you select the input and not closing until you actually select an option (or on blur). For example, I have a situation where I want to scroll the page down to the bottom of the options when the select is opened (the select is in a modal and it's not intuitive that it's possible to scroll the modal, so I'm just doing it automatically). As it is, the page scrolls down on each keystroke.

The feature request is a new event that triggers once when the menu opens and not again until the menu is closed by either selecting an option or blurring out of the input, and is then re-opened. Basically just not triggering on each keystroke.

**Comment by ebonow** [comment]
Greetings @cullylarson ,

I attempted to replicate your issue, but the source code and my testing hasn't been able to replicate the behavior you are seeing. 

Here is a code sandbox demonstrating that onMenuOpen does not appear to be firing on every keystroke. 
https://codesandbox.io/s/react-select-trigger-warnning-onmenuopen-lmy7s

Perhaps if you share a codesandbox of your implementation someone can help you find what is happening, but as is I am unable to replicate the issue.

**Comment by ebonow** [comment]
I did some follow up research and wanted to let you know that indeed this behavior was present but was patched in v3.1.1 in PR https://github.com/JedWatson/react-select/pull/3897/files

I will mark this issue as closed and thank you for your patience on the resolution to this issue.
