### ISSUE TITLE
Multi Selection Menu not going off after clicking outside

### ISSUE THREAD

**Issue by sovanjana** [JedWatson/react-select#4216]
I am using **react-select** multi select but using a custom **ValueContainer** for showing value instead of **MultiValueContainer**.
In case of **MultiValueContainer** it is going off after clicking outside but when I am using **ValueContainer** to show custom value with **hideSelectedOptions** as **false** it's not going off.

What I need is I want to select multiple options and until I click outside it should remain open and after clicking outside it should close the menu.

Guys, PLease share your thoughts on how I can achieve this blocker

**Comment by sovanjana** [comment]
fixed the issue..
passing **components={{ MultiValue: ValueContainer }}** to **Select** component and  using **components.SingleValue** in **ValueContainer** solves the issue.

**Comment by hekenji** [comment]
Hi, this solution has a side effect... It render one div for each selected option, so it gets darker and darker, eg.

![all_selected](https://user-images.githubusercontent.com/39958068/113289378-85bf0380-92c6-11eb-81c4-ca6e18c19856.png)
![one_selected](https://user-images.githubusercontent.com/39958068/113289388-8788c700-92c6-11eb-9808-2efa1d78dc5a.png)
