### ISSUE TITLE
Type definition missing for state of styles

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4219]
The [accepted StackOverflow answer](reactjs.org/docs/create-a-new-react-app.html) mentions the type of `state` should be `ControlProps` but that doesn't seem to work.

As mentioned in [this comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27737/files/4a7471a7242426622710a681504531839d2e41d5#r207170226), there is a lack of documentation in the `react-select` website about how to use the `state` parameter when using the `styles` prop in react-select to style components.

It would be nice to have some proper answer or guide on how to exactly use the `styles` prop in TypeScript without using `state: any`.

```tsx
import { CSSProperties } from "react";
...
<Select
  ...
  styles={{
    control: (base: CSSProperties, state: any) => ({ ...base })
    menuList: (base: CSSProperties, state: any) => ({ ...base })
   }}
/>
```
For example, for the above code, what should the type for `state` be? And is there any reference available in the documentation that mentions the different properties that the `state` variable contains?

In addition, the [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a6699c7c10747bfd93be4561a36cae9dcd38e6f9/types/react-select/src/styles.d.ts#L34) for `react-select` also contain `state: any` which makes the `state` variable even more of a mystery to understand and use.

**Comment by Methuselah96** [comment]
The second parameter of the `styles` function is almost always the props of the component (except in the case of `groupHeading`, `input`, and `menuPortal`). I have [a branch](https://github.com/Methuselah96/react-select/tree/typescript-final) where I've converted `react-select` to TypeScript. To investigate what the different types should be you can look at [the types for props on that branch](https://github.com/Methuselah96/react-select/blob/typescript-final/packages/react-select/src/styles.ts#L52-L87).

Also, your link to the type definitions is outdated. I started working on filling in the type for that second parameter in [a recent PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46386), but I've only done it for `ControlProps` so far. You're welcome to contribute and fill out more of those types.

**Comment by cseas** [comment]
Thank you for the response!

The [test added here](https://github.com/Methuselah96/DefinitelyTyped/blob/a6c49aa0706c2b3a812e81e692ec24f2ada300c3/types/react-select/test/Header.tsx#L6) finally helped me figure out how to add the type.

So I can confirm the below way works:
```
import { CSSProperties } from "react";
import { MenuListComponentProps, OptionProps } from "react-select";
...
<Select
  ...
  styles={{
    control: (base: CSSProperties, state: ControlProps<{}>) => ({ ...base })
    menuList: (base: CSSProperties, state: MenuListComponentProps<{}>) => ({ ...base })
    option: (base: CSSProperties, state: OptionProps<{}>) => ({ ...base })
   }}
/>
```

However, I'm still not able to find a proper type for `placeholder`.
When trying to use `placeholder: (base: CSSProperties, state: PlaceholderProps<{}>)`, I get an error saying `Property 'isFocused' does not exist on type 'PlaceholderProps<{}>'`.

But that can't be right because I have been using `state.isFocused` in placeholder styles and it seems to work fine.

Here's my placeholder styles for reference:
```jsx
placeholder: (base: CSSProperties, state: PlaceholderProps<{}>) => ({
          ...base,
          position: "absolute",
          top:
            state.isFocused || state.hasValue || state.selectProps.inputValue
              ? -5
              : "50%",
          transition: "top 0.1s, font-size 0.1s",
          fontSize:
            (state.isFocused ||
              state.hasValue ||
              state.selectProps.inputValue) &&
            "0.688rem",
        })
```

Regarding whether to call it `state` or `props`, I'm not really sure. I just saw that most people called it `state` and went with it.

**Comment by Methuselah96** [comment]
The [`PlaceholderProps` interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/components/Placeholder.d.ts#L6-L11) is incomplete in `@types/react-select` and needs to updated to [include `isDisabled` and `isFocused`](https://github.com/Methuselah96/react-select/blob/typescript-final/packages/react-select/src/components/Placeholder.tsx#L16-L27). You could make a PR on the DefinitelyTyped repository to fix it if you want it to be fixed.

**Comment by cseas** [comment]
I was able to use the `styles` property with the type definitions for `state` as given in the example code I mentioned above so I'll close this issue. There seems to be issue with only the type definition of PlaceholderProps so I've opened a separate issue for it on the DefinitelyTyped repository since that doesn't have much to do with react-select directly.
