### ISSUE TITLE
Spinner remains visible

### ISSUE THREAD

**Issue by akum32** [JedWatson/react-select#422]
In async mode with new values allowed, when results are being fetched and user enters a new value and hits enter, the Spinner remains visible.

**Comment by ICervantezMirth** [comment]
In the async mode you need to make sure to call the callback() function, even if that's with an error or an empty value.  Once you call the callback(), it will remove the spinner.  If your async function cancels or fails to call callback() then the spinner will continue to display.

**Comment by TigerC10** [comment]
In the async mode you need to make sure to call the callback() function, even if that's with an error or an empty value. Once you call the callback(), it will remove the spinner. If your async function cancels or fails to call callback() then the spinner will continue to display.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
