### ISSUE TITLE
A complete floating placeholder/label solution

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4221]
Opening a new issue because #2152 has been closed.

[The example](https://github.com/JedWatson/react-select/issues/2152#issuecomment-470889515) given by @Rall3n for making the placeholder float up on entering input works fine but the problem is that the placeholder doesn't go up on focus which is expected behaviour for most input fields with floating labels.

I was able to use the `styles` prop to make the placeholder float up on focus without using a custom `ValueContainer` component but on doing that the placeholder disappears soon as we start typing. [[Example](https://codesandbox.io/s/react-select-keep-placeholder-make-it-float-forked-kxzhl?file=/example.js)]

Multiple issues regarding this topic have been raised in the past so it would be nice to have a full working example for how to make a floating placeholder work with the latest react-select version (3.1.0).

There could be 2 solutions to this:
- Either make the placeholder float up on focus in [this example](https://codesandbox.io/s/6x9405rlqk).
- Or stop the placeholder from disappearing in [this example](https://codesandbox.io/s/react-select-keep-placeholder-make-it-float-forked-kxzhl?file=/example.js). (Preferred since this doesn't require a custom component)

The first example could be a potential bug because `state.isFocused` seems to stop working when we use a custom `ValueContainer` component.

This is a common use case and would be a nice addition to the documentation examples as well if the functionality is difficult to add to the library as a prop.

**Comment by ebonow** [comment]
Greetings @cseas ,

Let me begin by saying that this is a common use-case, but there might be a slight difference in semantics and expectations.

The `Placeholder` is intended to be a workaround for the input placeholder text (as the input element is hidden by opacity until focused). An input's placeholder text should not persist beyond the user's input so it would be counter intuitive to have it behave differently than what a placeholder is.

Likely what you are looking for would be more commonly be referred to as a "label", or in this particular case, a "floating label". A label permits for greater accessibility and can be used to wrap the Input and then can be targeted for styling with the `:focus-within` selector.

So yes, I agree that this is common and that some more documentation examples would be helpful, but I don't believe that the existing implementation would be a good fit for this without custom components. 

For the record, I have already implemented something similar to this in my own react-select wrapper component by passing in a `label` prop. Even better though... I apply the existing placeholder prop to my custom input onFocus (and remove it onBlur) so I have the best of both worlds: a floating label and real placeholder text for even greater flexibility. 

I would be happy to provide a codesandbox if desired. 

Cheers!

**Comment by cseas** [comment]
Hello @ebonow, thank you for the response! I completely agree that trying to make the placeholder work as a label would be a hack and indeed counter-intuitive.

Can you please provide an example of how to add a floating label to react-select without trying to manipulate the placeholder?

**Comment by cseas** [comment]
@ebonow Thanks for the heads up! I tried using a custom label with a custom control component and removed the placeholder and everything seems to work fine.

For reference, here is the code to add a floating label to the control field without modifying the placeholder:

```tsx
// CustomControl.tsx

import React from "react";
import styled from "styled-components";
import { components } from "react-select";

export const Control = (props: any) => {
  return (
    <>
      <Label isFloating={props.isFocused || props.hasValue}>Select</Label>
      <components.Control {...props} />
    </>
  );
};

const Label = styled.label<{ isFloating?: boolean }>`
  left: 10px;
  pointer-events: none;
  font-family: sans-serif;
  font-style: italic;
  position: absolute;
  transition: 0.2s ease all;
  -moz-transition: 0.2s ease all;
  -webkit-transition: 0.2s ease all;

  top: ${(props) => (props.isFloating ? `5px` : `35%`)};
  color: ${(props) => (props.isFloating ? `red` : `blue`)};
  font-size: ${(props) => (props.isFloating ? `0.5rem` : `1rem`)};
`;
```

Then just add this custom control component to Select:
```
<Select 
  ...
  components={{ Control }} />
```
