### ISSUE TITLE
How to keep the dropdown open when a selected item is removed on a touch device(mobile)

### ISSUE THREAD

**Issue by bhatvikrant** [JedWatson/react-select#4222]
Since there is no `onRemove` function that I can access, how can I keep the dropdown open when removing an item.

**Comment by ebonow** [comment]
Greetings @bhatvikrant and sorry for the late reply.

There are two possible workarounds to achieve this.
1. Refocus the input after blur
2. Replace the onRemove function called by the MultiValueRemove

Both approaches are discussed in this thread and have codesandbox demos: https://github.com/JedWatson/react-select/issues/4410

I will keep that issue open for time being as it discusses a bit more in depth the issues as well as it has a PR associated with it. It may be possible in the near future that we are able to add a new prop so please keep an eye open on new releases.

**Comment by bhatvikrant** [comment]
Thankyou!
