### ISSUE TITLE
Ellipses instead of word wrap 

### ISSUE THREAD

**Issue by ketanthakkar** [JedWatson/react-select#4223]
I want ellipses instead of word wrap for react-select component.

I have small size of select component but, 1-2 option are long in select. If user select that then text gonna wrap to second line.

![Screenshot from 2020-09-25 18-24-28](https://user-images.githubusercontent.com/44302674/94292296-0ccca100-ff5d-11ea-9059-c5bc626785f8.png)

Expected behavior. Display text in single line with ellipses. "Already here..."

**Comment by ebonow** [comment]
Greetings @ketanthakkar ,

What version are you using and what options/styling are you applying to your Select components? It would appear that the default behavior for me is such that the singleValue does not wrap and shows text-overflow ellipsis.

[Here is a code sandbox demonstrating this,](https://codesandbox.io/s/react-select-singlevalue-overflow-1e9mh?file=/example.js) but if you are seeing a different behavior, please let me know.
