### ISSUE TITLE
No scrollbar for dropdown in safari for mac

### ISSUE THREAD

**Issue by blanteigne-dovico** [JedWatson/react-select#4225]
In other browser when there is a react-select with so many option they can't all be displayed in the dropdown, there is a scrollbar so the user can scroll down and pick the bottom options. However, in safari for the mac the scrollbar doesn't appear and so the user can't scroll down . [You can see this happening in on the react select home page](https://react-select.com/home) in the very first dropdown, and also any dropdown that needs to display a scrollbar

**Comment by hsw107** [comment]
If you're using a trackpad this is the expected behavior on a Mac. This is an OS setting you can change.
<img width="668" alt="Screen Shot 2020-10-01 at 11 08 51" src="https://user-images.githubusercontent.com/2524299/94840926-80940100-03d6-11eb-8988-8272a0d24254.png">

**Comment by bladey** [comment]
Thanks for the reply @hsw107. @blanteigne-dovico if you need further assistance please let us know.a
