### ISSUE TITLE
Add a Discussions section

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4226]
GitHub has a "Discussions" feature where you can ask questions, discuss and select answers similar to StackOverflow. The difference being it's a lot less restrictive.

It seems to be working really well for projects like [react-query](https://github.com/tannerlinsley/react-query/discussions) as you can see there are lots of questions posted and answered every day.

It might just be me but I think it's a bad idea to direct all questions on an open-source project to StackOverflow. A good example is that most of the Issues I've opened on this repository are because the StackOverflow questions were either left unanswered for months, had the wrong or "hacky" answer selected or are way too outdated comparing to the current react-select release but still top the Google results.

It would also help segregate the "Issues" and "Questions" on this repository if the users aren't forced to get some minimum amount of reputation on StackOverflow to actually be able to discuss what they want with react-select there.

There are multiple versions of react-select and most FAQs have already been asked on StackOverflow with almost all of them having outdated answers. Shifting those discussions to GitHub might actually help keep the answers updated because a question on SO is almost dead once the asker gets some solution to what works for them at that point of time but questions on an open platform that doesn't put restrictions on anyone can help keep discussions alive and in sync with the latest features in react-select.

**Comment by ebonow** [comment]
Done. 🎉
