### ISSUE TITLE
Styling Select component with CSS className

### ISSUE THREAD

**Issue by omersname** [JedWatson/react-select#4230]
Hi, I'm trying to style the Select component like written in the DOCS but adding a class with className does not work. The class tag is added to the DOM element's classes but doesn't affect the element itself. The theme stay the same.

If I add a class like this:
```
<Select
    className='my-class'
    {...selectProps}
/>
```

The DOM element looks like this:
```
<div class="my-class css-2b097c-container">
...
</div>
```

Which means that the default class `css-2b097c-container` of `react-select` will always "overide" my custom class.
I've tried to use the `classNamePrefix` option but did not work either :(

In order to keep my UI design complete I need to design it with classes and not with inline styling!

Please help me solve this, THANKS :)

**Comment by oran1248** [comment]
@omersname 
I'm facing this problem too, please help us!

**Comment by ebonow** [comment]
Greetings @omersname 

This is an issue of CSS specificity. 

Using className and classNamePrefix, you would be able to override the default theme. 

```
<Select className="react-select" classNamePrefix="react-select" ... />

.react-select .react-select__control {
    width: 6rem;
}
```

Another CSS trick of the trade is that you could simply repeat a className for extra specificity.
```
.react-select__control.react-select__control {
    width: 6rem;
}
```

**Comment by seenitall** [comment]
I'm facing the same issue. Trying to change the default color when the control is active. Your suggest solution @ebonow doen't seem to work:
```
.react-select-container .react-select__control--is-focused .react-select__control--menu-is-open {
  border-color: red;
  box-shadow:  pink;
}
```

**Comment by ebonow** [comment]
@seenitall 

It appears you have an issue with your CSS selector.

`.react-select__control--is-focused` and `.react-select__control--menu-is-open` should be selecting the same DOM element and not a descendant.

Additionally, box-shadow is expecting offset spread parameters so the browser would ignore it.

Try this instead:
```
.react-select .react-select__control--is-focused.react-select__control--menu-is-open {
  border-color: red;
  box-shadow:  0 0 10px pink;
}
```

Here is a demo representing CSS className overrides of the parent container as well as the react-select control.
https://codesandbox.io/s/react-select-classnames-490yy?file=/style.css

**Comment by bladey** [comment]
Thanks for your assistance @ebonow.

@seenitall, @oran1248, and @omersname please let us know if this hasn't solved your issue.

**Comment by andrew-aladev** [comment]
Unfortunately this issue doesn't look resolved. `classNamePrefix` is not enough for regular customization:

```js
const menuClass = `.${BASIC_PROPS.classNamePrefix}__menu`;
```

It is not possible to pass multiple `classNamePrefixes`. For example `classNamePrefix="react-select react-select-for-component-x"` won't work, but it is required for everyday usage.

**Comment by khooz** [comment]
Why not just precedent default with the provided class names? A concise library should consider user preference with higher priority than theirs. Simply re-order class composition maybe?

**Comment by Rall3n** [comment]
@khooz Rearranging classes on the HTML elements would have no effect. And this is not a bug per se, but the default behavior of how CSS is parsed in the document.

`react-select` uses `emotion` to style its components. This CSS-in-JS library appends styles to the end of the `<head>` element, giving those styles a higher priority over your styles in a stylesheet as they appear later.

But there is a solution that is not a simple workaround. You can change the default behavior of `emotion` by setting the `prepend` option in a custom cache to prepend styles to the beginning of the `<head>` element.  This should give your stylesheet styles a higher priority.

```jsx
import createCache from '@emotion/cache';
import { CacheProvider } from '@emotion/react';

const cache = createCache({
    key: 'my-select-cache',
    prepend: true
});

...

<CacheProvider value={cache}>
    <Select {...} />
</CacheProvider>
```

**Comment by ebonow** [comment]
@andrew-aladev you can use `classNamePrefix` to create multiple classNames on a component, but perhaps not in the way you imagined. Try using the modifier classes first, and then use the base classNamePrefix separated by spaces in the string. For example,

```jsx
return <Select classNamePrefix="react-select-for-component-x react-select" /> 
```

The result of this would match on `.react-select-for-component-x.react-select__menu`.

**Comment by ebonow** [comment]
@khooz 
> Why not just precedent default with the provided class names? A concise library should consider user preference with higher priority than theirs. Simply re-order class composition maybe?

Perhaps you did not read through my earlier replies citing the initial issue as a failure to write proper css selectors where I had even taken the time to write a working codesandbox solution to verify. 

> This is by far not closed. It is an inherent problem. Other suggestions are just workarounds and not capabilities. Not all bugs are features.

Do you have any non-working examples or use-cases that you are unable to resolve? I like to think it would be a better use of everyone's time here instead of empty cliches.

Perhaps it's worth noting that creating a classNames api similar to the current styles api is something Jed has identified as a roadmap target.
