### ISSUE TITLE
noOptionsMessage Props not working

### ISSUE THREAD

**Issue by AnthonyDaSilvaFe** [JedWatson/react-select#4235]
Hello guys,

I have an issue with the prop noOptionsMessage, no matter what I put the message stay the same (Select...).
I'm using react-select 3.1.0
Here's my code :

            <Select
              noOptionsMessage={() => `toto`}
              isMulti={true}
              options={this.state.typeOptions}
            />

**Comment by Rall3n** [comment]
@AnthonyDaSilvaFe I think what you mean is the `placeholder` prop. The `noOptionsMessage` is when you don't have any options available ("No options found").

**Comment by AnthonyDaSilvaFe** [comment]
Damn you are right ! My bqd, should have more read the doc.
Sorry...
