### ISSUE TITLE
yarn info: The platform "linux" is incompatible with this module

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4237]
`npm` doesn't work for trying to run the docs website locally as discussed in #4232 
However, even when trying to run it with `yarn`, an info message appears indicating an incompatibility with linux.

I'm wondering whether this project is incompatible with linux or npm?
Would npm have worked if I was on Windows?
What's the "recommended" development environment?

### Steps to reproduce
```sh
git clone https://github.com/JedWatson/react-select
cd react-select/docs
yarn
```

### Screenshot
![Selection_090](https://user-images.githubusercontent.com/29686866/95018320-99254500-067c-11eb-931a-d52f89aad495.png)

**Operating system:** Ubuntu 20.04.1 LTS

**Comment by Rall3n** [comment]
```
fsevents@2.1.3: The platform "linux" is incompatible with this module.
```
That is a common error on windows and linux machines. `fsevents` is a node module which allows listening to changes in directory trees on **MacOS** platforms.

-----

In regards to incompatibility to `npm`: Hard to say if it is a problem with `npm` linking, `webpack` (the process to build the docs) or the `babel-loader` (handling code compilation and in this example `flow` types). But I would guess a cause could be found in one of `babel` or `npm`.
