### ISSUE TITLE
Adding ID attribute in generated hidden input 

### ISSUE THREAD

**Issue by logesr** [JedWatson/react-select#4239]
Is there a way to add ID attribute to the generated hidden input when there is a selected value by default

**Comment by Rall3n** [comment]
@logesr Unfortunately not.

If you need to access the input using a selector string (`querySelector`) you can access it using the `name` attribute (`querySelector('[name=mySelectName]')`).

You can set the attribute using the `name` prop on the `Select` component.
```jsx
// Would render the input as follows: <input name="mySelectName" type="hidden" value="..." />
<Select name="mySelectName" />
```

**Comment by imrandyk** [comment]
```
      <Select
        name="my-name"
        inputId="my-id" // this is the id that gets put on the hidden input
        defaultValue={options[0]}
        options={options}
      />
```

**Comment by bladey** [comment]
Thanks for the assistance @Rall3n. @logesr if you need any further help, please let us know.
