### ISSUE TITLE
Intelligent positioning on dropdown.

### ISSUE THREAD

**Issue by anton-kabysh** [JedWatson/react-select#424]
Hi!, selector should decide to dropdown up or down in some intelligent way.  
![screenshot 2015-08-28 12 20 10](https://cloud.githubusercontent.com/assets/809822/9543217/be1a3ce6-4d7f-11e5-96bc-8bec5768d62d.png)

**Comment by gwyneplaine** [comment]
v2.x.x has logic for doing this

Closing this issue, if for some reason you feel that what I've described above doesn't correctly address your problem, please feel free to create a new issue. Mostly doing this for clarity ad to reduce our issues list down to a sane and relevant number of actionable tasks.
