### ISSUE TITLE
React-select style props issue:unexpected token if provided variable is spread.

### ISSUE THREAD

**Issue by FrankenDeba** [JedWatson/react-select#4245]
const customStyles = {
  menu: (provided, state) => ({
    ...provided,
    width: state.selectProps.width,
    borderBottom: '1px dotted pink',
    color: state.selectProps.menuColor,
    padding: 20,
  }),

  control: (_, { selectProps: { width }}) => ({
    width: width
  }),

  singleValue: (provided, state) => {
    const opacity = state.isDisabled ? 0.5 : 1;
    const transition = 'opacity 300ms';

    return { ...provided, opacity, transition };
  }
}

**Comment by ebonow** [comment]
Greetings @FrankenDeba ,

I believe you likely have another syntax error somewhere else as I am not having any issues using the styles you provided. 

Here is the codesandbox for you to compare in case you have any questions. 
https://codesandbox.io/s/react-select-styles-spread-syntax-error-m6v9v

Additionally, not rendering the provided styles for the control will have an impact on the display so I added that to the codesandbox example.

If this resolves your issue, please feel free to close this issue.

**Comment by bladey** [comment]
Thanks for the assistance @ebonow. @FrankenDeba please let us know if this should be re-opened.
