### ISSUE TITLE
UNSAFE_componentWillReceiveProps warning on react js

### ISSUE THREAD

**Issue by SL-CodeBlaster** [JedWatson/react-select#4246]
i have getting the warning about `UNSAFE_componentWillReceiveProps`. image attached.

[https://ibb.co/R7Wjdvg](url)

**Comment by ebonow** [comment]
Greetings @SL-CodeBlaster ,

This is a known issue and is already documented.
https://github.com/JedWatson/react-select/issues/4094

Please feel free to close this issue.
