### ISSUE TITLE
How to create a custom drop-down ?

### ISSUE THREAD

**Issue by stfenjobs** [JedWatson/react-select#4258]
hi there , I want custom drop-down ,

i use  `components={{ Option: CustomSelectOption,  }}` can custom  drop-down , but i don't know how to change the style to horizontal. like [stackoverflow] 

![image](https://user-images.githubusercontent.com/6580897/96669633-30361080-1390-11eb-861f-3c5baa92ba3b.png)

 

can you help me? thank you

**Comment by dakur** [comment]
@stfenjobs For questions there is obviously StackOverflow. But I guess it can be achieved with `styles` prop declaring it to be a [CSS grid](https://learncssgrid.com/).

**Comment by ebonow** [comment]
Greetings @stfenjobs ,

The approach suggested by @dakur works without much effort. 

Here is a quick sandbox demonstrating the menu list as a grid.
https://codesandbox.io/s/react-select-flex-menu-options-ye2b8?file=/example.js

The only thing left is to create your custom options.

**Comment by stfenjobs** [comment]
thank you very much @dakur  @ebonow
