### ISSUE TITLE
setstate in callbacks cause error

### ISSUE THREAD

**Issue by jamesjjk** [JedWatson/react-select#426]
Hi,

When calling setState from the onChange & onOptionLabelClick in both multi and non multi mode it resets the component. Is the component binding from the state or replicating state props to state? Makes it difficult to use this component as you cannot set state in the parent.

```
onChange(val) {
  this.setState({ value: val });
}

render(){
  <Select
  options={this.props.options}
  onChange={this.onChange.bind(this)} />
```

   }

**Comment by hoiyd** [comment]
see https://github.com/JedWatson/react-select/issues/383 and you may find the answer.
"So the solution is to set value=''" so that it uses that to call length on."

**Comment by mikakun** [comment]
same issue, value is set to ''

    changeSelectHandler: function(nv,sel) {

       // console.log(sel);
       // ...
       this.setState({chartData:newChart});
     }

    <Select 
    name='benchmarks'
    value=''
    options={this.selectOptions}
    multi={true}
    onChange={this.changeSelectHandler} 
    />

the first time clicking on select, the option selected remains & chart is updated as it should, the issue happens on a second select (whether multiple true or false does not change it): AFTER the setState is called (& chart updated as it should) the options selected are reset. However the change event is not fired.

am I missing stg ?

**Comment by mikakun** [comment]
i found a work around

in the handler

    this.setState({chartData:newChart, selectValue:nv});


and in render obviously

    value={this.state.selectValue}

this raise another issue which is value & label of options have to be the same otherwise we see the value in the selected options list, not the label (with some warning in the console)

I will open an issue about that

**Comment by rileyjshaw** [comment]
++, also noticed this issue. It's a pretty bad one, since the React docs recommend to link state to inputs like this.

**Comment by erchaves** [comment]
+1

**Comment by josantana** [comment]
+1

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
