### ISSUE TITLE
formatOptionLabel is always applied over formatCreateLabel

### ISSUE THREAD

**Issue by aSlug** [JedWatson/react-select#4260]
Currently it looks like there is no way to avoid `formatOptionLabel` to be applied also on the _create new..._ option generated with `formatCreateLabel`.

Suppose i have something like this: i want the _create new_ option to be always visible and open modal if selected. No problem, i can do it with `formatCreateLabel`
![chrome-capture1](https://user-images.githubusercontent.com/34537387/96900498-74a9d500-1492-11eb-9e35-dffd1b9135c9.gif)

Suppose now that i also want to add something to the existing options, like a clickable icon to see details, or something like that. Unfortunately such icon would be applied also on the _create new_ option.
![chrome-capture3](https://user-images.githubusercontent.com/34537387/96901346-6d36fb80-1493-11eb-9668-417199de467d.gif)

I may also try to use apply the option formatting only if the option has a `value`. It works only until the user types something, since it takes it as the `value`
![chrome-capture4](https://user-images.githubusercontent.com/34537387/96901694-e20a3580-1493-11eb-90e5-16fc54daab43.gif)

Looks like there is no way to avoid `formatOptionLabel` to be applied on it.

**Comment by Rall3n** [comment]
@aSlug You could avoid it if you check for the `__isNew__` property on the option. The `create new` option always has this property.

```jsx
<Createable
  formatOptionLabel={option => option.__isNew__ ? option.label : `${option.label} Whatever`}
/>
```

**Comment by aSlug** [comment]
Thank you very much 🙏 
In my case there were a couple of layers over the component hiding that property.
