### ISSUE TITLE
state value when no options are found

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4263]
With `isSearchable` enabled, is there a state value available for when no options are found in the react-select search?

**Use case:** I'm trying to add some custom css based on whether options are found in the search or not. To be precise, I want to make some icons in a `CustomControl` component turn red when no options are found for the given search.

I can see from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/components/Control.d.ts) that the only values available for state under Control are `isDisabled`, `isFocused`, and `menuIsOpen`.

Would it be possible to add another value called `state.noOptions`?

**Comment by Rall3n** [comment]
@cseas You could easily make a wrapper which would add this functionality.

Because the component adds a `NoOptionsMessage` component if there are no options found, we can create a custom component to set a state value if this component renders:

```jsx
const NoOptionsMessage = ({ selectProps: { setNoOptions }, ...props }) => {
  React.useEffect(() => {
    setNoOptions(true);

    return () => setNoOptions(false);
  }, [setNoOptions]);

  return <components.NoOptionsMessage {...props} />;
}

const customControlStyle = (provided, state) => ({
  ...provided,
  color: state.selectProps.noOptions ? 'red' : null
});

const NoOptionsSelect = () => {
  const [noOptions, setNoOptions] = React.useState(false);

  return <Select
    setNoOptions={setNoOptions}
    noOptions={noOptions}
    components={{ NoOptionsMessage }}
    styles={{ control: customControlStyle }}
  />
}
```

Only caveat is that the state is being reset to `false` if the focus is lost / the menu is closed.

**Comment by cseas** [comment]
Thanks a lot!
That works perfectly.
The state resetting to false is actually is a good thing because when focus is lost the entered text gets deleted as well so the icons return to their original color as they should.
