### ISSUE TITLE
innerProps for menuList not applied.

### ISSUE THREAD

**Issue by supersheen** [JedWatson/react-select#4265]
I am trying to remove the top and bottom white margin between menu and menuList, but seems the innerProp is not applied, here is example. Can you have a look and let me know why? thanks. 
https://codesandbox.io/s/react-select-v3-sandbox-forked-xe8ms?file=/example.js

**Comment by Rall3n** [comment]
@supersheen Unfortunately the example does not show what you are trying to accomplish / proof. Could you perhaps update the example?

**Comment by supersheen** [comment]
Thanks your reponse @Rall3n yes the example doesn't work, I am trying to figure it out. Here `<components.MenuList  {...props} innerProps={Object.assign({}, props.innerProps, {'data-role': 'menuList'})} />` I am hoping to add an attribute `data-role: menuList` in output to get rid of the top and bottom white margin using `padding-bottom: 0; padding-top: 0;` but it's not working. I checked source code, seems `innerProps` is not assigned for `menuList`? `menu` is working fine for me.

**Comment by supersheen** [comment]
![Screenshot 2020-10-29 at 18 54 51](https://user-images.githubusercontent.com/12728272/97619691-6f133880-1a18-11eb-9024-22fa262dff83.png)

**Comment by Rall3n** [comment]
@supersheen You can override the style using the styling framework.

Removing the styles for `paddingTop` and `paddingBottom` from the `menuList` styles should result in what you want to achieve.

```jsx
<Select
  styles={{
    menuList: ({ paddingTop, paddingBottom, ...baseStyles }, props) => baseStyles
  }}
/>
```

**Comment by supersheen** [comment]
thanks @Rall3n, I thought about that. Does it mean `menuList` doesn't support `innerProp`? I also need to add other none style props like `data-testId`.

**Comment by ebonow** [comment]
Greetings @supersheen ,

The code above is simply to address the styling of the component. You would still need to create your own custom menuList component if you need to modify the component in any way such as adding a data attribute.

If you need a look at how this would be done, you can refer to this example on how to get started. If you have an additional questions after taking a look, just let us know.

**Comment by ebonow** [comment]
@supersheen I wanted to revisit your question as I wasn't sure it was completely resolved. @Rall3n seems to have already answered your concern on styling the component. 

It seems that MenuList is unique in that it does not spread innerProps into the element as you can see [here](https://github.com/JedWatson/react-select/blob/998c979b4ed51ee39b87c9b2f0f03da440017dcf/packages/react-select/src/components/Menu.js#L370)

What you would have to do is either add a parent container:
``` JS 
const MenuList = ({ children, ...props }) => <components.MenuList {{...props}}><div data-role="menuList">{children}</div></components.MenuList>
```

Or create your own MenuList if you didn't want to risk introducing new DOM elements:
``` JS
const MenuList = props => {
const { children, className, cx, getStyles, isMulti, innerRef } = props;
  return (
    <div
      css={getStyles('menuList', props)}
      className={cx(
        {
          'menu-list': true,
          'menu-list--is-multi': isMulti,
        },
        className
      )}
      ref={innerRef}
      data-role="menuList"
    >
      {children}
    </div>
  );
```

I am not quite sure why innerProps is treated differently here vs other components and will look into getting a response so we can have better clarity if it's a bug or by design.

**Comment by pavelBondarenkoEPAM** [comment]
Hi mates. Where I can find types for this list of props?

> ```js
> const { children, className, cx, getStyles, isMulti, innerRef } = props;
> ```

**Comment by Methuselah96** [comment]
`MenuListProps`:

https://github.com/JedWatson/react-select/blob/3d33e7d7b8072392da149ad939df753a437917f3/packages/react-select/src/components/Menu.tsx#L379-L394

Which extends `CommonProps`:

https://github.com/JedWatson/react-select/blob/3d33e7d7b8072392da149ad939df753a437917f3/packages/react-select/src/types.ts#L80-L114).

**Comment by pavelBondarenkoEPAM** [comment]
@Methuselah96 Sorry mate, how can I use it in my case? I can't get it...

**Comment by Methuselah96** [comment]
Can you create a CodeSandbox with an example of what you're trying to do?
