### ISSUE TITLE
Cannot hide input spin buttons on Windows/Chrome

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [JedWatson/react-select#4266]
I am using `react-select` in my project and trying to hide the input spin buttons that appear on the google chrome (windows).
Tried to add the following styles but it didn't work.
```
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

input[type='number'] {
  -moz-appearance: textfield;
}
```
![image](https://user-images.githubusercontent.com/34172195/97692415-165ca200-1ae3-11eb-9dab-1aea223fbd8e.png)
Please let me know how to hide those spin buttons.  Thanks in advance.

**Comment by Rall3n** [comment]
@ThunderBoltEngineer It seems like you are trying to customize the component using custom components.

Could you provide an [CodeSandbox example](https://codesandbox.io/s/react-select-v3-sandbox-jgdch) with your implementation?

**Comment by ThunderBoltEngineer** [comment]
@Rall3n  Thanks for your attention.  
Those spin buttons are coming from the <input> element itself, not from the react-select component.  I tried to follow the css rules to hide those buttons but it didn't work.
I am not sure if it is OS/browser problem (Windows/Google Chrome) or somehow those styles are overwritten by the library internally.

**Comment by Rall3n** [comment]
The component uses a `<input type="text">` by default. Having the spinners would mean that the input's `type` attribute has been changed to `number`.

If you are not required to use a number input, try changing the attribute to `type="text"`.

**Comment by marianayap** [comment]
@ThunderBoltEngineer hello! is this issue taken?

**Comment by ThunderBoltEngineer** [comment]
@marianayap  It is not resolved yet.

**Comment by ebonow** [comment]
@ThunderBoltEngineer if you would like help with this issue, would you please kindly provide either your code or even better a codesandbox so we can better diagnosis the issue? 

As it stands, it appears that this is the result of a custom Input component with the prop "type=number" (as mentioned above). Any props passed to the Input component are added as attributes to the input element itself so that would be the first place to look and the only lead I have currently given only the description and screenshots.

**Comment by marianayap** [comment]
okay, I'll do it and post it here as soon as possible @ebonow @ThunderBoltEngineer

**Comment by ebonow** [comment]
@ThunderBoltEngineer Unfortunately, there have been no provided code samples or sandboxes. We will be closing this to focus on remaining react-select issues as this does not appear to be an issue with the library itself. If you wish to provide a codesandbox demonstrating the behavior, someone we may able to provide more direction on next steps and we can re-open this issue if necessary.
