### ISSUE TITLE
No values displayed after upgrade

### ISSUE THREAD

**Issue by stefancic** [JedWatson/react-select#4267]
I have upgraded from 1.1.0 to 3.1.0 and can't get the values to display on load. All I did was changed multi to isMulti, since this changed in the newest version, but I don't know if I need to change anything else. 

This worked in 1.1.0:

`        <Select
          className={`${touched && error ? 'form-input-error' : touched && (valid && input.value.length > 0) ? 'form-input-success' : ''} form-white mb-1`}
          name=""
          placeholder={placeholder}
          value={input.value}
          {...input}
          onBlur={() => {input.onBlur(input.value.value)}}
          options={options}
          isMulti={multi}
        />`

The problem is, that on the field load, the values are not displayed (only the placeholder) and onBlur is also not working.

**Comment by dakur** [comment]
@stefancic According to [migration guide](https://react-select.com/upgrade-guide) I do not see any problem. What's in `input` which you spread there? (`{...input}`) Does console in devtools output any error?

**Comment by stefancic** [comment]
Console does not output any error, if console logging input.value, it displays and changes okay, if I select the dropdowns, but the changes do not appear visually in the input field, neither values do appear when the inputs are loaded.

**Comment by dakur** [comment]
Are the items passed to `options` in format of `{label: string, value: string}[]`? (array of objects having keys `label` and `value` consisting of `string`s) That might be the issue. I do not know what was the option format in v1.

**Comment by stefancic** [comment]
Yes, here is an example:

options: [{"label":"General","value":"General"},{"label":"Individual","value":"Individual"},{"label":"Shipping","value":"Shipping"}]
input: {"name":"type","value":"General"}
Input.value: General

**Comment by dakur** [comment]
Ok. Try then to cut off props one-by-one starting with the least importants (classnames, placeholder, event listeners etc.). This way you'll go down to the one which causes problems.

Or you can pass **just** `options` first and see whether it works on clean Select without any other props.

**Comment by stefancic** [comment]
![Screenshot 2020-10-30 at 14 47 40](https://user-images.githubusercontent.com/15705409/97712550-e0a5c200-1abe-11eb-9930-757c165bec36.png)

Options are working and dropdown is working, the only problem is, the values are not displayed in the input. So I dont think there is a problem in the props.

**Comment by dakur** [comment]
Well it obviously must be, because it works in my case. :-) But I've understood better now. I suspect the `value` prop, because it is used to manage what should be render as selected. What is in `input.value`? If you have custom handler of state update, there's probably problem in it, otherwise just get rid of it.

**Comment by ebonow** [comment]
Greetings @stefancic,

I believe the issue is your `value` prop. The select expects the value to be an option and not just its value.

**Comment by stefancic** [comment]
So its like this, the inputs are first empty:

![Screenshot 2020-10-30 at 15 13 46](https://user-images.githubusercontent.com/15705409/97715399-9f171600-1ac2-11eb-9500-bc5f74fc78bb.png)

When clicking, the options are displayed:

![Screenshot 2020-10-30 at 15 13 50](https://user-images.githubusercontent.com/15705409/97715410-a3433380-1ac2-11eb-9aaf-9184bd25d530.png)

When selecting an option:

![Screenshot 2020-10-30 at 15 13 54](https://user-images.githubusercontent.com/15705409/97715446-afc78c00-1ac2-11eb-883d-2640b1e69fb0.png)

When clicking outside:

![Screenshot 2020-10-30 at 15 13 58](https://user-images.githubusercontent.com/15705409/97715460-b6560380-1ac2-11eb-833b-245bf510bc16.png)

It's strange, because in 1.1 of the plugin everything works okay, I don't know why the values dont load at initial load.

**Comment by dakur** [comment]
That's the point of upgrading a major version (1 -> 3). According to semver, it may contain backward incompatible changes.

So does it work now?

**Comment by ebonow** [comment]
@stefancic Would you kindly mind sharing an example of values are in your `input` prop that is being spread or create a CodeSandbox?

**Comment by stefancic** [comment]
No, it does not work, values are not rendered on initial load of inputs. 

Sample values:

options: [{"label":"General","value":"General"},{"label":"Individual","value":"Individual"},{"label":"Shipping","value":"Shipping"}]
input: {"name":"type","value":"General"}
Input.value: General

**Comment by dakur** [comment]
@stefancic Ok, I'm prettx confused now what's going on. I've prepared a codesandbox [in here](https://codesandbox.io/s/withered-mountain-2j7t2?file=/src/App.js) which works. Can you please edit it to whatever use-case you have so that we can see fully non-working example? Then we can help better.

**Comment by ebonow** [comment]
Let's break this down based on the relevant props.

```
const input = {"name":"type","value":"General"}

<Select 
  value={input.value} 
  {...input} 
  onBlur={() => {input.onBlur(input.value.value)}} 
/>
```

The `value` prop should be THE OPTION and not just the value of the option. In this case it should be:
`value={input}` and not `value={input.value}`. Additionally you could use a find method within your options to find the matching value if you wanted to sync the value from some outside source to your existing options doing something like this:
```
const value = options.find(opt => opt.value === input.value) || undefined;
```

`{...input}` seems redundant as it is already spreading the value in the prop declaration immediately before it. As mentioned above, this value will likely cause issues.

The `onBlur` method isn't apparent to me what the desired behavior is as an onBlur generally doesn't take a value.

Also worth mentioning is the lack of an onChange prop. If you want to define a value prop, you need to update the value onChange likely using React state. You may instead want to use `defaultValue`, but Ill run through both options. 

Try the following instead for an uncontrolled (component manages its own state internally) Select:
```
const placeholder = 'Izberi tip kupona...';
const options = [{"label":"General","value":"General"},{"label":"Individual","value":"Individual"},{"label":"Shipping","value":"Shipping"}];
const input = {"name":"type","value":"General"};

const defaultValue = options.find(opt => opt.value === input.value) || undefined;

<Select 
  className={`${touched && error ? 'form-input-error' : touched && (valid && input.value.length > 0) ? 'form-input-success' : ''} form-white mb-1`} 
  name="some_name" 
  placeholder={placeholder} 
  defaultValue={value} 
  options={options} 
  isMulti={multi} 
  />
```

OR if you want a controlled component (declaring/setting value outside of the select) you would need to add an onChange event and react State to update the value sent to the Select when an item is chosen.

```
const [ value, setValue ] = useState(defaultValue);
const onChange = opt => setValue(opt);

<Select ...otherPropsDeclaredAboveInFirstExample value={value} onChange={onChange} />
```

Please let me know if this helps or if it's unclear.

**Comment by stefancic** [comment]
Hi @ebonow and thanks! I got it to work now to a point that the values render and changes can be made. The only problem is now that the changes are no longer saving. Can you maybe let me know of a working onBlur with this example? Before the onBlur effect gave the form-input-success class and changed the value properly.

**Comment by ebonow** [comment]
@stefancic Sorry for the late reply.

You would need to call your validation and touched variables onBlur.

```
const [ valid, setValid ] = useState();
const [ error, setError ] = useState();
const [ touched, setTouched ] = useState();

const onBlur = () => {
  setTouched(true);

  const getValidationErrors = () => { /* your validation logic... */ }

  const hasError = getValidationErrors();
  setError(!!hasError);
  setValid(!hasErrror);
}

return <Select onBlur={onBlur} ... />
```

**Comment by ebonow** [comment]
@stefancic just checking in to see if this is still an issue or if this can be closed
