### ISSUE TITLE
How do I reset/update the select with a button press?

### ISSUE THREAD

**Issue by UPLukeet** [JedWatson/react-select#4268]
I am trying to implement a button that resets the value of the selects onclick(using hooks), but currently the setting the value back to null doesn't update the select is there any way to do this? I feel like it should be this simple? but clearly not lol

```
const [series, setSeries] = useState(null);

 const seriesOptions = [
    { value: "1", label: "1" },
    { value: "2", label: "2" },
    { value: "3", label: "3" },
    { value: "4", label: "4" },
    { value: "5", label: "5" },
    { value: "6", label: "6" },
  ];

  const Reset_Data = () => {
    setSeries(null);
  };

  return (
<div>
<Select
              className={"poloOption_container"}
              classNamePrefix={"poloOptions"}
              defaultValue={series}
              onChange={setSeries}
              options={seriesOptions}
              styles={colourStyles}
              placeholder={"Polo seies"}
            />
<p onClick={Reset_Data}>Start Again</p>
</div>
)
```

**Comment by Rall3n** [comment]
@UPLukeet you are using the wrong prop for your value. The `defaultValue` sets the value for first render, best used for uncontrolled scenarios. 

Instead use the `value` prop.

**Comment by UPLukeet** [comment]
oh ok thanks I will give it a try and see if the result is different

**Comment by bladey** [comment]
@UPLukeet please let us know if this hasn't solved your problem. Thanks @Rall3n.
