### ISSUE TITLE
Problems with positioning options list

### ISSUE THREAD

**Issue by yantakus** [JedWatson/react-select#427]
I'm trying to style react-select in material design style (for example: https://elements.polymer-project.org/elements/paper-dropdown-menu?active=paper-dropdown-menu&view=demo:demo/index.html). To make options list overflow the input field like in the example above, I have to set `.Select-menu-outer` `top` property to `0`. But in this case any option can be selected, because when clicking on the arrow or the input, options list appears and disappears immediately without possibility to choose an option. This seems to be a JS problem.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
