### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by mtmacdonald** [JedWatson/react-select#4272]
Can we please have React 17 support so I don't get this peer dependency warning upon `npm install` in my React 17 projects. Thanks!

npm WARN react-select@3.1.0 requires a peer of react@^16.8.0 but none is installed

**Comment by nvnran** [comment]
Looks like i am not the only one facing this issue.

**Comment by Methuselah96** [comment]
Resolved by https://github.com/JedWatson/react-select/pull/4275 and https://github.com/JedWatson/react-select/pull/4326.
