### ISSUE TITLE
SyntaxError: Select.js: Unexpected token, expected "," (3:32)

### ISSUE THREAD

**Issue by realmayus** [JedWatson/react-select#4274]
I tried to run the example code but React tells me that there's a syntax error in the library:
![image](https://user-images.githubusercontent.com/38134006/98398205-dfe1d280-2060-11eb-8d46-cdbb483a221e.png)

My code (the example)
```jsx
const options = [
    { value: 'chocolate', label: 'Chocolate' },
    { value: 'strawberry', label: 'Strawberry' },
    { value: 'vanilla', label: 'Vanilla' },
];

export default function App() {
    const [selectedOption, setSelectedOption] = useState(null);

    return (
        <div className="App">
            <Select
                defaultValue={selectedOption}
                onChange={setSelectedOption}
                options={options}
            />
        </div>
    );
}
```
I'm using React 17.0.1 and react-select ^3.1.0.

**Comment by dakur** [comment]
@realmayus It's because the code is written in Flow, which is typing superset over Javascript. I think the problem is well readable from the screenshot you've attached – if you look on the line 3, above the `^` sign (which highlights the place where the error happened) you see there is keyword `type` which you do not know from JS world. Try to remove it and you'll see what happens next.

**Comment by trodix** [comment]
> @realmayus It's because the code is written in Flow, which is typing superset over Javascript. I think the problem is well readable from the screenshot you've attached – if you look on the line 3, above the `^` sign (which highlights the place where the error happened) you see there is keyword `type` which you do not know from JS world. Try to remove it and you'll see what happens next.

So, what is the solution for this issue ? because I don't know flow and I don't want to use it for make react-select working on my app.

**Comment by ebonow** [comment]
@realmayus would you please review this and see that either of these identify or resolve your issue?

**Comment by realmayus** [comment]
Yup, thanks, that worked!

**Comment by LeoZaroff** [comment]
Hello,

This solution didn't work for me -- my import for react-select is `import Select from "react-select";` but I still receive the same error. Any ideas for what could be causing this? The module was working perfectly until it suddenly started throwing this error.

Thanks.

**Comment by ebonow** [comment]
@zimaRed would you mind pasting a codesandbox of your code so we can take a look and assist?

**Comment by 6a6ak** [comment]
I'm surprised that after about 50 years, the debugger still can't recognize that I left a short parenthesis and shows the same message to all errors.

**Comment by bilalsarimeseli** [comment]
Hello everyone; 

Appreciating this channel of conversation profusely, while trying to find a solution to my similar problem, I deemed to ask mine here asking your pardons. Same, syntax error, from React Props syntax error. Here is the code. Your help is greatly applauded. If not, no problem, stay y'all safe. 

`          
exact
  48 |           path="/"
> 49 |           render={(props) => (props.user?.id ? <Home /> : <Signup />)}
     |                                          ^
  50 |         />
  51 |         <Route path="/home" component={Home} />
  52 |       </Switch>
`

**Failed to compile.

./src/routes.js
Syntax error: Unexpected token, expected , (49:41)**


Thanks so much.
