### ISSUE TITLE
Move the 'create-option' to the the top (first option in the list)

### ISSUE THREAD

**Issue by RiatIO** [JedWatson/react-select#4276]
Hello,
Sorry for asking a question here, tried StackOverflow, no one answered there:

Is it possible to have the 'create a new option' to be the first item in the list, such that if the user just type and press enter he searches on the query - and if the user sees some options in the dropdown, the user can press the arrow button down or select one from the list.

**Comment by ebonow** [comment]
Greetings @RiatIO ,

Have you tried 
```
createOptionPosition="first"
```

https://react-select.com/props#creatable-props

**Comment by RiatIO** [comment]
Thank you so much, @ebonow!
