### ISSUE TITLE
consider releasing pinned dep on @emotion/core@10.0.9

### ISSUE THREAD

**Issue by VinSpee** [JedWatson/react-select#4278]
Hi! I am adding `chakra-ui` to a project. It is also directly dependant on `@emotion/core`. It, however, uses `v10.0.35`. They do [cite some real reason](https://github.com/chakra-ui/chakra-ui/issues/2414) for pinning to an exact version.

I'm wondering, is it possible for `react-select` to be more permissive with the required version?

When react-select's version conflicts with another library's version, it can create some catastrophic problems.

**Comment by chinanderm** [comment]
I'm running into this same problem as well.

**Comment by Methuselah96** [comment]
@VinSpee We've upgrade to Emotion 11 in 4.0.0 (https://github.com/JedWatson/react-select/pull/4283), so I don't think it would be possible to allow Emotion at v10 at this time.
