### ISSUE TITLE
CreatableSelect defaultInputValue property display issue 

### ISSUE THREAD

**Issue by DScorpion** [JedWatson/react-select#4281]
Created a CreatableSelect control and set the defaultInputValue property. The default value gets displayed on the control on while control is loaded, but first time when I click on the control ( either on the the textbox or the drop down symbol ) the list does not display, on clicking again the default value is replaced by 'select...' and then the list is displayed. I would think  the default value should not be cleared when I click on the control unless I explicitly clear it. I would want the default value to remain until I make a selection in the dropdown or clear the value myself? can someone please help?

import React, { Component } from 'react';
import CreatableSelect from 'react-select/creatable';

export default class CreatableSingle extends Component<*, State> {
  handleChange = (newValue: any, actionMeta: any) => {
    console.group('Value Changed');
    console.log(newValue);
    console.log(`action: ${actionMeta.action}`);
    console.groupEnd();
  };
  handleInputChange = (inputValue: any, actionMeta: any) => {
    console.group('Input Changed');
    console.log(inputValue);
    console.log(`action: ${actionMeta.action}`);
    console.groupEnd();
  };
  render() {
    return (
      <CreatableSelect
        isClearable
        defaultInputValue ={'Yellow'}
        onChange={this.handleChange}
        onInputChange={this.handleInputChange}
        options={ [
          { value: 'ocean', label: 'Ocean' },
          { value: 'blue', label: 'Blue' },
          { value: 'purple', label: 'Purple' },
          { value: 'red', label: 'Red' }]}
      />
    );
  }
}

**Comment by ebonow** [comment]
Greetings @DScorpion ,

`defaultInputValue` pertains to the input that is displayed in the text input. The default behavior of react-select is that the input will be cleared when a user "blurs" into/out of the input.

What you are more likely looking for instead is `defaultValue`

In this case, 
```
defaultValue={{ value: 'yellow' , label: 'Yellow' }}
```

Please let me know if this resolves your issues or if I am misunderstanding your problem.

**Comment by bladey** [comment]
Thanks for your help @ebonow! @DScorpion please let us know if this doesn't resolve your issue and we'll re-open the issue.

**Comment by DScorpion** [comment]
> Greetings @DScorpion ,
> 
> `defaultInputValue` pertains to the input that is displayed in the text input. The default behavior of react-select is that the input will be cleared when a user "blurs" into/out of the input.
> 
> What you are more likely looking for instead is `defaultValue`
> 
> In this case,
> 
> ```
> defaultValue={{ value: 'yellow' , label: 'Yellow' }}
> ```
> 
> Please let me know if this resolves your issues or if I am misunderstanding your problem.

Thank you @bladey appreciate the response and help..
