### ISSUE TITLE
Getting issue in all files of react-select

### ISSUE THREAD

**Issue by hesamZandian** [JedWatson/react-select#4284]
node_modules\react-select\src\theme.js: Unexpected token (3:12)

1 | // @flow
2 |

3 | import type { Theme } from './types';
| ^
4 |
5 | export const colors = {
6 | primary: '#2684FF',

**Comment by hesamZandian** [comment]
can someone please help?

**Comment by Methuselah96** [comment]
Can you post the code you're using to import `react-select`?

**Comment by hesamZandian** [comment]
import Select from 'react-select'

**Comment by hesamZandian** [comment]
> Can you post the code you're using to import `react-select`?

import Select from 'react-select'

**Comment by Methuselah96** [comment]
Are you absolutely sure this is the only place you're importing from `react-select`?

**Comment by hesamZandian** [comment]
> Are you absolutely sure this is the only place you're importing from `react-select`?
yes
when I hover on react-select this route displayed:
C:/Users/.../AppData/Local/Microsoft/TypeScript/4.0/node_modules/@types/react-select/index
