### ISSUE TITLE
React-Select display wrong

### ISSUE THREAD

**Issue by nguyenvantruong17** [JedWatson/react-select#4287]
Before open the menu list
<img width="1439" alt="Screen Shot 2020-11-20 at 13 22 52" src="https://user-images.githubusercontent.com/18642063/99766392-92bb3180-2b33-11eb-9c2f-3e411300713a.png">

After opening the menu list
<img width="1440" alt="Screen Shot 2020-11-20 at 13 23 02" src="https://user-images.githubusercontent.com/18642063/99766382-8f27aa80-2b33-11eb-8b78-c270a266a39e.png">

My expectations
<img width="1241" alt="Screen Shot 2020-11-20 at 13 29 23" src="https://user-images.githubusercontent.com/18642063/99766804-6f44b680-2b34-11eb-8f00-54faf492cd9b.png">

Does anybody know why it has occurred? It seems the height of the container, not auto-increment.

**Comment by Rall3n** [comment]
@nguyenvantruong17 Would you be so kind and provide a minimal reproducible example using CodeSandbox, as it was requested in the issue template you deleted.

**Comment by ebonow** [comment]
Greetings @nguyenvantruong17 

From looking at your screenshot, it appears the parent container has overflow: hidden so the menu is being clipped. It's hard to tell without seeing code/css so if that's not the issue, providing some code may help better diagnose the issue.

**Comment by nguyenvantruong17** [comment]
@Rall3n @ebonow 
Sorry. My mistake. I've set `overflow-x: hidden` for the HTML tag. I solved this issue by removing it.
Once again, sorry for bothering guys.
I'll close this issue.
