### ISSUE TITLE
Add a backdrop props

### ISSUE THREAD

**Issue by tompap** [JedWatson/react-select#4288]
When using react-select in a portal or fixed position, if the select has a parent with a overflow:scroll, then menu is not following the "input" when you scroll.

By adding a backdrop to the select, we can prevent scroll event on parent element when the menu is opened

I make an example here:

https://codesandbox.io/s/react-codesandboxer-example-forked-r2tw2?file=/example.js

But maybe this could be a "new props" to add ?

**Comment by Rall3n** [comment]
@tompap There already exists a prop which prevents scrolling when the dropdown is open. It is called `menuShouldBlockScroll`.

**Comment by ebonow** [comment]
Greetings @tompap ,

Can you confirm if this resolves your issue or is there anything else left to resolve?

**Comment by ebonow** [comment]
In an effort to close out stale issues, I will be closing this. Please feel free to reply if this remains an issue for you and we can reopen if necessary.
