### ISSUE TITLE
foating menu list react-select

### ISSUE THREAD

**Issue by Rashawa97** [JedWatson/react-select#4291]
![errorUI](https://user-images.githubusercontent.com/45872095/99907218-4105d900-2ce4-11eb-904f-32f3f2f8df95.png)

i have this issue the menu list floats over other components

**Comment by ebonow** [comment]
Greetings @Rashawa97 

This is a layout issue and not a react-select issue.

You can go to this [link](https://coder-coder.com/z-index-isnt-working/#4-the-element-is-in-a-lower-stacking-context-due-to-its-parents-z-index-level) to learn more about stacking order. Long story short is that the z-index only applies to the elements within the scope of the parent so you'd want to set the z-index on the *row* and not the col or nav element.

Setting `overflow: hidden` on the row that contains your main content would also be an option, but regardless, none of this is related to react-select.

In any case, hope this helps and please feel free to close this issue.

**Comment by bladey** [comment]
Thanks for the assistance @ebonow, @Rashawa97 please let us know if this issue should be re-opened.
