### ISSUE TITLE
Remove Border Not Working in Select and CreatableSelect

### ISSUE THREAD

**Issue by ankitgoyal100** [JedWatson/react-select#4303]
I am using this code to try and remove the border in my `Select` and `CreatableSelect` component:

```
style={{
  control: (base: any) => ({
    ...base,
    borderRadius: 0
  }),
  menu: (base: any) => ({
    ...base,
    borderRadius: 0
  }),
  menuList: (base: any) => ({
    ...base,
    borderRadius: 0
  })
}}
```

Nothing is changing. Is this a known bug?

**Comment by Rall3n** [comment]
@ankitgoyal100 Please check your code again. It seems like you have a typo on the prop name.

The name for the styling prop is `styles` (plural).

**Comment by ebonow** [comment]
Greetings @ankitgoyal100 ,

Perhaps you meant `borderWidth: 0` or `border: 'none'` as borderRadius would simply remove the rounded corners but not the borders. You may also want to look into removing the boxShadow from the Control as well for the focus effect.

Please feel free to let us know if you are still having issues and if not, please also feel free to close this issue.

**Comment by ankitgoyal100** [comment]
@Rall3n @ebonow thank you both for the speedy responses! it works 👍

**Comment by ebonow** [comment]
BTW: Here's a codesandbox I had put together to [demonstrate an inline react-select](https://codesandbox.io/s/react-select-inline-kk1u6?file=/example.js). Perhaps you will find it helpful as it deals with overriding several of the inline styles.
