### ISSUE TITLE
Key press issue with custom Control

### ISSUE THREAD

**Issue by jbyomuhangi** [JedWatson/react-select#4317]
#4279 
Wasn't sure how to reopen an issue so thought I'd open a new one 

I think I have a better way to illustrate the problem and what I am trying to do. Here is the updated [code sandbox link](https://codesandbox.io/s/dreamy-bouman-03usu?file=/src/App.js). 

In this example, I want to open the menu by clicking something, could be anything, and still have the normal behavior of the selector. Given the selector is not searchable the docs say this:

>  If the select is not searchable, a dummy input is rendered instead

It appears that this dummy input that is rendered when a selector is not searchable has control of the key presses and if it it not rendered, key presses are not handled correctly. This can be seen in the sandbox link, try doing the following to see the behavior:
1. Click hello button to open menu
2. Use the arrows to navigate the list, then hit `Enter` to select an option.  
3. Comment out line 20 (<div style={{ position: "absolute" }}>{props.children[0]}</div>) and repeat steps 1 and 2

You will see that when you comment out line 20, you lose the keyboard controls, so my question is, why does this happen, and what component is responsible for the focus management?

How can I achieve what I'm trying to do with react-select?

**Comment by ebonow** [comment]
Closing this as a duplicated issue.
