### ISSUE TITLE
Uncaught error: Element type is invalid

### ISSUE THREAD

**Issue by corfizz** [JedWatson/react-select#4319]
I installed react-select with npm install react-select

Whenever I try to use a Select component in my project I get these messages in the console and the script crashes:

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`
`Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

I have version 3.1.1 and the latest react version in my package.json

My test case:

````
import Select from 'react-select';
...
const options = [
            { value: 'chocolate', label: 'Chocolate' },
            { value: 'strawberry', label: 'Strawberry' },
            { value: 'vanilla', label: 'Vanilla' },
      ];
<Select options={options} value={options[0]} />
````

**Comment by Rall3n** [comment]
@corfizz I could not reproduce the error using your example.

* Are you sure the error has to do with the `Select` component?
* Is there more code related to your usage of the `Select` component?
* If so, could you create a [minimal reproducible example using CodeSandbox](https://codesandbox.io/s/react-select-v3-sandbox-jgdch)?

**Comment by corfizz** [comment]
Thanks for your reply. I was importing a component in a file with a .mjs extension. When I changed it to .js the error went away. However strangely I could not reproduce this on CodeSandbox.

**Comment by ebonow** [comment]
Greetings @corfizz 

Is this still an issue for you or can this be closed?

**Comment by ebonow** [comment]
In an effort to close out inactive issues, I will be closing this. If you continue to have any other problems or questions, please feel free to reply or open a new issue.
