### ISSUE TITLE
Styles not copying over on bundle with browserify.

### ISSUE THREAD

**Issue by MattMcFarland** [JedWatson/react-select#433]
If using `browserify` and `package.json` to indicate which transforms to be used _(which is the most expedient transform method)_ you cannot use `lessify` because transforms _**do**_ _**not**_ apply across module boundaries.

[Per the Browserify Handbook](https://github.com/substack/browserify-handbook#browserifytransform-field) + [node_modules](https://github.com/substack/browserify-handbook#node_modules)  **Transforms DO NOT apply across module boundaries!**

The workarounds are:
- Use alternative transform methods (spelling it out in command line, using task runner plugins, etc)
- Manually copying LESS files over.
- Overwriting react-select `package.json` to include browserify transforms.

**I have an aging pull request to fix this:** https://github.com/JedWatson/react-select/pull/412

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
