### ISSUE TITLE
ValueContainer's getValue method returns an array for non-isMulti type selects

### ISSUE THREAD

**Issue by ArnaudWeyts** [JedWatson/react-select#4332]
### Are you reporting a bug or runtime error?
* A bug

According to the typings, the value returned by the `ValueContainer's` `getValue` should depend on the `isMulti` boolean, however it seems like it always returns an array of Options.

### Demonstration of the issue

https://codesandbox.io/s/react-select-v3-sandbox-forked-w3k32?file=/example.js

**Comment by Methuselah96** [comment]
Thanks for the issue! The types are actually wrong for this one. The `getValue()` function on the common props will arrays return an array of options even on a single-select. I've made a PR to fix the issue on Definitely Typed: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50129.

Let me know if you need anything else. I'll close this issue once the PR on DefinitelyTyped is merged.

**Comment by ArnaudWeyts** [comment]
> Thanks for the issue! The types are actually wrong for this one. The `getValue()` function on the common props will always return an array of options even on a single-select. I've made a PR to fix the issue on Definitely Typed: [DefinitelyTyped/DefinitelyTyped#50129](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50129).
> 
> Let me know if you need anything else.

Allright, thanks!
