### ISSUE TITLE
Change BackgroundColor

### ISSUE THREAD

**Issue by MZarif00** [JedWatson/react-select#4334]
Hello , I want to change the background color of control and drop down indicator together , but I can't .
When I change the background color of control , the drop down indicator changed its position . Thank for your help .

**Comment by ebonow** [comment]
@MZarif00 without sharing your code implementation, I would have to guess that you are overriding the styles without spreading the existing provided css styles.

Working Demo: [codesandbox](https://codesandbox.io/s/react-select-papayawhip-4zn1u)

```js
const styles = {
  control: (css) => ({ ...css, backgroundColor: 'papayawhip' })
};

return < Select styles={styles} />
```

Please let us know if this resolves your issue.

**Comment by MZarif00** [comment]
@ebonow 
Thank you . It works
