### ISSUE TITLE
Hover over Disabled react-select not working

### ISSUE THREAD

**Issue by JeffersM963** [JedWatson/react-select#4335]
Hi,

I am trying to set the cursor to not-allowed when the react-select is disabled, so it is consistent with the other text fields on my page. I have tried overriding styles, components and everything else I can think of, but cannot get it to recognise the hover event when disabled. I have got it pointing to the correct classname proven by the following.

The following CSS works when the react-select is disabled (the background turns green):

```
        .react-select.react-select-primary .react-select__control.react-select__control--is-disabled
        {
            background-color: green;
        }
```

However, the following CSS DOES NOT work when the react-select is disabled (the background turns green):

```
        .react-select.react-select-primary .react-select__control.react-select__control--is-disabled:hover
        {
            cursor: not-allowed;
        }
```

Here is the Component:

```
                <Select
                    className="react-select react-select-primary"
                    classNamePrefix="react-select"
                    name="clientInput"
                    options={
                        clientList.map((client, index) => {
                            return {
                                label: client.Name,
                                value: client,
                                key: index
                            }
                        })
                    }
                    placeholder="Select Client ..."
                    onChange={handleChange}
                    valid={clientSelectionValid}
                />

```
Any ideas would be greatly appreciated

**Comment by ebonow** [comment]
Greetings @JeffersM963 ,

For starters, you don't need to add the hover pseudo selector for `:hover` as it's already implied for the cursor. One of those things I still need to remind myself every now and then.

To answer your question, the `isDisabled` styling also adds `pointer-events: none` so you need to override it to get a cursor to appear.

```css
.react-select.react-select-primary .react-select__control.react-select__control--is-disabled
{
  pointer-events: auto;
  cursor: not-allowed;
}
```

Working demo: [codesandbox](https://codesandbox.io/s/react-select-disabled-control-cursor-ozw67?file=/src/App.js)

I'll mark this as closed, but if you come across any issues or further concerns we can always re-open if necessary.

**Comment by JeffersM963** [comment]
Many thanks for that. I did see that in container.js:

`  pointerEvents: isDisabled ? 'none' : null, // cancel mouse events when disabled`

and tried setting it to someting else, but did not tray "auto".

Appreciate the quick turnaround.

I have another question around validation and setting the field to green with the green tick (once again to make it consistent), but will raise that in another question.

Once again, many thanks.
