### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_this3.getInputNode().focus')

### ISSUE THREAD

**Issue by liamcardenas** [JedWatson/react-select#434]
<img width="507" alt="screen shot 2015-09-08 at 6 00 22 pm" src="https://cloud.githubusercontent.com/assets/5027235/9750952/9208a426-5653-11e5-9bf0-779921965681.png">

I get this when a user selects a delete option in the dropdown, which then delete the entire row of the table containing the select box. Do you think this is the cause of the error? Everything is working properly, but I would like to not get this error if possible.

Thanks

**Comment by jorrit** [comment]
Same as #208 ?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
