### ISSUE TITLE
Option Menu doesn't close when tapping / clicking away on iOS Safari

### ISSUE THREAD

**Issue by jwarning** [JedWatson/react-select#435]
When you try to click out from the dropdown menu on an iPad for example the options menu doesn't automatically close. This issue may possibly explain the cause: https://github.com/facebook/react/issues/134. React 0.14 supposedly may fix this issue, but it may be worth noting for now anyway.

**Comment by jooj123** [comment]
This is fixed in this PR: 
https://github.com/JedWatson/react-select/issues/435
