### ISSUE TITLE
Invalid html inside of the Input element in a searchable select

### ISSUE THREAD

**Issue by Siggnja** [JedWatson/react-select#4350]
For some reason this style is being applied to the Input element in a searchable Select. This causes the html to become invalid since `label: input;` is not a valid css style. 

https://github.com/JedWatson/react-select/blob/a0133f19f45eb2dc9a2faebd74e18f44da7d509b/packages/react-select/src/components/Input.js#L33

**Comment by manvydasu** [comment]
It was added with this PR: #3492 

In my opinion, it does not make much sense to add invalid css inr order to make it easier to inspect elements. Perhaps someone else has better insights

**Comment by Siggnja** [comment]
It does not make any sense. If you want something like this it should only be applied during development builds.

**Comment by ebonow** [comment]
I agree that it doesn't make sense and have a note to ask about this with Jed. 

I do see this in the code for other custom components as well. Can I ask what HTML validator you are using and also if you could take a screenshot of the css being applied? While I see the label in code, I am not seeing it in the rendered css.

**Comment by ebonow** [comment]
Greetings @Siggnja I did a bit more digging

I was confused about how you were coming to the conclusion that the HTML was invalid and assumed you were using some kind of HTML validator. To my knowledge, unknown style properties does not "cause invalid HTML" as it's the basis of vendor prefixes.

The main source of my confusion was that there was no `label` css style being generated in the DOM or styles.

TIL that the `label` property is instead an [Emotion api feature](https://emotion.sh/docs/labels) that allows text to be appended to the generated classNames to add more readability to the components in the DOM. 
ie: `css-yk16xz`  =>  `css-yk16xz-control`

Given this, it seems that the title is a bit of a red herring as it is not rendered at all to the DOM. I will be closing this issue, but feel free to reply with any questions and I'll be happy to look into any other concerns you might have.
