### ISSUE TITLE
React Select v2.4.4 is unstyled and displaying aria message text

### ISSUE THREAD

**Issue by NikhilAnand95** [JedWatson/react-select#4357]
I am using react-select v2.4.4 for a dropdown list in a react v15.6.2 project with material-ui. However, the react-select component is displaying some unnecessary details whose source I am unable to find. [This image](https://drive.google.com/file/d/1N45SzWzXOVWONx_0kJuI5adWFezhjtlq/view?usp=sharing) shows the components used in my code. Row 3 with title IAE is the react-select component. When I click on the dropdown arrow, [this](https://drive.google.com/file/d/1Kzfkpfvvh9zIefqJ6gNpY4H-p1oTd4qa/view?usp=sharing) is what is being displayed. This description is nowhere present in the code. On trying to click/select on the description, it reverts to the first image. Can someone guide me as to what could be causing this issue? Is it a known issue or a one-off case that I am facing and how can I resolve it. I have pasted the react-select part of the code below.

`const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' },
]`

`<Select
   options={options}
   placeholder={'Enter Value'}
   isSearchable={true}
/>`

PS. I cannot upgrade the react-select version since this is the latest my project is able to support.

**Comment by ebonow** [comment]
Greetings @NikhilAnand95 

This is likely a styling issue of some sort as the Select in your examples are missing borders, flex, and then also not properly making the aria live messaging visually hidden. 

My guess would be that there is likely some conflict with Emotion which is used to provide styles to the components.

In regards to your setup, here is a codesandbox with react v15.6.2 and react-select v2.4.4 which seems to be working fine: [codesandbox](https://codesandbox.io/s/quirky-haslett-k4pzx?file=/src/App.js)

Do you have any other data that we can use to identify the problems you are running into? Some other things to look at:
 - Are you using SSR?
 - Are you overriding any styles that might be conflicting?
 - Are you using any library that strips inline styles?
 - Is there another library using emotion that might be causing conflicts? 
 - Is this being run in react-window or some other popup library?
 
Would love to help more though I am unsure how to move forward without knowing more details about your environment and web application build, but happy to help you investigate.

**Comment by ebonow** [comment]
Also, I am editing your title to help others out who may later be searching for the same issues you are experiencing. The details you are referring to are used for accessibility purposes. This text uses the aria live messaging api to provide audio prompts for screen readers.

**Comment by marcopaivaa** [comment]
Greetings @ebonow !

I'm suffering with this issue too (or a similiar one), when running locally [everything works perfectly](https://drive.google.com/file/d/13qXRV85VP9oSra-GtcjAVfjpGaQ5_TJl/view), but when published (webpack release with micro frontend approach), [this ](https://drive.google.com/file/d/18FI3vlFjqbNH66PojH7Y3ob6xyGxDZQA/view)happen... weirdo that's intermittent, doesn't happen every time...

Both select component are in distinct projects, without any custom classes. I'm using the latest version (3.1.0/3.1.1)

**Comment by ebonow** [comment]
Perhaps related to this? https://github.com/JedWatson/react-select/issues/3309

**Comment by marcopaivaa** [comment]
> @marcopaivaa Perhaps related to this? #3309

Thanks @ebonow, I'll try this and give you feedback later, if it works.

**Comment by tjg37** [comment]
I was also experiencing the same issue using a CRA application. When running locally there is no issue, but when I build and deploy using CSR the `Select` components are "unstyled" and display aria message text as described by @marcopaivaa and @NikhilAnand95.

I'm using the following packages:
- react: 16.8.6
- react-select: 3.2.0
- @emotion/react: 11.1.1
- @emotion/styled: 11.0.0

The `Select` component is used in multiple components (Components A). There is one component that contains both the `Select` component and an `@emotion/styled` component (Component B). Upon initial observation the `Select` appears to be intermittently "unstyled", however upon further inspection it would appear that `@emotion/styled` is overwriting the styles for the `Select` component. 

**Scenario 1**
1. Navigate first to Component B and the `Select` is styled correctly. 
2. Navigate to any Component A and the `Select` is still styled correctly. 
3. Navigate to either Component A or B and the `Select` is still styled correctly. 

**Scenario 2**
1. Navigate first to Component A and the `Select` is styled correctly. 
2. Navigate to Component B and the `Select` is "unstyled" and aria message text displayed. 
3. Navigate back to Component A and the `Select` is "unstyled" and aria message text displayed. 

**Scenario 3**
1. Navigate first to any Component A and the `Select` is styled correctly. 
2. Navigate to any Component A without navigating to Component B and the `Select` is still styled correctly. 

It would appear that `@emotion/styled` is overriding the styles for the `Select` component if the @emotion/styled component is rendered after the `Select` component is first rendered as suggested by @ebonow. 

To fix the issue I replaced `@emotion/styled` with the `styled-components` package and there were no longer any conflicts between the packages.

**Comment by ebonow** [comment]
@tjg37 If you are using Emotion 11, then I would advise upgrading to v4 of react-select as it upgraded it'd dependency on Emotion to v11.

**Comment by ebonow** [comment]
@marcopaivaa just wanted to follow up and see if you had success with any of the recommended methods from the other thread.

**Comment by marcopaivaa** [comment]
Greetings @ebonow!
  
So, I tried some of the methods reported in #3309, but I was unsuccessful ... However, I realized that the scenarios described by @tjg37 are the same as mine ... So we removed the emotion from ours components and, at least for now, there was no more css conflict with emotion in react-select lib... We made these adjustments yesterday, so it's still being tested to confirm if the problem has been solved.

**Comment by ebonow** [comment]
@marcopaivaa I wanted to follow up and see if your issues were resolved.

As a side note, I wanted to share that we are going to be exploring an unstyled version of react-select in the future to shed Emotion as a dependency for those experiencing issues like these.

**Comment by ebonow** [comment]
Greetings, 

In an effort to give more visibility to existing bugs we will be closing this out. The issue seems to be related here to conflicting versions of Emotion, but SSR users may also be interested in https://github.com/JedWatson/react-select/issues/3309 for more information

**Comment by IDrissAitHafid** [comment]
I have the same issue it happens only for some devices, also, on screen readers. Here's how `CreatableSelect` looks: 

![Screenshot_20230827_164045](https://github.com/JedWatson/react-select/assets/31975500/ffca2ba3-47c0-4ccc-a7ed-36b016fb2059)


I'm using the following packages:
* react: ^18.2.0
 * react-select: ^5.7.4
 * remix-run: ^1.16.1
 * tailwindcss: ^3.1.8

More info:
* My app is SSR, and I have this problem on all environments dev and prod (I have tested everything said here #3309).
* the app is rendered inside an iframe
* more details can be found on [this discussion](https://github.com/JedWatson/react-select/discussions/5719)

Is there some conflicts between tailwind and react-select styles? 
Did anyone had this problem and solved it? 
Is there anyway to just disable accessibility features on react-select?

**Comment by IDrissAitHafid** [comment]
It turns out on my case it is a hydration problem, using `hydrateRoot` doesn't append the styles to the head, I used `hydrate` instead which resolved the problem for the moment. 

For more details check [this Remix discord thread](https://discord.com/channels/770287896669978684/1060684366071738491)

**Comment by IDrissAitHafid** [comment]
@jordisantamaria actually, hydrate just solved the issue for some users and not all. So, I finally just switched to HeadlessUI which turned out to be more flexible and easy to use.

**Comment by jordisantamaria** [comment]
@IDrissAitHafid Sure, I was also trying radix/ui select, but I couldn't use the autocomplete feature, typing to reduce options like react select does
![image](https://github.com/JedWatson/react-select/assets/6263700/072c848b-c9f9-4cba-8450-35ab1eb4e301)

So what headlessUI library select do you recommend me?

**Comment by IDrissAitHafid** [comment]
@jordisantamaria I used the [combobox of headless UI ](https://headlessui.com/react/combobox). For my use cases which includes multiple searchable creatable select it worked really great.

**Comment by NinjaLukeI** [comment]
this is still an issue for me. i'm using:
    "@remix-run/node": "^2.9.2",
    "tailwindcss": "^3.4.17",
    "react-select": "^5.10.0",
    "react-google-places-autocomplete": "^4.1.0",

<img width="437" alt="Image" src="https://github.com/user-attachments/assets/bf78ac42-e085-4176-976f-c6de642365fa" />

This is what shows up for me when I SOMETIMES try to use the component. Other times it loads properly but I can't really predict when and it happens in both production and development.
