### ISSUE TITLE
Placeholder should act as an actual placeholder.

### ISSUE THREAD

**Issue by mull** [JedWatson/react-select#437]
1. Enter some text into the input
2. Change the placeholder prop
3. Whatever text was entered is removed, and replaced with the placeholder

The placeholder **should** act as an actual placeholder. Modifying it on an <input> tag doesn't interfere with whatever was previously entered.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
