### ISSUE TITLE
isSearchable + starts with functionality 

### ISSUE THREAD

**Issue by ariel-zap** [JedWatson/react-select#4382]
Hi,
Is it possible to use `isSearchable={true}` with "starts with" functionality, instead of default "contains" functionality?
For example:
Options - 1. **a**a 2. ba 3. **a**c
Searching "a" will cause only the following options to appear: "aa", "ac"
I found no documentation of this.

**Comment by manvydasu** [comment]
I believe you could just use custom `filterOption` and for those options, which should not be searchable, just filter them out whenever search input is non empty. For other options, just filter them with default 'contains'.

**Comment by ebonow** [comment]
Greetings @ariel-zap ,

There is an example in the documentation [here](https://react-select.com/advanced#custom-filter-logic) under the example **Custom filterOption with createFilter**

The `filterOption` prop allows some predefined ways to change the filtering via a config. 
The config value you are likely looking for is `{ matchFrom: 'start' }`

``` JSX
return <Select filterOption={{ matchFrom: 'start' }} {...otherProps} />
```

**Comment by ebonow** [comment]
I'll close out this issue, but if you have any other questions, please feel free to reply or use the Discussions.

**Comment by ariel-zap** [comment]
Thanks

**Comment by nelhwong** [comment]
@ebonow I got this error 
![Screenshot 2021-01-29 123412](https://user-images.githubusercontent.com/47463908/106324662-61936780-622e-11eb-9560-f10c645ef998.png)

**Comment by Methuselah96** [comment]
You need to specify the type for `filterConfig` in order to defeat type-widening:

```
import { Config } from 'react-select';

const filterConfig: Config = {
  matchFrom: 'start',
};
```

**Comment by goamn** [comment]
If anyone ends up here, it looks like filterOption is much smarter now, you can implement your own custom search. Here is the one for starts with:

```
  const filterOption = (option: FilterOptionOption<Option>, inputValue: string) => {
    const label = option.label;
    return !!label && label.startsWith(inputValue);
  };

...

  <Select
    ...
    isSearchable
    filterOption={filterOption}
      />
```
