### ISSUE TITLE
Option to use comma as well as tab in CreatableSelect isMulti

### ISSUE THREAD

**Issue by stahlmanDesign** [JedWatson/react-select#4386]
If there is an option for this, forgive me, but I can't find it.

When using CreatableSelect (see attached video) I keep pressing comma to create, but instead it types a comma. I'd like the option to have comma to work just as tab does, and add an item.

Tab should remain the default so that items contain commas, but I would like an option such as `commaCreates: true` or `additionalCreateCharacters: [',']`

https://user-images.githubusercontent.com/972804/105084514-702a9380-5a64-11eb-95bb-7f200b2315e2.mov

**Comment by ebonow** [comment]
Greetings @stahlmanDesign ,

I think this type of request is likely going to come with its own set of customization for users so likely would be left for individual users to implement. React-select provides the api's to do something like this and I have posted an example in this discussion:
https://github.com/JedWatson/react-select/discussions/4341

You see the example codesandbox for it here:
https://codesandbox.io/s/react-select-create-on-comma-szmuw

Let me know if you have any additional questions or concerns.

**Comment by stahlmanDesign** [comment]
Thanks, that's exactly what I was looking for.
