### ISSUE TITLE
loadAsyncOptions raises TypeError in setup (example included)

### ISSUE THREAD

**Issue by dotcs** [JedWatson/react-select#439]
I have a setup in which the internal `loadAsyncOptions` of react-select raises a `TypeError`, which I think is a bug in react-select.

#### Setup description

Please have a look at the following setup: https://gist.github.com/dotcs/99041355fbae0d5c757c

I have defined two components. `RecipientSelect` is a wrapper around `Select` from react-select and makes use of its async call mechanism. `AsyncDemoComponent` uses `ReciepientSelect` together with one input field and a textarea to create some basic setup to write messages.

If I search for `Test` in the `RecipientSelect` component, I get the three options `Test 1`, `Test 2` and `Test 3` from which I then choose one. The click then triggers a `setState` call in `onSelectChangeHandler`.

#### What I expect

I expect is that the `name` of the selected entry is written in `this.state.recipients` of the `AsyncDemoComponent`.

#### What I get

The `Select`-Component raises a TypeError (although `this.state.recipients` is updated correctly):

> Uncaught TypeError: Cannot read property 'length' of undefined

```javascript
loadAsyncOptions: function loadAsyncOptions(input, state, callback) {
	var _this6 = this;
	//if (!input) { return; } // this would fix the problem

	var thisRequestId = this._currentRequestId = requestId++;
	if (this.props.cacheAsyncResults) {
		for (var i = 0; i <= input.length; i++) { 
        // ...
```

The exact line of the error is [this one](https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L536).

#### First analysis

I have noted a possible fix in the example above, which I have used as a quick fix for the problem. But I think the actual problem is buried somewhere deeper in the code. I think the call to `loadAsyncOptions` isn't necessary at all at this point, which is why `input` is undefined which raises the error.

Interestingly in the setup (without my fix) every attempt to fill one of the other fields ends in the same error which seems to me that somehow this might be related to a problem with how `this` is treated in the component. But as far as I can tell I have linked all contexts correctly.

**Comment by oliversong** [comment]
+1, also seeing this

**Comment by claflamme** [comment]
I'm running in to the same issue using 0.6.11. I was able to get around it temporarily by setting `cacheAsyncResults={ false }` but that's obviously not ideal.

**Comment by claflamme** [comment]
Looks like the cause is the input not being coalesced to a blank string in a couple of places.

For example, in **lib/Select.js**, the `autoloadAsyncOptions()` method coalesces `this.props.value` to a blank string...
```js
this.loadAsyncOptions(this.props.value || '', { isLoading: false }, function () {
```
...but the two other calls to `loadAsyncOptions()` don't do that.

Changing the top of `loadAsyncOptions()` to the following fixes it for me:

```js
loadAsyncOptions: function loadAsyncOptions(input, state, callback) {
  var _this6 = this;
  input = input || ''
```
@dotcs and @oliversong, can you let me know if that fixes it for you? I'll try to do a proper pull request soon.

**Comment by oliversong** [comment]
I fixed this by adding `if (!input) { return; }` as noted in @dotcs's comment, but `input = input || ''` is probably more correct

**Comment by Webkadabra** [comment]
Also experiencing issue with that. As I see you fixed this? Do you mind doing PR for react-select, so we can all enjoy? :)

**Comment by Webkadabra** [comment]
BTW, @claflamme's fix work

**Comment by dotcs** [comment]
@claflamme's Your fix does work for me.

**Comment by dotcs** [comment]
Commenting out `this.loadAsyncOptions(newProps.value, {}, setState);` as mentioned in https://github.com/JedWatson/react-select/issues/494 does resolve the problem for me. I think both issues might be related.

**Comment by pancham348** [comment]
I am running into the same issue, has a PR been opened for this yet?

**Comment by JedWatson** [comment]
Thanks for the fix @pancham348! publishing a patch release now.

**Comment by JoseJollja** [comment]
> Lo arreglé agregando `if (!input) { return; }`como se indica en el comentario de @dotcs , pero `input = input || ''`probablemente sea más correcto

Si justamente tenia un error parecido, al iniciar en el componente como cuando tenia 0 productos queria mandarle     if(productos.length === 0) return null; para que no se vea la cabecera, entonces cuando eliminaba el ultimo producto seleccionado me manda error, busque por varios dias y con esto logres solucionarlo leyendo el comentario del citado.
 if(!productos || productos.length === 0) return null;
