### ISSUE TITLE
Search input shows wrong value

### ISSUE THREAD

**Issue by dmeij** [JedWatson/react-select#4393]
I'm using the latest release of react-select 3.2.0, look at the screen. Can anybody tell me how this is possible?

![Schermafbeelding 2021-01-22 om 13 24 20](https://user-images.githubusercontent.com/33659751/105490693-6f3c7080-5cb5-11eb-8558-f9d2753e6417.png)

I use this props, it's a grouped select:

`defaultValue: null
isDisabled: false
isMulti: false
options: (6) [{…}, {…}, {…}, {…}, {…}, {…}]
placeholder: "Alle objecten"
isClearable: true
value: null`

Can someone help me?

**Comment by Rall3n** [comment]
@dmeij Could you perhaps provide your complete set of options (as written in your code)?

**Comment by dmeij** [comment]
Like this?

`{"placeholder":"Alle objecten","options":[{"label":"test","options":[{"value":"31","label":"test"},{"value":"32","label":"test"},{"value":"33","label":"test"},{"value":"34","label":"test"},{"value":"35","label":"test"},{"value":"36","label":"test"},{"value":"37","label":"test"},{"value":"38","label":"test"},{"value":"39","label":"test"},{"value":"40","label":"test"},{"value":"41","label":"test"},{"value":"53","label":"test"},{"value":"54","label":"test"}]},{"label":"test","options":[{"value":"13","label":"test"},{"value":"14","label":"test"},{"value":"15","label":"test"},{"value":"16","label":"test"},{"value":"17","label":"test"},{"value":"18","label":"test"},{"value":"19","label":"test"},{"value":"20","label":"test"},{"value":"21","label":"test"},{"value":"22","label":"test"},{"value":"23","label":"test"},{"value":"24","label":"test"},{"value":"25","label":"test"},{"value":"26","label":"test"},{"value":"27","label":"test"}]},{"label":"test","options":[{"value":"28","label":"test"}]},{"label":"test","options":[{"value":"30","label":"test"}]},{"label":"test","options":[{"value":"1","label":"test"},{"value":"2","label":"test"},{"value":"3","label":"test"},{"value":"4","label":"test"},{"value":"5","label":"test"},{"value":"6","label":"test"},{"value":"7","label":"test"},{"value":"8","label":"test"},{"value":"9","label":"test"},{"value":"10","label":"Gulf"},{"value":"11","label":"test"},{"value":"12","label":"test"},{"value":"42","label":"10"}]},{"label":"test","options":[{"value":"29","label":"test"},{"value":"43","label":"test"}]}],"defaultValue":null,"isMulti":false,"isDisabled":false,"value":null, isClearable: true, menuPortalTarget: document.body}`

**Comment by dmeij** [comment]
Seeing this makes me think the searchbar also searches in the value, is it possible to only search in the label field?

**Comment by Rall3n** [comment]
@dmeij Yes, by default the component searches through both `value` and `label`.

If you want to only search through the `label` you have to use the `filterOption` prop in conjunction with the `createFilter` method exposed from the package. This will create a new search function based on a configuration you provide.

```jsx
import Select, { createFilter } from 'react-select';

const customFilterOption = createFilter({
    stringify: option => option.label // Default is `${option.label} ${option.value}`
});

/* ... */

<Select
    filterOption={customFilterOption}
 />
```

**Comment by dmeij** [comment]
Works, thnx!
