### ISSUE TITLE
In version 3.1.1, the menu options are transparent, could not solve this by adding a zIndex to menu with custom styles. 

### ISSUE THREAD

**Issue by karthik19894** [JedWatson/react-select#4394]
![image](https://user-images.githubusercontent.com/36123644/105515200-69b54980-5cfa-11eb-99c9-121ac3d46197.png)
The issue looks like the above, unable to solve by adding zIndex or changing background.

**Comment by karthik19894** [comment]
Attaching screenshot for reference:
![image](https://user-images.githubusercontent.com/36123644/105515054-438fa980-5cfa-11eb-9441-8ebbf264f7fd.png)

**Comment by ebonow** [comment]
Greetings @karthik19894 

This seems to be an issue with your implementation or styling rather than react-select. It does not appear that changing `background` or `zIndex` would fix this as it appear to be more an issue with your `opacity` setting.

Would you kindly confirm that setting `opacity: 1` to your menu styling solves your issue?

**Comment by karthik19894** [comment]
@ebonow no, setting `opacity:1` doesn't seem to resolve it.

**Comment by ebonow** [comment]
Would you be able to create a codesandbox of your implementation or at least the styling being applied to it?

If not, would you be able to send a screenshot of the styles being applied to the menu and menu options? 

`react-select` does not apply any opacity to the menu so it would be helpful to identify why/where it is occurring in your implementation.

**Comment by karthik19894** [comment]
Please find the code snippet for the custom styles that I have applied:

`const customStyles = {
  control: (provided) => ({
    ...provided,
    width: 120,
    minWidth: 120,
    height: 34,
    minHeight: 34,
    font: "normal normal bold 14px/19px Roboto",
    background: "none",
    paddingLeft: "0px",
    backgroundColor: "white",
    boxShadow: "0px 3px 6px #00000012",
    border: "none",
  }),
  option: (provided, { isSelected, isFocused }) => ({
    ...provided,
    width: 120,
    minWidth: 120,
    height: 34,
    minHeight: 34,
    letterSpacing: "0px",
    color: isSelected ? "#39C379" : "#838EAB",
    font: isFocused
      ? "normal normal bold 14px/19px Roboto"
      : "normal normal normal 14px/19px Roboto",
    backgroundColor: isSelected || isFocused ? "#E6EBF1" : "white",
    border: "none",
  }),
  dropdownIndicator: (provided, state) => ({
    ...provided,
    width: 28,
    paddingTop: 0,
    paddingBottom: 0,
    transform: state.selectProps.menuIsOpen ? "rotate(180deg)" : null,
  }),
  singleValue: (provided) => ({
    ...provided,
    color: "#39C379",
  }),
  menu: (provided) => ({
    ...provided,
    zIndex: 100,
    opacity: 1,
  }),
};
`

And the component is rendered like below:

`<Select
        defaultValue={selectedOption}
        onChange={this.handleAgentStatusChange}
        options={options}
        styles={customStyles}
        value={that.state.selectedOption}
      />`

**Comment by ebonow** [comment]
I am not able to reproduce the behavior you are seeing in your screenshot.
https://codesandbox.io/s/exciting-smoke-3m0k8?file=/src/App.js

Would you be able to confirm that the options also have `opacity: 1` and perhaps try adding it to your styles just in case?

**Comment by karthik19894** [comment]
@ebonow Just found that its an implementation issue, the parent element of the dropdown seems to have opacity set to 0.75, which seems to be causing the issue, thanks a lot for your time, The issue can be closed.
