### ISSUE TITLE
Escape character entity references

### ISSUE THREAD

**Issue by jossmac** [JedWatson/react-select#44]
![allow character entities](https://cloud.githubusercontent.com/assets/2730833/5639076/6da19d2c-9664-11e4-9b6e-d1fa63a3967f.png)

**Comment by kumo** [comment]
It looks like the issue is in KeystoneJS instead. The examples work with apostrophes and accented characters.

**Comment by bruderstein** [comment]
Confirmed - double checked this, and it works fine in the control itself.
I've got a couple of tests if anybody thinks they're worth adding :smile:
