### ISSUE TITLE
Custom field names in Options object

### ISSUE THREAD

**Issue by sriprabha** [JedWatson/react-select#440]
Is it possible to pass in array of options that are in different format, for example, instead of having field names as 'label' and 'value', is there an option to use custom field names?

**Comment by oluckyman** [comment]
Now you can. It was introduced in [v0.6.12](https://github.com/JedWatson/react-select/blob/master/HISTORY.md#v0612--2015-10-02).
Use `labelKey` and `valueKey` props.

**Comment by jssridhar** [comment]
There seems to be a a problem with the labelKey parameter when using with multi-select. It is working fine in case of single select, but with multi select it is still looking for the 'label' parameter.

**Comment by takashi** [comment]
I encountered same issue in 0.9.1
`addLabelText` always try to find the value with `label` key. I've set `labelKey` but doesn't works with `addLabelKey` 

Is there any workaround ?

**Comment by jssridhar** [comment]
I upgraded to 1.0.0-beta13. That fixed lot of my issues. But i had to refactor quite a bit of my codebase.

**Comment by takashi** [comment]
thx for ur information. 
If you can, could you show me your refactor of your codebase?

**Comment by jssridhar** [comment]
I had to do it because i used Select in multiple places. I think the primary change is moving async select components as separate Select.Async.  I don't think i can show all the refactors here, it should be a straight forward refactor though

**Comment by takashi** [comment]
@jssridhar i see, thanks for your information about refactoring. 
it's ok that you cant show the codebase and i know its too much amount to show.

again, thanks for ur information :)

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
