### ISSUE TITLE
How to update value of Async select in dynamic row?

### ISSUE THREAD

**Issue by nkdweb** [JedWatson/react-select#4413]
I have used Async select using https://react-select.com/home#async in reactjs application

Please refer to the attached image, Which shows the UI design

![asyn_select](https://user-images.githubusercontent.com/2375291/106396593-e8169780-642e-11eb-8d24-09827cd97cb0.JPG)

**Functional Scenario**

- Dynamic row, where you can add and delete customer name.
- If I add 3 customers and try to delete any customer, for eg: 2nd customer from the dynamic row
- After deleting 2nd customer, Now I have 2 customers and 2nd customer name still exists.
- Async select not updating its value after deleting the row.
- Async select is part of formik, updated formik value is not reflecting on Async select.

Please suggest, How to update AsyncSelect once after its value got updated?

**Comment by ebonow** [comment]
Greetings @nkdweb,

Would you mind providing a codesandbox? Just a note, that this is more likely a formik question than react-select especially if the expectation is that Select values would change when the form changes.

**Comment by ebonow** [comment]
Closing due to no reply.
