### ISSUE TITLE
Broken keyboard navigation on grouped selects during filtering

### ISSUE THREAD

**Issue by dmarkow** [JedWatson/react-select#4421]
#4398 / v4.0.2 fixed some issues with up/down navigation in a grouped select. However, if you type into a grouped select to filter it, then try to use the arrows, it's not working correctly. The arrow keys appear to be navigating all of the unfiltered options rather than just the filtered ones. This only seems to affect grouped selects. The regular ungrouped ones navigate filtered options just fine.

To reproduce:

- https://codesandbox.io/s/codesandboxer-example-forked-epz7k
- Click into the select box
- Type the letter 'o' which will show just "Ocean", "Orange", "Yellow", "Forest", etc.
- Use the up/down arrows on the keyboard to navigate. You have to press multiple times to get to some options.

Using the same example based on 3.2.0 works as expected: https://codesandbox.io/s/codesandboxer-example-forked-uhw5d

**Comment by Methuselah96** [comment]
🤦 That's pretty embarrassing. There was a bug in my bug-fix. Fix coming soon.
