### ISSUE TITLE
Unable to click onto the dropdown menu with placeholder set

### ISSUE THREAD

**Issue by lifehome** [JedWatson/react-select#4440]
### Development envrionment
**nodejs version:**
- v15.5.0

**package manager:**
- yarn

**react version:**
- 17.0.1

**react-select version:**
- 4.1.0

### Problem description
With reference to a few previous issues, I managed to create a customized styling react-select component that looks like this:

> 
> <img width="512" alt="螢幕截圖 2021-02-10 下午6 25 24" src="https://user-images.githubusercontent.com/1886237/107497321-6280ad80-6bcd-11eb-9b1f-f40c5150420a.png">
> 

It is however, when clicking onto most of the blank area around the placeholder text, it is unable for the users to open the dropdown menu. The user has to click on the dropdown icon, for them to display the menu.

### CodeSandbox to reproduce
https://codesandbox.io/s/react-select-410-placeholder-issue-oh3vc

**Comment by Rall3n** [comment]
@lifehome This is an error on your end.

You overwrite the `ValueContainer` component and correctly extract the `Input` component from the `children` prop for further usage as the `children` prop on the original `ValueContainer` component.
But then you render a custom  `Placeholder` component as the child, effectively overwriting the `children` prop.

Render the extracted `Input` component next to the `Placeholder` component. This should fix your issue.
```jsx
<components.ValueContainer>
    {result} // The extracted `Input` component
    <components.Placeholder>{...}</components.Placeholder>
</components.ValueContainer>
```

**Comment by ebonow** [comment]
Greetings @lifehome ,

Also worth noting that the "isFocused" and menu open behavior is triggered by focusing on an Input. Even when it is not searchable, there is a "DummyInput" component that is rendered that is visually hidden and focused on. Blurring out of it then causes the menu to close, but this should explain why this implementation does not work.

Please feel free to ask any other questions and we can reply to assist, and I will close this issue now as it does not appear to be an issue with library.
