### ISSUE TITLE
Using selected value from dropdown

### ISSUE THREAD

**Issue by Nishant-Pall** [JedWatson/react-select#4441]
I'm using react-select in a react application, I just want to clarify that how do I use the selected value from the dropdown as I'm going to use them further in making API calls. I have to use a handler that takes in the selected value and changes the state of the parent component. If possible can you please share the link for the appropriate documentation of the props I need for such a task?

**Comment by ebonow** [comment]
If you need to access the selected options, then you would likely want to [create a controlled input](https://www.geeksforgeeks.org/react-js-uncontrolled-vs-controlled-inputs/). 

```jsx
const MySelect = props => {
  const [ value, setValue ] = useState();
  
  const onChange = newValue => {
    setValue(newValue);
    props.onChange && props.onChange(newValue);
  }

  return <Select {...props} value={value} onChange={onChange} />
}

Please let me know if any of this is unclear or if you have any other questions.
