### ISSUE TITLE
How to make reactselect get focus when required and empty

### ISSUE THREAD

**Issue by Saeed-ul-haq** [JedWatson/react-select#4450]
This is my code but reactselect does  not  get focused when have error. other html field do get focus on error.

 ```
useEffect(() => {
    if (isSubmitting && !isValidating) {
      let keys = Object.keys(errors);
      debugger
      if (keys.length > 0) {
        const selector = `[name=${keys[0]}]`;
        const errorElement = document.querySelector(selector);
        if (errorElement) {
          errorElement.focus();
        }
      }
    }
  }, [errors, isSubmitting, isValidating]);
```

**Comment by ebonow** [comment]
Greetings @Saeed-ul-haq ,

Native validation is a known missing from react-select at this time. You can read more about the issue and challenges here: https://github.com/JedWatson/react-select/issues/4327

**Comment by ebonow** [comment]
@Saeed-ul-haq I will close this as a duplicate but if you wanted to discuss methods of working around this, we can still continue the conversation. Happy to discuss further. By chance are you using a form manager like formik or react hook form?
