### ISSUE TITLE
Uncaught TypeError: cache.sheet.hydrate is not a function

### ISSUE THREAD

**Issue by liby** [JedWatson/react-select#4451]
# Are you reporting a bug or runtime error?

* runtime error

After upgrading react-select to the latest version, I encountered the following error.

![image](https://user-images.githubusercontent.com/38807139/108494333-5dfd7880-72e2-11eb-8a20-fbab97fa69be.png)

![image](https://user-images.githubusercontent.com/38807139/108492603-5210b700-72e0-11eb-89d9-d7100b093466.png)

**Comment by Rall3n** [comment]
@liby Could you provide information on what version of `react-select` you are using and if you are using any other library with `@emotion` as a dependency?

**Comment by liby** [comment]
@Rall3n 

Our project itself does not introduce `@emotion`.

In `yarn.lock`, I searched for packages that refer to `@emotion`, excluding the packages related to `@emotion` itself, e.g. @emotion/utils, @emotion/styled-base, @emotion/core... and I listed all the packages that refer to `@emotion` below.

<details>
<summary>yarn.lock</summary>

```
"@storybook/theming@6.1.18":
  version "6.1.18"
  resolved "https://registry.yarnpkg.com/@storybook/theming/-/theming-6.1.18.tgz#a2aa08a52d589ce9662b9e789506ffa42d97da24"
  integrity sha512-q97mKSLLnB2LmjzKiNpip7jvvrVPDi+bnYoUCWCt04zuXiaIVU8Bu4i0Y/w3Y3bHqfRbae3gZErFr89Z+f77vA==
  dependencies:
    "@emotion/core" "^10.1.1"
    "@emotion/is-prop-valid" "^0.8.6"
    "@emotion/styled" "^10.0.23"
    "@storybook/client-logger" "6.1.18"
    core-js "^3.0.1"
    deep-object-diff "^1.1.0"
    emotion-theming "^10.0.19"
    global "^4.3.2"
    memoizerific "^1.11.3"
    polished "^3.4.4"
    resolve-from "^5.0.0"
    ts-dedent "^2.0.0"

"@storybook/ui@6.1.18":
  version "6.1.18"
  resolved "https://registry.yarnpkg.com/@storybook/ui/-/ui-6.1.18.tgz#e88ad5ba0e041127c8624f15b3071e796348b817"
  integrity sha512-EKOja3ji0gHxnKWFBt+nK7xuBOzKTEKJ3+PiW0+QS0jZ18EkR7U7h0U052jNXdiI1c6Sck5n9+gI5EylzN18+Q==
  dependencies:
    "@emotion/core" "^10.1.1"
    "@storybook/addons" "6.1.18"
    "@storybook/api" "6.1.18"
    "@storybook/channels" "6.1.18"
    "@storybook/client-logger" "6.1.18"
    "@storybook/components" "6.1.18"
    "@storybook/core-events" "6.1.18"
    "@storybook/router" "6.1.18"
    "@storybook/semver" "^7.3.2"
    "@storybook/theming" "6.1.18"
    "@types/markdown-to-jsx" "^6.11.0"
    copy-to-clipboard "^3.0.8"
    core-js "^3.0.1"
    core-js-pure "^3.0.1"
    downshift "^6.0.6"
    emotion-theming "^10.0.19"
    fuse.js "^3.6.1"
    global "^4.3.2"
    lodash "^4.17.15"
    markdown-to-jsx "^6.11.4"
    memoizerific "^1.11.3"
    polished "^3.4.4"
    qs "^6.6.0"
    react-draggable "^4.0.3"
    react-helmet-async "^1.0.2"
    react-hotkeys "2.0.0"
    react-sizeme "^2.6.7"
    regenerator-runtime "^0.13.7"
    resolve-from "^5.0.0"
    store2 "^2.7.1"

"@types/react-select@^4.0.13":
  version "4.0.13"
  resolved "https://registry.yarnpkg.com/@types/react-select/-/react-select-4.0.13.tgz#8d2c41a0df7fbf67ab0b995797b0e9b4e6b38cde"
  integrity sha512-rXYEc565IzzjgQzs9C0YCFxV/QajMZnCHG5QwRQ5BZMfH0Lj90VI/xohawemRkD46IvpaLRbO6xzSquJlgBGUA==
  dependencies:
    "@emotion/serialize" "^1.0.0"
    "@types/react" "*"
    "@types/react-dom" "*"
    "@types/react-transition-group" "*"

babel-plugin-emotion@^10.0.20, babel-plugin-emotion@^10.0.27:
  version "10.0.27"
  resolved "https://registry.yarnpkg.com/babel-plugin-emotion/-/babel-plugin-emotion-10.0.27.tgz#59001cf5de847c1d61f2079cd906a90a00d3184f"
  integrity sha512-SUNYcT4FqhOqvwv0z1oeYhqgheU8qrceLojuHyX17ngo7WtWqN5I9l3IGHzf21Xraj465CVzF4IvOlAF+3ed0A==
  dependencies:
    "@babel/helper-module-imports" "^7.0.0"
    "@emotion/hash" "0.7.4"
    "@emotion/memoize" "0.7.4"
    "@emotion/serialize" "^0.11.15"
    babel-plugin-macros "^2.0.0"
    babel-plugin-syntax-jsx "^6.18.0"
    convert-source-map "^1.5.0"
    escape-string-regexp "^1.0.5"
    find-root "^1.1.0"
    source-map "^0.5.7"

react-select@^4.1.0:
  version "4.1.0"
  resolved "https://registry.yarnpkg.com/react-select/-/react-select-4.1.0.tgz#7ce06b4e8e79b8f58d09a15d25c705abb1ac4885"
  integrity sha512-OYn+jL8TXMMaZtosErpkdvoI1UWN4ZqMFulIRp5r5bbuqe4OaZN7yv1BNq7PdAJgRu2E19ODFiV1SgJ6wPUaeA==
  dependencies:
    "@babel/runtime" "^7.12.0"
    "@emotion/cache" "^11.0.0"
    "@emotion/react" "^11.1.1"
    memoize-one "^5.0.0"
    prop-types "^15.6.0"
    react-input-autosize "^3.0.0"
    react-transition-group "^4.3.0"

styled-components@^5.2.1:
  version "5.2.1"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-5.2.1.tgz#6ed7fad2dc233825f64c719ffbdedd84ad79101a"
  integrity sha512-sBdgLWrCFTKtmZm/9x7jkIabjFNVzCUeKfoQsM6R3saImkUnjx0QYdLwJHBjY9ifEcmjDamJDVfknWm1yxZPxQ==
  dependencies:
    "@babel/helper-module-imports" "^7.0.0"
    "@babel/traverse" "^7.4.5"
    "@emotion/is-prop-valid" "^0.8.8"
    "@emotion/stylis" "^0.8.4"
    "@emotion/unitless" "^0.7.4"
    babel-plugin-styled-components ">= 1"
    css-to-react-native "^3.0.0"
    hoist-non-react-statics "^3.0.0"
    shallowequal "^1.1.0"
    supports-color "^5.5.0"
```
</details>

There may be another method or command to find out who is relying on `@emotion` more efficiently and accurately, please share it with me and I will try to find it.

**Comment by Methuselah96** [comment]
Have you tried deleting your `yarn.lock` and re-running `yarn install`? That might not do anything, but it's worth trying before going down the dependency rabbit hole. The dependency on both Emotion 10 (by Storybook) and Emotion 11 (by react-select) seems like a good candidate for what's causing the issue.

**Comment by liby** [comment]
@Methuselah96 
I tried to delete both `yarn.lock` and `node_modules` and re-running `yarn install`.
It is worth mentioning that if you upgrade React select to "4.1.0" and encounter an error, and do not delete the `node_modules` folder after downgrading, then  re-running `yarn install` again will still throw an error

**Comment by liby** [comment]
I've tried, but I still see the error.

**Comment by Methuselah96** [comment]
I tried reproducing your issue in [a sample repo](https://github.com/Methuselah96/react-select-testing) with the dependencies you listed, but I wasn't able to reproduce it. Is there any more info that you can provide that would help reproduce the issue? You could also email me privately at `nbierema` (gmail) if you have something you can't share publicly.

**Comment by liby** [comment]
@Methuselah96 
First of all, thank you very much for your enthusiastic help. Because it is a commercial project of the company, so sorry I can not share.
But I tried to clone your example repository and copy the dependencies from our project, but I couldn't reproduce the error in the end.
Of course, I will continue to track this issue, you can also close this issue.

**Comment by ebonow** [comment]
I tried to see if this has come up before and though it was reported, it doesn't appear that there was any further documentation. https://github.com/emotion-js/emotion/issues/1743

Good luck though and please let us know if you come across a resolution should anyone else come across this.

**Comment by liby** [comment]
@ebonow @Methuselah96 
I think I've pinpointed the cause.

First, to review, the error is reported as follows: `Uncaught TypeError: cache.sheet.hydrate is not a function`.

The packages that depend on `emotion@sheet` at the time of `react-select@4.0.2` are the following:
<img width="773" alt="yarn-why-4-0-2" src="https://user-images.githubusercontent.com/38807139/109250800-4152ca80-7825-11eb-94ed-604930a0693d.png">

At this point, the version of `@emotion/sheet` installed in node_modules is as follows, it matches the version in the `@emotion/cache` dependencies project:
<img width="1808" alt="package-4-0-2" src="https://user-images.githubusercontent.com/38807139/109251241-10bf6080-7826-11eb-9e7c-5cdabd1de3d5.png">

The packages that depend on `emotion@sheet` at the time of `react-select@4.1.0` are the following:
<img width="781" alt="yarn-why-4-1-0" src="https://user-images.githubusercontent.com/38807139/109251498-904d2f80-7826-11eb-9801-63c50573ec46.png">

At this point, the version of `@emotion/sheet` installed in node_modules is as follows, it does not match the version in the `@emotion/cache` dependencies project:
<img width="1793" alt="package-4-1-0" src="https://user-images.githubusercontent.com/38807139/109251527-9a6f2e00-7826-11eb-8250-d3c7d028dcd7.png">

The current solution is to modify the `yarn.lock` file and install the correct version of `@emotion/sheet`.

**Comment by Domiii** [comment]
Thanks go out to @liby - had a very similar (but not exactly the same) problem, so I followed the same problem solving approach:

1. Check `@emotion/sheet` version:
   * `code .\node_modules\@emotion\sheet\package.json` -> `0.9.4`
1. `yarn why @emotion/sheet`
   > yarn why v1.22.10
   > [1/4] Why do we have the module "@emotion/sheet"...?
   > [2/4] Initialising dependency graph...
   > [3/4] Finding dependency...
   > [4/4] Calculating file sizes...
   > info Has been hoisted to "@emotion/sheet"
   > info Reasons this module exists
   >    - "workspace-aggregator-4xcc1c24-5cf6-43b0-aa9f-f6b7bac89be8" depends on it
   >    - Hoisted from "_project_#@storybook#addon-actions#@storybook#theming#@emotion#core#@emotion#sheet"
   >    - Hoisted from "_project_#@storybook#addon-actions#@storybook#theming#@emotion#core#@emotion#cache#@emotion#sheet"

# Solution

From above analysis, we found, it came from `addon-actions`.

Similar to the other solution proposal, we can fix this via [`resolutions` override](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/):

```js
  "resolutions": {
    "@storybook/addon-actions/**/@emotion/sheet": "^1.0.1"
  }
```

Maybe a more general solution that also fixes the problem mentioned by @liby :

```js
  "resolutions": {
    "@storybook/addon-*/**/@emotion/sheet": "^1.0.1"
  }
```

NOTE: This might also be a fix for https://github.com/storybookjs/storybook/issues/13145

**Comment by liby** [comment]
> That got me a bit further, but got me stuck on another dependency conflict.

So adding `"@storybook/**/@emotion/styled": "^11"` solves the problem? Anyway, I'm glad I can help you.

**Comment by Domiii** [comment]
@liby No it is not just adding that line that solves the problem. `sheet` also had more conflicts with other `@storybook` packages.
