### ISSUE TITLE
Menu closes when option is selected on mobile

### ISSUE THREAD

**Issue by Wiz1991** [JedWatson/react-select#4455]
With **closeMenuOnSelect** set to false and **isMulti** enabled as well as isSearchable, after selecting an option on mobile the input loses focus and the keyboard dissapears. When the input loses focus the menu closes as well. This of course does not happen on desktop.  
  
The menu as well as the keyboard should stay open after selecting an option  

I could not find a solution to this anywhere so if anyone has resolved this please tell me how. As it is very bad UX for the menu to close each time, especially on mobile

**Comment by ebonow** [comment]
@Wiz1991 I am not able to reproduce. I have tested with both isMulti and not.

Codesandbox: [Demo](https://codesandbox.io/s/codesandboxer-example-forked-bgryd?file=/example.js)

<img width="489" alt="Screen Shot 2021-02-23 at 8 00 11 AM" src="https://user-images.githubusercontent.com/1007579/108870799-532a3880-75ad-11eb-91a0-cf8da73810d5.png">

**Comment by Wiz1991** [comment]
@ebonow  On mobile, not desktop

**Comment by ebonow** [comment]
@Wiz1991 Correct. This is on Chrome with mobile simulator which is why I included a screenshot. Do you have a reproducible example?

**Comment by Wiz1991** [comment]
I opened your sandbox and i have the same issue

**Comment by Wiz1991** [comment]
Try running the sandbox on actual phone, not simulator

**Comment by ebonow** [comment]
Bug confirmed. I ran the sandbox on iPhone Simulator instead of Chrome Emulator and was able to reproduce the issue.

<img width="450" alt="Screen Shot 2021-02-23 at 8 24 49 AM" src="https://user-images.githubusercontent.com/1007579/108874258-d6995900-75b0-11eb-85a3-f37a50053677.png">

**Comment by arkadeepde142** [comment]
Could I work on this issue? I am new to open source.

**Comment by ebonow** [comment]
Greetings @arkadeepde142 you are more than welcome to take a look.

**Comment by bjnsn** [comment]
I ran into the same issue and tracked it down to the `blurInputOnSelect` property which defaults to `isTouchCapable()`. So, I don't think this is a bug, per-se, but it is confusing. See: https://react-select.com/props

**Comment by Wiz1991** [comment]
> I ran into the same issue and tracked it down to the `blurInputOnSelect` property which defaults to `isTouchCapable()`. You should be able to set `blurInputOnSelect` to `false` and have the panel stay open on touch devices. So, I don't think this is a bug, per-se, but it is confusing. See: https://react-select.com/props

You are right, this 'fixes' that. Its weird that this is enabled by default. It provides different behavior on PC and on Mobile.

**Comment by jamesedmonston** [comment]
Appreciate that this is an old issue, but I'm running into this problem even when supplying both `closeMenuOnSelect` and `blurInputOnSelect`. Is there something I'm missing?

```typescript
<label className='relative'>
  <Select
    unstyled
    isMulti
    closeMenuOnSelect={false}
    blurInputOnSelect={false}
    isSearchable={isSearchable}
    placeholder={label ?? 'Select an option'}
    options={options.map((option) => ({
      label: option,
      value: option,
    }))}
    value={selected.map((option) => ({
      label: option,
      value: option,
    }))}
    classNames={{
      ...
    }}
    onChange={(values) => onChange(values.map(({ value }) => value))}
  />

  <Image
    src={arrows}
    alt=''
    className='pointer-events-none absolute right-5 top-1/2 -translate-y-1/2'
  />
</label>
```

**Comment by Nosferatu31** [comment]
I also could not make it work.
