### ISSUE TITLE
findDOMNode deprecated

### ISSUE THREAD

**Issue by Wiz1991** [JedWatson/react-select#4456]
The warning is generated from the animated components.  
![image](https://user-images.githubusercontent.com/45233935/108875557-9ad8b080-75fd-11eb-8b7b-66bd2edad491.png)

**Comment by ebonow** [comment]
@Wiz1991 which version of react-select are you using?

**Comment by Wiz1991** [comment]
It would seem the warning is generated from some package that is using version 4.0.0

**Comment by Methuselah96** [comment]
Yeah, this is an issue of us not using [the `nodeRef` prop](https://reactcommunity.org/react-transition-group/transition#Transition-prop-nodeRef) when creating a `Transition` from `react-transition-group`, which means it falls back on using `findDOMNode`. This is worth fixing although it only affects animated components at the moment.

**Comment by shehi** [comment]
Any update re this?

**Comment by fre-ben** [comment]
Same here - using animated components combined with a custom MultiValue component.

**Comment by dgwyer** [comment]
I'm also seeing this as other have reported when using animated components.
