### ISSUE TITLE
label & value of options have to be identical

### ISSUE THREAD

**Issue by mikakun** [JedWatson/react-select#446]
```
options = [
{ value: '1', label: 'One' },
{ value: '2', label: 'Two' }
];
```

render

```
value : {this.state.selectValue}
```

in some event handler

```
this.setState({selectValue:'1,2'});
```

we'll then see "1" & "2" in the select (as selected), not "One" & "Two" along with some warning in the console.

**Comment by Webkadabra** [comment]
:+1:

**Comment by oluckyman** [comment]
do you passing options array as a props in render too?
and what warning?

**Comment by wbecker** [comment]
This is a bit of a problem. The use case for this is when you want to have extra information in the select option, which you do not want in the actual view. For example, you may want to put tags on options, that users can see when selecting, but are not needed when the value is chosen.

Selectize allows this, by having [custom renderers](https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md#rendering) for many things

It would be great if react-select did something similar!

I might have a look into seeing how feasible this is, if that's cool!

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
