### ISSUE TITLE
Unable to paste into react-select input using the mouse

### ISSUE THREAD

**Issue by MattTheRed** [JedWatson/react-select#4461]
I'm using the react-select library in single select mode. I am able to paste into the field by using CTRL + V but am not able to paste into the field using my mouse.

The browser does not seem to recognize that the field is an input field from what I can tell. There is a similar stackoverflow post mentioning this issue at: https://stackoverflow.com/questions/58897432/react-select-unable-to-paste-value-in-the-search-field

## Steps to reproduce
1. Open https://react-select.com/home in Google Chrome v88 on Mac OS
2. Right click into the first input field. The option to copy appears but the option to paste does not appear.

![Screen Shot 2021-02-23 at 2 01 43 PM](https://user-images.githubusercontent.com/784532/108907880-ed0ad900-75df-11eb-87ae-f0f3b04263d1.png)

**Comment by ebonow** [comment]
Greetings @MattTheRed ,

This is because the default input width is "2px" and doesn't fill the full width of the control. This is something that can be changed via the styles api. Please see the following thread and see if the proposed solution resolves your use case.

https://github.com/JedWatson/react-select/issues/4106

**Comment by ebonow** [comment]
Solution found here:
https://github.com/JedWatson/react-select/issues/4106#issuecomment-743959376

Ideally, you would want the width of the input to stretch the width of the container and you can use the api styling on the Input. However, the input within the Input component is wrapped in 2 divs, so you will need to target the selectors a bit more explicitly. 

Try this in your styles prop...
[Working Forked Codesandbox](https://codesandbox.io/s/react-select-paste-on-mobile-q51wl)

```js
input: (css) => ({
  ...css,
  /* expand the Input Component div */
  width: "100%",
  
  /* expand the Input Component child div */
  "> div": {
    width: "100%"
   },

  /* expand the Input Component input */
  input: {
    width: "100% !important",
    textAlign: "left"
  }
})
```

I'll mark this closed for now, but I can reopen this if you have any questions or issues with the implementation. Hope this is helpful and thanks for you patience.

**Comment by MattTheRed** [comment]
Trying this out and I can get these changes working with a <Select/> component, but am struggling to get it working with a <MultiSelect> or <Async>. 

It doesn't look like the `styles` prop is exposed for either of these components: https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Async.js

Is there a workaround or maybe a way to pass nested props down to the child <SelectComponent/>?

Thanks for your help!

**Comment by ebonow** [comment]
@MattTheRed I am guessing that you mean an AsyncSelect?

Async exists as an HOC so it shouldn't prevent styling...
Here is a quick Async example I threw together.
https://codesandbox.io/s/react-select-paste-on-mobile-forked-85scf?file=/src/App.js

**Comment by MattTheRed** [comment]
Ah I see, we're on an older version of react-select that didn't expose that. Thanks for your help

**Comment by kainosnoema** [comment]
@ebonow this is once again an issue with the new grid layout, and I can't seem to find an easy solution to making the input full width to allow paste on touch devices. This seems like something that should maybe work by default though... ?

**Comment by uragecz** [comment]
+1 having same issue after updating to newest react-select with new grid layout system

**Comment by davidgg** [comment]
From https://stackoverflow.com/questions/70897522/react-selects-short-input-box-component-width-causes-cursor-position-problem

```jsx
input: (base) => ({
  ...base,
  gridTemplateColumns: '0fr',
}),
```

**Comment by kainosnoema** [comment]
I can't believe this still hasn't been fixed in react-select upstream. It's basically unusable on iOS as-is. We finally got paste working by combining the above solution linked by @davidgg with disabling pointer events on the placeholder since it's covering the input:

```ts
input: (base) => ({
  ...base,
  gridTemplateColumns: '0fr',
}),
placeholder: (base) => ({
  ...base,
  pointerEvents: "none",
  userSelect: "none",
}),
```

**Comment by dvalsagna89** [comment]
> I can't believe this still hasn't been fixed in react-select upstream. It's basically unusable on iOS as-is. We finally got paste working by combining the above solution linked by @davidgg with disabling pointer events on the placeholder since it's covering the input:
> 
> ```ts
> input: (base) => ({
>   ...base,
>   gridTemplateColumns: '0fr',
> }),
> placeholder: (base) => ({
>   ...base,
>   pointerEvents: "none",
>   userSelect: "none",
> }),
> ```

can you explain why `gridTemplateColumns: '0fr'` works? my first thought was this is making the input invisible
