### ISSUE TITLE
Dropdown does not appear on clicking inside value but appears on click of down arrow icon in React Select

### ISSUE THREAD

**Issue by Shivraj97** [JedWatson/react-select#4467]
I am using Multi Select and want to render just 1 item and then show additional selected item as +(this) more inside the selected area, it works fine when there is no value selected, but when the select component is populated from api response i.e when it already has value inside it the dropdown doesn't appear on clicking of the area where selected value are shown but it opens when I click on down arrow icon. I am using styled component for styling. I asked in [StackOverflow](https://stackoverflow.com/questions/61467417/how-to-change-valuecontainer-of-react-select-so-that-minifying-does-not-introduc) but didn't got any answer, so posting here hope I get some solution.
`             

           const ValueContainer = ({ children, getValue, hasValue, ...props }) => {

		let maxToShow = 1;
		let length = getValue().length;
		let displayChips = React.Children.toArray(children).slice(0, maxToShow);
		let shouldBadgeShow = length > maxToShow;
		let displayLength = length - maxToShow;

		if (!hasValue) {
			return (
				<components.ValueContainer {...props}>
					{children}
				</components.ValueContainer>
			);
		}

		return (
			<components.ValueContainer {...props}>
				{!props.selectProps.inputValue && displayChips}
				<Div
					fontSize={0}
					fontWeight={5}
					color="#4380FF"
					ml="auto"
					pl="3px"
					minWidth="56px">
					{shouldBadgeShow && `+ ${displayLength} more`}
				</Div>
			</components.ValueContainer>
		);
	};
       const Option = props => {
		return (
			<Div>
				<components.Option {...props}>
					<Flex alignItems="center">
						<CheckBox
							checked={props.isSelected}
							width="20px"
							height="20px"
							mr="10px"
						/>
						<Div width={0.85}>{props.label} </Div>
					</Flex>
				</components.Option>
			</Div>
		);
	};
        <Select
		classNamePrefix="faq__dropdown"
	        className={
		'faq__dropdown--empty'
		}
		isClearable={false}
		isSearchable={false}
	        isMulti
		hideSelectedOptions={false}
		closeMenuOnSelect={false}
		components={{ Option, MultiValue }}
		options={attributeMsgs}
		value={selectedAttributeMsgs}
		onChange={e => handleAttributeMsg(e)}
									
		/>

`

**Comment by Rall3n** [comment]
Possible duplicate of #2597 and #4193.

[This solution](https://github.com/JedWatson/react-select/issues/4193#issuecomment-686691429) should apply to your problem.

**Comment by ebonow** [comment]
@Shivraj97 also please kindly refer to [this in the documentation](https://react-select.com/components#defining-components) as to why you should try to avoid declaring the components in the same scope that you are rendering the Select.

**Comment by Shivraj97** [comment]
@Rall3n this solution https://github.com/JedWatson/react-select/issues/2597#issuecomment-579224823 solved my actual problem but now I can't see placeholder.

**Comment by Shivraj97** [comment]
@ebonow I was able to solve the issue, Thanks for the help.

**Comment by saver711** [comment]
@Shivraj97 
How?

**Comment by DanieII** [comment]
For me this issue appeared because of drag and drop. I solved it by disabling dragging in the parent component.
`typescript
<div
        onMouseOver={() => setIsDragDisabled(true)}
        onMouseLeave={() => setIsDragDisabled(false)}
      >
        <Select
          options={...}
        />
      </div>
`
