### ISSUE TITLE
Placeholder does not display with custom inputs

### ISSUE THREAD

**Issue by barrychapman** [JedWatson/react-select#4469]
When using
```
                    components={{ Input }}
```
to render a custom input, the placeholder property is not passed, so the placeholder does not display.

**Comment by ebonow** [comment]
Greetings @barrychapman ,

The `Placeholder` component does not get applied directly to the Input but is rendered in the same manner as a `SingleValue` component.

It's possible that your expectation is that a a placeholder attribute on an input shows but the behavior of react-select is such that the input is hidden (opacity set to 0) when it is not focused. To work around this, You can pass a prop called `isHidden` and set it to false to your `<component.Input />` though you may run into other concerns. 

Feel free to share a codesandbox if you would like to work on this further or if none of this applies to your implementation.

**Comment by ebonow** [comment]
WIthout further information, we will be closing this as an implementation misunderstanding and not an issue with react-select.
