### ISSUE TITLE
React-hook-form onBlur doesn't trigger

### ISSUE THREAD

**Issue by WeakCookie** [JedWatson/react-select#4472]
Hi! I'm using `Controller` with Select from react-select, every prop is passed from `Controller` to `Select` properly except for the `onBlur` one, it doesn't even trigger the `onBlur`
My code look something like this

```
    <Controller
          as={<Select />}
          onBlur={(e) => console.log(e)} // not thing happen !!!
          name={'name'}
          control={control}
          onChange={([selected]) => {
            return selected
          }}
          options={options}
     />
```

I have also used `render` but it doesn't seem to work :(
Am i missing or doing anything wrong, please let me know. Thanks in advance

**Comment by ebonow** [comment]
Greetings @WeakCookie ,

Would you mind creating a codesandbox with the above to make it easier for others to hop in and test?

**Comment by WeakCookie** [comment]
Oh god i post on wrong repo :((( i'm gonna close the issue. Thanks for your response
