### ISSUE TITLE
Dependant dropdown placeholder update

### ISSUE THREAD

**Issue by esponges** [JedWatson/react-select#4473]
Before anything, I'd like to thank for this awesome package. It's been really useful for my team.

I have a dependant dropdown that it's rendered after the value from the setter dropdown is selected. 

Mostly, everything works as expected, excepting than:

- _When the value from the first dropdown is changed_, the value from the dependant dropdown placeholder is _not cleared_. Making not clear to the user that the dependant option must be also re-selected.

![image](https://user-images.githubusercontent.com/68973307/109887448-54abce80-7c47-11eb-8300-eef52f0eb634.png)

The dependant dropdown is evidently changing after every change in setter dropdown. 

I've playing with some props and I have not found any solution yet. 

My component

```
import Select from "react-select";

const DeliverySchedule = (props) => {
  const [selectedDay, setSelectedDay] = useState(null);
  const [schedule, setSchedule] = useState(null);
  const [depDropIsSelected, setDepDropIsSelected] = useState(null);

  const handleDayChange = (day) => {
    if (depDropIsSelected) {     //avoid active submit btn    
      props.getDeliveryInfo(false, false);
    }

    setSelectedDay(day.value);
    if (day.value === "Saturday") {
      setSchedule(saturdayHourSchedule);
    } else {
      setSchedule(weekdayHourSchedule);
    }
  };

  const handleScheduleChange = (schedule) => {
    setDepDropIsSelected(true);
    props.getDeliveryInfo(selectedDay, schedule.value);
  };

  const days = [
    { value: "Monday", label: "Monday" },
    { value: "Tuesday", label: "Tuesday" },
    { value: "Wednesday", label: "Wednesday" },
    { value: "Thursday", label: "Thursday" },
    { value: "Friday", label: "Friday" },
    { value: "Saturday", label: "Saturday" },
  ];

  const weekdayHourSchedule = [
    { value: "10am a 12pm", label: "10am a 12pm" },
    { value: "12pm a 2pm", label: "12pm a 2pm" },
    { value: "2pm a 4pm", label: "2pm a 4pm" },
    { value: "4pm a 6pm", label: "4pm a 6pm" },
  ];

  const saturdayHourSchedule = [{ value: "10am a 3pm", label: "10am a 3pm" }];

  return (
    <Form.Group>
      <Form.Label>¿Qué día deseas recibir tu pedido?</Form.Label> // choose a day
      <div style={{ marginBottom: "1rem" }}>
        <Select options={days} onChange={handleDayChange} />
      </div>
      {schedule && selectedDay && (
        <div>
          <Form.Label>¿En qué horario?</Form.Label> // choose an hour
          <Select options={schedule} onChange={handleScheduleChange} />
        </div>
      )}
    </Form.Group>
  );
};

export default withRouter(DeliverySchedule);
```

Thanks in advance for any idea and also your time.

**Comment by ebonow** [comment]
Greetings @esponges, 

It sounds like you want the Select values to be  controlled by passing in the `value` prop so that you can pass in a cleared value (null) to the schedule select.

I'd consider setting your state values `selectedDay` and `schedule` to be the selected option instead of just the value so it can be reused.


```jsx
const DeliverySchedule = (props) => {
  const [selectedDay, setSelectedDay] = useState(null);
  const [selectedHours, setSelectedHours] = useState(null);
  const [schedule, setSchedule] = useState([]);


  const handleDayChange = opt => {
    setSelectedDay(opt);
    setSelectedHours(null); // clear dependency scheduled hours value
    
    const scheduleHours = (opt.value === 'Saturday')
      ? saturdayHourSchedule 
      : weekdayHourSchedule;
      
    setSchedule(scheduleHours)
  }

  const handleScheduleChange = opt => {
    setSelectedHours(opt);
    props.getDeliveryInfo(selectedDay.value, opt.value);
  }

  return (
    <Form.Group>
      <Form.Label>¿Qué día deseas recibir tu pedido?</Form.Label> // choose a day
      <div style={{ marginBottom: "1rem" }}>
        <Select options={days} onChange={handleDayChange} value={selectedDay} />
      </div>
      {schedule && selectedDay && (
        <div>
          <Form.Label>¿En qué horario?</Form.Label> // choose an hour
          <Select options={schedule} onChange={handleScheduleChange} value={selectedHours} />
        </div>
      )}
    </Form.Group>
  );
};
```

Let me know if this helps, if you have questions, or if I am missing something.

**Comment by ebonow** [comment]
Greetings @esponges ,

I hope you found the above useful. Since your question is not related to any existing issues with react-select I will be closing this, but happy to work through any other questions you have.

**Comment by esponges** [comment]
> Greetings @esponges ,
> 
> I hope you found the above useful. Since your question is not related to any existing issues with react-select I will be closing this, but happy to work through any other questions you have.

Hello Eric! Thanks for taking time helping me with this issue.

An important bug fix has been keeping me away to work on this, but I expect to have time this afternoon to test it out. 

Regards,

Fernando

**Comment by esponges** [comment]
> Greetings @esponges,
> 
> It sounds like you want the Select values to be controlled by passing in the `value` prop so that you can pass in a cleared value (null) to the schedule select.
> 
> I'd consider setting your state values `selectedDay` and `schedule` to be the selected option instead of just the value so it can be reused.
> 
> ```js
> const DeliverySchedule = (props) => {
>   const [selectedDay, setSelectedDay] = useState(null);
>   const [selectedHours, setSelectedHours] = useState(null);
>   const [schedule, setSchedule] = useState([]);
> 
> 
>   const handleDayChange = opt => {
>     setSelectedDay(opt);
>     setSelectedHours(null); // clear dependency scheduled hours value
>     
>     const scheduleHours = (opt.value === 'Saturday')
>       ? saturdayHourSchedule 
>       : weekdayHourSchedule;
>       
>     setSchedule(scheduleHours)
>   }
> 
>   const handleScheduleChange = opt => {
>     setSelectedHours(opt);
>     props.getDeliveryInfo(selectedDay.value, opt.value);
>   }
> 
>   return (
>     <Form.Group>
>       <Form.Label>¿Qué día deseas recibir tu pedido?</Form.Label> // choose a day
>       <div style={{ marginBottom: "1rem" }}>
>         <Select options={days} onChange={handleDayChange} value={selectedDay} />
>       </div>
>       {schedule && selectedDay && (
>         <div>
>           <Form.Label>¿En qué horario?</Form.Label> // choose an hour
>           <Select options={schedule} onChange={handleScheduleChange} value={selectedHours} />
>         </div>
>       )}
>     </Form.Group>
>   );
> };
> ```
> 
> Let me know if this helps, if you have questions, or if I am missing something.

Hello Eric,

Once again thanks for your help. 

Your solution solved my problem. I'm very grateful for taking time answering my query and also for your effort put in your contributions.

Best wishes, 

Fernando
