### ISSUE TITLE
Class 'is-selected' doesn't get added to selected options when `multi=true`

### ISSUE THREAD

**Issue by a6hi5h3k** [JedWatson/react-select#448]
Upon passing your own method in props for `filterOptions` to also show selected options in Dropdown for MultiSelect box, the class `is-selected` doesn't gets added to the option elements.
Following line in `buildMenu()` looks to be rogue which could be fixed.

``` javascript
var isSelected = this.state.value === op.value;
```

The value in `state` is a comma-separted string of values here, which will always fail this check.

**Comment by gwyneplaine** [comment]
Resolved in 2.x.x 

Closing this issue, if for some reason you feel that what I've described above doesn't correctly address your problem, please feel free to create a new issue. Mostly doing this for clarity ad to reduce our issues list down to a sane and relevant number of actionable tasks.
