### ISSUE TITLE
Adding react-select to repository with theme-ui and Next.js results in broken styles for production website.

### ISSUE THREAD

**Issue by pacxiu** [JedWatson/react-select#4498]
# Are you reporting a bug or runtime error?
Bug - as in title. While in development mode on localhost this issue is not visible at all.

# Reproduction and investigation
Repo to reproduce:
https://github.com/pacxiu/react-select-bug

For reproducing issue locally (running production build) run `yarn build && yarn start`

Production deployment on vercel - https://react-select-bug.vercel.app/ (You could see that on initial load for couple msec website is looking correctly, after that `body` element is loosing it styles eg: `background` and `font-size`)

I think it could be somehow related to the fact that both react-select and theme-ui are using emotion-css underhood? However I'm not sure at all how it is caused.

# Expected
Production build shouldn't have broken CSS styles and match what we could see locally.

### Production build:
![image](https://user-images.githubusercontent.com/19193499/111483453-15947780-8735-11eb-803a-8d32cf7d9212.png)

### Local environment
![image](https://user-images.githubusercontent.com/19193499/111483586-3361dc80-8735-11eb-8dce-394de95b1f54.png)

@edit
Another hint that I've fround - production seems okayish with 3.2.0 version of react-select.

**Comment by ebonow** [comment]
Greetings @pacxiu ,

First of all nice avatar 😎

Secondly, I took a look at the yarn lock file and it looks like theme-ui is using Emotion 10 and the newest version of react-select uses Emotion 11 so it's likely a conflict there.

Fortunately, it looks like the latest version of `theme-ui' updated their dependency to Emotion 11, would it be possible to give it a try and see if you have better results?

**Comment by pacxiu** [comment]
@ebonow yeah, that was it, thanks for guiding!

**Comment by binajmen** [comment]
Hi @pacxiu and @ebonow,

I've a similar issue on my current project. Not quite sure how I should fix it though. Would you mind to have a look? 🙏 🙏 

I'm using `react-google-places-autocomplete` that uses `react-select` that uses `@emotion/react` that raises the error:

`You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.`

Combined with the `prefetch` capabilities of NextJS, it results in broken styles.

https://github.com/emotion-js/emotion/issues/2343

**Comment by ebonow** [comment]
@mattvb91  react-select uses Emotion which is a CSS-in-JS solution by injecting style tags into the body of the document.

I suppose there could be a conflict in the styles if the maps api relies on an iframe.
