### ISSUE TITLE
Why cypress tests use force if it's not recommended?

### ISSUE THREAD

**Issue by MikeKoval** [JedWatson/react-select#4507]
Hi!
I noticed that react-select cypress tests use force: true, i copied some tests into our project, then enabled eslint and noticed errors
"Do not use force on click and type calls  cypress/no-force".
https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-force.md

Wondering why react-select uses it and maybe there is better way to not use bad practice?

**Comment by ebonow** [comment]
Greetings @MikeKoval,

Thanks for bringing this up. Per the Cypress documentation:
> Forcing
> While the above checks are super helpful at finding situations that would prevent your users from interacting with elements - sometimes they can get in the way!

> Sometimes it’s not worth trying to “act like a user” to get a robot to do the exact steps a user would to interact with an element.

> Imagine you have a nested navigation structure where the user must hover over and move the mouse in a very specific pattern to reach the desired link.

> Is this worth trying to replicate when you’re testing?

> Maybe not! For these scenarios, we give you an escape hatch to bypass all of the checks above and force events to happen!

This seems relevant to the type of testing especially for use cases where the Menu is scrolled and then clicked. Curious on your thoughts though and whether you've had an opportunity to run the tests without using force to identify any issues that we might be missing.

**Comment by ebonow** [comment]
@MikeKoval wanted to know if you had anything to add given the comments I left above.

**Comment by MikeKoval** [comment]
>This seems relevant to the type of testing especially for use cases where the Menu is scrolled and then clicked. 
Maybe filtering could be used?

>Curious on your thoughts though and whether you've had an opportunity to run the tests without using force to identify any issues that we might be missing.
No, did not try, but i think it will fail to click on invisible element without force: true.

Ok, i think we can close the ticket.
