### ISSUE TITLE
more than one Select in a Component

### ISSUE THREAD

**Issue by luodaxu** [JedWatson/react-select#451]
now I need more than one Select in a Component, How can i choose the specific Select and when first Select Component selected value change the second one will rerender the options...do not use React state will be better
Is it possible? Thanks

**Comment by PetrGlad** [comment]
Add callback to first select that will change properties of second one.
Most likely  you have 2 select components in your JSX that have their own properties. You change properties and components are updated by React. No need to refer components directly (although you can).  
Is this what you mean?

**Comment by brianreavis** [comment]
(closing because i'm assuming this is resolved)
