### ISSUE TITLE
Scroll doesn't work in Shadow DOM

### ISSUE THREAD

**Issue by ajotka** [JedWatson/react-select#4512]
At first I would like to thank you for your work. I use react-select in basically every project. 

I have a project that is entirely written in Shadow DOM. 
To my surprise, react-select doesn't work properly in shadow root. 

Styles don't work, emotion lib doesn't work, inline styles don't work.
But it's a small thing, I solved it by adding my own classNames and own css styles.

Broken events are the biggest problem. Click/Touch works, but not scroll (wheel event) or keyboard events.

**Codesandbox:**
https://codesandbox.io/s/react-select-shadow-root-7grpg?file=/src/index.js

Issue with styles (emotion css): 
https://github.com/JedWatson/react-select/issues/3680

**Comment by engray** [comment]
I have same problem :/

**Comment by ebonow** [comment]
Thanks for reporting this. We are working diligently on getting the conversion from Flow to TypeScript. Once released, addressing the scroll/wheel event will be near the top of the list as well as other Menu related fixes.

We can further look into keyboard events as well.

**Comment by Rall3n** [comment]
Hello @ajotka,

exactly what scroll/keyboard events are not working? Could you please go into more detail?

-----

Regarding Shadow DOM styling issue #3680 has been updated with a solution of how it should be done.

**Comment by ebonow** [comment]
Closing as resolved.
