### ISSUE TITLE
Can't control the filtering when using creatable / broken filtering

### ISSUE THREAD

**Issue by alexandernst** [JedWatson/react-select#4517]
I have a use case in which I want the following things:

1) Fill the dropdown with predefined elements
2) Make a fetch and pull some additional elements when the menu gets opened (emulated with a `setTimeout` and a `Promise` in my demo)
3) Make it possible to create new elements by typing inside the dropdown without filtering the currently shown elements

"1" and "2" are easy to implement, but adding "3" to the mix seems impossible.
As soon as I start typing, the "Create new" element shows up, and everything else is filtered.

Demo: https://codesandbox.io/s/react-select-v3-sandbox-forked-x3qy2?file=/example.js

It seems that this should be possible by using the `filterOption={() => true}` prop in order to avoid elements to get filtered / hidden, but in practice it doesn't seem to be working.

Is this a bug or is this the expected behaviour?

**Comment by alexandernst** [comment]
Revisiting this, I realized that the filtering itself is broken.

The dropdown has the following elements by default:

* Foo
* Bar
* Loaded value 1 (this one appears after 2500ms)

If I type "F", I'd expect the "Foo" element to be visible (and maybe the "Create 'F'" text to appear at the top of the menu list), but that's not what's happening.

Unless I'm really misunderstanding the docs and the expected behaviour, this seems like a bug.

**Comment by ebonow** [comment]
Greetings @alexandernst ,

The expected behavior of `Async` or `CreatableAsync` is to have a `loadOptions` prop which provides the function that should be called on input to provide a set of new options to the select.

It would appear both of your examples are missing this prop.

Please let me know if this helps.

**Comment by ebonow** [comment]
If you are still unable to get options to appear after adding the loadOptions prop, then let us know and we can re-open this ticket.

**Comment by alexandernst** [comment]
@ebonow Sorry for taking so long to reply. Unfortunately, `loadOptions` won't allow me to "retrigger" it every time the menu is opened. This is why I'm relying on the `onMenuOpen` prop and custom state management.

**Comment by alexandernst** [comment]
@ebonow Expanding on my previous comment:

The `loadOptions` functionality is very limited. For example, it will hide all the "defaultOptions" element while the "loadOptions" function is resolving the new elements.
It won't trigger until the user has actually written something in the select (which makes it impossible to have default options and fetch "dynamic" options without user interaction).

I'm aware that setting the "defaultOptions" to `true` will make the `loadOptions` function to be called immediately, but then I can't set a default set of elements and I'm forced to rely only on whatever the "loadOptions" function returns. It's actually worse than that: The user isn't seeing anything until the "loadOptions" function resolves, which might take a while.

I added a couple of demos in my original question. Please take a look at them. Note that a few things happen in my demos:

1) The dropdown is prefilled with default options
2) Some more elements are added once the user opens the menu

Can the `loadOptions` function could be somehow triggered when the element is mounted? And make it *not* hide the current elements while the new elements are being loaded?

**Comment by alexandernst** [comment]
@ebonow Expanding even further: on a related note, the issue described here is affecting my use case: https://github.com/JedWatson/react-select/issues/3047

Basically, even if I went with the `loadOptions` way, my default elements still won't show then a search is performed. 
Which is why I want to be able to control the filtering function and avoid select2 to hide any elements.

**Comment by ebonow** [comment]
@alexandernst 

If you do not plan on using the `loadOptions` prop, then perhaps what you are looking for is a normal Select as the AsyncSelect is merely an abstraction to make typeahead lookups easier to implement. This would also allow you more control over how and when the options load. 

- options can exist in state initialized to some defaultOptions
- onMenuOpen you can fetch additional options and append it to the defaultOptions
- onMenuClose you can reset the options to the defaultOptions

If you wish to instead load the options onMount, this is much easier. You can also still optionally add the isLoading prop to indicate api loading activity. 

```jsx
const defaultOptions = [{ label: 'Foo', value: 'foo' }];
const toOptions = ({ id, name }) => ({ label: name, value: id });

const [ options, setOptions ] = useState(defaultOptions);
const [ isLoading, setIsLoading ] = useState(false);

useEffect(() => {
  setIsLoading(true);
  api.getOptions().then(apiOptions => {
  
    const newOptions = [
      ...options,
      ...apiOptions
    ];
    
    setOptions(newOptions);
    setIsLoading(false);
  }, 
}, []);

return <Select options={options} isLoading={isLoading} {...otherProps} />
}

```

Let me know if I perhaps missed something that you are trying to achieve.

**Comment by alexandernst** [comment]
Thank you for the reply! Let me give this approach a shot

**Comment by alexandernst** [comment]
@ebonow I'm getting back just to say that removing the Async component and managing the state myself completely worked out! Thank you once again!

**Comment by ebonow** [comment]
@alexandernst Thanks for following up and glad it's working for you!
