### ISSUE TITLE
Filtering a Creatable select breaks when `formatCreateLabel` returns a React node

### ISSUE THREAD

**Issue by jamesonhill** [JedWatson/react-select#4519]
If you use the creatable component (ie `import ReactSelect from "react-select/creable"`), the entire react node of the create-able option is passed to the option's label in the `filterOption` function prop. The typings state that `filterOption` receives `{ label: string; value: string; data: any }`, so you should be able to do the following:
```
filterOption={createFilter({ stringify: option => option.label })}
```
however due to the above mentioned issue the entire component will crash due to the option's label being a node and not a string.

Here is a repro on the v3 fork: https://codesandbox.io/s/react-select-v3-sandbox-forked-v7b9t?file=/example.js

**Comment by Rall3n** [comment]
Hello @jamesonhill,

> however due to the above mentioned issue the entire component will crash due to the react node being passed to this function instead of an object.

to clarify: The object representing the option is still passed as an argument to the `filterOption` prop. It's just that the `label` property is a react `Node` which is a direct cause of returning a `Node` from `formatCreateLabel` (as used in your example sandbox). Returning a string instead and handling format through other means (`formatOptionLabel`, overwriting `Option` component) would circumvent the issue on your end.

```jsx
<Creatable 
    formatCreateLabel={(value) => `create ${value}`}
    formatOptionLabel={(option) => option.__isNew__ ? <span>{option.label}</span> : option.label}
/>
```

-----

But the base issue can be confirmed. Uncertain if it should by labeled as a documentation/typing issue or a general code issue. This will be brought up for discussion.

**Comment by jamesonhill** [comment]
@Rall3n good point. I updated my description to clarify the base issue of the label being a node instead of string.

**Comment by ebonow** [comment]
This has been fixed in recent versions. 
https://codesandbox.io/s/react-select-v3-sandbox-forked-ndg2r?file=/example.js
