### ISSUE TITLE
Options Menu stays open when you add transition property to styling

### ISSUE THREAD

**Issue by skanderbenalaya** [JedWatson/react-select#4526]
Hi, i'm starting to use react-select and been doing some styling, but after some testing i found out that when i select options in the menu and switch between them quickly, the menu closes then opens up again after the selection. It does close again if you do any action on the screen (like scrolling or clicking anywhere).
Seems like a visual bug, the item i select is the correct one returned in the console log call.

Thanks for the support.

**Comment by ebonow** [comment]
Greetings @skanderbenalaya ,

Can you please share a codesandbox or minimal reproducible code so we can identify any potential library bugs vs implementation discrepancies?

**Comment by skanderbenalaya** [comment]
The problem seems to be fixed after a restart of the server, maybe hot reloads after a lot of style changes made it bug like that, but now it's all smooth. Sorry for the disruption and thank you.
