### ISSUE TITLE
`LiveRegion` call to `isOptionDisabled` omits secondary argument.

### ISSUE THREAD

**Issue by bartram2** [JedWatson/react-select#4527]
The docs show that the `isOptionDisabled` prop should be a callback function that accepts two arguments, the option and the selected value. The LiveRegion component does not include the second argument when calling `isOptionDisabled`, so implementations that rely on the second argument will receive `undefined` instead.

https://github.com/JedWatson/react-select/blob/b0411ff46bc1ecf45d9bca4fb58fbce1e57f847c/packages/react-select/src/components/LiveRegion.js#L74

**Comment by Methuselah96** [comment]
Fixed in https://github.com/JedWatson/react-select/pull/4489.
