### ISSUE TITLE
Typing in examples does not work

### ISSUE THREAD

**Issue by PetrGlad** [JedWatson/react-select#453]
Typing does not allow to select existing values in any of examples on the site on site https://jedwatson.github.io/react-select/ (with Firefox and Chrome).
I tried precompiled demos from git repo / dist and they work as expected.
Probably site is outdated or not configured properly.

**Comment by gwyneplaine** [comment]
2.x.x comes with a brand new [site](https://www.react-select.com) with working examples!

Closing this issue, if for some reason you feel that what I've described above doesn't correctly address your problem, please feel free to create a new issue. Mostly doing this for clarity ad to reduce our issues list down to a sane and relevant number of actionable tasks.
