### ISSUE TITLE
When the menu is open, state.menuIsOpen can be false

### ISSUE THREAD

**Issue by Slapbox** [JedWatson/react-select#4534]
# Bug

When the menu is open, `reactSelect.current.state.menuIsOpen` can be false.

Unfortunately I've not been able to reproduce the issue reliably yet. https://codesandbox.io/s/react-select-v3-sandbox-forked-0urxx?file=/example.js

We're trying to rely on the internal state for some logic to avoid having to spaghetti-code things, but unfortunately it's returning this unexpected result right now.

**Comment by Slapbox** [comment]
Ahh I see now. `menuIsOpen` is being treated like it really means `inputIsFocused`

Here's a workable example: https://codesandbox.io/s/react-select-v3-sandbox-forked-omflh?file=/example.js

If you click out of the React-Select component, `menuIsOpen` becomes false even though it's explicitly receiving the `menuIsOpen={true}` and is a controlled component.

**Comment by Rall3n** [comment]
Hello @Slapbox,

I believe the component you are `ref`erencing is the `StateManager` component. This component handles behavior for an uncontrolled `Select` component. This includes handling the value, the search string and last but not least the open state of the menu.

If you really want to depend on the state of the component, I suggest you use the `ref` to the `Select` component instead and check the state through the props.

```jsx
// `select` is the reference to the `Select` component in the `StateManager` component
reactSelect.current.select.props.menuIsOpen
```

**Comment by Slapbox** [comment]
@Rall3n thanks for your reply, that's a good tip! We're using React-Select as a conditionally controlled component, so there are times we want to know if the menu is open when that state is being managed internally by React-Select, so that's a great help!

I did find a workaround for our particular use case, and another workaround it sounds like might work would be: `current.state.menuIsOpen || current.select.props.menuIsOpen`

Thanks again for your help!

----

PS: This question is just more of a curiosity, but would you happen to know where in React-Select the code is that decides whether the menu is open and how it works differently for controlled/uncontrolled components? We're doing some stuff that forces us to rely on React-Select's internal states/functions so I'm trying to understand as much of it as I can.
