### ISSUE TITLE
async react-select OVERRIDING chakra ui css.

### ISSUE THREAD

**Issue by danielmaartens-sovtech** [JedWatson/react-select#4541]
@JedWatson 

We're using ChakraUI and using your react-select/async component in our project results in our CSS to be overridden and to look like this:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/59686723/115015416-e39d3f00-9eb3-11eb-88cb-d1f908459328.png">

We're going live on Monday and would really appreciate your help here!

Is there any way we can use your react-select/async component without the styling package you use so that it won't override our core css package?

**Comment by danielmaartens-sovtech** [comment]
Your component is the only one that is being rendered properly.

**Comment by ebonow** [comment]
Greetings @danielmaartens-sovtech ,

Do you have a codesandbox example available? What version of react-select are you using?

`react-select` and `chakra-ui` both appear to use emotion as the core styling mechanism, so there could be a conflict there. 

We are exploring the possibility of releasing an unstyled version of react-select to remove emotion as a dependency, but that would take quite a bit of time.

**Comment by JedWatson** [comment]
I think this is related to an issue we've been made aware of upstream in Emotion, where multiple versions running on a page can cause conflicts and remove styles unexpectedly.

It's likely the versions of Chakra and React Select being included are in conflict, and that's causing the problem - we're following up with the Emotion team to try and get this resolved, and then we'll release a patch with the updated dependency.

Sorry we can't offer a quicker fix, the underlying problem is pretty delicate and out of our hands

As a workaround you may have some success forcing webpack (or your bundler of choice) to include a single version of Emotion on your page.

**Comment by conoremclaughlin** [comment]
+1'ing with an additional Web Extension use case. We've been tracking down a heisenbug for our Web Extension and it ends up react-select, which we load in Shadow DOM-wrapped components via content scripts will blow the emotion cache for the original page itself if that page also uses Emotion. It will wipe all the styles on the page specified by the page's author via emotion. An example page would be YC's Startup School pages:

https://www.startupschool.org/curriculum

Thanks for the preliminary investigation. Given it's upstream I'll also note it in the Emotion repo.

**Comment by binajmen** [comment]
> I think this is related to an issue we've been made aware of upstream in Emotion, where multiple versions running on a page can cause conflicts and remove styles unexpectedly.
> 
> It's likely the versions of Chakra and React Select being included are in conflict, and that's causing the problem - we're following up with the Emotion team to try and get this resolved, and then we'll release a patch with the updated dependency.
> 
> Sorry we can't offer a quicker fix, the underlying problem is pretty delicate and out of our hands
> 
> As a workaround you may have some success forcing webpack (or your bundler of choice) to include a single version of Emotion on your page.

Hope this response from @Andarist can help:
https://github.com/emotion-js/emotion/issues/2343#issuecomment-817265816

**Comment by ebonow** [comment]
Greetings @danielmaartens-sovtech, @conoremclaughlin , and @binajmen , 

I am not sure this has been properly communicated, but we've released 4.3.1 to address this specific issue. We will be closing this, but please feel free to reply or open another issue if the observed behavior persists.
