### ISSUE TITLE
It doesn't work with Next.js & CSS modules production build

### ISSUE THREAD

**Issue by piotrrussw** [JedWatson/react-select#4547]
Hi,

I am using next.js with CSS modules and trying to add react-select v4.3.0, but it doesn't work. On dev enviroemnt styling looks correct as on the image below:
![image](https://user-images.githubusercontent.com/38919699/115235503-8fe05f00-a11a-11eb-8982-cc29f0b652ca.png)

But after building application with default `next build` styles completely fails:
![image](https://user-images.githubusercontent.com/38919699/115235658-b7372c00-a11a-11eb-9342-cf4afc68dbff.png)

I think that is issue with webpack and hashing styles, but before doing more detailed debugging, I would like to ask if anyone faced this kind of issue?

Best,
Piotr

**Comment by gregg-cbs** [comment]
How are you applying the style? Can you show me a code snippet?

**Comment by akuznetsov-md** [comment]
@piotrrussw I faced a similar issue. I manage to solve it by moving style declaration inside the component:

```js
// BAD
// Doesn't work with SSR
const selectStyle = {
  control: (provided) => ({
    ...provided,
    borderRadius: 10,
    minHeight: 44,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#f5f6f7"
  })
};

const LocationSelect = (props) => {
  return (
    <GooglePlacesAutocomplete
      selectProps={{
        ...props,
        styles: selectStyle,
      }}
    />
  );
};
```

```js
const LocationSelect = (props) => {
  // GOOD!
  // Works well with SSR
  const selectStyle = {
    control: (provided) => ({
      ...provided,
      borderRadius: 10,
      minHeight: 44,
      borderWidth: 1,
      borderStyle: "solid",
      borderColor: "#f5f6f7"
    })
  };
  
  return (
    <GooglePlacesAutocomplete
      selectProps={{
        ...props,
        styles: selectStyle,
      }}
    />
  );
};
```

**Comment by ebonow** [comment]
@piotrrussw Just wanted to followup if this has been resolved yet for you?

**Comment by gregg-cbs** [comment]
@ebonow I got it right by targeting the react select classes like this:
```
.selectWrapper {
  .Select__control {
    padding-top: 0px;
    padding-bottom: 0px;
    padding-right: 0.2em;

    &--is-focused {
      color: var(--slate);
      outline: none;
      box-shadow: none;
    }
  }

  .Select__value-container {
    padding: 0;
  }

  .Select__placeholder,
  .Select__single-value {
    color: inherit;
  }

  .Select__indicator-separator {
    width: 2px;
  }
}
```

**Comment by ebonow** [comment]
@piotrrussw It's likely that the default styling is running into some conflicts. I would suggest updating to version 4.3.1 to see if the Emotion version conflict resolution fix helps with this. Any other information would also be helpful.

**Comment by piotrrussw** [comment]
@gregg-cbs @ebonow thanks for trying to help, but I decided to change react-select with another library, so I can't check right now in my project if solution works :/

**Comment by mattvb91** [comment]
@piotrrusw what library did you end up using I cant use this with nextjs / styled components because missing styles

**Comment by honia19** [comment]
https://github.com/JedWatson/react-select/issues/5710#issuecomment-1913643129
