### ISSUE TITLE
No event value in onFocus on onBlur

### ISSUE THREAD

**Issue by glenkitchen** [JedWatson/react-select#4548]
# onFocus & onBlur don't provide event.target.value

See this [codesandbox](https://codesandbox.io/s/react-select-onfocus-onblur-il7i9)  

The `onFocus` an `onBlur` events don't provide a value to `event.target.value`

Is this a bug, or is there another recommended way to get the value with `onBlur`, instead of `onChange` ?

**Comment by Rall3n** [comment]
Hello @glenkitchen,

the `focus` and `blur` events are triggered on a focus-handling `<input>` element, which in most cases is the same element you search with. As the search resets itself on losing focus by default the value of the event target is empty.

If you want to access the value of the component without using `onChange`, I recommend you use a reference to the component to access the value through it.

```jsx
const selectRef = useRef(null);

const onBlur = () => {
    // either (will always return an array)
    selectRef.current.select.getValue();
    // or (will not always return an array)
    selectRef.current.state.value;
}

<Select ref={selectRef} onBlur={onBlur} />
```

**Comment by glenkitchen** [comment]
Thanks @Rall3n. Your recommendation works.

**Comment by glenkitchen** [comment]
Update for v5

Use ```selectRef.current.getValue();``` instead of ```selectRef.current.select.getValue();```

See 'Use forwardRef for all wrapped components' at [Upgrade Guide](https://react-select.com/upgrade)
