### ISSUE TITLE
onClose fires before onChange

### ISSUE THREAD

**Issue by sheam** [JedWatson/react-select#4549]
The onClose event is firing before the onChange event. This is causing a lot of issues with my application.

As a work around, I tried storing the `closing` state, by calling `setClosing(true)` in the onClose event. Then in the onChange handler, I check if `closing` is true, and if it is, call my applications closeHandler. But the two events from Select seem to fire right after one another, so that event those `setClosing(true)` is called first, the value of `closing` is still false in the onChange event.

You can see the issue here: https://codesandbox.io/embed/react-codesandboxer-example-forked-rq31s?fontsize=14&hidenavigation=1&theme=dark

**Comment by ebonow** [comment]
Greetings @sheam ,

version 1.2.1 is considered deprecated. Using the most recent version (v4.3), this no longer appears to be an issue. 

[codesandbox](https://codesandbox.io/s/react-codesandboxer-example-forked-ijw9s?file=/example.js
)

If you have any further concerns about this, please feel free to reply, but it seems that this can be closed.

**Comment by blurymind** [comment]
upgrading to ^4.3 doesnt fix this at all for me. Whats interesting is that it happens on the initial mount. After you click it the first time and fail, it starts selecting again
