### ISSUE TITLE
 menuIsOpen is broken when menuPosition="fixed"

### ISSUE THREAD

**Issue by declan-warn** [JedWatson/react-select#4551]
If you set `menuIsOpen={true}` and use `menuPosition="fixed"` then the menu will not be open initially. After manually opening the menu, by clicking on the select, then the menu will stay open.

## CodeSandbox
https://codesandbox.io/s/react-select-issue-m2veo

## Related
https://github.com/JedWatson/react-select/issues/3708 seems related, observing a similar issue but with different causes.

**Comment by ebonow** [comment]
Thanks for reporting @declan-warn ,

There are several existing issues we'll round up and look to resolve regarding fixed positioning and portaling that will be the focus of development following the TypeScript rewrite that is currently underway.
