### ISSUE TITLE
how to rename the (create) name in Creatable Multiselect

### ISSUE THREAD

**Issue by karthiktrp102** [JedWatson/react-select#4552]
![Screenshot (50)_LI](https://user-images.githubusercontent.com/77161149/115872614-a1e63880-a45f-11eb-904d-ce702ae93a12.jpg)

**Comment by BATCOH** [comment]
```jsx
<CreatableSelect
  {...props}
  formatCreateLabel={(value) => `Whatever ${value}`}
/>
```
https://react-select.com/props#creatable-props

**Comment by karthiktrp102** [comment]
how to change styles for that

**Comment by BATCOH** [comment]
```jsx
<CreatableSelect
  {...props}
  styles={{
    option: (provided, state) =>
      state.data.__isNew__ ? { ...provided, color: "pink" } : provided,
  }}
/>
```
https://react-select.com/styles

**Comment by karthiktrp102** [comment]
@BATCOH need to add styles only for formatCreateLabel

**Comment by BATCOH** [comment]
Yep, my example is exactly for this case.
"option" means any option, but you you can apply styles to creation label only with `state.data.__isNew__` condition.

**Comment by karthiktrp102** [comment]
@BATCOH <CreatableSelect
      styles={{
        formatCreateLabel: (provided, state) =>
          state.data.__isNew__ ? { ...provided, color: "blue" } : provided,
      }}
      isMulti
        isClearable
        onChange={this.handleChange}
        onInputChange={this.handleInputChange}
        options={colourOptions}
        formatCreateLabel={(value) => `+ Add item ${value}`}
      />

like this but its not change color

**Comment by BATCOH** [comment]
```jsx
<CreatableSelect
  isMulti
  isClearable
  onChange={this.handleChange}
  onInputChange={this.handleInputChange}
  options={colourOptions}
  // Rename label
  formatCreateLabel={(value) => `+ Add item ${value}`}
  // Apply style
  styles={{
    option: (provided, state) => {
      if (state.data.__isNew__) {
        // Styles for "Add item" option
        return { ...provided, color: "blue" };
      } else {
        // Default styles for other options
        return provided;
      }
    },
  }}
  />
```

**Comment by ebonow** [comment]
Thank you @BATCOH. I think it is safe to mark this as closed.
