### ISSUE TITLE
Portaling bugged with scrollable parents

### ISSUE THREAD

**Issue by Etheryte** [JedWatson/react-select#4554]
When using [portaling](https://react-select.com/advanced#portaling), the dropdown position becomes bugged when a parent is scrolled while the dropdown is open.

https://user-images.githubusercontent.com/3171718/115887093-e23eba00-a451-11eb-9719-6b5a7dcfe8df.mov

Repro case: https://codesandbox.io/s/react-select-v3-sandbox-forked-lgkms  
Also reproducible on [the docs page](https://react-select.com/advanced#portaling) if you manually edit the layout to have overflow.  

This is a pretty common issue with dropdown libraries, common solutions include closing the dropdown on any parent scroll or trying to dynamically keep the position updated with a transform.

**Comment by ebonow** [comment]
Thanks for reporting @Etheryte ,

There are several existing issues we'll round up and look to resolve regarding fixed positioning and portaling that will be the focus of development following the TypeScript rewrite that is currently underway.

**Comment by Methuselah96** [comment]
Can you set the `menuPortalTarget` to be the div element that actually does the scrolling?

CodeSandbox: https://codesandbox.io/s/react-select-v3-sandbox-forked-un5el?file=/index.js

**Comment by Etheryte** [comment]
@Methuselah96 Thanks for taking the time to look at this. While that would work for dropdowns which fit into the parent viewport (shown in blue below), you will end up with cropping on longer dropdowns — the very problem that portaling is meant to solve.  

<img width="857" alt="Screenshot 2021-05-07 at 16 44 15" src="https://user-images.githubusercontent.com/3171718/117466979-8f85f780-af53-11eb-9987-879b8452a17a.png">

**Comment by Methuselah96** [comment]
This is the same issue as reported in https://github.com/JedWatson/react-select/issues/4088, so I'm going to go ahead and close this in order to consolidate the issues. Thanks for the helpful reproduction case, we hope to make some progress on this soon.
