### ISSUE TITLE
How to change the value of React-Select using React-Hook-Form

### ISSUE THREAD

**Issue by beverlylaurel** [JedWatson/react-select#4558]
I'm using react-hook-form to manage my forms
and also using react-select for my select elements
What I want to do is actually very simple but I just couldn't do it and I'm stuck here.

I want to change the value of react-select with external conditions but how do I do this with react-hook-form

The code sample I've written. I want to get the selected value on the radio and set it to react-select

https://codesandbox.io/s/react-hook-form-controller-v5-forked-ndh54?file=/src/index.jsx

note: if the react-select value changes, the radio does not need to be changed either. the main purpose is to manipulate react-select from radio

**Comment by beverlylaurel** [comment]
use setValue api

https://react-hook-form.com/api/useform/setvalue

**Comment by ebonow** [comment]
As a side note, we are working on new documentation and form management examples is something on our radar

**Comment by beverlylaurel** [comment]
> As a side note, we are working on new documentation and form management examples is something on our radar

@ebonow 
Good news. thanks. It may take some time to use it with other plugins. but it works just great.

**Comment by nerijunior** [comment]
@mustafatas0 following your example I couldn't replicate the same behavior using updated versions of both libraries.

Could you help me to find if it's a bug or I'm using it in the wrong way?

https://codesandbox.io/s/nameless-glade-bkou7?file=/src/App.tsx

**Comment by bin** [comment]
The above example is currently not working on version `5.0.0` with typescript; the `options` prop gives a type error that necessitates `ts-ignore`.  Any ideas on how to resolve this?

**Comment by Methuselah96** [comment]
Try setting the first generic:
```
<ReactSelect<SelectOption>
    options={categoryOptions}
    ...
/>
```
