### ISSUE TITLE
TypeError: Object(...) is not a function [NOT USING WEBPACK]

### ISSUE THREAD

**Issue by varshneymehul** [JedWatson/react-select#4563]
Greetings
I have installed React Select latest version in my Create React App. 
I have created a different issue because I am NOT using Webpack and still seeing this error.
I am seeing this error by just importing React Select:
```
TypeError: Object(...) is not a function
createCache
D:/Web Development MEHUL/CovidHelp/client/node_modules/@emotion/cache/dist/emotion-cache.browser.esm.js:254
  251 | } : rulesheet(function (rule) {
  252 |   currentSheet.insert(rule);
  253 | })];
> 254 | var serializer = middleware(omnipresentPlugins.concat(stylisPlugins, finalizingPlugins));
  255 | 
  256 | var stylis = function stylis(styles) {
  257 |   return serialize(compile(styles), serializer);
```

This is my Component for which error is coming:
```
import React from "react";

import { Select } from "react-select";
import csc from "country-state-city";
import { ICountry, IState, ICity } from "country-state-city";

function Blood() {
  const states = csc.getStatesOfCountry("IN");
  console.log(states);
  return <div></div>;
}

export default Blood;

```

My package.json looks like this
```
{
  "name": "covid-help",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.6.0",
    "country-state-city": "^2.1.0",
    "firebase": "^8.4.3",
    "firebaseui": "^4.8.0",
    "react": "^16.2.0",
    "react-bootstrap": "^1.5.2",
    "react-dom": "^16.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "1.0.17",
    "react-select": "^4.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "proxy": "http://localhost:5000",
  "devDependencies": {
    "autoprefixer": "^9.8.6",
    "postcss": "^7.0.35",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.1.2"
  }
}
```

**Comment by ebonow** [comment]
Greetings @varshneymehul ,  

You are going to need a minimum React version of 16.8.

-  What are you using for your build process? 
- Can you share your package-lock?

**Comment by ebonow** [comment]
@varshneymehul it also looks like you are incorrectly importing the Select.

``` jsx
import { Select } from "react-select";
```

should be:

``` jsx
import Select from "react-select";
```

**Comment by varshneymehul** [comment]
@ebonow I forgot to tell you, I have imported both the ways and still the same error comes up. I have deleted and reinstalled node modules as well.

**Comment by varshneymehul** [comment]
> Greetings @varshneymehul ,
> 
> You are going to need a minimum React version of 16.8.
> 
> * What are you using for your build process?
> * Can you share your package-lock?

@ebonow I am not using anything for my build process. I am not really an experienced React developer but if you mean webpack, I have not installed it. 
My package lock.json can be viewed here:

**Comment by ebonow** [comment]
Would you kindly also update your version of react-scripts and try again? 1.0.17 seems awfully out of date as well.

**Comment by varshneymehul** [comment]
@ebonow thanks a lot. I updated everything and eventually moved to Webpack, now it works. Not sure why it did not work before.
