### ISSUE TITLE
when adding isValidNewOption the 'create ""' option is always on

### ISSUE THREAD

**Issue by dudilugasi** [JedWatson/react-select#4564]
# Are you reporting a bug or runtime error?

i want to add validation on new options but it seems to change the default behavior when I'm clicking on the input 

![image](https://user-images.githubusercontent.com/10431969/116970175-2cc8fd80-acc0-11eb-86ef-486f6577aba8.png)

```
import React, { Component } from 'react';
 import CreatableSelect from 'react-select/creatable';
const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
]

export default class CreatableSingle extends Component<*, State> {
  handleChange = (newValue: any, actionMeta: any) => {
    console.group('Value Changed');
    console.log(newValue);
    console.log(`action: ${actionMeta.action}`);
    console.groupEnd();
  };
  handleInputChange = (inputValue: any, actionMeta: any) => {
    console.group('Input Changed');
    console.log(inputValue);
    console.log(`action: ${actionMeta.action}`);
    console.groupEnd();
  };
  render() {
    return (
      <CreatableSelect
        isClearable
        onChange={this.handleChange}
        onInputChange={this.handleInputChange}
        options={options}
        isValidNewOption={() => true}
      />
    );
  }
}
```

**Comment by ebonow** [comment]
Greetings @dudilugasi ,

This is the expected behavior `isValidNewOption`, per the specs: 

> isValidNewOption function = (inputValue, selectValue, selectOptions, accessors) => undefined

> Determines whether the "create new ..." option should be displayed based on the current input value, select value and options array.

Returning true will always make the option appear, so I will close this issue, but I am willing to discuss further to help figure out what kind of behavior you are trying to implement.
