### ISSUE TITLE
Creatable does not work with custom option component

### ISSUE THREAD

**Issue by genesis-algorithms** [JedWatson/react-select#4565]
Hi, I'm trying to use Creatable with a custom option component using the components prop but when I do that the creatable (create new option) functionality stops working.

Example: https://codesandbox.io/s/happy-cray-x9s5v?file=/src/App.js

**Comment by genesis-algorithms** [comment]
Think I've found my problem but sadly after opening the issue :( sorry. Looks like I have to put the `children` prop inside my custom option component.

**Comment by ebonow** [comment]
Greetings @genesis-algorithms ,

If you are creating an Option component, then all of the data you provide will be available via the Option props. There is also a `formatOptionLabel` prop which allows you to render the component's JSX.

Also if you are replacing the Option component, keep in mind that you would need to pass in the `innerRef` if you are not using and spreading the component props into a `<components.Option>`

I'll close out the issue, but let me know if you have any other questions.
