### ISSUE TITLE
Question: Disabling removal of items in multiselect

### ISSUE THREAD

**Issue by sconno05** [JedWatson/react-select#458]
Is there a way to disable the removal of an individual value in multiselect mode?  I have a use case where a user can select multiple things, but some items are locked in, meaning they cannot be removed from the list.  I'd really need two things here:

1. Disable or hide the "X" when the item is in the list of current values.
2. Apply a different class to a disabled value so that I can style it differently.

**Comment by medv** [comment]
+1 Would be nice to render "ticks" next to each item visually signifying that multi-selection is possible, and styling the item to be ticked and greyed out when already picked.

**Comment by slybridges** [comment]
+1 I have a similar use case (in a certain situation, a multi select is prepopulated with 1 selected option that the user cannot remove).

Did anybody find a workaround for this ?

**Comment by slybridges** [comment]
I've created a PR suggesting a fix.
@JedWatson - let me know any comment.
