### ISSUE TITLE
Native `select` inside `MenuList` not working

### ISSUE THREAD

**Issue by vjee** [JedWatson/react-select#4580]
When rendering a native html `select` inside a custom `MenuList` component, the default behaviour of the browser (opening the select) is prevented.
It helps to add `onMouseDown` to the `select` with `(event) => event.stopPropagation()` to allow the native html `select` to open but also causes the `react-select` menu to close.

Here is a small repro: https://codesandbox.io/s/react-select-v3-sandbox-forked-t3g1k

Is this intended behaviour?
Shouldn't the menu stay open because of the `event.stopPropagation()`?
Is there a workaround?

Thanks in advance.

**Comment by ebonow** [comment]
Thanks as always @Rall3n for holding down the fort. Very appreciated! 

It appears that this is resolved now, but if you feel otherwise @vjee let us know and we can discuss more or re-open if necessary.
