### ISSUE TITLE
Option to wait before sending queries for asyncOptions

### ISSUE THREAD

**Issue by oliversong** [JedWatson/react-select#459]
It would be nice if we could specify a time delay to wait after the last keystroke before calling asyncOptions, so it doesn't make unnecessary requests.

**Comment by PSkierniewski** [comment]
Bump, as far as I can see asyncOptions are fired on change, is it possible to fire it when user stops typing?

**Comment by oliversong** [comment]
It's implemented in my branch https://github.com/JedWatson/react-select/pull/473 @PSkierniewski

**Comment by PSkierniewski** [comment]
@oliversong Thx I used it and it works.

**Comment by tommyalvarez** [comment]
@oliversong i need this too. Could you submit a PR to this library so the owner can merge it?

**Comment by phamthaibaoduy** [comment]
For those who might need, for now you can have debouncing by wrapping your loadOptions callback by lodash/debounce 

```
const wait = 500; // milliseconds
const loadOptions = input => dataStore.getData(input)
const debouncedLoadOptions = _.debounce(loadOptions, wait)

return <Async loadOptions={debouncedLoadOptions} ... />
```
