### ISSUE TITLE
Options looks disabled and not triggering onChange when clicked

### ISSUE THREAD

**Issue by vitorregisrr** [JedWatson/react-select#4591]
How you can see I'm using a really basic setup inside a Next.js application, just using the components with basic properties and when I click on an option it's just not triggering the onChange event... Also, it's are looking as disabled options!

May can anyone help?

Best.

![image](https://user-images.githubusercontent.com/9900252/118741789-7e779900-b825-11eb-8c8b-fcfe4115fc87.png)

![image](https://user-images.githubusercontent.com/9900252/118741800-86cfd400-b825-11eb-8fbb-d851b1af5726.png)

**Comment by vitorregisrr** [comment]
I really think snippets and code examples will be not necessary... But if it's, just ask for and I will send. Ty

**Comment by Rall3n** [comment]
Hello @vitorregisrr,

the text color of the option elements is set to `inherit` by default. It is possible that they are changed by any parents text color definition (outside of the `Select` component). This would explain the "disabled" look on the options.

The other issue (no `onChange`) I can't reproduce with a basic setup. What is the `FormSelectWrapper` component? Does it change the props of its child component?

Would you mind providing a live code example using [this CodeSandbox example](https://codesandbox.io/s/react-select-v3-sandbox-jgdch)?

**Comment by vitorregisrr** [comment]
Hey @Rall3n!

Your question makes me think about the component parents...

FormSelectWrapper is just a dumb container wrapper, but this part of my application is inside a react-leaflet map.

So, what i did is to move the filtering form to outside the map, and now it's working.

Thank you for the help and sorry for starting this thread without testing that.

For people with this bug: **SEARCH AND DEBUG THE PLACE YOUR COMPONENT IS IN YOUR APPLICATION.**
