### ISSUE TITLE
Async loadOptions do not render arrays generated from the response by array.map() and array.from()

### ISSUE THREAD

**Issue by benacq** [JedWatson/react-select#4593]
My response contains an array of objects with very plenty keys so I had to extract the information I want and return a new array of objects with my preferred elements but it is not rendered in the options when I return it but when I hard code an array of objects and return it, it works.
![Screenshot from 2021-05-19 23-08-55](https://user-images.githubusercontent.com/32628708/118897588-2199e280-b8fa-11eb-8eb0-407b43cbb1de.png)
![Screenshot from 2021-05-19 22-59-09](https://user-images.githubusercontent.com/32628708/118897648-442bfb80-b8fa-11eb-91ea-2d67465c3c95.png)

The checkAccountType method returns the extracted object I am interested in.

**Comment by Rall3n** [comment]
Hello @benacq,

would you be so kind an provide more of your code specific to your usage of the `AsyncSelect` component? Preferrably in a reproducible example with [CodeSandbox](https://codesandbox.io/s/react-select-v4-sandbox-rxvsh) (API calls replaced by `Promise`).

Could you also provide information about the shape of your options?

**Comment by benacq** [comment]
CodeSandbox link

https://codesandbox.io/s/exciting-framework-e3red?file=/src/App.js

**Comment by Rall3n** [comment]
@benacq At first glance I see a typo in your options properties. I believe `lable` should be spelled `label`.

**Comment by benacq** [comment]
I corrected it and it's working but the one in my code is not working.

**Comment by benacq** [comment]
Hey @Rall3n please take a look at the sandbox again, i am using react-select with formik, i have copied my code to the sandbox, the first example i sent you is still working but the one with formik is what's causing the issue, could you please take a look for me?

**Comment by Rall3n** [comment]
@benacq Seems like you are not directly using the `AsyncSelect` component, but instead a custom wrapper component named `AsyncSelectDropDown`. This component defines the props `getOptionLabel` and `getOptionKey` referencing the properties `code` and `name`. Removing those props solves the issue.

**Comment by benacq** [comment]
Thank you very much, this fixed the issue.
