### ISSUE TITLE
src published to npm is Typescript, but have .js extension

### ISSUE THREAD

**Issue by itsjavi** [JedWatson/react-select#4596]
As you can see, the files have the .js extension,  but the contents are written in TypeScript

Version: `4.3.1`

I am using TypeScript in my project and when I import the library, there is no IDE code completion for props in WebStorm, because of the syntax errors:

<img width="1121" alt="Screenshot 2021-05-20 at 12 22 14" src="https://user-images.githubusercontent.com/122741/118963086-60658200-b966-11eb-8fee-0f55f2370e33.png">

**Comment by Methuselah96** [comment]
What you see there is actually Flow. But either way, you shouldn't be trying to import from the `src` directory. How are you importing components from react-select and do you have `@types/react-select` installed?

**Comment by itsjavi** [comment]
Ok it makes sense now, and adding @types/react-select solved the issue.

Sorry for the confusion
