### ISSUE TITLE
Select element cannot be disabled

### ISSUE THREAD

**Issue by julen** [JedWatson/react-select#46]
If you pass the `disabled` prop to the `<Select />` element, it's completely ignored.

This should:
1. Pass the prop to the hidden `<input />` element.
2. Do not render the `<Input />` element from react-autosize at all, and only display the placeholder instead.
3. Adjust the default styling for a disabled `<Select />` element.

If you are OK with it, I can provide a PR for this.

**Comment by JedWatson** [comment]
Good call @julen, I'd be really happy for a PR for this. If you want, @jossmac can do the styling for an `-is-disabled` class.

**Comment by dannyshaw** [comment]
submitted a pull request in reference to this.

**Comment by julen** [comment]
So unfortunate I have this locally done but didn't find time to create the PR :(

**Comment by JedWatson** [comment]
Closed by @dannyshaw's PR
