### ISSUE TITLE
The exiting animation on MultiValues doesn't look correct

### ISSUE THREAD

**Issue by mengX666** [JedWatson/react-select#4602]
Hi there 👋 
The current exiting animation on the multi values looks a bit janky, the demo below was recording on https://react-select.com/home
![home](https://user-images.githubusercontent.com/32695390/119419079-cb370480-bd3c-11eb-8be4-a0dc3ac55a02.gif)

![image](https://user-images.githubusercontent.com/32695390/119419566-e2c2bd00-bd3d-11eb-9fe7-cb210e6e09fe.png)
Click on "Perth" to remove it
↓
![image](https://user-images.githubusercontent.com/32695390/119419567-e5251700-bd3d-11eb-9aea-5b8e22ea4e98.png)
The 2nd "Perth" was removed, but the last 3 items ("Perth", "Darwin", "Melbourne") on the first pic were added to the end
↓
![image](https://user-images.githubusercontent.com/32695390/119419574-e7877100-bd3d-11eb-86a3-041e01561d4b.png)
3. The last 3 items were removed 

My assumption is the `index` was added to the `key` field in the `<MultiValue>` [here](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.tsx#L1604). Every time a value get removed from the list, the index would change so the `key` of the MultiValue get changed as well, which causes the rerender 🤔 

The index was add on v3.2.0, also made a codesandbox to verify that: https://codesandbox.io/s/sad-northcutt-3s5ce?file=/src/App.tsx
the animation looks good when using react-select v3.1.1 but not on v3.2.0

**Comment by ebonow** [comment]
Note: This looks mostly correct now with the release of v5. 

There is still however a minor issue present when the last multiValue is removed as the ValueContainer. The display of the ValueContainer shifts from flex to grid and causes the value to jump to a new line before exiting.
