### ISSUE TITLE
default.css is missing from dist directory

### ISSUE THREAD

**Issue by burtyish** [JedWatson/react-select#463]
`dist/default.css` is missing, causing v0.6.9 to break my build.

**Comment by wejendorp** [comment]
:+1:

**Comment by PetrSnobelt** [comment]
+1

**Comment by rlancer** [comment]
+1

**Comment by marcio** [comment]
+1

**Comment by thiagoteles** [comment]
+1

**Comment by oliversong** [comment]
+1. @JedWatson, seems like when you run the build tool from the previous commit it generates that file deletion. Did something underlying change that's confusing gulp?

**Comment by oliversong** [comment]
Hm, it's possible that one of these packages updating could have broken this https://github.com/JedWatson/react-component-gulp-tasks/commit/4c33afc950ca43875365aa3617fb10a6b88d2385

**Comment by pmast** [comment]
:+1: :dango:

**Comment by wphampton** [comment]
:+1:

**Comment by JedWatson** [comment]
Sorry this took so long to work out. @oliversong was correct, there was a problem upstream in the gulp tasks package. I've just published `v0.6.10` with the css restored.
