### ISSUE TITLE
CHANGELOG.md has changes up to version 3.1.0 only

### ISSUE THREAD

**Issue by josephmarkus** [JedWatson/react-select#4637]
### Thanks for using react-select!

Before creating an issue...

# Are you asking a question?

n/a

# Are you reporting a bug or runtime error?

n/a
 
# Are you making a feature request?

n/a

Provide as much information as possible about your requested feature. Here are a few questions you may consider answering:

n/a

# Issues

1. CHANGELOG.md has changes up to version 3.1.0 only, even though the package is at 4.3.1 at the time of writing - https://github.com/JedWatson/react-select/blob/master/docs/CHANGELOG.md
2. Also ISSUE_TEMPLATE.md contains this outdated reference:
> Please note we are currently only directing our efforts towards the current major (v3) version and beyond.

**Comment by Rall3n** [comment]
Hello @josephmarkus,

[this particular `CHANGELOG.md` file](https://github.com/JedWatson/react-select/blob/master/docs/CHANGELOG.md) is for our documentation. It updates only when there are changes to the documentation itself.

Changelogs for our releases of `react-select` can either be found [in each of the releases themselves](https://github.com/JedWatson/react-select/releases) themself or in the `CHANGELOG.md` file located at [`packages/react-select/CHANGELOG.md`](https://github.com/JedWatson/react-select/blob/master/packages/react-select/CHANGELOG.md).

-----

Regarding our outdated issue template: Thanks for bringing it to our attention. This is already on our radar.
