### ISSUE TITLE
[feature] allow to don't display option list when focus on input (for very large options set)

### ISSUE THREAD

**Issue by Ventirad** [JedWatson/react-select#4638]
We use `react-select` in our app and in some case with a very large set of options (around 500 items).

When users use these selectors, the web app suffer some lags due to loading all the items.

I was vainly looking for an option to not display options without any entry inside the input. 

Is it possible to include en option to add this feature? 

I imagine this option like a boolean or a number (a minimum of n char in input before displaying possible entry.

Thanks to read me.

**Comment by ebonow** [comment]
Greetings @Ventirad , 

There already exists a prop specifically for opening menu on focus.

**openMenuOnFocus** 
_default value: false_
> Allows control of whether the menu is opened when the Select is focused

If you wanted to implement a minLength before opening, you can do so by writing your own filterOption function to check the input length.
- Be sure to add a createFilter to use the default filtering (or pass in a config object to modify) or use your own filtering logic (ie: `(candidate.toLowerCase()).indexOf(input.toLowerCase()) > -1`)
- The input can also be used to modify whether the No Results message should be shown.

Here is a working demo: [codesandbox](https://codesandbox.io/s/react-select-min-input-length-5uut4)

Here is the code for the working demo.
```jsx
import Select, { createFilter } from "react-select";
import { compliments } from "../data/options";

const App = (props) => {
  const MIN_INPUT_LENGTH = 3;
  const filterOption = (candidate, input) => {
    return (
      // Min input length
      input.length >= MIN_INPUT_LENGTH &&
      // Use Select's default filtering for string matching by creating filter
      createFilter({})(candidate, input)
    );
  };

  // Only show no options when at min length or can create custom message
  // or return null if no minLength message desired
  const noOptionsMessage = (input) =>
    input.length >= MIN_INPUT_LENGTH
      ? "No options"
      : "Search input must be at least 3 characters";

  return (
    <Select
      filterOption={filterOption}
      noOptionsMessage={noOptionsMessage}
      options={compliments}
    />
  );
};

export default App;
```

Please let us know if anything is unclear or unresolved.

**Comment by zhil** [comment]
In latest version you should use inputValue prop in noOptionsMessage

```
 const noOptionsMessage = (input) =>
    input.inputValue.length >= MIN_INPUT_LENGTH
      ? "No options"
      : "Search input must be at least 3 characters";
```

**Comment by eshton** [comment]
thank you I had the exact same requirement.
