### ISSUE TITLE
Option to make the Selectable "material" stylable

### ISSUE THREAD

**Issue by gonzalo-rivas** [JedWatson/react-select#464]
Would be nice to complete the component to add some labels/divs to make the react compatibe with material ui (blue underline, dynamic placeholder....)

http://material-ui.com/#/

I can (indeed, im coding it modifying the original file) and then pull request.

**Comment by jgoux** [comment]
It would be awesome, this component is really important and it's not (hopefully yet) in material-ui.

**Comment by CezarLuiz0** [comment]
+1

**Comment by timaxxer** [comment]
+1

**Comment by tomRedox** [comment]
Registering an interest in this too.  @gonzalo-rivas did you have any luck getting this working?  Anything you could share?

**Comment by RyanCCollins** [comment]
Indeed, would love to see this!  Any luck?

**Comment by gerbal** [comment]
Here's my quick and dirty [Material Selector](http://codepen.io/gerbal/pen/dXaJyK) I did to replace Material UI's selector. It doesn't cover all react-select usage and the CSS is a bit rough, but it works for basic cases.

**Comment by Mythli** [comment]
Any progress?

**Comment by JTCE** [comment]
+1

**Comment by riseremi** [comment]
+1

**Comment by AnandItagi** [comment]
+1

**Comment by byronrau** [comment]
+1

**Comment by KirillSuhodolov** [comment]
+1

**Comment by denova** [comment]
+1

**Comment by sanjevShakya** [comment]
+1

**Comment by lmichailian** [comment]
+1

**Comment by galki** [comment]
this is a working example https://sharlaan.github.io/example2

**Comment by halink0803** [comment]
Any update on this?

**Comment by goodbomb** [comment]
+1

**Comment by pavanshinde47** [comment]
any update ?

**Comment by nvma** [comment]
I ended up doing good old css overriding, it does not give you a native feel like autoposition of select pop-up and other nifty details, though. But otherwise injecting [these styles](https://gist.github.com/nvma/a0db8c758534653c65b76de8709732a3) makes a [decent basic styling](https://i.imgur.com/m7TwwGT.png) of components.
It would be very nice to have a complete integration where `react-select` would use `material-ui` components directly, but one will have to rewrite a lot of stuff to achieve that.

**Comment by zsinryu** [comment]
+1

**Comment by Dynogic** [comment]
+1

**Comment by zsinryu** [comment]
@all https://material-ui.com/demos/autocomplete/#react-select has updated for V2

**Comment by iashris** [comment]
+1

**Comment by Dynogic** [comment]
> @ALL https://material-ui.com/demos/autocomplete/#react-select has updated for V2
> But as I see, use the Popper for menu would be better.

Thanks!

**Comment by nadavivry** [comment]
> @ALL https://material-ui.com/demos/autocomplete/#react-select has updated for V2
> But as I see, use the Popper for menu would be better.

But unfortunately, the only example contains a shrink label, which is not compatible with the other inputs in my forms. looks like it's not trivial to have a floating label here. would be great to get a solution for that.

**Comment by blackberry4311** [comment]
> shrink

you could use boolean check for shrink label, an example in my case:
`<Select
        classes={classes}
        className={classes.root}
        options={options}
        components={components}
        value={value}
        onChange={this.onChange}
        isClearable
        textFieldProps={{
          InputLabelProps: !_.isEqual(value, {label: '', value: ''}) && !_.isUndefined(value) ? {shrink: true} : null,
          label,
        }}
      />`
before value:
![image](https://user-images.githubusercontent.com/438441/58167203-9a3b1980-7cb5-11e9-8df2-44511e1c17bc.png)

after value:
![image](https://user-images.githubusercontent.com/438441/58167245-b2ab3400-7cb5-11e9-8a4c-b83296c866c3.png)
anyone has solution for use popper for menu in reacts-select-v2 ?
