### ISSUE TITLE
Feature: Allow replacement of DummyInput

### ISSUE THREAD

**Issue by dreamwasp** [JedWatson/react-select#4656]
# Allow replacement of DummyInput

I'd like to be able to customize or replace the `DummyInput`, as is possible with other components, as I need to be able to spread custom props onto the `<input/>` of the React-Select when `isSearchable` is false. 

Happy to work on this as well, thank you!

**Comment by ebonow** [comment]
Greetings @dreamwasp,

I was midway writing you back, got caught up in meetings, and then noticed you closed this. Just wanted to make sure you had everything you needed.

**Comment by dreamwasp** [comment]
Hi @ebonow - thank you! I realized I didn't give you much info here so am putting together a more comprehensive issue summary / proposal.

**Comment by ebonow** [comment]
Please feel free to add it to the Discussions under Ideas.
