### ISSUE TITLE
creating new options is not showing up in the dropdown list of options

### ISSUE THREAD

**Issue by mehrdadrafiee** [JedWatson/react-select#4665]
Hi! Thanks for creating this cool library. I just came across an issue where user can create an option using `CreatableSelect` component but the option won't be visible in the list of options.

I've attached a screenshot where this issue happens even in https://react-select.com/creatable page.

![Screen Shot 2021-06-28 at 11 14 52 AM](https://user-images.githubusercontent.com/7308807/123685150-3aec5380-d803-11eb-9cdb-de78965235e6.png)

**Comment by ebonow** [comment]
@mehrdadrafiee, 

This is by design as the options are passed as props to the Select without the new options. If you would like to add the new options, you would need to add it to the list of options when a new one is created.

```jsx
const [ options, setOptions ] = useState([...props.options]);
const onChange = (value, { action, option }) => {
  if (action === "create-option") {
    setOptions([...options, option ]);
  }
  props?.onChange(value);
};

return <Select {...props} options={options} onChange={onChange} />
```

Please let me know if you have other questions

**Comment by mehrdadrafiee** [comment]
@ebonow it makes sense and thanks for the prompt response + the solution! 🙏 
However, I see a similar issue where I have default values for the `CreatableSelect` component but when I add a new option, the list of options does not show the default values anymore. Here is how I'm implementing it:

```js
const MyComponent = (props) => {
  const { filters, setFilters } = props

  <CreatableSelect
    isMulti
    styles={dropDownStyle}
    components={animatedComponents}
    onChange={(selected) =>
      setFilters(selected?.map(({ label }) => label) ?? [])
    }
    options={filters.map((item, index) => ({
      label: item,
      value: index,
    }))}
    defaultValue={filters.map((item, index) => ({
      label: item,
      value: index,
    }))}
  />
}

export default MyComponent
```

![Screen Shot 2021-06-30 at 10 28 32 PM](https://user-images.githubusercontent.com/7308807/124070354-8f095a80-d9f2-11eb-8e8d-e648ef650bfb.png)


am I doing this wrong?

**Comment by ebonow** [comment]
`defaultValue` is only valid at the time of first render. You likely are looking for a controlled input implementation where you pass and set the `value` of the select as opposed to the defaultValue.

```jsx
const [ value, setValue ] = useState(props.defaultValue);
const onChange = selected => {
  setValue(selected);
  props?.onChange(selected);
}

return <Select {...otherProps} onChange={onChange} value={value} />
```
