### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by kirankumarrr** [JedWatson/react-select#4667]
**Below is the Warning Issue in ValueContainer  Class Component**

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by Input)
    in Input (created by Select)
    in div (created by ValueContainer)
    in ValueContainer (created by Select)
    in div (created by Control)
    in Control (created by Select)
    in div (created by SelectContainer)
    in SelectContainer (created by Select)
    in Select (created by StateManager)
```

**Comment by Rall3n** [comment]
Hello @kirankumarrr,

I could not find any usage of a `<p>` element inside of our component so the problem has to be as a result of customization.
Could you provide more information on how this error appeared? Could you also provide a reproducible example?

**Comment by kirankumarrr** [comment]
Issue is happening in another library : sorry for the bug 

https://github.com/mui-org/material-ui/issues/21117

**Comment by immdraselkhan** [comment]
Those who are facing the same issue use this CustomTabPanel component. If you check the MUI source code, you will see returning the {children} inside a <Typography>{children}</Typography>. That is the root cause. So I modify the code by removing the <Typography> component.

MUI source code: https://github.com/mui/material-ui/blob/v5.11.11/docs/data/material/components/tabs/BasicTabs.tsx#L26
  
```
import * as React from "react";
import Box from "@mui/material/Box";

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function CustomTabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && <Box sx={{ p: 3 }}>{children}</Box>}
    </div>
  );
}

export default CustomTabPanel;
```
