### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by morr6** [JedWatson/react-select#4668]
Hi,

i'm getting an error `TypeError: Object(...) is not a function` using React-Select v4.3.1 
in `emotion-cache.browser.esm.js:265` file

packages versions:
react: 16.14.0 
react-scripts: 4.0.3
emotion: 11.0.0
stylis: 4.0.10

if some others packages versions can make this error please tell me which one and i will check which verion i use

**Comment by Methuselah96** [comment]
Can you take a look at https://github.com/JedWatson/react-select/issues/4448 and https://github.com/JedWatson/react-select/issues/4563 see if either of those help?

**Comment by morr6** [comment]
#4448 |  exclude node_modules in right place worked for me, thx
