### ISSUE TITLE
react-select.com website is down!

### ISSUE THREAD

**Issue by mansoor-omrani** [JedWatson/react-select#4674]
It seems the website is down.

Do something please!

**Comment by Methuselah96** [comment]
Seems to be up for me.

**Comment by ebonow** [comment]
It seems to be up for me as well.

**Comment by mansoor-omrani** [comment]
It doesn't work on my side. I even tried various kinds of VPN connections (connecting from Japan, Korea, Netherland). Nothing is shown up!

**Comment by Rall3n** [comment]
Hello @mansoor-omrani,

if you can't access the site but others still can, then it is most likely a problem on your end. And if it is, then we can't easily offer anything beyond minor suggestions on how you can fix it yourself.

Getting an "404 - Not found" error or something similar? Check your DNS settings.
Blank site? Try activating JavaScript or check if you are blocking critical resources.

**Comment by mansoor-omrani** [comment]
Hi @Rall3n.

No. It's not a 404 or javascript problem. 

After @Methuselah96 and you are saying the website is working fine there's no doubt it's a network problem. I'm just not completely sure if it's my side.

Actually, this is the first time I've ever facing such a weird problem with a website.

It happens at times though, because of the two censorship layers applied from inside and outside over the network we use in my country - Iran, (some websites are censored by order of government, others filter you as soon as they detect you are visiting them using an IP address of a banned country).

We bypass this problem by help of an anti-filter, proxy or VPN server. It works most of the time. But not this time!
