### ISSUE TITLE
Missing form labels

### ISSUE THREAD

**Issue by Hannah-goodridge** [JedWatson/react-select#4684]
Using an accessibility tool (wave chrome extension) run on your demo site and also run on the code sandbox below:

https://codesandbox.io/s/react-select-v3-sandbox-jgdch aka: https://jgdch.csb.app/
It highlights inputs that are missing labels.

The example on the sandbox was:

```
<input autocapitalize="none" autocomplete="off" autocorrect="off" id="react-select-2-input" spellcheck="false" tabindex="0" type="text" aria-autocomplete="list" value="" style="box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 1; padding: 0px; color: inherit;">
```

Not sure if this should be raised as a bug or feature request, but it would be nice to have this sorted if possible.

**Comment by ebonow** [comment]
Greetings @Hannah-goodridge ,

React-select uses an input to capture user entry to do searching through a list. As such, react-select allows users to create a label as would be expected for any other form control.

Here are two approaches:
https://codesandbox.io/s/react-select-labels-6dm02?file=/example.js

```jsx 
<div>
  <label>
    <span>Label wrapping Select</span>
    <Select options={colourOptions} />
  </label>

  <br />

  <label htmlFor="colors2">Label with htmlFor attribute</label>
  <Select inputId="colors2" options={colourOptions} />
</div>
```

Please let me know if you have any other questions regarding react-select implementation or configuring various accessibility attributes.
