### ISSUE TITLE
Is this a tailwind project issue? I can't override the class / style options

### ISSUE THREAD

**Issue by alextaymx** [JedWatson/react-select#4686]
can anyone help me on this? i am using tailwind in react js. The input seems weird 

![image](https://user-images.githubusercontent.com/58934562/125505744-bcd54438-9419-4b68-92f6-afc61340e1fb.png)
the there is an empty small box on top of the placeholder, i can't right click in the input because the width is too small , 
I wish to paste something inside the input, which requires me to increase the input width so that i can right click inside.
anyone can help me on this? thanks in advance

**Comment by donnfelker** [comment]
@alextaymx I'm having this exact same problem. That weird border. I'm also using Tailwind and cannot seem to figure out whats causing it.

**Comment by ebonow** [comment]
@alextaymx this would likely be due to styling applied to a focused input. 

``` jsx
const styles = {
  input: (css) => ({
    ...css,
    input: {
      outline: none;
    }
  })
}

return <Select styles={styles} {...otherProps} />
```

With new version 5 (currently in beta) there was a prop added to the Input component that allows a className to be directly added to the Input specifically to make it easier to work with TailwindCSS.

```jsx
const Input = props => <components.Input {...props} inputClassName="outline-none" />
return <Select components={{ Input }} {...otherProps} />
```

**Comment by ebonow** [comment]
I will close this for now, but if you are still having issues, please let me know and we can reopen this if necessary.

**Comment by alextaymx** [comment]
Thanks @ebonow for the clarification! Turns out it was due to a tailwind form plugin , I fix it using your props and also some css overwrite, thanks a lot. 

@donnfelker did u fix it?

**Comment by wh1le** [comment]
@ebonow, @alextaymx I'm on `^5.0.0-beta.0` and this removes the outline:

```jsx
import Select, { components } from 'react-select'

const Input = props => (
  <components.Input 
     {...props} 
     inputClassName="outline-none border-none shadow-none focus:ring-transparent"
  />
)

...


  render() {
    return (
      <Select
        value={this.state.selectedOption}
        onChange={this.props.onChangeEvent}
        options={this.props.options}
        components={{ Input }}
      />
    );
  }

```

**Comment by mcunningham** [comment]
@alextaymx @ebonow @donnfelker @wh1le 
The reason this occurs is likely due to the fact that you are using `@tailwindcss/forms` which add default styles to all `input[type='text']`(used in the underlying react-select input). I found that removing the input type also worked for me as `@tailwindcss/forms` didn't apply the default styles.  For example: 
```jsx
const Input = ({ type, ...rest }: InputProps) => <components.Input {...rest} />;`

```

**Comment by karimdaghari** [comment]
In case anyone wants a (pure) css solution

```css
.custom-select__input {
  @apply ring-0 !important;
}
```

p.s: `custom-select` is set through the `className` prop.

**Comment by kohheepeace** [comment]
This is my solution

```js
const customStyles: StylesConfig = {
  input: (provided, state) => ({
    ...provided,
    "input:focus": {
      boxShadow: "none",
    },
  }),
};

...

<CreatableSelect
 ...
  styles={customStyles}
/>
```

**Comment by vamsikrishnareddybevara** [comment]
I am facing the same issue. I tried the above solutions. It removed the outline but the width of the input remains the same.

![image](https://user-images.githubusercontent.com/38369869/173523168-ca9101d6-b0d4-452b-aa44-19c778a926a1.png)

Did anyone face a similar issue?

**Comment by Kaceykaso** [comment]
I am still seeing this floating, disconnected select option set in the upper left of the UI. I am not using tailwindcss/forms, and basic HTML elements. The above "solutions" have not worked. I am on the latest.
