### ISSUE TITLE
Select not closing when using components.ValueContainer

### ISSUE THREAD

**Issue by manisha-seclogic** [JedWatson/react-select#4687]
I am using components.ValueContainer. After selecting multiple options, when I click outside somewhere else, dropdown doesn't get closed.

When no options are selected, it works perfectly fine

**Comment by ebonow** [comment]
@manisha-seclogic Would you kindly provide a code sample? There are several examples of this covered and closed, but wanted to confirm your use-case before making assumptions.

**Comment by sibiraj-sr** [comment]
@ebonow We are facing the same issue as well.

See https://codesandbox.io/s/bold-mountain-g5n0j?file=/src/index.tsx

**Comment by ebonow** [comment]
@sibiraj-sr apologies for the late reply on this. 

The issue with your implementation is that you are replacing the ValueContainer without an Input. The Input component is used to give focus to and ultimately to also close the menu automatically when it loses focus (assuming it is not controlled with the `isMenuOpen` prop. By removing the Input component as a child to the ValueContainer, it effectively breaks this contract.

Perhaps you would have better results by instead overwriting the `SingleValue` or in this case `MultiValue`

```jsx
// MultiValue is wrapper for each selected value. 
//- Here we only want to display a single string so we overwrite any first selected value with "Random Content" 
//   and return null for the other values to prevent rendering their value.

const MultiValue = ({ index }) => (index === 0) ? `Random Content` : null;

const App = props => (
  <Select components = {{ MultiValue }} {...otherProps} />
)
```

Please let me know if this helps, and if so we can close this ticket.

**Comment by sibiraj-sr** [comment]
Thanks @ebonow. That works. https://codesandbox.io/s/bold-khayyam-qj3q3
