### ISSUE TITLE
[BUG] “Create” option isn't visible in AsyncCreatableSelect When setting keys/values with getOptionLable & getOptionValue

### ISSUE THREAD

**Issue by rohitcoder** [JedWatson/react-select#4692]
I was working on implementing AsyncCreatableSelect and everything was working properly but somehow I noticed a blank record was appearing in all populated lists, and after debugging I noticed it's not a blank list, it's an invisible "Create " option which we get at bottom of the Dropdown list.

![Screenshot 2021-07-15 at 10 58 11 PM](https://user-images.githubusercontent.com/17665703/125833327-814dd858-7cf2-470c-abc6-b5b539797315.png)

Expected Behaviour (Creat option should be visible) check the below example.

![Screenshot 2021-07-15 at 11 11 03 PM](https://user-images.githubusercontent.com/17665703/125833390-23225ba8-cb71-4950-93f7-00632646398e.png)

I am sharing my component and Parent component.

**Child Component**

```
import makeAnimated from "react-select/animated"; 
import AsyncCreatableSelect from 'react-select/async-creatable';
const AsyncCreatableSelectBar = ({ setValue, loadOptions, placeholder, onInputChange, isLoading }) => {
  const animatedComponents = makeAnimated();
  return (
    <>
      <AsyncCreatableSelect
        cacheOptions
        isMulti
        components={ animatedComponents }
        getOptionLabel={(e) => e.name }
        getOptionValue={(e) => e.name } 
        loadOptions={ loadOptions ? loadOptions : () => null } 
        placeholder={ placeholder }
        onInputChange = { onInputChange }
        isLoading = { isLoading } 
        onChange={(value) => setValue(value)}  
      />
    </>
  );
};

export default AsyncCreatableSelectBar;
```
**Parent Component (Where I am implementing this)**
```
function fn() {
    const [state, setState] = useState({
        AsyncSearchValue: [],
        AsyncSearchQuery: ""
    });

    const [getUniversities, { loading, client, data }] = useMutation(getUniversitiesMutation);

    const loadOptions = async (val) => {
        return getUniversities({
            variables: {
                "query": val
            }
        }).then((res) => res.data.getUniversities.data)
    };
    return ( 
      <div>
        <AsyncCreatableSelectBar setValue = {
            (val) => setState({
                ...state,
                AsyncSearchValue: val
            })
        }
        loadOptions = {
            debounce(loadOptions, 1000)
        }
        placeholder = "Start typing your skills...."
        onInputChange = {
            (value) => setState({
                ...state,
                AsyncSearchQuery: value
            })
        }
        className = "col-12" />
        </div>
    }
    export default fn;
```

**Comment by rohitcoder** [comment]
Just noticed this, this works when we don't use 

 ```
 getOptionLabel={(e) => e.name }
 getOptionValue={(e) => e.name } 
```

**Comment by Rall3n** [comment]
Hello @rohitcoder,

the `Create ...` option is just that, another option in the list with the default schema (`{ label, option, __isNew__ }`).
It would have to have the same properties as you access in both accessor functions.

There are two ways you could handle this:
1. You check for the `__isNew__` prop on the option to handle the `Create ...` option seperately.
    ```jsx
    <Select
        getOptionLabel={option => option.__isNew__ ? option.label : option.name}
        getOptionValue={option => option.__isNew__ ? option.value : option.name}
    />
    ```
2. You use the `getNewOptionData` prop to customize the `Create ...` option.
    ```jsx
    <Select
        getNewOptionData={(inputValue, optionLabel) => ({ name: inputValue })}
    />
    ```
    `inputValue` is the value entered in the search input, `optionLabel` is the formatted label after using `formatCreateLabel`.
    
I would suggest you use a combination of both so you can keep the formated option label.

**Comment by rohitcoder** [comment]
Thanks @Rall3n 

1st method worked! I was stuck here since tomorrow just because of debugging this 😂.

Many many thanks for this solution :)
