### ISSUE TITLE
How to wait for user type ends and clear all previous pending loadOptions request?

### ISSUE THREAD

**Issue by rohitcoder** [JedWatson/react-select#4694]
I am trying to implement `<AsyncCreatableSelect />` Everything working fine, but the issue is with a lot of requests being sent in the background when the user starts typing. I want to send these  requests only after 500ms user typing ends, I tried implementing https://www.npmjs.com/package/debounce-promise like this

```
<AsyncCreatableSelect
loadOptions = { debounce(loadOptions, 500) } 
/>
```

But this code waits for 500 ms after the user stops typing and then sends a lot of requests just after that 500 ms in one shot.

Any idea or recommendations, how i can solve this?

This is my loadOptions

```
 const loadOptions = async (val) => { 
    return getSkills({ variables: { "query": val }}).then((res) => res.data.getSkills.data)
  }; 
```

**Comment by shulcsm** [comment]
You probably want to memo that debounce, now you are creating a new one on each render

**Comment by rohitcoder** [comment]
@shulcsm 

Many many thanks for your suggestion, I am totally new to React and I have only a little idea about `useMemo` and just with a little bit of google, I was able to make it work! 

Thanks for your help :)
