### ISSUE TITLE
types too strict OptionBaseType v5

### ISSUE THREAD

**Issue by shulcsm** [JedWatson/react-select#4696]
```tsx
interface Entity {
  id: number;
  name: string;
}

const s = <Select<Entity> getOptionValue={(e) => e.id.toString()} getOptionLabel={(e) => e.name} />;

>>> Type 'Entity' has no properties in common with type 'OptionBase'
```

This used to work with v3/4 https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/types.d.ts#L4
but i'm not sure that is correct.

This does work but is not very ergonomic and causes different issues:
```tsx
interface Entity extends OptionBase {
  id: number;
  name: string;
}
```

**Comment by Methuselah96** [comment]
Thanks for the issue. That's definitely a fair criticism, let me think about the best solution.
