### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by srconklin** [JedWatson/react-select#47]
I looked through the set of open issues but did not not see an open one concerning the error that I receiving.. sorry if this is has been asked before.. 

I installed the package via NPM and when I require it in my module. 
var Select = require('react-select');
i get  "Cannot find module "react-select" MODULE NOT FOUND"

I am using webpack.

Any advice?

**Comment by JedWatson** [comment]
There have been some issues with web pack, I am currently working on a different build process that should be friendlier to both Browserify and Webpack (see #40)

That said there's no issue I know of that would cause this... maybe someone else has seen it?

**Comment by srconklin** [comment]
sorry- 
i misread the stack trace.. the issue was indeed this one:
https://github.com/JedWatson/react-select/issues/26
and the workaround proposed by @julen solved the issue for me:

 { test : /\.js$/,
              include: path.join(__dirname, 'node_modules', 'react-select'),
              loaders: ['jsx']
             }, // special case for react select
