### ISSUE TITLE
Clicking an option after searching doesn't always close dropdown

### ISSUE THREAD

**Issue by abraham-chan** [JedWatson/react-select#470]
On the [demo page](http://jedwatson.github.io/react-select/) on the States dropdown, search for "e". 
Click "New South Wales" and the dropdown closes as expected.
Click "Queensland" and the dropdown stays open.

**Comment by wmf23** [comment]
Yes, I see the same issue. I want to create a new items if it's not already in the list of options. If I click 'Add "my new item"?' then the dropdown does not close and shows the original options. However, if I press enter to create my new option then the dropdown goes away (as I would expect).

e.g. on the [demo page] (http://jedwatson.github.io/react-select/) if you go the 'Custom render options/values' select and type in 'a' and then click on 'Add "a"?', you see that the dropdown shows up.

**Comment by VadimMustyatsa** [comment]
We faced the same issue after implementing this control in our solution. On the demo page it reproduces too:
- For 1 charater: 3rd+ item (searh for "e", click "Queensland"+)
- For 2 characters: 2nd+ item (search for "li", click "Western Australia"+)
- For 3 characters: 2nd+ item (search for "lia", click "Western Australia"+)

**Comment by RichardD012** [comment]
This seems to be a timing issue.  If you pause in the chrome dev tools, and wait a few seconds, regardless of the option you pick, the menu stays open.

**Comment by romanonthego** [comment]
+1
we have the same problem

**Comment by romanonthego** [comment]
Please note that menu reopens only when:
1) where is no value to begin with (if where is preselected value - everything is fine, you need to clear value to reproduce this issue)
2) only on mouse click (tab+enter works well)
oh, and it's in case of async functionality used.

**Comment by abraham-chan** [comment]
Appears to be fixed?
@JedWatson was this resolved in https://github.com/JedWatson/react-select/commit/768486963cf99c3556bcec582fda00ffcfb1c966 ?

**Comment by wmf23** [comment]
Yes, seems to be fixed.

**Comment by JedWatson** [comment]
Thanks for picking that up @abraham-chan and @wmf23!
