### ISSUE TITLE
Sometimes styles aren't applied, reloading fixes it

### ISSUE THREAD

**Issue by hailwood** [JedWatson/react-select#4700]
So we have this strange issue happening, Sometimes the styles aren't getting applied to react-select.
A reload fixes it, and it only seems to be every 1/100 times that it's happening.

Currently using 5.0.0-beta.0 but it's been an issue in 4.2+ (didn't use it previously).

It ends up looking like this - 
![image](https://user-images.githubusercontent.com/709773/126420425-5cbc8558-b9ef-4979-8321-49574a218bd5.png)

We have a custom style object that looks like this, applied through the style prop. Aside from that everything is stock standard.

```js
export const styles = {
  container: (provided, state) => ({}),
  control: (provided, state) => ({
    ...provided,
    borderRadius: 5,
    paddingLeft: 10,
    minHeight: theme.height['10.5'],
    ...(state.isFocused ? {
      backgroundColor: 'white',
      '--tw-border-opacity': 1,
      borderColor: 'rgba(38, 198, 218, var(--tw-border-opacity))',
      'outline': '2px solid transparent',
      outlineOffset: '2px',
      '--tw-ring-offset-shadow': 'var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color)',
      '--tw-ring-shadow': 'var(--tw-ring-inset) 0 0 0 calc(4px + var(--tw-ring-offset-width)) var(--tw-ring-color)',
      boxShadow: 'var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000)',
      '--tw-ring-color': 'rgba(38, 198, 218, var(--tw-ring-opacity))',
      '--tw-ring-opacity': 0.2,
      '&:hover': {
        borderColor: 'rgba(38, 198, 218, var(--tw-border-opacity))',
      },
    } : {
      boxShadow: theme.boxShadow.input,
      backgroundColor: theme.colors.gray[100],
      borderColor: theme.colors.gray[600],
      '&:hover': {
        borderColor: theme.colors.gray[600],
      },
    }),
  }),
  input: (provided, state) => ({
    ...provided,
    color: theme.colors.blackish,
    fontSize: theme.fontSize['sm'][0],
    'input:focus': {
      boxShadow: 'none',
    },
  }),
  placeholder: (provided, state) => ({
    ...provided,
    color: theme.colors.gray[800],
    fontSize: theme.fontSize['sm'][0],
  }),
  singleValue: (provided, state) => ({
    ...provided,
    color: theme.colors.blackish,
    fontSize: theme.fontSize['sm'][0],
  }),
  indicatorSeparator: (provided, state) => ({
    ...provided,
    backgroundColor: theme.colors.transparent,
  }),
  dropdownIndicator: (provided, state) => ({
    ...provided,
    color: theme.colors.blackish,
  }),
  indicatorsContainer: (provided, state) => ({
    ...provided,
    color: theme.colors.blackish,
  }),
  menu: (provided, state) => ({
    ...provided,
    borderRadius: 5,
    color: theme.colors.blackish,
    fontSize: theme.fontSize['sm'][0],
    backgroundColor: 'white',
    marginTop: 0,
    marginBottom: 0,
  }),
  menuPortal: provided => ({
    ...provided,
    zIndex: 9999
  })
};
```

**Comment by Tina-Dumilina** [comment]
Hi!
We have encountered the same problem today. How have you fixed it?

**Comment by hailwood** [comment]
Hi @Tina-Dumilina,

I believe the issue is that we also use react-google-places-autocomplete which includes an older version of react-select as a dependency rather than a peer dependency causing the older version to be compiled in along with it's dependencies which includes styled-components. My theory is that this is a conflict between the two version of styled-components.

I haven't had a chance to test the theory as it's frustratingly intermittent (so likely a timing issue), but I closed the issue as I believe it's not related to react-select directly.

I'll update here once I've managed to test (which may not be for a couple of weeks) but would love it if you could add in here whether you use anything that might include a different version of styled-components also as that will help narrow it down.
