### ISSUE TITLE
Change default `Select...` text

### ISSUE THREAD

**Issue by goxr3plus** [JedWatson/react-select#4707]
Hello i can't find a way to change the default `Select...` because our ui is for multiple languages and we have a problem with that when no option is selected (There might be cases that no options are available at all for the dropdown).

![image](https://user-images.githubusercontent.com/20374208/128006030-8aba5deb-9879-4d5a-97c2-a72f7abd1c13.png)

For example instead of example i want to put another text like ( `Wählen Sie` ) 

Is it possible with `React Select 4.3.1 `

**Comment by BATCOH** [comment]
```javascript
<Select noOptionsMessage={() => "Wählen Sie"} {...otherProps} />
```
https://react-select.com/props#select-props

**Comment by goxr3plus** [comment]
@BATCOH 

Still it just changes the message on the pop up 

![image](https://user-images.githubusercontent.com/20374208/128014371-8546b4f7-79a4-4021-94bc-b0f2be0a1d42.png)

**Comment by BATCOH** [comment]
Oh, sorry. Wrong option.
```javascript
<Select placeholder="Wählen Sie" {...otherProps} />
```

**Comment by goxr3plus** [comment]
My issue was solved thank you a lot :)

**Comment by henok8515** [comment]
thanks a lot man
