### ISSUE TITLE
Weird typings for onChange badly needs a refactor.

### ISSUE THREAD

**Issue by Johnrobmiller** [JedWatson/react-select#4715]
These types are silly:
```
const [ selectedValues, setSelectedValues ] = useState<OptionsType<OptionType>>([])

const handleChange = (values: OptionsType<OptionType>, actionMeta: ActionMeta<OptionType>) => {
  // do something
}
```
Not only are these types unintuitive in of themselves, but they are also not well explained neither in the docs nor elsewhere online.  Problem solving these types has costed me a huge amount of time.  As much as I would love to replace these types with "any", I'm working with a strict linter that doesn't allow such things.  I seriously look forward to the day when I can just dip in-and-out of a visual editor like Webflow to do UI, but since visual editors don't yet integrate with complex code bases, I'm stuck dealing with silly types likes these.

Please consider making it a priority to both refactor these ugly types and to update the docs to make it easier to apply them.

**Comment by Methuselah96** [comment]
How would you suggest we refactor the types? Feel free to suggest better types and/or open a PR with the changes.

**Comment by hackedhead** [comment]
I'm also struggling with `OptionType` and friends being used as the values passed around by this element.

With a generic `<select>` in HTML, the DOM element's `value` when an option is selected is the value of that option.

`document.getElementById("mySelect").value` yields, for example, `banana` (corresponding to `<option value="banana">Banana</option>`)

with react-select, the same DOM query would yield an `<OptionType>` that looks like `{label:"Banana", value: "banana"}` which is ... frustrating.

**Comment by Methuselah96** [comment]
I don't think we store the option object anywhere in the DOM. Here's what the DOM looks like for our basic single select on our website. The only `value` attribute is the `input`, which correctly shows `option.value`. Can you create a CodeSandbox where a DOM query would yield an `<OptionType>`?

![image](https://user-images.githubusercontent.com/693755/130462853-a6745701-ed03-4f4b-8d49-3e05fbbd97be.png)

**Comment by steve-taylor** [comment]
> I'm also struggling with `OptionType` and friends being used as the values passed around by this element.

Agreed. Anything other than the `value`, which is just a `string`, is redundant.

```ts
const [ selectedValues, setSelectedValues ] = useState<OptionsType<OptionType>>([])

const handleChange = (values: OptionsType<OptionType>, actionMeta: ActionMeta<OptionType>) => {
  // do something
}
```

Yes, it's a bit too strict. You can replace `OptionsType` with `ReadonlyArray` if that improves readability.

**Comment by ebonow** [comment]
This was a complete refactoring of Flow to TypeScript. We are happy to consider any updates to the types, but these conversations would likely be a better fit for the Discussions area as would any topic regarding a change from value representing a `String` or `Number` instead of an `Object`.

Again this rewrite was based on the intention of creating compatible code. The next major version would likely be a bit more opinionated with breaking changes (like the one mentioned above abut changing the type of the value), so it's one that we would happily address if it were a popular topic in the Discussions area and made sense to do so.
