### ISSUE TITLE
Empty Label but number of Options rendered correctly

### ISSUE THREAD

**Issue by sikandarchishty** [JedWatson/react-select#4716]
Hi,
When I pass the data from my state in options, the number of options (occurrences) are rendered correctly but I cannot see the label name. 

Do the values in state (data array) need to match a certain pattern for react-select to render options with labels or something else is going on?

The items are created dynamically, please see this [Sandbox](https://codesandbox.io/s/react-select-fx2bo?file=/src/ReactSelect.js)
 
Thanks in advance.

**Comment by Rall3n** [comment]
Hello @sikandarchishty,

the component can't know how your options are structured. By default it expects the options in the form of `{ label, value }`.

**But** you can adjust the behaviour by using the `getOptionLabel` and `getOptionValue` props.

```jsx
<Select
  {/* ... */}
  getOptionLabel={option => option.userAnswer}
  getOptionValue={option => option.id}
/>
```

**Comment by sikandarchishty** [comment]
Thank you, that fixed it.
