### ISSUE TITLE
Manually Triggering / Simulating MouseDownEvent on React-Select Components

### ISSUE THREAD

**Issue by akhileshThapliyal** [JedWatson/react-select#4732]
Hi Team,

I am recently creating test cases for one of my Web Applications which is built on RactJS. Some of the application forms heavily use react-select. I am writing test cases using selenium.

When I use selenium functions to trigger focus or click or mouse down events on the react select nothing happens. In addition to this If I try to leverage the browser console (using inspect) that also does not work.

I tried using various methodology stated in the below links but was not successful.

https://stackoverflow.com/questions/40091000/simulate-click-event-on-react-element
https://stackoverflow.com/questions/20567748/how-to-trigger-a-onmousedown-event-manually-from-javascript-not-jquery-on-a-em

Could you please help me understand how can I manually trigger events on the react-select dropdowns using Javascript outside of the ReactJS environment? Appreciate your prompt help and support.

Please refer to the attached ScreenFlow

https://user-images.githubusercontent.com/7280745/129943860-61543f13-cbf9-435e-9575-7062c2b601db.mp4

![Screen-Recording-2021-08-19-at-1](https://user-images.githubusercontent.com/7280745/129945243-24a4fd86-3652-4e46-b000-04d05cd0c3d9.gif)

**Comment by akhileshThapliyal** [comment]
@JedWatson, May I please request your advice. Thank You :)

**Comment by Amedeo91** [comment]
Hello @akhileshThapliyal, did you find a way to make it work? I am currently stuck in my selenium test!

@JedWatson any suggestion on how to do it? I see many many tickets with a similar issue with selenium. Any clue why?

**Comment by mellis481** [comment]
@JedWatson Can you speak to this issue please? It's quite problematic.

**Comment by mellis481** [comment]
> The element with the class suffix `container` is the wrong element to trigger events on. It is just a wrapper without any listeners attached. Instead target the element with the suffix `control`. This element does not listen to an `click` event, but instead uses the `mousedown` event. Afaik this is to reuse the same event code for touch events.

@Rall3n THANK YOU! Targeting the element with the `control` suffix and dispatching a `mousedown` event (rather than a `click` event) worked for me.  There is a slight delay (maybe 500ms), but that is not an issue for me.

AFAIC, this issue should be closed.

**Comment by Rall3n** [comment]
@mellis481 Thank you for your confirmation. Closing.

**Comment by darren4ten** [comment]
> `mousedown`

How do you make it work?
I usw this piece of code but not work at all.
`
 $(".css-yk16xz-control")[0].dispatchEvent(
    new MouseEvent("mousedown", {
      button: 0,
      bubbles: true, // this is key, otherwise it wont work
    })
  ); //
`

**Comment by LorenzHW** [comment]
> How do you make it work?
I usw this piece of code but not work at all.
$(".css-yk16xz-control")[0].dispatchEvent( new MouseEvent("mousedown", { button: 0, bubbles: true, // this is key, otherwise it wont work }) ); //

Using the dropdown indicator works for me: https://github.com/JedWatson/react-select/issues/856#issuecomment-1301858426
