### ISSUE TITLE
Latest version of typings is missing the option value in the second arg for onChange handler

### ISSUE THREAD

**Issue by arackaf** [JedWatson/react-select#4739]
### Thanks for using react-select!

Before creating an issue...

# Are you asking a question?

No

# Are you reporting a bug or runtime error?

No

# Are you making a feature request?

No

I hope this is the right place - apologies if not. I'm reporting a bug in the TypeScript typings. For the onChange handler, the second argument, of type `ActionMeta<T>` no longer has the optional `option` property, which, if I understand correctly, is only used in multi mode (which is why I assume it was optional).

With the latest version of the typings, this optional prop is now gone, and so you get a TypeScript error when accessing it, even on a Select instance that's multi.

**Comment by Methuselah96** [comment]
1. Are you on v4 or v5 beta?
2. If you're pass a custom `onChange` handler, there shouldn't be an TypeScript error if you don't provide the `option` property. In what way are you accessing the optional prop? It would be great if you could provide a CodeSandbox or TypeScript playground.

**Comment by arackaf** [comment]
Sorry, I'm on 4.3.1.  When I upgrade the types to `"@types/react-select": "^4.0.17",` then my change handler:

```js
function handleChange(_: any, action: ActionMeta<Genre>) {
  if (!action.option) return;
  props.onGenreSelect(action.option);
}
```

errors with 

```js
Property 'option' does not exist on type 'ActionMeta<Genre>'.
  Property 'option' does not exist on type 'CreateOptionActionMeta'.ts(2339)
```

**Comment by Methuselah96** [comment]
That's because `ActionMeta` will not always have an `option` property ([here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/types.d.ts#L65-L106) is the full list of possibilities).

I would suggest changing your code to be:
```
function handleChange(_: any, action: ActionMeta<Genre>) {
  if (action.action === 'select-option') {
    props.onGenreSelect(action.option);
  }
}
```

**Comment by Methuselah96** [comment]
That's because `ActionMeta` will not always have an `option` property ([here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/types.d.ts#L65-L106) is the full list of possibilities).

If you only want to update when an options is explicitly selected I would suggest changing your code to be:
```
function handleChange(_: any, action: ActionMeta<Genre>) {
  if (action.action === 'select-option') {
    props.onGenreSelect(action.option);
  }
}
```

However my guess is that you also want to handle the other possible actions as well (clearing, deselecting, etc.) in which case you probably want:
```
function handleChange(value: Genre | null) {
  props.onGenreSelect(value);
}
```

**Comment by arackaf** [comment]
@Methuselah96 ohhhhh - it's a discriminated union. I'm SO sorry for wasting your time. And no, this is a multi-select, so the first argument is not what I need here. Your first code sample is, I think, exactly what I need, but I'll of course verify.
