### ISSUE TITLE
Feature Request: merge styles with provided by default

### ISSUE THREAD

**Issue by brandonchinn178** [JedWatson/react-select#4743]
# My use case

I'm adding a multiselect field to a form, that's basically intended to be a nicer version of a `<textarea>` with comma separated values. As such, I want the cursor to still show the `text` cursor when hovering over the input, but not over the `multiValue` elements. Specifically, I have the following:
```ts
styles={{
  valueContainer: (provided: object) => ({
    ...provided,
    cursor: 'text',
  }),
  multiValueLabel: (provided: object) => ({
    ...provided,
    cursor: 'default',
  }),
  multiValueRemove: (provided: object) => ({
    ...provided,
    cursor: 'pointer',
  }),
}}
```
I find it rather annoying to have to repeat `...provided` every time; in fact, I can't personally think of an instance where I would want to throw away `provided` entirely and start completely from scratch. Most if not all of the time, I want to add styles on top of `react-select`'s built-in styles.

# Proposal

1. By default, merge styles with `provided`. `() => ({ foo: bar })` should be equivalent to `(provided) => ({ ...provided, foo: bar })`
2. If a special `override` key is set to `true`, don't merge. `() => ({ override: true, foo: bar })` is equivalent to today's `() => ({ foo: bar })`
3. As a shorthand, a plain object may be specified. `valueContainer: { foo: bar }` should be equivalent to `valueContainer: () => ({ foo: bar })` which merges `{ foo: bar }` with provided, per (1)

**Comment by ebonow** [comment]
Greetings @brandonchinn178 ,

I had some concerns about making this part of the common library. 

I would agree that in most use-cases, the provided properties are spread into the style, but unfortunately this isn't always the case. The are times users may simply want to remove some css property and default to something either in their stylesheet or browser default. While there are `unset`, `initial`, `inherit`, etc... I think these add more complexity.

Additionally, there have been other requests to disable all injected styles. The resolution to this was using a `Proxy` to return an empty object. https://github.com/JedWatson/react-select/issues/2872#issuecomment-654251799

Your proposal would likely be a shortcut for most users, but it would ultimately remove this flexibility required for some.

The other critical thing here is that this change would likely require its own major release as it would break every user of the library using the styling api as the first variable would no longer be the provided props, but instead the `state` object.

For these reasons, I would be opposed to making this change at this time. That said, the team has discussed some preliminary thoughts about providing alternative means of styling that could remove the dependency on Emotion. We are still very much in preliminary discussion about what that would look like, specifically with getting 5.0 and its documentation working properly.

**Comment by ebonow** [comment]
@brandonchinn178 I had originally left a comment here, but looked more at the PR and will instead move the conversation there.

**Comment by brandonchinn178** [comment]
Makes sense. Thanks for following up!

Just to be clear, that's not a React hook or hooking into any React-Select stuff, it's just a function to use like
```
<Select styles={useMerged(styles)} ... />
```
right?

**Comment by ebonow** [comment]
I guess technically it's not a hook since it's not stateful so it is just a function that achieves the same functionality.
