### ISSUE TITLE
CreatableSelect hasn't menuPortalTarget

### ISSUE THREAD

**Issue by gormonn** [JedWatson/react-select#4747]
CreatableSelect hasn't menuPortalTarget...

**Comment by Rall3n** [comment]
Hello @gormonn,

unfortunately I cannot confirm what you are claiming. The prop `menuPortalTarget` is working as expected on the latest version of the library.

Could you provide more information (e.g. the version you are using, an usage example)?

**Comment by gormonn** [comment]
It's was my mistake, sorry.
