### ISSUE TITLE
defaultMenuIsOpen doesn't work with menuPortalTarget

### ISSUE THREAD

**Issue by mthorning** [JedWatson/react-select#4749]
Hi, we're using v4.3.1 and wish to load the select with the menu open. We're using the component like this:
```
<ReactSelect defaultMenuIsOpen menuPortalTarget={document.body} />
```
The component doesn't render with the menu open. It does work if I remove the `menuPortalTarget` prop. 
I've had a look at the source code and it looks like there's a race condition with the `MenuPortal` component and the `controlRef`. I'll create a PR for you to take a look at.

Thanks :)

**Comment by mthorning** [comment]
PR is [here](https://github.com/JedWatson/react-select/pull/4750), apologies for not having created it on the right branch so that it would link automatically.

**Comment by Rall3n** [comment]
Hello @mthorning,

could you please check if the issue still occurs with the latest beta release ([react-select@5.0.0-beta.1](https://github.com/JedWatson/react-select/releases/tag/react-select%405.0.0-beta.1))?

**Comment by mthorning** [comment]
Hi @Rall3n, the same issue exists in 5.0.0-beta.1.
