### ISSUE TITLE
Incorrect typing in onChange handler

### ISSUE THREAD

**Issue by hmnd** [JedWatson/react-select#4751]
## Details 
Version: v5.0.0-beta.1
Reproduction: https://codesandbox.io/s/react-select-v3-sandbox-forked-99kmd?file=/src/example.tsx

## Issue
When options are grouped, the typing of newValue in `onChange` (and possibly other handlers) seems to be incorrect. It uses the groups' full type, instead of extracting the type of the groups' options.

**Comment by Methuselah96** [comment]
I think you'll have to specify the `Option` generic type for it to figure out that you're providing groups.
Here's to do it: https://codesandbox.io/s/react-select-v3-sandbox-forked-pfst5?file=/src/example.tsx

Does that help?

**Comment by hmnd** [comment]
@Methuselah96 Ah, yup that fixed it. Thanks for the really quick response!
