### ISSUE TITLE
Random text displaying on the inputbox

### ISSUE THREAD

**Issue by vishalmarneni** [JedWatson/react-select#4759]
Randon text displaying on the input box and this is happening on the apple systems only 
, Below is the screenshot 

![image](https://user-images.githubusercontent.com/79602980/132509602-d0effed7-2273-4bfe-ab15-8170b3e70288.png)

Below is the code snippet i used 
`                <Typeahead
                  openMenuOnFocus
                  autoFocus
                  ref={selectElementRef}
                  id="prescription-name"
                  styles={colourStyles}
                  className="react--select-overide"
                  menuPosition="fixed"
                  value={drugName}
                  isClearable
                  aria-relevant="additions text"
                  aria-atomic="true"
                  loadOptions={fetchOptions}
                  onChange={handleOnPrescriptionSelect}
                  formatOptionLabel={formatOptionLabel}
                  components={{
                    Menu,
                    DropdownIndicator: () => null,
                    IndicatorSeparator: () => null,
                  }}
                  placeholder={"Start typing prescription name"}
                  noOptionsMessage={() => (
                    <div className="no-search-data">
                      <span>
                        {searchString
                          ? "Prescription not found, try a different search"
                          : "Start typing prescription name"}
                      </span>
                    </div>
                  )}
                  menuIsOpen={!drugName}
                />`

**Comment by ebonow** [comment]
Greetings @vishalmarneni this is usually a side effect of when the styling is not being properly applied. 

The text displayed is used by assistive technologies to aide in usability. It should be hidden from view, but it would seem that this is not the case for you and it's unclear what kind of styling is being done.

My first question would be a to understand what the className `react--select-overide` does and if there are any other styles being applied or overridden.

**Comment by ebonow** [comment]
Closing this issue as it has been open nearly a month now with no response. It is also a duplicate of the one posted here: https://github.com/JedWatson/react-select/issues/4792
