### ISSUE TITLE
Add `isLoading` prop

### ISSUE THREAD

**Issue by rileyjshaw** [JedWatson/react-select#476]
I'm working on a project that async loads options for react-select. The async behavior is complex and needs to start **before** react-select is rendered, so using the built-in `asyncOptions` functionality doesn't really work for me.

I'd love to be able use the `searchingText` and `isLoading` indicator, and the best way I can think of is to pass down an `isLoading` prop. Since this could override the built-in `asyncOptions` behavior, maybe `forceIsLoading` would be a better prop name? Not sure.

I'm happy to submit a PR, but since this is a new feature I thought a discussion was in order. So... Let the discussion begin!

**Comment by jgautsch** [comment]
:+1: for `isLoading` prop, or something else that covers this use case

**Comment by JedWatson** [comment]
Closed by #482
