### ISSUE TITLE
React select dropdown menu z-index

### ISSUE THREAD

**Issue by newilu** [JedWatson/react-select#4760]
![download](https://user-images.githubusercontent.com/78621873/132626100-cd45157f-d5c7-4136-909c-654585b599ff.png)
Wth this issue is like 4 y.o. and still not resolved? None of the solutions i found worked (all z-indexes on parents more than 1000, z-index of select, select-menu, etc is 9999+)
On screen you can see an issue BUT THE BUTTON HAS Z-INDEX OF -1!!! Does select have  a negative 1000000 z-index?

**Comment by Rall3n** [comment]
Hello @newilu,

could you provide a minimal reproducible example using [this CodeSandbox](https://codesandbox.io/s/react-select-v4-sandbox-rxvsh?file=/example.js) as a base?

**Comment by newilu** [comment]
theme prop makes z-index -1000000000000 or something idk, just need to remove theme prop
