### ISSUE TITLE
Menu doesn't open on click when using custom Control component

### ISSUE THREAD

**Issue by haddigan** [JedWatson/react-select#4773]
It looks like I lose the ability to open up the select dropdown by clicking on the ValueContainer when I use a custom Control component:

https://codesandbox.io/s/react-select-v3-sandbox-forked-fwh1y?file=/example.js

The only way the dropdown will open when I'm using a custom Control is by clicking the Indicator or by using keyboard actions. Using a custom Indicator doesn't seem to cause any issues

**Comment by Rall3n** [comment]
Hello @haddigan,

one could assume that `props` can just be spread onto the DOM element, but one should not do so. `props` can contain more than DOM compatible properties.

Part of the `props` for the `Control` component is the `innerProps` object. This contains properties meant for the underlying DOM element (e.g. event handlers). You should also forward the props `innerRef` (required for internal functionality) and `children` (the children of the component).

```jsx
const CustomControl = ({ innerProps, innerRef, children, ...props }) => (
  <div {...innerProps} ref={innerRef}>{children}</div>
);
```

**Comment by ebonow** [comment]
@haddigan let us know if the proposed solution works for you. If not, we can re-open this ticket or discuss further.

**Comment by gsambrotta** [comment]
I had the same problem and this fix helped me to solve the issue. 
Seems that the important bit to make it work is the `children` prop. 
This is a bit annoying because in my case I want to display just an icon, instead of the text. But with some tweaks I made it work.
