### ISSUE TITLE
Is beta release of TypeScript version coming soon?

### ISSUE THREAD

**Issue by michaltaberski** [JedWatson/react-select#4787]
Hi, I have a short question.
I can see on master the code has been updated to TS already. That's awesome! However the last version has no TS yet and I would like to ask you for an alpha or beta (if ready) release current master to be able to use the TS notations.

Thanks M.

**Comment by Rall3n** [comment]
Hello @michaltaberski,

a v5 beta version including TypeScript has already been published on [this repository](https://github.com/JedWatson/react-select/releases/tag/react-select%405.0.0-beta.1) and on [npm](https://www.npmjs.com/package/react-select/v/beta). You can install it using:
```bash
npm install react-select@beta
```

**Comment by michaltaberski** [comment]
Perfect @Rall3n ! I was confused by this section here:
<img width="1291" alt="JedWatson:react-select: The Select Component for React js 2021-09-18 11-58-38" src="https://user-images.githubusercontent.com/202033/133885017-e4dc9801-df41-4a07-8b35-b0ba2e949047.png">

**Comment by Rall3n** [comment]
@michaltaberski I can understand the confusion. GitHub by default only shows the latest stable release.
