### ISSUE TITLE
Select won't open when menu covers the control

### ISSUE THREAD

**Issue by bezreyhan** [JedWatson/react-select#479]
This is how a select normally looks:
![select_50px](https://cloud.githubusercontent.com/assets/6013763/10081346/52c2ad36-62a9-11e5-9f57-85539f6956a8.png)

However, if I change the css of  `Select-menu-outer` to have a `top: 0px` then the select will no longer open. This is the design I want to create - when the menu is open it should cover the control:

![select_0px](https://cloud.githubusercontent.com/assets/6013763/10081433/be9d3ad0-62a9-11e5-8344-750d33c57af7.png)

The menu will flicker open for a split second and close right after. 

I have suggested a fix in this PR: https://github.com/JedWatson/react-select/pull/467

**Comment by c-moss-talk** [comment]
@bezreyhan looks like your PR didn't get merged but maybe it was solved with 1.0.0 -- can we close this?

**Comment by bezreyhan** [comment]
Yes
