### ISSUE TITLE
Confusing upgrade documentation

### ISSUE THREAD

**Issue by developerdizzle** [JedWatson/react-select#4791]
I'm in the process of upgrading from `v3.1.0` to the latest version and reviewing your upgrade documentation.  The most obvious documentation I see is the "Upgrading" link on the homepage navigation, linking to https://react-select.com/upgrade-guide which mostly talks about `v2`, with no mention of `v3` or the latest `v4`.

Also, as of writing, `v4.3.1` is the latest version, but there's a link in `README.md` that says:
> v3, v4, and v5 upgrade guide

`v5` doesn't exist yet, right?  But upgrading to `v4` is relevant to my scenario so I click on it.  Turns out that [page doesn't exist](https://react-select.com/upgrade) and I'm dumped into the homepage.  Doh!

Hopefully with `v5`s release these documents and links can be fixed, but it's not a great experience right now.

**Comment by Methuselah96** [comment]
Sorry about that, we merged the v5 upgrade documentation into the main branch last week with the intention of releasing 5.0 that same day but we hit a hiccup and decided to delay the release of 5.0 by a week. Everything should make a lot more sense once 5.0 is released, but for now the release notes for [v4](https://github.com/JedWatson/react-select/releases/tag/react-select%404.0.0) and [v3](https://github.com/JedWatson/react-select/releases/tag/react-select%403.0.3) are where the upgrade documentation can be found.

Apologies for the poor experience, hopefully this should be resolved this week.

**Comment by developerdizzle** [comment]
No worries!  I didn't realize there was a hiccup with v5's release so that certainly explains things.  Appreciate the response!

**Comment by Methuselah96** [comment]
This should be fixed now!
