### ISSUE TITLE
react-select v4.3.1 - Unexpected border while typing text

### ISSUE THREAD

**Issue by SimranDev** [JedWatson/react-select#4794]
There is an unexpected blue border when I type text. Please check the image. I tried editing **control** styles by setting **border** zero or none and even removed **boxShadow**. But nothing works. Please check the image. 

`  control: (provided) => ({
    ...provided,
    boxShadow: 'none',
    border: 0,
  }),`

![Screenshot 2021-09-24 110030](https://user-images.githubusercontent.com/81152234/134595481-9e025f62-2d5d-4a74-b6e6-2400dc08394d.png)

**Comment by ebonow** [comment]
Greetings @SimranDev ,

Would you be able to provide a codesandbox example? I wonder if this is perhaps a browser default focus outline being applied to the input.

**Comment by SimranDev** [comment]
I just tried in CodeSandbox. There is no border like this around the text. I tested my app in chrome and edge, the same issue on both browsers. Is there any solution if it is related to browser default focus? And my normal HTML input tags don't have this behavior. Cheers @ebonow

**Comment by ebonow** [comment]
@SimranDev can you do an inspect on element and identify where the styling is coming from. Certainly the red caret color appears to be non-standard with anything I have seen so I wonder where these styles are being applied from...

**Comment by SimranDev** [comment]
Thanks for the advice. While inspecting I figure out **tailwindcss-forms** plugin was overriding **box-shadow** on focus. So I found two solutions to it. 

1.  Remove plugin from **tailwind.config.js** file. Basically remove this line `require('@tailwindcss/forms')`.
2.  If you can't afford to remove the plugin. Just override it from your parent CSS file. In my case, **_index.css_**. I added this and it resolved the issue created by tailwindcss. `input[type='text']:focus {
  box-shadow: none;
}`

Thanks again @ebonow

**Comment by donnfelker** [comment]
Thank you! I've been trying to figure this rogue box out forever now.

**Comment by bimalgrg519** [comment]
Thank you @SimranDev 

With custom styles way:

`const customStyles: StylesConfig = {
  input: (base) => ({
    ...base,
    "input[type='text']:focus": { boxShadow: 'none' }, // 
  }),
};`
