### ISSUE TITLE
v5 should export the SelectComponentsConfig type

### ISSUE THREAD

**Issue by srmagura** [JedWatson/react-select#4798]
My TypeScript codebase had the following import which is now failing after upgrading to v5 and removing `@types/react-select`:

```ts
import { SelectComponentsConfig } from 'react-select'
```
> Module '"react-select"' has no exported member 'SelectComponentsConfig'.

I see `SelectComponentsConfig` still exists in the source. Could it be exported? Thanks!

Hacktacular workaround:
```ts
type SelectComponentsConfig<T1, T2, T3> = any
```

**Comment by Methuselah96** [comment]
Yeah, we can do that. Better workaround until we get that exported from the main entrypoint:

```
import { SelectComponentsConfig } from 'react-select/dist/declarations/src/components';
```
