### ISSUE TITLE
V5: Custom selectProps require ts-ignore in Typescript

### ISSUE THREAD

**Issue by jmrossy** [JedWatson/react-select#4804]
Hi, congrats on the big v5 release!

After upgrading to v5, use of custom props on Select cause errors in Typescript. They still seem to work but require ts-ignore directive to silence the error.

Example:
```
    <Select<MyOption>
      id={id}
      options={options}
     {... more props ...}
      components={{ SingleValue }}
      myCustomProp='foobar'
    />

function SingleValue({ children, ...props }: SingleValueProps<MyOption>) {
  return (
      <div>
        <label htmlFor={selectProps.name}>
          {props.selectProps.myCustomProp}
        </label>
         <components.SingleValue {...props}>{children}</components.SingleValue>
         <div className="ml-1">
            <components.DownChevron />
         </div>
      </div>)
}
```

**Comment by Methuselah96** [comment]
Sorry, I forgot to include how to type custom `selectProps` in the upgrade guide and TypeScript usage documentation. I'll work on adding that documentation.

The only reason this worked for `@types/react-select` is because there was an index signature that would type any unknown prop as `any`. This was a little bit too loose and was causing numerous problems. In order to do this in v5 you'll need to use module augmentation to augment the type of the Select props. Here's how to update your example so it works in v5:

```jsx
import Select, { components, GroupBase, SingleValueProps } from 'react-select';

declare module "react-select/dist/declarations/src/Select" {
  export interface Props<
    Option,
    IsMulti extends boolean,
    Group extends GroupBase<Option>
  > {
    myCustomProp: string;
  }
}

function SingleValue({
  children,
  ...props
}: SingleValueProps<MyOption, false>) {
  return (
    <div>
      <label htmlFor={props.selectProps.name}>
        {props.selectProps.myCustomProp}
      </label>
      <components.SingleValue {...props}>{children}</components.SingleValue>
      <div className="ml-1">
        <components.DownChevron />
      </div>
    </div>
  );
}

export default function App() {
  return (
    <Select<MyOption>
      id={id}
      options={options}
      components={{ SingleValue }}
      myCustomProp="foobar"
    />
  );
}
```

Let me know if that works for you.

**Comment by jmrossy** [comment]
@Methuselah96 Works for me! Thanks for the response :)

**Comment by doubleforte** [comment]
> ```js
> declare module 'react-select/dist/declarations/src/Select' {
>   export interface Props<
>     Option,
>     IsMulti extends boolean,
>     Group extends GroupBase<Option>
>   > {
>     myCustomProp: string;
>   }
> }
> ```

I tried adding the `declare` to my `react-app-env.d.ts` file and the app crashes because it can't find my custom prop. If I have it in a separate file it works just fine. Any idea why this wouldn't work in `react-app-env.d.ts`?

**Comment by Methuselah96** [comment]
No, not off-hand. Are you sure `react-app-env.d.ts` is being included in the TypeScript compilation? That's the only thing I can think of. Also, I assume you're importing `GroupBase` in `react-app-env.d.ts`?

**Comment by doubleforte** [comment]
Yes, importing `GroupBase`.

Seems that there was a conflict with another `declare module` I had in that file. I was able to find a way around declaring in `react-app-env.d.ts` and now everything is fine. Thanks. :)

**Comment by eckmLJE** [comment]
Is this in the docs yet? I was looking for it but couldn't find it. Glad I was able to find this here! It would be nice to be able to reference docs for the rest of my team that may come across this in the future vs. an issue here.

**Comment by Methuselah96** [comment]
Sorry that I've neglected to add this to the documentation earlier. I've created https://github.com/JedWatson/react-select/pull/5044 to add it to the TypeScript docs and upgrade guides and can now also be found in the release notes for [v5.0.0](https://github.com/JedWatson/react-select/releases/tag/react-select%405.0.0).

**Comment by gxxcastillo** [comment]
Hi @Methuselah96 , I have different use cases for react-select within my app and when I use module augmentation the result is that now every instance of react-select is being required to comply to the new augmented props.  Is there a way to work around this?

**Comment by vjee** [comment]
@gxxcastillo See https://github.com/JedWatson/react-select/issues/4804#issuecomment-945972022

**Comment by mdmathewdc** [comment]
If you are using an external file for defining the typings, use this:

**Inside `app/typings/react-select.d.ts`**:

```
// eslint-disable-next-line import/no-extraneous-dependencies
import { GroupBase } from 'react-select';

declare module 'react-select/dist/declarations/src/Select' {
  export interface Props<
    Option = unknown,
    IsMulti extends boolean = false,
    Group extends GroupBase<Option> = GroupBase<Option>,
  > {
    option?: Option;
    isMulti: IsMulti;
    group?: Group;
    myCustomProp?: boolean;
  }
}
```

**Comment by wojtekZajac** [comment]
Hi @mdmathewdc, I'm trying to create a similar external typings for async select but cannot get it working.
Any ideas what should it look like? Thanks.

**Comment by bostrom** [comment]
> Also, I assume you're importing `GroupBase` in `react-app-env.d.ts`?

This just bit me, too. Although it's kind of obvious, the import could be included in the example in the docs for copy-pasters like me, since even eslint didn't seem to notice it 😉

**Comment by nifanic** [comment]
I managed to augment `Select.d.ts` (to add custom `isValid`) by importing `Prop`, like so—

```tsx
/* eslint-disable @typescript-eslint/no-unused-vars */
import { Props } from 'react-select/dist/declarations/src/Select';

/**
 * @see https://react-select.com/typescript#custom-select-props
 */
declare module 'react-select/dist/declarations/src/Select' {
  import { GroupBase } from 'react-select';

  export interface Props<
    Option,
    IsMulti extends boolean,
    Group extends GroupBase<Option>
  > {
    /**
     * `true` if value is valid.
     */
    isValid?: boolean;
  }
}

```

**Comment by eckmLJE** [comment]
The [docs for this issue appear to have changed](https://react-select.com/typescript#custom-select-props), and since updating react-select and using what is shown in the docs in my component library, consumers of my library are no longer getting my custom props, although they are available within the library. Previously, consumers were able to pick up these custom prop types fine. 

```ts
import type {} from 'react-select/base';

// https://react-select.com/typescript#custom-select-props

declare module 'react-select/base' {
  export interface Props<
    Option,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    IsMulti extends boolean,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    Group extends GroupBase<Option>
  > {
    appearance?: SelectAppearance;
    isSortable?: boolean;
    status?: InputValidationStatus;
    maxSelectedOptions?: number;
  }
}
```

![image](https://github.com/JedWatson/react-select/assets/31972879/c236ee47-32c2-40d3-840d-179b1092c87c)

**Comment by blerner** [comment]
I found a _very_ hacky, unsound workaround for now:
```ts
const Group: React.FC<GroupProps<MyCustomOptions>> = (props) => {
  const {
    selectProps,
  } = props;
  const {
    myCustomProp,
  } = (selectProps as unknown as {
    myCustomProp: ...
  });
  return <CustomComponent myCustomProp={myCustomProp} />
};

///// later, to use it
      <Select
        // Pass-along props to CustomComponent
        // Must use this spread-of-lieral-object shenanigan to
        // dodge TS's complaining about unknown properties
        {... { myCustomProp: "some value" }}
      />
```
As far as I can tell, the custom props get passed along just fine; I just needed to hide them from the overzealous type-checker here :)
