### ISSUE TITLE
[5.0.0] Build error in src/components/Menu.tsx

### ISSUE THREAD

**Issue by jhg023** [JedWatson/react-select#4805]
![image](https://user-images.githubusercontent.com/18515648/134793397-46f5d233-d765-45da-8ad3-b2c92e257985.png)

I'm encountering the above error when attempting to build any project with v5.0.0 of `react-select`, which looks to be caused by the following line in `src/components/Menu.tsx`:
```
context!: ContextType<typeof PortalPlacementContext>;
```

The documentation of `Component` states the following:
```
* If using the new style context, re-declare this in your class to be the
* `React.ContextType` of your `static contextType`.
* Should be used with type annotation or static contextType.
*
* ```ts
* static contextType = MyContext
* // For TS pre-3.7:
* context!: React.ContextType<typeof MyContext>
* // For TS 3.7 and above:
* declare context: React.ContextType<typeof MyContext>
```
The current code that's causing the error looks like it was intended for use in TS pre-3.7, but `react-select` currently depends on version `^4.1.3` of `typescript`.

I'm not much of a web developer, but it looks like the proper solution is to replace the problematic line with the following:
```
declare context: ContextType<typeof PortalPlacementContext>;
```
If it would be helpful, I'm happy to open a pull request to fix this issue.

Thanks!

Edit: The version of React in my project is `17.0.2`, whereas `react-select` depends on version `^16.13.0`.

**Comment by sallakos** [comment]
Could someone maybe take a look at this?

**Comment by Methuselah96** [comment]
How are you importing `react-select`?

Please note from the migration guide:

> If you were previously importing a type from the `src` directory when using `@types/react-select`:
> 
> ```
> import { ... } from 'react-select/src/...';
> ```
> 
> These should now be imported from the `dist/declarations/src` directory:
> ```
> import { ... } from 'react-select/dist/declarations/src/...';
> ```
> 
> We export any types from the main entry point that we think might be useful to the user. If you are using a type that is not exported from the main entry point please open a PR or issue so that we can add it.

**Comment by sallakos** [comment]
I did some digging and I think I found the problem in another project ours depends on, so false alarm. Sorry for the trouble.

**Comment by jhg023** [comment]
Why was this issue closed?

I (the author of this GitHub issue) am still experiencing the problem. The source code of `react-select` does not use the recommended TypeScript syntax for the version of React that I'm using, as seen in my screenshot.

The error does not occur in my own project's code, but in the `react-select` source code itself.

**Comment by Methuselah96** [comment]
Apologies, I'm sure there was just confusion about whether the issue was resolved.

How are you importing `react-select`.

**Comment by jhg023** [comment]
> Apologies, I'm sure there was just confusion about whether the issue was resolved.
> 
> How are you importing `react-select`?

No worries :)

I am not importing anything from `react-select/src/...`

The only related code was:
```
import { OptionTypeBase } from 'react-select';
```
However, I believe `OptionTypeBase` was eliminated in this latest version, so I simply removed the respective imports.

My project also depends on `react-select-async-paginate` (which could be causing the issue?), so I'll do a little more investigating now on that end and get back to you.

**Comment by jhg023** [comment]
I updated `react-select-async-paginate` to the latest version (`0.6.0`), and that seemed to fix the issue.

I apologize for the inconvenience!
