### ISSUE TITLE
Export AsyncCreatableProps in react-select/dist/declarations/src/AsyncCreatable

### ISSUE THREAD

**Issue by hcharley** [JedWatson/react-select#4806]
# Are you asking a question?

No

# Are you reporting a bug or runtime error?

No

# Are you making a feature request?

My usecase is to migrate this line from `@types/react`:
 
```tsx
import ReactSelectCreatable, {
  Props as ReactSelectCreatableProps,
} from 'react-select/async-creatable';
```

To this line:

```tsx
import ReactSelectCreatable, {
  AsyncCreatableProps as ReactSelectCreatableProps,
} from 'react-select/dist/declarations/src/AsyncCreatable';
```

**Comment by Belco90** [comment]
Hey @hcharley!

This shouldn't be an issue: React exposes `ComponentProps` type util for this case. You have more info here: [React + TypeScript Cheatsheets - The Types I need weren't exported!](https://github.com/typescript-cheatsheets/react#the-types-i-need-werent-exported)

So you could just do:

```ts
import type { ComponentProps } from "react";
import ReactSelectCreatable from 'react-select/async-creatable';

type ReactSelectCreatableProps = React.ComponentProps<typeof Button>;
```

**Comment by Methuselah96** [comment]
I don't think that will be sufficient since `AsyncCreatableProps` is generic and I'm not sure it `ComponentProps` can preserve the generics.

**Comment by Belco90** [comment]
@Methuselah96 that's interesting! I've never run into that issue with generics before, so I can't help you with that case 😞
