### ISSUE TITLE
The page `https://react-select.com/props` is broken

### ISSUE THREAD

**Issue by OfirD1** [JedWatson/react-select#4808]
Browse to [https://react-select.com/props](https://react-select.com/props), and you'll see all examples are "loading". 

The console shows the following error:

> Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

The error is thrown from `useMagicalNodes` on this line:

> `.then((x) => x.json())`

The "json" URL is:

> https://react-select.com/magical-types/magical-types-0-0.pl5a2gtoah.json

But this file is actually an HTML.

Please fix :pray:

**Comment by Methuselah96** [comment]
Thanks for the report, we're going to keep the issue centralized in https://github.com/JedWatson/react-select/issues/4796.
