### ISSUE TITLE
Can't create a prodaction build with react select

### ISSUE THREAD

**Issue by AlekseiBobrov** [JedWatson/react-select#4811]
Hi, i have the same error like https://github.com/JedWatson/react-select/issues/4179:
ERROR in ./node_modules/react-select/src/theme.js 3:12
Module parse failed: Unexpected token (3:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // @flow
|

import type { Theme } from './types';
|
| export const colors = {

It happens in 3 and 4 versions of react-select( i need support of IE11)

**Comment by Rall3n** [comment]
Hello @AlekseiBobrov,

what is the exact line of code when you try to import the component?

**Comment by AlekseiBobrov** [comment]
import Select from 'react-select';

**Comment by AlekseiBobrov** [comment]
Hello! Do you have any ideas?
