### ISSUE TITLE
Different placeholder/input behaviour on single and multi select

### ISSUE THREAD

**Issue by santialbo** [JedWatson/react-select#4815]
After 5.0.0 on multiple Select the input is placed after the placeholder. See the 2 following screenshots from the current docs.

<img width="639" alt="Screenshot 2021-09-27 at 15 12 29" src="https://user-images.githubusercontent.com/1557563/134915297-82728f77-a8d5-4eca-9e9c-ae045949bdb7.png">
<img width="594" alt="Screenshot 2021-09-27 at 15 09 09" src="https://user-images.githubusercontent.com/1557563/134915076-185f23eb-dd04-4587-bf48-937098b0c1a3.png">

react-select version: 5.0.0
browser: firefox 93

**Comment by Rall3n** [comment]
Hello @santialbo,

thanks for reporting this issue. The same has already been reported through #4797, so I'm going to close yours in favor of the other one to keep things centralized.
