### ISSUE TITLE
First letter is chopped in Safari

### ISSUE THREAD

**Issue by patrikhultgren** [JedWatson/react-select#4821]
First letter is chopped in Safari with react-select 5.0.0. Take a look at "AA" in the attached image. I'm using an iPhone 12 Pro Max with iOS 14.3. (I'm experiencing the same issue in Chrome)

<img width="606" alt="iphone-safari" src="https://user-images.githubusercontent.com/1917147/135222438-9d46837f-3e13-4e5a-adec-6019d54f0b13.png">

**Comment by mikunpham** [comment]
@patrikhultgren I saw the same issue on Chrome too. This happens whenever I type a `space` in the input. Apparently, if multiple `space` are typed, the text will be moved to the left too.

![image](https://user-images.githubusercontent.com/6479147/135307476-d169f87b-5278-4169-b300-a9443de4468d.png)
