### ISSUE TITLE
React Multi Select places the cursor(caret) at the end of the placeholder when the input is focused

### ISSUE THREAD

**Issue by ioanungurean** [JedWatson/react-select#4830]
Check the Multi Select on the oficial page: https://react-select.com/home

Chrome Version 94.0.4606.71 (Official Build) (64-bit)

**Comment by Rall3n** [comment]
Hello @ioanungurean,

thanks for reporting this issue.
There already exists an issue (#4797) which addresses the same problem. I will close your issue in favor of the other to keep things centralized.
