### ISSUE TITLE
Accessibility issue with combobox

### ISSUE THREAD

**Issue by sanjaykc** [JedWatson/react-select#4832]
Getting below accessibility issue while using combo box component.

**Issue**: The 'id' "react-select-5-listbox, react-select-5-listbox" specified for the ARIA property 'aria-controls, aria-owns' value is not valid

Above issue can be replicated with react-select samples https://codesandbox.io/s/codesandboxer-example-forked-vcdjt

**Comment by ebonow** [comment]
@sanjaykc 

I am not seeing this error though the console is throwing a different error. Would you mind attaching a screenshot or producing a codesandbox that will reliably throw the error that you are seeing?

**Comment by LauRoxx** [comment]
When using Continuum Explorer Pro chrome extension it lists the same issue. `aria-controls` and `aria-owns` reference the listbox element even when it is not in the DOM. As recommended [here](https://github.com/w3c/aria/issues/531#issuecomment-280757475) "Wait until it is [added to the DOM] before adding `aria-controls` to the controlling element; that is, synchronize the presence/absence of the two."
![aria-controls error screenshot](https://user-images.githubusercontent.com/39015049/148977266-7b831b3c-84ff-405d-ab71-964b7c90766a.png)

**Comment by LauRoxx** [comment]
looks like this issue should be solved with [this PR](https://github.com/JedWatson/react-select/pull/5131)

**Comment by Rall3n** [comment]
@LauRoxx thanks for the information.

I will close this issue based on the status of the mentioned PR.
