### ISSUE TITLE
How to provide Ref to ReactSelect? 

### ISSUE THREAD

**Issue by balex777** [JedWatson/react-select#4835]
How to provide Ref to ReactSelect? In last version was prop inputRef but in new version its prop gone

**Comment by Markus1607** [comment]
How come this issue is closed without an answer? 
If there is an answer then how do you provide Ref in the new version?

**Comment by mbonaci** [comment]
@Markus1607 it was closed because it belongs in discussions, I assume.
I think they implemented ref forwarding in v5, so you can just assign a regular `ref` prop, as you would to a native HTML element.
