### ISSUE TITLE
Implicit return in Select.tsx causing compile issues with tsc

### ISSUE THREAD

**Issue by Benjamin-Kuzava** [JedWatson/react-select#4841]
The .map on line 1849 has an unchecked branch if there is no item type of "group" or "option". This causes a compilation issue if a tsconfig has noImplicitReturns: true, regardless of the fact that this file is in node_modules. Would suggest filtering first, or using .reduce here.

**Comment by Methuselah96** [comment]
In what case would `item.type` be something other than `'group'` or `'option'`?

**Comment by Methuselah96** [comment]
Sure, but why are you loading any of the files from the `src` directory? Are you importing some types by chance? Note this from the v5 upgrade guide:

> If you were previously importing a type from the `src` directory when using `@types/react-select`:
> 
> ```
> import { ... } from 'react-select/src/...';
> ```
> 
> These should now be imported from the `dist/declarations/src` directory:
> ```
> import { ... } from 'react-select/dist/declarations/src/...';
> ```
> 
> We export any types from the main entry point that we think might be useful to the user. If you are using a type that is not exported from the main entry point please open a PR or issue so that we can add it.
