### ISSUE TITLE
Clicking on the same option twice clear the selected value

### ISSUE THREAD

**Issue by yoni-salt** [JedWatson/react-select#4843]
Clicking on the same option twice, clear the select value, also the onChange send a null as the value
not sure if it's a bug, if not, How can i disable this behavior?

**Comment by ebonow** [comment]
The value of the select can be 4 Types:
1. Option
2. Array of Options
3. `null` - The value has explicitly been set to empty or the selected option has been removed
4. `undefined` - The value of the select has not been set

What is your use-case for wanting to "disable this behavior"?

**Comment by ebonow** [comment]
Since this is intended behavior, this is not an issue. 

If you do need to change this behavior, it is possible to use a controlled input so that you control what value is set and passed into the Select.

```jsx
// Default value for when value is null
const nullOption = { label: 'No Option Selected', value: null };

const [ value, setValue ] = useState(nullOption);

const onChange = selectValue => {
  const newValue = (selectValue === null)  ? nullOption : selectValue;
  setValue(newValue);
}

return <Select onChange={onChange} value={value} {...otherProps} />
```
