### ISSUE TITLE
Outside click does not close drop after deselecting custom options if MultiValueContainer/ValueContainer is used

### ISSUE THREAD

**Issue by PrabhatInt17** [JedWatson/react-select#4845]
Steps to reproduce:

Step1: Open Dropdown and select all values(by selecting each values or by clicking *Select All*) and try to close by clicking outside. It works.
Step2: Open drop down and deselect any selected value and try to close by clicking outside. It doesnt work.

Note: it does not work only when *Select All* gets selected and then deselecting any value. It works otherwise.

here is codepen link: https://codesandbox.io/s/stoic-brown-uengy?file=/src/MultiSelect.js:0-3136

If it doesnt work then below is code per file:

MultiSelect.js
============================================================

```jsx
import React, { useRef } from "react";
import ReactSelect from "react-select";
import Option from "./Options";
import { components } from "react-select";

const allOption = {
  value: "<SELECT_ALL>",
  label: "All People"
};

const ValueContainer = ({ children, hasValue, getValue, ...props }) => {
  if (!hasValue) {
    return (
      <components.ValueContainer {...props}>
        {children}
      </components.ValueContainer>
    );
  }
  const CHIPS_LIMIT = 3;
  const [chips, otherChildren] = children;
  const overflowCounter = getValue().length;
  let displayChips = chips.slice(0, CHIPS_LIMIT);
  const currentValues = getValue();
  let allSelected = false;
  if (currentValues.some((val) => val.value === allOption.value)) {
    displayChips = [[children[0][0]], children[1]];
    allSelected = true;
  }

  return (
    <components.ValueContainer {...props}>
      {overflowCounter > CHIPS_LIMIT && !allSelected
        ? `${overflowCounter} selected`
        : displayChips}

      {otherChildren}
    </components.ValueContainer>
  );
};

const MultiValue = (props) => {
  let labelToBeDisplayed = `${props.index !== 0 ? "," : ""} ${
    props.data.label
  }`;
  if (props.data.value === allOption.value) {
    labelToBeDisplayed = "All";
  }

  return (
    <components.MultiValueContainer {...props}>
      <span>{labelToBeDisplayed}</span>
    </components.MultiValueContainer>
  );
};

const NoOptionsMessage = (props) => {
  return <components.NoOptionsMessage {...props} />;
};

export const MultiSelect = (props) => {
  // isOptionSelected sees previous props.value after onChange
  const valueRef = useRef(props.value);
  valueRef.current = props.value;

  const isSelectAllSelected = () =>
    valueRef.current.length === props.options.length;

  const isOptionSelected = (option) =>
    valueRef.current.some(({ value }) => value === option.value) ||
    isSelectAllSelected();

  const getOptions = () => [allOption, ...props.options];

  const getValue = () => (isSelectAllSelected() ? [allOption] : props.value);

  const onChange = (newValue, actionMeta) => {
    const { action, option, removedValue } = actionMeta;

    if (action === "select-option" && option.value === allOption.value) {
      props.onChange(props.options, actionMeta);
    } else if (
      (action === "deselect-option" && option.value === allOption.value) ||
      (action === "remove-value" && removedValue.value === allOption.value)
    ) {
      props.onChange([], actionMeta);
    } else if (
      actionMeta.action === "deselect-option" &&
      isSelectAllSelected()
    ) {
      props.onChange(
        props.options.filter(({ value }) => value !== option.value),
        actionMeta
      );
    } else {
      props.onChange(newValue || [], actionMeta);
    }
  };

  return (
    <ReactSelect
      isOptionSelected={isOptionSelected}
      options={getOptions()}
      value={getValue()}
      onChange={onChange}
      components={{
        Option,
        ValueContainer,
        MultiValue,
        NoOptionsMessage
      }}
      hideSelectedOptions={false}
      closeMenuOnSelect={false}
      isMulti
    />
  );
};
```

Options.js
====================================================================

```jsx
import React from "react";
import { components } from "react-select";
const Option = (props) => {
  return (
    <div>
      <components.Option {...props}>
        <input
          type="checkbox"
          checked={props.isSelected}
          onChange={() => null}
        />{" "}
        <label>{props.label}</label>
      </components.Option>
    </div>
  );
};

export default Option;
```

App.js
====================================================================

```jsx
import React, { useState } from "react";
import { MultiSelect } from "./MultiSelect";

export const App = () => {
  const [selected, setSelected] = useState([]);
  const options = [
    { value: "1", label: "Jimmy" },
    { value: "2", label: "Laura" },
    { value: "3", label: "Tommy" },
    { value: "4", label: "Jane" },
    { value: "5", label: "Mike" }
  ];

  return (
    <MultiSelect options={options} value={selected} onChange={setSelected} />
  );
};
```

index.js
====================================================================

```jsx
import React from "react";
import ReactDOM from "react-dom";
import { App } from "./App";

ReactDOM.render(<App />, document.getElementById("root"));
```

====================================================================

react-select: 5.0.0
Please let me know the feedback

**Comment by PrabhatInt17** [comment]
I tried this approach but still cannot resolve the issue. Drop down is still not closing unless I deselect all the values.
Below is the modified code I tried.
const ValueContainer = ({ children, hasValue, getValue, ...props }) => {
  // if (!hasValue) {
  //   return (
  //     <components.ValueContainer {...props}>
  //       {children}
  //     </components.ValueContainer>
  //   );
  // }
  const CHIPS_LIMIT = 3;
  const chips = React.Children.toArray(children);
  const overflowCounter = getValue().length;
  let displayChips = chips.slice(0, CHIPS_LIMIT);
  const currentValues = getValue();
  let allSelected = false;
  if (currentValues.some((val) => val.value === allOption.value)) {
    displayChips = [[children[0][0]], children[1]];
    allSelected = true;
  }

  return (
    <components.ValueContainer {...props}>
      {overflowCounter > CHIPS_LIMIT && !allSelected
        ? `${overflowCounter} selected`
        : displayChips}

      {/* {otherChildren} */}
    </components.ValueContainer>
  );
};

> Hello @PrabhatInt17,
> 
> the main problem that causes this issue is you are rendering two different `ValueContainer` components based on state. Rendering a different container leads to the focused input being unfocused due to it being a completely different input. This will also fire no `onBlur` event leading to the menu not closing on clicking outside.
> 
> This can be fixed by rearranging your component to render only one `ValueContainer`:
> 
> ```js
> return <ValueContainer>
>   {hasValue & myValueChild}
>   {otherChildren}
> </ValueContainer>;
> ```
> 
> It is also a huge anti-pattern to directly access the `children` prop as an array without using the `React.Children` utilities. I recommend using the utility `Children.toArray` which makes sure that the prop `children` is an array (as it can also be a single component or nothing). With us being sure that the value is an array we can filter through it and remove every component that is not part of the value:
> 
> ```js
> const chips = React.Children.toArray(children)
>   .filter(child => ![components.Input, components.Placeholder].includes(child.type));
> ```

**Comment by govind1718** [comment]
click multi checkbox after hide that chackbox value how to solve??

**Comment by faizantroon** [comment]
Today i have come across with this issue and i resolved it by moving my custom components outside of React functional component, Basically you can't define functional component within another functional component because it cause re renders and it will not close the dropdown

**Comment by cleitonpin** [comment]
> Today i have come across with this issue and i resolved it by moving my custom components outside of React functional component, Basically you can't define functional component within another functional component because it cause re renders and it will not close the dropdown

can you give an example? I've been here for a while trying to solve it and without success :(

**Comment by faizantroon** [comment]
> > Today i have come across with this issue and i resolved it by moving my custom components outside of React functional component, Basically you can't define functional component within another functional component because it cause re renders and it will not close the dropdown
> 
> can you give an example? I've been here for a while trying to solve it and without success :(

Share your code or sandbox link

**Comment by cleitonpin** [comment]
> > > Today i have come across with this issue and i resolved it by moving my custom components outside of React functional component, Basically you can't define functional component within another functional component because it cause re renders and it will not close the dropdown
> > 
> > 
> > can you give an example? I've been here for a while trying to solve it and without success :(
> 
> Share your code or sandbox link

everything works as I want, but only the part when I select something and try to click outside and it doesn't close
D:

```
export const CustomValueContainer = ({ isOptionsTag, ...props }: CustomValueContainerProps) => {
  const isMobile = useCheckMobileScreen()
  const selectedOptions = props.selectProps.value as OptionType[]

  if (props.selectProps.isMulti && selectedOptions?.length > 0 && isOptionsTag) {
    const handleRemoveOption = (option: OptionType) => {
      const newSelectedOptions = selectedOptions.filter(selectedOption => selectedOption.value !== option.value)
      props.selectProps.onChange(newSelectedOptions, { action: 'remove-value', removedValue: option })
    }

    const CHIPS_LIMIT = 2
    const twoFirstChips = selectedOptions
      ?.filter(option => option.label !== 'Todos os meses')
      .slice(0, CHIPS_LIMIT)
      .map(option => option.label)

    const counterChips = selectedOptions?.filter(option => option.label !== 'Todos os meses').slice(CHIPS_LIMIT).length
    return (
      <Row gap='0.5rem' alignItems='center' p='0.3rem'>
        {twoFirstChips?.map((option, index) => (
          <Row gap='0.2rem' backgroundColor='neutral.light' p='0.25rem 0.75rem' borderRadius='8px' key={option}>
            <Text variant='tiny' fontWeight={500} color='neutral.low'>
              {option}
            </Text>
            <CancelOutlinedIcon
              sx={{
                '&:hover': {
                  cursor: 'pointer'
                }
              }}
              fontSize='small'
              style={{ fill: theme.colors.neutral.low, transform: 'scale(0.8)' }}
              onClick={() => handleRemoveOption(selectedOptions[index])}
            />
          </Row>
        ))}
        {counterChips > 0 && (
          <Text variant='regular' color='neutral.medium'>
            +{counterChips}
          </Text>
        )}
      </Row>
    )
  } else if (props.selectProps.isMulti && selectedOptions?.length > 0 && isMobile) {
    const firstSelectedOption = selectedOptions?.[0]
    const remainingCount = selectedOptions.length - 1
    let child = null

    if (Array.isArray(props.children)) {
      child = props.children[1]
    }

    return (
      <components.ValueContainer {...props}>
        <Row gap='1rem' alignItems='center' m='0.5rem'>
          {firstSelectedOption && (
            <Row backgroundColor='neutral.light' p='0.25rem 0.75rem' borderRadius='8px'>
              <Text variant='tiny' fontWeight={500} color='neutral.low'>
                {firstSelectedOption.label}
              </Text>
            </Row>
          )}
          {remainingCount > 0 && (
            <Text variant='regular' color='neutral.medium'>
              +{remainingCount}
            </Text>
          )}
          {child}
        </Row>
      </components.ValueContainer>
    )
  } else if (props.selectProps.isMulti && selectedOptions?.length > 0) {
    const selectedOptionsLabel = selectedOptions?.map(option => option.label)
    let child = null

    if (Array.isArray(props.children)) {
      child = props.children[1]
    }

    return (
      <components.ValueContainer {...props}>
        <Row alignItems='center' mx='0.5rem'>
          <Text
            variant='regular'
            color='neutral.medium'
            overflow='hidden'
            width='152px'
            style={{
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap'
            }}
          >
            {selectedOptionsLabel.join(', ')}
          </Text>
          {child}
        </Row>
      </components.ValueContainer>
    )
  }

  return <components.ValueContainer {...props} />
}
```

**Comment by mrKorg** [comment]
Same problem.
The problem seems to occur when you uncheck all the selected options inside the dropdown list,
and when the last option is unchecked, the input loses focus (the cursor is removed),
The dropdown cannot then be closed by outside click, you have to click again to select the input and then the dropdown can be closed.

**Comment by jasan-s** [comment]
> Today i have come across with this issue and i resolved it by moving my custom components outside of React functional component, Basically you can't define functional component within another functional component because it cause re renders and it will not close the dropdown

this solved the issue for me

**Comment by mistadikay** [comment]
If you experience this issue try it without any custom styles. In our case it was css issue
