### ISSUE TITLE
Not able to import /async, /creatable, .etc from an ES module

### ISSUE THREAD

**Issue by srmagura** [JedWatson/react-select#4859]
### [Minimal repro](https://github.com/srmagura/react-select-esm-repro)

If placed in an `.mjs` file, the following code results in an error.

```js
import AsyncSelect from "react-select/async";

console.log(AsyncSelect);
```

```text
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\Projects\OSS\Bugs\react-select-esm-repro\node_modules\react-select\async' is not supported resolving ES modules imported from C:\Projects\OSS\Bugs\react-select-esm-repro\index.mjs
Did you mean to import react-select-esm-repro/node_modules/react-select/async/dist/react-select.cjs.js?
    at finalizeResolution (internal/modules/esm/resolve.js:281:17)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///C:/Projects/OSS/Bugs/react-select-esm-repro/node_modules/react-select/async'
}
```

While this reproduction uses Node, the issue also occurs when using Webpack 5 which follows Node's handling of ES module imports. Here's the Webpack error for Googleability:

```text
Module not found: Error: Can't resolve 'react-select/async' in 'C:\Projects\ITI\iti-react\iti-react\dist'
Did you mean 'react-select.esm.js'?
BREAKING CHANGE: The request 'react-select/async' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

## Suggested Solution

Utilize the `exports` field in `package.json` [as described in the Node documentation.](https://nodejs.org/api/packages.html#packages_subpath_exports)

## Additional Context

- react-select version: 5.1.0
- Node version: 14.17.6

**Comment by ebonow** [comment]
Just had a meeting with Jed and would be grateful and willing to accept a PR that would address this.

**Comment by srmagura** [comment]
Hey @ebonow, I made an attempt at this but I am unable to get even the most basic case to work...

I added this to the `react-select/package.json`:

```json
"exports": {
    ".": "./dist/react-select.esm.js",
},
```

With this change in place, the following will fail if placed in an `.mjs` file:

```js
import Select from 'react-select'
```

Node will resolve `react-select` to `node_modules/react-select/dist/react-select.esm.js`. The issue is that Node thinks this is a CommonJS module since the extension is `.js` and `react-select/package.json` does not specify `"type": "module"`. So Node throws an error on line 1 because it sees an `import` statement in a CommonJS module.

I think you need to publish your ES modules with the  `.mjs` extension for this to work. Is that possible, or is it a nonstarter?

**Comment by ebonow** [comment]
I don't suspect we'd want to introduce any breaking changes. I'll bring this up for further discussion and do some more investigation.

**Comment by AlonsoLucasls** [comment]
Hello guys, Any news about this?

**Comment by LucianoRochaDev** [comment]
Hello there, we need some help here! Same problem...

**Comment by gdiazdelaserna** [comment]
I created the PR above to address this issue. Want to take a look @ebonow?

@srmagura was on the right track, but his solution was missing the conditions to be able to support both CJS and ESM environments.

I tested the solution in the PR in a Webpack 5 environment and it works correctly.

**Comment by w-a-t-s-o-n** [comment]
I ran into this issue on version `5.7.0` when using the `react-select/creatable` library.  I can confirm that upgrading to `5.7.2` fixed this issue for me!

**Comment by aashishsingla567** [comment]
I am having the same issue in verstion ```5.7.3```
