### ISSUE TITLE
Select component doesn't higlight new value when setup it via "onMenuOpen" event

### ISSUE THREAD

**Issue by Vladqqqqoo** [JedWatson/react-select#4867]
**USE CASE:**
What I'm trying to do is to pre-filled some value when user click on select component using _onMenuClick_ event.

**EXPECTED:**
When the user click on period year select component I want to pre-fill the select component with current year value. I want selected option to have focus and highlighting (as if we click it manually). I don't want the select component has a default value.  I want it to have simple controlled value and pre-filled it with some value when user click on menu and the select component is empty.

**OBSERVED**:
The value of the current year is set, but the value has no focus and highlighting. But if you close and reopen the select component, the focus will appear and highlight the value we set earlier.

**STEPS TO REPRODUCE:**
Create a select component as in the code below.

```
import React, { useState } from 'react';
import Select from 'react-select';
import './App.css';

const periodYearData = [
    { value: 10, label: '2030' },
    { value: 9, label: '2029' },
    { value: 8, label: '2028' },
    { value: 7, label: '2027' },
    { value: 6, label: '2026' },
    { value: 5, label: '2025' },
    { value: 4, label: '2024' },
    { value: 3, label: '2023' },
    { value: 2, label: '2022' },
    { value: 1, label: '2021' },

];
const currentYear = new Date().getFullYear();
const defaultValue = periodYearData.find(obj => currentYear.toString() === obj.label);

function App() {
    const [value, setValue] = useState<any>();

    const onChange = (value: any) => setValue(value);

    const onMenuOpen = (): void => {
        if (!value) {
            onChange(defaultValue);
        }
    };

    return (
        <div className="App">
            <div style={{ width: '200px' }}>
                <Select
                    value={value}
                    options={periodYearData}
                    onChange={onChange}
                    isClearable={true}
                    isSearchable={false}
                    onMenuOpen={onMenuOpen}
                />
            </div>
        </div>
    );
}

export default App;
```

**INFO:**
library version - "react-select": "5.1.0",
browsers - firefox 78.15.0esr (64-bit), google chrome Version 94.0.4606.71 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/42637889/138105154-fd54eb6c-9d58-4ced-b583-82a243619468.png)
![image](https://user-images.githubusercontent.com/42637889/138105202-8934c4df-99c0-44b0-85f0-1128035bd61c.png)

**Comment by ebonow** [comment]
@Vladqqqqoo 

Your approach will not work. The `onMenuOpen` callback is called after the focusedOption has been determined and set to state.
https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.tsx#L800-L807

Your options would be to:
1. Use an event prior to the menu open such as `onFocus` 
<Select onFocus{() => (!value)  && onChange(defaultValue)} {...otherProps} />

2. Wait for the menu to open and then manually scroll the menu to the element.
3. You could create a ref to the Select and manually update the internal state

With approach # 2, there is a known issue where the reference to the menuList doesn't exist yet so a `useTimeout` is necessary to wait for the event queue.

With approach # 3, there is no guarantee that internal methods will not break in future updates as only documented external

**Comment by ebonow** [comment]
Any of the above solutions should suffice for you to achieve what you are trying to do. The issue you are describing seems more a matter of implementation by design rather than some issue and there is already a bug logged to ensure that the menuListRef is available onMenuOpen https://github.com/JedWatson/react-select/issues/4243 

If you would like to propose a change in behavior or a feature request, please feel free to use the discussions area so that the list of issues remain focused on bugs for maintainers and users to sort through.
