### ISSUE TITLE
'touchend' event type not handled when closing menu

### ISSUE THREAD

**Issue by sreedhap** [JedWatson/react-select#487]
The methods "handleMouseDownOnArrow" and "handleMouseDown" do not check for "touchend" event-type, so the "if" expression returns false and the dropdown menu does not close in mobile browsers. You check this behaviour by opening the http://jedwatson.github.io/react-select/ demo page in chrome with device mode toggled on.

**Comment by sreedhap** [comment]
(bump) any updates ?

**Comment by FutureKode** [comment]
+1

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
