### ISSUE TITLE
React-select doesn't like undefined values?

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#488]
Needs investigation; based on erikras/redux-form#82 it sounds like react-select doesn't play nicely with undefined in the `value` prop. If not, we should fix that.

**Comment by markuso** [comment]
I am using redux-form and when I clear the current selected value (which sets it to undefined), it breaks  with the following console error:

```
Uncaught TypeError: Cannot read property 'length' of undefined
```

The error is within the `loadAsyncOptions` method on the following line:

```
for (var i = 0; i <= input.length; i++)
```

**Comment by markuso** [comment]
This is now working correctly after v0.9.0 release. Thanks and this issue can be closed.

**Comment by eipark** [comment]
@markuso your issue looks like #439

**Comment by eran-or** [comment]
I'm using ^3.0.4 same issue

**Comment by bertho-zero** [comment]
Same with ^3.0.8, in 2020.

**Comment by JedWatson** [comment]
I'm going to close this on the basis I believe it's working as it should now.

The current behaviour as designed is that:

* Providing `undefiend` to the `value` prop makes the component "uncontrolled" and react-select will manage the state and onChange event
* Providing the `value` makes the component "controlled", so you need to maintain the value and handle `onChange` in your app

This is covered by tests and reproducible, so if anyone can report unexpected behaviour please open a new issue with a description and how to reproduce it.
