### ISSUE TITLE
Dropdown Hiding inside the table

### ISSUE THREAD

**Issue by Fir-3** [JedWatson/react-select#4880]
I have a react-select component in my table it works fine when there are lots of data but when I search for a row/value inside the table or If I have 2 or 3 rows in my table, my dropdown hides inside the table attaching the screenshot below
so can you help me with this, please?

![Untitled](https://user-images.githubusercontent.com/74525345/139072947-1575675d-db67-4135-aa78-97e1e99a282e.png)

code sandbox --> [https://codesandbox.io/s/tender-sound-95sgv?file=/src/App.js](https://codesandbox.io/s/tender-sound-95sgv?file=/src/App.js)

- react: ^16.14.0
- react-data-table-component: ^7.0.0-rc6
- react-select: ^4.3.1

**Comment by robxbob** [comment]
> ```js
> ```js
> <Select menuPortalTarget={document.body} />
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Is there a way to resolve this without affecting accessibility? (if it does affect it)

**Comment by Pragati-Kashyap** [comment]
I've been stuck on this problem for so long. Thanks, @Rall3n, it worked perfectly!
