### ISSUE TITLE
HOC replacement hooks are not exported

### ISSUE THREAD

**Issue by vjee** [JedWatson/react-select#4884]
It seems `useAsync`, `useCreatable` and `useStateManager` are not exported at the moment while in the [upgrade guide](https://react-select.com/upgrade) they are advertised as replacements for the preciously exported HOCs.

Can these exports be added?

**Comment by Akridian** [comment]
Feels sad we don't get those changes in 5.2.0. 😢

**Comment by ebonow** [comment]
> Feels sad we don't get those changes in 5.2.0. 😢

@Akridian 
Sorry 5.2 was based on features/fixes completed several weeks ago but was held up by authentication issues in the release pipeline. We just got those issues resolved over the weekend. 

We'll likely discuss your PR this week and hope to get a new release together soon.

**Comment by Akridian** [comment]
I appreciate your attention.

**Comment by ebonow** [comment]
@Akridian I'm happy to report that the PR for this was approved and has been merged and released as a part of v5.2.1
