### ISSUE TITLE
Pass current value in `onBlur` event

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#489]
As discussed in erikras/redux-form#82

When you listen to the `onBlur` event on input fields, `e.target.value` will contain the value of the input which can be useful. This behaviour doesn't work in `react-select` because the DOM node being blurred is the search input, not the field itself.

We could hack around this and set `e.target.value` before firing the event handler - I'm not absolutely positive this would have no unintended side effects, but it seems safe.

Anyone want to weigh in on this?

**Comment by oluckyman** [comment]
Related discussion was here #186

**Comment by Agamennon** [comment]
@JedWatson i might have a related issue here,  if the user types in a search, but does not select it,  it just completely types in the option then blurs the field, if what the user input completely matches on of the options, the select component should select that option and fire a change event.  (at this time it will fire if the user tab's out, but not if the user clicks out from the component)

**Comment by gmethvin** [comment]
@JedWatson I have a similar issue. In my case, if the user has typed something but deselects the input, I'd like it to add that value to my multiselect. If a user presses tab, I would like it to also add the value and keep the input selected. For an example, check out how the compose view in Gmail works when you type someone's email in the "to" field.

I think there should be some configurability with respect to what happens when a user fails to select an option.

**Comment by motoedie** [comment]
@JedWatson I use multiselect with redux-form and it expects data which is stored and propagated back to form. Could it be possible to add calling eg. onBlurValues?

I use wrapper component between redux-form and select component so I could map onBlur to onBlurValues.

**Comment by wmertens** [comment]
So basically, `onBlur` should behave like any input and provide the current value. Can't think of any reason overwriting `event.target.value` is a problem, the events are syntetic events created by React to begin with.

Configurability of behavior could be done by adding methods to the Select class that are available via a ref to the component?

**Comment by ntucker** [comment]
any new ideas here?

**Comment by theskillwithin** [comment]
causes problems with redux-form

**Comment by kumar91mahesh** [comment]
@JedWatson  i am getting blank value in mobile browser in onBlur method. I am getting value of event.target.value in side onBlur method. 
can anyone tell me the solution ?

**Comment by jossmac** [comment]
Assuming resolved in v2. Bump if needs to be reopened.
