### ISSUE TITLE
There is a value on frontend but no value is sent via form

### ISSUE THREAD

**Issue by AdamHasma** [JedWatson/react-select#4907]
So I had this working react-select before I changed my style.scss. After a few styling adjustments, it suddenly didn't work anymore. Well at the frontend everything seems to work. Value is put in and even the props of the component are the same as my old code. But when I send the form data to my google spreadsheet, no value is sent. The rest of the data like email and name just works fine.

![image](https://user-images.githubusercontent.com/59115022/141101989-2db5f508-30bb-4e6b-8640-ffaa1d41bf41.png)
Top is what it should look like and bottom the current issue

![image](https://user-images.githubusercontent.com/59115022/141102739-124d7ec1-bdf5-4c15-b146-f4eec0e8ca61.png)
![image](https://user-images.githubusercontent.com/59115022/141102824-2a13ae88-da79-4ad5-a37e-3033b289a3b4.png)
proof that the value is on the frontend (same output as in my old code)

This is my code: 
```js
<Select
    placeholder="Wähle deine Kategorien"
    name="tags"
    className="basic-multi-select"
    isMulti
    options={allTagsSelect}
    theme={(theme) => ({
    ...theme,
    borderRadius: 4,
    colors: {
      ...theme.colors,
      primary25: '#19F8E5',
      primary: '#19F8E5',
      neutral0: '#282828',
      neutral20: '#4e4e4e'
      }
    })}
  required
  delimiter=" | "/>

  // sending form code if this helps you (same as the old code but with `setLoading`, this is just used for a loading container):
  useEffect(() => {
    const scriptURL = 'https://script.google.com/macros/s/XXXXXXXXXXXXXXXXXXX' +
        'XXXXXXXXXXXXXXXXXXXXX/exec'
    const form = document.forms['submit-to-google-sheet']

    loadCaptchaEnginge(4, '#222', 'white', 'numbers');

    form.addEventListener('submit', e => {
      setLoading(true);
      e.preventDefault();
      if (validateCaptcha(refCaptcha.current.value) === true) {
        fetch(scriptURL, {
          method: 'POST',
          body: new FormData(form)
        }).then(() => {
          setLoading(false);
          setSent(true);
        }).catch(error => console.error('Error!', error.message));
      } else {
        setLoading(false);
        toast.error('Captcha war nicht richtig.', {
          position: "bottom-center",
          autoClose: 5000,
          hideProgressBar: true,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: false,
          progress: undefined
        });
      }
    })
  }, [])
  ```

**Comment by ebonow** [comment]
@AdamHasma 

It doesn't appear that your example includes a `form` prop so can you verify that the Select is a child of the form you are submitting?

Here's a [codesandbox](https://codesandbox.io/s/suspicious-danny-irnom?file=/src/App.js) with your Select example and it doesn't appear to be having any issues retrieving the form data from the select.

**Comment by AdamHasma** [comment]
> @AdamHasma
> 
> It doesn't appear that your example includes a `form` prop so can you verify that the Select is a child of the form you are submitting?
> 
> Here's a [codesandbox](https://codesandbox.io/s/suspicious-danny-irnom?file=/src/App.js) with your Select example and it doesn't appear to be having any issues retrieving the form data from the select.

It is look here: 
![image](https://user-images.githubusercontent.com/59115022/141160323-2d9bc663-2558-4783-9200-f20ef68d8939.png)
It's the prod built so "anonymous" here is the Select component

**Comment by AdamHasma** [comment]
This is my [site](https://search-filter-eta.vercel.app/)

**Comment by ebonow** [comment]
I suspect that the hook is using a stale reference to the form. Perhaps try using `this` or `e.currentTarget` instead of `form` when creating a new instance of the FormData.

From the debugger, I was able to successfully retrieve the selected values  of the Select from the form on your site.
![Screen Shot 2021-11-10 at 9 32 24 AM](https://user-images.githubusercontent.com/1007579/141182661-a81f30f3-d388-4414-9587-487806dfd712.png)

**Comment by AdamHasma** [comment]
> I suspect that the hook is using a stale reference to the form. Perhaps try using `this` or `e.currentTarget` instead of `form` when creating a new instance of the FormData.
> 
> From the debugger, I was able to successfully retrieve the selected values of the Select from the form on your site. ![Screen Shot 2021-11-10 at 11 44 43 AM](https://user-images.githubusercontent.com/1007579/141183210-40ebe89e-25fc-4711-a989-3f7861539109.png)

Sry but I can't follow. Do you mean to not use the form tag? Could you give me an example of how your solution could look like.

**Comment by ebonow** [comment]
> Sry but I can't follow. Do you mean to not use the form tag? Could you give me an example of how your solution could look like.

Replace this:
``` js
   body: new FormData(form)
```

With this (literally):
``` js
   body: new FormData(this)
```

or possibly even with this:
``` js
  body: new FormData(e.currentTarget)
```

Let me know if either of these make a difference in what you are seeing on your end.

**Comment by AdamHasma** [comment]
`this` didn't sent any data at all and `e.currentTarget` did sent the data but again without the select value

**Comment by ebonow** [comment]
Can you try building the formData and logging it before changing state or submitting? I'm curious where this is breaking for you since it doesn't appear to be an issue from where I logged it.

``` jsx
    form.addEventListener('submit', e => {
      const body = new FormData(this);

      // check for entry with tags key value
      body.entries().forEach(entry => console.log(entry));

      setLoading(true);
      e.preventDefault();
      ...
```

**Comment by AdamHasma** [comment]
@ebonow I'm probably doing it wrong but it says `body.entries(...).forEach()` is not a function.
But I found the exact commit since this happened and deployed the working commit [here](https://working-submit-search-filter.vercel.app/) 
And [here](https://github.com/AdamHasma/working-submit-search-filter/commit/756bc9f6e8b103f1622be871d5963a1c7182c75c#diff-616ca554150cf693578d03f995d81e50b2288e87c3f2470686889a7fcdfc0e9f) is the diff on Submit.js. It might be confusing but keep in mind that all the parts of minus are actually plus, so just reversed diff.

But I still can't find the problem :/

**Comment by ebonow** [comment]
I keep forgetting that the entries iterator is different than an array. Here's how to loop through the FormData.

```jsx
    const body = new FormData(e.currentTarget);
    for (const entry of body.entries()) {
      console.log(`${entry[0]}: ${entry[1]}`);
    }
```

I updated the [codesandbox here](https://codesandbox.io/s/suspicious-danny-irnom?file=/src/App.js:403-543) to reflect this. 

Perhaps you want to lead with e.preventDefault before changing state or try adding the onSubmit event directly to your `animated.form` as a synthetic event instead of directly attaching it to the dom element. 

The one clue I see is when the form is rejected by the captcha, the Select's value is being cleared. I'm not entirely sure what's causing this, but it does seem that something is clearing it via the validation or causing it to re-render.

In either case, it doesn't seem to be related to a react-select issue.

**Comment by AdamHasma** [comment]
> I keep forgetting that the entries iterator is different than an array. Here's how to loop through the FormData.
> 
> ```js
>     const body = new FormData(e.currentTarget);
>     for (const entry of body.entries()) {
>       console.log(`${entry[0]}: ${entry[1]}`);
>     }
> ```
> 
> I updated the [codesandbox here](https://codesandbox.io/s/suspicious-danny-irnom?file=/src/App.js:403-543) to reflect this.
> 
> Perhaps in the `useEffect` hook you want to lead with e.preventDefault before changing state or instead of adding an eventListener directly to the DOM item, try adding the onSubmit event directly to your `animated.form`.
> 
> The one clue I see is when the form is rejected by the captcha, the Select's value is being cleared. I'm not entirely sure what's causing this, but it does seem that something is clearing it via the validation or causing it to re-render.
> 
> In either case, it doesn't seem to be related to a react-select issue.

It works! Thank you so much. I did what you suggested.
