### ISSUE TITLE
let asyncOptions accept promises

### ISSUE THREAD

**Issue by dmatteo** [JedWatson/react-select#491]
Looking at the doc here https://github.com/JedWatson/react-select#async-options and after having tried a bit, it doesn't seem that `asyncOptions` is able to use promises.

Being able to do something like this would be great:
```javascript
  render() {

    return (
      <Select
        name={this.props.name}
        asyncOptions={this.fetchOptions.bind(this)}
        onChange={this.handleChange.bind(this)}
        valueRenderer={this.renderValue}  />
    );
  }

  fetchOptions(query) {
    return fetch(`some/uri/with/${query}`)
      .then((response) => {
        return response.json();
      })
  }
```

Any support or interest for a PR?

**Comment by JedWatson** [comment]
I'd happily merge a PR adding promise support for `asyncOptions`

**Comment by dmatteo** [comment]
Do you think it would be better to create another prop for that or just "extend" `asyncOptions` ?

I am worried about adding unnecessary complexity to `asyncOptions` here.

**Comment by dmatteo** [comment]
After a bit of research, I'm more convinced we should have a different prop for the promises, or break the current API with `asyncOptions` and always assume a promise is passed in.

Detecting promises with certainty is expensive: https://github.com/promises-aplus/promises-tests
