### ISSUE TITLE
Tests breaking on node 4.x

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#492]
The test suite currently don't run for me, I think it's because I've upgraded to 4.1.0 and I suspect we need to update `jsdom` to the latest version. We've been holding back on that because jsdom > 3 wasn't compatible with node 0.10/12, but I think now that 4.0 has been released it's fine to update.

The new version of jsdom has breaking changes in its API so running the test suite with the update breaks, we'd need to fix all the tests if we switch.

@bruderstein, thoughts?

**Comment by bruderstein** [comment]
Sorry for the delay in response.  I think we do it - should be fairly trivial to fix.  I'll try and sort a PR out in the next couple of days.
