### ISSUE TITLE
Manually Triggering / Simulating MouseDownEvent on React-Select Components

### ISSUE THREAD

**Issue by anubhav217** [JedWatson/react-select#4933]
**Thanks for using react-select!**

If you are going to ask a question or want to propose a change or a new feature, then please don't file an issue for this.
Questions and feature requests have their own place in our discussions section.

## Are you reporting a bug or runtime error?

Please include a test case that demonstrates the issue you're reporting!

This is very helpful to maintainers in order to help us see the issue you're seeing.

Please note we are currently only directing our efforts towards the current major (v5) version and beyond.

We understand this might be inconvenient but it is in the best interest of supporting the broader community and to sustain the `react-select` project going forward.

To report bugs against react-select v5 please fork the following code-sandbox:
https://codesandbox.io/s/react-select-v5-sandbox-y5jtm

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by Rall3n** [comment]
Hello @anubhav217,

I will close your issue for reasons of low effort.

Also if you want to ask a question please do so in our [dedicated discussions category](https://github.com/JedWatson/react-select/discussions/categories/q-a).
