### ISSUE TITLE
`loadAsyncOptions` receives option value as input

### ISSUE THREAD

**Issue by oluckyman** [JedWatson/react-select#494]
I think the problem is in this part of `componentWillReceiveProps` in [Select.js](https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L191-L193):

``` js
if (newProps.value !== this.state.value || newProps.placeholder !== this.props.placeholder || optionsChanged) {
    var setState = function setState(newState) {
        _this2.setState(_this2.getStateFromValue(newProps.value, newState && newState.options || newProps.options, newProps.placeholder));
    };
    if (this.props.asyncOptions) {
        this.loadAsyncOptions(newProps.value, {}, setState);
    } else {
        setState();
    }
}
```

In case when options are objects like

```
{ value: '54640c91e955f94766279d14', label: 'Test Division' }
```

And a user is selecting one of them, the `newProps.value` will be `'54640c91e955f94766279d14'`. And the `loadAsyncOptions` will use that string as a query to request options from server (via `asyncOptions` prop).
<img width="875" alt="ss 2015-10-02 at 2 45 34 pm" src="https://cloud.githubusercontent.com/assets/642673/10261973/523646f4-69b4-11e5-9c09-007d01889f6a.png">

Actually I don’t understand why is `this.loadAsyncOptions(newProps.value, {}, setState);` call here.

**Comment by Duan112358** [comment]
@oluckyman It also happened to me , :confused:

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
