### ISSUE TITLE
TypeScript: Incompatible `'aria-invalid'` types for `Select`

### ISSUE THREAD

**Issue by prichey** [JedWatson/react-select#4940]
I'm having some issues satisfying TypeScript when upgrading from `react-select` v4 (4.3.1) to v5 (5.2.1).

The crux of it is this:

```
Type '{ styles: StylesConfig<SelectInputOption<T>, false, GroupBase<SelectInputOption<T>>>; options: SelectInputOption<T>[]; ... 356 more ...; className: string; }' is not assignable to type 'Omit<Pick<Props<SelectInputOption<T>, false, GroupBase<SelectInputOption<T>>>, "aria-errormessage" | "aria-invalid" | ... 28 more ... | "form"> & Partial<...> & Partial<...>, StateManagedPropKeys>'.
  Types of property ''aria-invalid'' are incompatible.
    Type 'boolean | "false" | "true" | "grammar" | "spelling" | undefined' is not assignable to type 'boolean | undefined'.
      Type '"false"' is not assignable to type 'boolean | undefined'.
```

I can provide a relatively complete reproduction of my types if useful but TL;DR: up the tree I'm using `AllHTMLAttributes<HTMLSelectElement>` which pulls from React's own [AriaAttributes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1567) type (deep link to `'aria-invalid'` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1654)). This type differs from what's declared as `Props` in [Select.tsx](https://github.com/JedWatson/react-select/blob/20ea0308199ce27309ff89df30c21ecd1c9c5166/packages/react-select/src/Select.tsx#L79), so when I spread props of one type onto the `Select` component, `tsc` yells at me.

IMO the types in `Select` should be modified to match those defined in `AriaAttributes`, since presumably the attribute should follow the same spec. Let me know if I'm missing something on my end, though!

**Comment by prichey** [comment]
I have a naive PR up for this: https://github.com/JedWatson/react-select/pull/4941. This fix is preventing me from upgrading to v5 so please let me know if there's anything else I can do here!

**Comment by prichey** [comment]
@Rall3n tagging you since I see you've been doing triage on recent issues, please let me know what you think whenever you have a chance!

**Comment by Methuselah96** [comment]
As far as preventing you from upgrading to v5, can you just cast until it gets fixed here?

**Comment by prichey** [comment]
I think I'd rather hold off on upgrading instead of introducing a brittle type cast. I'm happy to hold off until this gets sorted out (unless it gets put on ice for some reason)
