### ISSUE TITLE
Creatable is not working with Custom filterOption

### ISSUE THREAD

**Issue by vaishalip151** [JedWatson/react-select#4945]
import Creatable, { useCreatable } from 'react-select/creatable';

i am using creatable with multi select but i want the searching would be according to the prefix match so i used CUSTOM FILTER LOGIC of react select  but  now creatable functionality is not working please help me.
![image](https://user-images.githubusercontent.com/49092971/145262515-d6d84eb4-08ce-4baf-b303-6123740df279.png)

**Comment by Rall3n** [comment]
Hello @vaishalip151,

could you please provide a minimal reproducible example showing your implementation and the problem at hand?

**Comment by vaishaliplms** [comment]
import React,{Component,useRef} from 'react';
import CreatableSelect from 'react-select/creatable';
import Select, { createFilter } from 'react-select';
import { FixedSizeList as List } from "react-window";
import _ from "lodash";
import AsyncCreatable from './AsyncCreatable'


class MenuList extends Component {
    render() {
      const { options, children, maxHeight, getValue } = this.props;
      const [value] = getValue();
      const initialOffset = options.indexOf(value) * 35;
  console.log('children',children,options)
      return (
        <List
          height={maxHeight}
          itemCount={children.length}
          itemSize={35}
          initialScrollOffset={initialOffset}
        >
          {({ index, style }) => <div style={style}>{children[index]}</div>}
        </List>
      );
    }
  }


  
const CreateSelectComponent =(props)=>{

  const filterConfig = {
    ignoreCase:true,
   
    matchFrom: 'start',
  };

  

return( <>
 
<CreatableSelect
    isMulti
    placeholder={props.placeholder}
    name={props.name}
    components={{MenuList}}
    value={props.value}
    onChange={props.onChange}
   options={props.options}
    className="basic-multi-select mrg10-B"
    classNamePrefix="Add Skills"
    openMenuOnClick={false}
   
     filterOption={createFilter (filterConfig )}
    styles={{
      
      dropdownIndicator: defaultStyles => ({
        ...defaultStyles,
        '& svg': { display: 'none' }
      })
    }}
  />
  
  </>
  )
}

export default CreateSelectComponent;

**Comment by Rall3n** [comment]
@vaishalip151 @vaishaliplms

I can't find the problem you described. Using your code as a base I could search through a list of options, where the start of the option matches the input string, and I could create a new option if the option does not already exist.

Could you please create a functional example using [CodeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-y5jtm?file=/example.js)?

**Comment by vaishaliplms** [comment]
![image](https://user-images.githubusercontent.com/70058959/145363142-e435a5fc-096b-4f91-aeca-da134bace194.png)


see this image i want that when i search "ee" gives me the option start from "ee" not Green if that option is not present in the list show the create option. got my point or not?

**Comment by Rall3n** [comment]
> see this image i want that when i search "ee" gives me the option start from "ee" not Green if that option is not present in the list show the create option. got my point or not?

@vaishaliplms As I said before: The code you provided already does filter the options if they match from the start. You never mentioned clearly that you want the `Create ...` option to only be shown when there are no matching options.

For this you have to use the `isValidNewOption` prop, check if any option matches the search string and if not, render the `Create ...` option.

```jsx
const filter = createFilter({
    matchFrom: 'start'
});

<Creatable
   filterOptions={filter}
   isValidNewOption={(inputValue, selectValue, selectOptions, accessors ) => {
    // Check if any options matches inputValue, either from selectValue or selectOptions
    // If not, return true to render the `Create ...` option

    const hasValue = selectValue.some(option => ...);
    const hasOption = selectOptions.some(option => ...);

    return (inputValue && (hasValue || hasOption)) ? true : false;
   }}
/>
```

**Comment by vaishaliplms** [comment]
CreatableSelect  is not working with  filterOptions={filter} and does not filter the options if they match from the start. 

https://codesandbox.io/s/react-select-v5-sandbox-forked-w6zqb?file=/example.js:880-895
please check the above link

**Comment by Rall3n** [comment]
@vaishaliplms The props name is `filterOption`, not `filterOptions`. There is no trailing `s`.
