### ISSUE TITLE
IE10/11: Menu closes when trying click+drag scroll indicator

### ISSUE THREAD

**Issue by rethwyll** [JedWatson/react-select#495]
In IE10 (Win8) and IE11 (Win8.1), when you try to click and drag the scroll indicator in the dropdown menu, the menu closes instead of scrolling. This behavior can be observed on the live demo page (http://jedwatson.github.io/react-select/) with the very first example, the "States" select.

**Comment by songz** [comment]
Ping. I am having this issue as well.

**Comment by petetnt** [comment]
Maybe too closely* based on Selectize: https://github.com/brianreavis/selectize.js/issues/182 

> * It's loosely based on Selectize (in terms of behaviour and user experience)

**Comment by petetnt** [comment]
Okay, the fix is pretty trivial:

```
	handleInputBlur (event) {
        var menuDOM = ReactDOM.findDOMNode(this.refs.menu);
        if (document.activeElement.isEqualNode(menuDOM)) {
            return;
        }

        /**/
```

Working branch here: https://github.com/petetnt/react-select/tree/petetnt/ie10-11-blur-fix 

It needs a test though. ping @JedWatson

**Comment by nil4** [comment]
@petetnt: thank you, I can confirm your fix resolves this issue on IE 11.

**Comment by duoduoin** [comment]
@petetnt Thanks, this fixes the issue on IE9-IE11. 
@JedWatson  could you merge this fix and make a new release?

**Comment by petetnt** [comment]
I'll create some tests for it and fix spaces to tabs and try to create a PR for this today or tomorrow

**Comment by JedWatson** [comment]
Thanks @petetnt :grinning:
