### ISSUE TITLE
Custom classnames should be added after the original classnames. Overriding css classnames not easly possible.

### ISSUE THREAD

**Issue by jackblackCH** [JedWatson/react-select#4953]
If you want to custom style the react-select by applying custom classnames and prefixes, they only work by adding !important to all properties because react-select adds the custom classnames before the original one. 

e.g  `<div className="mycomp-select-search__input-container css-6j8wv5-Input">`

should be  `<div className="css-6j8wv5-Input mycomp-select-search__input-container">`

**Comment by Rall3n** [comment]
Hello @jackblackCH,

order of the CSS classes inside the `class` attribute (`className` property) has nothing to do with how CSS properties are applied.
E.g.:
![image](https://user-images.githubusercontent.com/15950630/145596171-caaf1063-fd01-4689-b778-2ab58c1aeb1a.png)

Whats important is:
1. Order of Stylesheets. `emotion` (the css-in-js library being used by `react-select`) adds their styles by default at the and of the `<head>` tag, having higher priority being at the end. But you can prevent this by using emotions [`CacheProvider`](https://emotion.sh/docs/cache-provider) component and a custom cache created with [`createCache`](https://emotion.sh/docs/@emotion/cache#createcache) and the [`prepend`](https://emotion.sh/docs/@emotion/cache#prepend) option being set to `true`.
2. Order of rules inside the Stylesheets.
3. [CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

**Comment by ebonow** [comment]
Closing this due as a CSS misunderstanding. I'd advise using both className and classNamePrefix to get the class scoping you are likely looking for without using `!important `

``` css
.mycomp-select-search .mycomp-select-search__input-container {
  // styles go here 
}
```
