### ISSUE TITLE
Idea about returning an array as the value when multi-select is true

### ISSUE THREAD

**Issue by sharky93** [JedWatson/react-select#498]
The issue with using delimiters to join is that they're not guaranteed to work all the time. Why not just return an array of all values?

**Comment by aidanlister** [comment]
Yeah the delimiter thing just screwed us ... that's not how normal POST data looks.

**Comment by aidanlister** [comment]
Here's a quick widget to wrap react-select to give you properly formatted post data.

```jsx
var React = require('react');
var Select = require('react-select');


var PrettySelect = React.createClass({
  getInitialState: function() {
    return {
      value: this.props.value,
    };
  },
  renderHiddenInputs: function() {
    var inputs = this.state.value.map(function(val, i) {
      return <input key={i} type="hidden" name={this.props.name} value={val} />
    }.bind(this));
    return (
      <div>{inputs}</div>
    )
  },
  onChange: function(change) {
    this.setState({
      value: change.split(","),
    });
  },
  render: function() {
    var fake_name = this.props.name + '_fake';
    return (
      <div>
        {this.renderHiddenInputs()}
        <Select
          name={fake_name}
          multi={this.props.multi}
          value={this.state.value}
          options={this.props.options}
          onChange={this.onChange}
          noResultsText='No options available ...'
        />
      </div>
    )
  }
})

module.exports = PrettySelect;
```

**Comment by sharky93** [comment]
@aidanlister also, from the outset it looks like `state.values` actually stores the currently selected multiple values

**Comment by aidanlister** [comment]
Not sure what you mean?

**Comment by claflamme** [comment]
Maybe I'm missing something, but the readme states the following in the **Multiselect Options** section:

> The onChange event provides an array of the selected options as the second argument

Just alter the `onChange` handler method to accept the second param and it should be an array of tags:

```js
<Select multi={ true } onChange={ this.onChange } />

// ...

onChange: function(tagString, tagArray) {
  // Do whatever array operations you'd like.
  console.log(tagArray);
},
```

**Comment by aidanlister** [comment]
Great thanks I've updated the script

**Comment by aidanlister** [comment]
I updated it again as the previous change introduced some problems.

**Comment by ustun** [comment]
I agree that this should be changed so that values is an array. If the options depends on input, it screws up the whole thing since the input there is the whole array. :/

**Comment by jonathanphz** [comment]
Any  update on how to make this work??

**Comment by amitripshtos** [comment]
I think it makes more sense to send array instead a string. since array of ids won't go back to number but to string when striped by the delimeter

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
