### ISSUE TITLE
Safari Keyboard covers input when select element is on bottom of page

### ISSUE THREAD

**Issue by mleister97** [JedWatson/react-select#4980]
Please reopen the issue https://github.com/JedWatson/react-select/issues/1321

This still does not work on iOS/Safari devices

**Comment by Rall3n** [comment]
Hello @mleister97,

I cannot confirm the problem (using iPhone 7 - iOS 15 Safari) based on the conditions of the original issue you referenced. 
Could you by chance provide a minimal reproducible example using [CodeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-y5jtm) (as requested in the issue template)?

**Comment by mleister97** [comment]
For some reason it is working now, I guess a broken css was cached.
