### ISSUE TITLE
No possibility to add customizable props eg. icon name after upgrade

### ISSUE THREAD

**Issue by henryjack1** [JedWatson/react-select#4995]
Let's think about adding some additional prop which allow to pass some costomizable props.
In v4 it was possible to pass there anything developer wants. It was not good approach but now we lost a lot of possibilities.

**Comment by Methuselah96** [comment]
Are you referring to TypeScript? See https://github.com/JedWatson/react-select/issues/4804#issuecomment-927223471 for how to accomplish it in v5.

**Comment by henryjack1** [comment]
Many thanks!
