### ISSUE TITLE
String matches bold

### ISSUE THREAD

**Issue by nwinch** [JedWatson/react-select#5]
Perhaps the results could bold the matching parts of the search string? eg.

Search: Sou
Results: New **Sou**th Wales

**Comment by dlong500** [comment]
Any progress on this yet?  I like the idea of a span tag around matched text.

**Comment by dcousens** [comment]
@dlong500 it might be easier to add this functionality through other means, rather than adding all this rich text handling in the component it self. 
As it stands, you could probably handle this in the async search options callback to update the list to have bolded [relevant] values,  but that doesn't really work for the non-async case.

**Comment by dlong500** [comment]
@dcousens I agree it would be possible to handle this outside the component for async operations, but  even then it would be much more pleasant if the component could wrap a span tag around any matching text.  I don't like the idea of having to mix CSS tags into a function that would otherwise only be returning raw data.  Plus it means a lot of code duplication if you've got to implement that functionality all over the place.

**Comment by rkichenama** [comment]
I have been able to get a highlight effect on the options through a sort of kludge of onInputChange and optionRender. Essentially, whenever the input changes, I capture it and use it to construct an array of spans that wrap the matching text with a specific class I can style (react-select-match).

```javascript
Highlighter = (function () {
  function Highlighter () {
    this.input = '';
  };
  Highlighter.prototype = {
    wrap (t, c) {
      return (
        <span className={c}>{t}</span>
      );
    },
    chop (v, i) {
      var
        regexp = new RegExp(i, 'i'),
        mark = v.search(regexp),
        len = i.length;
      if (mark === -1) {
        return [this.wrap(v)];
      } else {
        return [].concat(
          this.wrap(v.substr(0, mark)),
          this.wrap(v.substr(mark, len), 'react-select-match'),
          this.chop(v.substr(mark + len), i)
        );
      }
    },
    onInputChange (inp) {
      this.input = inp
        .replace(/^ +/, '')
        .replace(/ +$/, '')
      ;
    },
    optionRenderer (val) {
      if (this.input && this.input.length) {
        var looking = this.input,
          resp =this.chop(val.label, this.input);
        console.log(resp);
        return resp;
      }
      else {
        return val.label;
      }
    },
  };
  return Highlighter;
}());

...

var highlighter = new Highlighter();

<Select
  onInputChange={highlighter.onInputChange.bind(highlighter)}
  optionRenderer={highlighter.optionRenderer.bind(highlighter)}
  />

```

**Comment by Siyfion** [comment]
I too, think that this would be a really nice addition to the core package, maybe just a toggleable option if nothing else? As this is quite "normal" behaviour for a typeahead I would say.

**Comment by bvaughn** [comment]
Hi all!

This is possible using a custom `optionRenderer` and a 3rd party library like [react-highlight-words](https://github.com/bvaughn/react-highlight-words).

```js
import React from 'react';
import Select from 'react-select';
import Highlighter from 'react-highlight-words';

const options = [];
let inputValue;

function optionRenderer (option) {
  return (
    <Highlighter
      searchWords={[inputValue]}
      textToHighlight={option.label}
    />
  );
}

function render () {
  return (
    <Select
      onInputChange={(value) => inputValue = inputValue}
      options={options}
      optionRenderer={optionRenderer}
      {...otherProps}
    />
  );
}
```

Example:
<img width="423" alt="screen shot 2016-09-04 at 1 37 16 pm" src="https://cloud.githubusercontent.com/assets/29597/18229253/bc71a320-72a4-11e6-8a2f-d3f4a402dbff.png">

I don't think this functionality belongs in `react-select`. It's useful to keep the base component as simple as possible in order to keep in maintainable and bug-free. Since it's easy to add this functionality using 3rd party libraries (like shown above) I'm going to close this issue for now.

Cheers! 😄

**Comment by untone** [comment]
Sorry for late, but i have questions about it.
1. Can i use both optionRenderer and optionComponent in one time?
2. It is possible to pass onInputChange value to optionComponent?

**Comment by bvaughn** [comment]
> Can i use both optionRenderer and optionComponent in one time?

Yes. `OptionComponent` specifies the component class-type used to render the option-wrapper. `optionRenderer` renders the children/content inside of the option. Look [here](https://github.com/JedWatson/react-select/blob/master/src/utils/defaultMenuRenderer.js) to see what I'm talking about.

> It is possible to pass onInputChange value to optionComponent?

No. Input is handled separately, outside of the scope of a single option.

**Comment by untone** [comment]
Oh, react-highlight-words still use babel v5 :(

**Comment by raviteja83** [comment]
@bvaughn How can this be used with v2? CustomOption does not get value of the option. can you suggest a possible way to do the same in v2?

**Comment by bvaughn** [comment]
No idea. Haven't used v2. Sorry!

**Comment by arvinsingla** [comment]
@raviteja83 I used `formatOptionLabel` in v2 to accomplish this.

**Comment by Juliusdz** [comment]
@raviteja83  Here is what I came up to (please share your thoughts if you know how it could be improved):

```
formatOptionLabel = (e) => {
  const fullString = e.label.toLowerCase();
  const input = this.selectRef.state.inputValue.toLowerCase();

  let arr = fullString.split(input);
  
  const index = fullString.indexOf(input);
  const length = input.length;

  // if text match is not at the beginning, it measns text before and after it is not highlited , otherwise, only after it is not highlited.
  if (index > 0) {
    const replace = e.label.substr(index, length)

    arr.splice(1, 0, replace)

    const match = React.createElement('b', {}, arr[1]);
    const beforeMatch = React.createElement('span', {}, arr[0])
    const afterMatch = React.createElement('span', {}, arr[2])

    const container = React.createElement('span', {}, beforeMatch, match, afterMatch);
    return container;

  } else if (index === 0) {
    const replace = e.label.substr(index, length)

    arr.splice(0, 1, replace)
    const match = React.createElement('b', {}, arr[0]);
    const afterMatch = React.createElement('span', {}, arr[1])

    const container = React.createElement('span', {}, match, afterMatch);
    return container;
  }

  return e.label
}

<Select formatOptionLabel={this. formatOptionLabel} />
```

Also added a check if less than 2 chars been typed, don't show suggestions.

**Comment by craigmichaelmartin** [comment]
Thanks @arvinsingla!! Here is @bvaughn's helpful example updated for v2:

```js
import React from 'react';
import Select from 'react-select';
import Highlighter from 'react-highlight-words';

const options = [];

function formatOptionLabel ({label}, {inputValue}) {
  return (
    <Highlighter
      searchWords={[inputValue]}
      textToHighlight={label}
    />
  );
}

function render () {
  return (
    <Select
      options={options}
      formatOptionLabel={formatOptionLabel}
      {...otherProps}
    />
  );
}
```

[Test it out in codesandbox](https://codesandbox.io/s/l76p1pxy39)

**Comment by xseman** [comment]
This should work without `react-highlight-words`
```javascript
function formatOptionLabel ({label}, {inputValue}) {
    const highlighted = option.label.replace(
        new RegExp(labelMeta.inputValue, 'gi'),
        highlighted => `<mark>${highlighted}</mark>`
    );
    return (
        <span dangerouslySetInnerHTML={{ __html: highlighted }} />
    );
};
```
