### ISSUE TITLE
integrating typescript into my project breaks import statements

### ISSUE THREAD

**Issue by aguetkriegerisch** [JedWatson/react-select#5004]
### Discussed in https://github.com/JedWatson/react-select/discussions/5002

<div type='discussions-op-text'>

<sup>Originally posted by **aguetkriegerisch** January 17, 2022</sup>
first of all, in order to use the new documentation examples with typescript, it forces me to use the tsconfig.json file
![image](https://user-images.githubusercontent.com/39163176/149828298-f8a4156b-7281-4e49-b585-89d8ba7cdd42.png)
which also forces me to delete the jsconfig.json file 
![image](https://user-images.githubusercontent.com/39163176/149828581-552b1458-a1b9-4676-b3e7-c1bffa1ca1e1.png)

my project uses react router dom to handle views, and when implementing react-select typescript, imports stop working, for example
![image](https://user-images.githubusercontent.com/39163176/149829159-47e545d9-052d-4a28-bd56-cc16987d8846.png)
![image](https://user-images.githubusercontent.com/39163176/149829247-c6301a59-1ddb-483b-94bd-d54a4e1c66cf.png)

Considering that I don't know typescript, and having read a lot of documentation about the use of paths and baseUrl in the tsconfig.json file, I tried several configurations but none of them worked for me, and it seems very complicated to be able to integrate react-select, but I am very interested in using it for the potential it has in my project.
My question is if there is an easier way to integrate typescript with jsx while resolving conflicts when importing project components. 

The solution that seemed the most logical to me was to change compileroptions.jsx from 'react-jsx' to 'preserve', as I read from here:
https://blog.mgechev.com/2015/07/05/using-jsx-react-with-typescript/
here:
https://www.typescriptlang.org/docs/handbook/jsx.html
and here
https://www.typescriptlang.org/tsconfig#jsx 
</div>

**Comment by Rall3n** [comment]
I will close this issue as being off-topic, because it is neither a problem with nor a question about `react-select`. Your problem seems to be more TypeScript and TS configuration related, and I would recommend you seek out the appropriate channels for those specific topics.

But let me say that even if the examples are written and shown in TypeScript, you can still use those in vanilly JavaScript if you remove the type annotations.
