### ISSUE TITLE
Accessing refs in override components

### ISSUE THREAD

**Issue by Merynek** [JedWatson/react-select#5017]
### Discussed in https://github.com/JedWatson/react-select/discussions/5016

<sup>Originally posted by **Merynek** January 19, 2022</sup>
Hello,
Can you help me with accessing to ref of all components?
I need these refs for getting real (DOM) elements.
I dont know how can I solve this problem.
I tried this but new Menu component what I create is without base innerRef so it could be a problem, but i dont know another options to get it.

```
function Menu<T, IsMulti extends boolean, GroupType extends GroupBase<T>>(props: IMenu<T, IsMulti, GroupType>) {
    const ref= useRef<HTMLDivElement|null>(null);

    return (<components.Menu {...props} innerRef={ref}} />);
}

<Select
    components={{
        Menu: Menu 
    }}
/>

**Comment by Rall3n** [comment]
Please do not open issues for unanswered discussions if the topic of the discussion has not been identified as a bug.

I will close this for now and continue in the discussion.
