### ISSUE TITLE
Rerendering component on onChange causes default value to appear

### ISSUE THREAD

**Issue by andrewhl** [JedWatson/react-select#504]
If I have the following select component:

```
<Select onChange={this.handleChange}
    ref="inputName"
    name="inputName"
    options={inputOptions}
    value="Please select one of the following:"/>
```

And I define the following onChange event:

```
handleChange: function (value) {
    this._someStateValue = value === 'new';
    this.forceUpdate();
},
```

or, for that matter, this:

```
handleChange: function (value) {
    var someStateValue = value === 'new';
    this.setState({_someStateValue: someStateValue});
},
```

Note that both of these approaches causes a component re-render. 

Then, whenever I change the Select, triggering the onChange event, which in turn causes the component to re-render, the default value is displayed and not the value in the select options that I have just selected. Subsequently re-selecting the desired select option will then display it, most likely because react does a diff check on the state of the component and does not trigger a re-render (my best guess).

**Comment by geakstr** [comment]
The same for me

**Comment by geakstr** [comment]
Now I hacked this through setting in onChange function additional field to React state with selected options. And in render component

```
<Select
  value={this.state.selected}
...
/>
```

**Comment by damusnet** [comment]
Your line `value="Please select one of the following:"` should probably be `placeholder="Please select one of the following:"`

**Comment by andrewhl** [comment]
I've had more issues with this. Basically, this select component resets its state whenever this.setState() is called in the parent context. I can't use the component as is. It has to be more intelligent about preserving state.

Note that using placeholder does not resolve this issue.

**Comment by andrewhl** [comment]
I found a workaround: making the `value` of the `Select` a function that checks the state of the component, and the `onChange` another function that updates the state to whatever value is passed along. I don't love this, but it seems to be working. Mind you, I've only tested with a limited use case; I can't yet confirm that it resolved the original issue I posted. I will test against my issue when I get a chance.

    <Select onChange={this.updateValue} value={this.getValue()} />

    ...

    updateValue: function(value) {
        this.setState({value: value});
    },
    getValue: function() {
        if (!this.state.value) {
            return 'Some default text';
        }
    }

**Comment by adrianbon** [comment]
thank you @andrewhl

**Comment by lustrousgorilla** [comment]
Took me forever to isolate the cause of this bug. Thanks for the workaround @andrewhl.

**Comment by dev-tim** [comment]
Thanks @andrewhl!

**Comment by amiteshrai** [comment]
Here is my solution to the problem... without maintaining component state

export class SingleSelect extends Component {
  static propTypes = {
    name: PropTypes.string,
    input: PropTypes.object,
    options: PropTypes.array,
    handleChange: PropTypes.func,
    controlLabel: PropTypes.string,
    selectedValue: PropTypes.string
  }

  onSelectChange = value => {
    let { handleChange } = this.props
    handleChange(value)
  }

  render () {
    const { options, selectedValue, controlLabel } = this.props
    return (
      <FormGroup>
        <Col md={2} lg={2} mdOffset={1} lgOffset={1}>
          <ControlLabel className={'required'} style={{lineHeight: '38px'}}>
            {' ' + controlLabel}
          </ControlLabel>
        </Col>
        <Col md={2} lg={3}>
          <Select
            options={options}
            value={selectedValue}
            onChange={this.onSelectChange}
          />
        </Col>
      </FormGroup>
    )
  }
}

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
