### ISSUE TITLE
Switching browser tabs cause dropdown to focus and re-open

### ISSUE THREAD

**Issue by chrispalka** [JedWatson/react-select#5040]
Hello,

I scoured most of the issues here but couldn't find anything pertaining to what I'm experiencing.

So basically what happens is I select something in a dropdown which closes it, then if I switch to a different browser tab and then switch back, the drop down is open and focused again.

If I change openMenuOnFocus to false, it solves the issue but our clients would like to tab through form fields and have them open when focused.

Any help is much appreciated, thank you for a great package.

**Comment by Rall3n** [comment]
Hello @chrispalka,

I cannot reproduce your problem with the examples on the website.

Could you please follow the issue template you graciously chose to delete and provide a minimal reproducible example using [CodeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-y5jtm)?

**Comment by chrispalka** [comment]
There was no template when drafting a new issue. If I failed to read instructions and follow a template in the README, my apologies. I'll see if I can get a working example and post it here. Thx.

**Comment by chrispalka** [comment]
Ok @Rall3n, creating a new issue now gave me options for bug report and template. 

Below is my codesandbox, only thing I changed was passing openMenuOnFocus={true}. 

https://codesandbox.io/s/react-select-v5-sandbox-forked-ifloo

So basically select something from the drop down, switch a browser tab and switch back and it will re-open. 

It looks like if you leave it focused after selecting an item (and not clicking away from the drop down) it remains focused, and switching tabs and back it re-opens it. This may be by design and it's still focused and switching back to the tab with the focused item re-opens it. Just want to clarify whether this should occur or not.

Thanks for your help.

**Comment by chrispalka** [comment]
Nvm! Looks like it's by design. This was what I was looking for and solved my use case.

`blurInputOnSelect={true}`

Thanks again.
