### ISSUE TITLE
React-Select not showing all options

### ISSUE THREAD

**Issue by DmitrySheklein** [JedWatson/react-select#5043]
Hi, I'm using 
`import Select, { components } from 'react-select';`

But at the first render, it does not show all the options
I don't use `cacheOptions` `loadOptions` only `options` props
[Youtube bug video](https://youtu.be/dLCyLNKPGuc)

**Comment by Rall3n** [comment]
Hello @DmitrySheklein,

would you be so kind and provide a minimal reproducible example using [CodeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-y5jtm) as per the issue template?

**Comment by DmitrySheklein** [comment]
@Rall3n It's all right. Figured it out.Auto-sorting was triggered.
