### ISSUE TITLE
Typescript error when using css={getStyles(...)}

### ISSUE THREAD

**Issue by mmakarios** [JedWatson/react-select#5048]
When I declare the `css` prop passing `getStyles`, as documented in the "Style composition for custom components" section in the Styles page (https://react-select.com/styles), such as `css={getStyles("option", props)}`, I get this type error:

`Type 'CSSObjectWithLabel' is not assignable to type 'InterpolationWithTheme<any>'.`

I can fix it by changing it to `css={getStyles("option", props)} as {}`, but it looks like the types should be matching.

**Comment by Rall3n** [comment]
Hello @mmakarios,

as far as I can see, `InterpolationWithTheme<any>` is a type from `@emotion/core@10.x`. `react-select` uses `@emotion/react@11.x` (rename of `/core`).
Therefore please make sure you are not using different versions of `@emotion/...` packages in your project.

**Comment by mmakarios** [comment]
Thanks, that was it! I had to manually import the correct version `import { css } from "@emotion/react";` and change the attribute declaration to `css={css(getStyles("option", props))}`.

**Comment by mmakarios** [comment]
Just a correction: to actually fix this I had to import `CSSProperties` from `react` and in the component props:

`style={getStyles("option", props) as CSSProperties}`
