### ISSUE TITLE
Opening dropdown via dropdown icon hijacks events (react-datepicker example)

### ISSUE THREAD

**Issue by rkulinski** [JedWatson/react-select#5050]
When using `react-select` with `react-datepicker` it seems that some architectural issue of `react-select` shows up.

Repro:
https://stackblitz.com/edit/react-o6gkep?file=src/App.js

Correct behaviour:
1. Open datepicker.
2. Click on select (not the part with icon on right) and observe datepicker is closed correctly.

Issue:
1. Open datepicker.
2. Click on the part with icon on right of select and observe datepicker is not closed.

I think there's a problem with how this div with icon is designed. Seems to me like it's highjacking events. That doesn't happen for other part of the select and IMO it shouldn't happen here as well.

It was reported here:
https://github.com/JedWatson/react-select/issues/1539
but closed without any resolution.

Versions:
```
    "react": "17.0.2",
    "react-datepicker": "4.6.0",
    "react-dom": "17.0.2",
    "react-select": "^5.2.2"
```

**Comment by rkulinski** [comment]
I think the issue is that dropdown indicator has it's own method for click (onDropdownIndicatorMouseDown). It calls `stopPropagation` which causes e.g. `react-datepicker` to not receive an event. I honestly don't understand why there are two handlers (with different logic inside) for something that seems should be working exactly the same.

**Comment by hushee69** [comment]
For information, the bug isn't reproductible in mobile view for some reason (used this [https://stackblitz.com/edit/react-o6gkep?file=src/App.js](https://stackblitz.com/edit/react-o6gkep?file=src/App.js) while on mobile view and DatePicker does close correctly when select is clicked using the icon on right)

**Comment by rkulinski** [comment]
@hushee69 what do you mean by "mobile view" - mobile device or narrow window? Note that this issue occurs only when you click "icon area" as described in issue.

**Comment by rkulinski** [comment]
Will be fixed in https://github.com/JedWatson/react-select/pull/5138
