### ISSUE TITLE
Typescript Creatable Select not passing through generic for GroupType

### ISSUE THREAD

**Issue by Ampatte2** [JedWatson/react-select#5080]
Foremost the Typescript support is top notch, thank you. 

There was only one issue with `Creatable` select that it is not passing through the generics for `GroupType` even though it exists on the props. 

### Current

<img width="1152" alt="Screen Shot 2022-02-27 at 9 24 33 AM" src="https://user-images.githubusercontent.com/29719870/155890727-3b7e33e9-2906-49d0-9853-a2a60e05b97b.png">

### Proposed

<img width="1236" alt="Screen Shot 2022-02-27 at 9 24 22 AM" src="https://user-images.githubusercontent.com/29719870/155890750-afa6a125-4b0c-4b3b-b2fa-0c33dfbe6313.png">

**Comment by Methuselah96** [comment]
It looks like you're using `@types/react-select` which was [deprecated in v5](https://react-select.com/upgrade#from-v4-to-v5) in favor of the types that we now package with `react-select`.
