### ISSUE TITLE
allow users to input more custom functions

### ISSUE THREAD

**Issue by sarahbkim** [JedWatson/react-select#509]
First of all, thanks for making this, it saved me a lot of time and effort! I am using react-select for a project at work, which uses react + flux. As the UI required a bit more from the select box than its typical use-cases, I used es6 to extend the class and needed to add a number of custom functions overriding the default selectValue, popValue, etc. functions. 

I made some changes to my local copy of the project to include these functions as props and edited some of the functionality like so: 

```
handleKeyDown (event) {
    if (this.props.disabled) return;
    switch (event.keyCode) {
      case 8: // backspace
        if (!this.state.inputValue && this.props.backspaceRemoves) {
          event.preventDefault();
          if(this.props.customPopValue) {
            this.props.customPopValue();
          else {
            this.popValue();
          }
        }
      return;
```

I'd like to know if there are better ways going about this and if you've given any thought to allowing further customization of this module without the user going ahead and ripping its guts out a bit?

**Comment by gwyneplaine** [comment]
As of 2.x.x we now have multiple points for configuring the functionality of Select. 

Please see the components section of our docs for details 
https://react-select.com/components 

In regard for the actual case enumerated here, value selection and removal are pieces of logic that are quite core to the select, so we generally don't have any plans to make this easy. Though more often than not we've found that users tend to want to add functionality either adjacent to or on top of these core pieces of logic. In such cases, the following documentation may be helpful 

https://react-select.com/advanced
https://react-select.com/props

Closing this issue, if for some reason you feel that what I've described above doesn't correctly address your problem, please feel free to create a new issue. Mostly doing this for clarity ad to reduce our issues list down to a sane and relevant number of actionable tasks.
