### ISSUE TITLE
Loosing styles when using inside a #shadow-root (Shadow DOM)

### ISSUE THREAD

**Issue by hcasatti** [JedWatson/react-select#5096]
## Are you reporting a bug or runtime error?

Using [react-shadow](https://www.npmjs.com/package/react-shadow) and other methods to mount a Select inside a Shadow DOM, I loose every style of the component.

_NOTE: This example uses react-shadow, but the problem happens with standard Shadow DOM too_

```
const Root = require('react-shadow').default;

<Root.div>
  <ReactSelect options={[
    { value: 'chocolate', label: 'Chocolate' },
    { value: 'strawberry', label: 'Strawberry' },
    { value: 'vanilla', label: 'Vanilla' },
  ]}
  />
</Root.div>
```

[CodeSandbox with the issue on ReactShadow](https://codesandbox.io/s/react-select-v5-sandbox-forked-4ftqkn?file=/example.js)

[CodeSandbox with the issue using standard Shadow DOM](https://codesandbox.io/s/react-select-v5-sandbox-forked-3gonij)

**Comment by Rall3n** [comment]
@hcasatti 

`react-select` uses `emotion` for styling. According to the documentation of `react-shadow` you should import from `react-shadow/emotion` for `emotion` support.

**Comment by hcasatti** [comment]
Thanks @Rall3n . What about standard Shadow DOM [like this](https://codesandbox.io/s/react-select-v5-sandbox-forked-3gonij) ?
How can I do in that case ?

**Comment by Rall3n** [comment]
For this please see https://github.com/JedWatson/react-select/issues/3680#issuecomment-924248517.

I will close this issue now as it seems to be resolved.
