### ISSUE TITLE
Can't access SelectContainer's ref/innerRef

### ISSUE THREAD

**Issue by florinpavel22** [JedWatson/react-select#5099]
Hi, I have this custom SelectContainer component.

```
import React, { useCallback } from 'react';
import { components } from 'react-select';

export function SelectContainer(props) {
  const { selectProps: { controlRef }, innerRef, children } = props;

  const setRef = useCallback((node) => {
    innerRef(node);
    controlRef(node);
  }, [ innerRef ]);

  return (
    <components.SelectContainer { ...props } innerRef={ setRef }>
      { children }
    </components.SelectContainer>
  );
}
```

And I cannot access its ref. Actually I am not sure if it's available, if not, would be nice to have.

**Comment by Rall3n** [comment]
@florinpavel22

Please do not open issues for unanswered discussions if the topic of the discussion has not been identified as a bug.

I will close this for now and continue in the discussion.
