### ISSUE TITLE
Where is the onMenuInputFocus prop?

### ISSUE THREAD

**Issue by rgcejudo** [JedWatson/react-select#5117]
Hi!

I need to create something like this https://codesandbox.io/embed/m75wlyx3oy , but I noticed that onMenuInputFocus prop is missing on version 5.2.2.

How could I get that behavior with this version?

Thank you for your support.

**Comment by Rall3n** [comment]
Hello @rgcejudo,

`onMenuInputFocus` is not and never was a prop of the `Select` component.

The example you referenced is actually mine. `onMenuInputFocus` is a custom prop never used internally by the `Select` component, only through custom components.

> How could I get that behavior with this version?

Same as the example you referenced. But if you are using TypeScript, then you might want to additionally look into [how to define custom properties](https://react-select.com/typescript#custom-select-props).

-----

I will close this issue as not a problem with functionality of `react-select`, but instead being a question about a customized implementation.
