### ISSUE TITLE
Update `peerDependencies` to include React 18

### ISSUE THREAD

**Issue by nil4** [JedWatson/react-select#5129]
React 18 is now available: https://reactjs.org/blog/2022/03/29/react-v18.html

Trying to use react 18 together with `react-select` v5.2.2 (latest version) currently leads to a dependency conflict:

```cmd
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@0.0.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   dev react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from react-select@5.2.2
npm ERR! node_modules/react-select
npm ERR!   dev react-select@"5.2.2" from the root project
```

This seem to be related to the `peerDependencies` defined here:

https://github.com/JedWatson/react-select/blob/2d3d6afe18421ea5b6c3f8f0db479ad323c35639/packages/react-select/package.json#L29-L31

Would it be possible to publish a new version which allows react 18 too?

**Comment by alemarra89** [comment]
Same problem here
