### ISSUE TITLE
dependency management a la npm is hard, even harder than naming things and cache invalidation

### ISSUE THREAD

**Issue by giogonzo** [JedWatson/react-select#516]
I think [this](https://github.com/JedWatson/react-select/blob/65ec63ef0ff9961b6111de68d5ddd6fc0afb275f/package.json#L37) is dangerous in some non trivial way now that react `0.14` is out of rc

Tests for my own (shrinkwrapped!) libs and apps (in)directly requiring `react-select` started failing exactly when react 0.14 came out two days ago, both on our machines and CI.
Failures are of course due to two different versions/instances of react being pulled in (oh irony: react 0.14 introduces a warning for this)

This #506 would probably be enough to not cause any harm to anyone

dependency management a la npm (`@2.x`) is hard, even harder than naming things and cache invalidation

**Comment by JedWatson** [comment]
Good point. Ugh. Maybe the best option is to publish a new 0.6.x version with the React dependency `^0.13.3`, leaving react-select@0.7.x to depend on React 0.14.

**Comment by giogonzo** [comment]
possible solutions on my side:
- pin all my deps on `react-select` to `0.6.3` (last with a `0.13.x` peer dependency). I just tried this and it is still not working, probably due to `react-input-autosize@^0.6.x` (https://github.com/JedWatson/react-input-autosize/blob/master/package.json#L24)
- switch to npm 3 (and thus avoid peerDependencies auto install), fix all my package.json/shrinkwraps accordingly
- switch to react 0.14 everywhere (and probably struggle with many other libs not supporting it)

I don't consider any of the above feasible, except maybe for the first one (although temporary)

On your side, what you propose seems reasonable, except you'd probably have to do the same for more modules (see `react-input-autosize` above), and maintain coherent fixed deps "recursively"

Still not sure who to blame: it's mainly npm @ 2 , peerDependencies and shrinkwrap not playing well together..

**Comment by giogonzo** [comment]
Also, is there a documented reason why the `"react": "^0.13.3 || ^0.14.0-rc1"` peerDependency causes npm trying to install `0.13.3` until 2 days ago and `0.14.0` now? couldn't find it in npm docs..

**Comment by gcanti** [comment]
> Also, is there a documented reason why the "react": "^0.13.3 || ^0.14.0-rc1" peerDependency causes npm trying to install 0.13.3 until 2 days ago and 0.14.0 now? couldn't find it in npm docs..

It seems that NPM doesn't recognize semvers that end with '*-rc' (i.e. release candidates) https://github.com/npm/npm/issues/8854

**Comment by JedWatson** [comment]
@giogonzo has this settled down now that 0.14 is out and relatively stable / supported? hopefully for the next version bump there'll be a less painful way to deal with this.

I'm tempted to close the issue because it's a transient problem, let me know what you think first though.

**Comment by giogonzo** [comment]
still didn't have the chance to update to `0.14` on affected projects, but yes, everything should be ok after the switch

Closing for now, thanks!

**Comment by JedWatson** [comment]
:+1:
