### ISSUE TITLE
Warning when adding to tags with same name

### ISSUE THREAD

**Issue by mordonez-me** [JedWatson/react-select#517]
After trying to add a tag with the same name the following message appear on console.

Warning: flattenChildren(...): Encountered two children with the same key, `.0:$asdasd`. Child keys must be unique; when two children share a key, only the first child will be used.

**Comment by agoransson** [comment]
The way I get around this is setting the unique key for the items using the `valueKey` property.

Here's an example of how I use it.

```
<Select
  name="segment"
  value={this.state.formData.segment}
  valueKey="uuid"
  labelKey="name"
  placeholder="Välj segment"
  options={this.state.segments}
  onChange={this._onSegmentChange} />
```

**Comment by kirubasankars** [comment]
I having the same issue 

"warning.js:45 Warning: flattenChildren(...): Encountered two children with the same key, `.$option-59648`. Child keys must be unique; when two children share a key, only the first child will be used."

I have tried with valueKey, no luck.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
