### ISSUE TITLE
DropdownIndicator doesn't work well on mobile browsers

### ISSUE THREAD

**Issue by phpstudyone** [JedWatson/react-select#5171]
I'm using the DropdownIndicator to change the style of the Dropdown area, but I'm finding that on mobile browsers, it's a bit buggy. Doesn't work very well.   

Load the component directly, you cannot click the Dropdown area to open or close the drop-down box.

Hardcoded into components.DropdownIndicator, the dropdown can be opened or closed by clicking on the Dropdown area.

(can be emulated with chrome Toggle device toolbar )

**Here is the code that reproduces the above problem:**  https://codesandbox.io/s/codesandboxer-example-forked-ui2zx8?file=/example.tsx

1.  click the "Open In New  Window" button 

![image](https://user-images.githubusercontent.com/11455285/165735887-a22104d1-bcab-4f1a-8c69-f635e54aaecd.png)

2.  F12 switch to mobile device

![image](https://user-images.githubusercontent.com/11455285/165735984-1b9f35a4-37c2-4e7d-b744-c4c356f85d79.png)

3.  click the Dropdown area.

![image](https://user-images.githubusercontent.com/11455285/165736032-ec06d4a1-59d7-40aa-bb3f-4c97dac872d6.png)

**Comment by cheechoo28** [comment]
I have the same problem

**Comment by cheechoo28** [comment]
@phpstudyone 
I have found a solution to this problem. 
You should add the "pointer-events: none" property to the indicatorsContainer class and it will work

**Comment by phpstudyone** [comment]
@cheechoo28 Thanks for your help.  add the "pointer-events: none" property is indeed a working solution.

**Comment by halhinaty** [comment]
use an **useState** for **isMenuOpen** and add the below as prop on the react-select:

    menuIsOpen={isMenuOpen}
