### ISSUE TITLE
Enter is swallowed when searchable is false

### ISSUE THREAD

**Issue by ptim** [JedWatson/react-select#518]
I'm using v0.7.0, and find that:
- when `searchable` is false, and
- I've focussed a field
- hit the down arrow to highlight an option
- hit enter to select the option
- hit enter on the closed Select, 

...that the field doesn't budge: the form is not submitted, and 

The select is inside a form element, and the form is submitted as expected if `searchable` is true.

Here's my Select:

```
<Select className="form-control"
  name="gender"
  placeholder="Gender"
  options={options}
  value={this.props.patient.gender}
  onChange={this.handleGenderChange}
  searchable={false}
/>
```

I found this related issue which was previously merged: https://github.com/JedWatson/react-select/issues/212

Couldn't immediately fathom why, looking at the source...

Thanks for the awesome component :)

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
