### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by jared-leddy** [JedWatson/react-select#5182]
React-Select: v5.2.2

## Problem
Data Structure: Array of Objects, With Field being an array of objects that have key/value pairs. 
Field Value Structure: This is an SPFx webpart, which is at the last piece. Once this renders, we can post it to the correct dataset and be done. In the bottom right corner, there is an example of the HTML structure. 

This HTML structure is necessary because the users need to search all three of the fields used to build out the HTML. 

![example-webpart](https://user-images.githubusercontent.com/57743183/167434707-d95dc83a-8661-431d-b053-315be65ec82f.jpeg)

Using React's new state to update the values. Which works like a charm, until we look at the rendering of values. The correct number of options are being shown, but the text/html isn't rendering.

Example:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/57743183/167433505-05e7336f-cbe5-4dc6-877a-7c227f2a5887.png">

**Comment by jared-leddy** [comment]
Problem Update:
I'm getting the results now, but the style is crap. How can this be fixed?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/57743183/167459572-6bc428be-3ce8-4ceb-b57f-c6ec1722a571.png">

**Comment by Rall3n** [comment]
Hello @jared-leddy,

I apologize for the late reply.

If your data structure does not use `{ label, value }` then you should set the `getOptionLabel` and `getOptionValue` props accordingly. If you want to use a custom design for your options, either use the `formatOptionLabel` prop or use a custom `<Option>` component. Both should return proper **JSX**. Styling can be adjusted using the provided [styling framework](https://react-select.com/styles). 

-----

I will close this issue as it is not a technical issue with the library, but a problem with understanding customization. Next time please open a discussion if you have questions regarding implementation/customization.
