### ISSUE TITLE
How to do dual Selects, contents filtered by the selection of the other?

### ISSUE THREAD

**Issue by jefftune** [JedWatson/react-select#519]
I have a problem which involves two Selects, both are filled with "asyncOptions".

I am requesting within documentation or example for dual Selects which its contents are dependent upon selection of the other.

Simplifying the need. Select A is "food types", and Select B is "food products".
Upon component loading, both Select A and Select B are filled with all possible values.

If user chooses Select A value, then that should filter Select B values.
And vise versa, choosing a value in Select B should filter Select A values.

Recommendations on how I should approach this problem.

I tried the following:
Upon onChange() of Select A, which calls the forceUpdate() of Select B, hoping it calls render of Select B, which then it regenerates "asyncOptions" assigned to Select B. However, but calling forceUpdate() of "Select B" did not call its "asyncOptions".

**Comment by jefftune** [comment]
Is there a way a re-draw a react-select if one dynamically modify contents after options after initial rendering?

**Comment by eventhough** [comment]
@jefftune I'm dealing with the same challenge. I have two select boxes, one is dependent on the other. When the user updates Select A, I would like Select B to automatically filter down based on the value of Select A.

What I'm doing right now is setting the filterOptions prop in Select B to filter based on the value of Select A, but it only fires when the user begins to type. What I need is just a manual way to force a filter update.

Another issue that is similar: #372

**Comment by crudexec** [comment]
@eventhough @jefftune im dealing with this same issue was there any resolution? I would love to know. thanks

**Comment by akonyushevskiy** [comment]
Hey, I have the same issue, anybody found a solution?

**Comment by ebonow** [comment]
Greetings everyone, 

It is likely this was initially created when react-select v1 was around and as such I would close this issue, but I thought to answer this question with the most recent version of react-select (3.1.1) or at least version 2...

[Here is a codesandbox demonstrating how this can be done.](https://codesandbox.io/s/react-select-async-dependency-lookups-ecefm)

While the example is fairly rudimentary, the gist is to enable the second lookup once the first has been selected. The load options would then likely take two parameters (the type and the input string) which would return from the api whatever results came back, which can then be filtered. Closing this now, but open to resolving any questions or concerns.
