### ISSUE TITLE
closeMenuOnSelect doesn't work

### ISSUE THREAD

**Issue by ivanafanasyeu** [JedWatson/react-select#5192]
With a custom components.ValueContainer it doesn't work

```jsx
const ValueContainer = ({ withIcon, className, ...props }) => (
	<components.ValueContainer
		className={`${className ? className : ""} ${withIcon ? css.withicon : ""}`.trim()}
		{...props}
	>
		{withIcon && <SearchIcon />}
		{props.children}
	</components.ValueContainer>
);
```

```jsx
	<Select
				className={`${css.select} ${error ? css["select-error"] : ""}`.trim()}
				classNamePrefix={"r-select"}
				name={name}
				options={options}
				components={{
					Option,
					DropdownIndicator,
					IndicatorSeparator: () => null,
					// MultiValue,
					ValueContainer: props => <ValueContainer withIcon={withIcon} {...props} />,
				}}
				id={id}
				instanceId={id}
				closeMenuOnSelect={false}
				blurInputOnSelect={false}
				{...props}
			/>
```

**Comment by Rall3n** [comment]
Hello @ivanafanasyev,

please be so kind and provide a minimal reproducible example using [CodeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-y5jtm) as requested in the issue template.

**Comment by ivanafanasyev** [comment]
@Rall3n it's not even working on codesandbox, when I add components={{}}
<img width="1249" alt="Screenshot 2022-05-18 at 13 44 29" src="https://user-images.githubusercontent.com/25664253/169031259-61feafb4-0d1e-408d-bc2b-7b05d285c930.png">
x

**Comment by Rall3n** [comment]
@ivanafanasyev Even so, please provide the example so we can reproduce the issue you encounter.
