### ISSUE TITLE
Typescript error on options props when wrapping the Select component v5

### ISSUE THREAD

**Issue by emilie-t-ledn** [JedWatson/react-select#5208]
If I fork the example in here https://react-select.com/typescript for "Wrapping the Select component" and use the options from the Home page example, there is a TS error on the options prop. The fiddle sandbox is using TS v4.5.5, but I have the same error in my project with v4.6.3

```
(property) options?: OptionsOrGroups<Option, Group>

Array of options that populate the select menu
Type 'readonly ColourOption[]' is not assignable to type 'OptionsOrGroups<Option, Group>'.
  Type 'ColourOption' is not assignable to type 'Option | Group'.
    Type 'ColourOption' is not assignable to type 'Group'.
      'Group' could be instantiated with an arbitrary type which could be unrelated to 'ColourOption'.ts(2322)
Select.d.ts(180, 5): The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & Omit<Pick<Props<Option, IsMulti, Group>, "aria-errormessage" | "aria-invalid" | "aria-label" | ... 27 more ... | "form"> & InexactPartial<...> & InexactPartial<...>, StateManagedPropKeys> & Partial<...> & StateManagerAdditionalProps<...> & RefAttributes<...>'
```

https://codesandbox.io/s/codesandboxer-example-forked-ebwkr3?file=/example.tsx

Not sure I understand why I get an error since the options are properly formatted and I'm using the typing from the package. Could there be an issue with the typing?

Thanks

**Comment by emilie-t-ledn** [comment]
Thanks for the quick response!
This is a reusable Select for a design system, so I don't know within the component which type of option will be used. How can I type this then?

**Comment by Methuselah96** [comment]
In that case you can't set the `options` prop within the reusable Select, you need to set it where the reusable Select is being used. Try [this](https://codesandbox.io/s/codesandboxer-example-forked-s21zjn?file=/example.tsx).

**Comment by emilie-t-ledn** [comment]
Thanks again for your support. I already had this already in some unit test, but I realized with your example that I was missing a proper value prop.
