### ISSUE TITLE
Using react-select with webpack instead of browsify

### ISSUE THREAD

**Issue by ohmirocks** [JedWatson/react-select#521]
Hi,
i am using webpack for bundling in my application. I tried importing the react-select only the JS is getting bundled and the CSS is not. Is there a example which i can refer how to use this with webpack

Thanks
Om

**Comment by maxcnunes** [comment]
Hi,

Include the css loader in your webpack, for example:
```js
module.exports = {
  module: {
    loaders: [
      { test: /\.css$/, loader: "style!css" },
    ]
  }
};
```

And in your react component you can require the css file from `react-select` module:
```js
require('react-select/dist/default.css');
```

**Comment by captainill** [comment]
thanks, @maxcnunes. This should really be in the docs.

**Comment by onedesert** [comment]
I'm using webpack and l'm importing the scss filed to be able to reset som select.scss vars

**Comment by dyyylan** [comment]
Can you provide any more details on this? I'm not too familiar with webpack and with the above code, it's telling me it can't find the default.css in `/path/to/my/component.js`

**Comment by FutureKode** [comment]
@dyyylan 

``` require('react-select/dist/default.css'); ``` isn't the correct path in the latest few versions. Check the path to the css.

**Comment by dyyylan** [comment]
Ok, I updated the path (currently `react-select/dist/react-select.css`). Now I am getting this error:
`Module not found: Error: Cannot resolve module 'style' in /path/to/component.js`

If I look at the page it says something about webpack-style-loader?

**Comment by dyyylan** [comment]
Never mind, this is a waste of time thanks for your help.

I'm just going to copy/paste the css file into my project's assets folder

**Comment by maxcnunes** [comment]
@dyyylan You should have installed `css-loader` and `style-loader`

```
npm install css-loader style-loader
```

But if you are not interested learning how to use webpack then is much easier running it without webpack.

**Comment by dyyylan** [comment]
Ok, thanks for the help.

**Comment by Kure69** [comment]
Thanks for explaining :)
