### ISSUE TITLE
Multi select label show only text

### ISSUE THREAD

**Issue by krngd2** [JedWatson/react-select#5213]
### Discussed in https://github.com/JedWatson/react-select/discussions/5210

<div type='discussions-op-text'>

<sup>Originally posted by **krngd2** May 30, 2022</sup>
Hello, 

I am trying to show the number of items selected in the label.
There seems to be no way as components MultiValue, MultiValueContainer, MultiValueLabel all are looping for each value. I just want to show some text. How can I do it ?  </div>

I did not get any reply in the discussions. So I made it into an Issue

**Comment by Rall3n** [comment]
Hello @krngd2,

please do not open issues for discussions that
1. are clearly not technical problems with the library, and
2. do not get an answer.

Discussions should only be promoted to issues if a problem has been identified that needs a change in the codebase.
