### ISSUE TITLE
Selectable value prop

### ISSUE THREAD

**Issue by benquinteros** [JedWatson/react-select#5222]
### Discussed in https://github.com/JedWatson/react-select/discussions/5221

<div type='discussions-op-text'>

<sup>Originally posted by **benquinteros** June  9, 2022</sup>
Current behaviour when clicking opens the drawer, would be nice if there was a prop we could set so we could doubleclick and edit current values text, especially for Creatables :)</div>

**Comment by Rall3n** [comment]
Please don't open issues for feature request discussions just to let it gain attention.

I will close it now. Discourse will continue in the discussion if needed.
