### ISSUE TITLE
react-select.com down

### ISSUE THREAD

**Issue by Orololuwa** [JedWatson/react-select#5229]
the documentation page is down

**Thanks for using react-select!**

If you are going to ask a question or want to propose a change or a new feature, then please don't file an issue for this.
Questions and feature requests have their own place in our discussions section.

## Are you reporting a bug or runtime error?

Please include a test case that demonstrates the issue you're reporting!

This is very helpful to maintainers in order to help us see the issue you're seeing.

Please note we are currently only directing our efforts towards the current major (v5) version and beyond.

We understand this might be inconvenient but it is in the best interest of supporting the broader community and to sustain the `react-select` project going forward.

To report bugs against react-select v5 please fork the following code-sandbox:
https://codesandbox.io/s/react-select-v5-sandbox-y5jtm

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by Methuselah96** [comment]
Seems to be working for me.

**Comment by Orololuwa** [comment]
![316F64D5-783A-43FF-9943-84BC9BE89E70](https://user-images.githubusercontent.com/67964734/174101161-cba8c93f-2ff5-4a4d-b9bc-1f00ff774f5b.png)

**Comment by Methuselah96** [comment]
Have you tried accessing it using a different network connection?

**Comment by Orololuwa** [comment]
Seems like it's restricted in my location.. I was able to access it with a vpn though

**Comment by Methuselah96** [comment]
Got it, sounds like there's nothing that we can do to resolve that, so closing this for now, let us know if we can help you with anything.
