### ISSUE TITLE
First option selected is bigger than orthers

### ISSUE THREAD

**Issue by MarcHbb** [JedWatson/react-select#5231]
I think the title is quite explicit, this is what happen when I select the first option
When I select more, the size of the others are perfect.
Even if I remove every options then selected one, it still happen

<img width="490" alt="Capture d’écran 2022-06-17 à 15 33 27" src="https://user-images.githubusercontent.com/15633836/174309264-bf723910-df1d-4f83-9e0f-6aeed35f7288.png">

Demo :
https://codesandbox.io/s/frosty-dan-rkughf?file=/src/App.js

**Comment by manjushsh** [comment]
@MarcHbb I guess both have same issue
https://github.com/JedWatson/react-select/issues/5205

**Comment by Rall3n** [comment]
Thx @manjushsh.

Closing as being a duplicate of #5205.
