### ISSUE TITLE
UI issue when using the makeAnimated()

### ISSUE THREAD

**Issue by Alejandro-Marco** [JedWatson/react-select#5251]
The select item container is longer that its content when using the makeAnimation() in components

Expected Behavior:
<img width="599" alt="1" src="https://user-images.githubusercontent.com/78371908/176674617-405202ec-dc93-4ed4-a615-d8ae40605621.png">

Actual Behavior
<img width="581" alt="5" src="https://user-images.githubusercontent.com/78371908/176674848-c362c133-1c47-443b-9105-ca130a2ad733.png">

Steps to reproduce:
1) Access https://react-select.com/home#animated-components
2) Remove all added items and type "O" ( any other character would also do as long you can select any item )
<img width="641" alt="2" src="https://user-images.githubusercontent.com/78371908/176675112-241fe15f-c18c-4c21-aa3d-a689d8cae7ac.png">
3) Select any item, the container of the item is longer than the content 
<img width="607" alt="3" src="https://user-images.githubusercontent.com/78371908/176675205-8ca667f9-b5e7-4907-9f00-8f694429898e.png">

This issue only occurs on the first item, any other item added after does not experience this.

Adding another item:
1) <img width="589" alt="4" src="https://user-images.githubusercontent.com/78371908/176675320-28c8419b-eac5-4d9e-a44a-e8d2e138a663.png">
2) <img width="581" alt="5" src="https://user-images.githubusercontent.com/78371908/176675342-838c5cb4-b3ba-4589-933b-fb0c5da8b828.png">

The issue only occurs when using makeAnimated(), so not that big of an issue. Really just wanted to make use of the animation.

**Comment by vicnguyenqt** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/93513978/189339541-3d9ae5c5-293c-481e-b6cc-89c824e61794.png)

**Comment by jorge30fm** [comment]
I'm having this same issue. How can it be fixed?

**Comment by Alireza17224** [comment]
Same issue !

**Comment by lukebennett88** [comment]
Hi @Alireza17224, can you confirm that you're still seeing this issue? What version of react-select are you using? It _should_ be fixed in 5.5.2.

**Comment by Alireza17224** [comment]
Hi yes ! I am using this version
react-select: "^5.4.0",
I will update it to version 5.5.2
Thank you very much

**Comment by Alireza17224** [comment]
> Hi yes ! I am using this version react-select: "^5.4.0", I will update it to version 5.5.2 Thank you very much

FIXED BY UPDATING !
