### ISSUE TITLE
Use ReactDOM from window/global scope

### ISSUE THREAD

**Issue by harlow** [JedWatson/react-select#526]
Facebook's install page (https://github.com/facebook/react#installation) recommends including both React and ReactDOM from CDN.

```js
<!-- The core React library -->
<script src="https://fb.me/react-0.14.0.js"></script>
<!-- The ReactDOM Library -->
<script src="https://fb.me/react-dom-0.14.0.js"></script>
```

By using this style we don't need to vendor `ReactDOM` directly. Would it make sense to do this:

```js
var ReactDOM = (typeof window !== "undefined" ? window['ReactDOM'] : typeof global !== "undefined" ? global['ReactDOM'] : null);
```

Here:
https://github.com/JedWatson/react-select/blob/master/dist/react-select.js#L73

Thoughts?

**Comment by twe4ked** [comment]
:+1:

**Comment by wavejumper** [comment]
Another :+1:  - would allow this library to work for other compile to js languages (eg clojurescript)

**Comment by TigerC10** [comment]
Count that +1 for :thumbsup: - this killed react-select in my build system since I'm not leveraging browserify or requirejs (yet).

**Comment by sobrinho** [comment]
Another :+1:, the component is broken on browsers without module loaders.

**Comment by bavardage** [comment]
(+1)

**Comment by l4u** [comment]
:+1: When react-select is used with Bower and react-rails, it shows `Error: Cannot find module 'react-dom'`. When we can reuse window.ReactDOM, it works.

**Comment by dbkaplun** [comment]
+1

**Comment by twe4ked** [comment]
@JedWatson is there a reason not to do this?

**Comment by twe4ked** [comment]
Thanks, I'll give this a go now!

**Comment by JedWatson** [comment]
@twe4ked had to figure out the right way to do it without interfering with the other build processes and target environments. Done now, and I've added an updated usage example in `examples/src/standalone.html`

**Comment by twe4ked** [comment]
Actually I'm using bower so I'm not sure this will fix it for me. I'll have a look now.

**Comment by JedWatson** [comment]
I'll have to publish a new version first, but you can test it by downloading the repo directly from npm and dropping the `dist` folder into your project (this is effectively what bower does anyway)

**Comment by sobrinho** [comment]
Thanks! \o/

**Comment by mockdeep** [comment]
Has this been released to bower yet? We just tried to plug it in alongside `react-rails` and got the same error as @l4u above.

**Comment by l4u** [comment]
@mockdeep Use the build at or after b2afb88

**Comment by mockdeep** [comment]
@l4u are you including it in your project assets or using `rails-assets`? We actually just ended up setting up `browserify-rails` and will probably move to using the npm package.

**Comment by l4u** [comment]
@mockdeep we have to wait for a new release v1.0.0-beta6 before we can use it with rails-assets (bower). Alternatively you can get the dist/react-select.js at b2afb88

**Comment by bondarevpavel** [comment]
Thanks for fixing this!

**Comment by atroche** [comment]
Thanks! I'm on master too, and it's working well. Any ETA on when anyone can cut a new release? This PR is depending on it: https://github.com/cljsjs/packages/pull/273

But no rush =)

**Comment by twe4ked** [comment]
I've got a feeling this is waiting on #568.

**Comment by atroche** [comment]
@JedWatson any chance of a quick beta release, just so we can use this fix on a release?

**Comment by moggyboy** [comment]
@l4u can you please elaborate on how you got this working in Rails?

**Comment by l4u** [comment]
@moggyboy The patch has been applied to v1.0.0-beta6 only. If you use 0.9.x, you've to edited that `ReactDOM` line.

**Comment by moggyboy** [comment]
@l4u Thank you - I noticed you'd already answered above and deleted my comment.
