### ISSUE TITLE
closeMenuOnSelect not working as expected with <label />

### ISSUE THREAD

**Issue by errmayank** [JedWatson/react-select#5272]
Hi, thanks for creating this library! I'm currently having a problem while creating a dropdown, where i'm trying to check/uncheck the input if someone clicks the list item, i'm using `<label />` & `<input  />` combo and i want to keep the list open when someone is selecting, but even after setting the `closeMenuOnSelect` prop to `false` it's not working as expected, the only time it works is when i directly click on the input checkbox

Steps to reproduce:

1. Go to https://codesandbox.io/s/react-select-input-label-w2cp2t
2. Open the dropdown and click directly on the checkbox, it will work as expected
3. Now click on the title of the list item, dropdown will close without even checking the box

**Comment by Rall3n** [comment]
Hello @errmayank,

this issue was already filed on this repository (#4666).

Closing as duplicate.
