### ISSUE TITLE
Cannot update value for multi select

### ISSUE THREAD

**Issue by muckee** [JedWatson/react-select#5278]
Values don't update when changing the value of the array passed to the `values` property programatically.

I have an array of objects stored in state (managed by a reducer), defined like this:
```
[
    {
        ...
        name: 'layer one',
        conflicts: [],
        ...
    },
    {
        ...
        name: 'layer two',
        conflicts: [],
        ...
    },
    {
        ...
        name: 'layer three',
        conflicts: [],
        ...
    },
    ...
]
```

The conflicts arrays are empty by default. A select field is rendered for each of these objects and the options are equivalent to the value of the `name` field for each other layer.

So when a user interacts with layer one's select input, the available options are 'layer two' and 'layer three'. If, for example, a user were to select 'layer two', then the reducer would add 'layer two' to the conflicts array of the first item... and it would also add 'layer one' to the conflicts array of the second item.

To clarify, after selecting 'layer two' on the first object's select input, the state is updated as follows:

```
[
    {
        ...
        name: 'layer one',
        conflicts: [
            'layer two',
        ],
        ...
    },
    {
        ...
        name: 'layer two',
        conflicts: [
            'layer one',
        ],
        ...
    },
    {
        ...
        name: 'layer three',
        conflicts: [],
        ...
    },
    ...
]
```

It seems like the value field is being ignored and the component is following its default behaviour - the options selected *do* appear within the target input, but the values I'm assigning to the `value` prop are ignored.

When I select 'layer two' as an option from the dropdown list of layer one, I can see in the console that the value being assigned to layer two's select input value prop is:

```
value=[
    {
        label: 'layer one',
        value: 'layer one',
    },
]
```

But no values are ever assigned and selected options are only ever rendered on the input that is the target of the click.

There is no state management issue as I can render the values of the updated state as strings on the frontend, they just aren't passed to the Select element.

**Comment by glipR** [comment]
@muckee is there any particular reason this was closed? I'm seeing a very similar issue (updating the value prop programmatically is not showing in the frontend, not a state issue as I can render the changed values as strings on the frontend)

**Comment by muckee** [comment]
@glipR to be honest, I'm not sure why I closed this as I don't think I ever found a solution.

I ended up creating a bespoke select component, instead.

I'm pretty sure that MUI's Select component handles this behaviour properly, too.

**Comment by glipR** [comment]
@muckee appreciate the thorough response. I actually did some more testing and found that my particular issue (and possibly yours), is that setting `value=null` on the select component preserves the previous value. 

Setting the `value=[]` (even for `isMulti=false`) fixed the issue, and actually cleared the select component. Hopefully anyone else coming across this issue finds that useful :)
