### ISSUE TITLE
TS isMulti type confusion

### ISSUE THREAD

**Issue by Xuroth** [JedWatson/react-select#5279]
## Are you reporting a bug or runtime error?
Possible bug. Using TS, the `isMulti` prop seems to only expect `false | undefined`, but to enable multiple select, this prop should accept `true` (based on my understanding - which may be incorrect). In the docs, `isMulti` prop uses type `IsMulti` (which extends `boolean` but seems to only allow the aforementioned values, not `true`).

I'm willing to admit this may be a usage issue, though I've been unsuccessful getting this to work.

```jsx
type SelectOption = { label: string; value: string };
// ...
<ReactSelect<SelectOption>
          options={options}
          autoFocus
          menuIsOpen
          isSearchable
          isClearable={false}
          isMulti={isMulti} // this is passed from the wrapper component, which is used directly in a form.
          onChange={handleSelectChange}
          controlShouldRenderValue={false}
          placeholder={placeholder}
          components={{
            SelectContainer: SelectComponent,
            Control: ControlComponent,
            IndicatorSeparator: null,
            Menu: MenuComponent,
            DropdownIndicator: null,
            Input,
            Placeholder,
            MenuList,
            ValueContainer,
          }}
        />
 ```
The specific error for the issue is:
`Type 'true | undefined' is not assignable to type 'false | undefined'`
`Type 'true' is not assignable to type 'false'`

Side note:  adding a `// @ts-ignore` above the isMulti prop suppresses the TS warning in editor, though the actual component only allows single select regardless.

**Comment by Methuselah96** [comment]
Try this:

```diff
- <ReactSelect<SelectOption>
+ <ReactSelect<SelectOption, boolean>
```

**Comment by Xuroth** [comment]
Thank you! It looks like this was just a misunderstanding of TS implementation on my part. Adding that type resolved the issue!
