### ISSUE TITLE
Unfocused Select in form always intercepts submit on enter

### ISSUE THREAD

**Issue by Oikio** [JedWatson/react-select#5331]
Unfocused `Select` inside `form` tag prevents user from submitting whole form on `enter`, no matter if it has values/suggestions or not.

Reproduction: focus on input and press `enter`, in case `Select` is present form will not be submitted: https://codesandbox.io/s/intelligent-wilbur-e0hv9t?file=/src/App.js

**Comment by Rall3n** [comment]
@Oikio This is standard browser behavior. 

Based on current spec:
> If the form has no submit button, then the implicit submission mechanism must do nothing if the form has more than one field that blocks implicit submission, and must submit the form element from the form element itself otherwise.
>
> For the purpose of the previous paragraph, an element is a field that blocks implicit submission of a form element if it is an input element whose form owner is that form element and whose type attribute is in one of the following states: Text, Search, URL, Telephone, Email, Password, Date, Month, Week, Time, Local Date and Time, Number
> *- [HTML Standard | Form | Implicit submission](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission)*

In other words:
The form can be submitted from an `<input>` element if it is the only validatable `<input>` element in the form or if there is a submit button present. 

And `react-select` uses an `<input>` element for searching, so your `<input>` element is not the only existing one in the form, and form submission is prevented according to the spec.

-----

I will close this issue as it being not an issue with the library, but a misunderstanding of standard browser behavior.

**Comment by Oikio** [comment]
Thank you very much for the explanation, never knew about this behavior and indeed this is the case for reproduction I provided. 
It helped me to understand how to fix it in the app, I did not have type="submit" on form button in my form, just forgot to add it.
