### ISSUE TITLE
when using asyncOptions filter should be disabled by default

### ISSUE THREAD

**Issue by FrancescoCioria** [JedWatson/react-select#534]
In order to use `asyncOptions` you must have `searchable={true}` (which is `true` by default) and if `searchable={true}` `react-select` tries to filter the `options`.
I think this behavior is unwanted (and hard to debug) as when using `asyncOptions` you're already supposed to pass `react-select` an array of `options` generated using the user input (for example by doing an asynchronous search).

**Comment by angelinacc** [comment]
+1

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
