### ISSUE TITLE
`Cannot read properties of undefined (reading 'name')` with useFieldArray in react-hook-form

### ISSUE THREAD

**Issue by rikusen0335** [JedWatson/react-select#5360]
So thus using `react-select` and `useFieldArray` in `react-hook-form` which is handles array of input, will occur the error that `Cannot read properties of undefined (reading 'name')`.

I'm really not sure what's the reason of issue, I investigated few hours but I still doesn't know why.
This could be a question but instead I opened this issue as bug.

### How to reproduce
1. Go [here](https://codesandbox.io/s/react-select-v5-sandbox-react-hook-form-kn2jl7?file=/example.js) (CodeSandbox)
2. Add `Select`
3. Select anything you want

## Are you reporting a bug or runtime error?
Runtime error probably?

**Comment by Rall3n** [comment]
Hello @rikusen0335,

using `register` is not recommended with `react-select`, as the `onChange` prop returned by `register` expects a qualified `Event` object, which `react-select` cannot provide.

It is recommended to use the `Controller` component from `react-hook-forms`. More on that in the [offical `react-hook-form` documentation](https://react-hook-form.com/api/usecontroller/controller).

**Comment by rikusen0335** [comment]
I must notify about that. Thank you.

**Comment by tosebikan** [comment]
if your'e experiencing this you need to remove the  register and it should start working.

eg. from the initial post above
removing ` {...register(`test.${index}.id`)}` fixes the issue
