### ISSUE TITLE
Uncaught TypeError: dispatcher.useInsertionEffect is not a function 

### ISSUE THREAD

**Issue by krajcikondra** [JedWatson/react-select#5365]
Hi, after update react to version 18 react select throw following error:
```
Uncaught TypeError: dispatcher.useInsertionEffect is not a function 
```

Are you planning to update this package for react 18? Thanks in advance

**Comment by Methuselah96** [comment]
This package should with React 18. Can you check out https://github.com/JedWatson/react-select/issues/5076 and see if anything there helps resolve your issue?

**Comment by krajcikondra** [comment]
update react-dom from v17 to v18 solved my problem.

**Comment by SetupCoding** [comment]
We provide a component library to be consumed by the users, which uses react-select internally, this comment here described what helped us fix the error:
https://github.com/JedWatson/react-select/issues/5555#issuecomment-2221453923

> If you're using this in a component library, you can install emotion as a devDependency and externalize them in your `vite.config.ts`.

```
	"devDependencies": {
		"@emotion/react": "^11.11.4",
		"@emotion/styled": "^11.11.0",
	}
```
```tsx
export default defineConfig({
	build: {
                 ...
		rollupOptions: {
			external: ['react', 'react-dom', '@emotion/react', '@emotion/styled'],
			output: {
				globals: {
					react: 'React',
					'react-dom': 'ReactDOM',
				},
			},
		},
	},
});
```
