### ISSUE TITLE
Call stack size exceeded with centered text

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#540]
If you have a select input (not multi-select) and horizontally center the value, typing into the search field causes an infinite loop leading to a "Call stack size exceeded" error.

It would definitely be nice to support centering text in single-select mode, so this should be looked into. I suspect the issue is related to the `input-autosize`; maybe it's worth adding a prop that disabled use of that component if you don't need it.

**Comment by brunogenaro** [comment]
Still having this error here... anyone?

**Comment by tyson-kubota** [comment]
I also ran into this.

One workaround I've found is to add custom style overrides to specify text-align on a per-element basis for the children of `Select`, instead of on the `Select` component itself:

```
.Select-placeholder,
.Select--single > .Select-control .Select-value
  text-align: center

.Select-option
  text-align: center
```

**Comment by manavsehgal** [comment]
Still seeing this error with centered text.
flattenChildren.js?0d06:28 Uncaught RangeError: Maximum call stack size exceeded

**Comment by giladgray** [comment]
for the record, there are several other centering strategies that work fine:

- `margin: auto`
- flex box `justify-content: center`

**Comment by nandukalidindi** [comment]
![screen shot 2017-03-16 at 1 26 43 pm](https://cloud.githubusercontent.com/assets/4492228/24011209/7a93787c-0a50-11e7-8265-e5a4d1aa6b1f.png)

After copying the `react-select.css` from node_modules into my local styles folder. I applied the above diff to prevent the error.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
