### ISSUE TITLE
options prop and onChange not infering the Option type

### ISSUE THREAD

**Issue by frle10** [JedWatson/react-select#5401]
I'm using react-select with react-hook-form and I have a problem where the options prop from react-select doesn't infer the type of options I pass in even tho I gave them an explicit type.

You can see the example of this in the following CodeBox:
https://codesandbox.io/s/react-select-v5-sandbox-forked-jy1w0m?file=/example.tsx

I'm not sure why this is happening, might just be me not fully understanding how TypeScript works, but I spent a lot of time on this now and it's a problem because I can't fully integrate react-select in my form without explicit type casting and other hacky things I don't want to have in my code.

Any ideas on why automatic inference doesn't work here?

Versions of libraries are visible in the CodeBox, but I will write here also that I'm using React 18.2.0, Typescript 4.8.4 and react-select 5.5.2

**Comment by Methuselah96** [comment]
It has to do with the value you're passing into the `styles` prop. Specifically, `StylesConfig` has generics that correspond with the option type and whether it's a multi-select.

Your two options if you don't want to manually type the `onChange` parameter are to set the generic parameters on `StylesConfig` or inline the styles prop (demonstrated [here](https://codesandbox.io/s/react-select-v5-sandbox-forked-txweoz?file=/example.tsx)).

Let me know if that answers your question.

**Comment by frle10** [comment]
Alright that worked out! Thank you very much. I don't fully understand yet how this works exactly but it fixed my problem. :) Issue can be closed.
