### ISSUE TITLE
Can not install latest react-select version

### ISSUE THREAD

**Issue by antollika** [JedWatson/react-select#5407]
Hello everyone
I'm trying `npm install react-select@5.5.4`

But receive
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-select@5.5.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I see that this version is published to NPM but can not install it

![image](https://user-images.githubusercontent.com/34944312/196997820-13a61b11-f109-47c0-bff6-19e0e7a5e61a.png)

**Comment by Methuselah96** [comment]
It's working for me, maybe try again?

**Comment by lukebennett88** [comment]
Confirmed that it's also working for me.
