### ISSUE TITLE
Value not clearing for Creatable single value dropdown

### ISSUE THREAD

**Issue by virender-gupta1** [JedWatson/react-select#5412]
I have used react-select/creatable in my react project. I have set isMulti to false and isClearable to true. The clear indication shows but it does not clear the value on click. It does not even trigger onChange event. It just loads the options just like clicking elsewhere in the dropdown.

I have used the same component in another place with isMulti set to true and it works fine there.

<CreatableSelect
                          placeholder="Please select/add search terms to help users find this question"
                          className="filter-form"
                          classNamePrefix="select"
                          isDisabled={false}
                          isRtl={false}
                          isSearchable={true}
                          name="CXM Tool"
                          options={options}
                          isMulti={false}
                          isClearable={true}
                          onChange={(
                            ev, newValue
                          ) => {
                              function1(ev.label, index2,newValue['action'] === "create-option");
                            }
                          }
                          value={{label:singleService2.creativeproductName,value:singleService2.creativeproductName}}

**Comment by Rall3n** [comment]
Hello @virender-gupta1 ,
would you be so kind and provide a minimal reproducible example using [CodeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-y5jtm) as requested in the issue template?

**Comment by virender-gupta1** [comment]
Hi @Rall3n ,

I tried this in codesandbox. It worked as expected and I identified the issue in my code.

ev object was null in case of clear and i ignored that, My bad.

Thank you for you quick response.

**Comment by mdodge-ecgrow** [comment]
@virender-gupta1 I think I am having the same issue as you.  When I click on the 'X' to clear the selected value, it just closes/opens the menu.  It never clears out the value.  What did you have to do to fix it?
