### ISSUE TITLE
Import declaration conflicts with local declaration of 'Select'.ts(2440)

### ISSUE THREAD

**Issue by paulous** [JedWatson/react-select#5417]

**Comment by paulous** [comment]
Not sure why this is happening?
package.json:

  "dependencies": {
    "framer-motion": "^7.5.3",
    "localforage": "^1.10.0",
    "match-sorter": "^6.3.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.4.2",
    "react-select": "^5.5.4",
    "sort-by": "^0.0.2",
    "styled-components": "^5.3.6"
  },
  "devDependencies": {
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@types/styled-components": "^5.1.26",
    "@vitejs/plugin-react": "^2.1.0",
    "typescript": "^4.6.4",
    "vite": "^3.1.0"
  }

**Comment by Methuselah96** [comment]
Do you happen to be importing `Select` from `react-select` and also have a variable with the name `Select` in your file?

**Comment by paulous** [comment]
Thanks! That was fast. I deleted the message as it was just my stupidity.
