### ISSUE TITLE
Documentation: Unacceptably low contrast on view sample source button

### ISSUE THREAD

**Issue by judfs** [JedWatson/react-select#5434]
For https://react-select.com/home:

Even drawing a giant red circle around it, its easy to look at this screenshot and not realize this button exists.
![image](https://user-images.githubusercontent.com/39133604/198116215-28b28cf5-a001-41ab-af53-26e7e989aa17.png)

I just spent a bunch of time trying to understand things in devtools because I had no clue this button existed.

There is no need de-emphasis the button blocks when not hovered, but `opacity: 0.2;` is absolutely not ok.

**Comment by lukebennett88** [comment]
Thanks for raising this @judfs. I fully agree with you. 
We're planning to improve the docs soon, but in the meantime as a quick fix, I've opened a PR to improve the contrast: 
- https://github.com/JedWatson/react-select/pull/5436
