### ISSUE TITLE
react-select as cellRenderer in fixed-data-table

### ISSUE THREAD

**Issue by LeafInStrom** [JedWatson/react-select#545]
I am trying use  react-select in fixed-data-table , and I've met some issues.
Any tip helps, thx.
```js
     _renderTags(cellData, dataKey, rowData, rowIndex) {
		var ops = [];
		for (let i = 0; i < cellData.length; i++) {
			ops.push({
				label: cellData[i].name + '-' + cellData[i].score,
				value: cellData[i].uid + '-' + cellData[i].score,
			})
		}

		return (
			<div>
				<Select
					multi={true}
					value={ops}
					placeholder="uid-score"
					options={this.props.tagOps}
					/>
			</div>
		);
	}
.....
   <Column dataKey='tags' align={'center'} isResizable={true} width={this.state.columnWidths['tags']}
	label='tags' cellRenderer={this._renderTags}/>
```
When I am typing ,browser become extremely slow . In browser console I'v got this error.
**But same code out of cell works fine**.
<img width="602" alt="1" src="https://cloud.githubusercontent.com/assets/12244395/10818408/48bec0ec-7e7c-11e5-993d-5262e63e89ca.png">

**Comment by LeafInStrom** [comment]
react-select@0.6.12  fixed-data-table@0.4.7 react@0.13.3

**Comment by LeafInStrom** [comment]
Solved by remove **align={'center'}**   param  
Inspired by https://github.com/JedWatson/react-select/issues/540

**Comment by kamaldlk** [comment]
Hi @LeafInStrom I'm trying to add react select my fixed-data-table while click it's not opening please help me on this
