### ISSUE TITLE
true/false values is not working

### ISSUE THREAD

**Issue by sobrinho** [JedWatson/react-select#546]
``` javascript
<Select value={true} options=[{value: true, label: "Yes"}, {value: false, label: "No"}] />
<Select value={false} options=[{value: true, label: "Yes"}, {value: false, label: "No"}] />
```

In both cases the option isn't selected. Using string like `"true"` and `"false"` make it works.

Isn't allowed to use boolean values?

**Comment by joefiorini** [comment]
+1 I've run into this same issue as well. @JedWatson is this something the component should support?

**Comment by 592da** [comment]
+1

**Comment by adamaoc** [comment]
+1, just running into this issue...

**Comment by 592da** [comment]
Someone ? :octopus:

**Comment by jeremym** [comment]
+1; having same issue.

**Comment by ktalebian** [comment]
Is there a plan to support this anytime soon?

**Comment by Aaronius** [comment]
I found:

https://github.com/JedWatson/react-select/blob/17d76a4161096cb88fb04a6e9e6529580e67b305/src/Select.js#L564

which essentially restricts values to strings and numbers. If I change that line to:

```
if (typeof value !== 'string' && typeof value !== 'number' && typeof value !== 'boolean') return value;
```

...then booleans seem to work fine.

**Comment by swp44744** [comment]
Hello, I am observing this issue again.. value gets selected just fine if value is true. but value is not selected when value is false.
const OptionValues = [
  {value: true, label: 'Yes'},
  {value: false, label: 'No'}
];

I am @^1.0.0-rc.10

**Comment by swp44744** [comment]
forgive me for false alarm.. It was my mistake... i was checking if value is not selected then set default value. and i was doing that by - !value ? defaultValue : value. so whenever value is false it was trying to set it to default value and for that dropdown default value was " ".

**Comment by Pawankashap** [comment]
onChange={e=> setFavorite(JSON.parse(e.target.value))}
return true value
