### ISSUE TITLE
Incorrect link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Mikilll94** [JedWatson/react-select#5464]
![contributing link](https://user-images.githubusercontent.com/17653648/200191088-4660b3a8-80d2-4be7-b9fb-00a9ba0724f1.PNG)

https://github.com/JedWatson/react-select/blob/master/CONTRIBUTING.md

The link which I highlighted in `CONTRIBUTING.md` is pointing to the incorrect location.

**Comment by dcousens** [comment]
@Mikilll94 please open a pull request! :)
