### ISSUE TITLE
Unable to select option because list moves on hover since 5.5.7

### ISSUE THREAD

**Issue by TruffeCendree** [JedWatson/react-select#5471]
The bug is triggered on hover when the list of options overflows outside the view. I was not able to reproduce on codesandbox.

![Issue react-select](https://user-images.githubusercontent.com/4479304/200499612-b4c8c969-40e5-4575-a37b-bf83009118ca.gif)

It seems the bug was introduced in a refactoring : https://github.com/JedWatson/react-select/compare/react-select%405.5.6...react-select%405.5.7

**Comment by badders** [comment]
We also see exactly the same issue

**Comment by santialbo** [comment]
It's also happening to us, as in the example you showed it happens to use within fixed dialogs. I've unable to reproduce it in a simple example...

**Comment by Methuselah96** [comment]
@nderkim Any progress on a fix or should we maybe revert the PR for now?

**Comment by nderkim** [comment]
Unfortunately, I can't seem to replicate the issue. Is there perhaps a public repo that I can access that replicates the issue? Or if there is a public site where I can see this bug in action maybe it will give me more to work off in trying to reproduce it.
Is the issue always there, or only under certain conditions?

**Comment by santialbo** [comment]
I managed to reproduce the gist of the issue
https://codesandbox.io/s/friendly-elion-w6sx1d?file=/example.js

It's a combination of the following:
- Using the portal option
- Using a theme function override

@TruffeCendree, @badders, @Methuselah96 can you please confirm if you are also using these options?

I suspect there's a hook somewhere using the `theme` as dependency, and since it is changing everytime it causes these weird rerenders.

If you comment/uncomment lines 20, 21 you will see how the bug appears or goes away.

**Comment by TruffeCendree** [comment]
@santialbo Nice! We are in a similar case to the one you are describing. We are overriding `theme` and the select is mounted in a dialog, itself mounted in a portal.

**Comment by santialbo** [comment]
In the meantime I created this custom callback to wrap my theme function so that it returns the same instance.

```ts
import { useCallback, DependencyList, useRef } from "react";

export function useMemoizedCallback<T extends (...args: any[]) => any>(
  callback: T,
  deps: DependencyList
): T {
  const depsRef = useRef<DependencyList>();
  const resultRef = useRef<any>();
  return useCallback(
    ((...args) => {
      if (!depsAreEqual(deps, depsRef.current)) {
        depsRef.current = deps;
        resultRef.current = callback(...args);
      }
      return resultRef.current;
    }) as T,
    deps
  );
}

function depsAreEqual(d1: DependencyList | undefined, d2: DependencyList | undefined) {
  if (!d1 || !d2 || d1.length !== d2.length) {
    return false;
  }
  for (let i = 0; i < d1.length; ++i) {
    if (d1[0] !== d2[0]) {
      return false;
    }
  }
  return true;
}
```

then when defining the theme

```ts
const theme = useMemoizedCallback(
    (theme: Theme) => {
      return {
        ...
      };
    },
    [size, colors]
  );
  ```

**Comment by nderkim** [comment]
> I managed to reproduce the gist of the issue https://codesandbox.io/s/friendly-elion-w6sx1d?file=/example.js

Thanks @santialbo 🙏 That was super helpful 😊
