### ISSUE TITLE
loading icon shouldn't show up if there are no unresolved callbacks

### ISSUE THREAD

**Issue by savvopoulos** [JedWatson/react-select#548]
In this example:
https://github.com/JedWatson/react-select#async-options

Setting value to undefined, results in the loading icon showing up.
(I prefer not to have a preselected option, so I don't add that prop. Let me know if that's wrong.)

<img width="424" alt="screen shot 2015-10-30 at 11 39 21" src="https://cloud.githubusercontent.com/assets/747519/10843805/6da76222-7efb-11e5-9194-ff23099e718a.png">

Thanks!

**Comment by savvopoulos** [comment]
One more note: my callback returns an empty array at first, until the user has typed three characters.

**Comment by JedWatson** [comment]
Should be fixed in the new version!

**Comment by 7rulnik** [comment]
@savvopoulos you can try insert empty string by default. Something like that `value={''}`

**Comment by clinyong** [comment]
@7rulnik It works, thanks.
