### ISSUE TITLE
name property is not being set on the input element

### ISSUE THREAD

**Issue by berndfourdigits** [JedWatson/react-select#5484]
In this example https://codesandbox.io/s/react-select-v5-sandbox-y5jtm?file=/example.js:205-222 the `name` prop is set with the value `color`. When you inspect the DOM and look for the input element the `name` attribute is missing.

**Comment by berndfourdigits** [comment]
Apparently I was looking at the wrong input as there is another one and that one has the name attribute

**Comment by arnaudambro** [comment]
oh thanks ! I didn't see it until I saw your issue
