### ISSUE TITLE
<Wrong behavior when loading defaultValues on options styles>

### ISSUE THREAD

**Issue by lucasnatanmelo** [JedWatson/react-select#5490]
Hello React-Select team.
I'm having a problem when loading default values and options on Select Component. The backgroundColor and Color are changing as the usual default when I try to use the component with defaultValue.  I'm not using the customStyles, with control properties like the documentation determines. Here's how I'm rendering the Select component:

<Select
    // name, options, onCreateOption, etc...
    defaultValue: {lastSubmittedData ? { label: lastSubmittedData[key], value: key } : undefined}
/>

Where lastSubmittedData is an object with the data that I want to render inside the options.
The problem is not on rendering data, only the CSS properties of the options, as you can see in an example in my application with the images attached.

Correctly options show method -First filling on Select input: 
![image](https://user-images.githubusercontent.com/100950738/202468281-534f5b58-1dff-486a-9072-bb332c353a62.png)

Wrong options show - When load lastSubmittedData on Select input: 
![image](https://user-images.githubusercontent.com/100950738/202468641-19088158-d0a9-462e-9308-8156210c4813.png)
Note: In this example, I filled the Select with completion.

**Comment by Rall3n** [comment]
@lucasnatanmelo Would you be so kind and provide a minimal reproducible example using [CodeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-y5jtm) as requested in the issue template?
