### ISSUE TITLE
Disabling input

### ISSUE THREAD

**Issue by farism** [JedWatson/react-select#55]
I'm interested in using this plugin as a regular dropdown (like in the `react-dropdown` module, purely for styling purposes) and would love a way to disable the input field and autocomplete functionality. Is this something you would be interested in adding?

**Comment by julen** [comment]
I've got a local branch that I started some time ago to disable the searching input. If that's what you're referring to, I could look at rebasing my branch on top of current master and create a PR.

**Comment by farism** [comment]
If its not too much work I wouldn't mind checking it out. Right now I have a bit of bloat from using both react-select and react-dropdown, when the former could potentially take care of everything.

**Comment by JedWatson** [comment]
@farism yep, I'd be happy to add that.

So it'll work like a dropdown menu that tracks the currently selected value, right?

Maybe if we implement a `input` prop to control the visibility of the field that defaults to `true` that would do the trick.
