### ISSUE TITLE
Windows phone - dropdown closes straight away when searchable=false

### ISSUE THREAD

**Issue by FutureKode** [JedWatson/react-select#550]
Testing windows phone 8.1 - touching the select to choose an option. The dropdown shows but then closes straight away. This is happening when searchable is set to false.

You can see this on the demo site first example on a windows phone by toggling Searchable checkbox.

**Comment by JedWatson** [comment]
@FutureKode could you let me know if this still happens with the new version? You'll have to run the examples locally until we're out of beta.

**Comment by FutureKode** [comment]
Hiya, I have it running locally, is it possible to view the server from
another device? I have used browsersync to do this on other projects but
not sure if you have something setup already

On 7 November 2015 at 15:13, Jed Watson <notifications@github.com> wrote:

> @FutureKode <https://github.com/FutureKode> could you let me know if this
> still happens with the new version? You'll have to run the examples locally
> until we're out of beta.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JedWatson/react-select/issues/550#issuecomment-154713304>
> .
>



-- 
Mark Steggles

**Comment by FutureKode** [comment]
Testing react-select 0.9.1 on windows phone 10 preview the issue is no longer there. So guessing it will be fixed on the react select beta version as well.

Windows phone 10 should be released this week and available to all by the carriers in December.

**Comment by JedWatson** [comment]
Thanks @FutureKode!
