### ISSUE TITLE
can't update options use with  componentWillReceiveProps

### ISSUE THREAD

**Issue by Pyiner** [JedWatson/react-select#551]
I set `value` and `options` props with a  async select like this:
` 
<Select  value={value} options={this.props.options} asyncOptions={this.loadOptions} />
`
and when I update the options with componentWillReceiveProps, some thing wrong

it use `value` as the `input` for the `asyncOptions` method.
my `options` has been filter out,

and I find is OK in old version.
```
	componentWillReceiveProps: function componentWillReceiveProps(newProps) {
		if (JSON.stringify(newProps.options) !== JSON.stringify(this.props.options)) {
			this.setState({
				options: newProps.options,
				filteredOptions: this.filterOptions(newProps.options)
			});
		}
		if (newProps.value !== this.state.value) {
			this.setState(this.getStateFromValue(newProps.value, newProps.options));
		}
	},
```
but in this version, these code in the bottom of the method,
```
			if (this.props.asyncOptions) {
				this.loadAsyncOptions(newProps.value, {}, setState);
			} else {
				setState();
			}
```

**Comment by JedWatson** [comment]
I've totally changed the way this works, and this shouldn't be a problem any more.

Note that in the new version, with `Select.Async` providing your own `options` prop isn't supported, if you want to provide default options handle it in the function that the `loadOptions` prop points to.
