### ISSUE TITLE
react-select not working with react version 18

### ISSUE THREAD

**Issue by yjoon45** [JedWatson/react-select#5523]
Hi team,

I was using the react-select in my project it was working fine, but upgrading React version from 17 to 18. It stopped working.

Getting this error.

Thanks in advance ✌️

<img width="689" alt="Screenshot 2022-12-29 at 9 47 05 PM" src="https://user-images.githubusercontent.com/7107185/209980422-60ac2504-15aa-428a-89e5-792e2796aa24.png">
<img width="1222" alt="Screenshot 2022-12-29 at 9 47 34 PM" src="https://user-images.githubusercontent.com/7107185/209980471-28ccd3bc-95ec-48fe-9e35-0b3325d6d600.png">

**Comment by yjoon45** [comment]
My bad, the react-dom version was not updated. Closing this issue.

**Comment by pauloguilherm** [comment]
I have react version 18 and? react-router-dom 5.x, I need to use 5.x because it is already in a project, but when updating react from 17 to 18 I am getting the same error, is there a way to solve it without updating react-router to 6?

**Comment by kodmanyagha** [comment]
The problem still exist. Let me show the code:

```
import Select from "react-select";

...

              <Select
                defaultValue={selectedOption}
                options={options}
                onChange={(newValue, actionMeta) => {
                  console.log(newValue!.value, actionMeta);
                  setSelectedOption(newValue!.value);
                }}
              />


```
`'Select' cannot be used as a JSX component. Its type 'StateManagedSelect' is not a valid JSX element type.`

**Comment by L-U-C-K-Y** [comment]
> The problem still exist. Let me show the code:
> 
> ```
> import Select from "react-select";
> 
> ...
> 
>               <Select
>                 defaultValue={selectedOption}
>                 options={options}
>                 onChange={(newValue, actionMeta) => {
>                   console.log(newValue!.value, actionMeta);
>                   setSelectedOption(newValue!.value);
>                 }}
>               />
> ```
> 
> `'Select' cannot be used as a JSX component. Its type 'StateManagedSelect' is not a valid JSX element type.`

@kodmanyagha I also face this issue, were you able to find a solution?
