### ISSUE TITLE
Provide a validator method to check against bad data

### ISSUE THREAD

**Issue by damassi** [JedWatson/react-select#553]
While I'm aware that validation should occur before the data is passed into the component, I'm wondering if it would be a good idea to provide an additional layer of validation internally since the expected format of the data always remains the same. I'm finding that something as simple as 

```
[
  { 
     value: { value: '', label: '' }},
     label: { value: '', label: '' }}
  }
]
```

has the ability to cause havoc on your application. Having an additional layer of validation, or some kind of 'warnIfInvalid' prop that disables the component and explicitly prevents a render -- but also prints a helpful warning -- might be helpful. Tracking down the above issue took quite some time.

**Comment by JedWatson** [comment]
I've checked these data conditions in the new version and it's much more robust.

If you still see issues that validation could fix, please reopen this and we'll see.

**Comment by damassi** [comment]
Awesome, thanks so much. This will be a great help.
