### ISSUE TITLE
Lazy-render large option lists (and reuse option panels)

### ISSUE THREAD

**Issue by mathew-kurian** [JedWatson/react-select#554]
Something similar to this http://devblog.orgsync.com/react-list/

**Comment by mwkurian** [comment]
I have added it my repo: https://github.com/mwkurian/react-select
Example of its benefit: http://4playdb.me/platform/94

**Comment by asides** [comment]
Great work! Waiting in the official branch...

**Comment by bvaughn** [comment]
Check out PR #859 (and the demo linked) which adds react-virtualized support.

**Comment by bvaughn** [comment]
**Update**: If you're able to use react-select 1.0.0 beta, then you might be interested in trying a new HOC, [react-virtualized-select](https://bvaughn.github.io/react-virtualized-select/). Does windowing/lazy rendering so it should help with the issue you're reporting.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
