### ISSUE TITLE
The `name` prop is not passed to DummyInput

### ISSUE THREAD

**Issue by eugenet8k** [JedWatson/react-select#5560]
The API doc https://react-select.com/props says 

> name: Name of the HTML Input (optional - without this, no input will be rendered) string

The reality is:

https://github.com/JedWatson/react-select/blob/c350a124f8de853a79e0158578d438a35e67e63e/packages/react-select/src/Select.tsx#L1646-L1658

There is no way to pass `name` to the underlying `input`, hence it's hard to enable essential HTML Form-related functionality...

**Comment by eugenet8k** [comment]
A suggested workaround could be:

```js
  const Select = ({name, ...props}) => {
     const selectRef = useRef()

      useEffect(() => {
        if (name && selectRef.current?.inputRef)
          selectRef.current.inputRef.name = name
      }, [name])

     return <ReactSelect name={name} ref={selectRef} {...props} />
  }
```

**Comment by Rall3n** [comment]
@eugenet8k `react-select` differences between two types of input internally: The search input and the value-holding input. One is for search functionality and focus handling, the other is for form based data submission.

The search input does not have the `name` attribute, as it does not hold the value needed for form submission. That is the sole purpose of the value-holding input.

Also see:
https://github.com/JedWatson/react-select/blob/c350a124f8de853a79e0158578d438a35e67e63e/packages/react-select/src/Select.tsx#L2021-L2058

**Comment by eugenet8k** [comment]
@Rall3n yeah, I guess it's a valid point. But this makes it hard to integrate ReactSelect with another 3rd party. For example https://github.com/jaredpalmer/formik. There, if we want to kick off form validation, we need to pass Formik's `onBlur` callback to ReactSelect. Currently, in ReactSelect it is hooked, as you mentioned, to the dummy input, so when Formik gets the Blur event, the event target's dummy input does not have `name` attr, so the integration breaks.

**Comment by Rall3n** [comment]
@eugenet8k And the event target does not need the `name` attr with formik.

Formiks `onBlur` is not only an event callback, but also a linking-function. Providing it the name of the field will return a new event callback which will use the provided field name instead of the one set on the event target.

Here is a [CodeSandbox example](https://codesandbox.io/s/react-select-formik-blur-bzphky) implementing the above mentioned with `react-select`.
