### ISSUE TITLE
Setting value/defualtValue not hiding them from option for complex values

### ISSUE THREAD

**Issue by PixeledCode** [JedWatson/react-select#5565]
So this bug happens when we use a little complex value for options. Something like this: 
`{ value: { abc: 1, color: "#00B8D9" }, label: "Ocean" }`

A small repo showcasing the problem: https://codesandbox.io/s/react-select-v5-sandbox-forked-eplhgm?file=/example.js:96-151

**Problem:**
The default selected value `Vanilla` is still available in the options.

**Expected Behaviour:**
The default selected value should not be in the list.

**Comment by Rall3n** [comment]
@PixeledCode Implementation issue: The component by default will always use the `value` attribute of an option for comparison. Visually, your options are the same, but as they are created separately, their identities do not match.

```js
let opt1 = {test:1};
let opt2 = {test:1};

opt1 == opt2 // false
```

Providing the `getOptionValue` prop with `(option) => option.value.value` will fix this issue.
