### ISSUE TITLE
Wrong option type in getOptionLabel/getOptionValue

### ISSUE THREAD

**Issue by nik-webdevelop** [JedWatson/react-select#5569]
When I use Select with groups, the option parameter in getOptionalLabel/getOptionalValue is inferred as a whole group. Function `getOptionLabel={(option) => option.name}` is accessing the name properly but TS shows errors.

```typescript
const colors = [
  {
    label: "Colors",
    options: [
      { name: "white", value: "1" },
      { name: "yellow", value: "2" }
    ]
  }
];

<Select
  options={colors}
  getOptionLabel={(option: inferred as group and not the actual option) => ... }
  getOptionValue={(option: inferred as group and not the actual option) => ... }
/>
```

[Codesandbox](https://codesandbox.io/s/bitter-meadow-mrerpk?file=/src/App.tsx)

**Comment by Rall3n** [comment]
@nik-webdevelop If the `Select` component has problems inferring the option type from the given options, you can provide a set type for those options to the component:

```tsx
<Select<{name: string, value: string}>
  options={colors}
  getOptionLabel={(opt) => opt.name} // properly coerced as option
/>
```

**Comment by nik-webdevelop** [comment]
Thanks for your response. Yes, this will work, but it's not really handy to explicitly pass option type each time. I just was surprised that an option isn't inferring by default.
P.S. also setting `defaultValue` or `value` fixes an option inferring
