### ISSUE TITLE
styles on menuPortal return top, left and width as 0

### ISSUE THREAD

**Issue by norbulcz** [JedWatson/react-select#5588]
After updating to 5.7.0 menuPortal isn't working as before. 

Before, styles held information about top, left and width but now 0 is returned hence I can't see my dropdown menu(it's there but it has 0 width and it's positioned on top left corner). Looked at the documentation and nothing changed. Just want to mention that the menuPortalTarget it's set to document.body.
```
<Select
    styles={{
        menuPortal: (base) => ({
                    ...base,
                    ....
                })     
    }} 
    .... 
/>
```

**Comment by Rall3n** [comment]
@norbulcz Please provide a minimal reproducible example using [CodeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-y5jtm).

**Comment by norbulcz** [comment]
While trying to do reproducible example and reading your docs noticed that I was passing inline declaration to custom components, after refactoring according to your guidelines it worked well. If it helps the previous version that worked well with inline declaration and was forwarding the top, left and width was 5.3.2. I will close this bug. Thank you for your help and understanging.

**Comment by Bolnus** [comment]
Thank you! Fixing inline declaration really worked in my case. So if you need to pass something to sub components, you need to add props to main component and then get the data in sub component via `props.selectProps`. This way the bug is not triggered.
