### ISSUE TITLE
Menu is re-rendered after customizing Menu component

### ISSUE THREAD

**Issue by devdreamsolution** [JedWatson/react-select#5594]
I've just put this customize Menu without any customizing.
Then the Menu is re-rendered.
```js
<Select
	components={{
		Menu: ({ children, ...rest }) => (
			<components.Menu {...rest}>{children}</components.Menu>
		),
	}}
/>
```

**Comment by pascalstr** [comment]
See this documentation: https://react-select.com/components#defining-components

**Comment by devdreamsolution** [comment]
@pascalstr , that works well. thank you.
