### ISSUE TITLE
Usage of defaultProps on functional components is deprecated and results in warning

### ISSUE THREAD

**Issue by DerpyCrabs** [JedWatson/react-select#5596]
I get console warnings on nextjs 13.2.4 (app directory), react 18.2.0 and react-select 5.7.2 about the usage of defaultProps on functional components in LoadingIndicator, LoadingMessage, NoOptionsMessage, MultiValue.

I couldn't reproduce it with 18.2.0 in codesandbox, but could with 18.3.0 https://codesandbox.io/s/react-select-v5-sandbox-forked-bxhjk2?file=/index.js.

Pull request that enabled warning for everyone in react https://github.com/facebook/react/pull/25699.

**Comment by riteshreg** [comment]
do you fix this warning

**Comment by Ruebs** [comment]
Getting the same warnings.

Found this thread that shows how it was fixed in chakra-ui: https://github.com/chakra-ui/chakra-ui/issues/7057

**Comment by felipemullen** [comment]
Also seeing this as an error in the console:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/3488482/233085961-fd3483b1-901a-4114-9e87-8c87f45fa0dd.png">

I can't create a PR at this point, but maybe someone else can.
I believe [this line](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/indicators.tsx#L309) should be removed

```typescript
LoadingIndicator.defaultProps = { size: 4 };
```

and the component  props should be redefined as mentioned in the post above mine like this

```typescript
export const LoadingIndicator = <
  Option,
  IsMulti extends boolean,
  Group extends GroupBase<Option>
>(
  props: LoadingIndicatorProps<Option, IsMulti, Group>
) => {
  const { innerProps, isRtl } = { size: 4, ...props};

  return (
    ...
```

**Comment by asdutoit** [comment]
Same issue here

**Comment by riteshreg** [comment]
Any one solve this

**Comment by GOLIVEIRABR** [comment]
Same issue here on noOptionMessage.

**Comment by vincentwinkel** [comment]
Same issue here on `NoOptionMessage`.

**Comment by hsuanyi-chou** [comment]
Same issue here on `NoOptionMessage`.

**Comment by ruslanguns** [comment]
Yeah, this error message is a bit annoying. Thanks for working on it.
