### ISSUE TITLE
Custom ValueContainer looses click with blurInputOnSelect

### ISSUE THREAD

**Issue by CyrilQuandalle** [JedWatson/react-select#5605]
Hello,

I'm having an issue while using a Custom `ValueContainer` with the prop `blurInputOnSelect` set to true. On first click on it the menu opens correctly,  after selecting an element the menu closes but when I try to click on the Select to open the menu again nothing happens whereas it should.

I'm using react-select v5.7.2
Here is my codeSandbox link : 
[codeSandbox](https://codesandbox.io/s/react-select-v5-sandbox-forked-skhly6?file=/example.js)

Thanks in advance

**Comment by Rall3n** [comment]
Hello @CyrilQuandalle,

You do not persist `children` into both `ValueContainer` components.
This is the main problem, as `children` contains an `<input>` element which is used for focus handling of the `Select` component.
You can apply a filter onto `children` to remove any component related to selected options.
```jsx
const noValueChildren = React.Children.toArray(children).filter(
  child => [components.Input, components.Placeholder].includes(child.type)
);
```

**Comment by CyrilQuandalle** [comment]
Hello @Rall3n,

Thank you very much for your answer. It seems to be working in the codesanbox, locally it doesn't but the implementation is more complicated over there. I'll keep digging and keep you posted.

**Comment by CyrilQuandalle** [comment]
It turns out that I didn't need to replace the ValueContainer to achieve what I wanted to do. I just needed to change the label of the selected value in the onChange method where I do a setValue (useState), since I only wanted to have a custom value for each option selected but different from what was in the menu.

**Comment by saver711** [comment]
@Rall3n 
i saw different answers from u on this and similar issues
i always get this error
![image](https://github.com/user-attachments/assets/f75650de-ce31-42f2-9301-3b2f809ff521)

**Comment by uu29** [comment]
> @Rall3n i saw different answers from u on this and similar issues i always get this error ![image](https://private-user-images.githubusercontent.com/28202010/351440081-f75650de-ce31-42f2-9301-3b2f809ff521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDk0MzYsIm5iZiI6MTczMzc0OTEzNiwicGF0aCI6Ii8yODIwMjAxMC8zNTE0NDAwODEtZjc1NjUwZGUtY2UzMS00MmYyLTkzMDEtM2IyZjgwOWZmNTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEyNTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNmM1NGE4ZDhjZjYxMjdkYWVjMjg3MTNiNmJhYWY5ZDE1YjA3NjhiNjJjNmRmMmQ3OWFmMzczNGI5NmVmMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vBcFyicAvmL5r44oNHi1IqLv81DsdOmrYiUnWB_-3NE)

I also have this type error.

![CleanShot 2024-12-09 at 22 13 05@2x](https://github.com/user-attachments/assets/9bd11e36-ca24-463f-ab0c-0aade2fc0579)

**Comment by uu29** [comment]
> Hello @CyrilQuandalle,
> 
> You do not persist `children` into both `ValueContainer` components. This is the main problem, as `children` contains an `<input>` element which is used for focus handling of the `Select` component. You can apply a filter onto `children` to remove any component related to selected options.
> 
> ```js
> const noValueChildren = React.Children.toArray(children).filter(
>   child => [components.Input, components.Placeholder].includes(child.type)
> );
> ```

When using multi-select, clicking on an external DOM after selecting only one item does not work properly. This method only functions correctly when two or more items are selected.
