### ISSUE TITLE
Field doesn't reset filter value

### ISSUE THREAD

**Issue by tema87** [JedWatson/react-select#561]
1. Go to http://jedwatson.github.io/react-select/
2. Click on multiselect field:
![2015-11-02 13 52 36](https://cloud.githubusercontent.com/assets/1525524/10880067/42482b8c-8169-11e5-824d-357792cc7cf9.png)

3. Type something:
![image](https://cloud.githubusercontent.com/assets/1525524/10880012/c7edcf22-8168-11e5-8fbb-acca783f247d.png)

4. Click anywhere outside the field:
![2015-11-02 13 49 56](https://cloud.githubusercontent.com/assets/1525524/10880141/c91640fe-8169-11e5-92a3-bd4d948b1543.png)

5. Click again on the field:
![2015-11-02 13 50 04](https://cloud.githubusercontent.com/assets/1525524/10880157/ea1bf2d0-8169-11e5-9083-1e572d328c0f.png)

**Result:** there are no options

I think it would be better if field will reset filter value after onblur-event.

**Comment by JedWatson** [comment]
Fixed in version 1.0.0

**Comment by mqklin** [comment]
@JedWatson , can you show this commit, please?
