### ISSUE TITLE
Yarn audit fails

### ISSUE THREAD

**Issue by LubosK** [JedWatson/react-select#5615]
I just install a new fresh next.js app and only your latest version of react-select specifically "5.7.2".

When I run `yarn audit` I got following error.
![image](https://user-images.githubusercontent.com/15995793/234212074-68084485-3042-4395-97e1-61030d13bdfb.png)

**Comment by Methuselah96** [comment]
This is not something `react-select` can fix itself, we're waiting on https://github.com/emotion-js/emotion/issues/3024 and/or https://github.com/kentcdodds/babel-plugin-macros/pull/193.

**Comment by LubosK** [comment]
for those who cannot wait until this issue will be fixed, as temporary! solution you can force to use yaml version "2.2.2" if you define in `package.json` in `resolutions` part the version you need to use.
e.g.
` "resolutions": {
    "yaml": "2.2.2"
  },`
  
But be careful and check it twice to ensure it doesn't cause you any other issues

**Comment by Methuselah96** [comment]
Also worth noting that some on `babel-plugin-macros` are of the opinion that this the security vulnerability [does not affect the users of babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros/issues/192). For most I imagine this doesn't matter, but there's likely no real security vulnerability here.

**Comment by Methuselah96** [comment]
This should be resolved now (https://github.com/kentcdodds/babel-plugin-macros/issues/192#issuecomment-1527703093).
