### ISSUE TITLE
Adding an onChange function hides the selected value

### ISSUE THREAD

**Issue by Siyfion** [JedWatson/react-select#562]
If I use the select input with no `onChange` function defined, when I select something it stays in the input window, as soon as I add an `onChange` when I select something the input empties itself.

While the answer may be obvious to some, perhaps this needs to be put into the docs for clarity?

**Comment by camallen** [comment]
Ran into this too. You have to update the state, see [this example](https://github.com/JedWatson/react-select/blob/15a06acc5e9d17776fd468d80ec8ea0eaaf6e2a0/examples/src/components/MultiSelectField.js#L21).

**Comment by Siyfion** [comment]
I thought that, so I adjusted my code as per below, but it still doesn't work...

```jsx
SearchBar = React.createClass({
  mixins: [ReactMeteorData],
  getMeteorData() {
    let handle = Meteor.subscribe("site-names");
    return {
      isLoading: !handle.ready(),
      sites: Sites.find({}).fetch()
    }
  },
  handleChange(selectedSite) {
    this.props.onUserInput(selectedSite);
    this.setState({
      value: selectedSite
    });
  },
  render() {
    // If the data isn't ready yet, show a loading spinner
    if (this.data.isLoading) {
      return <Loading />;
    }

    let options = _.chain(this.data.sites)
      .map((site) => {
        return { value: site._id, label: site._id.toUpperCase() };
      })
      .sortBy('label')
      .value();

    // Render the react select control
    return (
      <Select
        name="site-select"
        options={options}
        onChange={this.handleChange}
        matchProp='label'
        />
    );
  }
});

```

**Comment by camallen** [comment]
Reference the value in the component definition ala [here](https://github.com/JedWatson/react-select/blob/15a06acc5e9d17776fd468d80ec8ea0eaaf6e2a0/examples/src/components/MultiSelectField.js#L38)

``` JavaScript
<Select multi value={this.state.value} />
```

**Comment by Siyfion** [comment]
Ah doh! I'm an idiot. Apologies! Thanks, @camallen!

**Comment by camallen** [comment]
it caught me out too!
