### ISSUE TITLE
autofocus on render

### ISSUE THREAD

**Issue by TrkiSF2** [JedWatson/react-select#563]
Is it possible to have autofocus behaviour? Or after component is mount to force focus on input? Can't make it work.

**Comment by JedWatson** [comment]
Just added an `autofocus` prop, but calling `.focus()` on the ref for the component should work as well.

**Comment by TrkiSF2** [comment]
@JedWatson okay nice. I updated the lib. .focus() was not working for some reason but I realised I was using 0.8.2 so maybe in latest ones it would work. Thx
