### ISSUE TITLE
Change `getOptionLabel` type

### ISSUE THREAD

**Issue by beerose** [JedWatson/react-select#5633]
Is there a reason why a function passed to `getOptionLabel` has to return a string? Based on the code, it can render a React component. (I'm also using it as `o => ReactElement` and it works fine). 

I'd be happy to send a PR that updates the types, examples, and docs.

**Comment by Methuselah96** [comment]
Yes, it returns a `string` for accessibility reasons (so that it can be read by a screen reader).

**Comment by beerose** [comment]
Ok, that makes sense. Thanks!
