### ISSUE TITLE
autoloadAsyncOptions and componentWillReceiveProps conflict, causing infinite load

### ISSUE THREAD

**Issue by jtadmor** [JedWatson/react-select#564]
This is probably something of an edge case, but I have a situation where I have an initial set of options but am making an API call to make the full list. I am also using the asyncOptions feature to allow the user to enter custom values.

What happens now is autoloadAsyncOptions gets called, but before it can finish, the component receives my updated list of options, and componentWillReceiveProps gets called, which turns around and calls loadAsyncOptions but sends {} instead of { isLoading: false } for the state. This causes isLoading to remain true from the initial load.

I've disabled autoload for now, which doesn't seem like it causes any problems, but it also seems that componentWillReceive props should send { isLoading: false } if isLoading is true when it is called.

**Comment by JedWatson** [comment]
This should be all sorts of fixed after the big rewrite. let me know if you have any issues with the new version.
