### ISSUE TITLE
react-input-autosize inputWidth Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by janryWang** [JedWatson/react-select#567]
When I use the "Async options" feature and the "multi" feature, the system will be very easy to throw an error Uncaught RangeError: Maximum call stack size exceeded, and I monitor the call times of  setState  , I found setState always call in an infinite loop, and has been in the value of a “inputWidth” passed to it.

**Comment by JedWatson** [comment]
Thanks for the heads up @janryWang. I've fixed the issue in `react-input-autosize` and pushed a new version, so this should be fixed now.
