### ISSUE TITLE
multiselect end

### ISSUE THREAD

**Issue by jvillasante** [JedWatson/react-select#57]
It would be nice to have an option to end the multiselect, I mean, after selecting 3 elements (for example) it would be nice to end the selection (if user wants to).

**Comment by JedWatson** [comment]
Do you mean to have a max. number of options that can be selected?

**Comment by dcousens** [comment]
This could be done by having your own `onChange` handler that limits the user to 3 options.   Closing as it is super easy to do this at the parent level.

**Comment by dcousens** [comment]
Though,  @JedWatson what might be necessary is a `limited` prop, which stops the user from adding more, but they can still be `clearable` and **not** `disabled*.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/JedWatson/react-select/issues/174

**Comment by k2kkapoor** [comment]
Hello I have an issue that i have huge amount of data and disabling multiselect takes a lot of time using function like: $("#mymultiselect").multiselect("disable"); but for large amount of data it is taking a lot of time, can anybody suggest some simpler and faster way to achieve this.
