### ISSUE TITLE
Can't use object as value in options

### ISSUE THREAD

**Issue by super-cache-money** [JedWatson/react-select#572]
This would be nice. It currently throws errors since I assume it uses the value for the key. Maybe we could allow specification of the key in options?

**Comment by JedWatson** [comment]
There's a `valueKey` prop for that

**Comment by JedWatson** [comment]
@super-cache-money I'm going to close this, please reopen if I've misunderstood what you're trying to do.

**Comment by ersefuril** [comment]
@super-cache-money is in fact speaking about a non-implemented feature.
What should be interesting is to pass Objects into this option's values :

var options = [
    { value: **someObject**,, label: 'One' }
];
