### ISSUE TITLE
Customized searchable options in the dropdown after selecting once.

### ISSUE THREAD

**Issue by kuldeep-dadheech** [JedWatson/react-select#5725]
### Discussed in https://github.com/JedWatson/react-select/discussions/5724

<div type='discussions-op-text'>

<sup>Originally posted by **kuldeep-dadheech** August 11, 2023</sup>
I have to create a dropdown in which once a value is selected by the user then the options should change and one search input should appear and the user can select a value from them<img width="685" alt="Screenshot 2023-08-11 at 6 38 59 PM" src="https://github.com/JedWatson/react-select/assets/106507147/deffe38e-f253-41e3-9cea-607f589bbbf2"></div>

**Comment by Rall3n** [comment]
@kuldeep-dadheech Please do not promote a discussion into an issue if it has not been identified as such.

Closing as not an issue, but implementation question.
