### ISSUE TITLE
Any chance to use it with React 0.13.3 ?

### ISSUE THREAD

**Issue by asso1985** [JedWatson/react-select#573]
I'm in the need of using it in an environment that now can't update to 0.14, is there any chance at all ?

**Comment by jabhishek** [comment]
[This] (https://github.com/JedWatson/react-select/tree/65ec63ef0ff9961b6111de68d5ddd6fc0afb275f) was the last commit that used React 0.13.3 before upgrading to 0.14.0. Try using that?

**Comment by JedWatson** [comment]
use version `0.6.3`, which was the last version released with React 0.13 support.

the latest version is written with React 0.14 in mind, it would be too complicated to continue providing backwards compatibility, sorry!
