### ISSUE TITLE
Value not working with space separation. (1.0.0-beta2)

### ISSUE THREAD

**Issue by zackify** [JedWatson/react-select#576]
<img width="2477" alt="screen shot 2015-11-06 at 10 38 16 am" src="https://cloud.githubusercontent.com/assets/449136/11000952/971b9232-8472-11e5-83d6-62ade94e06da.png">

If the value has a space in it, the select box shows no selected value by default. I would fix it if I had time to dig into it, I don't today.

**Comment by zackify** [comment]
It was my fault, the old version would display whatever you passed in, this one checks if the value is an option value.

**Comment by JedWatson** [comment]
Got a lot more strict with this version, means things don't "just work" as often but "work properly" _more_ often :)

**Comment by zackify** [comment]
I didn't want to handle state. Is there any way to not have to do that?

**Comment by JedWatson** [comment]
I'm open to shipping a wrapper control that manages state for you, managing value with state in the component before the rewrite was a real nightmare and the source of a lot of issues.

**Comment by zackify** [comment]
Yeah I know it's not a really good thing to do. Just wondering thanks.
