### ISSUE TITLE
Provide an example, how to use new Select.Async

### ISSUE THREAD

**Issue by TrkiSF2** [JedWatson/react-select#578]
"The asyncOptions prop has been replaced by a new wrapper component: Select.Async"

Could you add into documentation an example how to use it?

**Comment by lanmengyujing** [comment]
thank you for the information, it really hard to found that.

**Comment by akhayoon** [comment]
@TrkiSF2 
I'm kind of confused on exactly how to use this. For example where do I make my ajax call in the getUsernames function?

**Comment by TrkiSF2** [comment]
I pasted it here.

getUsernames: function(query, callback) {
        $.get(http://youApi) + '?q=' + Validation.keepAlphaNumeric (query))
            .done(function(response) {
                callback(null, {options: response.usernames})
            });
    },
