### ISSUE TITLE
Return custom id instead of value

### ISSUE THREAD

**Issue by jvillasante** [JedWatson/react-select#58]
It would be nice to have an option to pass custom data that would be passed on to handleSelect.
something like:

```javascript
options.push({
  label: 'label',
  value: 'value',
  id: 494949494
});
```

`id` being the value i want to get back later on selection/deletion.

**Comment by Gregoor** [comment]
+1

**Comment by cmnstmntmn** [comment]
:+1:

**Comment by dcousens** [comment]
@jvillasante is there any reason you can't just have a look up?  Meaning we can leave the implementation as simple as possible?
I don't expect the lists to ever have duplicates?

**Comment by dcousens** [comment]
Closing in favour of #194
