### ISSUE TITLE
Autoopen options list

### ISSUE THREAD

**Issue by EnchanterIO** [JedWatson/react-select#580]
With those options the remote data are loaded immediately after component is mounted and the loading icon is visible. I think it should be appropriate to display directly list of options when load finishes so the user doesn't have to start typing to see the loaded options.

```
            <Select.Async
                loadOptions={this.getUsernames}
                autofocus
```

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
