### ISSUE TITLE
Grouping items?

### ISSUE THREAD

**Issue by jk171505** [JedWatson/react-select#581]
Is this possible to group items in the dropdown list? Something equivalent to opt group?

**Comment by mmahalwy** [comment]
Find a way to make this happen?

**Comment by max-mykhailenko** [comment]
@jk171505 @JedWatson @mmahalwy Are you solve this issue?

**Comment by max-mykhailenko** [comment]
I find pull request for this. I'll wait merge https://github.com/JedWatson/react-select/pull/480
