### ISSUE TITLE
Lock down dependencies

### ISSUE THREAD

**Issue by texttechne** [JedWatson/react-select#583]
Dependencies should be locked down for release builds. Otherwise bugs in those dependencies will affect `react-select`. Current problem which raises this issue: https://github.com/JedWatson/react-input-autosize/issues/26

Either npm-shrinkwrap should be used or at least both dependencies should be set to a defined version, i.e. without the leading `^`; like so:
```
"dependencies": {
    "classnames": "2.1.5",
    "react-input-autosize": "0.6.2"
  }
```

**Comment by Webkadabra** [comment]
I got into this issue right now as well. Damn, this is unfortunate!
