### ISSUE TITLE
Uncaught Error: Cannot find module './Select'

### ISSUE THREAD

**Issue by radleta** [JedWatson/react-select#584]
I'm trying to pull in the npm react-select@1.0.0-beta5 via browserify. I'm getting the below error.

```
Uncaught Error: Cannot find module './Select'
...
require.243../Select @ Async.js:11
...
require.react-select../Async @ Select.js:31
...
```

It appears the recursive reference between Async and Select is causing the relative path not to resolve properly. Any ideas?

**Comment by JedWatson** [comment]
That's strange, I'm not having any trouble with browserify in the examples or a couple of projects. Which version are you using?

**Comment by radleta** [comment]
I'm using *browserify@6.2.0* and *browserify-shim@3.8.10*.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
