### ISSUE TITLE
selector cannot select any option in IE

### ISSUE THREAD

**Issue by duoduoin** [JedWatson/react-select#585]
We open a dropdown for selector, the option cannot be selected, and the dropdown cannot disappear automatically.

**Comment by JedWatson** [comment]
@duoduoin can you please confirm which version you're using?

**Comment by duoduoin** [comment]
@JedWatson I tested it in IE9. When I open the example page: http://jedwatson.github.io/react-select/, all the components in this page are broken.

**Comment by martin-jujou-sirca** [comment]
I am getting this as well - although for some reason the example page works in IE

When opening the select it shows the options but displays the error
```
SCRIPT65535: Invalid calling object 
```
in the console, and you cant select an item.

Tested under IE 10. There doesnt seem to be anything special with my sample:

```
import React, { Component } from 'react';
import Select from 'react-select';

class Test extends Component {

  constructor() {
    super();
  }

  render() {
    const options = [
      { value: 'one', label: 'One' },
      { value: 'two', label: 'Two' },
    ];

    return (
      <Select
        className="SearchReport-lender"
        placeholder="Lender"
        options={options}
        tabIndex="1"
      />
    );
  }
}

export default Test;

```

**Comment by martin-jujou-sirca** [comment]
Never mind, seems to be related to this PR: https://github.com/JedWatson/react-input-autosize/pull/30

**Comment by davey-h** [comment]
Sorry, I'm a bit lost, is this fixed? The related PR seems to be for auto-size. Maybe I'm missing something. Thanks

**Comment by martin-jujou-sirca** [comment]
For me the issue was related to the dependency lib autosize

**Comment by blakedietz** [comment]
Platform: Windows 7
Browser version: Internet Explorer 9

@duoduoin @JedWatson I can confirm that this bug is still a problem. It looks like @martin-jujou-sirca was referring to IE10 instead.

**Comment by blakedietz** [comment]
So although this original issue is not about IE10 I wanted to make sure that people are aware that IE10 does not work with the examples page. The reason being that there does not seem to be a polyfill for promises in the page.

If you check out the examples yourself and include babel-polyfill, all examples will work in the examples page.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
