### ISSUE TITLE
Dont't clear Input on onBlur

### ISSUE THREAD

**Issue by slybridges** [JedWatson/react-select#588]
I noticed that when `Select` is blurred, the `onBlur` event clears the input text field: https://github.com/JedWatson/react-select/blob/master/src/Select.js#L215

How can I disable this behaviour and keep whatever the user has started typing ?

**Comment by JedWatson** [comment]
I'm open to adding an `onBlurResetsInput` prop (default true) that prevents this behaviour... PR welcome, as I'm travelling for the next week, otherwise I'll get to it when I'm back.

**Comment by slybridges** [comment]
Hi @JedWatson, thanks, I've created the PR as suggested.
Let me know any comment.

And great job on `react-select` by the way! (should have started with this, how rude of me)

**Comment by Kola-Kola** [comment]
Any update in v3 ?

**Comment by gitowiec** [comment]
@JedWatson How to not clear the input value on blur?

**Comment by alita-moore** [comment]
@gitowiec you have two work around options

Here's the best way that I've found, it's a rough work-around and this feature is probably way easier to just program into the source code; I might make a PR later if desired.
```
const App = () => {
	const [input, setInput] = useState("");
	const [inputSave, setSave] = useState("");
	const options = [... your options ...]
	
	const onSelect = (value) => {
		setSave(input); // this needs to be set here because directly after 
				// the onInputChange is called with "" i.e. input is
				// cleared
	}
	
	return (
		<Select
			placeholder={inputSave} // when blurred & value == "" this shows
			value="" // always show placeholder
			inputValue={input} // allows you continue where you left off
			onInputChange={setInput} // allows for actually typing
			options={options}  
			onChange={onSelect}
			onFocus={() => setInput(inputSave)} // input will be cleared regardless
		/>
	)
}
```
This keeps the search on select, meaning that when you type input, select, the select bar will keep a placeholder of the input and then when you click on it again it will continue where you left off

**Comment by AlexLomm** [comment]
A little less hacky way would be to watch for the actual user-initiated input changes by checking the `action` argument of the `onInputChange()`.

Example:

```jsx
export default function App() {
  const [input, setInput] = useState("");

  const options = [
    { label: "first option", value: 1 },
    { label: "second option", value: 2 },
    { label: "third option", value: 3 }
  ];

  return (
    <Select
      options={options}
      inputValue={input}
      onInputChange={(value, action) => {
        // only set the input when the action that caused the
        // change equals to "input-change" and ignore the other
        // ones like: "set-value", "input-blur", and "menu-close"
        if (action.action === "input-change") setInput(value); // <---
      }}
    />
  );
}
```

**Comment by javascript-alex** [comment]
@AlexLomm thanks for your solution. However, if you select a value from the options now, the value will not be displayed anymore. In your CodeSandBox and in my app is it the same behaviour.

**Comment by javascript-alex** [comment]
I would suggest something like this. With this approach it worked for me.

`
export default function App() {
  const [input, setInput] = useState("");

  const options = [
    { label: "first option", value: 1 },
    { label: "second option", value: 2 },
    { label: "third option", value: 3 }
  ];

  return (
    <Select
      options={options}
      inputValue={input}
      onInputChange={(value, action) => {
       if (actionMeta?.action !== 'input-blur' && actionMeta?.action !== 'menu-close') {
	setValue(newValue);
	}
      }}
    />
  );
}
`

**Comment by Minozzzi** [comment]
> If anybody else experienced the same problem I have written above, try this. The code below worked for me.
> 
> ```js
> export default function App() {
>   const [input, setInput] = useState("");
> 
>   const options = [
>     { label: "first option", value: 1 },
>     { label: "second option", value: 2 },
>     { label: "third option", value: 3 }
>   ];
> 
>   return (
>     <Select
>       options={options}
>       inputValue={input}
>       onInputChange={(value, action) => {
>        if (action?.action !== 'input-blur' && action?.action !== 'menu-close') {
> 	setInput(value);
>        }
>       }}
>     />
>   );
> }
> ```

@javascript-alex it's worked for me, why works? 
Thanks for solution :D

**Comment by netgfx** [comment]
any idea how to do this when usint Controller from `react-hook-form`?

**Comment by Dakuan** [comment]
i tried this but every keystroke blurred the input...
