### ISSUE TITLE
Custom keys for values?

### ISSUE THREAD

**Issue by lifehackett** [JedWatson/react-select#590]
I've set the `labelKey` and `valueKey` and the options are being displayed as expected, but it doesn't seem to apply to the `values` prop.  This was unexpected.  Am I missing something? Is their some limitation that prevents this?

(Note: I am using v0.6.12 due to our version of React)

**Comment by JedWatson** [comment]
I'm afraid that's probably a bug in `0.6.12`, you're welcome to submit a PR against that branch if you like but I won't be able to jump in and fix unfortunately.

A workaround would be to re-map your options to use the default keys for label and value before passing them to `Select` until you're able to update to the new version.

**Comment by lifehackett** [comment]
Gotcha.  That's what I'm doing, but thought I'd remove some code and take advantage of the property.  I think we are upgrading React next sprint so should be able to take advantage soon.

Thanks for your response and great work on this product.

**Comment by JedWatson** [comment]
No worries! Happy to have made something so many people find useful :)

Good luck with the upgrade!
