### ISSUE TITLE
worst thing ever see in my life

### ISSUE THREAD

**Issue by AnandPatel404** [JedWatson/react-select#5909]
is se worst chiz aj tak mene nahi dekhi ek dam chutya chiz hai ye is se to acha me apna khud ki ek library create karlu vo bhi kuch achi chalengi

**Comment by cutterbl** [comment]
@AnandPatel404 You do you, Boo. Some of us are very thankful for it.

**Comment by Geowan** [comment]
@AnandPatel404 Why post such nonsense here. If you dont like the package why not just create yours and use it privately. I like this package, its not like your have a hammer on your head to use it. Be respectful of other peoples work. Looking at your profile i see a bunch of forked repo's which speak much about your character as a developer.
