### ISSUE TITLE
I can't install @0.6.3

### ISSUE THREAD

**Issue by jovey-zheng** [JedWatson/react-select#593]
Using react#0.13.3 and node#0.12.7, the error info below:

```
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer boron@0.1.2 wants react@>=0.12.0
npm ERR! peerinvalid Peer halogen@0.1.10 wants react@>=0.12.0
npm ERR! peerinvalid Peer react-autosuggest@1.18.3 wants react@^0.13.3
npm ERR! peerinvalid Peer react-data-components@0.5.0 wants react@^0.13.0
npm ERR! peerinvalid Peer react-dropzone@2.2.4 wants react@>=0.13
npm ERR! peerinvalid Peer react-modal@0.3.0 wants react@>=0.13.3
npm ERR! peerinvalid Peer react-sticky@2.5.2 wants react@0.x
npm ERR! peerinvalid Peer react-dom@0.14.2 wants react@^0.14.2
npm ERR! peerinvalid Peer react-select@0.6.3 wants react@>=0.13.3
npm ERR! peerinvalid Peer redbox-react@1.1.1 wants react@>=0.13.2 || ^0.14.0-rc1

npm ERR! Please include the following file with any support request:
```

how can i fix it?

**Comment by cjhveal** [comment]
I think you've got `react-dom@0.14.2` installed which depend on a peer version of `react@^0.14.2`. Since you're using `react@0.13.3`, it will complain about invalid peers. React `0.13.x` included `ReactDOM` explicitly, so you can likely remove it and use the copy included with React.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
