### ISSUE TITLE
React 19

### ISSUE THREAD

**Issue by kumarSNS** [JedWatson/react-select#5983]
Since React 19 is out, would it be possible to update the peer dependencies to include v19?

**Comment by Methuselah96** [comment]
Yes, can you create a PR? I think just the `peerDependencies` in `packages/react-select/package.json` would need to be updated.

**Comment by Thris3n** [comment]
I have added a PR to include version 19 on peer dependencies

**Comment by antlanc7** [comment]
Also it would be great to upgrade use-isomorphic-layout-effect in the packages/react-select/package.json to 1.2.0 for the same reason.

**Comment by Methuselah96** [comment]
@Thris3n Can you make that update to your PR as well?

**Comment by Thris3n** [comment]
@Methuselah96 added as well

**Comment by Methuselah96** [comment]
Fixed by https://github.com/JedWatson/react-select/pull/5984, released in [5.9.0](https://github.com/JedWatson/react-select/releases/tag/react-select%405.9.0).
