### ISSUE TITLE
IE11 exception when onBlur event

### ISSUE THREAD

**Issue by aceoftrumps** [JedWatson/react-select#600]
Hello. Highlighting does not disappear on blur event because of the exception. I attached 2 debugger screenshots for v0.9.1 and v1.0.0-beta5 . This issue is also reproduced on page with examples in IE11

v0.9.1
![v0 9 1](https://cloud.githubusercontent.com/assets/5478109/11212959/f1e2a7be-8d41-11e5-860e-5de760a1b052.png)

v1.0.0-beta5 .
![v1 0 0-beta5](https://cloud.githubusercontent.com/assets/5478109/11212965/f9f4759a-8d41-11e5-868d-c958353917a4.png)

examples page in IE11
![examples_page](https://cloud.githubusercontent.com/assets/5478109/11212998/31f72a46-8d42-11e5-8628-b846945bc914.png)

I use react 0.14.2

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
