### ISSUE TITLE
componentWillReceiveProps handles passing option as value incorrectly

### ISSUE THREAD

**Issue by wizhippo** [JedWatson/react-select#601]
When passing an option as a value componentWillReceiveProps will always fire a state change and if  using aysncOptions causing a fetch every time state is updated.  This checks to see if the value prop is an object and and handles this special case.

https://github.com/wizhippo/react-select/tree/v0.9.1-fix-value-check

I know there is the new v1.0.0 but it does not support create and tags yet so this is still needed and I was unable to create a PR against v0.9.1 as it is a tag.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
