### ISSUE TITLE
Component CSS is Not loaded

### ISSUE THREAD

**Issue by VictorSage** [JedWatson/react-select#602]
Installed version v0.9.1, I can use the component, but seems no CSS is loaded.

**Comment by pranav** [comment]
+1

**Comment by milesegan** [comment]
I'm seeing this as well. Also in 1.0.0-beta.

**Comment by pranav** [comment]
I ended up importing the css in my main.scss file to get it to work fyi
```
@import url('../../node_modules/react-select/dist/react-select.css');
```

**Comment by milesegan** [comment]
Thanks @pranav. That's a good workaround.

**Comment by Heboy** [comment]
I import default.scss in /node_modules/react-select/lib/Select.js
```javascript
require('../scss/default.scss');
```
it works too

**Comment by thirdknife** [comment]
for me it's still not working even after adding

`
require('../../node_modules/react-select/dist/react-select.css');
`

**Comment by VictorSage** [comment]
this is my work around: create a `package.json` file and include the following:
```
{
  "style": "style.scss"
}
```
add the following line in `style.scss` 
```
@import "react-select/scss/default";
```

**Comment by vzaidman** [comment]
+1

**Comment by brwinkle** [comment]
+1

**Comment by brwinkle** [comment]
This still seems to be present in the newest beta. I'm using browserify and trying to require the CSS file, but the transforms that allow me to do so that I've tried (partialify and browserify-css) don't seem to play well with babelify. This seems to be a long-standing issue and I'm wondering if there's a fix on the way.

**Comment by jonaskello** [comment]
+1

**Comment by bradparks** [comment]
+1

**Comment by cema-sp** [comment]
`import 'react-select/dist/react-select.css';` helped in my case (npm + webpack)

**Comment by rcoh** [comment]
I needed `import 'css!react-select/dist/react-select.css` as well as the webpack css module

**Comment by StevenLangbroek** [comment]
FYI, if you're using `css-loader` with `?modules` enabled, you can override its default behavior like so:

```js
:global {
  @import "~react-select/scss/select";
}
```

**Comment by dianjin** [comment]
Used @cema-sp's workaround, thank you! Wish there was a more elegant way to import the css though.

**Comment by jxm262** [comment]
@cema-sp  Thanks a ton :+1:   Took me a long time to finally stumble on this ticket.  Your're suggestion is working for me on webpack

**Comment by huvber** [comment]
I tried to add `import Select from 'css!react-select/dist/react-select.css'; ` in the main js and in the files where I used this component but doesn't style it

**Comment by mrconnormurphy** [comment]
+1

**Comment by cema-sp** [comment]
@huvber you should not import anything from css, just css itself (remove **Select from** from your import expression).

**Comment by anton6** [comment]
+1

**Comment by gojohnnygo** [comment]
This helped me. https://github.com/JedWatson/react-select/wiki#for-webpack

**Comment by craigcartmell** [comment]
@StevenLangbroek I had no idea you could do this. Such a life saver.

**Comment by SVITY** [comment]
@VictorSage 
It is problem because of you use css-modules. Easy way to fix it to use several loaders. The first is for local styles, the second is for node_modules.
```
{
 test: /\.css$/,
 include: /node_modules/,
 loader: 'style!css!postcss',

},
{
 test: /\.css$/,
 exclude: /node_modules/,
 loader: 'style!css?modules&localIdentName=[name]---[local]---[hash:base64:5]!postcss',
},
```

**Comment by ArunRamachandran** [comment]
@SVITY  Finally this helped me ! Thanks .

**Comment by SVITY** [comment]
@ArunRamachandran You are welcome!

**Comment by Startouf** [comment]
Hey @dimagimburg and @SVITY I'm quite new to React and it's not really wlear where I should put this code... Does this go somewhere in the webpack config ? Do I need NPM any dependency for this to work ?

**Comment by dimagimburg** [comment]
@Startouf It depends what dependencies would you like, I used CSS Modules for my css rendering into the component. The piece of code I pasted here is from my webpack.config.js

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
