### ISSUE TITLE
Document how to test with selenium

### ISSUE THREAD

**Issue by ben-manes** [JedWatson/react-select#603]
I'm having difficulty selecting an entry using webdriver. I can get as far as clicking on the input, but despite hacks have not yet been able to set the selection. A short guide on how to test this component would be appreciated.

**Comment by ben-manes** [comment]
A hack, but this seems to work.

```python
self.driver.find_element_by_class_name('Select-control').click()
wait = WebDriverWait(self.driver, timeout=10)
wait.until(EC.element_to_be_clickable((By.CLASS_NAME, 'Select-option')))
options = self.driver.find_elements_by_class_name('Select-option')
for option in options:
    if option.text == value:
        option.click()
        break
```

**Comment by radar** [comment]
I have some Ruby code for this:

```ruby
    first("#{element} .Select-input input").set(value)
    first("#{element} .Select-option").click
```

Setting the input's value will populate the component with the options that match that name. Then it's just a matter of clicking on that first option.

**Comment by mipearson** [comment]
Here's what we settled on for poltergeist/phantomJS. The trick is the keypresses need to be "sent" for it to work - can't just "set" the value of the hidden field.

```ruby
    within(select_container_element) do
      find(".Select").click
      find(".Select").native.send_key(desired_option)
      find(".Select-option", text: desired_option).click
    end
```

**Comment by DanielSundberg** [comment]
In C#/Seleno I had to do the following to get it to work:

    public void SetSelectText(string optionText) {
        var select = Find.Element(By.CssSelector(".Select"));
        select.Click();
        var options = Find.Elements(By.CssSelector(".Select-option")).ToList();
        options.ToList().Single(o => o.Text == optionText).Click();
    }

At least some response whether this is prioritized or not would be nice.

**Comment by etburke** [comment]
I can't seem to get anything working with NightwatchJS.

**Comment by oren** [comment]
The following works for me: 

In the IDE:
```
Command: sendKeys
Target: css=div.Select-control input
Value: Allergies${KEY_ENTER}
```

And the Java translation:
```
driver.findElement(By.cssSelector("div.Select-control input")).sendKeys("Allergies" + Keys.ENTER);
```

https://groups.google.com/forum/#!topic/selenium-users/FWsu_r7bbr0

**Comment by jackTheRipper** [comment]
Hey,

I faced the same issue, here is my solution for the Nightwatch:

```
const util = require('util');
const events = require('events');

function selectOption() {
  events.EventEmitter.call(this);
}

util.inherits(selectOption, events.EventEmitter);

/**
 * Click an option in a select in rwd_cheaptickets_nl
 * It injects a script which triggers the events expected by the listeners in the core component.
 * @param {String} itemSelector The selector of the section where the select is.
 * @param {String} selectSelector Optional, the selector of the select. Default value: '.dropdow__element'.
 */
selectOption.prototype.command = function command(itemSelector, selectSelector = '.dropdown__element', callback) {
  this.api.execute((itemSel, selectSel) => {
    // eslint-disable no-undef
    var item = document.querySelector(itemSel); // eslint-disable-line no-var
    var select = item.parentNode.querySelector(selectSel); // eslint-disable-line no-var
    var evt = document.createEvent('MouseEvents'); // eslint-disable-line no-var
    evt.initEvent('mousedown', true, true);

    select.children[0].click();

    item.parentNode.getElementsByTagName('li')[1].children[0].dispatchEvent(evt);
    // eslint-enable no-undef
  }, [itemSelector, selectSelector], () => {
    if (typeof callback === 'function') {
      callback.call(this);
    }
    this.emit('complete');
  });

  return this;
};

module.exports = selectOption;
```

In fact the select is activated on the MouseDown event, here we fake it by injecting some code

**Comment by mfpiccolo** [comment]
For those of you trying to work with nightwatch and multiselect, I was able to get this to work with multi select using:

```
      .click('.custom-class')
      .click('.custom-class .Select-option[id*="-option-1"]')
```

**Comment by kgunbin** [comment]
I've came up with a custom command for NightwatchJS which worked for me:
`commands/setReactSelect.js`
`
exports.command = function(selector, data) {
  var select = selector + ' .Select .Select-control';
  var item = selector + ' .Select .Select-menu .Select-option';
  var self = this;

  return this
    .waitForElementVisible(select, 1000)
    .click(select)
    .waitForElementVisible(item, 1000, function() {
      self.executeAsync(
        function() {
          var item = arguments[0][0];
          var data = arguments[0][1];
          var parent = arguments[0][2];

          var multi = Array.isArray(data);

          if(!multi) {
            data = [data];
          } else {
            // Close the dropdown after a second when all events are hopefully dispatched
            setTimeout(() => document.querySelector(parent + ' .Select-input input').blur(), 1000);
          }

          data.forEach((label) => {
            var option = Array.prototype.find.call(
              document.querySelectorAll(item),
              (e) => label == e.innerHTML
            );

            option.dispatchEvent(new MouseEvent('mousedown', {bubbles: true}));
          });
        },
        [[item, data, select]] // Pack params into an array, as Selenium works correct with a single parameter only
      );
    }).waitForElementNotPresent(item, 4000);
};
`
and the respective test
`
module.exports = {
  'Select Tasmania': function(browser) {
    var states = '#example .section';
    browser
      .url('https://jedwatson.github.io/react-select/')
      .setReactSelect(states, 'Tasmania')
      .waitForElementVisible('div.Select-value.State-Tas',  5000)
      .end();
  },

  'Select Chocolate and Peppermint': function(browser) {
    var root = '#example .section:nth-child(2)';

    browser
      .url('https://jedwatson.github.io/react-select/')
      .setReactSelect(root, ['Peppermint', 'Chocolate'])
      .waitForElementPresent(root + ' span.Select-value-icon', 5000) // Just assume any value is there
      .end();
  }
}
`
Hope this helps someone.

**Comment by joechromo** [comment]
This one worked for me: 

`.click('.Select-value-label')
   .click('.Select-option[id*="-option-1"]')`

**Comment by RamadhanaRey** [comment]
Hi @oren how to handle next field with your selenium IDE command?
i have problem with next field, because the target always input on a first field..

**Comment by gor181** [comment]
What @radar proposed also works nicely in nightwatch alike syntax:

```
const commands = {
  fillSignUpInformation(email) {
    return this
      .setValue('@email', email || chance.email())
      .setValue('@password', 'somepw')
      .setValue('@companyName', 'company')
      .setValue('@phoneNumber', '+11234567890')
      .setValue('.Select-input input', 'United States')
      .click('.Select-option');
  },
  register() {
    return this.click('@submit');
  },
};
````

**Comment by PashminaT** [comment]
Has anyone got an example for selenium webdriver in java please?

**Comment by Roscian1Frank** [comment]
@PashminaT 
Java version 
`driver.findElement(By.className("Select-control")).click();
        WebDriverWait wait = new WebDriverWait(driver,10);
        wait.until(ExpectedConditions.elementToBeClickable((By.className("Select-option"))));
        List<WebElement> options = driver.findElements(By.className("Select-option"));
        for(WebElement option: options){
            if (option.getText().equalsIgnoreCase(clientName)){
                option.click();
                break;
            }
        }`

**Comment by Olliebaba** [comment]
@Roscian1Frank  - your example worked for my team. Thanks!

**Comment by rocastaneda** [comment]
Command: sendKeys
Target: css=div.Select-control input
Value: 1
+
Command: click
Target: id=react-select-2--option-0

This works for me

**Comment by pietrofxq** [comment]
@Roscian1Frank could you make it work with latest versions? I cannot find a way to trigger click in the select and open the dropdown with webdriver

**Comment by Roscian1Frank** [comment]
Hi @pietrofxq,

My above example is still working for me on Selenium V3.14.0.
Need more details for investigation. 
Thanks 
Roscian

**Comment by Vyshnavi-N** [comment]
what does (clientName) in the code signify?

 if (option.getText().equalsIgnoreCase(clientName)){

**Comment by Roscian1Frank** [comment]
@Vyshnavi-N 
`ClientName = Dropdown value `

**Comment by brendadev** [comment]
anyone has an example using selenium/mocha/nodejs?

I want to test clicking on multi-select and select one or more options

**Comment by kfox112** [comment]
For anyone using nightwatch and the chrome driver, this is what worked for me (custom command):

`exports.command = function(selector, data) {

    // Turn any numbers into a string
    keysToSend = "" + data;

    // Split the string on each character into an array of keys
    keysToSend = keysToSend.split("");

    // Hit enter after characters are typed
    keysToSend.push("\n");

    return this
        .waitForElementVisible(selector, 1000)
        .click(selector)
        .keys(keysToSend);
};
`

**Comment by jossmac** [comment]
Please reserve the GitHub issue tracker for bugs and feature requests. [StackOverflow](https://stackoverflow.com/questions/tagged/react-select) would be more appropriate for this sort of discussion.

**Comment by DanielSundberg** [comment]
Why close? This was reported as a documentation bug. Stackoverflow is not really the place for documentation of a custom component. The OP + many others including me wanted the creator of the component to document how it could be tested since automated testing is a first class citizen since many years.

Perhaps testing the component also could be made a bit easier.

Anyway, I'm not using the component any more so feel free to ignore my comment.
