### ISSUE TITLE
Is it possible to add id and ref attributes to the generated hidden input?

### ISSUE THREAD

**Issue by tkiethanom** [JedWatson/react-select#604]
Is it possible to add id and ref attributes to the generated hidden input? So far I haven't found a way to add attributes to the hidden input.

**Comment by robtweed** [comment]
I'd also find such a feature very useful.  Without being able to define a ref for the text input field, it's not possible to invoke its focus() method as there's no way to reference the element

**Comment by hank7444** [comment]
+1, I want to focus the hidden input

**Comment by DanBradbury** [comment]
bump

**Comment by Petesta** [comment]
@JedWatson This appears to be a problem with the `jsx-a11y/label-has-for` rule for `eslint`. In the generated hidden input we're missing an `id` and there is no way to specify this. This behavior conflicts with the aforementioned rule.

What can be done to help fix this?

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md

https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/51

**Comment by lbalceda** [comment]
+1

**Comment by rubencodes** [comment]
I second the issue mentioned by @Petesta.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
