### ISSUE TITLE
Support for form onChange

### ISSUE THREAD

**Issue by lukemorton** [JedWatson/react-select#605]
Would be great if react-select triggered an synthetic event on the form with a target name and value.

Is this feature planned at all?

**Comment by radar** [comment]
@drpheltright It might help here to show some code that explains what you're trying to accomplish.

**Comment by drpheltright** [comment]
I'd like to handle the synthetic event at the form rather than on the input itself:

``` html
<form onChange={this.handleFormChange.bind(this)}>
  <Select name="form-field-name"
          value="one"
          options={options} />
</form>
```

**Comment by devzsolt** [comment]
any plans on this? or an existing simple workaround?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
