### ISSUE TITLE
Click outside element not working

### ISSUE THREAD

**Issue by rlesniak** [JedWatson/react-select#607]
With option `searchable={false}` click outside `react-select` element doesnt close itself. 
Is this intended behavior?

**Comment by hank7444** [comment]
+1

**Comment by VanDavv** [comment]
+1

**Comment by yahyazini** [comment]
+1

**Comment by agirton** [comment]
@yahyazini this issue is almost two years old and is currently working on the latest build. Do you have steps to reproduce?

**Comment by davidchase** [comment]
@agirton i have a somewhat similar issue

https://codesandbox.io/s/534j7y18ol

if you look at that sandbox and you click on the dropdown arrow and then click outside somewhere it doesnt close the dropdown

however if you visit the demo page http://jedwatson.github.io/react-select/ and try any of the dropdown arrows and click outside they always close

any ideas? thanks

**Comment by Dsweih** [comment]
I have got the same issue as what @davidchase has described. It works as expected when clicks input and then clicks outside of it, whereas it does not work when clicks the drop-down arrow.

Thanks

**Comment by davidchase** [comment]
current work around for our team was to revert back to v1.0.0rc10

**Comment by parthsr** [comment]
Why is this bug unconfirmed? It can be easily reproduced by passing `searchable={false}` as props. When clicked outside the `react-select`, the dropdown does not close.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
