### ISSUE TITLE
Value is assumed to be string

### ISSUE THREAD

**Issue by sudodoki** [JedWatson/react-select#61]
https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L367 this code might break if values is number instead of string.
Thanks for the component.

**Comment by julen** [comment]
This is a dupe of #25.

**Comment by dcousens** [comment]
@JedWatson unless you have a change of heart on this/#25.  Closing.

**Comment by dcousens** [comment]
Duplicate.
