### ISSUE TITLE
0.9.1 stop async search when value is selected

### ISSUE THREAD

**Issue by JonathanStevensFN** [JedWatson/react-select#622]
Is there a way to stop the asyncOptions from being called when I select an option? My need is to use Promises (using the fetch api) to get values from the server based on what the user types. When the select from the list of options I notice another call is made with no input to my async get options. The server does what it is supposed to and returns an empty list. 

I want to stop the enter or selection fire another call to the get options,

Thanks

**Comment by radar** [comment]
At the top of your request, stop the AJAX request like this:

```js
if (input.length < 1) return;
```

**Comment by radar** [comment]
My mistake, this will still show the loading spinner. I don't know of a good way to fix this.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
