### ISSUE TITLE
Should Props that render strings also allow Components?

### ISSUE THREAD

**Issue by MrLeebo** [JedWatson/react-select#624]
This sample
```
<Select 
  name='helpful-select'
  options={options}
  noResultsText={
    <span><em>No results found.</em> <a href='#' onClick={this.showHelp}>Would you like some help?</a></span>
  }/>
```

will work, but generates a warning
```
Warning: Failed propType: Invalid prop `noResultsText` of type `object` supplied to `Select`, expected `string`.
```

I think its useful to be able to embed links, buttons, and other components inside Text props and it shouldn't generate a warning.

The prop should be "noResults" and allow either strings or components, but that would be a breaking change. So the "noResultsText" could be deprecated and phased out over a couple of versions. Ditto for all the other properties that render text like this. Agree?

**Comment by jorgenhorstink** [comment]
**Fix**
You should update to at least v1.0.0-beta8. That resolved the issue for me.

**Background**
I needed the same functionality. After inspecting the most recent code I saw it has been fixed (https://github.com/JedWatson/react-select/commit/9d6f3b761e2b3b196379dfc760bbe4efe6bb3cde).

**Issue status advice**
I think this issue has been resolved and can be closed.

**Comment by MrLeebo** [comment]
@jorgenhorstink I think you're right, thanks!

**Comment by aindlq** [comment]
Apparently this was fixed only for Sync select, Async is still restricted to string.

**Comment by rssteffey** [comment]
Does anyone know of a clean workaround for dynamically updating the string with Async options?  I'd like to swap out the noResults text based on what the user has typed so far.
