### ISSUE TITLE
Select list gets empty on state change

### ISSUE THREAD

**Issue by thirdknife** [JedWatson/react-select#626]
I am developing a SPA which has some filters. I am able to add the select list and on change event I am updating the state of the react application.

States

```
this.state = { genres: null , categories: null , fBooks: [] , gBooks: [] };
```

React tags

```
<Select
    name="genre"
    value=""
    options={this.state.genres}
    onChange={logChange}
/>
<Select
    name="category"
    value=""
    options={this.state.categories}
    multi={true}
    onChange={logChange}
/>
```

logChange

```
var logChange = (function(val) {
      filterBooks(val.split(','));
    }).bind(this);
```

and the filterBooks method

```
var filterBooks = (function(val){
      var selected = [];

      _.filter(this.state.gBooks, function (item) {
        if(_.contains(val, item.genre.name) === true){  
            selected.push(item);
        }
      });
        this.setState({fBooks: selected});
        console.log(selected);

    }).bind(this);
```

When the select list is first changed, the item are filtered correctly but when I select another option the select list changes to blank. Visuals might help better.

![screen shot 2015-11-24 at 5 31 48 pm](https://cloud.githubusercontent.com/assets/885125/11366979/86948b8a-92d2-11e5-9340-2d60e14a7629.jpg)
![screen shot 2015-11-24 at 5 32 01 pm](https://cloud.githubusercontent.com/assets/885125/11366978/8693d05a-92d2-11e5-9772-bf7ba1a11b7a.jpg)
![screen shot 2015-11-24 at 5 32 06 pm](https://cloud.githubusercontent.com/assets/885125/11366981/86a26f52-92d2-11e5-876f-af2376b6d192.jpg)
![screen shot 2015-11-24 at 5 32 10 pm](https://cloud.githubusercontent.com/assets/885125/11366980/869df71a-92d2-11e5-8ee5-ea426e2a2d20.jpg)

This only happens when I change the state to re-render the list 
`
this.setState({fBooks: selected});
`
Otherwise it works fine.

**Comment by thirdknife** [comment]
Do I have to separate the Select tags from the list of books?

**Comment by jonathanasquier** [comment]
+1

**Comment by Lothiraldan** [comment]
I have the same problem and you should separate the Select tag in a isolated component which will render only if the options props changed.

Something like:

```
class JobRunForm extends React.Component {

    shouldComponentUpdate = (nextProps, nextState, nextContext) => {
        return !(nextProps == this.props) ||
          !(nextState == this.state) ||
          !(nextContext == this.context);
    }

    render() {
      return (
        <form className="form-horizontal style-form">
              <Select
                  name="form-matcher-name"
                  options={this.props.matchers}
                  onChange={this.props.onChange}
                  searchable={true}
                  placeholder={'Glob'}
              />
       </form>
     )
```

The onChange props is passed by the parent and it will change the parent state without re-rendering the JobRunForm.

If you don't need the allowCreate, you should try the beta version, it solves the problem more elegantly.

**Comment by jonathanasquier** [comment]
I'm using redux-form and the onBlur event used to dispatch empty values which is quite ennoying.
I'ts ugly but it works (1.0.0-beta6):
```
<Select
     options={options}
    {...field}
     onBlur={function(){}}
 />
```

**Comment by ericqt** [comment]
I'm also getting this issue.

**Comment by viveleroi** [comment]
Calling `setState` somehow wipes out the value the select component uses, so what's worked for me is passing that value back to the `value` attribute. That solves the issue for me.

**Comment by huvber** [comment]
@jonathanasquier 
> I'm using redux-form and the onBlur event used to dispatch empty values which is quite ennoying.
> I'ts ugly but it works (1.0.0-beta6):
> 
> <Select
>      options={options}
>     {...field}
>      onBlur={function(){}}
>  />

in my case doesn't work. The field result empty even if there is some value.

**Comment by petermikitsh** [comment]
@jonathanasquier Your onBlur hack worked in my case. Thanks for commenting.

**Comment by MilllerTime** [comment]
There is another issue specific to handling onBlur: https://github.com/JedWatson/react-select/issues/805

@jonathanasquier's trick works well if you're not using redux-form, but if you are, that approach won't notify redux-form that the field was blurred since it's overriding the `onBlur` handler from `field` (or `input` for v6). If you look at the actions dispatched, the blur action never happens.

You can manually trigger the redux-form `onBlur`, and pass it the current Select value so that it is preserved. It's the same hack, but properly integrated with redux-form:

```JS
<Select
  options={options}
  // redux-form wiring
  {...input}
  onBlur={() => input.onBlur(input.value)}
/>
```

**Comment by keehun** [comment]
I might have a similar, but different, problem, if anyone is able to take a look: https://github.com/JedWatson/react-select/issues/1817

Thank you!

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
