### ISSUE TITLE
Disable allowCreate feature until asyncOptions returns no more results

### ISSUE THREAD

**Issue by spoolphiz** [JedWatson/react-select#627]
Is it possible to only show the row item prompting creation of an option if the result of asyncOptions is an empty array?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
