### ISSUE TITLE
Add a `maxOptions` prop 

### ISSUE THREAD

**Issue by cedricdelpoux** [JedWatson/react-select#628]
When the `<Select/>` component has `multi` `allowCreate` props, it will be great if we can add an optional `maxOptions` prop to limit the number of possible `options`

**Comment by jolyonruss** [comment]
+1 for this please

**Comment by tirli** [comment]
+1

**Comment by sttevan88** [comment]
+1

**Comment by SVITY** [comment]
+1

**Comment by riseremi** [comment]
+1

**Comment by super-cache-money** [comment]
@H3katonkheir  :(

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
