### ISSUE TITLE
Remote search?  Callback on clear?

### ISSUE THREAD

**Issue by drewhamlett** [JedWatson/react-select#63]
I may be missing some of this info, but I can't seem to find it anywhere.

I have a component.

```js
 <Select
              multi={true}
              options={this.state.storeList}
              value={this.state.stores}
              onChange={this._onChange} />

  {(this.state.stores.length > 0) ?
            <Select multi={true} autoload={false} asyncOptions={this.loadOptions} />
            : <div>Please select a store</div> }
```

When stores are selected you can then filter down the inventory based on stores.  This works fine until someone clears some of the selected stores.  Then the inventory select is out of date.  I guess I need to force a re render on the select component or give it new options?  Is there a good workflow for this?

Also is there a plan to add a remote search api?  Like if someone enters a string hits a server to give back results?  Thanks.

**Comment by dcousens** [comment]
> Also is there a plan to add a remote search api? Like if someone enters a string hits a server to give back results? Thanks.

There is [now] an async example given on the demo site and in the [README](https://github.com/JedWatson/react-select#async-options).

If you have any further questions, please open a new issue,  it is my understanding that this may have solved the core of your question.
