### ISSUE TITLE
Allow for detection and user-handling of backspace

### ISSUE THREAD

**Issue by robtweed** [JedWatson/react-select#633]
I've made my own local customisation of Select.js to do this.  I added:

   this.props.onInputChange('', event.keyCode);

after line 475, ie:

```
handleKeyDown: function handleKeyDown(event) {
    if (this.props.disabled) return;
    switch (event.keyCode) {
        case 8:
            // backspace
            if (!this.state.inputValue && this.props.backspaceRemoves) {
                event.preventDefault();
                this.popValue();
            }
                            this.props.onInputChange('', event.keyCode); // ********
            return;
```

So I can now check in my onInputChange() function if input is an empty string and keycode is 8, then I can modify my generated options array

Would be nice if this (or equivalent) could be made available as standard

Rob

**Comment by lucasreppewelander** [comment]
This issue is resolved by now?
the `handleKeyDown` function got this code before the `switch`:

    if (typeof this.props.onInputKeyDown === 'function') {
        this.props.onInputKeyDown(event);

        if (event.defaultPrevented) {
            return;
	    }
    }

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
