### ISSUE TITLE
Menu list is not shown in a scrollable div

### ISSUE THREAD

**Issue by xabikos** [JedWatson/react-select#637]
When we render the select component inside a div that has overflow auto and there is not enough space for the menu to appear then we need to scroll to be able to see all the options. You can see an example here 
![select](https://cloud.githubusercontent.com/assets/487416/11473084/c57812fc-9770-11e5-9f31-46a8c6aee34b.png)

Instead a behavior like on that follows would be better

![date](https://cloud.githubusercontent.com/assets/487416/11473104/e674d3aa-9770-11e5-8c15-d7c093cafe0a.png)

Both of the pop ups are absolute positioned but I couldn't find any other differences

**Comment by xabikos** [comment]
After investigating a bit more and dig into the code of react-datepicker to see how they do it I found that this control uses [tether library](https://github.com/HubSpot/tether) to have the pop up absolute positioning and always to the right spot. Is there any interest to submit a pull request and follow the same approach to solve the issue? @JedWatson

**Comment by christophediprima** [comment]
I am very interested on this feature as I am having the same issue in my list !

![capture d ecran 2015-12-22 a 10 30 23](https://cloud.githubusercontent.com/assets/3352687/11952252/2259dd66-a897-11e5-906f-53f5971eeb9c.png)

**Comment by winterbe** [comment]
Is this fixed in latest 1.0-beta? I would love to give react-select a try but this issue would be a job stopper for us.

**Comment by guilleCM** [comment]
Any fix this issue?

**Comment by matthewcorreia** [comment]
@guilleCM if you use react-select v2, there is an option to use portals to solve this issue:
https://react-select.com/advanced#portaling
