### ISSUE TITLE
backspace in single select sometimes doesn't show placeholder again

### ISSUE THREAD

**Issue by ckrivik** [JedWatson/react-select#638]
Cloned and ran examples for 1.0.0beta5. 

In the example titled "Custom render methods", select an item and then clear it with the backspace key. The item disappears, but the placeholder isn't shown until the user clicks the x or hits escape.

This is present in the "custom render methods" and "custom option and value components" examples, but not in "States" or "numeric values". Does not occur in multi selects.

**Comment by ckrivik** [comment]
It appears that the cause is the value sent to the onChange function. Clearing by clicking the x sends null, which I believe is the intended functionality, but clearing with backspace sends an empty array.

Users could just handle the empty array case, but is this the intended functionality for a single select?

**Comment by slestang** [comment]
I stumble on the same issue today.
I fix it by modifying popValue() to:
```javascript
	popValue () {
		var valueArray = this.getValueArray();
		if (!valueArray.length) return;
		this.setValue(this.props.multi ? valueArray.slice(0, valueArray.length - 1) : null);
	},
```

I currently don't have a recent enough version of Node to run the test but I'll do a PR with this fix + tests when I have time.
