### ISSUE TITLE
`undefined` vs. `null` for empty values

### ISSUE THREAD

**Issue by macgyver** [JedWatson/react-select#639]
Currently `null` is passed as the option value parameter to `onChange` handlers when the select element is cleared out. I can think of one good reason why you did this - that parameter will always be an object - but have you considered passing `undefined` instead? It maybe doesn't make as much sense conceptually (the value *is purposefully* `null`) but if you used `undefined` then we would be able to take advantage of ES2015 default parameters. Just curious what your thoughts are?

**Comment by hbarudin** [comment]
This seems to me a duplicate (or close relative) of https://github.com/JedWatson/react-select/issues/703, in which case I'd quote @benzen 's answer:

> The api of the select expose a resetValue, which let you decide which value should be use when the select is cleared

**Comment by macgyver** [comment]
Agree, thanks for showing me that @hbarudin !
