### ISSUE TITLE
Any way to access `focusedOption` from outside ?

### ISSUE THREAD

**Issue by Lothiraldan** [JedWatson/react-select#640]
Hi,

I'm trying to use react-select to display a large list of option and for each option I have lots of information to display. I tried to use `optionComponent` but the quantity of information to display looks to big to display inside the optionComponent.

I would like to display these information beside the Select form input but I would need access to the `focusedOption` to display the relevant documentation for focused option.

Is it possible right now without accessing `focusedOption`? If not, do you have an idea of how to implement it so I could try to do a Pull-Request.

Thank you for your work!

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
