### ISSUE TITLE
Accept readOnly props

### ISSUE THREAD

**Issue by mping** [JedWatson/react-select#642]
The component should accept `readOnly` props, in some cases its helpful because it prevents the keyboard in mobile devices from appearing.

**Comment by mping** [comment]
Nevermind, just use `inputProps={{readOnly:true}}`

**Comment by lkjx77** [comment]
not working

**Comment by johneakin** [comment]
this doesnt work...

**Comment by umdech** [comment]
`isSearchable={ true }` worked!

**Comment by sombrerox** [comment]
`isSearchable` as you can tell by it's name will only prevent user from typing/searching in the select.

I think what @mping wants is `isDisabled={ true }` which will make select grayed out and will prevent interaction.

**Comment by mehrdad-shokri** [comment]
I achieved readonly mode with the following approach:  
```
<Select
   isSearchable={!readOnly}
   menuIsOpen={readOnly ? false : undefined}
   ...otherProps
/>
```

**Comment by lakesare** [comment]
There is the `isDisabled={true}` option that works.

**Comment by johnmarinelli** [comment]
on mobile devices, I need to specifically set readonly=true on the rendered <input/>.  is there any straightforward way to do this?

the reason is that even if isSearchable=false, the system keyboard opens when the user clicks on the select field.

**Comment by Mohammedalasaad** [comment]
Hi,
I think thats still not work good even with isSearchable=false .. 
if we have another Input field on the same page and click on the select list it still shows iOS footer with "Done" button and arrow to jump between inputs in Safari "iPhone".
Any way to solve this?
https://i.ibb.co/jLh8RHc/Screenshot-2019-11-22-at-11-14-29.png

Thanks

**Comment by bhargavshah** [comment]
A lot of suggestions here are using `disabled`. While this is visually the same, it is a problem for accessibility, as a screen reader won't read a disabled field (Will skip it)
Whereas, for a readonly field, the screenreader will read the field, and will say that it is readonly and can't be modified.

**Comment by umphy** [comment]
My workaround was with the following props:
```
isClearable={!readOnly}
isSearchable={!readOnly}
openMenuOnClick={!readOnly}
```
Of course that doesn't help with adding a readonly attribute to the input field. For those who need it, you should probably create a thin wrapper around `<Select/>` with your custom props, then manually set the readonly attribute via the input element's handle.

**Comment by richardpayne** [comment]
I added the following, as clicking the chevron for opening the menu also opened it:
`menuIsOpen={readonly ? false : undefined}`
As mentioned by @umphy it doesn't help with the readonly attribute...

**Comment by abotsi** [comment]
Hi,
in cas anyone still here after 2024, you can add the following to prevent removing option in case of multi-select: 
`styles={{
        multiValueRemove: () => (readOnly ? { display: 'none' } : {})
      }}`
