### ISSUE TITLE
Question: Why press tab select the current choice?

### ISSUE THREAD

**Issue by slestang** [JedWatson/react-select#643]
I am using 1.0.0-beta6 with a multi value select. The select is part of a form displayed in a modal dialog.
I want to be able to navigate and fill my form only with the keyboard.

When tabulation is press, currently the current choice is added to the list of values (see https://github.com/JedWatson/react-select/blob/master/src/Select.js#L242). It's seems a weird behavior to me as we usually expect tab to move the focus to the next input/selectable element.
Do we have a good reason for this current behavior or a PR is welcome to change it?

I my specific case I cannot use escape to close the choices list as it aslo close the modal dialog and I want to keep this behavior for consistency with the other modal.

**Comment by piecyk** [comment]
:+1: @slestang you are not alone :) if this is needed for some custom logic at least we can have some props value to turn it of and allow to switch.

**Comment by rdsubhas** [comment]
Yes this behavior is confusing users when combined with other form controls that act normally (textboxes, normal select boxes, etc). Everybody is like `Why do we have to press tab twice just for this one thing?`.

Problem increases with validations. So right after they press tab, validations get triggered and the `Next Field` shows an error. Users see the Next Field marked as error and start typing, except the tab switch has not happened yet. Very confusing.
