### ISSUE TITLE
[Question] Load on scroll/pagination

### ISSUE THREAD

**Issue by junhanamaki** [JedWatson/react-select#644]
Hello.

I would like to know if react-select supports pagination on scroll like (for example) select2: https://select2.github.io/examples.html#data-ajax

Thank you for your attention.

**Comment by angelf** [comment]
It doesn't but it seems it's on the plan (#568)

**Comment by M3lkior** [comment]
I have the same need, nice.

**Comment by vtaits** [comment]
You can use [this wrapper](https://www.npmjs.com/package/react-select-async-paginate).

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
