### ISSUE TITLE
Why string instead of array?

### ISSUE THREAD

**Issue by evgenyrodionov** [JedWatson/react-select#645]
Why react-select returns joined string like `"apple,mushrooms,orange"` instead of normal array `["apple", "mushrooms", "orange"]`?

**Comment by theaqua** [comment]
Guys?

**Comment by mqklin** [comment]
I do this: 

    onSelectChange = (value) => {
      if (!value) {
        return this.selectData = [];
      }
      this.selectData = value.split(",")
    }

**Comment by theaqua** [comment]
It's not cool.

**Comment by mqklin** [comment]
а хули делать

**Comment by CosticaPuntaru** [comment]
what happens when you don't have control over the value and it can be a string containing `,`, also you can't make a difference between numbers and strings.
plus it should reflect the default browser behavior.

**Comment by mqklin** [comment]
@CosticaPuntaru , you can set your custom delimiter with `delimiter` prop.

**Comment by CosticaPuntaru** [comment]
yea i know but is rely hackish

**Comment by SylarRuby** [comment]
It's not cool indeed but we could `.split()` etc

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
