### ISSUE TITLE
react-select breaks in tables that have their own border-spacing

### ISSUE THREAD

**Issue by dantman** [JedWatson/react-select#646]
Because of the new `display: table;` handling react-select breaks in some situations where react-select itself is put inside a table.

Namely if a surrounding table has its own border-spacing, react-select will inherit this and end up like this:

![screen shot 2015-12-03 at 1 00 24 am](https://cloud.githubusercontent.com/assets/53399/11556107/8b009a0a-9959-11e5-9e61-d236767f531e.png)

.Select-control should explicitly declare the `border-spacing: 0; border-collapse: separate;` it requires for its styles.

**Comment by rwrz** [comment]
Same problem here! No PR?
