### ISSUE TITLE
Uncaught Error: Cannot find module 'react-dom'

### ISSUE THREAD

**Issue by kalashnikovisme** [JedWatson/react-select#647]
in my Rails app

`reactjs` version `0.14.3`, via `gem react-rails version: 1.5.0` see [react-rails/versions.md](https://github.com/reactjs/react-rails/blob/master/VERSIONS.md)
`react-select` version `0.9.1` via Bower

also I've installed `react-dom` version `0.1.0` via Bower.

**Comment by masonjm** [comment]
I had the same error. Upgrading `react-select` to `1.0.0.beta6` fixed it for me. Possibly an incompatibility with React `0.14`?

**Comment by johannesnagl** [comment]
0.14.3 of react and 0.9.1 of react-select is working fine for me!

**Comment by justinkwanlee** [comment]
I am having this issue as well:
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-select": "^0.9.1",

**Comment by felixcheruiyot** [comment]
Tried @masonjm workaround but still fails.Any person who has managed to solve this?

**Comment by felixcheruiyot** [comment]
I removed and installed it again and then I bumped into #582 and I fixed it by including the classnames and react-input-resize files before calling the react-select. It works now:

    "react": "~0.14.3",
    "react-select": "~0.9.1"

**Comment by medius** [comment]
Just in case someone is wondering where can they get those dependencies,

https://github.com/JedWatson/classnames
https://github.com/JedWatson/react-input-autosize

**Comment by psimoneau22** [comment]
including the dependencies does NOT work for me:

```
<head>
    <link rel="stylesheet" href="node_modules/react-select/dist/react-select.css"></link>
    
    <script src="node_modules/classnames/index.js"></script>
    <script src="node_modules/react/dist/react.js"></script>
    <script src="node_modules/react-dom/dist/react-dom.js"></script>
    <script src="node_modules/react-input-autosize/dist/react-input-autosize.js"></script>
    <script src="node_modules/react-select/dist/react-select.js"></script>
</head>
<body></body>
</html>

```
```
"dependencies": {
    "classnames": "^2.2.3",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-input-autosize": "^0.6.8",
    "react-select": "^0.9.1"
  }
```

**Comment by stuyam** [comment]
Upgrading "react-select" to 1.0.0-beta9 fixed this error for me in my rails application.

**Comment by Carlows** [comment]
I'm having this issue too, I can't get any beta versions through rails-assets though 😢

**Comment by hartator** [comment]
I am stuck as well. I am getting `Uncaught TypeError: (0 , h.default) is not a function`with `1.0.0-beta6`. (Not such thing as `1.0.0-beta9` for now.)

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
