### ISSUE TITLE
Select Menu Scrollbars don't play nice with React-Bootstrap Modal

### ISSUE THREAD

**Issue by MrLeebo** [JedWatson/react-select#648]
This happens in v1 but not in v0.9.1. 

Expectation: When a Select control is inside a React-Bootstrap Modal, clicking on the Select Menu scrollbars will scroll the menu.

Actual: The menu closes.

Repro:
```
import React from 'react';
import { Modal } from 'react-bootstrap';
import Select from 'react-select';

const options = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight'].map(text => ({ label: text, value: text }));

export default React.createClass({
  getInitialState() {
    return { selected: null }
  },

  onChange(option) {
    this.setState({ selected: option && option.value });
  },

  render() {
    return (
      <Modal show>
        <Select value={this.state.selected} options={options} onChange={this.onChange}/>
      </Modal>
    );
  }
});
```

The culprit appears to be related to this line:
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L238
For some reason, the `document.activeElement` value is the modal/backdrop container.

**Comment by nemish** [comment]
I have this error too. Any luck about this?

**Comment by MrLeebo** [comment]
@nemish No, I don't have a workaround, sorry. It hasn't been a big enough priority for me to dive into any further.

**Comment by rigobertocontreras** [comment]
Same problem

**Comment by jorgechen** [comment]
Anyone found a temporary solution to this?

**Comment by hahuerta** [comment]
Clicking the scrollbar seems to trigger the modal onclick. The only solution i found is not to use a modal with a select inside.

**Comment by MrLeebo** [comment]
@nemish @rigobertocontreras @jorgechen @hahuerta Since there was so much interest in this lately I took another look at it. The implementation for `handleMouseDownOnMenu` was missing in the master branch.

**Comment by jorgechen** [comment]
:+1:

**Comment by hahuerta** [comment]
It's working now :smile:
