### ISSUE TITLE
Selected option doesn't scroll into view

### ISSUE THREAD

**Issue by atroche** [JedWatson/react-select#651]
Hi, I'm not sure if this is expected behaviour, but if you go [the examples](https://jedwatson.github.io/react-select/), then choose “Northern Territory” from the first select box, then click on the select box again, Northern Territory isn't shown until you scroll down.

Is there a way of making it so that the menu scrolls down to the focused option? That'd be really handy for what I'm making right now.

Cheers!

**Comment by ianwitherow** [comment]
This would be really nice, like how Selectize does it.

**Comment by nil4** [comment]
:+1:

**Comment by martin-jujou-sirca** [comment]
I have added a pr for this: https://github.com/JedWatson/react-select/pull/724

**Comment by sombro** [comment]
Agree with this issue, need the solition too...

**Comment by JedWatson** [comment]
I just merged #724 with the fix for this, thanks to @martin-jujou-sirca
