### ISSUE TITLE
`newOptionCreator` not working as intended.

### ISSUE THREAD

**Issue by bIgBV** [JedWatson/react-select#658]
I am facing this issue when trying to add a new value through the input box.

When `allowCreate` is set to `true`, the function passed as the `newOptionCreator` prop is not being called. 

For example:

```javascript
....
    optionCreator: function (value) {
        console.log(value); // This line isn't reached.
    },

    render: function() {
        return (
            <Select multi={true}
                    allowCreate={true}
                    newOptionCreator={this.optionCreator} />
        );
    }

...

```

**Comment by bIgBV** [comment]
Something that I noticed was that the prop wasn't being used anywhere in `select.js`. If so does this mean it still isn't implemented ?

**Comment by hsrobflavorus** [comment]
Confirmed, this isn't being used anywhere in the code, and doesn't appear to have any affect on the selected results.

**Comment by asazernik** [comment]
@bigBV In case you haven't seen the linked #658 - this is functionality that hasn't yet been implemented in the 1.0 rewrite. Use the latest 0.9.x version instead.

**Comment by bIgBV** [comment]
Yeah, we ended up moving to the previous version for that feature. Thanks !

**Comment by f2net** [comment]
Is there any plan to add this feature in v.1 beta 13?
Thank you

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

Look for an updated RC with this functionality soon. 😎
