### ISSUE TITLE
Async: omit searchPromptText

### ISSUE THREAD

**Issue by FranBran** [JedWatson/react-select#663]
I'd like to omit `searchPromptText` and therefore not be shown an (empty) menu. As I think the UX-Design of the dropdown is very nice, a `searchPromptText` should thus not be necessary

**Comment by jnachtigall** [comment]
@FranBran Did you find a way to disable the `searchPromptText`? Either by overriding something or CSS?

**Comment by jnachtigall** [comment]
Got it :)
```
  // Hide the "Type to Search" searchPromptText
  .Select-noresults {
    display: none;
  }
```
