### ISSUE TITLE
Select.Async replaces german letters

### ISSUE THREAD

**Issue by kuuup** [JedWatson/react-select#664]
When I type german letters like ä, ö, ü and ß they are replaced by a, o, u and s. This behavoir leads to wrong search results.

**Comment by StevenLangbroek** [comment]
There's a prop called `ignoreAccents` you can set to `false` to negate this behavior. See https://github.com/JedWatson/react-select/blob/master/src/Async.js#L43. @JedWatson want me to add some docs around this?

**Comment by kuuup** [comment]
Works :thumbsup:
Thank you.

I'll leave this one open for Jed.

**Comment by JedWatson** [comment]
That would be great, thanks @StevenLangbroek!

**Comment by jochenberger** [comment]
I wonder if stripping the diacritics is a good default behavior when querying remote data sources.

**Comment by jochenberger** [comment]
IMO, `Async` should have `filterOption={()=>true}`. The filtering should be done by the remote endpoint.

**Comment by JedWatson** [comment]
In hindsight I don't think these props should have defaulted to `{true}`, but I don't want to push a breaking change at the moment to update that. The props are now more clearly called out in the documentation, which should make it easier for users to understand what's going on and how to manage the behaviour.
