### ISSUE TITLE
Components in options labels?

### ISSUE THREAD

**Issue by antonsivogrivov** [JedWatson/react-select#666]
Hi!

Is it possible to do something like this?

var options = [
 {label: < Component / >, value: 1},
...
];

**Comment by jprichardson** [comment]
Yes, see examples. See docs, specifically `optionComponent`.

**Comment by ahstro** [comment]
I'm having trouble with this and `multi` though. Adding one option is fine, but any more than that will refuse to render for whatever reason.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
