### ISSUE TITLE
Clicking clear on adjacent input interrupts onBlur

### ISSUE THREAD

**Issue by etburke** [JedWatson/react-select#671]
I have a form: 
![screen shot 2015-12-14 at 1 53 00 pm](https://cloud.githubusercontent.com/assets/436070/11795250/93e42d52-a26a-11e5-9c02-0d83e8f49a00.png)
Where the flight number field is disabled unless an airline value is selected. When I select the airline field, open the flight number field, and then click the airline clear X the flight number field is disabled but left open.
![screen shot 2015-12-14 at 1 53 20 pm](https://cloud.githubusercontent.com/assets/436070/11795304/d01203f8-a26a-11e5-8001-7dd68d052c75.png)
![screen shot 2015-12-14 at 1 53 31 pm](https://cloud.githubusercontent.com/assets/436070/11795314/d51031d6-a26a-11e5-963c-7a8491a55007.png)
The flight number field is left unresponsive, even if the disabled prop is toggled back to false.

**Comment by JedWatson** [comment]
Fixed by #686
