### ISSUE TITLE
Changing/intial string value not rendered with Select.Async

### ISSUE THREAD

**Issue by kromit** [JedWatson/react-select#672]
Passing a string as value does not work on `Select.Async` when there was no manual input. Since options are only loaded on manual input, there are no options to get a label from. 

Caching also prevents value rendering, since previously loaded options may not contain changed `prop.value`.

Load option on change of `prop.value` should be a solution

**Comment by stevoland** [comment]
For others who bump into this, you can workaround by clearing the cache when the value changes:

```javascript
export default class AsyncSelect extends Component {
  static propTypes = {
    onChange: PropTypes.func
  }

  state = {
    cache: {}
  }

  handleChange = (value) => {
    // Wipe the cache when the value is changed so it doesn't lookup ''
    // and receive the previous empty []
    this.setState({
      cache: {}
    });

    if (this.props.onChange) {
      this.props.onChange(value);
    }
  }

  loadOptions = (input) => {
    // The input query is removed when a value is selected
    // So we need to search for the value itself in order
    // to get the label
    const q = (this.props.value && !input) ?
      this.props.value : input;

    return API.get(q);
  }

  render() {
    return (
      <Select.Async
        {...this.props}
        cache={this.state.cache}
        onChange={this.handleChange}
      />
    );
  }
}
```

**Comment by junhanamaki** [comment]
In our case we solved it by extending Select.Async and creating a second cache, which gets populated on getResponseHandler and is used to complete options during render.

**Comment by yleclanche** [comment]
Thanks for this workaround, but it's not perfect : it does not work with minimumInput, and doesn't work if Api.get returns many results.

Here's mine (without the cache workaround) : 
```
loadOptions = (input) => {
  const selectedValue = this.props.value;
  const selectedLabel = this.props.label;
  if(input.length < 2){
      if(selectedValue && typeof selectedValue === 'string')
         return Promise.resolve({options:[{label:selectedLabel, value:selectedValue}]});
      else
         return Promise.resolve({options:[]});
    }
  else
      return API.get(input);
```

I know this is far from perfect too :\
We need a proper solution for this.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
