### ISSUE TITLE
browserify-shim conflicts

### ISSUE THREAD

**Issue by tanqhnguyen** [JedWatson/react-select#673]
I am working on a project that uses global transform option (`b.transform({ global: true }, 'browserify-shim');`) for browserify-shim which results in a conflict with

```
  "browserify-shim": {
    "classnames": "global:classNames",
    "react": "global:React",
    "react-dom": "global:ReactDOM",
    "react-input-autosize": "global:AutosizeInput"
  },
```

Basically, classnames becomes undefined because of this transformation. Other modules that use `classnames` such as `react-bootstrap` work normally

```
var classes = (typeof window !== "undefined" ? window['classNames'] : typeof global !== "undefined" ? global['classNames'] : null);
```

I am not sure how I should handle this?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
