### ISSUE TITLE
doesn't work with 1000's of entries

### ISSUE THREAD

**Issue by natehardy** [JedWatson/react-select#674]
Don't know if it was intended for this purpose but I just tried to load a few thousand entries into the select and the fist scroll through is very jumpy. After that scrolling is fine.
However, selecting an item doesn't work.

**Comment by CosticaPuntaru** [comment]
i think there should be a hook that allows you to render options,
in this way you can use something like [virtual-list](https://www.npmjs.com/package/react-virtual-list) to handle large number of options

**Comment by bvaughn** [comment]
Check out PR #859 (and the demo linked) which adds react-virtualized support.

**Comment by bvaughn** [comment]
**Update**: If you're able to use react-select 1.0.0 beta, then you might be interested in trying a new HOC, [react-virtualized-select](https://bvaughn.github.io/react-virtualized-select/). Does windowing/lazy rendering so it should help with the issue you're reporting.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
