### ISSUE TITLE
Select.Async gives warning when using in documented asyncOptions manner

### ISSUE THREAD

**Issue by togakangaroo** [JedWatson/react-select#682]
Trying to use [async options with promises](https://github.com/JedWatson/react-select#async-options-with-promises) style API and am getting an error

```
Warning: Failed propType: Required prop `loadOptions` was not specified in `Async`
```

Is that right? shouldn't supplying an `asyncOptions` key be sufficient?

**Comment by alexanderchan** [comment]
In the 1.0 release the loadOptions prop is the place to provide the functions. The readme has been updated.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
