### ISSUE TITLE
How can I change arrow?

### ISSUE THREAD

**Issue by Xurma2** [JedWatson/react-select#685]
I need another arrow. Example of font-awesome.

How can a change ?

**Comment by CosticaPuntaru** [comment]
you can use css on `.Select-arrow-zone` and `.Select-arrow`

**Comment by Xurma2** [comment]
Cool thanks

**Comment by LoicUV** [comment]
Would it be possible to allow to pass a custom prop for the arrow so you can for example use svg icons ?

**Comment by RichardForrester** [comment]
... or to hide altogether; it's in the same location as bootstrap feedback icon.

**Comment by MiguelCord** [comment]
It's been a while already, but for anyone still having issues with this you can pass a custom function to the property `arrowRenderer`

You can find an example here https://github.com/JedWatson/react-select/blob/master/examples/src/components/CustomComponents.js

**Comment by praveenaj** [comment]
@MiguelCord looks like the feature has been taken out? The link doesn't work.

**Comment by Rahulkr204** [comment]
Any progress on this issue ?

**Comment by Dracontis** [comment]
@Rahulkr204 Came here for the same reason of changing arrow. Maybe this issue could help you: https://github.com/JedWatson/react-select/issues/2926

**Comment by subnomo** [comment]
@matheusalxds @praveenaj @Rahulkr204 @Dracontis

See [the docs](http://www.react-select.com/components) to learn how to replace components such as `DropdownIndicator`.

**Comment by Rahulkr204** [comment]
```
<Select
                    arrowRenderer={this.arrowRenderer}
                    optionRenderer={this.props.optionRenderer}
                    isMulti={false}
                    closeMenuOnSelect={false}
                    options={options}
                    onChange={(props)=>this.editDropdown(props,name)}
                    value={value}
                    className={classes.selectOption}
                    placeholder={placeholder}
                    disabled={isDisabled}
                    clearable={false}
                    style={dropdownStyle}
                />
````

**Comment by Rahulkr204** [comment]
I solved this by using arrowRenderer props
```
                arrowRenderer() {
                  return <div className={classes.arrowRenderer}><DownChevron/></div>
                }
               <Select
                    arrowRenderer={this.arrowRenderer}
                    optionRenderer={this.props.optionRenderer}
                    isMulti={false}
                    closeMenuOnSelect={false}
                    options={options}
                    onChange={(props)=>this.editDropdown(props,name)}
                    value={value}
                    className={classes.selectOption}
                    placeholder={placeholder}
                    disabled={isDisabled}
                    clearable={false}
                    style={dropdownStyle}
                />
```

**Comment by praveenaj** [comment]
@subnomo Thanks. I got it working. Here's my code if anyone still trying to do it.

```
const DropdownIndicator = props => {
  return (
    components.DropdownIndicator && (
      <components.DropdownIndicator {...props}>
        <FontAwesomeIcon icon={props.selectProps.menuIsOpen ? "caret-up" : "caret-down"}/>
      </components.DropdownIndicator>
    )
  );
};


<Select
   components={{ DropdownIndicator }}
    // pass other props
/>

```

**Comment by erfansamieyan** [comment]
I wanted to remove the dropdown arrow and by seeing this issue I rendered `arrowRenderer` as an empty `div` but there is still an annoying border (or divider something) which used to separate clear and arrow. First anyone has any better solution to remove arrow down icon and second if there is not how to remove that divider? 

Thanks :)

**Comment by visualcookie** [comment]
@erfansamieyan That's simple. Just do this in your `customStyles` Object.

![simple](https://user-images.githubusercontent.com/1857554/45753205-540a5380-bc18-11e8-9bd5-aa0e00537443.png)

**Comment by AllaSorokina** [comment]
Here's the link to the example on how you can substitute arrow-down with your image:
https://react-select.com/components
(search for Custom Dropdown Indicator Example)

**Comment by brendadev** [comment]
@praveenaj what is `FontAwesomeIcon`? I have the following, but passing this in doesn't replace the icon.

```
const CaretDownIcon = () => {
  return <i className="fas fa-caret-down" />;
};
```

https://codesandbox.io/s/jnk420nmrv

**Comment by praveenaj** [comment]
@brendadev https://github.com/FortAwesome/react-fontawesome

**Comment by ninariccimarie** [comment]
I also solved this by passing a function that renders the icon to `arrowRenderer` props

like so:
```js
const renderIcon = () => (
  // return icon render
)

<Select
  arrowrenderer={renderIcon}
/>
```

**Comment by vaske** [comment]
Is there a simple way to just pass id for `dropdownIndicator` component, so not to create custom to use existing one but to add html id?

**Comment by scrayWC** [comment]
To remove the dropdown indicator in a select add this to your custom styles object. 
`  dropdownIndicator: base => ({
            ...base,
            display: 'none'
        }),`

**Comment by vaske** [comment]
@scrayWC I know that one, I was looking for passing html id to dropdownIndicator but that is not possible just like that, so I had to pass whole custom component to render `dropdownIndicator` it's a bit hassle but still make sense.

**Comment by kandasj** [comment]
how do you change dropdownIndicator icon for <AsyncSelect /> ?
components is not exported in react-select/async

**Comment by vaske** [comment]
@kandasj I created my own component and pass to react select

**Comment by dunncl15** [comment]
> @scrayWC I know that one, I was looking for passing html id to dropdownIndicator but that is not possible just like that, so I had to pass whole custom component to render `dropdownIndicator` it's a bit hassle but still make sense.

@vaske I'm looking to do something similar. Are you able to use the default child icon when passing a custom component? I'm trying to pass an id attribute to the ClearIndicator, but still take advantage of the default cross svg.

**Comment by vaske** [comment]
@dunncl15 I had same problem as you, my goal was just to add id to dropdown arrow due to testing purpose, and run into issue that it's not possible to pass just id, then I had to create entire component.

If you pass just `prop.children` it should render default icon ;)

**Comment by matabgaryan** [comment]
dropdownIndicator: (provided, state) => ({
          ...provided,
          color: '#0D51FF',
          cursor:'pointer',
          'svg':{
            width:'24px',
            height:'22px',
            '&hover':{
              color:'#0D51FF',
            },
          },
        }),

**Comment by eco-faria-netto** [comment]
<Select 
                           components={{ DropdownIndicator:() => null, IndicatorSeparator:() => null }}
                        />

**Comment by GlebBigma** [comment]
> It's been a while already, but for anyone still having issues with this you can pass a custom function to the property `arrowRenderer`
> 
> You can find an example here https://github.com/JedWatson/react-select/blob/master/examples/src/components/CustomComponents.js

broken link

**Comment by ebonow** [comment]
@GlebBigma sorry looks like it likely pointing to V1 code. I updated the link which you can find here:
https://github.com/JedWatson/react-select/blob/master/docs/examples/CustomDropdownIndicator.js

**Comment by opopMihai** [comment]
https://gist.github.com/mihailsitnic/528491b1460b6805452ebe0f8b8c825b

**Comment by mihailsitnic** [comment]
https://gist.github.com/mihailsitnic/528491b1460b6805452ebe0f8b8c825b

**Comment by ahmadjoya** [comment]
> It's been a while already, but for anyone still having issues with this you can pass a custom function to the property `arrowRenderer`
> 
> You can find an example here: https://github.com/JedWatson/react-select/blob/master/docs/examples/CustomDropdownIndicator.js
> 
> Update 2020-12-25: Fixed broken link

not found

**Comment by Methuselah96** [comment]
https://github.com/JedWatson/react-select/blob/master/docs/examples/CustomDropdownIndicator.tsx

**Comment by ekpono** [comment]
> @subnomo Thanks. I got it working. Here's my code if anyone still trying to do it.
> 
> ```
> import Select, { components } from 'react-select';
> 
> const DropdownIndicator = props => {
>   return (
>     components.DropdownIndicator && (
>       <components.DropdownIndicator {...props}>
>         <FontAwesomeIcon icon={props.selectProps.menuIsOpen ? "caret-up" : "caret-down"}/>
>       </components.DropdownIndicator>
>     )
>   );
> };
> 
> 
> <Select
>    components={{ DropdownIndicator }}
>     // pass other props
> />
> ```

This fixed it. Thank you
