### ISSUE TITLE
loading spinner is rotating forever until select a item

### ISSUE THREAD

**Issue by netssfy** [JedWatson/react-select#688]
![00da6318-a513-11e5-8cc6-b5f086f52fce](https://cloud.githubusercontent.com/assets/6095138/11976864/589e8f2c-a9b7-11e5-8d7c-96945a9e565e.png)
My code:

``` javascript
body.push(<Select multi={this.props.many} onChange={this.updateValue} name={this.props.path} cacheAsyncResults={this.props.cacheAsyncOptions} asyncOptions={this.getOptions} value={this.state.expandedValues} />);

getOptions: function(input, callback) {
        superagent
            .get('/keystone/api/' + this.props.refList.path + '/autocomplete?' + this.buildOptionQuery(input))
            .set('Accept', 'application/json')
            .end(function (err, res) {
                if (err) throw err;

                var data = res.body;

                callback(null, {
                    options: data.items.map(function (item) {
                        return {
                            value: item.id,
                            label: item.name
                        };
                    }),
                    complete: data.total === data.items.length
                });
            });
    },
```

**Comment by ConAntonakos** [comment]
I have a similar issue. I referenced it here: #867.

**Comment by ConAntonakos** [comment]
So, I played around with the `callback` arguments, and it seems as though the `complete` key needs to be given a value of `true` for the spinner to stop immediately. Have you tried that at all? An example is documented, but not very well.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
