### ISSUE TITLE
Newbie Questions - How to drop in code with css

### ISSUE THREAD

**Issue by crobinson42** [JedWatson/react-select#689]
Hi, I stumbled across this component and thought it looked cool! I npm installed and dropped in a component to quickly see how it worked and i'm obviously missing the css portion of including this component because it renders funky. Does anyone have a quick example how to include the css with this component when dropping in as a replacement for another component?

**Comment by crobinson42** [comment]
** What is the minimal css code needed to render correctly.

**Comment by vgoklani** [comment]
same problem here
