### ISSUE TITLE
handleInputBlur requires additional check

### ISSUE THREAD

**Issue by pavel-kudishin** [JedWatson/react-select#690]
react-select@0.9.1.
handleInputBlur function must check if this.state.isOpen before using this.refs.menu this way:
        if (this.state.isOpen){
            var menuDOM = ReactDOM.findDOMNode(this.refs.menu);
            if (document.activeElement.isEqualNode(menuDOM)) {
                return;
            }
        }
because if this.state.isOpen == false then this.refs.menu is null and in IE 11 you get unhandled exception 0x80004003 invalid pointer

**Comment by timothyallan** [comment]
Just ran into this error myself, kills IE dead. 
![screen shot 2015-12-30 at 10 37 04 pm](https://cloud.githubusercontent.com/assets/1995135/12061535/ed6fac9c-af45-11e5-813e-58aafbb35164.png)

**Comment by StefanBilliet** [comment]
Yes, me too :-(

**Comment by tltowles** [comment]
Any one find a workaround?

**Comment by timothyallan** [comment]
I started using the 1.0.0-beta8 and it seems to have fixed it.

**Comment by stnwk** [comment]
Any update here?

**Comment by stnwk** [comment]
Is it correct this issue only exists for older versions and was fixed for 1.x?

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
