### ISSUE TITLE
Selecting a value does not display text in input

### ISSUE THREAD

**Issue by BossGrand** [JedWatson/react-select#692]
I just tried the base example but the input box never shows the option I have selected.

The onChange function is firing correctly with the value I chose, but the input just shows the place holder text "Select..."

Edit:
I looked at the underlying input value and it does not update.

I looked around the code and found this bit

http://pastebin.com/raw/kDfznF3v

shouldn't setState be setting the input value to value?

**Comment by BossGrand** [comment]
I'm using react 0.14.3

**Comment by SylarRuby** [comment]
@BossGrand 

```
getInitialState() {
  return { bar: ' ' }
},

handleChange (newValue) {
  this.setState({
   bar: newValue
 });

// in your render return:

<Select options={your-option-variable} value={this.state.foo} onChange={this.handleChange} />
```

**Comment by SylarRuby** [comment]
Typo should be:

```
value={this.state.bar}

```

**Comment by hafeez1042** [comment]
Have the same issue, not fixed with the above solutions.

**Comment by littleben93** [comment]
The same issue.
I'm using <Select.Async multi={true}... loadOptions={...}/>

Digging into sources, i found that after selecting options, inputValue resets and options also resets.

The next code is from Select:
```
getValueArray () {
		let value = this.props.value;
		if (this.props.multi) {
			if (typeof value === 'string') value = value.split(this.props.delimiter);
			if (!Array.isArray(value)) {
				if (value === null || value === undefined) return [];
				value = [value];
			}
			return value.map(this.expandValue).filter(i => i);
		}
		var expandedValue = this.expandValue(value);
		return expandedValue ? [expandedValue] : [];
	},

	expandValue (value) {
		if (typeof value !== 'string' && typeof value !== 'number') return value;
		let { options, valueKey } = this.props;
		if (!options) return;
		for (var i = 0; i < options.length; i++) {
			if (options[i][valueKey] === value) return options[i];
		}
	},
```

When Select renders values, inputValue is already empty, and options is also empty, therefore ``` return value.map(this.expandValue).filter(i => i); ```  alway returns [].

**Comment by jamesfzhang** [comment]
@hafeez1042 you need to add a second argument to `logChange`, the cumulative selected items is in the second argument.

```js
function logChange(val, selected) {
  this.setState({ searchQuery: selected });
}

**Comment by shivamsethi** [comment]
This works:
`onSelectChange(val){
      this.setState({
      selected_value:val.value
   });
}`


`const options = [
  	{ value: 'research', label: 'Research' },
  	{ value: 'mechanics', label: 'Mechanics' }
];`


And then:

`<Select
	name="select-category"
	options={options}
	value={this.state.selected_value}
	onChange={this.onSelectChange}
	clearable={true}/>`

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
