### ISSUE TITLE
In a multi select allow to dismiss menu after each selection

### ISSUE THREAD

**Issue by m4nuC** [JedWatson/react-select#695]
On small mobile devices it's a bit unhandy to have to tap outside the drop down menu to dismiss it. Could there be an option to hide the menu after each selection ?

**Comment by gabrielenosso** [comment]
It's the same thing I proposed there:
https://github.com/JedWatson/react-select/issues/706#issuecomment-171944038

**Comment by AlexRiina** [comment]
I think this exists now as `autoblur`

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
