### ISSUE TITLE
Render to "other" container & use Tether to position overlays

### ISSUE THREAD

**Issue by Andreyco** [JedWatson/react-select#697]
_I am not using screenshot of react-select in action, but they do apply to react-select as well_

In some scenarios you have to use `overflow: hidden`. This causes undesired side effects such as cropping list of options. See this picture...
![](http://i.stack.imgur.com/siaKj.png)

This can be solved by attaching select's overlay to outer element, `document.body` preferably.
**Tether** does this job very well. Bootstrap 4 is moving to Tether as well.
https://github.com/HubSpot/tether

Would you consider use of Tether to display overlays?

**Edit**
It's was not clearly stated. Tether does not render elements to "other" tree. It just positions those elements to their targets. Rendering should happen via "portals".

**Comment by thejameskyle** [comment]
I doubt that tether will work with this, but just to note if you want to make this type of rendering work universally (isomorphically) you can use https://github.com/cloudflare/react-gateway

**Comment by Andreyco** [comment]
Yes, you need to render element via "portals" to target container. Then, with Tether positions those elements next to their targets on scrolling, window resize, ...

**Comment by jsdf** [comment]
A more extensible option here would be to add a prop like `renderMenu` which allows developers using react-select to implement the actual rendering of the menu, eg. via a portal. They could use tether if they wish, or implement their own rendering logic. This would also allow stacking context problems to be solved by rendering the dropdown at the end of `<body>`.

**Comment by Andreyco** [comment]
Oh yes, this is an excellent option too!

**Comment by jsdf** [comment]
https://github.com/JedWatson/react-select/pull/529 would allow this, though I am not sure it is the best approach, as I've mentioned on the PR.

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
