### ISSUE TITLE
Multiple Copies of React

### ISSUE THREAD

**Issue by SylarRuby** [JedWatson/react-select#702]
Hi @JedWatson, great package and it works well in other Meteor apps I have. One of my meteor apps I've used webpack. The issue I'm now facing is:

> Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

My app now and must use `import React from 'react';` Is there a way to remove the error message I'm getting? I'm sure it's because I'm pulling two versions of react.

**Comment by looshi** [comment]
I ran into this issue using another react package alongside Meteor.  I just deleted the extra react folder and it worked , here's an explanation and solution that worked for me : https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375#.pl4tej604

**Comment by SylarRuby** [comment]
What extra folder?

**Comment by looshi** [comment]
Inside a package's own node_modules file there existed an additional react folder, which was the problem for me.  I'm not sure whether you experience the same issue or not.  The link above has instructions how to determine if you are importing multiple copies of react.

**Comment by SylarRuby** [comment]
Ok. I have solved it with: http://ttrmw.co.uk/code/rails_and_react_with_npm_modules.html

**Comment by JaakkoKarhu** [comment]
I have the same problem when trying to fork React-Select as a git_submodule. Not using webpack on this project. No idea what to do, nothing seems to work.
