### ISSUE TITLE
1.0Version API onChange issue

### ISSUE THREAD

**Issue by yesvods** [JedWatson/react-select#703]
When react-select onChange fired,normally an array was provided.
But when clear all options, `null` will be return.This will causes inconsistent operation when I do a map to the incoming array.`[]` empty should be passed as first param when clear button was clicked.

**Comment by benzen** [comment]
The api of the select expose a resetValue, which let you decide which value should be use when the select is cleared

**Comment by sajinshrestha** [comment]
`[]` is passed as the first parameter to `onChange`  when the field is cleared manually using backspace/delete key. Wouldn't it make sense to pass an empty object by default to make things consistent? An object `{label: "some Some Label", value: " Some Value"}` is passed when a valid option is selected from the dropdown.
