### ISSUE TITLE
Blur on select a new value when multiselect

### ISSUE THREAD

**Issue by gabrielenosso** [JedWatson/react-select#706]
When multiselect is enabled and user selects a value, the list of options remains open (the component doesn't blur).

Even though it could be handy in some situations, it's really annoying when you have to select one value and go away.

I would really like to have an option to disable it.

Thanks!

**Comment by DERIIIFranz** [comment]
+1

**Comment by gabrielenosso** [comment]
Maybe not blurring (the cursor will still remain in the input field), but just closing the list.

**Comment by lalitkapoor** [comment]
+1 on being able to close the list pragmatically

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
