### ISSUE TITLE
Option to preserve inputValue after select item in multiselect

### ISSUE THREAD

**Issue by nosovsh** [JedWatson/react-select#709]
Use case: user types search text in text field to filter items in multiselect. Then he wants to select few of filtered items(more than one). In current implementation dropdown will be closed after selecting one of the items so user has to type search text again.

What about adding an option "preserveInputValue"? if it is true, search text will not be cleared after item selection.

I'm currently working on PR because I need it anyway in my project. Please tell me if this feature fits in your roadmap or you have any advices/suggestions.

**Comment by wmertens** [comment]
Would `onBlurResetsInput	bool	true	whether to clear input on blur` do what you want? And then another option would be needed on multi-select that keeps the option list open on select?

**Comment by trashgenerator** [comment]
no, onBlurResetsInput is responsible for clearing or not clearing input when widget looses focus. I want the input value to be not cleared when some option is selected. 
I create PR #750. Check it please
You can pass onSelectResetsInput=false to achieve this

**Comment by mthomas46** [comment]
I would also like to see this, even thought the list is preserved, when working with large volumes of data, the user can easily forget what they typed to get that list
