### ISSUE TITLE
React-rails with react-select,  Only a ReactOwner can have refs.  =(

### ISSUE THREAD

**Issue by CostaRico** [JedWatson/react-select#711]
Maybe here somebody could help?

https://github.com/reactjs/react-rails/issues/437

Thx u a lot!

**Comment by olalonde** [comment]
Having same issue :(

**Comment by SylarRuby** [comment]
I had the same isssue. You are really use two reacts. Use the method. Trust me: http://ttrmw.co.uk/code/rails_and_react_with_npm_modules.html

**Comment by marudhupandiyang** [comment]
@CostaRico I had the same issue and this is how i fixed it. Please check your `Gemfile.lock`. If you see more than 1 version of react-rails, then trace back the parent which installed different versions of `react-rails` and some how make all of its dependencies use only one version.

In short, make sure your `Gemfile.lock` contains only one version of `react-rails`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
