### ISSUE TITLE
Allow validation/rejection of options for allowCreate

### ISSUE THREAD

**Issue by asazernik** [JedWatson/react-select#712]
It would be nice to be able to restrict the inputs that a user can attempt to create in "tags mode" - either by allowing newOptionCreator to reject a proposed value, or by allowing the text input itself to reject values as they're being typed in.

**Comment by Shnolik** [comment]
+1

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

The new `Creatable` HOC supports a configurable `isValidNewOption ` property that allows users to do custom validation on options. Learn more [here](https://github.com/JedWatson/react-select#creatable-properties).

Look for an updated RC with this functionality soon. 😎
