### ISSUE TITLE
Failed propType when using the "value" property

### ISSUE THREAD

**Issue by do87** [JedWatson/react-select#715]
When i add a default value to the select, i'm getting this error:

Warning: Failed propType: Invalid prop `placeholder` of type `object` supplied to `SingleValue`, expected `string`. Check the render method of `Select`.
- the default value i'm assigning is a string. i also tried casting to String() but it didn't help

**Comment by vyorkin** [comment]
@foxeil try to update react-select, there is no `SingleValue` component anymore

**Comment by vyorkin** [comment]
have a look at https://github.com/JedWatson/react-select/commit/1c8c0f71c9edf7b88874789092e82f28891dc14c#diff-04191649796841200b33375bdff7c78fL11, its ancient stuff

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
