### ISSUE TITLE
Suggestion: Call `onMenuScrollToBottom` when result set length reduced by filter.

### ISSUE THREAD

**Issue by rhys-vdw** [JedWatson/react-select#716]
Version: v1.0.0-beta-8.

I'm using the undocumented prop `onMenuScrollToBottom` in combination with `isLoading`. Which seems the natural place to hook into my Redux store.

The idea here being that whenever the end of the result set is reached, I dispatch a 'fetch more items' action with the correct search term. This temporarily switches the `isLoading` flag and ultimately updates the `options` prop and resets `isLoading` to `false`.

The query to grab more options has a search parameter. Ideally I'd just fire off this query whenever the end of the results is visible, which works in most situations. However if there are only a few options and the result set is not scrollable, changing the filter to match a subset of these does not trigger the event (since the check is done on [`handleMenuScroll`](https://github.com/JedWatson/react-select/blob/v1.0.0-beta8/src/Select.js#L313-L315)).

I suggest having a test to see if the bottom of the menu is visible after any change to the number of results (in `componentDidUpdate`) and firing off the same event.

Happy to contribute a PR.

**Comment by bladey** [comment]
Hello @rhys-vdw,

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest versions.

If you feel this issue is still relevant and you'd like us to review it, please leave a comment below.

**Comment by bladey** [comment]
Hello @rhys-vdw -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
