### ISSUE TITLE
`filterOptions` is called in `render()`

### ISSUE THREAD

**Issue by rhys-vdw** [JedWatson/react-select#719]
Expensive operations should be called when their dependant props change, not every time a mouse hovers over the component.

**Comment by mnpenner** [comment]
👍 `filterOptions` is called repeatedly as I mouse over the list.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
