### ISSUE TITLE
How can I display (4selected) if more than 3 items get selected?

### ISSUE THREAD

**Issue by mohak1990** [JedWatson/react-select#720]
I want similar behavior like bootstrap dropdown.

**Comment by yashchauhan28** [comment]
any update on this ?

**Comment by Rall3n** [comment]
**v1.x** has no possibility to allow this customization. But the library has a new version **v2.x** in which you can overwrite any component with its [component framework](https://react-select.com/components).

@yashchauhan28 [This comment](https://github.com/JedWatson/react-select/issues/2790#issuecomment-460636017) (https://github.com/JedWatson/react-select/issues/2790#issuecomment-460636017) has a solution for what you are asking (in **v2.x**).

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
