### ISSUE TITLE
missing CSS to render boxes in example

### ISSUE THREAD

**Issue by vgoklani** [JedWatson/react-select#721]
I installed react-select: npm i --save-dev react-select
and added this CSS to my index.html: http://jedwatson.github.io/react-select/example.css

Then I ran your example code as follows:

	import React from 'react';
	import ReactDOM from 'react-dom';
	import Multiselect from './Multiselect';

	var Test = React.createClass({displayName: "Test",
		render: function() {
			return (
				<Multiselect label="Multiselect" />
			)
		}
	});

	ReactDOM.render(React.createElement(Test, null),
		document.getElementById('terminal'));

The main outer select box is rendered, but the individual select boxes (for example Strawberry) are missing all the styling. Any idea on how to fix it?  I can see example.css being used in the developer console, so I'm not sure what's missing and how to fix it?

**Comment by raptoria** [comment]
I have the same issue.. +1

**Comment by Mike-Dax** [comment]
So instead of installing with `npm install react-select --save` 
Run this:
`npm install react-select@1.0.0-beta8 --save`

Then look at the examples/ folder instead of README.md

**Comment by vgoklani** [comment]
perfect - thanks!
