### ISSUE TITLE
configure when options open

### ISSUE THREAD

**Issue by defiant718** [JedWatson/react-select#723]
Hi, 

Is there a way to make the results only appear when specified (ie. when user types 3 characters)?

Thanks!

**Comment by KoAi** [comment]
+1

It would be very interesting

**Comment by jljorgenson18** [comment]
Isn't there already a minimumInput option? https://github.com/JedWatson/react-select/blob/master/CHANGES.md

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
