### ISSUE TITLE
show allowCreate message only when no results are found

### ISSUE THREAD

**Issue by akhayoon** [JedWatson/react-select#725]
Currently when I set allowCreate={true} it shows me the "Would you like to add {label}" message whether or not the result exists.

Is there a way to make it so that the allowCreate message only shows, when there are no results in the options?

**Comment by nerder** [comment]
+1

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it! (The "create" placeholder option is only shown if there is not an existing match already in the options array.)

Look for an updated RC with this functionality soon. 😎
