### ISSUE TITLE
Get focus on component using JQuery or JavaScript

### ISSUE THREAD

**Issue by akhayoon** [JedWatson/react-select#726]
I have a case where an outside component is trying to gain focus on react-select, but I don't have the 'this' for the react-select available. Hence I cannot use <instance>.focus()

Is there a way that I can focus on the instance using vanila JS or JQuery? I seem to have a hard time doing so.

**Comment by wmertens** [comment]
You need to focus on `.Select-input input`

**Comment by EricOutsiderX** [comment]
i have the same issue with @akhayoon ,  I use react-select in jquery steps,  the select can't open, others in tab wok fine, i found when I click the select input field the is-focused and is-open class not showing.

**Comment by wmertens** [comment]
@ericoutsiderx can you provide a codepen or at least some code?

**Comment by EricOutsiderX** [comment]
Thank you, this is the brief code below, hope you can help me out
/* sub component, use react-select */
export default class XSelect extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            value: this.props.initialValue || ''
        };
    }

    render() {
        var xSelect;
        const divProps = Object.assign({}, this.props);
        delete divProps.layout;

        xSelect =
                <Select
                    {...divProps}
                    placeholder="Click to select"
                    options={divProps.options}
                    optionRenderer={this.renderOption.bind(this)}
                    onChange={this.setValue.bind(this)}
                    value={this.state.value}
                />;

        return (
            <div>
                {xSelect}
            </div>
        );
    }
}

//target component  
class targetComponent extends React.Component {
      render() {
        return (
          <form id="wizard" action="#">
                        <div>
                            <h3>show</h3>
                            <fieldset>
                                <fieldset className="form-group">
                            <label>showing: </label>
                            <XSelect
                                options={[
                                    { label: 'ggg', value: '0'}
                                ]}
                            />
                        </fieldset>
                            </fieldset>
                        </div>
                    </form>;
        );
      }
}

//JQUERY steps, 
var form = $("#wizard");
    form.validate({
        errorPlacement: function errorPlacement(error, element) { element.before(error); },
        rules: {
            confirm: {
                equalTo: "#password"
            }
        }
    });
    form.children("div").steps({
        headerTag: "h3",
        bodyTag: "fieldset",
        transitionEffect: "slideLeft",
        onStepChanging: function (event, currentIndex, newIndex)
        {
            form.validate().settings.ignore = ":disabled,:hidden";
            return form.valid();
        },
        onFinishing: function (event, currentIndex)
        {
            form.validate().settings.ignore = ":disabled";
            return form.valid();
        },
        onFinished: function (event, currentIndex)
        {
            alert("Submitted!");

            // Submit form
            $(this).submit();
        }
    });

**Comment by wmertens** [comment]
@EricOutsiderX that code is incomplete (for example, this.renderOption is missing). Can you make it so you reproduce the issue?

**Comment by EricOutsiderX** [comment]
this is the full code @wmertens 
http://codepen.io/sxhuanx/pen/JRGxbB

**Comment by wmertens** [comment]
I don't see anything wrong with the code at first glance. You don't show
how it gets put in the jquery form.

- Does the select work when it is not in a jquery div?
- are there any console errors?
- did you try putting a breakpoint in the clickhandler of react-select so
you can trace what is happening?

If you manage to make the codepen actually function, you will probably find
the answer yourself.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
