### ISSUE TITLE
Customizable Clear button

### ISSUE THREAD

**Issue by gabrielenosso** [JedWatson/react-select#728]
It would be good to have a clearRenderer option to have a custom clear button.

So developers could use it to style the component properly.

**Comment by couzic** [comment]
:+1: 
In my case I intend to use `clearRenderer` not to customize the style, but to register a click handler to update my externally managed state.

**Comment by couzic** [comment]
Here's a quick fix:

declare module 'react-select' {
   interface ReactSelectProps<TValue = OptionValues> {
      clearRenderer?: any
   }
}

**Comment by Hongbo-Miao** [comment]
Thanks, @couzic , I was looking for same thing. `clearRenderer` works perfect.

For future people, I am using like this
```
<Select.AsyncCreatable clearRenderer={() => <i className="fa fa-refresh" />} />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by cseas** [comment]
Top Google result for "change icon of clear button react-select" leads to this issue so I'll leave the link here that actually has the solution. The ClearIndicator custom component example from the documentation shows how to change the clear button:
https://react-select.com/components#replaceable-components
