### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by binarykitchen** [JedWatson/react-select#73]
That's a nice component but how come there are no tests?

**Comment by ryanzec** [comment]
That is the first thing that I noticed.  A component as complex as this without tests is just asking for trouble.

**Comment by binarykitchen** [comment]
Yep ... I am already having trouble running Jest tests with a Rect component I own which is including react-select within :(

**Comment by ryanzec** [comment]
I can actually understand some things not having unit tests depending on the unit test setup.  I use Mocha/Chai/JSDom to unit test my code and I can't unit test any visual based stuff but this component definitely has a lot of none-visual stuff that can be unit tested.

**Comment by binarykitchen** [comment]
You can unit-test visual based React stuff with Jest very well!
http://facebook.github.io/jest/docs/tutorial-react.html

And the visual based stuff you are referring to, are mostly called end to end tests (aka E2E). Just run a standalone selenium server in a gulp task, then run a middleware server and at last have a Jasmine test runner. It works well for my other projects.

All I am saying here is that having no tests is not good. I do not like the idea to ship code without enough test coverage, especially for enterprise apps we are developing here.

**Comment by JedWatson** [comment]
I would really appreciate help implementing tests for this component.

I have a set of manual processes that I run through to test the component before every release (based on the example configurations), it would certainly take less work to merge PRs and manage releases if our tests were automated.

@binarykitchen you mention having this setup in place for other projects - can you help get them set up here as well?

Also @ryanzec is correct, there are several things that are non-visual and could easily be unit tested.

**Comment by binarykitchen** [comment]
@JedWatson Use the gulp-jest plugin for unit tests. Works like a charm.

**Comment by JedWatson** [comment]
@binarykitchen I probably wasn't clear - I'm managing a heap of open source projects at the moment between React stuff, KeystoneJS and TouchstoneJS as well as a having a full time job.

If someone else is able to contribute unit tests for this component I would _really_ appreciate it, otherwise I'll get to them when I can :)

**Comment by binarykitchen** [comment]
fair enough - it is just the fact that code without test is never good. always enforce yourself never to ship code without test ;)

**Comment by mattdell** [comment]
I've added Jest framework into react-select. Pending PR. https://github.com/JedWatson/react-select/pull/107

**Comment by JedWatson** [comment]
Basic tests are in - more to come.

**Comment by binarykitchen** [comment]
good, way to go

**Comment by dcousens** [comment]
Always could use improvement.  This issue isn't really quantifiable beyond a test count being > 1, so I'm closing.
@JedWatson if a given coverage requirement is wanted, lets set that up as a new issue.
