### ISSUE TITLE
[1.0.0-beta8] async: value select and minimumInput does not show label

### ISSUE THREAD

**Issue by wmertens** [JedWatson/react-select#732]
Steps:
- Async options loading with minimumInput set to 1
- search and select an option

Result:
- Nothing shows in value field

Expected Result:
- The label shows in the value field

What happens is this:
1. you select the option, which resets the inputValue and calls onChange, which sets the value eventually 
2. Async gets the value and because the inputValue is less than minimumInput, it clears the options
3. Select gets empty options and getValueArray cannot get the labels => doesn't display anything

Recommendation: Let Select cache the labels in the state, that is also faster than filtering the options array on every render.

Thoughts?

**Comment by wmertens** [comment]
It's even more problematic:

The options are only fetched on user interaction (which is fine), but when you are editing some model and providing an initial value to the select, it won't fetch the option (because it doesn't know how) and it won't have a label and therefore it won't show the value.

So the Async wrapper should accept a label for the value or a function to fetch the option for a value, and Select needs to accept the same.

This also means that Select should have some way to show that the current value isn't the only option and that typing something will produce a longer list.

**Comment by tomRedox** [comment]
I'm seeing exactly the same issue in beta 9.  Did you find a solution/workaround?

**Comment by jljorgenson18** [comment]
I'll have to find exactly where this was in the docs but the solution I found was to give the Select component an input object that represents the value and the label. 

My setup looks something like this

```
getValue: function() {
        // To work around react-select's weird input api
        const {val} = this.props.targetObj;
        if(val) {
            return ({
                label: val,
                value: val
            });
        }
    },

    render: function() {
        const {targetName, targetObj} = this.props;
        return (
            <div className={ this.generateGroupClassNames(targetObj) }>
              <label htmlFor={ targetName }>
                { targetObj.label }
              </label>
              <Async onChange={ this.onSelectChange }
                className="reactSelect"
                minimumInput={ 1 }
                name={ targetName }
                value={ this.getValue() }
                loadOptions={ getOptions }
                searchable={ true }
                menuBuffer={ 10 }
                placeholder={ targetObj.placeholder }
                clearable={ true } />
              <div className="formErrorFeedback">
                { targetObj.errorMessage }
              </div>
            </div>
            );
```

That being said, it seemed like there was some wonky behavior if you change the label and value keys in the props and the label still wasn't showing up. I also had better luck when doing the Promise based approach for the getOptions call as opposed to the callback approach.

**Comment by tomRedox** [comment]
@jljorgenson18 thank you so much for that information, I hadn't realised that the value you assign to select could be an object containing values for both the value and the label.  That was exactly what I needed to get me going.  My code ended up like this:

`import React from 'react';
import Select from 'react-select';

const AsyncSelectInput = React.createClass({
    // list out our required and optional properties for this class
    propTypes: {
        name: React.PropTypes.string.isRequired,
        label: React.PropTypes.string.isRequired,
        // The value needs to be an object with two properties called the same as the valueKey and the labelKey
        value: React.PropTypes.object.isRequired,
        loadOptions: React.PropTypes.func.isRequired,
        onChange: React.PropTypes.func.isRequired,
        valueKey: React.PropTypes.string.isRequired,
        labelKey: React.PropTypes.string.isRequired,
        error: React.PropTypes.string
    },

    onChangeHandler(selectedOption) {
        //console.log("AsyncSelectInput.onChangeHandler selectedOption ",
        //    selectedOption[this.props.valueKey] + " " + selectedOption[this.props.labelKey])

        this.props.onChange({
            name: this.props.name,
            value: selectedOption[this.props.valueKey],
            label: selectedOption[this.props.labelKey]
        });
    },

    loadOptions(input, callback) {
        console.log("OrderHeaderEdit.loadOptions() ", input);

        var data = {
            options: this.props.loadOptions(input),
            complete: true
        };

        setTimeout(function () {
            console.log("setTimeout", input);
            callback(null, data);
        }, 500);
    },

    // The value needs to be an object with two properties called the same as the valueKey and the labelKey
    getValue() {
        return {
            [this.props.valueKey]: this.props.value[this.props.valueKey],
            [this.props.labelKey]: this.props.value[this.props.labelKey]
        };
    },

    render() {
        //console.log("AsyncSelectInput.render() - value=", this.props.value)

        // This is for bootstrap, we want to wrap our label and textbox in a 'form-group'
        // class, and also to add 'has-error' (which gives us a red outline) if the data is in error
        var wrapperClass = 'form-group';
        if (this.props.error && this.props.error.length > 0) {
            wrapperClass += " " + 'has-error';
        }

        return (
            <div className={wrapperClass}>
                <label htmlFor={this.props.name}>{this.props.label}</label>
                <div className="field">
                    <Select.Async
                        name={this.props.name}
                        value={this.getValue()}
                        loadOptions={this.loadOptions}
                        onChange={this.onChangeHandler}
                        valueKey={this.props.valueKey}
                        labelKey={this.props.labelKey}
                        // stop the control caching the results - if true only searches the list retrieved on first load
                        cache={false}
                        searchingText="Loading results..."
                        minimumInput={2} // number of letters needed before a search starts
                        autoload={false}
                    />
                    <div className="input">
                        {this.props.error}
                    </div>
                </div>
            </div>

        );
    }
});

export default AsyncSelectInput;
`

**Comment by jljorgenson18** [comment]
Awesome, glad it worked. When you think about it, this makes sense as well because the set of options isn't set in stone because they change after every async call. If you just give the component a value key, there isn't a way to find an associated label. To get around this, you can pass in the value and label object instead of just the value.

**Comment by tomRedox** [comment]
Totally, it's exactly the functionality needed, the documentation could just be a bit more explicit about it.  My plan is to check the documentation after 1.0.0 is released from beta and if it's unchanged in this area then I'll propose some amendments to make it clearer how to deal with this situation.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
