### ISSUE TITLE
How to change the background-color of the .Select-control class dynamically?

### ISSUE THREAD

**Issue by vgoklani** [JedWatson/react-select#736]
The color is fixed in the CSS file, but I need to change it dynamically.

I know there is a "className" parameter, could someone please post an example of how to use it to change the background-color. I've tried this via "classnames" but it made a giant mess in the styling.

Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
