### ISSUE TITLE
Lazy loading of options

### ISSUE THREAD

**Issue by UrsBisang** [JedWatson/react-select#738]
I searched in the docs, but could not find anything about the following:

Is it possible to load the options lazily, i.e. to defer the ajax call, until the dropdown is actually openened or text is typed? Ideally it should be possible to display a default value when the select component is created, so that the select box is not empty at the beginning.

Is something like this possible?

We have a form with several select boxes on it and the call for retrieving the options is expensive and we try to avoid the overhead when nothing is changed.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by feyst** [comment]
I've created a topic in the Ideas section under Discussions please upvote: 
[https://github.com/JedWatson/react-select/discussions/5928](https://github.com/JedWatson/react-select/discussions/5928)
