### ISSUE TITLE
Setting value before options available doesn't update placeholder

### ISSUE THREAD

**Issue by farism** [JedWatson/react-select#74]
If you set the value on the component before the options are available (e.g. from a parent component's state, which got them from an async store), when the options are finally retrieved and the component is rerendered, the select placeholder stays stuck on the option value rather than displaying the option label. This doesn't seem to be an issue when using the async prop.

3 sec delay example: 

http://jsfiddle.net/kb3gN/10048/

**Comment by farism** [comment]
Submitted a PR to address this. I think the performance loss is fairly trivial.

https://github.com/JedWatson/react-select/pull/79

**Comment by dcousens** [comment]
Ref #53

**Comment by dcousens** [comment]
Resolved after https://github.com/JedWatson/react-select/pull/79 was submitted. 
ping @JedWatson to double check
