### ISSUE TITLE
Customizable loading

### ISSUE THREAD

**Issue by gabrielenosso** [JedWatson/react-select#740]
It would be cool to have a loadingRenderer prop to change the loading spinner (or render something different).

**Comment by gabrielenosso** [comment]
Moreover, is it worth to use a SVG solution? Wouldn't it be easier and more performant to use something like that?
http://codepen.io/jczimm/pen/vEBpoL

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
