### ISSUE TITLE
"Select all" for multiselect

### ISSUE THREAD

**Issue by nosovsh** [JedWatson/react-select#747]
It will be nice to have an ability to add "Select all" button to select all filtered options.

**Comment by trashgenerator** [comment]
Please check my PR #748 
If you like it I will add tests.
For now "Select all" button is not focusable but I think I can implement it.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
