### ISSUE TITLE
Callbacks for onOpen and onClose

### ISSUE THREAD

**Issue by DullReferenceException** [JedWatson/react-select#755]
I have a requirement for updating my component state when a `Select` is opened or closed. If there was an `onOpen` and `onClose` callback prop, we could easily use those to update component state. In my case, for example, I want to update a `className` in an outer container so that different styles are applied when the select is open.

**Comment by DullReferenceException** [comment]
Created https://github.com/JedWatson/react-select/pull/760 in case you agree that this would be useful.

**Comment by JedWatson** [comment]
Makes sense, thanks @DullReferenceException!

**Comment by pmckelvy1** [comment]
the onOpen and onClose functions do not seem to be firing for me.  i also cannot find any lines in the source that indicate when they would be fired.  help?

**Comment by pmckelvy1** [comment]
the onOpen and onClose functions do not seem to be firing for me.  I am defining them in my parent component (
onOpen: function onOpen() {
        console.log('open');
        this.setState({isOpen: true});
    },
)
and setting them on the select component (
onOpen = {this.onOpen}
)

am i setting them wrong?
