### ISSUE TITLE
No Virtual Keyboard on IE Mobile / Windows Phone 8

### ISSUE THREAD

**Issue by slybridges** [JedWatson/react-select#756]
I was testing my app on Windows Phone and faced an issue where when tapping a searchable Select component, it didn't trigger the Virtual Keyboard and hence broke the search.

This is a problem in my case since one of my Select component is Async and cannot display any option before user enters some text.

I could reproduce the issue with the [React-Select docs](https://github.com/JedWatson/react-select). Tested using a real Lumia 925 (with latest Windows Phone 8.1) and also on [BrowserStack.com](https://www.browserstack.com). Sometimes on BrowserStack emulators, I could get the Keyboard to show up (e.g. with the Contributors Async example) but most of the time (e.g. for the first States example) I could not.

It looks like the Input doesn't get the focus from the tap on the main component. Not too sure about how  debug this but if anybody has a lead, I'll be happy to help investigate.

**Comment by fhelwanger** [comment]
I faced this issue too.

I think that the problem is here: https://github.com/JedWatson/react-select/blob/master/src/Select.js#L760

IEMobile doesn't support touch events. I tried some polyfills but no success so far.

I'll try to figure out something later.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
