### ISSUE TITLE
Turn off autocomplete

### ISSUE THREAD

**Issue by tnrich** [JedWatson/react-select#758]
Hey there, 

Thanks for the excellent component.

I believe most browsers respect an `autocomplete='off'` rule: http://www.w3schools.com/tags/att_input_autocomplete.asp

I tried to apply an `autocomplete='off'` rule to the react-select box, but couldn't seem to get it to work. Is this something that other people have been able to do? And if not, I'd like to formally request the feature.

Thanks!
Thomas

**Comment by slybridges** [comment]
I'm wrapping the component doing this:
```javascript
<Select
  // ... other props
 inputProps={{ ...inputProps, autoComplete: 'off', autoCorrect: 'off', spellCheck: 'off' }}
/>
```

**Comment by tnrich** [comment]
Thanks for the tip, I'll try that out!

**Comment by tnrich** [comment]
Hey @slybridges , so I've tried to follow your suggestion, but can't seem to get it to work. Here's my code: 

```
<form>
...other inputs...
<Select
          inputProps={{autoComplete: 'off', autoCorrect: 'off', spellCheck: 'off' }}
          {...country}
          onBlur={() => country.onBlur(country.value)}
          className='UserInfoPageInput countryDropdown'
          sectionName='countriesDropDown'
          searchable={true}
          clearable={true}
          label='Country'
          placeholder="Country"
          options={COUNTRIES} 
        />
...other inputs...
</form>
```

But chrome goes right ahead and keeps placing a cursor in the box and filling in "United States". Here's a screenshot of that:

![image](https://cloud.githubusercontent.com/assets/2730609/12854136/cbfd8552-cbec-11e5-9ac3-8517946d7cea.png)

Do you have any other suggestions for getting this to work? Am I doing something incorrectly?

Thanks for the help!
Thomas

**Comment by tnrich** [comment]
Hey @slybridges , I looked further into the issue and it seems like my issue was caused by chrome ignoring the "off" parameter. Changing it to a random string, like "none" fixed it:

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

Thanks for the tip!

**Comment by slybridges** [comment]
Thanks for the feedback & tip @tnrich !

**Comment by enteeee** [comment]
Does it work for Safari browsers? When i set 
`inputProps={{autoComplete: 'none' }}` it doesn't work for Safari browsers.

**Comment by ifenega** [comment]
> Does it work for Safari browsers? When i set `inputProps={{autoComplete: 'nope' }}` it doesn't work for Safari browsers.

any update on this question? cause i am having the same issue

**Comment by mitchellgsides** [comment]
I'm having the same problem, still. I can't figure out any way around it on Safari.
