### ISSUE TITLE
Allow disable popup option menu for allowCreate

### ISSUE THREAD

**Issue by bbtfr** [JedWatson/react-select#759]
I'm using `react-select` as tags input box, and it would be nice if I can disable the menu manually, since I get no default values / suggestions, I don't want to display `Add "xxx"?` all the time.

Currently, I'm using css to disable it:

```
.Select-menu-outer { display: none; }
```

But it's better if there's a `isOpen` props or something similar.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
