### ISSUE TITLE
Type member is a function. Can't render component

### ISSUE THREAD

**Issue by olethanh** [JedWatson/react-select#76]
I'm having the problem with both react-select 0.3.3 and 0.3.4 in combinaison with React 0.12.2

In the chrome console:
```
e=React.createElement(Select, {name: 'a', options: [{label:'1', value: '1'}]})
      ReactElement {type: function, key: null, ref: null, _owner: null, _context: Object…}
React.render(e, document.getElementById('test_element'))
     react.js:18108 Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
e.type
    react.js:6691 function (props) {
          // This constructor is overridden by mocks. The argument is used
          // by mocks to assert on what gets mounted. This will later be used
          // by the stand-alone class implementation.
        }
````

**Comment by evandegr** [comment]
I'm also having what seems to be a related problem but with .11.2. I'm getting an error 

Uncaught TypeError: undefined is not a function

Inside 

function createDescriptor(type, props, children) {
  var args = Array.prototype.slice.call(arguments, 1);
  return type.apply(null, args);
}

Where type is not a function. It equals 'span'

**Comment by dcousens** [comment]
@olethanh are you sure `Select` is defined in your case?

**Comment by dcousens** [comment]
Closing, please re-open if this issue is relevant.
