### ISSUE TITLE
Disabling the component doesn't close the menu

### ISSUE THREAD

**Issue by gabrielenosso** [JedWatson/react-select#762]
Passing the "disabled={true}", doesn't close the menu.
It means that if you update then the component with "disabled={false}", the component is bugged: it doesn't close properly because the state.isOpen is still false (even though the menu is rendered).

So the closeMenu() method at https://github.com/JedWatson/react-select/blob/master/src/Select.js#L247 isn't invoked.

**Comment by jsnmoon** [comment]
Having the menu close once the component is disabled makes sense, although that's not currently happening here on `1.0.0-beta-13`. Could a collaborator comment on this issue?

**Comment by manvydasu** [comment]
@Rall3n
Seems like this issue appeared again..

**Comment by lijovijayan** [comment]
> @Rall3n
> Seems like this issue appeared again..

yes, i'm also facing the same issue

**Comment by lijovijayan** [comment]
> > @Rall3n
> > Seems like this issue appeared again..
> 
> yes, i'm also facing the same issue.



### Here is what i have done to solve it temporarily

```javascript 

const DropdownIndicator = (props: any) => {
  return (
    <components.DropdownIndicator {...props}>
      { props.selectProps.menuIsOpen && !props.selectProps.isDisabled
        ? <UpOutlined style={{ fontSize: 10, color: "#262626" }} /> :
        <DownOutlined style={{ fontSize: 10, color: "#262626" }} />}
    </components.DropdownIndicator>
  );
};
const ClearIndicator = (props: any) => {
  return (
    <components.ClearIndicator {...props}>
      <CloseOutlined style={{ fontSize: 9, color: "#262626" }} />
    </components.ClearIndicator>
  );
};
const Menu = (props: any) => {
  return props.selectProps.isDisabled ? <div /> : <components.Menu {...props} />
}

const SelectWrapper = (props) => {
	<Select
		{ ...props }
		 components={{ DropdownIndicator, Menu }}
	/>
}

```

**Comment by ebonow** [comment]
Greetings, 

There is another issue #4255 that is currently open that has a PR https://github.com/JedWatson/react-select/pull/4329 and has been scheduled for v3.2. 

We are working with Jed to establish when that exact date is. The code suggested above for the `Menu` component should work to ensure the menu is not shown when the Select is disabled.
