### ISSUE TITLE
Force autocomplete to actually select

### ISSUE THREAD

**Issue by tnrich** [JedWatson/react-select#765]
Hey there, 

I'm having an issue where my react-select dropdown component will be "partially" auto-completed by the browser. This is what that looks like:
![image](https://cloud.githubusercontent.com/assets/2730609/12924463/1b3e9348-cf0f-11e5-84ee-0c1f754b9b39.png)

As you can see, the cursor is still in on the first input. The dropdown has been opened, and a country has been "chosen", but the country isn't actually selected. I'm wondering if anyone knows if there is a way to get the country to be selected and the dropdown closed.

Maybe some little hack where if the dropdown is both open and not focused the country is selected and the dropdown closes?

Thanks for the help!
Thomas

**Comment by cognipla** [comment]
Hi,
 I bet you have not configured your component completely. 
After selecting the item you need to execute action in order re-render the component (to  see the selected items).
By action I mean flux/redux action . In other 'react' words, you need to update your state.
A typical place for it is onChange event. Assuming you have Select component like this:
<Select.Async
            name='someName'
                value={this.state.value}
                multi
                loadOptions={this.getOptions}
                onChange={this.onChange}
                />

your event handler should looks similar too this :

onChange = (value, values) => {
        //console.log('New value:', value, 'Values:', values);
        this.setState({ value: value });// or redux action
}

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by RobMixon** [comment]
This is still an issue

**Comment by minhtran289** [comment]
Would love to see if there's any improvements on this issue
