### ISSUE TITLE
Ability to implement custom menus

### ISSUE THREAD

**Issue by gizotti** [JedWatson/react-select#766]
Hey there,

We are currently implementing an autocomplete field that looks like the image bellow:

![screenshot 2016-02-10 15 29 11](https://cloud.githubusercontent.com/assets/1103597/12939710/42597b28-d00e-11e5-9cbe-7584ace16026.png)

We are using `Select.Async` somewhere else and it works great, however, for this specific input we would like to have a customised menu for the results.
Looking into react-select source we came up with a solution, which is the ability of passing a `renderMenu` menu prop to the `Select` component. This prop would then override [the existing one](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L642) if passed.

I am happy to make the change and put a PR for it, but would like to confirm this is something that would be merged.

Cheers

**Comment by gizotti** [comment]
@JedWatson any thoughts on this one?

**Comment by mehrdaad** [comment]
@gizotti can you describe how you achieve the result? Also I want to change the selected element style to a custom one too.
