### ISSUE TITLE
onClearValue

### ISSUE THREAD

**Issue by firedev** [JedWatson/react-select#768]
Hi,

Please consider adding `onClearValue` handler, this is useful when editing form with a list of dropdowns and you want to add/remove them.

![image](https://cloud.githubusercontent.com/assets/115612/12974772/16ed3b6a-d0e9-11e5-9482-deb44a829942.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
