### ISSUE TITLE
inputProps on the hidden input

### ISSUE THREAD

**Issue by purcebr** [JedWatson/react-select#772]
Hi!

I'm working on using your plugin to build a frontend form for submitting credit card info via stripe.js, and I'm confused about a couple things.
1. It seems like it's not possible to set up a field without a "name" attribute, but still have a hidden input show up when the select box renders. Since the cc info is never passed to the server, I'd like to avoid using the name attribute on the hidden input, and just add a data-stripe attribute instead. the custom data attribute lets stripe know it's a cc field. I'm unclear if this is possible?
2. It seems like inputProps doesn't add custom attributes to the hidden field, but it adds attributes to the "search box" field. Is there a way to add props to the input field?

Maybe it makes more sense to just manipulate the DOM directly to remove name / add data-stripe attributes for this specific case?

thanks!
Bryan

**Comment by purcebr** [comment]
Hi, just wanted to follow up with my solution to this -

`document.getElementsByName('expyear')[0].setAttribute("data-stripe", "exp-year");`
`document.getElementsByName('expyear')[0].removeAttribute("name");`

I used a variation of the above code for each of my Components wrapping the <Select> component - (Month Picker and Year Picker)

open to suggestions as to how to do this better, but this appears to solve the problem for now!

thanks,
Bryan

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
