### ISSUE TITLE
names conflict

### ISSUE THREAD

**Issue by plandem** [JedWatson/react-select#774]
WARNING in ./~/classnames/index.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

**Comment by razh** [comment]
You may be using different casings when importing the `classnames` module. They should all be lowercase.

Are you doing this anywhere?
```js
import classNames from 'classNames';
```

**Comment by plandem** [comment]
yep, i used like this everywhere.
