### ISSUE TITLE
showing option value instead of label upon loading

### ISSUE THREAD

**Issue by ttyao** [JedWatson/react-select#778]
When using asynOptions with some pre-selected options on multi select mode, the pre-selected options will show as the value instead of label until the whole thing is loaded. Although it is probably a few seconds or even less, it is a bad user experience. I prefer not showing these values until the full thing is loaded.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
