### ISSUE TITLE
How can I add custom scrollbar??

### ISSUE THREAD

**Issue by hank7444** [JedWatson/react-select#780]
I would like to use react-scrollbar as follow:

```
<ScrollArea>
   menu.....
</ScrollArea>
```

but I can't find any function that can do this, have any idea?

**Comment by kaiohon** [comment]
Is there a possibility to use SimpleBar for the custom scrollbars?

**Comment by DmitriyWebDev** [comment]
The question is really still relevant!

**Comment by manu1222** [comment]
The question is really still relevant!

**Comment by manu1222** [comment]
The question is still relevant! But no solution, either kill me or kill IE. :D

**Comment by zzossig** [comment]
```
import Select from "react-select";
const MyComponent = () => {
  const renderScrollbar = props => {
    return (
      <div className={classes.menuList}>
        <Scrollbars>{props.children}</Scrollbars>
      </div>
    );
  };
  
  return (
    <Select
       ....
       components={{ MenuList: renderScrollbar }}
    />
  );
}
```
something like this works for me.

**Comment by Grsmto** [comment]
@kaiohon yes you can use SimpleBar. Please have a look at that example: https://codesandbox.io/s/simplebar-reactselect-gwgpu

```js
const renderScrollbar = props => {
  return (
    <ReactSimpleBar style={{ maxHeight: 300 }}>{props.children}</ReactSimpleBar>
  );
};

function App() {
  return (
      <Select
        ...
        components={{ MenuList: renderScrollbar }}
      />
  );
}
```

**Comment by Tomassito** [comment]
> ```
> import Select from "react-select";
> import Scrollbars from "react-custom-scrollbars";
> 
> const MyComponent = () => {
>   const renderScrollbar = props => {
>     return (
>       <div style={{ height: 300 }}>
>         <Scrollbars>{props.children}</Scrollbars>
>       </div>
>     );
>   };
>   
>   return (
>     <Select
>        ....
>        components={{ MenuList: renderScrollbar }}
>     />
>   );
> }
> ```
> 
> something like this works for me.

Can you share a codesanbox with this working? I copied this and didn't work for me. Also, no need to wrap it in additional div just to get the height, as you can set autoHeight and autoHeightMax on Scrollbars.

**Comment by kyunghoon-KIM** [comment]
@Tomassito Is this what you are looking for?
[codesandbox link](https://codesandbox.io/s/cocky-chatelet-o1qng?fontsize=14)

**Comment by zzossig** [comment]
@Tomassito Here you are
[codesandbox link](https://codesandbox.io/s/cocky-chatelet-o1qng?fontsize=14)

**Comment by MDSilviu** [comment]
> @kaiohon yes you can use SimpleBar. Please have a look at that example: https://codesandbox.io/s/simplebar-reactselect-gwgpu
> 
> ```js
> const renderScrollbar = props => {
>   return (
>     <ReactSimpleBar style={{ maxHeight: 300 }}>{props.children}</ReactSimpleBar>
>   );
> };
> 
> function App() {
>   return (
>       <Select
>         ...
>         components={{ MenuList: renderScrollbar }}
>       />
>   );
> }
> ```
the  scroll doesn't work with the version 3.05

**Comment by sandbox4013** [comment]
Scroll doesn't work start with react-select's versions 3.0.5 - 3.0.8 - checked on @Tomassito codesandbox. 
3.0.4 works fine for me

**Comment by giladToluna** [comment]
Hello.
Here you can find example for react-select using Simplebar + keyboard navigation + scroll to selected on menu open: 
https://codesandbox.io/s/react-selectsimplebarkeboard-g6hfs

It's a bit hacky.., and also a bit flashy,  but didn't find any better solution until now.
I used timeout because when the keyDown action is called, the focused option is the previous one..
( and we want to check the new one )

**Comment by taiwanhua** [comment]
you can just use styled-component to rewrite css, like below


`
import Select from 'react-select'
import styled from 'styled-components'

const SelectExtend = styled(Select).attrs((props) => ({}))`
    && {
        [class*="MenuList"] {
            //滾動條美化
            ::-webkit-scrollbar {
                width: 0.5em;
                height: ${props => props?.theme?.scrollHeight ?? 'initial'}; //scroll-x 的高度
            }
            ::-webkit-scrollbar-track {
                -webkit-border-radius: 10px;
                border-radius: 10px;
                margin:0px 0.1rem 5px 0;
            }
            ::-webkit-scrollbar-thumb {
                -webkit-border-radius: 4px;
                border-radius: 4px;
                background: ${props => props?.theme?.scrollUnhoverBackgroundColor ?? '#9093994d'};
            }
            &:hover::-webkit-scrollbar-thumb {
                -webkit-border-radius: 4px;
                border-radius: 4px;
                background: ${props => props?.theme?.scrollHoverBackgroundColor ?? '#9093994d'};
            }
        }
    }
`
`

**Comment by taiwanhua** [comment]
you can just use styled-component to rewrite css, like below :

```code
import Select from 'react-select'
import styled from 'styled-components'

const SelectExtend = styled(Select).attrs((props) => ({}))`
    && {
        [class*="MenuList"] {
            //滾動條美化
            ::-webkit-scrollbar {
                width: 0.5em;
                height: ${props => props?.theme?.scrollHeight ?? 'initial'}; //scroll-x 的高度
            }
            ::-webkit-scrollbar-track {
                -webkit-border-radius: 10px;
                border-radius: 10px;
                margin:0px 0.1rem 5px 0;
            }
            ::-webkit-scrollbar-thumb {
                -webkit-border-radius: 4px;
                border-radius: 4px;
                background: ${props => props?.theme?.scrollUnhoverBackgroundColor ?? '#9093994d'};
            }
            &:hover::-webkit-scrollbar-thumb {
                -webkit-border-radius: 4px;
                border-radius: 4px;
                background: ${props => props?.theme?.scrollHoverBackgroundColor ?? '#9093994d'};
            }
        }
    }
`
```

**Comment by ebonow** [comment]
Greetings all, 

This issue has been open quite a while, so I will recap before closing this.

Using a custom scrollbar does work:
[react-select v3.0.4](https://codesandbox.io/s/cocky-chatelet-o1qng?fontsize=14&file=/src/MySelect.js)
[react-select v.4.0.2](https://codesandbox.io/s/react-selectsimplebarkeboard-g6hfs)

There was a bug introduced in v3.0.5, which was later resolved in version 4. In the affected versions, it is however possible to set `captureMenuScroll` to `false` to make the functionality work in these versions with simplebar.

It is also worth mentioning that there are viable css/style solutions that may be worth implementing:
You can see the [above example](https://github.com/JedWatson/react-select/issues/780#issuecomment-657983928) or also this one [which utilizes react-selects styles api](https://github.com/JedWatson/react-select/issues/4211#issuecomment-691541202) but also note that this is not supported by IE/Firefox users which may or may not be consider a graceful degradation in UX.

```jsx
const styles = {
  menuList: (base) => ({
    ...base,
    height: "100px",

   "::-webkit-scrollbar": {
     width: "9px"
   },
   "::-webkit-scrollbar-track": {
     background: "red"
   },
   "::-webkit-scrollbar-thumb": {
     background: "#888"
   },
   "::-webkit-scrollbar-thumb:hover": {
     background: "#555"
   }

return <Select styles={styles} {...otherProps} />
```

Related issues: https://github.com/JedWatson/react-select/issues/4221 and https://github.com/JedWatson/react-select/issues/4227

**Comment by alimzhanovamir** [comment]
> Greetings all,
> 
> This issue has been open quite a while, so I will recap before closing this.
> 
> Using a custom scrollbar does work:
> [react-select v3.0.4](https://codesandbox.io/s/cocky-chatelet-o1qng?fontsize=14&file=/src/MySelect.js)
> [react-select v.4.0.2](https://codesandbox.io/s/react-selectsimplebarkeboard-g6hfs)
> 
> There was a bug introduced in v3.0.5, which was later resolved in version 4. In the affected versions, it is however possible to set `captureMenuScroll` to `false` to make the functionality work in these versions with simplebar.
> 
> It is also worth mentioning that there are viable css/style solutions that may be worth implementing:
> You can see the [above example](https://github.com/JedWatson/react-select/issues/780#issuecomment-657983928) or also this one [which utilizes react-selects styles api](https://github.com/JedWatson/react-select/issues/4211#issuecomment-691541202) but also note that this is not supported by IE/Firefox users which may or may not be consider a graceful degradation in UX.
> 
> ```js-jsx
> const styles = {
>   menuList: (base) => ({
>     ...base,
>     height: "100px",
> 
>    "::-webkit-scrollbar": {
>      width: "9px"
>    },
>    "::-webkit-scrollbar-track": {
>      background: "red"
>    },
>    "::-webkit-scrollbar-thumb": {
>      background: "#888"
>    },
>    "::-webkit-scrollbar-thumb:hover": {
>      background: "#555"
>    }
> 
> return <Select styles={styles} {...otherProps} />
> ```
> 
> Related issues: #4221 and #4227

This won't work in firefox.

**Comment by ebonow** [comment]
> This won't work in firefox.

Added styling to make this point more clear.

**Comment by nodir-sulaymonov** [comment]
@Grsmto your example doesn't work ((
