### ISSUE TITLE
beta9 transpiled files aren't up to date

### ISSUE THREAD

**Issue by fhelwanger** [JedWatson/react-select#781]
I think that last released version files aren't up to date.

On the [changelog](https://github.com/JedWatson/react-select/blob/master/HISTORY.md#v100-beta9--2015-02-12) it says that:

> changed; Enter selects and retains focus, Tab selects and shifts focus, thanks RDX

It was made on #718.

But that change is only on `src/Select.js`, not on `lib/Select.js`.

`src/Select`

```js
336.	case 9: // tab
337.		if (event.shiftKey || !this.state.isOpen) {
338.			return;
339.		}
340.		this.selectFocusedOption();
341.	return;
```

`lib/Select`

```js
365.	case 9:
366.		// tab
367.		if (event.shiftKey || !this.state.isOpen) {
368.			return;
369.		}
370.		this.selectFocusedOption();
371.		break;
```

I installed through `npm` and checked my `node_modules` to verify it.

**Comment by JedWatson** [comment]
Thanks for the heads up @fhelwanger. I've updated the build & pushed beta 10.
