### ISSUE TITLE
Add prop to open the options menu on initial render

### ISSUE THREAD

**Issue by ijohnson888** [JedWatson/react-select#782]
I think an initialOpen prop should be added to configure whether or not the menu is opened when it is first displayed.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
