### ISSUE TITLE
Provide the optionRenderer access to the inputValue

### ISSUE THREAD

**Issue by ijohnson888** [JedWatson/react-select#783]
In one of my cases, I found that I needed access to the filter's inputValue in the optionRenderer function. As far as I can tell, in the current code there isn't another way to provide it to this function outside of tracking it separately via onChange in the parent component, which seems excessive.

**Comment by Orangeyness** [comment]
This would be useful for me too. I would like to have my custom optionRenderer highlight the segment of the label which matches the filter.

**Comment by JedWatson** [comment]
I've implemented this now, will be published in 1.1.0
