### ISSUE TITLE
React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements)

### ISSUE THREAD

**Issue by Klaitos** [JedWatson/react-select#788]
Getting this error :/

`
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `

```JAVASCRIPT
           <Select.Async
                name="form-field-name"
                value={this.props.selectValue}
                placeholder='Choisir'
                loadOptions={this.getOptions}
                onChange={this.updateValue}
                clearable={false}
                optionRenderer={this.renderOption}
            />);`

**Comment by kopaygorodsky** [comment]
I have the same issue.

**Comment by mkardas91** [comment]
Maybe You use 0.9 version while reading docs from 1.0.0 beta
try this
<Select
    name="form-field-name"
    value="one"
    asyncOptions={getOptions}
/>
https://github.com/JedWatson/react-select/tree/v0.9.1

**Comment by Klaitos** [comment]
Thanks mate ! You solved this
