### ISSUE TITLE
allowCreate new option in not multi mode

### ISSUE THREAD

**Issue by sanjaypoyzer** [JedWatson/react-select#795]
Is there a way for users to create a new option when the component is not in multi mode? 

This question was asked before in issue #324 but without the constraint of not being in multi mode.

**Comment by hari-rangarajan** [comment]
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L360

allowCreate seems to be disabled in the code. Does it even work for you? I'm also interested in creating new options in any mode.

**Comment by Secretmapper** [comment]
+1

**Comment by simpixelated** [comment]
`allowCreate: true` (aka "tags mode") is still in development for 1.0. See https://github.com/JedWatson/react-select/issues/568#issuecomment-153785740

**Comment by pierre-b** [comment]
+1

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

Look for an updated RC with this functionality soon. 😎
