### ISSUE TITLE
Changing value does not update select label or hidden input

### ISSUE THREAD

**Issue by johannesarnbro** [JedWatson/react-select#796]
I've added react-select to my react/redux project. Everything works as expected, except that changing value does not change the label of the select. Also the value of the hidden input is not set.

![untitled](https://cloud.githubusercontent.com/assets/11028434/13355530/26648d8c-dca1-11e5-9776-15c795a8fb2b.gif)

[react-select-bug.zip](https://github.com/JedWatson/react-select/files/148358/react-select-bug.zip)

**Comment by jooj123** [comment]
This isnt a bug, you need to change the `value` thats being supplied to Select - this can be done in your `onChange` handler

**Comment by oncletom** [comment]
Looks like a breaking change because it used to work differently in the past.

And to be honest, this is the kind of behaviour which is *native* — and should probably be better to override in some rare cases. I looked for a while trying to figure out what was wrong.

**Comment by d4nyll** [comment]
Yes - what @jooj123 said - you need to do something like this:

```
export default class CurrencySelector extends Component {
    constructor(props) {
        super(props);
        
        this.state = {
            currency: DEFAULT_CURRENCY
        }
    }
    
    updateState(newCurrency) {
        this.setState({
            currency: newCurrency.value
        });
    }

    render() {
        return (
            <ReactSelect
                value={this.state.currency}
                onChange={this.updateState}>
            </ReactSelect>
        );
    }
}
```

But I do think this is not clear in the documentation. The document states that the `value` is the `initial field value`, which can lead people to think it behaves like the `defaultValue` prop of a 'normal' React element.

Maybe the documentation should be more explicit, because not everyone (have time to) studies the examples.

**Comment by romgrk** [comment]
Up. I think @d4nyll has a valid point about the documentation. I have been relying on it to use the component, and it is clearly misleading.

**Comment by leefsmp** [comment]
I'm here because I'm having trouble to display the selected value of a select control ... I love React! :'(

**Comment by okyere** [comment]
React-select is a controlled component. So you need to set the value prop with the a state of the component as illustrated by @d4nyll

**Comment by eugensunic** [comment]
This should have been in the docs at the front page on github. I spent an hour at night figuring out what is going on.  I assumed that this was already built in but it wasn't, full working code for everyone:

```
import React from "react"
import Select from 'react-select';

export default class Header extends React.Component {
  constructor(props) {
     super(props);
     this.state = {value:"one"};
   }
  updateState(element) {
        this.setState({value: element});
      }
  render(){
  var Select = require('react-select'); //only for server-side
  var options = [
      { value: 'one', label: 'One' },
      { value: 'two', label: 'Two' }
  ];
    return(

      <Select
        name="form-field-name"
        value={this.state.value}
        options={options}
        onChange={this.updateState.bind(this)}
      />
   );
  }
}

```

**Comment by oanaalex** [comment]
Thank you @eugensunic so much!

**Comment by sahan91** [comment]
This thread helped me too. I was using `valueArray` instead of `value`. Changing that worked for me

**Comment by fatahn** [comment]
Having  a `label` key in my options object helped fix this for me! Anybody understand why?

**Comment by aprilmintacpineda** [comment]
I recently experienced this when debugging an existing code using `react-select`. I noticed that you actually need to provide an Object instead of a string as a value.

Example:

```js
const options = [
  {
    label: 'Value 1',
    value: 1
  },
  {
    label: 'Value 2',
    value: 2
  },
  {
    label: 'Value 3',
    value: 3
  }
];

// ...others

<ReactSelect
  value={{
    value: 2,
    label: 'Value 2'
  }}
  options={options}
/>
```

**Comment by khushaldusseja** [comment]
@aprilmintacpineda : This is really helpful. Many thanks for sharing this answer!
cheers

**Comment by peshoicov** [comment]
@aprilmintacpineda , not only that you have to provide object, but this object must have both same value AND same label as the options of the react-select.
I think react-select should automatically handle this IMHO.
1. if you provide simple value (string, number) - compare it with the value properties of the options;
2. and if you provide object - compare only the value properties of both provided object and the select's options.
=====
Aside from this - how are you clearing your value in your case? ... What mini-object can you provide that will reset/clear the value of the react-select? ... Cause on my side - I can't do it by simply providing a value property. I must refresh the whole page ... which is not fun, as you may imagine :( ...

**Comment by Alexander-Welsh** [comment]
Is there any explanation for why a string can't be accepted here?  

Does it really need vary from "A DOMString reflecting the value of the form control"?

**Comment by ebonow** [comment]
@Alexander-Welsh - Greetings,

My understanding is that the primary reason for this is to have a consistent Type for the Option and accepting either a string or object creates a lot of complexity in different parts of the source code. To that point, the effort to map an array of strings to an array of objects should be straight forward.

```jsx
const options = arrayOfStrings.map(label => ({ label, value: label })
```

**Comment by rubimbura** [comment]
I faced a smillar issue, the solution is to pass the value property and object.    

<Select
    value={ { label: 1, value: 1 } }
/>

**Comment by abenhamdine** [comment]
> I recently experienced this when debugging an existing code using react-select. I noticed that you actually need to provide an Object instead of a string as a value. 

How the hell is this not displayed on first page of the docs  ??  
I've noticed there is zero example of controlled component in the docs.

**Comment by pefad** [comment]
incase anyone saw this, use IonSelect instead of select it will work fine. for example:
          {/* Role */}
    <div className="form-group">
      <label>Role</label>
      <IonSelect
        value={newuserData.role}
        placeholder="Select Role"
        onIonChange={(e) => {
          const selectedValue = e.detail.value;
          setnewUserData({ ...newuserData, role: selectedValue });
        }}
      >
        <IonSelectOption value="">Select Role</IonSelectOption>
        <IonSelectOption value="admin">Administrator</IonSelectOption>
        <IonSelectOption value="manager">Manager</IonSelectOption>
        <IonSelectOption value="seller">Seller</IonSelectOption>
        <IonSelectOption value="service">Customer Service</IonSelectOption>
        <IonSelectOption value="engineer">Engineer</IonSelectOption>
        <IonSelectOption value="user">User</IonSelectOption>
      </IonSelect>
    </div>

**Comment by pefad** [comment]
`
          {/* Role */}
    <div className="form-group">
      <label>Role</label>
      <IonSelect
        value={newuserData.role}
        placeholder="Select Role"
        onIonChange={(e) => {
          const selectedValue = e.detail.value;
          setnewUserData({ ...newuserData, role: selectedValue });
        }}
      >
        <IonSelectOption value="">Select Role</IonSelectOption>
        <IonSelectOption value="admin">Administrator</IonSelectOption>
        <IonSelectOption value="manager">Manager</IonSelectOption>
        <IonSelectOption value="seller">Seller</IonSelectOption>
        <IonSelectOption value="service">Customer Service</IonSelectOption>
        <IonSelectOption value="engineer">Engineer</IonSelectOption>
        <IonSelectOption value="user">User</IonSelectOption>
      </IonSelect>
    </div>
    `
