### ISSUE TITLE
Error when referencing in script tag

### ISSUE THREAD

**Issue by psimoneau22** [JedWatson/react-select#800]
I am getting an unhandled exception when simply referencing the dist/react-select.js file:  Uncaught Error: Cannot find module 'react-dom'

Here is my html and package.json

```
<html>
<head>
    <link rel="stylesheet" href="node_modules/react-select/dist/react-select.css"></link>

    <script src="node_modules/classnames/index.js"></script>
    <script src="node_modules/react/dist/react.js"></script>
    <script src="node_modules/react-dom/dist/react-dom.js"></script>
    <script src="node_modules/react-input-autosize/dist/react-input-autosize.js"></script>
    <script src="node_modules/react-select/dist/react-select.js"></script>
</head>
<body></body>
</html>
```

```
{
  "name": "testselect",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "classnames": "^2.2.3",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-input-autosize": "^0.6.8",
    "react-select": "^0.9.1"
  }
}
```

![image](https://cloud.githubusercontent.com/assets/5247998/13372979/d6ce89b6-dd28-11e5-9f5e-7ea250d04673.png)

**Comment by psimoneau22** [comment]
This is fixed by changing line 82 of react-select.js

From this:
var ReactDOM = require('react-dom')

To this:
var ReactDOM = (typeof window !== "undefined" ? window['ReactDOM'] : typeof global !== "undefined" ? global['ReactDOM'] : null);

**Comment by lruckman** [comment]
Using the 1.0.0-beta10 version fixed this for me. Also if compiling server side making sure to include the react-dom-server.js instead of react-dom.js.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
