### ISSUE TITLE
ReactScriptLoadException: Error while loading "~/lib/react-select/dist/react-select.js": Script threw an exception: Unable to get property 'PropTypes' of undefined or null reference

### ISSUE THREAD

**Issue by lruckman** [JedWatson/react-select#802]
New to all this and trying to get react-select (1.0.0-beta10) running in a .NET MVC 6 application. Got the package installed and have all dependencies included but whenever [React.NET ](https://github.com/reactjs/React.NET) compiles my jsx plus the dependencies (classnames, react-input-autosize, react-select) I'm seeing this error:

ReactScriptLoadException: Error while loading "~/lib/react-select/dist/react-select.js": Script threw an exception: Unable to get property 'PropTypes' of undefined or null reference
 Line: 0
 Column: 0

Any clues?

**Comment by lruckman** [comment]
Seems like using the bundle.js file in examples/dist fixes the issue.

**Comment by ntdb** [comment]
I'm experiencing this as well with a fresh install of `1.0.0-beta11`. The error is at [this line](https://github.com/JedWatson/react-select/blob/master/dist/react-select.js#L54) in `react-select.js`.
