### ISSUE TITLE
keep selected items in menu

### ISSUE THREAD

**Issue by FranBran** [JedWatson/react-select#803]
I'd like to be able to keep selected items in the menu in order to implement a dropdown behaving similar to the multi-select at [MaterializeCss](http://materializecss.com/forms.html#select)

here's a screenshot: 
![multiselect](https://cloud.githubusercontent.com/assets/1215407/13396093/01389518-def3-11e5-8e9e-82fbf0c50da2.PNG)

**Comment by dherran** [comment]
Would definitely love to have the option to keep elements in the select box.

**Comment by dherran** [comment]
Just pushed a pull request for this: #882 

Options can easily be styled to look that way with some pseudo-elements.

**Comment by reintroducing** [comment]
Was literally about to ask for the same thing in a new issue and glad I looked over the current issues. I have a very valid use case for this as well and would love to see this get integrated.

**Comment by MarcZenn** [comment]
@JedWatson  Did this ever get resolved? The original issue was posted early 2016 so I'm hoping there's a solution for this by now.

**Comment by dherran** [comment]
Not yet. I sent a pull request ages ago that tackles this. It hasn't been merged into master yet. https://github.com/JedWatson/react-select/pull/882

**Comment by MarcZenn** [comment]
Thanks @dherran. I'm looking over it now to see if I can incorporate your changes into my project here but so far no luck. Hope it gets accepted soon.

**Comment by mihailmetro** [comment]
@dherran any news on this ?

**Comment by banderson** [comment]
Just a heads up that there is _some_ activity happening here. Not sure what to call it yet :)

https://github.com/JedWatson/react-select/pull/1891

**Comment by stilllife00** [comment]
This was merged long time ago but the prop is not in the file anymore. Any update?

**Comment by Rall3n** [comment]
@stilllife00 `removeSelected` was a prop introduced in `v1.x`.

In `v2+` the prop was renamed to `hideSelectedOptions`.
