### ISSUE TITLE
Feature request: valueLink/linkState support

### ISSUE THREAD

**Issue by CezaryDanielNowak** [JedWatson/react-select#804]
Reference:
- https://facebook.github.io/react/docs/two-way-binding-helpers.html
- https://github.com/srph/react-link-state

react inputs supports valueLink to link input value with component state.
In my case it works like this:

```
import React from 'react';
import Select from 'react-select';
import linkState from 'react-link-state';

const linkSelectState = (that, prop) => {
  return (valueObj) => {
    that.setState({
      [prop]: valueObj ? valueObj.value : null
    });
  };
};

export default class ComponentName extends Component {
  state = {
    val1: null,
    val2: null
  }
  render() {
  return (
    <div className="input-group">
      <input
        type="text"
        placeholder="Legal Name"
        valueLink={linkState(this, 'val1')}
      />
      <Select
        name="val2"
        options={...}
        value={this.state.val2}
        onChange={linkSelectState(this, 'val2')}
      />
    </div>
  );
  }
}
```

The ideal solution would be if I can do just `import Select, { linkSelectState } from 'react-select';`

**Comment by kulakowka** [comment]
`valueLink` is [deprecated](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html#new-deprecations-introduced-with-a-warning) in React v15.0.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
