### ISSUE TITLE
When component is searchable, onBlur always resets value even when onBlurResetsInput is set to false

### ISSUE THREAD

**Issue by akalajzi** [JedWatson/react-select#805]
Hi.
These are the options I'm using:

```
        <Select
          {...field}
          value={field.value}
          name={field.name}
          searchable
          onBlurResetsInput={false}
          clearable={false}
          className={"form-control"}
          options={options}
        />
```

Though I've tried all sorts of combinations, and the only way I can get selected value to stick is to set `searchable` to false. Otherwise, input resets when I click outside select.
Watching the state change, selecting option really does set value, and onBlur resets it.

Bug, or am I doing something wrong?

**Comment by jeffreybrowning** [comment]
I have seen this as well.

**Comment by akalajzi** [comment]
So I'm not crazy. Its quite a bug. Found any solution around it?

**Comment by tiagoengel** [comment]
As a workaround, you can add ```onBlur={() => {}}``` or if you're using redux-form ```onBlur={() => field.onBlur({value: field.value})}```

**Comment by MilllerTime** [comment]
Seems like this is still an issue.

@tiagoengel's suggestion is a decent workaround. If you're using redux-form v6, you'll want to use the updated blur handler as follows (make sure you place it after you spread the redux-form `input` prop!)
```JS
onBlur={() => input.onBlur(input.value)}
```

[Link to doc](http://redux-form.com/6.0.5/docs/api/Field.md/#-input-onblur-eventorvalue-function-) for  `onBlur()` signature.

**Comment by M3lkior** [comment]
it seems that `input.value` match the value/ label pair : 

My store state when selecting an item : 

![image](https://cloud.githubusercontent.com/assets/5501911/19276506/d7f42aa6-8fd6-11e6-97b6-a44ff4418534.png)

So, it works better if onBlur was used with `input.value.value`  : 

`onBlur={() => input.onBlur(input.value.value)}`

**Comment by MilllerTime** [comment]
@M3lkior I'm not seeing the behavior you described. How is your `input` prop from redux form getting a value/label pair in the first place? Seems to me that is the root of your issue, and fixing it in `onBlur` just fixes it for submission. Is something weird going on in your `onChange` handler?

**Comment by AlfredoQT** [comment]
It's not working on mobile though...

**Comment by resputin** [comment]
@alfredoqt I was running into the same issue, it looks like the blur and change actions from redux form were being called simultaneously when on mobile so the props weren't updated when the blur function checks the `input.value` prop. I just wrote a blur handler to check the value on the next tick and it solved it for me.

```js
const handleBlur = () => {
    setTimeout(() => {
      props.input.onBlur(props.input.value);
    }, 1);
  };
```

**Comment by vladpoltorin** [comment]
resolved that issue with
`handleInputChange = (inputValue, params) => {
  if (params.action === 'input-change') {
    this.setState({inputValue});
  }
};`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by johnnymetz** [comment]
For the record, this is still an issue.

**Comment by YopiRagil** [comment]
I try this trick and work for me:
`
.....
useEffect(() => {
    const timeout = setTimeout(() => {
          const el = document.getElementById("search-on-select");
          if (!!el) {
              el.focus();
          }
      }, 200);
      return () => {
          clearTimeout(timeout);
      };
  }, [isLoading]);
.....
 return( 
<Select
         ....... 
         inputId='search-on-select'
         isLoading={isLoading}
          ......
/>)
`
