### ISSUE TITLE
Setting required returns false negative when passing value as simpleValue

### ISSUE THREAD

**Issue by dayyeung** [JedWatson/react-select#806]
As mentioned at https://github.com/JedWatson/react-select/pull/731/files#r54407162, `handleRequired` incorrectly returns true when `value` is a number.

> multi value is an array, while single value is an Object like { label: 'Whatevz', value: 'Bananas' }

Actually single value could still be a string or number even when `simpleValue` is `false`, when `handleRequired` is called with pre-normalized `value`: https://github.com/JedWatson/react-select/blob/de462f58114da360caa5dfd31483c8497e4508a6/src/Select.js#L127

ping @dmatteo

**Comment by mshwery** [comment]
Encountered this same issue.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
