### ISSUE TITLE
allowCreate property not working

### ISSUE THREAD

**Issue by prakkarp** [JedWatson/react-select#811]
I am trying to use the allowCreate property but it is not working. On looking at Select.js I see code sections corresponding to allowCreate are commented out. Could you give me a tentative timeline on when this feature will be available for use? I am using 1.0.0-beta10

**Comment by simpixelated** [comment]
`allowCreate: true` (aka "tags mode") is still in development for 1.0. See https://github.com/JedWatson/react-select/issues/568#issuecomment-153785740

**Comment by jmeas** [comment]
A workaround can be found here: https://github.com/JedWatson/react-select/issues/586#issuecomment-177047129

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

Look for an updated RC with this functionality soon. 😎
