### ISSUE TITLE
For Async, call 'props.onInputChange' before loadOptions

### ISSUE THREAD

**Issue by adorsk** [JedWatson/react-select#813]
I think we should call 'props.onInputChange' before loadOptions.

This will allow for capturing raw input, as well as doing other things related to input changes.

This is also an alternative to https://github.com/JedWatson/react-select/pull/779 . Instead of passing the rawInput to loadOptions, users can capture it themselves via onInputChange.

I will submit a PR with a possible implementation.

**Comment by jasonh42** [comment]
This is a pretty big issue for me as well - I need to know when the input changes for the Async component.

**Comment by JedWatson** [comment]
Added by #914
