### ISSUE TITLE
Validate values when allowCreate and reject if needed

### ISSUE THREAD

**Issue by Shnolik** [JedWatson/react-select#815]
Looking for an option to validate options created by user (eg: value must be a valid email address).
Need to be able to reject the new value if it is not valid

**Comment by bradbirnbaum** [comment]
+1 - we need this as well

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

The new `Creatable` HOC supports a configurable `isValidNewOption ` property that allows users to do custom validation on options. Learn more [here](https://github.com/JedWatson/react-select#creatable-properties).

Look for an updated RC with this functionality soon. 😎
