### ISSUE TITLE
Pressing enter would add the tag

### ISSUE THREAD

**Issue by Ricardonacif** [JedWatson/react-select#818]
Guys, when adding a new tag, wouldn't be great if I could press enter and then the tag gets added (instead of the click on Add "tag")? Is there this option already or can I submit a PR?

**Comment by iominh** [comment]
Is there still any interest in this and by "tag" do you mean "value" (to fit react-select terminology)? I've implemented this feature (called "automatic tokenization" in Select2 land; https://select2.github.io/examples.html#tokenizer) in a branch but wanted to ping here first before submitting a PR

**Comment by Ricardonacif** [comment]
See #999
