### ISSUE TITLE
option should support title property when needed

### ISSUE THREAD

**Issue by yangjian666** [JedWatson/react-select#819]
such as 
`<option tile="example">example</option>`

**Comment by belkosyak** [comment]
Duplicates https://github.com/JedWatson/react-select/issues/273

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
