### ISSUE TITLE
Warning: a `input` tag was passed a numeric string value for CSS property (React v15.0)

### ISSUE THREAD

**Issue by kulakowka** [JedWatson/react-select#820]
I trying to upgrade my application to [React v15.0](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html). After the upgrade, I saw a message on the console:

```
Warning: a `input` tag (owner: `AutosizeInput`) was passed a numeric string value for CSS property
`width` (value: `5`) which will be treated as a unitless number in a future version of React.
```

Perhaps, could you correct it now?

**Comment by adidahiya** [comment]
Looks like this is the offending line: https://github.com/JedWatson/react-select/blob/master/src/Select.js#L600

Was the intent of this code to apply `width: 100%`?

**Comment by jazoom** [comment]
Is this from this library: react-input-autosize?

**Comment by kbytin** [comment]
I have similar situation:
```
 Warning: a `div` tag (owner: `Select`) was passed a numeric string value for CSS property `paddingTop` (value: `5`) which will be treated as a unitless number in a future version of React.
```
Just after update to React v15
