### ISSUE TITLE
html do not match css: official demo is "Select-value", but I get "Select-item"

### ISSUE THREAD

**Issue by sinkcup** [JedWatson/react-select#821]
`package.json`:
"react": "^0.14.7",
"react-select": "^0.9.1",

css:
<link href="//cdn.rawgit.com/JedWatson/react-select/v1.0.0-beta10/dist/react-select.min.css" rel="stylesheet" />

when I click on a multi select , I will grant `<div class="Select-item" />`, it doesn't match a css.
but I look at the official demo at http://jedwatson.github.io/react-select/ , it grant `<div class="Select-value" />`, css is fine.

screenshots:
my:
![2016-03-09 16-47-06](https://cloud.githubusercontent.com/assets/4971414/13629959/7aff3d90-e617-11e5-94c3-3c359ba34d68.png)
official:
![2016-03-09 16-47-29](https://cloud.githubusercontent.com/assets/4971414/13629969/87098622-e617-11e5-863c-7ac942b55b46.png)

**Comment by facultymatt** [comment]
+1 I'm finding it more difficult than expected to get an example working like the demo pages.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
