### ISSUE TITLE
how to auto submit form when onChange, suggest: return element

### ISSUE THREAD

**Issue by sinkcup** [JedWatson/react-select#822]
> When the value is changed, onChange(newValue, [selectedOptions]) will fire.

when use html select, we can auto submit this form when "onChange", because `onChange(event)` will fire, we can get the element from event, so can submit parent form.

now using react-select, there is no "element", so how to auto submit form when onChange?

suggest: onChange(newValue, [selectedOptions], [element])

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
