### ISSUE TITLE
Weird behavior: Scrolling to the first non disabled option in menu

### ISSUE THREAD

**Issue by kmudrick** [JedWatson/react-select#825]
If you have disabled items in your menu, the fact that this component scrolls to the first focusable option means that those disabled options are effectively hidden right away unless the user manually scrolls or uses keyboard navigation to go up.

I'm using the latest 1.0.0 beta.

Can we make this a prop to disable this behavior?

I believe the behavior is happening from here: https://github.com/JedWatson/react-select/blob/v1.0.0-beta11/src/Select.js#L149

**Comment by pollen8** [comment]
fyi react-select-plus fixed this for me

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
