### ISSUE TITLE
Select.Async prop minimumInput doesn't work with loadOptions

### ISSUE THREAD

**Issue by cloudhyde** [JedWatson/react-select#829]
I created a component like this:
```
<Select.Async
                        name="mySelect"
                        loadOptions={loadSelectOptions}
                        minimumInput={3}
                        placeholder="Type at least 3 characters to search..."
                        onChange={onChangeSelect}
                        multi={true}
                        />

loadSelectOptions: function (input, callback) {
        callback(null, {
            options: [
                { value: 'one', label: 'One' },
                { value: 'two', label: 'Two' }
            ]
        });
    }
```
It always returns empty options. But when I remove minimumInput prop, it works again.

**Comment by jljorgenson18** [comment]
I think I ran into this too. Not entirely sure why but it seemed to start working when I returned a promise instead of using a callback in the loadOptions function.

**Comment by cloudhyde** [comment]
That's weird, even when I return a promise it doesn't work for me as well.
My function is like: 
```
return $.ajax({
            url: conf.url + input,
            type: 'GET',
            dataType: 'json'
        }).then(function (data) {
            var options = data.map(function (item) {
                return {
                    value: item.id,
                    label: item.name
                };
            });
            return {
                options: options
            }
        });
```

**Comment by jljorgenson18** [comment]
I wonder if its related to multi? My setup is very similar except multi is off but clearable and searchable are both true.

I would also remove the callback parameter if its still an arg in the loadOptions function.... just a hunch.

**Comment by cloudhyde** [comment]
Thanks @jljorgenson18 , but still no luck. I found Select props.options has already been updated, but after render it still shows no data returned.

**Comment by cloudhyde** [comment]
I know why, it's because of JSON file I provided...
