### ISSUE TITLE
Input is undefined

### ISSUE THREAD

**Issue by evandegr** [JedWatson/react-select#83]
Am I the only crazy one having this problem? The React-Autocomplete Input is undefined in the standalone version.  I'm not using Require in my project so it is not easy for me to grab the React-Autocomplete files to complete the dependency. Is it possible to have everything needed included in the standalone build including React-Autocomplete?

**Comment by JedWatson** [comment]
@evandegr did you close this because it's now working for you, or is it still an issue?

**Comment by evandegr** [comment]
@jedwatson got it working, I messed up including the react-autosize-input in my project at first.
