### ISSUE TITLE
Question: Is it possible to select multiple filter results?

### ISSUE THREAD

**Issue by greensheep** [JedWatson/react-select#831]
First of all, great library, works beautifully!

Not sure if this is the right place to ask(?) but is it possible to select multiple items from the search dropdown?

I have thousands of options I'm loading async from the server as the user types.  For the majority of queries, there are multiple results.  I'd like to be able to CMD/CTRL+click each option to quickly select them without closing the search dropdown.

Is this possible?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
