### ISSUE TITLE
Select-Value width for single-select too big

### ISSUE THREAD

**Issue by FranBran** [JedWatson/react-select#833]
The `Select-value`'s max-width for single-selects should be less than 100%. See 
![value-width](https://cloud.githubusercontent.com/assets/1215407/13747701/da886350-e9f9-11e5-990e-3b6766f90451.PNG)

For clearable single-selects there should be set `max-width: calc(100% - 42px)`, while for non-clearable single-selects there should be set `max-width: calc(100% - 17px)`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
