### ISSUE TITLE
UNMET PEER DEPENDENCY react@^0.14 || ^15.0.0-rc || ^15.0.0

### ISSUE THREAD

**Issue by ntucker** [JedWatson/react-select#837]
I just have version 0.14.7. You should allow minor versions

**Comment by ntucker** [comment]
Was in wrong directory *pieinface*

**Comment by JobLeonard** [comment]
Well, I keep getting this message for no apparent reason; could you expand a bit on "was in wrong directory" and how that fixed your issue?
