### ISSUE TITLE
Pressing tab when allowcreate, the value is cleared

### ISSUE THREAD

**Issue by Shnolik** [JedWatson/react-select#838]
When allowcreate is true, and the user is typing a value not in the list, and then click "Tab", the value is cleared. If "Enter" is clicked, then the value is created and added.
Pressing "Tab" and while having a matched item, then the value is selected.
I would like to keep the new value if the user click the "Tab", as in a regular "Tab" while editing an input.

Thanks...

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

Look for an updated RC with this functionality soon. 😎
