### ISSUE TITLE
Breaking error in IE 8

### ISSUE THREAD

**Issue by Dharmoslap** [JedWatson/react-select#841]
![virtualbox_ie8 - win7_18_03_2016_10_50_19](https://cloud.githubusercontent.com/assets/3543614/13875677/8e46df68-ecff-11e5-92f8-2d1b0e492a0a.png)

How to replicate this issue

1. run Windows 7 with IE 8 on VirtualBox [https://dev.windows.com/en-us/microsoft-edge/tools/vms/](https://dev.windows.com/en-us/microsoft-edge/tools/vms/)
2. clone this repo https://github.com/Dharmoslap/react-select
3. run "npm start" and open http://10.0.2.2 in IE 8
4. try to select different options and the error will appear

However it's not fancy at all, I still need to support IE 8 for a few more months.

Thanks

**Comment by Dharmoslap** [comment]
It seems to be React related issue, so I created the same one in React repository as well.
https://github.com/facebook/react/issues/6291
Do you know how to run unconcatenatded library inside your stack, to provide more information about the error?

**Comment by gaearon** [comment]
Please see https://github.com/facebook/react/issues/6291#issuecomment-199023995. It is not a React-related issue. IE8 doesn’t support `isEqualNode()` which is used in https://github.com/JedWatson/react-select/blob/18758f78655b4004a3a22fc049f5706cd25bffcd/src/Select.js#L313.
