### ISSUE TITLE
searchText prop not showing prop value when isloading=true

### ISSUE THREAD

**Issue by aqumus** [JedWatson/react-select#842]
Hello Team,

searchText prop value is not shown when  isloading=true , tested in 1.0.0-beta

I really liked the react-select component and appreciate what u guys did.I am using this component with no hassle and tweaking cause everything is already provided by this component.

**Comment by thejameskyle** [comment]
I assume you mean the `searchingText` property, and that doesn't seem to exist anymore in 1.0

**Comment by aqumus** [comment]
on viewing the code , it seems searchingText prop value is used only when Asyn functions are used (i.e only in Async.js) but not while explicitly using isLoading prop (i.e in Select.js file).

Thanks @thejameskyle for your response

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
