### ISSUE TITLE
Adding cascade support

### ISSUE THREAD

**Issue by hasanmumin** [JedWatson/react-select#844]
hi,
I think the adding of the cascade support will be very useful.
example of cascade support http://demos.telerik.com/kendo-ui/dropdownlist/cascadingdropdownlist
what do you think about it ?

**Comment by thejameskyle** [comment]
This seems like the sort of thing you'd be better off implementing on your own and not within react-select. I'd recommend trying that first

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
