### ISSUE TITLE
In IE11 the focus of the select field is lost when scrolling through the list of options

### ISSUE THREAD

**Issue by elijahmanor** [JedWatson/react-select#848]
A strange IE11 specific bug was found in the react-select component when trying to scroll through the filtered options. You don't technically have to scroll the list to see the behavior, you can just click the scrollbar as shown in the following animated gif. You'll notice the field is blurred, which causes the cursor to be lost and if you click the scrollbar again focus will be regained and you can see the cursor blinking again.

![ngbfguo4op](https://cloud.githubusercontent.com/assets/86454/13999626/31656854-f10b-11e5-8c7d-ba1330718d25.gif)

I have a code fix and tests to address the IE bug and plan to submit a Pull Request soon. I wanted to give a heads up about the issue before I submitted the PR. Thank you for your component and the time you have invested in this project.

**Comment by JedWatson** [comment]
Fixed by #849
