### ISSUE TITLE
autosize not working

### ISSUE THREAD

**Issue by dragonza** [JedWatson/react-select#860]
Hello,
I have updated react-select by using 'npm install' to the lastest but the autosize is not working. When I downloaded the repo and run npm install, it works. Does autosize work on npm?

**Comment by nvartolomei** [comment]
I second that. Didn't had time to create an issue.

**Comment by brettdewoody** [comment]
@dragonza Is the issue the input isn't resizing based on the content? Or that setting `autosize` to `false` isn't working?

**Comment by dragonza** [comment]
@brettdewoody I set autosize to false and it did not work.

**Comment by diabolicfutility** [comment]
autosize={false} does not work for me either.

**Comment by adamtay82** [comment]
And me neither - would love a workaround if there is one!

**Comment by jooj123** [comment]
This doesnt work for me either

**Comment by mohak1990** [comment]
Ellipses is expected

**Comment by vnallamhawk** [comment]
any update on this issue ?

**Comment by individual11** [comment]
any update on this? same issue, no matter what I do, the select's width increases as tags are aded.
