### ISSUE TITLE
No input value after select an async option after search

### ISSUE THREAD

**Issue by jbmeslin** [JedWatson/react-select#865]
When I select an option after change the inputValue, the selectValue function set the state of the inputValue to an empty string then the loadoptions function is called and my selected option is no more in the options list. so during the renderInput, the function getValueArray return nothing and the place holder is rendered.

Note: After having select one option the renderlabel is called every time on option hover

**Comment by amrut-bawane** [comment]
+1

**Comment by xiaolin** [comment]
+1

**Comment by cirsteve** [comment]
I just figured this out, in async mode with an onChange handler you need to set the value to be the full options object, i.e. {label: 'foo', value: 'bar'}, not just a string value

**Comment by jbmeslin** [comment]
I already do that but my value setted by props was the string value. it seems more logical to have options object in both side but i think we should not do this. I think the value should be only the value an not the options.

**Comment by steve-taylor** [comment]
Thanks @cirsteve. I had exactly the same problem and your solution worked for me.

**Comment by xiaolin** [comment]
I was using `multi=true` with `value` set by a prop, the prop was an object using `{label: `foo`, value: 'bar', ...}` and that did not work.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
