### ISSUE TITLE
Multiple hidden inputs are created with the same name (when multiple === true)

### ISSUE THREAD

**Issue by dmatteo** [JedWatson/react-select#868]
Version 1.0.0-beta12 introduced a new behaviour that seems buggy to me.

Instead of having multiple values concatenated in the values as before, it is now creating one hidden input for each value (see attached img)
![podio](https://cloud.githubusercontent.com/assets/4091059/14320295/d2a45d92-fc14-11e5-8188-8c01f8247dd9.png)

Previous behaviour would have been `<input name="fields[relationship]" value="58727,58726"`

This is breaking a normal HTML form, since only the last input is taken into consideration.

@JedWatson If confirmed as a bug, I might dive in and fix it myself.
Just wanted to hear your take on this.

Thanks

**Comment by JedWatson** [comment]
This is actually intended behaviour, see #790

There's a new `joinValues` prop that re-enables the old behaviour - sorry I missed that when I was writing up the changelog!

From my understanding, all the inputs should be submitted by the browser, and (most? some?) body parsers (I can confirm this works with `body-parser` for express) will then combine the field values into an array.

If you know something I don't and this is the wrong behaviour / doesn't actually work, please do let me know - would be great to get it right before 1.0 comes out of beta

**Comment by dmatteo** [comment]
I see, thanks.

I have to admit I'm puzzled, as I thought it wasn't valid HTML, but I'm finding conflicting information on the web. Maybe it's just rails that is fucking it up for me.

I will use `joinValues` for now, thanks a lot!

**Comment by JedWatson** [comment]
No worries! that's why I added the prop :)

**Comment by dmatteo** [comment]
Good call :smile:
