### ISSUE TITLE
LESS Name error : variable @select-menu-max-height is undefined

### ISSUE THREAD

**Issue by freder** [JedWatson/react-select#87]
hi,

I just uploaded a [`keystone`](http://keystonejs.com) project to the server, did `npm install` and then tried to access the admin part — but there's s.th. wrong:

```
GET /keystone/ 302 11.825 ms
GET /keystone/signin 200 164.730 ms
POST /keystone/signin 302 359.484 ms
GET /keystone/ 200 167.749 ms
  LESS Name error : variable @select-menu-max-height is undefined
  LESS File : /var/www/sites/keystone-project/node_modules/keystone/node_modules/react-select/less/select-menu.less 21:13
Name Error thrown for request: /keystone/styles/keystone.min.css
{ [Error: variable @select-menu-max-height is undefined]
  type: 'Name',
  filename: '/var/www/sites/keystone-project/node_modules/keystone/node_modules/react-select/less/select-menu.less',
  index: 732,
  line: 21,
  callLine: NaN,
  callExtract: undefined,
  column: 13,
  extract:
   [ '\tmargin-top: -1px;',
     '\tmax-height: @select-menu-max-height;',
     '\tposition: absolute;' ],
  message: 'variable @select-menu-max-height is undefined',
  stack: undefined }
```

it runs fine locally though.
`keystone 0.3.3`

**Comment by freder** [comment]
I just realized: it works locally, because it's `keystone 0.3.2` — so it must be  a `0.3.3` thing.

**Comment by esparragito** [comment]
I've had the same bug pop up. I've been having a poke around, but nothing concrete. I'm not quite sure why keystone is running the less compiling on these files anyway. There seems to be a gulp file that handles that upon install, and it seems like a bad practice to dig into a module to edit the less files. It's got me.

**Comment by esparragito** [comment]
Have found the root of the problem I think. The @select-menu-max-height which seems to be a new addition to react-select isn't defined in keystones public/styles/react/react/less file. Add it in there and everything should be grand.

The default.less file in the react-select module never gets loaded by keystone, so any variables in there never get seen.

I guess that makes it a keystone issue? I'll pop this over to the referenced keystone issue

**Comment by konieshadow** [comment]
Same problem on me, and fixed by follow @esparragito 's suggestion. I think these dependencies on keystone is not very well.

**Comment by JedWatson** [comment]
Thanks for the sleuthing guys - that property should have been configured in Keystone, I'll push another release over there to fix it.
