### ISSUE TITLE
(Feature) Scroll-to-top for menu items when opening dropdown

### ISSUE THREAD

**Issue by emmenko** [JedWatson/react-select#870]
I haven't found a good way to do it, and I haven't seen it as an available option to the dropdown. 
Would it be possible to have an option (e.g. `scrollToTopOnOpen`) that will scroll the menu list items to top whenever you open the dropdown. This effectively will always show the first item on top of the list.

If not, what would be a good way to workaround it / implement it?

Thanks

**Comment by ClemDelp** [comment]
For those who are still facing this problem the solution is to use [menuRender](https://github.com/JedWatson/react-select#efficiently-rendering-large-lists-with-windowing) and define by yourself the isFocused parameter.
On your options list you can for example add a parameter to the option you want to focus (the first one in your case @emmenko ):
```javascript
const topOption = {
  focus: true
  label: 'label',
  value: 'value'
}
```

Then you override the menuRender's isFocused variable like this:

```javascript
let isFocused = option.focus // instead let isFocused = option === focusedOption
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
