### ISSUE TITLE
How to get the value when Select is in a submited form

### ISSUE THREAD

**Issue by frodrigueza** [JedWatson/react-select#873]
*_Select name="mySelect" options={...} ... *_

I cant access to the value selected by event.target.elements.mySelect when the form is submitted. It throws undefined. Is it the right way to this?

Thanks

**Comment by lonelydatum** [comment]
logChange(val){
console.log(val)
}

render(){
<Select onChange={this.logChange.bind(this)}/>
}

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
