### ISSUE TITLE
React v15.0 support

### ISSUE THREAD

**Issue by johannesnagl** [JedWatson/react-select#875]
Hi guys,

when updating react to the [newly releases v15.0](https://facebook.github.io/react/blog/2016/04/07/react-v15.html) I'm getting this npm error:

```
npm ERR! peerinvalid Peer react-select@0.9.1 wants react@^0.14.1
```

Any chance you can bump the dependency to allow v15.0?

**Comment by StevenLangbroek** [comment]
[Already landed](https://github.com/JedWatson/react-select/blob/master/package.json#L28)

**Comment by johannesnagl** [comment]
cool, thanks!

**Comment by janraasch** [comment]
@StevenLangbroek could this be merged back to `v0.9.x` so we do not have to wait for the big `v1` release?

**Comment by StevenLangbroek** [comment]
I'm not a maintainer, but it's in v1.0.0-beta12. So `npm i -S react-select@1.0.0-beta12` should do the trick!

**Comment by StevenLangbroek** [comment]
Ping @JedWatson if you need it for `0.9.x` range.

**Comment by janraasch** [comment]
I would make a pr, but I do not see a `0.9.x` branch.

**Comment by tonybaroneee** [comment]
+1, I need this ported back to 0.9.x as well.

**Comment by tonybaroneee** [comment]
@janraasch We ended up just forking, re-pointing master to the `v0.9.1` tag, then committing the React 15 patch on top.

**Comment by janraasch** [comment]
@tonybaroneee sure that is a good idea and it works, but, if this is a common use case (I am pretty sure it is as people like to stay up-2-date with their dependencies), I would like to see this *officially* supported/released on npm.

@JedWatson, any plans to release a `0.9.x` sporting bumped `react` dependencies? Or are there any pending issues with using `react v15` and `v0.9.1` of this component? I am sure people would love to help fix them, if there are any.

**Comment by tonybaroneee** [comment]
@janraasch I totally hear you, I did it because we haven't heard from Jed in over a week and we had to move on. Just letting others know of the option.

**Comment by StevenLangbroek** [comment]
@tonybaroneee from what I understood on twitter @JedWatson just became a father, so I imagine he's busy with that 🎉

**Comment by tonybaroneee** [comment]
Oh wow, that explains that then! :smile:

**Comment by impleri** [comment]
I forked the repo, created a new 0.9.x branch, and updated package.json to allow react 15.x: https://github.com/impleri/react-select/tree/v0.9.x

**Comment by johannesnagl** [comment]
@impleri would you like to update your repo to allow react 15.2? npm is complaining about your fork wants `react@^0.14.1 || ^15.0`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
