### ISSUE TITLE
Controlled input

### ISSUE THREAD

**Issue by frodrigueza** [JedWatson/react-select#877]
The component behaves like react-controlled-input when an option is selected, but when the user is writing over it, the props given don't make any effect. Is there a way to control the non-selected case?

@JedWatson 
@tomascharad

**Comment by mahtikebab** [comment]
Facing the same issue. In react-select's componentWillReceiveProps there is no handler for the value prop change.

https://stackoverflow.com/questions/47260618/how-to-update-react-select-plus-value-via-parent-component

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
