### ISSUE TITLE
Is it possible to move the 'select-value-icon' to right of 'select-value-label' through options?

### ISSUE THREAD

**Issue by topgun743** [JedWatson/react-select#879]
I am having a mandatory requirement from my client, to have the **'select-value-icon'** to the right of **'select-value-label'** as shown in the attached pic.
I know I can do it via my page CSS but I am wondering if there is any way to do that via react-select's options. Is it possible? 

If not currently, would be of great help if the great dev can add this feature to code.

Thanks in advance.
![react-select-custom](https://cloud.githubusercontent.com/assets/4273108/14405716/00c522c4-feae-11e5-962c-db28aaed342c.png)

**Comment by juanpasolano** [comment]
+1 
It would be nice if just like valueRenderer we could customise the whole `.Select-value` render
Awesome component, thanks

**Comment by GCinellu** [comment]
+1

**Comment by rimonn** [comment]
+1

**Comment by long-lienteam** [comment]
+1

**Comment by long-lienteam** [comment]
A workaround could be to use `direction: rtl`.
```
.Select-multi .Select-value {
  direction: rtl;
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
