### ISSUE TITLE
[1.0.0-beta11] Do not show dropdown if only one option is available

### ISSUE THREAD

**Issue by ConAntonakos** [JedWatson/react-select#884]
If this is not currently part of the component, what do you think? Is this something that the component should do?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
