### ISSUE TITLE
Handle `options` update when new props are received

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#885]
Currently the only way to update `options` is by specifying the `loadOptions` prop with a callback or Promise. I expect that when a new `options` prop is passed, it should also update.

This can be done using the `componentWillReceiveProps` lifecycle hook.

**Comment by TheXardas** [comment]
Same problem here

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
