### ISSUE TITLE
Error: variable @select-menu-max-height is undefined

### ISSUE THREAD

**Issue by liamwooding** [JedWatson/react-select#89]
Just did a fresh npm install of KeystoneJS, and the less compiler threw the following error on startup:

`{ [Error: variable @select-menu-max-height is undefined]
  type: 'Name',
  filename: '/Users/liam/code/project/node_modules/keystone/node_modules/react-select/less/select-menu.less',
  index: 732,
  line: 21,
  callLine: NaN,
  callExtract: undefined,
  column: 13,
  extract: 
   [ '\tmargin-top: -1px;',
     '\tmax-height: @select-menu-max-height;',
     '\tposition: absolute;' ],
  message: 'variable @select-menu-max-height is undefined',
  stack: undefined }`

**Comment by JedWatson** [comment]
Thanks for the report @liamwooding, was an issue with Keystone that's been resolved.
