### ISSUE TITLE
Boolean Operations?

### ISSUE THREAD

**Issue by vgoklani** [JedWatson/react-select#890]
Hey - we use react-select in production, and are quite happy with it. Some of our users recently started asking us about boolean queries, i.e. AND / OR operators. We ended up using two react-select boxes (side by side - yes,it's a hack job) and allowed one box to facilitate AND operations, while the other box could be used for OR operations. I'm just curious if anyone has found a better solution. Thanks!

**Comment by dherran** [comment]
Can you explain in more detail what the operations are for? Do you mean AND/OR operations within the search input, or operations that are out of the scope of the select box?

**Comment by vgoklani** [comment]
Sure - let's assume that the select box allows you to choose stock tickers, and if a stock ticker is chosen, then any headlines that mention that ticker are displayed. If the user chooses IBM, then all headlines that mention IBM are displayed. If the user chooses both IBM and GOOG, then all headlines that contain either IBM or GOOG are displayed. However, the user may instead request that they want all headlines that contain both IBM and GOOG, which I handle through a checkbox. But there are certain instances where a user says they want all instances of (say) (IBM AND GOOG) or (AAPL). 

obviously this is beyond the scope of react-select, but I'm unsure of where else to ask this question, and hoping someone has a good suggestion. Thanks!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
