### ISSUE TITLE
Feature request: make it possible to change the current search text through props.

### ISSUE THREAD

**Issue by gsanta** [JedWatson/react-select#893]
Right now the only way to change the text inside the search input, is to set the `value` property. But the `value` property creates some placeholder text not a 'real' text.

I came across this problem, when I created a validation outside react-select that prevents the user from typing specific characters. To achieve this I want to take control of the text inside of react-select search input. Currently there is no way for doing this, the only prop that 'resembles' this is the `value`, but if you change the value of the `value` property it will become some placeholder text not a real one. -> the result is that the user can not continuously type in the search field.

**Comment by hannupekka** [comment]
I'd need this kind of functionality too.

**Comment by gsanta** [comment]
I also find this whole placeholder behavior a little weird (when you click in the first time or after a selection). It is totally inconsistent with the browser default behavior. 

So for example I have a form where I use a simple bootstrap input field beside react-select, and they are just not working consistently with each other.

**Comment by olivergeorge** [comment]
The onInputChange feature doesn't cover my use case: setting without user input.

My workaround for this is to use the refs to set the state, something like:

```
this.refs.picker.refs.select.setState({:inputValue "some value"})
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
