### ISSUE TITLE
Compatibility with react-bootstrap

### ISSUE THREAD

**Issue by dmk23** [JedWatson/react-select#894]
We have a project that uses `react-bootstrap` for all forms. They are all composed out of `<Input/>` elements within a `<ModalDialog/>` and I want to replace some with async dynamic inputs.

When I replaced some of these `<Input/>` elements with standard examples for `react-select` (starting with static data) I found the component not rendering / responding correctly. Not only it does not resize (per screenshot) nor am I able to select an option by using mouse dropdown - unless I'm using a weird action sequence (mousedown on input, then drag to the option, the mouseup, then click the option).
![image](https://cloud.githubusercontent.com/assets/1828444/14528163/0fd652e4-0203-11e6-93e4-ca43e75146f7.png)

Is this project intended to be compatible with `react-bootstrap`? Could you provide any help / direction for resolving the issues discovered? We tried both latest beta and `0.9.1` releases to same effect...

**Comment by MarkLeMerise** [comment]
While `react-select` does not explicitly claim compatibility with `react-bootstrap`, my project is currently using `react-select@1.0.0-beta12` in concert with `react-bootstrap@0.28.2` (inside a `<ModalDialog>` as well) and have not experienced any styling or functionality issues. As far as I've seen, the `react-select` styles have been qualified enough to never be overridden by Bootstrap styles. If there are no explicit console errors, I would ensure that the styles of `react-bootstrap`, `react-select`, and your app aren't clashing somehow.

**Comment by dmk23** [comment]
@MarkLeMerise Thanks for the info. We are using the same major version of `react-bootstrap` through this project: https://github.com/scottwoodall/django-react-template/tree/master/frontend

I'm not seeing any console errors, but seems like some behaviors are broken as the input does not resize properly based on the initially supplied value... I tried looking into the CSS/JS in the browser, but because of webpack renaming things it is really hard to figure out what may be overriding what...

Any thoughts / suggestions on the best way to track down the problem? Could you by any chance share any code examples of your `react-select` setup?

**Comment by DonHansDampf** [comment]
I just loaded the component in a fresh boilerplate WITHOUT bootstrap and got the same output. Seems like something went wrong? Also no errors in console.

**Comment by DonHansDampf** [comment]
Seems like it doesnt load the scss or less files if you install just the package via `npm i --save react-select`.

You have to import the `default.scss` or `default.less` file manually. In my case i simply copied the scss folder from the npm_modules folder into my source folder and included the `default.scss` via `@import './select/default.scss'`.

**Comment by dmk23** [comment]
What may be the best way to integrate these files into Babel/Webpack build?

**Comment by DonHansDampf** [comment]
I have them in my webpack/babel-build in the folder: `src/styles/select/`. I import the files via `@import './select/default.scss' `in a file called `core.scss` in `src/styles/`. Nothing special. Of course you need a less or scss compiler configured in your webpack config.

**Comment by dmk23** [comment]
Hmmm I just looked at my `node_modules/react-select/{less|scss}` dirs and all the files are there

My webpack configs seem to already have entires for handing `less', as you can see here: https://github.com/scottwoodall/django-react-template/tree/master/frontend

What do you think might be missing?

**Comment by DonHansDampf** [comment]
The proplem is, your webpack doesnt load the less files in the node_modules folder. I am not sure why and if this is a bug. But if you want to get it work now:

Copy the files inside the less folder to `src/app/stylesheets/react-style/` (ofc you have to create the react-style folder first). After that add to your `index.less` file (in `src/app/stylesheets/`) the following line: `@import './react-select/default.less'`.

**Comment by dmk23** [comment]
This solved it, many thanks!

I had to go back to `0.9.1` though as `1.0.0-beta12` did not let me change default option selections. In any case seems like all the docs cover the older version anyways?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
