### ISSUE TITLE
Chrome rendering issue

### ISSUE THREAD

**Issue by AlexKovalevych** [JedWatson/react-select#896]
https://www.dropbox.com/s/23cnl4nu3338tow/Screenshot%202016-04-15%2017.38.01.png?dl=0

Steps to reproduce:
1. Go to http://jedwatson.github.io/react-select/, scroll down to multiselect.
2. Select all options, except chocolate. Then select chocolate.
3. Click on "I don't like Chocolate (disabled the option)" checkbox.

Environment: Chrome 49.0.2623.112 (64-bit), OSX.

**Comment by AlexKovalevych** [comment]
Similar thing happens when you uncheck the checkbox - it leaves empty space after the select.

**Comment by AlexKovalevych** [comment]
Update: chrome renders select correctly if i do mouse over after clicking the checkbox.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
