### ISSUE TITLE
newOptionCreator

### ISSUE THREAD

**Issue by f2net** [JedWatson/react-select#897]
I cannot make the "allowCreate" option to work.
Is there a working example of this? I cannot find it in the documentation.

I tried supplying a newOptionCreator, but it isn't called.

Thank you,
Matteo

**Comment by hsrobflavorus** [comment]
It's a known issue, see this thread for info/workarounds: https://github.com/JedWatson/react-select/issues/658

**Comment by rubencodes** [comment]
I'd like to add here that it would be nice to have *any* sort of documentation for what the `newOptionCreator` function should look like (e.g. input/output).

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

Look for an updated RC with this functionality soon. 😎
