### ISSUE TITLE
Multi Select not staying open on first select

### ISSUE THREAD

**Issue by ozoesono** [JedWatson/react-select#898]
I am using the multi option, but when I select the first item the dropdown closes. I have to click it again to select the next item. Is there a setting for this, as I can't see it in the docs, and checked the Issues raised and can't see this.

**Comment by rajeshps** [comment]
Hi @ozoesono 

Coiuld you provide more information and code snippet if still problem persist?
How are you using multi option?
It works as expected when multi option is passed to the props like
`<Select multi ....`
or
`<Select multi={true} ....`

Also, try to update to latest and check, hopefully that should help.

Thanks,
Rajesh

**Comment by Vadorequest** [comment]
I experience the same issue. Using 0.9.1 as in the demo: https://jedwatson.github.io/react-select/

In the demo it works fine, but in my code it doesn't. Each time I select an option it closes the select list.

```js
<Select
        name="actions"
        options={[
          {
            value: 'test',
            label: 'test',
          },
          {
            value: 'test1',
            label: 'test1',
          },
          {
            value: 'test2',
            label: 'test2',
          },
          {
            value: 'test3',
            label: 'test3',
          },
          {
            value: 'test4',
            label: 'test4',
          },
        ]}
        multi
        simpleValue
      />
```

**Comment by wijnbladh** [comment]
Was about to report that this still happens, but then came across this prop

`closeMenuOnSelect={false}`

And everything works nicely. Thanks for this.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
