### ISSUE TITLE
React 15.0.1 Support similar to https://github.com/JedWatson/react-select/issues/875

### ISSUE THREAD

**Issue by hegdeashwin** [JedWatson/react-select#900]
This is similar issue about the support for latest react version specified in https://github.com/JedWatson/react-select/issues/875

I have installed below sets of npm:
React : 15.0.1
React-Dom : 15.0.1
Twitter Bootstrap (Its not React-Boostrap)
React-Select : 1.0.0-beta12
Babel for ES6 syntax
Using Weback for bundle

The "react-select" is getting displayed with below issues:
1. Only last option is getting visible in the react-select dropdown list.
2. Selecting this last options is not working; I mean nothing happens the selected item does not get displayed in the value on react-select.

Below is my code snippet:

```
import Select from 'react-select';
require('../../../node_modules/react-select/dist/react-select.min.css');

let options = [{
      value: 'option1', label: 'Option 1',
      value: 'option2', label: 'Option 2',
      value: 'option3', label: 'Option 3'
}];

<Select name="filter" options={options} />
```

**Comment by n0m4dz** [comment]
```
let options = [
     { value: 'option1', label: 'Option 1'},
{      value: 'option2', label: 'Option 2',
      value: 'option3', label: 'Option 3'
}];
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
