### ISSUE TITLE
 React.__spread

### ISSUE THREAD

**Issue by binjospookie** [JedWatson/react-select#903]
> Warning: React.__spread is deprecated and should not be used. Use Object.assign directly or another helper function with similar semantics. You may be seeing this warning due to your compiler. See https://fb.me/react-spread-deprecation for more details.

[react-select/examples/dist/](https://github.com/JedWatson/react-select/tree/master/examples/dist)

«app.js» at least :)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
