### ISSUE TITLE
Retaining the searched list in the dropdown

### ISSUE THREAD

**Issue by bikash1605** [JedWatson/react-select#905]
Hi..
I want to retain the list corresponding to a search keyword in the dropdown. After I select an item in the serached list, the list disappears and the complete list is shown(in case of multi select).
How can i solve this ?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
