### ISSUE TITLE
Drag to reorder

### ISSUE THREAD

**Issue by wmertens** [JedWatson/react-select#91]
Would be very nice to have. The Angular UI-Select has it :grin: https://github.com/angular-ui/ui-select/blob/6e81746d31cb8e5fda8f6b9eed066d9a2e6ba4c1/src/uiSelectSortDirective.js

**Comment by atran** [comment]
+1

**Comment by JedWatson** [comment]
Keen. Will need some time to get around to adding it, PRs welcome.

**Comment by bkniffler** [comment]
+1

**Comment by sriprabha** [comment]
+1

**Comment by solognt** [comment]
+1

**Comment by solognt** [comment]
I created a little fiddle based on the react-select html and the html5 sortable by RubaXa (https://github.com/RubaXa/Sortable).

https://jsfiddle.net/oqjqgbpb/6/

On sort end it gives me the old and new index of the element so I can update the collection and re-render the selector.

This seems to work fine on the html alone but when I use it directly on the react-select element drag/drop does not work any-more. I seems the selector blocks the necessary events somewhere.

Any pointers would be welcome..

**Comment by dcworldwide** [comment]
Hi @solognt, i'm looking to solve this problem as well. Any progress? Happy to review your work / collaborate.

**Comment by davidworkman9** [comment]
+1

**Comment by sumitk** [comment]
+1any more updates?

**Comment by rich-b** [comment]
i've been thinking about implementing this using react-dnd.  Sound good?

**Comment by bkniffler** [comment]
Introducing a dependency for such a small feature seems overkill, especially since native html5 dnd isn't hard to implement, and might even be easier in this specific case.

**Comment by turnerniles** [comment]
+1

**Comment by bvaughn** [comment]
> @rich-b: i've been thinking about implementing this using react-dnd. Sound good?

I'd also suggest checking out [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc). It's really slick.

IMO this functionality (drag-and-drop re-ordering) is a bit more complicate than belongs in the base react-select library. (This library is primarily owned and maintained by Jed- an individual. It doesn't have a full team behind it like angular-ui. So limiting the scope and ambition of this project will help keep it easier for him to maintain.)

I believe this functionality should already be possible by supplying a custom `menuRenderer` and using react-sortable-hoc inside of it.

**Comment by krzysu** [comment]
I managed to integrate [react-dnd](http://gaearon.github.io/react-dnd/examples-sortable-simple.html) with react-select without any changes to latter one. gist [here](https://gist.github.com/krzysu/1b391ae0e3c87d0c654cdf6d5a409632). Let me know what do you think!

**Comment by davidworkman9** [comment]
@krzysu Did you try that on the 1.0 branch? It doesn't seem to work for me.

**Comment by krzysu** [comment]
@davidworkman9 no, I didn't, I haven't touched it since my last post. I have no idea about changes in 1.0 branch, you need to figure it out by yourself, sorry :)

**Comment by davidworkman9** [comment]
Thanks, just checking as the 1.0 branch was out in October. I was able to get it to work by adding ```onValueClick={() => {}}``` to the props to ```react-select```.

**Comment by songyanho** [comment]
#1720

**Comment by aschmoe** [comment]
@bvaughn I had the same thought re: [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc), here's a [gist](https://gist.github.com/aschmoe/5cf05ebec29d140f9bf0ad2c31d6a3cb).  I pulled out mobx code, so possible it doesn't work out of the box.

The only real hacky bit was extracting the index in `valueComponent`, so if that prop was to come through to the supplied component,  vanilla react-sortable-hoc components would be a go.

**Comment by bvaughn** [comment]
Adding a new prop, `index`, to `valueComponent` seems reasonable to me. Put together a PR?

**Comment by pwhipp** [comment]
I added the index property and also added an example with the sortable-hoc included in [this fork](https://github.com/pwhipp/react-select). Happy to create a PR if it is wanted.

However, adding the index property is a somewhat arbitrary thing from the perspective of react-select and the working example has some issues such as when the ordering extends over multiple lines or with the styling of the element being dragged.

**Comment by byc1990** [comment]
+1

**Comment by Ymx1ZQ** [comment]
+1

**Comment by tadaskay** [comment]
Perhaps this could be a good candidate for v2?

**Comment by poulet42** [comment]
@tadaskay It's still possible to implement sortable values in v2 (even without valueRenderer and exposed index) without making a change to react-select.

**Comment by tadaskay** [comment]
@poulet42 Could you elaborate? Do you mean by integrating with `react-dnd`?

**Comment by rlech** [comment]
would be awesome to see dnd working with multiselect

**Comment by Fahdshehzad** [comment]
+1

**Comment by Fahdshehzad** [comment]
+1

**Comment by wmertens** [comment]
People leaving +1: you're not helping. Use the emojis for the issue text, or create a pr. Never leave +1 anywhere on github, that's so 2012.

**Comment by jossmac** [comment]
This should now be achievable using the [components API](http://react-select.netlify.com/components) in v2.

Would love to see some links to working examples here if anyone builds it 🙂

**Comment by nickstrak** [comment]
Anyone with a working example using components API in v2 as @jossmac suggested? 🙂

**Comment by mbonaci** [comment]
Versions below `3.0.8` have [problems with hiding](https://github.com/clauderic/react-sortable-hoc/issues/220) `MultiValueItem`s after dragging, because the `index` prop (which is [mandatory](https://github.com/clauderic/react-sortable-hoc#sortableelement-hoc) for `react-sortable-hoc`'s `SortableElement`) was added to `MultiValueItem` in that [version](https://github.com/JedWatson/react-select/blob/master/packages/react-select/CHANGELOG.md#308).
