### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by codTango** [JedWatson/react-select#910]
Just cloned the repo and gave it a try, but I got this error:"npm ERR! cb() never called!" when run npm install. No idea what's going on? `node -v
v5.9.1`  `npm -v
3.7.3
`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
