### ISSUE TITLE
Prerelease Tags Being Used Incorrectly

### ISSUE THREAD

**Issue by JKillian** [JedWatson/react-select#911]
The tags should be `1.0.0-beta.12` instead of `1.0.0-beta12`. Without the dot, NPM seems to sort the last token alphabetically, which isn't desired:

![image](https://cloud.githubusercontent.com/assets/1400151/14799733/24090772-0b0c-11e6-8c98-d376e71d6012.png)

With the `.` in the version, NPM will handle things correctly and it will be treated numerically.

**Comment by JedWatson** [comment]
Eek, thanks for pointing that out @JKillian. I'm not sure that rewriting history at this point would be a good idea, so maybe keep up to date specifically with each beta release?

I'll be moving the new version out of beta shortly anyway, I shouldn't have kept it there so long but wanted to fix the fact that "tags" mode had been removed in the rewrite. Expect a proper release in the next few days :)

**Comment by JKillian** [comment]
Agreed that it's not worth changing for the 1.0.0-beta line of releases. Just worth changing in the future if there is a different line of betas someday 😃
