### ISSUE TITLE
How to clear selected value and all text when click reset value button?

### ISSUE THREAD

**Issue by 9tor** [JedWatson/react-select#912]
How to clear selected value and all text when click reset value button?

**Comment by aqumus** [comment]
Reset value button u mean clicking on cross button?
 Clicking on reset , this.props.onChange function is called with value passed as null , just handle the parent onChange callback with value=null and set the value of the Select component as empty string ("").

**Comment by 9tor** [comment]
I mean button reset on form.I have 2 button "save" and "reset" when I'm click reset I want to reset all data to default value.

**Comment by aqumus** [comment]
just set the prop value passed to the Select component as a empty string when clicked on Reset Button.

**Comment by bvaughn** [comment]
Closing this issue as it seems to have been sufficiently answered.

**Comment by maxfarseer** [comment]
@bvaughn , @aqumus 

> u mean clicking on cross button?
Do you have callback in options for this?

**Comment by aqumus** [comment]
Yes we do have,  you can pass your own template and callback options for multiselect, refer props and example for multiselect

**Comment by maxfarseer** [comment]
@aqumus  thank you, but can you attach little example?

**Comment by phocks** [comment]
> Reset value button u mean clicking on cross button?
> Clicking on reset , this.props.onChange function is called with value passed as null , just handle the parent onChange callback with value=null and set the value of the Select component as empty string ("").

When isSearchable={false} the expected behaviour would be for it to go back to the placeholder= text? This seems to just completely clears the box.

To have the placeholder text appear you need to assign the value prop to null

value={null}
