### ISSUE TITLE
Keyword / Tags / Chips feature proposal

### ISSUE THREAD

**Issue by goopscoop** [JedWatson/react-select#915]
Hi, I created a feature that builds on React Select designed for tags/chips or whatever you want to call this. Basically Select without the drop down. Would you be interested in incorporating this feature into the React Select library?

Demo (sorry about the scew):
![out](https://cloud.githubusercontent.com/assets/11171347/14832041/0fba9e56-0bad-11e6-932b-601b65232e4b.gif)

Usage:

```
<SelectList
  list={this.props.keywords}
  disabled={this.props.areFieldsDisabled}
  popListItem={this.props.popKeyword}
  pushListItem={this.props.pushKeyword}
  removeListItem={this.props.removeKeyword}
/>
```

Features:
- adds keyword on tab, enter, camma and semicolin
- removes last keyword on backspace (if no text is provided)
- can remove keyword by clicking 'x'

**Comment by felipesousa** [comment]
hi @goopscoop, can you show the example code more detailed? thanks a lot!

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
