### ISSUE TITLE
On hover?

### ISSUE THREAD

**Issue by Mauro74** [JedWatson/react-select#917]
Is there a way to trigger the drop down on hover rather than click?

Thanks

**Comment by gojohnnygo** [comment]
There's not a way out of the box. 

Though, it seems like you can and by adding an event listener [here](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L883-L887).

Something like `onMouseOver={this.handleMouseDown}` should do the trick bc you're trying to replicate the same functionality as `onMouseDown`. Note, I have not tested this myself.

**Comment by cbrwizard** [comment]
Hey @gojohnnygo could you please provide an example?
Rendering it with
```
        onMouseOver={() => {
          console.debug('mouse over')
        }}
```
prop doesn't call console on mouse over

**Comment by gojohnnygo** [comment]
@cbrwizard maybe try the following...

1. Set the `openOnFocus` prop to `true`.
1. Wrap `react-select` a div that has an `onMouseOver` handler
1. In the handler, call [`focus()`](https://github.com/JedWatson/react-select#methods) on the `react-select` instance

**Comment by Benornm** [comment]
What about close the dropdown on blur ???

**Comment by k8martian** [comment]
I need on hover specific option and trigger an event like populate some form fields before select the option. I tried the other way round, select and populate, the selected value disappear. Any suggestion?

**Comment by k8martian** [comment]
I found [this](https://github.com/JedWatson/react-select/issues/745#issuecomment-425402741) and might be helpful to someone.

**Comment by dalba1992** [comment]
add this
'&:hover':{
   backgroundColor:'#000'
}

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
