### ISSUE TITLE
Feature Request: Allow unexpected inputs for non multi selects

### ISSUE THREAD

**Issue by cleathers** [JedWatson/react-select#919]
I'd first like to say that this library is totally awesome. It was almost exactly what I was looking for but unfortunately I was unable to allow custom inputs for the single select case. We have an incomplete list of Provinces/States for certain Countries, so we were hoping that we'd be able to allow users to input whatever value they want, but have the typeahead as a convenience.

But yeah, custom inputs would be a great addition to the library. Keep up the good work @JedWatson!

**Comment by camsjams** [comment]
👍  +1

**Comment by scags9876** [comment]
+1  I've got a very similar situation.  I have a filter that loads distinct values asynchronously from a server.  Instead of forcing them to filter to a single distinct value, we want them to be able to search by a partial string as well.

I *think* what we want is the allowCreate property, but it is currently not functioning correctly

**Comment by scags9876** [comment]
actually, just updated to version 1.0.0-beta12 and allowCreate is working as expected.  Try it out @cleathers !

**Comment by scags9876** [comment]
No, my mistake, not working as expected.   At least with async select, allowCreate is not working as expected 😿

**Comment by cleathers** [comment]
Yeah I was hoping `allowCreate` would work for the non `multi={true}` but unfortunately it doesn't seem to.

**Comment by Data-Meister** [comment]
I agree this would be a fantastic feature

**Comment by danawoodman** [comment]
This seems like a major lack with this extension. What is the workaround?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
