### ISSUE TITLE
Selecting an option sometimes selects mutiple options in IE

### ISSUE THREAD

**Issue by jwarning** [JedWatson/react-select#92]
When using react-select on IE, I've noticed an issue where sometimes clicking the first option in the dropdown will select both that and the next option simultaneously. As far as I can tell this only happens in IE (version 11 is what I've tested it on). The first example on the demo page seems to have this issue.

**Comment by dcousens** [comment]
Still the case?

**Comment by jwarning** [comment]
Yeah, it still happens. The issue seems to be due to line 25 in Option.js: ` onClick={this.props.mouseDown}`. If you take this out it seems to be alright as the mouseDown handler only fires once from `onMouseDown={this.props.mouseDown}`. If you have both then IE seems to run the handler for each of the events. Not entirely sure why this issue only seems to affect IE though.

**Comment by bruderstein** [comment]
@dcousens, I think it's better if we don't assign people directly, especially to issues that are not specifically about code they've written. It makes it look like someone is working on it, which may not be true. Thanks!

**Comment by dcousens** [comment]
@bruderstein I was just hoping to tag you in to see if this was an easy fix.  No worries,  unassigned.

**Comment by jwarning** [comment]
Simply removing the onClick mapping does seem to do the trick. I have been using it in a project for a while like that and I haven't directly found any issues. I can PR that in if you'd like?

**Comment by bruderstein** [comment]
Yes please!

**Comment by jwarning** [comment]
I'm having an issue with a couple of the tests after the change:

'Select with allowCreate=true fires an onChange with the new value when selecting the Add option'
and 'Select with allowCreate=true allows updating the options with a new label, following the onChange' both supposedly fail to receive the newly created option, however in a browser this feature looks like it still works as expected.

It seems to be due to using the `TestUtils.Simulate.click` method, as switching to use `TestUtils.Simulate.mouseDown` fixes the tests. Would that be an ok change to make?

**Comment by jwarning** [comment]
I've PR'ed that here: https://github.com/JedWatson/react-select/pull/390
