### ISSUE TITLE
Value change causes asyncOptions to be called with it

### ISSUE THREAD

**Issue by RedRoserade** [JedWatson/react-select#920]
I'm using version 0.9.1.

When the user selects a new value from the list, the `asyncOptions` function is called, with its query as the value that was selected.

After poking a bit in the codebase, I suspect the issue is because `this.fireChangeEvent` is called before calling `setState`, and when `componentWillReceiveProps` is called, `this.state.value` is different from `nextProps.value`, causing `asyncOptions` to be called, i.e., the two weren't synchronized.

if, on `setValue`, I instead do:

``` javascript
this.setState(newState, () => this.fireChangeEvent(newState));
```

And comment the condition on `fireChangeEvent`, `asyncOptions` no longer gets called, but this causes `fireChangeEvent` to be called when the component mounts.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
