### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by ImranAhmed** [JedWatson/react-select#921]
Just took this from npm and the package.json contains:

```
  "peerDependencies": {
    "react": "^0.14.1",
    "react-dom": "^0.14.1"
  },

```

The package.json in git repo contains:

```
  "peerDependencies": {
    "react": "^0.14 || ^15.0.0-rc || ^15.0",
    "react-dom": "^0.14 || ^15.0.0-rc || ^15.0"
  },
```

Please could you update in npm, thanks.

**Comment by JuanCrg90** [comment]
+1

**Comment by JuanCrg90** [comment]
the package is nos updated in the npm 

https://www.npmjs.com/package/react-select

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
