### ISSUE TITLE
Can I create custom templates? And extend Select class?

### ISSUE THREAD

**Issue by yieldinov** [JedWatson/react-select#923]
Hi! Is there any way to extend original Select and modify some methods? For example I need custom arrow tempate (have an SVG that need to be styled)

``` js
class SelectPlus extends Select {
  renderArrow() {
    return (<span>arrow</span>);
  }
}
```

Above code hadn't worked for me :(

**Comment by iyel** [comment]
After investigation I've found way to achieve extension (polymorphism).

```js
class SelectPlus extends Select {
	constructor(props) {
		super(props);
		this.renderArrow =  function () {
			return (<div>Arrow</div>);
		}
	}
}
```

The presumed reason why the code in my first comment doesn't work is because source Select class created via ```React.createClass``` 
```js
// now
const Select = React.createClass({
    // CODE...
});

// should be
class SelectPlus extends React.Component {
    // CODE...
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
