### ISSUE TITLE
Dev mode react-select

### ISSUE THREAD

**Issue by khankuan** [JedWatson/react-select#927]
Hi, I noticed a little bit of annoyance when the menu keeps closing after losing focus. Wonder if there is already a way to overcome that while developing. Otherwise, will be `alwaysOpen` option be desirable?

Cheers!

**Comment by JedWatson** [comment]
Thanks for the PR! Could you explain a little more background on what the motivation is for this?

**Comment by khankuan** [comment]
There are times where i needed to debug the library, or to look at the menu elements in the inspector to figure out the css structure. The menu closes as soon as it loses focus and i can't really continue to debug. This option allow us to directly fix the `isOpen` state to true in such cases. And of course, who knows someone might design an interface that wants to keep the menu always open :P

**Comment by drobannx** [comment]
To add to this, I am using this in a project now and we have a use case where we do not want the menu to close when selecting an option in the menu. We still want it to close when clicking outside the component. Potentially we could utilize another hook to programmatically close the menu.

**Comment by ccslakey** [comment]
This would also be extremely useful for modifying the inner menu's CSS in development

**Comment by benjamindulau** [comment]
No need for a dev option for this. By using the Chrome React extension, you can simply force the "isOpen" state value to true on the Select component (note: there is an input at the bottom for searching components). Then you can freely inspect the select options :)

**Comment by mystrdat** [comment]
I am appaled that this option is missing, not just for testing purposes. Having fine grained control over how exactly the menu closes seems like an obvious addition.

**Comment by oldmill1** [comment]
+1

**Comment by pzrq** [comment]
Agree with @benjamindulau that no dev option is needed. 

However it would be a much more pleasant developer experience if it were documented somewhere how to do this:

<img width="501" alt="force isopen state" src="https://user-images.githubusercontent.com/1217010/27853434-f38e559c-61a5-11e7-8b83-273b9b546528.png">

**Comment by JedWatson** [comment]
I'm going to close this because the dev workflow has been clearly explained with react devtools, and there are other issues / PRs discussing this feature for other use cases

**Comment by Slapbox** [comment]
This method does not work in the React Devtools I have available in Electron. An option to keep the menu open built into the package would be extremely appreciated.

There are no checkboxes and modifying the state from false to true is not applied or saved.

![image](https://user-images.githubusercontent.com/6835891/32409340-2e7d29be-c180-11e7-8aa2-30722998806f.png)

**Comment by AMongeEntytle** [comment]
This does not work for working on ie 11

**Comment by wildeyes** [comment]
Not really a comfortable way to develop a select when using hot reload (as it resets state).

**Comment by AlahmadiQ8** [comment]
Hope this helps, I ran into this issue while trying to style the dropdown menu. I found that the easiest way is to remove the `blur` event listener from the input element using chrome devtools. This way the dropdown is not collapsed when you inspect it. 

Checkout my answer for more details: https://stackoverflow.com/a/49904173/5431968

**Comment by nosir** [comment]
+1 for @AlahmadiQ8 's solution also +1 for `alwaysOpen` option

**Comment by nickav** [comment]
here is a new prop now: `menuIsOpen` (https://react-select.com/props)

**Comment by iamdanthedev** [comment]
you can use "break on subtree modifications" feature on element inspector (right click on the parent node which the dropdown gets attached to)

but it doesn't always help as sometime is messes up the styles somehow

**Comment by loustak** [comment]
Another solution is to change the value of the `menuIsOpen` props by some text such as `hello`, very hacky 😃

**Comment by MatthieuJnon** [comment]
On chrome dev tools, if you go in the rendering tab, you can enable "Emulate a focused page", this will keep the page focused at all time.
