### ISSUE TITLE
react-native ?

### ISSUE THREAD

**Issue by vgoklani** [JedWatson/react-select#928]
Has anyone tried this component on react-native? any feedbacks, pros/cons?

**Comment by YoucefMami** [comment]
+1

**Comment by roysG** [comment]
+1

**Comment by daxreyes** [comment]
Just recently tried this with react native. Unfortunately, this package does not work since it requires react-dom package.

**Comment by amanthegreatone** [comment]
would be awesome if we can get this on react-native also! haven't found any package that comes close to this one for react-native. if anyone knows please share

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
