### ISSUE TITLE
Clearing select no longer renders hidden input field

### ISSUE THREAD

**Issue by jessehon** [JedWatson/react-select#934]
Since v1.0.0-beta12, the entire hidden `<input />` field no longer renders when `value=null`, which means the form can't pick up this field and null value.
It seems like it was still working in v1.0.0-beta11 though.

**Comment by dave-clover** [comment]
I'd like to bump this issue.  We tried to upgrade from beta11 to rc1 and are blocked right now.

As @jessehon said, the hidden input isn't rendered when no value is selected.  This is breaking our integration tests that look for the element on the page.  It would be really nice if an input was rendered with a blank value.  It would be a simple PR, and I am happy to do it.

Basically it requires adding an if statement around this return statement: https://github.com/JedWatson/react-select/blob/master/src/Select.js#L960

All it would do is check the length of valueArray, and if it is 0, render a blank hidden field.

@JedWatson what do you think?

**Comment by dave-clover** [comment]
Setting joinValues to true seems to fix the issue.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
