### ISSUE TITLE
inputChange method to call backend

### ISSUE THREAD

**Issue by Sandip-pal** [JedWatson/react-select#937]
I have a select field and i want the below functionality.

I will type keywords in my input field and it will call backend to get the auto suggested keywords matching my typing keys. I am writing **onInputChange**  method as below:
onInputChange={this.inputChange.bind(this)} and my inputChange is:
inputChange(input) {
    console.log(input);
/_code goes here after ajax call with the input_/
  }

My Select field is:
<Select allowCreate multi simpleValue value={this.state.value} options={this.state.options} onChange={this.handleSelectChange.bind(this)} onInputChange={this.inputChange.bind(this)}/>

I am not able to figure it out how i will write the ajax call success method. How can I populate the option 
that i will be getting from backend ajax call.
on every key press i will call a service and they will return an array of auto suggested keywords. I just need those keywords in my dropdown.

Any suggestion highly appreciated

**Comment by whitcik** [comment]
You should use Async Option
```
var getOptions = function(input, callback) {
    setTimeout(function() {
        callback(null, {
            options: [
                { value: 'one', label: 'One' },
                { value: 'two', label: 'Two' }
            ],
            // CAREFUL! Only set this to true when there are no more options,
            // or more specific queries will not be sent to the server.
            complete: true
        });
    }, 500);
};

<Select.Async
    name="form-field-name"
    loadOptions={getOptions}
/>
```

**Comment by samgavinio** [comment]
Is there a way to accomplish this by passing in the options as props from the parent component? I'm trying to use this with redux and I'd like to keep the all data coming from the redux store rather than doing a backend fetch within the `loadOptions` function.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
