### ISSUE TITLE
React-Select uses wrong name for global Classnames definition

### ISSUE THREAD

**Issue by nemothekid** [JedWatson/react-select#94]
Currently React-Select 'requires' ClassNames with

```
classes = (typeof window !== "undefined" ? window.classnames : typeof global !== "undefined" ? global.classnames : null),
```

However, https://github.com/JedWatson/classnames/blob/master/index.js exports itself as `classNames` (notice the case).

**Comment by JedWatson** [comment]
Thanks @nemothekid, that was a change in `classnames` I forgot to update here. Fixed now!
