### ISSUE TITLE
Themeable

### ISSUE THREAD

**Issue by infacq** [JedWatson/react-select#947]
Can I pass down a theme. That would be appropriate

**Comment by gojohnnygo** [comment]
If you're thinking theme like jQuery UI, then I believe the answer is no. Though, it looks like you can pass in some styles as props. 

```
wrapperStyle
menuContainerStyle
style
```

Fwiw, in my projects, I just override styles with CSS.

**Comment by infacq** [comment]
I'm thingking like this one 

https://github.com/markdalgleish/react-themeable

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
