### ISSUE TITLE
How to clear the focus of input when selected?

### ISSUE THREAD

**Issue by qmiao128** [JedWatson/react-select#951]
I tried the autoBlur option, but it didnot work.

**Comment by peterholmberg** [comment]
Can't get it to work either, is this a known issue?

**Comment by c-h-** [comment]
Also doesn't work for me

**Comment by tproenca** [comment]
Same here

**Comment by thiagocoelho** [comment]
Could you guys post some code sample here or explain using more details? 

I'm using autoBlur and it's working fine here.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
