### ISSUE TITLE
multi select onChange arguments uses are not as documented

### ISSUE THREAD

**Issue by damienleroux** [JedWatson/react-select#953]
Hello!

In the documentation, it is written that the multi select `onChange` callback as always a string as first parameter and an array as second parameter. I tried it and the first parameter is an array. There is no second parameter:

> The onChange event provides an array of the selected options as the second argument
The first argument to onChange is always a string, regardless of whether the values of the selected options are numbers or strings

I understand [from the code](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L488) that there is only the field value ( a string or an array) that can be passed to the callback.

Is the documentation not up to date or do I miss something?

Please correct me if I'm wrong :)

**Comment by bvaughn** [comment]
You're correct. Looks like a docs bug.

**Comment by bvaughn** [comment]
Thanks for pointing out this discrepancy. I've updated the docs to reflect reality.
