### ISSUE TITLE
libraries on cdn

### ISSUE THREAD

**Issue by anshulsahni** [JedWatson/react-select#955]
Please also make these libraries available on a CDN so that non npm users can also use it without any problem

**Comment by bvaughn** [comment]
All NPM packages are available on npmcdn for non-NPM users. This one is available [here](https://npmcdn.com/react-select@1.0.0-beta13), for example. You can also use [this link](https://npmcdn.com/react-select) to automatically grab the latest version.

If you'd prefer to see it hosted somewhere else (eg cdnjs.com) you can file a request [here](https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20react-select%20&body=**Library%20name%3A**%20%0A**Git%20repository%20url%3A**%0A**npm%20package%20url(optional)%3A**%20%0A**License(s)%3A**%0A**Official%20homepage%3A**%0A**Wanna%20say%20something?%20Leave%20message%20here%3A**%0A%0A=====================%0ANotes%20from%20cdnjs%20maintainer%3A%0APlease%20read%20the%20README.md%20and%20CONTRIBUTING.md%20document%20first.%0A%0AYou%20are%20welcome%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20then%20just%20opening%20a%20request%20issue%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!) on their repository or even submit a PR for it yourself ([here is an example](https://github.com/cdnjs/cdnjs/pull/7751)).

**Comment by bvaughn** [comment]
Closing this issue since it doesn't require any action from react-select.

I may submit a PR to cdnjs at some point myself if you don't beat me to it.
