### ISSUE TITLE
Submit custom attributes (inputProps) also to the event handler

### ISSUE THREAD

**Issue by pamuche** [JedWatson/react-select#956]
Is there some way to transfer custom attributes to the event handler?
Maybe as a second parameter? 

`
<Select
  ...
  onChange={ this.onChangeSelect(`**selectedOption**`, customArgument) }
  ...  
/>
`
But therefore I need some expression for **selectedOption** to not lose it when the event is called.

Maybe it could be the normal behavior to submit the content of `inputProps` as second argument to the event handler.

**Comment by gojohnnygo** [comment]
Without testing myself, I think something like this _should_ help you. 

`<Select ... onChange={ this.onChangeSelect.bind(this, customArgument) } ... />`

```
onChange(customArgument, selectedOption) {
  // customArgument comes first
}
```

**Comment by bvaughn** [comment]
This feature doesn't require any direct support from react-select. Just provide an adapter function that passes through react-select's selected option as well as whatever custom arguments you want your function to have. eg

```js
// Assumes "customArgument" is defined somewhere in scope...
<Select
  {...props}
  onChange={(newValue) => this.onChangeSelect(newValue, customArgument) }
/>
```

**Comment by bvaughn** [comment]
I'm going to go ahead and close this out since there's a working solution already available. Cheers! :)

**Comment by pamuche** [comment]
Yeah, both of your suggestions worked. Maybe the second solution of @bvaughn is little bit more readable because of the funny parameter swap in the first example of @gojohnnygo.
