### ISSUE TITLE
Clear value/clear Form to fire action 

### ISSUE THREAD

**Issue by m4cn4ir** [JedWatson/react-select#958]
Hello,

first things first: thanks for this great package.
I have a multiselect field. Every value has an additional attribute: isVisible which is by default false. If you hit a value its isVisible becomes true. If the value gets unselected the isVisible attribute should be set to false again. There are 2 ways to unselect:

- "the global clear" that clears every value if multi={true}. This works great with onClose={this.handleSelectClose.bind(this)}. However this also gets fired if the form was focused and I click outside the form with the mouse. Is there a way to prevent this? I found this in the todos: "handle _ closeMenuIfClickedOutside". Is there a quick workaround or any news on this todo?

- "the value specific clear": the "x" next to each value. Is there a function that fires only by clicking the "x"?

My intentions: I want to have multiple multiselect fields. Lets say the first contains car companys and the second its cars. If I click Bmw &Audi on the first, the second field should only show its corresponding cars. Hence the attribute isVisible. As mentioned, the problem is not setting the attribute but resetting it again. Besides the 2 options above, do you have any other possible solution?
Thanks in advance

**Comment by bvaughn** [comment]
It sounds like you're asking about how to structure your application's state to support cascading menus. This isn't really a question specific to react-select if I'm understanding you correctly. Here's a rough outline of how you could accomplish this. (I'm assuming some stuff about the structure of your data- since you didn't provide any sample data- but it's probably pretty easy to do the mapping.) :)

```js
// I'm assuming you have 2 collections here: manufacturers and makes.
// Makes belong to manufacturers.
// Selecting a manufacturer in your first menu causes its makes to be visible in the second.
// This information should live in your Flux/Redux store; I'm showing it inline for simplicity.
const manufacturers = [
  { name: "Audi", ... },
  { name: "Bmw", ... },
  ...
]
const makes = [
  { name: "s4", manufacturer: "Audi", ... },
  { name: "z4", manufacturer: "Bmw", ... }
]

function onManufacturerChange (newSelection, selectedManufacturers) {
  // This function should update your store/state and trigger a re-render.
  // The newly-updated :selectedManufacturers will be used to filter the collection of makes
}

// This filtering should be done by a memoized selector (eg 'reselect'); I'm showing it inline here for simplicity.
// The array of makes you pass to react-select is filtered to only include the selected manufacturers.
const filteredMakes = makes.filter(
  (make) => selectedManufacturers. includes(make.manufacturer)
)

// Partial rendering logic:
<Select
  onChange={onManufacturerChange}
  options={manufacturers}
  {...props}
/>
<Select
  options={filteredMakes}
  {...props}
/>
```

**Comment by bvaughn** [comment]
Closing this for now (to keep things tidy) as I assume the question has been answered sufficiently. Let me know if not and I can try to clarify. :)

**Comment by m4cn4ir** [comment]
test

**Comment by m4cn4ir** [comment]
Hi bvaughn,

thank you very much. Your approach helped me a lot and made it much easier for me. I managed to implement the 2 menus: "manufacturers" and "makes". If no values are clicked, both menus show all their attributes. If I click bmw in manufacturers it only shows the corresponding cars in the makes menu. 
However my initial problem still exists: I can not unselect the bmw selection. In order to get the makes menu "clean" of the selected values in manufacturers I need to refresh the page. I could implement  onClose for manufacturers: to reset the makes options to original but onClose fires on clicking the "x" aswell on just leaving the menu with escape or **mouseclick outside the menu while open**. Another solution would be to implement an extra button "clear selection" under each menu and set clearableValue and clearable to false. But this would be my last resort.
Therefore I need a function that **only** fires by clicking the "x" in the menu. Either the "x" to clear all values or for each value. 

Here is my code so far (Kunde stands for Manufacturer, Auto for makes)

`import React from 'react';
import TrackerReact from 'meteor/ultimatejs:tracker-react';
import {Button, Row, Col} from 'react-bootstrap';
import '/node_modules/react-select/dist/react-select.css';
import MultiSelect from 'react-select';

export default class KundeSelect extends TrackerReact(React.Component) {

    constructor() {
        super();
        this.state = {
            initialValueKunde: "",
            initialValueAuto: "",
            optionsKunde: [],
            optionsAuto: [],
            filteredAutos: []
        };
    }

    componentWillUnmount() {
    }

    componentDidMount() {
        setTimeout(() => {
            this.props.kunde.map((kunde, i) => {       //just assume [ {value:"1", label:"Audi"}, ..]
                this.state.optionsKunde.push({
                    value: i,
                    name: kunde.name,
                    label: kunde.name
                });
            });

            const optionsAutoData = [
                {value: "1", name: "a3(audi)", manufacturer: "Audi"},
                {value: "2", name: "a4(audi)", manufacturer: "Audi"},
                {value: "3", name: "a5(audi)", manufacturer: "Audi"},

                {value: "4", name: "x3(bmw)", manufacturer: "Bmw"},
                {value: "5", name: "x4(bmw)", manufacturer: "Bmw"},
                {value: "6", name: "z4(bmw)", manufacturer: "Bmw"}
            ];

            this.setState({optionsAuto: optionsAutoData});
            this.setState({filteredAutos: this.state.optionsAuto});
        }, 200);
    }

    handleKundeChange(value) {

        var varArray1 = [];
        var varArray2 = [];
        this.setState({initialValueKunde: value});

        if (value) {
            value.map((val) => {

                varArray1 = this.state.optionsAuto.filter(
                    (make) => (make.manufacturer.toLowerCase()).includes(val.name.toLowerCase())
                );

                varArray2.push.apply( varArray2, varArray1 );

                this.setState({
                    filteredAutos: varArray2
                })
            });
        }
    }

    handleAutoChange(value) {
        this.setState({initialValueAuto: value});
    }

    handleKundeClose() {

        console.log("close");                                       //here is the problem. This will be called by either clicking "x"
        //this.setState({filteredAutos: this.state.optionsAuto});   //or just leaving the menu with mouseclick
    }

    render() {
        return (
            <div>
                <Row>
                    <Col xsOffset={0} md={3} sm={3} xs={3}>
                        <div className="section">
                            <MultiSelect
                                name="form-field-name"
                                placeholder="Kunde"
                                options={this.state.optionsKunde}
                                value={this.state.initialValueKunde}
                                onChange={this.handleKundeChange.bind(this)}
                                multi={true}
                                clearable={true}
                                onClose={this.handleKundeClose.bind(this)}
                            />
                        </div>
                    </Col>

                    <Col xsOffset={0} md={3} sm={3} xs={3}>
                        <div className="section">
                            <MultiSelect
                                name="form-field-name"
                                placeholder="Auto"
                                options={this.state.filteredAutos}
                                value={this.state.initialValueAuto}
                                onChange={this.handleAutoChange.bind(this)}
                                //onClose={this.handleSelectClose.bind(this)}
                                multi={true}
                                clearable={true}
                                labelKey="name"
                            />
                        </div>
                    </Col>
                </Row>
            </div>
        )
    }
}`

**Comment by bvaughn** [comment]
I may be misunderstanding something still- but manufacturers should be _ unselected_ the same way they're _selected_- via the `handleAutoChange(value)` method. Unless I'm misunderstanding your intentions- closing the manufacturers select list should not actually unselect anything- (that would be confusing UX)- so you shouldn't be using the `handleKundeClose` for unselect.

**Comment by m4cn4ir** [comment]
> but manufacturers should be _ unselected_ the same way they're selected- via the handleAutoChange(value) method

There is a German proverb "Den Wald vor lauter Bäumen nicht sehen" (I couldn´t see the woods for the trees)
The solution was very simple:

```
 if (!value) {
            this.setState({filteredAutos: this.state.optionsAuto});
        }
```
Thank you very much for your help!! :)

**Comment by bvaughn** [comment]
Haha, no worries! Glad you got it working. :)
