### ISSUE TITLE
Options disappear when reporting selection change to parent

### ISSUE THREAD

**Issue by vith** [JedWatson/react-select#96]
When I create a wrapper component around react-select and pass data up to the parent via an onChange handler, the options dropdown becomes blank as soon as I select an option. Maybe I'm doing something wrong?

Here's a demonstration of the problem: http://jsbin.com/tulujuroxo/1/edit?js,output (edit: figured out how to use JSX on jsbin)

There's something weird going on with it in jsbin though: the setTimeout 1 second delay is nearly instant. So just in case, here it is in project form as well: https://github.com/vith/react-select-problem

**Comment by vith** [comment]
Adding
```js
    shouldComponentUpdate: function(nextProps, nextState) {
        return false;
    }
```
to SelectWrapper fixes it, but that seems sketchy. Is this related to #70?

**Comment by janmyler** [comment]
Oh, I see I'm having the exact same problem in #133. Disabling updates of the owner component shouldn't really be the solution as you cannot implement any other things such as validation messages or other custom feedback.

**Comment by dcousens** [comment]
Still the case?
