### ISSUE TITLE
AllowCreate AND newOptionCreator not working

### ISSUE THREAD

**Issue by GJ2511** [JedWatson/react-select#960]
Hi this my code 

```
 <Select.Async
 id='bonus_code'
 name='bonus_code'
 multi={true}
 allowCreate={true}
 newOptionCreator={this.newOption.bind(this)}
 value={this.state.bonusCode}
 onChange = {this.onChangeBonusCode.bind(this)}
 loadOptions={getOptions}
/>
```

**newOptionCreator** is not working

Any ideas????

**Comment by arman-mukatov** [comment]
This is functionality hasn't yet been implemented in the 1.0 rewrite. Use the latest 0.9.x version instead.

**Comment by jmeas** [comment]
This comment may help: https://github.com/JedWatson/react-select/issues/586#issuecomment-177047129

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!

Look for an updated RC with this functionality soon. 😎
