### ISSUE TITLE
`alwaysOpen` Prop

### ISSUE THREAD

**Issue by JKillian** [JedWatson/react-select#962]
There are certain scenarios when I would find it useful to force the menu to always stay open. Currently it can be opened automatically with `openOnFocus`, but it can still be closed.

Are there any plans for a prop like this? If not, would a PR be accepted or not? Apologies if this is a duplicate of any issue, couldn't find any identical issues while searching through them.

**Comment by adidahiya** [comment]
looks like this might be resolved by https://github.com/JedWatson/react-select/pull/817

**Comment by khankuan** [comment]
Had the exact same problem. Reference: #1015

**Comment by JedWatson** [comment]
I've put a more comprehensive write-up on this over at #1989 - let's please discuss there
