### ISSUE TITLE
autoload does not seem to do what it should do

### ISSUE THREAD

**Issue by philmetzger** [JedWatson/react-select#965]
I have the following setup:

```
<Select.Async
                        multi={true}
                        value={this.state.value}
                        onChange={this.onChange}
                        valueKey="key"
                        labelKey="value"
                        loadOptions={getOptions}
                        allowCreate={true}
                        autoload={false}
                    />
```

However on load I still get the loading symbol before any input it provided.
![screenshot from 2016-05-17 16 19 17](https://cloud.githubusercontent.com/assets/4325631/15325575/2a4b90c8-1c4b-11e6-941f-c3355a75be38.png)

Is there something I am doing wrong or is this an issue?

**Comment by dmk23** [comment]
I'm having the same problem. Cannot disable autoload.

This looks like a bug. Please fix!

**Comment by philmetzger** [comment]
Found this related solution: https://github.com/JedWatson/react-select/issues/617

**Comment by dmk23** [comment]
Reviewed that solution and find it lacking. Left my comment on that issue...

**Comment by moodysalem** [comment]
Also encountered this issue and would like autoload back

**Comment by anneFly** [comment]
I upgraded to version `1.0.0-rc.2` and I don't encounter this issue anymore. `autoload` seems to work fine now.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
