### ISSUE TITLE
compiled output in lib/ not ES6 compatible

### ISSUE THREAD

**Issue by cwalv** [JedWatson/react-select#966]
The `main` module [lib/Select.js](https://github.com/JedWatson/react-select/blob/5df5fa262853a7656fdbc958cfba13875bbdb410/package.json#L5) is not compatible with ES6 semantics due to a babel bug.  Specifically, the [last line](https://github.com/JedWatson/react-select/blob/aaddc94a6c91daab95de8457aacf302b07a4f239/lib/Select.js#L950) undoes the previous line, which is what we would expect from `export default Select`:

```
exports['default'] = Select;
module.exports = exports['default'];  // doh!
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
