### ISSUE TITLE
Text in input not selectable

### ISSUE THREAD

**Issue by Reggino** [JedWatson/react-select#967]
Thanks for this!

When typing text in the text-input to search for an option, it's not possible to select the search-text using the mouse. One has to remove the input using the backspace key, which is a bit inconvenient. 

Related to #916

**Comment by daletune** [comment]
Any plans for this by maintainers?

**Comment by MarkLeMerise** [comment]
Not straightforward, but you can use `Ctrl + A` to select all and then use the arrows to navigate within the word, so at least it's a workaround until a fix.

**Comment by fleetofthemalden** [comment]
@JedWatson Any plans to support this?

Without it we need to choose another implementation for our org.

**Comment by JedWatson** [comment]
This has been fixed

**Comment by IamKritika** [comment]
@JedWatson this is not working. I was referring to the examples in the documentation. Can you please look into this?

**Comment by pk936** [comment]
I am facing the same issue.

**Comment by vertic4l** [comment]
Nice maintenance on this one!
