### ISSUE TITLE
[bug?]multi-select on numeric value on react-select website not working

### ISSUE THREAD

**Issue by hyde777** [JedWatson/react-select#972]
Hello, it's juste a little message to notice you that the multi-select on numeric value in the website 
https://jedwatson.github.io/react-select/ is not working.

**Comment by bogdan-r** [comment]
Confirm, is not working.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
