### ISSUE TITLE
Suggestion: You could tweak this a bit and make it look and behave like a search box

### ISSUE THREAD

**Issue by ionelh** [JedWatson/react-select#975]
With a few tweaks, this could look and behave like a search box with suggestions and tagging, instead of a drop-down list. I almost did that with the current API, the only thing stopping me was the stopPropagation() on enter key press. You could stop the propagation based on pref at least, so that I can listen to enter press from a wrapper element if I want to. The arrow down and click to expand could be also based on props. For example, expand only if I start typing. These can be achieved with the current API too though, but it feels a bit like a hack.

**Comment by JMoxey** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
