### ISSUE TITLE
Error if `onChange` causes the component to unmount.

### ISSUE THREAD

**Issue by Xesued** [JedWatson/react-select#978]
If an `onChange` callback cause the component to unmount, the `Select`'s `selectValue` tries to setState after, causing a React Error.

**Comment by Xesued** [comment]
I believe that swapping the `this.setState(...)` and `this.setValue(value)`  (https://github.com/JedWatson/react-select/blob/master/src/Select.js#L499)  should solve the issue.

**Comment by bvaughn** [comment]
@Xesued,

Can you provide a reproduction test-case for this problem? I'm having some difficulty reproducing it the error you're describing with 1.0 beta 13 and React 15.

**Comment by Xesued** [comment]
https://plnkr.co/edit/nXHsCdRyUfxa8OR48bmd?p=info

If you change the results, you will notice an error thrown in the console.
