### ISSUE TITLE
Input error on Async.Select with loadOptions

### ISSUE THREAD

**Issue by inosphe** [JedWatson/react-select#980]
input value is assigned like '[object promise]'
This is fixed by 

In 'Async.js

`return thenPromise(this.props.loadOptions(input, responseHandler), responseHandler);`

to

`thenPromise(this.props.loadOptions(input, responseHandler), responseHandler);
return input;`

Thanks. best regards.

**Comment by sslotsky** [comment]
Change works, but breaks a couple of tests. Do you have plans to look into this?

**Comment by inosphe** [comment]
Sure, I will look into this.

**Comment by lobsteropteryx** [comment]
I believe I have a fix for this, with passing tests.  Shall I submit a PR?

**Comment by sslotsky** [comment]
I'd definitely submit it @lobsteropteryx , if yours works with passing tests I will close mine.

**Comment by JedWatson** [comment]
Fixed by #992
