### ISSUE TITLE
Document need to be updated to require style

### ISSUE THREAD

**Issue by rahulchavan30** [JedWatson/react-select#983]
Document needs to be updated to require "require('react-select/dist/react-select.css')", 
without using this its not possible and component rendered is not what is expected . 

i included this and everything worked perfectly fine thanks for all the work you have done on this component

**Comment by jkirkpatrick** [comment]
For ES6+:
`import 'react-select/dist/react-select.css'; `

**Comment by bvaughn** [comment]
FWIW there are 2 ways for you to include react-select styles in your project.

#### Use a CDN

In your index.html file load the styles directly from NPM CDN:
```html
<link rel="stylesheet" href="https://npmcdn.com/react-select@1.0.0-beta13/dist/react-select.css">
```

#### Use a bundler

(Assuming you've `npm install`ed react-select...) Somewhere in your entry file either _require_ or _include_ the styles:
```js
// either...
require('react-select/dist/react-select.css');
// or...
import 'react-select/dist/react-select.css';
```

I'll update the documentation to reflect this.

**Comment by bvaughn** [comment]
I've updated the [installation instructions](https://github.com/JedWatson/react-select#installation) in the main README to show how to import styles. Thanks for the suggestion!
