### ISSUE TITLE
Search is weird (e.g. "u" brings up "Hungary")

### ISSUE THREAD

**Issue by callumlocke** [JedWatson/react-select#986]
It's a very weird default, to search in the middle of words. And I can't find any way to change this behaviour.

**Comment by hedaro** [comment]
From the README:

> matchPos: "start" or "any": whether to match the text entered at the start or any position in the option value

Just pass the prop `matchPos="start"` and that should do what you want.

**Comment by callumlocke** [comment]
thank you! that solves my problem, I had missed that option.

but even with `matchPos="any"` is it really supposed to search inside words? I would understand if it searched from the start of _any_ word (e.g. typing <kbd>b</kbd> could bring up `Great Britain`), but it seems a really weird option to want to search for any letter _inside_ any word.

**Comment by hedaro** [comment]
That is because each value/label are whole strings, so "start" matches the beginning of the string and "any" searches anywhere inside the string.

**Comment by callumlocke** [comment]
Thanks, I get how to configure it now. But I still think react-router should change its default setting for this. In my opinion `matchPos="start"` would be a saner default
