### ISSUE TITLE
Select immediately collapses on Samsumg S3 Android 4.3 Internet browser

### ISSUE THREAD

**Issue by leanne-tite-jg** [JedWatson/react-select#991]
We implemented react-select and on a Samsung S3 running Android 4.3 on the bundle Android browser  when you click on the select it expands and then immediately collapses.

We are implementing with no custom styling / code, and even with the change handler removed it does the same. This is how we implement:

``` jsx
import Select from 'react-select';

<Select
    placeholder={placeholder}
    searchable={false}
    id={id}
    value={value}
    options={options}
    onChange={handleChange}
    clearable={false} />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
