### ISSUE TITLE
Lastpass adds a dropdown to react-select since adding aria

### ISSUE THREAD

**Issue by bruderstein** [JedWatson/react-select#993]
With the aria attributes added, lastpass adds a dropdown highlight box in a single select react-select control. 

I'm looking into it, to disable it.

**Comment by bruderstein** [comment]
The easy option seems to be to make the name of the input field contain `search`.

PR on the way for a suggested addition that we default the name of the input box to the `_instancePrefix + '-search-lastpass-disable'`.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
