### ISSUE TITLE
Regarding size of Select

### ISSUE THREAD

**Issue by Dauth** [JedWatson/react-select#994]
Did a clean install of react-select along with its dependencies 
May i know how do i rectify this whereby the size is out of proportion?
Note i have clicked on the input field.

![image](https://cloud.githubusercontent.com/assets/10680613/15634243/8a6223d2-25f1-11e6-9614-e40eb1e849a3.png)

`<Select  placeholder="Select A Choice"  options= {options}  onChange={this.printChange} />`

**Comment by bsideup** [comment]
I'm having exactly the same issue with auto sizing

**Comment by adamtay82** [comment]
See this: https://github.com/JedWatson/react-select/issues/983

You need to include the style sheet.

**Comment by bsideup** [comment]
Even after I include the stylesheet select doesn't autosize

**Comment by bvaughn** [comment]
FWIW there are 2 ways for you to include react-select styles in your project.

#### Use a CDN

In your index.html file load the styles directly from NPM CDN:
```html
<link rel="stylesheet" href="https://npmcdn.com/react-select@1.0.0-beta13/dist/react-select.css">
```

#### Use a bundler

(Assuming you've `npm install`ed react-select...) Somewhere in your entry file either _require_ or _include_ the styles:
```js
// either...
require('react-select/dist/react-select.css');
// or...
import 'react-select/dist/react-select.css';
```

If you've done this, the sizing should work. Are you sure you're including the stylesheet correctly? (Can you verify that the `.Select-control` styles exists, for instance?)

**Comment by bvaughn** [comment]
@Dauth, @bsideup Could one of you provide a Plunker or JSFiddle demonstrating the styling problem you're reporting?

Here is a Plunker you can fork that's setup to load the necessary JS and CSS: https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
