### ISSUE TITLE
Using array as value

### ISSUE THREAD

**Issue by diessica** [JedWatson/react-select#997]
It does work:

``` jsx
<Select
  value={1}
  options={[
    { value: [1, 2], label: 'Both' },
    { value: 1, label: 'One' },
    { value: 2, label: 'Two' }
  ]}
/>
```

But passing "Both" (which the `value` key is an **array**) in`value` prop **does not mark** the right option as selected:

``` jsx
<Select
  value={[1, 2]}
  options={[
    { value: [1, 2], label: 'Both' },
    { value: 1, label: 'One' },
    { value: 2, label: 'Two' }
  ]}
/>
```

It visually selects `value={1}` instead. `[2, 1]` selects 2 (`value={2}`).

`onChange`, on the other hand, works as expected.

**Comment by filipemerker** [comment]
Had EXACTLY the same problem here. Any solution?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
