### ISSUE TITLE
How come requiring from "dist/react-select" works but ...

### ISSUE THREAD

**Issue by bytewiz** [JedWatson/react-select#998]
if I copy the code and require my own file.css with the styles it is not loaded?

**Comment by bvaughn** [comment]
Hey @bytewiz,

Afraid there isn't enough information on this issue for us to provide any help. Please provide example code- best if you can link to a Plunker or JsFiddle demonstrating your setup.

I'll take a shot in the dark and suggest that there are 2 ways for you to include react-select styles in your project.

#### Use a CDN

```html
<link rel="stylesheet" href="https://npmcdn.com/react-select@1.0.0-beta13/dist/react-select.css">
```

#### Use a bundler
```js
// either...
require('react-select/dist/react-select.css');
// or...
import 'react-select/dist/react-select.css';
```
